### ISSUE TITLE
[css-contain-3][css-anchor-position-1] Containment makes it difficult to use anchor positioning with container queries

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#10040]
Currently, container queries rely on several types of containment: `size`, `layout`, and `style`. This already causes some confusion with authors, when fixed-position elements nested in a container are now _fixed to the container_ rather than the viewport (thanks to layout containment).

That issue will become much more noticeable when container queries interact with anchor positioning. As currently defined, `layout` and `style` containment will make it impossible for elements to anchor across different containers. I think that will mean:

- Positioned elements outside a container cannot see anchors inside a container, since `style` containment scopes the anchor name.
- Positioned elements inside a container cannot use an anchor outside the container, since `layout` containment doesn't allow reference to external layout? (I'm less clear on the interaction here)

While these decisions all make sense in terms of 'the promise' that each containment makes, it will cause a lot of problems for users who want to use both container queries and anchor positioning. Authors should be able to use these features without one constantly interfering with the other.

Since container queries are somewhat abstracted away from containment (we set a `container-type`, and browsers apply containment _as-needed_), I think the only path forward here is defining more subtle and targeted containment rules for container queries. Are there ways that we can relax _how much_ layout and style containment is required to make container size queries work?

(This came out of discussion on #9349)

/cc @tabatkins

**Comment by lilles** [comment]
> Currently, container queries rely on several types of containment: `size`, `layout`, and `style`. This already causes some confusion with authors, when fixed-position elements nested in a container are now _fixed to the container_ rather than the viewport (thanks to layout containment).
> 
> That issue will become much more noticeable when container queries interact with anchor positioning. As currently defined, `layout` and `style` containment will make it impossible for elements to anchor across different containers. I think that will mean:
> 
> * Positioned elements outside a container cannot see anchors inside a container, since `style` containment scopes the anchor name.

Right, it can only see the anchor-name of the container itself given the current spec for anchor-name:

"Anchor names are style-contained, [scoped to a sub-tree](https://drafts.csswg.org/css-contain-2/#property-scoped-to-a-sub-tree)."

> * Positioned elements inside a container cannot use an anchor outside the container, since `layout` containment doesn't allow reference to external layout? (I'm less clear on the interaction here)

Even style containment does that here:

https://drafts.csswg.org/css-contain-2/#property-scoped-to-a-sub-tree

> While these decisions all make sense in terms of 'the promise' that each containment makes, it will cause a lot of problems for users who want to use both container queries and anchor positioning. Authors should be able to use these features without one constantly interfering with the other.
> 
> Since container queries are somewhat abstracted away from containment (we set a `container-type`, and browsers apply containment _as-needed_), I think the only path forward here is defining more subtle and targeted containment rules for container queries. Are there ways that we can relax _how much_ layout and style containment is required to make container size queries work?

The reason why we added style containment for size containers was that generated content for counters and quotes inside the container could affect layout outside the container through intrinsic sizing, which again could affect the size of the size container, which would cause circularities in the layout when counter/quotes styles depended on size query evaluation.

Counters and quotes need to be style contained for size containers.

**Comment by vmpstr** [comment]
There is a similar desire for timeline names not being contained by style containment: https://github.com/w3c/csswg-drafts/issues/8915#issuecomment-1883461265

The difference is that being able to discover an anchor name likely has more implications in needing more layout (is that true?). In any case, it seems that maybe having style contain names vs contain counters are two separate needs that could be addressed by two different values.

FWIW, for content-visibility, we do want to contain names as well as counters, so that part is still necessary

**Comment by lilles** [comment]
> @lilles Right, so the questions are:
> 
> * Would it be possible to have `container-type: inline-size` apply those containments (counters and quotes) without applying other aspects of `style` containment?

Sure. I don't know if it makes sense to introduce separate contain keywords or just do it implicity through container-type.

> * And, if so, can we do something similar to apply a subset of `layout` containment as well? Something that would keep container queries stable, but not interfere with anchor positioning?

I didn't immediately  spot any items that could be lifted https://drafts.csswg.org/css-contain-2/#containment-layout but @bfgeek should have a look, but this was specifically about anchor-name containment that's not yet in the list, right?

**Comment by mirisuzanne** [comment]
> this was specifically about anchor-name containment that's not yet in the list, right?

My instinct would be to start with the implicit change to `container-type` behavior, and only add a keyword if we find it would be useful later. But we could discuss. 

> I don't know if it makes sense to introduce separate contain keywords or just do it implicitly through container-type.

Yeah… or anything else related to positioning that might interfere with anchorPos being used across container boundaries. I'm not sure that I know exactly what might impact that.

**Comment by chrishtr** [comment]
I agree that it's important to support anchors across container query boundaries, and also across every other kind of layout boundary such as `content-visibility`, for onscreen content. In addition, I don't think there is a big performance problem with excluding `anchor-name` from `style` and `layout` containment, except as it relates to [skipped](https://drafts.csswg.org/css-contain-2/#skips-its-contents) `content-visibility:auto` subtrees.

So what I propose is the following:

* Exclude `anchor-name` from style and layout containment (reverting the resolution in #9349 last week)
* Specify that `anchor-name` cannot cross skipped `content-visibility: auto` subtree boundaries

Agenda+ with that proposed resolution.

**Comment by chrishtr** [comment]
> Agenda+ with that proposed resolution.

Small amendment via a third bullet:

* if the anchor is on-screen, then the anchored element is considered [relevant to the user](https://drafts.csswg.org/css-contain-2/#relevant-to-the-user).

**Comment by vmpstr** [comment]
For posterity, also reverts resolution in #9100

**Comment by vmpstr** [comment]
The second resolution isn't what I was thinking about initially. I think it's a good one, but there are a couple of cases:

1. Anchored element (`A`) and positioned element (`P`) are both relevant to the user, then
  a. `A`'s container with c-v auto is scrolled offscreen -- it should still remain relevant
  b. `P`'s container with c-v auto is scrolled offscreen -- it should still remain relevant
  c. Both `A`'s and `P`'s containers are scrolled off screen -- not sure if things should stay relevant?
2. `A` is not relevant to the user, so its `anchor-name` should not be discoverable
3. `P` is not relevant to the user -- I don't think it should become relevant, since then we'd need to know it's being positioned

I propose spending a few minutes thinking through all of the cases here, since I want to avoid to accidentally requiring rendering in an otherwise skipped subtree

**Comment by vmpstr** [comment]
After a bunch of discussions, I think it's fine if positioned elements are within c-v, because there's paint containment that would end up clipping it if if it's moved too far.

It also establishes a containing block, so I don't see a use case for where this anchoring would be expected to work well when the anchor is elsewhere.
