### ISSUE TITLE
[css-color][cssom] Serialization of specified <color> values

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1004]
CSSOM spec defines the way to serialize resolved `<color>` values (to rgb and rgba functions), but nothing defines how specified `<color>` values should be specified, and it seems the existing implementations are rather complicated.

It seems to me that all browsers agree on the following things:
* `#008000` -> `rgb(0, 128, 0)`
* `RGB(0, 128, 0)` -> `rgb(0, 128, 0)`
* `green` -> `green`
* `CURRENTcolor` -> `currentcolor` / `currentColor`

Some differences:
* `rgba(0, 128, 0, 1)` -> Edge: `rgba(0, 128, 0, 1)`, Gecko & Blink: `rgb(0, 128, 0)`
* `GrEeN` -> Edge & Blink: `green`, Gecko: `GrEeN`

I think for the last case, Gecko is inconsistent to itself, so it's probably wrong. I'm less sure about the first difference, though.

Anyway, there doesn't seem to be any speced serialization algorithm does this. It should probably be put somewhere.

**Comment by svgeesus** [comment]
This would be a new feature in CSS Color 3, so it has been addressed in CSS Color 4:
https://drafts.csswg.org/css-color-4/#resolving-color-values

**Comment by svgeesus** [comment]
The spec text, which has been there a while, reads:

> The computed and used value is the corresponding sRGB color paired with the specified alpha channel (defaulting to opaque if unspecified).

(Note that the original issue, as raised on CSS Color 3, is about that subset of the present `<color>` type having to do with sRGB colors, only.

@upsuper okay to close your original issue? Or does the quoted text not solve your issue?

**Comment by svgeesus** [comment]
Note that the spec [currently treats rgba as legacy](https://drafts.csswg.org/css-color-4/#rgb-functions) so the Gecko and Blink `rgba(0, 128, 0, 1)` as `rgb(0, 128, 0)` is correct (and the Edge behavior has presumably changed meanwhile to the Blink behavior).

I would also therefore expect `rgba(0, 128, 0, 0.5)` or `rgba(0, 128, 0, 50%)` to serialize as  `rgb(0, 128, 0 0.5)`, right? If so that needs to be stated explicitly.

**Comment by svgeesus** [comment]
>   RESOLVED: Serialize RGB and RGBA with commas
>   RESOLVED: if the color has non-1 alpha, use the rgba() function
>   RESOLVED: Add some text about specified values and color keywords in specified and computed are given in lowercase

These are all done now.

**Comment by svgeesus** [comment]
All dealt with, CSSWG resolutions implemented, see see [Serializing sRGB values](https://drafts.csswg.org/css-color-4/#serializing-sRGB-values)

@upsuper do these edits resolve all of your concerns?

**Comment by upsuper** [comment]
Yes, those sound good to me.

**Comment by tabatkins** [comment]
What type of value you're observing depends on how you're querying it. Those bullet points talk about the value stages, and different APIs retrieve values at different stages of the pipeline.

So, are you asking about `el.style.color`, `getComputedStyle(el).color`, or something else?

> so I have to assume it is a component of a resolved value, which seems to be the only path to get green as the output instead of rgb(0, 255, 0)

I'm confused what you mean by this. The only way you'll get a color keyword is if the author specified one and you're retrieving the specified value; the bullet points in your quote make that clear. So I'm not sure how you conclude that the API you're querying is returning a resolved value, as that is defined to be either a computed or used value, and computed or used colors won't serialize as those named colors.

**Comment by cdoublev** [comment]
> So, are you asking about `el.style.color`, `getComputedStyle(el).color`, or something else?

I'm asking about *serialize a CSS value*, which means `element.style.color` (`CSSStyleDeclaration.getPropertyValue()`), `element.style.cssText`, `CSSRule.cssText`, and more.

> So I'm not sure how you conclude that the API you're querying is returning a resolved value

I proceeded by elimination. 

**Specified value** (first gut)

```js
element.style.color = 'red'
console.log(element.style.color)
foo.style.color = 'hsl(0 0% 0%)'
console.log(element.style.color)
```

The first output is `red` in Chrome/Firefox/etc, but the second output is `rgb(0, 0, 0)`, which is not my *original, author specified color value*.

**Resolving sRGB values**

> While the function names and named colors are ASCII case-insensitive, the specified value does not preserve any mixed casing and is treated as being all lowercase.

[Me thinking] Ok, this may be a hint that it preserves my specified keyword.

> For example, the computed value of `hsl(38.824 100% 50%)` is `rgb(255, 165, 0)`

[Me thinking] Ok, it fits.

**Computed value**

> The serialized form of the following sRGB values: hex colors rgb() and rgba() values hsl() and hsla() values hwb() values named colors is derived from the computed value and thus, uses either the rgb() or rgba() form.

[Me thinking] Does not fit because my specified keyword should not be transformed to `rgb()`.

[Me thinking] Ok, my input is a component of a resolved value. My gut was wrong.

**Comment by tabatkins** [comment]
> I'm asking about serialize a CSS value, which means element.style.color (CSSStyleDeclaration.getPropertyValue()), element.style.cssText, CSSRule.cssText, and more.

You're not getting the result of that directly, tho, you're getting the result of some API which invokes that algorithm, and those APIs feed values into that algorithm at various stages of the value pipeline. That's why I'm asking.

It looks like you're invoking the serialization of `el.style.color`, which returns specified values.

(Note that your logic that it must be a resolved value, since `hsl()` is canonicalized to `rgb()`, equally tells you it must be a serialized value, since `green` is preserved as `green`.)

**Comment by cdoublev** [comment]
So the current definition is clear and to answer myself on this:

> I can not even see when *the color was explicitly specified by the author* does not apply.

It can be specified by the user or the user agent.

Chrome/Firefox (and maybe other browsers) currently serialize `<color>` as a component of a specified value with the computed value, which is the resolved value (and used value) for the `color` property, when it is queried from `el.style.color`, instead of with *the original, author specified color value*.

So you can re-close this issue and I can report the problem on the issue tracker of these browsers, right?

**Comment by tabatkins** [comment]
I'm sorry, but I think you're confused about terminology and that's causing a lot of confusion overall. (I'm having trouble following your arguments, at least.)

Could you restate your question or problem? At this point I'm not sure what you're actually asking about.

**Comment by cdoublev** [comment]
You are certainly right so I let's focus on serialization as a component of a specified value.

```js
const authorSpecifiedColor = 'hsl(0, 100%, 50%)'
element.style.color = authorSpecifiedColor
const serialization = element.style.color
console.log(serialization)
```

The output in Chrome/Firefox is `rgb(255, 0, 0)` but it should be `hsl(0, 100%, 50%)`.

[**Specification**](https://drafts.csswg.org/cssom-1/#serializing-css-values):

  1. *If `<color>` is a component of a specified value, then return the color as follows*: **yes**
  2. *If the color was explicitly specified by the author*: **yes**
  3. *then return the original, author specified color value*: `hsl(0, 100%, 50%)`

**Comment by tabatkins** [comment]
Yes, that is a serialization of a specified value, and the value was explicitly set, so per spec it should be serialized as written (modulo minor reformatting, possibly). These sorts of serialization behaviors have long been inconsistent across browsers, but ideally this should be treated as a browser bug.

**Comment by svgeesus** [comment]
@cdoublev do the recent comments from @tabatkins satisfactorily answer your questions?

**Comment by cdoublev** [comment]
Yes, satisfied. Thanks.
