### ISSUE TITLE
[css-ruby-1] Obsolete HTML elements in examples

### ISSUE THREAD

**Issue by xgebi** [w3c/csswg-drafts#10065]
I have a question about obsolete HTML tags in the specification. Ruby annotation has `rb` and `rtc` which in HTML are marked as [obsolete](https://html.spec.whatwg.org/multipage/obsolete.html#rtc). Is there a plan to update current spec or will that happen in Level 2?

These two are in [the specification](https://drafts.csswg.org/css-ruby/). `rtc` is in about 30 places and `rb` is referenced in about 60.

**Comment by frivoal** [comment]
You are right that these elements are currently obsolete in the HTML specification.

However, this will hopefully change. The main reason that they are not in the HTML spec is not because they are thought to be a bad idea, but rather than they are currently lacking two browser implementations. Firefox does implement them, and Amazon kindle does implement rtc (but does not count as a browser, for the purpose of the WHATWG, who maintains the HTML specification).

(As an aside, not that all browsers do support parsing rb and rtc, including the handling of optional end tags, even if they don't all do anything useful with these tags at the moment).

An [agreement has been reached between W3C and the WHATWG](https://www.w3.org/2022/02/ruby-agreement) that W3C will work on an extension specification for ruby, which will cover those. It has not yet been published, but an early, unofficial draft can be found at https://w3c.github.io/html-ruby/. One of its appendices goes into some detail about why restoring these elements is useful: https://w3c.github.io/html-ruby/#diff-html

The plan is therefore not to remove the use of these two elements from CSS-RUBY-1, but rather to restore them as valid markup.
