### ISSUE TITLE
[css-view-transitions] 'type' argument that takes an array of types is very weird naming

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10070]
See https://www.w3.org/2024/03/13-css-minutes.html#x269

It's very weird to have a singular noun representing an array of such nouns.

**Comment by vmpstr** [comment]
FWIW this comes from https://github.com/w3c/csswg-drafts/commit/d6c50e9e8fff5636fde60438370e69dbb62d9475 I can't quite find the exact spot where we discussed this. The origin of a singular word here is that in CSS a list of idents is typically singular because of syntax (e.g. the only thing I can think of right now is `animation-name`), so we just matched javascript to that CSS name.

Should we have CSS `type: <custom-ident>+` and JS `sequence<DOMString>? types`? to be consistent with each domain

**Comment by noamr** [comment]
The discussion about this was in TPAC 2023.
One solution to this is to not have a special `startViewTransition` signature at all, and instead:
```js
const vt = document.startViewTransition(updateCallback);
vt.typeList.add(...theTypesIWantedToAdd);
```

**Comment by bramus** [comment]
> (e.g. the only thing I can think of right now is `animation-name`)

A counterexample is `font-family` which you set to a list of font names. The property could as well be named `font-name` but instead it use the `family` suffix.

Rewinding a little bit back, I raised this concern because there were a bunch of different names for it, which seems a bit weird: `types`, `type`, and `typeList` (the `types` one turning out to be a typo in the spec).

I could see Noam’s suggestion above work, but then that would not solve the descriptor in the `@view-transition` rule, which still is `type` _(at this moment)_.

Moving forward, I think the most consistent way to talk about this would be to use the term _“Type List”_ across the board. In CSS that would become `type-list` (in the `@view-transition` rule) and in JS `typeList` (when passing it into `startViewTransition()`, when reading it from a `ViewTransition` object, and when reading it from `CSSViewTransitionRule`).

So, proposal: Use the term “Type List” across the board. That is, `type-list` in a CSS context and `typeList` in a JS context.

**Comment by noamr** [comment]
> > (e.g. the only thing I can think of right now is `animation-name`)
> 
> A counterexample is `font-family` which you set to a list of font names. The property could as well be named `font-name` but instead it use the `family` suffix.
> 
> Rewinding a little bit back, I raised this concern because there were a bunch of different names for it, which seems a bit weird: `types`, `type`, and `typeList` (the `types` one turning out to be a typo in the spec).
> 
> I could see Noam’s suggestion above work, but then that would not solve the descriptor in the `@view-transition` rule, which still is `type` _(at this moment)_.

That one is a list of idents though. It's equivalent to `class`, it's not a JS array. So I think `type` is fine for the descriptor.

> 
> Moving forward, I think the most consistent way to talk about this would be to use the term _“Type List”_ across the board. In CSS that would become `type-list` (in the `@view-transition` rule) and in JS `typeList` (when passing it into `startViewTransition()`, when reading it from a `ViewTransition` object, and when reading it from `CSSViewTransitionRule`).

Is this consistent with anything existing in CSS atm? I was using the `*List` suffix only for a `DOMTokenList` which is consistent with `classList`.

**Comment by khushalsagar** [comment]
> That one is a list of idents though. It's equivalent to class, it's not a JS array. So I think type is fine for the descriptor.

The `class` vs `classList` is a good counter for why `type` in CSS is reasonable. But it feels like authors will have an easier time if its the same name everywhere:

1. [at-rule](https://drafts.csswg.org/css-view-transitions-2/#view-transition-type-descriptor)
2. [CSSViewTransitionRule](https://drafts.csswg.org/css-view-transitions-2/#navgation-behavior-rule-interface)
3. [startViewTransition](https://drafts.csswg.org/css-view-transitions-2/#dictdef-startviewtransitionoptions)
4. ViewTransition object

2) and 4) are already using `typeList`. So could startViewTransition and the at-rule use `typeList` as well. We have to do `typeList` for CSSViewTransitionRule because of https://github.com/w3c/csswg-drafts/issues/9905.

**Comment by noamr** [comment]
> > That one is a list of idents though. It's equivalent to class, it's not a JS array. So I think type is fine for the descriptor.
> 
> The `class` vs `classList` is a good counter for why `type` in CSS is reasonable. But it feels like authors will have an easier time if its the same name everywhere:
> 
> 1. [at-rule](https://drafts.csswg.org/css-view-transitions-2/#view-transition-type-descriptor)
> 2. [CSSViewTransitionRule](https://drafts.csswg.org/css-view-transitions-2/#navgation-behavior-rule-interface)
> 3. [startViewTransition](https://drafts.csswg.org/css-view-transitions-2/#dictdef-startviewtransitionoptions)
> 4. ViewTransition object
> 
> 2. and 4) are already using `typeList`. So could startViewTransition and the at-rule use `typeList` as well. We have to do `typeList` for CSSViewTransitionRule because of [[css-view-transitions-2] `CSSViewTransitionRule.type` overrides deprecated `CSSRule.type` #9905](https://github.com/w3c/csswg-drafts/issues/9905).

I think if we do away with (3) (https://github.com/w3c/csswg-drafts/issues/10070#issuecomment-1995165143), having it `type` where we can is equivalent with existing things (class, view-transition-class, font-family, part...). We use `typeList` only because the word `type` is overused and sometimes conflicting (e.g. in `CSSViewTransitionRule`).

So I think using `type` in CSS but `typeList` in JS when it's a `DOMTokenList` is consistent enough with current things. But I'm happy to resolve on whatever we reach consensus around.

**Comment by khushalsagar** [comment]
Thanks for clarifying Noam. So sounds like we at least have consensus on renaming the `type` param in `startViewTransition` to `typeList` for consistency across all javascript APIs. Let me Agenda+ for that.

I have a stronger preference for `type-list` for the at-rule than `type` for the same arguments that were made on https://github.com/w3c/csswg-drafts/issues/9972. Makes it more obvious that `typeList` on the ViewTransition object is initialized using the descriptor in the CSS at-rule.

@nt1m @fantasai what's your preference?

**Comment by nt1m** [comment]
I tend towards `types`, there is precedent for using plural in descriptors (e.g. @counter-style has a few)

**Comment by khushalsagar** [comment]
^ Is there a reason to favour `types` over `type-list`, even though the latter maps directly to the script references to types.

**Comment by bramus** [comment]
> I tend towards `types`, there is precedent for using plural in descriptors (e.g. @counter-style has a few)

As this point I was gonna suggest `types` as well. It describes what you are defining _(hinting at possibility to add more than one)_, it’s vague enough to be correct in both CSS and JS land, and it makes it easy for the author to use: the thing is called `types` _(independent of the context)_.

As you mention `@counter-style` has precedent for having a descriptor that is plural. Another one is [`@font-palette-values`](https://drafts.csswg.org/css-fonts/#om-fontpalettevalues)’s [`override-colors`](https://drafts.csswg.org/css-fonts/#override-color)

**Comment by noamr** [comment]
> > I tend towards `types`, there is precedent for using plural in descriptors (e.g. @counter-style has a few)
> 
> As this point I was gonna suggest `types` as well. It describes what you are defining _(hinting at possibility to add more than one)_, it’s vague enough to be correct in both CSS and JS land, and it makes it easy for the author to use: the thing is called `types` _(independent of the context)_.
> 
> As you mention `@counter-style` has precedent for having a descriptor that is plural. Another one is [`@font-palette-values`](https://drafts.csswg.org/css-fonts/#om-fontpalettevalues)’s [`override-colors`](https://drafts.csswg.org/css-fonts/#override-color)

I'm ok with this, we went with `type` because of a notion in the TPAC conversation that CSS doesn't use plurals. (I believe @tabatkins & @astearns raised this?)

**Comment by khushalsagar** [comment]
So *proposed resolutions* based on the comments so far is:

- Rename the `type` param in `startViewTransition` to `typeList`.
- Rename `type` descriptor in the css at-rule to `types`.

**Comment by vmpstr** [comment]
Replying to different people:

> A counterexample is `font-family` which you set to a list of font names. The property could as well be named `font-name` but instead it use the `family` suffix.

I don't believe this is a counterexample, since this is a list of font families (each item is a font family and there is potentially more than one). 

> So I think using `type` in CSS but `typeList` in JS when it's a `DOMTokenList` is consistent enough with current things. But I'm happy to resolve on whatever we reach consensus around.

That's my preference as well, since I believe the majority of the use cases are likely to specify a single type. Although there is precedence in plurality, it feels it would be more consistent with singular names. However, I'm happy with whatever CSSWG agrees on at this point

**Comment by nt1m** [comment]
> So _proposed resolutions_ based on the comments so far is:
> 
>     * Rename the `type` param in `startViewTransition` to `typeList`.
> 
>     * Rename `type` descriptor in the css at-rule to `types`.

Why not use `types` for both the JS & CSS APIs?

**Comment by khushalsagar** [comment]
^ That was resolved here: https://github.com/w3c/csswg-drafts/issues/9905#issuecomment-1969544713.

**Comment by bramus** [comment]
That resolution was to rename `type` to `typeList` for the CSSOM, as [`type` already exists there on `CSSRule` (and is deprecated by now)](https://drafts.csswg.org/cssom/#legacy-css-style-sheet-members:~:text=The%20type%20attribute%20is%20deprecated).

Tim’s suggesting to rename the descriptor and parameter to simply `types`, something [I’m also OK with](https://github.com/w3c/csswg-drafts/issues/10070#issuecomment-1999138223).

As noam [mentioned](https://github.com/w3c/csswg-drafts/issues/10070#issuecomment-1999158754), `type` was chosen at TPAC in Sept 2023 but I currently can’t seem to find back the minutes regarding this.

**Comment by noamr** [comment]
> That resolution was to rename `type` to `typeList` for the CSSOM, as [`type` already exists there on `CSSRule` (and is deprecated by now)](https://drafts.csswg.org/cssom/#legacy-css-style-sheet-members:~:text=The%20type%20attribute%20is%20deprecated).
> 
> Tim’s suggesting to rename the descriptor and parameter to simply `types`, something [I’m also OK with](https://github.com/w3c/csswg-drafts/issues/10070#issuecomment-1999138223).
> 
> As noam [mentioned](https://github.com/w3c/csswg-drafts/issues/10070#issuecomment-1999158754), `type` was chosen at TPAC in Sept 2023 but I currently can’t seem to find back the minutes regarding this.

OK, actually in TPAC the resolution was that this argument name was TBD: https://github.com/w3c/csswg-drafts/issues/8960#issuecomment-1719695337

The relevant resolution is this:
https://github.com/w3c/csswg-drafts/issues/9534#issuecomment-1802364085

**Comment by cdoublev** [comment]
The change is missing here. 😄

https://github.com/w3c/csswg-drafts/blob/dbdd87d907d9e7b6334aa52b6b589f6ce3b28771/css-view-transitions-2/Overview.bs#L531

**Comment by noamr** [comment]
> The change is missing here. 😄
> 
> https://github.com/w3c/csswg-drafts/blob/dbdd87d907d9e7b6334aa52b6b589f6ce3b28771/css-view-transitions-2/Overview.bs#L531

Oops, thanks for catching that, will follow up.
