### ISSUE TITLE
"Consume qualified rule" section in the "CSS Syntax Level 3" spec. appears to express same step _twice_, an omission? [css-syntax]

### ISSUE THREAD

**Issue by amn** [w3c/csswg-drafts#10119]
Reading https://www.w3.org/TR/css-syntax-3/#consume-qualified-rule I am confused as to why there is seemingly more or less identical steps described under "Repeatedly consume next input token", the first step is written thus:

> [<{-token>](https://www.w3.org/TR/css-syntax-3/#tokendef-open-curly)
    [Consume a simple block](https://www.w3.org/TR/css-syntax-3/#consume-a-simple-block) and assign it to the qualified rule’s block. Return the qualified rule.

Fair, enough, but then immediately after another is written thus:

> [simple block](https://www.w3.org/TR/css-syntax-3/#simple-block) with an associated token of [<{-token>](https://www.w3.org/TR/css-syntax-3/#tokendef-open-curly)
    Assign the block to the qualified rule’s block. Return the qualified rule.
    
If we disregard the fact that it's not at all clear how the condition quoted above is related to the sentence "Repeatedly consume next input token" that precedes the steps, it appears to basically express the same procedure as the first, regardless, albeit in a less comprehensible form if you ask me.

Is this an omission, and at any rate, can someone in the know clarify this issue?

If the second parable (step) is removed entirely, then in fact, the list of steps looks entirely comprehensible.

**Comment by tabatkins** [comment]
I recommend reading [the Editor's Draft](https://drafts.csswg.org/css-syntax/#consume-qualified-rule) for now, there's been significant editorial rewriting of the specification since the 2021 publication. (I do need to republish, tho.)

-----

That said, the old text is indeed expressing two different things - a { token or a simple block. The algorithm at the time could be invoked with either a raw token list, or a token list that had already been thru the consumption process once before (and thus now contained other types of component values, like simple blocks). This is no longer the case, tho.

**Comment by amn** [comment]
Thank you. Again, I got confused by the list title ending with the colon suggesting the steps are directly related to the token while I can't understand _how_ one is supposed to compare or otherwise relate a "simple block" to the current input token:

> Repeatedly consume the [next input token](https://www.w3.org/TR/css-syntax-3/#next-input-token):

> [simple block](https://www.w3.org/TR/css-syntax-3/#simple-block) with an associated token of [<{-token>](https://www.w3.org/TR/css-syntax-3/#tokendef-open-curly)
    Assign the block to the qualified rule’s block. Return the qualified rule.

I mean, a block is an object of different type than a token. When it is apparently asked whether a token is a block, I for one am not sure what is being asked of an implementation there.

The Editor's Draft has apparently rectified this as the steps mention tokens and tokens alone.

**Comment by tabatkins** [comment]
Even the /TR version you were originally looking at [defines "next input token" in that way](https://www.w3.org/TR/css-syntax-3/#next-input-token):

> The token or [component value](https://www.w3.org/TR/css-syntax-3/#component-value) following the [current input token](https://www.w3.org/TR/css-syntax-3/#current-input-token) in the list of tokens produced by the tokenizer.

Some of the parsing algorithms do a simple run over the token stream, assembling a list of component values (which can be tokens *or* things like blocks) until they hit the ending token they're looking for, then pass that list into another parsing algorithm to actually do something useful with. So those algos need to be prepared to see a list of *unprocessed* tokens (which can contain things like a `{` token) or a list of *processed* tokens (which will instead contain a simple block holding everything between the original `{` token and the matching `}` token).

But again, this is moot now in the current text, as I no longer invoke any algorithms in that way. (I needed to do so because I couldn't tell how to parse the contents of a block without contextual knowledge, but since then we've made some changes that do allow me to unambiguously parse all blocks.)

> I'll have to start over with implementing tokenization and parsing if I am to switch to the editor's draft, no?

Yes, you should use one or the other, and by "or" I really mean "you should use the ED, it's up to date and matches what browsers are expected to do". The differences are minimal, tho - other than an editorial rewrite, the changes since the TR publication were mostly focused around getting CSS Nesting to work properly.
