### ISSUE TITLE
[css-functions] Shouldn't the index of functions include `url()`?

### ISSUE THREAD

**Issue by praveenpuglia** [w3c/csswg-drafts#1014]
I am looking at the CSS Indexes, [Functions](https://drafts.csswg.org/indexes/#functions) section and I realized the `url()` function isn't mentioned there. Is this deliberate or am I missing something?

Looking at this [example](https://www.w3.org/TR/css3-values/#functional-notations) it feels like it should be part of it.

**Comment by plinss** [comment]
It should be present, it's missing because there is no &lt;dfn> markup for it in our specs so Shepherd can't find a link anchor, and Bikeshed doesn't see it. Needs a spec update for better markup.

css-values defines the &lt;url> type, but apparently not the url() function.

**Comment by praveenpuglia** [comment]
So is there something I can do on my end and send PR somewhere to get this fixed?

**Comment by svgeesus** [comment]
Sure! Sending a PR that adds the correct markup to declare that function would be super helpful. The editors could also do it, but they are busy with a lot of other specs as well so a PR would get the change in faster.

**Comment by praveenpuglia** [comment]
So all we need is `<dfn>url()</dfn>` snippet like [this](https://github.com/w3c/csswg-drafts/blob/master/css-values/Overview.bs#L1957) for `url()`?  If so, we might also need a paragraph of text which gives a brief intro to `url()` like it does for `attr()` or `toggle()`. Example - 

> The \<dfn\>toggle()\</dfn\> expression allows descendant elements
	to cycle over a list of values instead of inheriting the same value.

**Comment by plinss** [comment]
Basically, yes, but the `<dfn>` also needs an id or to be inside something with an id (like a heading) so that it serves as an anchor for other specs to link to. For specs using bikeshed (css-values-3/4), the id will be automatically generated by bikeshed, however CSS2.2 uses a different pre-processor, I'm not sure if it adds ids to `<dfn>s` or not.

For completeness, both Bikeshed and Shepherd also need type information for the `<dfn>` e.g. `<dfn data-dfn-type='function'>` but both will use heuristics and should determine the type automatically based on the `()`. See the [Bikeshed docs](https://tabatkins.github.io/bikeshed/#definitions) for more detail on that.

CSS2.2 should definitely get a `<dfn>url()</dfn>`, but as you say, might require prose changes to make sense in context. It's debatable whether a url function definition should be added to css-values or not, please consult the editors on that one, cc @tabatkins @fantasai
