### ISSUE TITLE
[css-align] Inconsistent fallback alignments for space-between and space-around/evenly

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#10154]
https://drafts.csswg.org/css-align/#distribution-values

| Alignment | Fallback |
| - | - |
| `space-between` | `flex-start` |
| `space-around` | `safe center` |
| `space-evenly` | `safe center` |

As per https://drafts.csswg.org/css-align/#valdef-overflow-position-safe, `safe center` will basically behave as `start`, which differs from the `flex-start` of `space-between`.

Blink seems to treat all of them as `flex-start`

```html
<!DOCTYPE html>
<style>
.flex { display: inline-flex; flex-wrap: wrap-reverse; flex-direction: row-reverse; height: 100px; width: 100px; border: solid; margin: 30px; }
.flex::before { content: ""; height:125%; width: 125%; flex-shrink: 0; z-index: -1; background: cyan; }
</style>
<div class="flex" style="place-content: space-between"></div>
<div class="flex" style="place-content: space-around"></div>
<div class="flex" style="place-content: space-evenly"></div>
```
![](https://github.com/w3c/csswg-drafts/assets/7477678/d3127907-f117-4e2f-afdd-715199011040)

**Comment by fantasai** [comment]
There's two effects that this controls:

- What happens with only one item.
- What happens with overflow.

Wrt rationale:

- Overflow on these should be safe, so they should probably all be `safe`. Maybe `space-between` needs to change here.
- `space-around` and `space-evenly` reasonably devolve into centering.
- `space-between` positions the first item flush, so it was decided to use start fallback alignment. IIRC at the time of discussion there wasn't a distinction between `flex-start` and `start` so we didn't debate that point. I think this is also why we overlooked whether it was safe or not...

Proposal: Update `space-between` fallback from `flex-start` to `safe flex-start`.

**Comment by nicoburns** [comment]
IMO the weird/confusing thing in the spec is `space-around` and `space-evenly` using the concept of fallback to specify their centering behaviour. I feel like the centering behaviour of `space-around` and `space-evenly` (and the start-like behaviour of `space-between`) in the case of a single node should just be part of the definition of those layout modes.

For example the spec for `space-around`:

> The [alignment subjects](https://drafts.csswg.org/css-align/#alignment-subject) are evenly distributed in the [alignment container](https://drafts.csswg.org/css-align/#alignment-container), with a half-size space on either end. The alignment subjects are distributed so that the spacing between any two adjacent alignment subjects is the same, and the spacing before the first and after the last alignment subject is half the size of the other spacing.

Could be adjusted to say something like: "If there is only a single alignment subject then available space is evenly distributed at either end". Or the ratio formula for dividing the available space (1:2:2:2:1) could be stated more explicitly in a way that is still works in the case that there are no spaces between alignment subjects.

Then the concept of fallback would only be required in the case of overflow and would be much more straightforward: just specifying a fallback to either `start` or `flex-start` (I guess it really needs to be `start` in order to be truly safe?).
