### ISSUE TITLE
[css-grid-3][masonry] Performance concerns wrt intrinsic track sizing in grid axis

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10266]
Blink raised concerns with quadratic performance of intrinsic track sizing with spanning items, filing this issue to track that item specifically (as opposed to the exponential issue tracked in https://github.com/w3c/csswg-drafts/issues/9326). See comments in https://github.com/w3c/csswg-drafts/issues/8206 and https://github.com/w3c/csswg-drafts/issues/9041 

> I'm also concerned that considering all non-explicitly placed grid items in every posible start position will likely result in bad performance, that's a guaranteed quadratic algorithm.

> The proposal outlined to address the placement/sizing mismatch in https://github.com/w3c/csswg-drafts/issues/8206#issuecomment-1710169743 could result in approximately quadratic performance, even in very simple cases.

**Comment by tabatkins** [comment]
More details:

* It's completely fine to have any arbitrary mixture of fixed and/or flexible tracks. They can be fully sized without regards to content, so there's no issue.
* It's fine to have multiple intrinsic-sized tracks *that are the exact same size* (aka a `repeat(5, auto)` or something). These can be dealt with by just measuring every item ahead of time (and adjusting the measured size to handle spanning items; subtract the gaps and divide by the span).
* It's fine to have any arbitrary mix of tracks, intrinsic or otherwise, if there are no spanning elements (or if spanning elements don't contribute to the size of columns). Again, you just measure every item once, and then account for the potential of them being in each track; it's slightly more work than the previous bullet, but not unreasonable. (*Technically* the complexity of this is also (number of items * number of tracks), but taking the measurements of an element into account for each of the tracks is much simpler/cheaper when they're only touching one track at a time).
* The potential perf issue arises when you have an intrinsic-sized track mixed with *any other-sized track*, and there are spanning items. This requires you to lay out the spanning items multiple times, for every possible position crossing one or more intrinsic tracks; this behavior is quadratic (in the number of spanning items times the number of columns, which can both be arbitrarily large).

> (as opposed to the exponential issue tracked in https://github.com/w3c/csswg-drafts/issues/9326).

This is actually identical to the exponential issue. The behavior listed here is quadratic for most grid items; it becomes exponential if the spanning items are subgrids (or rather, sub-masonrys) and contain their own spanning items.

**Comment by fantasai** [comment]
> This requires you to lay out the spanning items multiple times, for every possible position crossing one or more intrinsic tracks; this behavior is quadratic (in the number of spanning items times the number of columns, which can both be arbitrarily large).

Afaict, you don't actually have to lay out the items here? You're just taking their minimum / min-content / max-content sizes.

**Comment by fantasai** [comment]
Copying over the resolutions that were accidentally recorded in #10053:

* `RESOLVED: allowing mixed track sizing,  as long as the algorithm does not allow position-dependent effects`
* `RESOLVED: add a note about the grouping optimization and baseline handling`

<details><summary>The full IRC log of that discussion</summary>
&lt;noamr> fantasai: TabAtkins, Iank_ and I discussed this on monday, and decided that we think this is doable, want to resolve that we allow mixed track sizing on masonry and investigate<br>
&lt;noamr> fantasai: it is currently a point of contention<br>
&lt;fantasai> Proposed resolution? Allow mixed track sizing in masonry; investigate applying limitations on the size contributions of subgrid/submasonry child items to avoid pathological performance characteristics.<br>
&lt;noamr> IanK_: it would be good to explicitly spec how you're supposed to group things and then apply the sizing algo, otherwise it would get lost and implementers won't do it correctly<br>
&lt;noamr> IanK_: we need to list out how you're supposed to do this, and also mention the positional independence thing<br>
&lt;noamr> IanK_: to get the perf characteristics, you have to group everything by how it's sized, and then apply the track sizing algorithm<br>
&lt;noamr> IanK_: it's different from today where all the items are having applied the track sizing algorithm together<br>
&lt;noamr> fantasai: it's an optimization of the currently spec'ed algo, we can add it as a note for a possible optimization<br>
&lt;noamr> fantasai: I want to keep the algo easy to read<br>
&lt;noamr> IanK_: for an implementor, if they have to dig notes to find important optimizations it's difficult<br>
&lt;noamr> fantasai: there are further optimizations, this is not the only possible optimizations<br>
&lt;noamr> fantasai: It's ok to outline this, but it's not our jobs in specs to detail exactly how to optimize stuff. we might not come to the right solution. This problem exists in all spec<br>
&lt;noamr> fantasai: translating spec directly into code is a bad habit<br>
&lt;TabAtkins> It is useful to give guidance when something should be done in a particular way, fwiw.<br>
&lt;fantasai> Yeah, I'm fine with giving guidance<br>
&lt;noamr> IanK_: I don't want to lose the positional idenependence stuff as it requires for the algorithm to work<br>
&lt;TabAtkins> If there *is* a behavioral difference, tho, then it does matter and needs to be in teh algo, obvs.<br>
&lt;fantasai> obvs<br>
&lt;noamr> IanK_: positional independence is key to get this opt to work<br>
&lt;noamr> IanK_: otherwise we're back to CSS2.1 where there are no algorithm specified<br>
&lt;noamr> IanK_: we can write the basic constraints and build the other constraints on top of that<br>
&lt;noamr> astearns: hearing a few things to resolve. is this merely an optimization?<br>
&lt;noamr> fantasai: yes<br>
&lt;noamr> IanK_: as long as we have positional independence<br>
&lt;noamr> IanK_: the current algorithm does have positional dependence<br>
&lt;noamr> astearns: is the first resolution that we allow mixed track size, with a normative bit on positional independence<br>
&lt;noamr> proposed resolution: allow mixed track sizing on masonry, as long as the algorithm does not allow position-dependent effects<br>
&lt;noamr> RESOLVED: allowing mixed track sizing,  as long as the algorithm does not allow position-dependent effects<br>
&lt;noamr> astearns: proposed resolution, add a note about the grouping optimization and baseline handling<br>
&lt;noamr> RESOLVED: add a note about the grouping optimization and baseline handling<br>
&lt;noamr> fantasai: investigate limitations on subgrid contribution of subgrid items to avoid perf issues<br>
&lt;noamr> fantasai: we need to dig more<br>
&lt;noamr> astearns: any other resolutions needed on this one?<br>
&lt;TabAtkins> ScribeNick: TabAtkins<br>
</details>

See [details on performance analysis and optimizations here](https://fantasai.inkedblade.net/style/specs/masonry/performance).
