### ISSUE TITLE
[css-fonts-5] Computed value for font-size-adjust

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#10292]
Branched off from https://github.com/w3c/csswg-drafts/issues/6384

@shivamidow wrote in https://github.com/w3c/csswg-drafts/issues/6384#issuecomment-2060578912:

>> So, we currently have:
>> 
>> > **`from-font`**
>> > Computes to the [`<number>`](https://drafts.csswg.org/css-values-4/#number-value) corresponding to the specified metric of the [first available font](https://drafts.csswg.org/css-fonts-4/#first-available-font).
>> 
>> Proposed resolution (the "no adjustment" option):
>> 
>> > **`from-font`**
>> > If the specified metric exists, computes to the [`<number>`](https://drafts.csswg.org/css-values-4/#number-value) >
corresponding to the specified metric of the [first available font](https://drafts.csswg.org/css-fonts-4/#first-available-font). Otherwise, the same as `none`

> I'd like to clarify the computed value for `from-font` a bit more. Unless the specified metric exists in the used font, what is the computed value of `font-size-adjust: ic-height from-font` in the proposed resolution? [Is it `ic-height none` or just 'none'](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/parsing/font-size-adjust-computed.html#L46)?

to which @svgeesus replied, the computed value should ne `none` in this case.

@drott wrote:

> I am surprised the computed value would in either situation leak something from what's found in the font files. Whether that's related to a number fount in the font file, or from a heuristic, or none. Don't we need to adjust the [spec text for the computed value](https://drafts.csswg.org/css-fonts-5/#font-size-adjust-prop) to include from-font? Could it be that was historically not updated when from-font was added? But I might be misunderstanding something here.

**Comment by drott** [comment]
For two reasons I don't think it's right to compute this into actual values from the font. 

1) Compare: https://drafts.csswg.org/css-text-decor-4/#text-decoration-thickness-property which also contains a from-font keyword - and its computed value: This property does not leak any font data either. 
2) This would require a recompute of this property's value as an effect of font-family changes or availability of loaded web fonts. This sort of cross-talk is not desirable.

**Comment by jfkthame** [comment]
I thought that computing to the actual value was deliberate, because that's what we want to inherit. If it instead computes to `from-font`, that'll mean that child elements with a different first available font will not be adjusted based on the ancestor's value.

Given
```
data:text/html,<p style="font: 40px Impact; font-size-adjust: from-font">
                   Hello <span style="font-family: Times;">cruel</span> world
```
the expectation should be that the `<span>` inherits the adjustment factor from the **Impact** font, not that it computes its own from **Times**.

(See also https://github.com/w3c/csswg-drafts/issues/9050)

**Comment by xiaochengh** [comment]
Hmm... I was quite surprised when I didn't see "as specified" in the spec text and thought it's a mistake or something, but it makes sense now with @jfkthame's example.

So I'm switching my position :)

Leaking/Exposing font data via computed style is probably not a big issue, as we already have a lot of precedences (like the absolutization of `ex` unit in computed values). So we can allow one more here.

And it should be better if we have a note/example in the spec to explain the rationale.

**Comment by shivamidow** [comment]
I left a similar concern about the consistency in `from-font` [1]. Can we decouple the computed value for `from-font` from rendering? I mean using a computed/resolved value for rendering but returning the `from-font` keyword for `getComputedStyle()`.

[1] https://github.com/w3c/csswg-drafts/issues/9050#issuecomment-1756065407

**Comment by jfkthame** [comment]
> I left a similar concern about the consistency in `from-font` [1]. Can we decouple the computed value for `from-font` from rendering? I mean using a computed/resolved value for rendering but returning the `from-font` keyword for `getComputedStyle()`.
> 
> [1] [#9050 (comment)](https://github.com/w3c/csswg-drafts/issues/9050#issuecomment-1756065407)

I don't see how that could work. According to https://www.w3.org/TR/css-cascade-4/#computed, it's the _computed value_ that gets inherited, so as noted in my comment [above](https://github.com/w3c/csswg-drafts/issues/10292#issuecomment-2108251725), this needs to be resolved to a number (not remain the `from-font` keyword) in order to work as expected in descendant elements.

`getComputedStyle()` sometimes returns a _used_ value that is "further resolved" than the _computed_ value, but I don't think there's any precedent for it to return a "less resolved" value.

The `from-font` value of `text-decoration-thickness` or `text-underline-position` is not really comparable. Given:
```
data:text/html,<div style="font-size: 50px;
                           font-size-adjust: from-font;
                           text-underline-position: from-font">
                   <u style="font-family: Courier New">Courier</u>
                   <u style="font-family: Arial">Arial<u>
```
the two words will have underlines at different positions, because they each get it from their respective fonts (having inherited the `from-font` keyword), but they're expected to apply the same font-size-adjust factor, which they inherit (as a computed number) from the div, so that their ex-heights will be equalized.

**Comment by dbaron** [comment]
Minutes substitution I couldn't make in time: 
s/five other ways/five other ways, whether computed style from font relative units or layout/
