### ISSUE TITLE
[css-anchor-position] Alignment shouldn't interfere with sizing

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10315]
The current definition of `anchor-center` says

> Additionally, any auto inset properties resolve to 0. However, the available space for the positioned element in the relevant axis is reduced to the size of the largest rectangle that is centered on the default anchor element and doesn’t overflow the inset-modified containing block. (Possibly being zero-sized, if the anchor’s center is not within the inset-modified containing block.)

In general, alignment doesn't change the containing block for sizing, it just shifts the box within the alignment container. (The only exception is stretch, which simply fills the box.) In all cases, there are only two sizes to consider, and their relationship to each other: the alignment container, and the alignment subject. I don't think we should change that here.

Also this behavior yields some really weird, and likely unexpected, results for simple things like

```
inset-area: bottom;
max-width: 20em;
```

where if the anchor happens to be near the edge of the screen, the tooltip ends up wrapped into a very very narrow tall block.

If the author wants to cap the size to the largest width that could result in true centering, let's add that as a keyword to the sizing or inset properties or something else that's actually supposed to affect sizing.

**Comment by tabatkins** [comment]
Yes, this sizing behavior was very intentional, and necessary for reasonable behavior, even *if* it can result in a too-small containing block size sometimes.

Note that sizing and alignment are strictly in that order - size first, then align. In every other alignment keyword, that's fine - if you size into the full containing block size (and don't overflow right away), you can then left, right, or center yourself and you'll *always* stay within the containing block. This isn't true for anchor-center - if you size into the full width of the containing block, and then center on the anchor, it's *very easy* to overflow the rect. Here’s an example.

There are two solutions to this. The first is what the spec currently says - give it the sizing constraint that actually keeps it within the containing block rect when it's centered on the anchor.

The second is to give it the full size, but then *un-align* it if necessary to keep it in the containing block rect. This is the "slide" behavior we've talked about, and intentionally deferred so it can get more design thought. (See #9960) We want sliding for more than just anchor-center (I mention wanting anchor-left and anchor-right - Bikeshed's own dfn panels use JS to get an "anchor-left" behavior with sliding.)

When we design the sliding behavior more generally, it should override this containing block size reduction for anchor-center, and let you size as large as you want. But before then, it's better to be too small in some cases than overflow (possibly into the unscrollable area) in even more cases.

**Comment by fantasai** [comment]
The sliding behavior is what alignment does, fundamentally. I think that should be the default. Tweaking the available space is not what alignment does, generally, and I don't think it's an appropriate default here. If you want to tweak sizing, you should use a property that affects sizing.
