### ISSUE TITLE
[css-anchor-position] Default alignments for inset areas are wrong

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10313]
(I thought we had already edited this in, but apparently not...)

The current resolution of `normal` alignment is defined as follows:
* If the inset area includes the center region in an axis the default alignment in that axis is `anchor-center`
* Otherwise, it’s the opposite of the region it specifies: if it’s specifying the "start" region of its axis, the default alignment in that axis is `end`.

But actually it should be:
* If the inset-area is a side track, then the alignment is towards the center track (i.e. in the opposite direction of the named track).
* If the inset-area is the center track, or all tracks, then alignment is anchor-center.
* If the inset-area includes the center track and a side track, then alignment is towards the excluded track.

This behavior for the double tracks gets you the correct behavior for more cases, and is easier to switch to the other common behavior (centering) because centering isn't conditional on which area you're in.

**Comment by tabatkins** [comment]
(Just to be clear, the first two bullet points (in the second group listed above) are current spec behavior; it's the third, covering span-* keywords, that's different.)

It turns out that the Chrome impl already does what you're requesting, rather than what I wrote in the spec. I'm happy to update the spec to match; I agree it's better. [Here's an example](https://jsbin.com/mirabip/edit?output).

(IIRC, the current behavior for a span-* value was written when anchor-center automatically "un-aligned" for overflow, which resulted in a similar behavior to what you're suggesting. I just didn't revisit this when the sliding behavior was deferred; it definitely needs to be changed.)

Do you think we need a resolution for this, or are you okay with just an edit?
