### ISSUE TITLE
[css-overflow-4] Line-clamp and IFC

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#10323]
Currently, [`line-clamp`](https://drafts.csswg.org/css-overflow-4/#line-clamp), through [`continue: discard`](https://drafts.csswg.org/css-overflow-4/#valdef-continue-discard), is defined not to establish and Independent Formatting Context.

In @andreubotella 's experimmental implementation of it, he found it easier to implement as creating an Independent Formatting Context. Also, in his [exploration of the variant of line clamp based on hiding visibility rather than fragmentaiton](https://github.com/w3c/csswg-drafts/issues/10322), (so-called `continue: collapse`), he found that variant too to be simpler to implement and reason about if we can assume an Independent Formatting Context.

The original idea not to set up an IFC was not particularly driven by use cases, but rather by a theoretical argument: if we can get away without an IFC, it's more flexible, and authors can always opt into having an IFC if they need one. However, the priority of constituencies tells us to put implementation considerations ahead of theoretical concerns, so in the absence of a clear author need, we should keep it simple.

Therefore, the proposal is that, regardless of which approach we take to get to `line-clamp`, we do establish an IFC.

**Comment by andreubotella** [comment]
To expand on the difficulties found when trying not to establish an IFC:

The main feature of `continue: discard` is that it turns a box into a fragmentainer. The other existing fragmentainers are always an IFC from the perspective of the outside (not of the content flowing inside them): for multi-column (and regions) this is explicitly specified as such, and for paged media this is necessary because there is no content outside of the fragmentainer.

While this precedent by itself is not a reason to force `continue: discard` to establish an IFC, it means that existing layout engines might implement fragmentation in ways that assume an IFC (as Chromium does). And the possibility that fragmentainers are not always IFCs would open a number of spec questions that would need to be answered (e.g. what happens when a non-IFC `continue: discard` contains a float with a break inside it? Would it affect the positions of floats and the clearance of boxes in the same BFC but outside the fragmentainer?)

For `continue: collapse`, the main difficulty is floats. The way I conceptualize this variant as working, the rendered result should behave as if none of the content after the clamp point in the layout tree existed (modulo the ellipsis). Therefore, floats before the clamp point be able to affect the position of floats and the clearance outside of the `continue: collapse` container, but floats after the clamp point should not.

However, the geometry of boxes after the clamp point should be queried from JS APIs. If we want that to give any kind of meaningful result, then the positioning of floats and the clearance of boxes after the clamp point should depend on the floats before *and after* the clamp point.

So while I don't think this is a no go for the Chromium implementation, it certainly adds complexity that might not be needed for any actual use cases.

**Comment by frivoal** [comment]
Done in https://github.com/w3c/csswg-drafts/commit/dcc75edea85fca982a6112dde4e0ce7c8ade96ec

**Comment by andreubotella** [comment]
Tests were added in web-platform-tests/wpt#46734
