### ISSUE TITLE
[css-overflow-4] When does the blockification of -webkit-box occur?

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#10435]
Does it happen within style-adjustment or when building the box-tree?

**Comment by andreubotella** [comment]
In Blink, if the specified value of `display` is `-webkit-box` or `-webkit-inline-box`, that is also its computed value. Then, when building the box tree, if an element would have `display: -webkit(-inline)-box`, `-webkit-box-orient: vertical` and a value of `-webkit-line-clamp` (or `line-clamp` in our WIP implementation of `continue: collapse`) other than `none`, then a block box is created. (If any of those conditions does not hold, `display: -webkit(-inline)-box` creates a flex box.) Then, during block layout, those conditions are checked again to know whether `-webkit-line-clamp` would have any effect.

In Firefox, if those conditions hold, the computed value of `display` is `flow-root` (for `-webkit-box`) or `inline` (for `-webkit-inline-box`). None of the other properties are changed during style adjustment. But because of that, the check of whether `-webkit-line-clamp` applies during block layout needs to check the specified value of `display`, rather than the computed value.

**Comment by frivoal** [comment]
> In Gecko, if those conditions hold, the computed value of `display` is […] `inline` (for `-webkit-inline-box`)

Did you mean `inline-block` rather than `inline`?

In any case, I lean towards the approach followed by Blink. Since we need to refer to the display property again to check if it is `-webkit-box` before deciding if `-webkit-line-clamp` has an effect, keeping that as the computed value seems preferable.

That said, I don't care strongly either way, and if implementers prefer to align on the Gecko behavior instead, I have no objection.

**Comment by andreubotella** [comment]
> Did you mean `inline-block` rather than `inline`?
Indeed, it is `display: inline-box`.

**Comment by emilio** [comment]
I did this intentionally fwiw, it's more consistent with other display adjustments like the `position: absolute` blockification, etc...

**Comment by emilio** [comment]
> In any case, I lean towards the approach followed by Blink. Since we need to refer to the display property again to check if it is `-webkit-box` before deciding if `-webkit-line-clamp` has an effect, keeping that as the computed value seems preferable.

For reference, this is not an issue because engines need to store the "original" display anyways for e.g. static positioning. Ideally we'd remove that restriction to make `-webkit-line-clamp` work on blocks, too...

**Comment by andreubotella** [comment]
The spec text at a7a5838c449627765504c1dc7195d49ea409a34c has the computed value become `flow-root` for both `-webkit-box` and `-webkit-inline-box`. This doesn't match Firefox, where `-webkit-inline-box` becomes `inline-block`.

**Comment by frivoal** [comment]
oops, you're right. copy and paste gone wrong. Fixed.

**Comment by andreubotella** [comment]
Added tests in web-platform-tests/wpt#47993.
