### ISSUE TITLE
[css-values] attr()'s type system is inconsistent with other things

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#10437]
As briefly discussed with @tabatkins during CSS Day:

 - In `@property`, we have `"<length>"`, and similar.
 - We intend to use the same for the parameter types of custom functions (probably).
 - We have a loose plan of dropping the string-part of the syntax string, making it possible to specify `<length>` directly. (https://github.com/andruud/csswg-drafts/pull/2/files). EDIT: This now exists, but only for [css-mixins-1](https://drafts.csswg.org/css-mixins-1/#syntax).

Why doesn't `attr()` use the same way of specifying types? I.e., shouldn't we do `attr(data-foo <length>, 0px)` instead of `attr(data-foo length, 0px)`?

EDIT: I accidentally posted the issue template.

**Comment by andruud** [comment]
Agenda+ on behalf of @tursunova.

**Comment by Crissov** [comment]
#6408 proposes explicit type conversion functions and #3702 a string parsing function. Both approaches could be used instead of a type hint within `attr()`.

**Comment by tursunova** [comment]
#3702 was already closed, since it doesn't bring extra functionality and attr() is easier to read, compare https://github.com/w3c/csswg-drafts/issues/3702#issuecomment-488118915.

Even if it will be decided to add a conversion function, as per #6408, I don't think we would like to remove `<attr-type>` from the grammar. So adding angle brackets would make `attr()` grammar more compatible with other things, like registered custom property syntax types.

**Comment by tabatkins** [comment]
Edits checked in, including moving the `<syntax>` production over to Values 5 since multiple specs are using it now.
