### ISSUE TITLE
[css-text] Minor issue for line breaking strictness

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#10531]
https://drafts.csswg.org/css-text/#line-break-property

> The following breaks are allowed for `normal` and `loose` line breaking if the writing system is Chinese or Japanese, and are otherwise forbidden:
> breaks before certain CJK hyphen-like characters:
> 〜 U+301C, ゠ U+30A0

They are not only allowed for `normal` and `loose`, but also `anywhere`? Maybe it is already implied, but it would be better to mention it clearly?

**Comment by frivoal** [comment]
This whole list only discusses the difference between loose/normal/strict. In most cases the phrasing makes it obvious, but here I see the problem you're pointing out.

Just adding "normal and loose and anywhere", wouldn't work, because for normal and loose this is also conditioned on the writing system being Chinese or Japanese, while for anywhere that would always be true.

Maybe we can fix this ambiguity in the sentence that preceeds the list:
> However, <ins>for these three keywords, </ins>this specification does require that:

**Comment by xfq** [comment]
Thanks @frivoal. That works for me.
