### ISSUE TITLE
[css-text-decor] Results for text-underline-position: under

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1055]
https://drafts.csswg.org/css-text-decor-3/#text-underline-position-property

Here are the results of applying `text-underline-position: under` to some random text with a bunch of arabic script fonts i have on my system in Canary (today).  I also applied `text-decoration-skip: ink` just because it shows collisions more clearly (it didn't affect the results). All text is set  to 30px font-size.

![screen shot 2017-02-22 at 17 53 41](https://cloud.githubusercontent.com/assets/4839211/23225241/2e7b8c28-f929-11e6-867e-25fab0031047.png)

The result is font-dependent. Some don't clear the bottom of the text. (And generally the line seems a little thick to me.) I didn't find any difference whether the language was set to en, ar, fa, or ur.

The following shows that for vowelled text the result is unfortunately much worse.

![screen shot 2017-02-22 at 18 20 04](https://cloud.githubusercontent.com/assets/4839211/23226000/f6f4cd70-f92b-11e6-9378-79037e555073.png)

**Comment by r12a** [comment]
Fwiw, here are some similar tests for Tibetan, however, i should say that i don't know whether users of the Tibetan script do actually use underline.  I didn't find any in the materials i have here.

![screen shot 2017-02-22 at 19 09 19](https://cloud.githubusercontent.com/assets/4839211/23227972/baec281c-f932-11e6-8c3f-17b2709be0d0.png)

**Comment by khaledhosny** [comment]
My guess is that it is using the font descender for the underline position not the actual extents of the text box, which would explain why the results vary so much between fonts. Using a fixed value makes sense I guess since you don’t generally want the underline position to change between different lines based on their context, but may be the descender is not the best choice at least for Arabic since glyphs tend to go past the ascender and descender rather often, no idea what would replace it though.

**Comment by r12a** [comment]
I'm not sure whether a fixed value would work either.  You see the variation in letter size above, even though all font-size is set to 30px. I suppose that with a fixed line fonts like Scheherazade would have a very wide gap between the line and the text, whereas others could still hit the line, _unless_ there was some way to tie the distance to the actual size of the glyphs.

Also, there's the problem that the nastaliq fonts are much more greedy for vertical space than the naskh or ruq'a styles.

**Comment by behnam** [comment]
> The following shows that for vowelled text the result is unfortunately much worse.

@r12a, actually, IMHO, some of those results are actually the best you can get out of the font. For example, the Noto Nastaliq Urdu:

![image](https://cloud.githubusercontent.com/assets/37169/23231425/8db60254-f8fc-11e6-8648-2079982561df.png)

> Using a fixed value makes sense I guess since you don’t generally want the underline position to change between different lines based on their context, but may be the descender is not the best choice at least for Arabic since glyphs tend to go past the ascender and descender rather often, no idea what would replace it though.

@khaledhosny, as we have seen in various examples, it does happen that some letters (or diacratics) cross the descender line in Arabic script text, and I thought we agreed that there's nothing wrong with that.

And, about the font property value not being set correctly, what do you think about why the descender is being set too high (or too low) for Arabic fonts?

**Comment by kojiishi** [comment]
This is so great, thank you @r12a for starting this thread.

We have [a bug](http://crbug.com/681857) that we render under-underline too low for CJK on some fonts, because these fonts have [internal leading](https://support.microsoft.com/en-us/help/32667/) not only for ascender but also for descenders too, and drawing at the descenders (in the font metrics) looks terribly poor.

I was thinking to fix the position to be the bottom of em-box (i.e., bottom of "p") for East Asian scripts and was wondering how it affects other scripts, but IIUC it'll make Arabic underlines worse?

Also, a bit off-topic, but since we take the metrics from the primary font, how often does Arabic use `font-family: Times, some-arabic-font`; i.e., put Latin font before Arabic font? This happens a lot in East Asian pages, which makes this issue more complicated for me.

**Comment by khaledhosny** [comment]
> Also, a bit off-topic, but since we take the metrics from the primary font, how often does Arabic use font-family: Times, some-arabic-font; i.e., put Latin font before Arabic font? This happens a lot in East Asian pages, which makes this issue more complicated for me.

I happens quite often in Arabic as well.

**Comment by fantasai** [comment]
Older drafts of css-text-decor-3 have more guidance on underline positioning, fwiw. I don't think it handles fallback fonts, but that seems like an oversight since it delves into varying font settings across elements. https://www.w3.org/TR/2013/WD-css-text-decor-3-20130103/#line-position Some of that guidance could be helpful here for dealing with fallback fonts. Of course, that section was removed because implementers didn't want it...

I don't think there's anything we can do about bad font metrics. I'm happy to put guidance in the spec about <em>which</em> font metrics to use, but certainly the glyph bounding box--which is the only metric that would avoid collisions entirely--is not an acceptable answer here since it can place the underline on top of text in the next line when the font designer has chosen to bleed the glyphs outside the ascent/descent. I suspect the best place to put an underline will vary a lot by typeface: the more cursive ones will require greater levels of collision in order for the text not to look absurdly disjoint from the underline, whereas the more print-like ones will be able to accommodate a nearby underline without so many problems since they maintain a more consistent inked "baseline".

Wrt Tibetan, SIL has some examples: http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=iws-chapter09#964d1526 Afaict from @r12a's examples, it seems more important to avoid collisions with the top of the next line than to avoid collisions with the bottom of the current one, and what we choose to do here should ideally reflect that constraint.

**Comment by fantasai** [comment]
i18n comment: Turn this into a note/warning/example about under not being entirely under.
