### ISSUE TITLE
[css-easing-2] Linear easing function requires at least two points?

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#10580]
Is it correct to assume that the linear-easing-function requires at least two points?  If that's the case, shouldn't the syntax be
`[ <linear-stop> ]#{2,}`?
 
https://github.com/w3c/csswg-drafts/blob/065eb9119738d0e99e1bd8cef5f4cc97a22595b2/css-easing-2/Overview.bs#L173

**Comment by tabatkins** [comment]
Nah. Similar to gradients, you can supply two positions for a single stop, so a grammatical requirement like that would prevent authors from writing some otherwise reasonable things. (It would allow `linear(0 0%, 0 100%)`, but disallow the identical-meaning `linear(0 0% 100%)`.)

However, the text as currently written does fail if you provide a single stop, whether you give it two %s or not. ("create a linear easing function" explicitly fails if there is only a single stop, regardless of whether it's doubled or not; "calculate linear easing output" implicitly fails with an OOB access if there's only a single stop (not doubled).

The first failure should get fixed; there's nothing wrong it conceptually. The second should also be fixed, just to avoid grammar oddities, the same as how we just resolved to allow single-stop gradients; there's a trivial behavior for it. I'll propose some edits.

**Comment by tabatkins** [comment]
Agenda+ to request the following changes:

1. Allow "create a linear easing function" to accept a single stop (making it no longer possible to fail). (So `linear(.4 0% 100%)` is valid, identical to `linear(.4 0%, .4 100%)`.
2. Fix "calculate linear easing output" to handle having a single stop (acting as a constant function at that output value). (So `linear(.4)` is valid, identical to `linear(.4 0% 100%)` in behavior, tho it'll serialize as only a single stop.)r

**Comment by cdoublev** [comment]
Accepting a single stop would close #8932 (related/duplicate issue) with no change.

**Comment by tabatkins** [comment]
Fixed: grammar, parsing, serialization, and output all now correctly handle a single stop.
