### ISSUE TITLE
[css-view-transitions] persist transitions support more than just audio and video players

### ISSUE THREAD

**Issue by jlarmstrongiv** [w3c/csswg-drafts#10620]
I found an invitation to give [feedback](https://developer.chrome.com/docs/web-platform/view-transitions/same-document) on View Transitions.

I have been using view transitions since they were first [experimentally](https://astro.build/blog/astro-290/) supported in Astro, and experimenting with them even before that with chrome flags.

Today, they are now a [stable](https://docs.astro.build/en/guides/view-transitions/) part of the framework, and work is being done to power them with [Zero-JavaScript View Transitions](https://astro.build/blog/future-of-astro-zero-js-view-transitions/).

However, one section in a recent post concerned me: 

> What about transition:persist?
> [Persistent element transitions](https://docs.astro.build/en/guides/view-transitions/#maintaining-state) became a popular feature in Astro. The transition:persist directive told Astro to persist an element across navigation without interrupting or disrupting its state. This enabled UI like audio and video players to continue to play across pages, like in [Maxi Ferreira’s](https://twitter.com/charca) [music player demo](https://astro-records.pages.dev/).
> 
> Unfortunately, this feature is not yet supported by native cross-document navigation in the browser. Native support for persistent audio and video players may be coming in the future, but in the meantime you can continue to use our <ViewTransitions /> component if you need this additional functionality.

I believe that that persisting view transition should not be limited only to audio or video players.

For example, I am using persisted view transitions to keep web workers online across pages.  This lets users navigate across my site without reloading the page, unloading the worker, and having to restart processing.  What a wonderful user experience!

I can also see persisting transitions helpful for custom player controls, preventing the browser from resetting sidebar scroll positions, persisting state and other information, etc.  

Anyway, thank you for drafting and implementing view transitions!  I have really enjoyed using them so far, and I hope to keep using them in the future too.

**Comment by bramus** [comment]
What you are essentially requesting here is a way to pass element state across navigations from one document to another. This feature is not related to View Transitions as it applies to _any_ MPA – regardless of which framework you are using or whether you are using View Transitions or not.

👉 This is an HTML feature request, and is being discussed in https://github.com/whatwg/html/issues/8538

For completeness:

- The reason why elements can be persisted in SPAs across different views is because in an SPA architecture the document never unloads. The persisted elements can be any type of element – audio, video, div, h1, etc – and is not tied to the use of a framework nor View Transitions.
- If you are fine with a small glitch, you can manually pass state from one page to another using `pageconceal` and `pagereveal`. See https://view-transitions.netlify.app/video/mpa/ for a demo.
