### ISSUE TITLE
[css-color-4] Add `<alpha-value>` parameter to  `<named-color>` and `<hex-color>`

### ISSUE THREAD

**Issue by francescorn** [w3c/csswg-drafts#10678]
***Problem***
Currently, you have to specify the `alpha-value` separately in [`<named-color>`](https://www.w3.org/TR/css-color-3/#svg-color) and [`<hex-color>`](https://www.w3.org/TR/css-color-4/#hex-notation) as `opacity`. It affects all elements if there are multiple.
```
.element {
  background-color: #aaaaaa;
  color: black;
  opacity: 0.5;
}
```

***Proposed Solution***
Add an `alpha-value` to  [`<named-color>`](https://www.w3.org/TR/css-color-3/#svg-color) and [`<hex-color>`](https://www.w3.org/TR/css-color-4/#hex-notation) in the same line:
```
.element {
  background-color: #aaaaaa 0.5;
  color: black 0.7;
}
```

**Comment by nt1m** [comment]
This is what relative color syntax is for:
```
rgb(from #aaa r g b 0.5)
rgb(from black r g b 0.7)
```

(note that #aaaaaa80 should also halve the opacity of #aaa) 

I could see a function to apply alpha that acts as syntax sugar though: `color-alpha(#aaaaaa 0.5)`

**Comment by romainmenke** [comment]
Couldn't we relax the syntax for relative colors a bit more to make the channel values optional?

`rgb(from black / 0.5)` ?

**Comment by SebastianZ** [comment]
@romainmenke I've split your suggestion out into a separate issue, as it's a little different from the suggestion here (but obviously covers the same use case).

Sebastian

**Comment by Crissov** [comment]
Since 4-digit and 8-digit hex notation already exists, like @nt1m already pointed out, this leaves **named semi-transparent colors**. 

These would probably require new compound keywords, e.g. `translucent-navy`, `seethrough-deep-pink` or `foggy-goldenrod`. The WG seemed not very enthusiastic about adding *any* new [color keywords](https://drafts.csswg.org/css-color/#named-colors) in the past, so I don’t think this will ever happen. 

Inside `color()` or a dedicated, new pseudo function or with [relative color syntax](https://drafts.csswg.org/css-color-5/#relative-color) (RCS), it *could* be possible to introduce a keyword-based syntax to construct colors or alter the alpha value of a base color, but earlier discussions regarding such systematic color designations (like CNS) lead nowhere except eventually to the aforementioned RCS. Also, English does not really have good words to describe more than, say, three different levels of transparency. Therefore, this is also highly unlikely to ever happen.

**Comment by svgeesus** [comment]
Note that CSS Color 4 already [allows 8-digit hex colors](https://drafts.csswg.org/css-color-4/#hex-notation) so the example given would become `#aaaaaa7f`
