### ISSUE TITLE
[css-view-transitions-2] How are invalid types validated?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#10706]
Apparently there are invalid types (see #9534):
> type can accept any idents, except 'none' or '-ua-' prefixes

I would suggest throwing a TypeError or a SyntaxError when these are used in DOM APIs (notably the setters).

cc @noamr @khushalsagar @vmpstr @bokand

**Comment by nt1m** [comment]
cc @tuankiet65

**Comment by nt1m** [comment]
Aside from the DOM APIs, should the use of invalid names in the `types` descriptor of `@view-transition` make the declaration invalid?

(I personally think it should, for clarity)

**Comment by noamr** [comment]
See [this resolution](https://github.com/w3c/csswg-drafts/issues/10114#issuecomment-2023217450)

We specifically allowed invalid types in the `setlike` setters, to be consistent with `CustomStateSet` where the set can include and reflect invalid values, but they're not selectable in JS.

I think this validation should be in `@view-transition { types }` and in `:active-view-transition-type()`, not sure it needs to be in CSSOM.

I think it's important that it would make the whole at rule invalid, otherwise an at rule with invalid types would trigger a transition as if it has no types.

**Comment by noamr** [comment]
I can't attend the APAC meeting, but proposing to leave the wording as is, as per [previous resolution](https://github.com/w3c/csswg-drafts/issues/10114#issuecomment-2023217450).
