### ISSUE TITLE
Why there's no horizontal-rtl and horizontal-ltr values in the "Writing mode" property?

### ISSUE THREAD

**Issue by tomasts248** [w3c/csswg-drafts#10731]
There must be a reason but I'm failing to see which is..  also should the property direction be used with the Writing mode property, what is the recommended usage? Thanks

**Comment by nt1m** [comment]
```
writing-mode: horizontal-tb;
direction: ltr;
```
or
```
writing-mode: horizontal-tb;
direction: rtl;
```

are what you're probably looking for

**Comment by tomasts248** [comment]
Thank you! I only wonder why not using making it simpler and have something like horizontal-rtl and horizontal-ltr?

**Comment by nt1m** [comment]
The part after the `-` is the block flow direction (in this case top to bottom). The inline flow isn't really controlled by the writing mode.

Maybe(?) it could make sense to have a shorthand for the text flow though (cc @fantasai ) 

Although note that in your case, you really just need `direction: ltr;` / `direction: rtl`, `writing-mode: horizontal-tb` is the default value.

**Comment by tabatkins** [comment]
Marking as "Question Answered" - as Tim said, 'writing-mode' gives the *axis* of text flow, and the *direction* that text lines are stacked, but the *direction* of text flow is determined by the 'direction' property instead. This is somewhat a historical issue, as directionality was originally controlled solely by the `dir` attribute in HTML, which was adapted into the 'direction' property. 'writing-mode' was created separately and designed to work alongside that.

I'll let @fantasai decide if this issue should just be closed, or if there's more to discuss.

**Comment by tomasts248** [comment]
As I view it, is not congruent or consistent that in vertical you can specify ltr and rtl and in horizontal not, and that can cause confusion

**Comment by frivoal** [comment]
>As I view it, is not congruent or consistent that in vertical you can specify ltr and rtl and in horizontal not

In vertical, `-rl` vs `-lr` are about whether the lines of text stack from right to left or from left to right, as different languages need that (Chinese and Japanese vs Mongolian or Manchurian). Horizontal only has `-tb` to say that lines stack the other way (from top to bottom) because no (modern) language has lines that stack up from bottom to top, so a `-bt` value would serve no purpose, even if it would make the system more complete.

In both horizontal and vertical (both `-rl` and `-lr` variants), whether the flow of text within the line is English-like, which is usually called left-to-right (even though in the vertical case case the line's "left" is at the top) or Arabic-like, which is usually called right to left (even though in the vertical case the line's "right" is at the bottom) is controlled by `direction`, not by `writing-mode`.

**Comment by Crissov** [comment]
As an aside, I once thought that some chat systems were bottom-to-top, because the input box was on the top followed below by the latest message, but in fact those systems stack *blocks* (i.e. messages) and *not lines* of text on top of each other. 

However, some street markings in English and other languages are indeed B2T if the street is considered the canvas, so the first line/word can be read first, but this is clearly out of scope for CSS. 

Another however, some young kids intuitively start writing in the lower left corner of a page instead of the upper left corner, but this goes alongside turned or mirrored letters and other signs of early writing acquisition, so it is also out of scope.

**Comment by tomasts248** [comment]
> > As I view it, is not congruent or consistent that in vertical you can specify ltr and rtl and in horizontal not
> 
> In vertical, `-rl` vs `-lr` are about whether the lines of text stack from right to left or from left to right, as different languages need that (Chinese and Japanese vs Mongolian or Manchurian). Horizontal only has `-tb` to say that lines stack the other way (from top to bottom) because no (modern) language has lines that stack up from bottom to top, so a `-bt` value would serve no purpose, even if it would make the system more complete.
> 
> In both horizontal and vertical (both `-rl` and `-lr` variants), whether the flow of text within the line is English-like, which is usually called left-to-right (even though in the vertical case case the line's "left" is at the top) or Arabic-like, which is usually called right to left (even though in the vertical case the line's "right" is at the bottom) is controlled by `direction`, not by `writing-mode`.

Thank you I understand now ;)

**Comment by tomasts248** [comment]
May I ask as well here, the direction property actually seems to set the direction of the alignment of text?

**Comment by jfkthame** [comment]
The initial value of `text-align` is `start`, in which case the resulting alignment will indeed depend on the direction. (On the other hand, if `text-align` were set to one of the physical values `left` or `right`, it would be unaffected by direction.)

**Comment by tomasts248** [comment]
I see, thank you so much :-)

**Comment by Loirooriol** [comment]
> a -bt value would serve no purpose, even if it would make the system more complete

Worth noting that WebKit supports both horizontal-tb and horizontal-bt.

https://github.com/WebKit/WebKit/blob/d36c972c6b9472b5f4e8fa9292abf8b0a2e72532/Source/WebCore/platform/text/WritingMode.h#L51-L53
