### ISSUE TITLE
[css-view-transitions-2] Clarify inbound transition timeout semantics

### ISSUE THREAD

**Issue by mattwoodrow** [w3c/csswg-drafts#10800]
The current spec mentions a UA defined timeout as part of `resolve inbound cross-document view-transition`, which then cancels the active view transition (in a queued task).

The `pageswap-long-delay.html` test is using a very-long synchronous `pageswap` event to trigger the timeout, which suggests that the timed period starts before this event (which is fairly removed and before the `resolve inbound cross-document view-transition` algorithm).

It would be good to clarify when the timed period starts.

The test is also expecting the `pagereveal` event's `viewTransition` parameter to be null, which is different from queued cancellation of the view transition. I'm not sure if this is a test bug, or a spec bug.

**Comment by khushalsagar** [comment]
Looks like a spec bug. The spec text is for https://github.com/w3c/csswg-drafts/issues/9155 which asks to abort the transition if the navigation is too long. The navigation starts while the old Document is still active and `pageswap` is part of the navigation phase.

Was checking in case we got it wrong from a refactor but looks like this was set up that way since the PR which added it: https://github.com/w3c/csswg-drafts/pull/9608/files.

@noamr can you take a look?

**Comment by noamr** [comment]
See https://github.com/w3c/csswg-drafts/pull/10817
