### ISSUE TITLE
[w3c.gif] FlameWordMaker.com - It should be here?

### ISSUE THREAD

**Issue by INeedJobToStartWork** [w3c/csswg-drafts#10835]
# Hey
i have checked [w3c.gif](https://github.com/w3c/csswg-drafts/blob/main/w3c.gif) in this repo and there is domain name providing to website which seems to be... strange?

I guess 9 years ago when this gif has been added on this domain was text generator with flame effect but current it's other thing.

[This Gif](https://github.com/w3c/csswg-drafts/blob/main/w3c.gif)
<img width="225" alt="image" src="https://github.com/user-attachments/assets/ba119e8f-e72d-4b67-8314-1f49c4ce5f3c">

[WhoIs of website](https://who.is/whois/flamewordmaker.com)
<img width="609" alt="image" src="https://github.com/user-attachments/assets/497b1d04-3c16-413d-9869-e2653e9c4084">

This Website
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/659859d3-3404-4ed9-af50-d2e8e156332d">
**_Click on text:_**
<img width="1746" alt="image" src="https://github.com/user-attachments/assets/5e27b3e0-8d12-4794-94dc-477bf511eb7c">
**_Click on left Img:_**
<img width="1844" alt="image" src="https://github.com/user-attachments/assets/49b9937f-0880-49ff-8c89-94fcd9ffa1d6">

**Comment by tabatkins** [comment]
That image is used by our occasional "April Fools" styling - we replace the normal W3C logo with that flame logo. Keeping the domain name of the generator in there is part of the retro-shitty Geocities-esque aesthetic.

Not at all surprising the domain has disappeared in the years since I made the image. I'm pleasantly surprised by how *aesthetically consistent* the shitty ad landing page is, tho.
