### ISSUE TITLE
[css-values-5] Do not make the type of `*-progress()` consistent with its input calculations?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10840]
(Follow-up on this https://github.com/w3c/csswg-drafts/issues/10770#issuecomment-2333382568)

For `container-progress()` and [`media-progress()`](https://drafts.csswg.org/css-values-5/#media-progress-func):

  > The two input calculations but must have a consistent type or else the function is invalid. The result will be a `<number>`, made consistent with the consistent type of the arguments.

There is no size/media feature accepting percentages, but if there was one, say `hypothetical-length-percentage-feature`, I think `opacity: media-progress(hypothetical-length-percentage-feature from 0% to 100px)` should be valid.

**Comment by tabatkins** [comment]
I disagree. The % in the calculations needs to have a consistent source for resolving itself, and the clear answer in general is to take it from the property context (so you can do useful things with the box's size in 'width', for example).

So, your example would be invalid - the `0%` is typed as `{percent -> 1}` since it resolves against `<number>`, but that *can* be added to the `{length -> 1}` from `100px`. The function's type is thus `{}` and a percent hint of "length", which fails to match 'opacity's `<number>` grammar, since it has a non-null percent hint. This is good, since the % in this instance is not *intended* to be resolved against lengths.

(Hm, I should really capture that fact explicitly; the tip-toeing I do around percentages sometimes would be a little better if the percent hint could be non-null when it resolves against number or just as itself, so it'll fail earlier, at type-addition time, rather than later when matching the type against a grammar.)

There is certainly a *potential* for an MQ to accept a non-trivial percentage, such that you'd actually want its value. In that case, we'll have to create some clear way to obtain it. But there's no examples of this so far.

**Comment by tabatkins** [comment]
Actually, hm, I think I'm wrong. I need to check with @fantasai, but I suspect the *intention* is to evaluate the calculations *entirely* in the context of the MQ itself (or the CQ).

If that's the case, then indeed, the types shouldn't be made consistent, as they're self-contained. (`progress()` still needs to be consistent, as its calculations *are* evaluated in the outer context.)

**Comment by tabatkins** [comment]
Okay yup, fixed in <https://github.com/w3c/csswg-drafts/commit/4da8f9f0d7c7e78ec3a467a3b227dc78f2b118bd>. (accidentally mistagged the issue)
