### ISSUE TITLE
[css-values-5] Receive comma-separated arguments in `*-progress()`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10862]
All [math](https://drafts.csswg.org/css-values-4/#calc-syntax) and [mix](https://drafts.csswg.org/css-values-5/#mixing) functions receive comma-separated arguments whereas [progress functions](https://drafts.csswg.org/css-values-5/#progress) receive keyword-separated arguments.

What is the reason for this difference? Does this makes up for the inconsistent and more verbose syntax, which is somewhat unusual for a CSS function?

Nit: since progress functions can be used in math functions, which are internally represented with a calculation tree, you can no longer assume that any operator node representing a function (assuming progress functions are represented as operators) should serialize with its values joined with `, `; this information must be preserved.

**Comment by fantasai** [comment]
Thanks for pointing this out! I had noticed it and then forgot to follow up. I don't mind too much if mix() and progress() differ from the rest of the math functions, but those two have a very similar structure and should probably be consistent.

**Comment by tabatkins** [comment]
I agree that mix() and the progress functions should be consistent in their syntax, since they're doing such similar things. mix() doesn't have any choice - because it's using `<whole-value>`, the *only* choice for its separators are (upgradeable) commas; keywords are absolutely no-go. So that suggests we should shift the progress functions over to just being comma-separated arguments.

**Comment by fantasai** [comment]
Apparently I did notice, and filed this as https://github.com/w3c/csswg-drafts/issues/10489 :P Closing as a dup.
