### ISSUE TITLE
[css-animation] Is calc() allowed to be used for the <keyframe-selector> production in the @keyframes prelude?

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#10879]
The [\<keyframe-selector\>](https://drafts.csswg.org/css-animations-1/#typedef-keyframe-selector) production in the [@keyframes](https://drafts.csswg.org/css-animations-1/#keyframes) prelude is defined via the grammar:

> \<keyframe-selector\> = from | to | [<percentage [0,100]>](https://www.w3.org/TR/css-values-4/#percentage-value)

Generally, use of `<percentage>` implies the ability to use calc(), but it does not seem to be universally implemented that way. 

Is the intention of the spec that calc() should be allowed here?

**Comment by fantasai** [comment]
I think it wasn't explicitly thought about, but if there's no reason not to it might as well work.

**Comment by tabatkins** [comment]
Yes, it's generally expected that any place a type appears in the grammar, anything which produces that type is allowed (if valid in the context otherwise).

Historically UAs have been very inconsistent in where they allow math functions outside of properties (and even within properties), but it *should* work, yes.

**Comment by weinig** [comment]
Great, thanks.
