### ISSUE TITLE
[cssom] Don't describe CSSStyleDeclaration getters/setters using "macro" Web IDL

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#1089]
CSSOM has the following bits of problematic Web IDL:

```WebIDL
partial interface CSSStyleDeclaration {
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString _camel_cased_attribute;
};

partial interface CSSStyleDeclaration {
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString _webkit_cased_attribute;
};

partial interface CSSStyleDeclaration {
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString _dashed_attribute;
};
```

This cannot be copied verbatim into implementations or to idlharness.js, and is therefore more "inspiration" than concrete Web IDL. The reason I'm noticing is that we're comparing all of Blink's IDL to all of the specs it links to and it looks like we have a non-standard getter and setter. Those are what implements this.

Would it be possible to define all of this using getters and setters?

@zcorpan

**Comment by zcorpan** [comment]
It's not clear to me what you are proposing or how it helps your tools from listing these as non-standard. Can you clarify?

I'm happy to change this, but I would prefer to avoid duplicating WebIDL's requirements. My idea was that implementors would generate actual IDL files here. But if everybody does it in some other way then it makes sense to change the spec.

cc @bzbarsky - how is this handled in Gecko?

**Comment by foolip** [comment]
I'm not sure about all the constraints here, but I was imagining a getter and setter with prose explaining what it does. Maybe:

```WebIDL
getter DOMString (DOMString name);
setter void (DOMString name, DOMString value);
```

Although it isn't that simple in Blink right now:
```WebIDL
// The camel-cased and dashed attribute getters have custom bindings.
// https://dev.w3.org/csswg/cssom/#dom-cssstyledeclaration-camel-cased-attribute
// https://dev.w3.org/csswg/cssom/#dom-cssstyledeclaration-dashed-attribute
[Custom=(PropertyGetter,PropertyEnumerator,PropertyQuery)] getter (DOMString or float) (DOMString name);
[Custom] setter void (DOMString property, DOMString? propertyValue);
```

@doomdavve @rune-opera, would either of you happen to know the quirks of this API to say how the spec could be expressed using "plain" Web IDL?

Maybe the enumeration is what makes it all hard, is there such a thing as a custom enumerator in Web IDL? Would it be work to make the interface `maplike<>`, or would that create another kind of mess?

**Comment by bzbarsky** [comment]
In Gecko this is handled exactly how the spec does it.  We have a data file containing a list of all supported CSS properties (which we actually use for various things).  We use this data file to generate a webidl file.  See http://searchfox.org/mozilla-central/source/dom/bindings/GenerateCSS2PropertiesWebIDL.py

The output looks something like this:

  [Throws, TreatNullAs=EmptyString] attribute DOMString alignContent;
  [Throws, TreatNullAs=EmptyString, BinaryName="alignContent"] attribute DOMString _align-content;

etc.  The BinaryName bit just says that the getter/setter for the "_align-content" property call the same underlying bits as the one for the "alignContent" property.  We don't support [CEReactions] yet, but once we do it will appear here.

I would be rather loath to implement this with getter and setter, for several reasons:

1. It would be slower, because it would require runtime dispatch on the string passed in as opposed to the current static dispatch that can be done on the JS side once we have an IC or so.

2. It would require either adding stuff to WebIDL or adding non-standard things to make enumeration of the properties work.

3. It would break the ability of webpages to hook or polyfill the getter/setter for a given property.

The usual list of reasons why we don't just use 'getter' for everything, basically.  'getter' is needed when the list of supported properties is open-ended, but in this case that list is in fact static.  The only problem from the point of view of CSSOM is that it depends on the state of support for various CSS specs.  We _could_ have every CSS spec that defines a property also define a small IDL snippet for it, but that would be quite annoying for everyone involved...

In any case, I don't think we should be letting test tools drive the API we expose to web content, which is what @foolip seems to be suggesting above.  We should expose the API we deem right, then define it in the best way we can.

For what it's worth,  I tested Edge and it seems to have actual getters/setters on on CSSStyleDeclaration.prototype for things like "alignContent", but handles "align-content" via some sort of (broken) getter-like setup.  For example, in Edge:

    "align-content" in document.body.style

tests true, but Object.getOwnPropertyNames on document.body.style and everything in its proto chain does not include "align-content".

Actually, Blink is broken in a similar way.  Yet another reason to not use a getter here: it makes it too easy to create a bad implementation that doesn't actually behave like a spec requires a getter to behave.  :(

**Comment by bzbarsky** [comment]
I should note that Blink has other spec violations around this too.  For example, Object.freeze(document.body.style) silently no-ops in Blink!  Per spec, Object.freeze should throw if called on an object with a getter, because otherwise you can think you froze a thing and you haven't actually done so.

Edge is buggy in a moderately different way.  It allows you to freeze the object, and claims that its frozen, but also claims it to have configurable properties after the freeze() call, which is totally not something that should ever happen.  Again, as soon as a getter is involved, engines start doing stuff that is just crazy as soon as you squint at them.

**Comment by zcorpan** [comment]
Given @bzbarsky's comments I think we should leave the spec as is and work on tests to get everyone compliant.

As far as tools go, the spec has the `extract` class on these specifically to allow excluding them when scraping. e.g. this selector should get all other IDL blocks:

```
pre.idl:not(.extract)
```

The same pattern is used in the HTML spec's typographic conventions IDL example:

```
  <pre class="idl extract">interface <dfn data-x="">Example</dfn> {
  // this is an IDL definition
};</pre>
```

**Comment by zcorpan** [comment]
Realized now that these are included in the IDL index; filed https://github.com/tabatkins/bikeshed/issues/946

**Comment by rune-opera** [comment]
@foolip I'm afraid not.

**Comment by foolip** [comment]
Thanks for that elaborate response, @bzbarsky! If I knew that Gecko already implements this by generating IDL I wouldn't have suggested this change. I've filed [an issue to investigate](https://bugs.chromium.org/p/chromium/issues/detail?id=700338) and will close this.

My goal here is of course that observable behavior is the same everywhere. Having Blink's IDL align with the spec (usually) helps towards that end, and the tooling in turn helps us find cases where it doesn't. I agree we shouldn't change things *just* to make tooling easier.
