### ISSUE TITLE
[css-fonts-4] font-presentation doesn't have a great name (rename to font-variant-emoji)

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#1092]
font-presentation doesn't have a great name.

For an initial proposal, I chose the name because that's what Unicode calls this stuff - "Presentation Styles". But maybe there is a better name.

**Comment by Crissov** [comment]
`font-glyph-design`, `font-glyphs`, `font-glyph-selection`, `font-glyph-variation`, `font-emoji`, `font-pictogram`, `font-picture`, `font-pictorial`, `font-symbol`, `text-transform-emoji`

**Comment by fantasai** [comment]
Just for context: “This property allows web authors to select whether emoji presentation or text presentation is used for certain emoji code points.”

**Comment by patrickdark** [comment]
`font-emoji` or `font-variant-emoji` seem to be the most straightforward. Given that change, the value `text` might be better renamed to `none` even though `text` aligns with Unicode.

Anything that refers to "presentation" or "glyphs" is too generic since things like `font-variant-east-asian` could also fall under those descriptions.

**Comment by DeeDeeG** [comment]
`emoji-presentation` would be very similar to how this terminology is handled by Unicode on their site. Makes sense to me. (I am a bit biased after flipping through the Unicode documentation so much.)

e.g. `emoji-presentation: text` `emoji-presentation: auto` `emoji-presentation: emoji`

For places where Unicode has used this phrasing/terminology: 
http://unicode.org/reports/tr51/#Emoji_Presentation
http://unicode.org/emoji/charts/emoji-variants.html
http://unicode.org/emoji/charts/text-style.html

Alternatives based on their usage:

`emoji-presentation-style`, `emoji-text-presentation`

And on a different note, I give a +1 to `font-variant-emoji` which is both a very CSS way to do it, and pretty readable for a person who has never seen it before.

**Comment by fantasai** [comment]
I'm gonna recommend `font-iconography` here!

**Comment by Crissov** [comment]
I prefer something with _pictogram_ or _pictograph(ic)_, or _picture_ if you must.

**Comment by svgeesus** [comment]
+1 to `font-variant-emoji`

**Comment by Crissov** [comment]
Property-value combos like `x-y: y;` and `x-y: x;` always feel a bit strange. The values currently are `auto | text |emoji`.

**Comment by patrickdark** [comment]
I've used the terms "chromatic" and "monochromatic" for this dichotomy before. Then I decided it wasn't a good idea since some emoji can be one color. The Symbols block of Noto Color Emoji provides some good examples of monochrome emoji: https://www.google.com/get/noto/help/emoji/symbols.html.

A lot of people don't realize that arrows and media playback buttons can also be emoji or that some emoji can be achromatic (e.g., Yin Yang). (Yin Yang is inexplicably purple in Segoe UI Emoji though.)

IMO, the suggestion of "plain" is better than "text". "sans-emoji" is another alternative.

As for the other keyword, if "emoji" is already in the (new) property name, it seems most consistent to leave that keyword as is.

**Comment by tabatkins** [comment]
> Then I decided it wasn't a good idea since some emoji can be one color.

Not only that, with paletted fonts, the "text" emoji can be multicolor too. ^_^  The distinction really is "does it get painted like text (and respond to 'color')" or "does it get painted like an image", thus the current names. ^_^

**Comment by Crissov** [comment]
`text-like`, `image-like`

**Comment by DeeDeeG** [comment]
`font-variant-emoji: emoji` could refer to "text style" or "image style," so that could be confusing.

I would go with `text | image` because it is very pragmatic and clear.

I feel these are intuitive and harder to misconstrue.

I would also support `plain | graphic`, particularly because it is pleasant to read these words (so, it's user-friendly in that way), but I am afraid "plain" is vague, and "graphic" could be a noun or an adjective.

Perhaps `text | graphic`?

**Comment by fantasai** [comment]
The name of the property was [resolved already](https://lists.w3.org/Archives/Public/www-style/2017Aug/0018.html ). Agenda+ is for the value names, which were deferred from that decision. See https://github.com/w3c/csswg-drafts/issues/1092#issuecomment-322828654 and ensuing discussion.

**Comment by svgeesus** [comment]
I quite like the value names suggestion from @DeeDeeG `text | graphic` which is clear and readable.

**Comment by DeeDeeG** [comment]
There seems to be a lot of, um "un-clarity" about what these values would do.

I can guess/infer what these would mean from a present-day implemetation standpoint, by looking at current color font support in browsers.

(To summarize, I think browsers might use black/white only OpenType tables when implementing the `font-variant-emoji: text` value, and prefer using tables that can display multiple colors when implementing `font-variant-emoji: graphic`)

---

Given that browsers tend to support the TrueType spec, and/or OpenType spec <sup>[[1]](https://caniuse.com/#feat=ttf)</sup>, which is a superset of TrueType,  everything below here in this comment is in the context of the [OpenType spec.](https://www.microsoft.com/en-us/Typography/OpenTypeSpecification.aspx)
- glyphs can be defined in a "fill"/"not-fill" binaristic way.
  - This can be an exclusively vector (curve) data format, as in these OpenType font tables: [`glyf`](https://www.microsoft.com/typography/otspec/glyf.htm), [`CFF`](https://www.microsoft.com/typography/otspec/cff.htm) or [`CFF2`](https://www.microsoft.com/typography/otspec/cff2.htm) and potentially [`SVG`](https://www.microsoft.com/typography/otspec/svg.htm).
  - Or this can be in a (binaristic "fill"/"not-fill") bitmap format, as in the [`EBDT`](https://www.microsoft.com/typography/otspec/ebdt.htm) table.
    - `EBDT` can also support full grayscale bitmaps, apparently. (not just "fill"/"not-fill" per pixel in the bitmap, but a multi-bit "fill intensity" per pixel in the bitmap.)
  - I would expect these tables to correspond to a "text" or "monochrome" or "plain" value for this draft CSS property.
    - Sticky point for implementors?: `SVG` table is able to host binaristic fill/not-fill outlines, OR multicolor glyphs. So, it is the only one of these tables that is not always single-color.
- glyphs can be defined in a few different potentially-multicolor formats.
  - [`COLR`](https://www.microsoft.com/typography/otspec/colr.htm) + [`CPAL`](https://www.microsoft.com/typography/otspec/cpal.htm) as in Segoe UI Emoji, and EmojiOne Mozilla which is bundled with Firefox
    - Outline layers+ color pallet (one color per outline, stack them -> potentially-multicolor composed glyph)
  - [`CBDT`](https://www.microsoft.com/typography/otspec/cbdt.htm)
    - Color bitmap data in one size (width x height) of bitmap per glyph
  - [`SBIX`](https://www.microsoft.com/typography/otspec/sbix.htm)
    - Color bitmap data, potentially multiple sizes (width x height) per glyph
  - [`SVG`](https://www.microsoft.com/typography/otspec/svg.htm) again
    - Complex image format, one "SVG file" per glyph. Edge decided to support only some features of SVG spec within fonts for their browser implementation. Mozilla seems to try to support the whole SVG spec.
  - I would expect these to correspond with "graphic", "image", or "fancy" or what-have-you in this draft CSS property.

**Comment by tabatkins** [comment]
@DeeDeeG 
> (To summarize, I think browsers might use black/white only OpenType tables when implementing the font-variant-emoji: text value, and prefer using tables that can display multiple colors when implementing font-variant-emoji: graphic)

No, paletted characters (which respond to 'color') will be covered by the "text" value.  The distinction really is what I said before:

> Not only that, with paletted fonts, the "text" emoji can be multicolor too. ^_^ The distinction really is "does it get painted like text (and respond to 'color')" or "does it get painted like an image" (and ignore any color-defining properties), thus the current names.

**Comment by DeeDeeG** [comment]
Ah, okay. Very interesting.

Isn't there a bit of an overlap between those categories, namely SVG, though? Opentype SVG is capable of being "paletted" per the spec and per my actual obervations of browser behavior: An outline with an unspecified (or sometimes `#000000`) color will take color from CSS `color` property, but any portion of an SVG with defined (eg `#0101ff`) color will not take on the CSS `color`.

As such, SVG is acceptable as a vehicle for a purely "palletted" font; or a font with only baked-in, explicitly set colors; or some combination within the same font or within the same glyph.

I do think that black/white (exclusively "palleted") SVG fonts aren't very popular at the moment, but they do stlil exist. And a glyph can "respond" partly to CSS `color` without being a "palleted-only" glyph: https://github.com/eosrei/emojione-color-font/issues/21#issuecomment-198023126

I guess browsers could do (psuedo-code):
```
if [
  glyph_has_any_non-palleted_color_feaures_at_all) then[
    glyph_is_graphic(); ]
  else[
    glyph_is_text(); ] ]
end_if
```
P.S. The whole `COLR` + `CPAL` combo is based around pallets, but seems to require explicit colors so as *not* to take on CSS `color`.

**Comment by tabatkins** [comment]
Yeah, SVG's complicated and annoying here.

> P.S. The whole COLR + CPAL combo is based around pallets, but seems to require explicit colors so as not to take on CSS color.

<https://drafts.csswg.org/css-fonts-4/#color-font-support>

**Comment by svgeesus** [comment]
> Yeah, SVG's complicated and annoying here.

Sigh. Both SVG-in-OpenType and also COLR in OpenType can use palettes (CPAL). SVG-in-OpenType can also explicitly use inherited values (with `inherit` or `currentColor` or `color`) as an intentional part of the glyph design. 

CPAL also has a way to inherit the color: a reserved palette index:

> the palette entry index of 0xFFFF if specified in the COLR table represents the foreground color used in the system

In conclusion, the ability to specify hardcoded colors, or overideable color defaults, or to inherit the surrounding text color, or to mix them in whatever way the designer sees fit, is a property of chromatic OpenType fonts. If you happen to find that 'complicated and annoying' then so be it, but quit blaming SVG here.

**Comment by tabatkins** [comment]
I meant "complicated and annoying" because it breaks the boundaries here.  As @DeeDeeG said, and you confirmed with details, SVG fonts can pay attention to color, or not do so, up to the designer's whims, yes? While I think other ways of creating the font are all-or-nothing user-controllable or preset.  (Maybe that's just a convention, and you *could* mix some predefined colors with some overridable colors, but that's not common?)

**Comment by svgeesus** [comment]
Oh - yes, agreed. If you squint a bit there are two disjoint categories; but when seen clearly they are mostly but not completely distinct.

Remember the typeface used in Jurassic park? Yellow with a red inner line? As an example, that could be done so that the inner part is always that red, but the outer part takes on the surrounding text color.

Since we renamed the property to refer specifically to emojii, it seems it would not apply to other character ranges so that example (with latin text) would not be affected by this property anyway?

**Comment by DeeDeeG** [comment]
Thanks for the corrections and comments.

Summary of this comment: If browser vendors check per-font instead of per-glyph, this gets a lot easier. That passes my mental "can it be done" test.

In current practice, font vendors delivering "explicit-color" font data *always* deliver it in a designated "color font", as far as I've seen. (As in, "Here's this cool font. it has explicitly-designed multi-color glyphs! [or colorful emojis.] wow!" like it's the main distinguishing feature of the font. And it happens not to be mixed in with traditional outline "inherited color" stuff except maybe as a fallback.)

So I think color features could be detected on a per-font level, and fonts themselves could be designated "text-[only]" or "graphic" (or whatever the names end up being...). That makes the needed code simpler. It makes it a one-off font sorting task before font selection, and avoids having to do many checks of whether individual glyphs are "explicit color."

Browser vendors in that case would essentially be saying:
>If you include one glyph with explicit-color technology in your font, please don't make your font predominantly black/white (or "inherited color"), because it'll confuse our CSS implementation into thinking your font is mostly for explicit-color purposes and we'll treat it as such.

Or if browsers want to, they could set up some threshold for how much "explicit color" content there can be before the font flips over into the "graphic", "fancy", "rich" whatever category... My point is, implementing this sounds *possible* at least.

**Comment by astearns** [comment]
Removing agenda+ label as we discussed it here: https://github.com/w3c/csswg-drafts/issues/2304#issuecomment-369323232

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/7a5e0d702b00f8d3df5f2b43c9c65d1c2a2284f6

**Comment by DeeDeeG** [comment]
Wasn't Agenda+ for the value names? Per: https://github.com/w3c/csswg-drafts/issues/1092#issuecomment-363611493.
