### ISSUE TITLE
[css-text-decor] ink skipping should conform to glyph shape

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1093]
Toby Reif is complaining about the exact shape & distance of the ink-skipping gaps. https://twitter.com/TobiReif/status/839809400529383424

I don't think we should define the distance--we don't have a good answer there--but it might be worth recommending that the shape should follow the outline of the glyph. Would there be any objection to adding such a should clause?

**Comment by tobireif** [comment]
I wasn't complaining. Instead I was constructively pointing out a detail where browsers render something differently from the image in the spec

"The spec shows the line endings cut off based on glyphs, while Chrome and Safari have square endings"

so that you can consider specifying eg one of the options.

Ideally there'd be a clearly defined default (eg follow the glyph shape), and perhaps also an option for setting eg square line endings.

**Comment by kojiishi** [comment]
@drott

**Comment by litherum** [comment]
While implementing this in WebKit, we found a few things:

1. You are right that the inside curve of the underline should follow the curve of the letter (typographically).
2. Using a mask-based approach is too slow. It's a deal-breaker.
3. Even when we used the mask-based approach, the mask would leave little underline floaty bits inside the lower loop of lowercase "g". These are typographically bad.
4. Our current approach is just to draw rectangles. However, one day we want to move to a trapezoid-based approach. Because most underlines are thin, this approach will probably be the best balance between performance and typography.

Maybe some implementations with less of an emphasis on speed want to use the mask based approach. Maybe even other want to use the mask-based approach, but somehow detect and eliminate the floaty bits. Browsers should be able to innovate here. The exact behavior should not be required / specced.

**Comment by tobireif** [comment]
From my POV (one web developer) it would be ideal to have a specd default (any, eg based-on-glyph-shape) so that the default rendering is consistent in all browsers. Browsers sure are free to experiment/innovate eg by offering options to developers (eg first behind flags), but it would be great if everyone could agree on one default option for the rendering of underlines.

Plus eg three options that the web developer could set (eg square, trapezoid, based-on-glyph-shape). Then the web developer could decide, incl the perf trade-off.

Regarding your #3: This should be solved by implementers.

Regarding your #4: Some are thick. Ideally you'd let the CSS user (the web developer) choose and decide per case regarding the trade-offs.

**Comment by kojiishi** [comment]
I don't feel strongly either way, but having a should clause is unlikely to help us. Rather, I'm worried about negative side effects, so I tend to agree with @litherum.

I think filing bugs to rendering engines would help much better.

**Comment by tobireif** [comment]
I don't see a bug that could be reported. Square underline line-endings are OK for some I guess. But there could be inconsistent rendering across browsers because the underline line-endings aren't specd at all.

> worried about negative side effects

If there'd be options, CSS users could make the choice and could consider any trade-offs that are relevant per usage instance.

**Comment by fantasai** [comment]
A SHOULD clause would make it clear that conforming to the shape is the intended (goal) rendering. It looks nicer is one reason, but it also helps distinguish underline vs. diacritics, so following the outline is definitely the better option. However, RFC2119 SHOULD allows UAs to deviate if they have a well-thought-out reason to do so, and the perf concerns here qualify. https://www.ietf.org/rfc/rfc2119.txt

Wrt handling floaty things, I think saying" stroke endings should follow the curve of the glyph" is sufficiently lenient: the ideal rendering would probably be something like: UA determines where it can place underline segments by where a full-height underline segment of some minimum length would fit, and then each such segment's stroke ends are made to conform to the glyph outline. (Not suggesting we spec that exactly, just that such behavior would be conformant and reasonable.)

I do agree with @tobireif that not all underlines are thin (especially once we add `text-decoration-width` in L4), and in such cases the perf tradeoff would be more worth it. A UA that cares enough to implement the ideal behavior could switch it on above a certain threshold to maintain perf for the common case, though.

**Comment by tobireif** [comment]
Thank you all!

**Comment by fantasai** [comment]
OK, checked in! @litherum, would you mind looking things over to make sure the note captures everything you want it to say? I'm happy to take suggestions for improvement.

**Comment by litherum** [comment]
"typographically-awkward wisps of underline"

Looks good.
