### ISSUE TITLE
[css-align][css-flex] 'baseline' computed value needs clarification on flexbox specs

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#1095]
The alignment spec states the following about <baseline-position> values:

https://drafts.csswg.org/css-align/#typedef-baseline-position
> <baseline-position> = [ first | last ]? baseline
> 
> The first and last values give a box a baseline alignment preference: either “first” or “last”, respectively, defaulting to “first”.
> 'baseline': Computes to 'first baseline', defined below

In the other hand, the Flexbox spec states the following:

https://www.w3.org/TR/css-flexbox-1/#align-items-property
> Value: 	flex-start | flex-end | center | baseline | stretch 
> Computed value: 	specified value 

Firefox nightly returns the following computed values:

align-items: baseline => baseline
align-items: first baseline => baseline
align-items: last baseline => last baseline

Is the current Firefox's behavior correct ? 

In any case, shouldn't the Flexbox spec reflect the new baseline syntax and computed values ?

**Comment by fantasai** [comment]
yes, Firefox's behavior is correct. See https://drafts.csswg.org/css-align-3/#baseline-values particularly the second-to-last note.

Let me know if you think a spec fix is needed here.

**Comment by fantasai** [comment]
Flexbox's definitions of these properties are limited to the subset of features that were defined when it hit CR, so it can't include the first/last keywords.

**Comment by fantasai** [comment]
Think of Flexbox as Alignment Level 3 and css-align-3 as Alignment Level 3.5 :)

**Comment by MatsPalmgren** [comment]
@fantasai FYI, the _draft_ css-flexbox spec still defines these properties differently than css-align.
https://drafts.csswg.org/css-flexbox/#justify-content-property

That seems like a spec bug to me. I think 8.2/8.3/8.4 in the draft css-flexbox spec needs to be removed/merged into css-align. It's confusing for everyone to have definitions for these properties in two places. (It's fine if the TR still have them with the old syntax/values, because everyone knows that TR means it's likely already obsolete.)

**Comment by fantasai** [comment]
The ED is intended to be a temporary staging area for /TR; /TR is out-of-date mainly because it takes so long to get it updated. We're getting better at that now that W3C finally has tooling for pushing updates without involving handoffs among the editors and at least two members of W3C Staff, so differences between ED and /TR are really bugs in the process, and should be increasingly temporary.

I added a section to Module Interactions in Flexbox; there's already one in Align. And the Alignment section of Flexbox already says that it's will be superceded by Box Alignment. Not sure what else to do.

**Comment by fantasai** [comment]
Also wrt this issue, CSS values always serialize to their shortest representation (unless that representation is newer than the longer representation, but that's not the case here).
