### ISSUE TITLE
[css-values-5] Does media-progress() really want the entire <media-feature> production for its progress value?

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#10966]
I am trying to wrap my head around the [media-progress()](https://drafts.csswg.org/css-values-5/#media-progress-func) function and am having trouble understanding exactly what kind of `<media-feature>`s should be supported as the progress value.

The stated production, `<media-feature>`, is [defined](https://drafts.csswg.org/mediaqueries-5/#typedef-media-feature) to allow a whole host of syntaxes:

```
<media-feature> = ( [ <mf-plain> | <mf-boolean> | <mf-range> ] )
```

meaning it can match things like `width > 0`, `orientation: portrait`, etc.

The spec does state: "The specified [media query](https://drafts.csswg.org/mediaqueries-5/#media-query) must be a valid “range” type query", but I can't figure out how to map that to a spec concept.

From the tests in WPT, which use only `width` and `height` as features, making me think that perhaps the grammar should be changed to use [`<mf-name>`](https://drafts.csswg.org/mediaqueries-5/#typedef-mf-name) rather than[ `<media-feature>`](https://drafts.csswg.org/mediaqueries-5/#typedef-media-feature).

**Comment by cdoublev** [comment]
My guess is that the author preferred `media-progress(<media-feature> ...)` and `container-progress(<size-feature> ...)` because it better translates the expected function arguments than `media-progress(<mf-name> ...)` and `container-progress(<mf-name> ...)`.

The parens in `<media-feature>` should probably be hoisted into `<media-in-parens>` (#10131). There is also a plan to rewrite the syntax with a generic [`<boolean>`](https://drafts.csswg.org/css-values-4/#bools) (#10457). Similarly, I suggested rewriting `<mf-name>` to `<condition-name>` (#10790).

Obviously, the spec says to restrict `<mf-name>` to feature whose `Type` is `range` in their definition table.

**Comment by fantasai** [comment]
This looks like an error in the spec, it should be a media query name only, not an entire boolean expression.
