### ISSUE TITLE
[scroll-animations] Can progress-based timelines report a current time outside of the `[0%-100%]` range?

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#11033]
I couldn't find in the Scroll-driven Animations spec whether the current time of a progress-based timeline, such as a `ScrollTimeline` or a `ViewTimeline`, can be outside of the `[0%-100%]` value range, for instance when rubber-banding. Chrome's behavior appears to be that that range is enforced and values are clipped at `0%` and `100%`. Is that behavior specified somewhere?

**Comment by graouts** [comment]
Cc @kevers-google, @andruud and @flackr.

**Comment by stubbornella** [comment]
@flackr are you the best person to ask about this or would someone else be better?

**Comment by flackr** [comment]
> Chrome's behavior appears to be that that range is enforced and values are clipped at 0% and 100%

This is because chrome clamps the developer exposed scroll offset to the reachable range, whereas Safari does not, e.g. https://output.jsbin.com/yuvulef

Timelines themselves do not impose clamping and in fact ranges beyond 0 to 100% are used regularly in view timelines to start effects before an element enters the viewport.

**Comment by graouts** [comment]
Thanks for the explanation @flackr. This is indeed some unwelcome behavior specific to WebKit that I was not aware of. This can be closed.
