### ISSUE TITLE
[css-color-adjust] Should forced-colors support `color-mix()`?

### ISSUE THREAD

**Issue by cssence** [w3c/csswg-drafts#11097]
[CSS Color Adjustment Module Level 1](https://drafts.csswg.org/css-color-adjust-1/)

I realized that Firefox performs a `color-mix()` in Forced Colors Mode when all the colors in the mix are CSS System Colors:
https://cssence.com/2024/color-mix-in-forced-colors-mode/
https://codepen.io/cssence/pen/abeVWYK

Chromium-based browsers do not. After filing an issue ([Bugzilla ticket #1927252](https://bugzilla.mozilla.org/show_bug.cgi?id=1927252)), Mozilla responsed they implemented this on purpose, i.e. not a bug but a feature. We should clarify what the behavior should be, the Chromium-based way or the Firefox way.

**Comment by kbabbitt** [comment]
[From the spec](https://drafts.csswg.org/css-color-adjust-1/#forced):

> Forced colors mode is an accessibility feature intended to increase the readability of text through color contrast. Individuals with limited vision often find it more comfortable to read content when there is a particular type of contrast between foreground and background colors.

Allowing mixing, even of system colors, seems to me like it would be counter to the intent of the feature.

**Comment by nt1m** [comment]
I would prefer allowing mixing of system colors (which WebKit also supports fwiw), but also allow the UA to override it with `currentColor` when forced colors mode is enabled.

**Comment by nt1m** [comment]
It isn't the job of CSS to prevent illegible/non-ideal colors from being created fwiw. But if the colors are non-ideal for forced colors mode, then forced colors mode should be able to override them.

**Comment by kbabbitt** [comment]
> It isn't the job of CSS to prevent illegible/non-ideal colors from being created fwiw.

This is true, but it's orthogonal to the question of allowing mixing in forced colors mode. The goal of forced colors mode is to give the user control over foreground/background color combinations. The canonical use case is high contrast, but it can be any combination - some users might find low contrast more comfortable to read, for example. Mixing these colors, however, would not be applying them as they were set by the user.

**Comment by nt1m** [comment]
Yeah, my point is that forced colors mode should be able to prevent the colors from being mixed, and override the mixed colors with appropriate colors.

**Comment by svgeesus** [comment]
> if its [computed value](https://drafts.csswg.org/css-cascade-5/#computed-value) is a color other than a system color, its [used value](https://drafts.csswg.org/css-cascade-5/#used-value) is instead forced to a system color as follows:
>[Properties Affected by Forced Colors Mode](https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties)

I read that to mean that you can mix colors if you want but the computed value that results will be overridden by a system color.

**Comment by emilio** [comment]
I can provide some context for this, as this is also perhaps relevant to the `appearance: base` discussion. The reason I implemented this in Firefox (in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1774946)) was so that color mixes like the ones @josepharhar and @nt1m are suggesting in https://github.com/w3c/csswg-drafts/issues/10909#issuecomment-2435550602 can be used in forced-colors mode.

Those kinds of mixes allow authors to have meaningful hover / active feedback colors even when in forced-colors (without a designated system color for them).

**Comment by kbabbitt** [comment]
> I read that to mean that you can mix colors if you want but the computed value that results will be overridden by a system color.

Thanks, yes, that's a detail that I missed. I just checked, and that is in fact how it works in Blink.

> Those kinds of mixes allow authors to have meaningful hover / active feedback colors even when in forced-colors (without a designated system color for them).

Personally I'd be open to defining new system color keywords to cover these use cases. But I'm also wondering if using some other indicator in forced colors mode instead might (a) more closely follow the user's palette preferences, and (b) steer away from needing to invent even more system color keywords in the future as new use cases come up. Straw example just to illustrate one possibility:
```css
@media {forced-colors: none) {
  select option:enabled:hover {
    background-color: color-mix(in lab, currentColor 20%, transparent);
  }
  select option:enabled:active {
    background-color: color-mix(in lab, currentColor 30%, transparent);
  }
}

@media {forced-colors: active) {
  select option:enabled:hover {
    outline: 1px dotted canvastext;
  }
  select option:enabled:active {
    outline: 1px solid canvastext;
  }
}
```

**Comment by svgeesus** [comment]
To be clear, `color-mix()` of system colors is _always_ allowed, and the input to the mix is the sRGB value of the system color. [example](https://codepen.io/svgeesus/pen/gOVNLwL)

The issue under discussion is whether that mixed result is over-ridden in forced colors mode.

**Comment by svgeesus** [comment]
There is no change to the normative text, but I think an example showing this would be helpful for authors and perhaps implementers. Hence https://github.com/w3c/csswg-drafts/labels/Needs%20Example%20or%20Figure

**Comment by tabatkins** [comment]
I said this in the IRC chat, but just wanted to emphasize that the case Emilio brought up to argue for allowing mixing (making a button's text partially transparent to indicate a disabled state) is *precisely the behavior we need to be worried about*, because it lowers the contrast of the text against the background and potentially renders it hard to read for users who need high contrast in the first place.

So allowing this falls into the "might actually harm the users in question". If the author isn't specifically writing `(forced-colors)`-aware styles, it's probably better for at least some users to have the disabledness simply *not be visible* (because the text is forced back into `ButtonText`) but the button still be readable, versus it being low-contrast and difficult to read.
