### ISSUE TITLE
[css-conditionals-5] Test for the support of a property name

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#11159]
This is more of a question than a proposal.

Is there any reason to not allow `@supports (property)`, `CSS.supports(property)`, `supports(property)`? 

I searched for a reason in the issues of this repo and in the www-style archives, with no success.

Today, support (of a declaration, a selector, etc) is basically defined as the ability of the UA to parse the given value and accept it in a certain context. For exemple, `<supports-decl>` represents a declaration accepted in a style rule. 

So `<supports-property>` could be a property for which the UA accepts a declaration in a style rule.

I do not know how people test the support of view transitions today, or more specifically, of cross-document view transitions, as asked in this [SO post](https://stackoverflow.com/questions/78772900/how-check-browser-support-in-css-for-view-transition-navigation-auto). Instead of checking `navigation: auto`, they could only check `navigation`. Ok, this does not save a lot of bandwidth. But it clarifies the intent. 

(**edit:** `navigation` is a descriptor and thus a bad example; perhaps `view-transition-name` or `contain` are better ones?)

Actually, I asked myself this question when reading an issue about testing the support of a descriptor declaration in a nested rule. If `CSS.supports(property, value)` queries the support of `property` declared with `value` in a style rule, `CSS.supports(rule, descriptor)` and `CSS.supports(parent-rule, rule, descriptor)` could query the support of `descritor` in the given `rule` (nested in `parent-rule`) as context... which is a different topic and again, not a proposal.

**Comment by Loirooriol** [comment]
I think the idea is that an author using `@supports (property)` may assume that the browser has full support for the property, but maybe the browser just supports a few values, which may not include the value used by the author.

If needed, you can use `@supports (property: initial)` anyways, since all properties accept `initial`.

**Comment by cdoublev** [comment]
How to evaluate [support](https://drafts.csswg.org/css-conditional-3/#dfn-support) is indeed two parts:

  > If a processor does not implement, with a usable level of support, both the property and the value given, then it must not accept the declaration or claim support for it.

I assume *full support* means *parseable + usable*.

Closing as question answered... but the CSSWG resolved on adding `at-rule(@keyword)`, which seems similar, so I will keep an eye on how it should be evaluated, and possibly re-open this issue if necessary.

**Comment by tabatkins** [comment]
Right, we *very intentionally* didn't allow just a property name, because properties gain behavior regularly, and we wanted to make sure people were actually testing the behavior they were depending on, rather than just assuming that everyone who supported a given property supported all the possible values of that property. You can still make that assumption, as @Loirooriol points out, but you have to be more explicit about testing a global value, which definitely *looks* odd and suggests that you're doing the wrong thing.

For at-rules, we originally planned to try and do a similar thing, but decided it was just too weird to put an entire at-rule into a query like that. So, we fell back to the trivial "do you at least understand this at-rule name" behavior. At least it's less common for at-rules to change behavior, so it's a bit safer to do this.

**Comment by cdoublev** [comment]
(My previous comment is confusing as to my understanding of "full support of a property", sorry.)

You think authors would use `@supports (property)` to query the "full support of a property", which would be determined as whether the UA parses and interprets (uses) any value defined as valid for that property in the different specifications, which is volatile, agree. You do not think they (or at least not most of them) would use it to query whether the UA "understands" `property`, ie. whether they know it, regardless of any value.

But you think it is fine to use `@supports (@rule)` to query the support of an at-rule, determined as whether the UA knows it, regardless of its contents (prelude and block value).

As it can be seen in the StackOverflow issue linked in the initial comment, many authors do not even know that `@supports (name: value)` is only for properties. But the number of use cases for `@supports (property)` evaluated as wheter the UA knows `property` is small... so the absence of this feature, which is inconsistent with the presence of the `at-rule(@rule)` feature, is probably fine.

**Comment by tabatkins** [comment]
Right. The difference is not based on any strong theoretical difference between the two cases, but purely on a *usability* difference:

* it's easy to write an entire property into a test, but hard to write an entire at-rule into a test
* properties change their value space a lot more frequently than at-rules
