### ISSUE TITLE
[css-grid-1][css-grid-2] Basic support for "equal gutter" with justify-content on grid items

### ISSUE THREAD

**Issue by hunboy** [w3c/csswg-drafts#1116]
[css-grid-1][css-grid-2]
https://drafts.csswg.org/css-grid/#gutters

**Motivation**: the users often want equal (horizontally, vertically) gaps for stilistic reasons.

Currently the grid-row-gap doesn't support the equal value when justify-content is defined.

As a workaround I present 3 javascript algorythms to make equal gutter between the grid items when justify-content is defined.

 - **space-evenly**: https://jsfiddle.net/utasir/20yy425r/13/
 - **space-around**: https://jsfiddle.net/utasir/20yy425r/14/
 - **space-between**: https://jsfiddle.net/utasir/20yy425r/15/

(for testing resize the frame - the 100 value in the script is same as the grid-item's width, so it's hardcoded by constant)

**Resolution**: So some basic support would be good for gaps. Perhaps "grid-row-gap: auto", or some keyword to define equal gutter for the grid system.

**Comment by fantasai** [comment]
Just to summarize, the example is
  - definite width, auto height grid container
  - auto-fill columns e.g. 100px
  - auto-placed items
  - `place-content: space-between`
The spacing produced by `space-between` is not equal in both axes.

I think there are two possible solutions here:
1. Invent some new syntax to make this happen.
2. Define that if an axis is auto-sized (and therefore justification space would be zero), justification space is instead copied from the other axis. (This is not a far stretch from how we handle frs.)

**Comment by tabatkins** [comment]
Reusing any existing syntax makes this a level 1 feature, and level 1 has been in feature freeze for some time now, so if we address this it'll be with new syntax.

**Comment by fantasai** [comment]
Agenda+ to request some ideas. We should fix this by the L2 FPWD.

**Comment by fantasai** [comment]
**Proposal...**

Name: `align-content`, `justify-content`
New values: [ &lt;number> && &lt;content-distribution>? ]

&lt;number>
: Represents a multiplier against the analogous quantity in the other dimension. If that quantity cannot be determined (e.g. is itself specified as a ratio, or otherwise can’t be referenced), then it is assumed to be zero. Specifically,
  
  * For `align-content`, `1` represents the amount of space allocated between two adjacent lines/tracks/etc. by the `justify-content` property. (This value will be zero if `justify-content` does not allocates space between adjacent alignment subjects either due to not having a &lt;content-distribution> value or due to there being fewer than two alignment subjects.)
  * Unless a different &lt;content-distribution> value is specified, space is distributed according to the same &lt;content-distribution> rules as for `justify-content`.
  * The behavior of a &lt;number> value for `justify-content` is analogous to `align-content`.
  * If both `align-content` and `justify-content` have &lt;number> values, then `justify-content`’s number value has no effect. `justify-content` takes `align-content`’s &lt;content-distribution> value, if one was specified, and falls back to `space-between` otherwise.

  Note: This value can force extra space to be placed in gutters even when there is no free space left, causing oveflow.

In this example, a minimum of 1em is required between rows and columns. Additionally, any extra space in the inline axis that is distributed between columns, with full-size spaces on either side of the outermost columns. The gaps between rows are increased to match the extra space distributed between adjacent columns, but no space is added before the first row or after the last one.

	.grid {
	  grid-template-columns: repeat(auto-fill, 15em);
	  gap: 1em;
	  justify-content: space-evenly;
	  align-content: 1 space-between;
	}

This next example is the same as the previous, except that the ratio between row and column gaps is φ:

	.grid {
	  grid-template-columns: repeat(auto-fill, 15em);
	  gap: 1em 1.618em;
	  justify-content: space-evenly;
	  align-content: .618 space-between;
	}

**... Thoughts?**

**Comment by javifernandez** [comment]
I'm not sure if the new value's syntax should allow 'stretch'. Maybe don't understand completely the proposal, but what would be the behavior of _align-content: 2 stretch_  ?

**Comment by javifernandez** [comment]
How this new value will be used in the place-content shorthand ? Some possibly ambiguous expressions that came to my mind:

- place-content: 1 start  -> align-content: 1 (space-between)  / justify-content: start 
- place-content: 1 space-around 2 ->align-content 1 space-around / justify-content: 2
- place-content: space-evenly 2 -> align-content: space-evenly / justify-content: 2 

Shouldn't forbid this new value from the place-content shorthand's syntax ?

**Comment by javifernandez** [comment]
Another issue that I'd like to note down here is how we want to deal with the different scenarios producing overflow:

- height: auto - we will use the gaps to compute the final height. However, this new Content Distribution value will add extra size. Would this imply overflowing even with height auto ? Should we use the Content Distribution extra space, added to preserve the aspect ratio to compute the final grid's height ?

- height: fixed - I'm not sure if this new value, intended to preserve the aspect ratio, should end up causing an overflow.  I think aspect-ratio preservation should only be allowed with height: auto. 

In general, I find it weird that properties that were initially defined to "distribute the available free space" ended up adding extra space, even when there is no free space left.

**Comment by javifernandez** [comment]
If we accept that the Content Distribution properties may increase the grid's height, how this would affect to the track sizing algorithm and the content-sized tracks ?

**Comment by frivoal** [comment]
I think overflow / underflow is OK here. If that is not the desired behavior, the author should not set the height of the grid. Depending on the situation, maybe min-height would be more appropriate, or maybe both height and min-height can be auto.

**Comment by fantasai** [comment]
@mrego I think overflow is the expected behavior here. It's not much different from having gaps, they're just gaps that are calculated from a justification value on the opposite axis. The use case here is a grid which has a fixed height and scrollbars: you want the items to fit into the horizontal space so you use justification, and you want the gaps to be equal, so you use `align-content: 1ar`.

**Comment by fantasai** [comment]
Switched to using `ar` units per WG resolution. I also fixed the order of the values so that if we port them to the shorthand, they'll parse clearly. Closing out the issue for now, please file new ones for any issues with the current text!

**Comment by yisibl** [comment]
Has the `ar` unit been removed from css-grid-2? I can't find it in the specification.

**Comment by SebastianZ** [comment]
> Has the `ar` unit been removed from css-grid-2? I can't find it in the specification.

Dug a little through the commits, and yes, it has been removed with a note that it will be added back in CSS Align 4.

Changes history:

* Added in https://github.com/w3c/csswg-drafts/commit/4d172d63a9d2d01d716d7a0a621efbd3fd55cd51
* Renamed to `tr` in https://github.com/w3c/csswg-drafts/commit/0a5491f38d1a40a73ac6dbbd893f33d76bb98c1b
* Removed in https://github.com/w3c/csswg-drafts/commit/558b3005e26065284970baaa8f56f09a6f40321b and #4558 has been filed to add it to CSS Align 4.

@fantasai Maybe you can provide some context in the other issue, so it's clear that this already got resolved on and just needs to be added back.

Sebastian
