### ISSUE TITLE
[css-images-4] Blink Intent to Implement conic-gradient()

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#1123]
Blink’s intent to implement, announced today: https://groups.google.com/a/chromium.org/d/msg/blink-dev/-z66SwKdklc/5t-NBchECQAJ
Spec: https://drafts.csswg.org/css-images-4/#conic-gradients

As @fantasai pointed out in Blink’s intent to implement, if Blink is implementing, this needs wider CSSWG review asap. I can introduce the topic in next week’s call.

**Comment by atanassov** [comment]
[csswg] Resolved to: 
1. Add @LeaVerou as an editor
2. Publish a new WD
3. Change/Ensure the short name to css-images-4

**Comment by chharvey** [comment]
I'm late to the game, but I was wondering if there had been any discussion on naming the function `angular-gradient()` instead of `conic-gradient()`?

Seems to me that `angular` is a more "programmy/mathy" term, and goes well with the other polar parameter, `radial`. (A polar coordinate is defined by a radius and an angle, so these two terms complement each other.)

The only explanation for why `conic` was chosen that I've come across was that,

> … it [could] produce a pattern that looks like a cone observed from above.

which, as illustrated in the spec, is not always the case.

**Comment by tabatkins** [comment]
That's an explanation of the name, but the reason we went with the name is that it's what it's commonly called in several image editors.

**Comment by svgeesus** [comment]
See for example the conical gradient in [Corel Draw](http://community.coreldraw.com/share/b/insider/archive/2014/04/03/how-to-get-the-most-out-of-x7-s-fountian-fills) or [Gimp](https://docs.gimp.org/2.2/en/gimp-tool-blend.html)

Aso, changing the name once there is implementer momentum is in general an anti-pattern.

**Comment by ewilligers** [comment]
Closing, as we [RESOLVED: Clear conic-gradient() for shipping](https://github.com/w3c/csswg-drafts/issues/2383#issuecomment-371340088)
