### ISSUE TITLE
[css-display] [css-text-decor] Propagation of text-decoration with display:contents

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1136]
From [CSS Text Decoration](https://drafts.csswg.org/css-text-decor-3/#line-decoration),

>  the decorations are propagated to all in-flow children.

From [CSS Display](https://drafts.csswg.org/css-display/#valdef-display-contents), `display: contents` means

> The element itself does not generate any boxes, but its children and pseudo-elements still generate boxes as normal.

Then, if a decoration is specified in an element which does not generate boxes, does the decoration propagate to the descendants which generate boxes?

`display: contents` does not affect inheritance, but text decorations are special because they propagate using a mechanism different than inheritance. I'm not sure if it is an element-tree thing, and thus the decoration should still propagate, or if it's a box-tree thing, and thus it shouldn't.

Example: https://jsfiddle.net/203oz4jr/

```html
<div>Foo</div>
```
```css
div {
  display: contents;
  text-decoration: underline;
}
```

Should Foo be underlined? It's underlined on Chrome, but not on Firefox.

**Comment by rune-opera** [comment]
The propagation is a box tree thing. I wouldn't expect text-decoration on a display:contents element to propagate.

**Comment by Loirooriol** [comment]
OK, thanks. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=705999

**Comment by Loirooriol** [comment]
I guess it's the same for `opacity` (here both Firefox and Chrome agree). Maybe there should some list of properties which usually affect descendants but apply to the box, so will have no effect with `display: contents`.

**Comment by tabatkins** [comment]
I'm not sure I agree with @rune-opera; why should this propagate thru the box tree specifically?  I can easily see it doing so thru the element tree instead. That is, I can see it going either way, and I want to make sure we're making the decision deliberately.

@fantasai makes the argument (in person) that a run-in merging into a paragraph should pick up the paragraph's text-decoration. That would imply that it propagates thru the box-tree.  Any counter-arguments to this?

**Comment by rune-opera** [comment]
I don't remember what I thought when I wrote that comment, but I probably had https://crbug.com/553174 in mind, which isn't about display:contents but decoration propagation and anonymous boxes.

**Comment by Loirooriol** [comment]
I think I have a counter-argument which suggests that it propagates thru the element-tree.

When an inline element contains a block-level element, the block splits the inline. So the block box ends up outside the two inline box fragments. But decoration in the inline is propagated to the block.

From https://drafts.csswg.org/css-text-decor-3/#line-decoration,

> The decoration is then further propagated to any in-flow block-level boxes that split the inline (see [CSS2.1 section 9.2.1.1](https://www.w3.org/TR/CSS21/visuren.html#anonymous-block-level))

**Comment by tabatkins** [comment]
While that is a reasonable tick in the "element tree" column, there's so many aspects of the propagation that only work in the box tree that I think it's best served by just being an explicit call-out exception in how it box-tree propagates.

@rune-opera Yup, that bug makes it pretty clear that propagation needs to be a box-tree concept, so that fixup can interrupt propagation properly.

Okay, so I think we can close this issue with the conclusion that decorations definitely propagate thru the box tree, and thus the interaction of decorations and display:contents is already well-defined. (In particular, in the OP's example, no decoration should be applied - the `div` doesn't generate a box, so no decoration is ever established on a box.)

This work for everyone?

(Separately, @fantasai and I are now looking more closely at the propagation text, and realizing that the "applied to" paragraph is woefully underspecified.)

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/a9a8bdda32c4d22a2cbc98d6c3724b72f651b6b3
