### ISSUE TITLE
[css-grid] Stretching tracks fails to feed back into sizing algorithm

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1150]
Continuing from https://github.com/w3c/csswg-drafts/issues/1117 examples 3/4/7/8...

> ```
><div style="display: grid; width: 200px;">
>  <img style="width: 100%;" src="http://placehold.it/50x50">
> </div>
>```
> 
> Here to resolve the size of the auto column, we check our children.
> auto is somehow equivalent to minmax(auto, max-content).
> The image has width: 100%; which cannot be resolved as the column has auto size, so for the minimum track size we consider 0px. And we use 50px, the content size of the image as maximum track size. And for the row, we use 50px too (the content size of the image).
> Then the column size is affected by the default justify-content: stretch; which makes the auto column to grow up to 200px. The image is sized against that size of the column, so it ends up being 200x200. However the row is still 50px.

The row here being 50px is not very helpful. It should respond to the stretching of the track.

The responsible spec prose is in https://drafts.csswg.org/css-grid/#algo-overview where `stretch` is processed at the end of the grid sizing algorithm. It should instead be integrated as a final step of track sizing, after fr sizing, in order to be looped into later track-sizing passes.

**Comment by mrego** [comment]
I'm not sure if this will be possible without introducing other issues. For example in the case of orthogonal flows.

Let's try to illustrate that with the following example:
```html
  <div style="display: grid; with: 500px; grid: 250px / auto auto; border: magenta solid thick; font: 100px/1 Ahem;">
    <div style="background: cyan; writing-mode: vertical-lr;">XX X X</div>
    <div style="background: yellow; writing-mode: vertical-lr;">X</div>
  </div>
```

With the current spec `stretch` is done at the end of the grid track sizing algorithm. So this case works like:

1. On the 1st pass for the columns, the width is calculated as 100px for both columns (the items are vertical).
2. The pass for rows it's straight forward, as the row has a fixed size of 250px.
3. Then the `min-content` contribution of the 1st item has changed due to the row size, so we need to do a 2nd pass. On the 2nd pass for the columns, the width is calculated as 300px for the 1st column and 100px for the 2nd one.
4. Again the rows pass is simple as it's a fixed size.
5. Then we do `stretch` so the 1st column becomes 350px and the 2nd column 150px.

![Current behavior with stretch after tracks sizing](https://cloud.githubusercontent.com/assets/11602/24602373/ceed5680-185c-11e7-966a-93489266f332.png)

However, with the new proposal I believe this will end up in a worse result:

1. The 1st pass for columns is the same. 100px width for both.
2. But then we do `stretch`, so each column becomes 250px.
3. Then the pass for rows is again simple as it has a fixed size of 250px.
4. As the `min-content` contribution of the first item has changed again we need a new pass. On the 2nd pass for columns the 1st column has a width of 300px, and the 2nd one keeps its 250px width (the item was already sized  using the 250px of that column after the `stretch`. And here's the problem we'll have overflow on the grid container, because of the `stretch` done in step 2.

![New behavior with stretch inside track sizing](https://cloud.githubusercontent.com/assets/11602/24602620/e16451b4-185d-11e7-9e5d-10db7124d7b2.png)

As you can see in the picture, in the last case we'll be overflowing the grid container because of `stretch`, which feels really wrong as `stretch` should use the available space not more.

Last, I'm not sure if the use case is important enough to introduce changes on the track sizing algorithm at this stage. If you're using percentages on items against indefinite track sizes, I guess that having weird results in some cases can be somehow expected.

**Comment by fantasai** [comment]
Fixed max track sizes in the row axis are assumed at the beginning of the first column sizing pass, so the second interpretation can't happen in any case.  Note the second paragraph:
  
  > First, the track sizing algorithm is used to resolve the sizes of the grid columns.
  > 
  > If calculating the layout of a grid item in this step depends on the available space in the block axis, assume the available space that it would have if any row with a definite max track sizing function had that size and all other rows were infinite.

A case where we could get this result would be if the grid container itself had a fixed height.

A second comment is, if we're recalculating the column sizes, shouldn't the extra space from stretching be re-calculated? In which case we should still get the first result.

**Comment by fantasai** [comment]
Edits checked in. @mrego, please let us know if anything doesn't seem right to you?

**Comment by mrego** [comment]
> A case where we could get this result would be if the grid container itself had a fixed height.

Yep, you're right that I missed the part of the algorithm that explains that we'll be using the fixed max track size, so that case is not an issue.

Also if we go for the case where the row is `auto` but the grid container has `height: 250px` the issue is not present either, as due to the orthogonal item we do a 2nd pass and everything works as expected.

I've been doing some experiments and it seems that it works as expected and I didn't find any case that breaks due to this. Of course this need more testing but it seems a good approach.
It's always scary to touch the track sizing algorithm, but let's hope everything goes right. :smile: 

Regarding the prose, it seems there are 2 verbs together in:
> This step **sizes expands** tracks

**Comment by mrego** [comment]
JFTR, this seems to have caused a new issue #1866.
