### ISSUE TITLE
[css-grid] syntax errors in examples

### ISSUE THREAD

**Issue by phax** [w3c/csswg-drafts#1166]
Spec version: hhttps://www.w3.org/TR/2017/CR-css-grid-1-20170209/

Example 1 is missing one closing bracket (2. bullet point, at `@media print {`)

Example 2 uses the `→` character - what's the purpose?

Example 31 is missing the closing comment after ` Equivalent to grid-area: 2 / 3;`

Example 43 uses `…` instead of CSS comment

Thanks and keep up the good work!

**Comment by SelenIT** [comment]
I suppose it's usually better to link to the [current Editor's draft](https://drafts.csswg.org/css-grid/) then to the published snapshot, since the spec changes constanly and even the numbering of the examples is now different (e.g. the old Example 1 is now Example 3). But at least some of the errors you mentioned are still in place.

In the example 43 (Example 41 in the current ED), I guess the point of these `…` was not to replace CSS comments, but to mark that there is some CSS code was skipped, something like "replace this with the CSS code that creates a 4-column / 3-row grid container". Have you any ideas how this can be expressed more clearly, other than to place the actual code instead?

**Comment by phax** [comment]
I personally would simple change `… 4-column / 3-row grid container …` to `/* … 4-column / 3-row grid container … */`

The intention of writing this issue was basically that all stuff from the examples that looks like code can be copy-pasted  into a real CSS. That's all. I personally use the code as examples for my CSS parser to see that he gets everything right.

**Comment by SelenIT** [comment]
If the goal is to enable copy-paste the examples for testing, the actual code to create such grid container (e.g. `grid-template-columns: repeat(4, 1fr); grid-template-rows: repeat(3, 1fr);`) needs to be added after (or instead of) the comment. Wouldn't it make the example too verbose?

**Comment by phax** [comment]
I personally don't think so - there are so many specs out there that it is hard to read all of them in depth - therefore having working examples as a basis would imho be a good idea.
If you choose not to - I also understand your reasons....

**Comment by mrego** [comment]
I agree it'd be nice to fix the examples, so just in case people copy&paste them we avoid weird confusions.

**Comment by mrego** [comment]
This should be fixed now by #1181.
