### ISSUE TITLE
[css-text-3] word-break: break-all doesn't break before sentence-ending punctuation if UAX #14 is used

### ISSUE THREAD

**Issue by littledan** [w3c/csswg-drafts#1171]
[word-break: break-all](https://drafts.csswg.org/css-text-3/#valdef-word-break-break-all) is specified as:

> Breaking is allowed within “words”: in addition to normal soft wrap opportunities: specifically, any typographic character units resolving to the NU (“numeric”), AL (“alphabetic”), or SA (“Southeast Asian”) line breaking classes \[UAX14] are instead treated as ID (“ideographic characters”) for the purpose of line-breaking. Hyphenation is not applied. This option is used mostly in a context where the text consists predominantly of CJK characters with only short non-CJK excerpts, and it is desired that the text be better distributed on each line.

For layout implementations based on UAX 14, this tailoring doesn't affect code points like "." (FULL STOP), which is categorized as IS. In UAX 14,

> When not used in a numeric context, infix separators are sentence-ending punctuation. Therefore they always prevent breaks before.

This is codified in later text, where LB13 specifies not breaking before IS, and breaking around ideographs is specified by LB31 (break everywhere else), which is at a lower precedence.

The result seems a little counter-intuitive. I would've expected `word-break: break-all` to break in the middle of a long string of `.`, for example, but it seems like it is specified to not do this. Was this the intended behavior?

Dumb, higher-level question: why doesn't `word-break: break-all` break at all grapheme boundaries?

cc @frivoal

**Comment by kojiishi** [comment]
> higher-level question: why doesn't word-break: break-all break at all grapheme boundaries?

Because this value was designed for a use case in East Asia to break non-East Asian (e.g., Latin) words at every character boundary, but then many non-East Asian authors found it's useful for other purposes. The naming was unfortunate. You might also found that this value is not interoperable, which is also unfortunate.

We could add a new value if implementers agree to implement. Could you tell us your use case? In what case you want to break between two FULL STOPs, and isn't it sufficed by `break-word` instead?

**Comment by littledan** [comment]
@kojiishi Just curious, do East Asian use cases not want to break between consecutive `.` characters? What's `break-word`?

**Comment by frivoal** [comment]
> Just curious, do East Asian use cases not want to break between consecutive . characters? 

It depends why you have consecutive . characters. I would guess that the most common one is using three of them (...) instead of the ellipsis character (… U+2026). In that case, you do not want a break between the characters.
So you get
```
|どうでしょ   |
|う...      |
```
and not
```
|どうでしょう.|
|..         |
```
or
```
|どうでしょう.|..
```

> What's `break-word`?

[`overflow-wrap: break-word`](https://drafts.csswg.org/css-text-3/#overflow-wrap-property)
Makes it so that there can be linebreaks anywhere, including between a sequence of "." **if things would otherwise overflow**.

That last part means it is probably not what you're after, because what it will do is:
```
|foo bar     |
|baz.........|
|.......     |
```
it doesn't need to break between the periods to prevent the first line from overflowing, as breaking between baz works as well. It does need to break between the periods on the second line to prevent overflowing, so it does. If that's what you want, `overflow-wrap: break-word`

If what you want is this
```
|foo bar baz.|
|............|
|...         |
```
Then I think the only solution that matches the various specs is to put `<wbr>` between the periods.

**Comment by karlrim** [comment]
Sometimes people just type a few periods like.... um.... 
In my case I'm writing a text editor with a fixed layout and number of max characters, like a 60x15 grid of characters.  We have business reasons for this.  In any case when the text wraps unexpectedly, it throws off our layout and simply looks bad.  Adding <wbr> between the periods as well as any other punctuation that might cause this wrapping is doable but a pain to implement.

In other browsers like FireFox, the breaking on the periods works.  It's hard for me to imagine why anyone would WANT the break to occur between the last two letters instead of the periods.
If that's the issue is it possible to introduce some new break setting to insure the break occurs at the last character no matter what they are so as not to effect the existing break-all behavior?

**Comment by kojiishi** [comment]
> It's hard for me to imagine why anyone would WANT the break to occur between the last two letters instead of the periods.

That's what some writing systems want, I understand it's unlikely for Latin writing systems though.

I'm fine to add a new value, like `break-any` if desired. What to do with spaces might be needed to discuss, and maybe controversial. Do you want, when a space appear beyond the end of line, the space appear at the beginning of the next line? That's what most terminal programs do, but text editors seem to vary.

Note, [this test page](http://kojiishi.github.io/line-break-matrix/?show=edge-break-all&compare=chrome-break-all) tells which combinations of characters can prevent breaks (though there's a bit more complex logic is performed than the combination of two adjacent characters.)

**Comment by kojiishi** [comment]
|Value|When|Break At|Preferred Width|
|------|----|-------|-------|
|word-break: break-all|Anytime|Except certain punctuation|Same as line break|
|word-break: break-any|Anytime|Anywhere|Same as line break|
|word-break: break-word|If no other break opportunities|Anywhere|Same as line break|
|overflow-wrap: break-word|If no other break opportunities|Anywhere|Compute using normal break|

So maybe the space behavior should match to the one of `break-word`.

**Comment by frivoal** [comment]
@kojiishi Do you know of any place where `work-break: break-word` is defined? I know it exists in some implementations, but it is non standard and I don't understand it well. (Also, I thought the implementations where it exists where trying to remove it. How's that going?)

Also, I wonder what this proposed `break-any` is supposed to do with `&nbsp;`, 'WORD JOINER' (U+2060), etc. If we can all agree that it should break everything all the time, then the value is probably justified. If the answer ends up being "it depends", maybe we need a different custom control, rather than an ever expanding list of `break-sometimes`, `break-often`, `break-usually`… keywords

**Comment by kojiishi** [comment]
>  Do you know of any place where work-break: break-word is defined?

IIRC we resolved to add, but the spec want updated yet, sorry, my bad.

We tried to remove, but sites did not agree due to different behavior on preferred width.

**Comment by kojiishi** [comment]
> I wonder what this proposed break-any is supposed to do with...

I think it's best to make it the same as break-word, making "when" is the only difference.

If more controls are needed, we can extend further, but that should affect break-word too I think.

**Comment by kojiishi** [comment]
There was a suggestion to add the new value to `line-break` property instead, so update the summary table.

|Value|When|Break At|Preferred Width|
|------|----|-------|-------|
|New desired behavior|Anytime|Anywhere|Same as line break|
|[line-break: auto/normal/strict/loose](https://drafts.csswg.org/css-text-3/#line-break-property)|Anytime|Language dependent[1]|Same as line break|
|word-break: [break-all](https://drafts.csswg.org/css-text-3/#valdef-word-break-break-all)|Anytime|Except certain punctuation|Same as line break|
|word-break: break-word[2]|Only if no other break opportunities|Anywhere|Same as line break|
|word-wrap/overflow-wrap: [break-word](https://drafts.csswg.org/css-text-3/#valdef-overflow-wrap-break-word)|Only if no other break opportunities|Anywhere|Compute using normal break|

[1] Controls line break before/after East Asian letters, punctuation, symbols, and some common punctuation/symbols. ICU supported the idea, [currently supports variants for Chinese, Japanese, and Finnish](http://cldr.unicode.org/development/development-process/design-proposals/specifying-text-break-variants-in-locale-ids#TOC-F1.-keyword--lb-).
[2] Resolved to add (IIRC) but the spec not updated yet.

**Comment by frivoal** [comment]
Actually, I think there is another solution to this problem, which does not need anything new to be added to the spec.
```
white-space: pre;
overflow-wrap: break-word;
```
or depending on how you feel about breaks in consecutive runs of spaces maybe
```
white-space: pre;
overflow-wrap: break-word break-spaces;
```
That way, the fact that `overflow-wrap:break-word` only applies if there's no other break point is countered by the fact that `white-space:pre` has cancelled other break points.

So you would get
```
|foo bar baz.|
|............|
|...         |
```

@littledan, would this solve your problem, or does it have undesirable side effects?

**Comment by karlrim** [comment]
@frivoal , I tried those settings however it doesn't cause the line to wrap.  So I see this:

<pre>
|foo bar baz.|......
|            |
|            |
</pre>

**Comment by frivoal** [comment]
Strange. It does work in Safari, but not in other browsers. Safari does appear to be violating the spec, since `overflow-wrap` "only has an effect when white-space allows wrapping", but it seems to me that that is a more useful behavior, and since safari is shipping it, that's evidence that it is web compatible.

I'd love to have @fantasai 's take on this.

**Comment by karlrim** [comment]
Well Firefox just wraps the characters regardless if it's punctuation or not.  Every browser seems to violating the spec slightly. :-)

**Comment by frivoal** [comment]
@karlrim Yes, there isn't full interop in this area. Which means its a good opportunity to figure out what behavior is desirable and make sure the spec says that, because once browsers will have converged, changing things will be much harder.

**Comment by frivoal** [comment]
A leftover from the discussion at the F2F is that we still need to determine if authors will need to write `word-break: break-all; line-break: break-all;` or just `line-break: break-all` to get the effect discussed in this issue, which is to allow breaks absolutely anywhere.

The former would be needed if `line-break: break-all` only allows for breaks anywhere around punctuation, and we still need to apply `word-break: break-all` to allow for breaks anywhere within words, and the later would be sufficient if `line-break: break-all` on its own did both.

@r12a: To answer that, we would need your input and feedback from the i18n group to know if there are languages for which it would be desirable to control these separately. Specifically, is it ever useful to allow line breaks anywhere around punctuation while disallowing them within words?

**Comment by frivoal** [comment]
> RESOLVED: put an issue in the spec for overflow: wrap to apply regardless of whitespace

Added a commit (fa0fb3c) doing that. Editors, feel free to be angry at me if you think I stepped on your toes.

**Comment by frivoal** [comment]
> RESOLVED: add line-break: break-all to the spec

Created the #1438 pull request to do that. We had not decided if it should on its own trigger the line breaking style of terminals, or if it would need to be used together with `word-break: break-all`. Since implementors indicated that the later would be harder, and no use case has been brought forward to support the ability to break anywhere around punctuation but not within words, I've specified it so that `line-break:break-all` can work on its own.

**Comment by frivoal** [comment]
Since there are two possible ways to resolve this, and I've made a PR based on one of the 2 ways, I'd like to see if we can get a resolution approving that approach, so agenda+ing.

**Comment by fantasai** [comment]
I asked at the last i18n telecon if they knew of a case which would relax kinsoku but keep inter-letter restrictions, and they said they hadn't heard of such a thing. So I think we're okay to make break-all affect all characters.

**Comment by fantasai** [comment]
Ok, I reviewed the changes... the interaction of this directive and the mandatory glue characters (like nbsp) needs to be clearer.

**Comment by frivoal** [comment]
@fantasai I've added some extra wording to clarify that interaction. Is this clear enough?

**Comment by fantasai** [comment]
CSSWG resolved to add this functionality as `line-break: anywhere`.

**Comment by javifernandez** [comment]
FTR, I've just started to implement this feature for Chrome (https://crbug.com/720205)

**Comment by javifernandez** [comment]
> FTR, I've just started to implement this feature for Chrome (https://crbug.com/720205)

The feature landed in Chrome and will be shipped behind a flag in M76.

Additionally, it landed in WebKit trunk as well (https://trac.webkit.org/changeset/245275). It isn't available yet in any Technology Preview, though.

Finally, it seems than Firefox has started the implementation of the line-break:anywhere feature too, which is really good news (https://bugzilla.mozilla.org/show_bug.cgi?id=1531715)
