### ISSUE TITLE
[css-backgrounds-4] Initial value of 'background-position-y' should be 'top'

### ISSUE THREAD

**Issue by kuoe0** [w3c/csswg-drafts#1208]
I found the initial value of `background-position-y` defined in spec is wrong. I think it should be `top`.

See: https://drafts.csswg.org/css-backgrounds-4/#background-position-longhands

**Comment by LeaVerou** [comment]
Yup, that's certainly a spec bug. For those wondering: The current value listed is ...`left` 😂

**Comment by cdoublev** [comment]
This has been fixed in https://github.com/w3c/csswg-drafts/commit/eca3884223a26ad5e1db9bac09f3d50f3a20780d therefore this issue can be closed, but I would like to take this opportunity to ask why the initial `background-position-inline|block` value is not `start` (ie. the position where you start reading) instead of `not applicable (initial value comes from physical property)`? I mean: did you (the CSSWG) already discussed/resolved if the initial flow-relative background position properties should bind to their physical counterparts?

**Comment by SebastianZ** [comment]
You're right. All other specs that define logical properties also specify their initial values. So I went ahead and changed it to `0%` in https://github.com/w3c/csswg-drafts/commit/39e76125a1cc24dc0f247581d6d5bc54f891ab55. I chose 0% rather than `start` because all other logical properties also use the initial value of their physical counterparts.

Sebastian

**Comment by cdoublev** [comment]
Thanks. Indeed, resolving the writing mode at specified value time seemed problematic to me. 

Other logical properties seem to be mostly defining distance values, not a position like `background-position`, `mask-position`, or `scroll-start`. The latter has [`scroll-start-block|inline`](https://drafts.csswg.org/css-scroll-snap-2/#propdef-scroll-start-inline) defined with `auto` as its initial value but there is no associated definition. Shorthand encompassing both flow-relative and physical properties should map to their physical sub-properties after their flow-relative sub-properties, therefore the initial value of the latter will not affect the formers. But anyway, `0%` is fine.
