### ISSUE TITLE
[selectors] :read-only and :read-write

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#127]
Copying this over from http://lists.w3.org/Archives/Public/www-style/2016Apr/0294.html
(Disclaimer: My opinions are my own, not my employer's.)

[`:read-only` is currently spec'd as](https://html.spec.whatwg.org/multipage/scripting.html#selector-read-only) (basically) `:not(:read-write)`, and `:read-write` is currently spec'd as matching:
- `<input>` elements to which the `readonly` attribute applies, and that are mutable (i.e. that do not have the `readonly` attribute specified and that are not `disabled`)
- `<textarea>` elements that do not have a `readonly` attribute, and that are not `disabled`
- elements that are editing hosts or editable and are neither `<input>` elements nor `<textarea>` elements (i.e. contentEditable / designMode)

(A) This leads to an anomaly: Some inputs that the user can interact with to alter their "value" (which most folks would thus casually deem "writable") match `:read-only` instead of `:read-write`.
Namely, `<input>`s of type `range`, `color`, `checkbox`, `radio`, and `file` are `:read-only` since the `readonly` attribute doesn't apply to them.
(One can argue that this is a bug in HTML and that HTML should just allow the `readonly` attribute on these input types.)

(B) There's a question of whether the buttonish `<input>`s (types: `image`, `submit`, `reset`, `button`) should be `:read-only` or `:read-write`. Arguably, they should be `:read-only` since the user cannot normally directly modify their values. They are interactive insofar as they're clickable, but they aren't editable. However, Chrome and Edge currently have them matching `:read-write`, which doesn't conform with the current spec.

(C) There's a question of whether `<input type="hidden">` should match `:read-only` or `:read-write` or neither. Per spec, it currently matches `:read-only`. But in Chrome and Edge, it currently matches `:read-write`.

(D) I think there's some question as to how useful the `contentEditable` case is, particularly when it's lumped together with the form input cases.

---

Current state of affairs (FWICT):
- WebKit matches the current spec and [doesn't want to change their implementation until the spec itself is changed.](https://github.com/w3c/web-platform-tests/pull/2843#issuecomment-211687381)
- Blink and Edge both suffer from 2 bugs relative to the current spec:
  - `:read-only` doesn't match `<input>`s to which the `readonly` attribute does not apply
    - https://bugs.chromium.org/p/chromium/issues/detail?id=604154
    - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7229941/
      - As stated in a comment and on the www-style thread, the Edge folks (understandably) don't think the spec's current behavior here makes sense.
  - `:read-write` shouldn't match `<input disabled>` or `<textarea disabled>`
    - https://bugs.chromium.org/p/chromium/issues/detail?id=604117
    - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7226201/
    - (Gecko's prefixed implementation also suffers from this bug)
- Gecko currently only has a prefixed implementation. Relative to the current spec, it has the one aforementioned bug.
  - Feature request / unprefixing bug: https://bugzilla.mozilla.org/show_bug.cgi?id=312971

---

And in light of the lack of compatibility and questions about the utility of these pseudos as-then-specd, it looks like Hixie asked the spec editors ~3 years ago in https://www.w3.org/Bugs/Public/show_bug.cgi?id=17812#c24 whether `:read-only` & `:read-write` could be removed from the spec altogether, but he never got a reply.

---

@zcorpan @FremyCompany @makotokato @BenjaminPoulain @tabatkins @fantasai

**Comment by tabatkins** [comment]
I feel exactly as @fantasai does:

> If it's Web-compatible and no-one else feels strongly about keeping it,
> I don't mind. But I don't have that data.

**Comment by cvrebert** [comment]
Any opinion on the semantics in the event that removing it isn't web-compatible?

**Comment by tabatkins** [comment]
I'd prefer to define them *properly*, to be dependent on a host-language-defined editability boolean; I highly doubt that much content is purposely relying on :read-write matching type=text but not type=color.  And if possible, define :read-only to also depend on that boolean, so elements that don't have an editability concept at all don't match either.

**Comment by cvrebert** [comment]
So, any vendor(s) want to add telemetry to see whether these can be removed?

Complete shot in the dark: @foolip ?

**Comment by zcorpan** [comment]
```
SELECT * FROM (
SELECT page, url, REGEXP_EXTRACT(LOWER(body), r'((?:.){50}:read-(?:only|write)\s*\{(?:.){50})') AS match
FROM [httparchive:har.2016_05_15_chrome_requests_bodies]
) WHERE match != "null"
```

326 resources match (out of 496,446 pages).

[results-20160610-100007.csv.zip](https://github.com/w3c/csswg-drafts/files/308778/results-20160610-100007.csv.zip)

**Comment by cvrebert** [comment]
Some observations from skimming the CSV:
* `:read-write` only occurs 1 time. Perhaps someone could run another query, limited to just `:read-write`, to see how (un)popular it is specifically?
* 58 are http://carrotquest.io and 30 are http://www.drift.com , both of which are Olark-ish live text chat widgets
* 20 are http://tagboard.com widgets, where the selector suggests it's being used as part of an account settings screen (`.dashboard .content .account-tab#account-settings input:read-only`)
* 17 are websites using the https://www.muicss.com CSS framework

**Comment by tkent-google** [comment]
FYI.
Google Chrome 52 has counters for :read-only and :read-write.

- :read-only is used in 0.006% of page views: https://www.chromestatus.com/metrics/feature/timeline/popularity/1377
- :read-write is used in 0.004% of page views: https://www.chromestatus.com/metrics/feature/timeline/popularity/1378

Usually Chromium project assumes features with such values are removable.

**Comment by fantasai** [comment]
Thanks for the feedback and data. Someone please Agenda+? :)

**Comment by foolip** [comment]
> So, any vendor(s) want to add telemetry to see whether these can be removed?
Complete shot in the dark: @foolip ?

Sorry, I just fixed my email filters to make direct mentions like this stand out from all other GitHub mail. Glad to see my services weren't needed after all :)

**Comment by sab39** [comment]
From my (admittedly HTML-centric) perspective as a web developer using CSS, there's a definite use case for these pseudo-classes, but changing their meaning slightly would make them far more useful.

I see them as useful to allow a selector to [match all text entry elements in HTML](http://stackoverflow.com/questions/16333957/css-selector-for-general-textboxes), which is otherwise not possible. The linked article can only suggest variations on this fundamentally flawed approach:

```css
input:not([type]), /* all non-declared types */
input[size], /* text, search, tel, url email, or password */
input[type^=date], /* date, datetime, datetime-local */
input[type=color],
input[type=week],
input[type=month],
input[type=time],
input[type=number],
input[type=range] {
   /* styles */
}
```

This approach is problematic in many ways:

- It's unnecessarily clumsy and verbose.
- It presumes that the `size` attribute will be specified on all text inputs, which may not be the case.
- It is fundamentally tied to a specific user-agent - in fact, to a specific *version* of a specific user-agent - because user agents are rightly given free rein regarding the UI they present for the different `<input>` types, and do in fact make different choices from vendor to vendor and version to version.
- It cannot account for new `<input>` types that may be added to the HTML specification in the future

As currently specified, the `:read-write` pseudo gets partway to meeting this need, but does not offer a way to match readonly (other than a `[readonly]` attribute selector) or disabled text inputs because `:read-only` is defined too broadly.

I would suggest changing the specification of `:read-only` to match only elements that *could* support `:read-write` but are currently readonly or disabled.

**Comment by tabatkins** [comment]
On Mon, May 1, 2017 at 6:51 AM, Stuart Ballard <notifications@github.com> wrote:
> From my (admittedly HTML-centric) perspective as a web developer using CSS, there's a definite use case for these pseudo-classes, but changing their meaning slightly would make them far more useful.
>
> I see them as useful to allow a selector to match all text entry elements in HTML, which is otherwise not possible. The linked article can only suggest variations on this fundamentally flawed approach:

They don't do that, tho. As the SO answers state, :read-write doesn't
match disabled form controls (tho it does in Chrome, at least), while
it *does* match <textarea>, which isn't what you want.

[snip]
> As currently specified, the :read-write pseudo gets partway to meeting this need, but does not offer a way to match readonly (other than a [readonly] attribute selector) or disabled text inputs because :read-only is defined too broadly.
>
> I would suggest changing the specification of :read-only to match only elements that could support :read-write but are currently readonly or disabled.

Regardless of how we decide this, it won't support your use-case properly.

**Comment by sab39** [comment]
> They don't do that, tho. As the SO answers state, :read-write doesn't match disabled form controls (tho it does in Chrome, at least), while it *does* match <textarea>, which isn't what you want.

Actually I _would_ want it to match `<textarea>`, and anything that's `contenteditable` as well.

> Regardless of how we decide this, it won't support your use-case properly.

Perhaps I'm misunderstanding the discussion here, and if so I apologise. I thought that the issue was that the currently specified behaviour of `:read-only` and `:read-write` is problematic, vague, and doesn't have clear use cases; and that (probably because of these issues) they aren't widely used and maybe aren't worth continuing to support at all.

My suggestion was to _change_ the specified behavior of those selectors to give them a clearer reason for existence, rather than removing them entirely or continuing to support something that's not especially useful or used.

Specifically, my suggestion is to keep the behaviour of `:read-write` essentially unchanged, and define it explicitly as referring to any kind of editable _text entry_ (that is, `<textarea>` and all `<input>` types that render as textboxes, as long as they aren't `readonly` or `disabled`, along with anything `contenteditable`), and change the definition of `:read-only` to mean "editable text entry controls where editing is disabled", so it'd match `<textarea>`s and textbox `<input>`s that are `readonly` or `disabled`.

Is there some reason why such a change can't be considered?

**Comment by MatthewRaymond** [comment]
Well, these pseudo-classes were originally created for [XForms 1.1](https://www.w3.org/TR/xforms/#style):

> Selects any core form control **bound to a node with the model item property readonly** evaluating to true or false (respectively).

So the whole point wasn't that the element was interactive, but that it was bound to a node in the data model that had the property of being read-only. Read-only is a property of the underlying data model, not the control.

In HTML, the control elements have an implicit data model, but nothing has changed. The "readonly" attribute applies only to Web Forms elements. The other elements don't have an implicit data model. Thus, it's my feeling that :read-only should only apply to controls that are specifically set with the"readonly" attribute, and :read-write should match all controls that aren't "readonly". If we need a pseudo-class for editable elements, use something like :editable or :mutable instead of :read-write. We should never have a situation where :read-write is just :not(:read-only) or vice versa.

**Comment by annevk** [comment]
Since OP is about the HTML Standard, why isn't the issue raised against the HTML Standard?

**Comment by emilio** [comment]
Let's dupe this against https://github.com/whatwg/html/issues/3501.

**Comment by shrpne** [comment]
I agree with @MatthewRaymond 
I think it is very unintuitive, that such css
```css
/* both matches <select> */
select:read-only {}
select:not([readonly]) {}

/* both matches <div> */
div:read-only {}
div:not([readonly]) {}
```
will be applied to such html
```html
<div></div>
<select></select>
```
