### ISSUE TITLE
[css-images] Porting gradient midpoints to Level 3

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#1284]
Previous discussion: https://lists.w3.org/Archives/Public/www-style/2017Apr/0059.html

@cabanier said he didn't work on the Blink implementation, in which case there *are* 2 independent implementations, so we need to re-resolve on this.

**Comment by AmeliaBR** [comment]
I think this is awesome. If implementations are independent-but-compatible, getting it into a stable spec is even better.

But... would someone volunteer to add some actual examples to the spec?  Including figures of output for the same gradients with different hints, maybe a comparison of the difference between gradients with hints and gradients with explicit intermediary stops,  like these:

```css
background: linear-gradient(#f00, #f80 30%, #ff0 );
background: linear-gradient(#f00, 30%, #f00 );
```

I honestly had no idea this was so well supported.  Part of the reason is probably a lack of good examples encouraging people to use it.

____________________________

As an aside:

What happens if the same person/team *does* implement a feature in all major rendering engines?  How would you reach the W3C's "two independent implementations" in that case?  Couldn't there be an alternative standard for Rec, like having independent reviews or tests?

This is probably something for the TAG to discuss...

**Comment by tremby** [comment]
> `background: linear-gradient(#f00, 30%, #f00 );`

Just in case anyone is confused looking at this later, as I was today, there's a typo here in that both stops are the same red!
