### ISSUE TITLE
[selectors-4] :nth-child and friends are either underdefined or defined wrong

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1292]
All of these

* https://drafts.csswg.org/selectors/#the-nth-of-type-pseudo
* https://drafts.csswg.org/selectors/#the-nth-last-child-pseudo
* https://drafts.csswg.org/selectors/#the-nth-of-type-pseudo
* https://drafts.csswg.org/selectors/#the-nth-last-of-type-pseudo

have a definition that includes “the An+Bth element” with no details on what that means. This is either wrong (since this is using “the element” singular, where as multiple elements could match) or at least under-defined. A and B are from https://drafts.csswg.org/css-syntax/#anb, but what is n?

This is a regression from Selectors Level 3, which has a precise definition:

https://drafts.csswg.org/selectors-3/#nth-child-pseudo
> The :nth-child(an+b) pseudo-class notation represents an element that has an+b-1 siblings before it in the document tree, for any positive integer or zero value of n, and has a parent element.  

Notable edge cases that should be well-defined include n<0 and A=0.

**Comment by SelenIT** [comment]
Isn't the ['An + B' notation](https://drafts.csswg.org/css-syntax/#anb) described by reference to the CSS Syntax module for all these definitions?

> The An+B notation defines an integer step (A) and offset (B), and represents the An+Bth elements in a list, for every positive integer or zero value of n, with the first element in the list having index 1 (not 0).

The edge cases like A=0 are described in the next (though non-normative)[ section 6.1](https://drafts.csswg.org/css-syntax/#anb-syntax).

**Comment by SimonSapin** [comment]
Ah, I was misled by assuming that “CSS Syntax Module” only described the syntax of An+B. Either way, I think it wouldn’t hurt for Selectors 4 to repeat that.

> The edge cases like A=0 are described in the next (though non-normative) section 6.1.

I think the part you quoted is sufficient. With A=0, An+B simplifies to B regardless of n, and so at most one element (the Bth) is represented.

The A=0 case would only be problematic if division by A was involved in the definition (as it is in my implementation, which therefore requires a code path dedicated to A=0).

**Comment by Loirooriol** [comment]
I think the meaning is understandable, but nitpicking I agree it's not perfect because CSS Syntax says the notation "represents the An+Bth element<b>s</b> in a list", so it's a set of elements, but CSS Selectors says “the An+Bth element”. Instead, in Selectors I would say something like “<b>any one of</b> the An+Bth element<b>s</b>” or maybe “<b>an</b> An+Bth element”.

**Comment by FremyCompany** [comment]
@Loirooriol make a pull request :)

**Comment by Loirooriol** [comment]
More nitpicking, what I said above is something like

    E ∈ subList(A, B, inclusiveSiblings(E) ∩ match(S))

I don't like it much neither, because E is defined as belonging to the sublist, but the sublist depends on E. Not wrong because we know it's a sublist of elements, but I would prefer defining E in its domain and then impose the restriction: (if someone is interested, see [Russell's paradox](https://en.wikipedia.org/wiki/Russell's_paradox))

    E ∈ Elements | E ∈ subList(A, B, inclusiveSiblings(E) ∩ match(S))

In English I would say

> The :nth-child(An+B [of S]?) pseudo-class notation represents an element among its An+Bth inclusive siblings that match the selector list S.

**Comment by tabatkins** [comment]
Okay, I just pushed be7492ce3 which attempts to fix this.

**Comment by SimonSapin** [comment]
Looks good, thanks Tab.

**Comment by Loirooriol** [comment]
There is a repeated sentence. See #1308 and https://github.com/w3c/csswg-drafts/commit/be7492ce3c5a605704d6da2172e8c65e8f14775f#commitcomment-21954890
