### ISSUE TITLE
[css-scroll-snap] Clarifying that CSS Snap Points doesn't dictate any particular input method

### ISSUE THREAD

**Issue by bgirard** [w3c/csswg-drafts#1305]
I’d like to propose a clarification to the CSS Snap Point specification in Section 3:
https://www.w3.org/TR/css-scroll-snap-1/#overview

If we could add the following sentence in the Overview:
“Any input method for scrolling is outside the scope of this specification.”

 I believe this modification is minor and reflects the current intent of the specification. This clarification would help Facebook join the CSSWG. Posting this as a revised CR spec would help Facebook join the CSSWG sooner.

**Comment by fantasai** [comment]
The problem is... your sentence doesn't quite make sense. I could interpret it as saying that "This specification does not define the input methods used for scrolling", which is an obvious statement that's perhaps unnecessary, but could be added. I could also interpret it as saying that "This specification does not apply to scrolling methods that require user input", which defeats the whole point of the spec.

So, I think you need to clarify what you're asking for here. :)

**Comment by bgirard** [comment]
I agree it's not very clear. Your first suggestion covers what I intended to capture.

What about adding a new paragraph at the end of Section 6.1:
This specification only applies to scrolling methods supported by the user agent. It does not require the user agent to support any particular input or scrolling method.

I think either that or your suggestion should be sufficient.

I can send a PR if the edit is appropriate.

**Comment by tabatkins** [comment]
All right, we added your suggested sentence in a note at the end of section 6.1. Let us know if this satisfies your concern!

**Comment by bgirard** [comment]
Looks good. It is possible to get minor edit?
This specification only applies to scrolling methods supported by the user agent, but it does not require the user agent to support any particular input or scrolling method.

Sorry for not spotting it correctly the first time.

**Comment by fantasai** [comment]
I think it was more correct the first time, actually. :)

**Comment by bgirard** [comment]
Hey -- Sorry to push on this but our lawyers are just concerned the grammar is ambiguous and could be confusing here. Any chance we could put this through to make them happy? I think they have a point adding the "but" helps clarify the intent -- "you must implement touch scrolling for all scrolling methods BUT this specification doesn't require you to implement any specific method". Without the conjunction it's unclear the two concepts are related.

**Comment by bgirard** [comment]
@tabatkins Wanted to follow-up since the issue is now marked as closed.

**Comment by tabatkins** [comment]
They're related because they're adjacent sentences in a paragraph containing only them.  There's no way a reasonable person can interpret those as being independent, unrelated statements.  Plus, even if we did assume someone existed in the world who could interpret them in that way, *it means the same thing*.

Lawyers don't matter here - it's an informative note. There is literally no legal connection to this text.

I'm also extremely confused as to how and why lawyers are involved in the first place. This entire thread has had a weird legal subtext running thru it, and we don't understand how any of it is relevant.

**Comment by fantasai** [comment]
@bgirard My problem with the proposed wording change is that “but” is not the correct conjuntion to use here; and therefore as the editor I refuse to make that edit. If you want it all in one sentence, I can use “and”. But, like Tab, I don't think that actually changes the meaning of anything. Also, this spec is not limited to devices with touch interfaces, so your comment doesn't really make sense. If your lawyers are giving you trouble, maybe put them directly in touch with me and we can talk it through? I can send you my direct contact info.

**Comment by bmaurer** [comment]
@fantasai -- hey just wanted to follow up here that I sent you an email from my fb.com email address to your email on fantasai.inkedblade.net/contact. No rush, just wanted to make sure I had the right point of contact for you. feel free to reach out at bmaurer@fb.com and we can talk this through directly

**Comment by bmaurer** [comment]
Thanks @fantasai, we're happy from our side with this change now.
