### ISSUE TITLE
[css-ui-4] Make selection change behavior configurable

### ISSUE THREAD

**Issue by SaschaNaz** [w3c/csswg-drafts#1317]
Following #319.

Problem: MSEdge Insider Preview build recently changed its behavior not to change selection when clicking non-selectable area to match the requirement from #319. This breaks my app behavior which targets Windows 10 store platform.

Background: Web pages by default allows user selection for the whole page area, while desktop apps by default blocks it and wants to control selectable area strictly. This means the whole background of page body is unselectable, and it again means unselecting is hard.

Take a look here (Firefox and Edge is preferred, Chrome has slightly different behavior): http://codepen.io/SaschaNaz/pen/wdeqZX

Imagine users selected their texts to copy and paste, and then wants to unselect. Previously with MSEdge the user can just click anywhere on the page, but now the user has to think carefully to unselect without opening a popup. (The only way on MSEdge is to right-click anywhere)

Since unselecting got hard, I suggest a way to allow previous Chromium behavior, where unselection happened when clicking non-selectable area.

**Comment by frivoal** [comment]
In typical native apps, clicking on UI areas does not deselect any previously selected text. I don't quite see why we need a different behavior here.

Why apply `user-select:none` to areas that have nothing selectable anyway, especially if you're still hoping that a user interacting with that area would affect the selection?

Wouldn't your problem be solved if you applied `user-select:none` less aggressively, and let the whole content area be selectable (instead of just the text parts in the content area), keeping `user-select:none` for tool-bars and other UI centric components?

Besides making deselecting easier, this would have additional benefits. In the example you sent, if an image fails to load and the alt text is shown instead, it would not be selectable. What is to be gained by preventing users from selecting that?

**Comment by SaschaNaz** [comment]
>In typical native apps, clicking on UI areas does not deselect any previously selected text.

I would say "it depends". For example, imagine if you use Facebook app and you somehow want to copy someone's post. The current Facebook app allows user to cleanly select text only inside the post, without copying any UI components. Deselecting works by clicking outside of the post.

![selection2](https://cloud.githubusercontent.com/assets/3396686/25647380/6fcb00aa-2ffc-11e7-8529-a06c0d1de199.gif)

The original discussion was about editor apps and I agree the new behavior is helpful there, but not for all type of apps.

> In the example you sent, if an image fails to load and the alt text is shown instead, it would not be selectable.

Specifically I mentioned Twitter there, you will not expect any images fail to load on Twitter and instead show alternative text.

**Comment by frivoal** [comment]
To me, the behavior you're describing seem achievable by setting `user-select: none` just on the bits of UI that you don't want selected, leaving the empty areas at the initial value, instead of setting `user-select: none` on the root of the page, and setting it back to `auto` on whilte-listed bits of content.

With the current behavior, we can get both cases to work, while if we switched to `user-select: none` being able to cancel the current selection, there would be no way to make parts of the page unable to affect the selection.

**Comment by FremyCompany** [comment]
Allowing selection to start in "empty spaces" on the root of the page mean you cannot prevent selection to span across multiple ```-ms-user-select:element``` elements. That is usually not a behavior apps want to allow. I still have mixed feelings on this one, I think

**Comment by FremyCompany** [comment]
My point is that the advice given when you want app-like selection has always been to set none as the default and override as needed with element for your controls, so that your selection always start inside a contained selection wrapper.

**Comment by frivoal** [comment]
@SaschaNaz The group resolved against your initial suggestion. See the transcript in the comment above for full details. We would appreciate if you could let us if you can live with this decision.

**Comment by FremyCompany** [comment]
I would note on top of what Florian said that it is possible to clear the selection using a script if needed
```
addEventListener('pointerdown', e=>{
  if( isInUserSelectNoneRealm(e.target) ) { // using getComputedStyle(...) to check
    getSelection().empty();
  }
})
```
so if desired this effect can be achieve on the web platform in a cross-browser way already.

**Comment by cvrebert** [comment]
@frivoal 016920866197fe3a8fd0e23ce9d062358fcae49b seems to have a few typos in it:
"accidental[+l+]y", "inter[-e-]acted", "op[+p+]osite"

**Comment by frivoal** [comment]
@cvrebert Thanks. Fixed now.
