### ISSUE TITLE
[css-multicol] allow percentages for `column-gap`

### ISSUE THREAD

**Issue by chharvey** [w3c/csswg-drafts#1321]
Please allow percentage values for `column-gap`. An example use case would be:

```css
.article {
  column-count: 3; /* each 30% */
  column-gap: 5%;
}
```

'Percentages' would be from the calculated width of the containing block.

Links
- https://drafts.csswg.org/css-multicol-1/#column-gap
- https://lists.w3.org/Archives/Public/www-style/2013Feb/0494.html
- https://lists.w3.org/Archives/Public/www-style/2013Feb/0572.html

As I understand it, percentages are not allowed on `column-width` because using `column-count` is preferred for a fluid layout. This makes sense, and I agree, but it sounds like a case of "we're disallowing this feature because it's bad practice." I'm not sure how that fits into CSSWG principles. Furthermore, `column-width` still allows `vw` units, which can be used to achieve (approximately) the same effect as percentages.

**Comment by frivoal** [comment]
We have an [old resolution](https://lists.w3.org/Archives/Public/www-style/2013Feb/0572.html) in favor of allowing percentages for `column-gap`. Which level do we want to put it in? Level 2 because 1 is past that stage, or 1 because the resolution itself it pretty old as well? I am happy to do the edit regardless, but I want to know where the group wants it.
