### ISSUE TITLE
[css-display][css-ruby] Does inlinification really need recursion?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1341]
CSS Display defines [inlinification](https://drafts.csswg.org/css-display-3/#inlinify) as such:

> inlinification [...] sets the box’s outer display type, if it is not none or contents, to [...] inline [...]
>
> If a box with a flow inner display type is inlinified, it recursively inlinifies all of its in-flow children, so that no block-level descendants break up the inline formatting context in which it participates.

I think it makes more sense to transform the `flow` inner display type into `flow-root`. That is, transform `block` to `inline-block`. Then the box will be an [atomic inline](https://drafts.csswg.org/css-display-3/#atomic-inline), and thus block-level descendants won't break up the inline formatting context. Recursive inlinification is not needed. 

This seems what Firefox does for ruby. Chrome and Edge don't inlinify at all. https://jsfiddle.net/d1o5k7Ly/1/

It's worth noting that [CSS Ruby](https://drafts.csswg.org/css-ruby-1/#anon-gen-inlinize) says "directly contained"

> Inlinize block-level boxes: Any in-flow block-level boxes directly contained by a ruby container, ruby base container, ruby annotation container, ruby base box, or ruby annotation box are forced to be inline-level boxes, and their display value computed accordingly.

By the way, are inlinization and inlinification synonyms?

**Comment by tabatkins** [comment]
You're correct the making them flow-roots prevents the need for recursion, but that ignores that *now you have a flow-root*. That's not a meaningless change!  In particular, it means they won't line-break anymore.

> It's worth noting that CSS Ruby says "directly contained"

Which is unfortunate, and should be fixed.  Ruby's last update in the relevant area was long before we defined inlinification (but fantasai and I definitely defined it *for the purpose of* Ruby).

**Comment by Loirooriol** [comment]
Not a meaningless change, but converting whole subtrees of blocks to inlines seems also very drastic. Well, I don't really care about recursion, but then please update the ruby spec, otherwise it's confusing.

**Comment by tabatkins** [comment]
Yup. Pinging @fantasai for verification that Ruby needs updating.

**Comment by upsuper** [comment]
Ruby boxes are supposed to be inline box, and they should share all the characteristic of inline box like kerning.

Recursion isn't really a big issue, because in general content in ruby is expected to be small and shallow, and actually block-in-ruby should be considered a wrong use, which means handling it should not affect normal usecases, and it should be as easy as possible for impl.

**Comment by fantasai** [comment]
So, there are three definitions being considered here:
  - Display's definition that blocks are recursively turned into inline boxes
  - Ruby's definition that blocks are turned into inline-blocks.

I think either definition is reasonable. Agree with Tab that we should be consistent across ruby and run-ins, but I don't have a compelling reason to prefer one or the other.

**Comment by tabatkins** [comment]
So the core point of inlinification is to ensure that nothing can break the inline context it's working in.  "block flow-root" elements become "inline flow-root" ("inline-block"), which is fine - they're atomic inlines.  But "block flow" naively becomes "inline flow", which still allows descendant blocks to bubble up a break.

The current text solves this by recursing, so that a "block flow" becomes "inline flow", then its children inlinify as well, ensuring there's no visible block descendants.

Instead turning "block flow" into "inline flow-root" also solves this, by hiding any descendant blocks.

Either solution solves the problem.  Are there any good use-cases suggesting that we go for one vs the other?

**Comment by tabatkins** [comment]
@fantasai points out a strong reason not to use "inline flow-root" - it means that any inline elements inside a ruby will become inline-blocks, unnecessarily preventing linebreaking from occurring on the children, and disrupting inline layout in general (breaks shaping and justification across boundaries, etc).

**Comment by fantasai** [comment]
Okay, so afaict both the Ruby and Display definitions are pretty broken atm. :) Ruby fails to recurse into inlines, which it needs to do in order to suppress line breaks. The Display module turns 'display: block' into 'display: inline' and then recurses into it, which is also problematic because blocks should stay together as a unit.

**Comment by fantasai** [comment]
Cross-linked [Ruby](https://drafts.csswg.org/css-ruby/#anon-gen-inlinize) to the css-display 'inlinification' definition.

Also, to answer the original question, yes, it needs recursion, because inline boxes should remain untouched by this process.

**Comment by fantasai** [comment]
Since inlinification doesn't affect layout-internal display types, I also added https://github.com/w3c/csswg-drafts/commit/ec80a76213021f554ec721f671d32076a60a6b5c to address misparented internal table boxes inside ruby. (CSS Tables L3 already recognizes ruby in determining anonymous table box types.)
