### ISSUE TITLE
[css-counter-styles-3] Why was list-style: upper-greek removed?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#135]
*On Mon, May 23, 2016 at 12:38 PM, Athanasios Viennas <aviennas@vtopia.gr> wrote:*
> Dear folks at w3c,
> 
> I wonder what is the purpose of "removing" upper-greek value from list-style-type property (https://www.w3.org/wiki/CSS/Properties/list-style-type) between CSS1 and the modern versions. I honestly wonder who decided this and on what requirement, have you estimated the impact on the WWW as a community and the practical disabilities it has caused, and how about the trend of web standards directing towards multilingualism.
> 
> Can you please provide any pointers on the related minutes of the meetings supporting the given decision.

**Comment by dauwhe** [comment]
It's surprisingly hard to figure out the history of this!

Note that `list-style-type: upper-greek` was not in CSS 1, at least not the final [REC](http://www.w3.org/TR/REC-CSS1-961217.html#list-style-type). 

Values were: `disc | circle | square | decimal | lower-roman | upper-roman | lower-alpha | upper-alpha | none`

I found an issue in an [old WD](http://www.w3.org/TR/2011/WD-css3-lists-20110524/) of CSS Lists and Counters Level 3:

> According to a native Greek speaker, the lower-greek and upper-greek styles aren't actually used. I've removed upper-greek for now, but kept lower-greek because CSS2.1 included the keyword. Do these have actual use-cases?

There's also an old thread on www-style, starting [here](https://lists.w3.org/Archives/Public/www-style/2002Nov/0035.html). There seems to be lots of discussion on whether upper-greek is a valid and useful numbering scheme. For [example](https://lists.w3.org/Archives/Public/www-style/2002Dec/0034.html), 

 > The numbering schemes named lower-greek & upper-greek in the draft are not used (and not even useful) in modern greek. Please, do not invent them for us!

So it sounds like we never reached consensus on what to do. Would [counter styles](https://drafts.csswg.org/css-counter-styles-3/#intro) address your use cases?

**Comment by tabatkins** [comment]
Yup, feedback from authors (thanks for hunting it down, @dauwhe, I got distracted doing other things) is what led us to remove upper-greek as not useful.  As with many of the ancient languages, there appear to be several valid ways to number things using the letters; the spec documents one way that matches what all browsers do.

You can fill in all the rest by using `@counter-style` yourself.

**Comment by aviennas** [comment]
My warmest greetings to the clan of w3c officers and the beloved commoners consuming time of their lives in making the web (presumably) a better place; talking of which I have to strongly disagree with our anonymous Greek native speaker who unofficially consulted the group more or less, that upper case Greek text is pretty much gone in modern everyday world. 

I have to say that is totally wrong and besides my own personal experience being a native speaker and a veteran software developer who has worked in multiple and complex projects on the educational, banking, defense, legal and lately medical and estate sectors (I can bring more expert advice from domain experts of those areas too).

Greek text exists in millions of web pages inside portals, intranets, b2c government web apps, dms's, cms's, offline presentation apps and everyday legal documents and contracts flowing all over the place. I won't mention the amount of web documents circulating in the Greek language version inside the europa network because I will receive the argument that this is a dead piece of documentation, it turns out that only the author reads it.  

I realized the lack of the given property value while authoring a set of legal content web pages provided by my customer's legal advisor. The funniest thing on this issue would not be the act of including upper-greek as just another snobbish value-set but rather the act of removing it based on an anonymous testimony of someone who essentially maybe the type of person using 100 words to communicate and does no bother knowing how to type an accented Greek character as he/she uses Greeklish in everyday life. 

Two more groups directly affected by such change on the inverse scale of it's littleness are those who have Greek ancient and modern literature as their field of study (and not as just a medium to communicate) i.e. classic historians, archaeologists, literature and ecclesiastical academics and teachers. They professionally exist to teach or research how the Greek lang is written and they are supposed to review student essays structured using the "old-fashioned" (no matter what - still normal to them) way to do just that.

**Comment by tabatkins** [comment]
> based on an anonymous testimony of someone who essentially maybe the type of person using 100 words to communicate and does no bother knowing how to type an accented Greek character as he/she uses Greeklish in everyday life.

Insults are not appropriate in this forum. You will keep your tone civil or not discuss things at all.

---

There are *many* world languages not supported directly by this spec; the group made an intentional choice to only mandate support for the styles that were originally defined in CSS 2.1 (of which `lower-greek` was one, implemented as a particular variant of the greek lowercase alphabet), and a few other styles that can't be done properly by the extension mechanism.

*You* can use that extension mechanism - the `@counter-style` rule defined by the spec - to define your own counter style matching whatever language conventions you want. The Internationalization WG maintains a document of example `@counter-style` rules for many world languages at <http://w3c.github.io/predefined-counter-styles/>, including [several modern Greek styles](http://w3c.github.io/predefined-counter-styles/#greek-styles), so you might not even have to figure out how to write one on your own, just copy-paste from that document.

Note that currently `@counter-style` is only implemented by Firefox. Make sure to use a fallback built-in style for other browsers until they support it. (Or file bugs on them to encourage them to implement support!)

**Comment by aviennas** [comment]
I got overwhelmed by the strength of your arguments and decided to return back to my uncivilized cave putting extra stones at the opening. Lobbies are not places for peasants.

**Comment by LeaVerou** [comment]
Hi @aviennas,

I am the Greek speaker that said this to the WG. Thank you for your compliments. :D 

I think you skimmed through the replies you were given a bit too quickly, which is a bit disrespectful for the people who spent time replying to you.
At the risk of this reply being read diagonally as well, I will try to explain. 

Greek counter styles in CSS today are actually **incorrect**, which I imagine is an even worse problem for anyone having "Greek ancient and modern literature as their field of study". I'm surprised you did not focus your complaint on that. Which Greek ever uses α, β, γ, δ, ε, ζ, η, θ, ι, κ, λ, μ, ..., ω, αα, αβ, αγ etc for numbering?! I have never seen this in Greece, anywhere. If you're a native speaker, and especially someone with "Greek ancient and modern literature as their field of study", you know very well that the correct order is α, β, γ, δ, ε, **στ**, ζ, η θ, ... and that there's no such thing as αα, αβ, αγ. What CSS currently does, is basically a direct translation of how letter numbering works in English, which in Greek is wrong.

That's what Tab was explaining to you. Nobody claimed that the Greek language is not being used today, so you're arguing against a strawman here.

**Comment by aviennas** [comment]
@LeaVerou,

You don't have to thank me for the compliments as they have been subject to
reevaluation. I have not committed more posts to this thread due to a
disapproval of the overall culture that I confronted from the first post
especially the tutoring on civil tones etc. So no skimming on facts or
disrespect shown to those who traced back into the issue to find details.

To be frank as I read your post I feel a set of related guilts beginning
with the one for not initially spotting the wrong implementation, then one
for not having used the style for more that five top level numbered blocks
and finally for being somehow connected if not being the same person with
the one who designed the initial version of the greek letter numbering.

Two rhetoric questions I personally won't look for an answer (as my
conspiracy spirit revealed to me instantly):

1. "who did craft the original version you had to discontinue, the one that
you never corrected (excuse me, the one you did correct via custom counter
styles and expecting the whole browser community to adopt, any moment)?"

2. "Does the group hold any shred of responsibility for the dodgy
version?". No answers expected as the facts are all laid out for anyone to
judge.

**Comment by Crissov** [comment]
> Which Greek ever uses α, β, γ, δ, ε, ζ, η, θ, ι, κ, λ, μ, ..., ω, αα, αβ, αγ etc for numbering?!

@leaverou Maybe it’s not used by Greeks, but it’s a quite common enumeration style in (international) mathematics, although I’m not quite sure about the values after `αα`.

**Comment by therealglazou** [comment]
I can confirm α, β, γ, δ, ε, ζ, η, θ, ι, κ, λ, μ, ..., ω, αα, αβ, αγ... list numbering is extremely common in mathematics.

**Comment by svgeesus** [comment]
For other Greek numbering styles, see
https://www.w3.org/TR/predefined-counter-styles/#greek-styles
