### ISSUE TITLE
[selectors3] better terminology for ~ sibling combinator?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1382]
A [recent edit](https://hg.csswg.org/drafts/rev/20dedc56c691) changed the terminology for sibling selectors:
>   "Adjacent Sibling Combinator" -> "Next-sibling Combinator"
>   "General Sibling Combinator"  -> "Following-sibling Combinator"

I'm a bit hesitant about this change, because it doesn't seem obvious to me that "following" means "any later sibling".  I think I occasionally hear the term "following sibling" as a synonym for "next sibling" rather than meaning "any later sibling".

I wonder if there are better options here for the latter combinator.  Maybe "Later-sibling combinator" would be better -- although I'm still not sure that it fully disambiguates.

**Comment by inoas** [comment]
I know it is a bit more verbose but for sure clear?

`Next-Immediate-Sibling Combinator`
`Any-Following-Sibling Combinator`

**Comment by bkardell** [comment]
Maybe just pluralizing helps?
”following siblings” sounds less misleading than ”following sibling”

**Comment by inoas** [comment]
`Immediate-Sibling Combinator` vs `Following-Siblings Combinator` maybe?

**Comment by Loirooriol** [comment]
@bkardell The problem with plural is that it doesn't work when reading right-to-left, which is usually the natural way to read selectors. For example, `a ~ b > c` would be

> Select any `c` element
> that is a child of a `b` element
> that is a following sibling [can't use plural!] of an `a` element.

"Following" is confusing indeed. What about "posterior" or "subsequent"?

 - Next Sibling Combinator
 - Posterior Sibling Combinator

**Comment by SelenIT** [comment]
I suppose that it can be read as "...that is _one of_ the following siblings of..." or "that _belongs to the set of_ the following siblings of...". So pluralization is not such a big problem. But the word "subsequent" looks good to me.

**Comment by tabatkins** [comment]
Tangent: you have an interesting notion of "recent", @dbaron, since that edit was from 2012. ^_^

@dbaron: Are you okay with @SelenIT's suggestion of subsequent? I think it suffers from the same problem as "following", but it's my favorite suggested so far, at least. ^_^

I'm unsure that *any* single word would solve your concern 100% unambiguously; they can all be interpreted as "the immediate sibling" as well.  We'd have to go with multiple words to be fully unambiguous, I think.

That said, I do think the words we are using now are a definite improvement over the pre-2012 terminology of "adjacent" and "general", which don't convey directionality.

**Comment by dbaron** [comment]
> Tangent: you have an interesting notion of "recent", @dbaron, since that edit was from 2012. ^_^

Ah, it was an old edit, recently brought to the working group for republication of the selectors3 REC.

I guess I'm OK with "subsequent", although it's not clearly better than "later" to me, and it goes against [Orwell's advice](https://wikilivres.ca/wiki/Politics_and_the_English_Language) (see the "Pretentious Diction" section).

**Comment by tabatkins** [comment]
I agree that it's not better than later/following/etc, and also that it's a complicated word for no good reason. ^_^

**Comment by AmeliaBR** [comment]
I agree with the original concern that "following" can be too-easily read as "immediately following".  But not sure "subsequent" is an improvement.  I also suspect that "later" could be confusing, because it properly refers to time relationships and we're talking about spatial relationships.

From a plain-language perspective, my vote would be for "Any-Following-Sibling Combinator".

These are definitions, not syntax that people actually have to type on a regular basis, so clarity should win out over compactness.

**Comment by svgeesus** [comment]
I'm pleased to see this terminology change getting wide review, since that is one of the requirements for transition to a new (no substantive change) Recommendation.

**Comment by tabatkins** [comment]
(It's an editorial change, adjusting the non-API-exposed name of a feature in a spec. It's not substantive - it is impossible to cause any change, positive or negative, in impl support as a result.)

**Comment by svgeesus** [comment]
Yes, that is what "no substantive change" means :)

**Comment by fantasai** [comment]
Renamed to Subsequent-sibling Combinator. I think it's good enough. :)
