### ISSUE TITLE
[css-align] Should 'left' and 'right' really both fall back to 'start?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1403]
The [definition of `left`](https://drafts.csswg.org/css-align/#valdef-self-position-left) and [of `right`](https://drafts.csswg.org/css-align/#valdef-self-position-right) alignment currently both say:

> If the property’s axis is not parallel with the inline axis, this value behaves as start.

It seems less than ideal for both of them to fall back to `start`, since there may be an expectation that they end up on opposite sides.

I think one of them should probably fall back to `end`.  I'm inclined to say it should be `right`, given that line-left is equivalent to (see [mappings](https://drafts.csswg.org/css-writing-modes/#logical-to-physical)) inline-start whenever `direction` is `ltr`.  This is for two reasons:
* I believe `direction: ltr` is more widely used (on the Web, and as a share of world population)
* I suspect the main use case for such fallback might be flipping the `writing-mode` of CJK content between vertical and horizontal, where I suspect `direction: rtl` to be particularly rarely used.

**Comment by fantasai** [comment]
I'm somewhat disinclined to do this, because there is no clearly correct mapping from left/right to block-start/block-end, and I'd like to avoid privileging LTR if there isn't a clear reason to do so.
Also, since Align (and Flexbox and Grid) are heavily biased towards flow-relative keywords, it's reasonably likely that an author will use a start/end pairing anyway--even more so if the author is accustomed to working with writing-modes.

That said, I would not object if the WG decided otherwise, so adding Agenda+.

**Comment by asmusf** [comment]
As a generic argument, the case of having two opposite values mapped to the same thing does appear counterintuitive and should therefore be avoided. I don't see where the special condition ("if the property's axis is not parallel") makes this case special enough to override the expectation that these are opposites. (However, I'm prepared to find out that I'm wrong on that after all).

The principle of not favoring one class of writing system over another only goes so far: absent any definite information you have to pick one; I'm not sure why this case is different.

If there's a particularly common scenario where the axes are not parallel, then the fallback should be selected based on what conditions are most common for that scenario. I don't know if @dbaron is correct in his second reason, but if that can be borne out, would be the stronger of the two in my view.

**Comment by fantasai** [comment]
Okay, so, we definitely have a better answer for some of these: we can use either the physical directions or the line-relative directions in order to get an answer that is perfectly reasonable and non-arbitrary in the majority of cases. We should fix the spec to do that (to use the physical mappings where they exist). However, there still remain some cases that can't be solved with either mapping.

The table below summarizes all the cases. `L` represents line-relative mapping, `P` represents physical mapping. `?` represents cases that can't be mapped with either.

<table>
  <thead>
    <tr><th>	<th>`align-self`	<th>`justify-self`	<th>`align-content`	<th>`justify-content`
  <tbody>
    <tr><th>Horizontal Parent<br>Horizontal Self	<td>↕ ??	<td>↔ P=L	<td>↕ ??	<td>↔ P=L
    <tr><th>Horizontal Parent<br>Vertical Self	<td>↕ ?	<td>↔ P=L	<td>↔ P	<td>↕ L
    <tr><th>Vertical Parent<br>Horizontal Self	<td>↔ P	<td>↕ L	<td>↕ ?	<td>↔ P
    <tr><th>Vertical Parent<br>Vertical Self	<td>↔ P	<td>↕ L	<td>↔ P	<td>↕ L
</table>

The remaining cases are:
  * `align-self` and `align-content` in a 100% horizontal writing mode environment. There is no non-arbitrary answer for mapping left/right along the vertical axis here. (`??` in the table below)
  * `align-self` in the case of a horizontal parent and vertical self. `align-self` maps against the parent’s writing mode normally, but we could map against the self in this case to get an answer.
  * `align-content` in the case of a vertical parent and horizontal self. `align-content` maps against the self writing mode normally, but we could map against the self in this case to get an answer.
That said, I'm currently of the opinion that we should treat the second two cases according to the logic of the first, though, to avoid crossing contexts.

So we can reduce the number of cases affected, but horizontal writing modes will still need an arbitrary mapping for `left` and `right` in the vertical axis.

**Comment by murata0204** [comment]
Fantasai wrote:

> I'm somewhat disinclined to do this, because there is no clearly correct mapping from left/right to block-start/block-end, and I'd like to avoid privileging LTR if there isn't a clear reason to do so.

If different reasonable guys have different expectations, I would like to have no mapping.  Ignoring properties is fine.  Just my two cents.

**Comment by dbaron** [comment]
Contextually ignoring values in CSS isn't an option in CSS, though, since ignoring in CSS needs to happen at parse time, which is separated from value computation time.
