### ISSUE TITLE
[css-align] don't introduce baseline alignment to table columns

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1422]
The [section on Baseline Content Alignment](https://drafts.csswg.org/css-align/#distribution-flex) and the [definition of alignment context](https://drafts.csswg.org/css-align/#shared-alignment-context) introduce a concept of baseline alignment to table columns, which can happen when the writing mode of the cells is orthogonal to that of the table.  (The parts in-between are defined (by the [Applies to line of `writing-mode`](https://drafts.csswg.org/css-writing-modes-3/#block-flow) to have the same writing mode as the table.)

I think this is a very complicated feature, and should not be introduced.

Table layout is a rather complicated algorithm that is not particularly symmetric.  Column size calculation happens first, followed by layout and row size calculation.  Introducing baseline alignment to the column phase would be a complicated change, and it's not clear to me how it would work.  It is more complex than the union of:
* introducing character alignment
* doing intrinsic sizing of orthogonal table cells
since it has most of the issues that both of those problems have, and then I think some of its own.

I don't think the complexity is justified without substantial evidence of demand.

**Comment by dbaron** [comment]
Also, see the [details on character alignment, with issues](https://drafts.csswg.org/css-text-4/#character-alignment) in text level 4.

**Comment by FremyCompany** [comment]
I totally agree here. 

I am not even sure such a thing would be possible, because laying out the first line in the column 
direction for table-cells using an orthogonal writing mode would require to know the height of the rows 
(because this will change how many characters can fit in the first line, and if characters are sorted in 
constantly increasing font-size, each new char will push the baseline further down). The height of the 
rows can only be computed once the width of the columns has been decided, so we have a circularity 
here. (a similar argument might actually apply to grid as well, but I am not sure).

Besides, the current situation with orthogonal writing modes in tables is absolutely terrible, we don't 
even have a base on top of which to build. These two test cases should convince you: 

- https://wptest.center/#/m2f950

![image](https://user-images.githubusercontent.com/364405/27605184-b88c8386-5b30-11e7-80c8-4a2860f71ac5.png)
![image](https://user-images.githubusercontent.com/364405/27605199-c3e6e7b2-5b30-11e7-906a-59591f94418a.png)
![image](https://user-images.githubusercontent.com/364405/27605205-cdcd8b6e-5b30-11e7-8206-af778d018f17.png)

- https://wptest.center/#/ie2h39

![image](https://user-images.githubusercontent.com/364405/27605242-ee7ae492-5b30-11e7-8e84-94ab0e0e4c72.png)
![image](https://user-images.githubusercontent.com/364405/27605258-fd4e220e-5b30-11e7-959c-71bae8754203.png)
![image](https://user-images.githubusercontent.com/364405/27605278-0effe7d0-5b31-11e7-8799-0d8d319d65fb.png)

----------------------------------------------------
Also, why does justify-self still allow baseline alignment? I thought baselines were only generated for the inline direction, so you could not possibly justify yourself based on a baseline, can you?

**Comment by tabatkins** [comment]
> Also, why does justify-self still allow baseline alignment? I thought baselines were only generated for the inline direction, so you could not possibly justify yourself based on a baseline, can you?

align vs justify is based on the container's writing mode - if your container is horizontal but you're vertical, you can absolutely justify yourself to a baseline.

**Comment by FremyCompany** [comment]
> > Also, why does justify-self still allow baseline alignment? I thought baselines were only generated for the inline direction, so you could not possibly justify yourself based on a baseline, can you?
> 
> align vs justify is based on the container's writing mode - if your container is horizontal but you're vertical, you can absolutely justify yourself to a baseline.

Oh, I see, that makes sense.
