### ISSUE TITLE
[css-align] 'justify-self' should override 'auto' margins

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1426]
The current rules for [applying `justify-self` to blocks](https://drafts.csswg.org/css-align/#justify-block) and [applying it to absolutely positioned elements](https://drafts.csswg.org/css-align/#justify-abspos) are structured so that `auto` margins override `justify-self`(with the possible exception of baseline alignment when orthogonal).

However, I tend to think:

* that the newer and more ergonomic API should override the older and less ergonomic API, and
* that it wouldn't be too difficult to structure the rules so that non-`normal` values of `justify-self` override `auto` margins,

so I would suggest that we change so that `justify-self` wins.

This also moves towards erasing the quirk that auto margins do safe alignment for normal flow blocks and for the inline dimension on abspos, but unsafe alignment for the block dimension on abspos.

**Comment by dbaron** [comment]
This also applies to the [rules for `align-self` on absolutely positioned elements](https://drafts.csswg.org/css-align/#align-abspos).

**Comment by fantasai** [comment]
Ok, so, while we fully sympathize with the desire to be rid of the terribleness in abspos margin alignment, the fact is that Grid and Flexbox already prioritize auto margins, and we feel it's definitely more important to remain consistent in this respect across all layout modes.

Let us know if you're satisfied with this resolution; otherwise please mark Agenda+ so we can discuss with the WG. :)

**Comment by dbaron** [comment]
OK... I guess I should have caught that in flexbox.
