### ISSUE TITLE
[css-align] "passed to" wording in Default Alignment section is strange

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1448]
I find the "passed to" wording that appears in a number of places in the [section on default alignment](https://drafts.csswg.org/css-align/#default-alignment) to not fit very well with CSS's model of computation.  It reminds me of the occasional usage of "assignment" terminology where "matching" is what correctly describes CSS's model.

I think the "passed to" usage should be replaced by "used by" or "used by some values of".

**Comment by fantasai** [comment]
I think you're taking an overly-technical definition of "pass" here, trying to tie it to function arguments. Colloquially, the wording in the spec works fine, and I think it is much clearer than "used by", particularly since at least one instance occurs at compute value time. If you prefer, I can replace "passed to" with "copied by", though. Let me know~

**Comment by dbaron** [comment]
I'm still not OK with this.  It's unnecessarily algorithmic, but without any of the stuff surrounding it being at all algorithmic.  The vast majority of the spec is written in terms of definitions, and then you have one sentence floating around that's a piece of an algorithm, but the rest of the algorithm isn't present.  (Also see "retrieved".)

**Comment by dbaron** [comment]
Yep, looks good now.
