### ISSUE TITLE
[mediaqueries] Non-positive value should be invalid for 'resolution' feature

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1454]
Zero and negative values for 'resolution' feature don't make any sense, and it seems all of Firefox, Chrome, and Edge already reject non-positive values for it. The spec should follow the impl and say so.

A simple testcase:
```html
<!DOCTYPE html>
<style>
div {
  width: 100px; height: 100px;
  background: red;
  display: inline-block;
  margin: 10px;
}
@media (min-resolution: 1dpi) {
  #a { background: green; }
}
@media (min-resolution: 0dpi) {
  #b { background: green; }
}
@media (min-resolution: -1dpi) {
  #c { background: green; }
}
</style>
<div id="a"></div>
<div id="b"></div>
<div id="c"></div>
<pre>
<script>
let rules = document.styleSheets[0].cssRules;
for (var i = 1; i < rules.length; i++) {
  document.write(rules[i].media.mediaText + '\n');
}
</script>
</pre>
```

**Comment by frivoal** [comment]
Banning negative numbers at parse time makes sense to me. Excluding 0 seems more problematic, as I think we're trying to avoid open ranges in CSS. In your sample above, it you put `@media (resolution: 0.0000000000000000000000000000000000000000000001dpi)` firefox will output `not all` while Chrome outputs `(min-resolution: 1e-46dpi)`.

If Firefox had rounded to 0 when it reached its maximum precision instead of failing, the two queries would have been effectively equivalent (since they're a min- query).

**Comment by upsuper** [comment]
I don't have strong opinion for zero. We have something elsewhere that we treat zero specifically (e.g. `perspective`) so it isn't really something new... but yeah, in general we probably want to avoid this kind of thing.

**Comment by tabatkins** [comment]
As a general rule, banning zero from a `<number>` or `<dimension>` is disallowed; it's an open range <https://wiki.csswg.org/spec/limited-ranges>.  

perspective()'s special zero behavior is a worst-case thing; the behavior impls settled on is nonsensical from a numerical perspective, not to mention totally discontinuous, and we're sticking with it only because content depends on it.  If its behavior had been properly described originally, and someone had noticed it, it would have been changed in the design phase (almost certainly by specifying that there's a UA-specific minimum value).  It is never an example to look to, and cannot be used to justify more bad behavior.

The correct behavior for this case is fairly similar, in that as the value approaches 0 the size of the pixel approaches infinity.  The correct solution is thus to define that negative values are invalid, and that there's a UA-specific minimum value.

**Comment by frivoal** [comment]
> and that there's a UA-specific minimum value.

Depending on what you mean by that, do we even need that part? `(resolution: 0.000001dpi)` will never match any actual device, any more than `(resolution: 0dpi)`. On the other hand, every visual device will match both `(resolution > 0dpi)` and `(resolution > 0.00001dpi)`.

We should:
* forbid negative numbers
* define that `(resolution:0)` does not matches on non visual devices (to avoid the discontinuity between actual 0, rounded to 0, and very-small-but-not-rounded-to-0 numbers on non visual devices)
* (optionally) note that css-values allows for limited precision, and that rounding small numbers to 0 is ok.

**Comment by tabatkins** [comment]
By "there's a UA specific minimum value", I mean that values between 0 and that minimum are rounded to the minimum, not that values in that range are invalid.

**Comment by upsuper** [comment]
I... don't think this really needs a minimum value, because I don't think anyone is going to use this number as a divisor. Impls just get a resolution from the system and compare it against the provided number, no?

I think directly making zero valid should be enough, unless we use these units for computation somewhere.

**Comment by frivoal** [comment]
> By "there's a UA specific minimum value", I mean that values between 0 and that minimum are rounded to the minimum
I don't see how that's better than rounding to 0, so let's round to 0 when it's too small.

**Comment by tabatkins** [comment]
A resolution of 0dpi is meaningless; it corresponds to an infinite dot size, which isn't physically possible.  That's why I'm talking about a minimum value; it limits you to physically possible resolutions.

**Comment by tabatkins** [comment]
Again, this implies that zero *is a valid value* for parsing purposes, it's just *treated as* some particular non-zero positive value.

**Comment by frivoal** [comment]
> A resolution of 0dpi is meaningless; it corresponds to an infinite dot size, which isn't physically possible.

Neither is a device with pixels that are 375 miles across. 

I don't see the practical benefit / difference. No device will have infinitely large pixels. No device will have 375 miles large pixels either. So none of `resolution:0`, `resolution: something-tiny`, `max-resolution:0`, or `max-resolution: something-tiny` will ever match anything. However, both `min-resolution: 0` and `min-resolution: something-tiny` will match the same things (all the visual devices, for which a concept of resolution is meaningful).

So if the practical results are the same, why introduce extra logic in processing, when old fashioned rounding will do just fine?

**Comment by frivoal** [comment]
As far as I can tell, without any normative prose, this seems to be all we need on this topic of rounding / smallest values / 0.

> Note: Since `resolution:0` would imply infinitely large pixels, it will never match on any device (nor will `max-resolution: 0`). However, `min-resolution:0` does match on all visual devices. Small values that are rounded to 0 due to limited precision in the implementation behave identically.

**Comment by frivoal** [comment]
On the other side of the discussion, I wonder whether we should actually let negative values parse. `(resolution < -3dpi)` should always be `false`. But if we made it not parse, it would be `unknown` instead of being `false`, as per [the error handling section](https://drafts.csswg.org/mediaqueries-4/#error-handling):

> An unknown <mf-name> or <mf-value>, or disallowed <mf-value>, results in the value “unknown”.

Either way
```css
@media (resolution: -1dpi) { body { background: red; } }
```
would fail to give a red background on any device, but
```css
@media not (resolution: -1dpi) { body { background: green; } }
```
could very reasonably give you a green body on all visual devices.  And while we're at it, so could
```css
@media (resolution > -2dpi ) { body { background: green; } }
```

I don't think there's much of a use case for specifying such nonesense resolutions manually, but they could fall out of calc() or some server side math, and still be usable in range contexts.

If we clarify that this works, we should apply the same logic to other range properties with nonsensical negative values, like `width`

**Comment by dbaron** [comment]
For the record, the existing 2012 RECcomendation already requires that the value be *positive*, exactly matching what all the implementations do.  Its [Values section](https://www.w3.org/TR/2012/REC-css3-mediaqueries-20120619/#values) says:
> The &lt;resolution> value is a positive &lt;number> immediately followed by a unit identifier (‘dpi’ or ‘dpcm’).

This probably explains why we have such good interoperability.

The text that led to that interoperability just appears to have been dropped from all current specification drafts.

This text, however, didn't get ported to [the relevant section of values-3](https://drafts.csswg.org/css-values-3/#resolution) when the type was copied there (in late 2011 or early 2012).

**Comment by frivoal** [comment]
@upsuper We did agree to a change based on the issue you raised, but the conclusion we reached is not the one you initially suggested. Can you confirm that you are OK with that change?

**Comment by upsuper** [comment]
I'm OK with that change.
