### ISSUE TITLE
[css-fonts-4] Clarify meanings of variation range values in @font-face property descriptors

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#1455]
[In the font property descriptors section](https://drafts.csswg.org/css-fonts-4/#font-prop-desc), which describes style, weight, and stretch font-stretch has a notion of percentage and percentage range. 

I may be missing something, but I believe we should clarify what a percentage corresponds to. Does 100% correspond to normal stretch and what percentage ranges are permitted. Are percentages > 100% allowed? How are these mapped to the 'wdth' axis?

Similarly what should be allowed values for `angle` and `number` for style and weight respectively? Or if we don't restrict those with intervals up front, what should be the mapping, including out-of-range values that cannot be mapped to variation axis parameters for the font?

CC @litherum @PeterCon

**Comment by drott** [comment]
I assume the intention is to map these to the registered Variation Axis Tags, described on https://www.microsoft.com/typography/otspec/fvar.htm

So "Style" would be matching to 'slnt' or 'ital'?
"Weight" matching to 'wght'?
"Stretch" matching to 'wdth'?

So that would mean percentage values can be larger than 100%, and 100% would take on the same meaning as in this part of the OpenType spec, referring to "whatever the font designer considers “normal” for that font design".

"Weight" taking values from 1 to 1000, where the normal value would be 400, according to OpenType.

How do we map "Style"?

**Comment by drott** [comment]
Okay, I missed that there is already more information on those in sections [2.2](https://drafts.csswg.org/css-fonts-4/#font-weight-prop) to [2.4](https://drafts.csswg.org/css-fonts-4/#font-style-prop) which we should perhaps reference here.

**Comment by drott** [comment]
Now I found: "If specified values are out of range of the accepted values of the property of the same name, the descriptor is treated as a parse error." - that's what I was looking for.

**Comment by litherum** [comment]
The mapping for GX fonts is not straightforward; I had to study a font with many different weights to come up with a mapping (since these fonts use a different scale than CSS).

You have to remember whether “italic” or “oblique” was specified to font-style to make sure you trigger the correct axis.

**Comment by litherum** [comment]
(But you’re right about the mapping for non-GX fonts.)

**Comment by PeterCon** [comment]
I don't understand the references to percentage and percentage range for font-style and font-stretch in 4.4 since 2.2 and 2.4 indicate that percentages are "n/a" for those properties.

Also, in 2.3 it says "Percentages: Not resolved." It's not clear to me what that means. In the linked CSS Values and Units spec, it only offers (in 8.1.3), "Where percentages are not resolved at computed-value time, they are not resoved in 'calc()' expressions...". Perhaps a little clarification in Fonts/2.3 would help?

**Comment by litherum** [comment]
> I don't understand the references to percentage and percentage range for font-style

Where do you see percentages mentioned with regards to font-style in 4.4? Font-style doesn't accept percentages; only font-stretch does. These percentages are not resolved against anything; they remain as percentages and used directly when performing font selection and variation axis application. Section 2.3 mentions that these percentages are "not resolved," which is correct.

Because font-weight and font-style don't accept percentages, they are marked n/a.

Maybe I'm not understanding your question?

**Comment by PeterCon** [comment]
> I don't understand the references to percentage and percentage range for font-style

Sorry, pre-coffee remark; please ignore.
