### ISSUE TITLE
[css-display] Explicitly note display:contents does not affect inheritance

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1473]
[`display: contents`](https://drafts.csswg.org/css-display-3/#valdef-display-contents) has this note

> As only the box tree is affected, any semantics based on the document tree, such as selector-matching and event handling, are not affected.

This is kinda obvious: if `display: contents` can be set to an element via selector-matching, it shouldn't affect selector-matching. And event handling is entirely a DOM thingie.

CSS Cascade says inheritance follows the document tree but that's a blatant lie, e.g. `::first-line` intercepts inheritance for some properties, and it is based on the box tree. Therefore, I don't think it's obvious at all that children elements of a `display: contents` still inherit from it.

So please note style inheritance is not affected by `display: contents` neither.

**Comment by tabatkins** [comment]
Inheritance following the document tree is not a "blatant lie" - it's correct for everything that lives in the tree; ::first-line and ::first-letter are bizarro exceptions that are explicitly called out, because they don't live in the tree properly (that is, if they're included, *it's not guaranteed to be a tree anymore*, just a DAG).

But we're fine with calling out inheritance in that sentence too.

**Comment by Loirooriol** [comment]
Inheritance from `::first-line` is a mess which eventually should be properly defined in CSS Cascade. Anyways, the edit clarifies the behavior of `display: contents`, so it's fine, thanks.
