### ISSUE TITLE
[css-text-3] text-shadow's specified grammar is out of order

### ISSUE THREAD

**Issue by nox** [w3c/csswg-drafts#1485]
The [spec](https://drafts.csswg.org/css-text-decor/#propdef-text-shadow) says `none | [ <length>{2,3} <color>? ]#` but at least Safari and Gecko serialise `1px 1px black` as `black 1px 1px`.

**Comment by birtles** [comment]
So does Blink last I checked. Although actually Gecko and Blink serialize colors as their rgb() equivalents.

(Also, both Gecko and Blink fail to drop a 0px blur radius from their serialization which, as I understand it, should not be serialized since it is an optional component with its default value.)

**Comment by tabatkins** [comment]
Fixed in 31043718b

**Comment by birtles** [comment]
I believe that should be 5c46d7810730ac8b7bad2f8194ca24f7e30060b3
