### ISSUE TITLE
[css-tables-3] Table Width when percentage widths exceed 100%

### ISSUE THREAD

**Issue by joysyu** [w3c/csswg-drafts#1501]
https://drafts.csswg.org/css-tables-3/#width-distribution

The spec appears to be silent on what the table width should be when percentage widths exceed 100%. Repro here: https://jsfiddle.net/pfnvwLv4/

Edge 14 shows a table of width 1533917px, Firefox 45 shows a table of width 17895698px, and Chrome 50 shows a table of width 25600px.

/cc @davidsgrogan @FremyCompany @gregwhitworth

**Comment by FremyCompany** [comment]
Percentages cannot exceed 100% due to the fact they get capped at 100%. You can replace 5% by 0% or even 0px that wouldn't change the result.

**Comment by FremyCompany** [comment]
The various results seem to be only due to the width you set on the outer div, which is bigger than any browser accepts to handle for a table, and each browsers stops the table size at some value deemed to be not to be a bug. In this case it's not a bug, you just wrote a very big size for the parent, which browsers do not really expect.

**Comment by davidsgrogan** [comment]
> each browsers stops the table size at some value deemed to be not to be a bug

Isn't that what the spec omits? What "some value" should be?

**Comment by gregwhitworth** [comment]
@davidsgrogan This is UA specific, whatever Blink feels the largest table is possible, this going to vary browser to browser based and also may change based on the available hardware. This is not new to allow UAs to do their own optimizations based on their engine as no one can actually do an infinite table as memory is limited. We could if you'd like, add some terminology similar to Grid:

> Since memory is limited, UAs may clamp the possible size of the grid to be within a UA-defined limit, dropping all lines outside that limit. If a grid item is placed outside this limit, its grid area must be clamped to within this limited grid.

Ultimately, I don't think this is the largest hurdle in tables as a calc/layout of a table of this size is going to be costly so most usecases will probably result in the author batch this information into smaller tables so this probably won't be hit anyways. And since you have the smallest max, my suspicion is you'd probably know more than us since your users would see the content clipping if anyone would build a table this large.
