### ISSUE TITLE
[css-flexbox] [css-text] Alias "nowrap" as "no-wrap"

### ISSUE THREAD

**Issue by nainar** [w3c/csswg-drafts#1537]
This issue was discussed here: https://lists.w3.org/Archives/Public/www-style/2014Oct/0189.html in 2014 and the general consensus was that aliasing "nowrap" with "no-wrap" was worth doing. However no resolution was made. Filing this issue to track progress.

**Comment by fantasai** [comment]
There was no resolution because there was no consensus on making that change, as you can see from @zcorpan's skeptical reply (that you are linking). There's also this thread https://lists.w3.org/Archives/Public/www-style/2014Oct/0245.html and earlier WG discussion at https://lists.w3.org/Archives/Public/www-style/2012May/0541.html fwiw.

**Comment by tabatkins** [comment]
Right, Simon brought up the question of whether it was enough of a pain point for authors to be worth it.

I've anecdotally seen a small but persistent confusion about this among authors, so I support it.  It's also personally one of my biggest peeves. ^_^

**Comment by nainar** [comment]
Thanks for giving the extra context @fantasai . Is it worth discussing this again at a telecon/face to face? If a telecon could it wait until an APAC-friendly telecon slot so I can be present? Thanks!

**Comment by zcorpan** [comment]
A reason I think it's not worth doing is because developers will never be able to not know about "nowrap", since CSSOM has to return that value forever for web compat. So adding another value will make it harder to work with.

Alternatively, if you want to make the API roundtrip which keyword was used, that makes implementation more complex and JS that wants to check for this value needs to check for two values forever, again making it harder to work with.

**Comment by SebastianZ** [comment]
> A reason I think it's not worth doing is because developers will never be able to not know about "nowrap", since CSSOM has to return that value forever for web compat. So adding another value will make it harder to work with.

This statement calls for usage data. I.e. how many sites expect `"nowrap"` to be returned by CSSOM?

Sebastian

**Comment by zcorpan** [comment]
https://github.com/search?l=JavaScript&q=getcomputedstyle+nowrap+whitespace+OR+white-space&type=Code&utf8=✓ has plenty of examples of that.

**Comment by nainar** [comment]
I would prefer if we went with option 2. If I understand parse time aliasing correctly, the returned value would still be 'nowrap' which deals with the issue of the value being checked in JS. 

If folks are already checking for a value in JS they clearly know that flex-box/whitespace accepts 'nowrap' not 'no-wrap' so they are still in the clear. This helps those who are just setting a value and then scratch their head because it doesn't do what they expected.

**Comment by patrickdark** [comment]
Seems like a good idea to go with option three from an authoring perspective.

If I understand option two correctly, it leads to bizarre situations like:

    element.style.setProperty("white-space", "no-wrap");
    element.style.getPropertyValue("white-space") === "no-wrap"; // false

That seems pretty undesirable. However, that strange behavior might be worth accepting as I've never had a reason to poll the value of the `white-space` property and if one needs to do so in a CSS Text, Level 4 world, one can use the following code, assuming the `no-wrap` keyword modification is integrated into that spec:

    element.style.setProperty("text-wrap", "no-wrap");
    element.style.getPropertyValue("text-wrap") === "no-wrap"; // true

**Comment by astearns** [comment]
RESOLVED: No change for issue about adding no-wrap
