### ISSUE TITLE
CSS Snap Points: Snap should restore after resize

### ISSUE THREAD

**Issue by scottjehl** [w3c/csswg-drafts#155]
After resizing the browser, an overflow region inside the page that uses scroll snap points will often lose its snapped scroll distance. A current workaround would be to bind to a resize event and scroll back to the snap point that was "active" before resizing, but it would be nice if the browser did this natively.

**Comment by tabatkins** [comment]
This is already mandated by the spec (last paragraph of [the Snap Type section](https://drafts.csswg.org/css-scroll-snap/#snap-type)); if browsers aren't doing it, it's a bug. Please file. ^_^

**Comment by pitus** [comment]
Why is this issue closed without resolution?
It's a serious problem for anyone using snap points.
When the container resizes, the scrollLeft position remains at a fixed pixel position instead of 'scaling' proportionally to the container. There is no solution to this problem at the moment as there's no easy way to monitor container's resize in javascript (it's not the same as monitoring window resizing).

**Comment by frivoal** [comment]
> Why is this issue closed without resolution?

Because it is a browser bug, not a specification bug, and there is nothing we can on the specification that hasn't already been done.

Bugs should be filed against individual browsers to request that the match the spec.
