### ISSUE TITLE
[css-fonts-4] Animation type font-weight, discrete?

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#1579]
https://drafts.csswg.org/css-fonts-4/#font-weight-prop describes the animation type as "discrete". What does this mean and what is the intended behavior?

Does it refer to a behavior as defined in https://drafts.csswg.org/css-transitions/#animtype-font-weight, or is the intention to animate as https://drafts.csswg.org/css-transitions/#animtype-integer? Or should this rather be animated as <number>, same as stretch?

In my opinion, at least implementing this as discrete jumps from 100, 200, ..., 900 seems odd for variable fonts, which would make it necessary to use font-variation-settings to achieve a smooth weight animation.

**Comment by SebastianZ** [comment]
Looks like it should refer to the [font weight animation type](https://drafts.csswg.org/css-transitions/#animtype-font-weight), because the [definition in CSS Fonts 3](https://drafts.csswg.org/css-fonts-3/#font-weight-prop) also refers to it.

Having said that, the discussion whether the discrete transition between the number values should be changed to a smooth one is then rather related to CSS Transitions.

As `font-weight` was changed in CSS Fonts 4 to allow arbitrary `<number>` values (should that actually be `<integer>`?) instead of discrete values, it makes sense to redefine the transition so that it also allows `<number>` (resp. `<integer>`) values.

Therefore, the font [weight animation type in CSS Transitions 1](https://drafts.csswg.org/css-transitions/#animtype-font-weight) may either be changed accordingly or removed in favor of specifying an animation type of `<number>` (or `<integer>`) in CSS Fonts 4.

Sebastian

**Comment by svgeesus** [comment]
Agreeing it makes no sense for this to be discrete in fonts 4.
Therefore, it makes little sense for fonts 3 to specify something different here.
Maybe say that animation is discrete if variable fonts are not supported?

**Comment by LeaVerou** [comment]
Even in Fonts 3, the effect would be the same even if animated like a `<number>` due to `font-weight` resolution rules, no?

**Comment by litherum** [comment]
No, due to the font selection algorithm, the value can still be interpolated numerically, and the result will appear discrete. (At certain thresholds, a new font will be chosen, so it'll look discrete.)

It should just be animated as `<number>`, just like `font-stretch`.

**Comment by LeaVerou** [comment]
> No, due to the font selection algorithm, the value can still be interpolated numerically, and the result will appear discrete. (At certain thresholds, a new font will be chosen, so it'll look discrete.)

I’m confused. You said no, then proceeded to agree with me.

**Comment by litherum** [comment]
Sorry for the confusion. I totally agree with you, Lea. (My "no" was directed at an earlier post.)

**Comment by litherum** [comment]
I just forgot to list the "Animatable" keyword in the propdef table 😇

**Comment by fantasai** [comment]
Reopening to see if fonts-3 and transitions-1 should be updated accordingly. If so, fonts-3 probably needs some prose to explain how to round to the nearest 100.

**Comment by litherum** [comment]
https://drafts.csswg.org/css-transitions/#animtype-font-weight

> font weight: interpolated via discrete steps (multiples of 100). The interpolation happens in real number space and is converted to an integer by rounding to the nearest multiple of 100, with values halfway between multiples of 100 rounded towards positive infinity.

Is this insufficient?

**Comment by litherum** [comment]
Adding to F2F [agenda](https://wiki.csswg.org/planning/paris-2017?&#topics), so removing Agenda+

**Comment by litherum** [comment]
There is a small behavior change here. 🙁

Consider animating font-weight between 400 and 600, and at the current time, the "real number" is 425.

In the old model, 425 gets rounded to 400, which causes the [old font matching algorithm](https://drafts.csswg.org/css-fonts/#font-style-matching) to search the following list:
400, 500, 300, 200, ...

In the new model, 425 doesn't get rounded, and the [new font matching algorithm](https://drafts.csswg.org/css-fonts-4/#font-style-matching) searches the following list:
425, ..., 400, ..., 300, ..., 200, ..., 500

Therefore, if the system has installed fonts at weights of 500 and 300, in the first model, the 500-weight font will be selected, and in the second model, the 300-weight font will be selected.

**Comment by litherum** [comment]
We could solve this by making the font selection algorithm more complicated, or we could just swallow the behavior change.

Animation of font weights in the old world was fairly uncommon, so I'm not sure that this behavior change is very important. Keeping the new world's font selection algorithm as simple as possible seems important because it already had to get way more complicated because of variation fonts.

WebKit has had the new matching algorithm in our betas, Safari Technology Preview builds, and nightly builds for weeks/months, and I haven't seen a single bug about this.

**Comment by drott** [comment]
+1 for not making the algorithm more complicated, rather accepting this behavior change.

**Comment by astearns** [comment]
![image](https://user-images.githubusercontent.com/1380751/28923945-1ac8dd3c-7860-11e7-9175-291aede76f41.png)

**Comment by tabatkins** [comment]
Specifically (to summarize the picture):

1. If font-weight < 400, search down to zero, then search up to 1000.
2. If font-weight > 500, search up to 1000, then search down to 0.
3. If font-weight is between 400 and 500, first search up to 500, then search down to 0, then search up to 1000.

Then, we remove the "round to nearest 100" behavior from animations. This is a probably-minor change to font-weight animations, which we think are fairly rare in legacy, pre-variation-axis pages anyway, and the change itself isn't very significant; you just swap between the intermediate font faces at slightly different times, but end up with the same result on either end.

**Comment by ewilligers** [comment]
Should the syntax support <number>, and clamping to the range 0..1000, so animated values can round-trip?

**Comment by drott** [comment]
I think in the IRC log Myles confirms, it should animate as `<number>`. I'm in favor of a clamping range, but I think to be consistent with https://drafts.csswg.org/css-fonts-4/#font-weight-numeric-values it should be 1..1000: 

> Only values greater than or equal to 1, and less than or equal to 1000, are valid, and all other values are treated as parse errors.

**Comment by FremyCompany** [comment]
Just a ping that css-fonts-4 still mentions font-weight as being an `<integer>` while we now implement it as a `<number>`

**Comment by litherum** [comment]
@drott is right, and I don't believe there's anything to do here regarding that point.

@FremyCompany I'll do this now.

**Comment by litherum** [comment]
Whoops, this was already done. https://github.com/w3c/csswg-drafts/commit/0d2eca79ba
