### ISSUE TITLE
[css-text-decor-3] behavior of text-decoration + text-emphasis

### ISSUE THREAD

**Issue by momdo** [w3c/csswg-drafts#160]
I think that the spec mentions behavior of text-emphasis + ruby (see below) but doesn't say behavior of combination of text-decoration and text-emphasis.

> If emphasis marks are applied to characters for which ruby is drawn in the same position as the emphasis mark, the emphasis marks are placed outside the ruby. 
> https://drafts.csswg.org/css-text-decor-3/#text-emphasis-position-property

From an aesthetic point of view, text-decoration and text-emphasis should be separated from each other.

Furthermore, I feel that we have to think more complex pattern such as mixing text-decoration, text-emphasis and ruby.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1262792

**Comment by realskk** [comment]
It's just FYI, but our EPUB viewer behaves like the attached file.  We decided this after talking with Toppan printing people, so we believe this behavior might be sufficient for lots of printing situation. 

![capture](https://cloud.githubusercontent.com/assets/17156693/15734368/db4bf8ce-28c9-11e6-8fab-e2f73f9d7656.png)

**Comment by upsuper** [comment]
Interaction between decoration lines and emphasis marks could be complex (mostly because decoration line is complex). Text could be vertical aligned to some other place, which could be very far from the decoration line, and the relative position of the text and decoration line could even be reversed. There could also be multiple decoration lines, and they could be much further from the text as well.

Those kinds of cases may not be as important as the main usecases, but I think they should still be considered when specing the behavior, so that they would at least have a reasonable result.

**Comment by upsuper** [comment]
@realskk Could you provide more information about what rule are you using to archive that result? What would the behavior be for the cases I mentioned in the comment above?

**Comment by upsuper** [comment]
For example what behavior would be for this code?
```html
<span style="text-emphasis: circle; text-decoration: overline">CO<sub>2</sub></span>
```

**Comment by realskk** [comment]
In Blink, the underline is drawn in InlineTextBox.  It means "CO" and "2" correspondingly in your example. We moved the drawing functionality to InlineFlowBox.  Then the line is drawn over "CO2", as the attached file shows. 

Did I answer what you asked?? 

![pasted image at 2016_06_07 03_42 pm](https://cloud.githubusercontent.com/assets/17156693/15848671/4f2bdc8e-2cc9-11e6-8abc-137e611520b5.png)

**Comment by upsuper** [comment]
My question was, where should the emphasis marks be?

**Comment by realskk** [comment]
Sorry, I missed the mark. (I forgot prefixing.)  At least our implementation, the mark is drawn on top of underline. 

![image](https://cloud.githubusercontent.com/assets/17156693/15849088/b1c34826-2ccb-11e6-8896-fe81ba7a8491.png)

**Comment by realskk** [comment]
I wonder that the current editor's draft of 'text-underline-position' says in note that the line can be drawn line-through (as attached). 

![image](https://cloud.githubusercontent.com/assets/17156693/15849317/d333d222-2ccc-11e6-90d4-39c68d46d0f3.png)

But in case of the example below, where the emphasis mark can be drawn? If the line is drawn on top of the line as spec describes and emphasis mark is drawn on top of the line as shown by me, then the emphasis mark can be put on the character "2". 

<span style="text-emphasis: circle; text-decoration: overline;">CO<span style="font-size: 300%;">2</span></span>

**Comment by fantasai** [comment]
That example is showing a bad result. :) The UA should ideally not do that, is what it's saying. Maybe I should make the example clearer...

Underline/overline should be between the text and the ruby/emphasis marks. It's a bit complicated as you note in cases with varying font size or vertical alignment. I think maybe we need to add something like “The position of ruby and of text-emphasis dots may be adjusted in order to avoid text decoration lines.”

**Comment by upsuper** [comment]
@realskk Another question, is the position of emphasis marks affected by presence of decoration lines? I mean, in the CO<sub>2</sub> example, if there is no overline, should the emphasis marks be placed differently?

**Comment by fantasai** [comment]
OK, I checked in two sets of changes. First to clarify the note to address @realskk's confusion about the behavior in the note--you can see the new text and a new image in the [editor's draft](https://drafts.csswg.org/css-text-decor-3/#text-underline-position-property).

Second set of changes adds the following text to CSS Ruby and references it from the definition of `text-emphasis-position`:

> The positions of ruby annotations may be adjusted to avoid conflicts with overline and underline decorations applied to the base text. In the basic case of consistent font size and baseline alignment, an underline or overline is to be positioned between the base level and any annotations on that side. 

I'm open to additional suggestions/improvements, this is just a first pass. Let me know what you think.

Also, @realskk is it OK if I use your image in the spec?

Also, it seems to me that the variation in the emphasis marks' position and size in those examples is awkward, shall I open an issue on that for Text Decoration Level 4?

**Comment by realskk** [comment]
(At F2F, I told to fantasai, that using image is OK, of course.  Let me have more time for replying actually.)

**Comment by fantasai** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/1892 on maintaining size and position, which is also relevant to @upsuper's question.

Still need some feedback on whether the changes in https://github.com/w3c/csswg-drafts/issues/160#issuecomment-269450335 are enough or if there are further clarifications we'd like to make!

**Comment by fantasai** [comment]
Note: @upsuper filed https://github.com/w3c/csswg-drafts/issues/1918 for discussion of further details in css-ruby. If everyone's OK with the current allowances, I would like to close this issue. For reference, the added text is

CSS Text Decoration Level 3:
> Emphasis marks are drawn exactly as if each character was assigned the mark as its ruby annotation text with the ruby position given by 'text-emphasis-position' and the ruby alignment as centered. <ins>Note that this position may be adjusted if it would conflict with underline or overline decorations.</ins>

CSS Ruby Level 1:
> The positions of ruby annotations may be adjusted to avoid potential conflicts with overline and underline decorations applied to the base text. In the basic case of consistent font size and baseline alignment, an underline or overline is positioned between the base level and any annotations on that side.

**Comment by upsuper** [comment]
I don't really think #1918 covers some of the issues (specifically that what happens when font size changes in the piece of text). #1918 was merely for that ruby can conflict with decoration lines even if all text has the same size and position.

The interaction between them with changed font size and vertical position feels more complicated.

I think I have a question to @realskk not answered that: is the position of emphasis marks affected by presence of decoration lines? I mean, in the CO<sub>2</sub> example, if there is no overline, should the emphasis marks be placed differently?

It is not clear to me what the answer should be, and I think that would affect how the spec should work.

**Comment by upsuper** [comment]
This question can apply to ruby as well. Is the position of ruby annotation of text which has different size / vertical position affected by decoration lines?
