### ISSUE TITLE
[css-color-4] no contrast guarantee on semi-transparent colors

### ISSUE THREAD

**Issue by xi** [w3c/csswg-drafts#1628]
https://drafts.csswg.org/css-color-4/#contrast-adjuster

The heading of this section "Guaranteeing Adequate Contrast" is misleading because the algorithm ignores the alpha channel. A note should be added that warns about this detail.

I do not think that the contrast adjuster should take alpha into account. This would require more context ("is it background or font color?", "if it is background, what is behind that?"). Ignoring the context would mean to assume worst case. See also [this article](http://tobib.spline.de/xi/posts/2016-03-05-color-contrast/) for an in-depth discussion of this topic.

**Comment by tabatkins** [comment]
"Worst case" is fully transparent, which automatically fails, so we can't do that. ^_^

But yeah, it could do with some more options/variations.

**Comment by xi** [comment]
> > Ignoring the context would mean to assume worst case.
>
> "Worst case" is fully transparent, which automatically fails, so we can't do that. 

By that I meant that in a situation like [white text on `rgba(0,0,0,0.5)`](https://leaverou.github.io/contrast-ratio/#white-on-rgba%280%2C0%2C0%2C.5%29), we would need to know the color *behind that* to caluclate the contrast. Unfortunately we do not know it. So in order to still guarantee sufficient contrast, we would have to check the worst possible case (in this case white text on `rgba(0,0,0,0.5)` on white, which is 4).

**Comment by AmeliaBR** [comment]
@xi 

It's one thing to _calculate_ a worst-case contrast ratio for a given color pair when one is semi-transparent, but I don't think there's going to be a way to generate a good color from it.  The fix for white text on white+semi-transparent black might be to make the text darker.  But then what happens if the layer behind the background is black?  Your fix just became a problem of its own.  

But the entire section confuses me. From the syntax, I'm not sure how you specify both colors (the background and the desired foreground).  It looks like it is just starting from the base color as the background and then generating a shade of _that_ color (hue and saturation) that meets the desired contrast level.  So are you then supposed to use that result in a separate adjusting function, to adjust the luminance of your desired foreground color?

Giana Blantin's [Sass functions show one possible API for a "fix contrast" function that might be more clear](https://codepen.io/giana/project/full/ZWbGzD).

**Comment by xi** [comment]
@AmeliaBR I completely agree, but there are separate issues for that (see for example #1627). Let's stick to the issue of semi-transparency here.

**Comment by xi** [comment]
Closing since the contrast adjuster is no longer part of the spec.
