### ISSUE TITLE
[css-pseudo] When no word can fit due to floats and a line was pushed down, is it still ::first-line?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1644]
The [first formatted line](https://drafts.csswg.org/css-pseudo-4/#first-formatted-line) isn't very clear about this.

[A test](http://jsbin.com/bozuhec/edit?html,output) indicates:
* Gecko changes the definition by whether the float is within the inline formatting context or not.
* Blink/Edge/WebKit considers it's first formatted line regardless where the float appeared.

**Comment by Loirooriol** [comment]
My understanding was that this is a Gecko bug. I filed [bug 1352761](https://bugzilla.mozilla.org/show_bug.cgi?id=1352761) some months ago, nobody replied.

**Comment by mrego** [comment]
I've similar questions on #2120, I've another [test case](https://codepen.io/mrego/pen/PEGRmK) that shows differences between browsers.

**Comment by fantasai** [comment]
As @Loirooriol says in Gecko bug 1352761, CSS2 defines that the line moves down, not that it becomes another line. So I would say that the spec is clear that a line forced to move down due to floats is still the first formatted line. https://www.w3.org/TR/CSS21/visuren.html#floats

“If a shortened line box is too small to contain any content, then the line box is shifted downward (and its width recomputed) until either some content fits or there are no more floats present.”
