### ISSUE TITLE
Should font-variation-settings be a property, a descriptor, or both?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1652]
Fonts Level 4 introduces a [`font-variation-settings` property](https://drafts.csswg.org/css-fonts-4/#font-variation-settings-def) that sets particular variation parameters.  These seem likely to be reasonably specific to particular fonts, although I'm not entirely sure how much.

That they're specific to fonts makes me suspect that it may make more sense for this to be available as a descriptor so that a font-variation-settings doesn't accidentally apply to a fallback font.  This seems like it could become more problematic as system fonts (which are likely to be fallback) become more likely to support OpenType variations.

I wonder whether font-variation-settings should be available as a descriptor in addition to a property (like `font-feature-settings`), or maybe even *instead* of a property.

I got here from w3ctag/design-reviews#183.

**Comment by dbaron** [comment]
@plinss points out that animation is only possible with a property

**Comment by litherum** [comment]
You are right that only certain fonts will respond to certain axes, but the meaning of a particular value on a particular axis is expected to be consistent between fonts. This is why the high-level properties of `font-weight`, `font-style`, `font-stretch`, and `optical-sizing` are preferable over `font-variation-settings` because their behavior is well-defined over all fonts. This works the same way as `font-feature-settings`.

**Comment by litherum** [comment]
It's already a property, so it needs to be a descriptor too.
