### ISSUE TITLE
[css-text] "segment break" link should point directly to its definition

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1665]
CSS Text defines [document white space characters](https://drafts.csswg.org/css-text-3/#white-space) as

> spaces (U+0020), tabs (U+0009), and [segment breaks](https://drafts.csswg.org/css-text-3/#white-space-processing).

So I wanted to see the definition of "segment break", but surprisingly the link points to [§4. White Space Processing Details](https://drafts.csswg.org/css-text-3/#white-space-processing). This is not useful, because that section has a big preamble before the definition of "segment break". The link should directly point to https://drafts.csswg.org/css-text-3/#segment-break instead.

**Comment by fantasai** [comment]
It links to the top of the section because the definition of segment break effectively starts there, even though the defining instance is further down. Segment breaks are a bit of an arcanely abstract concept, so the first paragraph explains the context for them. So linking to the top makes sense to me. Do you have a stronger counter-argument? :)

**Comment by Loirooriol** [comment]
When I want to read the context I prefer to scroll up manually, because then I can control how much context I am willing to read. But well it's not a big deal, leave it as it is if you prefer.
