### ISSUE TITLE
[CSSOM] Separate camel_cased_attribute from CSSStyleDeclaration

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#1692]
In https://github.com/w3c/csswg-drafts/issues/825#issuecomment-320106940, we resolved to:

1. Remove [`_camel_cased_attribute`](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-_camel_cased_attribute) from `CSSStyleDeclaration`.
2. Create another interface with `_camel_cased_attribute`, somehow mix it into CSSStyleRule? The DOM2Style spec was extremely hand-wavy about this worked.

**Comment by zcorpan** [comment]
Do you mean mix it into CSSStyleDeclaration?

I don't understand what is being requested.

**Comment by tabatkins** [comment]
Yeah, CSSStyleDeclaration.

Some context:

Currently, if we change CSSFontFaceRule's spec back to matching reality (giving it an `attribute CSSStyleDeclaration style;`), it'll come with every CSS property as well.  This is nasty and dumb, and since Firefox doesn't do this and hasn't had any problems, clearly something we can avoid.

So, probably pull the `_camel_cased_attribute` into a separate `[NoInterfaceObject]` interface, and specify (I guess in prose?) that it's mixed into the version of CSSStyleDeclaration used on CSSStyleRule only.  We'll do similar for the set of descriptors actually used by `CSSFontFaceRule.style`.

(Tho, looking at Firefox, it currently uses CSS2Declarations as the type for CSSStyleRule.style; this interface inherits from CSSStyleDeclaration.  Presumably we can just copy that, then, and make both instances uses subclasses instead, to avoid doing weird prose shenanigans.)

**Comment by zcorpan** [comment]
So we have three different versions of CSSStyleDeclaration:

* The one returned by `element.style`
* The one returned by `getComputedStyle(element)`
* The one returned by `cssStyleRule.style` or `cssFontFaceRule.style` (or are these also different?)

Should each of these have different subclasses? Is that web compatible? What do browsers do?

Also note that it's not sufficient to separate only `_camel_cased_attribute`, there's also `_webkit_cased_attribute`, `_dashed_attribute`, and `cssFloat`.

**Comment by gsnedders** [comment]
We resolved this in #5649.
