### ISSUE TITLE
[css-fonts] Font matching algorithm; issue with weight selection

### ISSUE THREAD

**Issue by neilj** [w3c/csswg-drafts#1701]
This issue is related to the font-weight section of the font-matching algorithm (https://github.com/w3c/csswg-drafts/blob/master/css-fonts/Fonts.html#L3383).

When an exact match is not available for the specified weight, I believe the browser should instead choose the *nearest* available weight (with rules for tie-breaks obviously). This is very useful when you need to have multiple fallback fonts for different platforms, and one font has weights 400,500,700 (say), and another 400,600,700. For semi-bold text I want 500 from the first font, or 600 if the second font. The logical way to do this is to specify `font-weight: 550`, however with the current algorithm this would map to 700 rather than 500 in the first font. There is no way to specify this choice with the current algorithm.

**Comment by tabatkins** [comment]
We're somewhat limited by historical design here; when font-weights were limited to the multiples of 100, the rules were:

* If the requested weight is 400 or 500, see if the other weight exists; otherwise find the largest weight less than 400, otherwise find the smallest weight greater than 500.
* If the requested weight is less than 400, find the largest weight less than the request; otherwise find the smallest weight greater than the request.
* If the requested weight is greater than 500, find the smallest weight larger than the request; otherwise find the largest weight smaller than the request.

These rules more or less have the effect of dividing the weight space into three categories - "light", "medium", and "heavy", and searching within the requested space before going elsewhere.  They also encode an intent of "if you're asking for something light, and you don't find it, you'd probably prefer something even lighter rather than something closer to medium" and the reverse for heavy.

Now that we allow any integer in the 1-1000 space, the rules are written to be more explicit about this - if you ask for 398, and the only weights are 1 and 399, you'll get 1.  The three categories are now (1-399), (400-500), and (501-1000).

While the above example is a *little bit* ridiculous, the alternative would be to come up with a much more complex relative weighting scheme, so that the browser would *prefer* to select lighter weights, but would choose a heavier weight if it's much closer than the closest lighter weight (and vice versa for heavy, and something more complex for medium weights).  In practice this would rarely come up, and a much simpler rule does the job just fine.

Note that in complicated cases, you can always set up several `@font-face` rules and manually map them to a particular chosen weight, so you know for sure what the weight you need to use is.

**Comment by neilj** [comment]
Yes, setting up `@font-face` rules to map to different weights is fine for the custom font case. The trouble is if you need to use built-in fonts, and you want to map a different weight for the Windows vs Mac system fonts, to take a real-world example.

I know backwards-compatibility constraints may prevail, but I suspect most developers that haven't read the spec would intuitively expect the "nearest" weight to apply rather than the more complex partitioning algorithm that we currently have. It seems simpler and more useful to me.

**Comment by litherum** [comment]
Yeah, @tabatkins is right. If we ignore backwards compatibility and change the algorithm, many (most?) fonts will change in the wild, and everyone will get mad that their websites "broke." I have seen users complain when I wrote buggy code by accident, so doing this willingly is not acceptable.

**Comment by tabatkins** [comment]
Specifically, *when using built-in fonts*, most authors (myself included) don't know what weights are actually installed. We just use the keywords, or *sometimes* some numbers, and change things around until they get us the visible weight we want.

**Comment by litherum** [comment]
Thanks for raising this issue; we'd love to improve this but we feel constrained about compatibility. Please reopen this if you can find a way around the compatibility issue.
