### ISSUE TITLE
[cssom-view] scrollIntoView({}) dictionary default should match scrollIntoView(true)

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#1720]
Why isn't the IDL as follows:

    void scrollIntoView(optional (boolean or ScrollToOptions) arg = false);

Overloading is better to avoid when possible.

And the dictionary having different defaults than false also seems wrong. Passing {} shouldn't have different results from passing undefined or passing nothing at all.

(Via https://bugzilla.mozilla.org/show_bug.cgi?id=1389274.)

**Comment by zcorpan** [comment]
(Commenting here instead of creating a duplicate issue.)

https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface

annevk suggests the dictionary defaults for scrollIntoView should be the same as omitting the argument and passing in `true` (which is start-nearest). Currently the dictionary defaults are instead center-center, because in https://www.w3.org/Bugs/Public/show_bug.cgi?id=17152 it was argued to be a common case so there should be a convenient way to get center-center.

Due to legacy we can't change the behavior of omitted argument or passing `true`, but I think we can still change the dictionary defaults since they are not yet interoperably implemented. I also think having the defaults match between dictionary and boolean makes for a less surprising and easier to learn API.


| Test case                               | EdgeHTML | Blink | Gecko | WebKit |
|-----------------------------------------|----------|-------|-------|--------|
| http://software.hixie.ch/utilities/js/live-dom-viewer/saved/5300     | top         | center      | top      |  top      |

Current spec:
```
dictionary ScrollIntoViewOptions : ScrollOptions {
  ScrollLogicalPosition block = "center";
  ScrollLogicalPosition inline = "center";
};
```
Suggested change:
```
dictionary ScrollIntoViewOptions : ScrollOptions {
  ScrollLogicalPosition block = "start";
  ScrollLogicalPosition inline = "nearest";
};
```

Related: https://github.com/w3c/csswg-drafts/issues/1367

**Comment by zcorpan** [comment]
cc @SaschaNaz @bzbarsky @travisleithead @RByers

**Comment by bzbarsky** [comment]
Having {} match undefined sounds fine to me from first principles; it's certainly least-surprising.  I can't speak to whether that trumps the reasoning from https://www.w3.org/Bugs/Public/show_bug.cgi?id=17152

**Comment by zcorpan** [comment]
This issue is blocked on
https://github.com/w3c/csswg-drafts/pull/1505
https://github.com/w3c/web-platform-tests/pull/6253

**Comment by zcorpan** [comment]
OK I've now pushed fixes for this issue in the above-referenced PRs.
