### ISSUE TITLE
[css-grid] Error in distribute space to spanned tracks algo

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1729]
Testcase: http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=5307
Spec: https://www.w3.org/TR/css-grid-1/#distribute-extra-space

The spec currently says
> Distribute the space equally to the planned increase of each spanned track with an affected size, freezing tracks as their planned size reaches their growth limits (and continuing to grow the unfrozen tracks as needed). 

However, it's unclear about what "distribute the space" means. It's easy to conclude that it should incorporated by adding to the "planned increase", but actually it needs to be incorporated by ensuring the "planned increase" is at least that amount, i.e. by `max()`ing with the "planned increase".

This is necessary to ensure the spec's stated goal of “(This prevents the size increases from becoming order-dependent.)” The result should be as Chrome currently calculates it: if you have a series of items spanning two tracks each, then the tracks should be equally sized.

**Comment by fantasai** [comment]
Note: This error is a mistranscription of the original Microsoft algorithm, see description at the top of https://www.w3.org/TR/2014/WD-css-grid-1-20140123/#function-ResolveContentBasedTrackSizingFunctionsForItems

**Comment by astearns** [comment]
Reopening for testcase need.

**Comment by zcorpan** [comment]
@tabatkins can you point to the testcase in web-platform-tests? If there isn't one, this should be open?

**Comment by tabatkins** [comment]
No, we reversed the "must leave the issue open until it gets a test" decision, because it made things too noisy for differentiating between whether an issue was addressed or not.

(Also, next time you want to ask the same question on a dozen issues, maybe just ask it once and link to the other issues, or do the asking out-of-band? Now I have to decide between responding to every single issue again, or making it look like I'm just leaving you hanging on all the other threads.)

**Comment by zcorpan** [comment]
OK, thanks.

(Yeah, sorry about that. I'll clean it up.)
