### ISSUE TITLE
[css-scoping] Clarify that ::before/etc allowed after ::slotted()

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1747]
In <https://github.com/w3c/webcomponents/issues/655> a question was raised about whether you could style the ::before/etc pseudos of a ::slotted() element, and what the syntax would be for it.  I argued that it should be allowed, with `::slotted()::before` syntax.  Rune says this is easy, and even wrote a quick implementation with tests (all it took was some selector-parsing tweaking; the rest of the machinery worked automatically).

Just confirming that this is fine with the rest of the group before I make the change to the spec.

**Comment by annevk** [comment]
Wouldn't Selectors also need to be changed for this? I'm pretty sure it currently forbids things like this.

**Comment by rune-opera** [comment]
Selectors Level 3 says that one pseudo element may be appended[1].

The current level 4 draft says they may be followed by user action pseudo classes, but there is also a section showing an example of pseudo elements with internal structure[2], namely ::content, which is a bad example since it's no longer in a spec.

In the current level 4 draft there's also:

"Note: Note that, unless otherwise specified in a future specification, pseudo-classes other than the user action pseudo-classes are not valid when compounded to a pseudo-element; so, for example, ::before:first-child is an invalid selector."

The selectors spec could say something about pseudo elements specified in other specs may explicitly allow other selectors to follow such pseudo elements.

[1] https://www.w3.org/TR/css3-selectors/#selector-syntax
[2] https://drafts.csswg.org/selectors-4/#pseudo-element-structure

**Comment by tabatkins** [comment]
Yeah, it's a minor change to Selectors, no problem there.

**Comment by AmeliaBR** [comment]
I definitely agree that this use-case is sensible and necessary, but it would be nice to take a hard look at the Selectors spec & see if it can be re-written to have a more organized classification for which pseudoelements can or can't combine.

That way, a new spec could just define a new selector as being in X class, instead of trying to define all the particular combinations and interactions.

**Comment by tabatkins** [comment]
Currently (before the resolution this morning) the answer was "none of them", so we didn't need any categorization.  Now there's *one* combination, not enough to successfully generalize yet.  If/when we get more, then yes, we'll categorize as appropriate.
