### ISSUE TITLE
[css-scroll-snap] Consider introducing a term for the boxes creating scroll snap areas

### ISSUE THREAD

**Issue by alrdytaken** [w3c/csswg-drafts#1760]
The specification is about a `````scroll container`````and items/boxes/elements which are aligned using there `````scroll snap area`````and the `````scroll container's snapport`````.

At the moment the items/boxes/elements are referenced to as so:
`````[…] properties on the elements […]`````, `````[…] snapping this box to […]`````, etc.

I'd find it easier to read and explain if the items/boxes/elements had an own term. Like i.e. flex box has `````flex-items`````

I'd propose: `````scroll snap items`````

**Comment by tabatkins** [comment]
The thing being snapped is the "scroll snap area", which already has a term. There doesn't seem to be a particular reason to have a term for the boxes themselves, as we don't refer to them outside the definition of "scroll snap area".

**Comment by alrdytaken** [comment]
Well, I still think it's not as easy to read …

_"[…] positions that produce particular alignments of **content** within a scroll container […]"_

_"[…] specified as a particular alignment of an **element**’s scroll snap area […]"_

_"[…] area that is used for snapping this **box** to the snapport […]"_

as it would be when replacing **content**, **element** and **box** with _scroll snap item_ including a reference to the definition, _"any descendant of a scroll container"_ or whatever.

**Comment by fantasai** [comment]
The first two are in the introduction to the spec, and the purpose of that section is to introduce the general concept without excess jargon.  The last one is the actual definition of 'scroll snap area', which, as @tabatkins explained, is the term we are using for the thing that's actually getting aligned (and is used consistently throughout the rest of the spec). We can't very well define a term in terms of itself.

Closing this one out, because I don't think that creating and using jargon in the introductory paragraph is helpful, and because 'scroll snap areas' is correctly a) defined not in terms of itself but in terms of other things, as it should be and b) used consistently throughout the spec to refer to the thing being snapped/aligned.
