### ISSUE TITLE
[css-fonts-4] @font-face unicode-range and first available font

### ISSUE THREAD

**Issue by SergeyMalkin** [w3c/csswg-drafts#1765]
CSS-Fonts-4 defines first available font as "the first available font that would match any character given font families in the font-family list (or a user agent’s default font if none are available)". As I interpret this, following css and html should use Arial metrics as a source for ex unit:

```
@font-face {
    font-family: Test;
    src: local('Arial');
    font-weight:400;
    unicode-range: U+4??;
}
<div style="font-family:Test; line-height:10ex;">Should be as high as 10ex of Arial</div>

```
Edge is doing what I expect. But Chrome will no use Arial unless there is no unicode-range descriptor or (from my experiments) unicode-range has any value that covers U+0020 space character.

This has effect on performance of @font-face font downloads. Without additional restrictions, we will load extra fonts that would not normally be used because of unicode-range filtering. 

Do I interpret the spec correctly?

Repro page: [https://jsfiddle.net/fdsmzn6j/12/](https://jsfiddle.net/fdsmzn6j/12/)
Definition of first available font: [https://drafts.csswg.org/css-fonts-4/#first-available-font](https://drafts.csswg.org/css-fonts-4/#first-available-font)

**Comment by litherum** [comment]
WebKit does something similar. See https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/graphics/FontCascadeFonts.h#L129 (FontCascadeFonts::primaryFont())

**Comment by SergeyMalkin** [comment]
Should this be in the spec, then?

**Comment by upsuper** [comment]
I think Gecko's behavior here is that, the first available font which has `unicode-range` covers whitespace is used. That says, in the test case provided above, we should match behavior of Blink and WebKit, but if a local font (not defined by @font-face rule) is checked, it will be used unconditionally (because it doesn't have `unicode-range` specified). I'm not sure whether this could be a problem, or does it match other browsers' behavior.

**Comment by svgeesus** [comment]
>  if a local font (not defined by @font-face rule) is checked, it will be used unconditionally (because it doesn't have unicode-range specified)
It doesn't have a unicode-range _specified_ but it does have one _defined_. The initial value of the unicode-range descriptor is `U+0-10FFFF` 
https://drafts.csswg.org/css-fonts/Fonts.html#unicode-range-desc

**Comment by svgeesus** [comment]
> RESOLVED: Change spec text to read first available font that would match the U+0020 (space) character

The spec being Fonts 4, or Fonts 3 as well? The same text is in Fonts 3, section 5.2. Matching font styles.

As Fonts 3 is in CR we need a test for every spec change. I volunteer to write the test for this, and to send the PR to WPT.

**Comment by litherum** [comment]
Yeah, it'd be in both specs.

**Comment by frivoal** [comment]
I am running into this as I was working on #1798. I am not sure what the implications of this resolution are.

Say you have
```css
@font-face {
  font-family: foo;
  src: url("http://example.com/foo.woff");
  unicode-range: U+0061;
}
p { font-family: foo, arial; }
```
```html
<p>a</p>
```
According to the resolution, foo isn't the first available font, right? Does it mean that:
1. foo is not used at all and the `<p>`'s `a` is displayed in Arial?
2. foo is used and the `<p>`'s `a` is displayed in foo, but foo is still no considered the "first available font", which has implications on various other things, such as the explicitly listed font relative units, as well as line-height measurements as they also talk about the first available font, and possibly other things which care about the first available font (what things?)
3. foo is used and the `<p>`'s `a` is displayed in foo, but foo is still no considered the "first available font" for the exclusive purpose of the font relative units, not for any other thing that mentions "first available font".

(1) isn't what anybody does, so I presume that's not what we meant. We probably should add a note clarifying that this is not what we meant.

Between (2) and (3), I am not sure which one we meant.

In #1798, @kojiishi is understanding is this resolution to cover more than just the font relative units, and also apply to calculations about the line height and the height of the content area of non replaced inlines, which would match the (2) interpretation.

If we meant (2), then the spec needs to be clearer about that as well. Also this would be a breaking change for all browsers other than Chrome (see #1798). Based on the minutes above, it does not seem clear that there was a general understanding this resolution would mean a change for most browsers.

If we meant (3), we need to be more explicit that it doesn't apply to other things, and we also need to define what is the first available font for the purpose of the other things. Also, if we meant (3) rather than (2), then we probably need to carve out an exception for the `lh` and `rlh` font relative units, since they are meant to reflect `line-height` calculations, that (3) excludes.

**Comment by svgeesus** [comment]
Here is another example, where part of the text is displayed in the first font in the stack, but the second one is the "first available font" due to the unicode-range.

```
@font-face {
    font-family: swishamps;
    src: url(fonts/Rochester.woff);
    unicode-range: U+26;
}
@font-face {
    font-family: Arvo;
    src: url(fonts/Arvo.woff)
}
h1 {
	font-family: swishamps, Arvo, serif;
}
<h1>This & That</h1>
```
Arvo is the first available font here, and is used for line height calculations. Rochester is used only for the swishy ampersand.

**Comment by fantasai** [comment]
RESOLVED:  To define first available font more strictly  in the fonts module and leave it undefined in 2.1

**Comment by svgeesus** [comment]
@SergeyMalkin the edits have been made to both Fonts 3 and Fonts 4 (thanks @frivoal ) just checking you are satisfied with the resolution.
