### ISSUE TITLE
[css-grid] Reconsider the meaning of 1fr

### ISSUE THREAD

**Issue by svillar** [w3c/csswg-drafts#1777]
We have been getting many [reports](https://jsfiddle.net/utasir/kxy06m6b/) from authors about potential bugs in our implementations related to the beaviour of fr units. The problem is that `1fr` right now means `minmax(auto, 1fr)` and that's something that is not very well known/understood by authors.

The fact that `auto` is the min track sizing function has a lot of implications and in some cases produce completely different results to the ones expected by web developers. There is a good example in the link above. I'll try to explain what's going on. This is a reduced version of the example for reference

 ```html
<html>
   <body>
      <label>Some text</label>
      <main>
         <div><p>Some long text...</p></div>
```

the `<html>` has a definite height. Then the `<body>` has `height: 100%` which is still definite. The `<body>` is a grid and its second row is `1fr`. There is a grid item (`<main>`) in that row which turns out to be a grid as well. That item is sized with `height:100%`. Intuitively a web author would think that particular height is still definite, because 1fr "naturally" resolves to the size of `<html>`as everything in between is `height: 100%`.

The "problem" is that `1fr`resolves to `minmax(auto, 1fr)` and this means that we **need** to know the size of `<main>` before resolving the size of the `1fr` track (because the min track sizing function is content sized, it's `auto`). As the height of `<main>` is a percentage of an indefinite size (remember that the track size is still not resolved) it must be treated as auto. That makes the `<main>` grow to fit their contents and effectively overflow the grid container (as the height of the contents is larger than the final value of `1fr`).

There is a quick solution to this issue from the author POV, just replacing `1fr` by `minmax(0px, 1fr)` for example. The thing is that apparently most authors expect 1fr to behave in a different way, they don't expect 1fr to respect the min-content contribution its contents but instead "use the available space if any". I do think we should provide the most "logical" behaviour from authors' POV as default instead of forcing them all to do this kind of "hacks" to achieve the desired results.

WDYT?

**Comment by svillar** [comment]
[This is a slightly simplified](http://jsbin.com/juranokile/edit?html,css,output) test case, the original one has some other stuff that is not related to this particular issue.

This is the final rendering with `grid-template-rows: auto minmax(0px,1fr)` (left) vs `grid-template-rows: auto 1fr` (right).
![fr](https://user-images.githubusercontent.com/1826122/30019786-0562dc66-9162-11e7-897a-3678a41bbf58.png)

**Comment by FremyCompany** [comment]
I could be convinced otherwise, but my preference here would be to fix this like we did for tables, by changing the minimum height of direct chidren of a grid cell that have an height dependent of their parent (height: auto/%) and scrollable overflow (auto/scroll) to be 0 instead of min-content.

Changing how fr behave looks to be a way bigger change I am not convinced would not cause more problems than it would solve.

**Comment by rachelandrew** [comment]
I think that the expectation here from authors is different when it comes to rows vs. columns. The behaviour with regard to columns seems to make sense to people when it is explained. For example, in workshops I create a 6 column grid, intending to position items. Until I do they are all auto-placed into tracks and the content forces a track wider than it being one sixth of the available space. Someone will invariably notice that one of the tracks is wider and ask if these are not supposed to be equal, but the explanation seems to make sense to people.

However I can see why this rows example in this issue would be confusing to people, and I think that @FremyCompany has a reasonable suggestion there. I think changing how fr behaves for columns might be more confusing to people and is definitely a bigger change that might cause issues with existing layouts. I'm assuming there that more people are going to be using 1fr column-wise than are row-wise and are just relying on a bare `1fr` etc. not using minmax.

**Comment by jensimmons** [comment]
I really hesitate to change this. The way fr units are defined now is incredibly useful. 

Educating people in the difference between using 1fr unit vs minmax(0,1fr) is a good solution here. People should understand the potential of minmax() and all the possibilities that Grid brings. I know that might seem like a lame answer, given how many people read overly-short link-batty blog posts on new technology and think they are done. But there are people out there working to give people a full understanding of Grid. We have great hope the industry can learn all this. 

It's also likely too late to make such a change, as sites have already shipped using fr units in Grid.

**Comment by tabatkins** [comment]
This sort of behavior is common between Grid and Flexbox; if you set up the same examples in Flexbox you'll get the same "somethings things get too tall" problem.  I don't want to make any change to Grid specifically, then; anything we do should be generic and apply to them both.

And note that there are two possible ways to "fix" the problem here; either setting the track to an explicit min of 0, *or* setting the item to `overflow: auto`.  (For example, setting `main { overflow: auto; }` in the first example Manuel links "fixes" the problem just fine.)

A possible generic fix that @fantasai came up with is, when determining the min-content contribution of a grid or flex item in the block axis, let the min-content contribution be 0 (or rather, it's min size per other properties, ignoring its content) for items with non-visible overflow (with this definition being recursively applied).

Dunno how safe this is, or what effects it might have on existing sites.

**Comment by jensimmons** [comment]
Dave Rupert recently wrote a blog post explaining the problem people are hitting:
http://daverupert.com/2017/09/breaking-the-grid/

**Comment by fantasai** [comment]
The CSSWG resolved to close this issue as no-change partly because in a different subset of cases, the current behavior is desired, and partly because the existing deployed behavior is being relied on. Workarounds exist, such as using `minmax(0, 1fr)` or setting an individual grid item’s `min-width`/`min-height` to an explicit value other than `auto`. A separate issue #1865 has been filed on attempting to find a way to automatically yield the right behavior in some more of the more common cases.

@svillar Can you confirm whether you find this resolution acceptable?

**Comment by svillar** [comment]
I'm OK with the resolution
