### ISSUE TITLE
[css-flexbox] Flexbox spec uses inconsistent terminology: "Implied Minimum Size" vs "Automatic Minimum Size"

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#1780]
Flexbox Section 4.5 is titled "[Implied Minimum Size of Flex Items](https://drafts.csswg.org/css-flexbox-1/#min-size-auto)" -- however, this term used in the title ("Implied Minimum Size") is **never defined** and has zero usages in the spec's prose, outside of that title (and footnotes about change history).

Instead, the spec's prose uses a different term, "Automatic Minimum Size", which was introduced in [this commit](
https://github.com/w3c/csswg-drafts/commit/54c4c0c958537738cdaf005bc4b915105a99de46) and which seems to refer to the exact same concept. Here's a quote, showing the discrepancy:

> 4.5. **Implied Minimum Size** of Flex Items
> [...]
> In general, the **automatic minimum size** of a flex item is ...
https://drafts.csswg.org/css-flexbox-1/#min-size-auto

For consistency (and to avoid suggesting that there's an additional vaguely-defined concept in play), the title of this section should probably use the same term that we use in the prose -- i.e. the title needs `s/Implied/Automatic/`.

The exact same is true of Grid, too, BTW ([section 6.6](https://drafts.csswg.org/css-grid-1/#min-size-auto) over there).
>  6.6. **Implied Minimum Size** of Grid Items
> [...]
> The **automatic minimum size** for a grid item in a given dimension is ...
https://drafts.csswg.org/css-grid-1/#min-size-auto

CC @fantasai  @tabatkins

**Comment by tabatkins** [comment]
Sounds reasonable to me.

**Comment by fantasai** [comment]
Fixed. The reason, btw, that we used “Implied Minimum Size” rather than “Automatic Minimum Size” is because the automatic minimum size is particular calculation, which may or may not be used as the minimum depending on the value of `min-width`/`min-height`. What this section does is more than define the automatic minimum: it defines a new keyword for these properties that triggers that automatic minimum _and makes it the initial value_.

**Comment by dholbert** [comment]
Thanks!  (And thanks for the historical clarification RE "implied" -- makes sense.)
