### ISSUE TITLE
[css-align] Use of word 'justify'

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1789]
https://drafts.csswg.org/css-align/

The spec has properties with names like `justify-content`, `justify-self` and `justify-items`.

A much more appropriate alternative, imho, would be `arrange-content/self/items` (borrowing from Powerpoint's UI).  (If we wanted to go further we could  swap `arrange-content` and `align-content` (etc) so that `align` refers to inline direction, and `arrange` to line-stacking direction, because that works better with the current `text-align` concept.)

This worries me because content authors already have difficulties understanding the difference between text-align: justify and the text-justify property, and now we seem to be introducing another sense for 'justify', for something which i actually think is alignment rather than justification. For me (and for Bringhurst) justification is to do with _setting text flush left and right_ on a line. (Note the words 'text', and 'flush'. Some of the justify- options in css-align don't produce flush alignments.)

Other possibilities might be `line-align` vs. `stack-align`, etc.. But i don't think `justify` is appropriate or helpful here.

The i18n WG endorses this comment.

**Comment by fantasai** [comment]
Hi Richard,
I'm sorry to say we can't do anything about the names of these properties now. They were released with the initial release of Flexbox back in [2012](http://www.w3.org/TR/2012/CR-css3-flexbox-20120918/), and have been widely deployed on content ever since. We're going to have to close this issue as no-change.

I think if we were to go back in time, we would have made the axes 100% flow-relative and just used inline- and block- as prefixes. But too late now!

**Comment by r12a** [comment]
The i18n WG agreed to close this issue.
