### ISSUE TITLE
[css-ui-3] using non fixed size SVG in the cursor property

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1813]
About the cursor property, css-ui-3 says:
> The UA must support the following image file formats:
> * [...]
> * SVG, as defined in [SVG11], in secure static mode [SVG2] 
>
> In addition, the UA should support the following image file formats:
> * [...]
> * SVG, as defined in [SVG11], in secure animated mode [SVG2] 

Since it doesn't specify any exception, that includes SVG with non fixed sized. However, no browser implement that. See these test results: https://test.csswg.org/harness/details/css-ui-3_dev/cursor-image-005-nfs/

Unless we have 2 browser just about to implement support for non fixed sized SVG cursors, I suggest we punt this feature to level 4, and only require support for fixed size SVG in level 3.

> The UA must support the following image file formats:
> * [...]
> * SVG, as defined in [SVG11], in secure static mode [SVG2], if it has an intrinsic size.
>
> In addition, the UA should support the following image file formats:
> * [...]
> * SVG, as defined in [SVG11], in secure animated mode [SVG2], if it has an intrinsic size.
>
>
> In addition, the UA may support the following image file formats:
> * [...]
> * SVG, as defined in [SVG11], in secure static mode or secure animated mode [SVG2], even if it does not have an intrinsic size.

**Comment by frivoal** [comment]
Ramblings on IRC on this topic: https://log.csswg.org/irc.w3.org/css/2017-09-13/#e872693

**Comment by AmeliaBR** [comment]
What currently happens in browsers? Do they use the SVG, but scale it to 0px square? Or do they ignore it like a broken image, and fall back to default system cursors?

I would prefer a platform-specific default size, rather than ignoring it altogether.  If we plan to add in defaults later, it might be best to word it as "This specification does not define a default size if the referenced image does not have an intrinsic size; authors should be aware that many user agents currently do not render the image at all in those cases."

Also, that warning should be generic (for images without intrinsic size), rather than specific to SVG. Hypothetically, user agents could support other image formats that don't have intrinsic sizes.

**Comment by AmeliaBR** [comment]
PS, by "platform-specific default size", I meant "based on the size of the system cursors", in case that wasn't clear. A 300px by 150px cursor is probably not a good default.

**Comment by frivoal** [comment]
> What currently happens in browsers? Do they use the SVG, but scale it to 0px square? Or do they ignore it like a broken image, and fall back to default system cursors?

The later. Well, they fallback, but not directly to system cursors, they fallback to the chain you've defined. If you have `cursor: non-fixed.svg, fixed.svg, foo.ico, resize`, browsers that support svg in cursors (all but Edge) will fallback to fixed.svg, Edge will fallback to foo.ico, and a theoretical browser that supported none of this would fallback to `resize`.

> I would prefer a platform-specific default size, rather than ignoring it altogether.

That is what the spec currently calls for:

> The `default object size` for cursor images is a UA-defined size that should be based on the size of a typical cursor on the UA’s operating system.

where `default object size` is a term that redirects to the css-image spec, which results in what you'd want: display  non-intrinsically sized images at the largest size that fits within `default object size` without distorting its aspect ratio if it has one.

> A 300px by 150px cursor is probably not a good default.

Indeed:) 16x16 is likely a better starting point (in device independent CSS pixels, so 32x32 on a retina screen, and so on), keeping in mind that this isn't the largest size, but the default size.

**Comment by AmeliaBR** [comment]
OK, working on actual spec text.

The [current text in CSS UI 3](https://drafts.csswg.org/css-ui-3/#cursor):

> The UA must support the following image file formats:
>
> - PNG, as defined in [PNG]
> - SVG, as defined in [SVG11], in secure static mode [SVG2]
> - any other non-animated image file format that they support for `<image>` in other properties, such as the the background-image property
>
> In addition, the UA should support the following image file formats:
> 
> - SVG, as defined in [SVG11], in secure animated mode [SVG2]
> - any other animated image file format that they support for `<image>` in other properties, such as the the background-image property
>
> The UA may also support additional file formats.
>
> ...
>
> The default object size for cursor images is a UA-defined size that should be based on the size of a typical cursor on the UA’s operating system.

As I'm reading the IRC notes (sorry I missed the call), the changes should be:

- Add a qualification to both "The UA must support the following image file formats" and "the UA should support the following image file formats", saying "for images with [intrinsic dimensions](https://drafts.csswg.org/css-images-3/#intrinsic-dimensions)". (Added at the top of the list, not in the SVG bullet point, so that it includes both SVG and the "any other format" item).

- After "The UA may also support additional file formats" add something like "In particular, the UA may support images without intrinsic dimensions, by using a UA-defined default object size for cursor images, which should be based on the size of a typical cursor on the UA’s operating system."

- (Then remove the extra paragraph that has been moved up into the "may" section.)

- Maybe (?) add an informative note explaining that the CSS WG would really like to add normative support for cursors without intrinsic dimensions, if only UAs would be so kind as to implement it.

I personally would have argued for adding no-intrinsic size to the "should" list, instead of "may" but... anyway. Not a big difference in practice.

**Comment by AmeliaBR** [comment]
PS @frivoal s/indented/intended/ here

https://github.com/w3c/csswg-drafts/blob/5dcad3014735dbe9828273d952e2eb3115f33d5b/css-ui/Overview.bs#L979

Also, I'm not sure if Bikeshed will auto-link "intrinsic size" to CSS Images, but it would be nice to have that link.  (To the section on ["intrinsic dimensions"](https://drafts.csswg.org/css-images-3/#intrinsic-dimensions).)

**Comment by frivoal** [comment]
Pull request for updating the relevant test here: https://github.com/w3c/web-platform-tests/pull/7430
