### ISSUE TITLE
[css-ui-4] let user-select:contain prohibit selection from outside

### ISSUE THREAD

**Issue by yoichio** [w3c/csswg-drafts#1815]
https://drafts.csswg.org/css-ui-4/#valdef-user-select-contain

`user-select:contain` stops selection leaking from inside to outside, but often
 we want to prohibit selection from outside.
For `position: absolute`, we want selection on normal layout elements to skip over the abs elements but
 also want user to be enable to select the element.
For form/editable element,  it is also strange that selection from outside can go into the form.

How about make `user-select:contain` more strict that prohibits selection transit?

**Comment by frivoal** [comment]
So in essence, you would like a change from this sentence
> The UA must allow selections to extend across this element, and such selections must include the content of the element.

to

> The UA must allow selections to extend across this element, and such selections must **not** include the content of the element.

Maybe this is a good idea instead of the current behavior, or maybe this is a good idea of an additional value with a different behavior.

However, we have a problem: For this to work, we would need selections that can contain multiple  DOM ranges. Currently, only firefox supports this, and as far as I know, no other browser plans to implement that behavior.

If it would be acceptable to have the behavior you ask in browsers like firefox (and probably only firefox), and to keep the current behavior everywhere else (similarly to how user-select:none skips the content in Firefox only), then we can do this. Not saying everyone will agree, but at least it is arguable possible. Otherwise, I don't think we have a realistic path forward.

**Comment by frivoal** [comment]
I don't mind specifyng this (probably as an `user-select: [ current values ] || skip` if there is interest from browsers, but other wise it is not a useful exercise. Adding it to the Agenda to see if this is worth considering or not from that point of view.

**Comment by frivoal** [comment]
actually, if I were to spec this it would probably be `user-select: auto | text | all | [ [ none | contain ] skip?]`

**Comment by astearns** [comment]
@frivoal should this go on the weekly agenda, since we didn't get to it at the F@F meeting?

**Comment by frivoal** [comment]
@yoichio 

The existing behavior, which is not to skip over such elements, is interoperable. Even when the value is not explicitly supported, the behavior is the one you get on  (for example) a textarea.

If you have strong use cases that justify changing from what people currently do, we can reopen, but otherwise, the WG has decided to close as wontfix and to keep the specification (and implementations) unchanged.

We'd appreciate if you could let us know whether that's acceptable to you (and if not, why not).

**Comment by yoichio** [comment]
Thanks for discussing about this.
O.K. Since we don't have any strong request from user, let it be wontfix.
