### ISSUE TITLE
[css-color] spec is confused about initial value of 'color'

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1851]
[CSS 2.1](https://drafts.csswg.org/css2/colors.html#q1) says that the initial value of 'color' is UA-defined, and gives no further details.  [Color 3](https://drafts.csswg.org/css-color-3/#foreground) maintains this.

[Color 4](https://drafts.csswg.org/css-color/#the-color-property) keeps that wording in the "Initial Value" section, but then immediately says the initial value is "black" in the prose.  HTML also says it should be black.

This is confusing and weird? I presume that the UA dependence was initially to allow for a11y concerns (letting the UA default the canvas to a dark color and the text to a light color), right? (Or maybe to accommodate console browsers?)

Do we still need this, or can we just say that the initial value is `black`?

If we can't, we at least need to clean up the wording in Color 4, as it currently contradicts itself in a confusing manner.

**Comment by svgeesus** [comment]
The UA dependence was because in CSS1 days, we were thinking of green-screen visual display units and all sorts of stuff, and generally doing a lot of "UA decides, do whatever". Over time, CSS has pushed to be better specced and more interoperable and dependable.

Given that, I think that `black` is the correct initial value, and proposed to move that from the prose into the actual propdef table.
