### ISSUE TITLE
[snapshot] Copy document conventions (and conformance?) from 2.1

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1867]
The most recent definition of how to actually read the propdef blocks is still in 2.1. There's no other more appropriate CSS module for this, as it's meta knowledge, not any particular feature.  The snapshot seems like the best place to have it live.  (I can then redirect the newly-added propdef `th` links to those sections.)

Relatedly, we copy the conformance boilerplate in every single module. Much of it used to be in snapshot, but was moved out when the snapshot was made non-normative.  Can we do something about that?

**Comment by frivoal** [comment]
Wouldn't the definition of how to read the propdef table be considered normative text (because if it isn't, propdefs do not have any unambiguously normative meaning)? That seems to exclude the snapshot as a host for them. If we were to start a css-core or css-meta spec of sorts, would there be anything else to put in there?

Maybe:
* https://www.w3.org/TR/CSS21/intro.html#q2.0
* https://www.w3.org/TR/CSS21/about.html#conventions
* https://www.w3.org/TR/CSS21/conform.html#text-css

> Relatedly, we copy the conformance boilerplate in every single module. Much of it used to be in snapshot, but was moved out when the snapshot was made non-normative. 

We already have the "Requirements for Responsible Implementation of CSS" subsection of the "Conformance" section. I agree with having the whole thing in there.

**Comment by svgeesus** [comment]
Removed the process help flag. It just means snapshot 2018 will be a FPWD, and when snapshot 2019 is published then snapshot 2018 gets republished as a note.

**Comment by frivoal** [comment]
Actually, I'd like to revisit this. the part about propdef blocks is being solved in #1139.

So the only thing left here is removing the #conformance section from every spec, and adding to the snapshot instead. Do we actually want to do that? Even if you say it's doable with the process, it seems quite weird to me that every spec would have a normative dependency on something that only ever is either a WD or a Note. So whenever something goes to REC, wait a bit, and the conformance section which it incorporates by reference to a snapshot becomes non normative as the latest WD snapshot is retired into a note to make room for the following years snapshop…

That doesn't make very much sense to me.

**Comment by svgeesus** [comment]
It does seem weird, I agree. Let's not do that.

A separate normative document (see [this CSS Conventions prototype, for instance](https://xfq.github.io/specs/css-conventions/) by @xfq makes a lot more sense to hold that sort of thing.

**Comment by svgeesus** [comment]
OK so I read this as not blocking publication of snapshot-2018

**Comment by frivoal** [comment]
I agree. Since this was sort of a group consensus (despite the lack of an actual resolution), we might want to go back to the group before giving up on the idea entirely (hence agenda+), but that is certainly my stance.

**Comment by fantasai** [comment]
I think that's supposed to say “Pull boilerplate from the end of the documents into its own module”, not “Push boilerplate to the end of the document”. @frivoal Can you clarify?

**Comment by frivoal** [comment]
Ah, sorry. I didn't check the resolution in real time. It is supposed to say:

Resolved: Do not migrate the conformance boilerplate from the end of all specs to the snapshot

Separately from that, we had some degree of agreement that we should probably start a distinct document meant to normatively host this boilerplate, so that we could link to it from all specs, but I was not under the impression that we actually concluded on a concrete action to create it (no name, no editor, etc).

At least, that is how I interpreted our discussion. Chairs, can you confirm @atanassov @astearns
