### ISSUE TITLE
[css-overflow] shrink text

### ISSUE THREAD

**Issue by Array23** [w3c/csswg-drafts#1875]
Basicaly if text won't fill in, the text would be choped, to it's maximum fittable characters
option 1: preserve words... text would end up not trimming in middle of word, but in by words
option 2: string it would end by...

so 
`
overflow: chop;
chop: <words || characters>, <'...'>
`
so..
`... is the string it would end up inner text by`

**Comment by frivoal** [comment]
We already have `text-overflow` in [css-ui-3](https://drafts.csswg.org/css-ui-3/) that does something similar, but line by line, instead of the whole paragraph.

For the whole paragraph, this is something we're aware of, and have started working on, but it is actually a surprisingly difficult problem. Have a look at [css overflow 4](https://drafts.csswg.org/css-overflow-4/), starting at [Fragmentation of overflow](https://drafts.csswg.org/css-overflow-4/#fragmentation) and everything below, for the project that might eventually end up delivering this.

I expect this will happen eventually, but don't hold your breath.

**Comment by Array23** [comment]
I could take advantage of my ASCII fetish in character breaking...
Looks good. I will take deeper look in a month or so, keeping it on to-do list.

**Comment by frivoal** [comment]
This is now being worked out in #390 and [css-overflow-3](https://drafts.csswg.org/css-overflow-3/#line-clamp).

Closing.
