### ISSUE TITLE
[css-multicol] how does absolute positioning work in a containing block that was split by a column-span?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1894]
I'm filing this based on a discussion I just had with @neerjapancholi.  It is related to #1072.

It's not clear to me from the spec how absolute positioning works when the containing block for absolutely positioned elements is split by a column-span.

In particular, if you have markup like:

```html
<div style="column-count: 3">
  <div style="position: relative">
    ... position A ...
    <h2 style="column-span: all">... position B...</h2>
    ... position C ...
  </div>
</div>
```
then it should be clear what the absolute containing block is for elements at position A, at position B, or at position C.  (Consider use of both `top` and `bottom`.)

I haven't tested what current implementations do.

One possibility is that they act as though the `div` with style `position:relative` was split into three parts, and elements at positions A, B, and C position relative to the appropriate part.  Another is that behavior happens at positions A and C, but elements at position B fall back to the next absolute containing block outside of the outermost `div`.

**Comment by rachelandrew** [comment]
This doesn't appear to be specified. So I built an example to look at this: https://codepen.io/rachelandrew/pen/rYeagj?editors=1100

Currently it doesn't seem to make any difference if there is a spanner or not, and we don't have interop.

Firefox 58 will always act as if the abspos items are in the first column, so that is the containing block. If the items are positioned right, it puts them at the right hand edge of that column. Stacking them up.

Chrome 64 will act as if the first column is the containing block if items are positioned top, and the last column if items are positioned bottom. So left and right are the relative to that column, again stacked up.

Safari 11 acts like Chrome, except for the item that is inside the spanner. It seems to take context from the viewport.

I'd be interested in anyone's thoughts/use cases as to what would be the best way to resolve this.

**Comment by rachelandrew** [comment]
Closing as this is defined in Fragmentation as resolved at the meeting. If anyone has additional concerns these should be raised against that spec.
