### ISSUE TITLE
[css-backgrounds][css3-background] Consider removing the spread distance adjustment for small border radii

### ISSUE THREAD

**Issue by mstange** [w3c/csswg-drafts#1900]
https://drafts.csswg.org/css-backgrounds-3/#shadow-shape contains this piece of text:

> However, in order to create a sharper corner when the border radius is small, when the border radius is less than the spread distance, the spread distance is multiplied by the proportion 1 + (r-1)^3, where r is the ratio of the border radius to the spread distance, in calculating the corner radii of the spread shadow shape.

This seems to have originally been added in this commit: https://github.com/w3c/csswg-drafts/commit/170e7532494d4cadd7eca8bc86d9fbf2a25767fb

Has this been implemented by any browser? Firefox has not implemented it, and judging by the code [here](https://chromium.googlesource.com/chromium/src/+/85c12763181253aab7759f5e18ddf93f485ff304/third_party/WebKit/Source/core/paint/BoxPainterBase.cpp#140) and [here](https://chromium.googlesource.com/chromium/src/+/85c12763181253aab7759f5e18ddf93f485ff304/third_party/WebKit/Source/platform/graphics/GraphicsContext.cpp#510), Chrome hasn't either.

If there has been no interest from browser vendors, it may be a good idea to remove this section again.

If you decide to keep it, I think the case where the spread amount is negative needs some clarification (and the math may need to be double-checked).

**Comment by fantasai** [comment]
This section was added to create continuity between the shape of the shadow at a border-radius of zero and the shape of a shadow at a border-radius of not-zero. If there's a Web-compat limitation preventing us from implementing it, then we might need to re-evaluate, but if not we do have an interest in improving continuity in behavior for the sake of animations and transitions if nothing else. But also in this case the shadow seems to look more appropriately-shaped if the formula is followed: the curve is seems greatly exaggerated in the shadow otherwise.

I can raise it to the WG if you think the situation needs some re-evalutation, though. Lmk~

[Testcase to play with](http%3A%2F%2Fsoftware.hixie.ch%2Futilities%2Fjs%2Flive-dom-viewer%2F%3F%3C%21DOCTYPE%20html%3E%250A%3Cstyle%3E%250A%20body%20%7B%20border%253A%20solid%20orange%2010px%253B%20border-radius%253A%201px%253B%20box-shadow%253A%2010px%2010px%200%2010px%253B%20margin%253A%2020px%250A%3C%252Fstyle%3E%250A%250ACompare%20the%20corner%20of%20the%20box%20to%20its%20shadow.%20Interesting%20%3Ccode%3Eborder-radius%3C%252Fcode%3E%20values%20to%20try%253A%20%3Ccode%3E0%3C%252Fcode%3E%252C%20%3Ccode%3E1px%3C%252Fcode%3E%252C%20%3Ccode%3E5px%3C%252Fcode%3E%252C%20%3Ccode%3E10px%3C%252Fcode%3E%252C%20%3Ccode%3E20px%3C%252Fcode%3E.)

**Comment by fantasai** [comment]
You can also check out the widget at https://drafts.csswg.org/css-backgrounds-3/spread-radius which shows the various options we looked at for the behavior of r between zero and one.

**Comment by mstange** [comment]
Interesting! That's a very compelling argument. I have two requests, then:
1. Please mention that the purpose of this adjustment is to avoid discontinuous behavior at border-radius: 0.
2. Please clarify the behavior for inset box-shadows. If I understand correctly, for inset box shadows, all occurrences of "spread distance" need to be replaced with the "negative spread distance", because only negative spread distance values cause the border radius to be increased for inset box shadows. Maybe it would be good to introduce another variable here, like "shadow edge inflation", that's set to the spread radius for outset box shadows and the negative spread radius for inset box shadows.

**Comment by fantasai** [comment]
OK, I made two fixes (diffs linked above):
- Added “(and thus ensure continuity between round and sharp corners)” to the sentence describing the adjustment.
- Limited the adjustment to outer shadows only; the spread radius can only be a positive number, so for inner shadows there's no case where the shadow's radii grow.

Let me know if that works for you!

**Comment by dbaron** [comment]
> * Limited the adjustment to outer shadows only; the spread radius can only be a positive number, so for inner shadows there's no case where the shadow's radii grow.

I'm confused by this change; [the spec](https://drafts.csswg.org/css-backgrounds-3/#spread-distance) defines the meaning of negative spread distance, so it seems like this should still apply for negative spread distances on inner shadows.

**Comment by SelenIT** [comment]
Since Chrome implemented the change, some authors started complaining about the new behavior. It seems that taking into accound only _absolute_ values of radius and spread without accounting for the size of the element itself (i.e. _relative_ corner radius) breaks authors' expectations in many practical cases, especially large shadows of fully rounded shapes (`border-radius:50%`) which authors expect to remain completely rounded instead of turning into rounded squares.

Isn't it late to reconsider the adjustment to account for the relative corner radii, e.g. like [proposed here](https://github.com/w3c/csswg-drafts/issues/7103#issuecomment-1135036126)?
