### ISSUE TITLE
[css-fonts-4] font-variation-settings and font-feature-settings what should be returned for getComputedValue

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#1959]
Here is a testcase that we've seen interop issues with: http://jsbin.com/zenosupeke/edit?html,css,output

- Chrome: returns as authored
- Edge: returns as authored
- Safari: returns without dupes

The specification doesn't state what should be returned, it would be good if we could get agreement on what should be returned.

**Comment by litherum** [comment]
WebKit's internal implementation of these settings is a map, which automatically removes duplicates. Purposely adding in duplicates just for the purpose of getComputedStyle() seems like a waste of memory.

Other browsers will have to handle duplication anyway both for animation as well as for the text engine (because an instantiated font can only be drawn at a single position in the variation space). Therefore, they should just hold this de-duped data structure as their internal implementation.

**Comment by dbaron** [comment]
[just discussed](https://log.csswg.org/irc.w3.org/css/2017-11-07/#e910838) in CSS WG meeting

**Comment by litherum** [comment]
RESOLVED: For both font-variation-settings and font-feature-settings, the computed value is a map (and thus specified dupes are removed)

**Comment by gregwhitworth** [comment]
Added a test for feature settings, same results as above. @litherum I think that this should be added to the spec since 3/4 browsers do the opposite of what we resolved on.

**Comment by svgeesus** [comment]
@gregwhitworth could you refactor that jsbin into a couple of WPT tests? One for  font-variation-settings with rel=Help set to css fonts 4, and one for font-feature-settings with rel=help set to css fonts 3. I will review them.

**Comment by gregwhitworth** [comment]
@svgeesus sure thing - assigned to myself

**Comment by svgeesus** [comment]
@gregwhitworth please ping me when you have tests ready to review. Alternately, if you want me to take a crack at converting them, let me know.

**Comment by gregwhitworth** [comment]
@svgeesus ok done - it is linked to this thread

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/6e5884153bd429a4183f01457713714fef2f99b0
