### ISSUE TITLE
[css-scrollbars][css-scrollbars-1] Can we simplify to two scroll-*-color properties?

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#1960]
Can we simplify from seven scroll-*-color properties to just two? (roughly equivalent to foreground/background, stroke/fill)

It appears that scrollbar-face-color and scrollbar-base-color are used either directly for or as input in determining the other colors if the other colors are not set.

We should experiment to see if we can satisfy most use-cases with just two scroll-*-color properties.

In addition, real world examples (see [Bugzilla 77790](https://bugzilla.mozilla.org/show_bug.cgi?id=77790)) appear to typically use just two colors (but repeat them across the seven properties). 

Can we use those examples to help determine just which two properties we need for the 80/20?

(expressed by @upsuper and @smfr)

Update: tracking examples and which properties / unique colors they use here:
* https://www.w3.org/wiki/Css-scrollbars#Use-cases

**Comment by tantek** [comment]
The flow of which properties auto-set which others, from http://www.howtocreate.co.uk/tutorials/scrlbar.html we can derive these:

* scrollbar-base-color vvv
 * scrollbar-3dlight-color
 * scrollbar-face-color
 * scrollbar-highlight-color
 * scrollbar-shadow-color
 * will also turn scrollbar-darkshadow-color black if it is not already (OS dependent)

* scrollbar-face-color and scrollbar-highlight-color vvv 
 * scrollbar-track-color

Unspecified (where it comes from)
* scrollbar-arrow-color

**Comment by nt1m** [comment]
See my comment in https://github.com/w3c/csswg-drafts/issues/1956#issuecomment-344963919

**Comment by craigkovatch** [comment]
Here is our real-world product example that would not be possible with the paradigm being discussed here. (This is in Stylus, please let me know if any of the syntax isn't clear.)
```
// Chrome + Safari
::-webkit-scrollbar {
  width: 6px;
  height: 6px;
  border-radius: 1px;
}

::-webkit-scrollbar-track {
  border-radius: 1px;

  :hover& {
    background-color: $grey_2;
  }
}

::-webkit-scrollbar-thumb {
  border-radius: 1px;

  :hover& {
    background-color: $grey_4;
  }

  &:hover {
    background-color: $grey_6;
  }

  &:active {
    background-color: $grey_7;
  }
}
```

**Comment by mstange** [comment]
I'm in favor of simplifying the list of proposed properties to remove any Windows 95-isms. But I don't think a single fill color and a single stroke color is enough. At the minimum we need the ability to specify a different color on hover, and the ability to use rounded endcaps instead of square endcaps.

**Comment by upsuper** [comment]
I've implemented scrollbar color properties on Windows and macOS in Firefox, and so far there are only two properties necessary: `scrollbar-face-color` and `scrollbar-track-color`.

(Windows implementation has landed behind a pref, while macOS one is still pending on review.)

The following are screenshots from my implementation:
![Custom scrollbar colors on Windows](https://user-images.githubusercontent.com/333750/41881503-3607ebce-7927-11e8-8d76-4461f6698834.png)
![Custom scrollbar colors on macOS](https://user-images.githubusercontent.com/333750/41881506-37b82326-7927-11e8-89fe-689986e0993a.png)

The custom one are done with the following declarations:
```css
.custom {
  scrollbar-face-color: lightblue;
  scrollbar-track-color: azure;
}
```
```css
.custom {
  scrollbar-face-color: #2e4359;
  scrollbar-track-color: #1b2836;
}
```

This is simple to use and native to platforms.

I think we can remove everything else from the list at this point.

**Comment by craigkovatch** [comment]
Strongly, but respectfully, disagree. The web's current use of the existing `-webkit-scrollbar*` along with a number of "custom scrollbar" libraries suggests it's not this simple. Designers want border radii, they want hover colors, they want to be able to change dimensions.

**Comment by jonjohnjohnson** [comment]
I think just these two properties could be good enough, if they allow for colors with a transparent alpha value, for browsers that allow the track to "overlay" the content. And if using scroller styling is spec'd to not inhibit other native system ui, such as losing the whole scrollbar fading in/out on MacOs in chrome when using it's current custom styling properties. I'm mostly concerned about the familiarity side of usability here.

If people want to break further from the users expectations of system scrolling, I figure they can always do something like... https://developers.google.com/web/updates/2017/03/custom-scrollbar

**Comment by upsuper** [comment]
The basic idea behind doing the scrollbar properties approach (rather than the pseudo-element approach) is for giving browsers leeway to render what they think is most sensible for users while still addressing popular usecases required by authors like scrollbars in dark mode / theme / compact.

And yes, authors can always create different style of scrollbars with HTML elements especially, and with Web Components they can be well encapsulated. There can be way more creative way for scrollbars for specific web apps which can never be done with pseudo-element approach either.

This approach is focusing on provide simple and native way to help authors address basic usecases without much effort to deal with platform specific details (which pseudo-element approach is specifically bad on, e.g. scrollbar shape, buttons, etc.).

**Comment by craigkovatch** [comment]
To me the most critical issue to address is making scrolling *visually* customizable without affecting the *behavior* at all. Scrolling is one of the most viscerally important human-computer interactions. We all get muscle-memory accustomed to whatever scrolling behavior is afforded by ones hardware + OS, and it's very important that the browser doesn't try to mess with this. To this end, it's important we don't just say "well if you need more, make a custom scroller" -- because that most often ends with a component that looks good but doesn't *feel* right, and in a very aggravating way.

**Comment by jonjohnjohnson** [comment]
@craigkovatch If you check the google developer article I linked to, it shows a custom, yet "native" nyan cat scrolling example, which hopefully all browsers eventually support. I'd guess this addresses your concern for the _feel_ of scrolling? I'm more concerned with a happy path of styling a scroller that is _visually_ familiar for user experience, especially when I keep in mind many of my visually impaired friends relying on an accessible web.

**Comment by nt1m** [comment]
@upsuper What if a platform decides in the future that scrollbars are no longer flat, and no longer use two colors ? That's well possible because it was the case in the past.

**Comment by upsuper** [comment]
@nt1m browsers may try to derive the colors from the specified colors. Actually you can see that in my current implementation, there are already several colors derived from the two colors in the UI, including the arrow on Windows and the border on macOS.

**Comment by nt1m** [comment]
@upsuper I'd love to see how this works out for Windows 7 aero scrollbars :)

**Comment by craigkovatch** [comment]
@jonjohnjohnson I'd love to understand more about how you think visual familiarity of scrolling is important to visually impaired friends.

Incidentally, I also have a significant visual impairment, and have spent the better part of the last two years working professionally on web accessibility. That's probably why I care so much about scroll experience -- I spend a lot of time zoomed in. I couldn't care less about how scrollbars look -- but I want web designers to have a full set of styling tools available so that nobody ever has to re-implement scrolling. I think scroll experience is a fundamentally OS-level concern and whatever the user is used to shouldn't be mucked with. But if we don't give a full suite of styling tools (ala `-webkit-scroll*`), we encourage re-implementation instead. I think that is a much more unfortunate incentivization.

I'm not saying the old webkit properties ought to be standardized, there's some significant ambiguity to them. But only providing color properties seems woefully insufficient.

**Comment by upsuper** [comment]
Close as it has been simplified to two colors in the current draft.

**Comment by craigkovatch** [comment]
@upsuper this is an unfortunate and upsetting response. This issue has active discussion and lacks consensus. Codifying a standard before that consensus is achieved -- and now having Firefox 64 implement that draft -- ignores the issues that have been raised here. This is not the way the web is supposed to work.

**Comment by craigkovatch** [comment]
@astearns It absolutely prohibits an entire class of additional capabilities in the future -- becuase it assumes the issue to solve is "native scrollbars need some minor adjustments" rather than "scrollbars should be design-able like any other web element".
