### ISSUE TITLE
[css-sizing][css-align][css-text] Aligning an aligned block of text within its container

### ISSUE THREAD

**Issue by palemieux** [w3c/csswg-drafts#1975]
_Per the 20171109 joint TTWG/CSS meeting_

As illustrated at [multiRowAlign.pdf](https://github.com/w3c/csswg-drafts/files/1462969/multiRowAlign.pdf) and specified at https://tech.ebu.ch/docs/tech/tech3380.pdf, a common captioning style requires the author to control the alignment of lines relative to the longest line within a block. This styling capability is not currently supported by CSS.

See https://codepen.io/palemieux/pen/yVxZWm . Region 2 illustrate the intended result of centering the longest line and right-aligning other lines relative to the right edge of the longest line.

This capability mirrors the `ebutts:multiRowAlign` styling attribute at https://www.w3.org/TR/ttml-imsc1.0.1/#multiRowAlign, which is demonstrated in the following sample document, which can be rendered at http://sandflow.com/imsc1proc/index.html .

```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
 xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
 xmlns:ebutts="urn:ebu:tt:style" xml:lang="en" ttp:timeBase="media" xmlns:ebuttm="urn:ebu:tt:metadata" >
	<head>
		<metadata>
			<ebuttm:documentMetadata>
				<ebuttm:conformsToStandard>urn:ebu:tt:distribution:2014-01</ebuttm:conformsToStandard>
				<ebuttm:conformsToStandard>http://www.w3.org/ns/ttml/profile/imsc1/text</ebuttm:conformsToStandard>
			</ebuttm:documentMetadata>
		</metadata>		
		<styling>
            <style xml:id="baseStyle" tts:color="#FFFFFF" tts:lineHeight="100%"/>
            <style xml:id="blackBackground" tts:backgroundColor="#000000"/>
            <style xml:id="greenBackground" tts:backgroundColor="#00FF00"/>
			<style xml:id="startEnd" tts:textAlign="start" ebutts:multiRowAlign="end"/>
			<style xml:id="centerStart" tts:textAlign="center" ebutts:multiRowAlign="start"/>
		</styling>
		<layout>
			<region xml:id="area1" tts:origin="15% 10%" tts:extent="70% 20%" style="greenBackground" tts:displayAlign="center"/>
			<region xml:id="area2" tts:origin="15% 70%" tts:extent="70% 20%" style="blackBackground" tts:displayAlign="center"/>
		</layout>
	</head>
	<body>
		<div style="baseStyle">			
			<p xml:id="s1" region="area1" style="startEnd" begin="00:00:01" end="00:00:09">
multiRowAlign="end"<br/>textAlign="start"
			</p>
			<p xml:id="s2" region="area2" style="centerStart" begin="00:00:01" end="00:00:09">
multiRowAlign="start"<br/>textAlign="center"
			</p>
		</div>
	</body>
</tt>
```

**Comment by astearns** [comment]
On first readthrough of the subtitling format spec, I'm thinking this should likely be another longhand of the text-align property, like text-align-last. It would take the same values as text-align-last, and need to be called something that communicated its 'text-align-all-but-longest' functionality. The only thing that comes immediately to mind is 'text-align-inner'

**Comment by fantasai** [comment]
From what I recall from the discussions, this was actually a Sizing issue: it's desired to shrinkwrap around the text _after wrapping_, which was IIRC possible in some ancient browsers but is not how `fit-content` works today. Once a block is sized to fit the (wrapped) text content, the regular `text-align` property will work as expected (and various other layout desires become possible). This is an especially important capability for `text-wrap: balance`.

`text-align-all-but-longest` wouldn't work because if there is more space than would fit the longest line (which there typically is), then all the lines would be aligned further to the side than the untouched longest line.

**Comment by fantasai** [comment]
Thinking about it some more, we could take Alan's solution: the engine would virtually track the edges of that line and apply text alignment to those edges instead of the containing block edges.

But since you have extra space within the box (assuming the longest line doesn't perfectly fit the container, which it usually doesn't), you'd want to align that space as well. The `justify-content` property effectively does this for flexbox layout, so we could re-use it here as well--values other than `normal|stretch` would mean that within the containing block we tightwrap a virtual box around the text, and then align that virtual box according to `justify-content`; meanwhile, `text-wrap` would operate within that virtual box.

**Comment by astearns** [comment]
My assumption is that text-align would control how the longest line is aligned within the box (as it does now), and text-align-inner would control how the rest of the lines align to the longest line's endpoints

**Comment by fantasai** [comment]
(Well, technically for Flexbox it's the `align-content` property; but we're operating in the `justify-*` axis here.)

**Comment by fantasai** [comment]
@astearns So, we can use a text-align property (which inherits) if we want the set of line boxes that are being considered to be restricted to the direct contents of a block. If we need alignment across blocks, then it becomes more complicated... I'm not sure what TTML needs (@palemieux?), but I imagine more broadly we'll want to group lines of text across block boundaries for this kind of alignment.

**Comment by tabatkins** [comment]
So how about this: `text-group-align: <'text-align'>`. Non-inheriting, put it on a block at some point in your hierarchy where you want to apply the group-alignment.  This causes the text descendants of the box (down to the next BFC, I imagine) to align as specified in `text-group-align`, *then* the length of the largest such line is used to clamp the width of all the lineboxes (down to the next BFC), and they then align as normal per 'text-align'.

So in the first example PDF, you'd specify `text-group-align: center; text-align: left;` to get the effect.

This is non-inheriting so you can declare it on a particular block that you want all the text inside of to align.

This might also solve some CJK justification issues. It's common to want the longest line to fill the container exactly, and everything smaller to justify inside of that. Right now you can only achieve that if the box width is *exactly* a multiple of 1ic; if it's not, the text will justify looser than you want.  With this, you can do `text-group-align: center; text-align: justify` and get the effect you want - if the box isn't exactly the right size, the extra space will just be used on either side, rather than being distributed between the characters.

**Comment by palemieux** [comment]
> I'm not sure what TTML needs 

The longest line within a block is aligned according to `text-align`, and all the other lines within the same block are aligned within the lateral dimensions of the longest line according to `text-group-align` .

**Comment by palemieux** [comment]
>  it's desired to shrinkwrap around the text after wrapping

@fantasai Precisely. Post-wrapping processing is also necessary to support [fillLineGap](https://github.com/w3c/csswg-drafts/issues/1974) and [linePadding](https://github.com/w3c/csswg-drafts/issues/1973)

**Comment by tabatkins** [comment]
Note that in my proposal it was the other way around - `text-group-align` was the "align the longest line" thing, then text-align applied to all the rest of the lines, constrained within the bounds of the aligned longest line.

**Comment by palemieux** [comment]
@nigelmegitt is it preferable that the alignement of the longest line or the alignement of the other lines prevail if the multiRowAlign feature is supported?

**Comment by nigelmegitt** [comment]
Thanks for this, just seen it after a short vacation. @palemieux I don't quite get your question - if you mean "if the multiRowAlign feature is _not_ supported" then the fallback should be that all the lines are aligned as per `text-align`. 

For example `text-align: left; multi-row-align: center;` would left align every line if it did not support `multi-row-align`. (I'm not proposing a CSS solution with a property called `multi-row-align`, just using this "syntax" as a short-hand to try to answer the question)

Does that answer your question in https://github.com/w3c/csswg-drafts/issues/1975#issuecomment-379502048 ?

**Comment by palemieux** [comment]
@nigelmegitt @tabatkins suggests that CSS `text-align` worked like TTML `text-group-align`, and CSS `text-group-align` worked like TTML `text-align`, if I understand https://github.com/w3c/csswg-drafts/issues/1975#issuecomment-379499901 correctly. In addition to making the mapping more complex, it also means that the fallback would be the opposite of that of TTML.

**Comment by nigelmegitt** [comment]
> In the first example in the PDF linked in the OP, where the text is left-aligned but the block as a whole is center-aligned, if you had to only honor one of those I think left-aligning is better than center-aligning. 

In the context of subtitles and captions, this would not work well. The "coarse" positioning should have priority over the "fine" positioning, otherwise text that's overall supposed to be somewhere near the centre could be shifted all the way to the left, which is _less_ like the specified intention than centering it. The block alignment is more important than the text alignment within that block.

**Comment by fantasai** [comment]
@palemieux @nigelmegitt One major question we have is whether this needs to work across blocks or only within a single “paragraph”. In other words, do you choose the longest line only within that paragraph or do you choose the longest line considering some set of paragraphs > 1?

If you choose the longest line only within a paragraph, e.g. the text two consecutive blocks that have `text-align: left; text-group-align: center` will not align on the left edge, since they will be centered individually.

**Comment by nigelmegitt** [comment]
@fantasai as specified in EBU-TT-D and IMSC 1.0.1, `ebutts:multiRowAlign` applies to `<p>` only and is inheritable. The application to `<p>` implies that it works per paragraph, rather than per set of paragraphs.

**Comment by fantasai** [comment]
OK, @frivoal and I drafted up some text for this! Please have a look and let us know if there's any problem.

**Comment by fantasai** [comment]
https://drafts.csswg.org/css-text-4/#text-group-align-property

**Comment by nigelmegitt** [comment]
@palemieux did you spot the commenter response pending label on this? Might be good to give it a look over.

To me, it looks like it does what is needed.

**Comment by MatsPalmgren** [comment]
Hmm, why mint a new property instead of using `justify-content` for this?
