### ISSUE TITLE
[selectors-4] suggested edit to "major changes"

### ISSUE THREAD

**Issue by estelle** [w3c/csswg-drafts#1977]
In the css selectors 4 specification it reads under major changes since working draft: "Removed restriction on combinators within :matches(), :not(), :nth-match(), and :nth-last-match()."
 :nth-match(), and :nth-last-match() are not in the current draft other than in this line, so it should likely read "Removed restriction on combinators within :matches() and not:not()"
and on another line:
"Removed :nth-match(), and :nth-last-match()"
location: https://drafts.csswg.org/selectors-4/#changes

**Comment by SelenIT** [comment]
Maybe it should also mention that :nth-match(), and :nth-last-match() were replaced with the extended :nth-child/:nth-last-child syntax (`:nth-*(An + B of S)`), and the "S" part in these selectors can also be a selector lists with no restriction on combinators?

Also, maybe the Issue 22 after that line can be removed now since we have the implementation of this (WebKit/Safari 9+) since 2015?

**Comment by fantasai** [comment]
Fixed, thanks!

@SelenIT Gonna run that one past dbaron first, since he was complaining about it the other day.
