### ISSUE TITLE
[CSS-appearance] Should we not use it, for now?

### ISSUE THREAD

**Issue by jitendravyas** [w3c/csswg-drafts#1982]
I'm working on a website and ran CSS validation on its CSS. They only validation error (not warning) I have is about `appearance`. I was using it give custom look to `<select>` to match it with design file. 

![w3c css validator results f](https://user-images.githubusercontent.com/77309/32773917-bda93434-c950-11e7-8351-15f3c4ae5380.png)

And It's available in [non-vendor-prefixed ]( https://css-tricks.com/almanac/properties/a/appearance/)(Also knows as standard) too.

I found some discussion about it but not sure what is the current recommendation from W3C for now.
https://drafts.csswg.org/css-ui-4/#appearance-switching
https://github.com/w3c/csswg-drafts/issues/1250

Should I not use it for now 1) because Validator caught it as invalid and 2) there is a possibility that it can be abandoned like @apply http://www.xanthir.com/b4o00 later.

**Comment by tabatkins** [comment]
Validation, in general, isn't a worthwhile thing. Most validators are not up-to-date and will show errors for things that are perfectly fine.  Test the property on your own in as many browsers as you can, and decide how you want to deal with the support.

---

As a side note, `@apply` never showed up in an official spec, was never accepted by a Working Group as something to work on, and was not implemented by any browser.  It was a proposal that the Polymer team wrote a polyfill for, and we later decided it wasn't a good idea.  That's a very different situation than the 'appearance' property.

**Comment by jitendravyas** [comment]
Thanks for the reply.

What does this indicate?

> "**This is not ready for shipping**"

![css basic user interface module level 4 2017-11-15 01-27-11](https://user-images.githubusercontent.com/77309/32801807-2c60c4fc-c9a4-11e7-9f71-7f5c1d42bd81.png)

Do you mean that `appearance` has been a part of W3C **Draft** https://drafts.csswg.org/css-ui-4/#appearance-switching so there are no chances it getting removed in future?

How one can confirm that there is no chance of revert to any CSS property from the W3C official spec?

**Comment by frivoal** [comment]
"not ready for shipping" is information for web browser implementers, not for authors. The vendor-prefixed variant of appearance has issues, so we don't want the standard one to be the same. But we haven't finished figuring out how the standard one should work, so browser vendors engineers should read the spec to think about the problem and give feedback, not jump straight into implementing a half baked idea.

In the meanwhile, authors can use the vendor prefixed versions. For simple uses, that will probably be fine. For more complicated ones, you may have a harder time getting things to work the same on all browsers. Which is why we're trying to come up with a standard alternative, but we're not done yet.

Until we've found a solution that works, and browsers have agreed to implement it, and have implemented it, and enough authors have used it that removing it would break lots of sites, there's unfortunately no way to promise that it will never be removed. It is not our current intention to remove it, but if we fail to make a sensible standard version, who knows.

Either way, you should generally not write code that depend on the future unprefixed property to behave the way you think (based on the current state of the spec) it will, as there's not guarantee until it actually happens.

**Comment by chharvey** [comment]
Too small to submit a whole new issue, but I found a broken link:

In [[css-color-3] §4.5.1 CSS2 system colors](https://www.w3.org/TR/css-color-3/#css-system), the note at the bottom references the “CSS3 UI `appearance` property” and links to [css-ui-3](https://www.w3.org/TR/css-ui-3/#appearance), but the property has been moved to [Level 4](https://drafts.csswg.org/css-ui-4/#propdef-appearance).

Either the link in [css-color-3] should be updated, or a note should be added to [css-ui-3] clarifying the `appearance` property has been moved.

**Comment by svgeesus** [comment]
That is weird, because I found that same language (because of the broken link) and fixed the link by removing mention of the `appearance` property which was dropped from UI 3 in like 2012. Maybe I forgot to push that change?
Any way yes, that link should be corrected to point to UI 4.

**Comment by tabatkins** [comment]
@chharvey But also, please submit separate issues for these in the future. New issues are not troublesome, and they're much better than having unrelated discussions in an existing thread. (Thanks for the report, tho!)
