### ISSUE TITLE
[mediaqueries-4] interaction media features (any-pointer, etc) still at risk?

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-drafts#1989]
I found that the `hover`, `any-hover`, `pointer`, and `any-pointer` media features are marked as at risk.

> The following features are at-risk, and may be dropped during the CR period:
> * the hover, any-hover, pointer, and any-pointer media features
https://drafts.csswg.org/mediaqueries-4/#status

But my quick testing and caniuse show that they're actually supported in 3 engines (Blink, EdgeHTML, WebKit).
https://caniuse.com/#feat=css-media-interaction

Mozilla sent an intent to implement last month, so hopefully they'll be well supported pretty soon.
https://groups.google.com/forum/#!topic/mozilla.dev.platform/WhXB19qGVkI

So, I'm not sure why they're still marked as so. Are there other reasons besides implementations?

**Comment by bathos** [comment]
I’ve found these valuable repeatedly in different contexts. Hover MQs in particular can be the key to taking interactions over the line from ‘accessible, but not optimal for all devices’ to ‘friendly and intuitive for (hopefully) everyone’. They’re also supported in every major browser. I’m guessing the warnings are out of date. It would be a relief if they can be removed.

(Meta thing: it’s great to know about ‘at risk’ features, but I’ve seen devs choose not to use appropriate features because of that notice before, interpreting it as an indication that the API isn’t reliable enough. Maybe that’s a rare thing, I dunno, but since non-adoption can be a factor in at-risk-ness, I’ve wondered if they ever become self-fulfilling prophecies...)

**Comment by frivoal** [comment]
(meta thing: yes, it is a known problem that labeling things at risk, which is meant to be a W3C process thing only, irrelevant to users or implementer or anybody who's not tasked with transitioning specs to various maturity levels, ends up being misinterpreted as some kind of warning sign, and makes people shy away from the feature. That's really unfortunate.)

**Comment by frivoal** [comment]
Agenda+ to propose dropping the at-risk marker on these features.

**Comment by hiikezoe** [comment]
As far as I know there is no APIs on Windows to tell which pointer device is the primary one or not. Is there?

**Comment by hober** [comment]
WebKit implements `any-hover` and `any-pointer`; we support removing the at-risk markers.
