### ISSUE TITLE
[css-backgrounds] Subsection anchors have the form "#the-background-position"

### ISSUE THREAD

**Issue by theres-waldo** [w3c/csswg-drafts#2005]
For example, the link for subsection 3.6, "Positioning images: the background-position property", is

https://drafts.csswg.org/css-backgrounds-3/#the-background-position

Is the word "the" supposed to be there in the anchor? There are links out there (e.g. on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position)) pointing to a version without the "the", suggesting that in an earlier draft it wasn't there.

**Comment by tabatkins** [comment]
It's intentional, but not really necessary any longer. The spec-generator that spec previously used would generate `id=background-position` for the actual property definition, in the propdef table, and so we needed a different ID for the section so it wouldn't collide.

Now tho, the default ID that gets generated for the property is `id=propdef-background-position` instead, so it's not necessary to have the `the-` in it.

(The MDN specs were trying to point to the properties themselves, not the section.)
