### ISSUE TITLE
[css-overflow] how should ignoring overflow on the *-start sides of the scrollport be done?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#2006]
There's a longstanding interoperability issue relating to overflow that I really thought we'd discussed before, but I can't find any record of it.

Scrollbars provide a user interface that allows scrolling to overflow extending past the inline-end and block-end sides of the box.  However, overflow that extends past the inline-start and block-start sides of a box with `overflow:scroll` or `overflow:auto` is ignored.

Currently [the spec says](https://drafts.csswg.org/css-overflow-3/#scrolling-direction):
> Due to Web-compatibility constraints (caused by authors exploiting legacy bugs to surreptitiously hide content from visual readers but not search engines and/or speech output), UAs must clip the scrollable overflow region of scroll containers on the block-start and inline-start sides of the box (thereby behaving as if they had no scrollable overflow on that side).

This was introduced in [01821f08744d](https://hg.csswg.org/drafts/rev/01821f08744d524d6d532462444f3ef7912198e6), by fantasai, in January 2016.

This behavior description matches what Gecko and Edge do.

However, Chromium and WebKit have always done something different, which I believe is that if a box is entirely off of either the block-start or inline-start side of a box, that it makes no contribution to the box's overflow.

The difference matters when there's a box that is entirely before the inline-start (block-start) side of a box, but extends past its block-end (inline-end) side.  In that case, Gecko and Edge show a scrollbar, but Chromium and WebKit do not.

I'd like us to explicitly agree that we should do one or the other of these behaviors, and have the spec reflect it.

See also [Mozilla bug 1419142](https://bugzilla.mozilla.org/show_bug.cgi?id=1419142).

**Comment by ChumpChief** [comment]
In Edge we've observed a number of fairly severe interop bugs due to the (block-start / inline-end) combination you describe on mobile sites.

Since scrollable bounds impact the scaling imposed by meta viewport in some cases, getting a different answer results in a symptom of inappropriate scaling rather than unnecessary scrollbars.  In the event that the page has a meta viewport that scales page content to fit the viewport horizontally, a too-large horizontal scrollable bounds results in the symptom of extremely downscaled content on the left side, with a large chunk of blank space on the right.

Because of that, I'm of the inclination that for mobile web compatibility the Chromium/Webkit definition of scrollable bounds needs to be used.  Alternatively, the meta viewport behavior could be changed to no longer account for scrollable bounds in scaling calculations, but this would introduce a different set of mobile web compatibility regressions.

From a user perspective, I don't see a scenario where allowing scrolling into a region with no reachable content exists is a good experience.  So I think that also points to the Chromium/Webkit behavior being preferable.

**Comment by fantasai** [comment]
@dbaron Would you mind verifying that the edits correctly capture the resolution?
