### ISSUE TITLE
[css2] Naming of revision of CSS 2.1

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#2008]
As far as I can tell, looking through WG minutes, we never decided what to call the revision of CSS 2.1 incorporating errata. I think we have two options:

 * CSS 2.1 2nd Edition
 * CSS 2.2

I'm in favour of CSS 2.1 2nd Edition because with the exception of scientific notation for numbers, we haven't added/removed any features, it's a simple update to incorporate errata, and as such in my view it doesn't constitute a new subversion of CSS 2.

**Comment by SelenIT** [comment]
Doesn't three formatting context instead of two (Table formatting context added) count as a feature?

**Comment by frivoal** [comment]
Which one are you talking about: CSS2.1 + with all the work in progress errata, or the one with the limited subset or errata that are ready for REC republication?

I think the later does not need a new name at all. It's just CSS2.1, and if you want to be very specific, you can still say CSS2.1, 07 June 2011 Recommendation, or CSS2.1 29 February 2019.

For the former, it probably should have a name, but not a new version number, since it isn't meant to be a new document that ever gets published as a replacement for the 2.1 REC, just a staging area for changes. So I'd call it something along these lines: "CSS2.1, errata staging draft"

**Comment by SelenIT** [comment]
I'd prefer following the pattern consistent with the HTML spec development:

- CSS2.1 2nd Edition (like [HTML5.1 2nd Edition](https://www.w3.org/TR/html51/)) as a republished REC, with the limited subset of errata incorporated;
- its own Editor's draft (like https://rawgit.com/w3c/html/html5.1-2/single-page.html) as its errata staging draft, without the separate published verion;
- CSS2.2 (like [HTML5.2](https://www.w3.org/TR/html52/)), with all CSS2.1 errata incorporated and all sections that have been updated with newer CSS modules replaced with links to those modules, as a future CSS2.x release that will eventually replace the CSS2.1 as the "[Latest CSS level 2](http://www.w3.org/TR/CSS2/)";
- [Editors draft of "the latest CSS level 2"](https://drafts.csswg.org/css2/) pointing to the latest state of CSS2.x development (like https://w3c.github.io/html/).

Just changing the publication date, without updating the spec name, doesn't seem enough to me because people might conclude that it was just a formal editorial update (like adding the red warning box in 2016). However, the errata contain some changes in the specified behavior (e.g. rules of margin collapsing) and terminology (e.g. the term "Table Formatting Context" occurs only in the errata), which can lead to confusion.

**Comment by tantek** [comment]
I can see reasons for using either "CSS 2.1 nth edition" or "CSS 2.2 (nth edition)" moving forward. In either case we should use "++nth edition" for subsequent updates rather than incrementing the decimal. Here is what I could come up with and or saw or heard mentioned by others:

Arguments for CSS 2.1 nth edition moving forward:
* no new features, so no need to increment the decimal
* past decision(s) that CSS 2.1 would be the last version of CSS2.
* avoid version number inflation

Arguments for CSS 2.2 nth edition moving forward:
* CSS 2.1 has been a stable (unchanging) document for many years, "2nd edition" does not accurately reflect the extent of likely editorial and substantive edits necessary to incorporate years of accumulated errata and issues
* "CSS 2.2" explicitly sends a signal to browser implementers and detail-oriented web developers that it has (will have) major bug fixes since CSS 2.1 that everyone else has read and referenced (in books etc.)
* Regular updates is a new mode. Since the proposed CSS 2.x editing & publishing workflow (see <https://github.com/w3c/csswg-drafts/issues/2553>) will be publishing regular updates with changes, it makes sense to provide a new decimal version number to signal this change in expected maintenance as well
* A CSS 2.2 WD has been published, and will forever exist. It would now look weird (possibly be confusing) to have the "latest" CSS 2.x be 2.1, a perceived step backwards from the 2.2 WD
* A single decimal increment over the course of 10+ years is reasonable and provides no danger immediate or subsequent of version number inflation

Based on these reasons, I have some preference for now (continuing) moving forward with CSS 2.2 on the condition that our proposed seasonal/regular iterations use "nth edition" rather than incrementing the decimal.

I also agree that "Just changing the publication date, without updating the spec name, doesn't seem enough to me".

I would be open to incrementing the decimal in the distant future if we make major changes such as replacing whole chapters with normative references to CSS 3 modules, or perhaps obsoleting a whole chapter in deference to one or more CSS module(s) (e.g. perhaps colors.html with css-color-3 and css-backgrounds-3).

PROPOSED: Use CSS 2.2 for the next REC track revision of CSS 2.1, and then append "2nd edition", "3rd edition" etc. for subsequent Edited Recommendations.

(Originally published at: http://tantek.com/2018/102/t5/)

**Comment by gsnedders** [comment]
CSS 2.1 has lots of statements like:

> But, in CSS 2.1, it is undefined whether the decoration propagates into block-level tables.

What do we want to change this to? Given the plan is presumably to obsolete/supersede 2.1 (and we should probably make 2.0 obsolete), do we just want to say "in CSS 2"?

**Comment by gsnedders** [comment]
@tantek I'm leaving it down to you to make the required edits and change the status (in the Makefile) back to ED to bump us to 2.2, though please do this soon so we can start relanding changes. (Unless you're happy with us temporarily being an ED of 2.1?)

**Comment by gsnedders** [comment]
Done in #2581.
