### ISSUE TITLE
[css-pseudo] Problems with styling ::first-letter with punctuation

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2040]
Johannes Odland wrote in https://lists.w3.org/Archives/Public/www-style/2017Nov/0024.html :

> Hi
> 
> According to Selectors Level 3 the ::first-letter includes punctuation that precedes the first character. The example specifically shows a dropped cap with an opening quotation mark.
> 
> Although there are no hard and fast rules for initial caps, it is a common typographical practice to style the punctuation different than the letter itself. The punctuation can hang in the margin, and be styled in the same font and font-size as the body text so that the initial letter is flush with other initial letters that does not have punctuation. 
> 
> In Norwegian typography it is considered bad practice not to leave the letter itself flush with the other letters.
> 
> http://theworldsgreatestbook.com/book-design-part-6/
> http://www.typografi.org/dropcaps/initialer.html
> http://www.typografi.org/dropcaps/assets/lite-sitattegn_714.jpg
> 
> As the spec is now it is hard to achieve good drop caps. 
> 
> Should there be a way to select the initial-punctuation also?

**Comment by dauwhe** [comment]
If we have initial punctuation with an initial letter, we usually omit the punctuation.

**Comment by johannesodland** [comment]
It is possible to omit the punctuation in some cases.
A coherent solution would be to hide the punctuation using css. 

Say that you create a stylesheet for feature articles. You want to control both how the drop-cap looks and how to handle the punctuation.  Leaving it up to writers/authors/journalist to remove the punctuation if there happens to be a drop cap is a fragile solution. If you decide to change the stylesheet later on you would have to go back and edit the content as well.

If you choose to hide or hang your punctuation, it should be possible to do so using css.

**Comment by johannesodland** [comment]
http://www.graphics.com/article/creating-drop-caps-adobe-indesign
http://etutorials.org/Adobe/Adobe+Indesign+CS2+Professional+Typography/Part+II+Paragraph+Formats/Chapter+10.+First+Impressions+Creating+Great+Opening+Paragraphs/Coming+Unstuck+with+Drop+Caps/

**Comment by johannesodland** [comment]
What's the status of the `::first-punctuation` pseudo class?

**Comment by plinss** [comment]
I like the proposal for a child pseudo-element. I'm not sure of the status of nested pseudo-elements being legal, but it's a bridge we need to cross at some point anyway (if we haven't already), so let's not let that stop it.

1) I suggest that it be called simply `::punctuation`, the `first-` is redundant if it's a child of `::first-letter`. Also if we ever extend the notion to other pseudos like `::marker` we can simply re-use it rather than have `::marker-punctuation`.
2) There are examples of punctuation following the first letter being included in a drop cap, e.g. `L'` in French. I presume in that case punctuation following the first letter would also be a `::punctuation` pseudo-element. Which then allows two of them within a single `::first-letter`, e.g. `«L'`. In principle we could allow selecting them independently with pseudo-classes (once we allow pseudo-classes on pseudo-elements). I'm also guessing the rules about which following punctuation are to be included are likely language specific.
3) If there are multiple leading punctuation characters, would they all be considered one pseudo-element, individual pseudo-elements, or do we possibly need grouping rules, e.g. does `–«L'` have two or three `::punctuation`s? What if there's a space between the dash and quote? e.g. `– «L'`  This isn't relevant unless we can select the individual pseudo-elements with pseudo-classes, but I'm wondering if there's a use case to style them independently (I can see use cases for styling the leading and trailing punctuation differently, e.g. make the leading quote small, but the following apostrophe match the font size of the first-letter.)

**Comment by tabatkins** [comment]
We already have nested pseudos, they're fine.

**Comment by fantasai** [comment]
More examples: https://github.com/w3c/csswg-drafts/issues/5154#issuecomment-659129316

**Comment by AmeliaBR** [comment]
My preference is to keep this as a nested pseudo-element, but with a parenthetical modifier that distinguishes between the before / after.

It would probably also be useful to have a `::first-letter::the-letter-itself` pseudoelement (name TBD) so that if you want the font or color to change on the enlarged letter but to inherit from the paragraph for the punctuation, you can do that directly instead of changing it on `::first-letter` and then re-setting it on the nested punctuation pseudos.

Example:

```html
<p>“I’m on my way,” she said.</p>
```

`p::first-letter` selects `“I’`
`p::first-letter::punctuation(before)` selects `“`
`p::first-letter::letter-only` selects `I`
`p::first-letter::punctuation(after)` selects `’`
`p::first-letter::punctuation` selects both the quote and the apostrophe, separately.

In the case of `<p>— « Madame… »</p>` example, the string of punctuation before the M would ideally be a single `::punctuation(before)` pseudoelement, but if it was `<p>— <q>Madame…</q></p>` or some other markup structure that breaks up that string in the DOM tree, then there would be multiple consecutive pseudoelements that all match that selector, so the tree with pseudos inserted would look like:

```
p
  p::first-letter
    p::first-letter::punctuation(before)
      [text]— [/text]
    q [partial, split by the ::first-letter]
      q::before
        p::first-letter::punctuation(before)
          [text]« [/text]
      p::first-letter::letter-only
        [text]M[/text]
  q [rest of the element, outside the ::first-letter]
    [text]adame…[/text]
```

(Either way, we do need to carefully consider the case where the quotation mark at the start of the paragraph is generated content from a `<q>` element — that should still be stylable the same as a literal quotation mark in the text!)

I liked the suggestion that the `::punctuation` nested pseudoelement would also be useful on `::marker`. In that case we'd probably need an additional `::punctuation(separator)` modifier for multi-part counters like `(6.a.iii)`. The name of the “everything except the punctuation” nested pseudo-element should also be decided after considering this case.

P.S. I chose “before” and “after” for the modifiers because they are plain English terms already used in CSS, but if people think that it is confusing to re-use the terms another option would be “leading” vs “trailing”.

**Comment by fantasai** [comment]
Agree that before vs. after needs to be built into the pseudo, not a pseudo-class, because if we go with the idea that it is a tree-abiding pseudo-element, then there are potentially multiple pseudos representing the leading punctuation if there are element boundaries in there.

Wrt `::letter-only`, would be nice to pick a word that worked with `::marker`, if that's in fact the direction we want to go in eventually. Either way, I'd drop `-only`.

Wrt color, if we implement `fill` on CSS generally, you could do it like

```
::first-letter { fill: fun-color-here; }
::first-letter::punctuation { fill: currentColor; }
```

:) But that wouldn't solve for font family changes, so you're probably right that we need to have `::letter` be separate somehow. This is all getting very complicated. :/

**Comment by AmeliaBR** [comment]
> Wrt `::letter-only`, would be nice to pick a word that worked with `::marker`, if that's in fact the direction we want to go in eventually. Either way, I'd drop `-only`.

Yes, definitely, and one of the reasons I emphasized that the name needed work.

Maybe `::value`? So `::first-letter::value` would match the letter itself, while `::marker::value` would match the value of the counter(s).  That works for separating out any [prefix/suffix defined by an `@counter` rule](https://drafts.csswg.org/css-counter-styles-3/#counter-style-prefix), separators inserted by [`counters()` function](https://drafts.csswg.org/css-lists-3/#funcdef-counters). But… it's a little strange if you want to handle markers set directly via the `content` property. For `::marker { content: "(" counter(n) ")"; }`, the non-counter strings are equivalent to prefix/suffix punctuation. But for `::marker { content: "→"; }`, the string is the marker value.

So… maybe it would be best to focus on a name for the current use case & deal with the counter use case, if need be, with a more explicit name.

**Comment by johannesodland** [comment]
Adding examples in case they're needed: 

![ex3](https://user-images.githubusercontent.com/175195/90382224-c0996180-e07e-11ea-8112-2ddb7fd66edf.jpg)

**Comment by acli** [comment]
The Norwegian example also applies to English. Bringhurst specifically recommends keeping the initial quotation mark bu style it differently (smaller size, exact size by eye; see 4.1.5).

**Comment by frivoal** [comment]
As suggested by @fantasai during the call `::first-letter::prefix` and `::first-letter::postfix` seem like a good idea: short and clear.

**Comment by fantasai** [comment]
OK, posted edits for this following @frivoal's recommendation to go with ::prefix and ::postfix. Let me know if anything about the edits is unclear, or if anything else needs to be addressed here.

Agenda+ to confirm the naming.

**Comment by digeomel** [comment]
Sorry, I don't get from the above what "accept what's in the draft" means. Which draft? It's 2025 and I don't see either the `::prefix` or `::postfix` pseudo-elements being implemented. The problem persists, no?

**Comment by valtlai** [comment]
Is the name `::postfix` decided, or could it be renamed to `::suffix`? It would be more consistent as CSS already has a `@counter-style/suffix` descriptor.

**Comment by Loirooriol** [comment]
> Which draft?

https://drafts.csswg.org/css-pseudo-4/#first-letter-pseudo

> Is the name ::postfix decided

It was resolved, but resolutions can be revisited if new information appears, like consistency with `@counter-style`. Filed #11949
