### ISSUE TITLE
Add 'Privacy and Security Considerations' section

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#207]
The following specifications are missing a section for privacy and security considerations:
- [x] [CSS Animations 1](https://drafts.csswg.org/css-animations-1/)
- [x] [CSS Animations 2](https://drafts.csswg.org/css-animations-2/)
- [x] [CSS Backgrounds 3](https://drafts.csswg.org/css-backgrounds-3/)
- [x] [CSS Backgrounds 4](https://drafts.csswg.org/css-backgrounds-4/)
- [x] [CSS Box 3](https://drafts.csswg.org/css-box-3/)
- [x] [CSS Fragmentation 3](https://drafts.csswg.org/css-break-3/)
- [x] [CSS Cascading 3](https://drafts.csswg.org/css-cascade-3/)
- [x] [CSS Cascading 4](https://drafts.csswg.org/css-cascade-4/)
- [x] [CSS Color 3](https://drafts.csswg.org/css-color-3/)
- [x] [CSS Color 4](https://drafts.csswg.org/css-color-4/)
- [x] [CSS Generated Content 3](https://drafts.csswg.org/css-content-3/)
- [x] [CSS Counter Styles 3](https://drafts.csswg.org/css-counter-styles-3/)
- [x] [CSS Display 3](https://drafts.csswg.org/css-display-3/)
- [x] [CSS Exclusions 1](https://drafts.csswg.org/css-exclusions-1/)
- [x] [CSS Extensions 1](https://drafts.csswg.org/css-extensions-1/)
- [x] [CSS Font Loading 3](https://drafts.csswg.org/css-font-loading-3/)
- [x] [CSS Fonts 3](https://drafts.csswg.org/css-fonts-3/)
- [x] [CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/)
- [x] [CSS GCPM 3](https://drafts.csswg.org/css-gcpm-3/)
- [x] [CSS GCPM 4](https://drafts.csswg.org/css-gcpm-4/)
- [x] [CSS Images 4](https://drafts.csswg.org/css-images-4/)
- [x] [CSS Inline Layout 3](https://drafts.csswg.org/css-inline-3/)
- [x] [CSS Line Grid 1](https://drafts.csswg.org/css-line-grid-1/)
- [x] [CSS Lists 3](https://drafts.csswg.org/css-lists-3/)
- [x] [CSS Logical Properties 1](https://drafts.csswg.org/css-logical-props-1/)
- [x] [CSS Multicol 1](https://drafts.csswg.org/css-multicol-1/)
- [x] [CSS Multicol 2](https://drafts.csswg.org/css-multicol-2/)
- [x] [CSS Namespaces 3](https://drafts.csswg.org/css-namespaces-3/)
- [x] [CSS Overflow 4](https://drafts.csswg.org/css-overflow-4/)
- [x] [CSS Paged Media 3](https://drafts.csswg.org/css-page-3/)
- [ ] [CSS Paged Media 4](https://drafts.csswg.org/css-page-4/) Unofficial Draft
- [x] [CSS Page Floats 3](https://drafts.csswg.org/css-page-floats-3/)
- [ ] [CSS Pagination Templates 1](https://drafts.csswg.org/css-page-template/) Unofficial Draft
- [x] [CSS Positioned Layout 3](https://drafts.csswg.org/css-position-3/)
- [x] [CSS Regions 1](https://drafts.csswg.org/css-regions-1/)
- [x] [CSS Round Display 1](https://drafts.csswg.org/css-round-display/)
- [x] [CSS Ruby 1](https://drafts.csswg.org/css-ruby-1/)
- [x] [CSS Shapes 1](https://drafts.csswg.org/css-shapes-1/)
- [x] [CSS Shapes 2](https://drafts.csswg.org/css-shapes-2/)
- [x] [CSS Size Adjustment 1](https://drafts.csswg.org/css-size-adjust-1/)
- [ ] [CSS 2015](https://drafts.csswg.org/css-2015/) Superseded by CSS 2023
- [x] [CSS Speech 1](https://drafts.csswg.org/css-speech-1/)
- [x] [CSS Style Attributes 1](https://drafts.csswg.org/css-style-attr-1/)
- [x] [CSS Template Layout 1](https://drafts.csswg.org/css-template-1/)
- [x] [CSS Text 4](https://drafts.csswg.org/css-text-4/)
- [x] [CSS Text Decoration 3](https://drafts.csswg.org/css-text-decor-3/)
- [x] [CSS Transforms 1](https://drafts.csswg.org/css-transforms-1/)
- [x] [CSS Transforms 2](https://drafts.csswg.org/css-transforms-2/)
- [x] [CSS Transitions 2](https://drafts.csswg.org/css-transitions-2/)
- [x] [CSS User Interface 3](https://drafts.csswg.org/css-ui-3/) (Bikeshed requires this to be named 'Privacy and Security Considerations')
- [x] [CSS User Interface 4](https://drafts.csswg.org/css-ui-4/) (Bikeshed requires this to be named 'Privacy and Security Considerations')
- [x] [CSS Will Change 1](https://drafts.csswg.org/css-will-change-1/)
- [x] [CSS Writing Modes 3](https://drafts.csswg.org/css-writing-modes-3/)
- [ ] [CSS 2.1](https://drafts.csswg.org/css21/)
- [x] [CSSOM 1](https://drafts.csswg.org/cssom-1/)
- [x] [CSSOM View Module 1](https://drafts.csswg.org/cssom-view-1/)
- [x] [Media Queries 3](https://drafts.csswg.org/mediaqueries-3/)
- [ ] [Selectors 3](https://drafts.csswg.org/selectors-3/)
- [x] [Non-element Selectors 1](https://drafts.csswg.org/selectors-nonelement-1/)

_Note that I didn't include WG Notes, CSS 2.1, CSS snapshots except the one from 2015, CSS Expressive Generalizations and Gadgetry 1 and the documents listed under 'Other Documents' at https://drafts.csswg.org/. If considered valuable, the section should be added there, too._

Side effect of is to make Bikeshed happy. :smiley:

Sebastian

**Comment by frivoal** [comment]
https://github.com/tabatkins/bikeshed/issues/730

**Comment by frivoal** [comment]
CSS-UI (3 & 4) solved thanks to the fix to tabatkins/bikeshed#730

**Comment by frivoal** [comment]
CSS-2015 probably should not have such a section. It is not a spec by itself, merely a reference of other specs. Should we add such a section with "nothing to see here" content, or can bikeshed grow a new flag of somekind to let it know that it doesn't need to warn? ( @tabatkins )

**Comment by frivoal** [comment]
@tabatkins what are your thoughts about my previous comment?

**Comment by ao5357** [comment]
@tabatkins,

I figured it would be helpful to update the checklist, as well as to perhaps provide 
additional information about Security and Privacy sections in CSS specs so far.

@tantek really hit the nail on the head with css-ui-3 and css-ui-4, imho. A good 
security section should contain:

 * A statement of the section as informative rather than normative
 * Coverage of the questions from the questionnaire
 * Citation to the TAG security questionnaire appropriately (puts it in a draft context)
 * No indications that the section is an issue/todo, nor any verbiage like "Everything will be fine if you implement it correctly"

I'm a newbie to the spec-writing world, so my other opinion on the matter may be 
incorrect, but... I also believe Tantek's placement of the section as an _appendix_ 
was ideal for the circumstance.

Following the table is a bikeshed partial for a section similar to the css-ui-3 one, albeit with 
wording more boilerplate to accommodate the disparate specs. If the template is 
acceptable to you [and the WG], I'd be happy to roll it into the specs that still 
need it and tender a PR here.

| Spec | Status | § header | "-ative" | "...correctly" | Questions | Linked TAG |
| ---- | ------ | -------- | -------- | -------------- | --------- | ---------- |
| [CSS Animations 1](https://drafts.csswg.org/css-animations-1/) | N | | | | | |
| [CSS Animations 2](https://drafts.csswg.org/css-animations-2/) | N | | | | | |
| [CSS Backgrounds 3](https://drafts.csswg.org/css-backgrounds-3/) | N | | | | | |
| [CSS Backgrounds 4](https://drafts.csswg.org/css-backgrounds-4/) | N | | | | | |
| [CSS Box 3](https://drafts.csswg.org/css-box-3/) | N | | | | | |
| [CSS Fragmentation 3](https://drafts.csswg.org/css-break-3/) | N | | | | | |
| [CSS Cascading 3](https://drafts.csswg.org/css-cascade-3/) | [Y](https://drafts.csswg.org/css-cascade-3/#priv-sec) | (none) | N | N | N | N |
| [CSS Cascading 4](https://drafts.csswg.org/css-cascade-4/) | N | | | | | |
| [CSS Color 3](https://drafts.csswg.org/css-color-3/) | N | | | | | |
| [CSS Color 4](https://drafts.csswg.org/css-color-4/) | [Y](https://drafts.csswg.org/css-color-4/#priv-sec) | 19 | N | N | N | N |
| [CSS Generated Content 3](https://drafts.csswg.org/css-content-3/) | N | | | | | |
| [CSS Counter Styles 3](https://drafts.csswg.org/css-counter-styles-3/) | [Y](https://drafts.csswg.org/css-counter-styles-3/#priv-sec) | (none) | N | N | N | N |
| [CSS Device Adaptation 1](https://drafts.csswg.org/css-device-adapt-1/) | N | | | | | |
| [CSS Display 3](https://drafts.csswg.org/css-display-3/) | [Y](https://drafts.csswg.org/css-display-3/#priv-sec) | 4 | N | N | N | N |
| [CSS Exclusions 1](https://drafts.csswg.org/css-exclusions-1/) | N | | | | | |
| [CSS Extensions 1](https://drafts.csswg.org/css-extensions-1/) | N | | | | | |
| [CSS Font Loading 3](https://drafts.csswg.org/css-font-loading-3/) | [Y](https://drafts.csswg.org/css-font-loading-3/#priv-sec) | (none) | N | N | N | N |
| [CSS Fonts 3](https://drafts.csswg.org/css-fonts-3/) | N | | | | | |
| [CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/) | N | | | | | |
| [CSS GCPM 3](https://drafts.csswg.org/css-gcpm-3/) | N | | | | | |
| [CSS GCPM 4](https://drafts.csswg.org/css-gcpm-4/) | N | | | | | |
| [CSS Images 4](https://drafts.csswg.org/css-images-4/) | [Y](https://drafts.csswg.org/css-images-4/#privsec) | 8 | N | N | N | N |
| [CSS Inline Layout 3](https://drafts.csswg.org/css-inline-3/) | N | | | | | |
| [CSS Line Grid 1](https://drafts.csswg.org/css-line-grid-1/) | N | | | | | |
| [CSS Lists 3](https://drafts.csswg.org/css-lists-3/) | N | | | | | |
| [CSS Logical Properties 1](https://drafts.csswg.org/css-logical-props-1/) | N | | | | | |
| [CSS Multicol 1](https://drafts.csswg.org/css-multicol-1/) | N | | | | | |
| [CSS Multicol 2](https://drafts.csswg.org/css-multicol-2/) | [Y](https://drafts.csswg.org/css-multicol-2/#priv-sec) | (none) | N | N | N | N |
| [CSS Namespaces 3](https://drafts.csswg.org/css-namespaces-3/) | N | | | | | |
| [CSS Overflow 4](https://drafts.csswg.org/css-overflow-4/) | [Y](https://drafts.csswg.org/css-overflow-4/#priv-sec) | 8 | N | N | Y | Y |
| [CSS Paged Media 3](https://drafts.csswg.org/css-page-3/) | [Y](https://drafts.csswg.org/css-page-3/#priv-sec) | (none) | N | N | N | N |
| [CSS Paged Media 4](https://drafts.csswg.org/css-page-4/) | N | | | | | |
| [CSS Page Floats 3](https://drafts.csswg.org/css-page-floats-3/) | N | | | | | |
| [CSS Pagination Templates 1](https://drafts.csswg.org/css-page-template/) | N | | | | | |
| [CSS Positioned Layout 3](https://drafts.csswg.org/css-position-3/) | N | | | | | |
| [CSS Regions 1](https://drafts.csswg.org/css-regions-1/) | N | | | | | |
| [CSS Round Display 1](https://drafts.csswg.org/css-round-display/) | [Y](https://drafts.csswg.org/css-round-display/#security-considerations) | 9&10 | N | N | N | N |
| [CSS Ruby 1](https://drafts.csswg.org/css-ruby-1/) | N | | | | | |
| [CSS Shapes 1](https://drafts.csswg.org/css-shapes-1/) | N | | | | | |
| [CSS Shapes 2](https://drafts.csswg.org/css-shapes-2/) | N | | | | | |
| [CSS Size Adjustment 1](https://drafts.csswg.org/css-size-adjust-1/) | N | | | | | |
| [CSS 2015](https://drafts.csswg.org/css-2015/) | N | | | | | |
| [CSS Speech 1](https://drafts.csswg.org/css-speech-1/) | N | | | | | |
| [CSS Style Attributes 1](https://drafts.csswg.org/css-style-attr-1/) | N | | | | | |
| [CSS Template Layout 1](https://drafts.csswg.org/css-template-1/) | N | | | | | |
| [CSS Text 4](https://drafts.csswg.org/css-text-4/) | N | | | | | |
| [CSS Text Decoration 3](https://drafts.csswg.org/css-text-decor-3/) | N | | | | | |
| [CSS Transforms 1](https://drafts.csswg.org/css-transforms-1/) | N | | | | | |
| [CSS Transforms 2](https://drafts.csswg.org/css-transforms-2/) | [Y](https://drafts.csswg.org/css-transforms-2/#priv-sec) | 19 | N | N | N | N |
| [CSS Transitions 2](https://drafts.csswg.org/css-transitions-2/) | N | | | | | |
| [CSS User Interface 3](https://drafts.csswg.org/css-ui-3/) | [Y](https://drafts.csswg.org/css-ui-3/#security-privacy-considerations) | Appendix C | Y | N | Y | Y |
| [CSS User Interface 4](https://drafts.csswg.org/css-ui-4/) | [Y](https://drafts.csswg.org/css-ui-4/#security-privacy-considerations) | Appendix C | Y | N | Y | Y |
| [CSS Will Change 1](https://drafts.csswg.org/css-will-change-1/) | N | | | | | |
| [CSS Writing Modes 3](https://drafts.csswg.org/css-writing-modes-3/) | [Y](https://drafts.csswg.org/css-writing-modes-3/#priv-sec) | 10 | N | Y | N | N |
| [CSS 2.1](https://drafts.csswg.org/css21/) | N | | | | | |
| [CSSOM 1](https://drafts.csswg.org/cssom-1/) | N | | | | | |
| [CSSOM View Module 1](https://drafts.csswg.org/cssom-view-1/) | N | | | | | |
| [Media Queries 3](https://drafts.csswg.org/mediaqueries-3/) | N | | | | | |
| [Selectors 3](https://drafts.csswg.org/selectors-3/) | N | | | | | |
| [Non-element Selectors 1](https://drafts.csswg.org/selectors-nonelement-1/) | N | | | | | |

## 207--priv-sec.partial.bs

```html
<h2 class="no-num" id="security-privacy">Appendix. Considerations for Security and Privacy</h2>

This appendix is <em>informative</em> rather than normative.

The W3C TAG is developing a
<a href="https://www.w3.org/TR/security-privacy-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>
for editors of specifications to informatively answer.

Per the <a href="https://www.w3.org/TR/security-privacy-questionnaire/#questions">Questions to Consider</a>:

<ol>
  <li>
    Does this specification deal with personally-identifiable information?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification deal with high-value data?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification introduce new state for an origin that persists across browsing sessions?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification expose persistent, cross-origin state to the web?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification expose any other data to an origin that it doesn’t currently have access to?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification enable new script execution/loading mechanisms?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification allow an origin access to a user’s location?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification allow an origin access to sensors on a user’s device?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification allow an origin access to aspects of a user’s local computing environment?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification allow an origin access to other devices?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification allow an origin some measure of control over a user agent’s native UI?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification expose temporary identifiers to the web?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification distinguish between behavior in first-party and third-party contexts?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    How should this specification work in the context of a user agent’s "incognito" mode?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification persist data to a user’s local device?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification have a "Security Considerations" and "Privacy Considerations" section?
    <p><em>Pending editorial review</em></p>
  </li>
  <li>
    Does this specification allow downgrading default security characteristics?
    <p><em>Pending editorial review</em></p>
  </li>
</ol>
```

**Comment by ao5357** [comment]
Related issues not previously referenced:

  - [ ] #1988 "[css-scrollbars][css-scrollbars-1] needs Security, Privacy section(s)"
  - [ ] #1243 "[css-conditional] Add fingerprinting note to Security & Privacy considerations"

**Comment by svgeesus** [comment]
So I fixed 21 of our specs [with this commit](https://github.com/w3c/csswg-drafts/commit/095f2a813c0a9bf2c8bbf259a08e8bd3e7560dbe) and the remaining ones are mostly old specs that still use the .src format; as the preprocessor for that is ancient history and does not generate a publishable spec, the way forward for those is to edit the generated html, sadly.
