### ISSUE TITLE
[CSS3] Border width rounding clarification

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2114]
There is needed clarification in CSS specification due to rounding values in border-width.
Please test IE. FF and chrome for values: 

```
border:0.3px solid #000;

border:0.7px solid #000;

border1.3px solid #000;

border1.5px solid #000;

border:1.7px solid #000;

border:1.999px solid #000;
```

Which browser has correct behaviour for pixel-ratio=1 and zoom=1.0? 

shall antialiasing be or not? 

The difference is pretty visible.

**Comment by Loirooriol** [comment]
This [sub-pixel problem](https://johnresig.com/blog/sub-pixel-problems-in-css/) is not restricted to border widths. Sadly there is no perfect way to solve it.

**Comment by Nadya678** [comment]
I know not only border, but one way must be defined. I use definition of 1px for size of font of `<html/>` tag and other elements in `rem`s Using media query I switch `<html/>` font-size to 0.75 or 0.5 to make the site responsible on very small screens (emulation of zoom, the zoom is not needed in CSS) but... The border 2rem converted to 1.5px looks differently in Cr and FF. 

What are possible solutions of the problem? The problem with rounding border-width, margin, padding shall be resolved to show sites properly in Cr, IE and FF and shall be described in spec.

**Comment by fantasai** [comment]
The CSS specifications define the computation of “used values” -- the theoretical goal of the rendering. We don't discuss how to rasterize, though -- that's historically been out of scope and left to the UA. I'm not sure we want to do so now, and if we do I'm not sure which spec it would go into. But I can ask the WG what it wants to do.

**Comment by dbaron** [comment]
And note that I think we've discussed in the past in the working group that some things (e.g., borders, column rules, line-heights, line grid sizes) should probably be handled differently from the rest, as in the message of mine that [John Resig quoted](https://johnresig.com/blog/sub-pixel-problems-in-css/).  In particular, those should be snapped to *device pixels* at used value time (breaking the constraint that 4 * 25% matches 100%), before their use in layout, whereas we should otherwise do layout using subpixel sizes and snap *edges* at the end (breaking the constraint that every 25% size is the same).

I think there may even have been some implementation convergence towards this model over the past few years, although I'm not sure how interoperable things are.

**Comment by tabatkins** [comment]
Border widths (and outlines, and column-rules) are now interoperable between browsers, and well-specified to reflect that. Closing the issue as it should be a consistent answer now.
