### ISSUE TITLE
[css-transforms-2] Serialization of the computed value of `translate` property.

### ISSUE THREAD

**Issue by CJKu** [w3c/csswg-drafts#2124]
I can not find a definition of serialization of individual transform's computed value in the spec[1]

When serializing a 'translate' property with percentage value, such as 'translate: 50%', should we resolve it to px or keep it unresolved?

PS: Currently, both edge and chromium resolve percentage to px.

[1] https://drafts.csswg.org/css-transforms-2/#individual-transforms

**Comment by Nadya678** [comment]
`transform:translate(50% 0%)` is also by firefox translated to px. 

btw. `translate:50%` and `scale:2 2` and other "styles" from transform shall be removed. 

Example:
```
transform:scale(-1), translate(50px,50px);
transform:translate(50px,50px), scale(-1);
```

THERE ARE TWO DIFFERENT TRANSFORMS. It cannot be separated to scale and translate.

**Comment by Loirooriol** [comment]
@Nadya678 Of course it's not commutative, but it's well-defined if the spec specifies the order, and it does: https://drafts.csswg.org/css-transforms-2/#ctm

I suspect these new properties were added precisely because some people without linear algebra notions assume `transform` is commutative and then they are confused by the results.

**Comment by Nadya678** [comment]
> commutative and then they are confused by the results.

But I need the commutative effect. People without knowledge of algebra also doesn't describe the
`rotation: 0,1,1,60deg;`. The vectors and matrices are "black magic" for them, 

For me the hardly is imagine 3D effects. Not by knowledge of algebra - if I calculate, the values are correct but imagine without seeing it. 2D without any problem.  

BTW. Shall be rotation instead of rotate and translation instead of translate if you don't use them as values but as properties (a noun).
