### ISSUE TITLE
[css-transforms-2] Please remove from drafts: scale, translate, rotate CSS style etc. 

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2126]
Example:
```
transform:scale(2) translate(50px,50px);
transform:translate(50px,50px) scale(2);
```

THERE ARE TWO DIFFERENT TRANSFORMS. It cannot be separated to scale and translate. 
Living demo: https://jsfiddle.net/p7sb1o6h/
If there will be the same transform, the red and blue rectangle shall be in the same visual position. 

The scale, translate, rotate etc. styles (not transforms) shall be removed from all drafts. 
  
The 
```
{
   transform:scale(-1) translate(50px,50px);
}
```

cannot be translated to: 
```
{
   scale:-1;
   transform:50px 50px; 
} 
```

transforms are made in order in which they was defined. 
What is order of transformations in this case?
```
div
{
   scale:-1;
}
html div
{
   transform:50px 50px;
}
```

**Comment by astearns** [comment]
> transforms are made in order in which they was defined

This is incorrect. The order in which everything is applied is defined in https://drafts.csswg.org/css-transforms-2/#ctm

But perhaps this could be pointed out in the section defining the individual transform properties (replacing the current "Fluff here" text).

**Comment by Nadya678** [comment]
Thus... all browsers made it wrongly?

**Comment by birtles** [comment]
One of the purposes of these properties is two provide a consistent order for combining the different types of transforms, rather than having to manage the list of transform functions oneself. This is particularly useful when animating the individual components independently. Without this, to achieve the same effect the author would require either additional wrapper elements, or additive animation with careful control of the composite order.

Animation libraries such as GreenSock animation also do this (although GreenSock further separates out x/y components).

Applications that require a different order to that defined for these properties can continue to use the `transform` property. That is, these properties are not intended to entirely replace the `transform` property but at the same time they enable use cases not possible with `transform`.

**Comment by AmeliaBR** [comment]
I agree these properties are very useful, for the reasons @birtles stated, and would not want to see them removed. But I think they can also be confusing for the reasons given in @Nadya678's issue.

A few clarifications to the [section defining the properties](https://drafts.csswg.org/css-transforms-2/#individual-transforms) could help:

- As @astearns mentioned, there should be a description of the order in which the three properties are applied, with a link to the [section on the Current Transformation Matrix](https://drafts.csswg.org/css-transforms-2/#ctm)

- There should also be a note clearly stating that these are _not_ longhands for the `transform` property, and that they do not replace any transformations specified with that property.

- As mentioned in #2109, there should be some sort of explicit statement about which values trigger 3D transformation mode. 

It would probably also be useful to have an example showing how they can be used to apply multiple independent transformations. E.g., how it allows you to add a `:hover { scale: 1.1; }` rule on a class of elements that already have (possibly unique) translations or rotations.

**Comment by FremyCompany** [comment]
I would prefer we kept them. 

I wouldn't mind, though, if we limited them such that they cannot be used with preserve-3d nor any 3d effect. That would make them more intuitive, to my humble opinion.

**Comment by tabatkins** [comment]
Per the above resolution, we're keeping the individual transform properties.
