### ISSUE TITLE
[cssom] getComputedStyle only supports ::before/::after

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#2149]
https://drafts.csswg.org/cssom/#extensions-to-the-window-interface

Roughly, from what I've tested:

* Chrome, Firefox, and Safari all support gCS `::first-letter` and `::first-line`.
* Firefox throws `NS_ERROR_NOT_AVAILABLE` for `::marker` (and doesn't support `::marker` AFAIK), Chrome doesn't support it so returns the element, and Safari does support `::marker` and does support it for gCS
* Firefox supports gCS `::placeholder`, Chrome and Safari does not (despite supporting the feature)

Is there any reason not to allow all pseudo-elements for gCS?

**Comment by upsuper** [comment]
I think it makes sense to support all pseudo-elements which the user-agent supports, and it probably should also be specified that what should happen when the pseudo-element is not supported.

Personally I think throwing an exception (maybe `TypeError`) is better than returning the style of the element, but I can accept argument on that.

Note that, Firefox currently throws `NS_ERROR_NOT_AVAILABLE` when getting property value from the object returned from gCS in that case, and gCS itself doesn't throw, which, I would think, is a bug. I think gCS should throw, or everything should work smoothly.

FWIW, there could be tricky cases for supporting returning all properties on all pseudo-elements, for example, since many pseudo-elements have only limited properties applied, user-agents may want to avoid computing the rest if possible, and may optimize their storage, which can lead to observable difference on returned value.

Also some properties which use used value rather than computed value as resolve value might be tricky in some cases, although it isn't clear to me what the cases would be.

**Comment by FremyCompany** [comment]
Edge supports a broad range of them, and like Chrome we fallback to returning the style of the element if we are not able to return the pseudo element style. We are supposed to support -webkit-input-placeholder but I am not sure it's actually working in the end, this could be just a bug. 

I believe the advantage of returning a functioning style object when asked about a pseudo-element you don't support is that you don't crash, with a bit of chance the script will do just fine with slighly wrong values.
