### ISSUE TITLE
Test-suite errors

### ISSUE THREAD

**Issue by tobireif** [w3c/csswg-drafts#2194]
Filing this here because time doesn't allow me to be subscribed to public-css-testsuite@w3.org .

Screenshots:

<img width="1440" alt="screenshot_1" src="https://user-images.githubusercontent.com/80411/35039420-1478c658-fb7e-11e7-84f0-6b255150185f.png">

<img width="1440" alt="screenshot_2" src="https://user-images.githubusercontent.com/80411/35039429-19f782ae-fb7e-11e7-9b31-64b32b6eced4.png">

<img width="1440" alt="screenshot_3" src="https://user-images.githubusercontent.com/80411/35039439-2080a42a-fb7e-11e7-817e-2fe48790df68.png">

**Comment by tobireif** [comment]
(click on each image for the larger view)

**Comment by fantasai** [comment]
Just, to look at the mailing list issue for a moment--to subscribe (this is not super obvious) to public-css-testsuite@w3.org you have to send a mail with the subject “subscribe” to the address `public-css-testsuite-request@w3.org`. If you did that and it didn't work, let me know: we need to fix that.

But filing here is fine. @plinss is in charge of the harness, though, so I can't help you with fixing the actual problem. :)

**Comment by plinss** [comment]
The base problem is with the style-change.js file, it needs to be in a support directory that is in the same directory as the test, so the script tag should have a src="support/style-change.js" rather than "../support/style-change.js".

This is a known limitation of the build system, as the directory structure of the test suite gets flattened.

I do need to update the "Report Issue" button to no longer point to Shepherd

**Comment by tobireif** [comment]
One other error in the Chrome console: eg at
http://test.csswg.org/harness/test/css-grid-1_dev/grid-alignment-implies-size-change-001/ :
"The Content Security Policy 'default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'nonce-wDymwtEQWUymGrW8KxZ5lcZqWCJOESCFh01rH3IckHg='; frame-ancestors 'none';' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header."

**Comment by tobireif** [comment]
Thanks for looking into / fixing these issues!

Another one: eg at http://test.csswg.org/harness/test/css-grid-1_dev/grid-alignment-implies-size-change-011/ :
"Failed to load resource: the server responded with a status of 404 (Not Found)" "100x100-green.png"

**Comment by mrego** [comment]
I've fixed the issue with the image, it was again a problem with the `../` paths.

Regarding the JavaScript console error I don't know what it's but I don't see it in http://w3c-test.org/css/css-grid/alignment/grid-alignment-implies-size-change-001.html

**Comment by tobireif** [comment]
Thanks! The CSP error, in Chrome:

<img width="644" alt="screenshot" src="https://user-images.githubusercontent.com/80411/35107345-fde3f1e4-fc70-11e7-8290-dd2a31779723.png">

**Comment by tobireif** [comment]
The JS error at test.csswg.org/harness/test/css-grid-1_dev/grid-alignment-implies-size-change-019/ is gone (probably since the path to the .js got fixed).

**Comment by plinss** [comment]
The CSP error is the result of some experimental code in the framework that the harness is built on. It's set to report-only so doesn't affect the behavior of the browser. There's no report-uri because we don't need one yet (no point in reporting against an unfinished CSP policy). Chrome is just warning that the CSP heading isn't doing anything useful.
