### ISSUE TITLE
web font `src` is not available as an attribute on FontFace interface [css-font-loading-3]

### ISSUE THREAD

**Issue by brycethomas** [w3c/csswg-drafts#2213]
The `src` attribute (which site authors include in their definition of a `@font-face`) is absent in the spec here: https://drafts.csswg.org/css-font-loading/#fontface-interface.  Note it's also not implemented in the current Chrome .idl file: https://chromium.googlesource.com/chromium/src/+blame/a805e7a83cd286d08cb113ad60940e060905311a/third_party/WebKit/Source/core/css/FontFace.idl.  `src` seems like an attribute that should be accessible.  Is there a reason for its omission?

**Comment by tabatkins** [comment]
Yup! ^_^

FontFace is not @font-face.  When constructing a FontFace, the source is useful at precisely one moment - when it's being constructed.  After that you don't need it - changing it wouldn't do anything, and the FontFace might have been directly constructed from binary data anyway, and thus not have anything like a src in the first place.

(On the other hand, CSSFontFaceRule, which is the JS reflection of the CSS @font-face rule, *does* include the 'src' descriptor, because it *is* useful there.)
