### ISSUE TITLE
[selectors-4] a question or concern regarding anchor links

### ISSUE THREAD

**Issue by jonathantneal** [w3c/csswg-drafts#2255]
Is there an enforced pattern to naming the anchor ids used to link to specific sections in the selectors specification? Or, do they just vary inconsistently, as they seem to me? I’m sorry if I misunderstand the logic.

For instance, the section for `:not()` uses `#negation`, `:something` uses `#relational`, and `:matches()` uses `#matches`. This seems like a *conceptual* pattern. However, the section for `:dir()` uses `#the-dir-pseudo`, `:lang()` uses `#the-lang-pseudo`, and `any-link` uses `#the-any-link-pseudo`. This seems like a *literal* pattern, and it appears most often in the specification, with a minor variation when it’s dropped for `:focus-visible` (`#focus-visible-pseudo`) and `:focus-within` (`#focus-within-pseudo`). There are other exceptions, still, like `:drop` and `:drop()` which use `#drag-pseudos`, while `:playing` and `:pause` use `#video-state`.

I’m sorry to even concern you with this, but I would like to better understand and predict these ids in order to easily discuss concepts online, name polyfills, file caniuse requests, add cssdb features, etc.

**Comment by fantasai** [comment]
I'm guessing a number of those anchors were copied over from Selectors 3, which for awhile had them auto-generated from the title text rather than manually chosen. Some of the ones which don't follow the pattern cover multiple pseudos within the same section, so some other approach had to be chosen.

Agreed that altogether it's a mess. :)  I'm not sure what's a good way forward for the section IDs.

Wrt automatic linking... in general there's a `<dfn>` on the name of the selector in the paragraph where it's defined, and that has an ID which follows a more rigorous pattern. It's not as nice as taking the section heading, but it's there. If you want to be fancy, perhaps you can target that <dfn> and then walk up to the previous header and grab its ID. :)

**Comment by tabatkins** [comment]
But yeah, there is no pattern you can predict for any of the headings.  The actual terms can mostly be predicted, as most of them are auto-genned by Bikeshed (but Selectors has a bunch of legacy ones that needed to be manually maintained).

**Comment by jonathantneal** [comment]
Closing this as non-fixable at this point. My concern is sufficiently understood and addressed by the replies here, too. Thanks, all.
