### ISSUE TITLE
[css-align] place-items doesn't allow 'left | right' keywords 

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#2275]
We decided to remove 'left' and 'right' keywords from the <self-position> syntax clause so that we could use it in both, Self Alignment and Default Alignment properties' syntax. Since them, we explicitly add those keywords for the main/inline axis properties (justify-self and justify-items).

However, this change made the place-items grammar wrong, or at least, incomplete:

https://drafts.csswg.org/css-align/#place-items-property
> [ normal \| stretch \| &lt;baseline-position&gt; \| &lt;self-position&gt; ]   [ normal \| stretch \| &lt;baseline-position&gt; \| &lt;self-position&gt; ]?

**Comment by tabatkins** [comment]
Yup, the justify-items grammar was editted incorrectly (@fantasai figured that since left/right were already part of the `legacy` term, she didn't need to add it to `<self-position>` explicitly), and then we just simplified 'place-items' to just directly ref the grammars of align/justify-items, same as the other place-* properties do.  (The explicitly-written grammars were necessary when `<overflow-position>` was re-orderable, so there was potential ambiguity, but we set the order by WG resolution a while back.)
