### ISSUE TITLE
[css-grid-2] Dual-axis vs. Per-axis Subgrids

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2280]
This issue is a placeholder for discussion of dual-axis vs per-axis subgrids. General implementation concerns and author use cases are both welcome. Specific problems with the spec as it stands should be filed separately.

**Comment by rachelandrew** [comment]
These are some use cases I gathered prior to the Tokyo Face to Face https://codepen.io/rachelandrew/project/full/68cc7a5da9cfbb56c6e8366d7d92e6ba/XWYGMD/

**Comment by zellwk** [comment]
My main usage is to use subgrid for nested grids. Here's [an article](https://zellwk.com/blog/faux-subgrid/) and a [video](https://engineers.sg/video/faux-sub-grid-singaporecss--2502) detailing my usecase. 

Furthermore, I believe single-axis subgrids are easier to work with. If we have single-axis subgrids, we can rely on browsers to create implicit grids—which means we can use `autofill` and `autofit`.

**Comment by rachelandrew** [comment]
I think one of the biggest issues with double axis subgrids is that it would make creating reusable components very hard. I would want to create a component that could accept variable amounts of content and be able to drop it into a variety of layouts. Tying the inner to the outer, and needing to change the outer based on the content of the inner would mean a lot of repetition in CSS to cope with this.

A quick demo of the issue is here: https://codepen.io/rachelandrew/pen/geEeaE

**Comment by meyerweb** [comment]
Here’s a use case from 1997, with two grid approaches to making it work without subgrids:

https://meyerweb.com/eric/css/examples/grid/mit-libraries.html

NOTE: that was assembled a while back for other reasons, so the page doesn’t discuss one- versus two-axis subgrids.

I was able to remake the example layout in Grid without subgrid, and have row and column tracks that could respond to contents, by flattening the HTML.  As one does, now.  That’s the first case shown

In the second case, the one with a good markup structure, I’m pretty sure I would want dual-axis subgrids instead of per-axis, but I may have misunderstood the terminology.  As it was, without any subgrids, I had to layer three grids with each other, _and_ enforce static track sizes in order to make sure everything lined up.  I would have very much appreciated a subgrid feature that let me set up `min-content` or `fit-content` columns _and_ rows, in the creation of that layout.

**Comment by stitchng** [comment]
I will go for dual-axis over per-axis

**Comment by MatsPalmgren** [comment]
I've implemented a prototype subgrid layout in Gecko and I figured I should give some feedback on it here.

The following features are supported:

* subgrids can be subgridded in either or both axes independently
* subgrids can be nested to any level
* full support for `writing-mode` - an orthogonal subgrid subgridded in its column axis attaches to its parent row axis and vice versa
* line names in subgrid ancestors are overlaid onto the names in the subgridded axis
* line names can be specified in the sugrid axis using the [`subgrid <line-name-list>?`](https://www.w3.org/TR/2015/WD-css-grid-1-20150317/#track-sizing) syntax
* `grid-template-areas` are supported on subgrids, and are overlaid similarly
* grid-aligned abs.pos. children can be subgridded (for line name resolution)
* subgrids are fragmented the same as any other grid container

All of the above can be combined in arbitrary ways.

I followed the "Per-Axis Proposal" in ["Characteristics of a Subgrid Item"](https://drafts.csswg.org/css-grid-2/#subgrid-items)  for the most part, i.e. the subgrid itself contributes its border/padding/margin to the sizing of the edge tracks, but is otherwise transparent to track sizing of its container.
Subgrids do not have implicit tracks (in a subgridded axis), all lines are clamped to its explicit grid, which is the extent of the subgridded axis.
I disregarded point 'g', 'h' and 'i' in the spec.  I don't see any need to impose such restrictions on the subgrid box itself.  It behaves exactly as any other grid item when it comes to flowing/aligning/positioning it.

I implemented the above prototype in roughly three weeks full time.  I mention this because I think it demonstrates that the "Per-Axis Proposal" is fairly straight-forward to implement and the primary motivation for the "Dual-axis Proposal" was that the the "Per-Axis Proposal" would be too complicated to implement.  The existing Grid algorithms for line name resolution and track sizing are already axis-independent and introducing support for subgrid into them results in the "Per-Axis Proposal" almost automatically.  I don't see any wins from an implementor's perspective in the "Dual-axis Proposal".

So based on that implementation experience, I propose the following:

1. remove the "Dual-axis Proposal" - I don't think that it makes it any easier to implement subgrid and the "Per-Axis Proposal" is fairly straight-forward to implement anyway, as demonstrated
2. remove g, h and i from "Characteristics of a Subgrid Item" -
   I don't see any motivation for these restrictions.  It just means more code to write and maintain.  I'm pretty sure authors will make use of unrestricted subgrid box sizing/alignment/positioning in interesting ways... :-)

That's the broad strokes - I'll try to provide more detailed feedback on this implementation later.

Secondly, I also wanted to mention that I see some opportunity for a new feature related to subgrid layout. The grid placement algo has an ['occupied' ](https://drafts.csswg.org/css-grid/#auto-placement-algo) state for each cell in the grid. Currently, a subgrid item occupies the full extent of its grid area. It would be fairly trivial to support stenciling/masking these bits to/from the grid/subgrid.  That way, we could make subgrid items avoid being placed in cells that are already occupied in the outer grid. We could also make items in the outer grid be placed inside the boundaries of the subgrid that weren't occupied by items inside the subgrid. In case that would useful... :-)

**Comment by mrego** [comment]
Amazing feedback @MatsPalmgren! We were not so sure about how it would work, but if you have already implemented it I guess there's no doubt that the only choice should be per-axis approach.

Also from the use cases it seems that there are clear needs to suport the per-axis approach too.

Just as a note due to a previous comment, the dual-axis proposal is included in the per-axis if you just set `subgrid` in both axes.

**Comment by fantasai** [comment]
Thanks for all your feedback, @MatsPalmgren! I just checked in edits to remove the dual-axis proposal in favor of the per-axis proposal, as you recommended. I also removed the allowance to ignore `overflow` (item i).

Wrt removing g and h, I don't understand what it would mean for a subgrid to not be stretched or to have its tracks aligned in a manner that isn't controlled by the parent grid, so I did not make any changes to those items. Please file a separate issue on those with a better explanation of what's expected to happen if we lift those restrictions if you think something there needs to change. :)

Thanks~
