### ISSUE TITLE
[css-pseudo] ::first-line and line-height

### ISSUE THREAD

**Issue by OxyDesign** [w3c/csswg-drafts#2282]
Specs: https://www.w3.org/TR/css-pseudo-4/#first-line-pseudo

The part of the specs related to the issue raised:

```
The ::first-line pseudo-element’s generated box behaves similar to that of an inline-level element, but with certain restrictions. The following CSS properties apply to a ::first-line pseudo-element:

- all font properties (see [CSS3-FONTS])
- the color and opacity properties (see [CSS3COLOR])
- all background properties (see [CSS3BG])
- any typesetting properties that apply to inline elements (see [CSS3TEXT])
- all text decoration properties (see [CSS3-TEXT-DECOR])
- any inline layout properties that apply to inline elements (see [CSS3LINE])
- any other properties defined to apply to ::first-line by their respective specifications
```

I'm opening this ticket because I've recently used the `::first-line` pseudo element and realized that the `line-height` property for that pseudo element:
- is implemented in a different way in each browser
- doesn't behave as I was expecting (inline VS block)

A short code sample to explain: https://codepen.io/OxyDesign/pen/bc9238f85b871ba1059bc43c953c7a46
(The pseudo element `::first-line` has a smaller `line-height`)

- Chrome (63) applies the reduced `line-height`
- Firefox (58) doesn't apply the reduced `line-height`
- Safari (10) applies the reduced `line-height` but only if the line is not broken with a `<br>`, in that case it doesn't apply the reduced `line-height`
- Internet Explorer (I could only have a quick look at 9, 10 and 11) seems to follow the same logic as Chrome

So that might not be really clear on that point because each browser seems to have its own interpretation.

The second point is that the specs says that it should "behaves similar to that of an inline-level element". I was expecting this to behave as a block-level element. I understand that `::first-letter` should behave as an inline-element as it's part of the text content of a block and is just a part of the line. But `::first-line` is clearly supposed to use the whole width available. Anything that is on this line is included in the `::first-line` definition, therefore should behave like a block in my humble opinion.

The code samples shows that the first line has a smaller `font-size`, so indeed I wanted to apply a smaller `line-height` which is not applied by FF and (partially) by Safari because as an inline-level element it shouldn't. But I think this behavior would make only sense for the `::first-letter` as it's part of a line and we don't want the line to be shrink by the `::first-letter`'s `line-height`. But in the `::first-line` case there is no possibility that any other content would be in the same line without being a part of the `::first-line` pseudo element so that shouldn't behave like that I think.

**Comment by Loirooriol** [comment]
CSS 2 says that `line-height` on a block container behaves as a minimum height value for the line boxes inside it, due to the [strut](https://www.w3.org/TR/CSS22/visudet.html#strut).

However, it seems CSS Inline tries to explain this behavior by introducing a [root inline box](https://drafts.csswg.org/css-inline-3/#root-inline-box) that inherits the `line-height` from the block container.

Then, the question is: how do the root inline box and `::first-line` interact? That's #1384.

So if the strut no longer exists and the fragment in the first line of the root inline box inherits from `::first-line`, then I expect a reduced line height. If the strut still exists or all the root inline box fragments inherit from the block container, then I don't expect a reduced line height.

See [bug 1427241](https://bugzilla.mozilla.org/show_bug.cgi?id=1427241).

---

> Anything that is on this line is included in the `::first-line` definition, therefore should behave like a block in my humble opinion.

But a `::first-line` does not stretch to fill all the available space as a block would do by default. See https://jsfiddle.net/q36d3wmx/

**Comment by fantasai** [comment]
[Reduced testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Ap%20%7B%20border%3A%20solid%3B%20width%3A%2010em%3B%20font-size%3A%2024px%3B%20line-height%3A%2036px%3B%20%7D%0Ap%3Afirst-line%20%7B%20%20background%3A%20orange%3B%20font-weight%3A%20bold%3B%20line-height%3A%2012px%3B%20font-size%3A%2012px%3B%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%20class%3D%27container%27%3EThis%20is%20a%20test%20paragraph%20so%20let%27s%20make%20more%20text.)

So I guess this is the practical impact of @Loirooriol’s question in #1384. :)
It does seem to me that letting the ::first-line’s line-height affect the root inline fragment on the first line is helpful, so maybe we want to resolve on that?
