### ISSUE TITLE
[css-align][css-sizing] Indefinite percentages in calc() are underspecified

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2297]
The [relevant spec text](https://drafts.csswg.org/css-align-3/#propdef-column-gap) says:

> Percentages resolve to zero when specified against a content-based size [...]

It's unclear to me what that means for `calc()`-expressions with percentage terms.  For example, say we have an inline-grid with two columns, 50px each, and `grid-column-gap: calc(10px + 20%)`. 

My interpretation is that 20% ("Percentages") resolves to zero, and thus the gap resolves to 10px during intrinsic sizing, and thus the inline-size of the container is 110px. Is that correct?
Or should the entire  `calc()`-expression resolve to zero?

**Comment by fantasai** [comment]
Yes. It says “percentages resolve to zero”, not “expressions involving percentages resolve to zero”. :)

I'm not sure the spec needs any fixing here, would you mind if I just close this invalid?

**Comment by MatsPalmgren** [comment]
Here's the corresponding example in block layout:
```html
<style>
span { display:inline-block; width:50px; height:10px; background:lime }
</style>
<div style="display:inline-block; border:1px solid;">
  <span style="margin-right:calc(10px + 20%)"></span><span></span>
</div>
```
In Chome - the width of the `<div>` is 100px and the right margin for the `<span>` is 30px, i.e. `(10px + 0.2*100px)`. What you're suggesting is that the width should be 110px and the margin should be `30px + 0.2*110px`.  So are you saying that the block's intrinsic size here is wrong in Chrome?

(Firefox is still back-computing percentages in these cases, but we're [removing](https://bugzilla.mozilla.org/show_bug.cgi?id=1434478) that to comply with the recent CSSWG [resolution](https://github.com/w3c/csswg-drafts/issues/347).)

**Comment by mrego** [comment]
BTW, Edge and Safari have the same output than Chrome for the example above. The `<div>` has a width of `100px`.

**Comment by MatsPalmgren** [comment]
Well, if I change the above example to use padding instead of margin, like so:
```html
<style>
span { display:inline-block; width:50px; height:10px; background:lime }
</style>
<div style="display:inline-block; border:1px solid;">
  <span style="padding-right:calc(10px + 20%)"></span><span></span>
</div>
```
then the `<div>` has a width of 110px in Chrome (and the padding ends up being 32px).
It seems weird to me that padding and margin percentages are resolved differently.

**Comment by AmeliaBR** [comment]
From the author's side, I would definitely expect `calc(10px + 20%)` to always equal _at least_ 10px, for margin or padding or anything else.

I also would very much prefer that contents inside a shrink-to-fit container don't end up adding extra spacing after the container has been fit, unless the percentages sum up to greater than 100%.

Based on those objectives, I see two acceptable approaches. Either:

* calculate the container width using an algebra equation:

  - 100%*width = ∑(fixed widths) + ∑(percentage widths)*width
  - (100% - ∑(percentage widths) ) * width = ∑(fixed widths)
  - width = ∑(fixed widths) / (100% - ∑(percentage widths) ) 
  - AKA, for Mat's example, the width would be 110px/80% = 137.5px

* *Or,* treat the reference for percentage widths as 0, calculate out the rest of the expression, and stick with it even after the container width is resolved. Less ideal, but simpler.

***That said***, the consistent behavior for all browsers I've tested for

-  [`width` defined as a percentage + absolute length](https://codepen.io/AmeliaBR/collab/ba68490f0470fcf5917a8a4eb440c924/) in shrink-to-fit containers is to treat the entire `calc` expression as zero when determining the parent container's width, but then evaluate the `calc` for the children normally after the parent width is set (so the child elements now overflow the too-small parent).

-  [`height` defined as a percentage + absolute length](https://codepen.io/AmeliaBR/pen/c1a8fb61843e50986f0b0e1b49c2e4ec/) in contexts where percentage height isn't defined (because of a fit-to-contents auto-height parent container) is to treat the entire `calc` expression as unresolvable, setting the height to `auto`.

I'm not sure where/if either of those behaviors are defined ([CSS sizing says to refer to the individual layout modules](https://drafts.csswg.org/css-sizing-3/#sizing-values) for how to resolve percentages, and doesn't mention `calc`).

If height and width were consistent with each other, I'd argue that padding & margin should match the same behavior, too. But they aren't. They're a mess. So I refer again to my suggested solutions above, and wonder if there would be any compat issue with making `width` in a shrink-to-fit container behave similarly. *(The algebra isn't that complicated, really…)*

**Comment by dbaron** [comment]
This is related to #1132, as mentioned in today's telecon.

**Comment by MatsPalmgren** [comment]
(I've filed a Chromium bug about calc() margins [here](https://bugs.chromium.org/p/chromium/issues/detail?id=823066))

**Comment by fantasai** [comment]
Agenda+ to discuss zeroing out the percentage vs. zeroing out the entire expression, for margins/padding/gaps. The argument in favor of zeroing out the entire expression is that this is what seems to be implemented; the argument in favor of zeroing out the percentage is that it is more meaningful. (For the sizing properties (#1132), we fall back the entire expression to the initial value, but in that case the initial value is meaningful: it contributes the size of the content, which is usually a more important factor in sizing than the non-percentage parts of a calc expression. For margins and padding, however, the initial value is zero: zeroing out the percentage and scavenging the rest of the expression would be more meaningful.)

**Comment by fantasai** [comment]
OK, we've got edits in for zeroing out percentages in both margins/padding (in Sizing) and for gaps (in Alignment). Please re-open if the text is insufficiently clear, but otherwise I think we're closed out here.
