### ISSUE TITLE
[css-text-3] pre-wrap + break-word

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2329]
Which behaviour of `white-space:pre-wrap + word-wrap:break-word` is correct? 

1) end spaces are preserved and break the line (EDGE/IE11) and long series internal spaces (between words) also break the line
2) end spaces have any exception - doesn't break the and long series of spaces between words doesn't break the line? (Cr, Moz)

You can test it on `<textarea/>` or on content-editable `<div/>` by entering: 
test_________________________________________________________test_________________________________________________, the _ means a space. 

In my opinion the IE11/EDGE behaviour is correct.

**Comment by frivoal** [comment]
This text has evolved in the spec quite a bit over time to take various use cases and subtleties into account. The result is that with `white-space:pre-wrap` + `word-wrap:break-word`, the UA is allowed to do one of two things:
* collapse those of the the spaces at the end of the line that would otherwise overflow
* [hang](https://drafts.csswg.org/css-text-3/#hang) the spaces at the end of the line. So they stay there (selectable, underlinable, etc)

If you want them to be wrapped, with have introduced a new value: `white-space: break-spaces`, which does the same as `white-space:pre-wrap` except for that difference.

(Closing as Invalid, because this is a question, not an issue.)
