### ISSUE TITLE
[css-fonts-3] Finish up Bikeshed source

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#234]
The specification is not yet generated dynamically via Bikeshed due to https://github.com/tabatkins/bikeshed/issues/453.

Once that issue is fixed, the Overview-wip.bs can be renamed to Overview.bs and Fonts.html and Fonts.src.html as well as Overview.html (see also issue #213) can be removed.

Sebastian

**Comment by litherum** [comment]
What does "ready" mean?

**Comment by SebastianZ** [comment]
@svgeesus I just realized that the changes described above are still not done, so could this issue please be reopened?

Or even better, since I am a member for some time now, could I get the rights to change the issues by myself?

Sebastian

**Comment by astearns** [comment]
I’ve invited you to the github group, @SebastianZ

**Comment by SebastianZ** [comment]
Thank you very much, Alan!

Sebastian

**Comment by svgeesus** [comment]
Hi @SebastianZ 

Conversion to Bikeshed is a lot of work and can be error prone.

For me, it was a low priority because

1. Fonts 3 is a W3C Recommendation, so we can't just make arbitrary changes to it, like with a WD or CR
2. _All_ of Fonts 3 is in Fonts 4, which is the current work, so any changes and corrections can be made there

So yes, it will be useful to have a Bikeshed version of Fonts 3, provided that the generated result has no substantive or editorial differences compared to the existing Recommendation.

**Comment by SebastianZ** [comment]
Yes, it's definitely low priority and should be done without actually changing the contents. Though I still think it might be worth converting it to Bikeshed as long as there are references to it.

Sebastian

**Comment by tabatkins** [comment]
The important thing (well, "important") would just be adding appropriate attributes to all the dfns so that Fonts 3 can be a reasonable dfn source for Bikeshed. But since Fonts 4 is a strict superset of Fonts 3, and it *is* marked up appropriately (by default, due to being a Bikeshed document), that's really not very important.

So the only reason to rewrite Fonts 3 to Bikeshed at this point is ease of maintenance, and that's not really a concern either with an old Rec like this.

So, no reason *not* to do it, but very little reason *to* do it either.

**Comment by svgeesus** [comment]
> as long as there are references to it.

A [recent update to the bikeshed linking database](https://github.com/w3c/csswg-drafts/issues/6436#issuecomment-880869874) should mean there are fewer references to Fonts 3 going forward. For example, up to a week ago, CSS Text 4 referred to the definition of `font-size` from CSS Fonts 3; it now links to the definition in CSS Fonts 5.
