### ISSUE TITLE
[css-pseudo] Add stroke-color and stroke-width to the list of highlight properties

### ISSUE THREAD

**Issue by dbates-wk** [w3c/csswg-drafts#2362]
It seems reasonable to amend <https://drafts.csswg.org/css-pseudo-4/#highlight-styling> to allow a web author to set stroke-color and stroke-width for a pseudo element.

**Comment by svgeesus** [comment]
Yes, it does

**Comment by fantasai** [comment]
We probably need to clarify that these properties only affect ink overflow, not layout overflow, then. :)

**Comment by fantasai** [comment]
I was about to edit these resolutions in, but I'm no longer sure that `stroke-width` should be ink overflow, at least not in SVG. Ink overflow would be fine for CSS, where it's just text decoration, but in SVG it seems a little more fundamental, and maybe it should be layout overflow. And it'd be a bit weird to allow it for CSS but not SVG ::selections.

Also if we're doing `stroke-color` shouldn't we also be doing `fill-color`?

Agenda+ to confirm, would like to hear back from @AmeliaBR @smfr @svgeesus

**Comment by AmeliaBR** [comment]
I'm not sure that "layout overflow" is a meaningful concept in SVG. There's currently no way that a stroke  size on one element can affect the layout of another rendered element, although it can affect marker sizing (Markers being "decorations" on the same element as the stroke property -- from a rendering-tree perspective they'd be like child content.)

Chrome already supports the stroke and fill properties on `::selection` in SVG. (https://codepen.io/AmeliaBR/pen/VqMrPV) although not `paint-order`, which I would add to the list. 

In general, selection styling and SVG is a mess, because there is no official support for background color on SVG text spans, yet it's still part of the default selection styles in most browsers. But that's a separate issue that shouldn't hold up these changes.

**Comment by frivoal** [comment]
> I'm not sure that "layout overflow" is a meaningful concept in SVG. 

In CSS, the key distinction is whether that overflow can trigger scrollbars (layout overflow) or not (ink overflow). That's just not a thing in SVG?

**Comment by AmeliaBR** [comment]
> In CSS, the key distinction is whether that overflow can trigger scrollbars (layout overflow) or not (ink overflow). That's just not a thing in SVG?

Ah, I see. No, it's not a thing: SVG elements other than the document root currently never have scrollbars, and scrolling for the root element is defined by viewBox/width/height dimensions, not rendered content.

In SVG 2, we proposed adding scrolling mechanisms for certain elements, but never defined the exact dimensions of the scroller region.  However, since only elements with defined width/height dimensions would get scrollbars, it would presumably follow the same rules. (https://www.w3.org/TR/2018/CR-SVG2-20181004/render.html#OverflowAndClipProperties)

**Comment by bradkemper** [comment]
box-shadow and border-image should also be added to the list.

**Comment by fantasai** [comment]
@bradkemper We can't add anything that would illustrate the boundaries of the selection area, since that's up to the UA (it's complicated, and not necessarily rectangular). So the list of properties we can add here is much less than “anything that doesn't affect layout”.

**Comment by fantasai** [comment]
Specifically, the list of requirements here are

- Doesn't affect layout
- Not dependent on the exact bounds of the highlight painting area
- Can be applied performantly in a highly dynamic environment

**Comment by bradkemper** [comment]
How is stroke color or width different? Wouldn’t the stroke show the exact bounds of of the highlight painting area?  Wouldn’t that always be a merging of rectangles? 

OK, border-image would be weird if the selection went around a piece of text that was taller than other things in the line, but box shadow and border-radius could still work. Apply the border radius before merging the rectangles. Do box shadow like a filter, and then knock out the shape. 

Are filters disallowed because of performance?

**Comment by AmeliaBR** [comment]
> Wouldn’t the stroke show the exact bounds of of the highlight painting area?

The stroke isn't a border/box stroke, it's a stroke outline around the individual text glyphs (or SVG shapes).

**Comment by bradkemper** [comment]
Oh yeah. Of course you are right.

**Comment by svgeesus** [comment]
Confirming that `stroke-width` should be ink overflow. Stroke, and markers, in SVG do not affect the geometry (which is the closest analog to "layout" in SVG), only the rendered result.

**Comment by fantasai** [comment]
@svgeesus Can you also confirm about whether fill-color should be handled the same way as stroke-color? :)

**Comment by svgeesus** [comment]
yes, I can :)

**Comment by svgeesus** [comment]
So the proposed list of additional properties is

- `stroke-color` 
- `stroke-width`
- `fill-color`
- `paint-order`

and rejected candidates are
- `box-shadow`
- `border-image`

**Comment by smfr** [comment]
I'm concerned about adding stroke-width here. Changes to stroke-width affect visual overflow, and engines (at least WebKit) might have to run layout code in order to update visual overflow. I don't want to have to run layout when selection changes.

**Comment by fantasai** [comment]
@svgeesus Affecting ink overflow might not affect layout or scrollable area, but it still requires some geometrical calculations to figure out what needs to be invalidated, so I think smfr has an important point here. Reflagging for discussion.

**Comment by AmeliaBR** [comment]
There seem to be a few different definitions being thrown around about what should or shouldn't disqualify a property for use with `::selection`.  And there are some confusions about how the existing SVG properties work.  Some clarifications...

## 1) Layout overflow for scrolling region

As I mentioned above, element geometry & styles cannot currently trigger scrollbars in SVG.  There have been proposals for allowing scrollbars on elements with fixed dimensions if their content overflows. The [spec text](https://www.w3.org/TR/2018/CR-SVG2-20181004/render.html#OverflowAndClipProperties) (which is likely to be removed from SVG 2 for lack of implementation) didn't define what counted as scrollable overflow.  If that is ever implemented, it may be preferable to include the stroke region.  We may also in future want to add a way to auto-define a `viewBox` based on one of the content bounding boxes, such as the stroke bounding box, which would mean that stroke could affect layout. But those are both hypothetical future additions.

When it comes to strokes and scrolling layouts, however, we do have current implementations using `-webkit-text-stroke` on HTML text.  Based on a [quick test](https://codepen.io/AmeliaBR/pen/84c95eb4cd697f031f12487cbf239480), it seems that no current browser triggers scrollbars for overflow created from strokes on HTML text. (Note: someone please confirm for WebKit; but I'm assuming it's the same as Chromium.)

BTW, Chrome & Edge support changing the `-webkit-text-stroke` properties in `::selection` (with some issues in Edge, in that it resets the width to zero if you only change the color). Firefox doesn't support them as highlight properties.

## 2) Painting area and hit testing

All the following properties can affect the painting area, _including_ the hit-testing region in SVG:

- `stroke` (switching from `none` to any other value)
- `fill` (likewise)
- `stroke-width`
- `stroke-dasharray` and `stroke-dashoffset`

Changing `stroke` or `fill` (or any of their proposed longhands, which _do not_ include the existing `stroke-*` properties) between values that do not include `none` _wouldn't_ change the paint region or the hit-testing region. But I'm not sure how that restriction could be applied to `::selection` styles.

Based on the [current spec](https://drafts.fxtf.org/fill-stroke-3/) for the `stroke` and `fill` longhands, I'm not sure if anyone's considered how the `none` value gets extended into the longhands.  Specifically `stroke: none` and `stroke: transparent` are currently very different as far as hit testing goes but it looks like they are being expanded into the same longhands in the proposal.

## 3) Dynamic geometry of paint contents

For painting SVG text, scaling and positioning the paint source (e.g., patterns, gradients) is always based on the size of the `<text>` block, not on individual spans. So there would be no recalculating of the paint layer itself as a selection span dynamically changes.  But the proposed longhands are based on `background` syntax, where images are positioned according to the individual span dimensions.

________________________________

I am therefore tempted to suggest that any formal resolution should be deferred to the Fill & Stroke module, so that all the details can be thought through.

Which would mean that `::selection` painting in SVG would continue to be an inconsistent and poorly defined mess. And the behavior of the still unstandardized `-webkit-text-stroke` and its longhands in highlight properties would continue to be undefined (but if Firefox decided to match the other browsers and support them in highlight styles, it wouldn't make anything worse).

Which is all unfortunate, but maybe not as unfortunate as locking in a standard without considering the details.

**Comment by heycam** [comment]
I just want to mention that @smfr's comment applies in Gecko too. Any time the `stroke-width` property changes, we perform a reflow to recompute the painted bounds of the element. (This won't affect the layout / position of other elements, but it's still work that must be done.) It's probably not super awful to reflow during selection dragging as the selection encompasses new elements with `::selection { stroke-width: ... }` styles but it's not something we do now and it would be good to avoid if we could since currently updating for selection styles only require a repaint.

**Comment by svgeesus** [comment]
OK, it seems clear that `stroke-width` should be excluded here. I hadn't fully understood the intermediate class of operations between "causes reflow" and "just needs repaint of changed pixels".

**Comment by smfr** [comment]
@dbaron notes that changing text decoration also requires that you recompute ink overflow, so maybe we already need to deal with this.
