### ISSUE TITLE
[css-selector] I want a selector that prevents my class to be changed from Javascript 

### ISSUE THREAD

**Issue by PauloHDSousa** [w3c/csswg-drafts#2374]
Can I ask something to css4?
I want a selector that prevents my elements to have their styles changed throught Javascript or Jquery, is it possible?

**Comment by Loirooriol** [comment]
Why would you want to do that? I don't really see the point, even if there was such kind of protection, JS could just remove the stylesheet and then be able to alter the DOM.

**Comment by AmeliaBR** [comment]
The [`!important` modifier](https://drafts.csswg.org/css-cascade/#importance) can be used in your stylesheet to indicate that certain styles should take precedence over inline styles.  (Styles set by JQuery are usually inline styles; in vanilla JavaScript, inline styles are created by modifying the `style` property of the element object.)  

An `!important` priority is specified for each style property-value declaration:

```css
[hidden] {
  visibility: hidden !important;
/* regular inline styles can't make elements with a `hidden` attribute visible */
}
```

`!important` has been in CSS since the beginning, and is supported in all web browsers.

But `!important` doesn't give you much nuance or control. Whenever possible it is better to work _with_ the JavaScript, adjusting the styles that it sets, instead of trying to override them separately.

PS, One extra warning: you can also use `!important` in inline styles, or otherwise create `!important` priority styles from JavaScript. These then override `!important` in your stylesheet. But if a JavaScript library is using `!important` for styles that don't make sense on your website, you should probably reconsider using that JavaScript library.

**Comment by inoas** [comment]
IMHO the real solution is using (declarative) shadow-doms and a restriction policy of scripts not being able to *write into these*. First is being discussed but not there yet last I don't know enough about shadow doms but that should be a security feature for shadow doms/encapsulation.
