### ISSUE TITLE
Is it CSS "feature" or bug?

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2382]
IE11 and EDGE: 

https://jsfiddle.net/uu2n39eo/

IMHO 300 should be correct. I also measure the div in pixels and result is 293 instead of 300.

**Comment by jonjohnjohnson** [comment]
Guessing if the most recent version of any browser doesn't return 300 for width, then you should file a bug report with that specific browser.

**Comment by AmeliaBR** [comment]
Many browsers will have minimum font-size settings that will override the `font-size:0.75px` setting on the root element, which will then of course throw off your em sizing.

That said, for IE & Edge, it appears to be more of a rounding error: they only keep one decimal place, so that a `font-size: 0.75px` is treated as `font-size: 0.7px`.

Of course, you should never be setting unreadably small font sizes, and it is explicitly allowed [in the CSS Font specs](https://drafts.csswg.org/css-fonts-3/#font-size-prop) that when rendering text, the actual font-size can be adjusted as necessary for good rendering.  However, that only applies to the actual font-size used for text rendering, not to the official "used" font-size that is inherited and used for em/rem units.

If you have practical examples of scaling layout elements with em units, where the `font-size` rounding in Edge/IE throws off the correct layout, then [file a bug on the browser](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/).
