### ISSUE TITLE
[css-fonts] Cross-link to CSS Text order of operations

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2393]
https://lists.w3.org/Archives/Public/www-style/2015Feb/0328.html

Done for CSS Writing Modes already in https://github.com/w3c/csswg-drafts/commit/78a99ed700032030cdec9de57b3fa70a2420c9b4

**Comment by svgeesus** [comment]
Rather than the **Introduction**, which solely deals with fonts, it looks like the section **6.1. Glyph selection and positioning**, which also deals with text layout, would be the best place to insert this reference.

Here is my suggested text (to be appended to the first paragraph of that section:

> The point at which font selection and positioning happens in the overall order of text processing operations (such as text transformation, text orientation and text alignment) is described in [[css-text-3#order]]
