### ISSUE TITLE
[css-flex-1] Use more appropriate word than "sucks" 

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2431]
https://www.w3.org/TR/css-flexbox-1/#item-margins

"Note: This variance **sucks**, but it accurately captures the current state"

**Comment by SelenIT** [comment]
@Nadya678, this whole issue has been resolved in [#2085](https://github.com/w3c/csswg-drafts/issues/2085#issuecomment-362000362). The whole note about the "variance" has been removed from both [css-flex-1] and [css-grid-1] specs, since the single option for calculating margins/paddings of flex/grid items has been chosen. All browsers decided to switch to Chrome's behavior.

P.S. Please cite the latest Editor's drafts (e.g. https://drafts.csswg.org/css-flexbox/#item-margins), which usually incorporate the most recent edits, instead of /TR/ publications, which can be rather outdated.

**Comment by tabatkins** [comment]
Not to mention, "sucks" accurately captured the suckitude of the variance.

**Comment by MatsPalmgren** [comment]
> All browsers decided to switch to Chrome's behavior.

Well, that's a I nice euphemism...  The harsh truth is that Chrome's developers refused to implement what the specification said (which was a consensus decision in the CSSWG, btw)  thereby _forcing_ other UAs to change for web-compatibility reasons.  Shame on them.

**Comment by tabatkins** [comment]
It definitely was not a WG consensus, pretty much by definition, as Chrome/WebKit disagreed with Firefox/Edge. Please don't rewrite history.

**Comment by MatsPalmgren** [comment]
They disagreed _after_ the decision was made. Meanwhile they shipped an non-conformant implementation thereby establishing fait accompli due to their dominant market position. _Then_ the spec was updated to allow either behavior. Please don't rewrite history.

**Comment by astearns** [comment]
Find some other venue if you want to continue this.
