### ISSUE TITLE
[css-syntax][css-values] should clarify whether the <url-token> is potentially deprecated?

### ISSUE THREAD

**Issue by wargrey** [w3c/csswg-drafts#245]
http://www.w3.org/TR/css-syntax-3/#consume-an-ident-like-token
https://drafts.csswg.org/css-syntax/#consume-ident-like-token
https://drafts.csswg.org/css-values/#urls

Hello, I am implementing the CSS engine for my desktop application.
In [css-values], there is no words to mention the `<url-token>` but its functional notation, and in the [css-syntax] draft, the algorithm to consume the ident-like token is distinguishing these two forms. So is the `<url-token>` remained just for compatibility? Should a new implementation put its functional notation at the first place?

**Comment by tabatkins** [comment]
`<url-token>` **is** mentioned in Values, in the exact section you link to - it's the first bullet point after "In addition to the syntax defined above".

Syntax distinguishes the two forms because they parse differently.

`<url-token>` is not being deprecated or going away. If you're implementing a CSS engine, I recommend following Syntax exactly.

**Comment by wargrey** [comment]
Okay, thank you.
