### ISSUE TITLE
[css-text-3] What does 'allowed' mean?

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#2450]
https://drafts.csswg.org/css-text-3/#line-break-property

> The following breaks are allowed for normal and loose line breaking if the content language is Chinese or Japanese, and are otherwise forbidden: 

The counterpoint to 'allowed' in the spec text is forbidden, which is pretty clear for testing purposes.

Depending on how the author of the spec text was using the word, however, 'allowed', might mean 'could be, but might not be' (which is not testable) or might mean 'are expected' (ie. trying to express the opposite outcome).

It seems odd that there's no way to say "I want to ensure that things behave in the opposite way to `strict`".  An undefined behaviour seems acceptable for `normal` , but loose should surely be different?

Which is the correct interpretation?  (My tests currently assume the former, so no tests would be submittable to WPT for 'loose'. See https://w3c.github.io/i18n-tests/results/line-breaks-jazh)

**Comment by fantasai** [comment]
It's a list of requirements. Allowed is the opposite of forbidden, and not the same thing as undefined.

**Comment by r12a** [comment]
Thanks for the explanation, by which I understand the meaning to be that what's allowed is actually expected, and we should have tests to check that the specified effect is produced. The word 'allowed' is still ambiguous though, shouldn't we change it to 'expected'?

**Comment by AmeliaBR** [comment]
Yes, there are two ways of interpreting that "allowed":

- If a break is required, the user agent SHOULD/MUST consider these to be break opportunities (but whether you actually break or not still depends on layout requirements); or,
- These MAY be treated as break opportunities (but a user agent can choose not to recognize them as such).

The first case could be testable by constructing a layout which requires a line break and which has no other line break opportunities.

**Comment by fantasai** [comment]
Breaks are allowed. They're not required, otherwise you'd have to force a break at every such character and that would be bad.

**Comment by AmeliaBR** [comment]
No, by "required" I mean "to avoid overflow".

E.g., consider this code (using Latin text because I'm not familiar enough with the CJK case):

```html
<div style="max-width: 10ch">super-cali-fragil-istic-expe-ale-docious</div>

<div style="max-width: 10ch">supercalifragilisticexpealedocious</div>
```

Unless automatic hyphenation is turned on, the second one overflows. But the first one wraps at the hyphens, because hyphens are normally considered break opportunities in English text.  So the question is, is it enough to say that the user agent MAY break text at the hyphen, or is it better to say that they SHOULD consider the hyphen a break opportunity when fitting text to layout constraints?

Or another example, what about the "/" character?

```html
<div style="max-width: 10ch">super/cali/fragil/istic/expe/ale/docious</div>
```

I personally think that text layout SHOULD support breaks after a slash (especially for URLs and path strings, but also for "and/or" type grammatical use), but most browsers don't implement it that way. (Firefox does! So much nicer!)  The other browsers are "allowed" to break after the slash, but they never do, even if the result is overflowing text.

**Comment by frivoal** [comment]
The browser is not allowed to overflow if there are "allowed" wrap points, but it isn't quite "must wrap here" because it there are several allowed wrap points, the browser is given some discretion about prioritizing them differently, and choosing which one of them it wants to wrap at.

https://drafts.csswg.org/css-text-3/#line-break-details gives an example:

> UAs that allow wrapping at punctuation other than spaces should prioritize breakpoints. For example, if breaks after slashes are given a lower priority than spaces, the sequence "check /etc" will never break between the "/" and the "e".

so wrapping between / and e is allowed, but it is only required if that's the only possible wrapping point in the line.

So, back to Richard's original point, if you want to be strict about the spec's interpretation, this is somewhat hard to test, as allowed wrap points can be ignored by the UA when there are other allowed wrap points that it chooses to prioritize. So to check that a browser allows a break where it is supposed to, you need to craft a situation where not only the line could be wrapped there to avoid overflow, but also where this is the only place where you can possibly wrap.

The downside is that a poor implementation of priorities could result in most of the wrapping opportunities introduced by loose being ignored so long as there's another one on the line, which is 
not the intended effect.

I guess we could require that these allowed wrap points be considered at a high priority, but since we don't define how priorities work precisely, that seems trick.

For now, I suppose that this is what tests can rely on:

>  The precise set of rules in effect for each of loose, normal, and strict is up to the UA and **should follow language conventions**

It would not follow language conventions to down prioritize these break so much that they are ignored when any other break is possible. But that limits all such tests to be flagged as "should" tests only.

**Comment by r12a** [comment]
> So to check that a browser allows a break where it is supposed to, you need to craft a situation where not only the line could be wrapped there to avoid overflow, but also where this is the only place where you can possibly wrap.

Which is exactly what my tests at https://w3c.github.io/i18n-tests/results/line-breaking etc do.  But I'm trying to decide whether or not to send them to WPT repo, because if we do we are saying that we _expect_ such a behaviour.

What such tests also do is point up that situations where a browser doesn't break under such conditions there seems to be a pretty clear indication of a problem. It can render the text unreadable. (In particular, the tests seem to reveal that Firefox uses adhoc information about linebreaking behaviour, and is missing information for certain characters, rather than using the Unicode data.)

**Perhaps the spec should say, explicitly, that browsers SHOULD break a line at the nearest allowed break point before the line end (as defined by the rules given for loose, normal, and strict) unless it uses additional rules that would override that behaviour.**

**Comment by r12a** [comment]
LGTM.
