### ISSUE TITLE
[css-text-3] Audit details of break-spaces value against use cases

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2465]
https://lists.w3.org/Archives/Public/www-archive/2018Mar/0002.html

**Comment by frivoal** [comment]
On the one hand, I agree that over all, the various properties that affect line breaking and space preservation are a complicated mess from a UI point of view, and are hardly intuitive. It can be explained why which does what, but that's not the same thing.

Within that, I think overflow-wrap: break-spaces is not that unusual. It is not terribly obvious why that's there, but it can work, and it can be explained: The property is to deal with wrapping when the line would overwise overflow. Spaces at the end of the line are defined to overflow as "hanging" (which is either just ink overflow, or scrollable overflow, see #2398). Therefore, dealing with it there is OK.

Arguably, the value could also be attached to the `word-break` (e.g. a series of preserved white spaces is some kind of special "word") or `line-break` (e.g. this affects how the line breaks) properties. I suppose that if we did so, the new grammar should be `[ currently accepted values ] || break-spaces`. I am not theoretically opposed to that, but I am not convinced it is a real improvement either. It is just as easy to justify the value not being on these properties: `word-break` is self described as being about "soft wrap opportunities between letters", and `line-break` says it's "particularly how wrapping interacts with punctuation and symbols". At one point we also argued that it should be a value on the white-space property. I see no end to this discussion if we keep on reopening it.

Anyway, I am not objecting to better property design if there is a better solution, but I think that most likely, the better thing to do is to give it a rest, keep the current design we landed on, let people implement this (at least igalia is about to, and comments from others suggest that it may be in other people's roadmap as well). We may have a better chance at a sane UX by trying for nicer shorthand syntax in level 4, to paper over the mess that these various properties are in general, not limited to this question.

**Comment by frivoal** [comment]
@litherum I believe you were looking into implementing this. Any opinion?

**Comment by rachelandrew** [comment]
I was asked to have a look at this as someone who teaches this stuff. I'm not completely familiar with the whole spec but have read the linked meeting minutes. From an initial read I think I have a reasonable preference for how it is currently specified (as the `overflow-wrap` property). I think it better describes the situation of overflowing whitespace, rather than treating the preserved white space as a special word and therefore part of `word-break`. 

I think I'd describe this as "overflowing whitespace", and I think that would be something any author would understand. Making the property seem sensible.

**Comment by frivoal** [comment]
Right, that makes sense to me. So I think we should **not** change this syntax.

What we do need to tweak is that when `overflow-wrap: break-spaces` is on, the spaces are treated as more substantive things that otherwise, and therefore the one space at the end of the line that does not get wrapped should be counted towards in min-content inline size

**Comment by frivoal** [comment]
@fantasai I've made a [Pull request for the spec](https://github.com/w3c/csswg-drafts/pull/2612) and [one for the tests](https://github.com/w3c/web-platform-tests/pull/10627). Review appreciated.

**Comment by frivoal** [comment]
So, Igalia+Google are in the middle of implementing this, and have suggested we make a change to the syntax: instead of having `break-spaces` be a `||` alternative in `overflow-wrap`, it could be a `|` alternative in `white-space`.

Pros:
* `||` alternatives are easier to implement than `|` alternatives
* `break-spaces` is only useful when combined with `white-space:pre-wrap`, so you have to check that property anyway. It could instead be a variant of `white-space:pre-wrap`, on the same property.
* There is not a particularly strong correlation between the `break-spaces` and `break-word` values from the point of view of where authors want to set them. They don't particularly need to be cascading together
* It fits some people's mental model better

Cons:
* in a browser that does not support `break-spaces`, the fallback of `white-space: pre-wrap; overflow-wrap:break-spaces` would be `white-space:pre-wrap; overflow-wrap: normal`. This is closer to the original intent than falling back from `white-space: break-spaces` to `white-space: normal`. This is can be easily mitigated by authors explicitly providing a fallback value (`white-space: pre-wrap; white-space: break-spaces;`) though.
* It fits some other people's mental model better

The set of property and values that control line breaking and white space is messy and hard to understand anyway, and I don't think we can find a perfectly elegant answer. We've been renaming and shuffling this value between various properties for the last 3 years or so. Chasing perfect is the enemy of good.

Personally, I think either alternative is OK. Given that this request comes from the first implementation effort, I am inclined to support it, so that we can ship this asap, and finally put it in the hands of authors.

If the WG is firmly against that change, I'm OK with that too, and hope that Igalia+Google can live with that.

Either way, we should resolve and move on.

CCing people who have previously opined: @javifernandez @kojiishi @fantasai @litherum @tabatkins

**Comment by frivoal** [comment]
cc @rachelandrew

**Comment by frivoal** [comment]
Reposting a comment @fantasai accidentally made in the wrong issue:

----

Wanted to add some background: the proposal comes out of a discussion between me and Koji about the implementation of `overflow-wrap: break-spaces`.

The current syntax is `overflow-wrap: break-word || break-spaces` and Koji asked about splitting `overflow-wrap` into two longhands to simplify implementation. This was my response, which I'd advise everyone (regardless of interest in this particular property) to read since it's about principles that inform our decisions about property design.

> I think that adding properties is more overhead on the authors—there is more to learn and memorize—so while it might be a little more awkward for implementors, it's better for CSS overall to avoid adding properties when they aren't necessary, for the authors' benefit.
> 
> (We made a mistake in Flexbox by splitting some of the properties for implementors' convenience, and now authors frequently get themselves in trouble by using longhands when they needed the shorthands to perform appropriate resets.)
> 
> For authors, the reason to have separate properties is if it's needed to cascade the settings independently. If I think about that, then I would say that `break-word` and `break-spaces` are not very closely related, and probably should cascade independently.
> 
> However, this makes me think also that `white-space: pre-wrap` and `overflow-wrap: break-spaces` should _not_ cascade independently, so maybe it makes the most sense to shift the `break-spaces` value to the `white-space` property, e.g.
>
> ```
> white-space: normal | nowrap | pre | pre-lines | pre-wrap | break-spaces
> ```
>
> These are all mutually exclusive options on `white-space`: being able to combine `break-spaces` with any other value than `pre-wrap` is impossible, so the adjusted syntax reflects that structural relationship.
> 
> And this solves your implementation concern as well.

**Comment by kojiishi** [comment]
It might be clear already but I support the proposal. This proposal can help us reducing the necessary code change by ~100 lines for us.

**Comment by frivoal** [comment]
@fantasai spec and tests PR done. Review appreciated.
