### ISSUE TITLE
[cssom] getComputedStyle and shorthands.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2529]
Currently https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle says:

> declarations: All longhand properties that are supported CSS properties, in lexicographical order, with the value being the resolved value computed for obj using the style rules associated with doc.

Which means that `getComputedStyle(document.documentElement).font` shouldn't be present, since it's a shorthand.

This is inconsistent with https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-getpropertyvalue, though which handles shorthands.

Should `ComputedStyle.getPropertyValue` handle shorthands? If so, should they be exposed as a property in the declaration object?

Right now answers from browsers to "does `getPropertyValue` handle shorthands?", and "are shorthands exposed as a property?" are:

 * Firefox: no, no
 * WebKit / Blink: yes, yes
 * Edge: no, no

What should happen here?

Note that both FF and Edge have a special-case for `overflow`, which used to be a longhand.

**Comment by emilio** [comment]
cc @ericwilligers, which was filing bugs related to this.

**Comment by emilio** [comment]
This is very related to https://github.com/w3c/csswg-drafts/issues/1033.

**Comment by FremyCompany** [comment]
cc @FremyCompany

**Comment by FremyCompany** [comment]
I think "yes" was a not-great idea when css started, but now that shorthands can have values that you cannot expose in the longhands (like `font:var(--heading-font)`) the behavior of webkit/blink probably makes more sense.

**Comment by upsuper** [comment]
Variables cannot appear in result from getComputedStyle, so that's not an issue.

For Firefox, we do have a special case that system font on `font` is kept in computed style, but that's not something new anyway.

**Comment by upsuper** [comment]
I have an impression that not having shorthands in gCS result was also intended for forward compatibility. That might be a discussion with @dbaron three years ago, but I don't recall the reasoning exactly.

I would guess the reason is something like, when a new longhand property is added to a shorthand, and the new property contains some value which is not expressible in the shorthand, the shorthand may fail to serialize. If there is code relying on serialization of shorthand, they may fail unexpectedly in browsers with the new property, leading to webcompat issue and making it harder to ship some new properties. Obvious past examples may include `border` and `font`.

This argument may also apply to specified value as well, but my understanding is that computed value is usually more useful to interpret for scripts (since that's a step closer to the value engine actually uses), while specified value is often just used for setting. That means keeping serialization forward and backward compatible is probably more important for gCS than for specified value.

**Comment by upsuper** [comment]
I agree that "don't serialize shorthands at all" is definitely not something we want. We at least need to serialize shorthands which were longhands.

**Comment by tabatkins** [comment]
Right, but "dont' serialize this seemingly-random set of properties with no clear grouping" isn't nearly as convincing. ^_^

**Comment by emilio** [comment]
I'd like to discuss this at the F2F, given everyone would be around.

**Comment by foolip** [comment]
I depended on this difference in behavior accidentally in a Fullscreen test, which @upsuper fixed in https://github.com/web-platform-tests/wpt/pull/13102. I've created https://github.com/web-platform-tests/wpt/pull/13238 as a test for that issue specifically. When this issue is resolved, please be sure to also merge that or a similar test. Filing bugs on the browsers that fail it would be great too.

**Comment by christian-bromann** [comment]
This inconsistency also affects [WebDriver](https://w3c.github.io/webdriver/#get-element-css-value) tests where users try to get the shorthand CSS property of an element resulting in different responses, see webdriverio/webdriverio#6161.

**Comment by foolip** [comment]
I'm closing https://github.com/web-platform-tests/wpt/pull/13238 as it's blocked on this issue, but when this is resolved it could be a starting point for tests.

**Comment by emilio** [comment]
@foolip there's a resolution above (edits still needed), or what am I missing?

**Comment by gsnedders** [comment]
> Which means that `getComputedStyle(document.documentElement).font` shouldn't be present, since it's a shorthand.

This doesn't actually follow from the current spec; `font` is a [supported CSS property](https://drafts.csswg.org/cssom/#supported-css-property) and therefore we [generate](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-camel-cased-attribute):

```webidl
partial interface CSSStyleDeclaration {
  [CEReactions] attribute [LegacyNullToEmptyString] CSSOMString font;
};
```

It does, however, mean that `font` doesn't appear as an indexed property.

> The object’s supported property indices are the numbers in the range zero to one less than the number of CSS declarations in the declarations.

**Comment by gsnedders** [comment]
@emilio per my prior comment, what edit do you believe is actually needed?

**Comment by emilio** [comment]
I think given that the spec (and browsers it seems) are correct
