### ISSUE TITLE
Rename 'line box' to 'flow line'

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2546]
CSS 2 didn't distinguish between boxes and fragments, all were considered boxes. So it defined

> The rectangular area that contains the boxes that form a line is called a [line box](https://www.w3.org/TR/CSS21/visuren.html#line-box). 

But from https://drafts.csswg.org/css-display/#intro,

> In the course of layout, boxes and text runs can be broken into multiple fragments. This happens, for example, when an inline box and/or text run is broken across lines

So the so called "line boxes" are not really boxes, they exist in the fragment tree instead. Therefore the term doesn't really make sense and it's confusing.

We already have [flex lines](https://drafts.csswg.org/css-flexbox/#flex-lines), so I would call them "flow lines". This affects lots of specs, of course.

**Comment by fantasai** [comment]
Agenda+ to poll the CSSWG on whether they want to make this change. I'm not sure how helpful it would be, and certainly it requires changes across almost all our specs.

Wrt to the suggested terminology, on the one hand it totally makes logical sense, on the other it emphasizes “flow” rather than “line” which is likely to be confusing to a casual reader. (What's a flow?) Line box is more immediately obvious: a box that contains a line (of text/inline content, as is frequently implied by the term).

**Comment by SelenIT** [comment]
Maybe "line container" could work as the name (or even "line fragmentainer", given that line boxes are effectively fragmentainers for inline content)?
