### ISSUE TITLE
[css-overflow] 'overflow-block' and 'block-overflow' are too similar

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2561]
I am thinking that authors may get confused because the names are so similar, and will end up using the wrong one.

`overflow-block` follows the standard convention for logical properties, so maybe consider renaming `block-overflow` to something different.

**Comment by heycam** [comment]
In #2849 I wondered whether there is a word we can use in place of block that fits `inline : text :: block : <something>`, since `block-overflow` has similar behavior to `text-overflow`.

**Comment by frivoal** [comment]
More than the property name, I have some reservations about the name of the 'clip' value, since it doesn't really clip anything and allows for (inline) overflow. It was named that way to keep the parallel with `text-overflow`, but I'm not sure this is working all that well (also this isn't really about overflow).

Alternate suggestion, attempting to address your concern and mine:
`block-ellipsis: none | ellipsis | <string>`
or maybe
`block-ellipsis: none | auto | <string>`

**Comment by rachelandrew** [comment]
I'm just writing some docs for MDN on overflow so was thinking about this property in terms of how to explain it. I like `block-ellipsis` as a descriptive term, it seems to more accurately describe what this property is doing and avoids any confusion with `overflow-block`.

**Comment by frivoal** [comment]
Agenda+ing to attempt to get a 3 part resolution:
1. rename the property from `block-overflow` to `block-ellipsis`
2. rename the `auto` value to `none`
3. rename the `ellipsis` value to `auto`

I'm strongly in favor of 1 and 2, weakly in favor of 3.
