### ISSUE TITLE
[css-fonts] Unknown fragment identifiers in @font-face src:

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#2566]
In the src: descriptor of `@font-face`, the author can include a fragment identifier to indicate a particular font of a collection should be used. As of https://github.com/w3c/csswg-drafts/commit/d4e059749a1e84e5845398b853b841f7122ddccd it's unclear what to do if the fragment identifier doesn't identify any font in the file.

There are probably two possibilities:
  - Use the first one in the file
  - Classify this situation as an error, and mark the url as failed

**Comment by litherum** [comment]
@svgeesus

**Comment by litherum** [comment]
Option 2 is probably bad because that's not how fragment identifiers work in any other situation. For example, if you navigate to an html page with a bogus fragment identifier, the UA will scroll to the top of the new page. I think this is the equivalent of option 1.

**Comment by svgeesus** [comment]
Agreed, the first font found should be the behavior.

**Comment by tabatkins** [comment]
> Option 2 is probably bad because that's not how fragment identifiers work in any other situation. 

Note that it *is* how unknown fragments work in [`image()`](https://drafts.csswg.org/css-images-4/#image-fragments), so that authors can get similar backwards-compatible behavior to how property fallback works.  For example, you can do `image("foo.jpg#newFragType(bar)", "manuallyApplied.jpg")`, falling back to the "manuallyApplied.jpg" image if the first either doesn't load or the UA doesn't understand the fragment type.

**Comment by tabatkins** [comment]
1. Yes they do!  `image()` support *requires* that implementations support the #xywh version of Media Fragments.

2. That's the point - they don't *yet*, and so *any* use of fragments (beyond MF, as mentioned previously) will result in the image being rejected and moving on to the next one.  So there's precedent for this kind of behavior, rather than just ignoring the fragment and making assumptions about the file.

**Comment by svgeesus** [comment]
Hmm. I do find this use case compelling:

```
image("all-icons.png#xywh=256,160,32,32", "icon_8_5.png")
```
where all-icons has all the icons together in a grid and uses media queries to crop out a specific one; the fallback is to download the individual image icons.

Similarly, if browsers ever supported OpenType Collection fonts, one would not want the 'first available' font to be selected:

```
src: url(SomeFont.otc#CondensedUltaSomething, CondensedUltaSomething.otf)
```

So I'm persuaded by @tabatkins argument.

**Comment by upsuper** [comment]
> src: url(SomeFont.otc#CondensedUltaSomething, CondensedUltaSomething.otf)

I don't think we want to use `url` function for this. It should either have a new function like `image`, or just rely on the fallback mechanism of `src` descriptor which has already been there.

**Comment by upsuper** [comment]
> src: url(SomeFont.otc#CondensedUltaSomething, CondensedUltaSomething.otf)

Also this syntax is probably not going to work anyway... You would need something like
```css
src: url("SomeFont.otc#CondensedUltaSomething", CondensedUltaSomething.otf);
```

**Comment by tabatkins** [comment]
Yeah, we def don't want to add to the `url()` syntax here; `src` already has fallback behavior.

**Comment by litherum** [comment]
I don't have a particular agenda about what the solution is, but it seems there are good arguments on both sides.

- `image()` seems to have one behavior
- document navigation seems to have the other behavior
- Today (in browsers which don't support fragments in font URLs) the browsers will just use the first item in the font

**Comment by astearns** [comment]
fwiw on the difference between image() and document navigation I think it makes sense to follow image() here as the @font-face is loading resources like image()
