### ISSUE TITLE
[css-backgrounds-3] Computed value of background-size includes missing autos

### ISSUE THREAD

**Issue by csnardi** [w3c/csswg-drafts#2574]
https://drafts.csswg.org/css-backgrounds-3/#the-background-size says the computed value of `background-size` is:

> as specified, but with lengths made absolute and omitted `auto` keywords filled in

https://wpt.fyi/css/css-backgrounds/background-size-001.html shows that only Firefox outputs the computed value with missing `auto`s. It seems this was added in https://github.com/w3c/csswg-drafts/commit/bfd84cfbfe39e8ace84e003080f1753c7674f8e8 by @fantasai, but I don't see any reasoning there. Perhaps this should be changed to remove the portion about omitted `auto` keywords, as it would also conform to the shortest serialization principle outlaid in #1564.

**Comment by BorisChiou** [comment]
I'm working on updating the serialization of `background-size` on Firefox. I think the serialization of `12px auto` as `12px auto` (instead of `12px`) is also pretty weird to me, and it makes the implementation more complicated. I'm happy to update the wpt to satisfy the shortest serialization principle in the same patch.

cc @emilio @dholbert

**Comment by BorisChiou** [comment]
Actually, what I thought is:
For example,
`input` => `serialzation of the computed value`
1. `auto` => `auto`
2. `auto auto` => `auto`
3. `12px` => `12px`
4. `12px auto` => `12px`

In other words, we omit the 2nd value if it is `auto`.
Both Chrome and Safari follow this rule, and it makes sense to me.

**Comment by emilio** [comment]
Agreed, that seems more correct than what FF is doing right now. Will add it to the agenda to get a resolution from the WG, but I assume this is quite uncontroversial if it matches both WebKit and Blink.

**Comment by fantasai** [comment]
The computed value and the serialization of the computed value are not the same thing, and also, the computed value line was updated along with all the others last fall.

**Comment by tabatkins** [comment]
Note that the "missing autos filled in" part is, in particular, designed to make it easier to talk about the value without needing to worry about specially handling omitted values.

**Comment by dholbert** [comment]
Also, it looks like the "omitted auto keywords filled in" text has been replaced in the ED, and I think the new text makes it clearer that it's describing something conceptual rather than a specified serialization format.  (Nice!)

The ED's current text is:
>Computed value:
> list, each item a pair of sizes (one per axis)
> each represented as either a keyword or a computed `<length-percentage>` value

Link: https://drafts.csswg.org/css-backgrounds-3/#the-background-size

(For comparison, the old text with "omitted auto keywords filled in" is in the CR snapshot at https://www.w3.org/TR/2017/CR-css-backgrounds-3-20171017/#the-background-size )
