### ISSUE TITLE
[css-backgrounds-3] Computed value of background-repeat includes two values

### ISSUE THREAD

**Issue by csnardi** [w3c/csswg-drafts#2575]
According to https://drafts.csswg.org/css-backgrounds-3/#background-repeat, the computed value of `background-repeat` is:

> A list, each item consisting of: two keywords, one per dimension

However, I believe no browser follows this part of the spec (see https://wpt.fyi/css/css-backgrounds/background-332.html, where `round` is computed to `round` instead of `round round`). This was changed in https://github.com/w3c/csswg-drafts/commit/a3493c458c797fe16b18302c7f02639f83524f55 in response to http://lists.w3.org/Archives/Public/www-style/2012Feb/1094.html from @dbaron, but I believe #1564 flipped that by suggesting the shorter serialization is preferred. 

Related to #2574.

**Comment by dholbert** [comment]
As noted in https://github.com/w3c/csswg-drafts/issues/2574#issuecomment-505938620 and the subsequent CSSWG resolution, the CSSWG says that the specced "computed value" is not intending to describe the serialization.  See also #4060

So, this issue here probably wants the same fate as #2574. CC @fantasai

**Comment by tabatkins** [comment]
Closing, as #4060's edits now make it clear that the "Computed Value" lines are *not* serialization instructions.
