### ISSUE TITLE
App. A: Aural style sheets is informative yet sounds normative

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#2586]
This goes all the way back to 2002 when it was made informative in ac046f711d.

> This chapter is informative. 

 - [ ] It's an appendix, not a chapter.

> The properties in this appendix apply to a media type 'aural', that was introduced in CSS2. The type 'aural' is now deprecated.

 - [ ] Are we informatively deprecating aural?

> User agents should allow the values corresponding to '0' and '100' to be set by the listener. 

 - [ ] Are we using RFC 2119 "should" informatively? What does it mean that a UA should implement this as an informative statement?

> This property specifies whether text will be rendered aurally and if so, in what manner.

 - [ ] Does it? I thought the property didn't really exist; the appendix is, after all, informative.

> For information, here is the list of properties implemented by Emacspeak, a speech subsystem for the Emacs editor.

- [ ] Why are we informatively giving an implementation report for an informative appendix in the spec?

More generally, why is this appendix even here? We obviously don't expect/want anyone to implement it (otherwise it would've been made normative again), so what do we gain by having it here? Should we define `display: run-in` (which was also in CSS2) informatively as well and rename it "Appendix A. Abandoned Features"?

**Comment by svgeesus** [comment]
>> For information, here is the list of properties implemented by Emacspeak, a speech subsystem for the Emacs editor.

>    Why are we informatively giving an implementation report for an informative appendix in the spec?

I can give some historical context on that one. T.V. Raman proposed some aural properties, which were adopted into CSS in June 1997 and merged into CSS2 in September 1999.
https://www.w3.org/TR/1999/WD-acss-19990902
https://www.w3.org/TR/WD-acss-970630

It was also given a test implementation, in Java (by Vincent Mallet, an intern I had).

Later, we discovered that Raman had drastically reduced and simplified the list of properties in his actual implementation - but we were unaware he had done so.

Remember this was way before Candidate Recommendation became a thing (and was one of the drivers for CR, in fact).

> More generally, why is this appendix even here? 

Good question. It serves no useful purpose.

I suggest that the new CSS2 spec:
a) drops this appendix
b) mentions in the changes since 2.1 that it was dropped, with a pointer to the corresponding appendix in 2.1
