### ISSUE TITLE
[css-fonts] Feature resolution and caps synthesis conflicting

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#259]
**On Fri, Jul 1, 2016 at 2:08 AM, Dominik Röttsches drott@google.com wrote:**

> Hi,
> 
> consider the following example:
> 
> span {
> font-variant-caps: all-small-caps;
> font-feature-settings: "smcp" 0, "c2sc" 0;
> }
> 
> https://drafts.csswg.org/css-fonts/#feature-precedence says that at
> font-variant-caps should be take into account at precedence level 4,
> however, at level 6 it is overriden by font-feature-settings. 
> 
> The synthesis rules in
> https://drafts.csswg.org/css-fonts/#propdef-font-variant-caps describe that
> if none of the native features are available, all-small-caps should be
> synthesized by upper-casing the text and downscaling the font.
> 
> However, what should be the exact definition of availability here, taking
> into account the feature resolution?
> 
> The feature resolution can be interpreted in two ways:
> 1) It means it should deactivate/hide the available features in the font and
> trigger synthesis since the resolved available feature set does not have
> smcp and c2sc, or alternatively, 
> 2) no synthesis is done since the feature detection has determined that the
> features are available and should be enabled through font-variant-caps, but
> then are deactivated through font-feature-settings.
> 
> Opinions? What should happen in this case -

**Comment by tabatkins** [comment]
I lean toward #1 (it seems to enable more scenarios, and I like the mental model it suggests), but I could be convinced by a consistency argument the other way.

**Comment by litherum** [comment]
Interpretation number two is correct. Because font-feature-settings overrides the font-variant-caps, the feature is considered off (and therefore no synthesis occurs).

**Comment by frivoal** [comment]
Also, while #1 is more expressive, I am far from convinced that what it can express actually has legitimate use cases. I mean, sure, if you are writing a textbook about typography, and want to illustrate using a font that has smallcaps how comparatively ugly it is when you use synthesized small caps instead of real ones, then maybe you'd want that. But I don't think the ability to demonstrate bad results that nobody should want is a use case we go after. If you want to do that, do it as an illustration / image. This isn't a case where a separation between content and style is valid.

**Comment by litherum** [comment]
I started investigating this more, and I have to say that I've changed my mind. The low-level property is used when the web author has a priori knowledge of what features the font supports, so browsers shouldn't get in their way by interpreting `font-feature-settings` to turn off synthesis. Browsers are currently discouraged (disallowed?) from inspecting the 4-character-codes passed to `font-feature-settings` in order to perform synthesis. Because the concepts of synthesis and `font-feature-settings` are divorced, in this case, the addition of `font-feature-settings` shouldn't have any affect on synthesis.

**Comment by litherum** [comment]
This piece also interacts with the fact that the individual font's character-based feature support (using the OpenType GSUB/GDEF Coverage subtable) must be consulted when deciding whether or not to perform synthesis.

**Comment by litherum** [comment]
With the following test, Firefox, Safari, and Chrome all agree on the rendering (modulo the implementation of `font-synthesis: small-caps;`):

```
<div style="font: 100px 'Avenir Next'; font-variant-caps: small-caps;">Hello, World</div>
<div style="font: 100px 'Avenir Next'; font-variant-caps: small-caps; font-synthesis: none;">Hello, World</div>
<div style="font: 100px 'Avenir Next'; font-variant-caps: small-caps; font-feature-settings: 'smcp' 0;">Hello, World</div>
<div style="font: 100px 'Avenir Next';">Hello, World</div>
<div style="font: 100px 'Times'; font-variant-caps: small-caps;">Hello, World</div>
<div style="font: 100px 'Times'; font-variant-caps: small-caps; font-synthesis: none;">Hello, World</div>
<div style="font: 100px 'Times'; font-variant-caps: small-caps; font-feature-settings: 'smcp' 0;">Hello, World</div>
<div style="font: 100px 'Times';">Hello, World</div>
```

Therefore, option 1 should be in the spec.

**Comment by litherum** [comment]
Also 388a53dc7c8876684f3f27ef68bfb437c3188633
