### ISSUE TITLE
[css-fonts-4] font-weight and calc.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2590]
This is just a request for clarification.

https://drafts.csswg.org/css-fonts-4/#font-weight-numeric-values says:

> Only values greater than or equal to 1, and less than or equal to 1000, are valid, and all other values are treated as parse errors.

This doesn't say how to handle calc(), but per my reading of previous discussions the expected behavior is that `font-weight: calc(-1)` is _not_ a parse error, and it gets clamped at computed value time.

However no UA does this AFAICT. Am I right that that's the expected behavior? Or should we give up on not making calc() for numeric values out of range be a parse error?

**Comment by emilio** [comment]
cc @litherum, @jwatt

**Comment by svgeesus** [comment]
I agree that [invalid at computed value ](https://drafts.csswg.org/css-variables-1/#invalid-at-computed-value-time) time is the right way to go here.

**Comment by emilio** [comment]
Alright, apparently there are already tests for this, so I guess Edge at least does the right thing, will align with it.

Thanks!

**Comment by tabatkins** [comment]
Yes, the spec is very clear on this matter - it should be clamped to 1 at computed value time. It is definitely **not** invalid at computed value time; that's not even remotely related to calc(), it's a variables thing.

It absolutely can't be a parse error, because in the general case you can have expressions that can't be resolved at parse time.  (V&U 3's calc() doesn't have any of these for purely numeric expressions, so you *could* tell at parse time what the value would end up being, but now that we have unit algebra it's back to being generally undecidable.)
