### ISSUE TITLE
[css-grid-2] subgrid border/padding/margin

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2592]
There's a problem with how subgrid BPMs (border/padding/margin) are supposed to work.  As I understand [the spec](https://drafts.csswg.org/css-grid-2/#subgrid-items), the subgrid item itself doesn't participate in the TSA (track sizing algorithm) of its parent grid in a subgridded axis.  Instead, the size contributions of any items in edge tracks are inflated with the BPM on that side.  This doesn't work very well when there are no items, or only subgrid items, or items only in non-edge tracks.  In those cases, the BPM isn't accounted for and the parent track size will be too small causing the subgrid to overflow it.

I suggest we fix this by making subgrids contribute its BPM as a span=1 contribution to the TSA in the relevant edge track(s).  So, for example 3x3 subgrid with `border:10px solid` will contribute 10px to its start and end tracks.  The 10px size is fed into the TSA the same way as a span=1 item would.  Any items in those tracks should also be inflated by 10px, same as before.  If the subgrid is 1x1 instead, then it contributes 20px.  This should make the parent large enough to fit the subgrid.  I've implemented this in my prototype subgrid implementation in Gecko and it seems to work well.  (It was trivial to implement.)

ISSUE 1: I propose we add subgrid BPM contributions per above

Size contributions involving BPM's also needs to be floored at zero at some point and the spec needs to specify when that occurs.  I tend to think the flooring should occur as late as possible, just before the size is fed into the TSA, so for example, an empty span=1 subgrid with `margin-top:-20px; margin-bottom:30px` contributes 10px.  If the subgrid's span > 1 then it contributes 0px to its start track and 30px to its end track.  When applying the relevant BPMs to the size of an item they are simply added as is and the final result is then floored at zero.  E.g. an item with `height:10px` in the 1x1 case would contribute 20px.  In the 3x3 case, a 10px item (w. span=1) in the first track contributes zero; in the last track it would contribute 40px; with span=3 it would contribute 10px.  BPMs of nested subgrids are also accumulated as is without flooring and only the final result is floored.

ISSUE 2: specify that size contributions are floored at zero and that the flooring occurs after all lengths are summed up just before the final result is fed into the TSA

**Comment by fantasai** [comment]
Wrt ISSUE 1: Currently the spec says

> The subgrid itself lays out as an ordinary grid item in its parent grid, but acts as if it was completely empty for sizing purposes in the subgridded dimension. 

So the MBP _is_ accounted for, the accounting is just not constrained to any particular track. I agree, however, that this doesn't quite give the expected results if, e.g. the first track is empty but the second one contains an item. We have I think two options here:

- Minimally account for the MBP by making sure that the combination of tracks from the last track with an item in it to the edge of the subgrid has enough space to accommodate the subgrid’s MBP.
- Strictly account for the MBP in the track at the subgrid’s edge.

The difference between the two accounting methods is most easily seen in an empty subgrid, e.g.  one spanning `auto 20px auto` tracks. Suppose the subgrid has 5px borders and 5px padding. In the first solution, the auto tracks will be zero width, since there's enough room for the borders and padding in the middle track. In the second solution, the auto tracks will be 10px each, because the borders and padding are forced to be accounted for in the outermost spanned tracks.

I'm not sure which solution is ideal from an authoring perspective. @rachelandrew @jensimmons  @frivoal @bradkemper ?

**Comment by fantasai** [comment]
(Wrt ISSUE 2, the TSA already floors tracks at zero, so we just need to make sure the span=1 with negative margins case you mention is handled correctly for subgrids if we go with option 2 above.)

**Comment by FremyCompany** [comment]
This might be very naïve, but the way I implemented this in the subgrid Houdini demo is to count the mbp on the full subgrid (for which I compute a minimum width based on the items min-content for auto columns), then as margin on each subitem that starts/ends in the first/last row or column of the subgrid. 

It's not very clear to me why it is desirable to ensure the mbp is accounted for in the first track, that track could be fixed-size and not able to accommodate that mbp, and you might want to accommodate it in the other tracks instead. But maybe I missed something.

**Comment by tabatkins** [comment]
Yeah, we can't make any assumptions about what size the tracks will be.

But Mats' suggestion (in addition to inflating margins, pretend there's an MBP-sized item in the first/last track) makes sense to me - it correctly handles the edge-case of the first/last track being empty.

**Comment by fantasai** [comment]
Alright, committed changes based on the WG discussion! Had to think through a bit what happens when there's items with different spans in that last occupied column and varying configurations of fixed/auto tracks, but I think I got it right. @MatsPalmgren @tabatkins @FremyCompany I can haz review?

Spec: https://drafts.csswg.org/css-grid-2/#subgrid-edge-placeholders
Changeset: https://github.com/w3c/csswg-drafts/commit/c2e0acf5da649d8e918954618c4a31418ee79508

**Comment by FremyCompany** [comment]
Thoughts: https://github.com/w3c/csswg-drafts/commit/c2e0acf5da649d8e918954618c4a31418ee79508#r29892956

**Comment by fantasai** [comment]
@FremyCompany OK, good catch. Tried making corresponding edits. I can haz review? :)

**Comment by FremyCompany** [comment]
Sounds good to me!
