### ISSUE TITLE
[cssom] Why is CSSRuleList [LegacyArrayClass]

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#2601]
The point of marking things "legacy" is that they should not be used...  Do any browsers implement this?  Why should they?

//cc @domenic @annevk

**Comment by csnardi** [comment]
It looks like [Firefox](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/CSSRuleList.webidl), [Chrome](https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/core/css/css_rule_list.idl), and [WebKit](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/CSSRuleList.idl) all do not implement this. (That is supported by the tests of CSSRuleList in https://wpt.fyi/css/cssom/interfaces.html)

**Comment by emilio** [comment]
So, 83d7e07f876ef79a95cf61209b075af22f868ca7 was introduced to fix #424, but that is only a rename. 

The actual commit that introduced this for MediaList is 16efbbdea3.

For CSSRuleList is 2821e3f7245b4644225f8b1e54c371353aed12f2, arguing "since there may be content that rely on item() working".

I guess that since nobody implements it that way, we can remove it.

**Comment by emilio** [comment]
cc @zcorpan

**Comment by bzbarsky** [comment]
So https://github.com/w3c/csswg-drafts/commit/2821e3f7245b4644225f8b1e54c371353aed12f2 switched from a totally-not-what-browsers-do sequence to an interface that still isn't what browsers do...

I should note that at one point I supported making pretty much all arraylikes without a named getter ArrayClass.  That was before it became clear that some browsers have no plans to ever implement ArrayClass on anything.  At this point the best path to interop is to never use LegacyArrayClass.

**Comment by zcorpan** [comment]
Removing use of `LegacyArrayClass` sounds good to me.
