### ISSUE TITLE
[css-grid-1] Browsers disagree on layout of all-auto columns with overlapping spans

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#2633]
In #2356, Florian provides an example layout using a bunch of fixed-size items spanning 5 auto columns in various configutations <https://unicode.org/cldr/utility/>.  Firefox and Chrome give *similar* results, but not identical; Edge gives a dramatically different result:

* In Firefox, the grid as a whole is 745x590, with extra horizontal space on items 1, 2, 4, 7, and 8.
* In Chrome, the grid as a whole is 760x590, with extra horizontal space on items 2, 4, 6, 7, and 8.
* In Edge, the grid as a whole is 760x710, with extra *vertical* space on items 1, 3, 5, and 6.  (Note: to get a reasonable display you'll need to `float: left` the grid, as Edge doesn't yet support `width: max-content`.)

This is all very confusing and distressing!  Who's right, if any? What needs to be fixed in the spec to make this clearer?

/cc @mrego @matspalmgren @atanassov

**Comment by MatsPalmgren** [comment]
Firefox Nightly and Chrome Canary (both on Linux) have identical layout AFAICT.
The content area is 750x580 and the used track sizes are the same in both:
```css
grid-template-columns: 160px 140px 125px 75px 210px;
grid-template-rows: 260px 90px 100px 100px;
```
We fixed a sizing bug for spanning items somewhat recently (caused by Grid spec bug #1729, fwiw). It'll be in the next release (v60). That _might_ explain your different results if you were testing v59.

**Comment by tabatkins** [comment]
Hahaha, I'm actually on Firefox 52, because that's the ESR installed by Ubuntu's `apt-get`. ://///

But if Firefox is matching Chrome now, that's :+1:. It's just Edge's behavior that is somewhat boggling, then.
