### ISSUE TITLE
[css-transforms-1] Presentation attribute as start or end value of a CSS transition

### ISSUE THREAD

**Issue by dirkschulze** [w3c/csswg-drafts#2684]
Implementations differ when start or end value of a CSS transition is defined by a `transform` presentation attribute. I'll investigate and add examples.

**Comment by dirkschulze** [comment]
## Test
I created a test case here: https://codepen.io/krit/pen/XqvqyG?editors=1100

The behavior is different across browsers:

| Interpolation | `transform="rotate(45) scale(2)"` **to** `transform: rotate(3turn) scale(1)`  |
| ------------- |:----------------------------------------------------------------------------- |
| WebKit        | `transform` attribute gets ignored; _from_-value turns to `none`.<sub>1</sub> |
| Blink         | Interpolation per transform - as speced.                                      |
| Gecko         | `transform` attribute gets ignored; _from_-value turns to `none`.             |
| Edge          | Interpolation per transform - as speced.                                      |

1. After the transition back to _from_ the value doesn't get reset to attribute value.

| Interpolation | `transform="rotate(45 50 50) scale(2)"` **to** `transform: rotate(3turn) scale(1)`      |
| ------------- |:--------------------------------------------------------------------------------------- |
| WebKit        | `transform` attribute gets ignored; _from_-value turns to `none`.<sub>1</sub>           |
| Blink         | No interpolation.                                                                       |
| Gecko         | `transform` attribute gets ignored; _from_-value turns to `none`.                       |
| Edge          | Interpolation per transform. _from_-value **ignores** translation of `rotate(45 50 50)` |

1. After the transition back to _from_ the value doesn't get reset to attribute value.

## Conclusion
* Blink and Edge do interpolation per transform function for all CSS supported transform functions as speced.
* No implementation does fall back to matrix decomposition if `rotate()` has translation/origin values.

**Comment by AmeliaBR** [comment]
My thoughts:

- Having an existing transformation suddenly disappear at the start/end of a transform is very bad behavior.

- Ideally, the values would be interpolated [according to the usual algorithm](https://drafts.csswg.org/css-transforms/#interpolation-of-transforms), with `px`/`deg` units serialized in.

- If that is not possible for implementations, then the entire attribute should be condensed into a single `matrix` transformation, and that used for interpolation. 

The 3-value rotate function is a little trickier. According to the current spec text, it is one of the [primitive transform functions](https://drafts.csswg.org/css-transforms/#transform-primitives), and the simple rotate function should be upgraded to the 3-value form and then transitioned. But since the 3-value form is legacy-only, I think it would be acceptable to change the spec so that the 3-value form is treated as its own unique function that doesn't transition to any other rotate form (i.e., forcing the transition to use the cumulative matrices).



(PS, @dirkschulze I changed the Agenda+ label, assuming you weren't intentionally deferring discussion until the August F2F.)

**Comment by dirkschulze** [comment]
@AmeliaBR The current WebKit behavior (not returning to attribute value) for sure is a bug. Just thought I'd mention it here as well. I _think_ that the behavior of Edge is a bug too or a compromise for simplicity reasons. Maybe @dstorey or @atanassov know.

The [current spec text](https://drafts.csswg.org/css-transforms/#svg-transform-functions) reflects your expectation for the most part I think. I missed to remove the 3-value `rotate()` function from the [primitives transform function](https://drafts.csswg.org/css-transforms/#transform-primitives) list but had the intention to do so. I agree that it should be seen as legacy. Nevertheless (as you seem to agree) it should not just be ignored or reduced to its rotation for interpolation IMO.

And yes, I hope we can agree on the behavior that we already have for interpolation between 2 CSS property values and find a solution for the 3-value `rotate()`. The spec text request matrix interpolation if the transform list contains a 3-value `rotate()`.

IMO this is might be an extremely rare case anyway but should be clarified since implementations differ.

**Comment by AmeliaBR** [comment]
> IMO this is might be an extremely rare case anyway

I usually recommend that authors use the `transform` attribute for core aspects of the design (for backwards compatibility), and then use CSS transforms as progressive enhancement, such as `:hover` effects or media query adjustments. It is quite reasonable that an author would try to add a transition between the base and the enhanced state. So that much I'd consider core functionality.

Transitioning from/to a 3-value form is less likely, but it still needs an unambiguous behavior.

**Comment by tabatkins** [comment]
Yeah, I think it's most reasonable to just treat the 3-value rotate() as a new primitive that's compatible with nothing (including itself), so you always get matrix interpolation if it's used.
