### ISSUE TITLE
[css-variables] should "--" be a valid custom property name?

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#2692]
https://drafts.csswg.org/css-variables/#typedef-custom-property-name

> The <custom-property-name> production corresponds to this: it’s defined as any valid identifier that starts with two dashes.

Shouldn't it be "any valid identifier that starts with two dashes and has a length greater than equal to 3"?

**Comment by tabatkins** [comment]
The production needs to stay as written - `--` is intended to be a valid custom property name. That said, I intend to *reserve* `--` as a variable-specific `all`, so I should probably put an additional restriction there. ^_^

**Comment by bradkemper** [comment]
I’m fine with reserving it, but what situation is writing `—` better than just writing `all`? I assume you have something in mind?

**Comment by FremyCompany** [comment]
I should not it's valid but not special (it does not reset all the other custom properties)

**Comment by tabatkins** [comment]
> I’m fine with reserving it, but what situation is writing — better than just writing all? I assume you have something in mind?

When you're trying to prevent variables from inheriting into a component, but want to allow normal properties to inherit. (Without having to put in 100+ `foo: inherit` declarations.)

> In Edge -- is a valid custom property today, and it works fine in both declaration and usage.
Doesn't it in other browsers?

Yes, thus the issue and Agenda+.  It's currently valid and a perfectly normal property; I'm asking if we can restrict it (and then give it a special meaning).

**Comment by FremyCompany** [comment]
Ah ok. Sure, I'm fine with this. It wouldn't be hard to do.

**Comment by AmeliaBR** [comment]
For whenever it does come up in Variables 2, might I recommend `all--` as the "variable-specific version of `all`".

**Comment by lahmatiy** [comment]
All browsers I tried treat `--` as a valid custom property name (I've tried Chrome, Firefox and Safari; Edge the same as mentioned above).
Since it works in most (all?) browsers with custom properties support, it can be already used somehow by authors. For example, it using in [CSS Battle](https://cssbattle.dev/) as [a trick to minify size of CSS](https://spectrum.chat/css-battle/general/tips-n-tricks~6034b7fa-d08b-463a-9720-decb5e2c0f5b?m=MTU1NzY3Nzc0MTYyMQ==). I suppose CSS minifiers and other tools can util this technic as well.
It is likely that reserving `--` will be useless.
