### ISSUE TITLE
[css-text-decor-3] a image file is not found

### ISSUE THREAD

**Issue by momdo** [w3c/csswg-drafts#2699]
https://drafts.csswg.org/css-text-decor-3/#text-emphasis-position-property
At note section, https://drafts.csswg.org/css-text-decor-3/images/text-emphasis-ja.gif is not found.

**Comment by frivoal** [comment]
@fantasai I've fixed the broken link (sorry for breaking it in https://github.com/w3c/csswg-drafts/pull/2688). However, the new image has a white background, unlike the old one which was transparent. It's kind of hard to make the white background transparent since the font is anti aliased.

In the case of 2688 that didn't matter, but here it is a little unsightly on the green background. Do you think that's fine? Should I restore the previous image as well for the purpose of this figure? Something else?

**Comment by svgeesus** [comment]
> However, the new image has a white background, unlike the old one which was transparent. It's kind of hard to make the white background transparent since the font is anti aliased.

Use the antialiased image as the alpha channel; set a solid color on the color channel(s). Convert to PNG with alpha transparency. Will now display, anti-aliased, on any background.

**Comment by frivoal** [comment]
@svgeesus thank you! problem now fixed.
