### ISSUE TITLE
[css-color] "transparent" keyword being a special color value, which resolves to rgba(0,0,0,0) by default?

### ISSUE THREAD

**Issue by jonjohnjohnson** [w3c/csswg-drafts#2722]
https://drafts.csswg.org/css-color-4/#transparent-color

@tabatkins -> https://twitter.com/tabatkins/status/1001884320229830656

I used to forget about gradient interop issues with the `transparent` keyword all the time (https://stackoverflow.com/questions/30673204/css-linear-gradient-transparency-misbehaving-only-in-safari) and I know safari still doesn't "automagically" (https://twitter.com/tabatkins/status/1001885856716615680) treat the case described.

Is it possible that implementation of `transparent` isn't beyond tweaking the spec to *fix this?

**Comment by tabatkins** [comment]
Summary of the twitter thread:

* My original goal was to make `linear-gradient(white, transparent)` work "as expected" - white gradually fading away. As originally specced, it instead became grayish as it faded, as 'transparent' is actually #0000.  You could fix this by saying `white, #fff0`, but then you still can't easily fade back in with a different color - `white, #fff0, red` will be pinkish at the 3/4 mark. You instead needed to explicitly add two transparent stops with different color, like `white, #fff0 50%, #f000 50%, red`, and now this is a 4-stop gradient rather than the 3-stop that it *looks* like (so it won't animate with other 3-stop gradients).
* I assumed the 'transparent' equivalency was fixed, so I attacked the problem from a different angle, and specified that gradients transition in premultiplied space. `white, transparent` now works properly, as does `white, transparent, red`.
* Downside is that now if you *want* to color-shift as you fade, you can't do it easily. You instead have to add multiple intermediate stops to force it to "curve" in premultiplied space.  (But at least it's easy to figure out - you just manually do the linear interpolation you want to see - `rgba(100%, 100%, 100%, 1), rgba(50%, 50%, 50%, .5), rgba(0,0,0,0)` goes grayish, tho in practice you'll want a few more stops to make it smoother.)
* Further downside is that this doesn't match implementation internals - all the graphics libraries transition in un-premultiplied space, like the spec originally mandated. So to get the premultiplied behavior, browsers have to *internally* add several intermediate steps to "curve" it thru un-premultiplied space. ^_^


After my rant, @fantasai suggested that maybe we could still fix this, and just special-case `transparent` to *normally* resolve directly to `#0000`, but let gradients key off of it specially and do the no-color-change behavior. That way if you explicitly write a transparent color, you *will* get the standard un-premultiplied color shift.  This would allow browsers to switch back to the native behavior of the underlying graphics library, and just special-case "transparent" by turning it into one or two stops.

Thoughts?

**Comment by svgeesus** [comment]
> @fantasai suggested that maybe we could still fix this, and just special-case transparent to normally resolve directly to #0000, but let gradients key off of it specially and do the no-color-change behavior. 

That sounds tricky to explain in a spec, but would map better to underlying libraries. Premultiplication suffers from erosion of resolution (effective number of bits) unless calculations are done in an elevated bit depth, which most graphics libraries don't.

**Comment by tabatkins** [comment]
Agenda+ because this also ends up mattering for cross-fade(); I don't want `cross-fade(img 50%)` to darken the image, and it would be weird for that syntax to work differently than `cross-fade(img 50%, tranparent 50%)`.

**Comment by svgeesus** [comment]
So we would special-case cross-fade() as well as *-gradient()? Anywhere else?

**Comment by tabatkins** [comment]
I discussed the question of how cross-fade() can work with one of Chrome's implementors, and they said it didn't matter, they could do the averaging in premultiplied or non-premultiplied space, as Chrome does both at different parts of our compositing/rendering pipeline anyway.

I also researched the dissolve operation a little more; whatever reference I was originally looking at treated it as an unary operation that you applied to a single image, but Wikipedia defines it as a binary op (trivially extensible to an N-way). It's oddly defined as a stochastic operation that just randomly takes pixels from the source images according to their weights, but in the limit of infinitely small pixels, this converges to averaging in premultiplied space.

So, I've changed the spec to be clear that this averaging is done on premultiplied colors, and provided a good bit of additional detail on the operation to make sure it's clear. f6909a183

**Comment by svgeesus** [comment]
So @tabatkins does your https://github.com/w3c/csswg-drafts/commit/f6909a183350f15c245be0c70083a14e0c30c470 on css-images-4 completely solve this issue, or are changes also needed for css-color-4 ?

**Comment by tabatkins** [comment]
Solves it now. The direction seems to be "do pre-multiplied blending when appropriate, for whatever needs it".

**Comment by SebastianZ** [comment]
I want to reference https://lists.w3.org/Archives/Public/www-style/2016Jan/0181.html here, where transition to and from transparent was discussed earlier.

Sebastian

**Comment by svgeesus** [comment]
@leaverou wrote

> Any color transition, e.g. between solid colors over time.

While looking for something else, I just noticed that similar handling of `transparent` for transitions (and animations?) fell through the cracks. Should this be re-opened?
