### ISSUE TITLE
[css-fonts] FontFaceSet uses referential equality for calculating .has()

### ISSUE THREAD

**Issue by craigkovatch** [w3c/csswg-drafts#273]
FontFaceSet.has is not very useful right now, as it appears to use referential equality when comparing. So if I want to avoid adding duplicate FontFaces to my document, as currently speced I will have to do my own iteration and deep value comparison.

Could FontFace expose some sort of comparison method that could be used by FontFaceSet to provide easier deduping? i.e. so the following code could work:

```
var font1 = new FontFace("test", "url(test.woff)", {});
document.fonts.add(font1);
var font2 = new FontFace("test, "url(test.woff)", {});
if (document.fonts.has(font2)) {; // this should be useful
  continue;
}
```

**Comment by tabatkins** [comment]
The current behavior is just how JS Sets work, so `.has()` isn't going to change.

However, we could possible add a looser comparison function.  What is currently causing you to add duplicates to the page?  Why can't you avoid doing that in the first place?

**Comment by craigkovatch** [comment]
The content I'm rendering (and thus the fonts needed to render) can change based on server responses. Currently I'm having to generate a hash of all the necessary font properties and store it locally to ensure I don't add a duplicate font. But the general question of "is this font already defined in the document" seems like a fairly common scenario, and one that may be puzzling when .has() is reporting referential equality rather than (deep) value equality. 

Is it possible to define a looser comparison function that .has() would use? Or would it have to be a separate ability in FontFaceSet?

**Comment by craigkovatch** [comment]
It may also be reasonable for me to file a bug against the browser(s) to say "should no-op if an identical font definition is added".

**Comment by litherum** [comment]
The implementation of this comparison function is site-specific, and therefore cannot be implemented by the browser. For example, the browser doesn't know th example to questions like these:

- Many browsers don't implement font-stretch. Should this be a part of the comparison function? What happens when these browsers start implementing it? Existing websites break?
- Should two URLs with different fragment identifiers be considered distinct?
- What about "url(foo.woff)" compared with "url(foo.woff), url(fallback.woff)". These appear to be the same only if all the characters in the elements styled with them are supported by foo.woff
- foo.woff and foo.woff2 are often conceptually same font
- Are url(foo.ttf) and local(foo) distinct?
- How about unicode-range? If the ranges for the two fonts don't overlap? If they overlap by only one code point?

**Comment by craigkovatch** [comment]
I see what you're saying about the complexity of implementing this, but I'm not suggesting the comparison be that clever. Just do value equality for each member of FontFace. All the pertinent vales are DOMString. No need for parsing the semantics of each value.

**Comment by litherum** [comment]
Such an implementation would give incorrect results for many (most) applications and would be actively harmful.

**Comment by craigkovatch** [comment]
How and why? The point is to be able to construct FontFace objects and compare them to the Document's set. If you're going to make such a strong claim, provide am example of how -- within such a context -- this could be incorrect or harmful.

**Comment by tabatkins** [comment]
I agree that for the suggested usage (a single app trying to dedupe its own stuff) a generic and simple string-comparison method would work fine.

However, because such a simple method works fine, it's less clear that we need to add anything to the spec - it's trivial to write a comparison method that iterates over the set and checks if a given font is already there.  A native implementation won't be any faster than what you can write yourself, as it would have to do iterate-and-compare too.  And I'm not sure that the use-case is widespread enough to justify shipping an implementation to everyone else. :/

**Comment by craigkovatch** [comment]
I think those are reasonable points. You're right that it's not that hard to implement. It's kind of a bummer to make *everyone* implement such a low-level method. But my bigger concern is that people won't realize that .has() doesn't work in any useful way and the many debugging hours that could be lost to such a detail.

At the very least, what would you think about the spec offering a note of caution?
