### ISSUE TITLE
[css-contain] `contain` may not want to be animatable.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2737]
I can't think of a use case for it, and sounds like it may make optimizing it harder? Though I don't have a sense of this, maybe @mrego does.

cc @birtles, which noticed this.

**Comment by tabatkins** [comment]
While animating it would negate much of the performance benefit, there's nothing about it that makes it bad to animate (unlike 'display', 'animation-*', etc).  Considering how useful it is to animate various other properties without actual animation behavior (like, say, border-style from "none" to "solid"), I'm loathe to restrict properties that don't cause actual logical issues with animation.

**Comment by tabatkins** [comment]
Note: I'm not *strongly* against it, I'm just holding the general position of "let people shoot themselves in the foot unless it actually causes problems".

**Comment by birtles** [comment]
My concern is that at an implementation point of view it's slightly more complex to depend on the animated value of a property, than it's computed value.

We'll need to ensure that `will-change: contain` generates a stacking context too (since we don't want animations generating stacking contexts mid-way through as it looks horrible, causes jank, and prevents sending them to the compositor in advance).

**Comment by frivoal** [comment]
I'm confused. It already says `Animation type: discrete`.  Is there such a thing as `Animation type: none`? Otherwise, what are you asking about?

Reading https://drafts.csswg.org/css-transitions/#animatable-types:

> Some property types can be interpolated, which means they can animate smoothly from one value to another. Other property types cannot, and thus animate only in a single step from one value to the other. 

That does not suggest a difference between discrete and none.

**Comment by birtles** [comment]
Yes, there is such a thing as `Animation type: not animatable`. For example see the [`animation-duration`](https://drafts.csswg.org/css-animations/#animation-duration) property. Web animations also defines the [not animatable](https://drafts.csswg.org/web-animations-1/#concept-not-animatable) concept.

**Comment by frivoal** [comment]
So If the web Animation spec is right that some properties can be non animatable (as a separate concept from discrete interpolation), this needs to be clarified in the transitions and animations spec, including a definition of what happens when you transition over a non animatable property, then we need to review all the specs that use `Animatable: none` to decide if they mean `Animation Type: discrete` or `Animation Type: none`.

Or, we decide that there is no distinction, in which case Web Animations needs to be fixed. (and we still need to update all instances of `Animatable: *` into `Animation Type: *`

**Comment by birtles** [comment]
There a summary of the status quo here: https://github.com/w3c/csswg-drafts/issues/2736#issuecomment-394529978

Basically, I need to edit V&U before I can fix the other specs but every time I've tried I've got stuck working out how to refactor V&U.

**Comment by frivoal** [comment]
I think I get it now.

So this issue is blocked on https://github.com/w3c/csswg-drafts/issues/2736#issuecomment-394529978, and once that solves how to declare things as non animatable (and exactly what that means), we can fix this one.

**Comment by birtles** [comment]
Yes, that's right. Although this issue is really just raising the question about whether or not `contain` should be added to the set of non-animatable properties: `animation-*`, `transition-*`, `animation`, `transition`, and `display`. We might just decide it should be animatable and close this issue as invalid.

**Comment by frivoal** [comment]
I don't think authors care very much one way or the other, so it's more a question to implementers. @mrego @eaenet, what do you think?

**Comment by mrego** [comment]
I'm not an expert on animations or the implications of this, but it'd fine with me if it works similar to `display` or something like that. I don't really see the point of animating it, but again I don't have a strong opinion on this topic.

**Comment by fantasai** [comment]
I think treating it the same way as `display` makes sense. I could imagine an implementation wanting to e.g. construct its box tree in slightly different ways depending on `contain` and the optimizations it allows.
