### ISSUE TITLE
[css-text] spaces before break in 'pre-wrap' text should allow combination of hanging and collapsing

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#277]
[4.1.3. Phase II: Trimming and Positioning](https://drafts.csswg.org/css-text/#white-space-phase-2) in css-text-3 says:

<blockquote>If spaces or tabs at the end of a line are non-collapsible but have white-space set to pre-wrap the UA must either hang the white space or visually collapse their character advance widths such that they don’t take up space in the line.</blockquote>

Based on the discussion in [Mozilla Bug 1008019 - When a space overflows the width of a div, the previous word wraps as if it's attached to the div, with white-space: pre-wrap;](https://bugzilla.mozilla.org/show_bug.cgi?id=1008019), particularly starting at [comment 34](https://bugzilla.mozilla.org/show_bug.cgi?id=1008019#c34), it is my understanding that:
 * Chromium uses a combination of the two behaviors
 * in that bug, we're likely to change Gecko to do the same

It seems like the spec should allow the combination of the behaviors (i.e., collapsing only the part that would extend past the end of the line).

**Comment by JasonWoof** [comment]
We're discussing having gecko collapse only the part (of the whitespace at the end of the line) that extends beyond the _bounding box_

**Comment by frivoal** [comment]
Fair point. we should probably adjust the spec accordingly, as nobody collapses all the spaces. That said, note that:
- IE/Edge don't collapse at all, and hangs the spaces
- Safari does what you say you'll do
- Chrome does a strange inbetween thing: the overflowing spaces are sort of collapsed, since text-decoration for example won't underline them, but if you select them the selection will extend past the box. test here: http://jsbin.com/difonuw/1/edit?html,css,output

So the IE/Edge behavior is now ok and would stay ok after the change you suggest, the Safari would be more clearly ok after the change than before (and I think you plan to do the same thing), and the chrome behavior is just weird. I don't know that it is intentional though.

Finally, don't be too fast in dropping old code (well, sure you have source control...), some of the behavior Mozilla has now under `white-space:pre-wrap; word-wrap: break-word;` should be preserved for `white-space:pre-wrap; word-wrap: break-spaces;` when https://github.com/w3c/csswg-drafts/pull/111 gets merged (it's already resolved, just tweaking the wording now).

**Comment by JasonWoof** [comment]
Awesome! Thanks for all the details. It's good to hear that we're on the right track, or at least close enough to move forwards.

Thanks also for the heads-up about #111. I don't think we're dropping any code that would help with implementing `break-spaces`, since the old behavior in firefox is to never see break opportunities in the whitespace after the last word (of any line) and instead (if the whitespace extends beyond the available space) break _before_ the last word. i.e. firefox (in `pre-wrap`) acts as if the spaces after a word are part of that word.

**Comment by fantasai** [comment]
The general preference was to move towards hanging the extra spaces, not visually collapsing them, so if Gecko is working on this issue it should choose to hang the spaces. The allowance for visually collapsing spaces is for Level 3 only, and won't be preserved in level 4.

**Comment by fantasai** [comment]
(Unless there's some compelling reason why visually collapsing is better and everyone should change to doing that instead of what Edge is doing.)

**Comment by JasonWoof** [comment]
The only case I can think of where hanging space would be worse is when selecting text in <textarea>s. I think it would be confusing to have the hilight extend beyond the textarea.

I'm trying to get my patch to gecko merged which improves its handling of pre-wrap breaking. It collapses the portion of the whitespace that overflows the box bounds, because I can do this easily (I'm new to gecko development). I think it's a vast improvement on gecko's current behaviour which is to break in the wrong place (it wraps words to the next line that fit just fine on the current line)

It would take someone with more knowledge of gecko than me to implement spaces that hang outside of bounding boxes without triggering overflow/scrollbars/etc.

I hope they merge my patch in the meantime.

**Comment by JasonWoof** [comment]
Oop, discussion on gecko bugzilla has revealed another case where hanging spaces is potentially quite problematic: contenteditable nodes.

**Comment by FremyCompany** [comment]
If I read correctly, no change is required from Edge at this point, except if Gecko decides it is best to match Chrome in this case (then we need to have the spec updated). Do you have any ETA for the patch you want to submit? Is there any live-site bug you are trying to fix?

-----------------------

Another variant that is interesting to try out is to apply "text-align: justify" on the element (maybe "center" would reveal interesting things, too).

- In Edge, we only justify as a shrink to fit for the whitespace that does not fit (and when you try to select it, suddenly we stop applying text-align:justify on the whole line).
- In Chrome, the whitespace gets trimmed and non-whitespace text occupies both ends of the container.
- In Firefox, this cannot happpen at this time, so the problem does not apply.

**Comment by JasonWoof** [comment]
The gecko work I'm aware of and helping with is happening here: https://bugzilla.mozilla.org/show_bug.cgi?id=1008019

The priority for me (and the problem the original bug report there was about) is making the visible text break in the right place. And now that we're working on fixing that, we're trying to get the whitespace to behave properly too.

**Comment by frivoal** [comment]
@JasonWoof I believe that the extra control introduced in https://github.com/w3c/csswg-drafts/pull/111 deal adequately with the text-area and contenteditable use cases you mentioned.

**Comment by palemieux** [comment]
@dbaron @frivoal Is it possible to confirm that the proposed fix will result in both `div`s at https://codepen.io/palemieux/pen/PjeKyq being displayed identically? It would be very strange if the position of the space (inside or outside the `span`) would cause different results.

**Comment by frivoal** [comment]
@palemieux It looks like you sent the wrong link, failed to save, or overwrote what you have saved, as the codepen you sent doesn't contain two `div`s, nor anything with `pre-wrap` on it.

**Comment by palemieux** [comment]
@frivoal Ah. _spaces before break_ and _Chrome_ caught my attention, and thought this thread might be related to the issue highlighted in the codepen with Chrome when `white-space: normal;`.

**Comment by fantasai** [comment]
Just to clarify, afaict, this was fixed in https://github.com/w3c/csswg-drafts/commit/dcb654bae2e0386fd52386190540e5372ee2d300 :)
