### ISSUE TITLE
[mediaqueries-4][mediaqueries-5] Is the `<mf-range>` "swapping value and name" syntax really useful?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2791]
The `<mf-range>` syntax allows:

```
<mf-range> = <mf-name> [ '<' | '>' ]? '='? <mf-value>
           | <mf-value> [ '<' | '>' ]? '='? <mf-name>
```

That is, both `500px > width` and `width > 500px` is valid.

This is nice, but given `<mf-value>` can also be an `<ident>` it causes ambiguity, and complexity / slowness while parsing.

Given you can easily use negations, I think it's not terribly useful, but if people feel very strongly about it the spec should define how to resolve the syntax ambiguity.

**Comment by emilio** [comment]
cc @frivoal

**Comment by emilio** [comment]
There's a further problem with that, which is that we parse the value in terms of the feature name, so if we haven't seen the feature name we don't know which kind of value we're parsing. This becomes a bigger problem given you may need to parse arbitrary stuff like `calc()` as part of `<integer>`s or `<length>`s.

**Comment by tabatkins** [comment]
The full `100px < width < 500px` syntax *is* useful (and one of the main reasons we finally revived this syntax), and has the same issues as the more trivial `100px < width` example you bring up.

**Comment by tabatkins** [comment]
Oh, hm, I guess `100px < width < 500px` is detectable just from the number of tokens there, while `100px < width` isn't as easy to tell.

I'm fine with just dropping that syntax clause, then, if that's the only problem.

**Comment by emilio** [comment]
Yeah, though even if it's detectable it's kind of a pain to detect, you need to start accumulating tokens and doing lookahead instead of just looking at the feature name.

Is `(100px < width < 500px)` really so much more useful than `(width > 100px) and (width < 500px)` to justify the implementation complexity?

**Comment by frivoal** [comment]
I think the readability benefits are quite strong. In a media query that only consists of `(100px < width < 500px)` (or the expanded form), it is not *that* critical, but as soon as you combine it in some larger boolean syntax, the mental overhead goes way up if you have to think of it as a boolean expression, rather than a simple range thing. Yes, it is equivalent, but reading it as a range is much easier.

`@media (pointer) or (100px < width < 500px) {...}`
vs
`@media (pointer) or ((width > 100px) and (width < 500px)) {...}`

It is just syntactic sugar, so if the concern from the implementation side is too strong, we could simplify a bit, but it is really nice sugar.

Like Tab, I wouldn't be too sad about loosing `500px > width` in favor of `width < 500px`, but I would be sad about loosing `100px < width < 500px`
