### ISSUE TITLE
[css-values] should ic unit use 永 instead of 水?

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#2798]
https://drafts.csswg.org/css-values-4/#ic

A minor issue, but I wonder if the ic unit should use the advance of the 永 glyph instead of 水? To me 永 feels like it's closer to the idea of a representative Chinese character.

https://en.wikipedia.org/wiki/Eight_Principles_of_Yong

But I'd be interested to know if there was a particular reason for choosing 水.

**Comment by frivoal** [comment]
Good point. I think switching is reasonable. In the vast majority of fonts, it should not make any difference, and 永 is indeed more iconic.

I think 水 was picked as a character that's common (so that it would be in every font) and that did not differ based on the language. 永 should fit that bill too.

**Comment by myakura** [comment]
[Writing Modes uses 水 as well](https://www.w3.org/TR/2018/CR-css-writing-modes-3-20180524/#text-combine-compression) (used when scaling down the tate-chu-yoko to 1em). If switching to 永, I kinda want to see two specs refer to the same character.
