### ISSUE TITLE
[css-logical-1] flow-relative values should say what their computed values are

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#2821]
The [section on flow-relative values](https://drafts.csswg.org/css-logical-1/#directional-keywords) defines a bunch of new values for existing properties.  However, it doesn't say how these values influence the computed values of the properties, and I think it should say so explicitly (especially since the properties' existing "Computed Value:" lines may be wrong).

In other words, it needs to be clear whether `float: inline-start` results in a computed value of `inline-start` or a computed value of `left` (or `right`, depending on writing mode).  I tend to think the computed value should be `left`.

I got here from w3ctag/design-reviews#286.

**Comment by Loirooriol** [comment]
Note that `text-align: start` and `end` compute to themselves and not to `left` or `right`.

**Comment by Loirooriol** [comment]
I implemented `float/clear: inline-{start,end}` and `resize: {block,inline}` in Blink (behind a flag) so that they compute to the physical values. Because this matches Firefox for  `float/clear` and was simpler to implement.

If the opposite behavior is resolved, this WPT will need to be edited: https://github.com/web-platform-tests/wpt/pull/12326

**Comment by fantasai** [comment]
They should definitely not compute through. As you point out, this would break inherited properties like `text-align`. It also would mean that the CSSOM privileges physical coordinates over logical ones, which would be unfair.
