### ISSUE TITLE
[css-box-3] child-contain: border-box; to resolve child margins at parents edge

### ISSUE THREAD

**Issue by Meteor0id** [w3c/csswg-drafts#2848]
Countless times did I hit the same issue: I want to give child elements a margin all around them so they always keep distance from eachother. But I cant predict which children will border their partent containers edges, so I have no easy way of eliminating the margin where children are side to side with their parent.

Yes I could give the parent a negative margin and hide overflow, but that will only work if all children have the same margin, otherwise I pull content out of the partent too far or not far enough.

I could try to mess around with a calculated with, but that again often requires me to know with element will be dispalyed where, which especially on responsive designs I often can not predict.

Could we look into one simple property just for this problem.

child-contain: border-box;

meaning contain any child by its borders, but let the margins overflow. Default would me contain margin-box. And when we are add it it makes sense to consider contain padding-box and contain content-box;

Could we draft this?

I originally considered calling this property contain: , but it seems that same name has already been applied to another property in candidate release, where the name is rather vaguely related to what that property does. Too bad. child-contain will do, as it clearly indicates what is being contained, followed by a value of how it is being contained.

**Comment by Meteor0id** [comment]
When the parent is a flex container I can not set flow-root, as it is already display:flex;
first-child and last-child can also not solve this issue in a flex element, where it is not know ahead of time which child elements will be at the border.

**Comment by Meteor0id** [comment]
It might solve my problem, however would it not make more semantic sense to have a property which may be applied on any element?

`child-contain: border-box;` (Instructs that the margins of any child element will not be contained, but the borders and padding will be. Margins still have affect between children.)

Other options:
`child-contain: padding-box;` (margin and border of any child element will overflow)
`child-contain: margin-box;` (default, contain every part of child elements)

not sure if `child-contain: content-box;` will have a use case.

When gap is introduced, the issue has been addressed for flex boxes, but why not introduce a more general property which may apply on all relatively or statically positioned elements?

**Comment by tabatkins** [comment]
Because other layout systems have different constraints, and the problems are different. ^_^  In particular, margin collapsing and floats end up making it very complex to add the equivalent of 'gap' to block layout, much more so than it is in Flexbox or Grid.  Note that, for example, `child-contain: margin-box` as you describe it is *not* the default value for Block layout; child margins are allowed to "escape" (collapse thru) the parent if the parent has no padding or border, but are "contained" if it does, so it's not just a matter of the child deciding what it wants to do.

Furthermore, the *use cases* of Block layout (laying out text, generally) don't really call for that type of control over separation between children; if that's the sort of thing you need to be doing, you probably want to switch to a layout mode more specialized for your problem, like Flexbox.  Your use-case can be done in Block layout by just setting top/bottom margins on each child, and then setting the top margin to 0 on `:first-child` and bottom to 0 on `:last-child`.  You can't rejigger the order of elements in block layout; you can't have multiple rows of content so that multiple unpredictable elements are bordering the parent (except in multicol, which has some special abilities as a result); these are all things that Flexbox and Grid can do, and that's why we have specialized properties to make it easier to achieve these things there.

**Comment by fantasai** [comment]
Added a `margin-trim` property per #3068 which I believe should solve this use case.
See http://drafts.csswg.org/css-box-3/#margin-trim

@Meteor0id Can you have a look and let me know if this would resolve your concerns?

See also follow-up issues https://github.com/w3c/csswg-drafts/issues/3256 and https://github.com/w3c/csswg-drafts/issues/3255
