### ISSUE TITLE
[css-pseudo-4]: How should a selected spelling error be painted?

### ISSUE THREAD

**Issue by dbates-wk** [w3c/csswg-drafts#2850]
Looking to understand <https://drafts.csswg.org/css-pseudo/#highlight-painting>. How should the following markup be painted when you select the entire contents of `<p>`:

```html
<!DOCTYPE html>
<html>
<head>
<style>
body {
    text-decoration: underline;
    background-color: magenta;
}
p {
    color: black;
    background-color: white;
}
p::spelling-error {
    color: red;
}
p::selection {
    background-color: lightblue;
}
</style>
</head>
<body>
<p contenteditable="true">Select this entire sentence with the missspelled word.</p>
</body>
</html>
```

Should it paint as:

<img width="380" alt="pseudo-elements-replace2" src="https://user-images.githubusercontent.com/20798617/42139212-044a1db2-7d3e-11e8-8989-c0371ee6e4a4.png">

?

OR

<img width="359" alt="pseudo-elements-inherit" src="https://user-images.githubusercontent.com/20798617/42138992-0f102924-7d3b-11e8-8b07-fefc37d3fb30.png">
?

**Comment by dbates-wk** [comment]
CC @dbaron @fantasai @frivoal @smfr @litherum

**Comment by shallawa** [comment]
I think the second picture is the correct one.

According to the spec: 

> The ::selection overlay is drawn over the ::spelling-error overlay which is drawn over the ::grammar-error overlay.

I think this means the spelling-error overlay has to be drawn first which will draw the text with red color. Then the selection highlight overlay should be drawn next which will fill the selection rectangle with lightblue color.

**Comment by atanassov** [comment]
@grorg I don't see enough conversation to merit wg time just yet. Let's give others time to respond here first.

**Comment by fantasai** [comment]
If ::selection is drawn over ::spelling-error, then the color of ::selection wins in case of a conflict. However, ::selection says that if a `color` isn't specified, but a background is, then we use the text’s own color. Which in this case is the spelling-error color. So I agree with @shallawa that the spelling-error would be red.

If ::selection had specified a 'color', though, it would be that color.

**Comment by dbates-wk** [comment]
> If ::selection is drawn over ::spelling-error, then the color of ::selection wins in case of a conflict. However, ::selection says that if a `color` isn't specified, but a background is, then we use the text’s own color. Which in this case is the spelling-error color. So I agree with @shallawa that the spelling-error would be red.
> 
> If ::selection had specified a 'color', though, it would be that color.

Sounds reasonable to me.

**Comment by fantasai** [comment]
I've clarified this in the spec. Let me know if it's still awkward or if you have any suggestions for improvement. :) It's a weird section. https://drafts.csswg.org/css-pseudo-4/#highlight-painting

**Comment by fantasai** [comment]
Agenda+ to confirm with the WG that this is the behavior we want (I think it is) and to confirm that it's OK to use `currentColor` to represent this functionality.

**Comment by AmeliaBR** [comment]
To recap/clarify comments from the telcon:

I may have been misunderstanding the currently specified model for inheritance and `::selection` as defined in [Pseudo 4](https://drafts.csswg.org/css-pseudo-4/#highlight-cascade).

I understood the behavior as treating a selection as a sequence of separate pseudo-elements, one inside each element (or other pseudo) it overlaps. Each of those partial selections would then inherit from the base styles for that span of text. A selector like `p::selection` selects all the partial selection pseudo-elements inside the `p`, rather than selecting one pseudoelement that then has spans or other pseudos inside it. `em::selection` selects the partial selections inside the `em`, as does `p>em::selection` but the latter one wins out because it's a more specific selector.

So for real markup:

```html
<p>Unselected text selected text, <em>emphasized selected text, other emphasized text</em>.</p>
```

And a selection that covers "selected text, _emphasized selected text,_", you'd get an inheritance model of:

```html
<p>Unselected text <::s>selected text, </::s><em><::s>emphasized selected text,</::s> other emphasized text</em>.</p>
```

If that is the model used, then `color: currentColor` describes the behavior @fantasai wants (each span of text inside the selection taking the color it would be without the selection).
This is because each of those partial selections would inherit a different `color` value, and `color: currentColor` uses the inherited value, as defined in CSS Color [Level 3 (in the `currentColor` definition)](https://drafts.csswg.org/css-color-3/#currentcolor) or [Level 4 (in the "resolving color values" section)](https://drafts.csswg.org/css-color-4/#resolving-color-values).

But, now that I re-read the ["Cascading and Per-Element Highlight Styles"](https://drafts.csswg.org/css-pseudo-4/#highlight-cascade), I'm starting to doubt whether my mental model includes all the details in the spec:

> Each element draws its own active portions of the highlight overlays, which receives the styles specified by the corresponding highlight pseudo-element styles for which that element is the originating element. When multiple styles conflict, the winning style is determined by the cascade. When any supported property is not given a value by the cascade, it’s value is determined by inheritance from the corresponding highlight pseudo-element of its originating element’s parent element (regardless of whether that property is an inherited property).

Which is kind of hand-wavy language that doesn't match the normal inheritance rules, and never actually says that the highlight inherits from the local text span. So some additional hand-waving may still be required for `currentColor`.

**Comment by fantasai** [comment]
@AmeliaBR “and never actually says that the highlight inherits from the local text span” Right, it doesn't inherit from the local text span, at least not for color--it inherits from the parent ::selection. That's why I raised the issue of defining `currentColor` to refer to the color of the local text span.

**Comment by dbates-wk** [comment]
Re-defining currentColor in terms of the local text span would solve this bug as well as other color-like properties for pseudo-element. But this does not solve how to compute property caret and property text-shadow with respect to overlapping highlights. The spec. has existing text for how ::first-letter works with ::first-line in section 2:

> The ::first-letter pseudo-element is contained within any ::first-line pseudo-elements, and thus inherits from ::first-line.

Instead of re-defining currentColor can we solve this bug by adopting similar language for all the other highlights? Elaborating further can we describe the algorithm for computing the value of a highlight CSS property as cascade inheriting from the underlying highlight element up to the originating element. So, change the first paragraph of 3.4 to read:

[[
Each element draws its own active portions of the highlight overlays, which receives the styles specified by the corresponding highlight pseudo-element styles for which that element is the originating element. When multiple styles conflict, the winning style is determined by the cascade. When any supported property is not given a value by the cascade, it’s value is determined by inheritance from the next corresponding highlight pseudo-element layer of its originating element up to the originating element's parent element.
]]

**Comment by dbates-wk** [comment]
>dael> Daniel: One thing; did fantasai post the example? I can explain. That's broken. I have a patch for webkit. WE only do it for first-letter and first-line. I'm saying why can't we make selection have same model as first-line

The last sentence should read:

We only do it for first-letter and first-line. I'm saying why can't we make selection have same model as first-letter?
