### ISSUE TITLE
Add a new media query feature: client-width and client-height, which equal to (viewport size - scrollbar size)

### ISSUE THREAD

**Issue by Zhang-Junzhi** [w3c/csswg-drafts#2933]
Please consider adding two new media query features: `client-width` and `client-height`

which equal to the viewport size if there's no scrollbar;
or equal to (viewport size - scrollbar size) if there's a scrollbar.

`client-width`, `client-height` are very useful, they are even more useful than the existing `width`, `height` features.

Designers typically tend to care more about the available layout size than the size including a scrollbar

**Comment by jonjohnjohnson** [comment]
https://github.com/w3c/csswg-drafts/issues/1766

**Comment by Zhang-Junzhi** [comment]
I didn't think of why the two features weren't added in the first place, after a thought today, I kind of understand the reason behind it.

May it be a consideration of a paradox? The paradox is:
If we don't do layout, how can we know if it overflows beforehand? If we don't know if it overflows beforehand, how can we know the client width/height used for layout?

**Comment by tabatkins** [comment]
Yup, exactly. And further, you can adjust the `overflow` value based on a MQ, so you could get into styling loops with this where you apply `overflow:scroll` if the page is above a certain size, and switch to `overflow:hidden` when it's below that, and cycle back and forth as the scrollbars appear, shrink the page's size, then disappear.

**Comment by Zhang-Junzhi** [comment]
Thanks for the clarification. @tabatkins

**Comment by webdev3373117** [comment]
http://www.bisonapp.de?referral=SkQwqkyNm

**Comment by coreyworrell** [comment]
@tabatkins This probably isn't the right place for this, but I've never understood this attitude of not writing specs/features because of possibility of styling loops. If people want to write stupid code then let them write stupid code. JavaScript is open to endless loops, but specs/browsers don't prevent you from running them whether on accident or not.

**Comment by frivoal** [comment]
@coreyworrell loops in css and loops in js are different beasts. Js is an imperative language, so if you follow an bunch of steps, and then need to start again, and repeat forever, it may be stupid, but at least it is clear what that means. CSS is a declarative language, which describes the results, not the step to get there. The kind of loop we're talking here are circular logic and internal contradictions, not infinitely repeating steps. It's not stupid code as JS loops could be, it's meanignless / ambiguous / self-contradictory code, which browsers couldn't possibly implement, because nobody knows what it is supposed to mean.

**Comment by coreyworrell** [comment]
@frivoal Thanks for reply. I understand the difference and what loops we're talking about here. Circular logic and internal contradictions *created by the author*. If I have circular logic it is my own fault, not the browsers.

The rest of my reply I added to https://github.com/w3c/csswg-drafts/issues/1766#issuecomment-460470368 as it seems to fit there better.
