### ISSUE TITLE
Resolve values of attr() functions in a custom property

### ISSUE THREAD

**Issue by Zhang-Junzhi** [w3c/csswg-drafts#2946]
**Background**

Currently, an attribute value on the element can be obtained by the element itself or its pseudo-elements.

However, it's not possible, **for descendant elements**, to obtain an attribute value of their ancestor. Although an attribute selector can be applied such as `html[data-foo=val] .some-descendant`, that restricts ability of adjusting style of descendant elements accordingly to only situations where their ancestor's attribute value is **enumerable**; that is, if their ancestor's attribute value is **inumerable**, styling descendant elements accordingly seems hopeless in CSS. This proposal is to solve this issue.

------------------------------

**Proposal**

[css-variables](https://drafts.csswg.org/css-variables-1/) defines that only var() is resolved in a custom property declaration at computed-value time before the value is inherited, so I'd like to suggest we just do this for attr() as well. If both the two kinds of functions occur in one declaration, var() is resolved before attr(). Here are some examples:

```
/* Valid. Both var() and attr() are resolved at computed-value time, before the value is inherited. */
--foo: attr(data-foo);
--foo: foo attr(data-foo);
--foo: var(--bar) attr(data-foo);
--foo: attr(var(--bar)); /*Assuming --bar has a value of correct syntax for attr()*/

/*
 * Invalid. Both var() and attr() are resolved at computed-value time, before the value is inherited.
 * However, since var() is resolved before attr(), the literal "attr(data-foo)" is an invalid custom
 * property name, hence the declaration value is invalid.
 */
--foo: var(attr(data-foo));
```

------------------------------

I am looking forward to hearing from your opinions.

**Comment by tabatkins** [comment]
This can't be done for unregistered custom properties. It's just as valid to *want* the substituted value to be resolved on children, fetching *their* attribute value, not the ancestor's.  

For a registered custom property (see [Properties & Values API](https://drafts.css-houdini.org/css-properties-values-api/)), attr() will always be resolved immediately, because they process their values right away.

I do have future plans to allow people to *declare* that an unregistered custom property should be immediately evaluated according to some grammar, so you could cause this sort of thing to happen on command, but I'm not currently working on Variables 2, where it would go.

**Comment by tabatkins** [comment]
No, there's nothing bad perf-wise. It can't be done because it's a significant behavior change, and violates the consistent expectations that you can put anything into a custom property and it'll arrive, unchanged, at its destination when you finally substitute it into a real property.  The sole exception to that rule is `var()` functions, for necessary reasons, and I'm not willing to carve out more exceptions. Whatever benefit they may bring in one case is more than counter-balanced by the usefulness in *other* cases of them not being eagerly resolved, plus the loss of a consistent mental model for working with custom properties.

After all, why is `attr()` special? Why not any other function? `var()` has a reason to be special - building up composite variables from base variables is a core use-case - and even then, there's good use-cases for it to act the same as everything else and be "late-binding", substituted only at point-of-use further down the tree.

Like I said, I have a plan to address this in a **generic** fashion in the future. But I'm not going to change behavior that's been shipped for years at this point for a one-off special-case.
