### ISSUE TITLE
[css-contain-1] maybe 'contain-size' shouldn't apply to display:table-caption?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#2952]
The [definition of `contain:size`](https://drafts.csswg.org/css-contain/#containment-size) says that `contain:size` doesn't have an effect on `table` or on internal table elements.  This means it doesn't apply to `display:table-cell`... but it does apply to `display:table-caption`, which [isn't defined as an internal table element](https://drafts.csswg.org/css-display-3/#internal-table-element) (to my surprise, and in disagreement with Gecko's code).

I don't have a strong opinion here... and I just filed [Mozilla bug 1478850](https://bugzilla.mozilla.org/show_bug.cgi?id=1478550)... but it's possible the spec should change here?

**Comment by frivoal** [comment]
Leaving out table-caption was intentional, as it is a block box, and as far as I can tell does not have any special rule that would make applying `contain:size` unusually hard.

CSS2.1 claims:

> The caption boxes are block-level boxes that retain their own content, padding, margin, and border areas, and are rendered as normal block boxes inside the table wrapper box

Is it more special than the spec(s) lead me to believe? Setting an explicit width and height on a table caption, including setting them to smaller than the content and to 0, works just fine as it would on any block box, so I think we're good, but maybe I'm missing something.

**Comment by dbaron** [comment]
I think the issue is that in many cases the `table-caption`'s size interacts with the `table`'s size, much like the sizes of table parts interact with each other.  In other words, the width of the table definitely causes the caption's width to increase (Firefox and Chrome); vice-versa the caption's contents cause the table's width to increase in Chrome but not Firefox.  (Play with adding widths to [this testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Acaption%20%7B%20background%3A%20yellow%7D%0Atd%20%7B%20background%3A%20aqua%20%7D%0A%3C%2Fstyle%3E%0A%3Ctable%3E%0A%20%20%3Ccaption%3E%0A%20%20%20%20caption%0A%20%20%3C%2Fcaption%3E%0A%20%20%3Ctr%3E%3Ctd%3Ecell%3Ctd%3Ecell%0A%3C%2Ftable%3E).)

(I think this doesn't happen with `top-outside` and `bottom-outside` captions which represent the CSS 2.0 `top` and `bottom` rather than their redefinition in 2.1... and which we agreed to add for implementations (Gecko) that had actually implemented the 2.0 definitions... but I haven't tested.)

**Comment by dbaron** [comment]
Or, to put it another way, I don't think making this work for captions in particularly easier/harder than it is for table *cells*; it seems odd to allow one but not the other.

That said, it's also not clear to me why this isn't allowed for cells.

**Comment by frivoal** [comment]
> That said, it's also not clear to me why this isn't allowed for cells.

Because the effect would be something like setting the table cell's width and height to 0 (if they're not otherwise specified, or to what they're specified, if anything), then layout out the content of the cell without resizing it.

That cannot be done today, as table cells are always enlarged to fit their in flow content, which never overflows, and the `width`/`height` properties act more like `min-width`/`min-height`. Adding support for `contain:size` on table cells would therefore mean that we'd need to change how table layout works, which nobody expressed interest in doing.

Unlike table cells, on table captions you can set a width and height, can cause overflow if you set them too small (or to 0). So if `contain:size` is applied to a table caption with a definite size, you just do the layout with that size, and if it is applied to a table caption without a definite size, you do the layout with the captions's height being 0 and the caption's width being the fill-available width to the table size (where the table's size is not influenced by the intrinsic size of the captions's content, since it's contained away.)

**Comment by Loirooriol** [comment]
> it's also not clear to me why this isn't allowed for cells.

See #1791

**Comment by frivoal** [comment]
I would like to close with no change. Agenda+

**Comment by frivoal** [comment]
Marked as needs edits to add the note.
