### ISSUE TITLE
[css-grid-1] naming convention start-stop vs begin-end

### ISSUE THREAD

**Issue by bhamblok** [w3c/csswg-drafts#2957]
Why do we use the property name: "end" in combination with "start"?
- grid-row-start and grid-row-end
- grid-column-start and grid-column-end

IMHO the words "start" and "stop" or "begin" and "end" should be used together... like:
- grid-row-start and grid-row-stop
- grid-column-start and grid-column-stop
or
- grid-row-begin and grid-row-end
- grid-column-begin and grid-column-end

https://www.w3.org/TR/css-grid-1/#line-placement

**Comment by tabatkins** [comment]
At this point it's a historical accident that we're stuck with, but it does have *some* reasoning behind it.

Back in the day, when logical directions were first being developed (before I joined the WG, so >10 years ago), for some reason the block-axis directions were named "before" and "after", and the inline-axis directions were named "start" and "end". The start/end values were used in a few properties, like text-align. When developing Flexbox we wanted to finally settle on names, so we chose a single set ( qualifying them with "block-" or "inline-" when needed), and we preferred the start/end pair, both because they were already being used elsewhere, and they were a little easier to talk about.

Now, why did start/end get used, rather than start/stop or begin/end? One plausible reason is the start/end are both clearly nouns, which is what was desired. While "stop" *can* be used as a noun, it's more common as a verb; it's common to talk about "the start of X", but not "the end of X".  Similarly, "begin" is somewhat archaic as a noun; we'd have to use the conjugation "beginning", which is much longer and harder to type, which makes it pretty undesirable.

So start/end are both common as nouns, short, and easy to spell. And while they aren't each other's *canonical* pairing, they *are* paired together sometimes; it's not uncommon to hear things like "at the start of the race, X, but at the end of the race, Y". So they're not inappropriate to pair together, just slightly less common than other pairings.

We had a big discussion about all of this several years back, and argued over the whole thing before settling on the current terms. It's not possible to change at this point. ^_^
