### ISSUE TITLE
[cssom-view] Why is scroll-behavior on body element not propagated to the viewport in spec? Firefox ignores this.

### ISSUE THREAD

**Issue by jonjohnjohnson** [w3c/csswg-drafts#2990]
https://drafts.csswg.org/cssom-view-1/#propdef-scroll-behavior

I looked through issues here as well as the www-style mailing list to see any discussion around why this `scroll-behavior` has this caveat...

> The `scroll-behavior` property of the HTML body element is not propagated to the viewport.

I couldn't find anything. If the `body` element does not have a scrolling mechanism why can't `scroll-behavior` propagate to the viewport?

Currently there is an open [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=801857#c_ts1523316558) for chrome regarding the properties implementation, with an [example](https://jsfiddle.net/utasir/5odf114c/1/) that sets the property to `smooth` the `body` element and of course it doesn't scroll the viewport smoothly, per spec, but if you try that example in firefox, they in fact do allow propagation.

**Comment by upsuper** [comment]
This is probably a bug of Firefox.

I think we generally don't want to propagate more properties from body element, because that sometimes involves more complexity in implementation, especially given the fact that there can be multiple body element and only the value from the effective one should be propagated. Properties we propagate nowadays are mainly for compatibility I believe.

The implementation complexity may not be that bad for this property, but I think we want to be consistent that new things should stop doing such propagation.

Also, body element can indeed has its own scrolling apart from the viewport, such as in [this example](https://jsfiddle.net/mg41xcpz/1/).

**Comment by upsuper** [comment]
Filed [a Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1481103) for this.

**Comment by fred-wang** [comment]
Maybe related to #2977

**Comment by jonjohnjohnson** [comment]
If chrome closes https://bugs.chromium.org/p/chromium/issues/detail?id=801857#c_ts1523316558 out as wont fix, I s'pose this can be closed as well. It's understandable that for webcompat we have so many idiosyncrasies between viewport/html/body, but it's hard to keep track of which aspects get conflated and which do not.

@upsuper your point about people making the body a separate scroller from the viewport scroller lands well enough, sadly.
