### ISSUE TITLE
[css-ruby][css-text-decor-4] Add over-most-under-last value to ruby-position & text-emphasis-position for captioning

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2998]
https://lists.w3.org/Archives/Public/www-style/2014Dec/0211.html
https://lists.w3.org/Archives/Public/www-style/2015Jan/0126.html

TTML has requested a value to ruby-position (and text-emphasis-position) that would place the annotation above on all lines except the last one in the block. Names proposed include `outside` and `auto`.

**Comment by upsuper** [comment]
Neither `outside` nor `auto` feels like a good name for this in general... Maybe we can add a `ruby-position-last` for this usage just like `text-align-last`?

**Comment by fantasai** [comment]
@upsuper Seems like overkill. Not really something that needs to cascade independently afaik, doesn't have complex interactions with anything... Adding a value makes much more sense than adding a property.

**Comment by fantasai** [comment]
I think `outside` or `outer` is sufficiently clear, personally. The main concern I have is “What is the last line?”.

For justification we use the last line before any forced break. For text-indent we use the first line of a non-anonymous block. I have no idea what TTML’s markup model would require here...

**Comment by nigelmegitt** [comment]
> “What is the last line?”

@skynavga @cconcolato @palemieux ping! 

The TTML2 spec does answer the question:

[`<annotation-position>`](https://w3c.github.io/ttml2/index.html#style-value-annotation-position) says:

> **`outside`**
>
>    Equivalent to `before` for (1) the only line area of or (2) the first line area of the last block area generated by a `p` element which contains annotated text; otherwise, equivalent to `after`.

So I think the answer is it is based on the line areas generated by layout of the base text, with ruby and text emphasis then inserted in the appropriate position as a later step.

**Comment by astearns** [comment]
@nigelmegitt @palemieux would using ::first-line to set `before` work for this case?

**Comment by fantasai** [comment]
Hi @nigelmegitt and @palemieux, CSSWG wanted to know if it would be acceptable to just use
```
p { ruby-position: under; }
p::first-line { ruby-position: over; }
```
and if not, why not. :)

**Comment by r12a** [comment]
@nigelmegitt @palemieux @skynavga @cconcolato Can i just check that the wording in the TTML spec is correctly? 

> Equivalent to before for (1) the only line area of or (2) the first line area of the last block area generated by a p element which contains annotated text; otherwise, equivalent to after.

The case for a single line is fine. The case for two lines (the most likely scenario) is fine too.  I was under the (quite possibly mistaken) impression that in the case of 3+ horizontal lines, ruby would appear above the text except for the last line only, where the ruby would be shown below.

The Netflix requirements at https://medium.com/netflix-techblog/implementing-japanese-subtitles-on-netflix-c165fbe61989 say that there should never be more than two lines (because ruby should never appear between lines).

**Comment by skynavga** [comment]
@r12a for the 3+ case, we changed the spec to use after (below) for non-first lines; this was done to ensure we could map this to CSS using ::first-line;

also, regarding the NFLX requirements regarding no more than two lines, that is the NFLX style convention, but does not necessarily apply outside NFLX; one should read that document as one input providing guidance rather than universal requirements; in any case, we need the spec to handle the case where more than two lines are created during layout, which is something the author cannot predict due to variations in actual fonts on the client;

**Comment by r12a** [comment]
This is a notification test.  Please ignore.  I'll delete this in around 24 hours. (I'm testing out Dom's new merged repo notifications.  Should produce a single notification on the mailing list for this comment and another comment from the jlreq repo.)

**Comment by nigelmegitt** [comment]
@fantasai @astearns yes, it looks like using `::first-line` in the way suggested at https://github.com/w3c/csswg-drafts/issues/2998#issuecomment-413290078 and https://github.com/w3c/csswg-drafts/issues/2998#issuecomment-413319194 would work. 

As @skynavga pointed out, the TTML2 spec was changed after this issue was raised in a way that enabled exactly this hypothetical solution. I've confirmed this offline with @palemieux.

The change needed is to allow `ruby-position` to apply to `::first-line`. 

[Ruby Layout Module Level 1](https://drafts.csswg.org/css-ruby/#placement) explicitly excludes this currently, and the [Pseudo-Elements Module Level 4 `::first-line` specification](https://drafts.csswg.org/css-pseudo-4/#first-line-pseudo) is consistent with that because it does not list any ruby properties.

By the way, this is analogous to [text-emphasis-position](https://www.w3.org/TR/css-text-decor-3/#text-emphasis-position-property) which _does_ apply to `::first-line`. It seems obvious to me that the same mechanism should be used for positioning ruby as for positioning text emphasis.

**Comment by fantasai** [comment]
OK, I've made the edits for this. There's a tangential follow-up for the CSSWG in https://github.com/w3c/csswg-drafts/issues/4642 but I think this issue itself is closed.
