### ISSUE TITLE
[css-color] Working Color Space

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#300]
https://drafts.csswg.org/css-color/#working-color-space

> Resolved at San Francisco to add a working-color-space at-rule, which affects the entire document. Compositing, interpolation, blending use this. Initial value is sRGB. linear-sRGB, p3, rec2020, and lab were also discussed as values. Chris to read the canvas spec to see what it does there, particularly for the "optimal" value.

**Comment by karip** [comment]
Should the initial value be "auto"? Safari 10 seems to implement something like that. It means that on sRGB monitors, the working colorspace is sRGB. On P3 monitors, the working colorspace is P3.

**Comment by svgeesus** [comment]
> Edit: actually, I'm not sure what Safari does. But, it is able to show P3 images correctly on P3 monitors without a working colorspace at-rule.

That doesn't require a working colorspace. Things like interpolation and compositing of colors from different spaces are where this is needed.

The initial value, for Web-compat reasons, will be sRGB (because that is what  is currently used).

**Comment by frivoal** [comment]
>That doesn't require a working colorspace

Is that because when no interpolation / composition is needed, we can just do:
input space ---- (via CIE-lab)----> output space (which is a no-op when input=output)
instead of
input space ---- (via CIE-lab)----> working-space ----(via CIE-lab)----> output space
?

Presuming that's the case, it means that converting from the input to the output space is something that can happen late in the pipeline, well after computed or even used values. In which case the resolved value (result of getComputedStyle()) would presumably be the same as the specified value. This also seems fine when it comes to compositing.

However, when it comes to interpolation (gradients, animations...), this looks like something that you should be able to resolve at computed value time, as it does not depend on layout, much less painting or compositing. And that means it should affect the computed value and the result of getComputedStyle() somehow.

So how do we spec that? do we say that the computed and used values are the specified values, even in the cases where they will be used as inputs for an interpolation, but that when a property is set to a color that is the result of an interpolation (e.g. because of an animation / transition), then it is set to the right color in the working color space at computed value time?

----

Note: this relates to #871, #741, #480, #867, #883 (at least)

**Comment by george-steel** [comment]
Has this gone anywhere? I made a [demo](https://codepen.io/george-steel/pen/VopZyj) of color blending issues to demonstrate the need for this as well as the filter version of this property. Forefox renders to-spec while Chrome uses sRGB even for SVG filters (which should use RGB by default).

**Comment by george-steel** [comment]
The choice of which representation of linear space to use should probably be left unspecified (probably to be implemented as whatever's native on the platform in question) as all the operations currently used on colors are isomorphic over conversion between different linear spaces. The only caveat should be that tests should allow for enough imprecision for platforms that use float16.

**Comment by svgeesus** [comment]
To catch up on this long-standing issue:

There cannot be a per-document or even per-element `working colorspace` because different options require calculations to be done in different colorspaces:

- [color interpolation is now defined in CSS Color 5](https://drafts.csswg.org/css-color-5/#interpolation) and uses Lab by default, but individual properties or functions can override this
- [`color-mix()`](https://drafts.csswg.org/css-color-5/#color-mix) overrides the interpolation default to LCH, but has syntax to specify a different colorspace
- [compositing](https://drafts.fxtf.org/compositing-1/) currently uses gamma-encodes sRGB (which is terrible, but Web compatible) and will need to be upgraded to at minimum allow a linear-light option. CIE XYZ is the obvious choice here. Implementations can calculate in another linear-light space, like linear-light display-p3, and get the same result modulo gamut clipping. See https://github.com/w3c/csswg-drafts/issues/5669
- [gradients currently use alpha-premultiplied gamma-encoded sRGB](https://www.w3.org/TR/css-images-3/#coloring-gradient-line) for Web compat, and will need to be upgraded to allow a perceptually uniform (still alpha premultiplied) option. Lab and LCH are the obvious candidates there. CSS Color 5 defines [alpha-premultiplication for all color spaces](https://drafts.csswg.org/css-color-5/#interpolation-alpha)

Also the need for a working colorspace for serialization was removed [serialized value is in the colorspace it was declared](https://drafts.csswg.org/css-color-4/Overview.html#serializing-color-values).

**Comment by svgeesus** [comment]
In consequence, related issues are being or have been raised on other specs. Color 4 says how to specify, resolve, and serialize the colors. Combining them is handled on the appropriate spec as mentioned above, and does not affect Color 4. Thus, this issue can finally be closed.
