### ISSUE TITLE
[css-syntax] preprocessing says to remove CR and FF, but they are then mentioned in a definition

### ISSUE THREAD

**Issue by Netmosfera** [w3c/csswg-drafts#3004]
Section 3.3 says to remove carriage return and form feed during preprocessing,
but then they are included in https://drafts.csswg.org/css-syntax-3/#newline-diagram
Is this intentional and relevant somehow?

Thanks.

**Comment by tabatkins** [comment]
Yes, that's intentional; the diagrams are helpful informative constructions, not normative definitions.  The actual [definition](https://drafts.csswg.org/css-syntax-3/#newline) of a newline properly states that it's just \n, with a note about the other characters being removed/transformed during parsing, but forcing people to remember that a previous chapter has this sort of stream manipulation when reading a railroad diagram is too much in my opinion.
