### ISSUE TITLE
[css-sizing] cyclic percentage concept should not exist

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#3010]
The spec defines a [cyclic percentage](https://drafts.csswg.org/css-sizing-3/#cyclic-percentage) concept, I think from the resolution to #765 (which doesn't link to the commits that fixed it, though, and I didn't dig further to double-check this).

I don't think this concept should exist.  I think the rules that depend on the cyclic percentage concept should instead apply to all percentages used in intrinsic size calculation, not just those that are cyclic.  (Otherwise it's breaking the principle that the intrinsic size is *intrinsic*.)

It's also not immediately obvious to me how to test the difference.  (But if there is no difference, I'd strongly prefer the definition that doesn't make intrinsic widths depend on properties on ancestor elements.)

**Comment by Zhang-Junzhi** [comment]
If I understand the spec correctly, I think the spec already has applied the "intrinsication" to all the percentage-sized values of all descendant boxes in the "very first" step of an intrinsic size calculation, no matter how deep a descendant box is, that is, it's not possible to be non-cyclic percentage for an intrinsic size, because _all_ of descendant percentage-sized values are turned to cyclic for an intrinsic size calculation per spec, no matter how deep a descendant box is.

I didn't immediately realise that to begin with, because it's not obviously stated in the spec.

I happened to be aggressively learning and reading through css-size-3 these two days, and once had a hard time conclusing a simplified evocative "outline" in my brain, as to in which order various complicated situations that have cylic dependency would be resolved, and how would they work. After trying to figure out the haze for some time, I was finally enlightened and inferred that when caculating an intrinsic size calculation for a box, _all_ of its descendant boxes' percentage-sized values are converted to either auto or 0, no matter how deep the descendant box is. I think I have a clear understanding of the overall machenism now, but it's not easy for me to evocatively express it to others with just a few words.

Since the "intrinsicate" is applied to all the percentage-sized values of all descendant boxes in the "very first" step of an intrinsic size calculation. IMHO, the spec might have more explicit statements instead of the concept of cyclic percentage, so people don't have to infer to get such a conclusion.

**Comment by fantasai** [comment]
We can't unilaterally apply it to all percentages because, for example, a percentage that resolves against a definite size in one axis needs to be taken into account for intrinsic sizes in the other axis when an aspect ratio or orthogonal flows are involved.

For example, the intrinsic widths of an image with a percentage height that is resolved against a definite containing block height: http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22height%3A%2060px%3B%20border%3A%20solid%20orange%3B%22%3E%0A%20%20%3Cimg%20src%3D%22https%3A%2F%2Fplacehold.it%2F100x100%22%20style%3D%22max-height%3A%20100%25%3B%20display%3A%20block%3B%22%3E%0A%3C%2Fdiv%3E

While we could maybe have a more general definition of affected percentages that includes percentages which are not cyclic but which don't have an effect on intrinsic sizes anyway, I don't think that would be an easier definition to have here. By definition, a percentage which has an impact on the intrinsic size is cyclic; and for one which doesn't, it doesn't matter how we categorize it during intrinsic size computation. (The UA can of course categorize percentages however it's convenient if there's no effect on its output.)

Proposing to close WONTFIX, let us know if this is unsatisfactory.

**Comment by dbaron** [comment]
So some of my concerns, from a discussion with @fantasai and @tabatkins include:

* Schrödinger's intrinsic width:  it's one thing when you use it, and another when you don't.  It seems better to define it just as the thing that it is when you use it.  For example, consider the middle `div` in
```html
<div style="float: left"> <!-- consider this with width:auto and with width:500px -->
  <div> <!-- consider what the intrinsic width of this div is -->
    <div style="width: 25%"></div>
  </div>
</div>
```
it has a different intrinsic width depending on whether the outermost `div` looks at its intrinsic width.

* future-compatibility for things like `min(500px, min-intrinsic)` -- is such a thing cyclic some of the time or all the time

I'd rather have specific definitions to handle the case of things with an intrinsic ratio that do use percentages that are definite with respect to a size in the other dimension.

**Comment by dbaron** [comment]
Right now it seems like the spec is relying on implementors to be able to infer all of that.  If the idea is that you do a particular thing in a particular axis, I'd much rather say that, rather than having the spec specify something that you think is simple today but might actually be really complicated.

Could you replace "which itself depends on that percentage" with "in the same axis as the percentage"?  (If not... what cases are different?)

**Comment by fantasai** [comment]
> If not... what cases are different?

Margins and padding. Their percentages might resolve against the containing block in the opposite axis, and are therefore not cyclic and should resolve according to their usual rules, not these special rules.

**Comment by tabatkins** [comment]
Okay, folding in the simplification I talked about in my previous comment, along with the clarification to handle @fantasai's margin/padding point:

> Sometimes the size of a percentage-sized box’s <a>containing block</a>
> depends on the [=intrinsic size contribution=] of the box itself,
> creating a cyclic dependency.
> When calculating the <a>intrinsic size contribution</a> of such a box
> (including any calculations for a content-based <a>automatic minimum size</a>),
> a percentage value that resolves against a size
> in the same axis as the [=intrinsic size contribution=]
> is resolved specially:

We won't commit this to the spec quite yet, but we think it'll do what we need while being much more straightforward to interpret and adjudicate, like @dbaron wants.
