### ISSUE TITLE
[css-grid] Static position should use content-box, not padding-box

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3020]
Tab and I just noticed that while every other layout mode uses the content box of the static position containing block to set the static position, grid uses the padding box.

We suspect this was an error and we should fix this. Anyone have a different opinion?

Spec: https://drafts.csswg.org/css-grid-1/#static-position
Testcase: http://software.hixie.ch/utilities/js/live-dom-viewer/saved/6105
```html
<!DOCTYPE html>
<style>
.abspos { position: absolute; border: 4px solid rgba(0,0,0,.4) }
.container { float: left; border: solid; padding: 2em; width: 10em; height: 6em; background: yellow content-box }
</style>
<div class=container style="display: grid;"><span class=abspos></span>grid</div>
<div class=container style="display: flex;"><span class=abspos></span>flex</div>
<div class=container style="display: block;"><span class=abspos></span>block</div>
```

**Comment by mrego** [comment]
Regarding tests there is http://w3c-test.org/css/css-grid/abspos/absolute-positioning-grid-container-parent-001.html

**Comment by MatsPalmgren** [comment]
@mrego FYI, there's also a bunch of tests under css/vendor-imports/mozilla/mozilla-central-reftests/align3/  [they are all updated now](https://github.com/web-platform-tests/wpt/pull/13022).

**Comment by mrego** [comment]
@MatsPalmgren thanks for the info, probably we should import those in Chromium/WebKit too.

**Comment by MatsPalmgren** [comment]
>  I see tests for self and content alignment in the case of flexboxes, but only for self alignment in the case of grid layout. Why?

I don't know, but many of our Grid tests are in a separate [folder](https://searchfox.org/mozilla-central/source/layout/reftests/css-grid/). There should be some content-alignment tests there. (We want to convert these to WPT tests and upstream them eventually. Just lack of resources that it hasn't happened yet...)

> For example, I'm wondering if for grid layout the following two examples. Should they have the same output (the abspos element should be horizontally and vertically centered)?

Note that the grid container is **not** an abs.pos. containing block in your examples, so [§9.2](https://drafts.csswg.org/css-grid/#static-position) applies. In particular:
> The static position [CSS21] of an absolutely-positioned child of a grid container is determined as if it were the sole grid item in a grid area whose edges coincide with the content edges of the grid container.

In your first example (self-alignment), css-align [says](https://drafts.csswg.org/css-align-3/#justify-abspos) "_use the box’s [static position rectangle](https://drafts.csswg.org/css-align-3/#static-position-rectangle)_", i.e. "_By default, the static position rectangle of the child of a grid container corresponds to the content edges of the grid container._", so that's what leads to the first abs.pos. being centered in the content-box.

In the second case (content-alignment), it's the grid of the grid-container that is aligned, but since the abs.pos. box isn't grid-aligned at all it's not affected by that.  If you add `position:relative` to the container the child is still not affected by content-alignment since it's not anchored to any line in the grid (given that all its lines are `auto`). If you additionally add `grid-area:1/1/1/1` to the abs.pos. item to anchor it with the top-left of the grid it's still not centered because a grid with zero tracks is [special](https://drafts.csswg.org/css-grid/#grid-align): "_If there are no grid tracks (the explicit grid is empty, and no tracks were created in the implicit grid), the sole grid line in each axis is aligned with the start edge of the grid container._". This makes sense because the [alignment subjects](https://drafts.csswg.org/css-align-3/#distribution-grid)  are the _tracks_ (not lines) and with no tracks content-distribution doesn't apply. If you add a track, e.g. `grid:0/0`, then line 1 should be centered by content-alignment and then you can use self-alignment to align the item relative to that.

So this example should display the same as your first example:
```html
<div style="display: grid; width: 200px; height: 100px; place-content: center; place-items: center; border: solid thick; grid:0/0; position:relative">
  <div style="grid-area:1/1/1/1; position: absolute; background: magenta;">abspos</div>
</div>
```
