### ISSUE TITLE
Request for a "checked-within" pseudo class

### ISSUE THREAD

**Issue by omzy** [w3c/csswg-drafts#3027]
Similar to the `focus-within` (https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within) pseudo class, can we have a `checked-within` pseudo class?

Basically would allow a parent element of a checked checkbox or radio to be targeted. Sample usage:

HTML:

```
<div class="option">
    <div class="title">
        <input type="radio" id="basic" name="package" value="basic">
        <label for="basic">Basic</label>
    <div>

    <div class="content">
        <!-- some content -->
    </div>
</div>
```

CSS:

```
.option {
    background-color: white;
}

.option:checked-within {
    background-color: green;
}
```

Currently we have to use JS to detect a change event on the radio button in order to apply a class on a parent element (or conditionally apply a class on the server side for rendered pages).

**Comment by Zhang-Junzhi** [comment]
Love the idea!

**Comment by dtruffaut** [comment]
I support this feature !

**Comment by danielwaltz** [comment]
Would love to see this too, would enable a lot of interesting new capabilities!

**Comment by awesomesk1ll** [comment]
Support

**Comment by seeratawan01** [comment]
need this

**Comment by kyosheek** [comment]
approve

**Comment by frivoal** [comment]
On the one hand, yes. On the other hand, if we're going to need a bunch of `:foo-within`, making we should think of a generic mechanism, rather than adding them one by one?

**Comment by coleholyoake** [comment]
Support

**Comment by jimmyfrasche** [comment]
In a browser that has both `:is` and `:has` wouldn't `:foo-within` be `:is(:foo, :has(:foo))`, for any `:foo`? If I'm not wrong there, it sounds like it would be pretty easy to come up with sugar for that and it would be worth it if `:foo` is some large, ungainly selector

**Comment by frivoal** [comment]
Right. The `:*-within` family of pseudos mainly makes sense if `:has()` isn't expected to be implementable, otherwise it's syntactic sugar (unless the narrower version enables performance optimizations that the general mechanism doesn't). For the longest time, the assumption was indeed that `:has()` was not implementable in a performant way. It seems that [Safari is redefining expectations here](https://twitter.com/jensimmons/status/1473051429115940868), and that we may get `:has()` after all.

**Comment by meyerweb** [comment]
I’ve been thinking about this the past day or so due to a question someone asked me on the Twitters, and as far as I can tell, `:has()` does indeed obviate the need for “within” selectors.  The following would seem to have equivalent specificity:

```css
nav:focus-within {…}
nav:is(:focus, :has(:focus)) {…}
```

Plus one could use `:where()` to intentionally lower the specificity, if desired.

Admittedly, the `:is()` construct is a little more baroque than a “within” equivalent, but it might be worth waiting to see how often authors use those sort of patterns before deciding what needs a “within” shortcut.

(Alternatively, we could decide to “within” all the pseudo-classes that might need it by defining them as aliases for their `:is()` equivalents.  As a CSS author _and_ an author of CSS explanatory materials, I’d be fine with that.)

**Comment by TanawatJukmongkol** [comment]
Yep! I need this for my project. It's impossible to select the parent element whilst a child is in focus. I tried `.svg.pin:is(.pin-button:checked)` and it doesn't work like it supposed to.

**Comment by meyerweb** [comment]
> Edit: Oh, nvm. I've found a cleaner solution.

Wait, come back — what was the solution? WHAT DID YOU SEE, DENVERCODER9?!?

(https://xkcd.com/979/ for those who didn’t catch the reference.)

**Comment by omzy** [comment]
Hello :)

It's been 5 years since I logged this issue, are we likely to see this feature implemented anytime soon, if at all?

**Comment by tabatkins** [comment]
Ah, we should go ahead and close this. The solution is now `:has(:checked)`.

**Comment by omzy** [comment]
> Ah, we should go ahead and close this. The solution is now `:has(:checked)`.

Thanks. I just tested that and it works! In Chrome anyway - it doesn't seem to be supported yet in Firefox. I tried looking for information on browser support for this support but have been unable to find anything. Do you happen to have this information?

**Comment by omzy** [comment]
Ah it looks like Firefox doesn't support `:has()` at all. There's an open bug from 16 years ago 😂

https://bugzilla.mozilla.org/show_bug.cgi?id=418039
