### ISSUE TITLE
[css-grid] Inconsitence of the "intrinsically-sized track" concept when using flexible tracks

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#3046]
Lets consider the following example:

```
<div style="display: grid; font-family: Ahem; border: solid; width: 200px; grid: minmax(0px, 1fr) / 100px 100px; align-items: baseline">
  <div style="grid-column: 1; background: blue; font-size: 50px;  padding-bottom: 25px">É</div>
  <div style="grid-column: 2; background: green; grid-row: 1; writing-mode: vertical-lr">ÉÉ É ÉÉ ÉÉÉÉ É</div>
</div>

```

My doubt is whether or not the orthogonal item in column 2 can participate in baseline alignment along the column-axis, honoring the align-items property. 

Assuming that a flexible track on a indefinite sized container should be considered as a content-sized track (this should be clarified in issues #3042 and #3044),  in this case we have a situation where we can't determine this condition consistently during the different steps of the track sizing algorithm. 

https://drafts.csswg.org/css-grid/#algo-overview
> 2. Next, the track sizing algorithm resolves the sizes of the grid rows, using the grid column sizes calculated in the previous step and the effective column gap sizes after applying justify-content. 

During step 2 we have to use the baseline shims so that they contribute to the size of the track; hence, we have to compute the baseline shims just before computing the tracks intrinsic sizes.

https://drafts.csswg.org/css-grid/#algo-baseline-shims
> Shim baseline-aligned items so their intrinsic size contributions reflect their baseline alignment. For the items in each baseline-sharing group, add a “shim” (effectively, additional margin) on the start/end side (for first/last-baseline alignment) of each item so that, when start/end-aligned together their baselines align as specified. 

It's important to notice that we implement this shim computation as part of the track sizing algorithm, so that we can run it again in step 3, if necessary (eg. orthogonal items). This is an implementation decision, since the spec doesn't specify when the baseline shims must be computed; it just state when they should be applied. 

So, at this point, since we are under indefinite height, we should consider the flexible track as content-sized; hence, since the orthogonal item has 'auto' inline-size, there is a cyclic dependency that implies the item should not participate in baseline alignment along the column-axis. 

https://drafts.csswg.org/css-grid/#column-align
> If baseline alignment is specified on a grid item whose size in that axis depends on the size of an intrinsically-sized track (whose size is therefore dependent on both the item’s size and baseline alignment, creating a cyclic dependency), that item does not participate in baseline alignment, and instead uses its fallback alignment.

Then, we enter it step 3 of the grid sizing algorithm:

> 3. Then, if the min-content contribution of any grid item has changed based on the row sizes and alignment calculated in step 2, re-resolve the sizes of the grid columns with the new min-content and max-content contributions (once only), using the grid row sizes calculated in the previous step along with the effective row gap sizes calculated by applying align-content. 

We are indeed in this scenario, so we have to repeat steps 1 and 2. This will include (that's what we should clarify in this issue) the computation of the baseline shims. Although these shims shouldn't change because of the different sizes resolved in this step, it's possible that items that didn't participate in baseline before are now allowed to do so. 

The key is that for this step 3, the height is not indefinite anymore, so theoretically, we shouldn't consider the flexible tracks as content sized. The result is that the orthogonal item participates now in the baseline alignment.

is this the behavior we want ? The following pictures shows how the example above would be rendered:

![baseline-and-flex-tracks](https://user-images.githubusercontent.com/2230241/44531715-bf343900-a6f1-11e8-8eb9-e6cf57e9514f.png)

**Comment by fantasai** [comment]
I think the point of confusion is that you're evaluating whether the item is in a cyclic layout situation within the scope of a particular step in the algorithm. Within such a narrow scope, you get different answers depending on which step you're in. But the decision of whether an item can be baseline-aligned or not due to cyclic dependencies is at the top level. If any part of the layout creates this cycle, the cycle exists, and you must use fallback alignment--and that fallback alignment applies as if it were originally specified, not only in certain steps.

**Comment by tabatkins** [comment]
This implication, however (that the cyclic-baseline check is performed once at the beginning of track layout, and persists thru the later steps where the track may be treated as fixed) is not clear from the language, so we need to fix it. ^_^

**Comment by tabatkins** [comment]
(@fantasai and I are arguing with each other over these comments even tho we're sitting next to each other irl.)

**Comment by fantasai** [comment]
It's clear because it's unconditional and unscoped. It's defined at the same level as "if you're in a vertical writing mode, an 'auto' dominant baseline is treated as 'center' and in a horizontal writing mode it is treated as 'alphabetic'. We could make it *clearer* by being extra explicit about this, but the only condition is “there is a cycle during layout” and the command is ”treat baseline as its fallback”, with no conditions or scoping or timing constraints.

**Comment by tabatkins** [comment]
By definition it's not clear, since Javi didn't understand it, and I would have interpreted it differently five minutes ago too. ^_^

**Comment by tabatkins** [comment]
To be a bit more explicit:

Figuring out the baseline-alignment shims is a part of the track sizing algorithm, and this is run for one set of tracks at a time, either the rows or the columns.

In this case, step 2 figures out row heights, and assigns block-axis margins to baseline-align between rows. (Which, due to the vertical item not participating, means that everyone gets 0-sized shims; they're not baseline-aligning.)

Then step 3 happens - we treat the row as fixed-size, *but we're working on the columns*. So the baseline-shim determination is *for the columns* - inline-axis margins to align things across a column.  The fact that the row is fixed has no relevance here; the cyclic check we're doing is for widths (and in this case, the column widths are both fixed at 100px, so everything's cool).

Then step 4 happens - the columns are fixed, rows are un-fixed (because we're calculating them again), and so the cyclic-check is made for the rows, and once again, the vertical item still depends on an intrinsically-sized track, so it still can't baseline-align.

**Comment by tabatkins** [comment]
> It's important to notice that we implement this shim computation as part of the track sizing algorithm, so that we can run it again in step 3, if necessary (eg. orthogonal items). This is an implementation decision, since the spec doesn't specify when the baseline shims must be computed; it just state when they should be applied.

It does say when to calculate these - it's done in step 11.5.1. That's part of the Track Sizing Algorithm, tho (and does get re-run in step 3/4), so it looks like it's consistent with what you're already doing. ^_^

**Comment by javifernandez** [comment]
> It does say when to calculate these - it's done in step 11.5.1. That's part of the Track Sizing Algorithm, tho (and does get re-run in step 3/4), so it looks like it's consistent with what you're already doing. ^_^

I guess with 11.5.1 you meant the Step 1 in the 11.5 section: https://drafts.csswg.org/css-grid/#algo-baseline-shims 

Then, yes, we assume that but I meant that it was not explicitly stated. I didn't want to imply that the text would need edits to clarify it, though, just that we assumed it was necessary to do it in that precise step.

Then, we are on the same page regarding this specific sub-topic of the issue, about when to compute the baseline shims. I'm happy because it's a very important point of this issue.

**Comment by mrego** [comment]
> This is the main doubt that I, and a few other devs at Igalia (we used several meetings to discuss about this and I admit we still haven't reach an agreement). Is the available space definite during the step 4 ? Can/Should assume that the rows' size determined in Step 2 can be used to set the grid container's height, hence it can/should we use it as definite available space for computing rows' size in Step 4 ?

Regarding this we're currently assuming in Chromium and WebKit that grid size (width and height) is definite when we repeat the track sizing algorithm (steps 3 and 4).
And @MatsPalmgren requested to add this in [a comment on a different issue](https://github.com/w3c/csswg-drafts/issues/1921#issuecomment-399170288):
> And that the grid container's block-axis size is definite and final after the first pass (so that it works similar to the inline-axis).


About the particular problem of this issue, I agree with @fantasai that we should determine this at the beginning and then don't change the status during the whole track sizing algorithm.

**Comment by tabatkins** [comment]
> Is the available space definite during the step 4 ? Can/Should assume that the rows' size determined in Step 2 can be used to set the grid container's height, hence it can/should we use it as definite available space for computing rows' size in Step 4 ?

No. Step 4 tells you what information to use - it mentions using the column widths you calculated in step 3, but makes no mention of the previous attempt at row heights from step 2. So you ignore everything that happened in step 2; it has no relevance during step 4.

> About the particular problem of this issue, I agree with @fantasai that we should determine this at the beginning and then don't change the status during the whole track sizing algorithm.

Are there any particular edits you need for this to be clearer?

**Comment by mrego** [comment]
With the edits from #3042 it seems we won't need changes:
> For this purpose, <flex> track sizes count as “intrinsically-sized” when the grid container has an indefinite size in the relevant axis.

We guess that *has an indefinite size* is true on the first pass and also on the second pass.

Note that in order to resolve percentages rows on a grid container with indefinite size, we are setting the intrinsic height after the first pass and then use that size to resolve the percentages in the second pass. For that reason @MatsPalmgren asked for [some extra changes on the spec in this comment](https://github.com/w3c/csswg-drafts/issues/1921#issuecomment-399170288):
> And that the grid container's block-axis size is definite and final after the first pass (so that it works similar to the inline-axis).

If we do that maybe we'd need some extra clarification on the "intrinsically-sized" and flex tracks sentence. As otherwise both texts would be somehow contradictory: in one place we would say that after the first pass the height is definite, then with the current sentence the flex track would be "intrinsically-sized" on the first pass but not on the second pass.

**Comment by javifernandez** [comment]
I think we can close this issue, unless @rego or anybody else has anything to add.
