### ISSUE TITLE
[selectors] Specify the "all ::-webkit-* pseudos are valid" behavior

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3051]
For a while, WebKit-derived browsers have had a quirk where *all* `::-webkit-*` pseudo-elements are considered valid at parse time (and thus won't invalidate a selector list if they appear in only one selector).  This has apparently begun to create compat problems for Firefox (see <https://github.com/whatwg/compat/issues/103>), so they're adding that behavior themselves.  This behavior is being tracked in WPT tests in <https://github.com/web-platform-tests/wpt/pull/12673>.

We should go ahead and inline that into the Selectors spec, probably in a compatibility appendix.

**Comment by frivoal** [comment]
It is regrettable that we need this, but Firefox implementing it shows that we do. So yes, this should be in the spec, thanks for writing it.

**Comment by tabatkins** [comment]
Ah, that wasn't clear from the whatwg/compat issue. I'll fix.

**Comment by tabatkins** [comment]
Fixed in 456e9026f

**Comment by upsuper** [comment]
Looks good now, thanks.

**Comment by myakura** [comment]
Is it hard to limit the list to the currently exposed ::-webkit- pseudo-elements?

**Comment by tabatkins** [comment]
That's the point of the compat bug - WK-derived browsers accept *all* pseudo-elements with a -webkit- prefix as valid at parse time, not just ones that they actually know about.

If we can change Blink/WebKit to stop recognizing those as valid, great. But I doubt that's possible, if the quirk has gotten bad enough that Firefox feels the need to implement it.

**Comment by myakura** [comment]
> If we can change Blink/WebKit to stop recognizing those as valid, great.

yeah that was my intent. but after reading https://github.com/w3c/csswg-drafts/issues/2156#issuecomment-382730864 now I understand it seems impossible (still doubt how and why ~40% of page loads has unknown ::-webkit-whatever though...)

**Comment by upsuper** [comment]
There are two reasons for Firefox to implement it:
1. Apparently there are websites broken on Firefox due to this.
2. There are other webkit-specific things we may want to make shim to "fix", which would require such rules at least be parsed in stylesheets.

So this is a matter of webcompat directly and indirectly.

**Comment by jonjohnjohnson** [comment]
Sadly, folks use this hack to target those browsers in order to get around other compat issues, like differences in implementation of the `vh` unit or `position:sticky` over the years. Even if an `@support` rule passes for certain features, this is used to weed out, by hand, the support they want.  The past prefix way of things truly led to a muddy present, but rocks and hard places make it so these things need to be dealt with.

**Comment by dbaron** [comment]
Using hacks that assume support for X is equivalent to support for Y is a bad idea if those hacks are targeting *current* browsers.  Such hacks are safe only if the features are implemented in all current browsers and the equivalence holds in the old versions where they're not implemented.

**Comment by MrSorcus** [comment]
Web is so fat and ugly and you are continue supported all of this shit with non-standard prefixes? So stupid.

**Comment by jonjohnjohnson** [comment]
Years ago, allowing "MQ-style invalidation" for selector lists was seen as unsafe, most likely breaking old sites and when it would "activate unexpected declaration blocks". Though I trust @dbaron's opinion on the real issues `-webkit-` prefixes have caused in gecko, are we sure making the spec tell all vendors to accept selector lists with both unsupported AND then even the supported `-webkit-` prefixed pseudos is the way forward? This will surely cause current stylesheets to behave in ways that their authors won't have realized or intended when previously seeing that those selectors "isolate" styles to webkit?

> @fantasai: But this seems to be quite web-incompatible, because people depend on this behavior.
> @sylvaing: How do people depend on this?
> @glazou: Right now there are style rules which are fully invalid because of one selector, and authors never noticed the wasted rule. If you change, it'll start applying and change the page.
> @TabAtkins: And there is some history of people using prefixed selectors in the selector list as a browser hack, and this would change the behavior they're depending on.

https://www.w3.org/Style/CSS/Tracker/issues/223
http://lists.w3.org/Archives/Public/www-style/2013Apr/0246.html

**Comment by SelenIT** [comment]
In #3082, we have a proposal to use the reverse strategy regarding pseudo-elements: treat all unknown pseudo-elements (not just `-webkit`-prefixed) as potentially valid, _except_ pseudo-elements with other prefixes (most likely used for selector hacks). To me, this seems to be a good idea: it shouldn't break the compatibility (most existing hacks would be covered by the exception), and it would make adopting new features easier as authors wouldn't need to duplicate the entire style rule for the new selector.

Are there any pseudo-elements other than `-moz-`, `-ms-`, and probably `-o`-prefixed ones that were often used as a hack or otherwise were relied on _not_ being applied?
