### ISSUE TITLE
add top-level shared resources from WPT to test.csswg.org

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#3076]
See https://github.com/web-platform-tests/wpt/pull/9940#issuecomment-372360030.

**Comment by gsnedders** [comment]
And because I didn't actually mean to hit cmd+return:

> I think we should probably just make it possible to use all the top-level shared resource directories (`common`, `fonts`, `images`, `media`, `resources`); I think all of these have existed since WPT has, so there's not much risk of new ones getting added.

@plinss said:

> If it's just that set of 5 then fine, I can add the others as aliases to the csswg test server. All I had in mind was something like if new shared-resource directories get added that happens under `/common` (or let's create `/shared` and put everything, or all new things under that). That way new ones can be added without having to coordinate changes or worry about breakage.

(filing this issue so I have something better to link to than I discussion on a closed PR)

**Comment by plinss** [comment]
Done

**Comment by plinss** [comment]
No, because the directory structure gets flattened during the build process. The build does adjust the paths of references, but that's about it. The point of adding these aliases was to allow the use of absolute urls. I thought there was a lightweight python server that could be run locally out of wpt?
