### ISSUE TITLE
[css-ui] Consider adding `always-none` or some such to `appearance`, sometimes, style that's fully controllable for controls is really very demanded.

### ISSUE THREAD

**Issue by Zhang-Junzhi** [w3c/csswg-drafts#3087]
Please consider adding `always-none` or some such to `appearance`, sometimes, fully controllable for controls is really very demanded.

**Especially when in the vertical writing-mode**, UI interoperablities and apperances consistency for controls alsmot have no hope among different browsers, leaving control elements unuseful in vertical writing mode.

Contenteditable div, span workarounds can be used to simulate some editable controls, but lack semantics, and are unsafe(I think currently textplain-only contenteditable is still far from being standardised), and BTW, in real world case, they are buggy in vertical writing mode in most browsers, though it's not the issue of the CSS itself.

So please consider having a way of letting designers fully control the appearance of a control.

**Comment by frivoal** [comment]
It is still somewhat unclear how strong the effect of `appearance:none` can be. A large investigation into what is web compatible is needed for that.

If it turns out that `appearance:none` has to leave some native aspects on for compatibility purposes, then some kind of `appearance: none-i-really-mean-it` may indeed be in order.

But at this stage, it is hard to say.

**Comment by annevk** [comment]
#5998 aims to tackle this.
