### ISSUE TITLE
[css-values] ch units shouldn’t cause font downloads

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3135]
Migrated from https://github.com/w3c/csswg-drafts/pull/3129

Right now, [Values and Units](https://drafts.csswg.org/css-values-4/#ch) says:

> Equal to the used advance measure of the “0” (ZERO, U+0030) glyph in the font used to render it.

It’s pretty unfortunate that ch units can cause fonts to download.

WebKit doesn’t do this; it just uses the primary font, and if the primary font doesn’t support “0” then it uses that font’s .notdef glyph. No downloads necessary.

https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/graphics/Font.cpp#L123

https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/CSSPrimitiveValue.cpp#L661

In [this comment](https://github.com/w3c/csswg-drafts/pull/3129#issuecomment-423294483), @emilio says that Firefox does something similar.

**Comment by tabatkins** [comment]
Yeah, it's not intentional that `ch` should cause the "0"-containing subface of a composite face to be downloaded. I agree we should clarify that you can use the "not-defined" glyph if "0" isn't present.

(Is "`.notdef` glyph" a widespread concept we can refer to?)

**Comment by litherum** [comment]
`.notdef` is well-understood, well-defined, and common. (It's just glyphid 0 in every font, commonly rendered as the tofu)

I'd propose making the spec somewhat flexible here, as I can think of a few reasonable behaviors off the top of my head, and we probably shouldn't prescribe any until we can do more research:

1. Use the font's .notdef glyph's width
1. Use the primary font's average character width
1. Pick another character that is renderable somewhere in the fallback list, and is representative

**Comment by emilio** [comment]
Per the links in #3129, looks like WebKit is using (1) and Gecko is using (2). So yeah, if it's not clear one is superior to the other making the spec a bit flexible makes sense.

**Comment by kojiishi** [comment]
Blink does (1) too.

>> Is "`.notdef` glyph" a widespread concept we can refer to?

> .notdef is well-understood, well-defined, and common. (It's just glyphid 0 in every font, commonly rendered as the tofu)

`.notdef` is defined in [Recommendations for OpenType Fonts](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#glyph-0-the-notdef-glyph).

**Comment by bradkemper** [comment]
Today I discovered that a ‘ch’ unit in Font Awesome Pro (a popular icon font) is zero width in Safari. So, I think the .notdef glyph is not a reliable thing to fall back on. Average width doesn’t seem right either, as icons in an icon font tend to be much wider than a zero would be. Maybe something like 0.4em? Or use the width of an actual space character as a fallback first, if it is available?

**Comment by bradkemper** [comment]
Frankly, I don’t see why it can’t just use the next **installed** font from the font list (skipping past fonts that aren’t installed, or that would require a download).

**Comment by litherum** [comment]
We should be designing around the requirements of icon fonts. People shouldn't be using them in the first place.

**Comment by bradkemper** [comment]
People do use them. That’s the world we live in, and need to adapt to. 

Also, I don’t think this is unique to icon fonts. I suspect that the one I’m connecting to (which I don’t have total control over), has been subsetted to save bandwidth, to remove characters that are not actually being used in content. 

In those conditions, why not just...

> use the next installed font from the font list (skipping past fonts that aren’t installed, or that would require a download).

It seems a perfectly reasonable thing to do, as it will always eventually find an already loaded (possibly system) font that has a zero in it.

**Comment by kojiishi** [comment]
I agree there are some such fonts. I've seen them before too. I don't think `ch` needs to take care of such fonts.

**Comment by AmeliaBR** [comment]
I'd strongly say that calculating a `ch` unit (or `ic`, etc.) _shouldn't_ cause a font to download, but I'm not sure that should mean giving up the use of the 0 as the reference glyph.

Consider the case of a custom font with just a few special characters (e.g., fancy ampersand) as the first font in the list, with a regular web font or system font as the next font in the stack. Using an artificially calculated value from the first font seems a poor choice if there is a font available (already downloaded or on the system) with a 0.

In most CSS environments, there will be at least a default font with a 0 in it. And if there really isn't, the spec already defines a fallback (0.5em).

**Comment by kojiishi** [comment]
Finding a system fallback font is not a cheap operation; it requires an RPC call in Blink due to sandbox, and the style recalc pauses during the RPC. I'm not very happy to bake it into the spec when no browsers do it today.

**Comment by svgeesus** [comment]
Mainly, I don't understand why there is any issue. The worries seem to be

- using ch might cause a font to be downloaded that otherwise would not be
- doing a system font fallback for an unused character is a blocking operation

ch is defined to use *the actual font* that is used for rendering. The two things noted above would only occur if:

-  the font actually used has no glyph for "0", AND

- the font actually used has no .notdef (in this case, it would be a faulty font, or the font subsetter was faulty)

Also, falling back to another font for the width of "0" or .notdef misses the point of using *the actual font*.

So my preference would be an ordered list of things to try:

1) the width of the "0" glyph. if it doesn't have one,
2) the width of the .notdef glyph. if it doesn't have one (and thus, the font is broken),
3) use 0.5em

No additional webfont is ever downloaded, no additional local font is loaded either.

**Comment by AmeliaBR** [comment]
@svgeesus That sounds like a good start, although your wording doesn't acknowledge that there may be 2 or more active fonts (meaning loaded & being used in the document) applying for the element.  Would you would search for first the 0 and then the .notdef glyph in this filtered font stack of active fonts, or only use the first active font?

PS, has anyone looked into the other font-relative units & confirmed whether browsers are matching spec as far as the "first available font" being the first one with a space character available?

**Comment by bradkemper** [comment]
I don’t understand why a .notdef glyph is considered to be an acceptable fallback. It it expected to be the same width as a zero? Isn’t it commonly a square shape instead? Mightn’t it also be zero width or just a single stroke wide?

If checking the font-family list is expensive, then how about just getting the system’s default serif or sanserif proportional font?

**Comment by svgeesus** [comment]
> I don’t understand why a .notdef glyph is considered to be an acceptable fallback

Because all fonts are required to have one. 

> Isn’t it commonly a square shape instead?

No, it is typically a rectangle (and, I think, typically uses the default advance width)

>> It is recommended that the shape of the .notdef glyph be either an empty rectangle, a rectangle with a question mark inside of it, or a rectangle with an “X”. Creative shapes, like swirls or other symbols, may not be recognized by users as indicating that a glyph is missing from the font and is not being displayed at that location.

**Comment by svgeesus** [comment]
> your wording doesn't acknowledge that there may be 2 or more active fonts (meaning loaded & being used in the document) applying for the element

Well spotted and yes, it doesn't. Specs referring to "the font used to render" need to be tightened up.

**Comment by litherum** [comment]
The particular case I'm concerned about is something like this:

```
@font-face {
    font-family: DoesNotSupportZero;
    src: url(...);
    unicode-range: a range that doesn't include the '0' character
}

@font-face {
    font-family: ShouldNotBeDownloaded;
    src: url(...);
}

<div style="font-family: DoesNotSupportZero, ShouldNotBeDownloaded;">Some text that doesn't have the zero character in it</div>
```

**Comment by tabatkins** [comment]
Right, Elika's suggestion would use `ShouldNotBeDownloaded`'s 0 character for the ch size *if* something else has caused that font to download already, but would otherwise just use the fallback size. It's stateful, but accurate when there's a font being meaningfully used.

**Comment by jfkthame** [comment]
What about a slightly different case from Myles' example:
```
@font-face {
    font-family: CompositeFont;
    src: url(letters.ttf);
    unicode-range: U+20, U+41-5A, U+61-7A;
}
@font-face {
    font-family: CompositeFont;
    src: url(digits.ttf);
    unicode-range: U+30-39;
}
<div style="
    font-family: CompositeFont;
    border-top: 1ch solid;
">
    Some text that doesn't have the zero character in it
</div>
```
Does the use of the `ch` unit here cause `digits.ttf` to be downloaded? Should it?

**Comment by litherum** [comment]
We should consider "not downloading `digits.ttf`" as a requirement for any solution here.

**Comment by tabatkins** [comment]
No, it should again only use the 0 glyph size if it's already available. It'll never trigger a download on its own.

**Comment by frivoal** [comment]
So, how about:
* use the measurement of the 0 glyph in the font actually used to render that glyph, *unless this would be the only reason to download that font*
* otherwise, use the measurement of the .notdef glyph of the first available font, assuming there is one and it's measurement is not 0
* otherwise, use 0.5em (or 1em depending on writing modes, as usual)

**Comment by jfkthame** [comment]
The concern I have with the argument that the `ch` unit should never *trigger* a font download (but may *use* a glyph size from a downloaded font if available) is that it seems to open the door to mysterious, stateful, action-at-a-distance scenarios.

Given the example in https://github.com/w3c/csswg-drafts/issues/3135#issuecomment-960094958, suppose there's another element on the page that uses the same `font-family: CompositeFont` and *does* happen to contain a zero character; presumably that means `ch` *will* be derived from `digits.ttf`. But perhaps that element hasn't yet been reflowed (and hence loaded the `digits.ttf` resource), e.g. because it is hidden, but then it gets exposed as a result of some subsequent change.

Or the user types a zero into a similarly-styled editable field elsewhere on the page -- does that cause everything that was sized in `ch` units to suddenly shift?

**Comment by r12a** [comment]
Is there a summary of what came from the meeting discussion? (Given the length of the discussion multiplied by the number of people who will follow this thread, it seems that a summary could save a lot of reading and synthesis time. The alternative for those of us who read at about speaking speed is basically to sit through a simulation of the meeting.)

**Comment by dbaron** [comment]
I think the summary was:
 * most of the people present were leaning towards leaving the spec as-is (saying that `ch` units do cause font downloads).  However, given that @litherum , who raised this issue, was not present, we decided to defer trying to resolve the issue for 2 weeks.  (Otherwise we probably would have resolved.)
 * I think there was consensus that, whether or not `ch` units trigger font download, if the font *is* downloaded, then `ch` units get re-resolved if the newly-downloaded font is an earlier font.  (This, in turn, means that the implementation complexity of triggering downloads is merely the triggering of downloads.)
 * We considered and rejected the possibility of using .notdef glyphs rather than 0 glyphs.
 * There was another possibility (option (2)) that I think was also rejected, though I can't actually remember from the notes what it was, and I don't think we discussed it much.
 * The main discussion was between what is listed as option (1) (leave the spec as-is) and option (3) (don't trigger font downloads for `ch`/`ex`/`ic`/etc. units).
 * I think there was general agreement that the case where a  font is downloaded for the `ch` unit but would not otherwise be downloaded is extremely rare.  (I also argued that a big piece of what makes it rare is the "would not otherwise be used" aspect, which means triggering the download *earlier* when `ch`/etc. units are resolved might actually be a net benefit.)

**Comment by r12a** [comment]
Thanks @dbaron. That's really helpful.

**Comment by jfkthame** [comment]
I've created a small testcase at https://jfkthame.github.io/test/ch.html that demonstrates the sort of issues that can occur with option (3). Try it in current Safari to see the problem.

(Note that neither Chrome nor Firefox handle it correctly either, although their bugs are a bit different. As far as I can see, Chrome *never* uses the correct `ch` width, even when the relevant font is available; Firefox does try to use it, but fails to update things at the right time.)

I would argue that the correct rendering of this example is what Safari shows *after* a digit has been typed into the input field, but currently no browser gets this right on initial load. (Safari may get it right on subsequent page-loads, while the relevant font is cached; reload it in a new private-browsing window to see the problem again.)

**Comment by dbaron** [comment]
I think the conclusion is really:
* no normative change to spec
* leave it to the editors as to whether any clarifying notes would be helpful.

**Comment by svgeesus** [comment]
> leave it to the editors as to whether any clarifying notes would be helpful.

Yes, need to go through [your list](https://github.com/w3c/csswg-drafts/issues/3135#issuecomment-1205378100) looking for useful things to make clear in the spec.

In particular, this point would merit an example:

> I think there was consensus that, whether or not ch units trigger font download, if the font is downloaded, then ch units get re-resolved if the newly-downloaded font is an earlier font. (This, in turn, means that the implementation complexity of triggering downloads is merely the triggering of downloads.)
