### ISSUE TITLE
[css-multicol] Clipping of content that overflows a column

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#314]
- https://www.w3.org/TR/css3-multicol/#overflow-inside-multicol-elements

> Content in the normal flow that extends into column gaps (e.g., long words or images) is clipped in the middle of the column gap.
- https://drafts.csswg.org/css-multicol/#overflow-inside-multicol-elements

> Floated or in-flow content that extends into column gaps or neighboring columns — e.g., long words or images — is not clipped and may therefore cause overflow.

The ED change occurred in aa4138974baedaa9ae662a056f40f0054eb5d373.
The [email announcing the draft change](https://lists.w3.org/Archives/Public/www-style/2013May/0253.html) cites the TR as the reasoning for the change...😕

---

A. Some testing suggests that only Firefox implements the ED's "don't clip" behavior. Does the group think that the other browsers are actually going to change their behavior here? It's been 3 years.
B. The ED's text addresses floated and in-flow content. What about non-float out-of-flow content, such as `position:absolute`? Or in the case of the CR's text, what about out-of-flow content? I ask because of https://bugzilla.mozilla.org/show_bug.cgi?id=1282363

**Comment by bradkemper** [comment]
Personally, I'd like absolutely positioned content to get a waiver on being clipped or chopped up between columns. When I have absolutely positioned content inside columns, it is usually for help tip type things (positioned relative to a small span or hyperlink), which would work best if they could remain in one piece when overflowing in the block direction, and not be clipped, not affect the height of of the multicol box, and have a z-index and stacking context relative to the whole multicol box (not just the current column) so that subsequent columns don't cover it. There is no way to do that currently, and different browsers do different things (which sometimes depends on whether the item is near the top or bottom of the column).

**Comment by cvrebert** [comment]
The user in https://github.com/twbs/bootstrap/issues/20161 likewise wishes there wasn't clipping in this case.

**Comment by cvrebert** [comment]
@frivoal Any thoughts here (since you edit css-multicol-2)?

**Comment by frivoal** [comment]
Not clipping in these cases makes sense to me as well.

Both the TR wording and the ED wording are problematic though, as neither of them defines the behavior for all cases. So, what are we after?
1 - in flow
2 - floated
3 - abspos / fixpos
4 - relpos / transforms
5 - ... someting else?

As discussed above, I seems that we have a reasonably good justification for 3 to not be clipped, as there are valid use cases that depend on that. For the rest, I am less sure about use cases, as overflow seems more of an error case to me. In that case, clipping **will** lead to unreadable content, while overflow **may** do so, if the overflowing content overlaps with something. Neither seem great, but the later seem better.

On top of that, maybe one day we'll have a pseudo element selector for the column box, and authors will be able to change the value of the `overflow` property on it. With that in mind, it would be preferable that the behavior we pick today can be explained in terms of values of that property. “Always clip” can, and so does always “overflow”, but having a few things clip while others do not sound harder to retrofit.

=> I think we should let things overflow without clipping in all cases.

(Note: all that is independent of things that overflow in the block direction in a way that triggers fragmentation, as discussed in [the next section of the spec](https://drafts.csswg.org/css-multicol/#pagination-and-overflow-outside-multicol). That's fully governed by [css-break](https://drafts.csswg.org/css-break/). We're only discussing the things that overflow without causing fragmentation)

**Comment by frivoal** [comment]
One more reason to avoid clipping by default is discussed in http://www.w3.org/mid/44710381-60EF-4F3D-8695-2631F9A6887E@rivoal.net :

The default styling for lists (`ol`s and `ul`s) puts padding on the list itself, rather than on the list items. If you make the list into a multicol, that means there's no space for the list markers in columns after the first one. This is annoying enough (but likely unfixable as it's been that way forever), but if we clip in the middle of the column gaps, the markers not only overflow, but also become invisible. So no clipping is better.

**Comment by frivoal** [comment]
Agenda+ to bring this to more people's attention, and see if we can resolve on not clipping anything that overflows columns.

**Comment by cvrebert** [comment]
Pinged the relevant pre-existing Chrome bug: https://crbug.com/269061#c19
