### ISSUE TITLE
[css-scrollbars] Unclear whether keywords intentionally compute away or not

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3149]
The computed value lines for `scrollbar-color` and `scrollbar-width` allows the keyword auto, but not any of the other keywords (dark/light/thin/etc). It's not clear if this is an oversight (in which case “the keyword auto” should probably be replaced with “they specified keyword” or something) or if this was intentional (in which case, the keyword definitions should be more explicit about how they compute to an absolute color/length).

**Comment by upsuper** [comment]
For `scrollbar-width`, I think we may want to get rid of `<length>` eventually, since Apple and Microsoft are apparently unhappy with that, and I also found it easier to implement just the keyword values rather than a more general `<length>`. As far as the keywords approach is enough for usecases it's designed for, I think we can keep just those.

For `scrollbar-color`, I think it was a mistake that I didn't include the two new keywords in the "Computed value" field. I can fix it shortly. I think `auto` definitely should be inherited as keyword, because UAs may pick different style for different elements as they see fit, and inheriting resolved colors would break that. It's less clear to me whether `light` and `dark` need to be inherited as keywords as well, but having all these keywords behave the same way feels move consistent.
