### ISSUE TITLE
[css-flexbox] Flex basis and box-sizing

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#316]
I noticed a problem while working with flexbox last week:

```
<div style="display: flex">
    <div style="flex: 2"></div>
    <div style="flex: 1"></div>
</div>
```

If we add padding or borders, the flex items are not actually distributed at thirds according to the algorithm, even if box-sizing is set to border-box. This is in direct contradiction to our examples/descriptions in https://www.w3.org/TR/css-flexbox-1/#flex-common

The way things are, it's not possible to get things to align unless you do some fancy math with the padding and borders... the avoidance of which is exactly the point of having the box-sizing property. I'm somewhat afraid it's not possible to fix this anymore. :( But for sure it's got to be annoying for authors...

**Comment by p2227** [comment]
you can read this: http://stackoverflow.com/questions/34753491/how-does-flex-shrink-factor-in-padding-and-border-box

**Comment by tabatkins** [comment]
Yeah, it would be nice if flex would work with the box-sizing property, but it does complicate things; the border+padding would have to act as an additional min-size constraint, effectively.

I'm also very unsure whether it's compatible to make such a change now.  Perhaps we could add a property switch that makes it pay attention?

**Comment by fantasai** [comment]
The original intent of `flex: <integer>` was to specify flexibility as absolute ratios... we're failing at that if we don't/can't change it!

**Comment by fantasai** [comment]
@dholbert @cbiesinger @atanassov Comments here? Is this something we can fix?

**Comment by tabatkins** [comment]
In particular, would it be okay to make the necessary edits so that the following:

```css
.flexbox {
  display: flex;
  width: 300px;
}
.flex-item {
  box-sizing: border-box;
  border: 20px;
}
.flex-item:nth-child(1) {
  flex: 1;
}
.flex-item:nth-child(2) {
  flex: 2;
}
```

results in the first item being 100px wide (20px border, 60px content, 20px border) and the second item being 200px wide (20px border, 160px content, 20px border)?

Today you instead, unfortunately, get the first item being 113px wide (20px border, 73px content, 20px border) and the second being 186px wide (20px border, 146px wide, 20px border), because they're distributing the 220px of free space in a 1:2 ratio.

**Comment by FremyCompany** [comment]
Adding myself to the thread, but given how many websites are using flexbox today combined with a framework that sets border-box on all elements by default, this breaking-change seems unlikely to be webcompatible to me.

Maybe adding ```flex-sizing: border-box | content-box | ...``` would work. Future frameworks could set it on by default. This isn't exactly a high-priority problem to solve though...

**Comment by fantasai** [comment]
True, but I think in most cases the current behavior is either unintended or unnoticed.

I think it's worth fixing if we can. This is the one place we screw up and effectively don't use border-box sizing even when you've specified it.

**Comment by fantasai** [comment]
CSSWG resolved to try to fix this! Blink team has volunteered to try implementing; if they can pull it off without breaking anything, other vendors will follow.

**Comment by astearns** [comment]
Reopening for testcase need.

**Comment by zcorpan** [comment]
@tabatkins can you point to the test case? If there isn't one, this should be open?

**Comment by MartinMa** [comment]
Just to be clear. The behavior has not change since this issue report right? The example given by @tabatkins still leads to a distribution of 113px and 187px with a 300px-wide flexbox with two border-box-enabled items that have a border of 20px in a flex ratio of 1:2.

I made a quick pen to demonstrate the issue again:
https://codepen.io/MartinMa/pen/bGdMrjx

The spec reads

> When determining the flex base size, the item’s min and max main sizes are ignored (no clamping occurs). Furthermore, the sizing calculations that floor the content box size at zero when applying box-sizing are also ignored. (For example, an item with a specified size of zero, positive padding, and box-sizing: border-box will have an outer flex base size of zero—and hence a negative inner flex base size.)

So can we agree that `box-sizing: border-box` is essentially ignored?

**Comment by cbiesinger** [comment]
cc @davidsgrogan , I haven't worked on flex in several years now
