### ISSUE TITLE
[css-conditional-3] define whether/how it matters if namespace prefixes are declared

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#3220]
One issue that came up in #3207 (noticed by @heycam while reviewing code from @emilio) is that the spec should define to what extent namespace prefixes are required to be declared.  In particular, how do:

```css
@supports (content: attr(n|href)) {
}
```

```js
CSS.supports("content", "attr(n|href)");
```

```js
CSS.supports("(content: attr(n|href))");
```

depend on whether the namespace prefix `n` has been declared?  Do they:
* treat all namespace prefixes as already declared?
* treat all namespace prefixes as undeclared (invalid)?
* depend on a set of namespace declarations (which set, exactly)?

**Comment by emilio** [comment]
Thanks for filing, was on my list of things to do :)

As I said in the linked issue, I'd argue for keeping the consistency with existing APIs in regards of treating undeclared namespaces as invalid.

For example, right now `document.querySelector("a|b")` throws instead of returning null, for example. I think `CSS.supports` should do the same, and same `@supports` unless namespaces are registered in the style sheet.

This is both more consistent (IMO) and easier to implement / less special-casey.

**Comment by emilio** [comment]
(Do the same as in "treat it as invalid", not as in throwing :))

**Comment by dbaron** [comment]
In the discussion just minuted in #3207, we resolved not to take the option of "namespaces are all invalid", but didn't yet choose between "all valid" and "use the namespace map".

**Comment by fantasai** [comment]
Minutes of the earlier discussion: https://lists.w3.org/Archives/Public/www-style/2018Dec/0004.html

**Comment by svgeesus** [comment]
> RESOLVED: Namespaces are either always valid or valid when they're declared. (Issue #3220)

Well, we need to pick **one** of those :)

**Comment by svgeesus** [comment]
@emilio, any opinions?

**Comment by emilio** [comment]
I'd prefer the "valid when declared" option. Still less special-casey.
