### ISSUE TITLE
[css-sizing-4][css-grid-2][css-align-4] Rename 'ar' unit?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3225]
@jensimmons  was wondering if we should rename the `ar` unit to something else, since it's not exactly an aspect ratio. Not sure what, though. Maybe `tr` for “transfer ratio”?

**Comment by jonjohnjohnson** [comment]
What if we didn't add a new unit type exactly, but made it so box size properties could instead just accept a "unit-less" float that always represents the ratio/relationship of the dimension of the property it is declared upon to its opposing axis? Or possibly always block to inline size regardless of declared property?

```css
height: 2;
```
```css
width: calc(1 / 3);
```
```css
block-size: 1.5
```
```css
min-inline-size: 3
```
I know this is still adding a new *unit, just a slightly different way about the syntax?

**Comment by astearns** [comment]
@jonjohnjohnson we're not likely to add any new unit-less values in CSS. Over the years we have found it's much better to be explicit about what the numbers in CSS values mean.

**Comment by jonjohnjohnson** [comment]
@astearns I've noticed that and find it understandable, especially for typing. I just wasn't sure of the value in adding new unit types piecemeal.

Though `fr` for `grid` (and the unit-less values for `flex` grow/shrink) are fractions of available space. Would it be too confusing for an `fr` unit on a box size property to behave as a "fraction" of the computed value of an opposing axis?

**Comment by jensimmons** [comment]
I thought about this a lot on the plane from TPAC to View Source today. @fantasai wants to use a two character unit where the second letter is an 'r', so that it matches 'fr' well. So I make a list of every combination: ar, br, cr, dr, etc... and crossed out all the ones that don't work (like br, ir, lr... too confusing or weird). 

Purely looking at letter combinations, and thinking about what something-'r' units we might make up in the future, these are options:
- The best letter combo options (imho): kr, mr, tr 
- Others that also sort of work: ar, dr, gr, jr, nr, qr, sr, wr, xr, yr, zr

`tr` is a really good combination. So I started thinking about what `tr` could stand for. I don't like using `ratio` in the name, because it's not really a ratio. Or at least it's not a ratio in the way that an aspect ratio is a ratio. 

But then I started realizing, well, `fr` doesn't stand for "fraction r-something". `fr` stands for FRaction. And hey, transfer is also a word that has an 'r' as it's second letter. TRansfered. So I propose we do use `tr`, but we do _not_ include the word ratio. Instead we say "transferred length", or better, the phrase @rachelandrew said at the face to face this week, "transferred size". 

`TR` stands for TRansfered size. Or TRansfer. 
Just like FR stands for FRaction. Or FRaction of the available space.

**Comment by Archibald2** [comment]
This issue is also being discussed in #333 and #1173.

The "tr" (or "ar") unit either relates the width to the height or relates the height to the width.  I think this could be confusing.  Code would be easier to read if '%w' is used for width and '%h' is used for height. So for example;
```
div {
min-height: 100%w;
}
article {
max-width: 150%h
}
```
"%w" and "%h" are only suggestions: they could be just "w" and "h" (subject to comments in other threads).

If "tr" is favoured, I suggest it should be a percentage value like "vw" and "vh (as was proposed for "ew")..
