### ISSUE TITLE
[resize-observer] Add layoutBox property to constructor

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#3238]
Currently, the default box returned to the author is the content-box but there are many scenarios in which the author wants the border box.

**Comment by gregwhitworth** [comment]
I have added `layoutBox` to the WebIDL and outlined how this is set - it's allowed values and generalized it under [ResizeObserverEntry](https://drafts.csswg.org/resize-observer/#resize-observer-entry-interface). I'm not extremely versed in writing WebIDL so I welcome any feedback that @tabatkins or @heycam may have on these changes as can be seen here in the [ED](https://drafts.csswg.org/resize-observer/). After your feedback I'll add it to the agenda for review and feedback from others.

**Comment by gregwhitworth** [comment]
@atotic can you review and provide feedback as well.

**Comment by heycam** [comment]
A few comments:

We should use an enum to define the value space of layoutBox, so that what happens when we pass in an invalid value is handled in a way consistent with other APIs.  So something like:

```
enum ResizeObserverLayoutBox {
    "padding-box",
    "border-box",
    "content-box"
};
```

and then use that instead of DOMString in all places.  The result will be that an exception is thrown when invalid values are passed in.

Then we should make the ResizeObserver constructor argument have a default value, so:

```
[Constructor(ResizeObserverCallback callback, ResizeObserverLayoutBox layoutBox = "content-box")]
```

so then we don't need to do anything in the prose for the constructor to handle a missing/default value either.

The header for the prose section describing the ResizeObserver constructor should be updated to have the layoutBox argument.

The layoutBox declaration itself should be `readonly attribute ResizeObserverLayoutBox layoutBox;`.

The prose description of `new ResizeObserverEntry(target)` talks about this.layoutBox, but there's no layoutBox on ResizeObserverEntry.

**Comment by gregwhitworth** [comment]
@heycam @tabatkins thanks for the feedback. @atotic were both working in parallel on this and he has some solid ideas in a Google doc. After the breakout session we'll update the spec and get review again.

**Comment by gregwhitworth** [comment]
Based on discussions and changes made by Alek I'm going to close this one out as we went in a slightly different direction.
