### ISSUE TITLE
[css-position] should define containing block for static and relative positionings

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3253]
https://drafts.csswg.org/css-position-3/#def-cb says

> The containing block of a static or relative element is defined in the Box Model [CSS3BOX].

This was true before 5434e6a9752b6122cdd6f619431f1469af6aca7a:

https://github.com/w3c/csswg-drafts/blob/24ef9b696e69c76e0a0b8425bd8e11a116f64a0f/css-box-3/Overview.bs#L539-L600

But now css-box just links to https://drafts.csswg.org/css-display-3/#containing-block

**Comment by tabatkins** [comment]
Position now says:

> The containing block of a static, relative, or sticky box is as defined by its formatting context.

Since Flexbox, Grid, etc all have their own specialized definitions of CB, linking to Box explicitly is no longer correct anyway.

Currently Block/Flow layout is defined by 2.1, and it does define CB for that display type, so this is currently addressed satisfactorily, I think? When we finally do pull that bit out into a Flow Layout spec it'll need to come along, but that should happen automatically. ^_^

**Comment by Loirooriol** [comment]
I'm fine with that... but I'm not sure that all layouts clearly define the containing block. E.g. https://drafts.csswg.org/css-multicol/#the-multi-column-model

> These column boxes establish an independent block formatting context into which the multi-column container’s content flows, and form the containing block for its non-positioned children.

works great for `position: static`, but not for `position: relative`. I guess it ends up being fine since the column boxes are block containers, so it will be covered by the future Flow Layout spec, but it's a bit confusing.

Maybe CSS Position could defer the definition of the containing block of a static, relative, or sticky box to the formatting context, but specify that these 3 cases must have the same containing block
