### ISSUE TITLE
[css-values] The lh and rlh units are more complicated than what they seem.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3257]
https://drafts.csswg.org/css-values/#lh says:

> Equal to the computed value of the line-height property of the element on which it is used, converting normal to an absolute length by using only the metrics of the first available font.

But the computed value of line-height depends on other properties at least in some browsers, so this suddenly becomes really tricky.

For example, `<select>`'s line-height computed value for comboboxes changes in WebKit and Blink to `normal` if the select is themed (based on the -webkit-appearance) property:

  https://crisal.io/tmp/select.html

I'm considering doing the same in Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1501908.

In any case, the _used_ value does definitely depend on theming of comboboxes, for example, across all browsers (see above).

How are these units supposed to work in this case? We definitely don't want values to depend on used values. We should probably specify how these adjustments work and make them work across browsers before anyone implements these units.

cc @lilles @FremyCompany @zcorpan

**Comment by emilio** [comment]
https://bug1501908.bmoattachments.org/attachment.cgi?id=9020530 is probably a more permanent link that the one above.

**Comment by fantasai** [comment]
@emilio Seems a bit odd that -webkit-appearance affects the computed value of `line-height`, I recall implementers (particularly Mozilla) arguing for minimal interference among properties for computed values. Is `-webkit-appearance` your only example or are there more? Also, what happens if an author sets `line-height` on the OPTION elements or OPTGROUP? Does it take effect or no?

**Comment by MatsPalmgren** [comment]
@fantasai We currently have `option,optgroup { line-height: normal !important; }` in [our UA sheet](https://searchfox.org/mozilla-central/rev/a21ac3d8e53cd37b6725f982b185d92fe47d8835/layout/style/res/forms.css#342,373). I'm considering changing that, but I need to reverse-engineer what other UAs do first...

We used to have the same on `<select>` and when I removed the `!important` part there it broke Twitter since Gecko didn't have any "treat it as `normal` for themed comboboxes" code in place...

**Comment by emilio** [comment]
I'm all in to less interaction between properties.

Though sometimes (in particular in this case, where we _need_ to implement this interaction because of compat), it may be easier to do at computed value time rather than at used value time.

Seems like blink's code for this is:

  https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/layout/layout_theme_default.cc?l=303&rcl=a18d95d1f23d08476ebe0bae8ce198a4c1e93427

There's a bunch of other font controls that affect line height, looking at that file, and to:

  https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/layout/layout_theme.cc?l=243&rcl=1d2414e576dce6b3d55550002fd8f04c72e469d9

**Comment by emilio** [comment]
Note that differences between computed value time line-height and used-value-time line-height special-cases are indistinguishable as of now (in theory, see https://bugs.chromium.org/p/chromium/issues/detail?id=899489).

But it's something we need to have interop on before even considering implementing these units.

**Comment by emilio** [comment]
Another interesting case is text autosizing, which in some browsers like WebKit affects the computed line-height, and in others like Gecko or Blink affects the used line-height.

**Comment by emilio** [comment]
Though I guess that also affects font-size so there's a precedent on how they should behave there.
