### ISSUE TITLE
[css-sizing] Rethinking how to prevent overflow in a container with an explicit aspect ratio

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#3268]
We are working on defining a way to explicitly assign an aspect ratio to elements. We also want an easy way for Authors to be able to specify that they want their container to grow to fit more content, if there is more content than will fit into the constrained box. 

In the current rough draft at https://drafts.csswg.org/css-sizing-4/#ratios, there are two options proposed — an Option A, and Option B. (I'm not going to describe them here, you can go read them at that link.) (For more, read these slides: https://noti.st/jensimmons/FnU3KJ/adding-explicit-aspect-ratios-to-css) 

After the CSSWG last week at TPAC Lyon 2018, it struck me that maybe we don't need either option. Maybe we already have the building blocks needed. 

Would it work to simply do this?
```
.square-that-grows-to-hold-all-content {
    width: 100%;
    aspect-ratio: 1 / 1;
    min-height: max-content;
}
```
Do we need something more than this? I'm thinking this might do it. 

The `width` is set by the containing formatting context. The `height` is set by the `aspect-ratio` property to be (in this case) the same length as the width. And the `min-height` overrules the height, telling the browser to make the `min-height` be bigger if the `max-content` size of the content requires it (or perhaps, `min-content`). 

It seems this will work if `min-height` beats `height`. To see if this happens, I made this test: 
https://codepen.io/jensimmons/pen/ePbePr?editors=1100 

That Pen not work in Firefox, since we haven't implemented `max-content` yet. But it does appear to work the way I'm hoping in Safari & Chrome on Mac desktop.

Thoughts?  / cc @dbaron @fantasai @tabatkins

**Comment by jonjohnjohnson** [comment]
@jensimmons As long as we could also ensure things like...
```css
min-height: max(max-content,50vh);
```
Which, the current the implementation of `max()` in STP doesn't allow. I'm just hoping that `aspect-ratio` will clean up the mess that is trying to work with multiple constraints, such as this min/max/aspect utility setup -> https://jsbin.com/yuvaka/edit

**Comment by frivoal** [comment]
> It seems this will work if min-height beats height.

`min-height` does beat `height`, so this works, and I agree it means we don't need "option a", as we can indeed just do that. (As for option "b", if doing this is the only use case for it, we don't need it either, but it can express different things as well. Whether we need those is a different conversation).

However, for elements other than replaced elements / scrollers / iframes, I think this behavior should be the default one, rather than something authors need to opt into, in order to avoid accidental overflow when the font happens to be bigger than expected, or any other situation where the layout ends up being not exactly what the author had in mind.

Given that the initial value of `min-height` is `auto`, maybe we're in luck. How about defining that when `aspect-ratio` is set and the element is non-replaced / a scroller / an iframe, then `min-content: auto` resolves to `max-content` (or , as you said perhaps `min-content`)?

It looks like this would solve both the problem of having this behavior by default, and of making it possible to override, simply by having authors manually set `min-height` to `0` when they don't want things to auto-grow.

**Comment by radogado** [comment]
Hi, can I suggest an aspect ratio container's height to be divisible by the line height to preserve baseline (vertical rhythm)? Maybe optionally add bottom padding or margin to adjust the height. Thanks!

**Comment by jensimmons** [comment]
Re: @frivoal 's comment above (Nov 11) — I think that's a good idea. I could see debating it some more, but I'm leaning your way, so I think we should do that... and then change our minds later / figure out something else if we decide to later.

**Comment by jensimmons** [comment]
@radogado You might be interested in the `lh` unit — line height unit, in CSS Values and Units Level 4: https://www.w3.org/TR/css-values-4/#font-relative-lengths

**Comment by radogado** [comment]
@jensimmons thanks for the 'lh' unit, I wasn't aware of. It seems the above "block-step-size" property will solve the problem, looking forward to it. Another example:

I have line-height of 24 and a 40px tall image. I need that image to automatically get bottom padding of 8px to compensate for the discrepancy between real height and multiplied line-height:

`padding-bottom: round-up-to-line-height; // not hardcoded 8px, because it varies`

Regards

**Comment by frivoal** [comment]
@dholbert what do you think of https://github.com/w3c/csswg-drafts/issues/3268#issuecomment-437731901 ?

**Comment by dholbert** [comment]
> @dholbert what do you think of (comment)

@frivoal Sorry for not replying to this sooner -- it sounds good to me.

**Comment by Showcase-Joz** [comment]
i've just read through the smashing article (https://www.smashingmagazine.com/2019/03/aspect-ratio-unit-css/ @rachelandrew ) that covers the basics of issue.

The solution looks excellent and i cant wait to implement it. That said, i don't think every instance would be relative to the content, and a little forgiveness reserved for the aesthetics of layout design.

is there scope to **give grid-gap a little super power**? in as much as that when an item needs to keep its aspect ratio, the surrounding grid-gap (if used) pads out the difference in gap relative to its siblings. 

![example of variable grid-gap](http://i64.tinypic.com/34rvaxy.jpg)

as highlighted in the article, images can be cropped, copy can be scrolled with overflow, while video is ideally best viewed at the correct aspect and without cropping.

**Comment by jensimmons** [comment]
We just made the edits in https://github.com/w3c/csswg-drafts/commit/cb2ff676f4fc6ac6a86e14c4da993c1b7e16af69 which you can now see at: https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum

Let us know if it needs further corrections, or file new issues.

**Comment by jensimmons** [comment]
@Showcase-Joz It looks like you will be able to do exactly what you drew by using a combination of `grid-column: span 2` and `justify-self: center;` on the green box grid item. If we've misunderstood your point, and want to discuss something more, please open a new issue.

**Comment by cbiesinger** [comment]
@AmeliaBR -- I think this is the issue you were talking about yesterday, whether the default for aspect-ratio should allow growing the element to prevent overflow

**Comment by audio-recordingperceptib** [comment]
> [@radogado](https://github.com/radogado) You might be interested in the `lh` unit — line height unit, in CSS Values and Units Level 4: https://www.w3.org/TR/css-values-4/#font-relative-lengths





https://lnkr.fun/1baa0dc
