### ISSUE TITLE
[css-flexbox]the 'auto' value should be add to 'flex-basis' ?

### ISSUE THREAD

**Issue by p2227** [w3c/csswg-drafts#329]
https://www.w3.org/TR/css-flexbox-1/#flex-basis-property

should 
```
Value:	content | <‘width’>
```
be
```
Value: auto | content | <‘width’>
```

??

**Comment by frivoal** [comment]
`auto` is part of `<'width'>` already.

**Comment by chharvey** [comment]
This is confusing because the `auto` value for `flex-basis` behaves differently than the `auto` value for `width` (or `height`). And what's worse, if you *want* the width (or height) to be 'automatically sized', you must use `flex-basis: content`.

Because the `auto` keyword, even though already part of the `<'width'>` syntax, behaves differently, I completely understand @p2227's mistake in missing it. What a pedagogical nightmare!

May I suggest setting `auto` to trigger the 'automatic sizing' behavior, as it is for `<'width'>`, and introduce a new keyword `defer`, which would mean "look at my width or height property"?

**Comment by frivoal** [comment]
I'm afraid this suggestion comes a few years too late. Implementations have shipped, and web content depends on it. In addition to making the point that this would be a good idea, if you want this to happen, I think you need to present evidence that making this change would not result in many web-sites breaking, which I doubt is possible.
