### ISSUE TITLE
[css-color-4] Alias "grey()" to "gray()"?

### ISSUE THREAD

**Issue by jhpratt** [w3c/csswg-drafts#3298]
[Relevant section](https://www.w3.org/TR/css-color-4/#grays)

As far as I'm aware, anywhere "gray" is used in CSS, "grey" is treated identically. Will level 4 colors no longer follow this, or was it an oversight?

**Comment by tabatkins** [comment]
The `gray`/`grey` duplication was a property of the X11 colors that CSS took wholesale; it wasn't an intentional decision on anyone's part. (Take a look at [Alex Sexton's talk about the history of these colors](https://www.youtube.com/watch?v=HmStJQzclHc)!)

The 'grey' spelling is a British (and ex-empire in generally) spelling; CSS uses American spelling, and we don't generally add British spelling aliases. (See the perennial request for a `colour` alias. ^_^)

**Comment by jhpratt** [comment]
@tabatkins I had forgotten about the merging of colors. However, I feel as though people have come to expect `gray` and `grey` to work identically in all situations, as that's how it's been historically.

**Comment by svgeesus** [comment]
The aliasing of international-English grey and US-English gray is _least_ problematic as a property value (but would probably still not be adopted, were those keywords to be proposed today). As a functional notation, it would be more problematic; it would require precedence and de-duplicating rules in case both were specified. Even more so for aliasing the `color` property to `colour` (and the same for all the `*-color*` properties.

Sorry, this would add far more issues than it solves.

**Comment by HerrBertling** [comment]
Well, there's always https://github.com/hashanp/postcss-spiffing if someone really, really wants to use British English 😄 <sup>I know this is not helping the discussion, but I just could not resist</sup>

**Comment by tomhodgins** [comment]
Maybe an explanation about `grey`vs `gray`, or `color` vs colour would be good to add to one of these pages:

- https://wiki.csswg.org/faq
- https://wiki.csswg.org/ideas/mistakes

As a Canadian who teaches people HTML/CSS, the 'u' absent from `color` is an issue every single learner seems to stumble over at first because it doesn't appear wrong to them. It would be wonderful to have an official acknowledgement somewhere like these pages that's easy to point to and show people, as well as find if they're searching for it that explains why it's named the way it is and that US english is the standard for all CSS terminology.

**Comment by Sainan** [comment]
> The aliasing of international-English grey and US-English gray is _least_ problematic as a property value (but would probably still not be adopted, were those keywords to be proposed today). As a functional notation, it would be more problematic; it would require precedence and de-duplicating rules in case both were specified. Even more so for aliasing the `color` property to `colour` (and the same for all the `*-color*` properties.
> 
> Sorry, this would add far more issues than it solves.

I don't see how duplicate properties would be problematic or require any rules at all. Consider the following 'problematic' example:

```CSS
color: red;
colour: green;
```

This is not any more problematic than this:

```CSS
color: red;
color: green;
```

In fact, they're semantically identical (at least in my ideal world where CSS supports this).

**Comment by svgeesus** [comment]
> It would be wonderful to have an official acknowledgement somewhere like these pages that's easy to point to and show people, as well as find if they're searching for it that explains why it's named the way it is and that US english is the standard for all CSS terminology.

>> W3C uses U.S. English (e.g., "standardise" should read "standardize" and "behaviour" should read "behavior").
>> [W3C Manual of Style, Spelling](https://www.w3.org/Guide/manual-of-style/#Spelling)

**Comment by Sainan** [comment]
Hello, here's your annual reminder that American English is not the only English dialect. Still looking forward for CSS to support `colour`, `background-colour`, etc. in a future standards version! :)

**Comment by svgeesus** [comment]
Your question has [already been answered](https://github.com/w3c/csswg-drafts/issues/3298#issuecomment-1731880376). Please stop spamming this closed issue.

**Comment by Sainan** [comment]
Just because documents themselves should be written in American English doesn't mean that you can't introduce non-American English tokens as valid syntax.
