### ISSUE TITLE
[css-display] Consider removing display: run-in (for browsers)

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-drafts#339]
It doesn't seem like any browser has interest in implementing it, even if it's quite a neat feature.

**Comment by dauwhe** [comment]
Many non-browser CSS implementations support this. We use it all the time producing books with CSS.

**Comment by frivoal** [comment]
I think browsers gave up on their implementation before we got a revamped spec for this feature. Having been burned once, browsers don't seems to be in a rush to implement this again, but I'm hopeful that if they try, this will work out better than last time.

Also, as @dauwhe said, there are multiple non browser implementations and more coming, since it is on the list of things we want to Implement at Vivliostyle.

**Comment by gregwhitworth** [comment]
@Ms2ger My assumption is this issue is safe to close? Do you agree?

**Comment by fantasai** [comment]
Agreed with prior comments. If anything remains a problem, we'll defer it to L4.
