### ISSUE TITLE
[css-nav-1] Starting point can be off-screen

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3391]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/129
Originally created by @hugoholgersson on *Fri, 02 Nov 2018 07:26:42 GMT*

---
Even when the focused element F is off the screen, for example after `F.focus({preventScroll: true})`, spatnav uses F as starting point for distance calculations.

Why is this a problem? It gives an unpredictable user experience: 

Imagine F being off-screen, above the visual viewport. If the user goes `up`, she probably wants to search the viewport for candidates from the bottom-most edge. (This is how spatnav would search a focused scroller.) Instead, the current spec calculates distances from the scrolled out F. The closest candidate is the focusable closest to F's position - a position the user can't see.

In Chrome we've solved this by skipping off-screen starting points: when F is off-screen, we search from an edge of the first visible enclosing container of F. I've updated https://bit.ly/snav2, my vision for spatnav in Chrome, to cover this case.

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/129#issuecomment-436926367
Originally created by @jihyerish on *Thu, 08 Nov 2018 09:19:06 GMT*

---
In current spec, (let AD is the distance between A and D, AC is between A and C)
if AD < AC, then the focus will move to D.
For now, I'm more inclined to this behavior, but I agree that your opinion also makes sense. 
@frivoal, what do you think?

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/129#issuecomment-436140881
Originally created by @jihyerish on *Tue, 06 Nov 2018 06:03:56 GMT*

---
> Instead, the current spec calculates distances from the scrolled out F. The closest candidate is the focusable closest to F's position - a position the user can't see.

By default, the best candidate which will gain the focus from the focused element (starting point) is selected among the visible focusable elements, and invisible elements aren't considered as the candidates.
It means that if the starting point becomes off-screen, the focus will always move to the element which the user can see.
For example, 
![image](https://user-images.githubusercontent.com/6636090/48044946-b1129680-e1d1-11e8-8328-365d62746c4b.png)
- Step 1: Initial status
  ( A gains the focus.)
- Step 2: After scrolling down
- Step 3: After the down arrow button is pressed
  ( B is not considered as the candidate because it is invisible.)

You can see the result described above in here:
https://wicg.github.io/spatial-navigation/demo/sample/heuristic_scrollable.html

I think this approach can solve your concern.

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/129#issuecomment-436188715
Originally created by @hugoholgersson on *Tue, 06 Nov 2018 09:35:18 GMT*

---
That was not my concern (I do understand that spatnav only considers visible candidates).

Look at this example:

![where_to_go](https://user-images.githubusercontent.com/24312745/48054705-308e6e80-e1ae-11e8-816e-80c2785a9d41.png)

On `Down`, where do you expect focus to go? C or D? As a user who cannot see A and who is completely unaware of A, I'd expect focus to go to first element in the direction, C.

**Comment by jihyerish** [comment]
In current spec, (let AD is the distance between A and D, AC is between A and C)
if AD < AC, then the focus will move to D.
For now, I'm more inclined to this behavior, but I agree that your opinion also makes sense.

**Comment by hugoholgersson** [comment]
[Chrome ignores an off-screen `activeElement`'s rect](http://bit.ly/snav2). I think that makes spatnav's choice more intuitive (less confusing) for users. I'd appreciate if you could spec this behavior.

**Comment by jihyerish** [comment]
On top of this case, there are additional cases which need to reset the search origin.

1. Search origin can be disappeared
(style of the element is changed to `display:none` / `visibility: hidden` / etc)

    In this case, the search origin would be reset to the **`Rect` of the disappeared element**.

    Currently, the implementation is going on which is the same approach with this:
    https://chromium-review.googlesource.com/c/chromium/src/+/1600930)

2. Viewport can be changed by the non-focusable element
   * non-focusable elements could be: 
      * the target element of scrollIntoView API
      * the target element which corresponds '#id' in URL 
      * the target fragment from searching with CTRL+F

   In this case, the currently focused element also moves out of the viewport.
   But the considerable thing is that the viewport changes because of targeting the non-focusable element.

   My initial opinion was resetting the search origin to the **ancestor spatial navigation container** of the currently focused element.

   But talking with @frivoal, we make a more precise definition of "search origin" and "spatial navigation starting point".
  * spatial navigation starting point: The origin for searching next target which is set by UA. This can be element or point.
  * search origin: The spatial navigation starting point, if it exists, but if it's not, the currently focused element.

   Depending on this definition, in this case, the search origin can also be reset to the non-focusable object.

**Comment by hugoholgersson** [comment]
> Viewport can be changed by the non-focusable element

Could you give a more detailed example? You mean `activeElement` gets scrolled out (off-screen)?

**Comment by jihyerish** [comment]
@hugoholgersson Yes, the `activeElement` gets out of the viewport.
The reasons for this are different, but the result is the same.

These are the reasons that I've mentioned above:
> non-focusable elements could be:
> the target element of scrollIntoView API
> the target element which corresponds '#id' in URL
> the target fragment from searching with CTRL+F

For example, when you search the specific word in the web page with CTRL+F, and then press enter, the page will scroll towards the word that you found.

**Comment by hugoholgersson** [comment]
Ok!

> But talking with @frivoal, we make a more precise definition of "search origin" and "spatial navigation starting point".

I don't understand why we need both a "spatial navigation starting point" and "search origin". In Chrome we only use "search origin".

> My initial opinion was resetting the search origin to the ancestor spatial navigation container of the currently focused element.

This sounds more like what we do in Chrome today. Here's a description of our [SearchOrigin-algorithm](https://bit.ly/snav2).

> In this case, the search origin would be reset to the Rect of the disappeared element.

In Chrome today, when `activeElement` gets removed, we search from the first visible ancestor scroller's edge. Why is it better to search from the disappeared element's rect?

**Comment by frivoal** [comment]
> I don't understand why we need both a "spatial navigation starting point" and "search origin". In Chrome we only use "search origin".

It's just a spec concept, it doesn't have to be directly reflected in the implementation. The HTML spec does the same for Tab navigation. Basically, how to determine the "search origin" is fully defined by the spec, but if the browser wants to use some heuristic to search from somewhere else in some cases, it sets the "starting point", and that overrides the "search origin". That's all there's to it.

----

I can see use cases where keeping the SearchOrigin even when it is offscreen will make things more intuitive, and others when it doesn't. I think it depends both on the layout of the document, and on what the user is doing and how they are navigating the page. I would tend to think that keeping it even when offscreen is less surprising, but I don't have data to back that up, and if most people think otherwise, we could switch.

**Comment by jihyerish** [comment]
> In Chrome today, when activeElement gets removed or hidden, we search from the first visible ancestor scroller's edge. Why is it better to search from the disappeared element's rect?

@hugoholgersson , Because the user may want to focus the certain position of the page if he/she loses the focused element. 
The reason for making the element disappears isn't the user's intention. It's because the page changes dynamically.
So the user will be confused when the focus moves unintentionally.

If we search from the first visible ancestor scroller, it may look like the page suddenly scrolls to the top when the disappeared element had been positioned at the end of the scroller.
[Here](https://docs.google.com/document/d/1mmi3iPcuJMKwYzEWpLAV7Gi_n6aLto6CPEL7H8N24BI/edit) is a more detailed explanation from @junho

It would be nice to reset the search origin considering the last change the page performed and the user's action. I'd like to suggest to resolve like below:

1. If the search origin becomes off-screen by scrolling, 
    set the **scroll container** as the search origin.

2.  If the search origin becomes invisible/inactive (`display: none`, `visibility: hidden`, `inert`),
     set the **rect of the previous search origin** as the search origin.

**Comment by jihyerish** [comment]
Closed by https://github.com/w3c/csswg-drafts/commit/377dccc4af2dcbf6eb41f041f7fd8ea1d0427a18
