### ISSUE TITLE
[css-text-decor] text-decoration-skip: spaces should not skip Mongolian NNBSP

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#3393]
2.5.1. Text Decoration Line Continuity: the text-decoration-skip property
https://drafts.csswg.org/css-text-decor-4/#text-decoration-skip-property

The value `space`, when applied to the CSS property `text-decoration-skip`, breaks the line under white space. According to the [Mongolian Layout Requirements folks](https://github.com/w3c/mlreq/issues/9), there should be no break under a gap produced by the suffix separator NNBSP,  because the suffix(es) are considered to be part of the word.

The current text of the CSS spec says: "Skip all spacing, i.e. all typographic character units with the Unicode White_Space property [UAX44], plus any adjacent letter-spacing or word-spacing." This definition includes NNBSP, which is a problem for Mongolian.

There is a [test available](https://w3c.github.io/i18n-tests/run?base=css-text-decor/line-decoration&batch=line-decoration&test=text-decoration-skip-068.html), but no production browsers currently support text-decoration-skip, so there are no useful results yet, but it shows an example of relevant text.

**Comment by r12a** [comment]
Some additional background: NNBSP is in the Unicode Mongolian block because it was envisaged that Mongolian suffixes was the main reason for this character to be added. NNBSP also interacts with the characters on either side of it in Mongolian, changing shapes.  Since then, however, others have begun using the character as an ordinary white space – such as French people, who want a short no-break space before sentence-final punctuation !

**Comment by frivoal** [comment]
Without having researched it, and going from a gut feeling I'd say that for the french usage, not skipping NNBSP would also make sense. Otherwise, you'll end up underlining lone punctuation marks separately from the nearby word, which doesn't seem great. Compare these two (which also skip ink):

<img width="379" alt="screenshot 2018-12-04 09 51 39" src="https://user-images.githubusercontent.com/113268/49410921-404ba380-f7aa-11e8-9ab5-0c31e79b5eb1.png">

**Comment by fantasai** [comment]
Done. Thanks for the report @r12a!
