### ISSUE TITLE
[css-transforms] Have scale function accept percentage value

### ISSUE THREAD

**Issue by Ernedar** [w3c/csswg-drafts#3399]
Hello,
I would like to suggest adding percentage for [scale](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale) function in transformations.

Current state: `scale()` is using `[-NUM, NUM]` where NUM is whole number (integer)
Suggestion:` scale()` will support `[-NUM, NUM]` and `[-%, %]`
Example: 
`transform: scale(120%)` will work same as `transform:scale(1.2)` is working right now.

It is not a game-breaker but it is nice to have.

Thank you for your work.

**Comment by AmeliaBR** [comment]
Agree this is a nice to have, would be more intuitive for many authors (`scale(50%)` instead of `scale(0.5)`, `scale(150%)` instead of `scale(1.5)`). The impact on implementations would be restricted to parsing time — computed/serialized values would remain numbers.

It's very similar to the change in alpha values to support percentages, which the WG re-affirmed in #3342 after browser teams emphasized their plan to ship.

**Comment by birtles** [comment]
Presumably this should also apply to the [individual scale property](https://drafts.csswg.org/css-transforms-2/#propdef-scale) (and not just the `scale()` function).

**Comment by Crissov** [comment]
A convenient way, e.g. a keyword, to scale by √2 ≈ 1.414 or √½ ≈ 0.707 (as in ISO paper and pens) might also be nice.

**Comment by tabatkins** [comment]
Yes, now that `sqrt()` exists, that case is well handled.

**Comment by BorisChiou** [comment]
> Presumably this should also apply to the [individual scale property](https://drafts.csswg.org/css-transforms-2/#propdef-scale) (and not just the `scale()` function).

Agree, and Gecko just landed it (based on the spec PR).
