### ISSUE TITLE
[css-values] minimum nested pairs of parentheses in calc to 32

### ISSUE THREAD

**Issue by TalbotG** [w3c/csswg-drafts#3462]
[calc-errors.html test at line 68](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/css3/calc/calc-errors.html#L68)

At line 68 of the test above, there is a calc() function with 128 nested parentheses. Firefox is able to support 128 pairs of nested parentheses. Blink supports 32 nested pairs of parentheses and then fails when trying 33 nested pairs of parentheses:

[trac-webkit-calc-errors.html with 33 nested pairs of parentheses](http://www.gtalbot.org/BrowserBugsSection/CSS3Values/trac-webkit-calc-errors.html)

128 nested pairs of parentheses seems outrageously extreme but there seems nothing in the CSS3 spec and CSS4 spec that indicate ceiling limit for nested parentheses.

**Proposal: CSS4 spec explicitly state a limit (ceiling) of support to 32 nested pairs of parentheses in calc() function.**

Then the test calc-errors.html should be adjusted accordingly before submitted to wpt.

**Comment by TalbotG** [comment]
Same issue in this

[calc-errors.html test at line 59](https://chromium.googlesource.com/chromium/src/+/c825d655f6aaf73484f9d56e9012793f5b9668cc/third_party/WebKit/LayoutTests/css3/calc/calc-errors.html#59)

**Comment by emilio** [comment]
Why? And why only on calc() and not on other (all?) CSS blocks?

**Comment by TalbotG** [comment]
There ought to be a reasonable ceiling limit to everything. 32 seems to me very reasonable.
Right now, Blink supports 32 but not 33 nested parentheses; Firefox supports 128.

> and not on other (all?) CSS blocks?
Which other CSS blocks? I'm not sure I understand.

**Comment by ewilligers** [comment]
Another example is CSS Selectors 4 `:is(:not(...))`

When the spec has no limits, implementations are forced to make their own choices between
- having well known and ignored stack overflow crashes, e.g. on fuzzer-generated input. The smallest example that crashes can change when moving to a different compiler version or when adding an unrelated feature.
- not using their implementation language's support for recursion, complicating their code and increasing the development cost of future features.
- choosing their own limits and making an intentional choice to fail any WPTs that go further.

**Comment by TalbotG** [comment]
Right now, Firefox fails 
[calc-errors.html test](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/css3/calc/calc-errors.html)
only because it supports much more than 32 nested parentheses; it supports 128 nested parentheses. 

If we can not reach an agreement on a ceiling limit value on calc nested parentheses, the very least minimum to do will be to adjust such test.

**Comment by emilio** [comment]
That test is a WebKit-internal test, I don't see why Firefox would need to pass it.

**Comment by tabatkins** [comment]
CSS has never introduced actual maximums for anything. We have a few places where we've defined minimums that must be supported (with the implication that going over is implementation-defined and allowed to fail, in a particular spec-defined fashion).

@fantasai and I have tried to introduce such limits for all the numeric values, but haven't succeeded yet. :(

I'm happy to similarly define a nesting limit here. Presumably a separate nesting limit for rules vs values, since they're generally parsed in different phases?

> When the spec has no limits, implementations are forced to make their own choices between [snip]

Crashing is never a reasonable behavior. ^_^

**Comment by TalbotG** [comment]
> That test is a WebKit-internal test, I don't see why Firefox would need to pass it.

I will be submitting that test - most likely modified a bit - to WPT repository soon (say, within 6 weeks). So the test has to be modified somehow so that Firefox is not unfairly penalized (and does not fail) just because it supports 128 nested calc parentheses.

**Comment by Loirooriol** [comment]
> I'm happy to similarly define a maximum required nesting limit here

@tabatkins Did you mean *minimum*? Otherwise, why add this inconsistency if minimums are used everywhere else?

**Comment by fantasai** [comment]
I would agree with setting a minimum, but not a maximum, in the spec.

As for the test, it could be written with as many parentheses as needed to pass in all known implementations, and also include a comment to the effect that if your UA is failing because you support more, then ask the test to be adjusted. It might also be worth separating out that test into its own file.

**Comment by TalbotG** [comment]
> As for the test, it could be written with as many parentheses as needed to pass in all known implementations

I will eventually adjust that sub-test so that only 32 nested parentheses  are used. 
I am leaving this issue opened until this is done.

**Comment by tabatkins** [comment]
Sorry, yes, that's what I meant. Must support up to X degree of nesting; *can* support more but are not required to; *must* fail in a particular standardized way when the limit is exceeded.

**Comment by TalbotG** [comment]
> I will be submitting that test - most likely modified a bit - to WPT repository soon (say, within 6 weeks). (...)
I will eventually adjust that sub-test so that only 32 nested parentheses are used.

Following-up on the above.
I am no longer involved into submitting that test. @frivoal is:
[webkit-css-values-tests](https://github.com/frivoal/webkit-css-values-tests)

I think that 128 pairs of nested parentheses inside a calc() function in that test should be reduced to 32 pairs. Note that there was already a test from @FremyCompany that was testing 24 pairs of nested parentheses inside a calc() function:
 [calc-parenthesis-stack.html](https://web-platform-tests.live/css/css-values/calc-parenthesis-stack.html)

**Comment by TalbotG** [comment]
> It might also be worth separating out that test into its own file.

Then François Remy's [calc-parenthesis-stack.html](https://web-platform-tests.live/css/css-values/calc-parenthesis-stack.html) test could or would suffice.

**Comment by ExE-Boss** [comment]
I believe that CSS implementations should support a&nbsp;minimum of&nbsp;32 nested parentheses.

**Comment by frivoal** [comment]
agenda+ to confirm https://github.com/w3c/csswg-drafts/issues/3462#issuecomment-465492548

**Comment by AmeliaBR** [comment]
The [current spec in CSS Values](https://drafts.csswg.org/css-values/#calc-syntax) is

> UAs must support math function expressions of at least **20 terms**, where each NUMBER, DIMENSION, or PERCENTAGE is a term. If a math function contains more than the supported number of terms, it must be treated as if it were invalid.  _(emphasis added)_

Perhaps the 32 nested operations is a real-world limit from a particular browser engine?

**Comment by FremyCompany** [comment]
Just reviewed the test, and we might also want to make clear whether the parentheses for `calc()` itself are included in the `32` requirement or not. If they are not, we should update the proposed test to have one more nesting level, I believe.

**Comment by tabatkins** [comment]
@AmeliaBR Right, but that doesn't restrict the number of parens you have to be able to handle; you could have a single "term" wrapped in a hundred paren pairs and not violate that support requirement. ^_^

Tho I suppose there's no reason to mandate at least 32 nesting levels and mandate less than 32 *terms*, since the only reason to add parens is to separate terms. We should probably bump the minimum terms requirement to 32 as well, then.

I think I also need to rewrite that requirement a bit, as it's implicitly (and vaguely) referring to tokens; as stated, an expression containing a single `1` and a thousand `attr(foo px)` terms would be required to be supported.

**Comment by TalbotG** [comment]
@frivoal 
Florian, You now need to remove [lines 76 and 77 from calc-errors.html](https://github.com/frivoal/webkit-css-values-tests/blob/master/calc-errors.html#L76) before submitting that test. You will also need to remove [lines 72 and 73 from calc-errors-ref.html](https://github.com/frivoal/webkit-css-values-tests/blob/master/calc-errors-ref.html#L72) .

Someone (it could be you, Florian) will need to approve [pull request 16170](https://github.com/web-platform-tests/wpt/pull/16170) now that this issue has been settled. [Pull request 16170](https://github.com/web-platform-tests/wpt/pull/16170) involves a specific, dedicated test on a calc() with 32 pairs of parentheses.

**Comment by frivoal** [comment]
> Florian, You now need to remove lines 76 and 77 from calc-errors.html before submitting that test. You will also need to remove lines 72 and 73 from calc-errors-ref.html.

done.
