### ISSUE TITLE
[css-grid] Interpolate repeat()

### ISSUE THREAD

**Issue by BorisChiou** [w3c/csswg-drafts#3503]
We have a discussion about interpolating track listings (#3201), but the current spec doesn't have clear definition of how to interpolate `repeat()`. (Or maybe I misread it. Please feel free to close it if there is a duplicated issue or they are well-defined already.)

Example 1:
```
repeat(2, 2fr 30px)
repeat(2, 3fr 40px)
```
They use the same repeat count, so doing interpolation between them is ok to me.

Example 2:
```
repeat(2, 2fr 30px)
repeat(4, 40px)
```
Their resolved/expanded track lists have the same length, so people may think they are animatable. However, we do interpolation by computed values, so it seems we shouldn't expand the list during interpolation, which means they are not animatable? I'm not sure which behavior is expected.

Example 3:
```
repeat(auto-fill, 10px)
repeat(auto-fill, 20px)
```
Even if the keyword is the same it can result in different number of tracks. For both auto-fit/fill, the number of columns isn't known until you do layout since it depends on the container size, item placement and other factors. Therefore, we fallback to discrete in this case. Right?

Thanks.
cc @MatsPalmgren @birtles

**Comment by BorisChiou** [comment]
I will add some test cases to wpt by [Firefox Bug 1348519](https://bugzilla.mozilla.org/show_bug.cgi?id=1348519.) Please feel free to update them.

**Comment by tabatkins** [comment]
Yup, this is unspecified and should be fixed. My intuitions:

> ```
> repeat(2, 2fr 30px)
> repeat(2, 3fr 40px)
> ```

This should definitely interpolate. Same N, contained track list is same length and item-wise interpolable, everything's A-OK.

> ```
> repeat(2, 2fr 30px)
> repeat(4, 40px)
> ```

I could go either way. Fine with this being interpolable in theory (same lengths *once expanded*, expanded track list is item-wise interpolable), but I'd also be fine being simple here and saying no if it would cause implementation difficulties. I'm generally in favor of keeping interpolation simple and obvious if possible, which leans me toward saying "no", and requiring authors to write the second as `repeat(2, 40px 40px)` if they want it to interpolate.

> ```
> repeat(auto-fill, 10px)
> repeat(auto-fill, 20px)
> ```

I think these should interpolate, going from `10px` to `20px`. Yes, the number of tracks can change, but I think that's fine? Track-number determination doesn't happen until used-value time, so interpolation doesn't need to care about it. Leaning on my "should be simple and obvious", these definitely *look like* they're compatible with each other.

-----

So all in all, the rule I lean towards is "first argument must be identical, second argument must be interpolable as a computed track list; else discrete". So that's yes on Example 1, no on Example 2, and yes on Example 3.

**Comment by MatsPalmgren** [comment]
How about:
```
repeat(2, 2fr 30px)
repeat(4, 40px 40px)
```
 and
```
repeat(auto-fill, 10px)
repeat(auto-fit, 20px)
```

It might be convenient to authors if we could treat the first argument to `repeat()` as just another component that is animatable if the 2nd argument has the same length. My first example would then animate as `repeat(2, ...)` `repeat(3, ...)` `repeat(4, ...)`.   My second example would animate the first argument discretely while still animating `10px` -> `20px` as a `<length>`. (`<integer>` -> `auto-fill/fit` would also be discrete)

**Comment by tabatkins** [comment]
Hm. My first instinct is to say no to both, and require an exact match on the first arg. 

But that's not actually a very consistent position; if I'm fine with `repeat(auto-fill, 20px)` => `repeat(auto-fill, 10px)`, which at used-value time (if we pretend a 40px container) is equivalent to `repeat(2, 20px)` => `repeat(4, 10px)`, then I should be fine with that 2=4 transition directly.

So I think I agree. We can do either of the following:

* require that the first arg is a number, and identical between start/end; different values, or keyword values, both go discrete
* allow any values for the first arg: if they've the same value they transition by doing nothing; if they're different numbers they transition as integers; otherwise the whole function transitions discretely

**Comment by fantasai** [comment]
Alright, fixed in https://github.com/w3c/csswg-drafts/commit/2e57e1ebf31677ce7d7b70ad8012455c455490ae ! @MatsPalmgren @BorisChiou Let us know if the edits seem satisfactory.

**Comment by BorisChiou** [comment]
Thanks for this. :)

**Comment by birtles** [comment]
It would be nice if we didn't refer to interpolation but combination so that it covers addition and accumulation too.

**Comment by fantasai** [comment]
@birtles Done.

**Comment by birtles** [comment]
Thank you @fantasai!
