### ISSUE TITLE
[css-writing-modes] Clarify the baseline value during the top-to-bottom writing mode for Latin text

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/csswg-drafts#3505]
Moved from https://github.com/w3c/svgwg/issues/619

https://www.w3.org/TR/SVG/text.html#WritingModeProperty
https://www.w3.org/TR/css-writing-modes-3/#vertical-modes

It's probably *CSS Writing Modes Level 3* related. I'm not sure. For now, I'm experiencing the problem during the SVG 1.1 rendering, but I'm sure that this can be reproduced in HTML too (I'm not familiar with it). 

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" font-family="Arial" font-size="64">
    <path id="crosshair" d="M 20 100 L 180 100 M 100 20 L 100 180" stroke="gray" stroke-width="0.5"/>
    <text id="text1" x="120" y="30" writing-mode="tb">Text</text>
    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```

![a-writing-mode-006](https://user-images.githubusercontent.com/725494/50243414-d2bc8b80-03d5-11e9-9ea6-69caaf551bc9.png)

As you can see, the text has a different baseline(?). Which one is the correct one? Is this explained somewhere?

**Comment by fantasai** [comment]
Those should not be differing by implementation...
Is there a difference between implementations if you don't have writing-mode specified?

**Comment by fantasai** [comment]
The SVG specs are very vague as to what should be happening here, but I think what they're *supposed* to say is that the alphabetic baseline (a metric defined in the font file itself) is aligned to the alignment point you're specifying in the x and y attributes. In a correctly-developed font, that point will coincide exactly with the bottom of the capital T and lowercase x, and be slightly above the bottom of the lowercase e (due to optical alignment effects). Afaict, all those renderings are a bit off: that point should coincide exactly with the middle of the gray stroke.

Variant of this testcase using Ahem:

http://software.hixie.ch/utilities/js/live-dom-viewer/?<svg%20viewBox%3D"0%200%20200%20200"%20xmlns%3D"http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg"%20font-family%3D"Arial"%20font-size%3D"64">%0A%20%20%20%20<path%20id%3D"crosshair"%20d%3D"M%2020%20100%20L%20180%20100%20M%20100%2020%20L%20100%20180"%20stroke%3D"gray"%20stroke-width%3D"0.5"%2F>%0A%20%20%20%20<text%20id%3D"text1"%20x%3D"120"%20y%3D"30"%20writing-mode%3D"tb"%20font-family%3D"Ahem">Épx<%2Ftext>%0A%20%20%20%20<rect%20id%3D"frame"%20x%3D"1"%20y%3D"1"%20width%3D"198"%20height%3D"198"%20fill%3D"none"%20stroke%3D"black"%2F>%0A<%2Fsvg>

I think what needs to happen here is importing the testcase into WPT and filing bugs against all browsers. :( But thanks for the example and testcase!

**Comment by fantasai** [comment]
Filed https://github.com/w3c/svgwg/issues/629 against the SVG spec. I think for Writing Modes there is nothing to be done here.
