### ISSUE TITLE
[css-shadow-parts] Dynamic *exportparts=*

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3509]
(Split from issue #3467, reported by @stefsullrew)

Would it be possible to dynamically set the value of `exportparts=`?
The below example show some pseudo-code to illustrate the question.

```
<x-foo>
    <h1>Component headline</h1>
    
    <template for:each={items} for:item="item" for:index="idx">
        <x-item exportparts="item-header: foo-item-header-{idx}"></x-item>
    </template>
</x-foo>
```

**Comment by fergald** [comment]
@stefsullrew If you had a template system like the above, I don't see why it wouldn't work for exportparts but this seems more like a request for a template system than a feature for ::part, unless I have missed something. E.g. https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md

**Comment by fergald** [comment]
I'm closing this issue because I think what you want is already supported, at least from the ::part side of things. There's no native templating in HTML yet but exportparts="item-header: foo-item-header-{idx}" should work fine right now with any of the existing template engines.

Please reopen if I have misunderstood the request.
