### ISSUE TITLE
[css-logical] Should the `inset` shorthand allow quirks in their lengths like the individual properties do?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3525]
I'd prefer if not, but the current spec doesn't say. In quirks mode, some (non-zero) lengths don't require units, so for example `<div style="position: relative; top: 100">` works.

I'd prefer if we didn't have to do this for `inset`, given it's a new property, and that the `inset-` longhands don't allow this looks like.

**Comment by SelenIT** [comment]
I believe the unitless length quirk is applied only to properties [explicitly listed](https://quirks.spec.whatwg.org/#the-unitless-length-quirk) in the Quirks Mode Living Standard, isn't it?

**Comment by emilio** [comment]
Yes, though the definition of the inset property use `<'top'>`.

**Comment by emilio** [comment]
Also the Blink implementation (though not shipped) supports this: `data:text/html,<div style="position: relative; inset: 100 0 0 0">Foo`.

So not sure whether the spec needs fixing and/or whether Blink needs a bug on file.

**Comment by Loirooriol** [comment]
Ah, I overlooked this. Blink allows the quirk, because the easy way to parse the shorthand was using the longhands.

I don't have a strong opinion, if `inset` remains a shorthand of only the physical properties it may make some sense to allow the quirk in order to have a consistent syntax. But if it's going to become a shorthand of both logical or physical longhands [like fantasai wants](https://github.com/w3c/csswg-drafts/issues/2988#issuecomment-417017014), then I wouldn't allow it.

**Comment by Loirooriol** [comment]
@tabatkins [was against spreading the quirk any further](https://github.com/w3c/csswg-drafts/issues/2928#issuecomment-405397656) (but I was asking about logical longhands).

**Comment by emilio** [comment]
I agree with tab on that. I'd prefer to keep the quirks where we know it's needed. In this case it's clearly not needed, since the property is new.

**Comment by emilio** [comment]
I think we can close this unless anybody thinks the spec needs more clarification. Feel free to reopen if so. @ericwilligers added wpt tests for this (thanks!).

**Comment by ewilligers** [comment]
Blink is [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=924691).

**Comment by Loirooriol** [comment]
WebKit is also [fixed](https://bugs.webkit.org/show_bug.cgi?id=193773).
