### ISSUE TITLE
[cssom][css-conditional] CSSGroupingRule interface is duplicated

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#3528]
The CSSGroupingRule interface is defined in two specs:
https://drafts.csswg.org/cssom/#the-cssgroupingrule-interface
https://drafts.csswg.org/css-conditional/#the-cssgroupingrule-interface

They are not identical, but the one in CSSOM looks like the one to keep.

**Comment by jugglinmike** [comment]
Just stumbled over this myself.

As @foolip mentioned, there are a few discrepancies between the two. In particular, CSSOM defines an `insertRule` method whose second argument is optional, while CSS Conditional Rules' version of the method requires the second argument. 

This seems to be a source of confusion since Chromium requires the argument, but Firefox and WebKit do not:

    <style id="s"></style>
    <script>
    s.sheet.insertRule('@media all {}');
    s.sheet.cssRules[0].insertRule('* {}'); // throws in Chromium only
    </script>

For what it's worth, an optional argument is more consistent with [the `insertRule` method of `CSSStyleSheet`](https://drafts.csswg.org/cssom-1/#cssstylesheet).

**Comment by jugglinmike** [comment]
We resolved this issue via gh-4029 though I don't have the permissions to close it.
