### ISSUE TITLE
[css-pseudo-4] Mark unimplemented CSSPseudoElement features at-risk

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3540]
Gecko is implementing parts of the CSSPseudoElement interface to integrate with Web Animations, so those parts should stay. If there aren't strong use cases for other parts, we should either drop them (if we're not sure of the design) or mark them at-risk (if we're sure they're correctly designed, but not sure if they're needed).

**Comment by fantasai** [comment]
If nobody implements or plans to implement or is seriously advocating for the CSSStyleDeclaration style attribute, then I'd like to remove it. Otherwise I think we've stripped this down to the minimum at this point... @birtles any comment?

**Comment by fantasai** [comment]
See also https://github.com/w3c/csswg-drafts/issues/3607

**Comment by fantasai** [comment]
And https://github.com/w3c/csswg-drafts/issues/3603 (related to the last comment)

**Comment by birtles** [comment]
We don't have any specific plans at this point to implement any more than:
```idl
[Exposed=Window]
interface CSSPseudoElement {
    readonly attribute CSSOMString type;
    readonly attribute Element element;
};
```

Furthermore, for `type` we only support `::before` and `::after`. We don't implement `Element.pseudo()` either or have any specific plans to do so but it might be worth doing just to clarify the identity issues @heycam raised since they probably affect what we currently return.

(In our implementation the only way to get a `CSSPseudoElement` is to create a CSS animation / transition on a pseudo, then call `getAnimations()` and fetch the `effect.target` of the returned `CSSAnimation` or `CSSTransition`.)
