### ISSUE TITLE
[css-pseudo-4] Decide between Element.pseudo(type) and window.getPseudoElements(elem,type)

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3541]
See https://lists.w3.org/Archives/Public/www-style/2014Nov/0035.html
> Similarly, CSSOM defines Element.pseudo(type) while CSS Pseudo-Elements defines Window.getPseudoElements(elem, type) for what seems to be the same purpose. [Also, I notice that Window.getPseudoElements() takes a  type, then returns a list that can be filtered by type which seems odd to me.]

I don't know what the pros and cons of each style of interface is, and I couldn't find any discussion about it in the archives, so I think we still need to decide? Also if we're going with the latter, that parenthetical needs to be addressed.

**Comment by fantasai** [comment]
Any informed opinions @tabatkins @dbaron ? Because I have no idea.

**Comment by heycam** [comment]
FWIW the `PseudoElement` interface and `Element.pseudo()` function have already been removed from the CSSOM spec.  I feel like a function on `Element` rather than on `Window` is more ergonomic, but I also think it will be more common to want to get a specific pseudo rather than a list of all the pseudos that are available on the element, so maybe an API like this would be better:

```webidl
partial interface Element {
    CSSPseudoElement? pseudo(CSSOMString type);
};
```

The old `PseudoElement` interface did not allow writable access to the inline style for the pseudo.  The `CSSPseudoElement` interface does.  Though the `style` member on `CSSPseudoElement` now should probably be replaced with:

```webidl
CSSPseudoElement includes ElementCSSInlineStyle;
```

(And then perhaps `ElementCSSInlineStyle` should be renamed to `CSSInlineStyle`, since it would no longer be used just for elements.)

**Comment by fantasai** [comment]
@heycam Can I get your review on this https://drafts.csswg.org/css-pseudo-4/#cssom ? If it ever actually regenerates...

Also, lmk if I should delete all the issues left in this section of the draft yet? Given Mozilla is implementing, we should probably be a little more confident about what we're doing here, I think.

**Comment by heycam** [comment]
We need some wording about the identity of the object returned by `pseudo()`, for example whether it's required to be the same object each time you call it on an element with a given type.

Now that I think about it, if we do require that the same object is returned, what does it mean for the `CSSPseudoElement` object if we restyle the element and the pseudo goes away (and so `null` would be returned from another call to `pseudo()`)?  Is the `CSSPseudoElement` detached in some way?  If we restyle again and the pseudo-element is recreated, does the old `CSSPseudoElement` remain functional?  Might it be simpler to always return an object for a supported pseudo type, regardless of whether the pseudo currently exists?

I wonder if we should leave `::selection` off this list.  It feels like a pretty different thing from `::before`, `::after`, `::first-letter`, and `::first-line`, all of which basically have a box corresponding to them (at least for Gecko).  Or would it be allowed to return a `CSSPseudoElement` for `::selection` but not to support e.g. Web Animations targeting it?

The sentence

> The EventTarget interface [DOM-LEVEL-2-EVENTS] must be implemented by all instances of CSSPseudoElement as a conformance requirement of this module.

is redundant with the `CSSPseudoElement implements EventTarget;` line in the IDL, so we probably don't need it.

If the answer to #3540 is to remove `.style`, then yes I think all the issues in this section can be removed.  If no, then we should do what that issue says, and make the rules in there cascade normally.  (For the purposes of getting what we need for Web Animations targeting we don't need `.style`, but I'll let @birtles reply definitively in the other issue.)

Otherwise the change looks good to me, thanks.

**Comment by fantasai** [comment]
Split off your first two issues into https://github.com/w3c/csswg-drafts/issues/3607 (Identity of Element.pseudo()) and https://github.com/w3c/csswg-drafts/issues/3540; fixed the cascade issue and removed the redundant sentence.

**Comment by fantasai** [comment]
Thanks for the review~
