### ISSUE TITLE
[css-scoping] Please bring back scoped styles

### ISSUE THREAD

**Issue by o-t-w** [w3c/csswg-drafts#3547]
The scoped style tag HTML attribute works really well with popular frameworks and is far simpler to use than shadow DOM.

e.g. in React: 
```
import React from 'react';

const Profilecard = (props) => {
	
	const styles = `
	div {background-color: ${props.bgColor}}
	h2 { color: white; }
	img  { 
		border-radius: 50%;
		height: 80px;
		width: 80px;
	}`

	return (
		<div className="card">
			<style scoped>{styles}</style>
				<h2>{props.name}</h2>
				<img src="man3.jpg" alt=""/>
			</div>
	);
};

export default Profilecard;
```
Shadow DOM offer more encapsulation than scoped styles, but this level of encapsulation is not often needed, and even sometimes complained about by developers.

e.g. [Chris Coyier](https://css-tricks.com/regarding-css-global-scope/): 

> Personally, I wish it was possible to make the shadow DOM one-way permeable: styles can leak in, but styles defined inside can't leak out.

It is important to note that both [Vue js](https://vuejs.org/v2/guide/single-file-components.html) and [Svelte](https://svelte.technology/blog/the-zen-of-just-writing-css) have replicated this API - it is clearly an API that is both easy to work with and gives the _right level_ of encapsulation (unlike shadow DOM, which is useful for more niche cases).

At the moment people are using many different solutions ([CSS Modules](https://css-tricks.com/css-modules-part-1-need/), Styled Components and all the other CSS-in-JS options). It would be great if there was a standardized way to solve the problem of scoping rather than the very fragmented options in user-land. I strongly doubt that shadow DOM will prove to be a popular solution capable of attracting people away from these libraries.  

A prior discussion about the topic can be found here: https://github.com/w3c/csswg-drafts/issues/137

**Comment by tomhodgins** [comment]
I would love something like this. I've been experimenting with a custom HTML tag I call `<style-container>` that acts as a container for scoping CSS styles, and I'm also exploring the idea of interpreting contained media queries as container queries based off the `<style-container>` tag's dimensions, here's how I'm working with it:

```html
<style-container>

  <div>Make me 500+ px wide</div>

  <style media=none>
    div {
      border: 1px solid;
      padding: 1em;
    }
    @media (min-width: 500px) {
      div {
        background: lime;
      }
    }
  </style>

</style-container>

<script type=module>
  import styleContainer from 'https://unpkg.com/style-container'

  styleContainer()
</script>
```

- A version you can play around with: https://codepen.io/tomhodgins/pen/NoPNGY
- the source code of the plugin is here: https://github.com/tomhodgins/style-container/blob/master/index.js

From what I can see there are two main benefits:

1. Having something like this would be good for modularizing code - you could safely include stylesheets in certain HTML elements and be sure they weren't going to apply to other elements.

2. Another potential benefit — is it possible that interpreting media queries as based on the containing element's dimensions could be a way that existing CSS written with media queries can be re-used for modular responsive styles without having to refactor existing styles or introducing new syntax?

**Comment by AmeliaBR** [comment]
I think we need to separate the discussion of scoped styles as a concept from the specifics of the `scoped` attribute on a `<style>` element.  There are other syntaxes that could be used (an @-rule, maybe?) that could serve the same goal with different side effects and fallback behavior.

> If memory serves me, it was the vendors that pushed back on the spec initially. Maybe we need to revisit their concerns and see what can be done to mitigate them as a start?

I fully support this strategy.

Can anyone outline specifically why decisions were made to not implement the `scoped` attribute? For me, the major issue was progressive enhancement.  I couldn't accept the fallback behavior to be the scoped styles applying to the entire document—although this is really only an issue when the scoped styles are in the markup, since you can always test for attribute support in JS.

But maybe there were other reasons from a browser performance perspective?

I'd like to think that by rolling this back to the underlying needs and concerns, we can come up with a different syntax that addresses the needs without the same concerns.

**Comment by prlbr** [comment]
The already existing effort to implement it in Blink was actually removed because developers found it to be too complicated to develop `scoped` and ShadowDom in parallel. Developers said this would not be a final nail in the coffin of `scoped` and that it could be implemented later (e.g. internally based on ShadowDom?). See https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/JB8nFQXhAuQ

Edge didn’t implement it for whatever reason, but this does not seem relevant anymore since Microsoft ditched its effort to develop an own browser engine altogether.

Firefox on the other hand did implement `scoped`. They removed it mainly because it was removed from the specs when after other browser engine vendors did not implement it. https://groups.google.com/forum/#!topic/mozilla.dev.platform/iBoROFkR9V8

**Comment by SelenIT** [comment]
Interestingly, per the current [CSS Cascading Level 4](https://drafts.csswg.org/css-cascade-4/#cascade-scope) spec,

> Normal declarations from style attributes are considered to be scoped to the element with the attribute

Doesn't this imply that, once [CSS Nesting](https://tabatkins.github.io/specs/css-nesting/) makes it into standard, it would be possible to write element-scoped styles as nested selectors inside the `style` attribute?

**Comment by Heydon** [comment]
+1 to scoped styling making a return.

Here's how I see it:

1. Most of the time I want access to global / parent styles for my components. 
2. If I _don't_ want that, I have the `all` property to unset stuff anyway.
3. What I _don't_ have is the ability to simply scope, as the spec' once promised, any component specific styles

Shadow DOM really does not help, because it creates an _arbitrary_ barrier (except for custom properties, but that's not actually enough; values only, not declarations and no mixin support).

**Comment by Heydon** [comment]
> Svelte, Vue, Angular but also styled-jsx (React) instead scope the styles to a single component to simulate ShadowDOM.

This does not simulate Shadow DOM. Shadow DOM prevents inheritance. The Vue behaviour (they actually emulate `<style scoped>` exactly) is more desirable than Shadow DOM.

**Comment by giuseppeg** [comment]
Shadow DOM doesn't prevent inheritance (it used to in v1). eg. `color` crosses the SD boundaries https://jsfiddle.net/6ntd0cgw/

**Comment by o-t-w** [comment]
To be clear: shadow DOM does _not_ prevent inheritance, but it does prevent global selectors `*`, `p`, etc from affecting the component. Therefor Svelte, Vue, Angular and styled-jsx are far more comparable to the scoped attribute than to shadow DOM. As Heydon said, Vue _explicitly_ emulates `<style scoped>`

**Comment by giuseppeg** [comment]
> it does prevent global selectors *, p, etc from affecting the component

true 

> Therefor Svelte, Vue, Angular and styled-jsx are far more comparable to the scoped attribute than to shadow DOM. As Heydon said, Vue explicitly emulates <style scoped>

Not 100% sure about Vue (I think I checked once about it) and Angular but Svelte and styled-jsx act more like Shadow DOM. I am the co-author of styled-jsx and convinced Rich Harris (Svelte's author) to switch from emulating `<style scoped>` to behave like styled-jsx.

**Comment by giuseppeg** [comment]
update Vue also works like Svelte and styled-jsx https://codesandbox.io/s/ko4kp4nq5r https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles 

Anyway this thread is not about frameworks I guess :) `<style scope>` affects the entire subtree and technically who wants to emulate this behavior could just use a unique id to scope styles to a subtree. 

Eventually I don't mind if this makes it to the spec again but I don't think it is a proper solution the the lack of encapsulation in lite DOM.

**Comment by keithjgrant** [comment]
> The reason why the `scoped` attribute idea was abandoned is that, in contrast to ShadowDOM, it didn't come with any lower boundary. This means that styles affect an entire subtree rather than a single "component". In fact this is not different from prefixing every selector with a unique id eg. `.foo { }` becomes `#scope-unique-id .foo {}`.

I don’t think this is accurate. When scope was in the spec, it was defined such that inner scopes overrode outer scopes, regardless of selector specificity.

For example, given:

```css
/* in one scope */
.foo {
  color: blue;
}

/* in another scope */
.bar {
  color: red;
}
```

A `foo` inside a `bar` would be blue, and a `bar` inside a `foo` would be red. Which addresses *precisely* the problem CSS-in-JS seeks to solve, and would be hugely beneficial.

I also thought the final version of the spec, which relied on a `@scope` at-rule rather than an html attribute was much better. ([Here’s my write-up on that](https://keithjgrant.com/posts/2016/06/save-scoped-css/))

**Comment by keithjgrant** [comment]
Ah, yes. I see what you’re saying. I think you’re right.

The question of styles “leaking in” is an interesting one. Because I think in most cases, there are some style you would want to leak in, and others you wouldn’t.

Stepping back a bit, I think what I/we **really** want here is a first-class way to distinguish between base styles and “module” styles. Then you could define a bunch of base styles for the page (font family, color, default margins, etc.); these you would want to “leak in” to everything, as your default baseline. Then, on top of that, a way to define modular styles (module A has a blue heading, and some larger margins, module B has these borders, etc.); these you would want to scope only to their respective modules, and not leak in or out.

**Comment by fantasai** [comment]
CSS Scoped Style spec (@scope): https://www.w3.org/TR/2014/WD-css-scoping-1-20140403/#scope
Cascade rules for it: https://www.w3.org/TR/2018/CR-css-cascade-4-20180828/#cascading

**Comment by Heydon** [comment]
> To be clear: shadow DOM does not prevent inheritance, but it does prevent global selectors *, p, etc from affecting the component. Therefor Svelte, Vue, Angular and styled-jsx are far more comparable to the scoped attribute than to shadow DOM. As Heydon said, Vue explicitly emulates `<style scoped>`

This is correct, I think (largely? Depends on the kind of properties?) But that makes it even worse, because it's so particular about what works and what doesn't. And when would you ever want to _just_ inherit, but not have access the global styles? Who thinks and works like that?

**Comment by Heydon** [comment]
> CSS Scoped Style spec proposal (@scope): https://www.w3.org/TR/2014/WD-css-scoping-1-20140403/#scope

@fantasai This looks good/interesting. To be clear, is this a new proposal you recently wrote? 

One concern is the limitation of using selector identifiers. Would this preclude from doing...

```html
<custom-element>
   <div></div>
   <style scoped>
       div {
           max-width: 60ch;
       }
   </style>
</custom-element>
```

... where `max-width: 60ch` refers to just this instance of `<custom-element>`?

Sorry if I have understood it poorly.

**Comment by fantasai** [comment]
@Heydon It's a proposal that was put together many years ago. It was dropped because nobody seemed to be interested in it. Work continued on Web Components, and the scoped style proposals were deleted from the specs.

Wrt your example, doing exactly that would require bringing back HTML scoped styles, which is a different syntax for triggering the same behavior as @scope. In either case, you're binding some styles to a scoping root: the HTML syntax implies that relationship by placing the <style> element inside the scoping root, and the CSS syntax uses a selector. (The downside to the HTML approach is that you have to inject the style sheet into the markup. Which maybe isn't too bad if you only have one instance, but it can be pretty repetitive if you have multiple instances with the same styles!) If you wanted to tie some @scope'd CSS rules to a particular instance of custom-element, it's possible: you could do it with an ID selector, for example. @scope binds to whichever elements are selected by the @scope, and if you somehow manage to select only that custom-element instance (whether using ID selectors or some other method that happens to select only that one element) then it only binds to that instance.

**Comment by giuseppeg** [comment]
> Yes: inheritance; no: global styles? When would you ever want to just inherit, but not have access to the global styles?

@Heydon good question! My take on this is that if you don't have global styles then probably inheritance should be opt-in too (as opposed to opt-out / status quo). 

> Who thinks and works like that?

I have spoken with many supporters of styles in JavaScript and apparently they all do this (CSS Modules folks included). I guess they adopt a different strategy to avoid repetition: instead of using global and cascading styles they build up isolated components and reuse those instead. When it is time to tweak styles they then use custom properties or (in JavaScript) "context" by making explicit subscriptions so that they control what is affected by those changes.

FWIW this proposal by Nicole Sullivan sounded interesting to me https://mobile.twitter.com/stubbornella/status/1076144685867982849

@keithjgrant The other day I was playing with another idea https://mobile.twitter.com/giuseppegurgone/status/1089633480458358785 but I am not sure how feasible it is without a way to mark DOM boundaries for the scope. This would be just an addition not a replacement of CSS.

**Comment by SelenIT** [comment]
@fantasai, so does my [assumption](3547#issuecomment-458088313) that the rules for the `@scope`d styles could possibly apply also to `@nest`ed selectors inside the `style` attribute (since the declarations from the style attribute are considered element-scoped) make sense or not?

**Comment by Heydon** [comment]
@fantasai Thank you for the clarification! Some reflections:

> The downside to the HTML approach is that you have to inject the style sheet into the markup. Which maybe isn't too bad if you only have one instance, but it can be pretty repetitive if you have multiple instances with the same styles!

My understanding is that this would be less repetitive than when writing CSS into a shadowRoot. Why? Because you can still draw upon already set global styles. Currently, when I write a custom element, the only easy way to use styles specific to an _instance_ of that element is through Shadow DOM. And once I start using Shadow DOM, I have to play with its rules — including not being able to use global style rules.

**Comment by valtlai** [comment]
> I couldn't accept the fallback behavior to be the scoped styles applying to the entire document

We could use `type="scoped"` (similar to `<script type="module">`).

**Comment by keithjgrant** [comment]
Is there a reason to prefer the HTML attribute approach over a `@scope` rule in CSS? The latter seems to me to reduce code duplication and prevent poor fallback behavior.

**Comment by BrentARitchie** [comment]
@keithjgrant That is a good question. Using the @scope rule would address some of the backwards compatibility and allow us more time to discuss the html attribute syntax.

```css
body {
    background-color: red;
  }

@scope html {
  body {
    background-color: blue;
  }
}
```

The rule as written would give us a blue body background if the ```@scope``` rule is followed, but be coloured red if the rule isn't understood. Whereas, the scoped html attribute would simply act like an inline css declaration and make the body red anyways in all cases.

I think the ```@scope``` rule is more consistent with how the rest of the declarations work for backwards compatibility.

ie. If it is understood, use it. If it's not understood, just ignore it. Vendors have been touting progressive enhancement as the path of least resistence and for that to work, the language needs to be as consistent as possible. the scoped html attribute breaks that consistency in my opinion.

**Comment by benface** [comment]
> When scope was in the spec, it was defined such that inner scopes overrode outer scopes, regardless of selector specificity.

I (a web developer) would absolutely love to see this implemented, for this exact reason. It would finally allow us to easily and elegantly override styles for new modules in existing projects with huge, potentially messy stylesheets full of overly specific selectors. With the `@scope` approach proposed above, we would be able to do something like:

```
/* messy stylesheet rules here... */

@scope .new-module {
    * {
        /* optional, prevents outside styles from leaking in */
        all: revert;
    }

    .new-module-box {
        font-size: 18px;
        color: blue;
    }
}
```

Regardless of whether `all: revert` is used or not, there would be no risk that the styles defined in `.new-module-box` will be overridden by any of the existing stylesheet rules even though the selector has very low specificity, because we're in a new scope.

This allows new code to be clean and easy to understand (even if the foundation is messy), rather than filled with `!important` declarations or multiple ID selectors only meant to boost the specificity.

**Comment by tabatkins** [comment]
Note that your example would *not* do what you think it does; in addition to preventing any outside styles from leaking in, it also *completely shuts down inheritance internally*. That `font-size` and `color` you provide in that rule will only apply to direct text children of the element; if you use anything else (even an inline like `em`) the text inside will revert to the UA defaults.

There is no way to *just* prevent outside styles from "leaking in" that does not end up being functionally identical to Shadow DOM.

**Comment by o-t-w** [comment]
@tabatkins and yet it avoids the massive amount of baggage that comes with shadow DOM. 
Thread: https://twitter.com/rob_dodson/status/961780022628331520?lang=en

**Comment by tabatkins** [comment]
That thread seems irrelevant to the discussion at hand. It's mostly referring to the vague annoyance with all the confusion around Shadow DOM versions (which are all cleared up now, Shadow DOM is well-established and stable) and then some grumbling about slots/::slotted, which are a wrinkle of how Shadow DOM handles a particular thing involving distributing light-DOM children into the shadow; neither of those are relevant to "cutting off a chunk of the DOM from outside styles", which is the most basic application of Shadow DOM.

**Comment by benface** [comment]
> Note that your example would not do what you think it does; in addition to preventing any outside styles from leaking in, it also completely shuts down inheritance internally. That font-size and color you provide in that rule will only apply to direct text children of the element; if you use anything else (even an inline like em) the text inside will revert to the UA defaults.

Oops, you're right, I didn't think that `all: revert` through... Well to be honest I only added that to my example because it was mentioned earlier in the thread, but I'm perfectly happy with styles leaking in too, as long as I can override them easily.

**Comment by Heydon** [comment]
@tabatkins The limitations of `::slotted` seem to be many. I don't seem to be able to use combinators, for example (so not depth related)?

```css
::slotted(*) + *       /* Nope */

::slotted(* + *)       /* Nope */

::slotted(*) + ::slotted(*)       /* Nope */
```

**Comment by benface** [comment]
> Note that your example would not do what you think it does; in addition to preventing any outside styles from leaking in, it also completely shuts down inheritance internally. That font-size and color you provide in that rule will only apply to direct text children of the element; if you use anything else (even an inline like em) the text inside will revert to the UA defaults.

Wait, is that really the case @tabatkins? I just tested in the two browsers that support `revert` (Safari and Firefox 67) and it didn't shut down inheritance at all. It also, however, did not prevent outside inherited styles such as `font-size` and `color` declared on a parent element from leaking in. Now I imagine it's possible the implementation is buggy, but that behavior kinda makes sense to me...?

**Comment by SelenIT** [comment]
> That `font-size` and `color` you provide in that rule will only apply to direct text children of the element; if you use anything else (even an inline like `em`) the text inside will revert to the UA defaults.

Wouldn't this occur only if UA styles have these properties defined directly for these elements (as it occurs for e.g. the `mark` element)? AFAIK, most UA's internal stylesheets don't specify color and size for elements like `em`, expecting them to inherit these properties anyway, so _in most cases_ the inheritance would still work...

**Comment by tabatkins** [comment]
> Wait, is that really the case @tabatkins? I just tested in the two browsers that support revert (Safari and Firefox 67) and it didn't shut down inheritance at all. It also, however, did not prevent outside inherited styles such as font-size and color declared on a parent element from leaking in. Now I imagine it's possible the implementation is buggy, but that behavior kinda makes sense to me...?

Ah, you're right. `revert` "rolls back the cascade", so it acts like there are no rules at all, and inheritance is allowed to occur.

But yeah, that then doesn't block outside rules *or* inheritance from trickling into the subtree. ^_^

**Comment by benface** [comment]
> But yeah, that then doesn't block outside rules or inheritance from trickling into the subtree. ^_^

Which, now that I think about it, is often desirable.

I would really like to see `@scope` in addition to the Shadow DOM, because it's simpler and it covers the use case where you don't want to prevent outside styles from leaking in, but you want to prevent *inside* styles from leaking *out* AND have the ability to easily override outside styles without knowing their specificity.

**Comment by o-t-w** [comment]
There's an interesting new proposal: https://github.com/w3c/csswg-drafts/issues/3714 
It seems more complicated than the scoped style attribute 🤔

**Comment by tabatkins** [comment]
It's trying to solve a different problem. ^_^

**Comment by BrentARitchie** [comment]
The references proposal is trying to solve a different problem, but still fits into the framework of scoped styles. Allowing a component author to provide a set of references for a simple control would greatly reduce the complexity of many implementations. The learning curve and complexity of Shadow DOM is quite high frankly, it is a completely different way of thinking and multi-disciplinary. Using scoped styles with references would enable many powerful use cases and help ease people into the world of Shadow DOM.

One use case made easier would be the control of intricate animations within an otherwise simple web component. Think the material button, simple in nature but the animations can be tricky.

I believe that truly componentized structures in HTML are key, we have been heading in this direction for sometime. First was BEM and Smacss. Then came Atomic Design and now we have css-in-js. All of these techniques point to the direction of easily componentized structures.

There is a reason frameworks like React are so popular now. By enabling authors to do more with only declarations, it can only serve to flatten the learning curve for the other more advanced options.

**Comment by benface** [comment]
Revisiting this after reading (and briefly participating in) [this Twitter thread](https://twitter.com/Rich_Harris/status/1161335244802404352) today...

In my last post I said:

> I would really like to see @scope in addition to the Shadow DOM, because it's simpler and it covers the use case where you don't want to prevent outside styles from leaking in, but you want to prevent inside styles from leaking out AND have the ability to easily override outside styles without knowing/caring about their specificity.

But thinking about this some more, it would actually be easy to prevent outside styles from leaking in as well, if we wanted to:

```
/* messy stylesheet rules here... */

@scope .new-module {
    * {
        all: revert;
    }

    :scope {
        all: initial;
    }

    .new-module-box {
        font-size: 18px;
        color: blue;
    }
}
```

Resetting all properties to their `initial` value on the scoping root (`:scope`) ensures that no values are inherited from outside without breaking inheritance within the scope, and reverting all properties to their UA defaults on every element in the scope (except the scoping root) ensures that no global rule from outside (such as `p { font-size: 24px; }`) is applied.

Really loving this proposal.

**Comment by benface** [comment]
> The reason why the scoped attribute idea was abandoned is that, in contrast to ShadowDOM, it didn't come with any lower boundary. This means that styles affect an entire subtree rather than a single "component".

It doesn't have to be like that. The `@scope` syntax could support an optional lower boundary. Just an idea:

```css
@scope (include: .carousel) and (exclude: .carousel-slide) {
    p {
        /* styles here wouldn't affect paragraphs inside .carousel-slide */
    }
}
```

**Comment by giuseppeg** [comment]
Nice! Actually a syntax like this might be cool (not sure how hard it'd be to implement and what would be the cons)

```css
@scope (from: .carousel) and (to: .carousel-slide-content) {
  p { color: red }
}
```

**Comment by ExE-Boss** [comment]
`@scope` is definitely better than `<style scoped>`, as the latter would be treated as a plain old `<style>` in non‑supporting browsers, whereas the former will be ignored unless supported.

**Comment by zlamma** [comment]
A bit daunted to see yet another thread on this, despite [the working group setting some expectations that they will help prevent this](https://github.com/w3c/csswg-drafts/issues/270#issuecomment-399671975)...

Trying not to just rant though, I can say though that this thread's proposal is better that that old one (even if part of it look like the historical [`@scope` proposal](https://www.w3.org/TR/2014/WD-css-scoping-1-20140403/#scope-atrule)).

 
Still, as [said previously](https://github.com/w3c/csswg-drafts/issues/270#issuecomment-364677643), I would really like the working group to consider ways of adding scope to the rules outside of the very stylesheet where these rules live, bur rather somewhere in a parent. This would enhance the ability to quote hypertext content with its full richness.
Also as said, both ways could exist, and it would make the feature maximally powerful. E.g. what if this scope clause:

```HTML
<style>
@scope .post {
  color: blue;
}
<style>
```

also caught all `<style>` references inside the `.post`? It even seems quite natural (for web components, e.g.), but if this is too risky of a default, it could be controlled using an explicit version, e.g `@scope::--also-ensclose-contained-stylesheets` (name deliberately verbose - just for clarity of intent).

**Comment by sziberov** [comment]
> Is there a reason to prefer the HTML attribute approach over a `@scope` rule in CSS? The latter seems to me to reduce code duplication and prevent poor fallback behavior.

`@scope` can't be used without adding some identificator for a scope element, when `<style scoped>` can. It makes `@scope` rule absolutely useless, when you trying to avoid making your DOM look like messf*ck.

![Screenshot_933](https://user-images.githubusercontent.com/7362968/93116229-ad9d9f80-f6c5-11ea-955f-bb9d340df1c3.png)

**Comment by keithjgrant** [comment]
> `@scope` can't be used without adding some identificator for a scope element, when `<style scoped>` can. It makes `@scope` rule absolutely useless, when you trying to avoid making your DOM look like messf*ck.

Without `@scope`, the styles MUST be inlined in the HTML, and cannot be written in an external stylesheet. This also means the entire `<style>` block would have to be repeated in the HTML if you wanted the same styles in another scoped region elsewhere

**Comment by sziberov** [comment]
> cannot be written in an external stylesheet

Can, when you injecting styles with JS. Evenmore, there is CSS `@import` rule (don't know if it worked with `scoped` attribute when there was it's support though, but thinking logically it should).

> have to be repeated in the HTML

It's not something I should bother about when creating DOM dynamically, IMHO.

**Comment by keithjgrant** [comment]
yes, but my point is it only meets a certain set of use-cases. Using `@scope` works with injected styles and with traditional stylesheets. IMO, the spec shouldn't be written to require a certain JS-based toolset if there's a more general-purpose solution available.

**Comment by faceless2** [comment]
As this one is still being kicked around...

We've been experimenting internally with a slightlly different approach, moving the "scoped" attribute from the `<style>` to the scope root, and allowing values of `none` (for no scoping), or `inherit` and `isolate` to control the lower-boundary:
```html
<style>
 span { font-style: italic }
</style>
<div scoped="inherit">
 <style>
  span { font-weight: bold }
 </style>
 <span>bold and italic</span>
</div>
```
```html
<style>
 span { font-style: italic }
</style>
<div scoped="isolate">
 <style>
  span { font-weight: bold }
 </style>
 <span>bold only</span>
</div>
```
This is working well for our purposes (building up huge documents from many smaller ones with `<xi:include>`). We found for completeness we needed another value: `scoped=override`, which is added to a `<style>` to force the declarations to be applied even in an element with `scope="solate"`
```html
<style scoped="override">
 span { color: red }
</style>
<style>
 span { font-style: italic }
</style>
<div scoped="isolate">
 <style>
  span { font-weight: bold }
 </style>
 <span>bold only, but also red</span>
</div>
```

The need to impose upper and lower limits on the styles - scoping the scope, if you like - seems to be adding a lot of complexity, particularly when it's attempted from within the stylesheet itself (eg with @scope). It seems to me the decision on whether an element is a scope root belongs with the element itself, not with a stylesheet it includes.

**Comment by ExE-Boss** [comment]
@faceless2
The issue with your approach [is the same as with `<style scoped>`](https://github.com/w3c/csswg-drafts/issues/3547#issuecomment-524207845), in that non‑supporting user agents will ignore the `[scoped]` attribute and apply the `<style>`s to all `<span>`s, instead of just the scoped ones.

**Comment by sziberov** [comment]
@ExE-Boss Let only those who still write sites with IE6 compatibility worry about that. They can simply not use `<style scoped>` if they don't want to.

**Comment by faceless2** [comment]
Yes, but limited support for a new HTML feature is not a new problem. Trying to solve this in the CSS domain purely because HTML lacks an equivalent of `@supports` doesn't seem like a better approach to me.

**Comment by SebastianZ** [comment]
> @ExE-Boss Let only those who still write sites with IE6 compatibility worry about that. They can simply not use `<style scoped>` if they don't want to.

Note that a `<style scoped>` approach would also affect all _current_ browsers until they implement that feature and those versions get adopted. Without support, the website layout is broken.

>> have to be repeated in the HTML
>
> It's not something I should bother about when creating DOM dynamically, IMHO.

You definitely should, maybe not for two or three `<style scoped>`, but that doesn't scale well. If you have a significant amount of them on a page, the size of the HTML gets bloated and the parsing performance decreases much faster than with centralized solution.

Another idea related to the `@scope` rule in combination with HTML is to introduce a `scope` attribute naming the scope. The `@scope` rule then matches that name.

```html
<style>
p { color: blue; }
@scope main {
  p { color: green; }
}
@scope note {
  p { color: gray; }
}
</style>
<p>This text is blue</p>
<section scope="main">
  <p>This text is green</p>
  <div scope="note">
    <p>This text is gray</p>
  </div>
</section>
<div scope="note">
  <p>This text is gray</p>
</div>
```

Sebastian

**Comment by fantasai** [comment]
@SebastianZ This is what the original 2014 proposal did, except instead of using a special name to tie the @scope and the element together, you could use any selector.

**Comment by fantasai** [comment]
Fwiw there was some discussion on this topic on the CSSWG call this week, see minutes at
  https://lists.w3.org/Archives/Public/www-style/2021Mar/0011.html

**Comment by zlamma** [comment]
Thanks @fantasai . There are interesting [slides](https://slides.oddbird.net/csswg/f2f2102/#slide-26) ([PDF](https://lists.w3.org/Archives/Public/www-archive/2021Feb/att-0002/Container_Queries_Proposal_-_vF2F_2021-02-09.pdf)) and [minutes](https://lists.w3.org/Archives/Public/www-style/2021Mar/0011.html), and here's a shortcut to the current open issue created by the author: https://github.com/w3c/csswg-drafts/issues/5809

**Comment by yisibl** [comment]
Good news, `<style scoped>` is coming back to Chrome by way of `@scope`. The front-end framework will benefit greatly, thanks to everyone who worked on this!

This will be implemented here: https://chromium-review.googlesource.com/c/chromium/src/+/4161741

In order to push all browsers to implement it, you can go to the [interop 2013](https://github.com/web-platform-tests/interop/issues/183) issue to show your support.

**Comment by gnat** [comment]
This project is living in the future: https://github.com/gnat/css-scope-inline

Keep the syntax simple and short, friends. I want to see `<style scoped>` return too, but let's try our best to cut down the excess verbosity.
