### ISSUE TITLE
[css-text] Should <wbr> create a break opportunity in `nowrap`?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#3562]
```html
<style>
div {
  width: 10ch;
}
.nowrap {
  white-space: nowrap;
}
</style>
<div class="nowrap">1234567<wbr>7654321</div>
```
Should this create two lines? Blink/WebKit create two lines, while Edge/Gecko do not.

**Comment by upsuper** [comment]
It's worth considering what it means for inlinization if we allow it to break lines in ruby.

Although it is technically a question for HTML, it can still interact with CSS features like inlinization, so ideally we should be able to map it with some CSS mechanism.

**Comment by fantasai** [comment]
WBR is a breaking opportunity, not a break. I don't think it causes any problem with ruby. :)

**Comment by frivoal** [comment]
* Doing what Blink does is certainly web compatible (and follows the historic precendent that @fantasai mentioned)
* if you want the alternative behavior despite that markup, you can `display: none` the `<wbr>`, so authors are not stuck.
* Given that the `white-space` property applies to inlines, and `<wbr>` with that behavior is reasonably described as something like `<span style=white-space:normal`>&#x200b;</span>` (or the same on its ::before or ::after), so no particular magic needs to be involved
* The same logic applies with `white-space: pre` instead of `white-space: nowrap`
* Relatedly `<wbr>` introduces a word break even with `word-break: keep-all` (and that also works in Firefox)

I agree with @fantasai that no change is needed in css-text to support the existence of an element that behave like that. A clarification in the HTML spec seems like the right place. The right bug to discuss this is probably: https://github.com/whatwg/html/issues/2291

**Comment by fantasai** [comment]
Filed https://github.com/whatwg/html/issues/6227 as a follow-up.
