### ISSUE TITLE
[css-scroll-snap] More work needs to be done to address what happens when users with low vision zoom

### ISSUE THREAD

**Issue by mraccess77** [w3c/csswg-drafts#3602]
In the snap-strictness section the spec talks about how different screen sizes can prevent content from being accessible.  When users with low vision zoom in they end up with scaled content between breakpoints and often content is pushed off the bottom of the screen but when the user scrolls the viewport is moved to the next snap position and the low vision users can't access all of the content.  We need an inclusive solution.

**Comment by fantasai** [comment]
The solution is to only use mandatory snapping when you are using it on elements that collectively cover the total page content, so that you trigger the rules in https://www.w3.org/TR/css-scroll-snap-1/#snap-overflow when necessary. E.g. use it on SECTION and not on H3. Or use proximity snapping instead of mandatory snapping. This is already described in the spec.

**Comment by mraccess77** [comment]
Hi @fantasai can you point me to a working example of mandatory snap scrolling on sections so I can confirm how it is working?  Thanks.
