### ISSUE TITLE
[css-align] Special case for inline-block+scroll-container elements needs to cover inline blocks that **contain** scroll containers

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#3611]
This is about the special case described at the end of the "block" section, here:
  https://drafts.csswg.org/css-align/#baseline-export
which was added in https://github.com/w3c/csswg-drafts/issues/2902.
Right now, that spec text says:

> ...for legacy reasons, if an inline-block is a scroll container or contains no in-flow line boxes, its first and last baseline sets are synthesized from its margin box.

It appears we need to broaden the first part of that condition.

Right now, the special case specifically covers scenarios where the `inline-block` **is** a scroll container.  But it doesn't cover the case where the `inline-block` **contains** a scroll container (and nothing else).  Browsers render that scenario the same way, but the spec doesn't say they should, AFAICT.

i.e. Browsers render these two divs the same (using their margin-bottom edge for baseline alignment):
```
abc
<div style="display:inline-block;overflow:scroll">...</div>
<div style="display:inline-block"><div style="overflow:scroll">...</div></div>
```
Here's a real-world testcase demonstrating that browsers do in fact align them the same (using the margin-bottom for both): https://hg.mozilla.org/mozilla-central/raw-file/2064e7c799d2/layout/reftests/inline/inline-block-baseline.html

CC @tabatkins  @fantasai

**Comment by tabatkins** [comment]
You're right that the first condition isn't sufficient, but some testing by me and @fantasai seems to show that it should be broadened in a different way.

If the inline-block contains a scrollable *flexbox*, it still gets baseline-aligned per its content:

```html
<!DOCTYPE html>
<style>
.inline-block { display: inline-block; }
.test {
  background-color: lightgrey;
  overflow: hidden;
}
.border { border: solid blue;  border-width: 1px 3px 5px 7px; }
.padding { padding: 10px; }
.margin { margin: 1px 3px 5px 7px; }
</style>

The boxes should align vertically:
<div class="inline-block">
  <div>
      <div class="test border padding margin" style="display:flex">X</div>
  </div>
</div>

<div class="test inline-block margin border padding">X</div>
```

So it looks like the condition, rather than "inline-blocks that are scroll containers", should be "block containers that are scroll containers".

That covers the original condition, *and* makes your testcase valid per spec, as the inline-block tries to determine its baselines from its content, sees only a scrollable block container, and concludes that it has no baselines. (And then, per Inline, it synthesizes baselines from its own margin box.)

Does this sound correct?



----

Aside: Form controls are fun here, as semi-replaced elements. `input` is baseline-aligned (and can't be made scrollable), but `textarea` and `<select multiple>` margin-align (because they're inherently scrollable). This should be written down somewhere...

**Comment by dholbert** [comment]
I think that sounds correct, yeah. Thanks!

**Comment by bfgeek** [comment]
`input` is slightly more fun, in that even though it might not have any content, it'll still "baseline" align, e.g. https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=7691

**Comment by fantasai** [comment]
Minutes: https://lists.w3.org/Archives/Public/www-style/2020Feb/0008.html

**Comment by jonjohnjohnson** [comment]
Should this behavior be relative to the axis of overflow in the scroll container, such as only overflowing in the inline axis?

**Comment by fantasai** [comment]
Minutes from January https://lists.w3.org/Archives/Public/www-style/2020Feb/0008.html

**Comment by fantasai** [comment]
Testcase: https://lists.w3.org/Archives/Public/www-archive/2020Apr/att-0004/scroll-align-test.html :(

**Comment by fantasai** [comment]
OK, we've committed some changes to fix the spec here. @bfgeek @dholbert Would you mind reviewing?

**Comment by tabatkins** [comment]
Okay, edits were made in 7a66d53f693c973ac1f87993f6a42c88b21980dd (paired with 3bd261f0b92c7087640b6249e8f865f0ba9ccb6d to clarify exactly when baselines are synthesized). After puzzling over Elika's testcase a bit (now captured in the repo at <https://drafts.csswg.org/css-align-3/baseline-align-test>), we realized the actual behavior here is *weird* but *interoperable*:

* block-containers that are scrollable *have* a last baseline set, all of which are set to be the bottom margin edge of the box. (This is *different* from normal synthesis rules; in particular, the central baseline is also the bottom margin edge, rather than halfway between the top and bottom margin edge.)
	
	You can see the difference from your suggested "block container containing only a scroll container" by looking at cases B (inline-block scroll container) and I (inline-block containing only a scroll container) in Elika's testcase - these correspond to the two boxes in (your testcase from the first comment](https://hg.mozilla.org/mozilla-central/raw-file/2064e7c799d2/layout/reftests/inline/inline-block-baseline.html). Your testcase didn't give the wrapper inline-block any dimensions, so it couldn't tell the difference between the two cases like Elika's can - if everything has borders, you can clearly see that it *does* baseline-align to the child scroller, not the inline-block wrapper.

* block-containers that are scrollable *do not have* a **first** baseline set. Again look at cases B and I, but for the table/flex rows - in both cases, the outermost element is synthesizing a baseline from its box.

**Comment by dholbert** [comment]
Thanks for that explanation! I think your bullet-points there make sense and seem to mesh with my observations from fantasai's testcase.

RE the spec edits: they make sense if I don't think about writing-modes at all. :)

But if I take writing-mode into consideration, then https://github.com/w3c/csswg-drafts/commit/7a66d53f693c973ac1f87993f6a42c88b21980dd doesn't quite make sense -- in a vertical writing-mode, I don't think it's right (or meaningful) to say that we derive the last baseline set from the margin-**bottom** edge...  Perhaps that means to say that we derive it from the "block-end margin edge"?

That seems to be what Chrome uses for cases "B" and "I" if I load https://drafts.csswg.org/css-align-3/baseline-align-test with `body { writing-mode: vertical-rl }` or `vertical-lr`, too.  But, Firefox actually seems to use the central baseline for those cases when loading the testcase in a vertical writing-mode (and we use the central baseline for most of the cases there, in fact), rather than using the perhaps-proposed block-end margin-edge. So: it seems we're not interoperable on that particular point.

(CC @jfkthame & @MatsPalmgren who may have thoughts on this, too)

**Comment by tabatkins** [comment]
Oh phew, yes, definitely a writing-mode-aware edge, sorry about that.

Question, tho: line-under, or block-end? @fantasai, you know the appropriateness of line-under usage better than me.

**Comment by fantasai** [comment]
@tabatkins block-end of the scroll container, because we're compensating for the fact the line we would be aligning to is scrolled off-screen, potentially (or at least, I think that's the "logic" being applied here)?

@dholbert Firefox's handling of baselines in vertical writing modes is extremely broken in general. Not really useful as a reference implementation. :/
