### ISSUE TITLE
[css-grid] Unintentional change to grid container baseline?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3645]
There was [a change](https://github.com/w3c/csswg-drafts/commit/15fe334dc4aeea8dbf1a26497fc7b65cb626fd05#diff-d55daa50088af378e4c59fea0f0d01b8) made in the last bullet point under [§10.6. Grid Container Baselines](https://drafts.csswg.org/css-grid/#grid-baselines) that looks unintentional. It used to say that the first item should be used, but now it doesn't. It appears that part of this edit was not discussed in the [CSSWG meeting](https://lists.w3.org/Archives/Public/www-style/2016Sep/0000.html), nor mentioned in the resolution, AFAICT, so it looks like an unintentional change to me. It appears that the discussion is mostly about which box (content/block/margin) to use to synthesize the baseline, not that items in other tracks should be ignored. That edit was for issue #373 BTW.

Testcase:
```html
<style>
  .grid {
    display: inline-grid;
    grid: 100px 100px 100px / 10px;
    border: 1px solid;
  }
  .item {
    background: lime;
  }
</style>

A<div class="grid">
  <div class="item">B</div>
</div>

A<div class="grid">
  <div class="item" style="grid-area:2/1">B</div>
</div>
```

Firefox takes the item in the 2nd row into account while Chrome doesn't so we now disagree on this testcase.

I'd like clarification if the change to ignore all items except those in the first(last) track was intentional or not?

**Comment by MatsPalmgren** [comment]
Fwiw, it seems a bit inconsistent that we baseline-align with the "B" here, but not in the previous example:

```html
<style>
  .ib {
    display: inline-block;
    border: 1px solid;
  }
  .ib > div {
    height: 100px;
  }
</style>

A<div class="ib">
  <div></div>
  <div>B</div>
  <div></div>
</div>
```

**Comment by fantasai** [comment]
I don't think the change was intentional, I think it was an accidental oversimplification. I guess the question is now, what's the preferred behavior. I don't think the result of that oversimplification is it: I'd say either we align to the contents of the first item, or we synthesize a baseline off the dimensions of the first grid track itself. Falling back to synthesizing off the grid container makes sense for an empty grid, but not really for one with content...

@jensimmons @rachelandrew @LeaVerou What would you expect in @MatsPalmgren example (baseline aligning a grid that contains only a single grid item in 2nd row)?

**Comment by javifernandez** [comment]
As far I understand the [3 steps](https://drafts.csswg.org/css-grid/#grid-baselines) to determine the grid container's baseline, the grid in your first example has no first natural baseline, and it should synthesize one (step 3). The steps 1 and 2 state clearly that the items used to determine the grid s baseline should have an area intersecting the first row. 

The change @MatsPalmgren  mention, if I'm not wrong, stated originally:
> and the first (last) such <a>grid item</a> (in <a>grid order</a>) has a baseline set parallel to the relevant axis, ...

I've always had understood that **such** first item was one among those their area intersects with the first row, since there may be many; that's why we have to use the first one in grid order.

**Comment by MatsPalmgren** [comment]
I think we should definitely use items in other tracks if the first track is empty. I don't feel strongly about exactly how a baseline is derived from that item though. Using its natural baseline, if it has one, or synthesizing one if it doesn't, make the most sense to me. I think if we remove the _"whose area intersects the first (last) row"_ condition from Step 2 then we'd get that behavior. A slightly more advanced scheme would be to remove that condition from Step 1 too.

Using the track itself makes no sense to me since baseline alignment is a content-based alignment scheme and the grid itself is not content (and to be clear: by "the grid" I mean the abstract concept outlined with a dashed border in this [figure](https://drafts.csswg.org/css-grid/#example-ff8d888d), not the grid container box). I don't see how that would be useful anyway when that track is empty.  If that track is intrinsically sized it'd be zero, otherwise it's likely a definite size so alignment to that position can likely be achieved through other means (relative position or margin or whatever on the grid container).

It seems to me that if the author intentionally wants to align the grid lines to the baseline it should be a separate concept, perhaps as a new value for [alignment-baseline](https://www.w3.org/TR/css-inline-3/#alignment-baseline-property).

**Comment by javifernandez** [comment]
I understand @MatsPalmgren 's point, however, I find the first (last) row condition very intuitive to match the fist (last) baseline value. In this case, tracks behave line lines when we are talking about a general text box's baseline. I agree, though, that the grid is not content hence they are not its track, but I wouldn't remove the condition of using the first (last) row.

**Comment by javifernandez** [comment]
> Using the track itself makes no sense to me since baseline alignment is a content-based alignment scheme

I forgot to comment about this statement, which I don't think it can be interpreted reading the spec and it wasn't also in my comments. We indeed don't want to use the track itself, since tracks are not content, but the items in that track. 

If there are no items in the first track, then synthesizing makes sense, in my opinion.
