### ISSUE TITLE
Font-family name matching requires full Unicode case comparison

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3675]
https://drafts.csswg.org/css-fonts-4/#localized-name-matching

This is the only place in WebKit that requires a full Unicode case matching. We have intentionally not implemented this because it’s non-performant. Instead, we just do ASCII case folding. It would be good if we could improve the performance of all implementations by specifying in the spec to use only ASCII case folding. Font lookups are very common in every page load, so performance here is very important. Also, we haven’t had web compatibility bugs due to not performing full Unicode case matching.

http://userguide.icu-project.org/transforms/casemappings says that “there is a flag for whether to apply special mappings for use with Turkic (Turkish/Azerbaijani) text data“ so if we’re going to define that it really requires full Unicode case matching, we’ll have to define how to set this flag.

**Comment by tabatkins** [comment]
So ASCII case-insensitive, otherwise codepoint-wise comparison?

**Comment by litherum** [comment]
Cc @kojiishi @drott @jfkthame

**Comment by litherum** [comment]
@tabatkins Yes

**Comment by jfkthame** [comment]
I don't think performance should actually be an issue here, given that the spec says "the algorithm [Default Caseless Matching] must be applied without normalizing the strings involved and without applying any language-specific tailorings". So issues like the Turkish i/ı don't arise.

**Comment by drott** [comment]
> This is the only place in WebKit that requires a full Unicode case matching. 

Can you specify in more detail what do you mean by full Unicode case matching here? Do you mean case-sensitive matching? I understand the current spec to mean: Perform "Default Caseless Matching" from https://www.unicode.org/versions/Unicode9.0.0/ch03.pdf section 3.13, with emphasis on doing that without normalization and without language specifc tailorings. This would be only the comparison mentioned in the Unicode spec as D144:

> D144 A string X is a caseless match for a string Y if and only if:
> toCasefold(X) = toCasefold(Y)

Implementation wise, I believe this would be http://icu-project.org/apiref/icu4c/classicu_1_1UnicodeString.html#a0924f873180947aab38b7380da638533  with `U_FOLD_CASE_EXCLUDE_SPECIAL_I`.

I think the spec already describes that this flag should be set accordingly, as tailorings are excluded from the matching algorithm.

What performance benefits do you see from only performing casefolding for the ASCII range?

**Comment by litherum** [comment]
Right, implementing this would require calling into ICU for the string comparison, rather than a tight loop with some bit manipulation. We haven’t done performance analysis to know what the performance regression would be if we adhered to the spec here; however, we expect it to be significant. WebKit has never adhered to this part of the spec.

**Comment by jfkthame** [comment]
Can we double-check this, please?

> <emilio_> emilio_: We do whatever nsCaseInsensitiveStringComparator does
> <emilio_> dbaron: that's ascii

@dbaron are you sure about that? We have nsASCIICaseInsensitiveStringComparator, which indeed does ASCII-folding only and otherwise just does a direct codepoint comparison; but nsCaseInsensitiveStringComparator case-folds all of Unicode.

So I believe we follow the (current) spec here, performing a case-insensitive comparison, without normalization or language-specific processing. (And AFAIK we've never noticed this as being a performance issue.)

**Comment by drott** [comment]
Unfortunately I could not attend the meeting, but I do not find the string comparison a problematic performance aspect of font matching either. I agree with @litherum that font family matching is a hot code path but usually performance issues arise due to the fact that a potentially large number of fonts need to be indexed / their metadata needs to be accessed or cache to perform matching. The performance issues are not in performing string comparisons once the metadata is available. 

For Chrome, we have multiple backends:

On Windows we do what:
https://docs.microsoft.com/en-us/windows/desktop/api/dwrite/nf-dwrite-idwritefontcollection-findfamilyname
does, which seems to be a unicode case fold, not an ASCII only one.

On Linux and ChromeOS we do what FcPatternAddString for family + FcFontSort do. I haven't looked into the implementation of this to see what matching algorithm is used there. (@behdad - do you know what matching algorithm FC uses for family name comparisons?)

On Android which case insensitively match against alias names in the android fonts.xml configuration which are only specified there in Latin.

On Mac we use NSString caseInsensitiveCompare which does not seem to be restricted to ASCII according to https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/SearchingStrings.html#//apple_ref/doc/uid/20000149

(Unrelated: For the the upcoming fixes for src: local() matching in android we use ICU's FoldCase).

We have little control over the system APIs string matching behavior other than implementing our own full font indexer and lifting all metadata out of the system caches and performing our own matching operations, which I don't think we will do anytime soon.

**Comment by aphillips** [comment]
I18N recently published an entire Note about this: [Charmod-Norm](https://www.w3.org/TR/charmod-norm/) which you might look at.

ASCII case-insensitivity doesn't look like a good choice, since font names are not restricted to ASCII or even to the Latin script and I'm disappointed to see the above resolution. I think several of the assertions in this thread are incorrect.

**Comment by behdad** [comment]
FWIW, fontconfig does this.

**Comment by dbaron** [comment]
@behdad what does fontconfig do?

(Sounds like we should probably reconsider, though.)

**Comment by dbaron** [comment]
(And yes, I was wrong about `nsCaseInsensitiveStringComparator`.)

**Comment by behdad** [comment]
> @behdad what does fontconfig do?

Does full Unicode case-mapping.  Like nsCaseInsensitiveStringComparator I suppose.

**Comment by svgeesus** [comment]
An since no change means no edits needed either, it looks like this one can be closed. Myles, on the call you were okay with the resolution so tagging as commenter satisfied, too.
