### ISSUE TITLE
[css-lists] Initial value of counter-increment needs to be something different from none

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3686]
Background: we (Gecko) have implemented the `counter-set` property, the built-in `list-item` counter for `<ol>/<li>` etc, and the `::marker` pseudo for rendering.  This all works fine, with one exception:  `counter-increment` should be automatically set on [list items](https://drafts.csswg.org/css-lists-3/#declaring-a-list-item), which means its value depends on the computed value of `display`.  This means it's impossible to implement this in the UA sheet so we "adjust" the computed value in the style engine instead.  At that point though, an author-specified `counter-increment:none` is lost if the initial value is `none`.

The natural solution to this problem is to change the initial value to something else, e.g. `auto`, which then computes to the relevant `list-item` counter value on [list items](https://drafts.csswg.org/css-lists-3/#declaring-a-list-item) and to `none` on other elements.

(A quick resolution would be most welcome since it blocks shipping this new implementation (which fixes a bunch of decades-old HTML list counter bugs in Gecko).)

CC @emilio @fantasai

**Comment by dbaron** [comment]
We just discussed this in the meeting (see minutes).

When evaluating options here, some cases we considered were:
* author modifications to the `list-item` counter (to disable the implicit increment, or other modifications)
* author modifications to *other* counters that happen to be on the same element that implicitly modifies the `list-item` counter
* what the UA styles for `<li value>` and what (accidentally or intentionally) overrides them
* what the behavior for `<ol reversed>` is

So we have three alternative proposals that take a different approach, with subtle differences, made in the following order:

(A) @fantasai's proposal: if an element has `display: list-item`, then the `list-item` counter is incremented *unless* the `counter-increment` property contains a reference to the `list-item` counter.  (Authors can override this effect with `counter-increment: list-item 0`.

(B) @dbaron's proposal: if an element has `display: list-item`, then the `list-item` counter is incremented.  (Authors can override this effect with `counter-increment: list-item -1`, unless the list is reversed, in which case it would be by `1`.)

(C) @FremyCompany's proposal: if an element has `display: list-item`, then the `list-item` counter is incremented *unless* the `counter-reset`, `counter-set`, or `counter-increment` property contains a reference to the `list-item` counter.

I think there was probably the most support and the least objection to (A).

**Comment by dbaron** [comment]
We just discussed this in the meeting (see minutes).

When evaluating options here, some cases we considered were:
* author modifications to the `list-item` counter (to disable the implicit increment, or other modifications)
* author modifications to *other* counters that happen to be on the same element that implicitly modifies the `list-item` counter
* what the UA styles for `<li value>` and what (accidentally or intentionally) overrides them
* what the behavior for `<ol reversed>` is

So we have three alternative proposals that take a different approach, with subtle differences, made in the following order:

(A) @fantasai's proposal: if an element has `display: list-item`, then the `list-item` counter is incremented *unless* the `counter-increment` property contains a reference to the `list-item` counter.  (Authors can override this effect with `counter-increment: list-item 0`.

(B) @dbaron's proposal: if an element has `display: list-item`, then the `list-item` counter is incremented.  (Authors can override this effect with `counter-increment: list-item -1`, unless the list is reversed, in which case it would be by `1`.)

(C) @FremyCompany's proposal: if an element has `display: list-item`, then the `list-item` counter is incremented *unless* the `counter-reset`, `counter-set`, or `counter-increment` property contains a reference to the `list-item` counter.

I think there was probably the most support and the least objection to (A).

**Comment by faceless2** [comment]
For what it's worth we have
```
li[value] {
    counter-set: list-item attr(value integer, 1);
    counter-increment: list-item 0;
}
```
in our default stylesheet, and this approach for working around the implied list-item increment seems to go back [years](https://lists.w3.org/Archives/Public/www-style/2007Oct/0102.html), so (a) looks good to me.

**Comment by MatsPalmgren** [comment]
I prefer (A) since it's simpler than (C).  I don't really see any benefit of (C) that warrants the added complexity.
(B) seems tricky to implement since `<li value=N>` would need to be mapped to `counter-set:list-item N; counter-increment:list-item INC` where `INC` is ±1 depending on the `reversed` attribute of the nearest `ul/ol/menu` ancestor, which looks difficult to compute for us at the point where we map attributes to style.  Also, the final computed value will be `counter-increment:list-item -1 list-item 1` in that case which looks weird.

Fwiw, I implemented (A) and it was fairly straight-forward.

**Comment by tabatkins** [comment]
Thinking on this with a fresh mind, I think I'm for (A) as well: `display:list-item` just adds a magic `list-item` counter to the element iff counter-increment doesn't already mention `list-item`. It just seems overall simplest, with the least amount of tricky-looking hacks to "cancel out" the default increment.

**Comment by tabatkins** [comment]
Put more directly, I think (A) is the closest we can get to having the default list counter be implemented via the UA stylesheet, while maintaining back-compat. When you need to interact with the `list-item` counter explicitly, the code you write under (A) is identical to what you'd write if `list-item` was just set up in the UA sheet, or in an author sheet.

I'm against (B) and (C) because they cause the code you write for `list-item` to be *different* than what you'd write for a manually-created counter. (B) has some conceptual simplicity (it acts like an "additively" cascaded value, which we've talked about in the past), but I don't think that underlying conceptual simplicity is worth the additional visible complexity.

I'm against (C) because of the action-at-a-distance. Having `li[value] { counter-set: list-item attr(value integer); }`, all by itself, cancel out the increment, when any *author-created* list counters would require adding an additional `counter-increment: foo 0;` to the rule, looks confusing and unexpected. This is again added visible complexity, but without even the underlying simplicity that (B) attempts to apply.

**Comment by FremyCompany** [comment]
FWIW proposal (c) was mainly a counter-proposal to (b) but I would totally support (a) as well.

The reason behind (c) is that you can implement the [value] attribute of LI using a simple counter-set, otherwise that attribute also needs a counter-increment, and might interact negatively with other attributes. I'm not entirely convinced myself that being able to express [value=2] in pure css is worth it, but some people seemed to think so.

**Comment by emilio** [comment]
Note that this also needs to change the `li[value]` rule to set `counter-increment: list-item 0` rather than `counter-increment: none`.

**Comment by heycam** [comment]
> Note that this also needs to change the `li[value]` rule to set `counter-increment: list-item 0` rather than `counter-increment: none`.

Just to clarify, would that mean that with

```
<style>
.item { counter-increment: items 1; }
</style>
<ol>
  <li class=item>Abc
  <li class=item value=10>Def
  <li class=item>Ghi
</ol>
```

you would lose the UA-specified disabling of the list-item increment on the "Def" item?  Or is counter-increment's definition include wording about whether there is an implicit "list-item 1", "list-item 0", or "list-item -1" in the counter-increment property, based on the `value` and `reversed` attributes on the element?  If so, then I don't think we need the UA style sheet rule `counter-increment: list-item 0`.  If not, then I'm not sure how the above example should work.

**Comment by FremyCompany** [comment]
@heycam That was my understanding, yes. If you use `value` and `counter-increment` together, you need to specify `listitem 0` to disable the auto-incrementing in your `counter-increment` based on the currently approved proposal, otherwise you would still get an automatic increment on top of what `value` specified. That wasn't the case in proposal C which took into account the presence of `listitem` in any of `counter-set` or `counter-increment` but the group went with proposal A instead as it appears simpler to implement.

Now of course your proposal makes a lot of sense, and we could have a special css property that would be `listitem-counter-increment: <number>` which defaults to 1 but is also being set with things like `reversed` and `value`; that would indeed mean `value` would set this rather than rely on authors not providing their own `counter-increment` at the same time as using the `value` attribute. I'm find this proposal really attractive.

```css
ul {
    listitem-counter-increment: 1;
}
ul[reversed] {
    listitem-counter-increment: -1;
}
li[value] {
    counter-set: listitem attr(value as integer);
    listitem-counter-increment: 0;
}
```

Going further, we could make all UA actions on the listitem counter be based on a special propoperty, and have `listitem-counter-set` which would set the listitem counter except if listitem is mentioned in `counter-set` by the author, similar to your proposal for `counter-increment` but being applied to `counter-set` instead. That might be overkill given how rare I would expect that second case to be, but consistency is nice.

**Comment by fantasai** [comment]
Just for the record: https://github.com/w3c/csswg-drafts/issues/2464#issuecomment-375492907 links to the old WG discussions where we first worked out how the list-item counter should work.

**Comment by FremyCompany** [comment]
I think we can close this issue based on the other resolution (feel free to to reopen if you disagree). 

My understanding is that your proposed `auto` is already the behavior of `none`, and `listitem 0` corresponds exactly to the `none` value you were proposing. So adding `auto` and changing the meaning of `none` wouldn't provide any new capability to the author.

**Comment by MatsPalmgren** [comment]
@FremyCompany True, but `counter-increment: none` is a more concise and natural syntax than `counter-increment: list-item 0`, IMO. But yeah, implementing the automatic increment for list items as a used-value magic thing instead of a computed value lessens the need for `counter-increment: auto`.  I don't feel strongly either way, so used-value magic is fine with me.

**Comment by MatsPalmgren** [comment]
It would be nice though if the CSSWG could be a little more precise in its resolutions. This issue has "initial value" in the subject, and the [OP](https://github.com/w3c/csswg-drafts/issues/3686#issue-415389501) clearly states that we implemented it as a _computed_ value. 

The description of [options](https://github.com/w3c/csswg-drafts/issues/3686#issuecomment-468098431) and the resolution:
> RESOLVED: go with fantasai proposal (a) for initial value of counter increment?

never mentions _used value_ once. Additionally, _initial value_ is a CSS term that implies a _computed value_.

This creates confusion about what the CSSWG has discussed and resolved. Confusion that has on several occasions led us (Gecko) to implement things in the wrong way and thus waste precious resources on filing spec issues, re-implement it in the right way and update tests, filing bogus bug reports on other engines etc.  For an UA vendor with limited resources like Mozilla this is VERY costly.  I've also seen on several occasions that CSSWG members themselves don't agree afterwards what was being discussed and/or what the resolution means. 

I would suggest that you, before a resolution is made, take a minute to formulate a detailed and precise resolution statement that cannot be misinterpreted. In particular, when the word "value" appears in the resolution, make sure you **always** qualify every occurrence as a specified, computed, resolved or used value. Thanks.

**Comment by FremyCompany** [comment]
@matspalmgren Sure, but it's not like we are imprecise on purpose, it's just that when you just discussed something it appears clear in your head.

**Comment by wis** [comment]
why doesn't this work?
``` .css 
span[aria-label="Video"] {
    counter-increment: vidNumber;
}
span[aria-label="Video"]:before {
    content: counter(vidNumber)" ";
}
```
and this does
``` .css
._e296pg {
    counter-increment: vidNumber;
}
._e296pg:before {
    content: counter(vidNumber)" ";
}
```
I'm found counter-increment to be very useful while making a user style for KhanAcademy.com that shows the number of each lesson, video and practice next to it.
according to my experience making user styles using the accessibility attributes is very useful

**Comment by faceless2** [comment]
@wis without an initial counter-reset(vidNumber), the counter-increment will create a new counter scope each time. Try adding :root { counter-reset: vidNumber } - if that fixes it, that's the issue.

I don't think it's a spec problem.

**Comment by wis** [comment]
oh you made me see what's happening here, I had 
``` .css 
body {
    counter-reset: lessonNumber;
    counter-reset: vidNumber;
}
```
I forgot that a CSS selector is essentially a dictionary, and the key/CSS property `counter-reset` can be set once and overridden after, even though logically you'd expect it not to be the case for this specific property.
I fixed it by using more than one top selector like `body`, 
``` .css
body {
    counter-reset: vidNumber;
}
html {
    counter-reset: lessonNumber;
}
```
though, this is still limiting for user-styles if you need more than 2 counters, you'd need to find "top level container elements" with unique properties like `aria-label` that wouldn't change and break the user-styles with new site updates.
Thanks.

**Comment by dbaron** [comment]
The last three comments describe a use case for #1594 (already discussed there and in the predecessor discussions of the same topic that predated the group using GitHub).

**Comment by faceless2** [comment]
@wis you can do `body { counter-reset: lessonNumber, vidNumber }`
