### ISSUE TITLE
[css-transforms-1] SVG transform attributes: transforms don't need to be separated

### ISSUE THREAD

**Issue by dirkschulze** [w3c/csswg-drafts#3719]
https://drafts.csswg.org/css-transforms/#svg-transforms does not reflect implementations correctly.

Syntax says:

```
transform
| transform comma-wsp transforms
```

which requires a comma or a wsp between transform functions. Browsers do not require any separation between transform functions.

Example:
```xml
<rect width="20" height="20" transform="translate(20, 20)scale(20)"/>
```
... does translate _and_ scale the rect in Safari, Chrome and Firefox.

**Comment by AmeliaBR** [comment]
Interestingly, the [SVG 1.1](https://www.w3.org/TR/SVG11/coords.html#TransformAttribute) grammar supports _one or more_ `comma-wsp` tokens, but Firefox seems to be the only browser that allows arbitrary commas in between functions (Edge allows up to 2 commas, but no more, Chrome only allows zero or one).

We should definitely change to match reality where browsers are consistent (i.e., make the `comma-wsp` token optional in the grammar).  For the inconsistent bit (excess separators), I would say the spec should be more restrictive (max one `wsp*-comma?-wsp*` sequence), so that content that matches the spec works in all browsers.

**Comment by valtlai** [comment]
Why there’s comma separators for CSS transform functions in the first place? Why not spaces, like `translate(10px 20px)`?

**Comment by AmeliaBR** [comment]
@valtlai This discussion is about the legacy SVG syntax, which allowed either commas or spaces.

If you want to argue for loosening up the CSS syntax, that would be a separate issue.

I believe the reason to restrict things in CSS was about enforcing consistency: pick one syntax and stick with it! And _(x,y)_ is a common idiom for describing vector translations in math, so that's probably why it was chosen. But you're correct that we've muddied the waters by switching the syntax for colors, based on the argument that commas should be reserved for lists.

**Comment by tabatkins** [comment]
Note that the transform functions were defined and shipped *before* @fantasai and I elucidated the "commas are for repeated lists, even in functions" principles.

The color-function switch happened at the same time as we added multiple other new color functions, *and* relaxes the arg-length requirements on a "no -a" versions of the existing functions; as a small part of a much larger shift, it wasn't a big deal. Switching transforms at this point would be *solely* a comma-removal, which isn't really worth the cost.
