### ISSUE TITLE
[css-inline] A question for the procedure to compute the resolved value of "line-height"

### ISSUE THREAD

**Issue by joonghunpark** [w3c/csswg-drafts#3749]
I have a question about the procedure to compute the used value of "line-height".
I'm currently making a change on blink in
https://chromium-review.googlesource.com/c/chromium/src/+/1522053/3.
This change is for "line-height" to return used value instead of "normal keyword"
as resolved value.

In case of WebKit, fontMetrics().lineSpacing() value is used instead of 'normal' as below.

```c
int RenderStyle::computedLineHeight() const
{
    const Length& lh = lineHeight();
    // Negative value means the line height is not set. Use the font's built-in spacing.
    if (lh.isNegative())
        return fontMetrics().lineSpacing();
    if (lh.isPercentOrCalculated())
        return minimumValueForLength(lh, computedFontPixelSize());
    return clampTo<int>(lh.value());
}
```

And Firefox returns used value "px" instead of "normal" also.

But I'm not sure what is the exact procedure to compute the used value for "line-height",
because I coundn't find that in spec.

Is it ok to use font metircs linespacing value like WebKit, or is there a exact procedure to compute the used value?

**Comment by ewilligers** [comment]
Context:
https://drafts.csswg.org/css-inline-3/#propdef-line-height
https://www.w3.org/TR/CSS2/visudet.html#propdef-line-height

**Comment by frivoal** [comment]
The logic for `line-height` described in css2.1 is know to be buggy.

It has been quite thoroughly reviewed and fixed, and css2.2 was made reliable. There remained some unsolved questions for`line-height: normal`, but it is a lot less wrong than what came before it.

However, for unrelated reasons (insufficiently careful edits had been made throughout the spec, so various parts were wrong, and which was which had become intractable), all changes to css2.2 had to be reverted to css2.1. We still haven't been able to re-apply all the known-to-be good changes.

This means the better definition of line height is currently in no spec at all. We should fix that, but until that happens, I recommend reading form the PR that did fix it at some point: https://github.com/w3c/csswg-drafts/pull/1993, while keeping an eye for possible issues. I'm aware of at least these: 
* https://github.com/w3c/csswg-drafts/issues/1254 (This one is partly solved, so you may want to skip the first half of the issue, but as the comments after https://github.com/w3c/csswg-drafts/issues/1254#issuecomment-296129092 show, there are still some unresolved points)
* https://github.com/w3c/csswg-drafts/issues/2418
* https://github.com/w3c/csswg-drafts/issues/1551

Based on all that, I am not sure that what you're trying to do is possible: unlike the other values of the property, `line-height: normal` does not result in single a height per element. Each text run may end up having a different height. To me, that means that returning 'normal' as a keyword makes more sense. Unless there's a compat constraint, I think CSSOM should be fixed accordingly (non-normal values should still be absolutized, but normal should stay as a keyword).

**Comment by joonghunpark** [comment]
I see. Then current blink behavior returning "normal" keyword instead of px
value for "line-height" is reasonable I think.
In that case, in https://drafts.csswg.org/cssom/#resolved-values, it seems
that "line-height" should be excluded from the css property list of "used
value is resolved value".
Thank you for your help.

2019년 3월 20일 (수) 오후 12:57, Florian Rivoal <notifications@github.com>님이 작성:

**Comment by frivoal** [comment]
Agenda+ to check if we should change CSSOM to say that the resolved value of `line-height: normal` is `normal`

**Comment by dbaron** [comment]
I filed [bug 1536871](https://bugzilla.mozilla.org/show_bug.cgi?id=1536871) to change this behavior in Gecko.

**Comment by MatsPalmgren** [comment]
I don't really understand why the `line-height` property is singled out. Pretty much all of the properties where the resolved value = used value in [this  list](https://drafts.csswg.org/cssom/#resolved-value) may have different used values on each fragment. E.g. `padding-top:10%` on a block that is fragmented has 0px on all fragments except the first, unless ofc `box-decoration-break:clone` was specified, and if so there's no guarantee that the percentage basis is the same for all fragments so they may have a different used value in that case too.

IIRC, Gecko returns the used value for the first fragment for all these properties. It seems inconsistent to me to single out `line-height` as an exception when other properties have the same issue.  For that reason it seems better that Blink adopts the WebKit/Gecko behavior.  A pixel-value also seems more useful to authors than `normal`, even if the value can potentially be different in other fragments if they exist, but as I said, that's no different from padding/border/margin etc.

(Ideally, there should be an API for getting the values of all fragments, but that's a separate issue.)

**Comment by emilio** [comment]
Also, Gecko does have internal line-height values for form controls that right now are unobservable via the computed style (`-moz-block-height`) thanks to this property returning the used value. We'd need to figure out what to return for those, which is unfortunate.

**Comment by kojiishi** [comment]
Happy to discuss what we can do for better web compat. The context was that, @joonghunpark wanted to contribute the change to Blink, but we didn't understand what the desired behavior is, hence he came here to ask.

Do other browsers match to WebKit? I read @litherum's explanation, and also @joonghunpark showed me the WebKit code. If this is what other browsers do, this is a simple fix, and fast to compute. We can try to see if we can safely change. This is not a used value though, so it maybe nice to update the spec.

If other browsers do it differently, we may need to discuss what is the desired behavior. I wish it be simple and fast since we need to compute it for `getComputedStyle` regardless author needs it or not, but I don't have other strong opinions.

**Comment by kojiishi** [comment]
@MatsPalmgren 
> IIRC, Gecko returns the used value for the first fragment for all these properties. It seems inconsistent to me to single out line-height as an exception when other properties have the same issue.

Blink does that too, taking the first block fragment. This is the first case for Blink to handle inline fragment though, and there are more special cases to consider than other properties, so I'd like to understand what other browsers do.

**Comment by frivoal** [comment]
> I don't really understand why the line-height property is singled out. Pretty much all of the properties where the resolved value = used value in this list may have different used values on each fragment

* We're not talking about fragments here, but about text runs, or even parts of text runs. This may be considered sorta similar if you want to, but no fragmentation (either in the multicol/pagination sense, or in the line break sense) needs to occur here; we just need font fallback to happen. We may want to deal with these chunks the same way we deal with Fragments. Or not. I'd lean towards not, because I don't think it is specified anywhere if and how we're supposed to slice text runs into multiple chunks based on font fallback (and/or other things?), so it's hard to talk about the height of the first one until we agree on what's supposed to be in the first one. 

* Assuming I understand it correctly the cold snippet that was shared for webkit without looking up the functions it calls, and assuming it was described correctly, the behavior described as the webkit behavior does not give the height of the not the first chunk: If gives the height of a hypothetical chunk with text from the first available font. You may not have one of these, and even if you do, it may not be the first one. Let's say your font stack is `"times new roman", "hiragino mincho", serif`, that both `times new roman` and `hiragino mincho` are available, and that all the text in the element is in Japanese. The actual line height (of all text runs / fragments / chunks) will be based on `hiragino mincho`, but the getComputedStyle as described above would return the height of `times new roman` alone.

I think we could do a number of variants:
1. return `normal` as a  keyword.
2. return the theoretical height based on the first available font, regardless of whether it is actually used.
   Possible nuance: the [latest version of the spec text](https://github.com/w3c/csswg-drafts/pull/1993/files#diff-63ba98ee4330d917b726501a4e17046aL1473) includes (based I believe on @dbaron saying that this was needed):

   > User Agents may use different sets of font metrics when determining <var>A</var> and <var>D</var>
   > depending on whether the <span class="propinst-line-heigh">'line-height'</span> property
   > is 'normal' or some other value,
   > for instance taking external leading metrics into account
   > only in the 'normal' case.
   
   Since we're not returning something based on actual layout, which of the possible font metrics are we using? presumably the one that gets used for the `normal` case, but given that the code snippet in the first comment talks about "the metrics" of  "the font" when there are multiple fonts each having multiple metrics, I am not sure this nuance is taken into account, so maybe not.

3. return the actual height of the first inline box (i.e. from the beginning until a line break, or the start of a different inline, whichever comes sooner), enclosing all glyphs actually used, going from the tallest ascender to the deepest descender, including the [strut](https://drafts.csswg.org/css2/visudet.html#strut).

   Variants:
   1. if the element starts with an atomic/replaced inline, count the height of the first inline box after that
   2. if the element starts with an atomic/replaced inline, return the height of the [strut](https://drafts.csswg.org/css2/visudet.html#strut), i.e. the theoretical height based on the first available font.
   
   Further nuances:
   * If the anchor point of a float or an abspos comes in the middle of that box, does that count a cutting that box in two or not?
   * If we have some other formatting changes, within the line (say, a color change), does that count as splitting the box or not? If we have `<p>aあ<span style=color:red>अ</span>`, and we're asking for the line height of the `<p>`, we we work with the union of the Latin and Japanese fonts only, or do we include the Devanagari one as well? How about if the span is unstyled?
   * If the element starts with a block level descendent, do we look at the first inline box after that, or to we go pretend there's an empty inline at the start, and therefore return the height of the [strut](https://drafts.csswg.org/css2/visudet.html#strut)?
4. return the actual height of the first non empty inline box chunk: based on the height of first glyph actually used (or equivalently, on the height of the first run of glyphs that all come form the same font).

(1) is what Blink does now. (2) Is what I believe webkit does now. If Firefox does something based "on the first fragment", I suppose it does one of the other variants, but I'm not sure which, or maybe it does (2) as well.

Doing anything other than (1) needs us to dig into the details of the various variants. Given that no use case has been brought up so far, and that Chrome shipping variant (1) is fairly strong evidence that this behavior is web compatible, I'd rather do that.

**Comment by emilio** [comment]
FWIW, what Gecko ends up doing is here:

  https://searchfox.org/mozilla-central/rev/7c20ad925005fbad7b8e08813115f1ec7fa1c248/layout/generic/ReflowInput.cpp#2819

Using the font metrics of the first available font as specified by the style of the element. The default value for what to do is 2, which is `eCompensateLeading`, so:

  https://searchfox.org/mozilla-central/rev/7c20ad925005fbad7b8e08813115f1ec7fa1c248/layout/generic/ReflowInput.cpp#2831

  https://searchfox.org/mozilla-central/rev/7c20ad925005fbad7b8e08813115f1ec7fa1c248/modules/libpref/init/all.js#305

Then we adjust for the minimum font-size specified by the user (so that it's not reflected in the computed style), and for zoom here, though those are less interesting special-cases:

  https://searchfox.org/mozilla-central/rev/7c20ad925005fbad7b8e08813115f1ec7fa1c248/layout/style/nsComputedDOMStyle.cpp#2578

So no post-layout-dependent value for `normal`.

**Comment by frivoal** [comment]
Thanks @emilio. Unless I misunderstand something, it seems that getComputedStyle on `line-height: normal` does not, unlike what @MatsPalmgren suggested it might do, return the height of the first fragment (regardless of how you define fragment).

So I still think that returning `normal` as a keyword, rather than some artificial measurement of what the line-height might end up being, is preferable. getComputedStyle is generally attempting to return the computed value, and mostly only returns post layout used values when compatibility requires. In this case, compat doesn't seem to require it (since chrome can without issue do something else), and what webkit and gecko are returning aren't actually post-layout used values.

If we're actually trying to expose font-derived metrics so that people can do useful things with them, I think we should rather look into that on the houdini side, rather than try and shoehorn them through an API that doesn't have sufficient granularity anyway.

**Comment by kojiishi** [comment]
Thank you @emilio from me too, great to know Gecko doesn't return the used value.

Given Gecko and WebKit return somewhat similar logic and it's not expensive, I'm open to either option. Returning `normal` as proposed by @frivoal is fine. We can also try to match to WebKit if doing so is desired and see if the change can stick.

**Comment by emilio** [comment]
Hmm, as I wrote the patch to do this in Gecko, I realized that returning the computed value for line-height is not as easy, since `line-height: <number>` is defined to compute to a number, but Blink returns a `px` for `<number>` line-height.

Is Blink willing to try changing this @kojiishi?

Should line-height compute to `<length>` instead? That seems somewhat undesirable though, as in Gecko we account for min-font-size for numeric line height, but not for `Em`s.

**Comment by MatsPalmgren** [comment]
@frivoal I don't see any discrepancy in what @emilio and I said about how the value is calculated above. He was just a lot more detailed and pointed to the actual code (and if you look at that code, `mFrame` in there is the first fragment I was referring to).  Anyway, the only layout-dependent part of that code is `-moz-block-height` which we are [unshipping](https://phabricator.services.mozilla.com/D25118). The remaining part is a fairly straightforward calculation from the font metrics of the first available font from the style, as specified in CSS2.  I really don't see why this is controversial or complicated to implement (and as our code shows - it's not).  Perhaps you misunderstood and thought I was referring to the _line height_ of the first line-box or something?  That's a separate concept and not what I meant. Sorry for any confusion.

**Comment by MatsPalmgren** [comment]
@frivoal said:
> Chrome shipping variant (1) is fairly strong evidence that this behavior is web compatible

Well, Firefox and Safari is shipping the resolved pixel-value, which is fairly strong evidence that that behavior is web compatible too.

**Comment by MatsPalmgren** [comment]
I don't think we should return the computed value, given that no browser implements it like that.  Given that Chrome is resolving `<number>` to a pixel-value, I don't see why it can't do the same for `normal`. It's fairly straight-forward to implement if you look at the links @emilio posted above. I don't see why it would be more complicated to implement in Blink.

I don't see any strong reason why Firefox/Safari should change their decades-old behavior that implements _literally_ what the CSS2 spec says. I'd prefer that Chrome implement the spec instead.

**Comment by kojiishi** [comment]
@emilio:
> Is Blink willing to try changing this @kojiishi?

Created a [test@jsbin](https://jsbin.com/bisopel/edit?html,output), it looks like `normal` is the only case we differ. I can try, but it means all other browsers also need to change. We should probably not try to change behaviors where all browsers are interoperable today. Does this sound reasonable?

@MatsPalmgren:
> I'd prefer that Chrome implement the spec instead.

We can try it out, but because no one implements the spec (used value) today, for Blink doing so will create another new interop problem to all of us. I would rather prefer to change the spec to allow Gecko and WebKit behaviors, and to try to change Blink to match to WebKit.

To recap, for `normal`, Edge and Blink return `normal`. Gecko and WebKit return an estimated value from font metrics (and some other info in Gecko), but the logic differ by large.

@litherum is concerned about the breakage, which is understandable. We know a lot of pages already detect browsers and run different code, so Blink and Edge returning `normal` today does not prove it's safe to change. With @joonghunpark motivated to work on this (thanks!), Blink can try to return an estimated value if WG is happy to change the spec.

IIUC @frivoal's point is that, since the returned length are not reliable nor interoperable, he prefers not to return any length. It has a point, and I'm fine with it too.

I'm also fine to allow both as I've not seen complaints from authors yet, but I guess we prefer not to do it.

**Comment by emilio** [comment]
> Created a test@jsbin, it looks like normal is the only case we differ. I can try, but it means all other browsers also need to change. We should probably not try to change behaviors where all browsers are interoperable today. Does this sound reasonable?

Sure, but that means that either the css-inline definition needs to be changed to make numbers compute to length, or that CSSOM still needs to mention that line-height has a special resolved value, and define it properly. @frivoal, opinions?

**Comment by emilio** [comment]
Hmm, and the css-inline definition cannot change, since the computation is visible in terms of inheritance, so...

**Comment by emilio** [comment]
That is, the following should show 64px 64px 32px 32px if we show "resolved" values, `2 2 2 2` if we show computed values:

```html
<!doctype html>
<div style="line-height: 2; font-size: 16px">
  My line-height should be 32px.
  <div style="font-size: 32px">
    Mine should be 64px
  </div>
</div>
<div style="line-height: 2em; font-size: 16px">
  My line-height should be 32px.
  <div style="font-size: 32px">
    Mine should still be 32px
  </div>
</div>
<pre id="log"><script>
  for (const d of document.querySelectorAll("div"))
    document.writeln(getComputedStyle(d).lineHeight);
</script></pre>
```

I think resolving some values but not others is quite inconsistent.

**Comment by kojiishi** [comment]
I agree it's inconsistent. I think what Gecko and WebKit returns today is not a used value, and that it's been inconsistent already. Do you agree what Gecko returns today is not a used value? If our understanding on this point is different, I think we should try to sync better first.

**Comment by kojiishi** [comment]
[This test@jsbin](https://jsbin.com/papelec/edit?html,output) should show the same value 3 times if the resolved value is "the used value of the first fragment". No browsers do it today.

I'm fine with any of these options:
1. The resolved value is `normal`, matching to Blink and Edge.
2. The resolved value is "an approximate estimated value based only on the first available font of the element", matching to Gecko and WebKit.
3. Allow both of above. No browsers need to change.

Either way we go, I think we should update the spec.

Does this explain my opinion better?

**Comment by emilio** [comment]
I disagree, what we return is the value for line-height that is used during layout. That may end up not being the actual height of the line, but the used value of the line-height property is what we return.

**Comment by emilio** [comment]
I guess there can be a difference in what the used value of the line-height property means... But yeah, I agree with you.

**Comment by MatsPalmgren** [comment]
@kojiishi I think the way you present the options is slightly misleading though.  Edge will soon be based on Blink, so there's only one UA doing option 1, IMHO.  So here's the list of options as I would present them:
1. The resolved value is `normal`, matching Blink.
2. The resolved value is the [used value as specified by CSS2](https://www.w3.org/TR/CSS22/visudet.html#propdef-line-height) for over a decade, matching Gecko and WebKit.
3. Allow both of above. No browsers need to change.

**Comment by MatsPalmgren** [comment]
@emilio wrote:
> I disagree, what we return is the value for line-height that is used during layout.

Indeed, me too.  There seems to be some confusion in this issue about what the used value of the `line-height` property is.  That's odd, because [the spec](https://www.w3.org/TR/CSS22/visudet.html#propdef-line-height) is utterly clear on this:

> **`normal`**
>     Tells user agents to set the used value to a "reasonable" value based on the font of the element. The value has the same meaning as `<number>`. We recommend a used value for 'normal' between 1.0 to 1.2. 
> **`<number>`**
>     The used value of the property is this number multiplied by the element's font size.

Given those definitions and the fact that Blink returns a pixel-value for `<number>`, it seems it could trivially implement what the spec says.

To highlight exactly how Gecko does it, here's the [key lines](https://searchfox.org/mozilla-central/rev/7c20ad925005fbad7b8e08813115f1ec7fa1c248/layout/generic/ReflowInput.cpp#2810,2824-2826,2832-2835).

**Comment by kojiishi** [comment]
@MatsPalmgren I'm just asking the logic to be described more clearer in the spec, because our engineers could not read the desired logic from the spec. Thanks to you and @emilio pointing to Gecko's code, I think I can understand that. I also looked at WebKit's, which looks a bit different from Gecko's.

I'm fine with whichever options, or with the one @frivoal proposed, or with something else. My request is just to describe the logic more clearer to the spec so that we can implement. Did this explain better?

To explain our problem better, we were reading the [Resolved Values spec](https://drafts.csswg.org/cssom/#resolved-values), which says "The resolved value is the used value" for the `line-height` property. The [Used Values spec](https://drafts.csswg.org/css-cascade-4/#used-value) says:
> The used value is the result of taking the computed value and completing any remaining calculations to make it the absolute theoretical value used in the layout of the document. If the property does not apply to this element, then the element has no used value for that property.

We could not read this paragraph to the logic you quoted, hence asking better clarification in the spec.

**Comment by kojiishi** [comment]
@frivoal @fantasai are you ok for Blink to try to match to WebKit? IIUC you want Gecko and WebKit to change to return `normal`, correct?

**Comment by frivoal** [comment]
@kojiishi I agree with your logic (in comment https://github.com/w3c/csswg-drafts/issues/3749#issuecomment-477992347), and prefer option 1. I wouldn't object to option 2, but then I'd hope it would be defined precisely, which I don't think is the case today. option 3 is not terrible, but it just pushes the problem down the line.

@MatsPalmgren The bit of spec you quoted in https://github.com/w3c/csswg-drafts/issues/3749#issuecomment-478187692 is known to be wrong, as no browser implements `normal` as being equivalent to some number in the 1.0 to 1.2 range, and instead all browsers implement it as a union of the ascenders and descenders of fonts actually in use. We have a WG resolution and spec text to fix that (https://github.com/w3c/csswg-drafts/pull/1993), but unfortunately, not active CSS2.1 editor to apply the fix at the moment :( Either way, this is about the computed value, not the value returned by getComputedStyle, which may or may not be the same (and in this case, isn't).

**Comment by kojiishi** [comment]
@frivoal 
> I agree with your logic...

I think your proposal is very reasonable, but when @joonghunpark is willing to try to change Blink, @litherum showed a mild concern on the change, and @MatsPalmgren is very strongly against, I think choosing easier option for all of us might be worth considering, as long as you and @fantasai can live with it.

**Comment by frivoal** [comment]
I don't prefer returning a numeric value, but I don't oppose it either. If we chose to go that way, I would hope that we define how it's calculated though.

**Comment by kojiishi** [comment]
Thank you @frivoal for allowing our lives easier. @fantasai can you live with this? I could not read your opinion from the IRC log.

> I would hope that we define how it's calculated though.

I prefer that too. A proposed change to [CSSOM Resolved Value](https://drafts.csswg.org/cssom/#resolved-values) would be moving `line-height` to its own group, saying like:
> The resolved value is approximately estimated value from the first available font, even when the box does not have non-empty line box.

@MatsPalmgren are you ok with this?

**Comment by kojiishi** [comment]
gentle ping, any idea to move this forward?

**Comment by dbaron** [comment]
So I think one of the things that's difficult here is that different people in the conversation have different understandings of how `line-height` works at layout-time.  This is partly a result of the extended discussions we had a few years ago at the Tokyo face-to-face meeting (at Keio University's Mita campus), which are not currently reflected in any spec.  These discussions included the questions of how line-height works on elements that include multiple fonts within their text, and what answers to that problem produced better results for baseline consistency if the font fallback only occurred within some lines of a block or within some elements within the lines of a block, and what `normal` means in the context of these conclusions and in the presence of different internal and external leading metrics (and perhaps whether those metrics should be used for `line-height: normal`) across the fonts used.  I think there were some other issues as well. If there's at least a clear reference describing those topics and our conclusions that we can point the participants in this conversation to, that might help clear things up a bit.

Then there's additional the question of whether the things that we decided at that meeting are actually web-compatible, and also the other questions of what to do about the non-interoperable cases that we didn't decide about at that meeting.  Getting things written in a spec sooner rather than later would also help answer this... and may even affect the answer (since changes that are web-compatible now might not be five years from now).

**Comment by zcorpan** [comment]
WebKit bug for the line-height change: https://bugs.webkit.org/show_bug.cgi?id=201296

**Comment by joonghunpark** [comment]
I've read the reached conclusion here now, and happy to see that.
Gecko has https://bugzilla.mozilla.org/show_bug.cgi?id=1536871 for that,
and Chrome already has the behavior.
Then I will take https://bugs.webkit.org/show_bug.cgi?id=201296 on WebKit,
and address it.

**Comment by emilio** [comment]
Note that we still haven't shipped to release that change in Gecko. Though we haven't heard any compat issues since it landed, so we should probably try to do that.

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1579624 should enable it for all users starting with Firefox 71. If we get no reports after a while I guess closing this should be fine.

**Comment by joonghunpark** [comment]
With https://bugs.webkit.org/show_bug.cgi?id=201296,
now WebKit has the same behavior with Blink and Gecko, FYI.

**Comment by fantasai** [comment]
Agenda+ to check in on this resolution. If I understand correctly, the CSSOM spec and maybe also css-inline needs to be updated to say that 'normal' returns 'normal', and everything else returns an absolute length for gCS()?

**Comment by joonghunpark** [comment]
I think it is.
Currently Blink, WebKit, FF works in the same way,
i.e.
specified value -> resolved value
normal -> normal
number -> pixel
percent -> pixel
