### ISSUE TITLE
[css-lists] Is the list-item counter increment for list items reflected in the computed style?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3769]
@domenic raised this potential interop issue. Edge supports the list-item counter, but doesn't expose it in the computed style.

Reading https://drafts.csswg.org/css-lists/#declaring-a-list-item:

> (This has no effect on the values of the counter-* properties.)

I read it as "shouldn't be exposed in the computed style". But @MatsPalmgren disagrees with this (https://bugzilla.mozilla.org/show_bug.cgi?id=1539171#c3).

Given this requires some magic already I tend to think it shouldn't be exposed in the computed styles, though Mats thinks it's better.

Could this be clarified?

**Comment by MatsPalmgren** [comment]
I disagree that getComputedStyle should lie about the actual value of any of the counter-* properties.
I see no benefit to anyone in doing that and I also don't think it's needed for web-compatibility.

**Comment by MatsPalmgren** [comment]
BTW, what the initial value of the `counter-increment` property is has already been resolved (recently) in issue #3686 (for those that didn't see that).

**Comment by fantasai** [comment]
@emilio I think your reading of the spec is correct, at least, I think that's what it intends. What it *should* say being a separate question. :)

@MatsPalmgren Gecko implementers in particular have told use repeatedly that they dislike cross-property dependencies for computed style, so it's interesting that you want the opposite thing here? Fwiw I think I agree with @emilio that this shouldn't be exposed. It's an implied increment unless you make it explicit.

**Comment by MatsPalmgren** [comment]
@fantasai dependencies on `display` is not a problem - we have a lot of those already ;-)

What you say about the intention seems to contradict what @tabatkins said in https://github.com/w3c/csswg-drafts/issues/3686#issuecomment-472132164 "When you need to interact with the list-item counter explicitly, the code you write under (A) is identical to what you'd write if list-item was just set up in the UA sheet, or in an author sheet."

Since the resolution was (A), that's how we implemented it (by synthesizing a computed value), since that's basically "set up in the UA sheet" (with the selector is "display is list-item").

**Comment by fantasai** [comment]
@MatsPalmgren I think the distinction here is whether it gets synthesized at computed-value time or used-value time. Certainly by used-value time, that's what we should have.

**Comment by MatsPalmgren** [comment]
#3686 is explicitly about the _initial value_ - it even says so in the subject. So I don't see how the resolution can be interpreted in any other way than being about the computed value. (You are of course free to reverse that resolution here, but I don't see why given that it's less than two weeks ago it was discussed).

Fwiw, I don't feel that strongly either way. I just think a computed value is a more honest way to do it. It makes it explicit for authors to see rather being something magic that happens at used-value time, unless they specify an increment. Also, a computed value makes it possible to inherit (not saying that's a particularly useful feature or anything, just that "it works normally" is nice).

**Comment by fantasai** [comment]
@MatsPalmgren The issue was about that, but the discussion covered what happens on non-initial values. @dbaron's summary of the options in https://github.com/w3c/csswg-drafts/issues/3686#issuecomment-468098431 is pretty clear about that. Fwiw, I don't feel too strongly about used-value vs computed-value time; if there's a good reason to go with one vs the other it's fine with me.

**Comment by emilio** [comment]
I don't like to add code to the generic "fixup the style" mechanism that deals with all the dependencies between properties, but that's a bit of a personal preference in this case since as mats noticed we have plenty of other dependencies on `display` already. So I don't think there's a great argument for one against the other either...

Biggest argument for used-value time would be backwards compat. However the risk doesn't seem _terribly_ high here (unless proven otherwise of course).

It does feel weird that you have a computed value that you cannot override changing the specified value except overriding the counter again... It's a bit more magic than usual. But again that's a bit subjective.

Maybe @lilles has any opinion from the Chromium side? I just noticed https://bugs.chromium.org/p/chromium/issues/detail?id=946176 was filed not long ago.
