### ISSUE TITLE
[css-text-4] white-space:break-spaces is in level 3 but not level 4

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3794]
https://drafts.csswg.org/css-text-3/#white-space-property
https://drafts.csswg.org/css-text-4/#white-space-property

Is this an intentional deletion?

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/pull/2841

**Comment by litherum** [comment]
cc @frivoal

**Comment by frivoal** [comment]
No, this is not intentional. Level 4 is somewhat under-maintained at the moment, and all the stuff that relates to line-breaking and white-space processing is likely out of sync with the content of level 3.

Thanks for pointing it out, this is something we ought to address before long. There are a couple of open issues on that general area on Level 3, but once they're settled, we should make sure Level 4 is consistent with what we ended up with.

**Comment by kojiishi** [comment]
It'd be great if we can resolve this issue, as we plan to implement the `text-wrap` property.
/cc @fantasai
