### ISSUE TITLE
[various] Holistic review/proposal of color-modifying things

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3807]
@fantasai and I have spent the day reviewing all the various proposals regarding modifying the colors on the page (dark mode, high-contrast, etc), and have come up with an integrated set of proposals that we think address all the use-cases and interact fairly cleanly.

"High-contrast" proposal
========================

```
@media (forced-colors: none | active) {...}

forced-color-adjust: auto | none
```

[Undeprecate some System Colors, and add a few new ones](https://github.com/w3c/csswg-drafts/issues/3804) to match with MS's [High Contrast feature](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HighContrast/explainer.md) (which isn't actually about high contrast, but rather about forcing apps/websites to use a specific, small set of user-chosen colors-- which may or may not be high contrast, and in some cases may specifically be low-contrast).

When forced-color-adjust is `auto` and the user is forcing colors, then the [set of properties defined in the MS proposal](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HighContrast/explainer.md#css-properties) have their colors overridden to use the system colors defined above. Authors are encouraged to use these system colors for properties that aren't overridden to create a coherent page design when colors are forced.

If the forced background is dark (based on Lab lightness), (prefers-color-scheme: dark) must match; mutatis mutandi for light. This way, websites that support light/dark color schemes will adjust automatically to more closely match the color scheme implied by the forced colors. (This replaces the white-on-black and black-on-white values of the MSFT high-contrast media query proposal.)

The (prefers-contrast) MQ is unrelated and unchanged.

(We might further consider folding 'forced-color-adjust' into the existing 'color-adjust' property somehow, but can discuss whether and how to do that later.)

Light/Dark color scheme proposal
================================

```
@media (prefers-color-scheme: light | dark | no-preference)

color-scheme: only? && [light | dark | <custom-ident>]+

<meta name=color-scheme content="(same values)"> sets initial value of 'color-scheme' on the root.
```

Processing rules as defined by Rune <https://lilles.github.io/specs/supported-color-schemes.html>

If we can change system colors to compute to themselves, then 'color-scheme' changes the used values of the system colors on the element. If not, 'color-scheme' on the root does so for the whole page. In either case, the affected system colors are at least the set defined for "high contrast".

'color-scheme' must also affect input & scrollbar styling.

color-filter proposal
=====================

* [Sydney 2018 discussion minutes](https://lists.w3.org/Archives/Public/www-style/2018Jul/0023.html)
* Issue #2875 for rough proposal

This seems like an early attempt at ability to auto dark-mode a page, but doesn't seem particularly useful now that color-scheme/etc has reasonable consensus.

It might be useful to expose as a quick-and-dirty way for an author to dark-mode their page, but are there use-cases beyond auto-darkmode-ing? If not, maybe just switch this to a keyword property (adding to 'color-adjust'?) that can do "smarter" inversion based on luminance.

inverted-colors proposal
========================

```
@media (inverted-colors: none | inverted)
```

Supported in Safari; it's not clear whether "inverted" means all-pixels inversion, or color-inversion only, or what?

Important to distinguish these, as what authors do in response can vary based on which inversion is performed. (The `img { filter: invert(100%); }` rule in the spec's example, for instance, is only useful for all-pixel inversion; it would be *harmful* for a colors-only inversion.)

So, we either need to *specify* what kind of inversion is allowed to be performed, or add more values capturing the distinctions among the types.

**Comment by AmeliaBR** [comment]
I strongly support the goal of making the various media queries logically independent  (e.g., having `forced-colors` separate from the light/dark mode, separate from high/low contrast preference).  I think the proposals above achieve that goal for those features.

Authors can always use boolean combinations of media queries as needed, e.g. `@media (prefers-contrast: high) AND (prefers-color-scheme: dark) AND NOT (forced-colors) { /* author's high-contrast dark scheme */ }`

I'd recommend also splitting the relevant section of [Media Queries 5](https://drafts.csswg.org/mediaqueries-5/) to clearly separate out the user preference media queries which _ask_ the author to make changes (`prefers-reduced-motion`, `prefers-color-scheme`) from the media queries that _advise_ the author that the user agent is making its own modifications and some minor adjustments may be required (`forced-colors`, `inverted-colors`).

I wonder if `inverted-colors` could be generalized as `forced-filter`, to also include "night light" effects that change the brightness and hue of the screen.  e.g. `@media (forced-filter: invert)` vs `@media (forced-filter: sepia)` or just `@media (forced-filter)` to indicate that the user agent or OS is filtering the final rendered colors.

That would also avoid any confusion about how invert mode interacts with individual color values — it's a filter effect that applies to the full screen, although it is possible to revert the effect with opposite filters on individual elements. (I _think_ this is how the Safari implementation works, with the "reverting invert" filters on images and videos now specified in the user style sheet.  So specifying the same rule in an author stylesheet would have neither harm nor benefit.  But someone who is familiar with the latest WebKit changes needs to confirm.)

The special cascade order rules for `forced-color` / `-ms-high-contrast` might also apply for `forced-filter` and other “forced” UA media manipulations. Whether this is necessary would depend on how many other user-agent style tweaks get added in those conditions.  But for example, maybe I have an `<img>` that is a black line drawing on a white background and it _should_ actually get inverted to white on black when the user has inverted the rest of the screen, so I want to use `img { filter: none}` to cancel out any user-agent stylesheet that double-inverts images.

**Comment by smfr** [comment]
`@media (inverted-colors: none | inverted)` is about the screen-level color inversion accessibility feature (possibly with some re-inversion of images/video). It's a mode in which individual colors can't be independently adjusted; it's akin to a filter:invert() on the document.

**Comment by FremyCompany** [comment]
Hooking this thread to provide my own feedback.

Before anything, I wanted to say I generally approve the compromise solution outlined by Tab and Fantasai above:

> ✔ proposed renaming: `forced-colors[-adjust]` vs `high-contrast[-adjust]`
> ✔ proposed interaction with `prefers-color-mode: dark` (though I would add a note that it's preferable to compare the lightness of the forced text color vs the forced background color, and return based on which one is lighter)
> ✔ proposed no direct interaction with `prefers-contrast` (though UAs supporting `forced-colors` could auto-detect user preference for high contrast based on the contrast ratio between the forced text color vs the forced background color; if those are high-contrast and forced-colors is enabled, then `prefers-contrast` should also be enabled)

Now, back on to the MS proposal. My main concern is with the Cascade Order section:

> Given an element and a declaration from a CSS rule whose selector matches that element, the application of that declaration will be suppressed if all of the following conditions are met:
> 1. The declaration is for a CSS property in the set of properties that are adjusted for high contrast (as defined in CSS Properties)
> 2. High contrast mode is enabled in the host environment
> 3. The computed value of high-contrast-adjust on the element is auto
> 4. The rule is not contained (directly or indirectly) inside an @media block matching the high-contrast media feature
> 5. The rule is not defined in the default UA style sheet
> 
> If all of the above conditions are met, the computed color value of the CSS property is overridden by a system color value.

It's way too complex. I understand that this is how things used to work in IE, but I don't think we want to import this complexity in modern browsers.

**First point:** My understanding is that if you want to use your own colors in Edge, you should always set `forced-colors-adjust: none` otherwise the backplate will be drawn with the forced background which is unpredictable. Therefore, I think we should remove condition `2.` and only consider whether `forced-colors-adjust` is set to `none` or not. Compatibility with `-ms-` prefixed content can be achieved by automatically setting `forced-colors-adjust` to `none` when a declaration for a `color` property is detected in an `@media(-ms-high-contrast)` rule, which can be done at parse time instead of having to be done every time things get computed.

**Second point:** Disabling declarations based on the computed value of a property is against the normal flow of property computation, and would require a special computation pass just for `forced-colors-adjust`, and that is cumbersome. 

Based on these two points, I propose an alternative solution: drop the entire cascade section, and replace it with the following text: 

> after cascade as been applied (and if the `forced-colors` mode is active), elements which have their `forced-colors-adjust` property set to `auto` have the specified value of all its properties on which `forced-colors` apply set to `revert` (this effectively inhibits any author-provided value, and revert to the default ua stylesheet).

Gecko and Servo already support the `revert` value, and so does Webkit. I therefore guess it wouldn't be very complex for Blink to do as well. This would be way simpler to implement than the proposed cascade behavior for almost the same result (except the minor change I introduced in my first point).

**Apart from those two points about the cascade order,** I would like to point out again that I am in favor of the general proposal.

**Comment by AmeliaBR** [comment]
I am very intrigued by @FremyCompany's suggestion re using `revert` instead of the proposed cascade manipulation.

To clarify, this would mean that turning on a high contrast mode or other forced-color effect would have the following effects:

- Change the system colors (& make any extra changes to the user agent stylesheet that can't be handled just by system colors).
- Trigger the `forced-color` media condition.
- Set `forced-color-adjust: auto` on the document root (so it inherits into the whole document unless the other overrides it).  This could be represented by a conditional rule in the user agent stylesheet:
   ```css
   @media (forced-colors) {
     :root { forced-color-adjust: auto }
   }
   ```

From there, all values from the user agent and author stylesheet would cascade as normal.

_After_ cascade — and _separate_ from whether a high contrast mode is on or not — the `forced-color-adjust` property would have the following effects when it computes to `auto`:

- `revert` any author-specified values on the element for [the list of color-related properties](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HighContrast/explainer.md#css-properties)
- Add a solid-color text backplate (that matches the system background color) behind any text glyphs rendered for the element.

I do like this approach, especially if the existing `ms` media query can be made to work with it (with minimal magic).

I would suggest that `auto` is no longer the best keyword for something that causes a change by itself.  Maybe `forced-color-adjust: on` vs `off` makes more sense?  But then again, sticking with the `auto` and `none` keywords makes it easier to define the Microsoft `high-contrast-adjust` as a direct synonym.

**Comment by grorg** [comment]
> @media (inverted-colors: none | inverted) is about the screen-level color inversion accessibility feature (possibly with some re-inversion of images/video). It's a mode in which individual colors can't be independently adjusted; it's akin to a filter:invert() on the document.

To give a bit of history, this was originally offered as an accessibility feature and implemented at the system level - in that apps couldn't opt-out, and didn't even know it was happening unless they queried the system preferences (which I guess technically gave them a way to opt-out by pre-inverting things before they draw).

It was a popular feature, but the main complaint was that inverted images are wrong. So then came "smart invert", where everything was inverted except images and other media

Then we discovered that people would toggle this feature on and off depending on the page content. Basically they wanted either dark or light pages, and prefer to have their choice even if that meant the colours are all weird. So that's where we are today, and led to having a system preference for light/dark.

If the light/dark preference becomes widely adopted, we might not need the invert path any more.

**Comment by emilio** [comment]
I have various complaints about the high-contrast stuff:

 * The ability to override user preference using `high-contrast-adjust` that @MatsPalmgren has objected to in the past.

 * The dependency between high-contrast-adjust and basically all the color properties means that it's yet another property that needs to be cascaded early, which is not fun (probably wouldn't be a blocker though).

 * I find the `@media` block thing extremely weird / over-complicated. If we want to go that route, we also need to handle `<link media="">`, `<style media="">`, `@import url(...) <media>`, and all dynamic changes to those via the OM or attributes. I think implementing that properly is going to be a huge pain, and it really feels overkill for such a feature. I personally would prefer a simpler solution.

Regarding @FremyCompany's proposal of using `revert`, we probably would still need the extra priority to determine whether the value is `auto` anyhow, since we don't have the concept of cascaded values vs. computed values, we compute as we do the cascade. But it's the same complexity as the other model, and `revert` would respect user stylesheets (though again the first model condition about UA sheet could be made to respect user stylesheets as well).

**Comment by fantasai** [comment]
@emilio Please, let's not continue to call this “high contrast”. Rossen has already pointed out that it's also used to enforce low contrast, and we need to be clear when discussing it that it is not synonymous with a request for high contrast.

Wrt not being able to override... the user could theoretically set `* { forced-colors-adjust: auto !important; }`, which would prevent the page from making any customizations. I don't know too much about the use cases that prompted this property, but my inclination is, if MSFT has found this property to be necessary, we'll probably need to include it. However, I think they did find that usage declined significantly with their current version of the feature, so maybe it's not needed anymore. If they're continuing to ship it, though, I would like us to standardize it.

@grorg Dark mode is interesting, and I imagine in some cases it might be a user's base preference and for others they might prefer enforcing it. If inversion (rather than forced colors) is the path you're choosing for enforcement, I imagine you might end up with an option for "let the page do as it likes if it supports the appropriate color mode, otherwise invert". The media queries we have can express this state in case the author wants to query it and make adjustments... except we're not clear on the method of color inversion. If the author needs to invert images, or if it can depend on the UA doing so, or if hues will be distorted or preserved, those are important distinctions we need to be able to make. In other words, the inverted-colors MQ needs to be specific enough that the expected work the author needs to do is very clear and does not need to differ depending on the UA/OS/version, only on MQ values that they can legitimately query!

**Comment by FremyCompany** [comment]
The main reason the property is still needed, is that if you are building your own component, you need to be able to set the color of the text in that component to "DisabledText" when your component is disabled otherwise it becomes inacessible. Ditto for other custom states.

**Comment by astearns** [comment]
also resolved:

RESOLVED: Add the color-scheme property and meta with updated grammar and no 'only' property to Color Adjust spec instead of supported-color-scheme
RESOLVED: Move print-color-adjust property into the new spec

**Comment by fantasai** [comment]
OK, @tabatkins and I drafted up the spec text for all of this into https://drafts.csswg.org/css-color-adjust-1/ and https://drafts.csswg.org/mediaqueries-5/ based on the MSFT explainer, Apple proposal, WG discussions, and @FremyCompany's excellent [comment about cascading](https://github.com/w3c/csswg-drafts/issues/3807#issuecomment-481845423). Please review the drafts, especially css-color-adjust.

I've split out the `inverted-colors` issue into https://github.com/w3c/csswg-drafts/issues/3858.
There are also a number of follow-up issues reflecting details we ran into: https://github.com/w3c/csswg-drafts/issues/3846 https://github.com/w3c/csswg-drafts/issues/3848 https://github.com/w3c/csswg-drafts/issues/3849 https://github.com/w3c/csswg-drafts/issues/3850 https://github.com/w3c/csswg-drafts/issues/3855 We'd appreciate follow-up comments from y'all on whether we got those right or we need to further adjust the spec.

Please file more issue as you find them, or if there's anything you brought up here that didn't get adequately considered. Closing this one out based on this weeks' telecon resolutions and subsequent edits. Thanks!

**Comment by dbaron** [comment]
Hmmm, I thought what we'd agreed to resolve on was:

>  &lt;dael> astearns: Current suggestion is we put color-scheme in with a change to grammar such that you can only express the only keyword for the light theme

although the resolution following that is actually recorded as:

> &lt;dael> resolved: Add the color-scheme property and meta with updated grammar and no 'only' property to Color Adjust spec instead of supported-color-scheme

but the draft seems to have `only` without restriction.

**Comment by FremyCompany** [comment]
Yes, from what I understood we agreed that you can only use `only` if the set of modes you put in the property contains `light` somewhere in the list of supported modes. So we can do `light only` or `dark light only` but not `dark only` (with the assumption that we might relax this later whenever it appears all browsers/OS combinations support a `dark` theme by default, but in the meanwhile, we want to make it clear authors have to remain usable using the `light` theme regardless of the preference for dark they might express (even if on user behalf)).

**Comment by FremyCompany** [comment]
@fantasai Minor editorial issue, but it seems the link to `See [[!css-color-adjust-1#forced]] for details.` doesn't work and is rendered as plain text in the MQ5 spec.

Also, re-reading the list, I am curious as to why the `forced-colors` mode removes the box shadow. I had never considered it did, and I'm kinda wondering what the reasoning would be, given we have backplates under any text regardless. Remvoing `text-shadow` does make a lot of sense though, just wondering why `box-shadow` is also included in the list of things being reset.

**Comment by FremyCompany** [comment]
@fantasai Can we reopen this issue, or should we file new ones?

**Comment by tabatkins** [comment]
> but the draft seems to have only without restriction.

Yup, forgot about that as I was drafting from Rune's spec. Fixed now, with an explanatory issue.

**Comment by tabatkins** [comment]
@FremyCompany Open new issues.
