### ISSUE TITLE
[css-lists-3] Should unicode-bidi / direction apply to ::marker?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3809]
CSS Lists 3 currently lists `::marker { unicode-bidi: isolate; }` in its UA default rules. This is good, markers should be bidi isolated. However, unicode-bidi isn't listed in css-pseudo-4 as a valid property on ::marker. Options:

- Make `unicode-bidi` and `direction` apply to `::marker` and keep the UA rule.
- Just make marker's automagically bidi-isolated always.

@MatsPalmgren @emilio thoughts?

**Comment by MatsPalmgren** [comment]
Fwiw, here's our [current UA sheet rule](https://searchfox.org/mozilla-central/rev/6db0a6a56653355fcbb25c4fa79c6e7ffc6f88e9/layout/style/res/ua.css#129-134) for `::marker`.

> However, unicode-bidi isn't listed in css-pseudo-4 as a valid property on ::marker.

Please just remove all of the restrictions. It's better if `::marker` behaves exactly as `::before/::after` in terms of styling/layout. It literally follows the same code path as `::before/::after` in Gecko and I see no reason to change that. You could add a note there saying "we _may_ restrict which properties applies to `::marker` in the future if it proves impossible to implement in UAs or web compat demands it", if you think it's necessary (I don't).

**Caveat**: in Gecko, you need to use the `content` property to trigger the new code path. This is a temporary implementation restriction which we intend to fix so that the legacy code path for `list-style-type/image` synthesize a pseudo content node instead and then use the new path too. (We'll fix this soon hopefully.)

**Comment by fantasai** [comment]
`list-style: outside` marker box layout isn't defined, so applying properties like background or border or position or anything else that exposes the exact box dimensions isn't feasible right now.

**Comment by fantasai** [comment]
Therefore the whitelist. Happy to add things to the whitelist, but not if they expose things that aren't defined.
