### ISSUE TITLE
[selectors-4] additional resource state pseudo-classes for media elements

### ISSUE THREAD

**Issue by hober** [w3c/csswg-drafts#3821]
In [§11 Resource State Pseudos](https://drafts.csswg.org/selectors/#resource-pseudos) we currently have the `:playing` and `:paused` pseudo-classes, which collectively address the use case of a custom "play/pause" media control which should appear as a play button or as a pause button depending on the current play state of the associated media element. A bunch of us (@beccahughes @mounirlamouri @padenot @jyavenard @eric-carlson @jernoble et al.) would like to address several related use cases with additional resource state pseudo-classes:

* Whether or not the media element is [**muted**](https://html.spec.whatwg.org/multipage/media.html#concept-media-muted). Use case: styling a custom muted control. Proposal: mint a `:muted` pseudo-class.
* Whether or not the media element is currently **stalled** (see several paragraphs in the HTML spec starting at ["The **stall timeout** is a"](https://html.spec.whatwg.org/multipage/media.html#stall-timeout)). Use case: changing the appearance of a loading progress indicator to indicate that loading is currently stalled. Proposal: mint a `:stalled` pseudo-class.
* Whether or not the media element is currently [**seeking**](https://html.spec.whatwg.org/multipage/media.html#seeking). Use case: a custom seek control can reflect the case where a user is seeking using some other, UA-provided control. Proposal: mint a `:seeking` pseudo-class.

Currently, authors of custom media controls have to do some combination of UA-sniffing and other logic from script in order to handle these cases. Ideally, the appearance of such controls would be expressible in CSS, just as play state currently is.

**Comment by FremyCompany** [comment]
Looks good to me

Shameless plug: http://fremycompany.com/TR/2012/ED-css-content-state/#interactive

**Comment by tabatkins** [comment]
All these sound good.

For the volume one, is the issue that the UA can let the user dictate the volume, ignoring the `volume` attribute?

**Comment by jernoble** [comment]
@tabatkins, essentially yes. 

As a concrete example, some sites currently try to detect whether changing volume is supported by setting `video.volume` to some arbitrary value, and verifying whether that volume value "sticks". (Effectively, `let v = video.volume; video.volume *= 0.5; return v !== video.volume;`.) That doesn't work if the UA implements step 1 of the [effective media volume](https://html.spec.whatwg.org/multipage/media.html#effective-media-volume) algorithm.  We'd like to give those sites a way of determining this explicitly, without relying upon side effects or heuristics.

**Comment by tabatkins** [comment]
Cool, sounds good.  Been trying to think of decent names for the pseudo, tho, and am coming up blank. ^_^

**Comment by hober** [comment]
> Been trying to think of decent names for the pseudo, tho, and am coming up blank. ^_^

Yeah, same.

Would it help if I broke that one out into a separate issue?

**Comment by tabatkins** [comment]
Eh, sure. Might as well.

**Comment by AmeliaBR** [comment]
For starting the bikeshed debate on that separate issue (please copy over once there's somewhere to copy to):

- `:adjustable-volume`
- `:not(:user-volume)`
- `:not(:volume-locked)`
- `:volume-unlocked`
- Or maybe a set of `:volume()` variations, like `:volume(muted)`, `:volume(locked)`, `:volume(max)`…

**Comment by hober** [comment]
Okay, I moved the volume case over to its own issue, #3933. The three remaining cases in this issue should be really straightforward.

**Comment by tantek** [comment]
Please also add a :buffering (or :waiting) pseudo-class distinct from :stalled, at the same time as adding :stalled.

Use-case: showing loading/buffering spinner, often with a %, e.g. on Netflix.

I’d like to see :buffering defined similar to :stalled [https://html.spec.whatwg.org/multipage/media.html#event-media-stalled](https://html.spec.whatwg.org/multipage/media.html#event-media-stalled), however with the key difference that data *is* forthcoming. Similar to how the waiting event is defined: [https://html.spec.whatwg.org/multipage/media.html#event-media-waiting](https://html.spec.whatwg.org/multipage/media.html#event-media-waiting)

Alternatively I'd be ok with a :waiting pseudo-class that maps to the waiting event/definition (might be simpler for the platform / web-developers if we "just" do/keep a direct mapping of the pseudo-class to an existing HTML event name).

I do think it is important to add :buffering (or :waiting) at the same time as adding :stalled, in order to avoid having :stalled be errantly overloaded by implementers and/or web developers to handle the buffering use-case.

(Originally published at: https://tantek.com/2019/155/t2/)
