### ISSUE TITLE
[css-pseudo-4] should CSSPseudoElement have a pseudo() method?

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#3836]
https://drafts.csswg.org/css-pseudo-4/#CSSPseudoElement-interface

You can get to the pseudo-element of an element with `Element.pseudo()`.  But some pseudos are defined to have other pseudos hanging off them, like with `::part(label)::before`.  Does `CSSPseudoElement` need its own `pseudo()` method?

**Comment by emilio** [comment]
I'd much rather not make `Element.pseudo()` return pseudo-elements which are really other elements like `::slotted` or `::part`. They can match multiple elements at once I don't know what a sane return value for that would be.

**Comment by heycam** [comment]
That's a great reason for not doing it for those pseudos. :-)  Are there other pseudos where it still might make sense?

**Comment by emilio** [comment]
You could addres the `::marker` that `::before` and `::after` create themselves... But it'd be weird to be able to target them via this API but not via CSS Selectors.

**Comment by tabatkins** [comment]
> But it'd be weird to be able to target them via this API but not via CSS Selectors.

I've opened #3876 to discuss that, it is indeed weird.

**Comment by birtles** [comment]
Even if we don't have `pseudo()` on `CSSPseudoElement` itself, provided you can start a CSS animation/transition on the `::marker` for a `::before` (which I assume will be the case once #3876 is resolved), what should we return as the animation target in that case?

* Would it be a `CSSPseudoElement` with [`type`](https://drafts.csswg.org/css-pseudo-4/#dom-csspseudoelement-type) '::before::marker' and [`element`](https://drafts.csswg.org/css-pseudo-4/#dom-csspseudoelement-element) as per an un-stacked pseudo (i.e. the actual originating DOM `Element`)?
* Or would it have `type` '::marker' and `element` the parent `CSSPseudoElement`?
* Or just `type` '::marker' and the originating DOM `Element`? (Making it indistinguishable from the `::marker` pseudo on the `Element`.)

**Comment by tabatkins** [comment]
Should be the second; it's a ::marker whose originating element is the ::before.

**Comment by birtles** [comment]
Ok, I guess we need to change the type of [`CSSPseudoElement.element`](https://drafts.csswg.org/css-pseudo-4/#dom-csspseudoelement-element) from `Element` to `(Element or CSSPseudoElement)`.

**Comment by tabatkins** [comment]
Yeah. And add `.pseudo()` to `CSSPseudoElement`. ^_^

**Comment by heycam** [comment]
Maybe rename `CSSPseudoElement.element` to something like `parent`?

**Comment by heycam** [comment]
Also, what's the story for getting computed style of these "stacked" pseudo-elements?

**Comment by birtles** [comment]
> Maybe rename `CSSPseudoElement.element` to something like `parent`?

It used to be named that (or `parentElement` actually), but in #2816 it was pointed out that that was wrong and `originatingElement` was too long so it became `element`. In this world of stacked pseudos, maybe `parent` is actually now correct?

**Comment by Jamesernator** [comment]
I personally think `.pseudo` should be able to return a pseudo-element for *any* name rather than just the hard coded list of `::marker`, `::before` and `::after`.

Why? Well a pseudo-element is meant to be transparent as to whether or not it points to single element, multiple elements, text nodes, etc. Because of the way they are specified it's only possible to target all such components or none of them in CSS, similarly I think it should work identically with `.pseudo` that a `CSSPseudoElement` represents all parts that are used to construct that element.

This would work fine with `getComputedStyle` too as there's no way to actually style individual parts of pseudo elements. So even if a `::part(foo)` corresponded to 50 elements, a `::part(foo)` selector can only style all 50 or none of them, so `getComputedStyle` is consistent (assuming `getComputedStyle` is not allowed to leak styles out).

Also it'd be nice with [reference selectors](https://github.com/w3c/csswg-drafts/issues/3714) or similar ideas too as then you could do `someElement.pseudo("::part(name)").references = [partStyles]`.

**Comment by emilio** [comment]
Well, parts as well as slotted elements can have different styles even if they are the same part or slotted selector, because of rules in and outside the shadow tree respectively, so that just doesn't hold.

**Comment by Jamesernator** [comment]
> Well, parts as well as slotted elements can have different styles even if they are the same part or slotted selector, because of rules in and outside the shadow tree respectively, so that just doesn't hold.

No the elements that comprise of the parts can have different styles, the styles of an element are resolved from its `::part`, element, slotted, etc styles. But if you take a `.pseudo("::part(bar)")` on an element the styles applied via `::part(bar)` are necessarily unique from the rules of the cascade.

**Comment by lpd-au** [comment]
Would it be worth considering having two separate properties, `Element element` and `Element|CSSPseudoElement parent`?

**Comment by ExE-Boss** [comment]
@Jamesernator
Except that would violate the&nbsp;way `getComputedStyle(…)` is&nbsp;currently specified, as&nbsp;the&nbsp;computed style is&nbsp;the&nbsp;actual style used for&nbsp;rendering.

**Comment by fantasai** [comment]
Agenda+ to consider @lpd-au’s https://github.com/w3c/csswg-drafts/issues/3836#issuecomment-502344378

**Comment by fantasai** [comment]
Edits in. I had to add a new section to Selectors 4 also. See
https://drafts.csswg.org/selectors-4/#sub-pseudo-elements
and
https://drafts.csswg.org/css-pseudo-4/#cssom
once it all regenerates.

@frivoal @lpd-au @heycam Let me know if anything seems off, or if the edits seem to correctly reflect what we agreed here. (CSSOM stuff is not my forte, exactly.)

**Comment by frivoal** [comment]
Not an OM expert either, but it looks good to me.

**Comment by lpd-au** [comment]
This looks great to me, thanks for your work! :)

As a nitpick, I believe it would be helpful to readers for the definition of `parent` to say "[originating element](https://drafts.csswg.org/selectors-4/#originating-element) or [originating pseudo-element](https://drafts.csswg.org/selectors-4/#originating-pseudo-element)" for the spec reference, but maybe that's redundant and unnecessary since the rest of the definition already points to [sub-pseudo-elements](https://drafts.csswg.org/selectors-4/#sub-pseudo-element)... (I'm no expert either!)

**Comment by fantasai** [comment]
@lpd-au I think that would downplay the idea that an “originating element” can be either an element or a pseudo-element, i.e. that “originating pseudo-element” is defined as a sub-class of “originating element”. Since the next sentence explicitly mentions the case of having an originating pseudo-element, the intent should be clear from the spec already, so I think we don't particularly need to call it out. At least, that's my thinking. Lmk if that makes sense. :)
