### ISSUE TITLE
[css-easing] extend cubic-bezier() to take additional pairs

### ISSUE THREAD

**Issue by argyleink** [w3c/csswg-drafts#3838]
### Why
Physics aren't likely to land any time soon to help folks with spring, bounce or cliff effects, and there's big demand for these engaging and lifelike animation tactics. Due to lacking phsyics, folks bring in javascript animation libraries to do the work, or visit websites that generate 100s of keyframes, or just flat out abuse the `cubic-bezier()` function. JS libraries and `cubic-bezier()` abuse being the most common, since it's the easiest. 

Most of these workarounds result in difficult to manage, rigid or uncanny animations that don't make the web look very great at animation. 

### Examples
cubic-bezier()
https://codepen.io/AdrienBachmann/pen/VYVvGo

JS library (34kb)
https://codepen.io/rossorthwein/pen/XorVVV

### Proposal
I think we could pacify the need for physics by adding the ability for `cubic-bezier()` to take more points. Extend `cubic-bezier()` to chain/concat points together.

**Current**
![Screen Shot 2019-04-17 at 2 12 58 PM](https://user-images.githubusercontent.com/1134620/56321248-01940580-611b-11e9-94f0-02051fcd1606.png)

**Proposed**
Where we currently have 2 pairs passed into `cubic-bezier()`, we allow passing additional pairs so more points could be created. 

Explode out:
![austin-saylor-explode-out-ease-in](https://user-images.githubusercontent.com/1134620/56321526-bd553500-611b-11e9-8ddf-a2482183390c.gif)
![austin-saylor-explode-out-ease-in](https://user-images.githubusercontent.com/1134620/56321532-bfb78f00-611b-11e9-9aa6-e13d328bad85.png)
[source](https://www.austinsaylor.com/blog/2015/3/20/4-after-effects-graph-editor-basics-you-need-to-know)

```css
.animated-layer {
  transition: .2s cubic-bezier(.17,.67,.83,.67,.2,.02,.73,.59, ...);
}
```

**Comment by tabatkins** [comment]
Elaborating a little bit, more advanced real animation software (such as After Effects) seems to do a lot of its "advanced" animation curves by just chaining cubic beziers together.

You can do this manually today, but you have to do some funky manual calculating to explicitly set up the intermediate keyframes with the correct values.

So, the grammar would change from `cubic-bezier(<number>#{4})` to `cubic-bezier(<number>#{4} , [<number>#{6}]# )`; in each successive triple of points, the first point is the endpoint of the previous bezier / starting point of the next bezier, then the two control points of the next bezier. The first control point of the first bezier is still always (0,0), and the last of the last is still always (1,1).

**Comment by birtles** [comment]
I'm in favor of extending `cubic-bezier()` to accept more pairs of numbers. I've tried pushing this a few times (with pretty much the exact syntax Tab outlined) but typically the issues have been:

* What are the requirements on the control points to ensure that we end up with a function (i.e. produces a single output for each input)?
  * Issue #229―of which this issue is perhaps a dupe―[outlines some of the difficulties here and proposes cubic splines instead](https://github.com/w3c/csswg-drafts/issues/229#issuecomment-228259642). That issue didn't seem to arrive at a conclusion, however.
* How can we help authors produce curves with C1 continuity?
  * @AmeliaBR had a proposal for this: [smooth-cubic-bezier](https://lists.w3.org/Archives/Public/public-fx/2015JulSep/0037.html)

**Comment by AmeliaBR** [comment]
I definitely agree that there is a need for more complex easing patterns. But I do think it would be helpful to keep all the discussion in one place until we figure out the best strategy.

@argyleink, could you copy over your comment & examples to #229?

For the specifics of your proposal: it looks like all of your bezier curves are given equal time. Is that intentional? Had you considered what it would look like without that restriction?

**Comment by argyleink** [comment]
@AmeliaBR happy to move my comments over 👍  
I had searched and missed that open issue. What a lovely thread to catch up on.
