### ISSUE TITLE
[css-color-adjust-1] What happens with multiple <meta>s?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3846]
What should be the behavior if there are multiple `<meta name=color-scheme>` elements with different values?

My preference is that we honor the first and ignore the rest. This allows us to paint the background correctly as soon as possible. 

However, Device Adaptation specifies that the relevant `meta`s should be interpreted as `style` elements specifying a `@viewport`, so that they can cascade together; this means that the last `meta` affecting a particular @viewport descriptor "wins".

What rule should we use?

**Comment by lilles** [comment]
When you say "honor the first", what does that mean for meta elements inserted by a script?

- If there are no color-scheme meta elements and you insert one?
- If there is a color-scheme meta and you insert another one before it with a script in head?

Just apply the first that is inserted into the document either via parser or script?

**Comment by tabatkins** [comment]
The details are in the spec now for that - whenever the set of metas is changed, we re-evaluate which one is first.

**Comment by smfr** [comment]
We should do whatever browsers do now for other meta tags. For the viewport meta tag (and other meta tags as far as I can see), iOS uses the last one. This sounds like something HTML should spec.

**Comment by lilles** [comment]
Fwiw, theme-color is spec'ed to be the first (which is also what Blink implements):

https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color

For viewport, the Blink implementation applies the last that was inserted into the document, or had its attributes modified, not necessarily the last in the tree-order. This is a behavior we inherited from WebKit.

**Comment by smfr** [comment]
Has the ship sailed on HTML speccing the same behavior for all <meta> tags?

**Comment by domenic** [comment]
FWIW of the meta tags that HTML defines processing models for, the following are the behaviors I see:

- `application-name`:
  - First that matches one of the user's preferred languages based on the `lang=""` attribute.
  - Does not state how to handle dynamic changes; just gives an algorithm for one-shot determining the application name.
  - Unclear whether ones inside Shadow DOM are ignored or counted (uses ambiguous "in a Document")
  - Inside and outside the `head` are treated the same.
- `keywords`:
  - concatenate, split on commas, remove duplicates.
  - Does not state how to handle dynamic changes.
  - Very unclear whether ones inside Shadow DOM are ignored or counted.
  - Inside and outside the `head` are treated the same.
- `referrer`:
  - Last one wins, except unsupported values are ignored and don't overwrite previous, supported values. This is intentional to allow fallback in legacy UAs and the conformance requirements do not prohibit multiple.
   - Dynamic changes are handled.
   - Ones inside shadow DOM are ignored.
   - Ones outside the `head` are ignored.
- `theme-color`:
  - First parseable-as-a-color wins. Conformance requirements prohibit multiple.
  - Dynamic changes are handled.
  - Ones inside shadow DOM are ignored.
  - Inside and outside the `head` are treated the same.

It's kind of a mess. We might be able to align some of these but probably not all.

If I were to recommend one to follow for this case it would probably be theme-color.

**Comment by tabatkins** [comment]
Aw, thank you for doing this analysis, Domenic! Saves me some trouble.

This makes me pretty confident that first-wins is the right way to go, and just unifying fully with theme-color seems totally reasonable.

**Comment by lilles** [comment]
The current spec says only the meta elements in head are considered. The recommendation from @domenic would be to change that, then.

Viewport is not spec'ed, but the behavior in both WebKit and Blink is that the last one wins, allowed in both head and body, but has broken behavior for DOM modifications (last change wins regardless of tree order). The same broken behavior for dynamic changes was the same for color-scheme in WebKit last time I checked.

@smfr Do you have any feedback based on the last comments from @domenic @tabatkins ?

**Comment by tabatkins** [comment]
Yeah, aligning would mean `meta` in `body` would work (tho be recommended against; it negates the whole point of providing it in a `meta`).

**Comment by tabatkins** [comment]
Agenda+ to agree on matching Domenic's recommendation, making `<meta name=color-scheme>` match the processing of `<meta name=theme-color>`:

* First parseable-as-a-color wins. Conformance requirements prohibit multiple.
* Dynamic changes are handled.
* Ones inside shadow DOM are ignored.
* Inside and outside the head are treated the same.

**Comment by lilles** [comment]
Should we also try to resolve on moving this to the html spec?

**Comment by dbaron** [comment]
For extensibility to future color values, it might be worth dropping the "Conformance requirements prohibit multiple" from both `color-scheme` and `theme-color`, so that developers can use fallback with older and newer values (with the newer value first).  (e.g., consider use of a `lab()` color that's out of the sRGB gamut, intended only for implementations that support things reasonably).

**Comment by astearns** [comment]
At the end of the minutes above, @dbaron suggested we should have a link out to the HTML spec definition. I agree

**Comment by lilles** [comment]
PRs landed for both css-color-adjust and whatwg/html.

Tests moved to wpt/html and Blink implementation fixed: https://chromium-review.googlesource.com/c/chromium/src/+/2380654
