### ISSUE TITLE
[css-color-adjust-1] possible future <custom-ident> value 'sepia'

### ISSUE THREAD

**Issue by BillGoldstein** [w3c/csswg-drafts#3853]
Suggestion:

In section 'Opting Into a Preferred Color Scheme: the color-scheme property'<https://drafts.csswg.org/css-color-adjust-1/#color-scheme-prop>,
suggest a possible future 'sepia' value for color-scheme <custom-ident>.

Reasoning: It is a popular color scheme supported in many Reader Modes.

**Comment by AmeliaBR** [comment]
Agreed.  Although it's not really a standard UI color scheme, we've got multiple implementations of it in CSS user agents for document styling.  Standardizing the name & a couple details of what it means would allow those user agents to start experimenting with exposing it outside reader mode.

**Comment by fantasai** [comment]
Options here:
- Add it to the spec as a legal value with a description
- Don't add it to the spec, but use it in an example of handling unknown names from the future
- Don't mention it

**Comment by AmeliaBR** [comment]
My vote is for adding it directly as a valid value.

In addition to the reasons I stated previously, having a third value will force us to think carefully about how color schemes work when there are more than two options. E.g., should users be able to rank color schemes preferences in their browser options? (sepia > light > dark) How should that impact media queries & color scheme selections? If `sepia` UI (e.g. form elements) are available, should an author be able to force their use when the user preference is for `light`?

**Comment by AmeliaBR** [comment]
For the F2F, I think this is best as a breakout/workshop session, so we can work through some of the complications we just discussed on the call.

**Comment by tabatkins** [comment]
Summarizing from David's point in the minutes:

We don't necessarily need the 'color-scheme' property and (prefers-color-scheme) MQs to be in perfect alignment. In particular, we can define that "color-scheme: light" (or dark) just means that the UA's colors will generally be dark-fg-light-bg. That categorization matches the UA default, a high-contrast black-on-white, or even sepia (which is sepia-fg-white-bg).

This would mean that pages generically opt themselves into *some kind of* light (or dark) color scheme, without knowing the details beyond the aforementioned broad strokes about fg/bg lightness. Then the MQ can provide more detailed information for authors to specifically respond to if they'd like; `(prefers-color-scheme: sepia)` makes a lot of sense to add and respond to.

We'll have to put a little bit of thought into the MQ categories then, since presumably "light" and "dark" would still be supercategories there, so if we're carving out "sepia" we might want to also carve out some other common light schemes (like high-contrast white-on-black)

-----------

I like this quite a bit, as it handles lots of variation reasonably well. For example, the Nook app on Android has four different "light" themes (black on white, sepia on cream, black on pale brown, and black on light gray), two "dark" themes (white on black, light gray on dark gray), and one that's kinda light but a little weird (dark red on light red, presumably to help reduce blue light during evening reading)

**Comment by AmeliaBR** [comment]
>  sepia (which is sepia-fg-white-bg).

I'm not sure what colour you think "sepia" is, but the sepia colour scheme we're talking about is dark gray or dark brown foreground on cream/peach/beige background.  The background color is the defining feature.

Firefox reader mode sepia:
![Dark brown text on a creamy beige background.](https://user-images.githubusercontent.com/9876129/58767476-b2ceed80-8559-11e9-8e50-96f167ef02cd.png)

Their other options are dark-gray-on-white and white-on-dark-gray:
![The Firefox reader mode font and color dialog, with color options as described.](https://user-images.githubusercontent.com/9876129/58767535-88316480-855a-11e9-80b9-2b57702fcf08.png)

MS Edge reader mode sepia:
![Dark gray text on a light beige background.](https://user-images.githubusercontent.com/9876129/58767486-d7c36080-8559-11e9-8040-56cb39fd1e68.png)

Their other options include black-on-white, white-on-black, and black-on-gray:
![The Edge reader mode style selection dialog.](https://user-images.githubusercontent.com/9876129/58767519-42749c00-855a-11e9-95ad-8b49a5308034.png)

So three of four are light modes, with the background lighter than the text color: one high contrast, one sepia, and one low contrast monochrome.

**Comment by tabatkins** [comment]
There are a lot of sepia-ish schemes. "sepia" is a dark brown tho, so white-bg-sepia-fg also qualifies; in particular, it's what happens when you run a `sepia(100%)` filter on the white-bg-black-fg default. ^_^

**Comment by tantek** [comment]
Would this page/post be considered "sepia"?

[https://tantek.com/log/2002/12.html#L20021216](https://tantek.com/log/2002/12.html#L20021216)

If I could I would use prefers-color-scheme: sepia for that page.

(Originally published at: https://tantek.com/2019/156/t4/)

**Comment by lilles** [comment]
Closing based on resolution: https://github.com/w3c/csswg-drafts/issues/3853#issuecomment-499249648
