### ISSUE TITLE
[mediaqueries-5] Remove or expand inverted-colors

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3858]
Splitting out from #3807.

inverted-colors proposal
========================

```
@media (inverted-colors: none | inverted)
```

Supported in Safari; it's not clear whether "inverted" means all-pixels inversion, or color-inversion only, or what?

Important to distinguish these, as what authors do in response can vary based on which inversion is performed. (The `img { filter: invert(100%); }` rule in the spec's example, for instance, is only useful for all-pixel inversion; it would be *harmful* for a colors-only inversion.)

So, we either need to *specify* what kind of inversion is allowed to be performed, or add more values capturing the distinctions among the types.

**Comment by fantasai** [comment]
@grorg wrote in https://github.com/w3c/csswg-drafts/issues/3807#issuecomment-481868265 ...

> @media (inverted-colors: none | inverted) is about the screen-level color inversion accessibility feature (possibly with some re-inversion of images/video). It's a mode in which individual colors can't be independently adjusted; it's akin to a filter:invert() on the document.

To give a bit of history, this was originally offered as an accessibility feature and implemented at the system level - in that apps couldn't opt-out, and didn't even know it was happening unless they queried the system preferences (which I guess technically gave them a way to opt-out by pre-inverting things before they draw).

It was a popular feature, but the main complaint was that inverted images are wrong. So then came "smart invert", where everything was inverted except images and other media

Then we discovered that people would toggle this feature on and off depending on the page content. Basically they wanted either dark or light pages, and prefer to have their choice even if that meant the colours are all weird. So that's where we are today, and led to having a system preference for light/dark.

If the light/dark preference becomes widely adopted, we might not need the invert path any more.

**Comment by fantasai** [comment]
Since the behavior of `inverted-colors` varies wildly among implementations, and there is definitively no way for an author to react to it in a sensible manner, it seems that we should remove the feature.

If we are not removing the feature, then we need to split out these various behaviors into individual values so that authors know whether to rotate hues or double-invert images or whatever.

**Comment by frivoal** [comment]
The spec was already unambiguous that this media feature only applied when all pixels are inverted, not in some content-aware version of inversion. But unambiguous and obvious may not be the same thing, so I've rephrased it to be more obvious.

That doesn't mean we shouldn't discuss this, but the question is "what do we want", not "what does the spec say".

And I think what we want is what the spec says, because otherwise there's nothing useful an author can do with this media feature.

**Comment by AmeliaBR** [comment]
Copying over my comments from https://github.com/w3c/csswg-drafts/issues/3807#issuecomment-480447849:

I wonder if `inverted-colors` could be generalized as `forced-filter`, to also include "night light" effects that change the brightness and hue of the screen.  e.g. `@media (forced-filter: invert)` vs `@media (forced-filter: sepia)` or just `@media (forced-filter)` to indicate that the user agent or OS is filtering the final rendered colors.

That would also avoid any confusion about how invert mode interacts with individual color values — it's a filter effect that applies to the full screen, although it is possible to revert the effect with opposite filters on individual elements. (I _think_ this is how the Safari implementation works, with the "reverting invert" filters on images and videos now specified in the user style sheet.  So specifying the same rule in an author stylesheet would have neither harm nor benefit.  But someone who is familiar with the latest WebKit changes needs to confirm.)

The special cascade order rules for `forced-color` / `-ms-high-contrast` might also apply for `forced-filter` and other “forced” UA media manipulations. Whether this is necessary would depend on how many other user-agent style tweaks get added in those conditions.  But for example, maybe I have an `<img>` that is a black line drawing on a white background and it _should_ actually get inverted to white on black when the user has inverted the rest of the screen, so I want to use `img { filter: none}` to cancel out any user-agent stylesheet that double-inverts images.

(Note, that last comment is less relevant if forced-color overrides are done using revert instead of cascade trickery.)

**Comment by frivoal** [comment]
@AmeliaBR I don't think we should generalize. When the screen switches to warmer colors for night time, there is no expectation that the author will change something in response (nor, as far as I know, a demand from authors to be able to respond). I don't think we should generalize for the sake of generalizing.

For inverted colors, other need to respond to uninvert (or double invert, call it what you want), an to turn off the shadows-that-have-now-become-highlights, so that one does need a media feature.

But it's existence is driven by the need to react to it. Conceptually similar effects that don't need to be reacted to don't need to be exposed via MQs.
