### ISSUE TITLE
[css-text] U+205F Medium Mathematical Space (MMSP) not mentioned

### ISSUE THREAD

**Issue by briansmith** [w3c/csswg-drafts#3878]
https://www.w3.org/TR/css-text-3/#word-spacing-property says "General punctuation and fixed-width spaces (such as U+3000 and U+2000 through U+200A) are not considered word-separator characters."

U+205F Medium Mathematical Space is not mentioned and so it is not clear if it is considered a word-separator character. I'm guessing not. It should be mentioned to make it clear.

**Comment by frivoal** [comment]
"U+205F Medium Mathematical Space" is classified by unicode as General punctuation, so the specification already says what is supposed to happen: it agrees with you that this is not a word separator.

Maybe we could make an editorial clarification, making the reference to General punctuation clearer.

**Comment by fantasai** [comment]
I reverted this change because it was incorrect.

**Comment by briansmith** [comment]
> I reverted this change because it was incorrect.

What was incorrect about it?

**Comment by fantasai** [comment]
@briansmith The word "General punctuation" in that sentence wasn't about the General Punctuation Unicode Block but about punctuation in general. The point of the paragraph was to say that punctuation in general, and fixed width spaces in particular, are not word separators by virtue of being punctuation. Only characters that have the specific use of separating words as defined above are word separators.

**Comment by frivoal** [comment]
With the specification now clarified, I think we can answer the original question: is U+205F Medium Mathematical Space a word-separator character or not? The answer is no, because it is not a character "whose primary purpose and general usage is to separate words". (it's primary purpose and general use is to separate parts of equations/formulas).

The bit of text listing various fixed sized spaces (but not this one) is clarified to be neither normative nor exhaustive, and merely illustrate that just because something is punctuation or spacing, that doesn't necessarily means it is a word separator. This informative note doesn't change the above conclusion.

Given than unicode is an evolving dataset, we cannot be exhaustive here about which character is or isn't a word separator, as that list would eventually become stale. That's why it is stated in terms of the principle that guides this classification (with a clarifying note), so that the reader can apply it themself.

@briansmith, does that work for you?
