### ISSUE TITLE
[css-color-adjust-1] Combine forced-color-adjust and color-adjust properties somehow?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3880]
The `forced-color-adjust` and `color-adjust` properties are both switches for opting out of a form of forced color modification. Is there an ergonomic way (in terms of the cascade) to combine them?

**Comment by AmeliaBR** [comment]
In terms of the cascade, the questions (and my best guesses for answers) are:

- Would an author ever want to insist on exact color rendering for one situation but not the other?

  Yes.  If the author was turning off automatic forced-color adjustment to apply a more nuanced version of the system colors (e.g., for custom form controls or SVG diagrams), but the actual colors don't have specific meaning & could safely be adjusted when printing.  Or if the author cared about the aesthetics of their brand colors, but not to the point of overriding accessibility.

- Would an author want to toggle the values based on independent factors instead of setting both at once?

  Possibly, but I can't think of a good example.  Both controls are very much content-based; neither should be applied blindly as a global page style.

- Can the two be combined into a set of keywords that is intuitive to use?

  See below.

_______________________

Initial syntax for a combined `color-adjust` property, as a strawman:

```
<color-adjust>: any | never [ economy || forced ]?
```

`any` would be the default and would mean that the user agent can adjust colors whenever it deems that the change is in the user's best interest.

`never` on its own would mean "not unless the user very explicitly over-rides the page or print-preview styles".

The other keywords _combine_ with `never` to indicate the specific cases where the user agent should not make adjustments: 

- `never economy` means that the user agent should not adjust colors for print economy.

- `never forced` means that the user agent should not apply forced color values.

The list of specific situations could be extended in the future, which is why I also allowed `never economy forced` and `never forced economy` as valid declarations (currently equivalent to `never` on its own).

This arrangement is a little different from most CSS properties, because we want the default to be to allow everything, and we want authors to carefully think about which values they are disabling.

The downside is that authors might just use `never` everywhere because it is shorter, instead of thinking carefully about the situations they are disabling.

**Comment by dbaron** [comment]
I'm inclined to think that these are separate things that should stay in separate properties.  I think the risk of combining them is that some pages whose authors have carefully considered how printing should work will work badly for users with accessibility needs related to color contrast, and pages whose authors have carefully considered how they should work for users who require high color contrast will waste a lot of ink when printed.

**Comment by fantasai** [comment]
@dbaron Yeah, we'd need to express the values in a way that trying to turn off a specific type of adjustment doesn't turn off all of them.

**Comment by alice** [comment]
Coming here from the [TAG review](https://github.com/w3ctag/design-reviews/issues/583) for css-color-adjust-1.

We are also curious about the reasoning behind not combining these two. I see @dbaron's comments above, but I think more investigation is warranted as to whether the mitigations in each scenario are similar enough that they're not worth keeping separate, only to end up duplicating styles or failing to handle one or other scenario.

**Comment by emilio** [comment]
Err, was going to close https://github.com/mozilla/wg-decisions/issues/515 (though this one should probably be closed as well)

**Comment by fantasai** [comment]
@alice We're closing this as no change because we don't have a good idea for how to do this in a way that doesn't introduce problems. Considerations are:

- `color-adjust` has been shipping for quite awhile, used to get backgrounds to print, so we need to continue to support the current syntax.
- Elements that have `color-adjust` to get backgrounds to print should, for the most part, still be affected by forced-colors mode, so we can't combine the two into one switch.

There's one use case where pretty much any imagineable color adjustment (the ones that exist, and ones we might invent in the future) should be turned off: color swatches. It would be nice if there was some way to indicate this without encouraging authors to overuse it.

But overall it seems like pages are more likely to make errors if we cascade these two switches as a single property than if they are separate. :(

**Comment by LeaVerou** [comment]
> `color-adjust` has been shipping for quite awhile, used to get backgrounds to print, so we need to continue to support the current syntax.

I just looked at the Almanac 2020 data, and `color-adjust` is only used in 0.25% of pages. Actually, `print-color-adjust`, a nonexistent (?) property is used in 0.17% of pages, which indicates how incredibly confusing this name is. Lastly, `-webkit-print-color-adjust` is used in 1.19% of pages.
I don't think there's a huge web compat cost to changing the name.
I'm not even sure `print-color-adjust` would be a good name, since whether backgrounds print is not about adjusting colors at all…

> * Elements that have `color-adjust` to get backgrounds to print should, for the most part, still be affected by forced-colors mode, so we can't combine the two into one switch.
> 
> There's one use case where pretty much any imagineable color adjustment (the ones that exist, and ones we might invent in the future) should be turned off: color swatches. It would be nice if there was some way to indicate this without encouraging authors to overuse it.
> 
> But overall it seems like pages are more likely to make errors if we cascade these two switches as a single property than if they are separate. :(

What about making `color-adjust` a shorthand of `print-color-adjust` (name TBB) and `forced-color-adjust`? 
Depending the specifics of the shorthand syntax, that could also mitigate any web compat issues.

**Comment by tabatkins** [comment]
Note that 0.25% is *far* above our threshold for potential breakage. That's an enormous number of pages.

**Comment by fantasai** [comment]
@LeaVerou It's not just about getting backgrounds to print: UAs do automatic adjustment for e.g. light on dark pages to flip their colors so they'll print readably without using all the ink.

That said, I wonder if we should add `print-color-adjust` as an alias.

**Comment by tabatkins** [comment]
Agenda+, specifically, to discuss the option of moving the name to `print-color-adjust`, and leaving the excessively-generic `color-adjust` as a deprecated alias. We switched to the generic name back when we thought we might do more color adjustments in the same property, but that hasn't panned out and we don't think it's a good idea any longer.
