### ISSUE TITLE
[css-text] Clarify whether soft breaks exist at boundaries of an inline element with `word-break:break-all`

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#3897]
While looking into some Gecko bugs related to `word-break`, I'm trying to understand exactly where the `break-all` value should be allowing soft line break opportunities, and it's not clear to me that the spec text addresses some edge cases.[1]

Consider an example like `<div>abc<span>xyz</span>def</div>`, where the div has `word-break:normal` and the span has `word-break:break-all`.

It's clear that break opportunities exist between 'x' and 'y', and between 'y' and 'z'. But is there a break opportunity between 'c' and 'x'? Between 'z' and 'd'?

Existing browsers disagree on this: AFAICT, Webkit allows a break between 'c' and 'x', but not between 'z' and 'd', while Blink does not allow it in either of these positions. So if this div is reflowed with a width of 0, Safari will render it as

    abc
    x
    y
    zdef

while Chrome will render as

    abcx
    y
    zdef

I can't tell from the spec which of these, if either, is correct; am I overlooking text somewhere that makes this clear, or is it unspecified?

Personally, I think the most intuitive result would be

    abc
    x
    y
    z
    def

and would like to patch Gecko such that it would have this behavior - i.e. if the letter on either side of the boundary has `word-break:break-all`, then a break opportunity exists. If it's not currently clear in the spec, could we agree that this is the best result and converge on it?

[1] https://drafts.csswg.org/css-text-3/#word-break-property

**Comment by kojiishi** [comment]
I agree the spec can be improved more, but I guess this case is where the spec says the boundary should belong to the nearest common ancestor, in this case, `div`. @fantasai can you confirm?

**Comment by frivoal** [comment]
Yes, this is covered by the second sentence of the third bullet from the bottom in section [5.1](https://drafts.csswg.org/css-text-3/#line-break-details):

> For soft wrap opportunities defined by the boundary between two characters, the properties on nearest common ancestor of the two characters controls breaking.

So, in this case, as Koji says, at the boundary between c and x, and between z and d, the `word-break:normal` style of the div applies, and this rendering is correct:
```
abcx
y
zdef
```

As for making the spec clearer, if you have a concrete suggestion, I'm happy to take it, but as far as I can tell, the problem isn't that the sentence isn't clear, but rather that there are lots of rules, and that it is easy to fail to notice this one.

WPT has some tests that relate to this, but it could use some more.

**Comment by jfkthame** [comment]
OK, I see. I recall this is how letter-spacing is defined to work across element boundaries, for example (though does anyone actually implement it that way?), but missed that the same idea applied to soft breaks.

TBH, I think the result this gives will tend to be counter-intuitive for an author. Breakability is (to my mind) an attribute of the characters, so that in an example like

    data:text/html,<style>b,i{word-break:break-all}p{width:0}</style><p><b>hello</b><i>world</i>

it's unexpected for the "o" and "w", both of which have the break-all attribute, to end up stuck together.

Given that there isn't currently full interop in this area (this example renders with "ow" on the same line in Chrome, but in Safari each letter is on a separate line), is this something that we can/should reconsider?

(The same would apply to letter-spacing, fwiw:

    data:text/html,<style>b,i{letter-spacing:1em}</style><p><b>hello</b><i>world</i>

should, as I understand the spec, have no letter-spacing between "o" and "w", but Chrome, Safari and Firefox all have 1em of spacing there. Again, ISTM that the behavior called for by the spec, ignoring the letter-spacing of the inlines on both sides of the boundary and looking to the common ancestor, is not what an author would likely expect.)

**Comment by jfkthame** [comment]
Actually, on the surface it seems like this contradicts the spirit of #3886, where it was just resolved that "Inline box boundaries don't affect line breaking opportunities".

Consider:

    data:text/html,<style>p{width:0}span{word-break:break-all}</style><p><span>foo</span><span>bar</span>

vs:

    data:text/html,<style>p{width:0}span{word-break:break-all}</style><p><span>fo</span><span>ob</span><span>ar</span>

The only difference between these is where the boundaries of the inlines fall; the actual styles applied to all the text is the same in both. Yet Chrome (following the spec text as pointed out above) renders them differently, with pairs of characters stuck together at the span boundaries. Safari, OTOH, and also latest Firefox Nightly (since the patch in https://bugzilla.mozilla.org/show_bug.cgi?id=1507744), renders both examples the same, with no letter pairs stuck together.

**Comment by kojiishi** [comment]
> it seems like this contradicts the spirit of #3886

I agree, I referred to the issue because I felt the same as you. I think we'll need to discuss that and make more edits.

**Comment by kojiishi** [comment]
> TBH, I think...Breakability is (to my mind) an attribute of the characters

I actually like the idea.

> letter-spacing is defined...does anyone actually implement it that way?

I think last time @litherum said he can try it out, and we're waiting for the result.

**Comment by frivoal** [comment]
> Actually, on the surface it seems like this contradicts the spirit of #3886

I see where you're coming from, but I don't see it this way. #3886 is about making sure that an unstyled span (or a span styled in an irrelevant way) doesn't change anything. In the case you're describing, the spans are styled, so they are having an effect. Yes, there's two of them, and they are contiguous, but it is because they are styled in a way that affects line breaking that something happens, not just because we added spans to the markup.

> I think the result this gives will tend to be counter-intuitive [...]
> Given that there isn't currently full interop in this area [...], is this something that we can/should reconsider

I don't find it counter intuitive, so I'd leave it as is, but yes, it does seem that the lack of interop makes it possible to reconsider if we want to.

As for why I think it's fine: the primary purpose of break-word is to deal with east-asian typography. If we think about it in the abstract based on the `abc<span>xyz</span>def` example you gave, your proposal may seem sound, but that example isn't really a use case. If we look at actual use cases, I think it the current definition does the intuitive thing. Examples:

1. turn off breaking in the middle of words but keep breaks between words for Japanese by applying word-break:keep-all to individually marked up words:

  ```css
   p { word-break: break-all; } /* this line optional, defaults are fine*/
  .word { word-break: keep-all; }
  ```
  ```html
   <p><span class=word>日本語を</span><span class=word>文節ごと</span><span class=word>分割する</span>
  ```
2. similar to 1, but turn off middle-of-the-word breaks for a single word (for example, a name, a brand, etc) in the middle of otherwise break-all text
  ```css
   p { word-break: break-all; } /* this line optional, defaults are fine*/
  .name { word-break: keep-all; }
  ```
  ```html
   <p>我叫<span class=name>罗阳</span>。
  ```
3. quoting some old-fashioned space-less text in modern space separated Korean:
  ```css
  :lang(ko) { word-break: keep-all; }
  :lang(zh) { word-break: break-all; }
  ```
  ```html
   <p lang=ko>훈민정음 첫 문장은 <q lang=zh>國之語音異乎中國</q> 입니다.
  ```

Example 3 would work with the rule you proposed as well as the current one, but example 1 or 2 would not work with the rule you propose.

All in all, I think it is a discussion worth having, but my preference would be no change (other than maybe editorial clarifications and additional examples).

**Comment by frivoal** [comment]
(also, can we leave letter spacing out of this? Even if there are similarities, it's a separate piece of spec text, driven by separate use cases. If you feel that's wrong too, please open a separate bug).

**Comment by jfkthame** [comment]
I'm not sure I follow your examples. In (1), no browser I tested (Chrome, Safari, Firefox) breaks between the words at all. In any case, this use-case can (better?) be addressed by inserting ZWSP at the desired word breaks, rather than per-word markup -- although if you particularly want to do it based on markup, without the break points being part of the text stream, you could do this by using `.word::after { content: '\200b' }` to introduce the breaks.

Regarding (2), keeping the name unbroken, this seems to me like it should work exactly as an author would expect using the approach I suggest, although currently the `keep-all` here doesn't seem to work correctly in Firefox; this looks like a bug. In Chrome the two-character name also stays glued to the preceding character that was not part of the name. IMO this would be unexpected; applying the keep-all attribute to the two characters of the name (only) should ensure those characters stay together, but shouldn't affect the fact that there's a possible break before it.

**Comment by jfkthame** [comment]
My codepen showing that no browser currently splits between the words in (1), afaics: https://codepen.io/anon/pen/LoGWoq

(And using word::after to introduce ZWSP works as expected in both Chrome and Firefox, but not Safari.)

**Comment by frivoal** [comment]
I agree with you that a quick bit of testing suggests that no browser currently supports 1. I consider that a bug.

Regarding 2, following your approach would not only keep the name unbroken, but would also forbid a break between the name and adjacent characters, wouldn't it? You agree that this is undesirable, but claim that this feels like a chrome bug, while it seems to me that this is a consequence of your proposal. If it is not, then I am misunderstanding what your proposal is, and would appreciate if you could clarify.

In both cases, yes, you could work around that by injecting ZWSP with ::before and ::after, but why should you have to? Is there any use case where the behavior you propose is needed beneficial? (I mean easier for authors to use in realistic scenarios, not easier for implementers to reason about in the abstract.

**Comment by jfkthame** [comment]
> Regarding 2, following your approach would not only keep the name unbroken, but would also forbid a break between the name and adjacent characters, wouldn't it?

I don't think so. I admit I haven't attempted to reason through all cases at this point, but my intuitive sense of what `keep-all` should mean when applied to a run of characters is that it prohibits soft breaks between CJK characters (etc) within that run, but does not influence whether a break can occur before the first character of the run, or after the last.

If there's an inline boundary (e.g. one span ends and another begins), but the `word-break:keep-all` property is present on both sides of the boundary, then that boundary is irrelevant for line-breaking purposes (as per #3886); the run of `keep-all` text extends across it and therefore doesn't break (regardless of the style of the ancestor of the two spans).

**Comment by jfkthame** [comment]
BTW, https://codepen.io/anon/pen/joWzVX appears to show that Chrome's behavior is more peculiar than I'd realized until just now: whether it allows a break before the first letter in a break-all span seems to depend on *how many* characters precede it within the word. I can't figure out how to get to that result from any reading of the spec; should probably file a bug on it, but it'd be good to be more confident of what is actually the desired behavior.

**Comment by fantasai** [comment]
- Wrt @kojiishi's https://github.com/w3c/csswg-drafts/issues/3897#issuecomment-490397810 ; yes, the spec text Florian quotes says line-breaking between two characters—where the line break opportunity is created by the pairing, not the individual character (as by a word-separator character)—is by the nearest common ancestor, so Chrome's rendering in the OP would be correct. This behavior seems reasonable to me.
- Afaict @jfkthame's intuition is that `word-break` is applied to characters not to break opportunities, e.g. it effectively reclassifies AL as ID or vice versa, and behavior at boundaries falls out of that reclassification. This seems like a reasonable alternate way of interpreting `word-break`.
- However, per-character logic is not one that transfers well to `line-break`, and is definitely not something we can apply to `white-space`, consider `<nobr>中文</nobr><nobr>中文</nobr>`. It would maybe be ideal to be consistent in how we consider all line-breaking properties at an element boundary, as these are confusing enough already.
- I think Florian's examples in https://github.com/w3c/csswg-drafts/issues/3897#issuecomment-490847382 are fairly compelling... although 1 and 2 could also be done with `white-space: nowrap`. It might be interesting to compare use cases if @jfkthame's preferred behavior helps some others.
- It's important to me that behavior be symmetric. WebKit's behavior (interpreting the boundary one way at the start, and a different way at the end, of the inline) is imho unacceptable.

Altogether, I'd conclude the current spec behavior is best; but might be convinced otherwise if there are compelling use cases to change.

**Comment by jfkthame** [comment]
>     * Afaict @jfkthame's intuition is that `word-break` is applied to characters not to break opportunities, e.g. it effectively reclassifies AL as ID or vice versa, and behavior at boundaries falls out of that reclassification. This seems like a reasonable alternate way of interpreting `word-break`.

Well, it's not just "a way of interpreting", it's literally how the text explains `break-all`: "any typographic character units resolving to the NU [...], AL [...], or SA [...] line breaking classes [UAX14] are instead treated as ID". It doesn't directly explain `keep-all` in the same terms of revised line breaking classes, but that seems the obvious interpretation.

>     * However, per-character logic is not one that transfers well to `line-break`, 

I'm not sure why not? AFAICS, the kind of differences the spec describes between `strict`, `normal` and `loose` can similarly be handled by overriding the line breaking classes of the characters concerned. (As can `anywhere`, although that may be easier handled by short-circuiting the usual line breaking mechanism altogether.)

> and is definitely not something we can apply to `white-space`, consider `<nobr>中文</nobr><nobr>中文</nobr>`

ISTM `white-space` isn't really comparable to `word-break` and `line-break`. It's about white space processing (collapse, preserve, ...) rather than about identifying soft break opportunities between characters.

>     * It's important to me that behavior be symmetric. WebKit's behavior (interpreting the boundary one way at the start, and a different way at the end, of the inline) is imho unacceptable.

Agreed, that doesn't seem like a good result from any point of view.

I guess my unease is with that spec text Florian quoted, "For soft wrap opportunities defined by the boundary between two characters, the properties on nearest common ancestor of the two characters controls breaking." In my understanding, a soft wrap opportunity isn't "defined by the boundary between two characters". It *occurs* at the boundary but is *defined* as a consequence of the line-breaking classes of the characters on each side of the boundary. Those line-breaking classes are provided primarily by the Unicode standard, potentially tailored by any browser-specific customizations (many of the Unicode LB property values are informative rather than normative), and adjusted by the `word-break` and `line-break` styling of the characters.

**Comment by fantasai** [comment]
> Well, it's not just "a way of interpreting", it's literally how the text explains break-all

Fair point. :)

> I'm not sure why not? AFAICS, the kind of differences the spec describes between strict, normal and loose can similarly be handled by overriding the line breaking classes

Some of them... I'm not so sure about handling the breaks between inseparable characters, or the variants of Thai dictionary breaking.

> white-space isn't really comparable to word-break and line-break. It's about white space processing (collapse, preserve, ...) rather than about identifying soft break opportunities between characters.

It also controls whether breaking is allowed within the element or not, though. So although it does control white space collapsing as well, it is also a line-breaking control and is frequently used as such.

> [A soft wrap opportunity] occurs at the boundary but is defined as a consequence of the line-breaking classes of the characters on each side of the boundary.

Right, but it's a consequence of the pairing. E.g. you can't break between two horizontal ellipsis characters, or between two alphabetic characters, or between an alphabetic character followed by a horizontal ellipsis; but you can break between a horizontal ellipsis followed by an alphabetic character. Creating a break opportunity is not a fundamental characteristic of the horizontal ellipsis or the alphabetic character; but some of their pairings will allow breaks.

Pairing … and … together isn't allowed to break under `strict` but can under `loose`. If one is wrapped in `strict` and the other in `loose`, is the break allowed or not? An implementation based on reclassifying UAX14 classes might come up with a particular answer, but from the typographer's point of view how do you answer that question?

**Comment by jfkthame** [comment]
> Pairing … and … together isn't allowed to break under strict but can under loose. If one is wrapped in strict and the other in loose, is the break allowed or not? An implementation based on reclassifying UAX14 classes might come up with a particular answer, but from the typographer's point of view how do you answer that question?

It's an edge case (literally) where I don't feel that as a typographer I'd have a strong view one way or another. When the two … characters are adjacent but styled differently, do they belong together or not……who knows? Most likely, given that they're in separate elements, there's no compelling argument for keeping them together, and if the outcome of applying `loose` to one of them is that it can get separated from the one that has the `strict` styling, that's reasonable.

In practice, I guess the likely result would be that `<strict>…</strict><loose>…</loose>` could break, because a loose ellipsis is allowed to detach from the preceding character, while `<loose>…</loose><strict>…</strict>` would not break, because the strict ellipsis stays attached to the preceding character.

**Comment by fantasai** [comment]
OK, so we have some possibilities here:

- A) Use the "nearest common ancestor" behavior for interpreting `word-break` and `line-break` at element boundaries. This means a given character can be interepreted, effectively, as AL when evaluating whether to break before it and as ID when evaluating whether to break after it.
- B) Use per-character classification for interpreting `word-break`; use "nearest common ancestor" for `line-break`.
- C) Use per-character classification for interpreting both `word-break` and `line-break`. This will cause some intricate dependencies on the exact way that UAX14 defines line-breaking opportunities, which can result in some oddly asymmetric behavior.

Factors to consider:
 - Implementations are inconsistent in some pretty weird ways, so not helpful.
 - At least two people have opposite intuitions about this.
 - We can construct some use cases for A, but don't seem to have any for B or C.
 - The `white-space` property uses "nearest common ancestor".
 - I don't like the asymmetric side-effects of definition C (per-character on `line-break`).

**Comment by kojiishi** [comment]
> I don't like the asymmetric side-effects of definition C (per-character on line-break).

Can using the value from outer or inner, not from before, solve the asymmetry problem? I'm not sure whether outer is better or inner is better.

The "nearest common ancestor" is simple to dfine, I like that part, but implementing it doesn't perform well, and requires optimizations because line breaker is very hot. But too much optimization is the source of non-interoperability. I think making it simpler to implement will help interoperability.

**Comment by faceless2** [comment]
The same issue also applies to overflow-wrap. Affected tests:

* [overflow-wrap/overflow-wrap-anywhere-inline-002.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/overflow-wrap/overflow-wrap-anywhere-inline-002.html)
* [overflow-wrap/overflow-wrap-anywhere-inline-003.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/overflow-wrap/overflow-wrap-anywhere-inline-003.html)
* [overflow-wrap/overflow-wrap-anywhere-inline-004.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/overflow-wrap/overflow-wrap-anywhere-inline-004.html)
* [word-break/word-break-break-all-inline-004.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/word-break/word-break-break-all-inline-004.html)
* [word-break/word-break-break-all-inline-007.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/word-break/word-break-break-all-inline-007.html)

Is it worth removing the `<link rel=match` from these while the issue is undefined?

**Comment by frivoal** [comment]
Marked the existing tests as tentative, since they're interesting, but no longer have a basis in current spec text https://github.com/web-platform-tests/wpt/pull/37700
