### ISSUE TITLE
[cssom][css-transforms] Conflicting on resolved value of various properties

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#392]
CSSOM has a list of properties which should have their resolved value be their used value rather than computed value. That list doesn't include `perspective-origin`. However, CSS Transforms spec says the resolved value of `perspective-origin` should be used value.

I guess one of them should be changed to match the other.

**Comment by upsuper** [comment]
This also applies to `transform-origin`.

**Comment by fantasai** [comment]
We should probably just update the CSSOM spec to say that its list is limited to CSS2 properties, and all other properties are as specified by their respective modules (defaulting to computed value).

**Comment by dbaron** [comment]
It probably needs to be a slightly larger set than CSS2, representing "modules predating CSSOM".  (Much like transforms does for the Animation type...)

**Comment by fantasai** [comment]
Reopening because I don't think this was correctly handled. In particular, the CSSOM specifies, for properties that have resolved value as used value, certain rules for e.g. handling `display: none`. The specs that reference the new term “resolved value special case property” do not contain these caveats.

I think “resolved value special case property” is overly-general. It seems to me that the properties that do not resolve to the computed value follow one of the existing patterns in the CSSOM, and therefore we should have these properties specifically reference those rules, not make up their own rules, which are intended to be the same as what's in CSSOM but aren't.

**Comment by zcorpan** [comment]
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4879 shows transform-origin and perspective-origin should be like 'height'

**Comment by fantasai** [comment]
Are there any “resolved value special case properties” aside from top/left/bottom/right that do not resolve like 'height'?

**Comment by zcorpan** [comment]
Yes. The 'grid-template-rows' and 'grid-template-columns' properties.
