### ISSUE TITLE
[selectors-4] Rescope :has to static CSS rather than .querySelector

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3925]
There are no implementations of :has() in .querySelector and the like. However, we do have implementations of :has() in PDF renderers: https://www.princexml.com/doc-refs/#sel-logical

The spec should be updated to reflect this.

**Comment by SelenIT** [comment]
The linked document also lists the `:contains()` pseudo-class, which seems to have gone [from the specs](https://www.w3.org/TR/2001/CR-css3-selectors-20011113/#content-selectors) at some point before 2005, as supported. Is its implementation status also still relevant?

Honestly, as a web developer, I would prefer something less general that can be safely used in styling (like `:has-children()` or `:has-following-siblings()` mentioned [here](https://github.com/w3c/csswg-drafts/issues/1694#issuecomment-320784244)) to the powerful general mechanism that _can't be used in the context it's most needed_ because of possible performance implications. Maybe it's not late to introduce them into the current module (and probably to postpone the whole "selector profles" thing to some future levels, to keep the current level simple and more developer-friendly)?

**Comment by shaunrashid** [comment]
I prefer brevity when it comes to CSS. I would prefer :contains() for the syntax because it makes sense to me to read as "x contains y". But :has works too, especially if it matches how PDF renderers use it and if :contains could be used to match text within an element.

**Comment by bkardell** [comment]
@fantasai what would you update? Wouldn't a PDF renderer fit the same profile?

**Comment by SelenIT** [comment]
Please. Don't fix what is not broken yet, and it's unclear if it ever gets broken in the future. Don't make simple things complicated. There is no evidence that the "CSS profiles" concept is anything more than a purely theoretical question. Anywhere in practice, there is just CSS.

The impossibility to style elements depending on their content or following siblings is a real problem that [web](http://stackoverflow.com/questions/1014861/is-there-a-css-parent-selector) [developers](http://stackoverflow.com/questions/45004/complex-css-selector-for-parent-of-active-child?lq=1) [have suffered](http://stackoverflow.com/questions/2000582/css-selector-for-foo-that-contains-bar?lq=1) [from](http://stackoverflow.com/questions/4220327/css-selector-element-with-a-given-child?lq=1) [for years](http://stackoverflow.com/questions/21252551/apply-style-to-parent-if-it-has-child-with-css?lq=1). The slowness of the selector that only _perhaps would be implemented in the future_ is not (although the slowness of its _script-based alternatives_ that web devs currently have to resort to _probably is!)._ Please, help solving the real problem. If `:has()` can't be reasonably done so that web devs could safely use it for styling, than please give the web devs _anything that can_ instead.

Even if `:has()` was implemented in JS-only context, it would be merely kind of a syntactic sugar: `document.querySelectorAll('a:has(img)')` is not _that_ more readable for a JS developer than `[...document.querySelectorAll('a')].filter(el => el.querySelector('img'))`. It's _styling_ where it would be a game-changer and totally worth implementation effort, just like already existing content-aware selectors like `:focus-within`. Please, help the web developers to solve the real problem!

**Comment by Jamesernator** [comment]
I dunno if any engine implementors are here but is there any reason browsers have at not least implemented the partial version of just `:has(>` and `:has(+`?

This would solve a lot of developer's use cases while still leaving the door open for `:has(descendentSelector)` if it proves feasible.

**Comment by ExE-Boss** [comment]
@SelenIT
The following is more performant:
```js
Array.from(document.querySelectorAll('a img', img => {
	let el = img;
	while ((el = el.parentElement)) {
		if (el.localName.toLowerCase() == 'a') return el;
	}
	return null;
});
```

**Comment by SelenIT** [comment]
@ExE-Boss agree, this would be more suitable in most practical cases (though this seems to have a slightly different semantics in the unlikely case of nested `a` elements). I guess it also can be rewritten as a one-liner like `Array.from(document.querySelectorAll('a img'), img => img.closest('a'))` which would be probably even more performant. But my example was there just to illustrate the point that JS developers probably won't benefit from the new sub-syntax for the tree structure logic as much as CSS developers would benefit from content-depending styling of elements.

**Comment by oleedd** [comment]
Why is `:has()` risky? Difficult to implement is not risky, it is about problematicity.

**Comment by SelenIT** [comment]
Good point! Since we already have two shipped implementations in two most popular engines, does marking `:has()` as "at-risk" still make any sense?

**Comment by Marat-Tanalin** [comment]
And it’s not even difficult to implement.

**Comment by SebastianZ** [comment]
I've created #8168 to update the at-risk info in that spec.

Sebastian

**Comment by tabatkins** [comment]
"At-risk" is a W3C term of art that has meaning only in terms of the W3C Process; marking a feature as "at-risk" allows us to drop it from the spec after it's reached a "stable" level (like Candidate Rec) without as much rigamarole as adding or changing a feature normally would require.

But, yes, the at-risk list in Selectors is out-of-date; thanks for the issue, @SebastianZ
