### ISSUE TITLE
[selectors-4] Password reveal pseudo-element and pseudo-class

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#3934]
Hey everyone,

We've posted an [explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/PasswordReveal/explainer.md) on our public site regarding a proposal to add an optional psuedo element to the `<input type="password">` as well as a `:revealed` psuedo class. The explainer delves into the user and web research we've done as well as telemetry we've added that support the addition of this element and class.

The proposal is as follows (copied from the explainer for ease of discussion):

## Proposal:

The goal of our below proposal is to enable two key aspects:

* Allow user agents to include this functionality if they wish
* Enable web developers an ability to style it beyond color modifications

This proposal is to include this as part of CSS Selectors Level 4 with the addition of the following specification text:

### The ::reveal pseudo-element

User agents may implement the reveal pseudo-element on inputs that have `type=password`. If the user agent does implement this pseudo-element the following rules must be followed:

#### Toggling between revealed and obscured

* Activating the pseudo-element reveals the obscured password in plain text.
* Activating the pseudo-element again returns the password to being obscured.

#### Allowing for ease of author adjustment

* The graphic, text or other visual represenation the user agent utilizes to inform the user that they can interact with it must be set as a background image to allow authors to easily utilize the functionality but adjust this representation to meet their design needs if necessary.

#### Showing, hiding password reveal element, obscuring the password

Following events would show a password reveal element:

* User is typing password into an initially empty password input

Following events would prevent password reveal element from appearing: 

  * An empty password input has been focused
  * Password input is pre-filled programmatically
  * User has typed the password, and then the password input has lost focus

Following events would obscure password and hide a reveal element:

 * Password input has lost focus

 This is important because even though the user may find value in being able to see their password, they may only desire for it to be visible for a short amount of time and doing this allows for keeping the password private even if the user forgets to invoke the `::reveal` psuedo-element. Additionally, when the browser itself loses focus the password is obscured as well.

#### Supported styles

Only the following CSS properties can be applied:

* background-clip
* background-color
* background-image
* background-origin
* background-repeat
* background-size
* border-bottom-color
* border-bottom-left-radius
* border-bottom-right-radius
* border-bottom-style
* border-bottom-width
* border-left-color
* border-left-style
* border-left-width
* border-right-color
* border-right-style
* border-right-width
* border-top-color
* border-top-left-radius
* border-top-right-radius
* border-top-style
* border-top-width
* box-shadow
* box-sizing
* cursor
* display (values block, none)
* font-size
* height
* margin-bottom
* margin-left
* margin-right
* margin-top
* opacity
* outline-color
* outline-style
* outline-width
* padding-bottom
* padding-left
* padding-right
* padding-top
* transform
* transform-origin
* width

### The :revealed pseudo-class

User agents that implement the `::reveal` pseudo-element must also implement the `:revealed` pseudo-class on the password input. When a user invokes the `::reveal` pseudo-element the pseudo-class should be applied to the password element.
This will allow authors to provide different styles when the password is either revealed or not.

**Example**

Here is an example of an author that wants to show an eye image to reveal and a closed eye image to hide the password again.

    <input type="password" />
    <style>
    input[type=password]:not(:revealed)::reveal {
        background-image: url(my-eye-image.png);
    }
    input[type=password]:revealed::reveal {
        background-image: url(my-eye-image-revealed.png);
    }
    </style>

**Comment by jonjohnjohnson** [comment]
@gregwhitworth did you mean this in the third line of your example?
```css
input[type=password]:not(:revealed)::reveal
```

**Comment by heycam** [comment]
Without having looked at the proposal in much detail yet, my first thought is that there are other, similar widgets that are often embedded in `<input>`s, like an `(x)` button that clears the input.  Is it worth trying to think of a general mechanism for allowing authors to place these widgets inside an `<input>`?

**Comment by heycam** [comment]
(Although I suppose a password revealing button does need access to some internals to actually do the password revealing, unlike the `(x)` button.)

**Comment by Crissov** [comment]
Indeed, sounds a lot like (interactive) [`::marker`](https://drafts.csswg.org/css-lists-3/#markers). 😈

**Comment by gregwhitworth** [comment]
@heycam I'm fine with that - clear is something we've also considered and seen quite a bit of usage of `-ms-clear` across the web. Something I've seen in the past (can't recall where thought) was `::action` which would cover the individual input type interactions. For example one can image `input type="search"` also having something similar. At any rate, bike shedding the names is fine. I'm not sure if the psuedo classes should follow the same generalized statement because not all of them you'll want to adjust in the same manner as password. But as I said, feel free to bikeshed.

**Comment by gregwhitworth** [comment]
@jonjohnjohnson yep - good catch, wouldn't want to show the same icon in the each state. Fixed :)

**Comment by gregwhitworth** [comment]
Sorry for the delay on this, finally had a chance to sit down and parse it all out. If I understand this thread correctly, the request currently on me is to:

1. Define what happens between the revealed psuedo-class & `input-security`
2. Consider an over-arching and uniformed approach for styling form controls not necessarily this one alone
3. HTML/DOM state for revealed

Is there anything else I'm missing? @litherum @fantasai  @dbaron @AmeliaBR @bkardell @atanassov @frivoal @una @jensimmons @tantek @heycam @FremyCompany

**Comment by therealglazou** [comment]
Hello Greg. I have a few concerns I would like to share here. All of that comes from my experience as CTO of a company releasing a WebExtension containing a password manager. Disclaimer: I don't work there any more and my words represent my own opinion only.

The main issue with your proposal is the following one: as of today, "Show" buttons exposed on the Web in password fields are added through extra elements and these elements allow third-party tools - like password managers - to detect UI collisions with the UI thingies they want to add themselves to password fields. If we move to a pseudo-element added to `<input type="password">`, that will be extremely difficult for password managers to continue doing so. Furthermore, styling dynamic changes on that Show button is going to be tricky since pseudo-elements are always last in a selector, after pseudo-classes.

In short:

- it's limited to password fields while some other `<input>` fields could greatly benefit from added  "internal buttons"
- it's not extensible. `:revealed` and `::reveal` are nice but why should we limit this to one action only?
- dynamic styles will be an issue. `:hover::reveal` is possible but `::reveal:hover` is not
- it will severly harm all existing password managers since it won't be easy to detect the bounding rect of the pseudo-element. Because of that, extra buttons will often overlap with this new Show button because password managers will not be able to detect UI collisions
- the action attached is browser-defined only. There are two very different UXs for a reveal button: first statically switches the field value from obfuscated to readable and back, the second one does only when the button is maintained pressed/activated. This should remain possible.
- it raises pretty serious A11Y concerns because it's based on a pseudo-element

In my opinion, the requirements here should be the following ones:

1. the solution should be generic enough to apply to all `<input>` representing a text field, including `<input type="search">` and its omnipresent clickable mag-glass button.
2. input field buttons should allow all possible behaviours: simple buttons, dropdown menu, on-hover tooltip, etc.
2. it should be possible to add user-defined (JS-based) behaviours to an input field button
3. ability to fully style input field buttons
4. ability to add a localized tooltip to input field buttons
5. ability to query the DOM to retrieve the position/geometry of input field buttons
6. extensible solution allowing password managers to add their own input field buttons without UI collision with the existing ones (for instance added in reverse direction from the end edge of the input field)
7. it should allow to get rid of existing solutions absolutely positioning a button inside a text field and tweaking the `type` attribute of the input field. On some web pages, it's even worse: the reveal button switches between two different elements, one `<input type="password">` and another `<input type="text">`...

More about a potential proposal later.

**Comment by therealglazou** [comment]
Hi again. I gave myself a bit more time to confront the requirements above to the ecosystem, and in particular to the design of the 100 most visited web sites of the world and the main WebExtensions available. After careful review, I don't think that the original proposal above based on `:revealed` and `::reveal` is a desirable solution. Let me explain:

1. the only opt-in/opt-out option is to use `display: block` or `display: none` on the `::reveal` pseudo-element. That seems to me pretty hacky.
2. it's going to be extremely hard to attach anything, and in particular a page-defined localized tooltip or a specific behaviour, to the pseudo-element.
3. the behaviour of the reveal "button" will be browser-defined while I deeply think it should be user-defined.
4. it's not extensible to other buttons/actions
5. the burden on web sites and WebExtensions is a bit too high since the position of the reveal button will be extremely painful to detect

So I think a better option is to completely change the point of view and simplify the proposed solution:

- add a new `helpers` attribute to all `<input>` elements being a text field
- this `helpers` attribute should carry a coma-separated list of IDs
- if an ID in the coma-separated list in a `helpers` attribute corresponds to an element in the document, that element is fully extracted from the normal flow of the document and rendered inside (we need to discuss what it precisely means) the text field, from the end edge of the field and in order of appearance inside the `helpers` attribute.
- add a new attribute `revealed` to `<input type="password">` matching a new DOM boolean read-write `revealed` attribute to let both JS and CSS deal with revealing the value of a password input field. After all, this will be a intrinsic behaviour of password fields, not a rendering thing only, so that deserves to be in the DOM.
- no need for a pseudo-element since the component (not using the word "element" on purpose here) representing a given helper is in the DOM
- no need for a dedicated pseudo-class. No need to think of a functional pseudo-class if we want to make it extensible.
- allows localized tooltips, user-defined behaviours and all the powah of the Web
- no more security risk than a WebExtension changing the `type` attribute of an input field from `password` to `text`...

With the above, web sites and extensions implementing a Show button in password fields will be able to drop their existing hacky code easily; web sites and extensions adding extra UI elements to text fields will be able to do so in a way that does not collide with existing UI (and that's a VERY big plus), getting rid of usually hacky and very expensive code; extensions willing to "disable" the Show button will be able to do it; the solution works for mag-glass in search fields, powerful dropdown menus in combos, etc.

Looking forward to reading your opinions.

**Comment by gregwhitworth** [comment]
@therealglazou Thank you so much for the feedback Daniel. As I noted on LinkedIn, we've been digging more and more into controls/components and we probably won't go the way in which we originally proposed as we want to ensure that every usecase is possible; as you noted above. I'm intrigued at the helpers solution you describe, but I don't quite follow it. Mind sharing some psuedo code?

**Comment by therealglazou** [comment]
```<html>
  <head>
    <meta charset="UTF-8">
    <title>Input field helpers</title>
    <script>
      function ShowOrHide(aElement) {
        const id = aElement.id;
        // why don't we have a attribute selector for coma-separated lists?
        const field = document.querySelector("[helpers='" + id + "']")
                      || document.querySelector("[helpers^='" + id + ",']")
                      || document.querySelector("[helpers$='," + id + "']")
                      || document.querySelector("[helpers*='," + id + ",']");
        if (field) {
          field.revealed = !field.revealed;
          aElement.src = field.revealed ? "hide.png" : "show.png";
        }
      }
    </script>
  </head>
  <body>
    <input helpers="showButton"
           type="password">
    <input id="showButton"
           src="show.png"
           onclick="ShowOrHide(this)"
           type="image">
    
  </body>
</html>```

**Comment by FremyCompany** [comment]
Daniel, I have the impression your design assumes this control won't be available by default on all inputs unless they really take care of adding it?

If that's the case, I would like that to be revised. I want my browser to have this reveal button by default, and it should work consistently on all websites (barred really good exceptions). I don't mind websites adding new behaviors to the fields, or disabling the default behavior if it doesn't suit them, but I don't want every website to have to be updated to continue to get the experience I have in Edge today.

**Comment by therealglazou** [comment]
@FremyCompany you must clearly not impose such a constraint to all web sites. Forcing a Show button on password fields can be a HUGE security issue in some high-security environments (defense, intelligence, etc.).

**Comment by gregwhitworth** [comment]
@therealglazou I don't buy that argument, if someone is in proximity to read your password then there are other issues. That said, they can simply hide it via the psuedo element. That said - as I noted above due to the constraints we're going to go back and revise this. I have an expectation that we'll still want to define an anatomy that has this in by default but it will be up to the UA if they want to expose it or not. That isn't a discussion for this WG however, I'll be closing this thread for now until I have an updated proposal.
