### ISSUE TITLE
[css-sizing-4] Does aspect-ratio work on the content box or the border box?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4007]
@dholbert wrote:

We need to be sure it's clear *which box* (content-box vs. border-box) the aspect ratio is used for sizing, especially for elements that have an explicit "box-sizing:border-box". I imagine the ratio should always control how an element's content box is sized, since I think that's how aspect ratios work with images... but we should be sure that's explicitly stated.

**Comment by fantasai** [comment]
It's pretty clear that replaced elements need to apply their intrinsic aspect ratio to the content box; and also that for non-replaced elements, we frequently want to size the border box instead.

One possible way to do both is:
- for `aspect-ratio: auto` , which takes the aspect ratio from the intrinsic aspect ratio, we always use the content box
- for explicit aspect-ratio values, we ask `box-sizing`

**Comment by jensimmons** [comment]
@dholbert also wrote regarding this topic:

I'll include an example for (1), to make it concrete:  suppose we have a div with this styling:
    <div style="width: 100px; aspect-ratio: 2/1;">

This would produce a used 'height' of 50px.

However, if we add "box-sizing: border-box; padding: 10px", then I think it should instead produce a used 'height' of 60px, for consistency with how elements with "real" intrinsic aspect-ratios behave.  (This is because I think we'd want apply the ratio to the content-box - so first we have to discover the width of the content box, 100px-10px-10px = 80px. Then we use the ratio to get the height of the content-box, 40px. And then we add the padding-top and padding-bottom to get the height of the border-box, which is 60px.  So, we have a used 'height' of 60px in this box-sizing:border-box scenario.)

Here's a demo using <canvas> -- the first canvas has a used 'height' of 50px, the second has a used 'height' of 60px, as you can see in devtools (tested in Chrome and Firefox): https://jsfiddle.net/k0xjg5pz/
