### ISSUE TITLE
[css-text-3] Should preserved white space overflowing be visible ? 

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#4038]
Lets consider the following test case, which defines a styled span with a sequence of white space character that, honoring the white-space: pre-wrap feature, it overflows the box's inline size:

```
<!DOCTYPE html>
<meta charset="utf-8">
<style>
.test {
  font: 20px/1 Ahem;
  border: 1px solid;
  width: 2ch;
  white-space: pre-wrap;
}
span { background: blue } /* If the space is removed instead of hanging, there will be no blue box*/
</style>
<div class="test">X<span>X&#x0020;&#x0020;</span></div>
```

The following table shows how 3 of the main browsers render the test case defined above:

<table>
<tr><td>Firefox</td><td>Safari</td><td>Chrome</td></tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/59589639-ad8da900-90ea-11e9-8f7c-bb1bd91b5660.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/59589639-ad8da900-90ea-11e9-8f7c-bb1bd91b5660.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/59589700-d6ae3980-90ea-11e9-9943-095aa878527b.png"/></td></tr>
</table>

**Comment by javifernandez** [comment]
Maybe this other case makes the interoperability issue more visible, despite the chrome's [bug](973358) (in my opinion) in the wrapping behavior:

```
<!DOCTYPE html>
<meta charset="utf-8">
<style>
.test {
  font: 20px/1 Ahem;
  border: 1px solid;
  width: 2ch;
  white-space: pre-wrap;
}
span { background: blue } /* If the space is removed instead of hanging, there will be no blue box*/
</style>
<div class="test">X<span>X&#x0020;&#x0020;</span></div>
```

<table>
<tr><td>Firefox</td><td>Safari</td><td>Chrome</td></tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/59590289-fdb93b00-90eb-11e9-89cc-2fcfdd990dc2.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/59590289-fdb93b00-90eb-11e9-89cc-2fcfdd990dc2.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/59590388-3c4ef580-90ec-11e9-8dad-b10081280348.png"/></td></tr>
</table>

**Comment by emilio** [comment]
@jfkthame do you know off-hand about Gecko's behavior?

**Comment by frivoal** [comment]
@javifernandez both behaviors are currently allowed by the spec:
> If white-space is set to pre-wrap, the UA must hang this sequence if it does not otherwise fit prior to justification. It may also visually collapse the character advance widths of any that would otherwise overflow. 

This is intentional: there was a theoretical preference for not allowing the spaces to be collapsed (i.e. for what is currently the Chrome behavior), as it makes editing/selecting etc easier, but there is currently no interop on this (as you are pointing out in this bug), and browser vendors said they did not plan on changing this in the short term. So we decided to allow both, thinking that me may later be able to come to an agreement in level 4.

Interestingly, when we made that decision, Chrome and Safari used to collapse the spaces that overflow, and Firefox and Edge did not. Since then, Chrome and Firefox have swapped behavior. However, Chrome continues to collapse the spaces that overflow if the element is editable (using `<textarea>` or the `contenteditable` attribute). Despite that change, we continue to have multiple behaviors, so I don't think we're closer to resolving on a single one (although I'd be happy only allow hanging and no collapsing if browsers were willing).

----
PS: in the second example, your fix for the chrome's bug has been landed, and it now looks like this:

 <img width="78" src="https://user-images.githubusercontent.com/113268/60903980-93229780-a272-11e9-820f-c02466fd6c59.png">

**Comment by frivoal** [comment]
As far as I can tell, this is more a question than a bug, and I think it's been answered. @javifernandez, are you ok with closing this?

**Comment by javifernandez** [comment]
I'd rather keep it open for some time. I think there is something in the spec that may contradicts your conclusion. 

I'll close it once I'm done with my analysis, if you don't mind. 
Thanks for your feedback, in any case.

**Comment by javifernandez** [comment]
Ok, i think we can close it then.
This would also imply that I'll close the Chrome's bug https://crbug.com/974371 as WONTFIX, as @kojiishi  suggested in the first moment.

**Comment by frivoal** [comment]
Ok, thanks.

closing https://crbug.com/974371 as WONTFIX would indeed be my prefered outcome. The spec doesn't force you either way, but I think chrome current behavior is better (and is allowed).
