### ISSUE TITLE
[css-contain-1] layout containment should make an element containing block for absolute/fixed positioned elements

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#404]
[Layout containment](https://drafts.csswg.org/css-containment/#containment-layout) does not currently specify that an element must be a containing block for absolute and fixed positioned descendants.  ([Paint containment](https://drafts.csswg.org/css-containment/#containment-paint) does specify this.)

I believe failing to specify this makes some of the optimizations intended to be possible with layout containment not be possible.  In particular, if you have:

```
<div id="A" style="position:relative"> <!-- containing block for abs pos elements -->
    <div id="B" style="contain: layout">
        <div id="C" style="position: absolute; top: auto; left: auto">
        </div>
    </div>
</div>
```

then changes inside of B require relayout of A, since they can move the position of C, which is (box-wise) a child of A.  Note that C could also be positioned partly relative to the contents of B, and partly relative to the size of A (e.g., bottom: 20px; left: auto).

I think layout containment should also specify the line that paint containment currently does:

>  The element must act as a containing block for absolutely positioned and fixed positioned descendants.

**Comment by frivoal** [comment]
In terms of the internal tree structure the browser is maintaining, I suppose you're right, but it terms of actual changes to the layout, it seems to me that we're actually safe, because even if we're in the situation you describe, item 3 of [this section of the spec](https://drafts.csswg.org/css-containment/#containment-layout) (which as discussed in #396, should be rephrased to “If the contents of the element overflow the element, they must be treated as ink overflow”) requires that any overflow from the element B is treated as ink overflow, and thus doesn't affect the layout of anything outside of B.

So, it doesn't seem to me that making `contain:layout` elements containing blocks for absolute and fixed positioned descendants is strictly speaking needed. With that said, if I am wrong, or if I am right but implementation would be difficult, I don't see a big downside to adding such a requirement.

**Comment by atanassov** [comment]
CSSWG Discussion: There was general agreement to accept the proposal, but TabAtkins needed to check with the implementor first.

https://lists.w3.org/Archives/Public/www-style/2016Sep/0028.html

**Comment by frivoal** [comment]
@tabatkins Any result on this?
