### ISSUE TITLE
[css-fonts] Why is there no font-weight `light`?

### ISSUE THREAD

**Issue by benface** [w3c/csswg-drafts#4048]
The only keywords for `font-weight` that map to absolute values are `normal` (maps to `400`) and `bold` (maps to `700`). Why is there no `light` keyword, which would map to `300`? Light fonts are pretty common in modern design.

**Comment by svgeesus** [comment]
The keywords `normal` and `bold` date to the earliest days of CSS1, when there was vastly less control over rendering than there is now. (In fact, the definition of `bold` is simply that it is a ["weight that is at **least as dark** as"](https://www.w3.org/TR/CSS1/#font-weight) `normal` i.e. no lighter, but it could be the same weight actually.

Even then, a more precise set of numeric-like keywords (100, 200 etc to 900) were also specified. Bear in mind that the two CSS keywords map to the numeric vales and are pretty much unrelated to any words (`ultralight`, `book`, `heavy`, `black` etc) that may form part of the full font name, as those words are very irregular.

In CSS Fonts 4, with support for variable fonts, this is extended to [any numeric value from 1 to 999](https://drafts.csswg.org/css-fonts-4/#font-weight-prop).

So in modern usage, you would specify the precise weight you want (in the `@font-face`) rather than relying on imprecise keywords. It would be rare to be satisfied with "any weight that is a bit lighter" than the normal weight.

**Comment by benface** [comment]
Ah interesting, I wasn’t aware of that bit about `bold`. It really sounds like we shouldn’t be using the keywords anymore, so I’ll just close this issue. Thank you!

**Comment by BenjaminAster** [comment]
I somehow still think that numbers are very unreadable, especially to newcomers. Seeing a `font-weight: 600` declaration somewhere without knowing the exact "boldness" mappings basically gives no information to the reader, making the DX pretty bad. I know that numbers are much more precise and "absolute-ish", but I couln't we just add extra keywords as simple aliases of numbers, e.g.
- `thin` = 100
- `extralight` = 200
- `light` = 300
- `medium` = 500
- `semibold` = 600
- `extrabold` = 800
- `heavy` = 900

Font weights like 600 are often used because 700, especially with big text, seems "too bold" in many fonts. Usually, as a simple website designer without any special typographic background, you just want the font to be e.g. "not quite as bold as with the `bold` keyword", i.e. 600. The CSS declaration `font-weight: semibold` would directly imply that the font has a &ndash; well &ndash; semibold weight, instead of `font-weight: 600`, which is just an arbitrary number to most people. Anyone who wants to use the precise typographic numbers 1-999 could still do that, but the "normal", "average" web developer would have a more intuitive and readable alternative.

**Comment by Crissov** [comment]
For those curious in the [history of CSS](https://www.w3.org/Style/CSS/history.html), early [Level 1 drafts](https://www.w3.org/TR/WD-css1-960726.html) actually _did_ include proper absolute keywords for `font-weight`: `extra-light` | `light` | `demi-light` | `medium` | `demi-bold` | `bold` | `extra-bold`. They were removed some time before the release of the draft dated 1996-09-11, probably as a result of this [thread in www-style](https://lists.w3.org/Archives/Public/www-style/1996Aug/0055.html) and [this one](https://lists.w3.org/Archives/Public/www-style/1996Sep/0000.html).
