### ISSUE TITLE
[css-backgrounds] background-size: cover spec seems to not reflect implementations

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4049]
https://drafts.csswg.org/css-backgrounds/#valdef-background-size-cover says:

> Scale the image, while preserving its intrinsic aspect ratio (if any), to the smallest size such that both its width and its height can completely cover the background positioning area.

That definition means that if combined with `background-origin: content-box`, which changes the positioning area according to https://drafts.csswg.org/css-backgrounds/#background-origin:

> For elements rendered as a single box, specifies the background positioning area.

Per spec I'd expect the following test-case:

```html
<!doctype html>
<style>
body { margin: 0 }
.test {
  background-size: cover;
  background-repeat: no-repeat;
  background-position: top left;
  background-origin: content-box;
  /* 2x1 red background */
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAH0AQMAAACU5pVuAAAAA1BMVEX/IyMFLA8kAAAAVElEQVR42u3BMQEAAADCoPVPbQZ/oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+A/YYAAHqybvmAAAAAElFTkSuQmCC);
  height: 0;
  width: 100px;
  padding-bottom: 100px;
}
</style>
<div class="test"></div>
```

To render blank, since the positioning area is zero-sized. But browsers don't seem to do that, and doing that causes web compatibility issues like https://bugzilla.mozilla.org/show_bug.cgi?id=1559094 (which I plan to fix).

Seems like the spec should be fixed to not make it relative to the positioning area but the padding-box of the element (maybe?). I don't know, this seems quite broken over-all.

**Comment by AmeliaBR** [comment]
I don't see the problem with your example:  In order to cover the 100px width of your (zero-height) content box, the image is being scaled to 100px wide.  If you make both width _and_ height 0, then other browsers show nothing.  Similarly, if you set the image size to `contain` (and keep one dimension 0), then it gets scaled down to nothing in the other browsers, as well.

We certainly can't change the "cover" reference box in the general case of a valid-sized content-box; there is nothing broken in that situation.

I'd say that this—not drawing a cover-sized image if one dimension of the reference box is 0—is a Firefox bug. (Sorry.)

The only real edge case, to me is what to do with _repeats_ of a scaled-to-zero image. But that's something that needs to be dealt with regardless of how the base image size is computed.  And the last paragraph of the [`background-size` spec](https://drafts.csswg.org/css-backgrounds/#background-size) gives the rule: if the used image size is zero for either width or height, then the image is treated as a transparent layer. My guess is that the Firefox code is checking for this zero value a little too soon in the case of `cover` sizing.

**Comment by emilio** [comment]
> I'd say that this—not drawing a cover-sized image if one dimension of the reference box is 0—is a Firefox bug. (Sorry.)

No need to be sorry. To be clear I agree with this and the bug is fixed already. What I don't understand (and this may be me not properly understanding something subtle of the spec sentence) is what makes my first example any different from:

```html
<!doctype html>
<style>
body { margin: 0 }
.test {
  background-size: cover;
  background-repeat: no-repeat;
  background-position: top left;
  background-origin: content-box;
  /* 2x1 red background */
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAH0AQMAAACU5pVuAAAAA1BMVEX/IyMFLA8kAAAAVElEQVR42u3BMQEAAADCoPVPbQZ/oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+A/YYAAHqybvmAAAAAElFTkSuQmCC);
  width: 0;
  height: 100px;
  padding-left: 100px;
}
</style>
<div class="test"></div>
```

Which all browsers agree to render blank. The only difference here is which axis of the positioning area is zero.

**Comment by emilio** [comment]
Err, never mind, that's a bug in my example. Spec is alright, and I should use padding right instead of padding left so the background is actually positioned.
