### ISSUE TITLE
[css-text-decor] Limits on text-underline-offset to preserve semantic meaning

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#4059]
If an author puts `text-underline-offset` on an underline in a naive implementation, they could potentially make the underline look like a strikethrough. When this content is viewed on an older browser that doesn't support `text-underline-offset`, the semantic meaning of the text will appear to be changed (from struck-through to underlined). This is unfortunate. Instead, implementations should try to restrict the offsets on underlines so the underline always looks like an underline, rather than a strikethrough or overline.

There are a few questions to designing this:

1. Should the specification prescribe specific rules about where these limits are, or should the spec simply say that implementations should attempt to solve this problem?
2. Regardless of the result of 1, the spec should probably at least suggest some rules. So, what should the suggested rules be?
    1. The close-edge boundary for horizontal Latin text should probably be the baseline.
    2. What about Hindi text, that uses a hanging baseline?
    3. What about vertical text, where the baseline is at the same place a strikethrough should be?
    4. The underline is supposed to be one consistent stroke, regardless of the presence of child elements of differing sizes. Should a super large font-size child element push the limit outward?
    5. How about the other direction; the underline of one line of text shouldn't be able to look like an overline on the next line of text. For simple paragraphs this is probably straightforward, but what about when various elements on the next line have differing line-heights? Different sizes?
    6. Do we take in the border box of the containing block into account?

**Comment by jensimmons** [comment]
Having some kind of limit to prevent authors from mis-using underlines (overlines, sidelines, and such) sounds like a good idea to me. I feel strongly that whatever the limits are, we get interop on them (through the spec), so that Authors don't invent new hacks around this space — using the new powers we are adding to underline (et al) (thickness, placement, color, kind, etc) — that don't work the same in every browser. 

Here's a drawing of different underline results that Authors might want to use, none of which cause a misunderstanding of strikethrough. Might be helpful for discussion. I'm seeing a _lot_ of designs lately that use something like v4 to style underlines. File under Hot Trends of 2019. 

<img width="891" alt="Untitled 2019-06-26 12-46-30" src="https://user-images.githubusercontent.com/108474/60199322-a9ac0600-9811-11e9-88fd-954b82e2d637.png">

**Comment by litherum** [comment]
> none of which cause a misunderstanding of strikethrough

Even Sample text 5?

**Comment by AmeliaBR** [comment]
I agree that 1-4 in Jen's samples are all valid underline styles. Yes, the position in 3 & 4 overlaps the text, but it is clearly still near the baseline and there is sufficient color contrast between the text and underline that it doesn't look like a cross-out.

To cover these situations, we could define a clamp such that the mid-point of the under/over line is never moved inwards by more than ⅓ of the distance between the normal underline position & the normal overline position.

If we accept sample 5 as a valid underline, then we'd be basically giving up on the idea of clamping the values at all.  However, it's also not a valid strike-through text decoration (since that would be painted on top of the text).  So this effect would continue to be dependent on background gradients.  I'm OK with that; what I see when I look at it is text with a background effect. _But_, if authors are using it to have the same semantic meaning as an underline, then we have to consider that underlines are communicated to assistive tech & are preserved in simplified CSS environments, but background images are not.

Another use case to consider: animating this value.  If an author is trying to create an animated hover effect with the line sliding into position, then interpolating an offset length is much easier than trying to swap between underline, strike-through, and overline.  Which again would argue for no clamping.

**Comment by jensimmons** [comment]
> Even Sample text 5?

Let's see....

<img width="1058" alt="Untitled 2019-06-26 13-20-57" src="https://user-images.githubusercontent.com/108474/60201007-5471f380-9815-11e9-9e71-e07e85dc8f95.png">

**Comment by AmeliaBR** [comment]
> we could define a clamp such that the mid-point of the under/over line is never moved inwards by more than ⅓ of the distance between the normal underline position & the normal overline position.

BTW: defining it this way — relative to the normal text-decoration positions instead of relative to baseline positions — avoids adding any special rules for clamping based on text with different baselines.  (The special rules would still exist, but in the calculation for where to put the default under/over line!)

**Comment by nigelmegitt** [comment]
Is the difference between underline and strikethrough that an underline is drawn behind the text and a strikethrough in front, i.e. a drawing order difference? Then the only time when strikethrough and underline are indistinguishable is when they are the same colour. My guess is that is probably the majority of the cases in actual use so worth avoiding. 

I'm not suggesting making the clamping behaviour dependent on colour contrast between the line colour and the text colour, just to be clear.

**Comment by litherum** [comment]
@jensimmons That screenshot makes it look more like a highlight than an underline. I wonder if `background-image` would be a better fit for that case.

**Comment by litherum** [comment]
This conversation is making me think

1) We shouldn't be encoding 2019's design trends into CSS
2) There is enough design taste and fiddly-ness here that the spec probably should just let implementors decide the best solution for now, and write down whatever the implementors collectively decide is best.

**Comment by astearns** [comment]
FWIW, designers often use underline offsets and weights in InDesign to create custom text highlights (for the past decades, not just 2019). I was assuming the web versions could be used for the same purpose. I'm not sure the worry about confusing a custom underline for strikethrough is worth limiting flexibility here.

**Comment by dauwhe** [comment]
Historically, CSS gives us freedom to do many things, like position elements off the screen, overlap text, and so on. Users of CSS have taken advantage of this freedom by using features in ways that weren't anticipated by their creators. There's a rich tradition of such "hacks" in the design world, especially with underlines, borders, etc. 

I'm a bit wary of restricting what clever people can do, in the absence of documentation of harm.

**Comment by jensimmons** [comment]
> We shouldn't be encoding 2019's design trends into CSS

I agree. But we aren't talking about encoding a design trends into CSS. We are talking about whether or not to limit what's possible, or rather where to place that limit. And I'm saying, we should not limit something that people clearly want, even if they only want it for a short time. Trends do come back around. And this is a big one right now. These trends also tend to point us in the direction we, the CSSG, need to move. That's why we made `border-radius` for example. Rounded corners were hot right before CSS could do it.

**Comment by jensimmons** [comment]
I made a demo while diving deeper (so I could understand the issues better).
https://codepen.io/jensimmons/pen/wLrjGG?editors=1100
This works today in Safari. 

At the moment, in the Safari implementation, a negative or zero value for `text-underline-offset` makes the underline disappear. This is unexpected. And, imho, not desired.

I do believe there are legitimate reasons to allow Authors to pull the underline up to be behind the text ("up" in the horizontal writing mode). I really do not like the clamp that prevents this. 

At the moment, if one browser allows a negative value, while another makes the underline disappear with a negative value, we'll have a nasty interop problem.

I would prefer we remove any clamp, and expect Authors can be responsible.

**Comment by andybelldesign** [comment]
Howdy all 👋 first time caller, long time listener. 

I'm skeptical about a negative offset purely because of accessibility concerns, but after seeing the demos on here, I can see an opportunity from a creative angle, which is great.

Would there be a way that if say, the colour contrast between the underline and its text fell short, the underline would vanish like it does now?

**Comment by jfkthame** [comment]
> At the moment, in the Safari implementation, a negative or zero value for text-underline-offset makes the underline disappear. This is unexpected. And, imho, not desired.

This isn't what I observe in (Safari Tech Preview); a negative or zero value works as expected to move the line. However, Safari's skip-ink behavior means that it's likely to disappear "behind" the letters, particularly if you're using a thick underline, unless the offset is so negative that it actually moves entirely above the text. (And Safari doesn't support `text-decoration-skip-ink: none`, so you can't turn off the skipping for an "underline" that overlaps the body of the letters.)

> I would prefer we remove any clamp, and expect Authors can be responsible.

I agree. I don't think there's any real basis for deciding on a clamp value. If authors want to put the line far away from the text, or move an "underline" to be above, or whatever, that's their business, not ours. We may consider it unwise, but it's not CSS's job to decide on arbitrary limits to design.

**Comment by jpamental** [comment]
I agree that we shouldn't limit the placement. @jensimmons examples show legitimate design use cases. There are indeed many other ways people can use CSS in ways that don't make sense. This one is purely presentational. In some cases I would agree that a background gradient would be a better option, but as @AmeliaBR points out, the actual text decoration would still be preserved for screen readers and more limited CSS implementations. So it would still work as it should. I don't think it should be clamped.

Once more browsers are implementing this, I'd certainly hope that more the text-decoration spec would be implemented in Safari as well (instead of being a 'similar but not quite the same' behavior it is now with ink skipping)

**Comment by jensimmons** [comment]
I made another drawing that's better than the one above — a clearer drawing of the use-case I would like to allow. 

If there were a mid-line to clamp to, I'd be ok with that. But I'm not sure we have a good line in the font files to use. I don't like clamping to the baseline. 

As @dauwhe & I chatted today about what's available in a font file, he mentioned perhaps "between x-height and descent". I guess we could cap at x-height? I'd be totally fine with that. Or at a calculated mid-point between the x-height and the descent? Could that be a thing? That is what this drawing basically shows. 

<img width="1064" alt="Untitled 2019-06-26 16-34-29" src="https://user-images.githubusercontent.com/108474/60213881-657d2d80-9832-11e9-9fd7-49dbefb26073.png">

**Comment by jonjohnjohnson** [comment]
> When this content is viewed on an older browser that doesn't support text-underline-offset, the semantic meaning of the text will appear to be changed (from struck-through to underlined)

IMHO this is the primary concern. Can't we simply evangelize progressive enhancement by use of `@suports` as its solution? Instead of limiting designers/developers creativity by clamping the placement?

**Comment by BillGoldstein** [comment]
When I first tried a test with Firefox' new implementation TRY build, I intuitively tried positive value, saw it didn't work as I expected, then went and read spec text carefully.  So my "vote" would also be positive values being away from the text, i.e. down for underlines.

Also, please no clamping to just positive values...at least without also adding a new text-overline-offset property.  Currently text-overline-offset can be simulated with text-underline-offset.

**Comment by AmeliaBR** [comment]
> at least without also adding a new text-overline-offset property

Wait, this property _only_ applies to underlines? I missed that. I was definitely assuming that it would apply to both over & underlines.  But using a very-offset underline to simulate a slightly offset overline seems like a hack. If that feature is necessary, let's define it directly.  @BillGoldstein, do you have any screenshots of cases where you are using overlines & need to tweak their position?

**Comment by fantasai** [comment]
@AmeliaBR Yeah, you wouldn't necessarily want the same offset for the underline and the overline. :)

**Comment by BillGoldstein** [comment]
https://billgoldstein.name/about but you'll need this FF build https://treeherder.mozilla.org/#/jobs?repo=try&revision=e2f9053a82dd6aaef208c2d5a51f828aa8157ab8

**Comment by AmeliaBR** [comment]
> you wouldn't necessarily want the same offset for the underline and the overline.

Definitely. So there would need to be a two-value syntax. Or as Bill Goldstein suggested, two different properties, though I'm not sure they need to be separate: you're either going to set them both at the same time you set `text-decoration` to have two lines, or you're going to set them both when you set the font to something that doesn't work well with the default line positions.

Anyway, that's a separate issue.  My point was, if there's a use case for adjustable overlines, it should be addressed directly, not as an argument for extreme underline offsets.

**Comment by jfkthame** [comment]
I wondered about this, too (the ability to control underline position, but not other decoration lines); it seems a bit inconsistent. The only explanation I could think of was that underlines are much more commonly used (e.g. to indicate links) than overline or strikeout, and so people care more about them.

But if we're going to complete the set, presumably we also need `text-line-through-offset`, or a three-valued `text-decoration-line-offsets`. The default position of line-through doesn't always look particularly good.

**Comment by dauwhe** [comment]
I worry that clamping can result in a bad author experience. It's quite frustrating when you change the value of a property but there is no visible change. Even worse is changing a value of the property and the line disappears. 

More generally, why is CSS now restricting what authors can do? I can create unreadable text in a thousand different ways. CSS gives authors tremendous power, and talented people can use features in unexpected and beautiful ways. Is it the role of the CSS Working Group to say that some designs are OK, and some designs shouldn't even be possible?

**Comment by astearns** [comment]
+1 to @dauwhe. I don't think we should have any clamp for this offset.

**Comment by jensimmons** [comment]
After the discussion on the call, it seems like there are three options:
1) **No clamp** — allow anything. Leave it to Authors to be responsible.
2) **Wide clamp** — allow all kinds of visual styling that might be wrong semantically (bending the purpose of 'underline'), but do clamp enough so that the underline for one string of text doesn't end up three line boxes away or further (like on another page/screen).
3) **Narrow clamp** — clamp tighter, to prevent Authors from putting the underline across the ascenders, for example, so that it's not possible for an underline to loose its semantic meaning. 

If we decide on one of these three, then we can debate the details of how to do it (if we choose option 2 or 3).

We also debated:
1) Should the specification be precise, with musts, so that there's interop in the details?
2) Allow implementers to figure out some of these details for themselves, and spec with mays or shoulds. Don't worry that it's inconsistent between browsers, and see how things work out. Perhaps spec details later?

**Comment by jensimmons** [comment]
I believe we should have interop, and that having this behave differently in different browsers will be a serious problem for Authors.

I also believe that — if we do clamp — the line should not disappear. It should just stop moving / appear at the clamped value. Having it disappear leaves a box of mystery for Authors to debug. And a serious interop bug trap waiting to eat people's underlines in untested browsers. 

I lean towards no clamp at all. Let Authors do what they want. If people can change the color of a strike-through, and change it's thickness, they can style them however they want, separately. 

If we want to do a wide clap (option 2 above), so that an underline can't end up on the wrong page (in paginated cases), or mess with paint performance, I could agree with that. But I would want it to be fairly wide, this clamp. I definitely don't want to get too fussy, though, and make this super hard to implement. 

I agree with @dbaron on the call,  we should look at doing `text-strikethrough-offest` and `text-overline-offest` asap, so that Authors can also adjust the placement of the line. That will remove the temptation to use underlines for these other use cases. Let all three have equal superpowers in styling, and tell people they should use the correct one semantically.

**Comment by AmeliaBR** [comment]
For what it's worth, I'm leaning towards "No clamp — trust authors to be responsible” _but_ with the requirement that we extend this feature so that anything that can be done visually with an underline can also be done visually with a strikethrough or an overline. That way, authors can pick the line that makes sense for their use case & that provides the most accessible fallback.

**Comment by bradkemper** [comment]
I also prefer no clamp at all (other than extremely large numbers that create memory problems, etc).

People can be very creative, and I don’t want to stifle the creativity with artificial limits. Some things mentioned after the call:

- @jensimmons: Reason to have an extreme offset underline: Fancy heading with mildly obnoxious hover effect that causes an underline to appear, but it doesn't just appear it slides into place from offscreen.  I'm not saying it's good design, I'm just saying that once you allow animated underline offset distances, some designer is going to want to take it to the extreme.
- people *are* going to animate this line
- @tantek: web designers will use overlines and underlines as alternative borders or alternative to outline-top and outline-bottom
- me: Could be used as an offset solid background too
- @tantek: graphical effects you can position without affecting layout

I agree with all of this. Also, text-decoration is decoration. It is not semantic. I do think overline and strikethrough should be offsettable too. So an author can adjust the position of a strike-through without having to change it to an underline. And so an author can use underline for colored lines/rectangles behind the text, and strike-throughs in front of the text.

**Comment by bradkemper** [comment]
I don’t know why we don’t just have `text-decoration-offset` instead of `text-underline-offset`.

**Comment by fantasai** [comment]
@bradkemper Because you generally don't want to offset each line by the same amount. :)

**Comment by jfkthame** [comment]
You could have `text-decoration-offsets` accepting three values, for underline offset, overline offset, and strikethrough offset. (Omitted trailing values would default to `auto`, if less than three are provided.)

**Comment by jensimmons** [comment]
We were just discussing the possibility (after looking at the straw poll taken during the CSSWG call) that maybe we could settle on the following:

We do have a clamp (and it is a clamp, where the underline is always shown, not a clip where the underline disappears — as resolved on the call). And the clamp is at +/1 one-line-box. 

<img width="1309" alt="Underlining drawings 2019-07-17 13-14-57" src="https://user-images.githubusercontent.com/108474/61396082-e6a96c80-a894-11e9-8e68-6a70f7f35ea4.png">

In this case, the word "neighborhood" is underlined. And that underline could actually be allowed as high up as the top of the line box above or as low as the line box below, but no further. 

The idea is that....
- This would help browser engineers make sure performance wouldn't be a problem. 
- This might help Authors who accidentally wrote bad code (saying 15em, when they meant 15px), by keeping the line from being unexpectedly far away.
- This would not limit the creativity of Authors, because there's not a reasonable use case for going any further out.
- This would help accessibility by not allowing nonsense choices.

Of course, there are reasons to go for a "narrow clamp" instead — but the straw poll shows a lot of people wanting "A: no clamp", and this might be a better compromise. Allowing creativity and avoiding too narrowly defining a limit, while still also providing a way to limit performance drains or deep confusion.

**Comment by frivoal** [comment]
https://github.com/w3c/csswg-drafts/issues/4059#issuecomment-512421819 seems like a good compromise to me. I'd prefer no limit at all, but I can live with that.

**Comment by astearns** [comment]
I'm still a no-limit partisan, but it's nice to have a specific example to work from. 

I am assuming this would be based only on the current linebox height (or probably line-height, since linebox height is something that's not directly controllable by authors). Whether there is a line above and/or below and what their heights are wouldn't figure in.

In the picture, the yellow area is actually going about two heights above the initial position, and only one height below. If we're going with a limit, that would be fine - but we might want to allow two heights in both directions for symmetry.

If we do limit things based on line-height (or linebox height), there is an escape hatch authors can use for single lines of text - setting line-height to an absurdly large amount to make a larger offset available. I suppose that could be taken up by both sides (limits: look, for weird things you can work around it) (no-limits: whatever implementation benefits accrue from a limit can be subverted, so you still need to figure out how to handle it)

**Comment by astearns** [comment]
While several (but not all) of the people who voted for no limit did say they could live with some limit, when I asked the reverse I got no response. Is there anyone who would prefer some kind of limit who could not live with a limitless offset?

**Comment by jfkthame** [comment]
I'm a no-limit partisan, too. :) (Aside from more general implementation limits a browser might have, such as the range of fixed-point dimensions.)

I don't think a clamp such as ±1 line really gains us much. It leaves plenty of scope for visually misleading effects, like an underline that looks like an overline, or one that appears to belong to the preceding or following line; and yet it does potentially impose limits on authors' creativity. I don't think CSS should do that without compelling reasons for it, and I don't see such reasons here.

For a silly example that uses a large offset, see https://jfkthame.github.io/test/anim-underline.html (requires latest Firefox Nightly and a couple of `about:config` settings, see info on the page).

**Comment by jensimmons** [comment]
To understand better what we are making, and the issues we've been discussing, I made another set of demos — this time ones that are more realistic to what Authors will do: 
https://codepen.io/jensimmons/pen/voYMPE?editors=1100

<img width="1604" alt="Underlines" src="https://user-images.githubusercontent.com/108474/61489527-eedad800-a978-11e9-92dc-83e344c9c258.png">

I thought a lot about accessibility considerations as I worked on this, and realized there are already quite a few guidelines and best practices that should also be followed when styling underlines. Much of this is about choosing colors that work for the widest range of users — considering color contrast AA and AA guidelines, and guidelines about text that goes over any kind of image. I don't see any need to add additional a11y guidelines to make sure text is readable because of color choices. That's already defined. Plus there are guidelines about underlines already in play — don't remove the line and then make the color difference between regular text and linked text too faint, for example. When I made the demo with a very thin hairline underline, I realized, oh, the same guidelines apply if I was instead removing the underline. Right. Don't make it too hard to see. 

Perhaps folks who are making a11y linters and tests should add to their test suite, to consider underlines styles. That would likely help, and more and more of these tools pop up. But I didn't think of anything new for WCAG 2. 

If anything, I think these styles will encourage Authors to do a better job at a11y, because they can _have_ an underline for a link, and make it 'pretty', instead of always removing it because they don't like how it looks. 

Also I realized that the much more common accessibility consideration will have to do with line thickness, and color contrast. Especially with the new ability to let the underline go behind the text. 

In our debates, the concern has centered on giving Authors too much leeway with offset — that they could put the underline in a place that's confusing. That is an accessibility consideration, but it's also a UX consideration in general. Putting the underline so far away that it's confusing to a person with low vision or a cognitive disability is going to be confusing to everyone.

**Comment by fantasai** [comment]
> I am assuming this would be based only on the current linebox height 

The line can move in some cases to accommodate descendant content, so we do want to use the line box height as part of the equation. Somewhat more precisely, I would define the limits as something like "from the middle of the line box the upper/lower limit is at max(line box height, font height)/2 + slack", where slack is whatever we'd like to decide, and at *minimum* should be (line-height - font-size)/2 to represent the other half of the line gap.

I do want to note that the offset position is measured from the top of the underline, however thick it is: zero places the entirety of the underline below the alphabetic baseline (assuming `text-underline-position: auto`). If we add controls for strike-through and overline offsets, they'd be measured from the middle and bottom of the line thicknesses, respectively.

**Comment by jensimmons** [comment]
Jonathan Kew at Mozilla pointed something out to me that made me realize I think I've been misunderstanding what Safari's current implementation does. He said:

> According to my testing, it's not exactly that negative values cause the underline to disappear, what's happening is that once the underline crosses the baseline of the text, `skip-ink` behavior kicks in and makes it disappear. If you make the offset so negative that it moves above the letters, it starts to appear again (skipping ascenders etc at first), and sometimes you'll see bits of it in between letters even when it's mostly hidden "behind" them. 

I had thought Safari made the underline disappear for any offset value less than 0 — that the line was disappearing because it was being clipped. That's not the case.

Instead, this raises the point that without `text-decoration-skip-ink: none` the line does appear to get clipped. Safari needs to implement `text-decoration-skip-ink: none` to make the toolset complete. (And Firefox needs to implement `text-decoration-skip-ink` in general. We hope to do so as we implement the rest of these properties for styling underlines.) 

I don't know that this realization affects the decision before us, but it's true that Authors will need to learn to always pair an explicit `text-decoration-skip-ink: none` every time the want to use `text-underline-offset: [negative value]` — or the line will seem to disappear, and that might be confusing. Apparently it was for me.

**Comment by jensimmons** [comment]
Learning that Safari doesn't already have a clip in place makes me lean even more to the no-limit camp. I'd personally prefer no limit at all. 

I could live with a wide clamp, as drawn in https://github.com/w3c/csswg-drafts/issues/4059#issuecomment-512421819 (or something like it).

**Comment by jensimmons** [comment]
Actually, I can see that Safari does currently clamp.... I just updated this demo: https://codepen.io/jensimmons/pen/voYMPE?editors=1100#0 to include `text-decoration-skip: none; /* for Safari */` so that skip-ink doesn't remove the underline, and we can see the clamp.

**Comment by jensimmons** [comment]
We need to resolve on this so that Firefox can ship in Firefox 70 (which merges Sept 2).

**Comment by jfkthame** [comment]
> Actually, I can see that Safari does currently clamp.... I just updated this demo: https://codepen.io/jensimmons/pen/voYMPE?editors=1100#0 to include `text-decoration-skip: none; /* for Safari */` so that skip-ink doesn't remove the underline, and we can see the clamp.

What version of Safari are you testing? Last time I tried Safari Tech Preview, it didn't appear to implement skip-ink:none control.

**Comment by litherum** [comment]
When we implemented underline skipping, the spec said the property was `text-decoration-skip: ink`. Since then, the `text-decoration-skip` property has expanded to multiple longhands, and we haven't had a chance to make the accompanying change in WebKit.

**Comment by litherum** [comment]
I think this is already what the spec says, so I think this issue should just be closed.

**Comment by asmusf** [comment]
What about the consistency issue raised for treating overlline + strikethrough the same?

**Comment by litherum** [comment]
Test: https://github.com/web-platform-tests/wpt/pull/26033
