### ISSUE TITLE
split tranform to set seperate 

### ISSUE THREAD

**Issue by L2L2L** [w3c/csswg-drafts#4083]
using left, right, top, bottom to animate a html element is more powerful than using transform. Why? cause you can't break apart the different transform properties across animation without resetting it. My proposal which might already been suggested is to define new css properties such as transform-translate, transform-rotate, transform-scale, transform-skew, transform-translateX, transform-rotateX and so on to help set individual transform properties. If they must be a rule that if one do this they can't use the transform: property on the element that have different transform-* set on it than so be it that is manageable than putting a div with in a div to use different transform:* values on it to animate.

**Comment by AmeliaBR** [comment]
Transforms level 2 already proposes independent [`translate`, `rotate`, and `scale` properties](https://drafts.csswg.org/css-transforms-2/#individual-transforms), which could be used instead of `transform`.

These would apply in a set order. If you used a `transform` as well, it would apply separately.

There are not currently any plans for an independent skew property (since skew isn't used much), or for a way to set translateX and translateY independently.

Does this address your feature request?

**Comment by tabatkins** [comment]
Closing, as the translate/rotate/scale properties seem to address this request.
