### ISSUE TITLE
[css-text-decor] Rename `text-decoration-thickness` to `text-decoration-weight`?

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#4138]
I discovered this week that there was still a bit of confusion about the name of the new CSS property for adjusting the width/thickness of an underline. (Mozilla had implemented the [older name & just updated to the new one.](https://bugzilla.mozilla.org/show_bug.cgi?id=1567282).) Because I was poking around, trying to figure this out, a new name occurred to me. 

For background: Currently, [see draft spec](https://drafts.csswg.org/css-text-decor-4/#text-decoration-width-property), the name for this new property is `text-decoration-thickness`. It was originally called `text-decoration-width`. The name [was changed last October](https://github.com/w3c/csswg-drafts/issues/3118#issuecomment-432301016). Best I can tell, along the way, some folks argued "width" better matched some of the other CSS properties, like `border-width`. While some argued `width` is confusing, because it's not going to adjust the length in the inline-direction. (I agree with this, width sounds like adjusting the length of the underline, not the thickness). Some folks also argued that the word "thickness" is not great for an international audience, the 'th' might be especially hard for non-English speakers. I don't think that any other names were debated (from a cursory skim of the issues).

Yesterday, I was chatting with a journalist/editor in NYC about CSS and recent CSSWG debates, and he said in his world of newspaper typesetting, that dimension is called weight. They talk about the _weight_ of an underline. Which struck me as perhaps a really good solution.

`text-decoration-weight`

This better matches existing CSS — `font-weight` also adjusts the thickness of typographic lines (the one inside the characters themselves). It's not a word that's as hard for an international audience. And it will not be confusing for Authors. 

Thoughts?

It's annoying to have to change existing implementations (shipped in Safari, on it's way in Firefox). But perhaps this is worth it?  

@litherum @fantasai ?

**Comment by AmeliaBR** [comment]
The values for underline thickness aren't consistent with the values for `font-weight`, though. So that could provide another aspect of confusion.

**Comment by SebastianZ** [comment]
I'm torn appart. "thickness" and "weight" both have their pros and cons.

As a non-English speaker I do *not* have problems understanding it's meaning. As far as I know, 'th' only causes pronunciation problems for some people but they don't have problems when writing it.

Anyway, pros for "thickness" are that it's generally understandable in this context and there are already implementations using it, cons are that it's a bit long and doesn't relate to any other property name.

Pros for "weight" are that it relates to `font-weight` and it's short, cons are that it's rather hard to spell because of the "gh", its meaning may not immediately be clear without knowledge of typography, and that implementations would have to be changed (again).

Sebastian

**Comment by litherum** [comment]
Are we really going to rename something after there are two implementations of it?

**Comment by dholbert** [comment]
I'm not *entirely* opposed to changing Firefox's implementation -- ours hasn't been preffed on by default yet, and we [spun up & landed a rename patch for "-thickness"](https://bugzilla.mozilla.org/show_bug.cgi?id=1567282) in a matter of hours last week. :)  But I do agree there should be a high-ish bar for performing another rename.

I do share @AmeliaBR's concern that `font-weight` has an entirely different category of values, which makes the analogy/muscle-memory more confusing, IMO.  And to me, "weight" sounds like a fuzzy "suggestion", and less like a pixel-precise measurement (perhaps because I'm used to font-weight where that's basically what it is).

**Comment by fantasai** [comment]
I agree with not renaming to `-weight` based on @AmeliaBR's argument that its values are not related to `font-weight`.

I'm still disappointed that we renamed from `-width` to `-thickness`, given every other line thickness in CSS is labelled as `-width` and having this be different is arbitrary from an i18n and learning perspective.

**Comment by Crissov** [comment]
[`stroke-width`](https://drafts.fxtf.org/fill-stroke/#propdef-stroke-width) and `::marker` _could_ have been a model. 

~~~~ css
::lines {stroke: gray}
::underline {stroke-width: 2px} 
~~~~

**Comment by jensimmons** [comment]
> Are we really going to rename something after there are two implementations of it?

I definitely understand this concern.

**Comment by jfkthame** [comment]
Agree with the comments that `-weight` is not appropriate because the values bear no relation to `font-weight`; I think that would be confusing.

I'm on the fence regarding `-thickness` vs `-width`; could live with either, I think. It does seem a little odd for something that ends up as a two-dimensional shape on the page to use `width` for the dimension that is normally its height. It makes sense (IMO) if we think of the decoration as a line described by its `length` and `width` (which would be independent of the line's orientation), rather than as a rectangle (normally a very slim one!) that CSS would describe by `width` and `height`. But we don't expose its `length` because that is automatic, at which point the `width` sounds like it should be associated with a `height` like other CSS widths.

The `-thickness` name avoids the (false) implication that this is a horizontal measurement, but does perhaps seem less natural as a way to describe a line. Another possible name could be `text-decoration-breadth`, but I doubt anyone will like that; it sounds clumsy to me, even though it's a couple of characters shorter.

**Comment by fantasai** [comment]
I think from an i18n perspective and a learning perspective, given all other line weights in CSS (literally all of them, including from SVG) are in properties called `-width`, it'd be easier to learn if this one also was named `-width`. If we were starting from scratch, maybe calling them all `-thickness` or `-weight` or `-breadth` or whatever would be better to avoid confusion with the sizing properties, but given where we are now...

**Comment by jensimmons** [comment]
I put this on the CSSWG call agenda, but can't make today's meeting. Please do discuss this without me (we need these to be resolved so work in Gecko is not slowed down).

Personally, I prefer `-thickness` to `-width`. And I prefer `-weight` over both of them.

I believe `text-decoration-weight`  is best because that _is actually what is is called in print typography._ And we should use terms that have been used for hundreds of years when we can. Especially since this one does make a lot of sense. It's clear what it is. 

I do not think it's a problem that `text-decoration-weight` would have different values to `font-weight`. People can learn this. It makes sense.

I also understand if the CSSWG decides that this has already been litigated, and wants to stick to `-thickness`. I just thought `-weight` might be a prefer solution, and wanted to bring it up, since I don't believe the idea occurred to us in the past. And THAT'S THE WORD FOR IT IN TYPOGRAPHY. 

Wherever the discussion leads, I do want to see this resolved quickly. We on working on this in Gecko, and I want us to be able to ship as soon as we are ready.

(BTW, Chrome/Edge?? Any movement?)

**Comment by faceless2** [comment]
weight: consistent with print typography.
width: consistent with the rest of CSS.
thickness: er...

**Comment by bradkemper** [comment]
Forgive my plain speaking, but please let it be `-width`. It is a burden on authors new and old to have to remember inconsistent naming for similar concepts. We should not have to try to recall which properties use `-thickness`, which use `-weight`, which use `-width`, and which use whatever we come up next year for the next property needing to describe the stroke width of a line. 

In case I miss a meeting where we discuss this again, please recall my urging for `-width` (`text-decoration-width` and for all future  values measuring the thickness of lines). It is too late to go back and change border-width and outline-width and border-image-width to something else, and consistency is important.

**Comment by Crissov** [comment]
`text-decoration-width` has a disadvantage (besides lacking a `-height` counterpart): We _might_ want to add a property to control the (possibly negative) amount a decorative line protrudes beyond its text, which could be called `text-decoration-width` as well, although `-length`, `-extent` and `-protrusion` would also be available.

````
Normal Underline
----------------

  Elongated Underline  
-----------------------

Shortened Underline
  ---------------

Shortened Underline with Skips
  -----     -----    --   ---
````

**Comment by yisibl** [comment]
I am in favor of rename to `text-decoration-weight`

`text-decoration` is part of the text, so we should respect the terms in traditional typography, don't forget, essentially CSS is to restore typography and design. As for saying that width is easier to understand than weight, it is just some people's wishful thinking. Using `weight` I think this is not something that is difficult to understand. As a non-English speaker, I hate the unfamiliar and long words: thickness.

**Comment by kojiishi** [comment]
> ...so we should respect the terms in traditional typography

I'm not strong on any options, but I'm confused with this. "Thickness" is the terms in the traditional typography, but you seem to prefer...which one? `weight`?

https://docs.microsoft.com/en-us/typography/opentype/spec/post
https://stackoverflow.com/questions/13840403/edit-line-thickness-of-css-underline-attribute

**Comment by yisibl** [comment]
@kojiishi I prefer `weight`.

So both are terms in traditional typography?

**Comment by kojiishi** [comment]
I see, thank you. I personally have never heard of using "weight" for underline in traditional typography, and had an impression that people prefer it because it's already used in CSS, but if you have, fine. I just wanted to understand which you meant.

**Comment by dcrousso** [comment]
Frankly, I think that `thickness` is the least likely to be misinterpreted (vs `weight` or `width`), as it's the most directly applicable to what's visible.  If I saw a line underneath some text (broad generalization), I wouldn't ask "how _wide_ is the line" or "how much _weight_ does the line have", I'd ask "how _thick_ is the line".  I understand that there's a precedent in the typographic world, but I don't think that should be the entire reason for naming something, as I don't think we can reasonably expect _every_ (or even most) CSS authors to be familiar with typographic terminology.

I also agree with @Crissov ([comment](https://github.com/w3c/csswg-drafts/issues/4138#issuecomment-517195456)), in that there are other properties we could add that _would_ be better off using `width`/`height`, and changing this name would preclude that.

Also, given that it has already been implemented twice ([as @litherum stated](https://github.com/w3c/csswg-drafts/issues/4138#issuecomment-513639036)), that should already be reason enough to keep it as is.

**Comment by heycam** [comment]
I'm not really in favour of renaming at this point, but for interest here are the number of Google results that come back for different search terms:

* "width of underline" - 5380
* "thickness of underline" - 1780
* "weight of underline" - 8

**Comment by litherum** [comment]
![Screen Shot 2019-08-07 at 4 15 05 PM](https://user-images.githubusercontent.com/918903/62663981-8efb9f80-b92e-11e9-9bec-4275fe8f93a2.png)

**Comment by heycam** [comment]
I used quotes around my queries.

**Comment by dcrousso** [comment]
> I used quotes around my queries.

Personally, I don't think most people search with quotes unless the non-quoted string doesn't get then what they want.

**Comment by heycam** [comment]
Sure, but for the purpose of comparing popularity of the three terms, and to exclude potentially irrelevant results that include the terms but in different places on the page or in a different context, I think it's OK.

**Comment by litherum** [comment]
"width of underline" is incorrect grammar, it's unlikely to be commonly searched for.

Anyway, the purpose of me posting that screenshot was to show that, even when you search for width, the top hit uses the word "thickness"

**Comment by jonjohnjohnson** [comment]
`text-decoration-block-size` 😆

**Comment by scottkellum** [comment]
+1 for weight

**Comment by scottkellum** [comment]
+1 weight. I may change the underline weight to match the font weight better. These two things are linked in how I will address styling them.

**Comment by SebastianZ** [comment]
> <dael> fantasai: Sympathetic that we impl and shipped.

Just to note again, Mozilla's implementation did *not* ship yet. It will be in Firefox 70. See https://bugzil.la/1567282.

I personally now think, "width" would be better for consistency reasons, though I'd be fine to stay with "thickness", too.

I assume, most authors nowadays are using IDEs, which have autocompletion of property names, so that should mitigate the problem, anyway.

As [Christoph mentioned](https://github.com/w3c/csswg-drafts/issues/4138#issuecomment-517195456), there might also be a property specifying how wide a text decoration line protrudes the text at some point, but I believe authors rather associate the "width" of a line with the thickness due to the other properties using that word.

Sebastian

**Comment by valtlai** [comment]
> As [Christoph mentioned](#issuecomment-517195456), there might also be a property specifying how wide a text decoration line protrudes the text at some point,

Maybe that would be called `text-decoration-limit`, `-clip`, or whatever the somewhat similar property for [partial borders](https://drafts.csswg.org/css-backgrounds-4/#partial-borders) will be called.

**Comment by chharvey** [comment]
Any ideas on adding a _new_ property `text-decoration-weight` with the values `100 | 200 | 300 | …` etc? This would resolve many of the concerns in the comments above.
