### ISSUE TITLE
[css-color-adjust-1] background-color in forced color modes needs more than a simple unset

### ISSUE THREAD

**Issue by melanierichards** [w3c/csswg-drafts#4175]
In [Properties Affected by Forced Colors Mode](https://www.w3.org/TR/css-color-adjust-1/#forced-colors-properties) we define a set of UA stylesheet expectations for various properties, including:

```
background-color: revert !important;
```

In practice, this means most elements are unset to a transparent background color, which is not precisely the best user experience. For example, as the spec is currently written, `.foo` in [this fiddle](https://jsfiddle.net/3s65bgjq/) would have a transparent background and would be awkward to modify via UA stylesheet on top of an unset/revert.

Instead, we probably want to manage the forced `background-color` post computed-value resolution, such that:

* Elements with non-transparent computed background colors are rendered with a solid system background color (e.g. `.foo` in the example renders with a background color of `Canvas`)
* Otherwise, elements' `background-color` can be unset as described. The UA is then free to make further adjustments in their stylesheet, using simple selectors (e.g. selecting for `<button>` elements).

The spec probably needs a language update if allowing this UA logic seems reasonable.

**Comment by atanassov** [comment]
One more clarification in case it is needed. The intended behavior is for `background-color'`only, `background-image` are unaffected. The intended contrast ratios in these cases is achieved through the use of `backplate`.

**Comment by fantasai** [comment]
Another question: define “non-transparent”? :) Is it only rgba(0,0,0,0) or also other fully-transparent colors?

(It would be really nice if `transparent` computed to itself here, so we could run the check against the keyword and not one edge of a continuous scale.)

**Comment by melanierichards** [comment]
Good question, I was considering "transparent" to mean "any color whose alpha channel computes to `0`". So both of these should be unset based on computed value, as opposed to rendered with a system background color: https://jsfiddle.net/pn7sjc2h/2/embedded/result

**Comment by fantasai** [comment]
OK, I edited this in https://github.com/w3c/csswg-drafts/commit/cffce2008ce030f4b098aece82b95c109485594f

I ran into a complication: not all elements are supposed to be forced to CanvasText. It wasn't clear from the discussion what to do here, so I specified that if the UA stylesheet has no background-color rule, then we do the force-channels-other-than-alpha rule, but if it does, we revert.

Marking Agenda+ to discuss whether that's what we want, or we want something else.

**Comment by fantasai** [comment]
OK, I drew up wording for both proposals and they're now in the draft at https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties Agenda+ to choose, and republish this draft as WD!

**Comment by AmeliaBR** [comment]
We were also asked in the last discussion to provide examples.  Here's a quick one that covers the two problematic cases:

https://codepen.io/AmeliaBR/pen/dyoLMGd

![demo with regular colors, a button with text and icons and a pop-up tooltip that partially obscures other text on the page](https://user-images.githubusercontent.com/9876129/78195634-697f5100-743d-11ea-85da-e6c1a8b0cab9.png)


Both issues are demonstrated using childs of buttons, but they could be childs of any element that has special colors in forced-color mode (e.g., links).

One element (svg icon) must have transparent background or it will obscure the text. The other element (pop-up) needs to have a solid background, and that background color must be properly paired with the text color (which in forced-color mode would be the inherited button text color).

Here's how it looks in Chromium Edge currently, with various color schemes:

1. One of the standard dark mode contrast schemes. Note that the button white text is used on the pop-up, instead of the main canvas green text, but that the button and canvas backgrounds are both black.

   ![image, as described](https://user-images.githubusercontent.com/9876129/78195896-0f32c000-743e-11ea-85f1-bfd482ef0281.png)

2. One of my custom low-contrast schemes, and then a custom high-contrast I made for this demo. In these cases, the button and canvas backgrounds are different, so you see that Edge is drawing in a backplate around the button text that is not the right color for the button, and similarly the background color used for the pop-up isn't correct.  The first one is supposed to have pink text on dark blue buttons, the second one is supposed to have dark blue text on yellow buttons:

  ![color scheme is mostly purple and light blue. the padding area of the button is dark blue, but the text color is pink](https://user-images.githubusercontent.com/9876129/78195800-c7139d80-743d-11ea-9ad4-8773ae1b0008.png)

  ![different colors, but same issues, and even worse readability](https://user-images.githubusercontent.com/9876129/78196045-751f4780-743e-11ea-8860-16ebfb96ba8a.png)
