### ISSUE TITLE
[css-lists-3][css-pseudo-4] Does text-transform inherit to ::marker?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4206]
Gecko blocks inheritance of `text-transform`, whereas Chrome allows it. [Testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Col%20type%3Da%20style%3D%22text-transform%3A%20uppercase%3B%22%3E%0A%3Cli%3Ea) What should the spec say?

Originally raised in http://www.w3.org/mid/515ED601.3090909@exyr.org by @SimonSapin

**Comment by Loirooriol** [comment]
Actually it's more complex than "Gecko blocks inheritance of text-transform, whereas Chrome allows it."

Consider this [testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Ali%20%7B%20text-transform%3A%20uppercase%20%7D%0A.type-roman%20%7B%20list-style-type%3A%20lower-roman%20%7D%0A.type-string%20%7B%20list-style-type%3A%20%27i.%20%27%20%7D%0A.marker-roman%20%3A%3Amarker%20%7B%20content%3A%20counter(list-item%2C%20lower-roman)%20%27.%20%27%20%7D%0A.marker-string%20%3A%3Amarker%20%7B%20content%3A%20%27i.%20%27%20%7D%0A%3C%2Fstyle%3E%0A%3Col%20class%3D%22type-roman%22%3E%3Cli%3Econtent%3C%2Fli%3E%3C%2Fol%3E%0A%3Col%20class%3D%22type-string%22%3E%3Cli%3Econtent%3C%2Fli%3E%3C%2Fol%3E%0A%3Col%20class%3D%22marker-roman%22%3E%3Cli%3Econtent%3C%2Fli%3E%3C%2Fol%3E%0A%3Col%20class%3D%22marker-string%22%3E%3Cli%3Econtent%3C%2Fli%3E%3C%2Fol%3E):

```html
<ol class="type-roman"><li>content</li></ol>
<ol class="type-string"><li>content</li></ol>
<ol class="marker-roman"><li>content</li></ol>
<ol class="marker-string"><li>content</li></ol>
```

```css
li { text-transform: uppercase }
.type-roman { list-style-type: lower-roman }
.type-string { list-style-type: 'i. ' }
.marker-roman ::marker { content: counter(list-item, lower-roman) '. ' }
.marker-string ::marker { content: 'i. ' }
```

Firefox renders it as

```
i. CONTENT
i. CONTENT
 I.CONTENT
 I.CONTENT
```

So it seems ::marker's `content` obeys `text-transform` just like a ::before would do, but `list-style-type` does not. But I guess https://bugzil.la/1542807 may make `list-style-type` obey `text-transform`.

Note that Chromium doesn't support ::marker yet, but recently I implemented `list-style-type: <string>`. With LayoutNG, the result looks like

```
I. CONTENT
I. CONTENT
1. CONTENT
1. CONTENT
```

So `list-style-type` obeys `text-transform`. But in legacy, `list-style-type` behaves like in Firefox:

```
i. CONTENT
i. CONTENT
1. CONTENT
1. CONTENT
```

Given that Firefox plans to remove legacy layout code path for ::marker, and Chromium will also remove legacy layout at some point, maybe we can resolve that ::marker should inherit `text-transform`? And probably other text properties like `letter-spacing` and `word-spacing`?

**Comment by emilio** [comment]
cc @MatsPalmgren

**Comment by fantasai** [comment]
The question of whether these properties apply is a separate one from whether we should reset them on ::marker in the UA style sheet, though.

Thinking about it more, especially in light of the `list-style-type` values being case-sensitive, I think we should block inheritance here for at least `text-transform`.

And maybe also `letter-spacing` and `word-spacing` also.

Poking @dauwhe / @jensimmons / @faceless2 for authoring perspective.

**Comment by Loirooriol** [comment]
I don't follow the argument. If you have a ::before pseudo-element, then `content: "a"` or `content: "A"` is case-sensitive, but it still obeys `text-transform`. Why shouldn't ::marker do the same?

**Comment by fantasai** [comment]
@Loirooriol Because conceptually (from an authoring, rather than implementation perspective) ::before/::after are more part of the content of the paragraph, whereas markers are more separate from it. And in particular because markers are commonly used in a way where casing creates a semantic distinction. Making the author go through the extra step of requesting the loss of casing information explicitly is therefore a good idea, imho.

**Comment by Loirooriol** [comment]
If they don't want to lose a semantic distinction, maybe they shouldn't be using `text-transform` in the first place. Blocking inheritance by default would also make authors who want to lose it go through the extra step of setting `::marker {all: unset}` or something.

Given that, regardless of what we decide, it will always be an annoyance for some authors, I would just keep the UA styles for ::marker as simple as possible, and not block inheritance.

**Comment by dauwhe** [comment]
I was actually quite surprised that 

```css
ol { list-style-type: lower-roman; }
li { text-transform: uppercase; }
```

is not interoperable, and that something I do to a list item can potentially mess with the list marker. I explicitly said I wanted lowercase numbering. Why does Chromium (and Prince) get to change that?

I think of this as a separation of content (`li`) and style (the list marker). So I don't want text-transform to inherit to ``::marker``.

**Comment by faceless2** [comment]
I think I agree with @fantasai and @dauwhe, mainly because a ::marker can be generated and populated with content without the author ever having heard of the `::marker` pseudo-element.

That means we really have to try and do the right thing in the UA stylesheet - resetting `text-transform`, and probably `letter-spacing`, `word-spacing` and `text-indent` (if it applies). We already reset `unicode-bidi` and set `font-variant-numeric`, so markers are already a little bit different to before/after.

I think the case for resetting `letter-spacing` and `word-spacing` is much less clear for inside markers, but I know we went over that in #4568 and didn't get to a solution. If we don't want to do anything clever here (as discussed in #4568) then optimizing for the most common case means we should reset them.

Because we have inside list markers, all text properties must all still apply. But I don't think anyone's arguing against that.

(aside: I know there's a list somewhere of what proportion of websites use certain features, but can't find it. What does it say about `list-style-position: inside`?)

**Comment by Loirooriol** [comment]
IMO the only of these properties for which blocking inheritance seems a clear benefit is `text-indent`, for the reason described in https://drafts.csswg.org/css-text/#text-indent-property

> Since the `text-indent` property inherits, when specified on a block element, it will affect descendant inline-block elements. For this reason, it is often wise to specify `text-indent: 0` on elements that are specified `display: inline-block`.

Outside markers are inline-block-like (and actual inline-blocks in Chromium LayoutNG), and this is not obvious to authors since they didn't set `display: inline-block` themselves, so `text-indent: 0` in UA origin seems wise.

**Comment by tabatkins** [comment]
I also agree that it would be surprising to me to have text-transform affect the marker by default; it means that to "safely" do text-transform on the content of a list item, I have to wrap the contents in a `span` and style *that* instead.

I think I'm with @faceless2, in that while general styling *should* inherit (color, weight, etc), anything that can affect the semantics or otherwise make it harder to understand the marker should be blocked.

**Comment by MatsPalmgren** [comment]
Fwiw, I agree with the resolutions above. I think it's a reasonable default behavior. Authors can easily override that UA rule as they see fit.

**Comment by bradkemper** [comment]
I'm a little late, but I think the resolution is a good one. I don't expect text-transform to affect the market, and this seems like a reasonable way to prevent it without magic or tying the hands of authors who want to explicitly transform the case of the marker.

**Comment by Loirooriol** [comment]
I have changed Chromium and added some WPT checking that `text-transform` is supported and that it defaults to `none`.
So now what's missing is just updating the spec.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/a1caf7722a2253e42ebfd538cf166c4e2cea1569
