### ISSUE TITLE
[css-scroll-anchoring] Should not apply anchoring adjustments from scroll event handlers

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4239]
Most of the most annoying scroll anchoring issues I've fixed on Firefox over the last few months are due to the adjustments accidentally triggered from scroll event listeners. Some examples off the top of my head:

 * https://bugzilla.mozilla.org/show_bug.cgi?id=1568778
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1543599

These adjustments trigger other scroll event listeners, which in turn generally either confuse the page or let the page burn a lot of CPU for no good reason.

The spec has the concept of [suppression triggers](https://drafts.csswg.org/css-scroll-anchoring/#suppression-triggers) to prevent most of these. Those are mostly heuristics, and are not equally implemented across browser.

In https://bugzilla.mozilla.org/attachment.cgi?id=9087497 I came up with a reduced test-case for something that we saw in the wild, and for which we _don't_ want to suppress the adjustment in the more general case of it not being triggered by a scroll event listener. The test-case locks up scrolling in Firefox and Chrome once you scroll to the bottom.

Other than not doing scroll anchoring adjustments every time anyone updates layout (which may or may not be implementable), the other reasonable solution I can think of is to not adjust scroll positions of an element if we're processing an scroll event listener for that target.

That's what I'm going to implement in https://bugzilla.mozilla.org/show_bug.cgi?id=1561450, I think, and I'm going to investigate removing other suppression triggers which should be unnecessary after that change as followup work.

cc @skobes @eqrion @dholbert

**Comment by skobes** [comment]
Is this proposal specifically limited to scroll handlers that force synchronous layout (e.g. reading back offsetTop or scrollTop after changing the DOM) before yielding?

Based on https://phabricator.services.mozilla.com/D43233 it sounds like yes.  Blink could also implement this fairly easily.

Some historical context: the sticky header feedback loops that we originally encountered didn't necessarily force synchronous layout.  They would just touch DOM and yield.  Then the lifecycle update performs the scroll anchoring adjustment, but we are no longer "inside" the listener.

We thought about a more general solution, in which the adjustment would be suppressed if the movement of the anchor node occurred "because of" a scroll event listener which finished in the past.  We concluded that tracking causality in this manner was too difficult.

The cases that motivated http://bit.ly/sanaclap ("suppression triggers" in the spec) would not have been solved by merely suppressing adjustments during sync layouts inside scroll listeners.

But it might make sense to do this, if it fixes additional cases that are not addressed by the suppression triggers.

On the other hand it is weird for the behavior to be different because the scroll listener did a layout-forcing readback before yielding.  Usually a readback is a nop.

**Comment by emilio** [comment]
> Is this proposal specifically limited to scroll handlers that force synchronous layout (e.g. reading back offsetTop or scrollTop after changing the DOM) before yielding?

Yes, basically.

> Some historical context: the sticky header feedback loops that we originally encountered didn't necessarily force synchronous layout. They would just touch DOM and yield. Then the lifecycle update performs the scroll anchoring adjustment, but we are no longer "inside" the listener.
> We thought about a more general solution, in which the adjustment would be suppressed if the movement of the anchor node occurred "because of" a scroll event listener which finished in the past. We concluded that tracking causality in this manner was too difficult.

I see, that's fair.

> The cases that motivated http://bit.ly/sanaclap ("suppression triggers" in the spec) would not have been solved by merely suppressing adjustments during sync layouts inside scroll listeners.
>
> But it might make sense to do this, if it fixes additional cases that are not addressed by the suppression triggers.

It does, see above. But you're right we probably  cannot remove the existing triggers.

> On the other hand it is weird for the behavior to be different because the scroll listener did a layout-forcing readback before yielding. Usually a readback is a nop.

Well,  it is when scroll anchoring _isn't_ suppressed when reading back also changes scroll positions, right? At least that's my mental model of it.

**Comment by emilio** [comment]
@skobes interesting, that document mentions running adjustments during the animation frame, that's one of the things we thought about too... see https://bugzilla.mozilla.org/show_bug.cgi?id=1529702.

That would _also_ fix this issue of scroll listeners doing readback, fwiw...

**Comment by skobes** [comment]
Chrome does defer scroll anchoring adjustments to a well-defined point in the frame lifecycle.  I think this is also in the spec, which defines the "suppression window" with reference to the event loop.

However, readback of scroll position forces the adjustment to occur (there is a test that verifies this).  There is some discussion on the review thread of https://codereview.chromium.org/2404393003 about when to flush the adjustment.

**Comment by emilio** [comment]
Sure, so does Gecko, but reading back layout-dependent values goes through all the lifecycle steps including applying adjustments, unless I'm misreading the blink code:

https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/dom/document.cc?l=3038&rcl=85bca75346768d2f213696319acdd149467a8bab

So doing stuff like `getBoundingClientRect()`, or `offsetHeight`, or whatever else would _also_ perform adjustments.

**Comment by chrishtr** [comment]
I currently don't think we should update the spec to disallow scroll anchoring adjustments from scroll event handlers. I think it's ultimately too arbitrary and restrictive.

In addition, I have been able to find solutions to a few of the cases Emilio added to the WPT test suite without resorting to disabling scroll anchoring during scroll event handlers. See:

https://chromium-review.googlesource.com/c/chromium/src/+/1902767
https://chromium-review.googlesource.com/c/chromium/src/+/1928243
https://chromium-review.googlesource.com/c/chromium/src/+/1929439

**Comment by emilio** [comment]
So one of the diffs (https://chromium.googlesource.com/chromium/src.git/+/6a9dd6d26726f346345cf1970c2bc3af3ec1afbd) changes the expectations of http://w3c-test.org/html/interaction/focus/the-autofocus-attribute/update-the-rendering.html... What's the reasoning for that? https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering seems it defines the order that _was_ in the test...

Also, that commit means that scroll events from scroll anchoring are not dispatched directly, but at the end of a frame if something else has not changed the offset back... right? If so, that is observable and we should probably put that in the spec.

**Comment by chrishtr** [comment]
The CL causes scroll offsets due to scroll anchoring and clamping (but *not* other causes, such as explicitly setting scroll offset via script) to occur after the layout part of the update-the-rendering steps have completed. Therefore the scroll events corresponding to them are sent at the subsequent update-the-rendering event loop opportunity.

i.e. the sequence is:

1. Web app dirties layout
2. Update-the-rendering runs (frame N)
2a. Various things, including firing any scroll events
2b. Layout
2c. Enqueue scroll event
...
3. Update-the-rendering runs (frame N+1)
3a. Fire scroll event enqueued by 2c
...

Before my CL, a scroll anchor or clamp related to a forced layout would enqueue a scroll event right then and there. But I don't think anything in the spec requires this. Instead we can enqueue it after layout during update-the-rendering, resulting in it being fired in the next frame (N+1 in my example above).

**Comment by chrishtr** [comment]
I think we should go ahead and close this and not change the specs. @emilio ok by you?

**Comment by emilio** [comment]
Yeah, I'm ok with this, sorry for the lag.
