### ISSUE TITLE
[cssom-view] [css-tables] should table.clientWidth include borders?

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#4245]
Firefox includes table borders in clientWidth. Blink doesn't. I suspect Firefox adheres closer to the spec (though see below), but is it intended that `table.clientWidth` and `table.offsetWidth` always return the same value?

Given that the border properties apply to the table grid box, not the table wrapper box, the pertinent question is: does clientWidth operate on table wrapper box or table grid box?

The text from [clientWidth](https://drafts.csswg.org/cssom-view/#dom-element-clientwidth) :

1. If the element has no associated CSS layout box or if _the_ CSS layout box is inline, return zero.  
2. N/A
3. Return the width of _the_ padding edge excluding the width of any rendered scrollbar between the padding edge and the border edge, ignoring any transforms that apply to the element and its ancestors

I assume that when the steps above say _the_, they refer to the element's principal box, but could I get clarification on that? Should they, in this case, refer to the table grid box? If these steps do refer to the principal box, then FF behavior is correct but seemingly unfortunate in that offsetWidth and clientWidth are the same for tables. Which brings back to the original question: is it intended that table.clientWidth and table.offsetWidth are the same?

More relevant research:
The [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=820891) where Gecko switched to using the wrapper box for client* properties cites the definition of offset* as justification, which [does say](https://drafts.csswg.org/cssom-view/#dom-htmlelement-offsetwidth) that offset* operates on the wrapper box. But the relevant part of that definition—"Return the border edge width of the _first_ CSS layout box"—only appears for the offset* properties, not the client* properties.

Further, the offset* and client* properties are extensions of different interfaces: offset* is on HTMLElement. client* is on Element. Is that relevant to why offset* includes _first_ CSS layout box but client* doesn't?

This stems from a [chrome bug report. ](https://crbug.com/978019)

/cc @FremyCompany  @fantasai (as she was instrumental in the current definition of table wrapper box)

**Comment by FremyCompany** [comment]
I would tend to think that both client* and offset* properties should refer to the wrapper box, and that box doesn't have a border applied to itself, so it's clientTop should be 0 and its clientWidth should match its offsetWidth. From what you describe, this seems to match what Firefox is currently doing?

Besides, Chrome might need a fix regardless of the decision we take here, because clientTop currently ignores any space taken by the captions. I don't think it's reasonable for clientTop to not include the space taken by the captions if it is going to include the border of the table-grid box. I would rather keep math consistent.

Actually, this got me thinking: since the math in Chrome is not consistent, I suspected that the padding edge used for absolutely positioned elements would be incorrect in Chrome when a table was the containing block and it also had a caption, and it turns out it is indeed incorrect. 

https://wptest.center/#/sf7zh0 (click the "Refresh watches" button to see the values, seems like there is a race condition issue to be debugged here; then compare visually the position of the blue span in Chrome vs Edge/Firefox)

**Comment by FremyCompany** [comment]
Based on that, I'd be inclined to say it'd be better for Blink to match the other engines in this case.

**Comment by FremyCompany** [comment]
Look at the test case. The span is positioned according to the grid box wrt the left but according to the wrapper box plus the border wrt the top.

My understanding is thus that Chrome is using the wrapper box, but doesn't take into consideration the fact it doesn't have a border for its used value.

**Comment by FremyCompany** [comment]
clientWidth/clientTop are what you want if you want to compute the size/position of an abspos whose containing block would be the current element.

As such the values returned in chrome are consistent with its incorrect positioning of the abspos.

But as you agreed the abspos is not correctly positioned.

**Comment by emilio** [comment]
Gecko changed behavior a while back here intentionally: https://bugzilla.mozilla.org/show_bug.cgi?id=82089. cc @bzbarsky

**Comment by FremyCompany** [comment]
I don't know any other, except checking if they match scroll* properties (which otherwise means there is a scrollbar and it has wiggling room) but tables can't have scroll bars.

**Comment by emilio** [comment]
Err, sorry, I missed you have linked that already, removed to just cc Boris then :)

**Comment by FremyCompany** [comment]
https://github.com/w3c/csswg-drafts/issues/4245#issuecomment-525492030 @emilio this bug doesn't look like it's about tables, did you paste the right one?

**Comment by FremyCompany** [comment]
@bzbarsky Chrome behavior is that you take the wrapper box, then deduct its border thickness (which should be 0 but is actually the same as the table grid box border, I guess they just don't change their internal style representation and ignore the border on table wrapper boxes). It's indeed wrong, and this is also what they use when the table wrapper box is the containing block of an abspos, which makes this even more of a problem.

Still pretty sure the fix is Chrome's to make here. But I don't disagree the specs could benefit from some clarifications.

**Comment by davidsgrogan** [comment]
If there's no big loss in clientWidth and offsetWidth always returning the same for a table, and the primary use-case for clientWidth is gathering data about where an abspos will be positioned, then I agree that Firefox's behavior is correct.

OTOH, I'm quite sad for the developer who is surprised to see that clientWidth includes borders for tables but not most other elements (see https://jsfiddle.net/dgrogan/vLfyjk8x/1/ in Firefox) -- it appears as another inconsistency (or at least another point of confusion) in the platform.

**Comment by bzbarsky** [comment]
@FremyCompany Do you know whether there is a Blink issue tracking this?

**Comment by davidsgrogan** [comment]
I'm not @FremyCompany but I do work on Blink, and the issue is the same one I included above: https://crbug.com/978019

**Comment by bzbarsky** [comment]
Ah, sorry, I had skimmed for a crbug or bugs.chromium.org url, and didn't see one.

I agree that tables are weird in various ways, especially when borders are involved.  The behavior you get with border-collapse does not help with that either...

I don't have _that_ strong an opinion on what the behavior should be here subject to: (1) it should make sense even when there is a caption; Blink's current behavior does not and (2) we should all agree on it and implement it interoperably.

**Comment by davidsgrogan** [comment]
I've been mulling it over and haven't come up with something that would make sense when there is a caption while also keeping the cases in https://jsfiddle.net/dgrogan/vLfyjk8x/1/ consistent, so we're going to have Blink add borders to table.clientWidth.

Thanks for the discussion, all.

**Comment by FremyCompany** [comment]
Sounds good then. I will add a clarifying note in the spec, just so this doesn't fall through the cracks of a rewrite in some browser.

**Comment by bzbarsky** [comment]
@FremyCompany could you also add some web platform tests?  Some people are a lot more likely to notice a test failure than a note in the spec...

**Comment by davidsgrogan** [comment]
We've got a web platform test in https://chromium-review.googlesource.com/c/chromium/src/+/1763510 for collapsed borders but should/will add another for separate borders before committing.

**Comment by bzbarsky** [comment]
And captions, please!

**Comment by davidsgrogan** [comment]
We changed Blink behavior to match this resolution a few months ago.
