### ISSUE TITLE
[css-text-3] Allow breaking anywhere when dictionary is missing for SEA scripts

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4284]
For scripts that require dictionary breaking or some other morphological analysis, if the resource is missing and the UA can't break the text, it should be allowed to break anywhere instead of overflowing.

**Comment by fantasai** [comment]
Note: This has been a problem with Javanese.

**Comment by rober42539** [comment]
I think that in Lao, there should be a way to detect the syllables. ICU supports word boundary analysis/word tokenization, so this is less of an issue now except on the few applications not using ICU (Firefox doesn't yet use ICU's line-breaker, though they use other parts of ICU it seems). 

But, if we want to be safe, and not assume that the browser has ICU support, it would be much more desirable to break at the syllable, rather than cutting one in half. Some vowels in Lao (Thai, Khmer, Burmese) wrap around the nuclear consonant, so if you break it at the wrong place, it cuts your vowel in half between 2 lines (very difficult to read). There is a document I will link to that helps explain this... 

[panl10n.net Syllabification of Lao Script for Line Breaking](http://www.panl10n.net/english/outputs/Working%20Papers/Laos/Microsoft%20Word%20-%206_E_N_296.pdf)

**Comment by rober42539** [comment]
![image](https://user-images.githubusercontent.com/282862/65009131-db76c980-d935-11e9-8fe6-a19b7bcc8b9e.png)

This excerpt explains the 'format' for which a Lao syllable is constructed.

Syllable breaking is usable in Lao and many people tend to be OK with it, but ultimately it isn't optimal, as it can render text more difficult to read than if the line-breaking is based on word boundaries, from my understanding.

**Comment by jmdurdin** [comment]
Not sure about panI10n.net rules but Lao syllable breaking has been fully implemented by Lao Script for Windows since about 1993 (usually using ZWSP insertion).  Excluding loan words, there are few ambiguities, and they are easily managed by *not* allowing a break if it would be ambiguous.  For Lao, as well as keeping grapheme clusters together, a break should never be allowed after a prefix vowel or before U+0EB2 LAO VOWEL SIGN AA, or either before or after  U+0EBD LAO SEMIVOWEL SIGN NYO.  Thai syllable breaking is much more difficult and requires a moderately large dictionary to be effective.

**Comment by fantasai** [comment]
Just want to be clear, this issue isn't about where to break correctly. It's what to do if you don't have the ability to break correctly.

**Comment by fantasai** [comment]
The proposal is "if you don't know where it's allowed to break, break somewhere, anywhere, instead of overflowing the box by not breaking at all".
