### ISSUE TITLE
[css-values] Computed value of a negative calc unit that doesn't allow negative lengths.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#434]
In the [CSS values spec, section 8.1.4. Range Checking](https://drafts.csswg.org/css-values/#calc-range):

> However, the **used value** resulting from an expression must be clamped to the range allowed in the target context.

Note that the used value is expected to be clamped, but not the computed value. Both Blink and Firefox (at least, probably other engines too) clamp the value at computed value time, as can be seen running the following test, where all the properties that don't accept negative lengths (like `font-size`, `padding-xxx`, etc.) report a computed value of `0px` instead of the expected `-1px`.

``` html
<!doctype html>
<script>
window.onload = function() {
  let style = window.getComputedStyle(document.body);
  for (prop of style) {
    if (prop in document.body.style) {
      document.body.style[prop] = 'calc(-1px)';
      console.log(prop, "reported: ", getComputedStyle(document.body)[prop]);
    }
  }
}
</script>
```

**Comment by emilio** [comment]
cc @SimonSapin

**Comment by emilio** [comment]
For the record, Firefox does follow the spec correctly, but clamps the value in `GetComputedStyle`. I guess that's more of another kind of issue.

**Comment by dbaron** [comment]
For properties where the computed value is a length (i.e., calc()s are computed at computed value time) like <code>font-size</code>, we clamp to nonnegative values at computed value time.  For properties where the calc() expression is part of the computed value space (like <code>font-size</code>) we have clamping at used value time (both in the GetComputedStyle code and in the code that actually uses the value).

I think the spec is still wrong for properties that accept calc() but where calc() is not part of the computed value space since it can be fully computed by computed value time (e.g., <code>font-size</code>).

**Comment by emilio** [comment]
Yeah, and WebKit (and Blink) also clamp at computed value time, see https://github.com/WebKit/webkit/blob/e999a05729f1c284fd6e734b88e81a2b078ed80f/Source/WebCore/css/CSSCalculationValue.cpp#L195

**Comment by tabatkins** [comment]
Note that getComputedStyle() returns the used value for a number of length-using properties, so that pollutes the data quite a bit here. WebKit/Blink doesn't actually have a separate notion of "computed value" in the engine.

**Comment by tabatkins** [comment]
Current text is:

> Parse-time range-checking of values is not performed within ''calc()'',
> and therefore out-of-range values do not cause the declaration to become invalid.
> However, the used value resulting from an expression
> must be clamped to the range allowed in the target context.

I propose we change this to:

> Parse-time range-checking of value is not performed within ''calc()'',
> and therefore out-of-range values do not cause the declaration to become invalid.
> However, at the point in the value computation process where the ''calc()'' can be resolved to a single term,
> it must be clamped to the ranged allowed in the target context.
> (For example, 'font-size' can resolve ''calc(10% - 1em)'' to a single term at computed-value time 
> (to -.9em, as it turns out), 
> which will then clamp to ''calc(0)''. 
> ''width: calc(10% - 1em)'', on the other hand, 
> can't resolve into a single term until used-value time.)

**Comment by fantasai** [comment]
Okay, so there are two interpretations of what dbaron said:
  * That clamping happens at each stage (computed and used), if it is possible at that stage.
  * That clamping happens at the stage in which it's guaranteed to be possible.

For example, `font-size` can compute all of its values at computed value time (and indeed, must do so in order for ems to be able to compute elsewhere). It would clamp at computed value time; and clamping at used value time is unnecessary.

`width` however depends on layout information to resolve percentages, and therefore it cannot clamp values that mix percentages and lengths at computed value time. Therefore two behaviors are possible:
  * `width` clamps calc() expressions that do not mix lengths and percentages at computed value time, and clamps calc() expressions that do mix them at used value time
  * `width` only clamps calc() expressions at used value time.
  
The latter seems slightly simpler, but since it means that a property only clamps exactly one time, a property that currently only has computed-value units and then later adds used-value units would change behavior in an author-observable way.

The wording for each of these options would be different, so we need the WG to resolve on which one.

**Comment by astearns** [comment]
Need to see more testing results before this goes on the agenda again.

**Comment by astearns** [comment]
I've written these tests that check whether an animated negative calc value is clamped at computed value time (and thus a range of negative values aren't present in the animation) or used value time (where a range of negative values will be present in clamped form for a duration in the animation)

https://github.com/astearns/web-platform-tests/commit/da5892fdfb227227c924405467f823b34c33b9a0

The results I'm seeing are all over the place. Pass means clamping is happening at used value time (mostly). Fail means it's clamping at computed value time.

width and padding-left have the same results

width-up
FF, Chrome: pass
Safari: fail
Edge: no animation

width-down
FF: pass
Safari, Chrome: fail
Edge: no animation

opacity and font-size have the same results

opacity-up
Chrome, Edge: pass
(though the Chrome animation appears to be incorrect)
Safari, FF: fail

opacity-down
Chrome, Safari, FF, Edge: fail

font-size up
Chrome: pass
FF, Safari: fail
Edge: loading problem page (though the animation seems to fail)

font-size down
Chrome, FF, Safari: fail
Edge: no animation

**Comment by birtles** [comment]
Alan, which version of FF did you test? The results may not differ but our animation code has changed significantly from version 57 onwards.

**Comment by astearns** [comment]
I'm on Mac nightly, so 58-ish? - I'll edit in the exact version number when I get back to the office tomorrow

**Comment by birtles** [comment]
That's recent enough--thank you!

**Comment by dbaron** [comment]
It may also be worth testing Firefox 56, though, since that's the code currently shipping.

**Comment by dbaron** [comment]
FWIW, I'd note that the Firefox results make sense to me:  the properties where calc() can be handled at computed value time "fail", and the properties where it needs to be deferred to used value time "pass".

**Comment by fantasai** [comment]
Agenda+ because we have test results (above) and a proposal (https://github.com/w3c/csswg-drafts/issues/434#issuecomment-310183908) and this is blocking CR update of Values and Units for months now so it would be really nice to resolve and republish.

**Comment by tabatkins** [comment]
@dbaron That has the forward-compatibility problems noted by @fantasai in <https://github.com/w3c/csswg-drafts/issues/434#issuecomment-310183908> - if a property initially accepts only computed-value-time units, it would be clamped at computed-value time, but if it later starts accepting used-value-time units, we'd have to move it to clamping at used-value time, which is observably different.

Thus the proposal to clamp at both spots - computed value clamping if possible, used-value clamping otherwise.  That way a `width: calc(-50px)` would clamp "early", at computed-value time, but a `width: calc(10px - 10%)` would clamp "late", at used-value time.

**Comment by astearns** [comment]
In the discussion above we talked about (but did not resolve) on what happens to calc() expressions when the value is clamped. I believe there was consensus on the call to simplify the calc() expression in that case, as the clamping changes the value significantly from what the expression might appear to be. 

We've had discussions in the past about preserving calc() expressions for tooling. It might be weird to have a "calc(50px)" value maintain the expression for a computed value, but a "calc(-50px)" value get simplified to "0px" upon clamping at computed value time. But it might be useful to represent the clamping in this edge case. Do you have an opinion, @therealglazou?

**Comment by therealglazou** [comment]
I am fine with the resolution from confcall 20171213.

**Comment by fantasai** [comment]
Ok, I've checked in the following changes:

> However, the <del>used</del> value resulting from an expression must be clamped to the range allowed in the target context. <ins>Clamping is performed on computed values to the extent possible, and also on used values if computation was unable to sufficiently simplify the expression to allow range-checking.</ins>

@emilio @tabatkins Can you let me know if that seems adequate?

**Comment by tabatkins** [comment]
:+1:

**Comment by emilio** [comment]
Looks good to me, thanks! Maybe noting explicitly that clamping should _not_ be done at specified value time is worth it? WebKit / Blink are buggy here wrt numbers / integers IIRC.

Haven't checked if it's something mentioned in other places of the spec.

**Comment by fantasai** [comment]
@emilio OK, added parenthetical about specified values.

> Clamping is performed on computed values to the extent possible, and also on used values if computation was unable to sufficiently simplify the expression to allow range-checking. <ins>(Clamping is not performed on specified values.)</ins>

**Comment by fantasai** [comment]
Closing out per @emilio’s verification over IRC.
