### ISSUE TITLE
[css-grid] Simplifying the new syntaxt of the grid shorthand 

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#438]
https://drafts.csswg.org/css-grid/#grid-shorthand

The new syntax suggests the use of " [ auto-flow && dense? ]" instead of reusing the current <grid-auto-flow> syntax. The only different is that <grid-auto-flow> allows omitting the 'auto-flow' value, assuming 'row' in that case. 

My proposal would be the following syntax:

<‘grid-template-rows’> / <'grid-auto-flow'> <‘grid-auto-columns’>? | <'grid-auto-flow'> <‘grid-auto-rows’>? / <‘grid-template-columns’>

**Comment by fantasai** [comment]
IIRC the reason Tab and I decided to use 'auto-flow' rather than the 'row'/'column' keywords was to make the shorthand a little more self-evident: just stating 'row' or 'column' in the appropriate place didn't make it as clear that the subsequent track-sizes were auto-flowed rather than part of the template. Since whether it was a row or column was already implied by the placement (it's implied whether you're doing auto-flow or template), we decided to use the 'auto-flow' part of the property name as a keyword here.

**Comment by javifernandez** [comment]
Ok, I really don't have an strong opinion, regarding the syntax, and I understand your point. My doubt was just whether we could simply the syntax, so we can do it the same at the implementation level. 

I'll leave this open for a while, just in case somebody else wants to add something, but I'll proceed with the implementation of the new syntax as it's written now.

**Comment by fantasai** [comment]
Javier, does this logic work for you?

**Comment by javifernandez** [comment]
Yes, I'm fine with the decision.
