### ISSUE TITLE
[css-ui] Actual caret caret-shape

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4402]
[`caret-shape`](https://drafts.csswg.org/css-ui-4/#propdef-caret-shape) currently defines three common types: `bar`, `block` and `underscore`. 

In handwritten proofreading marks, a _caret_ is an arrow-head instead, either pointing upwards from below (like U+2038 `‸` _caret_ and ) or downwards from above (like U+02C7 `ˇ` _caron_), cf. U+2380 `⎀` _insertion symbol_ and U+2324 `⌤`. Additionally, there are variants with one leg extended (e. g. like U+2041 `⁁` _caret insertion point_). 
I suggest to add keywords for these. They would be horizontally positioned like `bar`. 

Iʼm not sure whether there should also be a way to have both at once, an arrow-head from the top and one from the bottom.

Iʼm also not sure whether there should also be variants with filled chevrons, i. e. triangles.

**Comment by AmeliaBR** [comment]
Do you have examples of interactive user interfaces that are using these marks, or complaints about the inability to use them?

**Comment by litherum** [comment]
I’ve seen bidi-aware text fields on Windows use this UI when the caret is between bidi runs. In some situations, when you type a character, if it’s an RTL character, it would appear in one place, but if it’s an LTR character, it would appear in another place, because of how the bidi runs surrounding the caret are placed. These bidi-aware fields will place the upper caret in one of the two insertion points and the lower caret in the other insertion point. If a text field doesn’t do this, and only has a single caret, the user can get into a situation where the caret is in one place, but when they press a key, the character appears in some visually unrelated place, which is a bad experience.

**Comment by AmeliaBR** [comment]
The split caret for RTL/LTR edges seems like a more complex issue (I think I've also seen it displayed as a partial bar at the two possible places), but definitely something that needs to be considered in this property.

Might want to get internationalization folks to weigh in, but one question is whether that should be left up to the user agent to do something smart when split caret points are required, regardless of whether the author considered it when setting the caret type.

**Comment by litherum** [comment]
Oh, the case I was thinking of may have actually been two half bars, instead of two carets as I described. In that case, please disregard my above comment.

**Comment by tabatkins** [comment]
In either case, tho, you can't use CSS to make the caret do something special only when it's in an ambiguous place.

**Comment by litherum** [comment]
Right; the behavior I described above should be implemented by browsers, not websites.

**Comment by Crissov** [comment]
> Do you have examples of interactive user interfaces that are using these marks, 

Unfortunately, I do not. I am pretty sure I have seen a _caret below_ in a boot loader CLI a while ago, but I cannot find or remember it exactly. 

Since, unlike an I-beam or vertical bar, an arrowhead caret would usually not need to blink, it could perhaps be a useful feature to improve accessibility.

> or complaints about the inability to use them?

- https://stackoverflow.com/questions/8408041/customizing-text-cursor-in-contenteditable-element
- https://stackoverflow.com/questions/7339333/styling-text-input-caret
- https://www.codeproject.com/articles/633935/customizing-the-caret-of-a-wpf-textbox
- https://docs.microsoft.com/windows/win32/menurc/using-carets (allows custom bitmaps)

While researching this a bit, I also came across the issue of slanting carets and selection edges to match the angle of slanted or italic font variants.

- https://ux.stackexchange.com/questions/37743/slanted-cursorbackground-for-italic-text

**Comment by hftf** [comment]
What about a keyword for the common I-beam shape? (cf. https://ux.stackexchange.com/q/83430)

**Comment by frivoal** [comment]
Controlling the caret in general is useful, including its shape, as evidenced by the links provided in https://github.com/w3c/csswg-drafts/issues/4402#issuecomment-540542376, and the specification is exploring that. However, given no evidence that the specific caret shape that this issue is suggesting is in common demand, I'm closing as wontfix. This could be revisited on the basis of evidence of strong demand for this specific variant.

**Comment by Crissov** [comment]
I mentioned accessibility, but what about print and other static media? _If_ one wanted to have a visible caret there, a chevron shape would be preferred, I assume.

Browsers are not that strong in such media, so Iʼd like to hear some input from vendors of CSS to PDF converters, die insurance.

**Comment by frivoal** [comment]
The caret is the UI element that shows where text insertion will happen if you start typing. This isn't a thing on print and other static media. You're free to include images and graphical effects where you want, to display something resembling a caret, chevron-like if that's what you want, but I don't see printing as a relevant use case for styling the actual text insertion caret in particular ways.
