### ISSUE TITLE
[css-ui-3] Add an `outline-offset` to shorthand

### ISSUE THREAD

**Issue by yoksel** [w3c/csswg-drafts#441]
Spec: https://www.w3.org/TR/css-ui-3/#propdef-outline

`outline` doesn't contain `outline-offset` and it can be added only with a separate line. It would be nice to have `outline-offset` here too, something like this: `outline: 5px/10px solid green`

**Comment by frivoal** [comment]
If we were introducing `outline-offset` now, I think I would agree with this proposal.

However, both `outline` and `outline-offset` have been out for a while now without having a shorthand / longhand relationship. Due to this, the change you're suggestion is likely to be incompatible with existing content.

If `outline-offset` becomes  longhand of `outline`, then setting `outline` would always reset `outline-offset`, even if no `outline-offset` specific value is provided. For example, the following code would not set the offset to 5px, because the shorthand would win the cascade and reset it to 0.
```
.highlight {
  outline-offset: 5px;
  outline: 3px solid red;
}
```


Since this is different from the current behavior, this is almost certain to break existing pages.

Unless you have some evidence or some reason to believe either than this compatibility problem is not occurring, or that even if it does occur it is not actually an issue, I am afraid it is too late to change this.

**Comment by yoksel** [comment]
Thank you for the explanation : ) So simple. I didn't think about it.
