### ISSUE TITLE
[css-transitions-2] Start transitions on discrete animation types

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#4441]
One of the goals of web-animations is to [allow developers to define custom transitions](https://github.com/w3c/csswg-drafts/issues/2068#issuecomment-349194890). In theory, this would let a developer define a transition for property types which are animation type Discrete, however css-transitions-1 defines discrete animations as not transitionable:

https://drafts.csswg.org/css-transitions-1/#starting
> When comparing the before-change style and after-change style for a given property, the property > values are transitionable if they have an animation type that is neither not animatable nor discrete.

This issue is to explore the possibility of allowing developers to create custom transitions for such properties. Since a lot of content today likely relies on the current behavior (`transition-property: all` is a very common pattern), any solution would likely have to preserve the existing visual behavior

### Option 1 - Use custom easing on discrete transitions

We could define transitions on discrete properties to create a transition using an easing type which immediately assumes the end value. This would preserve the existing visual behavior while allowing developers to listen for and modify the transition.

However, if we assume that a lot of existing comment has transition: all >0 duration, doing all of the work to create and run these transitions may be prohibitively expensive.

### Option 2 - Start and cancel discrete transitions

Start the transition animation, and immediately cancel it, such that a developer could access it and play it / modify it from a transitionstart event?

**Comment by birtles** [comment]
Yes, it would be nice to support this.

Apart from perf considerations, I'm a bit concerned about compatibility with option 1. If scripts are, for example, waiting for transitionend events and then asserting their `propertyName` is such-and-such, then firing transitions for other events could lead to breakage.

Option 2 would still result in extra `transitionrun` and `transitioncancel` events but I expect far less content is actually listening to them so they are less likely to produce breakage.

What about not allowing `all` or any shorthand to ever match discrete properties but still creating transitions for them (using the behavior from option 1) if they are explicitly listed? e.g. `transition-property: all, overflow-x`?

I suppose that runs the risk that if a longhand is promoted to a shorthand we might need to special case it so it keeps working (depending on how we define a discrete property). Then again, any content listening for `transitionrun` events on the (now) shorthand name, would already break since the UA would start firing events on the corresponding longhand names instead.

The other option that comes to mind is simply to add extra syntax for this, be it an extra property (`transition-property-set: discrete-too`) or extra syntax attached to property names.

**Comment by TheBigApple** [comment]
Flackr,
I think your on to something. I am running into a problem with using the 'background-image' in an SVG transition [i.e. css: background-image: url (xyz)]

Once I have 'encode' in-line <svg> and apply it to the css as a background-image: url ...  I loose the transition ability.
This is because 'background-image' is "Animation type - DISCRETE".

If you have a work-around for this that would be great!

Here is where I'm stuck, I have an Accordion which uses the [+/-] svg as a toggle button.

I've got it working the way I want, but want to remove the HTML's in-line <svg>,
and place it into the CSS, Or at least have it as a <style> in the Header.
[see working: 1.0 default [current ver - no mod].html]

Placing it in the Header <style> works BUT I loose the animation.
[not working: 2.0 default [in header].html]

Ultimately I really want it in the CSS file, to get it completely out of the HTML.
[not working: 3.0 default [in css main2].html]

It could be that the 'encoding' will not allow the 'evenodd' method to work,
or I have it placed wrong, The animation/transitioning does not work.

The Button's CSS starts at line: 1495 

Example DL here: http://msgr.info/In-Line_SVG_to_CSS.zip - 152 KB (155,648 bytes)

[Note this 'example' is stripped down from the Original Site to lessen the load, it's a bit dirty-code - the best I could do to make an example]

Thank you for your help!

**Comment by flackr** [comment]
> What about not allowing `all` or any shorthand to ever match discrete properties but still creating transitions for them (using the behavior from option 1) if they are explicitly listed? e.g. `transition-property: all, overflow-x`?

@birtles I like the idea of having `transition: all` match everything that is animatable and not discrete, and allowing developers to explicitly specify discrete properties if they want them to participate in transitions.

> The other option that comes to mind is simply to add extra syntax for this, be it an extra property (`transition-property-set: discrete-too`) or extra syntax attached to property names.

I think that having `discrete` as something that could be specified in addition to all would be nice.

Thinking about this I'm realizing developers could also use transition events as a way to detect style changes. Not sure if this is an explicit use case we should support but it's interesting to think about what people might do with that.

**Comment by flackr** [comment]
So to be specific, the proposal here is:
1. Properties explicitly listed in transition will transition even if discrete.
2. (Optionally) add a keyword similar to `all` which includes discrete properties too, or optionally is just for discrete properties.

**Comment by birtles** [comment]
Yes, I agree with that summary, assuming we want to go ahead with this (personally I'm not familiar with the use cases).

**Comment by andruud** [comment]
@flackr I think I would phrase (1) as follows:

1a. Properties with discrete animation types _do_ transition (generally), however:
1b. The `all` keyword does not represent such properties.

That way there is nothing particularly special about certain properties being "explicitly specified". They transition because they are specified, end of story. Then (2) also becomes non-special, since it's just a keyword which represents a certain set of properties.

**Comment by graouts** [comment]
> Yes, I agree with that summary, assuming we want to go ahead with this (personally I'm not familiar with the use cases).

I also follow the general thrust of this issue but am uncertain what the use cases are. Being able to transition properties with a discrete animation type would mean that they would no longer switch value immediately but rather _halfway_ through the transition duration. What is foreseen as benefits from transitioning a discrete property in that way?

Or would we envision a different mode where the value change is performed at the _end_ of the transition?

**Comment by mfreed7** [comment]
> I also follow the general thrust of this issue but am uncertain what the use cases are. Being able to transition properties with a discrete animation type would mean that they would no longer switch value immediately but rather _halfway_ through the transition duration. What is foreseen as benefits from transitioning a discrete property in that way?

One important use case is transitioning the `display` property (see https://github.com/w3c/csswg-drafts/issues/6429#issuecomment-1318933547). Since interpolation for `display` is done like `visibility`, it prefers the non-`none` state. So `transition: display 200ms` is *immediate* for the "showing" transition, and *delayed* until the end for the "hiding" transition.

**Comment by flackr** [comment]
> What is foreseen as benefits from transitioning a discrete property in that way?

There two main benefits to transitioning discrete properties:
- Developers can use the transitionstart event to implement custom behavior. E.g. developers could prototype cross-fading of images or another effect when the background changes.
- This is very useful for holding particular discrete values for the purposes of an animation - e.g. primarily see the exit transition example at https://github.com/w3c/csswg-drafts/issues/6429#issuecomment-1318933547

I get that you're calling out the 50% flip and I agree in general most people will want the transition of these at the end if declared as a transition-property because switching immediately doesn't require any transition, however perhaps there are cases where they want the composite order of the transition animation?

> Or would we envision a different mode where the value change is performed at the _end_ of the transition?

So, developers could use `transition-timing-function` setting `step-start` or `step-end` to choose whether to hold the beginning or ending keyframe. We do define for particular properties where certain values may not be useful interpolations - e.g. display: none is useful to avoid in the same way that visibility interpolation avoids hidden: https://drafts.csswg.org/web-animations-1/#animating-visibility. I could see defaulting the timing function to step-end for discrete properties but it would be weird if you couldn't choose a different timing function.

**Comment by fantasai** [comment]
This should go into Transitions Level 2, btw.

**Comment by flackr** [comment]
Yes, there are many wpt tests which explicitly define transitions on discrete properties and test that they don't transition which will be changed by this, but in practice there is no reason for developers to explicitly have discrete properties in their transition list. This is similar to new properties which previously had no effect but could have been used by developers now having an effect when they are defined.

**Comment by fantasai** [comment]
This landed in https://github.com/w3c/csswg-drafts/commit/69f4ac71c0ae0ae70e363c775c1f84e87d3935ff via https://github.com/w3c/csswg-drafts/pull/8520 ; I don't know why GitHub isn't recording it.
