### ISSUE TITLE
[css-text] Writing System prose is currently unimplementable on ICU

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#4445]
The spec [says](https://drafts.csswg.org/css-text-3/#script-tagging):

> While most languages have a preferred writing system, many can also be transcribed into a different writing system. As a common example, most languages have at least one Latin transcription, and can thus be written in the Latin writing system. In these cases the document typically adopts the typographic conventions of the Latin writing system: for example Japanese “romaji” and Chinese Pinyin use Latin letters and word spaces, and follow Latin line-breaking and justification practices accordingly. As another example, historical ideographic Korean (ko-Hani) does not use word spaces, and should therefore be typeset as for Chinese.

The Web Platform Test [css/css-text/writing-system/writing-system-line-break-001.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/writing-system/writing-system-line-break-001.html) tests this, by setting `lang=ja-Latn` on an element and checking line breaking behavior. ICU does not abide by the above quoted prose, and erroneously uses Japanese-style line breaking.

cc @frivoal @kojiishi @fantasai @drott @jfkthame

**Comment by AmeliaBR** [comment]
To clarify, you're asking that the normative statements later in the section be changed from "must" statements to "should" statements?

>  UAs should assume the most common writing system of the specified content language when choosing typographic behaviors such as line-breaking or justification strategies, but must not assume that writing system if the author has explicitly indicated a different one. If the UA has no language-specific knowledge of a particular language and writing system combination, it must use the typographic conventions of the specified writing system (assuming the conventions of a different language if necessary), not the conventions of that language in a different writing system, which would be inappropriate to the writing system used in this case.

("Should" being the correct term if we agree on the correct behavior but acknowledge that it can't be consistently implemented because of limitations in widely used software.)

Also relevant: have you approached the people responsible for ICU text shaping about whether they could support script-specific breaking?

**Comment by frivoal** [comment]
> ICU does not abide by the above quoted prose, and erroneously uses Japanese-style line breaking.

Right, it feels like an ICU bug, although the difference between a missing feature and a bug is a subjective one, and I'd rather call this a missing feature.

ICU is smart enough to take the content language into account, and will do line breaking differently on Japanese vs English, as css-text expects it to. So far so good. However, it is insufficiently subtle about how it handles this language sensitivity.

This test is checking that the rules of https://drafts.csswg.org/css-text-3/#script-tagging are respected, whose intro you quoted in your opening comment. This specific text exercises the first sentence in the normative statements later in that section that @AmeliaBR quoted:

> UAs should assume the most common writing system of the specified content language when choosing typographic behaviors such as line-breaking or justification strategies, **but must not assume that writing system if the author has explicitly indicated a different one**. 

In this test, the language is set to "ja-Latn". ICU uses Japanese style line breaking, even though the writing system is explicitly set the writing-system part of the language tag to something else. Per the sentence above, that is what ought to drive what type of line breaking is used.

I am not an expert on ICU, but my sense is that while ICU currently doesn't handle this case as css-text-3 expects it to, I don't think think handling this correctly would go against the goals of ICU.

ICU already goes further than what UAX14 strictly requires. A large part of UAX14 is "shoulds" rather than "musts", and are explicitly called out as being tailorable. A number of differences between line-break loose/normal/strict are implemented in ICU based on what CSS says, while UAX14 merely allows for that sort of variation, without calling for these specific variations. In particular, the specific differences in line breaking when the language is different aren't part of UAX14 (though allowed by it). Paying attention to the writing-system subtag part of the language tag as well as the primary language subtag falls within that same kind of tailorings, and so while I agree it should be discussed and fixed in ICU, I don't think it needs any fix in Unicode-the-spec itself.

----

My recommendation would therefore be to work upstream with ICU to improve their behavior to handle this sort of case.

In the meanwhile, what do we do about the spec and the test(s)? Possibly nothing.

I would expect the failing test to help remind us that this is something we should fix eventually, independently of where the fix belongs, which it seems to have done in this case. I fully expect browsers to set their own priorities independently, and accept that certain tests will keep on failing for a while if you chose not to fix this right now (or if fixing it in ICU means the fix won't land in the browser for a while).

If we're trying to push this spec out of CR but haven't got around fixing this yet, changing the MUST to a SHOULD (to be restored to a MUST in the following level), or marking it at risk, to avoid blocking on it could make sense to me, but so far we're not even in CR yet (although I think we're pretty close).

Maybe we could already mark it as a should right now, in recognition this is a thing that makes sense to do but isn't done yet, but I worry that making test failures go under the radar will decrease the chances of ever getting to the bottom of it.

**Comment by jfkthame** [comment]
Contrary to the title of this issue, I think it's actually possible for a UA that wants to rely on ICU line-breaking to implement this part of the spec pretty well, even without ICU being enhanced to respect the script subtag. I believe something along these lines should give the desired result:

* check if the locale code from the `lang` attribute includes a script subtag
   - if not, it's fine to use the locale code as-is to control the line-breaker
   - example: `ja` or `ja-JP` has no script subtag, just use it
   - example: `ja-Latn` does include a script subtag, so we go to the next step

* call `minimizeSubtags()` on the locale code
   - if this removes the script subtag, then it was the "expected" script and it's fine to use the code as-is
   - example: `en-Latn` or `zh-Hans` will minimize to `en` or `zh` respectively, so are safe to use
   - example: `ja-Latn` will be unchanged (or return `ja-Latn-JP`? I'm not sure, but either is OK), so we go to the next step as the script code is still present

* there's a potential mismatch: the `lang` attribute is specifying a script that is not the "normal" writing system for the given language, and ICU line-breaking would behave incorrectly
   - generate a new locale code by passing "und-<script>" to `addLikelySubtags` and use the resulting code instead of the `lang` from the page to control the line-breaker
   - example: replace `ja-Latn` with `addLikelySubtags("und-Latn")` which will be `en-Latn-US`, which will result in Latin-appropriate line breaking
