### ISSUE TITLE
[css-variables] normalization of custom property names

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#4452]
This was originally discussed by email, and we are moving the discussion to GH. See https://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-352&list=www-style
Raised by: Addison Phillips
Opened on: 2014-05-29

> http://www.w3.org/TR/2014/WD-css-variables-1-20140506/#defining-variables
> 
> Section 2 says in part:
> 
> > Unlike other CSS properties, custom property names are case-sensitive.
> > 
> > EXAMPLE. While both --foo and --FOO are valid, they are distinct properties - using var(--foo) will refer to the first one, while using var(--FOO) will refer to the second. 
> 
> Case sensitivity is not the only variation that can apply to text. While citing the case sensitivity is useful, should mention be made of other variations, such as Unicode Normalization? I believe that the actual restriction is that the text must be identical.

**Comment by tabatkins** [comment]
That is indeed the actual restriction; we do no normalization whatsoever, and just match on the codepoint sequence.

That's also exactly what the term means, when you follow the link. ^_^ The example uses ASCII casing for the example, but the term "case-sensitive" [is clear that it's about exact codepoint comparisons](https://html.spec.whatwg.org/multipage/infrastructure.html#case-sensitive).

**Comment by aphillips** [comment]
I think the question here is whether your text should cite deeper encoding variation. While you're correct that HTML's definition of "case-sensitive" means codepoint-by-codepoint identity (which I18N prefers, btw), the text here is a little misleading (it is *calling out* the case sensitivity without making mention of the code point identity issue). The reference to HTML's definition of `case-sensitive` is via the DOM spec. It's easy to overlook. So I think that I personally would prefer that this "health warning" mention the encoding issue. Perhaps:

> Unlike other CSS properties, custom property names are case-sensitive. This means that the underlying code point sequence must be identical.

You might also include something like:

> For more info, see [[Charmod-Norm](https://www.w3.org/TR/charmod-norm/#sec_case_sensitive)]

**Comment by aphillips** [comment]
@r12a the exact HTML definition of `case-sensitive` (which the CSS text is linked to--well, via DOM) is explicit that it is code point identity, but the *phrase* `case-sensitive` doesn't mean that to the casual reader and the example doesn't call out any other meaning. 

That's why I didn't just suggest changing the text to say CP-by-CP: so they can keep the reference to the formal definition intact.

**Comment by r12a** [comment]
Useful links:
https://www.w3.org/TR/css-variables-1/#custom-property links to 
https://dom.spec.whatwg.org/#case-sensitive which links to 
https://html.spec.whatwg.org/multipage/infrastructure.html#case-sensitive which says:

> Comparing two strings in a case-sensitive manner means comparing them exactly, code point for code point.

**Comment by tabatkins** [comment]
I was very confused what y'all were talking about, since the current Variables spec *doesn't* link to DOM, but straight to HTML, and DOM doesn't have a #case-sensitive ID in it either. Then I realized y'all were looking at the CR from four years ago. ^_^  The ED links straight to the correct, clear definition; I need to republish this spec.

I can be a little clearer there in the example, but the point of the example is to make it clear that CSS's ASCII case-insensitivity does not apply like it does for all other property names; the fact that "case-sensitive" means something even stronger outside of ASCII wasn't relevant to the example.

**Comment by tabatkins** [comment]
I switched my use of "case-sensitive" to instead use the "identical to" terminology from Infra, and explicitly contrast it against "ASCII case-insensitive".
