### ISSUE TITLE
[css-pseudo-4] Should ::selection select hard wrap (or hard return) line break <br>?

### ISSUE THREAD

**Issue by TalbotG** [w3c/csswg-drafts#4460]
Test:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-026.html

Reference:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-026-ref.html

Chromium project's feedback:
https://bugs.chromium.org/p/chromium/issues/detail?id=1018465#c3

Just my opinion: ::selection should not select hard wrap line break. If a `<br>` is nothing more than a carriage return (CR: 0x0D) and a line feed (LF: 0x0A) (both non-printable characters), then I do not see why a `<br>` should be painted.

Either way, I think the current specification should be explicit on this issue since Chrome and Firefox disagree.

**Comment by TalbotG** [comment]
Under Linux, Epiphany version 3.32.1.2 (WebKitGTK+ 2.24.4) and Epiphany Technological Preview version 3.34.0-32-g514d1bfb6 (WebKitGTK 2.26.1) do not select `<br>`.

**Comment by fantasai** [comment]
Hi @TalbotG, I think the test is correct, because the selection background should be inherited into `<br>` anyway. But also, it's OK if `<br>` is rendered as taking up space: the question of whether it should or not is outside the scope of css-pseudo-4, so not particularly important to consider for this test. (It should definitely not affect whether the text fits within its container, or at what size its container shrink-wraps, but if it's rendered during selection, it's not much of a problem I think.)

**Comment by TalbotG** [comment]
@fantasai ,
So both (Chromium and Firefox) renderings are acceptable (or possible and valid) renderings?

> The UA should use the OS-default highlight colors for ::selection when **neither color nor background-color** has been specified by the author.

coming from
https://www.w3.org/TR/css-pseudo-4/#highlight-cascade

In the test, color has been specified by the author. Doesn't that make Chromium's rendering incorrect?

**Comment by fantasai** [comment]
@TalbotG Yes, you are right.

**Comment by fantasai** [comment]
I mean, your test is correct, and your assertion that Chromium's rendering is incorrect is also correct.
