### ISSUE TITLE
[css-color-4] [css-backgrounds-4] text system color conflicts with background-clip

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4465]
https://drafts.csswg.org/css-backgrounds-3/#propdef-background allows you to specify a `background-clip` value using one of the `<box>` bits in the syntax..

backgrounds-4 defines `background-clip: text`, which multiple browsers implement and ship from a long time ago. It is my intuition that if we allow to set background-clip in the background shorthand, we should also be able to set `background-clip: text`.

Firefox does this already: `background: linear-gradient(red, blue) text` parses as `background-image: linear-gradient(..); background-clip: text; background-*: initial`.

The system colors introduced in css-color-4 (#4091) include a `Text` value, which conflicts with `background-clip: text` in the background shorthand.

That means that the previous example will start parsing as `background-color: text` rather than `background-clip: text`, which is a significant behavior change.

So we have multiple options I guess:

 * Make this behavior change (as I think Gecko is the only engine that supports `background-clip: text` on the background shorthand as of now). This would be a bit unfortunate, but _probably_ ok?
 * Rename the `text` system color to something else, to prevent the naming conflict.
 * Something else I may be missing?

cc @melanierichards @dbaron

**Comment by BillGoldstein** [comment]
Bikeshed: rename color:Text to CanvasText (which would be consistent with Canvas)...though I kinda hate the name.

**Comment by tabatkins** [comment]
CanvasText sounds fine to me, given the parallel with all other *Text names.

**Comment by dbaron** [comment]
I'd note that it seems likely that one reason implementations differ here is that the level of css-backgrounds ([level 4](https://drafts.csswg.org/css-backgrounds-4/)) that defines `background-clip: text` doesn't define the `background` shorthand, so different implementers have made different decisions as to what to infer that level 4 will say about the `background` shorthand once it includes it.

I'd note that another option is to say that not all `background-clip` values can be specified in the `background` shorthand.  I think this wouldn't be the first case where the shorthand is not serializable from a set of longhands (e.g., lists of mismatched length).

I'd also note that "make this behavior change" isn't super-clear, since you need to define the behavior of:
* `background: text text`
* `background: blue text`
* `background: padding-box text`
* `background: blue padding-box text`
* `background: padding-box padding-box text`

I think renaming the `text` system color to something more specific is probably a good idea anyway, though, since there are already a bunch of other `*Text` system colors, so having one that's just `Text` is a little odd.
