### ISSUE TITLE
[css-values] Redundancy of atan2() 

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4485]
In https://github.com/w3c/csswg-drafts/issues/2331#issuecomment-468034127 Iʼve aleady asked to incorporate the functionality offered by `atan2()` into `atan()`. 

I understand that many authors will be familiar with “atan2” or “arctan2” from programming languages, JS in particular. According to [Wikipedia](https://en.wikipedia.org/wiki/Atan2), some languages support an optional parameter for their arctangent function: Common Lisp, Mathematica. Other implementations, spreadsheet formulas in particular, expect the arguments in the reverse order.

Can we add an optional second argument to `atan()` while keeping `atan2()` with two mandatory arguments?

**Comment by ewilligers** [comment]
If we copied `rgb` and `rgba`, we would have both allowing one or two arguments, with serialization rules that `atan` and `atan2` serialize as `atan` if they have one argument and `atan2` if they have two arguments.

I'd prefer that we be consistent with JavaScript. Intent is clearer when authors always use `atan` with one argument and `atan2` with two arguments.

**Comment by tabatkins** [comment]
I made the intentional choice to include both atan() and atan2() to coincide with JS; I've since made sure that the functions agree with JS in as many additional ways as possible, most particularly their corner-case behavior for NaN/Infinity/zero in various spots.

Sticking close to JS for these functions is, I think, better. And as long as we're keeping atan2() around anyway (as your issue suggests we do), I don't think diverging from JS to allow atan() to copy the functionality makes a lot of sense; it doesn't add any new functionality, and there's no guarantee it would accord in all the corner cases with the 1-or-2-args versions of atan in other programming languages.
