### ISSUE TITLE
[css-ruby-1] ruby overhang control

### ISSUE THREAD

**Issue by stantonma** [w3c/csswg-drafts#4492]
We (Kindle) have received feedback from publishers that overhanging ruby can confuse younger readers since the annotation/pronunciation is no longer directly above the base character. We'd like to give publishers the option to disable ruby overhang for certain content types like children's books.

This could also let us define the JLREQ default overhang of one ruby text character length as the default.

Proposed addition would be:

Name | ruby-overhang-limit
--- | ---
Value | \<length\>
Initial | 1em

Sets the maximum allowable overhang of ruby over allowable base characters. Length is relative to the ruby text font size.

**Comment by frivoal** [comment]
The current spec leaves the limit undefined and up to the UA. Which means implementations could possibly set it to 0 to disallow all overhang, and this seem to be what Firefox does.

Interestingly, disallowing overhand altogether is the recommendation of Professor Kobayashi as a good enough solution for general use (see list item number 4 in https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-mono-ruby-0 for mono-ruby, list item number 4 in https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-group-ruby-0 for group ruby, and list item number 4 in https://w3c.github.io/jlreq/docs/simple-ruby/#placement-of-jukugo-ruby-0 for jukugo ruby).

If disallowing overhand always is not acceptable, and we do introduce a property, I would therefore suggest that the initial value be `auto` (i.e. up to the UA, possibly 0) or `0` rather than `1em`.

**Comment by upsuper** [comment]
Overhanging control is something tricky actually. It's not just a single limit, but a bunch of rules.

For example, WebKit allows overhanging up to 1/2 (or something close) character of the ruby text regardless of surrounding characters, which is fine. Another possible rule is to overhang up to one whole ruby text, but only over certain kinds of characters (kanas & punctuations IIRC). But you should never hang a whole ruby annotation on a kanji before or after. These rules cannot really be covered by a single distance.

**Comment by frivoal** [comment]
`ruby-overhang: auto | none` is probably a safe minimal subset. Whether we can eventually express different kinds of non-`none` behavior, with or without numeric parameters, is a separate question, but unless we're comfortable banning overhand always (which I don't think we are), having the ability to opt out of overhand seems useful (as evidenced by the reqests Amazon has been getting).

**Comment by upsuper** [comment]
That sounds like a reasonable proposal.

**Comment by stantonma** [comment]
Sounds reasonable to me as well, and would cover our use cases

**Comment by macnmm** [comment]
I am surprised at the [example of jukugo ruby](https://w3c.github.io/jlreq/docs/simple-ruby/#types-of-ruby-0) where overhang of Kanji is allowed so as to preserve base text spacing. I would think this is an optional behavior but the default is to prevent overhang on Kanji, and only allow on kana and aki. I think having these rules as part of the minimum requirements is desirable.

**Comment by stantonma** [comment]
If we don't allow overhang within a Jukugo, then there would be no difference between if the author used a series of mono/group ruby right?

I'd prefer to leave that decision up to the UA by default (Kindle's implementation does allow it).

Though that does bring up if the property should apply to overhang within a Jukugo as well. I don't have any concern with saying it affects both cases.

**Comment by hftf** [comment]
See also #3498.

**Comment by stantonma** [comment]
Summarizing the comments above, I think we have this:

Name | ruby-overhang
-- | --
Values | auto \| none
Initial | auto

Controls the overhang of the ruby annotation box on adjacent text to its corresponding ruby base box.

'auto'
- The UA determines whether to overhang the ruby annotation box

'none'
- The ruby annotation box must not overhang any adjacent boxes to its corresponding ruby base box.

This way the 'none' value covers overhang for mono/group as well as overhang within a jukugo ruby.

@macnmm is the JLTF ok to move forward with this? Kindle is ready to implement.

**Comment by macnmm** [comment]
@w3c/jlreq-editors  ^^ see above question to me

**Comment by murata2makoto** [comment]
I recently read the editors' manual for magnified textbooks for low-vision.  First, the font size for ruby appears to be 70%.  Although 50% is used for junior high school textbooks, I doubt that the use of such small ruby is due to the cost and weight of textbooks.  Second, ruby-overhand is not used.  But space between base characters is expanded.

If you can read Japanese, [the editors' manual](https://www.nise.go.jp/kenshuka/josa/kankobutsu/pub_c/c-43.html) is very interesting.  Even if you cannot, please have a look at examples in [this page.](https://www.nise.go.jp/kenshuka/josa/kankobutsu/pub_c/c-43/normal/c-43_11_06_03.pdf)    The first figure shows a page of a usual textbook while the second shows the same page in a magnified textbook.

**Comment by frivoal** [comment]
@stantonma I think we should still allow overhang over ruby bases of a same ruby segment with `ruby-overhang: none` in the case where `ruby-merge` is a value other than `separate`. Other than that, I agree. 

@murata2makoto good to see actual examples confirming that no-overhand is desired. As for spacing between the base characters, this can be done with `rb { ruby-align: space-around; }`.

**Comment by r12a** [comment]
This is a test for new changes to the HR notification system. Please ignore. I will delete this tomorrow.

**Comment by stantonma** [comment]
@frivoal sounds reasonable, seems there's a bit of overlap here with `ruby-merge` actually. If we can say that `ruby-merge: separate` is equivalent to no overhang within a `<ruby>` we could switch the definition to only overhang on items adjacent to the `<ruby>` block.

If we want to keep overhang control within the `<ruby>` block, then I'd want keep control during `ruby-merge:auto` as well as `separate`.

**Comment by stantonma** [comment]
Since it seems like `ruby-merge` does handle all cases of overhang between ruby bases, I think this property should only affect overhang outside of the ruby container box (as opposed to ruby base box). So with that the value for 'none' would be something like:

'none'

- The ruby annotation box must remain entirely in the bounds of it's ruby container box

**Comment by fantasai** [comment]
Alright, I've committed changes to define `ruby-overhang: auto | none`. See https://drafts.csswg.org/css-ruby-1/#ruby-overhang

The exact rules for overhanging are left entirely to the UA.

Note that in the current model, the annotations don't leak out of the ruby container: the adjacent content is allowed to leak into the ruby container. (This ensures that no part of the ruby extends past the paragraph edges, and also ensures that any background on the ruby container extends behind all of its content.) If there's concerns about that, or any other details, please open a new issue.
