### ISSUE TITLE
Should vertical-align:middle behave differently when the dominant baseline is not alphabetic?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#4495]
In both [the definition in CSS 2.1](https://www.w3.org/TR/CSS21/visudet.html#propdef-vertical-align) and [the definition in css-inline](https://drafts.csswg.org/css-inline-3/#valdef-alignment-baseline-middle) `vertical-align: middle` is defined as:
> Align the vertical midpoint of the box with the baseline of the parent box plus half the x-height of the parent.

Nothing in the [Inline-level alignment section](https://drafts.csswg.org/css-writing-modes-3/#inline-alignment) of css-writing-modes appears to modify this definition.

Yet, as far as I can tell, this definition really makes sense primarily when the dominant baseline is alphabetic.  If you're starting from an alphabetic baseline, adding half the x-height gives a position that could reasonably described as the "middle".  If you're starting from a central baseline... I don't think it does.

In https://github.com/web-platform-tests/wpt/commit/07210df69af0daa9f07cd2109093b97ae917397e @hshiozawa added tests to web-platform-tests that test this behavior for vertical text with a central baseline.  Based on https://wpt.fyi/results/css/css-writing-modes it seems that these tests pass in Chrome (but no other engines).  [Mozilla bug 1220353](https://bugzilla.mozilla.org/show_bug.cgi?id=1220353) covers making them pass in Gecko.

We could try to implement this to pass these tests... but I'm hesitant to do so given that I don't see how the behavior makes sense.

**Comment by frivoal** [comment]
The `dominant-baseline` property that lets you change baseline at will is not in css2.1, and is introduced in css-inline-3, which is not even a CR yet. writing-modes-3 does have to define how that interaction works, it's css-inline-3 that needs to worry about that.

The remaining case is when the dominant baseline switches to something else than alphabetical via something else than that property. That can happen if writing-mode is vertical-* and text-orientation is upright or mixed,  in which case the dominant baseline is central. That ability also didn't exist in css2.1's time.

So, the text in CSS2.1 talks about "the baseline", but back then could either mean "the dominant baseline" or "the alphabetic baseline", as they used to be the same thing. I'd say css2.1 is more ambiguous than wrong. If we go with the interpretation that it meant alphabetical, then the behavior looks reasonable. [Last time we discussed this](https://lists.w3.org/Archives/Public/www-style/2015Jul/0008.html) seems to support that as well. Css-writing-mode-3 too is more ambiguous than wrong, but looking carefully, I think it actually does hint in this direction. Section 4.4 says there are two cases where the dominant baseline is used:
* The first one is about Aligning glyphs from different fonts
* The second one talks about the some values of the vertical-align, which don't include `middle`.

Logically, since it's not one of these two cases, "the baseline" discussed in the definition of `middle` isn't the dominant one, which supports the idea that it's supposed to mean the alphabetical one.

I'd say that the right thing to do at this point is to resolve the ambiguity in favor of the alphabetic baseline in css-inline-3 and to leave css-writing-modes alone.
