### ISSUE TITLE
[css-scroll-snap-1] Snap area trapping behavior of non scrollable elements

### ISSUE THREAD

**Issue by majido** [w3c/csswg-drafts#4496]
Here is  the current spec text related to an ancestor element's trapping behavior for snap areas.
  
>  A box captures snap positions if it is a scroll container or has a value other than none for scroll-snap-type. If a box’s nearest snap-position capturing ancestor on its containing block chain is a scroll container with a non-none value for scroll-snap-type, that is the box’s scroll snap container. Otherwise, the box has no scroll snap container, and its snap positions do not trigger snapping.

This allows any regular element which is not a scroll container to trap snap areas.

I tested this on latest Chrome, Safari, Firefox and as far as I can tell no engine does this. Here is a [simple test page](https://jsbin.com/vakafihehi/1/edit?html,css,output) that shows this.  Also I don't think we have a wpt test case for it.

Beside, one can simply achieve the same trapping behavior just by having an element with overflow `auto` or `hidden` that does not actually overflow. This works correctly across all engines.

Given that no engine implements this, and the behavior can be achieved without much problem, I suggest we drop this requirement. 

I am not really sure what is the motivation behind allowing none scroll container to trap snap areas so maybe I am missing something.

**Comment by majido** [comment]
@tabatkins @fantasai  wdyt about this?

**Comment by fantasai** [comment]
I'm not entirely convinced that we should be requiring to clip overflow in order to trap snap points.

Also wondering if `contain: layout` should be invoking this behavior? It's not quite layout, but to the extent that snaps within such an element could interfere with user interactions outside it... //cc @tabatkins

**Comment by frivoal** [comment]
I agree with the intent of this resolution, but would like to discuss the precise way to spec it a little further, due to a few principles I think ought to be true:
* the css-contain spec should not need to be (normatively) revised every time another spec adds a new feature. (Adding notes to highlight the effects of 
* the css-contain spec should state the requirements in a way that is generic enough to be always true. It's goal is to create a mode where correctness can be guaranteed, even in some otherwise necessary steps are skipped for the sake of optimizations. If we find classes of effects that ought to be affected by containment, that's worth revising css-contain for, but the revision should capture the whole class.
* other specs which introduce new features ought to clarify how these features interact with containment when that isn't obvious.

So, what I think we should do here is:
* in the contain spec, add an additional effect to layout containment about scrolling:
    > * The content, layout, or scroll position of an element with scroll containment or any of its descendants must not affect the scroll position of any box that is not a descendant of containing box for layout containment.

    On top of that, we could add a note in css-contain pointing readers to css-scroll-snap for details, for convenience.
    > Note: See "capturing snap positions" in [[css-scroll-snap]] for a specific mechanism affected by this requirement.
* in the scroll-snap spec, be specific about the implication for snapping:
    > A box captures snap positions if it is a scroll container<ins>,</ins> or has a value other than none for scroll-snap-type<ins>, or if it has layout containment</ins>. 

This more generic phrasing in the css-contain spec would not only apply to scroll snap, but also would cover potential future features with similar effects. Let's say we later introduce scroll-locking, where you can somehow declare that the scroll position of one box must continuously be adjusted to track the scroll position of another one, so that when you scroll one, the other follows. The generic phrasing I'm proposing above for css-contain would catch that, while phrasing that is specific to scroll snapping would not.

This would be similar to the second effect of layout containment, about fragmentainers with layout containment trapping the rest fragmented flow. It is stated in generic terms, and leaves it up to spec which would run into that possibility, like css-regions would, to clarify what it would mean for them.

**Comment by fantasai** [comment]
I believe the current state of this issue is Rejected No Change based on the CSSWG resolutions. Reasoning was, you might want to prevent snap areas within a container from affecting its scroll position without having side-effects on overflow.

@majido Do you think this would be difficult to implement? Do you think there's something else we should consider?

**Comment by majido** [comment]
FWIW when filed this issue the motivation was mostly from implementation perspective. 

From Blink perspective the most logical thing for us to do was to update snap element mappings as part of the scroll tree. Because simply adding and removing a scroll container has well-defined hooks which we use to redistribute the snap areas to new scroll containers. Basically treating snapping as a scrolling feature allows us to reuse lots of pre-existing machinery that exists for scrolling.

If any element can capture snap areas then you need to track their add/removal (and possibly maintain a separate tree for them 🤔 ). This is not impossible but I am not sure if it the usecase justifies the implementation cost in Blink. I am no longer have the most up to date information on this feature so take my opinion with a grain of salt. /cc @flackr who may provide better guidance.

**Comment by fantasai** [comment]
@majido Based on comments from WebKit, we ended up just marking this behavior at-risk. That means, if it's not implemented but everything else is, we'll drop the requirement; if it turns out to get implemented, it'll stay in the spec.
