### ISSUE TITLE
[css-pseudo] "Finding the First Letter" has ID #application-in-css

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4508]
The "Finding the First Letter" subsection has the id [#application-in-css](https://drafts.csswg.org/css-pseudo-4/#application-in-css). This is nonsense.

https://github.com/w3c/csswg-drafts/blob/4ce8f75cd58e5d796969e900f25e81997206511a/css-pseudo-4/Overview.bs#L268-L269

We already have [#first-letter-pseudo](https://drafts.csswg.org/css-pseudo-4/#first-letter-pseudo) and [#first-letter-styling](https://drafts.csswg.org/css-pseudo-4/#first-letter-styling), so I propose #first-letter-finding.

For consistency, [#first-text-line](https://drafts.csswg.org/css-pseudo-4/#first-text-line) could be renamed to #first-line-finding.

**Comment by fantasai** [comment]
Heh, that's from when this spec was incorporated into Selectors (and therefore wasn't CSS-specific). Since the URL has changed generally to css-pseudo-3, I'm OK changing the ID as well.

Don't think we should change first-text-line, as I suspect there are a number of cross-references to it from other specs.
