### ISSUE TITLE
[css-backgrounds-3] "background-repeat: no-repeat" as default

### ISSUE THREAD

**Issue by steffanhalv** [w3c/csswg-drafts#4526]
https://www.w3.org/TR/css-backgrounds-3/#propdef-background-repeat

Repeated background-images is rarely used & forces everyone to define 'no-repeat':

```css
background-repeat: no-repeat;
```

By setting background-repeat to 'no-repeat' as default I would guess a lot of css sheets would require less lines of code.

**Comment by Loirooriol** [comment]
I sympathize, but changing it would break the sites which want to repeat the background but don't specify `repeat` since it's the initial value.

**Comment by fantasai** [comment]
As @Loirooriol says, we can't change the value now. :( You'll need a time machine for that... the default was chosen because when CSS was first proposed, tiling backgrounds were much more common. (Images large enough to cover the whole page would have been prohibitively expensive to load.) But I've now added it to the list of mistakes: https://wiki.csswg.org/ideas/mistakes
