### ISSUE TITLE
[css-sizing] intrinsic-size lost the thread 🙁

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4531]
At the last f2f, when we discussed the proposal to allow an async-layout element to specify a "default" size while it's not actually laying out its contents (effectively `contain:size`), over the course of the conversation we ended up redefining it into a more general ability to manually set the intrinsic size of an element.

As we've experimented with implementation, tho, we've come to realize that this generalization accidentally significantly broke the usability of the feature for its original use-case.

* With the original [(attribute-based)](https://github.com/WICG/display-locking/) proposal, previously authors could set the "default size" property on all async-layout elements, and it would only trigger when needed (when the element wasn't displaying its children); it would stop affecting anything once full layout started working. With this change, authors instead have to carefully target their rules so that 'intrinsic-size' stops applying when full layout starts, or else lingering effects of the property can produce confusing layout artifacts.
* With our exploration into an alternative CSS-based async layout, you can't even target things carefully anymore; you instead have to track "is locked/unlocked" separately with script and rely on *that* to apply/unapply 'intrinsic-size', breaking all the elegant simplicity.

Regarding the additional use-cases we ended up addressing with the revised "applies all the time" property:
* Per [dbaron's comment](https://github.com/w3c/csswg-drafts/issues/4229#issuecomment-555286700), the auto/legacy usecase that partially justified the expansion of the concept needs some more thought anyway, and should maybe be a separate feature.
* The "generate appropriate scrollbars for virtual scrollers" use-case (#4415) was just a nice freebie feature; it's not an important feature to preserve right now, and can be easily hacked with a fake element at the moment.

So after discussion with @vmpstr and @chrishtr, we'd like to change tactics: we want to withdraw the general intrinsic-size property for now, and return to the earlier concept of something that solely provides a non-zero size for contents *solely when size containment is applying*.

Name is up for grabs; it just needs to be something other than 'intrinsic-size', since it's explicitly *not* setting that general concept.

---

And then separately we'll still want to figure out a good solution to the auto/legacy use-case, but need to review dbaron's feedback.

**Comment by chrishtr** [comment]
> * previously authors could set the "default size" property on all async-layout elements, and it would only trigger when needed

This was possible with CSS by using an attribute selector such as:

```
[rendersubtree*="invisible"] {
  intrinsic-size: 300px 400px
}
```

As Tab mentioned, in the past few weeks we have prototyped a [CSS implementation of rendersubtree](https://github.com/WICG/display-locking/issues/97), in response to partner feedback and some feedback from the previous F2F that this would be more ergonomic for developers.

But if `rendersubtree` is in CSS, you can't observe it via CSS or else there would be a circularity of CSS depending on CSS.

Due to the UA activation/async-rendering feature of `rendersubtree`, the value may change outside of developer control, and therefore we need a way to have placeholder sizing constraints apply only when the content is invisible; this is where the restriction to `contain:size` came from, since `contain:size` detaches subtree layout constraints from affecting outer layout.

Here are two ideas:

1. Augment containment syntax, via something like: `contain: size 300px 400px`
2. Choose a new name, such as: `contain-size-sizing: 300px 400px` (I didn't give this much thought, maybe there is a good name?)

**Comment by tabatkins** [comment]
I don't like adding this to the contain property directly; it feels like it's building too much orthogonal functionality into the property.

But I don't have a good name for the independent property either. ^_^

**Comment by vmpstr** [comment]
> 1\. Augment containment syntax, via something like: `contain: size 300px 400px`

I don't really like this, since it doesn't quite solve the case described. IOW, presumably that would also apply size containment and put in this size. What we would really like is to specify which size to apply _if_ containment is specified, without specifying the containment itself.

> 2\. Choose a new name, such as: `contain-size-sizing: 300px 400px` (I didn't give this much thought, maybe there is a good name?)

Yeah I think we need something like this, but I'm not really good at naming this. `size-containment-placeholder-size` or something like that is my best idea, but it feels a bit verbose.

**Comment by cbiesinger** [comment]
This change also makes me more comfortable with implementing aspect-ratio, because otherwise that was fairly close to intrinsic-size (in that aspect ratio could just be inferred from intrinsic-size, if set)

**Comment by fred-wang** [comment]
https://github.com/WICG/intrinsicsize-attribute/issues/16

**Comment by emilio** [comment]
> [WICG/intrinsicsize-attribute#16](https://github.com/WICG/intrinsicsize-attribute/issues/16)

Hm? How is that link related to this?

**Comment by fantasai** [comment]
We already have a similar "when things are loaded, use the real size, in the meantime use this explicit value" concept for aspect-ratio. It would make sense to be consistent in how we express that concept.

I really don't want to have separate properties for "explicit size that always wins" and "explicit size that's only used under certain conditions". It gets confusing from an author-learning perspective to have too many properties that are doing nearly identical things (in this case, identical things taking effect under slightly different conditions). And it's also not great from a cascading perspective to do that either.

**Comment by vmpstr** [comment]
> I really don't want to have separate properties for "explicit size that always wins" and "explicit size that's only used under certain conditions".

I kind of think of size containment as already putting in a 0x0 for its intrinsic size (which of course only applies if contain: size is present). This is due to the fact that it has to lay out as if it had no children, and also replaced elements get intrinsic width and height as 0. This proposed property would just allow the developer to specify something other than 0x0 under the same conditions.

In terms of the cascade or what wins when, I would imagine the same rules as size containment apply. In other words, if size containment is specified then instead of laying out as if empty, the element lays out as if it has a single child box of specified size or something along those lines.

**Comment by chrishtr** [comment]
> We already have a similar "when things are loaded, use the real size, in the meantime use this explicit value" concept for aspect-ratio. It would make sense to be consistent in how we express that concept.

I agree about things being consistent in this regard. Could you link to the spec text you're referring to so I can study it?

**Comment by chrishtr** [comment]
Hi @fantasai, ping on above question..

**Comment by fantasai** [comment]
@chrishtr Spec is at https://drafts.csswg.org/css-sizing-4/#aspect-ratio but it hasn't incorporated the "use actual value, fall back to this other value" behavior yet. So concern is less "let's be consistent with this existing thing" and more "let's make sure we design these two things together so they end up consistent".

**Comment by fantasai** [comment]
Created an issue to collect use cases for explicit intrinsic sizes at https://github.com/w3c/csswg-drafts/issues/4585

**Comment by chrishtr** [comment]
Per decisions made at last month's CSSWG, and given there were no use cases raised for intrinsic sizing, we should go with a specification of a new CSS property that applies only when `contain:size` is also specified. The new CSS property allows choosing a value other than `0x0` as the placeholder sizing of the subtree.

I suggest `content-placeholder-size` as the name of the property.

This is almost the same as the original name proposed at TPAC (see issue #4229) of `content-size`, but more clearly indicates that it has to do with sizing when the layout of the subtree is not known/skipped.

**Comment by chrishtr** [comment]
Also, since the setting much simpler now we should remove all the extra keywords, and only support fixed lengths (no percentages/keywords), since there is nothing to be percentage relative to. Also, the initial value should be 0, to correspond to the meaning of `contain:size` without specifying any intrinsic sizing.

(Ref to current spec before edits: https://drafts.csswg.org/css-sizing-4/#intrinsic-size-override)

**Comment by cbiesinger** [comment]
@vmpstr and I just discussed this update in person:

- There should an initial value "none" different from 0
- It would be nice if the spec had a non-normative note explaining this, something like:

'none' is different from 0 because some layout modes can have a nonzero intrinsic size even without contents; for example columns can have a column gap specified, or grids can have nonzero grid tracks. If an explicit contain-intrinsic-size: 0 is specified in such a case, the box will be laid out just like a zero width were specified explicitly (e.g. width: 0)

**Comment by cbiesinger** [comment]
@frivoal see also my comment above

**Comment by frivoal** [comment]
@cbiesinger I agree we need the none value as you described. That said, depending on how we write its normative description, we might not need the note.

**Comment by astearns** [comment]
Agenda+ to determine the order of the values

**Comment by cbiesinger** [comment]
We may also want to discuss what the initial value should be (auto/none)

**Comment by tabatkins** [comment]
Posting this for the aid of the telcon discussion.

I did a quick rundown of all the properties in CSS, finding those that take a pair of size values and whether they're physical or logical:

## physical ##
* aspect-ratio
* background-*
* box-shadow
* device-aspect-ratio
* fill-*
* stroke-*
* mask-*
* object-position
* overflow
* overscroll-behavior
* perspective-origin
* transform-*

## logical ##
* gap
* grid-*
* place-*
* scroll-snap-*

So the pattern is fairly clear: things @fantasai and I have worked on in the past few years are logical, everything else (both legacy, and newer things worked on by people other than us) are physical.

I'm sad about the overall inconsistency, but I don't think this is easily resolveable. We have to bite this bullet one way or the other, and I guess I'm fine with deferring to the larger numbers and history behind "default to physical". We'll just have a couple of specs that are inconsistent.

**Comment by tabatkins** [comment]
@cbiesinger @chrishtr All right, 'contain-intrinsic-size' is committed at <https://drafts.csswg.org/css-sizing-4/#intrinsic-size-override>; would y'all mind reviewing?

In particular, check that the definition of "explicit intrinsic inner size" matches what y'all think it should be: "pretend you've done layout on your contents and got back these sizes as the result". I think that hits exactly on the behavior we want.
