### ISSUE TITLE
[css-values-4] Specify simplification of min() and max() more explicitly

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#4550]
https://drafts.csswg.org/css-values-4/#calc-simplification doesn't say anything specific about `min()` and `max()` simplification, but it seems that two types of simplification could happen:

1. Sort the arguments, as sum/product node children are sorted:
`min(1vw, 1px, 2em,)` -> `min(2em, 1px, 1vw)`

2. Do partial simplification if possible:
`min(2em, 1px, 3px)` -> `min(2em, 1px)`

@tabatkins WDYT?

**Comment by AmeliaBR** [comment]
I think both of these are good additions, consistent with the rest of the spec.

**Comment by Loirooriol** [comment]
How do you sort when you have sums with different units? Like `min(1em + 1vw, 1lh + 1px)`, where `em < lh < px < vw`, so which argument goes first?

And about partial simplification, it may be problematic with percentages. It may seem `min(2em, 1%, 3%)` can be simplified to `min(2em, 1%)`, but percentages can resolve to negative values, so actually 3% may be smaller than 1%!

**Comment by tabatkins** [comment]
For (1), I don't specify anything about reordering the arguments because I assumed we want to keep the arguments in the order specified. As @Loirooriol points out, you can't generally sort them in any reasonable way; sorting only the arguments that are single values seems low-value and not worth the effort of speccing/implementing/testing, imo.

That said, any sorting we do would be identical to the sorting that is already specified for Sum nodes (as a legacy of the older, simpler calc() where you could always simplify things to a sum of simple values); the simple unit values are in alphabetical order by unit, and the more complex things go at the end in source order. Is it worthwhile applying that sorting to all the commutative operators?

For (2), I could partially apply the min/max function, sure. It would be identical to the combining that goes on within a Sum or Product node. I can go either way on this.

**Comment by tabatkins** [comment]
You didn't comment further on this, @smfr. Any further thoughts, or do you mind if I just reject these suggestions?

---------

Related: it's unclear exactly what "simplify as far as possible" can mean for the case of a min()/max() with *only* percentage arguments, such as `min(10%, 20%)`.

We've already established in a previous resolution that, when %s are relative to some other value, you need to wait until they resolve to do any simplification, because in some cases the %s might be relative to a *negative* value and thus `20%` might end up smaller than `10%`.

But in some cases we know that the % is relative to a *non-negative* value, so that isn't true, and we *could*, theoretically, immediately resolve `min(10%, 20%)` to `calc(10%)`.

However, this (1) seems silly, as it only applies in the (fairly worthless) case of a min()/max() with *only* % values in it, and (2) seems dangerous, as it brings us closer to "percolate arbitrary numeric constraints thru this expression" which I dont' want to do.

So I'm planning to make this case clearer in the spec, and mandate explicitly that %s must make the function unresolvable until they resolve against their base value.

In particular, this means that an expression like `margin-left: min(10%, 20%)` will serialize as `min(10%, 20%)` in both specified and computed values, and will only simplify away to a single value at used-value time when you can turn those into px values.

/cc @xiaochengh @emilio

**Comment by smfr** [comment]
I don't have strong feelings about this. I'm fine with no changes (other than spec clarification if necessary).

**Comment by emilio** [comment]
I think not doing this would be somewhat inconsistent with how all implementations work for cases like `color: rgba(0, 0, 0, min(10%, 50%))` or such.

`background-size` is a bit weirder and seems to be all over the place:

```
document.body.style.backgroundSize = "min(10%, 100%)"
document.body.style.backgroundSize //  firefox: calc(10%), chrome: min(10%, 100%), webkit: calc(min(10%, 100%))
getComputedStyle(document.body).backgroundSize // firefox / chrome: 10%, webkit: calc(min(10%, 100%))
```

**Comment by Loirooriol** [comment]
> I think not doing this would be somewhat inconsistent with how all implementations work for cases like `color: rgba(0, 0, 0, min(10%, 50%))` or such.

Why? Per https://drafts.csswg.org/css-values/#calc-type-checking, the type of the calculation is «[ "percent" → 1 ]». The percentages don't need to be further resolved in order to calculate the `min(10%, 100%)`. So it can be simplified away at specified-value time.

It's different for `background-size`. There the percentages are resolved into lengths with respect to the background positioning area, which depends on layout. So it seems to me that `min(10%, 100%)` shouldn't be simplified until used-value time.

**Comment by tabatkins** [comment]
Yeah, I'm talking about things that need to resolve % at used-value time. I just want to stick with "computed" vs "used" as the simplification-boundaries here, and not creating more categories like "technically used-time, but for this particular property we know that 10% will be less than 50% whatever they resolve to, so we *could* resolve at computed-value time".

**Comment by tabatkins** [comment]
Oh sorry, yeah, and specified-value time as well. The three normal value-distinction categories, and nothing fancier than that.

(Like, if we're talking *fancy*, something like `min(-10px, 1em)` is resolveable at specified-value time, because you know that the `em` value will resolve to a *non-negative* `px` value. But I don't want to specify that sort of constraint propagation, and I doubt that y'all want to implement it!)

In other words, the simplification rules should just be: if all of the arguments have been resolved to their maximum for the given context, and you can resolve the operation using just the values of the arguments, simplification should replace the function with its result. Otherwise it stays until a later value stage transforms arguments to their final form.

So in colors, %s don't resolve against anything, so a `min()` consisting of just them can and must be resolved immediately after parsing (the first simplification opportunity dictated by the spec).
