### ISSUE TITLE
[selectors4] :target-within?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#457]
A very common pattern is having a list of items (e.g. a gallery of products, or people, or a list of invoices etc) with every item being compact and showing little info until it's clicked, at which point all other items disappear and the item expands and displays all the data it contains in full size.

This can almost be done with CSS, by using `:target` to expand the item when the location hash matches its id. However, there is no way to make other items disappear in that case, so horrible hacks are usually employed, such as absolutely positioning the item to cover the list of other items.

Similar issues (and hacks to solve them) exist with UI patterns such as tabs, where if no tab is selected, one wants to show the first tab.

Since `:focus-within` is feasible, I don't see why `:target-within` wouldn't be, and it would immensely simplify such tasks. Thoughts?

**Comment by FremyCompany** [comment]
Seems like a good idea to me

**Comment by nuxodin** [comment]
+1
I asked for the same
https://lists.w3.org/Archives/Public/www-style/2015Feb/0022.html

**Comment by o-t-w** [comment]
A more general way of selecting parent elements, rather than confining the ability :focus-within and :target-within, would be amazing. They're a nice start though. I've already found using :focus-within very useful.

**Comment by tomhodgins** [comment]
> A more general way of selecting parent elements, rather than confining the ability :focus-within and :target-within, would be amazing. They're a nice start though. I've already found using :focus-within very useful.

The way I see it, `:has()` _is that more general way_, [it's already specced](https://drafts.csswg.org/selectors/#relational), but currently enjoys [zero browser support](https://caniuse.com/#feat=css-has). I too think having a way to select parents would be super helpful, but it seems like instead of supporting `:has()` we're speccing and supporting newer, smaller fragments of what `:has()` is already supposed to be able to do.

Isn't `:focus-within` functionally the same as `:has(:focus)`? And wouldn't `:target-within` be equivalent to `:has(:target)`?

If the general pattern of `:<thing>-within` correlates to `:has(:<thing>)`, then let me brainstorm a few more selector ideas (I'm just pulling the list of existing pseudo-classes from CSS Selectors Level 3 & 4…)

- `:link-within`
- `:visited-within`
- `:hover-within`
- `:active-within`
- `:enabled-within`
- `:checked-within`
- `:empty-within`
- `:blank-within`
- `:drop-within`
- `:current-within`
- `:playing-within`
- `:paused-within`
- `:disabled-within`
- `:valid-within`
- `:required-within`
- etc…

Adding each of these would add quite a bit more of `:has()` original power to CSS, but we'd be missing out on ways to do things like:

- `:has(p)`
- `:has(:nth-of-type(5))`
- etc…

I've experimented quite a bit with selecting parents and ancestors in CSS and I have found it useful, and I've even tried to DIY support like `:has()` using `querySelector()` from the context of elements matching a selector. If you want to check out the ways I've experimented with styling parents and ancestors have a peek at:

- [`$parent` selector in (unofficial) element queries spec](https://tomhodgins.github.io/element-queries-spec/element-queries.html#selectordef-meta-selectors-parent)
- [Selecting the Ancestor of an Element](http://responsive.style/techniques/ancestor-of-element.html)
- [Selecting the Parent os an Element](http://responsive.style/techniques/parent-of-element.html)

Alternatively to speccing a ton of newer, weaker, more limited selectors that do small aspects of what `:has()` should be already able to descrube, I'd love to see browsers actually support `:has()` — does anybody know why that hasn't happened yet?

**Comment by LeaVerou** [comment]
`:has()` is not in the fast selector profile and thus, even when supported by browsers, will not be available in regular CSS, just JS.
Browsers so far have not found a way to implement this efficiently enough for normal CSS, which is why we don't have such a feature yet, despite it being requested for almost 20 years.

We should really have an FAQ for this…

I do agree that duplicating syntax is not great though. If it were up to me, I'd just special case `:has(:focus)` and `:has(:target)` to be in the fast selector profile. But many (most?) others disagree with partially supporting syntax in certain contexts and think there should be a different syntax for that.

**Comment by js-choi** [comment]
There’s an alternative to @LeaVerou’s idea of turning `:has(:focus)` and `:has(:target)` into fast special cases of `:has()` that’s worth also considering.

The alternative idea is to revise the current Selectors Level 4 draft so that `:has` becomes an always-fast selector that accepts only a limited enumeration of arguments such as `:focus` and `:target`. The current draft’s slow/general version of `:has()` would be (hopefully safely) renamed. After all, it’s not yet implemented anywhere.

In this proposal, a longer name for the slow/general selector—like `:has-matches()` or whatever—may be appropriate, if one agrees that the slow/general selector would be used much less often (i.e., in JavaScript only) than the fast/enumerated selector.

**Comment by upsuper** [comment]
> In this way, the shorter word `:has` would be used on the more-common thing: a fast, enumerated relational pseudo-class specifically for `:has(:focus)`, `:has(:target)`, and whatever else could be in the fast selector profile. The current slow, general relational pseudo-class would be renamed to `:has-matches(…)`.

FWIW, `:focus-within` in Gecko is currently implemented as a separate flag on all matching elements which is added or removed accordingly when focus changes.

What I want to say is that, the implementation of `:focus-within`, at least in Gecko, is not in a general enough way that can be applied to whatever pseudo-class you can find. The same approach may be applied to other single target pseudo-classes (e.g. `:target`), but it's definitely expensive for pseudo-classes which can have multiple matches, like `:link`, `:enabled`, etc.

Also we are always lack of room for more flags to track on elements, which means we may need to pay tradeoffs when adding any new flag, and thus even for single target pseudo-classes, we may want to avoid adding support for those which don't really have good use cases.

I'm not sure how other browsers implement `:focus-within`, but I would be quite interested if they can implement it with an approach which is both general and efficient.
