### ISSUE TITLE
[css-pseudo] ::first-letter and pseudo-elements

### ISSUE THREAD

**Issue by ryuran** [w3c/csswg-drafts#4578]
Hello

At the beginning I declared a bug on Blink, but it's now "Won’t fix" according to the blur in the specification around it.

https://bugs.chromium.org/p/chromium/issues/detail?id=647239#c4

https://drafts.csswg.org/css-pseudo-4/#generated-content 
> As with the content of regular elements, the generated content of `::before` and `::after` pseudo-elements may be included in any `::first-line` and `::first-letter` pseudo-elements applied to its originating element.

https://drafts.csswg.org/css-pseudo-4/#first-letter-pseudo
> If the characters that would form the `::first-letter` are not in the same element, such as `’T` in `<p>’<em>T...`, the user agent may create a `::first-letter` pseudo-element from one of the elements, both elements, or simply not create a pseudo-element.

"may" but how to know if it should or not ?

**Comment by fantasai** [comment]
Good catch. I think that first "may" is an incorrect use of RFC2119 MAY. I've rephrased the sentence to be clearer. The second "may" still applies, however, and all three variations are allowed...

With the correction, it should be clear that in

```
p::before { content: "T"; }
<p>his</p>
```

the 'T' should match ::first-letter and not the 'h', however if we replaced the "T" with a "(" then it is up to the UA whether ::first-letter matches the (, the h, or both together.

Let me know if this resolves your concern or there's something else you wanted fixed in the spec.
