### ISSUE TITLE
[css-highlight-api] Priority by number or some other method

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4591]
Since multiple highlights can exist, we need to know which is on top of which (and then https://drafts.csswg.org/css-pseudo-4/#highlight-painting tells us how painting works). The current spec proposes doing that by assigning a number (and when the number is the same, by comparing the time of insertion into `CSS.highlights`).

This is simple to understand and to specify, but it's not clear to me that this is actually great to use. Should we drop priority by numbers system, and replace it with some other ordering mechanism? Experience with BASIC line number or z-index does not give much confidence that ordering by number is a good idea.

Is placing in an ordered data-structure instead of a map better? Should authors be able to express a desired to be placed above/below other named highlights, and let the UA figure it out? Something else?

**Comment by hober** [comment]
Ideally, a priority system would:

0. Be unnecessary by default (we have to spec how to order things when relative priority is not explicit)
1. Be simple to author
2. Would allow uncoordinated use of the Highlight API by multiple in-page libraries to not clobber each other
3. Would not repeat the mistakes of z-index
4. Would be straightforward to implement.

**Comment by sanketj** [comment]
Below are some options that I recall discussing in the past:

(1)
Priority as an attribute on `Highlight`. This is what we have in the spec today. Usage would be:

```
<style>
  p::highlight(foo) {
    background-color:yellow;
  }
  p::highlight(bar) {
    background-color:orange;
  }
</style>
<body>Some text
<script>
  let textNode = document.body.firstChild;

  let r1 = new Range();
  r1.setStart(textNode, 0);
  r1.setEnd(textNode, 6);
  let h1 = new Highlight("foo", r1);

  let r2 = new Range();
  r2.setStart(textNode, 3);
  r2.setEnd(textNode, 9);
  let h2 = new Highlight("bar", r2);

  CSS.highlights.add(h1);
  CSS.highlights.add(h2);

  // If we paint now, h2 will paint above h1 since there is no explicit priority and h2 was registered later.
  
  h1.priority = 1;
  
  // Now h2 will paint above h1.
  
</script>
```

If two highlights have the same priority, the order in which they are registered in the `HighlightRegistry` is used as a tiebreaker.

(2)
Priority as a CSS property. Though this feels more _CSS-y_ and there is prior art for this with `z-index`, this may present a problem for highlight overlays. The css-pseudo-4 spec mentions that there is [a single highlight overlay for the entire document per highlighting type](https://www.w3.org/TR/css-pseudo-4/#highlight-bounds). With priority as a CSS property, authors could write this:
```
#p1::highlight(foo) { priority: 1 }
#p1::highlight(bar) { priority: 2 }
#p2::highlight(foo) { priority: 2 }
#p2::highlight(bar) { priority: 1 }
```
If foo and bar overlap, foo will paint below bar in #p1, but above in #p2. This feels like a violation of the "single overlay for the entire document" concept.

(3)
Do not introduce any CSS property or attribute for priority, and just use the order of highlights in the `HighlightRegistry`. We would instead add methods like the ones below to `HighlightRegistry`, to allow reordering of highlights:
```
append([new highlight])
prepend([new highlight])
insertBefore([new highlight], [reference highlight])
```

This would also mean that `HighlightRegistry` can no longer be `setlike` - it will need a custom implementation.


Amongst the three, I still prefer option 1 - what we have today - since it avoids the problems of option 2, and we can continue to take advantage of `setlike` for the `HighlightRegistry`. Would be great to hear the thoughts of others.
