### ISSUE TITLE
[css-color-4] Better name for gray()?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#4621]
5 years ago, I opened [this mailing list issue](https://lists.w3.org/Archives/Public/www-style/2014Jul/0432.html):

> The gray() functional notation [1] is a great idea for specifying desaturated colors with varying degrees of transparency in a concise and readable way. However, I’m not sure about the naming. Right now, the named color `gray` corresponds to gray(50%). gray(0%) is black and gray(100%) is white. 

> After using this function myself for a while (through emulating it in Sass), I’m starting to think its naming is quite unintuitive. The usual assumption with functions that take a 0-100% parameter is that 100% gives the full “effect” of the function name, in this case, gray. Ask any random person what color they think gray(100%) represents, I doubt they’d guess white. [...]
> For example, think of CSS filter functions: sepia(100%) colorizes the image as sepia, values < 100% are a lighter version of the effect. Same with invert(), grayscale() etc. 

> If we want to keep the link to hsl(), white() might be a better name. Although, I’m not sure if white(0%) == black is exactly intuitive, but it seems more intuitive than gray(0%).
> Or, we might reverse the parameter and have black(100%) == black and black(0%) == white, which is on par with how many real life things work, such as (grayscale) printing.
> Or maybe someone else has a better idea?

There was consensus that the name needs to change, but not to what. So [I started a survey](https://lea.verou.me/2014/07/an-easy-notation-for-grayscale-colors/), which also confirmed that the name `gray()` as a bad idea. 

[The last post in the thread](https://lists.w3.org/Archives/Public/www-style/2014Jul/0543.html) is by @tabatkins saying that "the results are impressive, let's let it run for another week and take what people decide". 

Well, it ran for 5 years, and these are the [results](https://docs.google.com/forms/d/e/1FAIpQLScOvDU75W-UNPqDmVScprsO0YT6R_NJr1ZUjllrdNSf3pQPAA/viewanalytics):

![image](https://user-images.githubusercontent.com/175836/71252596-1bcb5680-232e-11ea-9748-bed0fad6d41b.png)

It looks like `rgb(<number>)` is overwhelmingly leading, but that is likely just a result of authors today being more familiar with the `rgb()` function. There is a famous quote (somewhat dubiously) attributed to Henry Ford: “If I had asked people what they wanted, they would have said faster horses.” The fact that RGB is not user friendly is well established in the literature, so I don't think it should be the only solution for easy specification of grayscale colors (though it may be nice to have it as an additional shortcut).
Apart from that, there doesn't seem to be any clear consensus on the name, besides that `gray()` is not the best option.
Renaming the function also eliminates the `gray`/`grey` confusion elaborated in #3298.

Since we're already working in Color 5, it would be nice to finally have a resolution on this, if it's going to be renamed.

To recap, here are some ideas for names that have been mentioned:

- `black()` with `black(0%)` = `white` and `black(`100%`) = `black`
- `white()` with `white(0%)` = `black` and `white(`100%`) = `white`
- `grayscale()`
- `lightness()`
- `darkness()`
- `shade()`

I personally feel much more strongly that `gray()` is a poor name choice than I feel that any of the above should be the one of choice. I think they're all better than `gray()`. Slight preference for `white()` as the absence of light producing black makes more sense than the absence of darkness producing white. We should also make sure that 50% is the gray that is perceptually between white and black, and not just `hsl(0,0%,50%)`.
Whichever name you propose, please write it out with 0%, 50%, 100% and make sure it still makes sense and reads naturally for the color it produces.

**Comment by faceless2** [comment]
You could always add rgb(n) and rgb(n/a), which seems harmless enough, but please don't drop gray() without giving a syntax that doesn't presume RGB.

We've had a colorspace called "gray" in PDF/PostScript since forever, with 0=black. It's defined as the black in CMYK - so `gray(1) == cmyk(0 0 0 1)`. I presume that's the origin of this name in CSS, but I completely agree that without this context the name is ambiguous. So while I can certainly live with gray(), if it's going to change then I'd go for black(), as it's mapped to black ink in print.

**Comment by Crissov** [comment]
What about any of these:

- `Lab(0%)` black through `Lab(100%)` white 
- `lch(0%)` black through `lch(100%)` white 
- `light(0%)` black through `light(100%)` white 
- `lightness(0%)` black through `lightness(100%)` white 
- `gray(0%)` white through `gray(200%)` black 
 - `gray(-100%)` white through `gray(100%)` black

**Comment by tabatkins** [comment]
I dislike most of these names, as they're misleading/weird: 

* `white()`/`black()` are odd, as only color geeks consider white/black to be variations of each other. (and `black(100%)` being white is right out)
* `shade()`/`tint()` have specific meanings and we should reserve them for actually shading/tinting colors as color-manipulation functions
* `lightness()` is a maybe, but it's long. Not a killer objection, but still.

----

I'm not sure what you mean by:

> Apart from that, there doesn't seem to be any clear consensus on the name, besides that `gray()` is not the best option.

since the data shows `gray()` as having the second highest individual % among all the options (only behind 1-arg `rgb()`).

If we did change the name, I'm okay with a 1-arg variant of an existing colorspace function, but not `rgb()` specifically, since `gray()` is *not* defined in terms of `rgb()`; it would be confusing and bad if `rgb(50%)` was not equal to `rgb(50% 50% 50%)`. 1-arg `lab()` and/or `lch()` might work tho.

Another possibility, inspired by the existing (oddly named, but we're stuck with them) colorspace functions, is just `l()`.

A final possibility is we just drop `gray()` entirely, since `gray(X)` is exactly equal to `lab(X 0 0)`, which is an insignificant difference in typing. Downside of this is that you lose the potentially-useful immediately-obvious semantics of "this is a gray color". But we've lived without that for 20+ years, so we can probably continue to. ^_^

**Comment by svgeesus** [comment]
> If we did change the name, I'm okay with a 1-arg variant of an existing colorspace function, but not rgb() specifically, since gray() is not defined in terms of rgb(); it would be confusing and bad if rgb(50%) was not equal to rgb(50% 50% 50%). 1-arg lab() and/or lch() might work tho.

Exactly.

Also, the fact that 1-arg rgb() was so popular means people responding did not read, or understand, what gray() does (although what it does now and what it did at several times in the past (`rgb(x,x,x)`, `hsl(0,0,x)`,  etc) is not the same.

I'm tempted to leave it for now, and see what happens when `lab()` and `lch()` get implemented.

**Comment by Crissov** [comment]
Why not have both, single-argument `rgb()` and `lab()`/`lch()` for two different gray functions?

**Comment by tabatkins** [comment]
More impl and testing work for essentially zero benefit.

**Comment by smfr** [comment]
I don't like single-argument `rgb()` because `gray()` should be tied to the `lab()` and `lch()` colors by virtue of using the same colorspace, and the same lightness scaling (which is different from hsl etc). And at some point `gray()` may be able to represent super-bright HDR whites by having a lightness value > 100%.

`lightness()` is OK but sounds like an adjective. How about `monochrome()`?

**Comment by bradkemper** [comment]
Of all the suggestions so far, black([percentage]) seems most reasonable and intuitive to me. I don’t consider myself a color geek, but I am a web designer and developer, a former print designer, and someone who paints occasionally.  

In printing with black ink, a 10% screen halftone is a very light gray, and a 90% screen halftone is a very dark gray. I also don’t think it is unusual to think of gray paints as being a percentage of black (with the rest of the mixture being white). See Exercise 2 on this page, for example:

http://kaplanpicturemaker.com/color/color_exercises

**Comment by Crissov** [comment]
I need to amend my earlier comment. Single-argument `rgb()` might be valuable, but would work differently from single-argument `lab()`: while the former would be a shorthand for setting all three components to the same value, the latter would only set the first component and use a default value for the other two. It now seems most logical to me to use `L()` or `lightness()` for that.

**Comment by svgeesus** [comment]
Closed in accordance with CSS WG resolution 8 Jan 2020

**Comment by Crissov** [comment]
`K()`, `key()` for them print folks. 

Also could have chosen for `gray()` to depend on  the working color space. #4647 #300 😝

**Comment by tabatkins** [comment]
k/key was mentioned in the minutes; it's similarly wrong/misleading, as `k(50%)` is *not* a 50% K value...

**Comment by Crissov** [comment]
As far as I see, only `black()` was mentioned, which is not quite the same as `key()` in a rarely but in this case important way.

**Comment by tabatkins** [comment]
Ah, it was a side comment, looks like it didn't get minuted; Chris was referring to [Brad Kemper's comment about black()](https://github.com/w3c/csswg-drafts/issues/4621#issuecomment-570827891), suggesting that it was in fact an intuition about K, which would be slightly off for a Lab-based function just like an rgb intuition would be.
