### ISSUE TITLE
[css-logical-1] Copy error in border-color section

### ISSUE THREAD

**Issue by impressivewebs** [w3c/csswg-drafts#4629]
In the [border-color](https://drafts.csswg.org/css-logical/#border-color) section of the CSS Logical Properties spec, it says:

> These two shorthand properties set the border-block-start-color & border-block-end-color and border-inline-start-color & border-inline-end-color, respectively. The first value represents the start edge **style**, and the second value represents the end edge **style**. If only one value is given, it applies to both the start and end edges.

It should say:

> These two shorthand properties set the border-block-start-color & border-block-end-color and border-inline-start-color & border-inline-end-color, respectively. The first value represents the start edge **color**, and the second value represents the end edge **color**. If only one value is given, it applies to both the start and end edges.

Bold added to indicate the mistakes. I believe this is due to a copy/paste error when adding the information from the [border-style section](https://drafts.csswg.org/css-logical/#border-style).

**Comment by Loirooriol** [comment]
>  The first value represents the start edge style, and the second value represents the end edge style.

This pattern is used almost everywhere:
https://drafts.csswg.org/css-logical/#propdef-margin-block
https://drafts.csswg.org/css-logical/#propdef-inset-block
https://drafts.csswg.org/css-logical/#propdef-padding-block
https://drafts.csswg.org/css-logical/#propdef-border-block-style
https://drafts.csswg.org/css-logical/#propdef-border-block-color

I think the idea is that "style" doesn't refer to a border style but to a CSS style in general. So in your quote "start edge style" means is "style for the start edge border color".

But it's a bit confusing because https://drafts.csswg.org/css-logical/#border-width does say "start edge width".

**Comment by impressivewebs** [comment]
Ok, interesting. But it seems it would make sense to specify the property in each of those cases, just to avoid ambiguity since the word "style" in this context has more than one meaning.

**Comment by fantasai** [comment]
Made the substitution requested, since here it's quite simple and does avoid that confusion with border-style.

**Comment by Loirooriol** [comment]
@fantasai Then, should e.g. https://drafts.csswg.org/css-logical/#propdef-margin-block say

> The first value represents the start edge ***margin***, and the second value represents the end edge ***margin***.

? And analogous for other links in my previous comment?
