### ISSUE TITLE
[css-color-4] Should lab() colors which are outside the sRGB gamut be rendered on capable displays?

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#4646]
Lab and LCH colors can be outside the sRGB gamut. https://www.w3.org/TR/css-color-4/#specifying-lab-lch says nothing about how to render those colors, other than not clamping lightness.

There is text about how to convert lab/lch to sRGB, so implementors may take this to mean that lab/lch should be converted to sRGB for rendering, but UAs that wish to support extended color rendering may choose to map lab/lch into some other working colorspace. I think the spec should make this clearer. Maybe https://github.com/w3c/csswg-drafts/issues/300 needs to be resolved before that happens.

**Comment by smfr** [comment]
@svgeesus

**Comment by svgeesus** [comment]
There are two cases:

1. The color is used as-is. In that case, it will be converted to the display (or other output device) gamut in the usual way (for ICC-based implementations, the source profile will be Lab and the destination profile will be the 'full gamut' or 'native' display or printer ICC profile
2. The color is manipulated first. The color manipulation functions in CSS Color 5 are defined to use `lch()` by default. Gradient interpolation and compositing are currently defined to use sRGB; working colorspace allows that to be changed (including `display-p3, or `lab` or `lch`). The resulting color is then converted to the display (or other output device) gamut .

I agree that this needs to be stated explicitly, otherwise implementers could easily guess wrong.

For case 1. it is independent of #300 

This probably needs a new section in the spec.

**Comment by jrus** [comment]
IMO document color space should be explicit, and out-of-gamut CIELAB colors should be brought into document gamut (e.g. by clamping chroma along a ray of constant hue/lightness) before display.

If someone wants to take advantage of a P3 display (or whatever) then that should be explicitly opted into by the document.

Then authors will be able to reliably target sRGB vs. P3 (etc.) displays, and an author who sets the document to sRGB mode will see the same output as an sRGB display, even if the display they are looking at has a wider gamut.

Otherwise it becomes very difficult for an author to simulate on their own wide-gamut display what typical viewers on an sRGB display will see.

**Comment by svgeesus** [comment]
> There is text about how to convert lab/lch to sRGB, so implementors may take this to mean that lab/lch should be converted to sRGB for rendering, but UAs that wish to support extended color rendering may choose to map lab/lch into some other working colorspace. I think the spec should make this clearer. 

I agree that this could have been misunderstood. I have:

- made sRGB be an example for RGB to Lab, and clarified that the sample JavaScript code has conversions from several RGB spaces
- clarified that the a reason to do Lab to RGB conversion is on-screen display
- clarified that the display profile should be used for this
- changed the example to use Lab to display-p3
- added brief CMYK to Lab and Lab to CMYK overview, indicating the ICC profile should be used for the conversion

The part about [gamut mapping](https://github.com/w3c/csswg-drafts/issues/5191) is still to be added

**Comment by svgeesus** [comment]
Gamut mapping section added https://github.com/w3c/csswg-drafts/commit/d51a437cc8be69b864a11f0cf9b8e6f5f6532973
