### ISSUE TITLE
[css-text-decor] Conflicting descriptions of `text-underline-position: left` or `right` in horizontal typographic mode

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#4656]
I'm unclear exactly how to handle the [`text-underline-position` property](https://drafts.csswg.org/css-text-decor-4/#text-underline-position-property) in _horizontal_ typographic mode, when _only_ one of the values `left` or `right` is specified.

Given for example `text-underline-position: left` and _horizontal_ English text, where should the underline appear -- close to the alphabetic baseline, or at the bottom of the em box?

There seem to be two relevant statements in the spec, but as I read it, they conflict with each other.

First, we read (just below Example 4):

> If `left` or `right` is specified alone, `auto` is also implied.

This seems to mean that the underline would typically appear close below the alphabetic baseline of the horizontal text, just as if the property were `auto`. This also seems consistent with the descriptions of the `left` and `right` values, which refer _only_ to an effect in vertical typographic modes.

However, at the end of the section there is a illustration showing the effect of `left` and `right` (in vertical mode), and the caption of this illustration says:

> In vertical typographic modes, the `text-underline-position` values `left` and `right` allow placing the underline on either side of the text. **(In horizontal typographic modes, both values are treated as `under`.)**

_(my emphasis)_

This seems to be saying that either `left` or `right`, alone, would have the same effect as `under` in horizontal mode, and so the underline would appear at the bottom of the em box.

Which should it be?

AFAICT, current implementations behave according to the first description above. If this is correct, I suggest the caption of that illustration should be changed to read:

> (In horizontal typographic modes, both values are treated as `auto`.)

**Comment by fantasai** [comment]
Looks like I forgot to update the caption in 
  https://github.com/w3c/csswg-drafts/commit/36fa9440fd0dfecc7794239445368349dcbe841d
See minutes of this discussion at https://lists.w3.org/Archives/Public/www-style/2017Feb/0049.html

Basically the logic was this: CJK languages need a `text-underline-position` value set in the default UA style sheet. Also, for compat reasons, the initial value has to be `auto` in horizontal writing modes. Given all that, to be more consistent with the initial value, an omitted one is `auto` rather than `under`.

Lmk if this makes sense to you or if you think we should do something different here. :)

**Comment by jfkthame** [comment]
Sounds OK to me, thanks.

**Comment by xfq** [comment]
This issue seems to be fixed in https://github.com/w3c/csswg-drafts/commit/2231d71942344e695ef39fa7b1941fc1ca1c4033

Should we close it?
