### ISSUE TITLE
[css-grid-2] No definition of grid: subgrid as used in example by the spec

### ISSUE THREAD

**Issue by AlaskanEmily** [w3c/csswg-drafts#4661]
The usage of grid: subgrid is show in [example 2 of the css-grid-2 spec](https://www.w3.org/TR/css-grid-2/#example-b3af119d), but there is no actual explanation of this shorthand since css-grid-1 doesn't include subgrid.

**Comment by tabatkins** [comment]
I'm sorry, I'm not sure I understand. Can you restate your issue?

**Comment by MatsPalmgren** [comment]
I'm guessing the example is from a time when the the `grid/grid-template` shorthands accepted a value for just one axis that were then copied to the other axis. That syntax was later removed. So I think the example needs to updated to use `grid: subgrid / subgrid` to be valid.

**Comment by MatsPalmgren** [comment]
(We fixed Gecko [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1549223) fwiw.)

**Comment by AlaskanEmily** [comment]
I do agree with that, although originally I was just pointing out that `grid: subgrid;` as shorthand is not actually explained with the actual grid-2 spec. I'm aware it's just using `subgrid` in what `grid` is shorthand for, but `subgrid` being a possible value of `grid` is not explicitly mentioned.

But as @MatsPalmgren points out, if the syntax used in the example is no longer valid then that's also an issue.

**Comment by tabatkins** [comment]
`subgrid` is defined (slightly above the linked example) to be a value for `grid-template-rows` and `grid-template-columns`; the `grid` property references these properties in its own definition.

But yeah, the current `grid` grammar does require one to specify *both* rows and columns, rather than just one, so the example's syntax needs to be updated to `grid: subgrid / subgrid;`.
