### ISSUE TITLE
[css-overflow-4] scrollbar-gutter is too complex

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#4674]
https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property

Blink is interested in implementing/shipping scrollbar-gutter, particularly the "stable" value.

However, the other keywords do not seem as useful. Both "force" and "always" request reserving space even when an overlay scrollbar is used. What's the use case for that? This does not seem useful, and at any rate it is not clear how much space should be reserved.

/cc @bfgeek fyi

**Comment by fantasai** [comment]
Side comment: this property really ought to be in the scrollbars spec, imho. :/ Even if only in L2.

**Comment by frivoal** [comment]
## force:

`force` itself doesn't force the creation of gutters with overlay scrollbars (although it can be used together with `always`, which does). It forces the creation of gutters even if `overflow` is `visible` (or `clip`) if there would be gutters with the other values of `overflow`. So `scrollbar-gutter: stable force` would add gutters to `overflow:visible` elements if the UA uses classic scrollbars, and not if it uses overlay scrollbars. `scrollbar-gutter: always force` does add gutters to every element 

The use case was being able to reserve the same amount of space on the edges of an element that is adjacent to a stroller as is being reserved in the stroller itself, so that things would visually line up. The same effect could be achieved by adding padding for classic scrollbars and none for overlay scrollbars, but there is no reliable way for authors to know if they should be adding that padding, and if so how much.

A concrete example that was given was Gmail (I believe this was raised by Googlers, though I cannot remember for sure), and it's attempt to line up the controls in the toolbar above the list of mails with those in the list of mails. Here are two screenshots from my system (macOS with Firefox), one with classic scrollbars turned on (at the OS level), where Gmail correctly guesses how much padding it should be adding to the toolbar above the list, and one with overlay scrollbars turned off, where Gmail incorrectly adds padding, throwing things out of alignment (orange dotted line added manually to highlight what I'm talking about).

<img width="335" alt="classic" src="https://user-images.githubusercontent.com/113268/72501818-3506ea80-387b-11ea-84fa-f6fb1ded1d64.png">
<img width="314" alt="overlay" src="https://user-images.githubusercontent.com/113268/72501821-3801db00-387b-11ea-84b0-d1e440883bd3.png">



## Always:

Always does reserve space for a gutter even on browsers with overlay scrollbars.

This is for cases when authors find the overlap between the overlay scrollbar and the content to be problematic. If the scrollbar ends up being over decorative elements or empty space, it's ok, but if it ends up over text, it can hinder readability, and if over interactive elements, it can get in the way of trying to click those. Overlay scrollbars generally disappear or shrink (or both) when not used, so if the user waits a bit, the content will eventually no longer be obscured, and can be read or interacted with, but this can be annoying.

For instance, something like https://jsbin.com/bulidiv/edit?html,css,output  is really annoying to use in a browser with overlay scrollbars. You could add padding to get around that, but (1) how much padding is enough to avoid the overlay scrollbars?, and (2) that padding isn't needed in case of classic scrollbars, so you have to detect that too and remove the padding if you don't want to waste space.

[Here's an example at stackoverflow](https://stackoverflow.com/questions/439553/how-to-prevent-scrollbars-from-overlapping-the-content) of someone trying to deal with this situation.

----

Anyway, that's what these values are for, and they can be combined because these two use cases aren't exclusive (e.g. https://jsbin.com/kafoyuw/edit?html,css,output).

I think It may be useful to add examples to the spec along the lines of the things I showed here, to help readers understand what this is for.

> It is not clear how much space should be reserved.

The spec isn't clear about that, but the intention is that you'd reserve enough space for the overlay scrollbar to fit into when it is displayed. If it has multiple states of varying sizes (on macOS it gets bigger when you hover it), you'd size it to the largest one.

I'm happy to add that clarification.

**Comment by tantek** [comment]
Note that Rossen later followed-up in that same meeting to undo that resolution:

[https://www.w3.org/2020/01/23-css-irc#T12-29-54](https://www.w3.org/2020/01/23-css-irc#T12-29-54)

"RossenF2F: Re. merging, scrollbar-width/color just styles controls... scrollbar-gutter is more about the box model

... so let's not move everything to scrollbars yet until we know what will remain there"

So for now, this no longer impacts CSS Scrollbars.

(Originally published at: https://tantek.com/2020/023/t2/)

**Comment by felipeerias** [comment]
Reading the CSS Working Group discussion above, it seems that the `scrollbar-gutter` spec is (was?) still likely to change or even disappear altogether.

I have started working on the Blink implementation of this property, but before I go any further I would like to ask about its current status?

@frivoal @fantasai @tantek

**Comment by Bosch-Eli-Black** [comment]
I hope this isn't adding noise to the discussion, but I wanted to pop in and say that `scrollbar-gutter` helped us to make a table with a sticky header where the width of the columns in the table's header are the same width as the columns in the table's body.

Table structure:

```test
|---------------------------------------|
|   header_col1       header_col2       |
|---------------------------------------|
|    body_col1         body_col2        |
|---------------------------------------|
|    body_col1         body_col2        |
|---------------------------------------|
|    body_col1         body_col2        |
|---------------------------------------|
```

HTML
```html
<div class="table">
   <div class="head">
      <div class="row">
         <div>col1</div>
         <div>col2</div>
      </div>
   </div>
   
   <div class="body">
      <div class="row">
         <div>col1</div>
         <div>col2</div>
      </div>
   </div>
</div>
```

CSS:

```CSS
.head, .body {
     display: flex;
     flex-direction: column;
}

.body {
     height: 200px;
     overflow-y: auto;
}

.row {
     display: flex;
}

.row > *:first-child {
     flex: 1;
}

.row > *:last-child {
     width: 100px;
}
```


Depending on how much content is inside `.body`, a scrollbar may or may not be shown. If the scrollbar is shown, then the first column ends up being wider in the header than it is in the body.

`scrollbar-gutter` fixed this:

```css
.body, .head {
     scrollbar-gutter: stable force;
}
```

What's not clear to me is how the browser knows to give `.head` a gutter for the vertical scrollbar but not for the horizontal scrollbar.

**Comment by felipeerias** [comment]
Thank you very much @Bosch-Eli-Black, that's a good example.

Regarding your last comment, `scrollbar-gutter` only applies to the scrollbars at the inline edges of the box (i.e. the vertical scrollbar for horizontal text, and the horizontal scrollbar for vertical text).

There is an example of `scrollbar-gutter` with vertical text in the [explainer](https://github.com/felipeerias/scrollbar-gutter-explainer) ([scrollbar_gutter_example_03](https://github.com/felipeerias/scrollbar-gutter-explainer/blob/master/examples/scrollbar_gutter_example_03.html)):

![](https://raw.githubusercontent.com/felipeerias/scrollbar-gutter-explainer/master/examples/images/example03-fixed-scrollbars.png)

There is also issue https://github.com/w3c/csswg-drafts/issues/5252 to look into adding a gutter for the scrollbar in the other direction.

**Comment by chrishtr** [comment]
I propose that we remove `stable` from the `scrollbar-gutter` spec, as it would require leaving space even in the presence of overlay scrollbars.

Second, I propose we introduce an environment variable or measurement unit for the width of scrollbars, to handle the use case of making sure interactive content does not end up underneath an overlay scrollbar (see issue 5232). As @emilio has mentioned elsewhere, this will also resolve issue 6026.

**Comment by frivoal** [comment]
> I propose that we remove always from the scrollbar-gutter spec, as it would require leaving space even in the presence of overlay scrollbars.

Yes, that is very much intentional, to solve the "interactive content underneath an overlay scrollbar" use case described in https://github.com/w3c/csswg-drafts/issues/5232#issuecomment-787614795.
<details style=border:solid><summary>(summary of that use case for those who haven't read that thread)</summary>
The use case is when you have (small) interactive elements near the edge where the scrollbar would be. For instance, a basic todo list, with each line starting with some text and ending with a right-aligned checkbox. If you have a classic scrollbar, everything's fine, but if you have an overlay scrollbar, it could obscure the check boxes and make them hard to interact with.

This is fine:
![Screen Shot 2021-04-15 at 11 05 22](https://user-images.githubusercontent.com/113268/114803479-81244000-9dda-11eb-94dc-5a56716080c1.png)

This is not great:
![Screen Shot 2021-04-15 at 11 03 34](https://user-images.githubusercontent.com/113268/114803509-8c776b80-9dda-11eb-9a17-ed69409e16f3.png)

Overlay Scrollbar are typically transient and disappear when not interacted with, so the checkboxes they cover are not impossible to use. But when the scrollbars are there they get in the way, and that makes for an awkward interaction. The author might try and solve the problem by adding some right padding, but (1) how much?, and (2) that padding isn't needed in the case of classic scrollbars. scrollbar-gutter: always does just the right thing in this case, yielding an identical result in the first case, but allowing for this with overlay scrollbars:

![Screen Shot 2021-04-15 at 11 03 59](https://user-images.githubusercontent.com/113268/114803712-ed06a880-9dda-11eb-9dc2-86668e812b16.png)

This is not necessarily always what you want, but some of the time it is.
<hr>
</details>

> Second, I propose we introduce an environment variable or measurement unit for the width of scrollbars, to handle the use case of making sure interactive content does not end up underneath an overlay scrollbar (see issue #5232). As @emilio has mentioned elsewhere, this will also resolve issue #6026.

* We would need two environment variables to solve this two use cases, not one:
    * for the use case summarized above, we would need an env variable that is the width of the scrollbar when scrollbars are of the overlay kind, but 0 with classic scrollbars
    * for #6026, we'd need the opposite: an env variable that is 0 when scrollbars are of the overlay kind, but the width of the scrollbar with classic scrollbars. This is also the one you'd need if you wanted to replace the `force` value as discussed in https://github.com/w3c/csswg-drafts/issues/4674#issuecomment-575027040
* You'd need a unit (well, two), not env variables, as due to the [scrollbar-width](https://drafts.csswg.org/css-scrollbars/#scrollbar-width) property, not all scrollbars in the page need to be the same width
* Possibly you'd need to double up the amount if units to 4, to account for the fact that scrollbars can end up on either side of the element (either due to bidi, or to something like https://github.com/w3c/csswg-drafts/issues/1293)
* Possibly, you'd need to double up yet again the amount of units to return the scrollbar width on the nearest scrolling ancestor rather than on the element itself, to replace the uses of the proposed `match-parent` value

If we could get away with a single env variable, it could possibly be a nicer solution. If we need a whole bunch of units, that feels a lot less attractive.

I've gone into more details about why I think units or env variables would not be a good solution in https://github.com/w3c/csswg-drafts/issues/5232#issuecomment-648047604

**Comment by chrishtr** [comment]
> Yes, that is very much intentional, to solve the "interactive content underneath an overlay scrollbar" use case described in [#5232 (comment)](https://github.com/w3c/csswg-drafts/issues/5232#issuecomment-787614795).

Right. What I'm saying is that we should use a different solution to this problem than `always`. According to my interpretation of the statement, this is the main reason the [webkit leads are not supportive](https://lists.webkit.org/pipermail/webkit-dev/2021-February/031708.html) of `scrollbar-gutter` right now:

"Our opinion is that we don't want to encourage web developers to reserve space for scrollbars in a way that prevents non-interactive content from intruding into that space. This undoes a big advantage of overlay scrollbars, in that they leave more space for content." @smfr who wrote that comment.

I propose we at least remove `always` for now, and then consider alternate solutions such as the `match-parent` value you suggested in #5232.

**Comment by felipeerias** [comment]
It seems that a key question is how to provide control over the behaviour of children elements in relation to their parent's scrollbar gutter. This is related to two use cases that are not yet covered by the spec:

- some elements (headers, footers, dividers, etc.) need to extend to the visible edge of the parent, drawing over the gutter if needed (https://github.com/w3c/csswg-drafts/issues/5232)

- some elements (buttons, checkboxes, etc.) need to be moved so they are not covered by their parent's overlay scrollbar.

One possible approach could be to consider adding the following functionality to `scrollbar-gutter`:

- with fixed scrollbars, when the box is not yet scrolling, a child element's background may extend to the edge of its scrolling parent (as in https://github.com/w3c/csswg-drafts/issues/5232#issuecomment-648047604):

![new_fixed](https://user-images.githubusercontent.com/1412060/115408952-47b16180-a22c-11eb-9401-d33ed985c173.png)

- with overlay scrollbars, a child element may get a gutter that matches its parent's so that the content inside that element is not covered when scrolling happens:

![new_overlay](https://user-images.githubusercontent.com/1412060/115408993-4e3fd900-a22c-11eb-8052-3ce31f7f765e.png)

I am still thinking about how those two behaviours could be expressed with `scrollbar-gutter` (one value? two values?).

**Comment by bmathwig** [comment]
Just to follow up on this from the meeting:

Simplifying scrollbar-gutter down to just auto and always makes the intent of the developer clear. If scrollbar-gutter is requested, the intent of the author is most likely to provided cross-UA reservation of scrollbar space regardless of classical or overlay scrollbars.

In the case of stable, the use case here is only to solve for the scrollbar pop from overflow: auto in y-axis alignment of UI elements. The author may apply padding or margin to a non-scrollbar container above the scrollable container to match the gutter, but would have to conditionally remove this if the UA implemented overlay scrollbars. Using always instead would guarantee alignment without having to differentiate between UAs with classical scrollbars and with overlay scrollbars.

In the description of scrollbar-gutter it states:
The scrollbar-gutter property gives control to the author over the presence of scrollbar gutters separately from the ability to control the presence of scrollbars provided by the overflow property.

The values stable and force seem intricately dependent on the overflow property, which voids the description of being separate from the overflow property. This is why I think we should drop everything except auto and always.

**Comment by chrishtr** [comment]
> Simplifying `scrollbar-gutter` down to just `auto` and `always` makes the intent of the developer clear. If `scrollbar-gutter` is requested, the intent of the author is most likely to provided cross-UA reservation of scrollbar space regardless of classical or overlay scrollbars.

I think that by far the most important use case of scrollbar gutter is to *avoid layout shifts that depend on the presence of scrollbars*. I hope we can all agree that this is an important use case, and as far as I can tell we do. Developers have been frustrated by this problem for a very long time. This problem only applies in the presence of classic scrollbars, and does not exist for overlay scrollbars. Overlay scrollbars never have layout shifts that occur due to the presence or absence of scrollbars.

This use case would be solved by the subset of `scrollbar-gutter` that does not include `always`, and is still solved even with @emilio's proposal in #6028 to restrict to boxes that might have a scrollbar. Let's just do those, and solve the most important use case.

**Comment by bmathwig** [comment]
>  Let's just do those, and solve the most important use case.

I agree with this @chrishtr. I think there is still the question of handling alignment between non-scrollable and scrollable boxes on classical vs overlay scrollbars between UAs. Could this be solved with a media query (overlay vs classical) like @emilio mentioned?

**Comment by chrishtr** [comment]
> I agree with this @chrishtr. I think there is still the question of handling alignment between non-scrollable and scrollable boxes on classical vs overlay scrollbars between UAs. Could this be solved with a media query (overlay vs classical) like @emilio mentioned?

The non-`always` values of `scrollbar-gutter` have no effect on overlay scrollbars. So for this use case, there is no need for a media query to detect overlay vs classic.

**Comment by Bosch-Eli-Black** [comment]
@bmathwig 
> If `scrollbar-gutter` is requested, the intent of the author is most likely to provided cross-UA reservation of scrollbar space regardless of classical or overlay scrollbars.

Most of the evidence that I'm seeing is to the contrary: We only want to add padding when classic scrollbars are present 🙂  I believe this is the case in both @frivoal and my examples, above.

**Comment by Bosch-Eli-Black** [comment]
It seems to me that there are three different use cases in this thread:

1. Be able to perfectly align an element's header with its scrolling body. (See the GMail example and my example)
2. Avoid layout shift when an element overflows and gets classic scrollbars.
2. Avoid drawing overlay scrollbars over interactive elements, such as checkboxes.

#1 and #2 are concerned with classic scrollbars but not overlay scrollbars.
#3 is concerned with overlay scrollbars but not classic scrollbars.

Personally, I think #1/#2 are the more pressing issues 🙂

**Comment by emilio** [comment]
Yeah, and for the third use-case scrollbar-gutter doesn't seem a great fit (as @smfr said, you mostly want to be able to position interactive elements outside of the overlay scrollbar area, not all elements, that kinda defeats the purpose of overlay scrollbars). 

Side note: I just realized that for the first use-case there's already a way around it, fwiw, which is something like `scrollbar-color: transparent transparent; overflow-y: scroll`. That doesn't work for the second since you want to actually show the scrollbar if needed though, so we need `scrollbar-gutter: stable` for that :)

Given those are the cases that people are interested in solving, and that we can always extend the property later if needed, simplifying `scrollbar-gutter` to apply to scrollable boxes, and maybe to just `{auto, stable, always}` (do we need `both`?) seems like a good path forward to solve those two use-cases, and seems much more reasonable to specify and implement interoperably.

**Comment by chrishtr** [comment]
> maybe to just `{auto, stable, always}` (do we need `both`?)

Why did you include `always`? That one requires a scroll gutter for overlay scrollbars, which is the main thing @smfr raised as a concern. Otherwise what you said sounds good to me.

**Comment by emilio** [comment]
Ah, true. Then `{auto, stable}` sounds good to me. I think `always` was required for Microsoft, but you're right about that, that probably requires more discussion :)

**Comment by bmathwig** [comment]
To solve for case:
1. Be able to perfectly align an element's header with its scrolling body. (See the GMail example and my example)

There is a need to specify padding on the header element if there are classic scrollbars, but remove that padding if on Safari with overlay scrollbars. For example, adding padding of 16px to my non-scrollable header will misalign on Safari because my scrollable content will not have a scrollbar gutter. I think that special casing is still an issue with ```stable```.

**Comment by bmathwig** [comment]
I think it would be okay to do ```{auto, stable}``` as @emilio suggests.

**Comment by bradkemper** [comment]
And `both`? That seems pretty useful for when you want the content centered, and one scroll bar or it's gutter is pushing it to one side.

**Comment by bradkemper** [comment]
Are you also saying it would apply to `overflow:visible`, etc.? Or would it still need `forced` for the Gmail example?

**Comment by chrishtr** [comment]
> Are you also saying it would apply to `overflow:visible`, etc.? Or would it still need `forced` for the Gmail example?

Hi, which comment are you responding? Not sure I get your question fully.

**Comment by bradkemper** [comment]
@emilio and @bmathwig seemed to be saying that `auto` and `stable` would be enough for the possible values, but it seems like `both` and possibly `forced` would also be good.

**Comment by bmathwig** [comment]
@bradkemper I think having ```both``` and ```forced``` gets back the primary issue of it being to complex to use, since that was the original proposal. ```auto``` and ```stable``` solve for the primary use case and only having those two seems sufficient for now to reduce complexity.

**Comment by bradkemper** [comment]
I see. I just thought the Gmail alignment issue and the table fixed header issue were pretty important use cases too. For me, those kind of things are probably more important, but I can see how others might not agree. 

`both` seemed like a rather simple addition to include, being the same as `stable`, but on both sides. But maybe that is more complex than I imagined?

**Comment by felipeerias** [comment]
A clear use case for ` both` happens when applying ` scrollbar-gutter` to the root element: without `both`, the page content will be permanently skewed to one side instead of centred in the viewport.

Left: `html { scrollbar-gutter: stable; }`
Right: `html { scrollbar-gutter: stable both; }`

![bothinroot](https://user-images.githubusercontent.com/1412060/115885905-5d709200-a48b-11eb-8ad0-567322b68726.png)

Note that without `both` there isn't an easy way to move from the scenario on the left to the scenario on the right using only CSS. IMHO the usefulness of this value would justify the small increase in complexity.

@chrishtr @emilio @bmathwig @bradkemper

**Comment by emilio** [comment]
Well, but with `both` you get that misalignment when the page is actually scrollable, right? As in, you show the scrollbar in one of those two sides, and the other side is a blank gap.

**Comment by felipeerias** [comment]
@emilio : Sure, there is a tradeoff between choosing one or the other. My intention was to present a use case where `both` is valuable and the author should have the option to use it. 

For example, in this SO question about [How to prevent scrollbar from repositioning web page?](https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page) several of the answers suggest workarounds that would have a similar outcome to `both` ([here](https://stackoverflow.com/a/30293718), [also here](https://stackoverflow.com/a/39289453) and others).

**Comment by bmathwig** [comment]
Since there is `auto` and `stable` to make it predictable for non-overlay scrollbars, we still need a third option to reserve space no matter what type of scrollbar it is. Instead of `both`, we can use either the keywords `always` or `force` to say 'No matter what, overlay or non-overlay, reserve that space for me'. It makes it deterministic. To replicate the right image above, use `always|force` and set padding/margin left. I think if we simplify it down to three cases it will reduce the complexity:

Case 1: Do what it does now, only create a gutter if the box is overflowing (auto)
Case 2: Allow the author to reserve space for a classic scrollbar even if the content is not overflowing (stable)
Case 3: Allow the author to reserve space for both classic and overlay scrollbars, no matter what (always or force)

Case 3 is important for alignment between Safari on Mac and Chrome on Windows. Currently, to make something align in a non-scrollable box, you need to detect the UA and set padding accordingly (depending on classic vs overlay).

**Comment by LeaVerou** [comment]
Indeed, I've found this property incredibly confusing every time I've looked into it (multiple times in the last few weeks). I can't even hold what the values do in my head long enough to finish reading the docs, which is a pretty bad sign.

Trying to introspect a bit more about what makes it so hard to learn, these are my raw thoughts:

- `stable` has no obvious meaning. I can think of many possible things that `scrollbar-gutter: stable` can plausibly do, and what it actually does is only one of them and it seems arbitrarily chosen. The same thing could have been expressed via `always` and it would have been no more surprising.
- `always` means always, except when it doesn't, and then you need `force` to get it to *really* mean `always`...
- `both` looks like it makes whatever the rest of the values means apply to both directions, which begs the question what direction is specified without it, and how to set `scrollbar-gutter` values that are different for X and Y.
- No combination of keywords seems to be able to specify the default behavior, which is just ...`auto`. `auto` should be possible to express through the property's syntax, which would make it easier for authors to tweak the default behavior by adding or removing parameters, whereas `auto` cannot be combined with anything else.

Ignoring `both` for a moment, I think the primary problem here is that we have a set of 4 distinct values to express a combination of parameters that, if specified independently, would produce far more than 4 combinations.   Therefore each of these values sets a number of parameters, which often seems rather arbitrary, making its syntax hard to internalize.

It seems that the actual thing this is trying to control is:
1. Is a gutter present with classic scrollbars?
	- If yes: Is a gutter present with overlay scrollbars as well? 
2. Is a gutter present when content is not overflowing?
3. Is a gutter present when `overflow` is `scroll`/`auto`?
	- If yes: Is a gutter present when `overflow` is `visible`/`hidden`/`clip` as well?

I think we may be seeing the same design mistake that was made with `display` or `position`.
I wonder if we can reach a more explicit syntax where each orthogonal decision is obvious instead of "packaged" behind a keyword. Also for 3, why do we need to account for this? Can't whoever sets this also set `overflow` accordingly?

**Comment by chrishtr** [comment]
> @felipeerias @chrishtr Is the solution to this issue to put `scrollbar-gutter: stable` on the `<div>` holding the three green squares at the top?

I'm not sure what the best solution is to this problem. Right now I'm arguing that we just solve a subset of the use cases that we all agree on, and consider solutions to more complex situations like this later.

**Comment by astearns** [comment]
Changing tags for this and #6028 in favor of a breakout session

**Comment by Bosch-Eli-Black** [comment]
I still think it'd be better to first focus on CSS properties related to non-overlay scrollbars. Reserving space for overlay scrollbars seems to be contentious, whereas it seems that no one has a problem with reserving space for non-overlay scrollbars 🙂

**Comment by felipeerias** [comment]
@LeaVerou 

That's a good point about the `scrollbar-gutter` syntax.

It makes me wonder whether it is possible at all to find meaningful keyword names to express that behaviour in a clear way, or we would do better by looking into other ways to cover the most complex use cases.

My concern is that we might not be able to find a simple way to cover all scenarios, regardless of whatever route we take.

The `scrollbar-gutter` functionality that requires a separate property is dynamically replacing the empty gutter with a fixed scrollbar as the content grows, avoiding layout changes. If that is all that  `scrollbar-gutter` does, `stable` seems a reasonable name choice (as in _"your layout will remain stable"_).

At the moment, I am leaning towards having that simple syntax for `scrollbar-gutter` plus a collection of small flexible tools to cover more complex scenarios.

For example, let's say that we also had:

* a unit or env var(s) to get the scrollbar thickness
* a media query to detect that the UA is using fixed/overlay scrollbars
* selector(s) to identify the edge where the block scrollbar is placed on a given element.

Then, implementing e.g. the `stable force` behaviour could be done with something like:

    @media( <SCROLLBARS ARE FIXED> ) {
      .header[ <SCROLLBAR ON THE LEFT> ] {
        padding-left: <SCROLLBAR THICKNESS> ;
      }
      .header[ <SCROLLBAR ON THE RIGHT> ] {
        padding-right: <SCROLLBAR THICKNESS> ;
      }
    }

Maybe this would be a better approach? Not really "simpler", but perhaps clearer for Web authors.

**Comment by bmathwig** [comment]
@felipeerias I think having a media query to detect that the UA is fixed/classic scrollbars is a great idea. It solves the concerns I had above for stabilizing padding and margins between UAs with different scrollbar implementations.

**Comment by chrishtr** [comment]
At the breakout meeting today, there plenty of attendance, and there was consensus on:

* The `auto` and `stable` keywords, as currently defined (in particular, that for `stable` the gutter is defined as an additional padding, so that backgrounds of the scrolling element will go into the gutter)
* Adding `overflow:hidden` to the list of cases where the gutter behavior of `stable` occurs (representatives of all three engines - @smfr @dholbert @chrishtr indicated it would be straightforward to support that, so @emilio's earlier concern is taken care of).

Adding agenda+ so that we can resolve at the next meeting of the whole group on the above.

**Comment by Bosch-Eli-Black** [comment]
@chrishtr Thanks for the update!

Am I reading this correctly, that there's consensus on `auto` and `stable` but not `always` and `force`?

**Comment by Bosch-Eli-Black** [comment]
@chrishtr Sounds good, thanks 🙂  At least for our use case, `auto` and `stable` are good enough 🙂

**Comment by chrishtr** [comment]
I propose we close this issue and discuss further enhancements in other issues. @frivoal any objection? Closing this issue will be useful because it's not clear what this issue represents now that we have consensus on an interoperable subset of the API.

**Comment by yisibl** [comment]
Normally when opening a modal dialog we want the page behind it not to be scrollable, which requires adding `html { overflow: hidden; }`, but since the scrollbar is hidden it causes the content of the page to be offset to the right.

`scrollbar-gutter: stable` solves this problem, but after opening the dialog you will notice a red background on the right side, which is very strange.

This is a very important scenario that seriously affects the usability of the `<dialog>` element. Both Chrome and Firefox have this issue, does this need further clarification in the spec?

Demo: https://scrollbar-gutter-stable-bug.glitch.me/

![image](https://github.com/w3c/csswg-drafts/assets/2784308/e675d79f-7ead-4645-b4cb-d60da3db1d87)
