### ISSUE TITLE
[resize-observer] attributes cannot be sequence<T>

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#4683]
There are 3 such attributes in https://drafts.csswg.org/resize-observer/#resize-observer-entry-interface

https://heycam.github.io/webidl/#idl-sequence says "Sequences must not be used as the type of an attribute or constant." This is because it would return a new JS array every time.

These should probably be FrozenArray<T> instead.

**Comment by foolip** [comment]
@atotic @gregwhitworth

**Comment by stephenmcgruer** [comment]
Looks like there's still one left; ResizeObservation has a lastReportedSizes attribute that is a sequence. (https://drafts.csswg.org/resize-observer/#dom-resizeobservation-lastreportedsizes)

**Comment by dlibby-** [comment]
Good catch - that interface is just an internal, non-normative web idl, as explained by this [note](https://drafts.csswg.org/resize-observer/#resize-observation-interface):

`This section is non-normative. ResizeObservation is an example struct that can be used in implementation of Resize Observer. It is being included here in order to help provide clarity during the processing model. It effectively holds observation information for a single Element. This interface is not visible to Javascript.`

I'll go ahead and update that as well for clarity

**Comment by saschanaz** [comment]
>Good catch - that interface is just an internal, non-normative web idl

How about using `.example` CSS class there?

**Comment by saschanaz** [comment]
Fixed by #4909
