### ISSUE TITLE
CSS Snapshot 2018

### ISSUE THREAD

**Issue by hugonteifeh** [w3c/csswg-drafts#4704]
I'm currently working on a project and have decided to use the "CSS Snapshot 2018" as a reference to decide which CSS properties to support and what possible values they may have. 

As I'm reading [CSS snapshot 2018](https://www.w3.org/TR/css-2018/#css), I feel like I'm constantly finding some kind of inconsistencies . For example the "2018 snapshot" includes the [CSS Flexible Box Module Level 1 spec](https://www.w3.org/TR/css-flexbox-1/) which in its turn extends the "display" property, clicking on any of the "display" links in that spec will lead to the [CSS Display Module Level 3 spec](https://www.w3.org/TR/css-display-3/#propdef-display) which does not really have the same "value" as the "display" property referenced in the ["Property index section"](https://www.w3.org/TR/css-2018/#properties) in the "CSS Snapshot 2018" which is derived from CSS 2.1. And so I feel completely lost and not sure how to actually use ""CSS Snapshot 2018"". I really appreciate if you guys can provide some insight or any tips regarding this. Thanks :)

**Comment by frivoal** [comment]
This is indeed somewhat tricky, but let's start with your example: `display` exited in CSS2.1, so it is certainly a stable property. Flexbox adds a value to it, and flexbox is stable, so the new value `flex` is also part of what can be considered stable CSS. The CSS Display module level 3 includes that, so these parts are also stable, but it includes more than that, such as `display: contents` or `display: flow-root`, as well as many detail explanations of how `display` works, which are much more precise than what we had before. When we made the determination in 2018 of what to include in the list, these didn't feel as stable as the rest, so they were not included.

Personally, at this point, I think the CSS Display 3 should be included in the next snapshot, but the CSS WG hasn't had that discussion yet.

Generalizing, things that are in the snapshot are known to be in a good shape. But that doesn't mean that other specifications are bad. Very often, modules which are not yet in the snapshot will include updated version of things in the snapshot, sometimes with new features, and often with better and more precise definitions. They're meant to be better (otherwise we wouldn't write them), but they have not yet received sufficient vetting / reviewing / testing to be sure that they actually are.

If you are looking to implement something that is in the snapshot, and the same thing exists in another newer module that isn't in the snapshot, I'd highly recommend looking at the newer version as well, but at the same time you should also read them more cautiously, as they are still drafts, and may contain mistakes.

As for whether the Snapshot is a good list of what to implement, it really depends on what you're project is. It's not a bad starting point, but depending on your goals, you may want to include more, or less, or prioritize differently than just by stability.

**Comment by hugonteifeh** [comment]
Hey Florian!

Thanks for this thorough answer. I think that "snapshots" as a concept suits me as an implementer and my project as it shifts the responsibility of wisely choosing what to go into the implementation to the committee. The problem here, as I see it, is that "snapshots" are released way _too infrequently_ (One to two years, If I remember correctly), especially that CSS is not anymore a monolithic specification but rather a collection of specs which can be developed at a different speed. Furthermore, I think that the 2018 snapshot particularly is not the best snapshot and 2020 will be better as many of the specs that were not stable at the time of releasing the "2018 Snapshot" are stable today.

So for now, I am gonna use the "2018 snapshot" as a good starting point, but won't limit myself to it.

**Comment by frivoal** [comment]
Closing this as a "question answered".

See https://github.com/w3c/csswg-drafts/issues/4715 for progress on making a new snapshot.
