### ISSUE TITLE
[css-nav] Urgent site issue(s)?

### ISSUE THREAD

**Issue by Malvoz** [w3c/csswg-drafts#4730]
Visiting (careful!) https://www.w3.org/TR/css-nav/ - which is latest publication to my understanding - as opposed to https://www.w3.org/TR/css-nav-1/ causes the browser to seemingly download resources indefinitely, with console errors about incorrect MIME-types such as shown in this image:

![css-nav](https://user-images.githubusercontent.com/26493779/73599515-99e16680-4544-11ea-8417-06d59988e199.png)

Probably not an issue that is restricted to the spatial nav spec.

/cc @plinss

**Comment by svgeesus** [comment]
Thanks for the report! This seems to be due to a server rewrite rule. I have reported it to the W3C systems team.

**Comment by jihyerish** [comment]
Thank you for reporting this issue!
I published css-nav-1, not css-nav.
(The confirmation mail for the latest publication: https://lists.w3.org/Archives/Public/public-tr-notifications/2019Nov/0070.html)

I didn't aware of https://www.w3.org/TR/css-nav/, and it had been created by mistake I guess?!

**Comment by svgeesus** [comment]
It isn't a mistake, it is created by the webmaster so that there is a `latest` and a `most stable` and so on link for all reports on /TR.

But the way it is implemented seemms to have triggered this but. @jihyerish  @frivoal  I cc'ed you on the report to systems team; that email has more detail on what I found.

**Comment by svgeesus** [comment]
The faulty redirect and the missing stylesheet are now fixed. Thanks for the report!
