### ISSUE TITLE
[css-color-5] comma-separated syntax clarification

### ISSUE THREAD

**Issue by jonathantneal** [w3c/csswg-drafts#4738]
First, thank you so much to everyone continually imagining these color functions for CSS. ❤️

Would you help me understand the syntax for [`color-adjust()`](https://drafts.csswg.org/date/2020-02-04T06:48:16/css-color-5/#coloradjust)?

```
color-adjust() = color-adjust( <color> [ [=color-functions|color-function=] <colorspace>? ]?] )
```

1. What does the **U+003D EQUALS SIGN (`=`)** mean in this syntax?

2. Will `color-adjust()` receive a comma-separated list of values, as seen in [**Example 8**](https://drafts.csswg.org/date/2020-02-04T06:48:16/css-color-5/#example-08a28efd)?

```
color-adjust(peru, lightness(-20%));
```

3. Would the answers these questions also apply to [`color-mix()`](https://drafts.csswg.org/date/2020-02-04T06:48:16/css-color-5/#colormix) and [`color-contrast()`](https://drafts.csswg.org/date/2020-02-04T06:48:16/css-color-5/#colorcontrast)?

---

**Additional Background**: Based on that comma-separated example, I may have expected `[=color-functions|color-function=]` to instead read as `<color-function>#` ([syntax reference](https://drafts.csswg.org/css-values-4/#mult-comma)). I would love the opportunity to better understand these syntax definition things in general.

**Comment by svgeesus** [comment]
1. What you are seeing is an attempt to use the [Bikeshed](https://tabatkins.github.io/bikeshed/) (our spec preprocessor) [autolink syntax](https://tabatkins.github.io/bikeshed/#dfn-autolink) with [alternate link text](https://tabatkins.github.io/bikeshed/#autolink-inside). It hasn't worked, which is why you are seeing what you see. Had it worked, you would see 

```
color-adjust() = color-adjust( <color> [ color-function <colorspace>? ]?] )
```

and `color-function` would be a link to the list of color functions.

2. The comma between `peru` and `lightness` is an error in the example. Those two are not alternates so should not use a comma.  It will be possible to use multiple functions, but they are also not alternates so won't use a comma either.

(BTW this is why CSS Color 4 dropped the commas in, for example, `rgb(r%, g%, b%)` compared to CSS Color 3 and earlier)

3. `color-contrast` take a comma-separated list of alternates as the second argument.  For `color-mix` see [color-mix to allow more than two colors?](https://github.com/w3c/csswg-drafts/issues/4711)

**Comment by svgeesus** [comment]
https://github.com/w3c/csswg-drafts/commit/c30f4416b632f0c0928b994a3c66a437a25c2202

**Comment by jonathantneal** [comment]
Thanks @svgeesus. I consider all my questions answered and this resolved. 👍

On a related note, I’ve submitted a PR to align some remaining legacy comma syntax. https://github.com/w3c/csswg-drafts/pull/4746

Thanks again, and thank you and all of the editors so much for your efforts here.
