### ISSUE TITLE
[css-contain] it should be clearer that size containment inhibits effects of contents on intrinsic sizes

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#4741]
The [definition of size containment](https://drafts.csswg.org/css-contain/#containment-size) says:

> 1. When calculating the size of the containing box, it must be treated as having no contents.

I think the implication here (given the text about replaced elements following this) is that "calculating the size of the containing box" includes both:
* finding the resolved values of `width` and `height`
* computing [intrinsic sizes](https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes)

However, I think a literal reading of the sentence implies that it means only the first and not the second.  I think it should be clearer that the computation of the intrinsic sizes of the box must also be done as though the box has no contents.  It's possible it might also be worth mentioning [automatic sizes](https://drafts.csswg.org/css-sizing-3/#automatic-size).

**Comment by frivoal** [comment]
This is indeed intended to cover both layout sizing and intrinsic sizing. Happy to clarify.

How's this?

> When calculating the size of the containing box, **including when computing its [=intrinsic size=]**, it must be treated as having no contents.

Also, 
> It's possible it might also be worth mentioning automatic sizes.

Not obvious to me that it would help. What would you do with that?

As this is a clarification rather than a contradiction or an addition, I think fixing it in level 2 is enough. I have no issue with including the fix in L1's ED, but I don't think it warrants going through the motions of republishing a REC just for this.

**Comment by frivoal** [comment]
(also are you aware of any bug triggered by this ambiguity, either in browsers or in tests?)

**Comment by dbaron** [comment]
That proposal seems reasonable.  I ran into it while writing up a proposal about the size containment needed for container queries.
