### ISSUE TITLE
[css-color-adjust-1] `color-scheme` should affect embedded iframes

### ISSUE THREAD

**Issue by tomayac** [w3c/csswg-drafts#4772]
When a site contains iframes that specify their `color-scheme` either via the [meta tag](https://drafts.csswg.org/css-color-adjust-1/#color-scheme-meta) or the [CSS property](https://drafts.csswg.org/css-color-adjust-1/#color-scheme-prop), the default text color changes, however, the background color is transparent, see this [demo](https://color-scheme-meta-css.glitch.me/) and note how the screenshot (Chrome Canary 82 left, Safari Tech Preview 100 right) shows the disappearing heading (white on white):

![Screen Shot 2020-02-12 at 10 15 16](https://user-images.githubusercontent.com/145676/74412619-22fa7680-4e3e-11ea-88d6-38fceb4f375f.png)

(Chrome doesn't implement form element darkening yet.)

If, however, one loads one of the embedded iframes in isolation ([demo](https://color-scheme-meta-css.glitch.me/dark-meta.html)), things work as expected and the background is dark (again Chrome left, Safari right):

![Screen Shot 2020-02-13 at 08 56 20](https://user-images.githubusercontent.com/145676/74412941-bd5aba00-4e3e-11ea-9ce6-419e77238ab5.png)

As discussed with @chrishtr in an offline thread, `color-scheme` should arguably also affect embedded iframes and render them as if they were the root document.

Spec links:

- https://drafts.csswg.org/css-color-adjust-1/#color-scheme-prop
- https://drafts.csswg.org/css-color-adjust-1/#color-scheme-meta

CC: @lilles

**Comment by lilles** [comment]
If we introduce this on the root element instead of the canvas you would also have the question of whether it should be solid white, instead of transparent, for the light color-scheme. That would not be web-compatible.

You have the same issue, without color-scheme, embedding an unstyled document in a top document with a black background:

```
<!doctype html>
<body style="background:black;color:white">
<p>Do you see the iframe text?</p>
<iframe src="data:text/html,iframe text"></iframe>
```

If the root element got a solid dark background here, and you wanted a transparent iframe with a dark color-scheme, you would have to explicitly set the background to transparent, which is the opposite of how iframes normally work.

My take is that we should resolve this issue with no change.

**Comment by chrishtr** [comment]
I think it would be web-compatible to do it for dark mode only, however. This is indeed a slight inconsistency between light and dark modes.

One other half-solution to the problem of overriding a UA-supplied canvas color in presence of dark mode: the developer can put an alternate opaque color on the HTML element, which will then completely obscure any black. This, however, does not work if the developer wishes to have any transparency on the iframe.

**Comment by AmeliaBR** [comment]
One way of looking at the problem is that it's about a mis-match between the color-scheme of the parent frame and the iframe: the iframe says it supports a dark background, but the parent page is giving it a light one at the same time as the browser is switching all the other iframe styles over to dark mode.

I see two solutions:

- When there is a _mismatch_ in color scheme between the parent document and the iframe document, the browser should draw an opaque iframe canvas (in the correct background color for the iframe's root color scheme).  The canvas remains transparent if the iframe element's color scheme is the same as the root element for its source document.

- Ignore a `supports-color-scheme: dark` meta setting for the root of the iframe embedded content unless the parent document (or the iframe element in particular) is also in a dark color scheme.

  That doesn't address the reverse issue (the parent document is in dark mode but the embedded iframe doesn't support a dark mode), but hopefully the parent document's authors are more likely to test this situation (and add their own opaque background to the iframe), when they define the dark mode.

**Comment by chrishtr** [comment]
@AmeliaBR I like your first suggestion a lot - it provides a logical color backplate when embedding into a setting that is likely to have an incompatible color scheme.

**Comment by tomayac** [comment]
> @AmeliaBR I like your first suggestion a lot

+1, as a developer, this meets at least my expectations… :-)

**Comment by emilio** [comment]
Doesn't that provide information from the parent document that the child document probably shouldn't have access to? Specially if the iframe is cross-origin.

**Comment by AmeliaBR** [comment]
> Doesn't that provide information from the parent document that the child document probably shouldn't have access to? 

That's a good argument against my second proposal (change whether `color-scheme` has an effect or not, and therefore how the system colors evaluate in the embedded document).

But I don't think it would be a problem for the first proposal (draw an opaque canvas behind the iframe's root background when there's a mismatch), since I don't think there's any way for the document to read back the used canvas color.

**Comment by tabatkins** [comment]
Right, the underlying canvas of a document isn't accessible to the page, so it should be undetectable when it happens.

**Comment by lilles** [comment]
Agree that solution 1 sounds good. Since color-scheme is specified per element, are we considering the used color-scheme of the parent document's root element, or the used color-scheme of the iframe element in the parent document?

**Comment by chrishtr** [comment]
I think it makes sense to use the used color-scheme of the iframe element in the parent document, since that element may have an override relative to its document and corresponding
different colors that may not suffice as a good enough backplate for the iframe content.

**Comment by chrishtr** [comment]
Agenda+ to achieve resolution on Amelia's first proposal: cause the canvas backdrop of an iframe to be drawn black or white if the color-scheme of the <iframe> element in the parent document differs from that of the root element of the iframe.

**Comment by fantasai** [comment]
Edited in. @AmeliaBR would you mind reviewing? :)

**Comment by AmeliaBR** [comment]
The [text](https://drafts.csswg.org/css-color-adjust/#color-scheme-effect) looks good, @fantasai, except that Bikeshed is linking the “canvas” keyword to an [SVG definition](https://svgwg.org/svg2-draft/coords.html#TermCanvas) about coordinate systems.

The most useful link would probably be the ["Backgrounds of Special Elements" section of CSS Backgrounds](https://drafts.csswg.org/css-backgrounds/#special-backgrounds), although it in turn links back to [CSS 2](https://www.w3.org/TR/CSS2/intro.html#the-canvas) for the theoretical definition of a canvas.

**Comment by fantasai** [comment]
Thanks, @AmeliaBR ! Fixed!

**Comment by lilles** [comment]
Test-cases here: https://chromium-review.googlesource.com/c/chromium/src/+/2095112

**Comment by lilles** [comment]
Tests: https://github.com/web-platform-tests/wpt/commit/348adc5c7b2e3abb76763af063fbd921afb99ac5

**Comment by AmeliaBR** [comment]
Since someone just asked me about this issue:

We still do not have cross-browser compat on the matter of opaque iframe backgrounds when there is a color-scheme mismatch. See [wpt.fyi summary](https://wpt.fyi/results/css/css-color-adjust/rendering/dark-color-scheme?label=master&label=experimental&aligned).

Are there additional spec issues still being debated, or should there be some pressure on the browser teams to get this done?

**Comment by tabatkins** [comment]
Nope, spec is fine, it's still just a browser bug. One of our engineers recently ran into it again when designing a personal site, and filed another bug for it. ^_^

**Comment by chrishtr** [comment]
Note: the only bug I could find for Chromium was [this one](https://g-issues.chromium.org/issues/40947106) (which was fixed this week by @lilles, thanks!)

**Comment by Prabhat-D-M** [comment]
Try doing this:
enableColorScheme={false} on next-themes (or removing color-scheme: dark from ) fixes the iframe/overlay rendering, and that dark mode works fine via CSS custom properties alone without the browser-level color-scheme hint.

I had a similar issue, this fixed it.
