### ISSUE TITLE
[resize-observer] The monkey patching of the event loop processing model appears to be outdated

### ISSUE THREAD

**Issue by rniwa** [w3c/csswg-drafts#4824]
The entire section about [HTML event loop processing model](https://drafts.csswg.org/resize-observer-1/#html-event-loop) appears to be outdated.

I think this section is trying to monkey patch step 14 of [updating the rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) step in the current processing model.

The spec also mentions steps like "recall styles" and "update layout". Since these aren't concepts formally defined anywhere, it's probably best to consolidate as a single step to generate or update the CSS boxes and their geometry or something instead too.

**Comment by domenic** [comment]
This is especially problematic because it is unclear when ResizeObserver callbacks happen in relationship to the other things that happen during "update the rendering", such as:

- requestAnimationFrame callbacks
- IntersectionObserver callbacks
- Paint timing
- Web animations events
- scroll and resize events
- autofocus

If someone could properly upstream this monkeypatch to HTML, with tests, that would be much appreciated.
