### ISSUE TITLE
[css-tables] Overconstrained fixed table layout: tests & questions

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#485]
Opening this on behalf of Gérard

> Greg, François,
> 
> Just in case you are not aware of this.
> 
> [CSS21] Overconstrained fixed table layout http://lists.w3.org/Archives/Public/www-style/2013Jan/0093.html
> 
> Re: [CSS21] Overconstrained fixed table layout http://lists.w3.org/Archives/Public/www-style/2013Jan/0094.html
> 
> Re: [CSS21] Overconstrained fixed table layout http://lists.w3.org/Archives/Public/www-style/2013Jan/0189.html
> 
> Can the computed width of a cell be negative and, if so, what would that imply overall? Or is this question outside the realm of the CSS3 table spec?
> ---
> 
> http://www.gtalbot.org/BrowserBugsSection/css21testsuite/border-spacing-percentage-cell-001.html
> How wide should be the navy rectangle: 200px or 400px?
> 
> IE11: 200px
> Firefox 48: 400px
> Chrome 53: 200px
> Edge: 200px
> Opera 12.16: 200px
> 
> Gérard

**Comment by cvrebert** [comment]
Safari 9.1: 200px

**Comment by FremyCompany** [comment]
I would note that by default, tables to use "box-sizing: border-box". Firefox does show a 200px-wide box like the other browsers if you apply "box-sizing: border-box" on the cells, which means that this is the problem they have to start with.

**Comment by FremyCompany** [comment]
Oh, sorry, thinking about this more, I realized the previous statement applies to tables, not to table-cells:

> However, in HTML and XHTML1, the width of the ```<table>``` element is the distance from the left border edge to the right border edge. 


I think the reason is that the width distribution **in fixed layout only** somehow inherits the strange height-distribution twist which the new spec refers to as "[Case 7](https://jsfiddle.net/6ec0hxgx/)" which creates a priority inversion between pixels and percentages when their sum exceeds available space (in that case, percentages are shrank proportionally to their preferred size, so that the sum of pixel-measures and percentage measures equals 100% of the distributable space; while width distribution usually shrink pixel values instead).

Here is a test case: https://jsfiddle.net/xz8kbp0w/ (which confirms all browser indeed have this behavior).

In your test case, the percentage is reduced to nothing because the distributable space is 0px once you remove the pixel measures. I guess the difference is that Firefox forgot to include padding in their calculation of that excess sum.

That being said, the current spec doesn't have the Case 7 behavior defined, neither for height nor width disbribution. I thought it was just a strange oddity but since it applied only to (currently undefined) height distribution, I didn't include that in the spec yet. If it happens it also reproduces for fixed tables' width distribution, we might want to include it sooner, though.

**Comment by gregwhitworth** [comment]
What the crap!!
