### ISSUE TITLE
[css-color-4] Update Default Style Rules section

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4863]
- Default Style Rules should maybe be using the corresponding system colors, not fixed colors? (If so, we need to define the default colors in prose.)
- Default Style Rules should not have a rule for html { color: black; } since the initial value of `color` handles this.
- Similarly, the initial value of `transparent` is already there, css-color-4 doesn't need a special prose rule requiring this.
- Information about the surface of the canvas is already in css-backgrounds-3. I don't have an especially strong position on which spec it should live in, but it certainly should not be duplicated across both specs. Either we remove it here and add the SHOULD statement about its expected color to css-backgrounds-3, or css-color-4 takes on defining the canvas and we remove overlapping statements about it from css-backgrounds-3.

See https://www.w3.org/TR/css-backgrounds-3/#special-backgrounds

**Comment by svgeesus** [comment]
I'm fine referencing [Backgrounds of Special Elements](https://www.w3.org/TR/css-backgrounds-3/#special-backgrounds) from color-4, since backgrounds-3 has useful prose about propagating backgrounds which fits better in that spec.

Would the prose for default `LinkText` (blue) and `VisitedText` (purple)  be defined in the [System Colors}(https://drafts.csswg.org/css-color-4/#css-system-colors) section?

**Comment by svgeesus** [comment]
Note that HTML LS has its own default stylesheet and [dark mode changes are being discussed](https://github.com/whatwg/html/issues/5426#issuecomment-607263527) so ideally changes should be coordinated between CSS WG and WhatWG so that they are in sync or at least, any divergences are deliberate.
