### ISSUE TITLE
[css-scroll-snap] snap points on pseudo elements

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#488]
In http://www.w3.org/mid/C65090CE-632C-4606-93A9-80F358A15510@rivoal.net, @tabatkins and I argued about snap points and pseudo elements. This was not resolved.

>>>but I'd also be in favor of making it apply to all pseudo elements. As long as something has a box, we should have all we need to make things work.

>>Yeah, but it has to be tree-abiding, or else it's unpredictable *how
many* snap-points it generates.  This rules out ::first-letter and
::first-line, as well as all the highlight pseudos like
::spelling-error.  This is the same reasoning that rules out
background-image and friends - it's unpredictable how many boxes the
pseudo-element will generate, as it depends intimately on the markup
it's applying to, and so we avoid any property that depends on or
visually exposes the number of boxes.

> I'm not sure I follow. While these pseudos do weird things to the tree
(making it no longer a tree), how do they create more than one box? Or do
you mean the boxes generated by their children? Why would that matter
for a snappoint?

> Also we do apply background image to non tree-abiding pseudos:
http://jsbin.com/nowose/edit?html,css,output

> I mean, yes, the non tree abiding pseudos are weird in general, and
there's all sorts of issues with them, but could you clarify a bit
what causes problems with regards to snap-points?

**Comment by fantasai** [comment]
The reason we don't want to do this is because it is additional implementation and testing work for no clear use case. If at some point we introduce a pseudo-element that clearly needs to support scroll-snapping or there is a demand from the authoring community to add scroll-snapping to an existing pseudo-element, then we can add scroll-snapping to that specific pseudo-element.

We don't even blanket-whitelist backgrounds. We are not going to blanket-whitelist scroll-snapping.

**Comment by fantasai** [comment]
https://lists.w3.org/Archives/Public/www-style/2016Mar/0353.html

**Comment by frivoal** [comment]
Didn't remember that we had a resolution for this, sorry.
For the record, I'm OK with the conclusion.
