### ISSUE TITLE
[css-color-4] system colors when NOT forced-colors:active

### ISSUE THREAD

**Issue by BillGoldstein** [w3c/csswg-drafts#4883]
I've been doing some testing of system colors when NOT forced-colors:active, and have a few ideas:
1) UA's should use dark color (black-ish) for Canvas, and light color (white-ish) for CanvasText, when prefers-color-scheme:dark
2) UA's should use colors with sufficient contrast for LinkText, VisitedText, and ActiveText, lighter in dark mode, darker when not in dark mode

**Comment by AmeliaBR** [comment]
I agree, and was suprised to find that our [current spec text](https://drafts.csswg.org/css-color-4/#css-system-colors) for system colors only talks about forced color mode.  The system colors are also useful for light/dark theming.

Do you have more details about your test results? Which browsers are not updating the used values for their System Color keywords to match their default styles when dark mode is active?

**Comment by BillGoldstein** [comment]
Tested with Chromium, and Gecko (with an autoland build - it's been backed out for now).
Neither adjusted Canvas / CanvasText in dark mode.
Same for LinkText / VisitedText / ActiveText.  They have less than WCAG-specified contrast ratios even in light mode, but it's worse in dark mode.

**Comment by AmeliaBR** [comment]
Agenda+ to confirm that the intention is that system colors will adapt to the used color scheme, whether it is forced or not. And to find out if there are implementation obstacles to make this so.

Note that the resolution to https://github.com/w3c/csswg-drafts/issues/4608#issuecomment-578151377 implies that system color values will adjust to color scheme

I'd also want a resolution that User Agent stylesheets _should_ use system colors, so that an HTML file with a `<meta name="color-scheme" content="dark">` command is readable by default if CSS doesn't load.

We already have text about using [“legible” pairs of colors](https://drafts.csswg.org/css-color-4/#system-color-pairs) in the default browser/system color schemes, although I'd prefer a more explicit requirement for WCAG AA contrast, unless the colors are user-selected.

**Comment by BillGoldstein** [comment]
I'd suggest going even further to WCAG AAA contrast ratio if/when @media (prefers-contrast:high) is implemented.

**Comment by lilles** [comment]
The css-color-adjust spec[1]  says in a couple of places that system colors are affected by the used color-scheme:

Safari ships color-scheme dependent system colors. In Chrome it's currently behind the same runtime flag as for dark themed forms (--enable-blink-features=CSSColorSchemeUARendering).

[1] https://drafts.csswg.org/css-color-adjust-1/#preferred

**Comment by BillGoldstein** [comment]
I agree with AmeliaBR about the WCAG AA 4.5:1 contrast ratio requirement for legible pairs...as default.

Later, when implementing <https://drafts.csswg.org/mediaqueries-5/#prefers-contrast>:

when @prefers-contrast:high (or "increased") applies, use WCAG AAA 7:1 contrast ratio,
when @prefers-contrast:no-preference, keep using the WCAG AA 4.5:1 contrast ratio,
when @prefers-contrast:low applies, use WCAG's 3:1 minimum contrast ratio.
@prefers-contrast "extremely high" could use maximum possible contrast.

**Comment by svgeesus** [comment]
[Added WCAG AA contrast requirement for matching pairs when browser generated](https://github.com/w3c/csswg-drafts/commit/dd84ae811c37b2efda40295ec1b25a758813171e)

**Comment by svgeesus** [comment]
All three resolutions have [now been incorporated](https://drafts.csswg.org/css-color-4/#css-system-colors).
