### ISSUE TITLE
[css-values] Parsing "<integer> | <length>" or "<number> | <length>"

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#489]
From #460 I noticed that `tab-size`'s syntax is `<integer> | <length>`, and I was confused on how `0` should be handled in this case, since `0` is valid as both `<integer>` and `<length>`. It seems the same issue applies to `<number>`, which `line-height` uses.

I do not find the answer whether for whether `0` should be parsed as `<integer>` or `<length>` in this case from css-values spec. Am I missing something, or probably the spec should say something about this case?

cc @fantasai @tabatkins

**Comment by tabatkins** [comment]
It doesn't matter which it parses as; both end up with an identical effect and serialize the same way.

Tho, hm, I guess the Typed OM would want to make a distinction.  I'm inclined to have it parse as integer/number, and would be happy to clarify that as a general rule in V&U.

**Comment by upsuper** [comment]
It seems to me zero `<length>` is [serialized](https://drafts.csswg.org/cssom/#serializing-css-values) as `0px`, no?

**Comment by wargrey** [comment]
I define a CSS:Zero for 0 as a subtype of CSS:Integer in my engine which implemented in a typed language(There also is a CSS:Flzero for 0.0). Then I can easily handle these two special number types when a dimension type is required.

**Comment by fantasai** [comment]
Agenda+ to ask if we should add a general rule to V&U that these ambiguous cases parse as `<number>`/`<integer>`

**Comment by cdoublev** [comment]
I think `<length> && <number>` cannot match `0 1` if you do not give priority to `<length>` for matching `0`.

I noticed the ambiguity with `border-image-outset`, defined with `[ <length [0,∞]> | <number [0,∞]> ]{1,4}`. Its initial value is `0` but imo it should be `0px`, because if you set `border` to `1px` then `border-image-outset` to `0px`, `border` cannot serialize to `1px` because its reset-only sub-property `border-image-outset` is not declared with its initial value.

**Comment by dbaron** [comment]
I think the discussion the working group had related to the `|` combinator, which accepts exactly one of the alternatives.  I don't think it's relevant to the `&&` combinator or to the all-values-present case of the `||` combinator (since these combinators are [not dependent on order of the grammar](https://drafts.csswg.org/css-values-4/#component-combinators), from which you can infer that the parse-time handling of them is not greedy).

Or, to put it another way, when parsing `<length> && <number>` or `<length> || <number>` none of the values `0 1`, `1px 0`, `0 1px`, or `1 0` is ambiguous.  The first two have the `<length>` before the `<number>`, and the latter two have the `<number>` before the `<length>`.

However, the cases that are ambiguous, and thus affected by the resolution above, are parsing `0` as `<length> | <number>` or as `<length> || <number>`; the resolution above says it is parsed as a `<number>`.

**Comment by cdoublev** [comment]
Oh, you are right, backtracking should handle it. Thanks for the reply. 

CSS Value is not 100% precise on this custom priority.

> However, if a 0 could be parsed as either a `<number>` or a `<length>` in a property (such as line-height), it must parse as a `<number>`.

`|` combinator is not specified, and it can apply to `<integer> | <length>`, `<number> | <length-percentage>`, etc. Do you think it is worth opening a new issue?
