### ISSUE TITLE
[css-color][css-color-adjust] We should add sufficient system colors to fully implement the HTML UA stylesheet

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4924]
See <https://github.com/whatwg/html/issues/5426> for some more context. In that thread, @tomayac pointed out that link colors, because they're explictly defined to be `blue` and `purple` in the UA stylesheet, aren't being inverted when the UA is in a dark color scheme, making them very hard to read.

Obviously, [we have `linktext` and `visitedtext` system colors](https://drafts.csswg.org/css-color-4/#css-system-colors), so that particular issue should just be a matter of switching the UA stylesheet to using the system colors rather than explicitly naming them.

However, further discussion suggests that there are some colors in the UA stylesheet that aren't adequately addressed by system colors yet. If the UA stylesheet for plain HTML can't be done with system colors, we're probably missing some useful semantics, so we should make sure that the HTML stylesheet can be done purely in system colors.

**Comment by AmeliaBR** [comment]
Reviewing the other colors found in @zcorpan's [review](https://github.com/whatwg/html/issues/5426#issuecomment-607263527) of the suggested stylesheet…

- Standard foreground/background colors for a dialog should use the CanvasText/Canvas pair. Similarly, the default table border color should be CanvasText if there's a compat reason not to make it `currentColor`.

- Colors for `<mark>` would need to be defined. First instinct is to use highlight/highlightText, but that's incorrect — those are for dynamic user selections, not for highlighted phrases in the document.  (They could still map to the same colors in WHCM if necessary, but they're definitely not the same in the default UA stylesheets.)

- The default color of an `<hr>` should probably be the same default as a button border, but even in the [deprecated system colors](https://drafts.csswg.org/css-color-4/#css-system-colors) that isn't a single color, since that set of keywords defined separate colors for all the 3D lighting effects instead of defining a single color that then gets modified by the 3D `border-style`. So that would also need to be a new keyword.

So new keywords would be (something like):

- Mark
- MarkText
- ButtonBorder

(Alternatively, it may be acceptable to just use `ButtonFace` for `ButtonBorder`, and let the raised/inset border styles do all the adjustments.)


Related issue: #4883.

**Comment by tabatkins** [comment]
(This comment was started before @AmeliaBR posted theirs, so by the end I'm mostly just agreeing with them.)

The full list of colors used in the UA stylesheet:

```css
dialog { color: black; background: white; }
dialog::backdrop { background: rgba(0,0,0,0.1); }
:link { color: #0000EE; }
:visited { color: #551A8B; }
:link:active, :visited:active { color: #FF0000; }
mark { background: yellow; color: black; }
table /* lots of variations */ { border-color: black; }
hr { color: gray; }
```

* `dialog { color: black; background: white; }`: Since these are just repeating the assumption of what the main page is already doing, those should be replaceable with `canvas` and `canvastext`.
* `dialog::backdrop { background: rgba(0,0,0,0.1); }`: This one's harder. I doubt we want to provide this color directly. Really, it's just `color-adjust(canvastext alpha(.1))`, so I suppose we can just pretend that exists already? The UA stylesheet already does some "doesn't really exist" stuff anyway.
* `:link`, `:visited`, and `:active`: already done, via `linktext`, `visitedtext`, and `activetext`
* `mark { background: yellow; color: black; }`: probably needs something new; at *least* a new background (`accent`?), probably a full pair (`mark` and `marktext`?)
* `table { border-color: black; }`: should be doable with just `canvastext`
* `hr { color: gray; }`: as @AmeliaBR says, could probably be aligned with button borders, which need their own singular color anyway.

----

So yeah I agree with @AmeliaBR: let's add `mark`, `marktext`, and `buttonborder`. Bikeshedding of `mark` and `marktext` appreciated.

**Comment by tomayac** [comment]
> Bikeshedding of mark and marktext appreciated.

+1 for [`Mark` and `MarkText`](https://github.com/whatwg/html/issues/5426#issuecomment-607692490).

**Comment by tabatkins** [comment]
> table { border-color: black; }: should be doable with just canvastext

Just to call this out specifically in answer to Amelia's question, this *can't* be `currentcolor`, as the default table borders don't respond to `color` today. So it has to be `canvastext`.

**Comment by tabatkins** [comment]
Agenda+ to discuss the addition of `mark` and `marktext` colors, and whether we want to add a `buttonborder` or not.
