### ISSUE TITLE
[css-ui] outline-width and "outline-style: auto"

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#4925]
All browsers ignore `outline-width` when `outline-style` is `auto`. Examle:
```data:text/html,<style>div { outline: auto 10px; background: silver; width: 200px; height: 200px;}</style><div></div>```

The [spec talks about `outline-color`](https://drafts.csswg.org/css-ui/#typedef-outline-line-style):
> As such, this specification does not define how the outline-color is incorporated or used (if at all) when rendering auto style outlines.

BTW, Chromium and WebKit respect the `outline-color` while Firefox ignores it, in the case of `outline-style` is `auto`.

However it doesn't mention anything about `outline-width`. But all browsers ignore it when `outline-style` is `auto`.
Should we add something to the spec so `outline-width` is ignored with `outline-style: auto`? or is optional? or something else?

There was a bug report on the topic in Chromium: https://crbug.com/945181
About that bug the `outline-offset` thing is going to be fixed, but this issue is to have a separated discussion for `outline-width`.

I'm wondering if the spec should be very specific and mention which properties apply and which are ignored when you set `outline-style: auto`: `outline-color`, `outline-width` and `outline-offset`.
Also probably it should also be explicit about following or not border-radius in that case (see #4671).

**Comment by emilio** [comment]
If you use the native outline, how are you supposed to respect outline-color? The color of that outline in Firefox depends on the OS. Same for outline-width.

outline-offset is different though, you _can_ apply an offset to the native outline, it's just a matter of expanding the rect.

**Comment by AmeliaBR** [comment]
I'm the one who filed the original Chromium bug report.

It was an issue for me because I _used_ to be able to reliably improve the contrast and position of a focus outline in most browsers by setting the outline properties other than `outline-style`.  I specifically avoided setting `outline-style` because it overrides the browser's focus-visibility heuristics. (This would be less of an issue if [`:focus-visible` had better browser support](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#Browser_compatibility).)

Over the past few years, more browsers have switched from using standard CSS outlines to using these glowy default focus outlines which frequently fail contrast requirements, and which cannot reliably be modified by setting the individual sub-properties. Content that previously had useful focus outlines now is broken.

But… for whatever reasons, all the browsers are standardizing around these faded, WCAG non-compliant focus glow effects. So at the very least CSS should warn authors about it.

**Comment by emilio** [comment]
> I specifically avoided setting outline-style because it overrides the browser's focus-visibility heuristics.

Can you elaborate? I'm pretty sure this is not how it works on Firefox, but I'm curious about WebKit behavior here.

**Comment by AmeliaBR** [comment]
> Can you elaborate?

If I set a rule like 

```css
button:focus { outline: solid red 3px; }
```

it will get the solid outline regardless of whether focused by click or keyboard.  That has UX issues because for non-keyboard users it makes it look like clicking toggled a state change, which is why `:focus-visible` was introduced.

But if I use

```css
button:focus { outline-color: red; outline-width: 3px; }
```
then I don't change whether the outline appears or not, only what color & thickness it has when it is drawn.

Or at least, it used to work that way.

It still works that way for color in Chromium, but not for the other outline properties. It still works in Firefox for links and other things that use normal CSS outline, but doesn't work at all for buttons or some inputs. (These results on Windows, some of this may be platform dependent.)

[Test code pen](https://codepen.io/AmeliaBR/pen/56987dfcb5fee580148c6ad2972074fe)

Again, this specific use case is better addressed in the long term with `:focus-visible`. But CSS should definitely be clearer about how `outline-style: auto` can override some or all of the other properties (and that there is huge cross-browser inconsistency in which and when).

**Comment by frivoal** [comment]
Given the expectation that UAs can use native outlines for outline-style:auto, I think it would be appropriate for the spec to say that they may ignore outline-width as well.

This is certainly not a should, as I don't want to express that that ignoring it is good, but honoring it may be impossible, so allowing it (or expecting spec violations) seems unavoidable.
