### ISSUE TITLE
[css-ruby] Ruby offset

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#4932]
From a clreq [meeting](https://www.w3.org/2020/04/08-clreq-minutes.html#t09):

> ... in the current css-ruby draft, it seems that the distance between ruby text and base text cannot be adjusted

I think we need a property for setting the offset of ruby from its default position, because sometimes the default position doesn't look good enough.

**Comment by nigelmegitt** [comment]
TTWG may be interested in this - see w3c/ttml3#8 for part of the history: ruby offset was included in a WD of TTML2 but removed before CR, in part due to lack of CSS implementation. The removed spec text can be found at https://www.w3.org/TR/2017/WD-ttml2-20170630/#style-attribute-rubyOffset 

CC @skynavga @cconcolato @palemieux

**Comment by macnmm** [comment]
If it were possible for the default position of the ruby to have ruby embox bottom touch the embox top of the base text, this feature request would be unnecessary. As it is now, it is difficult to control placement via Latin font metrics to get the correct effect.

**Comment by frivoal** [comment]
There is no dedicated ruby property, as offsetting ruby can already be done with margins (or paddings, or even borders):

https://jsbin.com/nunuqey/edit?html,css,output (view in Firefox, other browsers' ruby implementation are insufficient to show this).

[By spec](https://drafts.csswg.org/css-ruby-1/#ruby-layout), the (groups of) annotations are supposed to be stacked immediately against the (groups of) bases, margin-box against margin-box, (which is why margin/border/padding on bases or annotations can be used as offsets).

That said, margin/border/padding are added to the content area, but the content area of inline boxes is currently not defined and is implementation dependent. That part of the box model is know to be weak (see the second note in [css-inline section 3.3.1](https://drafts.csswg.org/css-inline/#leading)), and needs more work. Maybe some switches are needed to control what the content area of an inline is in general, maybe some are needed for ruby specifically, or maybe we just need to agree on what the default is. Either way, that's separate from the need for a ruby offset, which we do have in the form of margins (or paddings, or borders).

**Comment by frivoal** [comment]
@xfq About to close this issue, please confirm if the resolution is satisfactory.

**Comment by xfq** [comment]
Looks good to me. Thank you!
