### ISSUE TITLE
[css-ruby] Be more specific about the box model of base/annotation container boxes

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4937]
(this issue is similar to, but different from #4935 and #4936)

[Section 3](https://drafts.csswg.org/css-ruby-1/#ruby-layout) tells us that:
* > Each ruby base container is sized and positioned to contain exactly all of its ruby bases’ margin boxes.
* > Each ruby annotation container is sized and positioned to contain exactly all of its ruby annotations’ margin boxes

Presumably that means "**The content area of** each ruby base/annotation container…" (and then any borders, margins, and padding go outside of that). This should be clarified.

The same section 3 also states:
> Ruby annotation containers are stacked outward over or under their corresponding ruby base container, without any intervening space.

This could be interpreted to mean either:
* **the content box of** ruby annotation containers are stacked outward over or under **the content box of** their corresponding ruby base container, **ignoring any border, margin, or padding,** without any intervening space.
* **the margin box of** ruby annotation containers are stacked outward over or under **the margin box of** their corresponding ruby base container, without any intervening space.

[Section 3.2](https://drafts.csswg.org/css-ruby-1/#box-style) gives a hint:

> […] the UA is not required to support any of the box properties (borders, margins, padding), any of the background properties or outline properties, or any other property that illustrates the bounds of the box on ruby base container boxes, ruby annotation container boxes […]

Given that, I suspect the former (content box) interpretation is indented, otherwise whether borders, margins, and padding on base container boxes and annotation container boxes affect layout out nor would be implementation dependent, which would be bad. But this should be made explicit.

**Comment by frivoal** [comment]
Cursory testing shows that the content box interpretation is how it's implemented in Firefox (other browsers not relevant, as they don't support the ruby box model at all yet).

**Comment by frivoal** [comment]
Made a PR to implement that clarification: https://github.com/w3c/csswg-drafts/pull/4938

**Comment by frivoal** [comment]
Created https://github.com/web-platform-tests/wpt/pull/22843 to support the above proposal should we adopt it, and to check (Firefox's) implementation more carefully, expecting it to match.

As per the proposal above, Firefox ignores the block-axis margin / border / padding of base container boxes and annotation container boxes when it comes to stacking them (and for all other purposes as well as far as I can tell, but I was only testing the stacking).

It also ignores the inline border and inline padding on base container boxes and annotation container boxes, as well as the inline margin on annotation container boxes, but curiously, it does not ignore the margin on base container boxes. I suspect that's an accident, but if not, I'd be very curious about the logic behind that. @upsuper ?

**Comment by upsuper** [comment]
> Firefox ignores the block-axis margin / border / padding of base container boxes and annotation container boxes when it comes to stacking them (and for all other purposes as well as far as I can tell, but I was only testing the stacking).

For border and padding, yes. Actually for convenience it's done one step further that `border` and `padding` are all computed to zero for ruby base / annotation containers.

But I think this should be kept as implementation details for now, and shouldn't be specified. And my feeling is that it makes more sense to say that they should be stacked based on border box (or even margin box) instead. One argument against using margin box IIRC is that inline elements are not supposed to have margin on block direction, though.

> but curiously, it does not ignore the margin on base container boxes. I suspect that's an accident,

That doesn't match my read of the [code](https://searchfox.org/mozilla-central/rev/9120151ddb35f2d4c37bfe613a54a4f10a9a3dc5/layout/generic/nsRubyFrame.cpp#267-282), the [discussion(https://bugzilla.mozilla.org/show_bug.cgi?id=1055667#c6) on the implementing ticket, as well as my testing.

Could you provide your test code for this?

However... during testing I noticed that Firefox does respect the block margins on ruby base box and ruby text box, which doesn't seem to be consistent with the idea that block margins are ignored on inline elements. I think this is a [recent](https://bugzilla.mozilla.org/show_bug.cgi?id=1565681) regression...

But I think that also raise a question on what does margin box really means for ruby base box and ruby text box. They otherwise behave like inline element, so should their block margin counts in their margin box?

**Comment by frivoal** [comment]
> But I think this should be kept as implementation details

If it results in a different layout, it's not implementation details.

>> but curiously, it does not ignore the inline margin on base container boxes. I suspect that's an accident,

> That doesn't match my read of the code, the discussion on the implementing ticket, as well as my testing. Could you provide your test code for this?

See the 6th and 7th base/annotation pairs in the https://github.com/web-platform-tests/wpt/pull/22843

> But I think that also raise a question on what does margin box really means for ruby base box and ruby text box. They otherwise behave like inline element, so should their block margin counts in their margin box?

I think it should:
* The definition is clear: The spec says the base/annotation container box should wrap around the base/annotation's margin box, and the margin box is defined to include the margin in all directions
* The definition is useful: This gives us the ability to control the distance between the bases and the annotations, which is an important feature.

It's true that it makes them not entirely the same as inline boxes, but even if they have a number of similarities, they're not entirely the same anyway.

**Comment by upsuper** [comment]
> > But I think this should be kept as implementation details
> 
> If it results in a different layout, it's not implementation details.

OK, wrong word. I mean leaving whether implementation needs to support border / padding of ruby base / text container unspecified.

> > > but curiously, it does not ignore the inline margin on base container boxes. I suspect that's an accident,
> 
> > That doesn't match my read of the code, the discussion on the implementing ticket, as well as my testing. Could you provide your test code for this?
> 
> See the 6th and 7th base/annotation pairs in the [web-platform-tests/wpt#22843](https://github.com/web-platform-tests/wpt/pull/22843)

Oops, I misread your comment, sorry. You actually mentioned inline margin here.

So, yes, inline margin of ruby base containers is respected, because they are considered normal inline elements in the line flow, thus their inline margin is respected alike. But ruby text containers are not inline elements, they are out of the flow, and just attached to the base containers.

I don't think it's impossible to take the inline margin of ruby text container into account, but doing so would likely make the implementation more complicated (although not unmanageable), and I don't see it useful.

Regarding the block margin of ruby base container, though...

> > But I think that also raise a question on what does margin box really means for ruby base box and ruby text box. They otherwise behave like inline element, so should their block margin counts in their margin box?
> 
> I think it should:
> * The definition is clear: The spec says the base/annotation container box should wrap around the base/annotation's margin box, and the margin box is defined to include the margin in all directions
> * The definition is useful: This gives us the ability to control the distance between the bases and the annotations, which is an important feature.
> 
> It's true that it makes them not entirely the same as inline boxes, but even if they have a number of similarities, they're not entirely the same anyway.

if we agree on that ruby base / text container should have their content area wrapping the block margin of ruby base / text box, then I think it's more consistent to actually take block margin of the containers into account. This is not hard to implement. It was just that we didn't consider this as the right behavior.

But we may need to take some extra caution, as expanding the block size of ruby level containers would affect line height. It might not really be a problem, though.

**Comment by frivoal** [comment]
> if we agree on that ruby base / text container should have their content area wrapping the block margin of ruby base / text box, then I think it's more consistent to actually take block margin of the containers into account. This is not hard to implement. It was just that we didn't consider this as the right behavior.

To me, doing it on the base / annotations is good because it's useful, both in the inline direction and the block direction

For the base containers / annotations containers, these boxes seem mostly useful to me in the abstract sense, to figure out relationships between things, but you don't really need them as boxes in a visual sense, so I'd rather than no margin/padding/border apply at all, in either axis, and keep them as invisible glue. But if we make them more normal, and have M/B/P work in one axis, I'd rather be consistent and have them work in both axes.

> I mean leaving whether implementation needs to support border / padding of ruby base / text container unspecified.

I'd rather not, because controlling spacing between bases and annotations is a thing people want to do, and if it is possible in some browsers to do that with m/b/p on base containers or annotation containers, then sooner or later people will do it, and everybody will have to copy that behavior. So I'd rather state upfront whether they affect layout or not.

If they don't affect layout, whether you can still specify them or not and affect the painting of the background seems less important, and I'd be OK with leaving that open (as section 3.2 does).

**Comment by upsuper** [comment]
> For the base containers / annotations containers, these boxes seem mostly useful to me in the abstract sense, to figure out relationships between things, but you don't really need them as boxes in a visual sense, so I'd rather than no margin/padding/border apply at all, in either axis, and keep them as invisible glue.

I think this makes sense, and should generally simplify the implementation. I can update Firefox's implementation to also ignore the margin on level containers if the consensus is to going this way.
