### ISSUE TITLE
[css-contain] editorial: Paint Containment description is incomprehensible

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4946]
ISSUE 1:
The [Paint Containment](https://drafts.csswg.org/css-contain/#containment-paint) section says (1st bullet):
> The contents of the element including both the paint of the descendants and their geometry ...

The term "_the paint of the descendants_" is unfamiliar to me and I can't find any definition of it in any CSS spec.
The term "_geometry_" is unfamiliar to me and I can't find any definition of it in any CSS spec.
 (I really have no clue what you mean by either of those in this context.)

Please provide precise definitions of what you mean by these terms, or preferably, use well-known CSS terms that are defined in other specifications such as: _scrollable overflow_, _ink overflow_, _content-box size_, _border-box size_ etc... (please also linkify at least the first use of such terms for extra clarity). Thanks!

ISSUE 2:
The last sentence under the 1st bullet reads: "_This is as if `overflow: visible` was changed to `overflow: clip` at used value._". What does "this" refer to in that sentence? Is it the whole paragraph, or just the preceding sentence, or perhaps just the first sentence?
The only interpretation that makes sense to me is that it refers to the first sentence, since a scrolling mechanism is never created for `overflow:clip`. If so, then it seems better to insert this sentence directly after the first sentence. Or perhaps just re-write the first sentence with "`overflow:visible` behaves as `overflow:clip`" included in some way. (Again, it's better to use a familiar term like "behaves as" than trying to mint your own version of it.)

**Comment by frivoal** [comment]
Issue 1:

I think we can replace "the paint of the descendants" with "any ink or scrollable overflow" without altering the effect. I think the original intent of "the paint" was to talk about things that would be ink or scrollable overflow if they overflowed, but in this case we only care about what happens to that when it does overflow, so we can talk about the overflow using established terminology instead.

* I am less sure about what "and their geometry" was supposed to be about. @tabatkins ? Maybe it is supposed to be about was outlines (and possible other things like outlines): since outlines are pretty flexible about what they can be around, the "geometry" of anything that pokes out of the containing box might be taken into account, but this was trying to say that it must not be. If that's that, maybe it should be moved into a separate and clearer bullet point. If it's something else, what?


Issue 2:
It refers to the whole paragraph: it only behaves as `overflow: clip` if `overflow` was otherwise `visible`. If it was some other value, it says unchanged. Hence the "does not include the creation of any mechanism… nor does it inhibit…".

How about rephrasing the note into
> The behavior is described in this paragraph is equivalent to changing `overflow:visible` into `overflow:clip` at used value time, while leaving other values of `overflow` unchanged.

**Comment by tabatkins** [comment]
> I am less sure about what "and their geometry" was supposed to be about.

I'm referring to layout overflow.

**Comment by tabatkins** [comment]
Ugh, scrollable overflow, whatever. Overflow that causes scrollbars to happen.

**Comment by frivoal** [comment]
Issue1:

> The contents of the element including both the paint of the descendants and their geometry 

becomes

> The contents of the element including any ink or scrollable overflow

----

Issue 2:

> This is as if overflow: visible was changed to overflow: clip at used value.

becomes

> The behavior is described in this paragraph is equivalent to changing overflow:visible into overflow:clip at used value time, while leaving other values of overflow unchanged.

----

Ok for everyone?

**Comment by MatsPalmgren** [comment]
Issue 1: @tabatkins said "scrollable overflow", you said "ink or scrollable overflow". It seems you disagree?
If you want `visible` to behave as `clip` then it should be the latter since [CSS Overflow](https://drafts.csswg.org/css-overflow-3/#overflow-properties) says that `overflow-x/y` also clips ink overflow.


Issue 2: sounds good to me if you change all instances of "overflow" to "overflow-x/y" in that sentence, so that it's clear also when just one is `visible`.

**Comment by tabatkins** [comment]
> @tabatkins said "scrollable overflow", you said "ink or scrollable overflow". It seems you disagree?

No, I was explaining "geometry" as scrollable overflow. Florian is replacing the whole "paint and geometry" reference, which is indeed both ink and scrollable overflow. No disagreement.
