### ISSUE TITLE
[css-values-4] Ratio of `0/0`?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4954]
So, the old `<ratio>`, since it only allowed integers, could meaningfully restrict its values to "greater than zero", so all ratios you could write were meaningful.

Now that we've relaxed it to `<number>`, we can't do that - can't do open ranges. So 0 is allowed.

And mostly that's fine! A ratio of `0/1` is just infinitely tall; a ratio of `1/0` is infinitely wide; CSS is okay with infinities. The "division results" are well-defined too - 0 and infinity, respectively.

But what about `0/0`? We can't reject this at parse-time, since a calc() might be hiding a 0. But it definitely doesn't have a meaning; the division result is NaN.

Two possibilities I see:

1. Define that it produces an "invalid ratio", and places that take `<ratio>` have to define what that means. The 'aspect-ratio' property would define that it doesn't give an aspect ratio (same as "none"); the (aspect-ratio) MQs would define that it always fails to match.

2. Make it act the same as `calc(0/0)`: it produces a NaN, which is censored into an infinity, so it's the same as saying `1/0` for the ratio.

I'm mildly leaning toward option 2. It's more consistent with `0/0` in general, and it means we don't need to ensure that every place that uses `<ratio>` defines what an "invalid ratio" does.

**Comment by tabatkins** [comment]
Never mind, I'm *strongly* in favor of option 2 actually; it ensures that `aspect-ratio: calc(X/Y);` and `aspect-ratio: X/Y;` have identical behavior in *all* cases.

**Comment by AmeliaBR** [comment]
Zero/infinite values were discussed https://github.com/w3c/csswg-drafts/issues/3757#issuecomment-525845920. My comment there mostly agrees with you above, although I seem to have skipped over the `aspect-ratio: 0/0` issue. I'd personally prefer to treat that as invalid = no aspect ratio defined.

See also https://github.com/w3c/csswg-drafts/issues/4572, which came up when I was searching for the other discussion & is probably worth another look — when taking the aspect ratio from width/height attributes, do you ignore a zero value? Unlike the `aspect-ratio` property, here we have actual browser behavior to compare (though I doubt it would be a strong web compat issue to change, since it is kind of an extreme edge case).

**Comment by zjopy** [comment]
Might want to delete the reference in [css-values-4#ratio](https://drafts.csswg.org/css-values-4/#ratios) since this issue is closed?

**Comment by fantasai** [comment]
Not sure Tab agreeing with himself but disagreeing with Amelia qualifies as an obvious bugfix. :) Also related is https://github.com/w3c/csswg-drafts/issues/5557 which was raised by @cbiesinger  so flagging for WG discussion.

**Comment by LeaVerou** [comment]
First, I agree it should be the same as `calc(0/0)`. Anything else would cause confusion.
I don't understand the sentence "it produces a NaN, which is censored into an infinity". Mathematically, 0/0 does not tend to infinity and is an indeterminate form.
It seems more reasonable that it would be invalid at computed value time, or something along these lines.

**Comment by tabatkins** [comment]
Fixed in 84a573d49
