### ISSUE TITLE
[css-cascade] What are the proper "levels" for managing Cascade Layers?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#4969]
This is in relation to #4470 custom-origin proposal, and [Cascade 5](https://drafts.csswg.org/css-cascade-5/#at-layer).

There are several (non-exclusive) ways the feature could be implemented and managed by authors, at different levels. (Any new syntax here is for demo purposes, not a final proposal):

1. Entire files, via html (e.g. `<link>` & `<style>`)
2. Entire files, via css rules (e.g. CSS `@import`)
3. One or more selector blocks, via css conditionals (e.g. `@origin`)
4. Individual declarations, via flags (e.g. `!<origin>`)

If custom origins are managed only by the html file:

- All origins for a page are clearly visible in one location
- Custom origins are a way of *using* CSS, rather than part of the CSS
- Page authors have full control of the origins defined, and what CSS belongs in what origin
- There is no need to handle “nested” origins from different sources

I think this could cover the main use-cases (`Reset < Design System < Overrides`, `Reset < Defaults < Patterns < Layouts < Components`, `CMS Core < CMS Extend < Base Theme < Site Styles`, `Old Styles < New Styles`). Those layers can often be divided cleanly into files. 

One downside might be a performance hit from multiple links? It also ignores inline style attributes, which would either need a default relationship to custom origins, or a unique syntax.

Options 2-4, would support the same use-cases without enforcing any particular code organization or file-splitting. Overrides could be written directly next to the code they override. But the distributed approach makes things more complicated:

If custom origins are defined anywhere and shared globally, then an author would have to keep all possible origins in mind while working. If a library like Bootstrap decides to use 6 origins internally, you’ll need an origin-7 in order to override that. That doesn't feel manageable, and is where most concerns have been raised (the "`z-index` wars" comparison).

On the other hand, it might be resolved by allowing custom origins to be nested, so that the final link/import would retain full control over stacking. You could import hypothetical `bootstrap.css` with a file-level origin of 0, and any internal origin of 6 becomes 0.6 in context. This avoids escalation across CSS documents.

This also opens up some new use-cases – similar to the proposed `!default` – for defining component properties that should accept values from a lower-origin (e.g. "theme"), or using custom origins inside a style attribute. (These use-cases are currently handled by custom properties in Shadow DOM and elsewhere).

ToDo: 
- Flesh out use-case details for each level?
- Compare to use of custom-properties for explicitly "defaulting" values?

**Comment by tabatkins** [comment]
Manually capturing an important point of @fantasai's: we should design with the assumption that this is applied at the file level, because we definitely need to solve that and it'll be kinda tricky. Controlling origins *within* a file with at-rules is comparatively simpler; whatever mechanics we work out for between-file handling should trivially translate to within-file.

**Comment by mirisuzanne** [comment]
I also think there's something to be said for "nested" origins being *simpler* for authors – because of the potential for modularity. The ability to flatten origins when I consume them, means I *don't* need to maintain the full picture in my mind at once.

**Comment by AmeliaBR** [comment]
From the discussion, today, I think it's worth listing out our use cases / horror cases & work out requirements from them.

Some examples (which we can debate about how important they are):

Use case:
3rd party library ships both essential styles for components (e.g., show/hide), and also default theming styles. They want to make it easy for authors to declare styles that override the themes, but not the essentials.

Use case:
Web page author is importing/linking multiple 3rd-party stylesheets (resets, components, basic themes), and wants to organize them by priority without needing to edit the CSS content of those files.

Use case:
A website build system that concatenates multiple stylesheets for portability/performance reasons but still wants to preserve the custom origin feature.

Horror case:
Multiple 3rd-party components declare origins using some sort of global namespace that conflicts in a way the website author can't control.

**Comment by chrishtr** [comment]
I'd add one more use case: polyfilling for browsers that don't yet support cascade layers.

It seems to me that it would suffice to define exactly one new layer, and define it via an `@baselayer` @ rule. This would sit in the cascade between the user agent rules and all regular developer stylesheet rules. Within a style sheet, it would look like:

```
@baselayer {
  .foo { position: relative !important } /* Can't be overridden by regular rules not in @baselayer */
  :where(.foo) { background: blue } /* Can be overridden by regular rules with non-zero specificity */
}

.foo { position: absolute !important } /* Has no effect due to above */
.foo{ background: red } /* Changes blue to red */
```

The second layer would be just the usual CSS layer for a developer's style sheet.

Referring back to @AmeliaBR's use cases:

* *3rd party library with essential and default styles*: this would work by having the library put essential styles in the `@baselayer` with `!important` and default theming styles without it and zero specificity. The page that uses the 3rd-party library would then add rules as desired to override theming styles.

* *Importing/linking multiple 3rd-party stylesheets (resets, components, basic themes), and wants to organize them by priority*: can't be done without coordination or pre-processing tools. IMO this is ok not to solve, since solving it may introduce a lot of complexity or lead to the problem of the 4th use case.

* *Concatenating multiple stylesheets*: works fine because order of rules doesn't matter and multiple `@baselayer`s can be concatenated together.

* *Multiple 3rd-party components declare origins with conflicts*: can't happen because there is no way to define two layers.

* *Polyfilling*: can be done with an approach like the following:

1. A polyfill would insert a `@baselayer {}` stylesheet in front of any other stylesheets. This should be doable in SSR and lazy-loaded environments.
2. The `@base-layer` selectors would have to be at the lowest available specificity, e.g. using `:where`.
2.a. Alternatively, since it's not likely that most use cases can take advantage of tag-name selectors, it means that as much as possible `@baselayer` has to rely on selectors that consist of a single class or a single attribute.
2.b. In few use cases such as `.mycheckbox[checked]` a more specific selector could be warranted, b/c a user would be naturally expected to use a similar or higher specificity for overriding.
2.c. Perhaps a polyfill can warn a developer when a more complicated selector is used in the `@baselayer`, which would make it harder to override in the user stylesheet. And then it can be left up to the developer to decide if the risk of using a non-polyfillable scenario is worth it.

@dvoytenko

**Comment by tabatkins** [comment]
Our previous discussions on this suggested that we needed more than a single additional layer, but that we could generally solve each individual use-case with *three* built-in layers - "defaults", "normal", and "override" (along with their inverted !important versions). 

I think we also definitely still need to address the "scoping" of 3rd-party stuff, so they can use layers for their own purposes without necessarily having an effect on your layer usage. The important thing about providing predefined layers is that it allows us to reasonably do *non*-scoped stuff without complicated aliasing mechanisms (which custom names/ordering would require).

**Comment by tabatkins** [comment]
> (along with their inverted !important versions).

I keep doing this in my head, but per Emilio's concern about doing layers as specificity vs origins, I don't actually quite mean this. ^_^  (That is, I'm pretty sure layers need to be done as a new specificity value, stronger than all the existing ones.)

It *might* be useful to have layers invert their ordering in !important, tho, so "base" styles can put themselves in the highest position when necessary.

**Comment by mirisuzanne** [comment]
> 1. Entire files, via html (e.g. <link> & <style>)
> 2. Entire files, via css rules (e.g. CSS @import)
> 3. One or more selector blocks, via css conditionals (e.g. @origin)
> 4. Individual declarations, via flags (e.g. !<origin>)

The current [Cascade 5 draft](https://drafts.csswg.org/css-cascade-5/) allows nesting layers, using an `@layer` rule for conditional code-blocks and stylesheet imports. My current thinking:

1. (link/style attribute) **TBD/yes**: I think a layer attribute would be useful to avoid chaining imports
2. (import) **yes**: `@layer url();` (syntax marked for discussion)
3. (at-rule) **yes**: `@layer {}` 
4. (!flag) **TBD/no**: I don't think it makes sense at this point to attempt any sort of arbitrary `!layer` flag on individual properties, but a simpler binary `!default` has been proposed elsewhere, and might be interesting

**Comment by mirisuzanne** [comment]
Moved the remaining question into a new issue, and closing this general question as resolved by the spec.
