### ISSUE TITLE
[css-ruby] effect of `line-height` on nested ruby containers

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4986]
A follow up question to https://github.com/w3c/csswg-drafts/issues/4979:

What is the effect of `line-height` on a *nested* ruby container. As far as the effect on its insides, there should be no difference compared to a non-nested ruby container, and that should do nothing (assuming we resolve that way in 4979). What about its effects towards the outside. I can see two possibilities:
* There is no effect
* it does nothing to the outer ruby, but it does affect the line that it is in, in the same way any (possibly nested) inline box would.

**Comment by upsuper** [comment]
There are two cases of nested ruby container: it can be nested within the ruby base, or in ruby annotation. I suppose you are talking about the former.

My understanding is that for ruby container inside another ruby base, such ruby container behaves just like a normal inline element that contributes its line height to the line. When it's nested inside ruby annotation, on the other hand, have no effect, because ruby annotation container doesn't care about line height.
