### ISSUE TITLE
[css-position] physical inset properties

### ISSUE THREAD

**Issue by jonathantneal** [w3c/csswg-drafts#5005]
The [CSS Logical Properties and Values specification](https://drafts.csswg.org/css-logical-1/#position-properties) defines an `inset` shorthand property that sets physical values. This seems helpful because it follows consistent expectations with other directional shorthands.

It may also be helpful to CSS authors if the other physical inset properties were represented with `inset-*` prefixes for parity — `inset-top`, `inset-right`, `inset-bottom`, and `inset-left`.

```pcss
inset-top:    auto | <length-percentage>

inset-right:  auto | <length-percentage>

inset-bottom: auto | <length-percentage>

inset-left:   auto | <length-percentage>
```

A drawback to this proposal may be the lack of new functionality this syntactical sugar provides. CSS already has `top`, `right`, `bottom`, and `left` properties, and they are shorter in length.

This request is focused on providing familiarity to CSS authors by having both logical and physical `inset-*` properties. This request is intended to be thematically similar to the shorthand `gap` property and support for trailing commas.

**Comment by tabatkins** [comment]
While I agree it would have been nice to have all of them under a prefix originally, I doubt that adding an alias at this point is worthwhile.  We only add property aliases in situations where the original property name is *bad* and we'd like to replace it; t/r/b/l are overall fine. They're also very common, meaning that adding the alias has a decent chance of causing confusion rather than reducing confusion.

**Comment by mirisuzanne** [comment]
I understand not wanting to add new aliases for perfectly good properties – but I think this case is complicated by the fact that there _are_ `inset-*` properties, and `inset` is _not a shorthand for those properties_. I'm not sure if aliases are the only option to address that, but I agree with @jonathantneal that the current names are misleading. Not only do `inset` and t/r/b/l lack a clear relationship, but `inset` implies a clear relationship _to the wrong longhands_. That's very likely to cause confusion.

**Comment by heycam** [comment]
I tend to agree with Tab that, while it may be slightly surprising that the constituent physical longhands are not named `inset-{top,bottom,right,left}`, that it's not strange enough to justify adding the aliases.

For what it's worth, the `inset` shorthand can set the `inset-*` logical properties, by using the `logical` keyword in the shorthand value (or whatever syntax #1282 ends up with).

**Comment by Crissov** [comment]
One could argue that since there are now logical (medial) shorthands `inset-block` and `inset-inline`, we should also have physical shorthands `inset-vertical` or `inset-y` (for `top` and `bottom`) and `inset-horizontal` or `inset-x` (for `right` and `left`), but this would also apply to other TRBL properties.

By the way, the values are specified as `<'top'>`, which resolves to `auto | <length-percentage>`. While technically correct, it is a bit confusing to read. Can we get an explicit `<inset>`?

**Comment by tabatkins** [comment]
Note added in dac155905
