### ISSUE TITLE
[css-display-3]: 'display: contents' link break

### ISSUE THREAD

**Issue by Jiang-Xuan** [w3c/csswg-drafts#5007]
![image](https://user-images.githubusercontent.com/13357301/80327172-ccfa7400-886d-11ea-8e40-b1ba597a0092.png)

Here should be a link 😁

**Comment by Loirooriol** [comment]
The problem seems that both `display: none` and `display: contents` link to https://drafts.csswg.org/css-display-3/#propdef-display

Then, when bikeshed compiles the spec, if it notices that a paragraph has too references to the same term, it won't linkify them all (or something like that).

I guess that `display: none` should actually link to https://drafts.csswg.org/css-display-3/#valdef-display-none and `display: contents` should link to https://drafts.csswg.org/css-display-3/#valdef-display-contents

**Comment by Jiang-Xuan** [comment]
@Loirooriol Agree, but what is the bikeshed🧐

**Comment by frivoal** [comment]
> what is the bikeshed🧐

Bikeshed is the document preprocessor used to write the specifications: https://tabatkins.github.io/bikeshed/

**Comment by Jiang-Xuan** [comment]
@frivoal thanks 🙏

@fantasai Maybe we can update the spec according to the @Loirooriol comment.

**Comment by tabatkins** [comment]
I can't *generally* tell what value to link to in a form like `''foo: bar''`. Sure, simple cases like this are tractable, but we do a lot of things like `''width: 5px;``, and the best I can do in an automated fashion is link to 'width' there. (Even for cases that are just keywords, if the keywords are defined only as part of a larger grammar clause, I can't autolink them from the smaller use.)

The problem is that we didn't want to overwhelm a paragraph with multiple links to the same term, but also didn't want to have to remember to only link a term once per paragraph (and keep that correct as things are edited or moved around). Our original idea was just to make the subsequent links much subtler, but the a11y group feedback kiboshed that with their insistence that links *must* be obviously distinguished from the surrounding text. So instead we just remove the subsequent links entirely, which is worse than keeping them in.

We just need to ignore that a11y feedback and instead style the subsequent links more subtly, is all.

**Comment by Jiang-Xuan** [comment]
Thank for your explanation. Although I didn't fully understand it, I knew it was done intentionally.
