### ISSUE TITLE
[css-sizing] Make flex % row-gap resolve to 0 when height is indefinite (only flex, not grid)

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#5081]
(The terminology here assumes horizontal writing mode)

% row-gaps in an indefinite-height container are specified to resolve against the container's intrinsic height. This currently applies to both flex and grid.

For grid, this can be used with % grid tracks to make a sensible layout. E.g.

height: 33% row track
height: 33% row-gap
height: 33% row track

This makes the gap and rows the same height and the grid container does not have overflow. There's a nice match here: % tracks and % gaps resolve off the same height.

The same is not true for flex. For example,

```html
<div style="display: flex; flex-flow: column; height: auto; row-gap: 33%">
  <div class="flexitem" style="height:33%">some subtree</div>
  <div class="flexitem" style="height:33%">another subtree</div>
</div>
```

The items and gaps will not have the same size; there is no match like grid has. Items' % heights in an indefinite height flexbox resolve to 0. Further, the flex container will have overflow. In flex, using % row-gaps as specified now makes the flex container always have overflow.

This illuminates an inconsistency between flex and grid. Grid gaps resolve the same as the things they add space between: tracks. Flex gaps do not resolve the same as anything, they are their own beast.

Let's fix the inconsistency by prescribing that %gaps are resolved the same as their ~siblings: items for flex and tracks for grid. This would result in no changed grid behavior, because grid already does the right thing. There would also be no changed flex col-gap behavior. The only change is % flex row gaps would resolve to 0 when the flexbox has an indefinite height.

I don't know where this change would live. Maybe https://drafts.csswg.org/css-align/#column-row-gap. Maybe the first bullet point after the table in https://drafts.csswg.org/css-sizing-3/#min-percentage-contribution ?

/cc @chrishtr

**Comment by tabatkins** [comment]
Strong agree here. The original grid-gap behavior ended up resolving to satisfy the principles of (a) gaps acting like empty tracks as much as possible, and (b) row and column gaps acting identically. Since % tracks behave as auto during intrinsic sizing of the container, then resolve their %s against the container's size, gaps do the same thing.

We then applied a *different* consistency argument to transfer that behavior over to flex gaps, but that ends up meaning that we *break* the original consistency arguments! As you say, flex items with a % main size, when resolved against an indefinite flex container, do *not* resolve; they just behave as auto the whole time. So if we think of flex gaps as being empty items, a % gap should collapse to zero (aka the auto size for an empty item).  And tho we can't compare cross-axis gaps with anything (because you can't explicitly size flex lines), we can apply the "consistent behavior in both axises" argument to say that % gaps in the cross axis will also resolve to 0 if the flex container's cross size is indefinite.

Agenda+ to discuss this at the next call.

**Comment by mrego** [comment]
BTW, the very same argument would apply for column-gap in flexbox too, resolving percentage gaps there is always causing overflow:
```html
<div style="display: inline-flex; gap: 50%; border: solid thick;">
  <div style="background: magenta;">foo</div>
  <div style="background: cyan;">bar</div>
</div>
```

Anyway now going to the main point of my comment, IMHO we should change this for flex and grid at the same time. More specifically flex row gutters, grid row gutters and grid row tracks should resolve to auto when height is indefinite.

Usually percentages in the row axis behave like that and we added this different behavior for grid layout and flex in the past, and it seems it's not something really useful and it causes issues on the implementations as it's kind of tricky.

To give some historical background on the topic, we discussed about this in a bunch of places in the past but specifically these 2 issues:
* https://github.com/w3c/csswg-drafts/issues/509
* https://github.com/w3c/csswg-drafts/issues/1921

Some interesting things happened on summer 2018:
* [Firefox implemented the new behavior for grid row gutters only (not for grid row tracks)](https://hg.mozilla.org/mozilla-central/rev/be1b4c042170)
* [Firefox added support for flex gutters implementing this for flex row gutters too](https://hg.mozilla.org/mozilla-central/rev/347512fd214e)
* [Chromium and WebKit implemented it for grid row gutters and grid row tracks](https://blogs.igalia.com/mrego/2018/08/10/changes-on-css-grid-layout-in-percentages-and-indefinite-height/)

Since then there have been no changes in support regarding this, until very recently when Chromium added support fro flex gutters but without implementing this behavior (this hasn't been shipped yet).

This means that Edge never supported this for grid row gutters neither grid row tracks, until it started to use Chromium. And Firefox has never supported this for grid row tracks either.
Despite of that lack of interop I could only find 2 bugs on Chromium bugtracker about these topics:
* https://bugs.chromium.org/p/chromium/issues/detail?id=901447
* https://bugs.chromium.org/p/chromium/issues/detail?id=1020880

Also the bug for Firefox grid row tracks has 0 votes and no comments from authors asking about it: https://bugzilla.mozilla.org/show_bug.cgi?id=1481876

We also have a use counter for when percentage grid row tracks are used in a grid container with indefinite height in Chromium: https://chromestatus.com/metrics/feature/timeline/popularity/2248
It shows that a 0.03% of page loads hit this use counter, but I believe probably most of the cases would be `grid-template-rows: 100%` and a single row grid (which have the very same output resolving percentages or not doing it).

When we implemented the change related to percentage row tracks in grid layout [we broke a few sites](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/CJgcT4hR7Rk/_TBhjGLfAwAJ), but most of them were this single row 100% case that had no change in behavior. If we come back to the previous behavior the breakage would be way smaller, some sites might change a little bit, but we won't be causing overflow so not hard or problematic issues IMHO.
And we'll win in interop (I hope all browsers would be happy to come back to the old behavior, as it's going to simplify the implementations) and consistency, percentages for indefinite heights would be resolving the same everywhere (no exception for grid and flex).

I believe it's worth to reconsider all this, change it for everything flex/grid row gutters and grid row tracks and avoid the unnecessary pain on browsers implementations due to this without a clear benefit or web author's demand.

I'd love to hear opinions from @atanassov and @MatsPalmgren on the topic, as they were involved in the previous discussions.

**Comment by mrego** [comment]
About this example:
> For grid, this can be used with % grid tracks to make a sensible layout. E.g.
> 
> height: 33% row track
> height: 33% row-gap
> height: 33% row track
> 
> This makes the gap and rows the same height and the grid container does not have overflow. There's a nice match here: % tracks and % gaps resolve off the same height.

This doesn't render very well for grid either, as first tracks are treated as auto height, that gets you the intrinsic height of the grid container, then you resolve 33%, so probably some track will end up being smaller than what it was originally and you'll get overflow in the items (not the grid container, but overflow anyway).

I'm attaching the output of the following examples:
```html
<div style="display: grid; grid-template-rows: 33% 33%; gap: 33%; border: solid;">
  <div style="background: magenta;">foo</div>
  <div style="background: cyan;">bar</div>
</div>

<hr>

<div style="display: grid; grid-template-rows: 33% 33%; gap: 33%; border: solid;">
  <div style="background: magenta;">foo<br>bar</div>
  <div style="background: cyan;">baz</div>
</div>

<hr>

<div style="display: grid; grid-template-rows: 33% 33%; gap: 33%; border: solid;">
  <div style="background: magenta;">foo<br>bar<br>baz</div>
  <div style="background: cyan;">foobar</div>
</div>
```

![Screenshot of previous examples rendering in Chromium](https://user-images.githubusercontent.com/11602/82373979-b4b9e700-9a1e-11ea-9ee5-133e9010d4c5.png)

Not a great result IMHO, and dunno when something like this could be really useful for anyone.

**Comment by davidsgrogan** [comment]
Rego, you make good points that I find very compelling, but they are orthogonal to this issue.

This issue is that we realized flex % gaps were matching the wrong behavior from grid. In grid, gap % resolve identically to the things they put space between. In flex, gap % resolve in a _different_ way to the thing they put space between. Grid has that right. Flex has it wrong.

Your point is that grid gaps and tracks should change their current matching behavior to some other matching behavior. No matter how that shakes out, grid gaps and tracks behavior would still match each other, which is what we think flex should do too, so the point in this issue is unaffected.

**Comment by dholbert** [comment]
I'm fine with the proposed flexbox change here.

(The ~sibling consistency argument feels reasonable, and it feels unlikely that someone would intentionally write content that depends on the currently specced behavior, since it causes overflow pretty reliably/trivially.)

**Comment by tabatkins** [comment]
s/cause of undefined constraint/case of resolving against an indefinite constraint/
