### ISSUE TITLE
[css-fonts-4] [varfont] font matching algorithm should not favor italic as a fallback for oblique

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#514]
[Migrated](https://github.com/litherum/csswg-drafts/issues/3) on behalf of @jfkthame:

Back in the days of CSS2.1, the spec [said](https://www.w3.org/TR/CSS21/fonts.html#propdef-font-style):

> A value of 'normal' selects a font that is classified as 'normal' in the UA's font database, while 'oblique' selects a font that is labeled 'oblique'. A value of 'italic' selects a font that is labeled 'italic', or, if that is not available, one labeled 'oblique'. 

Note that it does _not_ suggest that an italic face should be used when oblique is specified.

However, in CSS Fonts 3, things have [changed](https://www.w3.org/TR/css-fonts-3/#font-style-prop):

> Values have the following meanings:
> 
> normal
>     selects a face that is classified as a normal face, one that is neither italic or obliqued 
> italic
>     selects a font that is labeled as an italic face, or an oblique face if one is not 
> oblique
>     selects a font that is labeled as an oblique face, or an italic face if one is not 

So now, 'italic' falls back to oblique (as before), _and_ 'oblique' falls back to italic (changed behavior).

(This difference is also reflected in the Font Matching Algorithm described in the two spec versions.)

I think this change was a mistake. When 'oblique' is requested but no actual oblique is present, a better fallback than the italic face would be a synthetically-slanted version of the regular face.

According to the reporter in [this Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1303580), browsers currently differ on this, which leads me to suspect that a spec change here (and corresponding changes to the browsers that follow the current CSS Fonts behavior) will be unlikely to break the web in any substantial way.

(This isn't directly linked with variation fonts, but as we're re-examining the font properties and matching algorithm anyway, and variations do have implications for font-style, it seemed like the right time to bring it up.)

**Comment by litherum** [comment]
If we decide that oblique takes a numerical argument but italic doesn't, then this sounds like a good idea.

**Comment by litherum** [comment]
See also: https://github.com/w3c/csswg-drafts/issues/519

**Comment by davelab6** [comment]
> When 'oblique' is requested but no actual oblique is present, a better fallback than the italic face would be a synthetically-slanted version of the regular face.

I don't agree with this. When 'oblique' is requested but no actual oblique is present, I think the better fallback will be the italic face, if available; a synthetically-slanted version of the regular face should always be a last resort.

**Comment by behdad** [comment]
> When 'oblique' is requested but no actual oblique is present, a better fallback than the italic face would be a synthetically-slanted version of the regular face.
> 
> I don't agree with this. When 'oblique' is requested but no actual oblique is present, I think the better fallback will be the italic face, if available; a synthetically-slanted version of the regular face should always be a last resort.

I don't agree with this.

**Comment by davelab6** [comment]
The "synthetic" or distorted fonts should be avoided and used as a last
resort because the distortion inherently makes resulting letterforms that
look bad, while crafted obliques or italics will have many subtle changes
that make the letterforms look good. This effects reading performance and
even legibility.

The purpose of a non-normal font-style is to add visual emphasis to the
text. The purpose of designing a non-normal style is to control and match
with the normal style in a way that harmonizes. Distortion can create
visual distinction but not with harmony.

If the CSS author has indicated one kind of emphasis is preferable, but the
font family selected does not have that kind and does have the other kind,
then using the emphasis style which is harmonious is a better choice.

**Comment by jfkthame** [comment]
CSS offers a three-way distinction: `font-style: normal | italic | oblique`. The usual convention (and author practice) for emphasis (or other purposes) is to use italic, and there is a well-established practice in software to use a "fake italic" (i.e. artificially obliqued face) to satisfy a request for "italic" style when no true italic is available.

The distinctive case is where an author explicitly requests oblique _rather than_ italic. We can assume this is usually a conscious decision by an author, given that tools and common practice all tend towards the italic choice. Indeed, an author who requests oblique may well be wanting to make a _distinction_ between italic and oblique. To use the italic face to fulfill the oblique request will erase this distinction, whereas using an artificially-slanted version of the normal face will maintain it.

In addition, while algorithmically generated "styled" faces (e.g. for bold, condensed, or extended) are generally inferior to crafted designs, oblique is one style for which this is less of a concern. A typical upright "normal" face can be algorithmically slanted by a moderate amount with little harm to the design.

Therefore, I still believe that `font-style: oblique` should _not_ fall back to using an italic face, but should _in preference_ use the regular face and synthetically slant it.

**Comment by davelab6** [comment]
Are you aware of any authors doing this? 

Would love to see real world examples of that (and examples where oblique is used by itself intentionally)

**Comment by jfkthame** [comment]
As one example, Knuth uses /oblique/ text as the style for emphasis in the body text of /The TeXbook/, in contrast to the _italics_ he uses for running heads and for math formulas and math-like material.

Looking through a few opening pages from /The Art of Computer Programming/, the convention there seems to be _italics_ for emphasis, while /oblique/ is used for titles in bibliographic references.

**Comment by svgeesus** [comment]
So, this would affect the two lists in the [font matching algorithm[():

> If the value of 'font-style!!property' is ''oblique'' and the requested angle is greater than or equal to 20deg,

and

> If the value of 'font-style!!property' is ''oblique'' and the requested angle is greater than or equal to 0deg and less than 20deg,

in both cases, a new step would be inserted between the current step 2 (checking nearby oblique values in the family) and step 3 (checking italic values). This step would say something like:

If [`font-synthesis-style`](https://drafts.csswg.org/css-fonts-4/#font-synthesis-style) has the value `auto`, the a match is is created (for variable fonts with a `slnt` axis, by setting the `slnt` value; otherwise, by geometric shearing) with the specified oblique value.

**Comment by svgeesus** [comment]
@litherum just looking for a quick sanity check before I make those edits

**Comment by behdad** [comment]
> If [`font-synthesis-style`](https://drafts.csswg.org/css-fonts-4/#font-synthesis-style) has the value `auto`, the a match is is created (for variable fonts with a `slnt` axis, by setting the `slnt` value; otherwise, by geometric shearing) with the specified oblique value.

This wording makes it sound like setting `slnt` value is as "fallbacky" as shearing.  Whereas the former is proper matching, not fallback.

**Comment by svgeesus** [comment]
Good point. Although in terms of the algorithm, 'match' is used to mean 'success, stop here'. How about:

If [`font-synthesis-style`](https://drafts.csswg.org/css-fonts-4/#font-synthesis-style) has the value `auto`, then for variable fonts with a `slnt` axis a match is is created by setting the `slnt` value with the specified oblique value; otherwise, a fallback match is produced by geometric shearing to the specified oblique value.

**Comment by behdad** [comment]
Sounds good to me.
