### ISSUE TITLE
[css-ui] Change appearance: button to only apply to buttons

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#5174]
https://drafts.csswg.org/css-ui-4/#valdef-appearance-button

See https://github.com/whatwg/html/pull/4857

> Change button to not be applicable to non-buttons
[intent to ship](https://groups.google.com/a/chromium.org/d/msg/blink-dev/QFXFzfQtlKk/YPOZLSoXCwAJ)

I didn't see a spec issue about this, so filing this.

I think the change to css-ui to match is to move `button` to the list of `<compat-auto>` non-terminal value type.

cc @tkent-google @emilio @smfr @frivoal

**Comment by zcorpan** [comment]
cc @heycam

**Comment by heycam** [comment]
For what it's worth, telemetry that I added to Firefox to check for -moz-appearance value usage showed that 0.051% of pages loads used `-moz-appearance: button` on some non-widget element, and 0.016% of page loads used `-moz-appearance: button` on a widget whose default appearance is not button.

**Comment by frivoal** [comment]
I believe we have a much older resolution saying that the WG didn't want any value other than none or auto, except for compat reasons. By that logic, if `button` on arbitrary elements isn't needed for compat, we ought to be retiring it, and making it part of `<compat-auto>` seems like the right way to do that.

@heycam Is 0.051% an acceptably low threshold for Mozilla for this particular change?

**Comment by heycam** [comment]
To me it feels a little high.  That's one in every 2,000 pages.

**Comment by zcorpan** [comment]
There was more detailed analysis behind Chromium's decision to change this, see https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/QFXFzfQtlKk/YPOZLSoXCwAJ

This shipped in chromium 80. @tkent-google have there been any bug reports from this change?

**Comment by tkent-google** [comment]
> This shipped in chromium 80. @tkent-google have there been any bug reports from this change?

AFAIk, there are only two bug reports.
https://bugs.chromium.org/p/chromium/issues/detail?id=1038687
https://bugs.chromium.org/p/chromium/issues/detail?id=1094709

We have no plan to revert the current behavior.

**Comment by atanassov** [comment]
As a follow up on the previous discussion, we should define what _buttons_ refer to.

**Comment by frivoal** [comment]
The conclusion reached during the meeting is a little bit flawed, as we used imprecise language and confused ourselves. 

> RESOLVED: Limit 'appearance: button' to buttons once we figure out what buttons are

> As a follow up on the previous discussion, we should define what buttons refer to

We don't actually need to define what buttons are, because the way we achieve "Limit 'appearance: button' to buttons" is by making `button` part of the `<compat-auto>` non-terminal value type. This means the button keyword will behave identically to the `auto`, this lets widgets get their native appearance, and leaves other things alone. The result is that things that aren't supposed to be buttons can no longer forcibly be made into buttons, but we don't need to specify which is which, as determining what is the correct native appearance of various widgets is the responsibility of the host language (HTML), not of the css spec.

Based on that, the resolution is actually enough to make the edit to the spec, and does not need further research to determine what buttons are.

**Comment by zcorpan** [comment]
Thanks @frivoal!

Tests updated in https://github.com/web-platform-tests/wpt/pull/25428

**Comment by zcorpan** [comment]
For the question "what is a button?", that is up to the host language per https://drafts.csswg.org/css-ui/#native-appearance

For HTML, per https://github.com/whatwg/html/pull/4857 these can end up with the "button" "kind of widget":

- `button`
- `input` with type Button, Submit, Reset, or Color

**Comment by MatsPalmgren** [comment]
Hmm, is this really web-compatible?  I thought we all agreed that `appearance:button` on a HTML `<select>` should suppress the drop-down button. That's what Firefox and Safari still do and it's a fairly common use case on the web last I checked.  I'm pretty sure Chrome used to have that behavior too because the reason we (Gecko) implemented it was that we were getting [bug reports](https://bugzilla.mozilla.org/show_bug.cgi?id=649849) about  broken web sites which expected that behavior because of Chrome.

**Comment by zcorpan** [comment]
@MatsPalmgren it has been shipping in Chromium since M80 (reached stable in February). See the [intent to ship thread](https://groups.google.com/a/chromium.org/g/blink-dev/c/QFXFzfQtlKk/m/YPOZLSoXCwAJ) for number of page views impacted.

From the minutes above:
```
<fantasai> Rossen_: That means you're not breaking anyone who depends on this?
<fantasai> iank_: Got a few minor reports
<fantasai> iank_: no large-scale breakage
```

**Comment by zb3** [comment]
Do you *really* need to make it impossible to make links look like buttons without having to write custom button styles from scratch? Maybe I'm missing something, but what's the other way to make a button have an "Open in new tab" entry in it's context menu?

**Comment by frivoal** [comment]
Without taking a personal opinion on the matter, yes, this is what the change means: links aren't buttons, and the ability to make them look like buttons was an unintended accident of how things were implemented, and as we're cleaning up the way things work, it was judged acceptable to remove that ability, given that data seems to show that very few web pages actually used it.

There was some skepticism during the call where we took that resolution (notably expressed by @fantasai), but this wasn't strong enough to stop the proposal.

If you think this is a mistake, it would be good to either provide some evidence that the breakage of existing sites is going to be more common / severe than anticipated, or some explanation of why this ability is desirable (what are you trying to achieve + why is that a good thing + why can't you do it some other way). The more strongly you can make this argument, the better the chances.

**Comment by zb3** [comment]
You don't have to look far to find the use case, because even on **this** page, we have the `New Issue` link, which does look like a button, yet with all the benefits of it being a link, like copying the url or opening it in the new tab. `a {appearance: button}` is not used in this case (so it didn't count and wasn't affected), but this is only because its styles were implemented from scratch. In the end, this is what I did as well, I just made another class to make button links look like buttons without relying on `a {appearance: button}` so now I don't have to think about that.

I think my argument here is just that `a {appearance: button}` makes this scenario easier to implement, but in no way decides whether implementing this scenario is possible. My original use case was for generating a document with the ability to copy the link to tweak some of its parameters, but I don't think that's what I'd argue about.

**Comment by Marat-Tanalin** [comment]
So we are now still forced to use an empty form:

```
<form action="/example/">
    <button type="submit">Link button</button>
</form>
```

just to create a [link](https://tanalin.com/en/blog/2013/03/link-button/) that looks like a native button. With no ability to open it in a new tab/window, see the target URL in advance or copy the URL, and with a need to work around the [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=108690) and [WebKit](https://bugs.webkit.org/show_bug.cgi?id=30103) bugs that cause adding a question mark even though the query string is empty.

That’s amazing, CSSWG.

**Comment by Marat-Tanalin** [comment]
@frivoal
> data seems to show that very few web pages actually used it.

Because people were waiting when the feature gets finally standardized? Instead of collecting stats regarding the `appearance` property, it would probably be more reasonable and useful to collect stats of:

* styling links to mimic buttons (GitHub is an example);
* using an empty form for that purpose (the _only_ way to make a link look like a _true_ native button, not just _similarly_).

**Comment by frivoal** [comment]
The past few comments (since https://github.com/w3c/csswg-drafts/issues/5174#issuecomment-704329991) seem to justify reopening this issue to me.

Summary: people want to do `appearance: button` on links, but per the latest spec this is not possible, `appearance: button` will only work on things that the markup language considers buttons, and links isn't one of those.

**Comment by zcorpan** [comment]
Maybe HTML could provide a way to create formless buttons that act more like links? And browsers could support submitting forms into a new tab through the context menu (without any spec changes).

I would be OK with allowing `button` on links, though.

**Comment by jensimmons** [comment]
I asked about this on Twitter: https://twitter.com/jensimmons/status/1329115564233662464

**Comment by Marat-Tanalin** [comment]
People will then just be forced to use empty forms to make “links” that can’t be opened in a new tab/window, and with no ability to see their URLs in advance. Such button is technically a button, but in fact is a link. Making a link button is technically possible, the resulting links are just not as usable as true links. Is that good?

Fwiw, the [russian version](https://tanalin.com/blog/2013/03/link-button/) of my [blog post](https://tanalin.com/en/blog/2013/03/link-button/) about making a link look like a native button, has about 60-70 visits daily and is consistently the  **most popular** page of my site for years.

> &lt;tantek&gt; I'm a bit surprised this is being re-opened without new information. one random github comment is not new information

There were _two_ comments actually. And mine was probably not about new information, but at least about that a **wrong type** of stats (using the `appearance` property itself for making a link look like a button) was used for making the whole decision. As I said, it would probably be more reasonable and useful to make the decision based on stats of:

* styling links to mimic buttons (GitHub is an example);
* using an empty form for that purpose (the _only_ way to make a link look like a _true_ native button, not just _similarly_).

That stats would be not about _how_ the goal is achieved (good developers tend to avoid using nonstandard features), but about _what_ people want to achieve. And I’m not sure collecting stats of cases of styling links to mimic buttons would be easy/possible in an automated way.

> astearns: I'd like a narrower issue and to close the older one

Does such a new narrower issue already exist?

P.S. The IRC log is confusing and hard to read. Why is it `<dael> florian: ` and not `<florian>`? It’s also unclear who each of the conversation participants is except for ones I personally historically know (while other readers might not) like bkardell_, fantasai, florian, tantek, zcorpan_. Some accompanying legend would be helpful for each of such IRC logs.

**Comment by astearns** [comment]
@Marat-Tanalin the log has `<dael>` at the beginning of most of the lines because she was minuting. It’s a fair point that the IRC nicks we use in the minutes don’t always match GitHub user names, both of which can be difficult to match to actual names. Perhaps I should start a wiki page with a table of who’s who (which may also help onboarding new members).

The narrower issue does not exist yet - I was asking to have a new one raised. This issue is about limiting the button value to actual buttons (mainly for compat reasons). I think allowing the button value on links is sufficiently different to merit a new start in the discussion.

**Comment by frivoal** [comment]
> Does such a new narrower issue already exist?

Not yet, but it should be created.

> The IRC log is confusing and hard to read. Why is it `<dael> florian:` and not `<florian>`?

Dael is the person who was taking minutes.

> It’s also unclear who each of the conversation participants is except for ones I personally historically know (while other readers might not) like bkardell_, fantasai, florian, tantek, zcorpan_. Some accompanying legend would be helpful for each of such IRC logs.

The logs included here in github is a direct, unedited copy from the IRC session. A cleaned up version of the log, with irc nicks expanded to full names, gets posted to the [www-style mailing list](https://lists.w3.org/Archives/Public/www-style/) once there's been time for cleaning it up. The one that covers this particular issue is: https://lists.w3.org/Archives/Public/www-style/2020Nov/0015.html
