### ISSUE TITLE
[css-contain] style containment counter scoping clarification

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#5175]
In the css-contain-2 spec under [style containment](https://www.w3.org/TR/css-contain-2/#containment-style) it says the following:
```
The counter-increment and counter-set properties must be
scoped to the element’s sub-tree and create a new counter.
```
with `scoped to the element's subtree` essentially being "pretend that the subtree is the root of the document, excluding the element itself"

Presumably this refers to counter-increment and counter-set properties of the subtree elements. It's unclear where the counter would be created though. To give an example,

```html
<style>
.contained { contain: style }
.increment { counter-increment: n } 
.increment_and_report::before {
  counter-increment: n;
  content: counter(n);
}
</style>

<div class="contained increment">
  <div class="increment_and_report"></div>
  <div class="increment_and_report"></div>
</div>
```
In my understanding from [one of the web platform tests](http://w3c-test.org/css/css-contain/counter-scoping-003.html), is that this should print out
```
1
2
```

Is this a correct expectation?

Note that the increment happens from .increment_and_report::before which isn't a sibling of the other div's ::before (I think). This would mean that the counter is created at at the subtree of .contained element, so both .increment_and_report divs use the same counter. Would this also mean that the counter-increment elements can be arbitrarily deep and still create counters at the root?

Or should the test instead expect
```
1
1
```
(Or be modified to instead increment the value on span rather than span::before)

That is, does scoping really mean just ignore the element and its ancestors and otherwise behave as you normally would if the subtree was the root of the document?

**Comment by vmpstr** [comment]
I'm pretty convinced this was just a small problem in the test case. Please re-open if you feel otherwise.

**Comment by Loirooriol** [comment]
I'm reopening this because https://drafts.csswg.org/css-contain/#containment-style has an example that says

> As [`counter-increment`](https://drafts.csswg.org/css2/#propdef-counter-increment) is scoped to an element’s subtree, the first use of it within the subtree acts as if the named counter were set to 0 **at the scoping element**

But I agree with changing that, since in

```html
<style>
.contained { contain: style }
.reset { counter-reset: n 10 }
.increment::before { counter-increment: n }
.report::before { content: counters(n, ".") }
</style>
<div class="contained reset">
  <div class="report"></div>
  <div class="increment report"></div>
  <div class="increment report"></div>
</div>
```

The 1st item is not modifying counters so it's supposed to read `10`.
The 2nd item increments, so it instantiates a new counter and produces `10.1`
But if this new counter is instantiated at the beginning of the scoping element, then we would have to go back to the 1st item and update it to `10.0`!
So better instantiate the counter locally, then the result is

```
10
10.1
10.1
```

Also, a note is not normative. All of this needs to be properly defined in normative text.

**Comment by frivoal** [comment]
@Loirooriol 's example above does yield 10 / 10.1 / 10.1 in both Chrome and Firefox, so unless someone has a good reason why it'd be friendlier to authors to do otherwise, I suggest we resolve to adopt that.

(Safari reports 0/1/1 which is indicative of some disagreement about other aspects of how this works, but agrees with Firefox and Chrome in the aspect relevant to this bug, as can be see by removing the `.reset { counter-reset: n 10 }` line from the stylesheet: in that case, all 3 engines do the same)

**Comment by tabatkins** [comment]
Man, I'm getting some odd results in Chrome - counter() and counters() are giving inconsistent results.

```html
<!DOCTYPE html>
<style>
body { counter-reset: foo; }
div {
  counter-increment: foo;
  margin: .2em; padding: .2em; background: #0001;
}
div::before { content: counters(foo, ".") " / " counter(foo) " "; }
</style>
<div>
  Expected (using the root "foo" counter).
  <div style="contain: style;">
    I'm contained. Incoherently, I appear to both have only a single counter (the root "foo" counter, as revealed by <code>counters()</code>) and two (or more?) counters (the inner fresh one created by my next sibling, as revealed by <code>counter()</code>). 
    <div>I'm not sure how I ended up with *three* counters here. But my <code>counter()</code> at least makes sense.</div>
    <div>Same.</div>
  </div>
  <div>Expected (using the root "foo" counter).
    <div>Expected (using the root "foo" counter).</div>
    <div>Expected (using the root "foo" counter).</div>
  </div>
</div>
```

![Screenshot 2024-06-12 17 31 11](https://github.com/w3c/csswg-drafts/assets/682840/c5040741-7110-43f4-a5f7-91015836d166)

**Comment by tabatkins** [comment]
Anyway, quoting the spec:

> When considering the effects of the scoped property on elements inside the subtree, the element at the base of the subtree is treated as if it was the root of the document.

So, each child of the scoper acts like they're a root (no parent, but possibly siblings). This should result in [the spec example](https://drafts.csswg.org/css-contain/#example-21ca5120) - the first child with `counter-increment` sees that there's no counter of that name (because it's root-like) and creates a fresh counter, while the second child inherits its "foo" counter from its preceding sibling.

The test given in [the OP](https://github.com/w3c/csswg-drafts/issues/5175#issue-631912976) should in fact return 1 and 1, but for boring reasons - because the element establishing the counter is the *grandchild* of the scoper (the ::before pseudo of the scoper's children), the first one establishes a fresh counter (on the ::before), and then the second one also establishes a fresh counter, because it doesn't see any counter coming from its parent *or* its previous sibling.

Similarly, the test given in [Oriol's comment](https://github.com/w3c/csswg-drafts/issues/5175#issuecomment-1380898285) should indeed be 10, 10.1, and 10.1 - the first scoped child hasn't touched the counters, so `counters()` only sees the one counter established on the parent. (Note that the `counter()`/`counters()` functions are explicitly *not* scoped in their effects.) Then the second and third child act like the previous paragraph - each one establishes a counter on its ::before child, so the next one doesn't see that counter and creates another fresh one.

-------

Ah, and the example cited in Oriol's comment was fixed in <https://github.com/w3c/csswg-drafts/commit/ca36447eb4f0b4ce8395523a3c7f7495479cf337>, which was associated with a near-dupe in #9192. So, aside from the fact that Chrome's current behavior is super broken in an exceedingly bizarre way, the spec seems to be all fixed up by now?

**Comment by Loirooriol** [comment]
Can we put the text that defines how `counter-increment` is scoped in a normative section?

**Comment by danielsakhapov** [comment]
@tabatkins that's the old implementation, latest Chrome (126) goes with a new (hopefully correct per-spec) implemenation. Please, check it out.

**Comment by tabatkins** [comment]
Okay, now that I've had time to load this up:

Yes, the example is now fixed in Chrome; it gives exactly the expected results, matching the spec's example.

So the normative text has been correct for some time, and the intro line of that one example was fixed some time ago. I'm closing this as fixed.
