### ISSUE TITLE
[css-color-adjust] Should dark mode apply to favicons?

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#5205]
I think it should. This doesn't seem to be in the spec, just make a simple addition?

See also [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1026539).

**Comment by fantasai** [comment]
Can you clarify what you mean by "apply"?

**Comment by chrishtr** [comment]
i.e. Should a dark mode theme apply to the document containing the SVG favicon, thereby adjusting its default background and foreground colors, etc?

**Comment by fantasai** [comment]
@chrishtr It should be handled no differently from any other linked/embedded SVG document. If it's an external document, it won't inherit any CSS properties, because those don't inherit through such links. But it should be given the same @media environment, and should follow the same rules as the loading of any other SVG document. We don't make any exceptions for favicons, so I don't see why that wouldn't be the case already.

Is there something you think should be happening that's an *exception* to the normal way we handle SVG documents?

**Comment by chrishtr** [comment]
Ok, this makes sense.  The spec for them in HTML also says it has the same @media environment: https://html.spec.whatwg.org/#rel-icon

> Is there something you think should be happening that's an _exception_ to the normal way we handle SVG documents?

No, I just wanted to make sure favicons would get the same color scheme and that this is in the spec.

**Comment by lilles** [comment]
The Chromium bug in this description is for devtools emulation, not favicons in the "normal" case.

There was an issue with SVG favicons not being rendered with the correct prefers-color-scheme, but that has been fixed: https://crbug.com/1090464
