### ISSUE TITLE
[scroll-animations-1] Effects for scroll linked animations are not inclusive at max scroll

### ISSUE THREAD

**Issue by JTensai** [w3c/csswg-drafts#5223]
Effects for scroll linked animations do not handle the inclusive end exception established by #37

When scroll timeline end scroll offset is default, reaching max scroll should result in the effect remaining at its last keyframe value. Instead it finishes. We need a way to allow the effect to detect that it should not finish when its corresponding timeline is at its end point (and satisfies the inclusive requirements).

**Comment by andruud** [comment]
Isn't this handled well by [The phase of a ScrollTimeline](https://drafts.csswg.org/scroll-animations-1/#phase-algorithm) already?

(BTW the linked PR seems irrelevant).

**Comment by flackr** [comment]
Issue #4325 introduces the various issues in this area. The phases solved the issue of the ScrollTimeline becoming inactive, but this particular issue is (I believe) that for the naive case, e.g.

```js
element.animate({transform: ['none', 'translateY(200px)']}, { duration: 10000, timeline: new ScrollTimeline()});
```

When you reach the maximum scroll offset, the timeline produces time value 10000, which means that the animation is in the after phase due to https://www.w3.org/TR/web-animations-1/#animation-effect-phases-and-states

@JTensai I believe your proposal from the other issue was:
> Update animation and animation effect active time and phase calculation to take the timeline state (or hold phase) into account.

At a high level this sounds reasonable to me.

**Comment by majido** [comment]
Given that we need to change the animation and effect timing calculation to change, I would argue it is probably better to no longer have the current special-case logic on ScrollTimeline. Basically just have it so that once timeline reaches its last position it is in "after" phase which is the normal behavior.

Then we just make the keyframe to have a fill forward or act as if it has one. If keyframe already has explicitly a fill value we honor that which allows authors a way to escape this behavior.

Basically I propose something like this:
 - Consider ScrollTimeline with scroll range 100% to be *terminal finite*. (I am sure there are probably better terms for this but I am just using this to just mean that it is not possible to go beyond their last time value).
 - When [setting timeline of an animation](https://drafts.csswg.org/web-animations/#setting-the-timeline), it that timeline is *terminal finite*, then consider that animation to be *prefers fill-forward*.
 - When [setting the associate effect](https://drafts.csswg.org/web-animations/#setting-the-associated-effect), if the animation is a *prefers fill-forward* and the effect's fill mode was not explicitly specified (we may need to introduce 'fill: auto' as a default value), then set the effect's fill to be forward.

I believe this:
 - achieves the desired behavior.
 - is author friendly (observable and overridable via effect.phase and).
 - is simple to understand and spec since it avoids the special case in timeline phase.

**Comment by birtles** [comment]
> * Consider ScrollTimeline with scroll range 100% to be _terminal finite_. (I am sure there are probably better terms for this but I am just using this to just mean that it is not possible to go beyond their last time value).
> 
> * When [setting timeline of an animation](https://drafts.csswg.org/web-animations/#setting-the-timeline), if that timeline is _terminal finite_, then consider that animation to be _prefers fill-forward_.
> 
> * When [setting the associate effect](https://drafts.csswg.org/web-animations/#setting-the-associated-effect), if the animation is a _prefers fill-forward_ and the effect's fill mode was not explicitly specified (we may need to introduce 'fill: auto' as a default value), then set the effect's fill to be forward.

I might not be following correctly but this sounds to be pretty stative? As it, it depends on the order in which these operations are performed? I think it shouldn't matter whether you associate the timeline or the effect first (and I don't think you want to magically update the fill mode -- but rather keep it as `auto` but define what that means in this situation, i.e. only update the computed fill mode).

**Comment by majido** [comment]
I am fine to spec this as you suggest Brian to make computed fill live.

**Comment by flackr** [comment]
This is fixed by the linked PR, and can be seen in spec at:
https://drafts.csswg.org/web-animations-2/#animation-effect-phases-and-states

**Comment by graouts** [comment]
I believe this does not account for animation ranges and filed https://github.com/w3c/csswg-drafts/issues/12134.
