### ISSUE TITLE
[css-images-3] change which images image-orientation applies to

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#5245]
In #4165 it was resolved that EXIF orientation applies to all images by default. There was some discussion about which images the `image-orientation` property and talk of a resolution, but no actual resolution.

This matters because we've got two sets of WPT tests added in the last six months which disagree - see https://github.com/web-platform-tests/wpt/issues/18549#issuecomment-645532399 - and different results in Firefox and Chrome (see [a](http://wpt.live/css/css-images/image-orientation/image-orientation-background-image.html), [b](http://wpt.live/css/css-images/image-orientation/image-orientation-none-content-images.html)). So we need a once-and-for-all resolution on this.

@heycam made the same observation in https://github.com/w3c/csswg-drafts/issues/4165#issuecomment-587949977, and we'd like to implement this but can't until it's clarified.

So the question is: does the `image-orientation` property apply to "decorative" images, such as `background-image` and `border-image`? And if it does not (as currently specified), the second question is can we tightly define "decorative" images.

@zcorpan made a full list at https://github.com/web-platform-tests/wpt/issues/18549#issuecomment-522631537

> CSS
> * ::before/::after + content
> * background-image
> * list-style-image
> * border-image
> * cursor
>
> SVG
> * image
>
> HTML
> * img
> * canvas drawImage() + getImageData()
> * video poster
> * input type=image
> * embed
> * object
>
> load an image in an iframe
> load an image in a top-level doc (this already respects EXIF in all browsers I believe)
> Favicon link rel=icon / favicon.ico (manual tests?)
> web app manifest icon (manual test?)

* I would expect "content" images to be those displayed from `content`, `list-style-image` (which generates content), SVG `image`, HTML`img`, `embed`, `object`, and `video` poster. The `image-orientation` property should apply to all of these.
* I would expect "decorative" images to be `background-image`, `border-image` and `mask-image`.
* `image-orientation` does not apply to cursor, top-level docs, favicon or web-app manifests. 
* I'm slightly unsure about exactly where iframe fits.

cc @schenney-chromium

**Comment by heycam** [comment]
> So the question is: does the image-orientation property apply to "decorative" images, such as background-image and border-image? And if it does not (as currently specified), the second question is can we tightly define "decorative" images.

Agree that that's what we need to answer.

The goal of the `image-orientation` property is to make it easy to turn off the new automatic re-orientation behavior, in case authors have content that breaks with the new behavior.  (We had a few bug reports in Firefox of content that broke, due to images being used that had incorrect orientation metadata in them, probably because of tools that rotated the image data but left the metadata untouched.  So it is useful for quickly fixing this.  But these were all `<img>` elements.)

If `image-orientation` doesn't apply to decorative images, then there is no easy way to opt out of any breakage that's occurred.  So I would prefer to have it apply to all content and decorative images that the element has, and then not bother with defining decorative images.

I don't have a strong opinion on `cursor` and resources linked to with `<link>` / `<meta>` elements, but I think it would be fine not to them apply there.  It's unlikely people are using JPEGs with orientation data in them.

My view of orientation metadata is that it's an implementation detail of the image, and the only reason that we are allowing control of whether it is honored is to help authors manage this change in behavior.

**Comment by faceless2** [comment]
I agree with Cam on all his points. If EXIF applies to all images, then I think `image-orientation` has to as well.

**Comment by fantasai** [comment]
Because the spec was pretty clear that it does not apply to background images etc., only to replaced elements (including generated content).
