### ISSUE TITLE
[css-color4] Precision issues when converting colors between Lab and sRGB

### ISSUE THREAD

**Issue by snigo** [w3c/csswg-drafts#5262]
I'm working on my own Lab color library implementing conversions according to CSS color4 spec and keep noticing small inconsistencies when converting from Lab color space to sRGB, resulting in following:
```js
// pseudo
color('#f00').toLab().toRgb(); // #fe0000
```

I've checked whole sRGB color wheel (at saturation 1 and lightness 0.5) and xyz values on conversion back from Lab are **steadily** lower in the range [0.0005 - 0.004] that is enough for side effects.

Conversions `sRGB -> XYZ -> sRGB`, `Lab -> XYZ -> Lab` and `sRGB -> XYZ(D65) -> XYZ(D50) -> XYZ(D65) -> sRGB` are precise as expected which means that either conversion between sRGB and XYZ or between Lab and XYZ are off a bit.

I wonder if anyone else experienced the same result?

**Comment by snigo** [comment]
Pretty much the same behaviour can be spotted in Photoshop color picker
RGB:
<img width="534" alt="Screenshot 2020-06-25 at 15 12 23" src="https://user-images.githubusercontent.com/56631054/85726707-a2565b80-b6f6-11ea-9a27-f3bdca6c9d65.png">
Lab:
<img width="534" alt="Screenshot 2020-06-25 at 15 12 55" src="https://user-images.githubusercontent.com/56631054/85726737-a97d6980-b6f6-11ea-994b-c5e18cecd881.png">

**Comment by svgeesus** [comment]
> Conversions sRGB -> XYZ -> sRGB, Lab -> XYZ -> Lab and sRGB -> XYZ(D65) -> XYZ(D50) -> XYZ(D65) -> sRGB are precise as expected which means that either conversion between sRGB and XYZ or between Lab and XYZ are off a bit.

Thanks for the detailed report (especially, of things which do work). I assume that you are carrying out calculations at a higher precision than the end result (ie not doing everything in 8 bits or using 8 bit sRGB as the storage format, which I have seen libraries do).

How are you implementing XYZ? Does it have a flexible whitepoint or do you always assume a D50 whitepoint? Which chromatic adaptation method are you using?

I ask because, depending how you do it, `sRGB -> XYZ -> sRGB` could all be D65, `Lab -> XYZ -> Lab` could be all D50. But they you list `sRGB -> XYZ(D65) -> XYZ(D50) -> XYZ(D65) -> sRGB` which clearly has two chromatic adaptation steps and yet still round-trips.

Lab is known to have higher precision requirements, and should be represented using a triple of floats. The integer 0 -100, -128 - 127 encoding used in Photoshop and in ICC profiles does introduce significant roundoff error and consequent banding. Even representing it as a tripe of 16bit integers is suboptimal.

**Comment by svgeesus** [comment]
The other thing to check is that you are rounding and not truncating, because otherwise Lab 99.9999 0 0 will not get you to 255 in RGB, only 100.000000 0 0 will.

**Comment by snigo** [comment]
I found it super confusing to store everything in one class and ended up implementing 3 classes: each for sRGB, Lab and XYZ color spaces with default D65 white point for sRGB, D50 for Lab and toggleable white point for XYZ using Bradford adaptation. Here's the repo:
https://github.com/snigo/color
(early stage without description at this point)

I've increased rounding from 3 to 7 decimal places and everything works perfectly fine now. 👍
The problem in particular was with Lightness of Lab which I stored as decimal in [0..1] range and in this way rounding to 3 places is not enough

**Comment by danburzo** [comment]
You might find [this thread](https://github.com/w3c/csswg-drafts/issues/2492) useful. I'm hard-pressed remembering the exact details, but you can look at the conversions in [culori](https://github.com/evercoder/culori). I think the errors in a rgb -> lab -> rgb roundtrip are now negligible, or at least don't produce a different hex code.

You can test with this sample code:

```js
let culori = require('culori');
let hex = culori.formatter('hex');

for (var r = 0; r <= 255; r++) {
    for (var g = 0; g <= 255; g++) {
        for (var b = 0; b <= 255; b++) {
            let c = {
                mode: 'rgb',
                r: r/255,
                g: g/255,
                b: b/255
            };
            let ret = culori.rgb(culori.lab(c));
            if (hex(c) !== hex(ret)) {
                console.log(hex(c), hex(ret));
            }
        }
    }
}
```
