### ISSUE TITLE
The Arabic-script part in Example 10.

### ISSUE THREAD

**Issue by ntounsi** [w3c/csswg-drafts#5281]
Two comments about the Arabic-script part of Example10 at [§5.2 ](https://drafts.csswg.org/css-text-3/#word-break-property)(https://drafts.csswg.org/css-text-3/#word-break-property)

1- The WAW letter و in "و کمی" is normally attached to it's next word کمی. There shouldn't be a space (nor a break opportunity) between them.
2- The Arabic translation should be وكذلك instead of وکمی.

**Comment by frivoal** [comment]
I believe this sentence fragment (`و کمی خط عربی`) is supposed to be Persian, rather than Arabic. I can't speak/read/write either language properly, but it seems to me that as a Persian phrase, it is correct. Do you think either or both of your comments still stand with the phrase being Persian rather than Arabic?

Maybe we could replace it with `و کمی خط فارسی` to make it less misleading to Arabic readers (assuming I got that right)?

**Comment by ntounsi** [comment]
> Maybe we could replace it with `و کمی خط فارسی` to make it less misleading to Arabic readers (assuming I got that right)?

You got it right. Misled by the sentence.  Keep it as it is.
