### ISSUE TITLE
Change three color names

### ISSUE THREAD

**Issue by XtinaSchelin** [w3c/csswg-drafts#5284]
[css-color-3]

The following three color names should be changed to the suggested new names:

* IndianRed to ChestnutRose
* Moccasin to Peach
* NavajoWhite to OldPaper

Those are the first ones I thought of. Changing them away from what they are now is the important part.

For the current list of color names, see:

https://www.w3.org/TR/css-color-3/

**Comment by dbaron** [comment]
This long list of color names exists not because we want it to be there, but because we're stuck with it for backwards compatibility.

I would be against creating any *new* color names to replace these existing ones.  Use of these names isn't good practice:  many of them are quite confusing and don't map to the colors people would expect them to map to.

I think we should use this issue to discuss whether to remove these names, without creating any new ones.

**Comment by gsnedders** [comment]
>This long list of color names exists not because we want it to be there, but because we're stuck with it for backwards compatibility.

Though perhaps we should alter the blue/green of NavajoWhite so it's not `#FFDEAD` if we think there's unlikely to be too many images trying to match it exactly (`#FFDFAE` increasing lightness from 83.9% to 84.2%?).

Would be nice to look at HTTP Archive and see how much usage we see of them.

**Comment by tabatkins** [comment]
Indian Red is named after a famous red pigment from India, and has no connection to Native Americans. 

Navajo White refers to the background color of the Navajo Nation flag.  I was under the impression that it was defined as the "official" color, but I can't find support for that now; slightly changing it to a less unfortunate hex code would probably be fine.

Moccasin has no particular special meaning, but also it's just the name of a type of shoe.

**Comment by gsnedders** [comment]
> Indian Red is named after a famous red pigment from India, and has no connection to Native Americans.

Arguments from etymology are pretty weak; it's hard to deny that both "indian" and "red" both have negative connotations in the US (especially combined!) and AFAICT many assume it is connecting to Native Americans without knowing otherwise. The only counterargument I've seen against renaming things using it is that to remove it effectively is writing out India.

> Navajo White refers to the background color of the Navajo Nation flag. I was under the impression that it was defined as the "official" color, but I can't find support for that now; slightly changing it to a less unfortunate hex code would probably be fine.

I can't find any official source more specific than "tan".

> Moccasin has no particular special meaning, but also it's just the name of a type of shoe.

I presume the potential objection comes from it being a type of (historically Native American) shoe, and an Algonquian loanword.

~~~

That said, along with any discussion about whether to remove these, an easier move we could do quickly is to deprecate them, as that at the very least signals a desire to remove them.

**Comment by Crissov** [comment]
@XtinaSchelin Your proposal is missing any argument or reasoning, although people are quick to jump to assumptions as to what they are.

**Comment by astearns** [comment]
We could officially deprecate these names in the spec, and allow user agents to stop supporting them (depending on usage)

**Comment by fantasai** [comment]
Going to second @crissov's point that the request to remove has zero justifications for it, and removing things from the Web platform really ought to have some significant rationale.

**Comment by tkore** [comment]
Ugh...

**Comment by tabatkins** [comment]
> > Indian Red is named after a famous red pigment from India, and has no connection to Native Americans.
> 
> Arguments from etymology are pretty weak; it's hard to deny that both "indian" and "red" both have negative connotations in the US (especially combined!) and AFAICT many assume it is connecting to Native Americans without knowing otherwise. The only counterargument I've seen against renaming things using it is that to remove it effectively is writing out India.

Right, etymology is only a minor part, but it's not nothing; if the name *did* have racist origins that would be a strong reason to change, but it doesn't at all.

So then the question is - is there any harm being done? I'm not aware of any racist usage of the color that would warrant a removal or rename.

I *am* supportive of adding a note to the spec *explaining* the name, because I also didn't know the source of the name before Alex Sexton's talk on the history of the color names.

> > Navajo White refers to the background color of the Navajo Nation flag. I was under the impression that it was defined as the "official" color, but I can't find support for that now; slightly changing it to a less unfortunate hex code would probably be fine.
> 
> I can't find any official source more specific than "tan".

Yup, that's my conclusion as well, so a minor change would probably be fine. And including it in the explanatory note would be good as well.

> > Moccasin has no particular special meaning, but also it's just the name of a type of shoe.
> 
> I presume the potential objection comes from it being a type of (historically Native American) shoe, and an Algonquian loanword.

I'm not sure what the objection there is, tho. English has a lot of loanwords from native languages; it doesn't *appear* to me that this one is being used in a problematic way. It's just the color of pale leather, which moccasins were made from.

------

I'll note that I have no attachment to any of the color names, and would be fine with deprecating most of them anyway. ^_^

**Comment by faceless2** [comment]
Removing or deprecating words of non-english origin needs solid justification. If they're offensive, deprecate them, but if not they should be left - otherwise, curiously, we'll be effectively whitewashing a list of colors.

**Comment by svgeesus** [comment]
> The Navajo Nation flag has a pale buff color background
https://www.discovernavajo.com/navajo-culture-and-history.aspx

The X11 color bears little relationship to the color on the actual flag; it seems instead to be a proprietary paint color:

> All the details about one of my favorite paint colors, Benjamin Moore Navajo White (not to be confused with Sherwin Williams color of the same name).
https://julieblanner.com/benjamin-moore-navajo-white/

However, these are color names which were already widespread by 1996 and eventually grandfathered in due to web compat; we can't therefore change the colors or change the names. We can deprecate them, and we can explain where the names come from if that helps.

**Comment by hober** [comment]
SVG also defines these colors (w3c/svgwg#805), so if we deprecate or remove them from CSS, we should do the same in SVG.

The Inclusion & Diversity Community Group is kicking off an effort to [review specifications for the use of oppressive or non-inclusive language](https://github.com/w3c/idcg/issues/15).

There is no cost to the CSSWG to deprecating color names. Removing support for color names in browser engines is a web compat question, of course, and one that we should investigate with usage counters. That said, discouraging their use in the spec is free. We should do so.

(hi @XtinaSchelin, it's been a loooooong time!)

**Comment by hober** [comment]
I should note that Crayola [renamed Indian Red to Chestnut](https://en.wikipedia.org/wiki/Indian_red_(color)) 21 years ago:

> At the request of educators worried that children (mistakenly; see [Etymology](https://en.wikipedia.org/wiki/Indian_red_(color)#Etymology)) believed the name represented the [skin color](https://en.wikipedia.org/wiki/Color_metaphors_for_race) of [Native Americans](https://en.wikipedia.org/wiki/Indigenous_peoples_of_the_Americas), Crayola changed the name of their crayon color *Indian Red* to *Chestnut* in 1999. [[5](https://en.wikipedia.org/wiki/Indian_red_(color)#cite_note-5)]

**Comment by TzviyaSiegman** [comment]
Thanks for raising this issue! I think it's important for us to signal awareness and sensitivity to the issues that the color names may raise, even if they were not intended.  I am seeing a lot of requests for explanations about why these should be deprecated, Those have been provided, Why shouldn't these be deprecated?

**Comment by frivoal** [comment]
I understand how the comments above explain why "IndianRed" is problematic, as it can be read with bad connotations, despite unrelated etymology.

I am not sure how this reasoning applies to "NavajoWhite". It's an odd name for a color, but I don't see how it's pejorative (and pretty much all css color names are odd). It includes the name of a people, but not in a stereotypical / disparaging way as far as I can tell.

I'm even less convinced about "Moccasin", which is just the name of an object. Sure, it is  a loanword, but so what? That doesn't make it into an offensive term. [Most words in English are loanwords](https://en.wikipedia.org/wiki/Lists_of_English_words_by_country_or_language_of_origin).

**Comment by wareid** [comment]
Agree with everything @hober and @XtinaSchelin have raised. I think it shows sensitivity to eliminate problematic colour names, even when it was unintentional. 

For `navajowhite` and `moccasin`, an additional issue is probably that they aren't particularly descriptive names for the colours? I noticed in looking at the list at large that most of the colour names are actually familiar or descriptive of the colour: `orangered` `mediumgreen` etc. To know that `navajowhite` is actually a shade of tan or that `moccasin` is closer to buff, you have to know those colours specifically. In this case I'd offer it's more effective to just rename them to something understandable as opposed to holding onto problematic language. 

I'd also add, since it's come up a few times that there's nothing wrong with `moccasin` since it's just a loan word, it's not the name of a colour in a different language, it's an item of footwear. I'd be comfortable with the loan word if it were a colour. Not to mention moccasins can come in a number of beautiful colours!

**Comment by Crissov** [comment]
@wareid A lot of the [X11 color names](https://en.wikipedia.org/wiki/X11_color_names) are utterly random or at least unsystematic. That has not been enough reason to deprecate (most of) them yet.

**Comment by frivoal** [comment]
There is wide agreement that the vast majority of color names in css are nonsensical / non descriptive / generally useless. They are kept not because we like them, but because they're necessary for web compat.

We're not going to rename them to better names, because we've given up on color names altogether. Those that are there are frozen as is for compatibility, and the policy for many years has been not to add or change anything. We even have [an entry about](https://wiki.csswg.org/faq#adding-more-named-colors) that in our (fairly short) FAQ.

Removing those that are merely nonsensical would result in dropping a large part of the list, which isn't doable. So, the fact that these are terrible names for colors is irrelevant. The whole set is terrible.

It may be desirable to list as deprecated those terms that are offensive. Note that depreciation in itself doesn't mean they won't be supported by browsers, just that the spec will describe them as such. Actual removal would requiring demostrating that this can be done without breaking sites, or convincing browsers that they should break sites, which is unlikely.

I still haven't seen an argument for why `navajowhite` and `moccasin` were offensive.

> I'd be comfortable with the loan word if it were a colour.

"chartreuse" is there as well, it's also a loanword, and it's also in reference to something that isn't a color in the original language (which is French, and in French it's the name of an type of alcohol, which is itself named after a place).

Again, all these color names are silly. That's not the same as offensive.

**Comment by svgeesus** [comment]
> Would be nice to look at HTTP Archive and see how much usage we see of them.

It would. Here is the preliminary result for navajowhite, which on mobile was found in 1,319 of  98,027,821 pages (13 ppm).

![image](https://user-images.githubusercontent.com/2506926/96714953-9714f300-13ab-11eb-8a77-fd62696ac3a0.png)

indianred is higher, at 7,139 of  98,027,821 pages and moccasin is rarely used, at 371 of  98,027,821 pages 

https://docs.google.com/spreadsheets/d/1sMWXWjMujqfAREYxNbG_t1fOJKYCA6ASLwtz4pBQVTw/edit#gid=279222916

**Comment by svgeesus** [comment]
Added a explanatory note, as there seems to be consensus for that:

> Note: these color names are standardized here, not because they are good, but because their use and implementation has been widespread for decades and the standard needs to reflect reality. Indeed, it is often hard to imagine what each name will look like (hence the list below); the names are not evenly distributed throughout the sRGB color volume, the names are not even internally consistent ( darkgray is lighter than gray, while lightpink is darker than pink), and some names (such as indianred, which was originally named after a red pigment from India), have been found to be offensive. Thus, their use is not encouraged.

Also on agenda for TPAC, which might result in deprecating some/all

**Comment by svgeesus** [comment]
> the fact that "orange" wasn't in the original HTML colors is such a weird historical wrinkle

BTW I also corrected the "originally from HTML". These colors were originally from the VGA graphics card. And there were exactly 16 of them, because those were the only colors you could get. Which is why orange, brown etc are not included.

**Comment by svgeesus** [comment]
@XtinaSchelin from the discussion in this thread, is it clear why we added an explanatory note but did not deprecate any colors?

And are you okay with the eventual result of your issue?

**Comment by svgeesus** [comment]
@hober @amyvdh @TzviyaSiegman are you okay with the eventual resolution of the issue?

**Comment by svgeesus** [comment]
> Would be nice to look at HTTP Archive and see how much usage we see of them.

[indianred is at 0.01% of color names](https://docs.google.com/spreadsheets/d/1sMWXWjMujqfAREYxNbG_t1fOJKYCA6ASLwtz4pBQVTw/edit#gid=279222916&range=A124:E124) while [navajowhite is 0.00%](https://docs.google.com/spreadsheets/d/1sMWXWjMujqfAREYxNbG_t1fOJKYCA6ASLwtz4pBQVTw/edit#gid=279222916&range=A223:E223) and [moccasin also 0.00%](https://docs.google.com/spreadsheets/d/1sMWXWjMujqfAREYxNbG_t1fOJKYCA6ASLwtz4pBQVTw/edit#gid=279222916&range=A305:E305)
