### ISSUE TITLE
[mediaqueries] Minor editorial issues

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5339]
Not wanting to hold up publication but also not wanting to lose sight of these editorial issues:

- [ ]  In response to [this comment](https://github.com/w3c/transitions/issues/255#issuecomment-661041464) about the date of HTML introducing media queries, I suggest

> In 1997, HTML4 [[HTML4]] defined a mechanism to support media-dependent style sheets,
	tailored for different <a>media types</a>.

- [x]   [XMLSTYLE]

    James Clark. Associating Style Sheets with XML documents. 29 June 1999. REC. URL: https://www.w3.org/1999/06/REC-xml-stylesheet-19990629/ 

This should be 

[XMLSTYLE]
    James Clark. Associating Style Sheets with XML documents 1.0 (Second Edition)
W3C Recommendation 28 October 2010 URL: https://www.w3.org/TR/2010/REC-xml-stylesheet-20101028/

_now fixed_ by changing `XMLSTYLE` to `xml-stylesheet`

the comment about the lack of a `media` pseudo-attribute [is now incorrect](https://www.w3.org/TR/2010/REC-xml-stylesheet-20101028/#PA-media)

_now fixed by deletion_

- [x]  The inlined biblio reference to Colorimetry, 3rd edition was blocking use of the [tobie specref entry for Colorimetry, 4th edition](https://api.specref.org/bibrefs?refs=colorimetry) (_now fixed by deletion_) (fix also solved the broken link)

**Comment by svgeesus** [comment]
[fixes](https://github.com/w3c/csswg-drafts/commit/c7bef3b78309d16409b4302f1fa916b0ce13a4f1)

**Comment by frivoal** [comment]
>  In response to [this comment](https://github.com/w3c/transitions/issues/255#issuecomment-661041464) about the date of HTML introducing media queries, I suggest
>
>> In 1997, HTML4 [[HTML4]] defined a mechanism to support media-dependent style sheets,
	tailored for different <a>media types</a>.

Added the date, but left the reference pointing to HTML4.01  rather than switching it to 4.0.  both have been revised since 1997, so that doesn't make much of a difference, and HTML4.01 is the "correct" way to refer to the 4 series. Admittedly, for a historical retrospective, pointing to the earlier document could be considered preferable, but that involves fighting with bikeshed, which would otherwise complain about pointing to obsolete version, and I don't think this is worth the trouble. I'm open to a deeper rewrite of the intro in Level 5, but for now, that feels enough.
