### ISSUE TITLE
[css-writing-mode] Why is writing-mode not inferred from the lang attribute?

### ISSUE THREAD

**Issue by zjopy** [w3c/csswg-drafts#5373]
(If this issue should instead be raised in [whatwg/html](https://github.com/whatwg/html), close this please).

Is there a reason, why the `writing-mode` of an element isn't inferred from its `lang` HTML attribute?

The `writing-mode` sets the block direction (e.g. top-to-bottom in English), while the `direction` sets the inline direction (e.g. left-to-right in English).

Now, `direction` is already inferred from the `dir` HTML attribute, because the inline direction is seen as a semantic property of the markup instead of the presentation, and therefore should be set in the HTML instead of by CSS. The CSSWG even discourages the use of `direction` over the `dir` attribute.

> Because HTML UAs can turn off CSS styling, we recommend HTML authors to use the HTML dir attribute and <bdo> element to ensure correct bidirectional layout in the absence of a style sheet. Authors should not use direction in HTML documents.

Why isn't the `writing-mode` similarly inferred from the `lang` HTML attribute? Why is the inline direction seen as semantic while the block direction is seen as presentational?

I know that some traditionally vertical languages like Chinese nowadays allow for both writing directions, but this doesn't mean that *all* vertical languages do this. I see no reason why defaulting the block direction to top-to-bottom is acceptable, when defaulting the inline direction to left-to-right is not.

**Comment by fantasai** [comment]
> I know that some traditionally vertical languages like Chinese nowadays allow for both writing directions, but this doesn't mean that all vertical languages do this.

For the overwhelming majority of vertical writing system usage, it is optional. And and with regards to the rest, the existing reality is that the page defaults to horizontal writing for several decades now. If we tried to infer from the lang tag, there's a decent chance we would break pages that are expecting horizontal writing mode. If vertical writing were part of the Web in the early days, we could have incorporated such auto-styling, but I suspect at this point, we can't.

Though, if it can be statistically shown that 99.99% of e.g. Mongolian pages are already setting themselves to vertical-lr, then you might have a case for making it part of the default settings.

> when defaulting the inline direction to left-to-right is not.

We do in fact default the inline direction to LTR, though. It's HTML that sets it otherwise. Technically this is an HTML default style sheet issue.
