### ISSUE TITLE
[css-om-view] Example 3 shows a bad way to check for HDR

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#5378]
https://drafts.csswg.org/cssom-view/#dom-screen-pixeldepth

Example 3 does not demonstrate a good way to check for HDR. Screen depth and color profile are insufficient; HDR is about brightness range, not color depth.

**Comment by svgeesus** [comment]
Simon is completely correct. While it is common for HDR to also use WCG, most WCG setups are not HDR. The lowest conformance level of the [DisplayHDR 1.1 specification](https://displayhdr.org/performance-criteria-cts1-1/) is satisfied with 8 bits per component (actual, not 6bits plus dithering), sRGB gamut.

As Simon says, luminance range is the crucial factor. Again looking at the DisplayHDR 1.1 specification, the lowest conformance level specifies a peak small-area luminance of at least 400 cd/m2 and a maximum black level of 0.4 cd/m2 giving a 1000:1 luminance range.

I would like to suggest a way to actually detect HDR using CSS OM View, but don't see a way to do so. 

I then tried to modify it to check for WCG (P3, which is best with 10 but can use 8 bits) or UltraWCG (2020 or 2100, which is best with 12 and a minimum of 10; but only TVs and set-top-boxes would pass and they don't expose that info to CSS) so that would not be a good example either.

Thus, unfortunately, the example is probably best deleted.
