### ISSUE TITLE
[css‑text‑4] Multi‑value `white‑space` syntax proposal

### ISSUE THREAD

**Issue by ExE-Boss** [w3c/csswg-drafts#5382]
Like how `display` now has a two value syntax, I’d like to propose a similar addition to the `white‑space` property:

## <code id="propdef-white-space">white‑space</code>

**Syntax:** <code>\[ [&lt;'text‑space‑collapse'&gt;] [||] [&lt;'text‑space‑trim'&gt;] [||] [&lt;'text‑wrap'&gt;] \] [|] [&lt;white‑space‑legacy&gt;]</code>

### <code id="typedef-white-space-legacy">&lt;white‑space‑legacy&gt;</code>

**Syntax:** <code>normal [|] pre [|] nowrap [|] pre-wrap [|] break-spaces [|] pre-line</code>

| `<white‑space‑legacy>` | <code>[&lt;'text‑space‑collapse'&gt;]</code> | <code>[&lt;'text‑space‑trim'&gt;]</code> | <code>[&lt;'text‑wrap'&gt;]</code>
| --- | --- | --- | ---
| `normal` | `collapse` | `none` | `wrap`
| `pre` | `preserve` | `none` | `no-wrap`
| `nowrap` | `collapse` | `none` | `no-wrap`
| `pre-wrap` | `preserve` | `none` | `wrap`
| `break-spaces` | `preserve` | `none` | `wrap`
| `pre-line` | `preserve‑breaks` | `none` | `wrap`

## <code id="propdef-text-space-collapse">text‑space‑collapse</code>

**Syntax:** <code>collapse [|] discard [|] preserve [|] preserve‑breaks [|] preserve‑spaces</code>

## <code id="propdef-text-space-trim">text‑space‑trim</code>

**Syntax:** <code>none [|] \[ trim‑inner [||] discard‑before [||] discard‑after \]</code>

## <code id="propdef-text-wrap">text‑wrap</code>

**Syntax:** <code>wrap [|] no‑wrap[^1] [|] balance [|] stable [|] pretty</code>

[||]: https://drafts.csswg.org/css-values-4/#comb-any
[|]: https://drafts.csswg.org/css-values-4/#comb-one
[&lt;'text‑space‑collapse'&gt;]: #user-content-propdef-text-space-collapse
[&lt;'text‑space‑trim'&gt;]: #user-content-propdef-text-space-trim
[&lt;'text‑wrap'&gt;]: #user-content-propdef-text-wrap
[&lt;white‑space‑legacy&gt;]: #user-content-typedef-white-space-legacy
[^1]: https://github.com/w3c/csswg-drafts/issues/5376

**Comment by faceless2** [comment]
Thanks for suggesting this - I agree, this is a good idea for several reasons:

1. It's consistent with how other shorthand properties are handled.
2. It gives forward compatibility for the `white-space` property. If we don't do this, the `white-space` will be able to set some combinations of its components, but not all. This will eventually lead to be becoming a sort of legacy property, which I don't think we want.
3. It's removing one level of magic from the shortcuts - "pre" is just s shorter way of writing "preserve none nowrap", which is easier to explain than saying it sets `text-space-collapse` to preserve, `text-space-trim` to none and `text-wrap` to no-wrap.

I'm unconvinced on the value of renaming "nowrap" to "no-wrap" as part of this move - in particular, because it would make both `white-space: nowrap` and `white-space: no-wrap` evaluate to the same result. This could lead to a very confusing transition period until css-text-4 is fully implemented. But otherwise, great idea.

**Comment by fantasai** [comment]
I think this makes sense, but we need to have some mapping for `break-spaces` that isn't the exact same mapping as `pre-wrap` since they have different behavior. :)

**Comment by kojiishi** [comment]
> we need to have some mapping for `break-spaces`

https://github.com/w3c/csswg-drafts/issues/3794

**Comment by cdoublev** [comment]
If I am not mistaken, this proposal seems to have been recently integrated via https://github.com/w3c/csswg-drafts/commit/4717dbcb83634fb108e36bd5846dd5942cd539a0.

When `white-space` is not specified with a *special keyword* (`<white‑space‑legacy>`), I assume that sub-properties that are not given a value matching their syntax reset to their initial value?

**Comment by fantasai** [comment]
@cdoublev Yes, good catch. Clarified in https://github.com/w3c/csswg-drafts/commit/b1f31d0e1dd20b09826bdb0b6c9711e97e5a06ae

**Comment by fantasai** [comment]
This is now edited into the ED at: https://drafts.csswg.org/css-text-4/#white-space-property
Agenda+ to ask the WG for review, if this is indeed what we want.
