### ISSUE TITLE
[css-text] Reconsider the resolution on #855

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5410]
In #855 it was resolved that CR gets treated as any other control char, but looking at the history, we had to make it render invisible in https://bugzilla.mozilla.org/show_bug.cgi?id=941940 for compat reasons.

It seems Gecko and WebKit render it invisible, and Blink just treats lone CRs as an space. Probably both behaviors are acceptable compat-wise, but that doesn't match the spec.

cc @jfkthame @litherum @kojiishi

**Comment by kojiishi** [comment]
> Blink just treats lone CRs as an space

Can you tell me how you tested this? I debugged:
https://github.com/web-platform-tests/wpt/blob/master/css/css-text/white-space/control-chars-00D.html
and we don't seem to render anything.

**Comment by emilio** [comment]
@kojiishi this test-case:

```html
<!doctype html>
<p>A&#013;B</p>
```

Renders a space between `A` and `B` in Blink, afaict, while WebKit and Gecko just render `AB`.

**Comment by fantasai** [comment]
I don't care what we decide here, but if we resolve on making it “invisible” please make sure it's defined [exactly what that means](https://github.com/w3c/csswg-drafts/issues/855#issuecomment-370370796).

**Comment by kojiishi** [comment]
> this test-case:

Thank you, confirmed that LayoutNG handles lone CR as a collapsible space, in [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/835947/) which refers to CSS Text but I can't find the definition any longer. [CSS2](https://www.w3.org/TR/CSS21/text.html#white-space-prop) has it, so maybe it was removed after we implemented LayoutNG?

The `control-chars-00D.html` test doesn't reveal this because it's a collapsible space, and it is collapsed in the test.

I think we can try to change this. Can you and @litherum tell me how you handle it?

**Comment by frivoal** [comment]
cc @jfkthame @litherum @kojiishi @emilio @fantasai (see previous comment)

**Comment by fantasai** [comment]
Personally, I suspect treating it as a visible space is easiest if we want to get interop. There are just way too many ways to make something 'invisible'.

**Comment by frivoal** [comment]
Agenda+ to propose resolving onto making lone CRs be treated as visible spaces, based on the results of https://github.com/w3c/csswg-drafts/issues/5410#issuecomment-686501195 and subsequent comments.
