### ISSUE TITLE
[css-inline-3] text-box-trim accumulation

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5426]
We allow ancestors to affect leading trimming on descendants, so that common cases like

```
<div class=warning style="borders and padding and leading-trim">
  <p>This is just a paragraph. Maybe this line is <p>, or not, it could be anything.
</div>
```
will work for authors. But we don't specify what happens if various ancestors have different values for `leading-trim`.

Maybe we should do something similar to `break-before` and switch to an auto/no/yes model where auto does whatever the ancestor says and otherwise the innermost value wins?

**Comment by fantasai** [comment]
Since it came up during today's call, here's a link to the presentation Ethan and I gave at ATypI two years ago on this topic: https://fantasai.inkedblade.net/style/talks/atypi-2021/ (You'll want the MP3 file.) There's also an earlier one, a bit less developed but broader scope, from CSS Day in 2019 at https://www.youtube.com/watch?v=OtlGo48iTOk

**Comment by johannesodland** [comment]
I was just looking into how to solve text-box-trim on the first/last blocks in a section or article, and having the possibility to set `text-box-trim: auto` would solve that use case, if I understand you correctly. 

```html
<section>
  <h2>A title</h2>
  <p>A paragraph</p>
  <p>Another paragraph</p>
</section>
```

```css
section {
  text-box-trim: both;
  text-box-edge: auto;
}

h2, p {
  text-box-trim: auto;
}
```

Would `auto` result in a used value of `start` for the h2, and `end` for the last paragraph?

**Comment by fantasai** [comment]
@johannesodland Yes. This is actually the currently-specced behavior, but there's no conflict resolution specified if both of them specify a text-box-trim value. :)

**Comment by chrishtr** [comment]
I propose that we go with "take metric from closest that asks for trimming" among the three listed from the meeting notes. I don't think we need any new keyword values.

More precise wording: a line is trimmed according to the `text-box-trim` property of its nearest ancestor that specifies `text-box-trim`. (Note: if the line is not the one affected--e.g. not the first or last line under that ancestor, depending on the value of `text-box-trim`--it is unaffected.)

Note: we don't need this spec language for `text-box-edge`, because it's inherited.

Note: This is different than inheritance, because it only applies to the first line of any descendant of the ancestor, not to all first lines of different paragraphs. The line referred to by `text-box-trim` is similar to `::first-line` ([example](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Adiv%3A%3Afirst-line%20%7B%20color%3A%20red%20%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%3E%0A%20%20%3Cp%3E123%3Cbr%3E456%0A%20%20%3Cp%3E123%3Cbr%3E456%0A%20%20%3Cp%3E123%3Cbr%3E456)).

**Comment by fantasai** [comment]
Taking the innermost metric probably is pretty easy to understand. I'm just worried we'll have a problem like we do with collapsed table borders, where the obvious thing was to have the innermost (“most specific“) win, but it actually works out to not do the right thing on most tables. :]

(The example is, btw: same-width solid borders applied to the table, row group, and cells, with the cells being gray and the table/row group being black. [Similar to this.](https://www.w3.org/TR/css-writing-modes-4/#logical-to-physical) You end up with all-gray borders, which isn't want you want: it's actually the outer elements that you want to win here, because the borders that coincide with them are the “most special”.)

**Comment by chrishtr** [comment]
> Taking the innermost metric probably is pretty easy to understand. I'm just worried we'll have a problem like we do with collapsed table borders, where the obvious thing was to have the innermost (“most specific“) win, but it actually works out to not do the right thing on most tables. :]

My suggestion is to resolve on this behavior in the spec because it's easy enough to understand, prototype it in a browser engine, and then ask developers to try it and gather their feedback. If they find problems we can reconsider the semantics.

**Comment by frivoal** [comment]
I think that while tentatively implementing "the right thing" even if we're not sure if it's going to be web-compatible and reverting if it isn't can often be a good idea, shipping a thing which may not be the best approach and changing later it if people don't like it is a lot dicier, as we may be trapped by compat by then, even if we do conclude that the alternative behavior would have been better.

Now, if it's about implementing without shipping in order to let people experiment with prototypes, sure. But then I don't think it needs to be in the spec.

**Comment by jantimon** [comment]
I am not sure if I understood the discussion result correctly.

When nesting different elements with different line-heights, the height of the largest line-height is used for the entire group.

For me as developer it would be most intuitive if text-box-trim would behave in a similar way.

Here are two examples and in both examples the largest font-size should be used for the trim calculation:


`<h1><span style="font-size:120%">` (trimmed to the span)

![inner element has larger font](https://github.com/w3c/csswg-drafts/assets/4113649/bb12241a-43b7-4b2e-928a-12261c7e1a82)

`<h1><span style="font-size:80%">` (trimmed to the h1)

![inner element has smaller font](https://github.com/w3c/csswg-drafts/assets/4113649/88e51f88-6496-441b-9a1a-553fc64d8712)

**Comment by kojiishi** [comment]
Thank you @jantimon for the great feedback. Let me explain my understanding of the resolution.

The #8829 resolved to split the line-box-affecting aspects of `text-box-edge` to a new property (name TBD, tentatively called `text-line-edge`). So, this issue is about multiple _block_ ancestors having different `text-box-edge` properties, as in the examples of the first two comments of this issue. Here's another more artificial example to explain the resolution:
```html
<div style="text-box-trim: both; text-box-edge: text">
  <div style="text-box-edge: leading">
    <div style="text-box-edge: cap text">FIRST</div>
    <div>MIDDLE</div>
    <div style="text-box-edge: text alphabetic">LAST</div>
  </div>
</div>
```
Since the resolution is "innermost", the top of the "FIRST" should be trimmed at the `cap` edge, and the bottom of the "LAST" should be trimmed at the `alphabetic` edge.

The split in #8829 made applying `text-box-trim` and `text-box-edge` to `<span>` in your examples to have no effects, so your examples will not be impacted by the resolution of this issue.

When we start discussing `text-line-edge`, I think your feedback is one of the most important points to discuss about.

@fantasai Please correct me if any.

**Comment by jantimon** [comment]
thanks @kojiishi for your quick response - so it is not `inline` but about `block` siblings / children?

in that case "innermost" makes perfect sense for many different scenarios e.g. optical vertical text centering:

<img width="962" alt="center-click-me" src="https://github.com/w3c/csswg-drafts/assets/4113649/55efd6e9-86b2-485a-a940-872574786987">

**Comment by bakura10** [comment]
Hi,

I'm not sure if this is related to this issue, but I'm facing a strange output and I'm not able to understand if this is expected or not (and if it is, this is extremely unintuitive): https://codepen.io/bakura10/pen/GgKMvqR

I'm applying the text-box on the parent, so the container now no longer wrap the content. I've tried to set the text-box on the button, but this does not seem to work.

<img width="418" alt="image" src="https://github.com/user-attachments/assets/0f793d56-ce5a-4629-8eb9-0213b1c930d0" />

Ideally, this is the end result I would like:

<img width="416" alt="image" src="https://github.com/user-attachments/assets/c8f524ef-d8d2-4e33-aeeb-32a0c53b7d43" />

I can of course use trim-start instead of trim-both, but I don't control the content, so the last element might be something different than a button.

**Comment by kojiishi** [comment]
@bakura10 IIUC it's the expected behavior, works the same in Blink and WebKit. As you pointed out, you'll need to use `trim-start`.

But it's also true that the WG may have missed some use cases. I think filing a new issue is helpful to get attentions.
