### ISSUE TITLE
[css-logical-1] Editorial: Correspondence diagrams

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#5505]
1. Introduction
https://drafts.csswg.org/css-logical-1/#intro

Could you add ids to the figures, so that they can be linked to?

It would be nice if these were slightly bigger - maybe ignore the margin of the page.

It would also be nice to show diagrams for Arabic/Hebrew and for Mongolian, to complete the set.

The caption for fig 3 says 'in typical Chinese layout', however, Mainland Chinese is typically horizontal, and so is much of Taiwanese text.  So maybe just say "in typical vertical CJK text layout".

Maybe have the the English fig on the left in this English page, since it sets a recognisable baseline.

**Comment by fantasai** [comment]
> Could you add ids to the figures, so that they can be linked to?

There actually is one already, #mapping-diagram. But the source of the diagrams, and the definitions for all these things, is Writing Modes so if you're linking probably it would make more sense to link there? Maybe in Writing Modes I could promote the figures to the top-level Abstract Box Terminology section to make that more convenient; they're in the flow-relative subsection atm. 

> It would be nice if these were slightly bigger - maybe ignore the margin of the page.

The corresponding diagrams in the Writing Modes are larger. I think here it's nicer to keep them side-by-side, since we're just reminding people, not defining anything here.

> It would also be nice to show diagrams for Arabic/Hebrew and for Mongolian, to complete the set.

I wouldn't mind adding those to Writing Modes, but I think here that would be a bit extra?

> The caption for fig 3 says 'in typical Chinese layout', however, Mainland Chinese is typically horizontal, and so is much of Taiwanese text. So maybe just say "in typical vertical CJK text layout".

Went with s/typical/vertical/ since the example is very specifically Chinese.

> Maybe have the the English fig on the left in this English page, since it sets a recognizable baseline.

Makes sense. Fixed.

**Comment by r12a** [comment]
Btw, one additional nit:

> The following code examplify

should probably be

> The following code ex**e**mplif**ies**

**Comment by fantasai** [comment]
Fixed, thanks. :) Otherwise
