### ISSUE TITLE
[web-animations-1] Expect iterationStart to not be NaN

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#5507]
`iterations` and `duration` are expected to not be `NaN`, but not `iterationStart`. Is there a reason for this or is it just missing?

https://drafts.csswg.org/web-animations-1/#update-the-timing-properties-of-an-animation-effect

Currently in Chrome:

```js
new KeyframeEffect($0, { opacity: [0, 1] }, { iterationStart: NaN })
// Uncaught TypeError: Failed to construct 'KeyframeEffect': The provided double value is non-finite.
new KeyframeEffect($0, { opacity: [0, 1] }, { iterations: NaN })
// Uncaught TypeError: Failed to construct 'KeyframeEffect': iterationCount must be non-negative
```

EDIT: and same question for all properties of `EffectTiming` or more exactly, why are they not validated?

**Comment by birtles** [comment]
> `iterations` and `duration` are expected to not be `NaN`, but not `iterationStart`. Is there a reason for this or is it just missing?

Yes, `iterations` and `duration` have type [`unrestricted double`](https://heycam.github.io/webidl/#idl-unrestricted-double) so they can take values like `Infinity` and `NaN`. That's because those values need to be able to represent infinity.

`iterationStart`, however, has type `double` so it can't take such values. Validation that `iterationStart` is not `NaN` happens at the WebIDL binding layer and so no additional spec text is required.

> ```js
> new KeyframeEffect($0, { opacity: [0, 1] }, { iterations: NaN })
> // Uncaught TypeError: Failed to construct 'KeyframeEffect': iterationCount must be non-negative
> ```

(That's odd that Chrome reports an error for `iterationCount` when validating `iterations`.)
