### ISSUE TITLE
[compositing] SDR and HDR compositing

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#554]
> The question of where to map the SDR / sRGB luminance range when compositing with HDR is unsolved. It may be that for consistent results across platforms this needs to be specified.

**Comment by frivoal** [comment]
Also, if my understanding is correct (and it very well may not be), the problem with that is that HDR luminance is an absolute scale, while SDR is a relative one (relative to a white diffuser). If we map SDR to HDR, it means we absolutize the luminance range of SDR, which leaves us with the question of what to do when the user/OS wants to adjust the screen brightness, or similarly, how to display the SDR range on screens whose peak brightness is less than the one we picked as the absolute luminance of the white diffuser. Also, this would prevent us from boosting the luminance of SDR content to view it in a bright environment.

The alternative of making the HDR luminance scale relative to the white diffuser, and therefore no longer having an absolute luminance, seems to have fewer practical downsides, even if it is theoretically just as wrong.

Or maybe we just let HDR fall where it should, and say that the luminance of the SDR white diffuser should be `min(peak screen brightness at current settings, 300nt)`

**Comment by svgeesus** [comment]
Related (HDR compositing in ttml) https://github.com/w3c/ttml2/issues/233

**Comment by palemieux** [comment]
> the problem with that is that HDR luminance is an absolute scale,
> while SDR is a relative one (relative to a white diffuser).

sRGB defines a reference display with a luminance level of 80 cd/m^2 (see Section 4.1 at IEC 61966-2-1), so I would not characterize sRGB as relative to a white diffuser.

Both sRGB and Rec 2100/PQ (HDR) content are effectively mastered against an absolute scale. They are also both experienced, by the end-users, on a wide range of displays with different luminance characteristics.

> If we map SDR to HDR, 

@frivoal It would be good to list the use cases where this might happen in order to best answer the question of what peak luminance level should be used when compositing SDR and HDR content a common plane. Did you have specific ones in mind? In the case of subtitles/captions, it is necessary to allow the author to specify that peak luminance level to ensure the right experience. In the long-run, subtitle/captions should ideally be specified using HDR pixels natively (instead of being specified in sRGB and composited using a gain value).

**Comment by mwatson2** [comment]
PQ is display referred (absolute luminance) but that doesn't mean that HDR in general is.

The basic problem is that on a linear [0-1.0] scale, 1.0 means something different for HDR vs SDR. In general, to composite, we need to know for a given HDR data source where the HDR peak white luminance should be relative to SDR peak white (or vice versa). Put another way, since SDR peak white is "page white" / "diffuse white" whereas HDR peak white is for specular highlights you arguably need to give the use two screen brightness controls (which Windows effectively does).

If the source data is PQ the peak luminance (1.0 in linear space) is known to be 10,000 nits, but in general some other source of metadata is needed to specify either absolute or relative-to-SDR luminance.

We have been able to [solve this problem](https://medium.com/netflix-techblog/enhancing-the-netflix-ui-experience-with-hdr-1e7506ad3e8) using an ICCv4 profile to specify BT.2020 colorspace and 16-bit 2.2 gamma coded pixel data and then using the ICC lumi tag to specify the absolute peak luminance of that signal. The pixel data could instead be PQ or HLG coded - using less bits per pixel - but these are not easy to include in ICC profiles because either you need to include massive LUTs or use the new calculator capability.

**Comment by svgeesus** [comment]
This is [now solved in CSS Color HDR](https://drafts.csswg.org/css-color-hdr/#Compositing-SDR-HDR) with a section entitled **Compositing SDR and HDR content** which in turn references ITU Rec.2408-0.

This places the diffuse white for all SDR RGB colorspaces as defined in Rec.2408:

> Relative HDR, using the HLG transfer function, must map SDR media white to the same luminance as is used to display the 75% HLG value.

and

> Absolute HDR, using the PQ transfer function, should map SDR media white to 140 cd/m², the same luminance as is used to display the 54% PQ value. However, implementations may chose to incorporate a color re-rendering step (OOTF) to account for non-reference viewing conditions.

**Comment by svgeesus** [comment]
and further corrected by [replacing the old Dolby suggestion of 140 cd/m2 with Rec.2408 203 cd/m2](https://github.com/w3c/csswg-drafts/commit/629b25d439a90a985c8028759361726d3b7b8f48)
