### ISSUE TITLE
[css-overflow] CSSOM scrollWidth/scrollHeight behaviour of "overflow: clip".

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#5572]
Consider:

```html
<!DOCTYPE html>
<div id="target" style="width: 50px; height: 50px; overflow: clip;">
  <div style="width: 100px; height: 100px; background: lime;"></div>
</div>
<script>
console.log(target.scrollWidth);
console.log(target.scrollHeight);
</script>
```

What should the console log?

FF currently logs `100`, we Blink currently log `50` as we saw some additional performance opportunities (and it isn't "scrollable" like other overflow types), but happy if this should be `100`.

**Comment by bfgeek** [comment]
cc/ @emilio @tabatkins

**Comment by x-Jake-x** [comment]
The draft currently says 

> ISSUE 3: should overflow: clip also clip the scrollable overflow or should it remain a pure paint-time operation, which would mean that scrollable overflow, while invisible, would still be scrollable.

but it also says

> `clip` This value indicates that the box’s content is clipped to its overflow clip edge and that no scrolling user interface should be provided by the UA to view the content outside the clipping region. In addition, unlike overflow: hidden which still allows programmatic scrolling, overflow: clip forbids scrolling entirely, through any mechanism, and therefore the box is not a scroll container.

My first impression is that `scrollWidth` and `scrollHeight` should be able to be retrieved programmatically in order to determine to what extent something can or should be scrolled. Since `clip` by definition seems to indicate it cannot be scrolled, the "50" that @bfgeek mentions above seems to make sense.

HOWEVER -- if we look at ISSUE 3 a bit more technically -- it seems like it would completely redefine the `clip` value entirely by saying "This IS a scrollable container, but scrolling to the end of the overflow area would not show more of the content that was previously clipped." I can't think of a practical use case for this, but that doesn't mean there isn't one.

As an impractical use case (at least impractical to me at the moment), the draft also says:

>The scrollable overflow area is the union of: 
>the box’s own content and padding areas

When we say "the box's own content" -- are we referring to elements, text, etc. within the parent box -- and is background considered part of that "content"? If background is not defined as part of content, then allowing ISSUE 3 to define `clip` as a pure paint-time operation and be scrollable would have to programmatically allow the scroll of the area in such a way that additional parts of the background could be revealed while simultaneously shrinking and shifting the box content -- think a "parallax" effect around the content -- at which point the "100" seems to make more sense to me.

**Comment by emilio** [comment]
cc @MatsPalmgren, I think returning 100 is just a bug. Per the blame on https://bugzilla.mozilla.org/show_bug.cgi?id=833542 the intention seemed to be that it behaves as if it was `overflow: hidden`.

**Comment by emilio** [comment]
(And moderately sure we clip the scrollable overflow for layout)

**Comment by bfgeek** [comment]
`overflow: hidden` element are scrollable as which is why `100` for them makes sense, e.g. they respect `scrollTop` etc (`overflow: clip` doesn't respect `scrollTop` etc).

I'm fine with returning `100` here for `clip` as well, the additional optimisation if you have `clip` in both axis is that you can skip the scrollable-overflow calculation (I'm pretty sure), but this isn't a big deal.

**Comment by x-Jake-x** [comment]
An example of what actually happens with clipped content:

https://jsfiddle.net/mq85u93s/

**Comment by x-Jake-x** [comment]
An example using explicit JS instead of CSS animations, and moving the contents of the clipped area instead of the background of the containing box:

https://jsfiddle.net/pzxrscbq/

**Comment by x-Jake-x** [comment]
Note that these behaviors do not use the "scrollLeft" property, which seems to be correctly restricted, so perhaps they do not actually count as scrolling -- but do UAs actually treat them as clipping?

**Comment by MatsPalmgren** [comment]
Blink's behavior seems more useful since any overflow is clipped and isn't seen as `scrollable overflow` by the parent, unlike an overflowing `overflow:visible` element.  I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1668714 to fix this in Gecko.

It's worth noting that `clip` may apply in just one of the axes in which case we should include any overflow in the other (`visible`) axis.

Gecko also have [a number of cases](https://searchfox.org/mozilla-central/rev/222e4f64b769413ac1a1991d2397b13a0acb5d9d/layout/generic/nsIFrame.cpp#11238) where we treat `hidden` as `clip`, and `contain:paint` + `overflow:visible` as `overflow:clip` etc.  I'll exclude those too for now.

**Comment by x-Jake-x** [comment]
It sounds like [Issue 3](https://drafts.csswg.org/css-overflow-3/#issue-3eeb0988) is moot, in that case, as clipped content wouldn't be seen as scrollable.

This seems to me as though this makes the only difference between `clip` and `hidden` to be that `clip` is considered non-scrollable, while `hidden` is considered programmatically scrollable.

Was the intent at any point to make it so that content in a clipped overflow would be clipped by the containing element's box, permanently, so that it would never show? Or was the intent to simply deal with scrolling using "scrollLeft" and "scrollTop", continuing to leave the contents programmatically manipulable in a simulated scrolling fashion (as in the above examples) using means other than scrolling?

It sounds like the decision to limit the "scrollWidth" and "scrollHeight" to the area of the containing elements box makes sense, as the element would technically be "not scrollable" (despite the not visible contents still being available through programmatic manipulation). However, I feel like this removes an easy way to determine the width and height of the content of the containing element, which still exist despite "clip" being set. Child elements of a clipped container would need to be contained inside another non-clipped element to easily get their total "scrollWidth" and "scrollHeight".

...I wanted to create an example to demonstrate this to myself, but I can't because `Chrome/85.0.4183.123` and `Chrome/85.0.4183.121` report the full width of the content area of the containing element. They don't limit it just the width of the containing box. Where can I test what Blink is currently doing @bfgeek?

Here is my base test case for what you gave: https://jsfiddle.net/6hfgm4yx/

**Comment by bfgeek** [comment]
> Where can I test what Blink is currently doing

On Chrome M88 you'll need to pass `--enable-blink-features=OverflowClip` in the command line.

Ian

**Comment by bfgeek** [comment]
@emilio @MatsPalmgren What is your behaviour if `contain: paint` instead of `overflow: clip` ?

**Comment by x-Jake-x** [comment]
Ah -- whether it's `contain: paint` or `overflow: clip`, the child elements maintain their "scrollWidth" and "scrollHeight". In that respect, you're not really losing the ability to calculate what the size is for the interior of the container.

https://jsfiddle.net/6dcj0fye/

It really does feel like it should be 50 and not 100 in that case.

Really, I'd think this should be `overflow: noscroll` instead of `overflow: clip` to be more semantically indicative of what is happening -- you cannot use specific scrolling functionality with it in JS, it is not considered a scrolling container, it is not related to clip-path (which still allows scrolling with `overflow: scroll`: https://jsfiddle.net/dgs71mo5/ and maintains the calculated scrollWidth and scrollHeight of its child elements) -- but I guess that ship has long since sailed.

**Comment by tabatkins** [comment]
`overflow:clip` is meant to be like `overflow:visible`, except it hides stuff. It's *analogous* to how `overflow:hidden` is like `overflow:scroll`, but yeah, `clip` is very explicitly *not* scrollable.

So the answer here should be that `clip` returns the same value as `visible` does, whatever that is.

**Comment by x-Jake-x** [comment]
In that case, `clip` and `visible` currently behave differently in Blink with the Chromium `--enable-blink-features=OverflowClip` argument:

https://jsfiddle.net/p8e769r5/

**Comment by emilio** [comment]
Well sorting that out is the point of the issue.

Upon reflection I tend to agree with @tabatkins... I see how actually clamping the value could be useful, but also I tend to agree that it probably shouldn't behave differently than `visible`...

**Comment by x-Jake-x** [comment]
Well, what exactly is the intention of the values reported in scrollWidth and scrollHeight?

**Comment by emilio** [comment]
So they only really make sense on scroll containers, and they return the size of the scrollable area. But we need to return stuff there for compat even if you're not a scroll container. The idea for `overflow: visible` is that they return the sizes that it would've returned would it be a scroll container. So if we follow the same logic `clip` should probably be the same.

**Comment by chrishtr** [comment]
The resolution made was that 50 is the correct answer in this example, and Firefox & Chrome already have that behavior.

Does the spec need to be edited to clarify this also? My impression is no.

**Comment by tabatkins** [comment]
No, the resolution was that it should match `visible`, and thus be 100 in the OP's example.

Looking over CSSOM View, I'm pretty sure that nothing needs to be done here - the [scrolling area](https://drafts.csswg.org/cssom-view/#scrolling-area) calculations don't reference the 'overflow' value at all, and from my reading should indeed give the same value regardless.
