### ISSUE TITLE
[css-contain] contain:size needs to mention its effect on aspect-ratio

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#5585]
[Contain 1, section 3.1 currently says:](https://drafts.csswg.org/css-contain/#containment-size)

> Replaced elements must be treated as having an intrinsic width and height of 0.

However, it makes no mention of the element's aspect ratio. I believe the ideal behavior is to treat the element as not having an intrinsic aspect ratio.

(This was brought up in #5550)

Agenda+ because this is a Rec-level spec now. ^_^

**Comment by fantasai** [comment]
Fixing this will close https://github.com/w3c/csswg-drafts/issues/5550

**Comment by frivoal** [comment]
I agree on the substance of of the issue, and think we should fix this in L2. 

However, I'm not sure we need to patch it up in the Level 1 spec as well, rather than just in the Level 2. As I see it, there's nothing wrong to be fixed in L1, it just doesn't define a particular thing, which will now be defined in the next level. We should absolutely go back and fix mistakes / contradictions in earlier levels, but having earlier specs be a tad vague, and later ones be more specific seems perfectly normal to me.

It's not particularly hard to fix l1 as well, so I won't object if y'all insist, but I just don't see the need.

**Comment by frivoal** [comment]
@fantasai said on IRC:
> I think it's a mistake in L1 to have not mentioned it
> That means it's not affected
> It's a concept that's existed in much earlier specs
> not something new
> so by leaving it out, that implies it's not affected

Good point, I now agree. :)
