### ISSUE TITLE
Revisiting standardization of the `zoom` property 

### ISSUE THREAD

**Issue by dlibby-** [w3c/csswg-drafts#5623]
As far as I can tell the last time this was discussed in depth was back in [2015](https://lists.w3.org/Archives/Public/www-style/2015May/0282.html). At the time there appeared to be consensus that it would have been better had the property never existed, and there was not a strong preference for standardizing the current implementations. However, usage on the web appears to be non-zero and relatively steady &mdash; I'd like to open another discussion on whether there is a path towards standardization.

Here is [Chrome's UseCounter data](https://chromestatus.com/metrics/feature/timeline/popularity/3578) for the percentage of pageloads where a zoom value that is not 1 (or 100%) is applied to any element during the style cascade. As of the opening of this issue it stands around 1% of pageloads.

I'm thinking that this would start mainly as a documentation effort (@atanassov went through this exercise previously [here](https://cdn.rawgit.com/atanassov/css-zoom/master/Overview.html)) &mdash; given that IE and legacy Edge are on their way out, I'm cautiously optimistic that the WebKit and Blink implementations are similar enough that there will only be a handful of behavioral differences to reconcile, if any.

One item of particular note is that Gecko does not implement zoom (see https://bugzilla.mozilla.org/show_bug.cgi?id=390936). There are unique challenges given that authors have used a `-moz-transform: scale(n)` fallback in the absence of zoom. Additionally, I believe there were attempts to implement zoom in terms of transforms but that was not sufficient to alleviate compat concerns.

In terms of use cases, similar to how browsers have both pinch zoom and page zoom, this does seem like a useful primitive for web authors (and clearly there is some usage today). For full disclosure, there are Microsoft web properties that have expressed interest in using the zoom property as a low-cost solution for zooming in certain portions of webpages. They don't want to introduce overflow in the inline direction or redesign their implementation, and the zoom property has provided an almost trivial way to improve these scenarios for their users (they're experimenting with this in production today).

@chrishtr also pointed me to previous discussions related to defining an interaction model driven by maps scenarios (https://github.com/w3c/csswg-drafts/issues/5275). Perhaps that would be another lens through which to have discussions about the use case, but I don't think that would move the needle for the large number of pages that use a property that is currently implemented by more than one browser.

**Comment by emilio** [comment]
There are a lot of issues with Blink's / WebKit's implementation of zoom, including their behavior with stuff like getBoundingClientRect(), etc, last time I looked at it.

zoom also has some very weird effects like affecting the intrinsic sizing of images and such even when no `width` / `height` is specified, which are not defined in Rossen's draft (and I just learned by chance).

Here's a super-trivial test-case: `data:text/html,<!doctype html><div style="width: 100px; height: 100px; zoom: 2"></div>`

`document.querySelector("div").getBoundingClientRect()` returns `x: 4` and `y: 4`, which are completely wrong (they're reverse-zoomed even though the origin doesn't change), and `width: 100` and `height: 100` (which is really odd because the zoom affects the size of the box, and something like `transform-origin: 0 0; transform: scale(2)` instead properly affects the result of `getBoundingClientRect()`).

This is just like, the beginning of the issues with zoom, I've seen a lot of bugs go by the Chromium's bug tracker related to it, and the Blink / WebKit implementation is extremely hacky (IMO).

So unless this gets very very very well defined (and my guess is that doing that is going to be very hard because WebKit's implementation is very ad-hoc and patchy in a lot of places), I'd be opposed to do this.

cc @karlcow

**Comment by emilio** [comment]
> One item of particular note is that Gecko does not implement zoom (see https://bugzilla.mozilla.org/show_bug.cgi?id=390936). There are unique challenges given that authors have used a -moz-transform: scale(n) fallback in the absence of zoom. Additionally, I believe there were attempts to implement zoom in terms of transforms but that was not sufficient to alleviate compat concerns.

For reference that's https://bugzilla.mozilla.org/show_bug.cgi?id=1589766. The main idea behind that was to keep sites that used stuff like:

```
  zoom: 2;
  -moz-transform-origin: 0 0;
  -moz-transform: scale(2);
```

basically keep working. My gut feeling is that to implement `zoom` in any other way  we'd have to drop `-moz-` prefixed transforms at the same time (which is extra risk). It mostly worked, but the main issue is that stuff that used `zoom: 1` and transforms, which then resets the transform-origin and messes up, see https://bugzilla.mozilla.org/show_bug.cgi?id=1599324#c0 which is what made me turn it off.

Another quirk that you don't learn until you try that is that `zoom: 0` ends up having to mean `zoom: 1` for compat reasons... yay :/

**Comment by dlibby-** [comment]
Thanks for those pointers! Sounds like there are two core objections:
1. Specifying the current behavior may be difficult and could very well end up codifying some really strange behavior if there are no appetite for implementation changes due to compat concerns.
1. Shipping this in Gecko has increased risk due to the probably need to sim-ship deprecation of -moz-transform.

I did go through crbug to see I could pull out a signal of the breadth of issues and tagged the ones that I found (searched "css zoom" and skimmed the titles, so probably not exhaustive):
https://bugs.chromium.org/p/chromium/issues/list?q=label%3Acss-zoom&can=1

I did a similar exercise in WebKit's bugzilla but did not discover anything unique (though again I could have missed something).

Certainly the `getBoundingClientRect()` behavior stands out as particularly weird and difficult to justify the standardization of such strange behavior. I'm not entirely sure the rest would be insurmountable to document/reconcile, and as you mention there is probably other weirdness to find when digging in further.

In any case, I think this is worth having a broader discussion to get consensus on next steps, so tagging for TPAC.

**Comment by dlibby-** [comment]
Based on TPAC discusssion, closing this issue out as there is no support in the WG for specifying `zoom` either as-is or prescribing modifications (due to compat concerns). I'll open a new issue for a new proposal for "layout-transforms" or perhaps something more scoped that solves the use-case.

**Comment by karlcow** [comment]
@dlibby- I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1142663 feel free to modify or rephrase it.

**Comment by maltenuhn** [comment]
@dlibby- 

> I'll open a new issue for a new proposal for "layout-transforms" or perhaps something more scoped that solves the use-case.

Is there a gh issue or other place to comment on? We're relying on both zoom and scale in our implementation of a browser-based design product, and would be happy to document our use case there if that's of any help. The Chromium bug @karlcow posted appears to be more specific, and the MapML initiative somewhat orthogonal.

**Comment by karlcow** [comment]
@maltenuhn you are welcome to do it here.

**Comment by MurakamiShinyu** [comment]
[Vivliostyle](https://github.com/vivliostyle/vivliostyle.js) is also relying on zoom, to solve the issue [Minimum font size setting in Chrome causes ruby font size problem](https://github.com/vivliostyle/vivliostyle.js/issues/673).

I admit that using `zoom: 0.5` instead of `font-size: 50%` in ruby-text is an insane way. However, I can't find a better workaround for the problem that `font-size: 50%` does not work correctly on Chrome because of [the default setting of minimum font size](https://bugs.chromium.org/p/chromium/issues/detail?id=36429).

See the following test sample, testing `font-size: 50%`, `zoom: 0.5`, and `transform: scale(0.5)` on ruby-text: https://jsbin.com/zewaloc/edit?html,css,output

Result screenshot on Chrome:
<img width="1343" alt="Screen Shot 2021-04-01 at 16 25 01" src="https://user-images.githubusercontent.com/3324737/113279082-ab2b2c00-931d-11eb-9f33-2990825852ad.png">

On Chrome, with the default setting of minimum font size, ruby is displayed typographically correctly only when zoom is used. (And on Firefox, only `font-size: 50%` works fine, of course.)

This zoom usage should never be recommended for normal web pages. However, for typographic apps (for print, in particular) running in browsers, Chrome's zoom property is still needed to workaround Chrome's limitations.

**Comment by emilio** [comment]
That seems like a Chrome bug that should be reported to them. In fact, I'd argue that the fact that zoom can be used to bypass the minimum font size in Chrome is a bug in Chrome. Firefox fixed the interaction between min font size and ruby in https://bugzilla.mozilla.org/show_bug.cgi?id=1165538.

**Comment by MurakamiShinyu** [comment]
@emilio Thanks for the suggestion, I reported https://bugs.chromium.org/p/chromium/issues/detail?id=1195041

**Comment by SNDST00M** [comment]
Why is there so much opposition to this? I think it's a really good way of implementing high accessibility userstyles, although it is established that other userstyle features such as `@document` never went through.

**Comment by astearns** [comment]
@SNDST00M The way zoom currently works is probably now required for web compatibility - we can’t improve the way it works without breaking pages that rely on its current behavior. And its current behavior is too weird and inconsistent to standardize and recommend for implementation.

But there is no opposition to creating a new layout-affecting transform. It would just likely be a really big thing to get to. @dlibby- have you had a chance to open a new issue for this?

**Comment by SNDST00M** [comment]
Okay, thanks for suggesting the new property and letting 1% of the internet stay "weird" 😄

**Comment by rockwotj** [comment]
FWIW Gmail uses zoom on mobile emails to force parts of them to be responsive, removing it without having a transform-effecting-layout would not be ideal.

**Comment by chrishtr** [comment]
I think a plausible path forward is incremental changes to the Webkit and Chromium implementation of `zoom` to remove undesired quirks. This would make `zoom` more predicable and simple to describe, and at the same time constrain it into a smaller set of behaviors that could potentially be eventually removed, or become an interoperable standard.

**Comment by SelenIT** [comment]
> which are completely wrong (they're reverse-zoomed even though the origin doesn't change)

To me, this behavior makes sense. It seems that values are returned in transformed coordinate system, where `1px` unit becomes equal to `2px` in the initial (non-zoomed) coordinate system. So 8 non-zoomed pixels are equal to 4 zoomed pixels and 200 non-zoomed pixels that the zoomed element now takes up are still `100px` in the zoomed coordinate system. All CSS properties for the zoomed element, like margins, offsets etc., are set in "zoomed" pixels (e.g., to push it to the top left viewport corner, you would need to set `margin: -4px`, not `margin: -8px`), so it seems quite reasonable to measure it in the same coordinate system...

**Comment by TahirAhmadov** [comment]
Zoom is very useful when showing documents. Transform doesn't work well. 

Yes current implementation is hacky - that's because it's not standardized. This conversation is a catch 22. This property is not standardized, so the implementations are hacky, so we cannot standardize.

**Comment by zm-cttae** [comment]
Was an issue defined for a standardised layout (flow dimension) transform property?

**Comment by annevk** [comment]
Reopening to discuss https://github.com/w3c/csswg-drafts/issues/5623#issuecomment-1005274895 further. (Please reopen in the future when adding new actionable comments.)

**Comment by zm-cttae** [comment]
Let's not forget that transform origin and perspective origin will need their coord offsets scaled too :)

**Comment by maltenuhn** [comment]
For [Utopia](https://github.com/concrete-utopia/utopia/), we'd be strongly supportive of a new property that basically behaves like a "pixel-perfect" magnification / inverse - in the manner of design tools like Illustrator / Figma / Sketch. 

Most authoring tools on the web would benefit from that, because in the design phase working at 2-4x magnification is frequent:  maybe you're looking to tweak that boxShadow just so, or match a `translate` to the _visual_ center of an icon, comparing visual weights of fonts but in situ, ... etc. etc.

**Comment by emilio** [comment]
Happy to discuss this further, but part of the issue with `zoom` seems pretty fundamental to me, and is that it breaks the CSS coordinate space in the page, so that CSS pixels mean different things for different elements, and basically no API accounts for that. I'm not sure what can be done to reasonably account for it? Not magically un-zooming in APIs / getComputedStyle / etc is an option, but then you cause the opposite problem, `style.width = getComputedStyle().width` not round-tripping for zoomed elements, which is also broken.

For the last comment / use-case here, it seems like rather than `zoom` (which behaves like layout zoom), you'd like to expose pinch-zooming (think of the mobile phone zoom) to a subset of the page, right? Though I don't understand why `transform` or `scale` isn't that? If you need pinch-zoom behavior, an easier solution might be allowing iframes to be pinch-zoomed separately? That doesn't have the same issue `zoom` has because the coordinate space would be different across the documents. But that is probably worth a separate issue.

**Comment by chrishtr** [comment]
Here are some additional thoughts based on my research into zoom, as part of my [effort](https://bugs.chromium.org/p/chromium/issues/detail?id=1142663) to potentially deprecate and remove CSS zoom from Chromium. The research involved reading the Mozilla [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=390936), relevant Chromium [issues](https://bugs.chromium.org/p/chromium/issues/list?q=label%3Acss-zoom&can=1), comments on this issue (i.e. #5623) analyzing a number of sites, and conversations with Gmail engineers.

# Compat risks:

* Microsoft Excel for Web uses CSS zoom in order to make text in cells larger.  (+)
* The Gmail mobile web app (which displays emails in a webview) uses CSS zoom to scale down HTML emails that are wider than the visible viewport, or scaling up ones that are a lot narrower, while also displaying them inline with adjacent emails or spacer divs in the same thread ([extracted example with zoom](https://jsfiddle.net/6sondL4b/1/)). (++)
* The Chrome UseCounter is [quite high](https://chromestatus.com/metrics/feature/timeline/popularity/3578).
* I [reviewed](https://docs.google.com/document/d/1cmbXpjAcXAht2ufi7bNKy-rbVNveqaf0UzeYg_DIMNA/edit?pli=1) a large number of other sites that hit the Chrome UseCounter and didn't see very many that seemed too problematic if zoom was removed.

It may not be feasible to get all of these fixed.

# Use cases I found that were compelling to me:

* Resizing external/non-responsive design content that is infeasible to make responsive (Example: Gmail.)
* A11y zooming features within the web page (examples: Microsoft Excel, and [this](https://css-tricks.com/forums/topic/emulating-browser-zoom-with-css-for-accessibility/). One other site I examined also used this pattern to provide a zoom button for a (conceptual, not iframe) sub-document.)
* Previewing content in a interstitial dialog by shrinking it down (Gmail desktop email themes do this - during the wizard flow it shows you an example result previewed in a second column. Transforms might work for this, but have worse responsive design and need special care to size correctly.)

# Chromium Implementation notes

* Chromium's implementation is not actually all that complex -- it just multiplies all non-percentage lengths, and all font sizes including percents, by the zoom factor, for the subdocument. Nested zoom multiplies. 

* On all platforms, Chromium actually implements both browser zoom (ctrl-+/-) scale factor and device scale factor by using zoom on the HTML element. (And this is reflected in the computed style of the HTML element presented to JS.) So even if CSS zoom was removed the code in Chromium would not be significantly simplified.

* APIs like `getBoundingClientRect` and `offsetWidth` divide all values by the multiplied zoom across ancestors (including self).

# Chromium Implementation known issues that should be fixed

* `getBoundingClientRect` reports values that don’t make a lot of sense:
  * X and y offsets are divided by zoom, even for cases when they shouldn’t affect it (Example: `data:text/html,<!doctype html><div style="background: lightblue;width: 100px; height: 100px; zoom: 2"></div>`. Should be x=8 and y=8 since those come from margin above the zoomed element.)
  * The result is [not usable for hit testing](https://bugs.chromium.org/p/chromium/issues/detail?id=967097&q=label%3Acss-zoom&can=1) or geometrical measurement.

# Summary

In general, I found that CSS zoom's superpower is a reliable way to make text, and the elements around it, zoom in or out, while retaining responsive design accessibility principles such as reflow within the content and to adjacent or wrapping content elements, and ensuring content is always readable. You can polyfill it by injecting custom variables into the entire document or with CSS pre-processors, but that may not be feasible for imported external content.

I think the visual implementation of zoom in Chromium works very well, and is consistent across all elements. Evidence includes:
* Web developers consistently say the same thing (including via comments on this issue and the Mozilla feature request issue).
* The browser zoom feature in Chromium works very well for increasing readability/accessibility, as does the same feature for Gecko and WebKit (which works the same way AFAIK).

The only significant problems with CSS zoom that I'm aware of are the inconsistent/illogical JS API behavior. (@emilio mentioned other complications that I'm not seeing, so I might be missing something?)

# My recommendation

* Standardize CSS zoom's *visual* behavior as-is (including behavior for percentage lengths, which I think are good as-is based on the above evidence)
* Adjust existing JS APIs as necessary to return *unzoomed* values for lengths, so that these values round-trip and are consistent with style sheets and existing browser zoom features.
* Adjust existing JS APIs as necessary to return *zoomed* values for offsets. For example `getBoundingClientRect().x` or `offsetLeft` should return a physical value that includes zoom. This allows hit testing to work and fixes an existing illogical behavior. (+++)

(+) The equivalent feature in Google Sheets / Docs uses custom code that modifies element styles to multiply their sizes by the desired zoom factor. 

(++) Imperfect [prototype version with transforms](https://jsfiddle.net/6sondL4b/2/) - note the background color is wrong in some areas. 

(+++) `offsetLeft` should only include zoom of ancestors, not self.

**Comment by chrishtr** [comment]
> zoom also has some very weird effects like affecting the intrinsic sizing of images and such even when no `width` / `height` is specified, which are not defined in Rossen's draft (and I just learned by chance).

I'm not totally sure what the weird effects are. @emilio could you clarify?

**Comment by dbaron** [comment]
For what it's worth, #1487 is open for having layout-affecting transforms.

**Comment by zm-cttae** [comment]
> even when no width / height is specified

A rabbit hole of an issue that could bikeshed us here!

**Comment by flackr** [comment]
I discovered the odd quirk of zoom not inheriting that I was thinking of after the fact. Descendant frames reset the zoom rather than getting the zoomed layout from the iframe element, e.g.

https://jsbin.com/jibiwev/4/edit?html,output

Both of the frames in this example have the same zoom on their contents despite the top one being within a `zoom: 2` styled ancestor. I think this is just an implementation quirk because we set the browser zoom as the zoom on the root of each frame so we don't want to scale up the frame by the browser zoom again - but more reasonable behavior would be for the frame's contents to be scaled by the zoom applying to its `iframe` element. We can avoid double applying the browser zoom by only applying it to the root frame.

**Comment by zm-cttae** [comment]
Reposted to Wikimedia Phabricator here - [⚓ T342528 RfC on use cases of standardized zoom CSS property in Wikimedia wikis](https://phabricator.wikimedia.org/T342528)

**Comment by emilio** [comment]
FWIW I have an implementation in Firefox in [bug 1854441](https://bugzil.la/1854441), but I filed #9397 and #9398 on things that make no sense to me.

**Comment by Schepp** [comment]
I'd like to add the following use-case of morphing from one view to the next: https://codepen.io/Schepp/pen/LYNZzWY

If not with `zoom` this would also work with View Transitions, but only if there's not multiple morphs running with different delays. And not without JavaScript.

**Comment by AndreiSva** [comment]
Does anyone know what ended up happening? Is the `zoom` [here](https://drafts.csswg.org/css-viewport/#zoom-property) the unchanged behaviour from IE / Chrome?

**Comment by chrishtr** [comment]
> Does anyone know what ended up happening? Is the `zoom` [here](https://drafts.csswg.org/css-viewport/#zoom-property) the unchanged behaviour from IE / Chrome?

Zoom is [now standardized](https://drafts.csswg.org/css-viewport/#zoom-property) (some changes from how it's currently implemented in Chromium and WebKit. No browsers ship the standard yet (two are working on it).
