### ISSUE TITLE
css should define and use consistent terminology for words like "deprecated", "obsolete"

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5644]
(moved from https://github.com/w3c/csswg-drafts/pull/4087#issuecomment-686271513, which was a discussion about one particular usage of such terminology)

Discussed this offline with @sideshowbarker (a while back, only remembering it now): css should define and use consistent terminology for words like "deprecated", "obsolete", and other similar terms.

Here are some of the possible meanings for such words (non exhaustive list):
1. Using this is a bad idea (but if you do, here's how it works)
2. this is an old bad name/API for a useful thing which has a new good name/API. Use the new one if you can, be mindful of compat.
3. This is going away, don't count on it being there, or on continuing to do anything

I think, at present, CSS specs have some cases of 1 (https://drafts.csswg.org/mediaqueries-4/#mf-deprecated), some cases of 2 (https://drafts.csswg.org/css-text-3/#valdef-word-break-break-word. I can't quite tell if https://www.w3.org/TR/css-color-3/#css2-system is 1 or 3. We call all these "deprecated".

Should we clean up our terminology to account for this nuance? Is there some systematic (and formally defined) existing use of these words by other groups we could align to?

Note that this is about individual features, and is different from obsoleting / superseding / rescinding entire specifications. That's clearly defined [in the Process](https://www.w3.org/2020/Process-20200915/#tr-end).

**Comment by svgeesus** [comment]
> I can't quite tell if https://www.w3.org/TR/css-color-3/#css2-system is 1 or 3. 

It is mostly 1. It isn't really 3 because they went away then [half of them came back](https://drafts.csswg.org/css-color/#css-system-colors) which is kind of an antipattern.

And then we have [named colors aka X11 colors](https://drafts.csswg.org/css-color/#named-colors) which are

1a. Using this is a bad idea (but if you do, here's how it works) and while we can't get rid of them we also won't add any more so please stop asking; nor can we rename them or change what they mean.

(related to [Change three color names](https://github.com/w3c/csswg-drafts/issues/5284) and [new predefined colors](https://github.com/w3c/csswg-drafts/issues/3192))

**Comment by svgeesus** [comment]
> In several fields, deprecation is the discouragement of use of some terminology, feature, design, or practice, typically because it has been superseded or is no longer considered efficient or safe, without completely removing it or prohibiting its use. Typically, deprecated materials are not completely removed to ensure legacy compatibility or back up practice in case new methods are not functional in an odd scenario.
https://en.wikipedia.org/wiki/Deprecation

seems like an okay definition

**Comment by fantasai** [comment]
IIRC in other fields, #3 is possible, and stuff moves from deprecation in one version to obsoletion in another, but on the Web, we generally can't remove things so #3 hasn't really been an option.

I think the Wikipedia definition @svgeesus cites is a pretty good one. I don't think we need to define terms which follow their normal English usage?

As for obsoletion, we generally pair it with "optional to implement" in RFC2119 terms, so I think there's nothing to specially define there, either.

**Comment by sideshowbarker** [comment]
> Is there some systematic (and formally defined) existing use of these words by other groups we could align to?

The HTML spec never uses the word *deprecated* at all; instead it only uses *obsolete* — but further makes a distinction between A) obsolete features that are *obsolete but conforming* — which is what most other specs label typically use *deprecated* for — and B) obsolete features that completely *non-conforming*.

See https://html.spec.whatwg.org/multipage/obsolete.html#obsolete

The reason the HTML spec uses *obsolete* rather than *deprecated* is that it wouldn’t make any sense to label those case B completely non-conforming features as “deprecated”.

So in the HTML-spec taxonomy, I think all three cases listed in the issue description map to “obsolete but conforming”.

And given that, I think what the issue description focuses on is basically what most other specs would call “deprecated”.

The HTML-spec taxonomy is arguably idiosyncratic and not aligned super well with what most other specs do.

That said, I think the HTML-spec taxonomy does expose that there’s at least one more case to consider, which is this:

4. This feature/name is in no way currently specified anywhere — and it’s either gone from implementations already, or else if if it’s still in implementations, you should have zero expectation that it works interoperably. Don’t use it.

That \#4 case is what the HTML case calls *non-conforming*.

But I think most other specs don’t even list such completely non-conforming features at all.

Given all that, as far as just the question of how to distinguish *deprecated* vs *obsolete*, I would suggest not to use both but instead only use one or the other. And between the two, I think *deprecated* is the one that’s more-commonly used by most specs, and the one that’s somewhat less ambiguous.

However, if as the HTML spec does, you also want to include consideration of case \#4 — features that are completely non-conforming — then it seems necessary to use the word *obsolete* rather than *deprecated*; it otherwise wouldn’t make much sense to describe any features as “deprecated and non-conforming” (whereas it does make sense to describe such features a “obsolete and non-conforming”).

**Comment by fantasai** [comment]
The CSS specs use 'deprecated' and 'obsoleted' as value judgements. What's required for conformance or not is a separate question represented via RFC2119 terminology. I believe our usage of 'deprecated' and 'obsolete' matches English usage, so I don't think there's anything to do here.

**Comment by sideshowbarker** [comment]
> What's required for conformance or not is a separate question represented via RFC2119 terminology.

At https://html.spec.whatwg.org/multipage/introduction.html#conformance-requirements-for-authors the HTML spec explains how it defines conformance requirements for authors and documents as a conformance class, and explains that the spec defines conformance requirements for distinguishing between a conforming document and non-conforming document. 

And the HTML spec uses RFC2119 terminology to specify those document/authoring conformance requirements.
 
In particular, the HTML spec defines some document/authoring conformance requirements as cases that MUST NOT be used by documents/authors, and some others as cases that instead SHOULD NOT be used by documents/authors.

For the set of CSS specs, is there somewhere a similar explanation of whether CSS defines requirements for documents/authors as a conformance class?

If a CSS spec states that a particular feature is _deprecated_, does that mean authors MUST NOT use that feature, or does it mean that authors SHOULD NOT use that feature? Does a CSS feature marked as _obsolete_ mean that authors MUST NOT use that feature, or does it mean that authors SHOULD NOT use that feature?

It seems like CSS specs do actually intend to define conformance requirements for documents/authors. And therefore it seems useful for there to be an explanation somewhere among the set of specs — similar to what the HTML spec has — that explicitly addresses document/authoring conformance requirements.

And along with that, if the terms _deprecated_ and _obsolete_  are intended to have some effect on what documents/authors must not do or should not do, then it seems like the intended effect of those terms for documents/authors should be explicitly and unambiguously stated somewhere.

As a maintainer of conformance-checking tools, I have a very practical need for those terms to be unambiguously defined — and in general, for the CSS specs to be unambiguous about identifying things that documents/authors MUST NOT have, and identifying things that documents/authors SHOULD NOT have, and unambiguously distinguishing between the two.

In practical terms, what the distinction means for me and other developers of conformance-checking tools is that if a CSS spec defines a case as a MUST NOT, then we make our conformance-checkers report an error for any instance of that — and for SHOULD NOT cases, we instead report just a warning.

So as a conformance-checker developer, ultimately what I want for any case of the terms _deprecated_ and _obsolete_ in a CSS spec is to clearly know: Do I make my conformance checker report an error for that case? Or do I make it report a warning?

And I’d like to be able to trust that the set of CSS specs are using those terms consistently, based on precise meanings defined somewhere, and with some formal statement somewhere in the set of CSS specs that explains how I can tell the difference between a case that a CSS spec intends MUST NOT be used by documents/authors versus a case that a CSS spec instead intends SHOULD NOT be used by documents/authors.
