### ISSUE TITLE
[css-overflow] Clarify what rect clips the root element with overflow:hidden on mobile environments with dynamic toolbar

### ISSUE THREAD

**Issue by hiikezoe** [w3c/csswg-drafts#5646]
The spec says what overflow:hidden means is [the box’s content is clipped to its padding box](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-hidden), and I believe the padding box of the root element is the initial containing block (which is 0-padding) (or maybe the layout viewport?).

On mobile environments with dynamic toolbar, the initial containing block doesn't include the dynamic toolbar height (it's not yet spec-ed though as far as I know of), all major browsers (Chrome, Safari and Firefox) do so.  So, I think overflow:hidden should clip the root element to the ICB (which is not including the toolbar height). But both on Chrome and Safari, the root element clips to the area including the dynamic toolbar, thus regions initially overflowed by the dynamic toolbar can be reachable by swipe up motions.
(note that I intentionally ignore cases where the minimum-scale is applied)

https://bug1663634.bmoattachments.org/attachment.cgi?id=9182769 is an example to show the issue.

CCing @bokand

(Though the behavior both on Chrome and Safari is pretty weird for me, I think Firefox has to align with it. )

**Comment by frivoal** [comment]
I am not sure I fully understand what the problem is, but to the extent I do, it feels more like an implementation issue than a specification problem. Can you clarify?

**Comment by hiikezoe** [comment]
https://hiikezoe.github.io/overflow-clip-on-root.html
Here is an example.  There are two divs, one is a blue position:fixed element attached to "bottom: 0px", the other is a red position:absolute element attached to "top: `document.documentElement.clientHeight`px".  And the root element has "overflow: clip" property.  In this example, the red div is initially outside of the viewport (both of the visual/layout viewports). But on mobile Chrome the red div can be reachable by swipe down gestures (You will probably have to do swipe down gestures several times, I don't know how Chrome handles those gestures).  I haven't tried the example on iPhone(s) since I have no such devices at all, but I suppose mobile Safari has the same behavior.

**Comment by bokand** [comment]
Is the questionable behavior that as the URL bar hides and the red div starts to come into view, it's technically outside the clip rect of the root element but we still see it?

If so, (speaking for Blink) the root element clipping is delegated to the "viewport" and is special in that it's adjusted by the URL bar. We expand the clipping rect but don't expand the ICB (so that we don't change the clientHeight or reflow the page). Without the special case of expanding the clipping rect I think any page on which you can scroll would clip out the bottom of the page as the URL bar became hidden.

This has historically been an area not covered by specs but I wouldn't be opposed to clarifying the exact and expected behavior.

**Comment by hiikezoe** [comment]
> Is the questionable behavior that as the URL bar hides and the red div starts to come into view, it's technically outside the clip rect of the root element but we still see it?

Yes, exactly.

> This has historically been an area not covered by specs but I wouldn't be opposed to clarifying the exact and expected behavior.

I am in the same boat. :)

**Comment by fantasai** [comment]
Agenda+ Do we want to spec this behavior?
