### ISSUE TITLE
[web-animations-1] Object-form keyframe with offset: 1

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#5664]
Hello,

I'm struggling to understand why a keyframe like `{ offset: 1, opacity: [0, 1, 0] }` doesn't trigger (in Chrome/Firefox) the `TypeError` described in step 6 of the [procedure to process a keyframes argument](https://drafts.csswg.org/web-animations-1/#process-a-keyframes-argument), ie:

> If processed keyframes is not loosely sorted by offset, throw a TypeError and abort these steps.

Allow me to sum up the meaningfull steps from this procedure:

> For each value in property [opacity] values:
> 1. Let k be a new keyframe with a null keyframe offset.
> 2. Add the property-value pair to k.
> 3. Append k to property keyframes.
>
> Apply the procedure to compute missing keyframe offsets to property keyframes

The result of the computed offsets must be `[0, 0.5, 1]`.

> Assign each value in offsets to the keyframe offset of the keyframe with corresponding position in processed keyframes until the end of either sequence is reached.

The result is now `[1, 0.5, 1]`, which should trigger the `TypeError`.

Am I misunderstanding/missing something that would explain why it is not?

**Comment by birtles** [comment]
The important distinction here is between (specified) keyframe offsets and computed keyframe offsets.

In this procedure, computed keyframe offsets are generated purely in order to merge corresponding elements from parallel arrays into the same keyframes. They are not used when determining if keyframes are sorted by offset or not, and don't interact with the specified offsets at all. For all intents and purposes, the computed keyframe offsets are ignored after keyframes are merged (they will be recalculated when the computed keyframes are later generated).

> > Assign each value in offsets to the keyframe offset of the keyframe with corresponding position in processed keyframes until the end of either sequence is reached.
> 
> The result is now `[1, 0.5, 1]`, which should trigger the `TypeError`.

The result here will be that the first keyframe gets an offset of `1` while all the other keyframes are untouched and have an offset of `null`. Later, when the computed keyframes are generated (e.g. by calling `getKeyframes()`), the computed offsets will be calculated.

**Comment by cdoublev** [comment]
Oh, I see. I missed this distinction (which I was aware of) in *If processed keyframes is not loosely sorted by **offset**, throw a TypeError [...]*.

Again, thank you for your time and help! I swear I spent the whole yesterday afternoon on this before opening this issue. I'm using only one offset value in my implementation as I'm still not sure why keeping both specified/computed offsets would be required.

**Comment by birtles** [comment]
> I'm using only one offset value in my implementation as I'm still not sure why keeping both specified/computed offsets would be required.

Right, it's mostly so that authors can roundtrip `null` offsets. e.g.

```js
const anim = elem.animate({ left: ['0px', '100px'] }, 2000);
anim.effect.setKeyframes(anim.effect.getKeyframes().concat('-50px'));
```

Without distinguishing between specified and computed, the returned keyframes would have resolved computed offsets and you'd lose the auto-spacing behavior.
