### ISSUE TITLE
[css-backgrounds-3] Adjustments to spec needed to implement rounded corner clipping of descendants

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#5680]
The spec currently says that `background-clip` defines a box for clipping the background, [as well as overflow clipping of descendants](https://www.w3.org/TR/css-backgrounds-3/#corner-clipping). All browsers implement `background-clip` correctly for the background, but for descendants it appears they all implement `padding-box` and do not support any other value. See [this testcase](https://output.jsbin.com/yayipavobo). A bug in Chromium has been present for [a long time](https://bugs.chromium.org/p/chromium/issues/detail?id=99364); similar bugs are filed on WebKit and Gecko.

I would like to implement `content-box` for overflow clipping. However, since browsers implement `padding-box`, I don't think it is web compatible to obey the spec as-is, since it would mandate `border-box` by default. I'm also not sure if there is a very good use case for overflow clipping to `border-box`, since in many cases this would cause descendant content to overlap the border when it paints after that border.

How about this: we change the spec to say that if `background-clip` is set to `content-box`, then we use that clip and its curve for overflow contents, and otherwise `padding-box`.

@frivoal @tabatkins Florian: Tab recommended you as a person who knows this part of the spec?

**Comment by fantasai** [comment]
Hi, I'm the editor. :) What the spec is trying to say there is that when something is clipped to a particular edge, that clipping is affected by the way the edge is curved by the border radius as described in the previous section. Backgrounds use the edge specified by `background-clip`. But content does not. Overflowing content is always clipped by the padding edge: the spec here is just saying that this edge is curved at the corners by the border radius. Similarly, the content of a replaced element is always constrained by the content-box; and the spec here is saying that the corners of that box are likewise curved and the replaced element content clipped accordingly.

If you want to clip content to the content edge instead of the padding edge, you'd need a new property to do it. Maybe re-using `overflow-clip-margin` or whatever we decided to call it, by giving it some keywords.

**Comment by chrishtr** [comment]
> Hi, I'm the editor. :)

Ok cool. I should have figured as much. :)

> Overflowing content is always clipped by the padding edge: the spec here is just saying that this edge is curved at the corners by the border radius.

I see. Then just to confirm, you think [this test case](http://jsbin.com/fezife/2/quiet) is working correctly in all browsers according to the spec (i.e. the expectation there is wrong and the browsers are right)? The bug I referenced also referred to a question (a long time ago, I know) that [I interpreted as saying otherwise](https://lists.w3.org/Archives/Public/www-style/2015Apr/0252.html).

I do think it seems useful to clip to the content box as an option. Your suggestion of `overflow-clip-margin` with a negative outset might work.

**Comment by fantasai** [comment]
The editors are always listed at the top of the spec for a reason: so that you can pester them with complaints and questions. ;)

I can't load the testcase right now for some reason, but [this testcase is correct](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cimg%20src%3D%22http%3A%2F%2Fplacehold.it%2F40x40%22%20style%3D%22border-radius%3A%2050%25%3B%20border%3A%201px%20solid%3B%20padding%3A%2010px%22%3E%0A%3Cdiv%20style%3D%22border-radius%3A%2050%25%3B%20border%3A%201px%20solid%3B%20padding%3A%2010px%3B%20overflow%3A%20hidden%22%3E%3Cimg%20src%3D%22http%3A%2F%2Fplacehold.it%2F40x40%22%3E%3C%2Fdiv%3E) in Gecko and Blink afaict.

**Comment by fantasai** [comment]
OK, I rewrote the confusing section in https://github.com/w3c/csswg-drafts/commit/b27601c97ae9664f1d2dec75c26750684ba187bf
You can compare before/after:
  https://www.w3.org/TR/css-backgrounds-3/#corner-clipping
  https://drafts.csswg.org/css-backgrounds-3/#corner-clipping

Lmk if that looks better (and still correct)!

**Comment by chrishtr** [comment]
The new text looks good, thanks. I'll close this issue and the Chromium bug.

**Comment by laukstein** [comment]
Isn't this a spec issue?

Test-case http://output.jsbin.com/fezife/2/quiet (@fantasai can you check it?)
Chrome Issue (just was closed as WontFix following this conversation) https://bugs.chromium.org/p/chromium/issues/detail?id=99364

**Comment by fantasai** [comment]
@laukstein I can't load your testcase, but I'm guessing what you're doing is wrapping a replaced element in another element and expecting it to clip the corner. But the way `overflow: hidden` works in CSS is that it clips to the padding edge of the box (the inner border edge), not the content edge (inner padding edge). The border-radius property causes all of these edges to curve, yes but it doesn't change which one you clip to. (If you put a negative margin on content inside your box, you'll see that it does not clip when you shift it into the padding area. Border-radius doesn't change this fact.)

I'll file a separate issue about addressing the use case, though.

**Comment by laukstein** [comment]
@fantasai here how it looks:
![grabilla g10212](https://user-images.githubusercontent.com/183966/102401451-02fe8b00-3fec-11eb-9173-9374efdfd797.png)

html:
```
<!DOCTYPE html>
<meta charset=UTF-8>
<title>CSS corner-clipping also for padding</title>
<h1>CSS corner-clipping for padding</h1>
<p>Resources: <a href="http://www.w3.org/TR/css3-background/#corner-clipping" target=_blank>W3C spec</a>, <a href="http://lists.w3.org/Archives/Public/www-style/2015Apr/0252.html" target=_blank> answer</a><br>Issue: <a href="https://code.google.com/p/chromium/issues/detail?id=99364" target=_blank>Chrome #99364</a></p>
<p>The padding must be rounded following <a href="http://www.w3.org/TR/css3-background/#corner-clipping" target=_blank>spec</a> - the <a href=#test>TEST-CASE</a> green box must look as a symmetrical circle <a href=#expected>EXPECTED RESULT<a>.</p>
<p id=test>Test-case:</p>
<ul><li></ul>
<p id=expected>Expected result:</p>
<ul class=expected><li></ul>
```

css:
```
ul {
    overflow: hidden;
    display: inline-block;
    padding: .5em;
    list-style: none;
    background-color: rgba(100,0,0,.1);
    border-radius: 100%;
}
li {
    padding: 2em;
    color: #fff;
    text-align: center;
    background-color: green;
}
.expected li {
    border-radius: 100%;
}
:target {
    background-color: yellow;
}
```
