### ISSUE TITLE
[web-animations-1] Inconsistent default document timeline in Animatable interface

### ISSUE THREAD

**Issue by hiikezoe** [w3c/csswg-drafts#5701]
In [animate() method section](https://drafts.csswg.org/web-animations-1/#dom-animatable-animate);

> if timeline member of options is missing, be the default document timeline of the node document of the element on which this method was called

In [KeyframeAnimationOptions dictionary member section](https://drafts.csswg.org/web-animations-1/#dom-keyframeanimationoptions-timeline);

> If missing, the default document timeline of the Document associated with the Window that is the current global object is used

I believe the former is correct and that's what Firefox and Chrome do currently.
@birtles @majido

**Comment by birtles** [comment]
Good catch. I think the text in the `animate()` method description actually overrides the description in `KeyframeAnimationOptions` (since it says what to do when that member is missing) so we should probably just drop the "If missing..." sentence from the description of `KeyframeAnimationOptions.timeline`.
