### ISSUE TITLE
[css-text-3] Is testcase css-text/white-space/full-width-leading-spaces-004.html correct?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#5732]
I'm trying to understand whether [this testcase](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/white-space/full-width-leading-spaces-004.html) is valid per the CSS Text 3 rules.

The testcase has
```
<div class="test">&#x03000;</div>
```
styled with
```
.test {
    width: min-content;
    font-size: 100px;
    line-height: 1;
    background: green;
}
```
(and using the Ahem font), and expects it to render as a 100px green square.

However, it's not clear to me that the `min-content` width of this element should in fact be 100px. Its content is an IDEOGRAPHIC SPACE, which has General Category = Zs and is therefore an [other space separator](https://drafts.csswg.org/css-text-3/#other-space-separators) in CSS Text 3 terms. This character is the only thing on the line, so clearly it is "at the end of a line (after bidi reordering)".

According rule 4 of the [Trimming and Positioning](https://drafts.csswg.org/css-text-3/#white-space-phase-2) rules, then:

> If there remains any sequence of white space, and/or other space separators, at the end of a line (after bidi reordering [CSS-WRITING-MODES-3]):

>    If white-space is set to normal, nowrap, or pre-line, the UA must hang this sequence (unconditionally). 

this character must [hang](https://drafts.csswg.org/css-text-3/#hang), which means that it is

> not taken into account when computing intrinsic sizes

and so the `min-content` width of the element should be zero, not 100px.

Am I missing something here, or is the testcase wrong in expecting this ideographic space to create a 100px `min-content` width?

**Comment by javifernandez** [comment]
Yes, the test is wrong. The ideographic space must indeed hang **unconditionally**  I was confused by the fact that the space was considered a leading space (hence it shouldn't be collapsed), rather than a trailing space, but it's definitively "at the end of the line". 

The space should **conditionally** hang  if 'white-space: pre-wrap', is used, though. since it is followed by a forced line break. However, even in that case, should only account for max-content, and never for min-content size. 
 
Sorry about the mistake, I'll fix, or remove, the test ASAP.

**Comment by jfkthame** [comment]
Thanks, that helps a lot. I'm looking at a possible change in Gecko that would affect behavior here, so wanted to check my understanding.

**Comment by frivoal** [comment]
Agreed, and fixed in wpt.
