### ISSUE TITLE
[css-color] Non-ICC color specifications

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#5737]
~~~~ ebnf
color() = color( [ 
    [<ident> | <dashed-ident>]? 
    [ <number-percentage>+ | <string> ] 
    [ / <alpha-value> ]? 
  ]# , <color>? )
~~~~

The  [`color()` function][color] as currently specified expects either a single color name or a sequence of numeric component values. This may well cover everything that is possible with [ICC profiles][color-profile], but it does not support systems which support multiple keywords to specify a single color, e.g. [CNS](https://en.wikipedia.org/wiki/Color_Naming_System) `very dark reddish orange`, or combine letters/words and numeric amounts, e.g. [NCS](https://en.wikipedia.org/wiki/Natural_Color_System) `S 2030-Y90R` ~ `20% 30% 10% yellow 90% red`. 

Should the syntax be relaxed a bit to support such systems in the future?

[color]: <https://drafts.csswg.org/css-color-4/#color-function> "Specifying profiled colors: the color() function" 
[color-profile]: <https://drafts.csswg.org/css-color-4/#at-profile> "Specifying a color profile: the @color-profile at-rule"

**Comment by faceless2** [comment]
The "string" component in that grammar is the color name, so it can include spaces. But whether this grammar, which doesn't allow the _amount_ of that color name to be specified, is the best fit for this purpose is going to depend on https://github.com/w3c/csswg-drafts/issues/2023

**Comment by svgeesus** [comment]
As I [proposed CNS for CSS in 1996](https://lists.w3.org/Archives/Public/www-style/1996Feb/0020.html) I am familiar with it, and the barrier to adoption remains the same - a mapping from name string to Munsell colors is alluded to in the paper but is not provided. I mailed the author at the time, and did not get a response.

So (unless someone did the work to create such a mapping) there is no way to get a colorimetric value from a given name. Which makes it a poor fit for the `color()` function, and more akin to how `device-cmyk()` was until we fixed it.

Similar problems for the proprietary NCS; the colorimetric values for each color are not available.

**Comment by Myndex** [comment]
Hi Chris @svgeesus 

> _So (unless someone did the work to create such a mapping) there is no way to get a colorimetric value from a given name._

RIT did, I have a spreadsheet with the Munsell renotation and transformed to a number of colorimetric values — it is attached, is this what you mean?

Let me know if you need other data sets, I have a few...

Andy
[real_sRGB.ods.zip](https://github.com/w3c/csswg-drafts/files/6059825/real_sRGB.ods.zip)

**Comment by svgeesus** [comment]
Thanks. I have a copy of that spreadsheet, which is becoming harder to find since http://www.cis.rit.edu/research/mcsl/online/munsell.php now just redirects to the modern [RIT website](https://www.rit.edu/science/integrated-sciences-academy) which is a glossy brochure with little useful content.

Note though that this data was for **Munsell**; the discussion here is for the Swedish **Natural Color System (NCS)**, and the **Color Naming Scheme (CNS)**.

NCS®© is the registered trade name of NCS Colour AB, Sweden. You use the system by [buying a printed swatchbook](https://www.e-paint.co.uk/products.asp?cat=62) or a rinted atlas, choosing a color visually, and buying a new one every few years as the colors fade beyond tolerances.

There is no published algorithm, no published table of data as far as I know and being proprietary there could be legal consequences to buying one, measuring it and publishing the values. There may also be trademark aspects as well.

**Comment by Myndex** [comment]
Hey Chris @svgeesus 

Ah okay, my mistake, I misread the thread... And yea, some of my treasure trove took a log of digging and or learning some Russian which is why I attached it... LOL.

NCS is kinda weird, and as I expressed in another...uh.. "essay" IMO W3 ought not to be supporting proprietary anything. But looking at the OP's post, not sure how this applies to ICC ?

Tangentially: I see the potential for a useful notation form though, such as L50C35h145...

**Comment by Crissov** [comment]
I’m just suggesting to change `[ <number-percentage>+ | <string> ]` to either `[ <number-percentage>+ | <string>+ ]` or `[ <number-percentage> | <string> ]+`, so it would be more versatile. 

As I said, the current grammar is probably sufficient to match the possibilities of ICC profiles as currently specified.

**Comment by svgeesus** [comment]
The `<string>` part was to support ICC Named Colors, which we then removed:

 - https://github.com/w3c/csswg-drafts/issues/6095
 
 NCS as stated in this thread is proprietary, and CNS never really took off in part because there was no published mapping to create a colorimetric interpretation and the authors of the original paper were unresponsive to queries.
