### ISSUE TITLE
[css-text-3] Note unclear in bidi & line boxes

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#5759]
8.3. Bidirectionality and Line Boxes
https://www.w3.org/TR/2020/WD-css-text-3-20201119/#bidi-linebox

Note between eg 31 & eg 32

> Note: The inline base direction determined here applies to the line box itself, and not to its contents. It affects text-align-all, text-align-last, text-indent, and hanging-punctuation, i.e. the position and alignment of its contents with respect to its edges. It does not affect the formatting or ordering of its content. 

Sorry if i'm being slow, but the meaning here is not immediately apparent to me.  Surely the inline base direction does affect the ordering of the content, as demonstrated by the position of the exclamation mark in eg. 32?

What am i missing?

**Comment by fantasai** [comment]
The paragraph is talking about the inline base direction of the line box, not of the paragraph within it. We need to distinguish, because the text content always has an inline base direction but the line box is sometimes neutral. I'll try to make that clearer.

**Comment by fantasai** [comment]
OK, edited. Lmk if this works. :)

**Comment by r12a** [comment]
Here's a schematic of how i see the structure here, and an example of some text following the rules set out in this spec.

![Screenshot 2020-12-04 at 13 36 26 copy 2](https://user-images.githubusercontent.com/4839211/101176415-5cef7000-363e-11eb-9535-7d7414860f82.png)

A container (eg. a textarea) contains paragraphs, which in turn contain one or more line-boxes.

Note that the second line box from the top (the middle one) contains no directionally strong characters, but the base direction applied to the content is still RTL, because that information comes from the paragraph direction.

The bottom line box is contained within a paragraph that has content that is ordered LTR because the paragraph has no strong directional character, but the alignment is RTL because paragraphs with no strong directional character in plaintext take their alignment from the preceding paragraph (or the overall container, if there isn't one).

Current text in ED says:

> The start and end sides of a line box are determined by the inline base direction of the line box. Although they usually match, the inline base direction of a line box is distinct from the inline base direction of the containing block or the bidi paragraph. The line box’s inline base direction affects text-align-all, text-align-last, text-indent, and hanging-punctuation—i.e. the position and alignment of its contents with respect to its edges. It does not affect the formatting or ordering of inline content (which is controlled by the Unicode bidirectional algorithm as applied by [CSS-WRITING-MODES-3]). 

I would suggest:

The start and end sides of a line box are determined by the inline base direction of the **bidi paragraph**. Although they usually match, the inline base direction of a line box **can be** distinct from the inline base direction of the **bidi paragraph** or the **containing block**, **if the paragraph contains no strong directional characters**. The **paragraph**’s inline base direction affects text-align-all, text-align-last, text-indent, and hanging-punctuation—i.e. the position and alignment of its contents with respect to its edges. It **also affects** the formatting or ordering of inline content **unless the paragraph contains no strong directional characters** (**in which case, the ordering of content** is controlled by the Unicode bidirectional algorithm as applied by [CSS-WRITING-MODES-3]).

**Comment by fantasai** [comment]
OK, running through your edits (thanks for the bold):

* s/line box/bidi paragraph/ and s/line box/paragraph/ - this is incorrect. The sides are determined by the directionality of the line box, not the bidi paragraph. A perfect example is the second part of your illustration: the bidi paragraph (fed to the UBA) is LTR, but the alignment is determined as for RTL. Where is RTL coming from? We're calling that the line box’s direction, to distinguish from the bidi and container directions.
* s/is distinct/can be distinct/ - We can either go with “can differ” or “is distinct” here. “can be distinct” is a bit indeterminate: are they or are they not two different things?
* insert “if the paragraph contains no strong directional characters” - I'd prefer to keep the details of what conditions trigger this to the next paragraph, since they are very particular, and leave this paragraph as describing the higher-level concepts
* s/does not affect/also affects/ - invalidated by above point about paragraph vs line box direction
* remaining edits - The UBA always applies. Always. Rule P2 is only applied in the case of `plaintext`, but the UBA overall always applies.

I think the only edit I can take is “is distinct” -> “can differ”. Lmk if you want that one, and/or if things are still confusing. :)

**Comment by r12a** [comment]
> A perfect example is the second part of your illustration:

Which part?  The second line box or the second paragraph?

**Comment by fantasai** [comment]
>  Do you need that parenthetical text there, given that you then go on to specify how things work in the following text?

The following text does not specify how the UBA is applied, Writing Modes does, and I think referencing that is relevant here because we need to clarify that what we're talking about here *does not affect* how Writing Modes applies the UBA.

> The text in brackets at the end makes it sound as if each line box should arrange the ordering of inline content independently, by applying the UBA.

I don't think it implies that. It says "controlled by the UBA", which it is, "as applied by Writing Modes", which is very clear about how it maps the bidi paragraph. It doesn't say "as applied to the contents of the line box" which *would* create the confusion you describe.

> Which second part? The second line box or the second paragraph?

The second paragraph.

> It seems to me that this paragraph should begin with 'Otherwise, 

I think I had one there, but ended up with too many parentheticals. :) Since the if-clause there is a parenthetical for Otherwise. But maybe if I put "Otherwise" in parentheses, we end up not nesting them, like...
> (Otherwise) if the line box is empty (i.e. contains no atomic inlines or characters other than the newline character, if any) or otherwise has no strong directionality (contains only weak or neutral characters), its inline base direction is taken from the preceding line box (if any), or, if this is the first line box in the containing block, from the direction property of the containing block. (This can result in an RTL line box whose contents have an LTR base direction.)

???

> I think the text in parens at the end is too vague. I think you mean that the inline base direction of the line box (RTL) would cause the line box content to be aligned RTL, but the ordering of inline-level content within the line is LTR because it is 'controlled by the Unicode bidirectional algorithm as applied by [CSS-WRITING-MODES-3]'.

This is what I meant, yes. It doesn't need to pinpoint the exact example, it just needs to bring up the fact that the two directions can differ as a consequence. Bringing up the exact example is the job of an example, not the prose here.
