### ISSUE TITLE
[css-contain-1] Allow new features, in future?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5808]
The pubrules checker has a suggestion:

```
If it is the intention to incorporate new features in future updates of the Recommendation, 
please make sure to identify the document as intending to allow new features.
If it is the intention to incorporate new features in future updates of the Recommendation,
 please make sure to identify the document as intending to allow new features. 
Recommended text is:

    Future updates to this Recommendation may incorporate new features.

Include one of this source code:
<p>Future updates to this Recommendation may incorporate
 <a href="https://www.w3.org/2020/Process-20200915/#allow-new-features">new features<a>.</p>
```

@frivoal @tabatkins  Do we want to do that? If so, now (before Monday) would be the time :)

**Comment by svgeesus** [comment]
Since if doesn't commit us to anything, but allows adding new features, should we add this to the CSSWG Proposed Rec boilerplate?

**Comment by tabatkins** [comment]
Yes and yes.

**Comment by fantasai** [comment]
I don't think we'll be adding features to the REC of css-contain-1, we'd be adding it to css-contain-2, which already exists.

**Comment by frivoal** [comment]
* We cannot.  As [6.2.9](https://www.w3.org/2020/Process-20200915/#transition-pr) of the Process says:
  > A Proposed Recommendation may identify itself as intending to allow new features (class 4 changes) after its initial publication as a Recommendation, as described in § 6.2.11.4 Revising a Recommendation: New Features. Such an allowance cannot be added to a technical report previously published as a Recommendation that did not allow such changes.

   css-contain-1 has already been a REC before, and didn't carry this text, so it cannot be added now.

   (this is intentional: RECs that predate Process 2020 could not gain new features, and may be normatively referenced by things that count on this property to be maintained. So as not to change the existing meaning of REC, only things that declare the intention of gaining new features **prior to becoming a REC** can do so)

* We don't need to, since css-contain has a level 2, which deals with the new features.
