### ISSUE TITLE
[css-cascade] What happens to the priority of unmentioned layers in the presence of the @layers rule?

### ISSUE THREAD

**Issue by Alohci** [w3c/csswg-drafts#5810]
In [6.4.2. Layer-Ordering Shorthand: the @layers rule](https://drafts.csswg.org/css-cascade-5/#at-layers),  what is the priority of unmentioned layers? Do the mentioned layers take precedence over the unmentioned ones?

e.g.

if you have

span { ... }
@layer a  { span { ... } }
@layer b { span { ... } }
@layer  { span { ... } }
@layer c  { span { ... } }
@layers  c a;

is the priority low to high: b, (unnamed), c, a, (unlayered)

**Comment by fantasai** [comment]
`@layers a, b, c` is identical to `@layer a; @layer b; @layer c;`. As for unlayered rules, they're effectively part of a final unnamed layer: “For the purpose of this step, any declaration not assigned to an explicit layer is added to an implicit final layer. ”

All of the layers are ordered in the order they are first encountered. Last in the order wins for non-important rules, so in your example the rules would be ordered Line 2, Line 3, Line 4, Line 5, Line 1 and Line 1 would win any conflicts. The @layers rule at the end would have no effect, because layers c and c were already declared and their order thus already established.

**Comment by Alohci** [comment]
Ah, got it. I was thrown by @layers being described a Layer-**ordering** shorthand and the phrase "... **otherwise** has the same effect as declaring each layer name in order ..." when in fact that's **all** it is doing. Maybe it would be better titled as Layer-declaring shorthand.

**Comment by mirisuzanne** [comment]
Clarified in fc8de6465
