### ISSUE TITLE
[css-fonts-4] Installed font aliasing

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#5819]
The [font matching algorithm](https://drafts.csswg.org/css-fonts-4/#font-style-matching) contains:

> For other family names, the user agent attempts to find the family name among fonts defined via @font-face rules and then among available installed fonts, matching names with a § 5.1 Localized name matching as outlined in the section above.

Where § 5.1 says:

> Some font file formats allow font faces to carry multiple localizations of a particular string (e.g. family name or named instance). User agents must recognize and correctly match all of these names independent of the underlying platform localization, system API used, or document encoding.

This arguably doesn't match reality; for example [fontconfig aliases various metric compatible families](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/master/conf.d/30-metric-aliases.conf), which means that requesting "Helvetica" on most systems using fontconfig will find a font matching Helvetica, even though it's not any of the names that the font file format carries (e.g., here it will find Nimbus Sans).

I can see an argument that because it's a lower layer implementing this matching that it's conforming, whereas if the aliasing was done within the browser itself it wouldn't be conforming.

Regardless, we should probably take an explicit stance here (and that stance should probably be that this is conforming, given I don't see systems practically moving away from this).

To note: this came out from me trying to re-triage long-abandoned WebKit bugs, specifically from https://bugs.webkit.org/show_bug.cgi?id=6686 questioning whether "Garamond" should match either of "Apple Garamond BT" or "Adobe Garamond".

**Comment by svgeesus** [comment]
>> Some font file formats allow font faces to carry multiple localizations of a particular string (e.g. family name or named instance). User agents must recognize and correctly match all of these names independent of the underlying platform localization, system API used, or document encoding.

This originally said that matching was on the US-English localized name, regardless of locale. We got feedback on that and fixed it to allow any localization.

The fuzzy matching (Arial matching Helvetica, Helvetica Neue matching Helvetica, etc) is as you say a lower-level thing that we have no control over.

**Comment by litherum** [comment]
The spec shouldn’t be too prescriptive here. Just as in the discussions about font privacy, the spec can’t list exactly which fonts are installed on any machine, and I don’t think there is a reliably-testable difference between “both Helvetica and Arial are installed” vs “only Helvetica is installed but Arial maps to it too.”

We should just add a normative “may” to the spec allowing user agents to add aliases if they feel their users would be served by having those aliases.

Background: many Chinese websites hardcode Windows-specific font names. We have added aliases in WebKit on iOS and macOS to fonts which have a similar design, in order to try to improve fidelity with the author’s intent. Having the freedom to do this is important for both browsers and operating systems to better serve their customers.

**Comment by svgeesus** [comment]
Okay so this one just needs a bit of "may" prose allowing such aliasing to be conformant.
