### ISSUE TITLE
[css-color-4] What serialization should be used when using color(lab ...) syntax to specify a lab color?

### ISSUE THREAD

**Issue by samweinig** [w3c/csswg-drafts#5825]
With the `color(...)` syntax now supporting the `lab` predefined colorspace (https://www.w3.org/TR/css-color-4/#predefined), what serialization should be used.

My assumption is that the `lab(...)` syntax should be used (just as `lch(...)` values serialize to `lab(...)`, but that is just a guess and would be great to have this clarified in the spec.

A similar question exists for `color(srgb ...)`. In WebKit, we have been shipping a serialization where use of `color(srgb ...)` maintains the `color(srgb ...)` syntax.

**Comment by svgeesus** [comment]
Ok, good catch! We already have [4.7.3. Serializing Lab and LCH values](https://drafts.csswg.org/css-color-4/#serializing-lab-lch) but that spec text is specific to `lab()` and `lch()`. And we have [4.7.4. Serializing values of the color() function](https://drafts.csswg.org/css-color-4/#serializing-color-function-values) which applies to all of the `color()` function.

In general, the color serialization tries to preserve a color as specified.

Now, it it was just `color(lab l a b)` I could argue it either way, but we also have (partly from prompting by @smfr and partly from other feedback that we need to expose CIE XYZ) the form  `color(xyz x y z) and this is _only_ available on `color()`.

So I would suggest that `color(lab l a b)` serializes as itself, rather than being converted to `lab(l a b)` form.

Same argument for `color(srgb r g b)` - if someone goes to the trouble of using that new form, then that is what they should get back on serialization. Remember that there are multiple differences between this and the legacy `rgb(%, %, %)` and `rgb(n, n, n)`  forms - removal of commas, use of `/` as alpha separator, addition of real rather than integer values in the non-percent form (but still 0..255 rather than 0..1) for backwards compat. So if an author wants to express sRGB in a 0..1 rather than 0% .. 100% or 0 .. 255 form, `color(srgb n n n)` is the only way to do that and they should get back what they specified.

Apologies for not noticing this issue, first week back after a long seasonal break.

**Comment by weinig** [comment]
No need to apologize, thanks for looking into it.

Not that this should play much all too much into how this plays out, but in WebKit, what we do right now is:

For `rgb()`, `rgba()`, `hsl()`, `hsla()`, any named color or color using the hex notation:
  - we store the color internally as sRGB-8888
  - we serialize as either `rgba()` or `rgb()` if alpha is 255

For `color(srgb ...)`
  - we store the color internally as sRGB-FFFF
  - we serialize as `color(srgb ...)`

For `color(display-p3 ...)`
  - we store the color internally as DisplayP3-FFFF
  - we serialize as `color(display-p3 ...)`

For `lab()`, `lch()` and `color(lab ...)`
  - we store the color internally as Lab-FFFF
  - we serialize as `lab(...)`

I've included the internal storage here because that is what we _currently_ use to indicate to serialization what form it should use, but that is something that we can change if needed (we could, for instance store extra information about what style to serialize to, as we have some extra bits to spare in our color type). 

Looking at this set, the thing that pops out to me as perhaps making the most sense would be to serialize all "new" (e.g. not those grandfathered into the 1rgba()` or `rgb()` serializations) colors using the `color(... )` notation, and think of the other syntaxes as sugar in the same way that `hsla()` is sugar for `rgba()`. The change that would make in WebKit is that instead of serializing `lab()`, `lch()` and `color(lab ...)` as `lab()`, we would serialize it as `color(lab ...)`.

**Comment by svgeesus** [comment]
> The change that would make in WebKit is that instead of serializing `lab()`, `lch()` and `color(lab ...)` as `lab()`, we would serialize it as `color(lab ...)`.

I can see the logic of that. It would be a change to the spec too, but one I am certainly willing to make. Adding to the agenda this week to get more input.

**Comment by svgeesus** [comment]
Oh and [4.7.3. Serializing Lab and LCH values](https://drafts.csswg.org/css-color-4/#serializing-lab-lch) says

> The precision with which lab() component values are retained, and thus the number of significant figures in the serialized value, is not defined in this specification, but due to the wide gamut must be sufficient to round-trip L values between 0 and 100, and a and b values between ±127, with at least twelve bit precision; this will result in at least two decimal places unless trailing zeroes have been omitted. (16bit, or half float, is recommended for internal storage). Values must be rounded towards +∞, not truncated.

while [4.7.4. Serializing values of the color() function](https://drafts.csswg.org/css-color-4/#serializing-color-function-values) gives a minimum precision of 16 bits for `color(lab)` (and for `color(xyz)`.

Although that was the proposal agreed by CSSWG, looking at it again the minimum precision should be the same for the two syntactic forms, so the `twelve bits` should be increased to 16.

**Comment by svgeesus** [comment]
related precision-related discussion [here](https://github.com/web-platform-tests/wpt/pull/27202#issuecomment-761889901)

**Comment by svgeesus** [comment]
> looking at it again the minimum precision should be the same for the two syntactic forms, so the twelve bits should be increased to 16

[Now fixed](https://github.com/w3c/csswg-drafts/commit/f9305a1d694ffe4d293e3aeb94389b4a424aa9e7)

**Comment by svgeesus** [comment]
So concretely, for Lab and LCH: if we go with 

**Option A: serializing `lab()` and `lch()` with the shortest serializable form**

 then

> The serialized form of `lch()` and `lab()` values is derived from the computed value and uses the `lab()` form, with lowercase letters for the function name.

would become

> The serialized form of `lch()`, `lab()`, and `color(lab )` values is derived from the computed value and uses the `lab()` form, with lowercase letters for the function name.

while if we go for 

**Option B: serializing `lab()` and `lch()` as `color(lab ...)`** 

then the entire section [Serializing Lab and LCH values](https://drafts.csswg.org/css-color-4/#serializing-lab-lch) would be shortened, simply stating to serialize as `color(lab)`. Edited versions of the examples would move to [Serializing values of the color() function](https://drafts.csswg.org/css-color-4/#serializing-color-function-values) and the introduction to that section would change from

> The serialized form of `color()` values is derived from the computed value and uses the `color()` form, with lowercase letters for the function name and the colorspace name.

to

>  The serialized form of `color()`, `lab()` and `lch()` values is derived from the computed value and uses the `color()` form, with lowercase letters for the function name and the colorspace name.

**Comment by svgeesus** [comment]
Note that Option B makes `color(xyz ...)` (which has no other serializable form) and `lab()` more consistent.

However I would fine either option acceptable. So really it comes down to what people want to implement.

**Comment by svgeesus** [comment]
> For `color(srgb ...)`

>    we store the color internally as sRGB-FFFF
>    we serialize as `color(srgb ...)`

There are two options here:

**Option 1: continue to serialize `color(srgb r g b)` and `color( r g b)` as `color(srgb r g b)`**

where r, g and b are numbers in the 0 to 1 range. This is the current spec text.

**Option 2: serialize `color(srgb r g b)` and `color( r g b)` as `color(r g b)`**

Noting that the colorspace name, if omitted, defaults to sRGB. This is shorter than option 1, but continues to use the new syntax for the new syntactic form and the legacy syntax for the legacy `rgb()` etc. forms. 

Spec-wise, serialization of `rgb()` and `color(srgb)` currently _both_ require a minimum of 8 bits per component. But we could, if desired, increase the precision requirement for `color(srgb)` to guarantee that more of the specified precision is kept. And perhaps, accept that the legacy forms are mostly rounding (or in some cases truncating, which is bad and not per-spec) the values to 8bit, even for the percentage forms `rgb(% % %)` and `rgb(% % %)`

**Comment by svgeesus** [comment]
I guess also

**Option 3: continue to serialize `color(srgb r g b)` and `color( r g b)` as `color(srgb r g b)`, also extended precision `rgb()`**

**Comment by tabatkins** [comment]
This didn't get grabbed by the RESOLVED line, but just to call it out: note that the first resolution was amended to apply to non-sRGB functions. (So `hwb()` will serialize to `rgb()`, just like `hsl()`.)

**Comment by svgeesus** [comment]
> the first resolution was amended to apply to non-sRGB functions. (So hwb() will serialize to rgb(), just like hsl().)

Right. The spec already said that, and we resolved not to change that.

**Comment by svgeesus** [comment]
- [ ] All new color functions serialize to themselves
- [ ]  Make the first param in the color function, the color space, required
- [ ]  Have the minimum precision raised to 10 bits
