### ISSUE TITLE
[css-pseudo-4] Fine-tuning ::first-letter punctuation pattern matching

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5830]
In https://github.com/w3c/csswg-drafts/issues/5154 we updated the spec to include "intervening" white space. Certainly for spaces before the first letter this is correct, but the example of “`A "b"` will have `A "` selected” in @csnardi’s https://github.com/w3c/csswg-drafts/issues/2164#issuecomment-359817376 shows a real problem with this approach: since we reach out to following punctuation, allowing intervening white space *after* the first letter means we'll jump a word space and scoop up opening punctuation on the other side. :( I think we definitely need to make this smarter.

A few rules we could adopt that could help:
- Break on normal word spaces and nbsp, at least on the following side of the first letter. If people want to scoop up subsequent punctuation after a space, they'll have to use typographically correct space codepoints such as thinsp.
- Exclude opening punctuation following the first letter. In writing systems without a word space, we shouldn't be picking up the opening parens after the first "letter"! Po/Pi/Pf are ambiguous, but Ps is not.
- If there's an element boundary *after* the first letter, require that the UA close ::first-letter before that boundary, excluding the content after that element boundary, rather than allowing them to create ::first-letter after (excluding the first letter itself!) or both before and after the element boundary as we do currently.

I think we also need to do some more thinking about following Po/Pi/Pf/Pd. E.g. CSS2 and [Selectors 3](https://www.w3.org/TR/selectors-3/#first-letter) excluded Pd entirely but we generalized to all of P*. And we actually do need to include Pd before the letter because dashes are frequently used as an opening quotation mark, but is slurping them up into the ::first-letter *after* the letter correct?

CC @dauwhe @r12a @faceless2 @johannesodland

**Comment by johannesodland** [comment]
@fantasai Upon revisiting the resolution on this issue, I've identified a potential oversight that could significantly affect Norwegian typography.

The decision to exclude both the regular space (U+0020) and the no-break space (U+00A0) from either side of the letter inadvertently limits the utility of the ::first-letter pseudo-element for Norwegian texts. In Norwegian typography, direct speech is often indicated with an n-dash that's separated from the subsequent character by a space. (As discussed in https://github.com/w3c/csswg-drafts/issues/5154) Due to the challenges of entering special characters on many devices, authors often resort to using a regular space or, _at best_, a no-break space between the n-dash and the first letter.

By excluding these spaces before the letter, we risk rendering the `::first-letter` pseudo-element less practical for Norwegian content. Given that other languages, such as French, also utilize spaces between punctuation and the initial letter, this decision might have broader implications. I genuinely believe this deserves another look. Would it be possible to reevaluate this decision?"
