### ISSUE TITLE
[css-ui] Should the cursor property support image-set()?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5831]
WebKit's implementation of image-set allows you to use `cursor: -webkit-image-set()`.

There's a few tests in WPT (http://wpt.live/css/css-ui/cursor-image-014.html, http://wpt.live/css/css-ui/cursor-image-015.html), that seem to claim it should work (and it should support full `<image>` syntax). However the spec syntax only has `<url>`: https://drafts.csswg.org/css-ui-4/#cursor

cc @frivoal

**Comment by emilio** [comment]
Note that WebKit / Blink only allows `image-set(<url>)`, not `image-set(<image>)`

**Comment by SebastianZ** [comment]
See also the discussions in #2480 and #3432.

The prose currently has this note:

> User Agents may, instead of `<url>`, support `<image>` which is a superset.

I agree that at least `image-set()` should be supported in order to cover the use case of #2480.

Though I can also imagine use cases for the other values of `<image>` like e.g. a radial gradient as it's used as cursor in the device emulation mode of the Chrome DevTools, or using image fragments as cursors as supported by the `image()` function.
So I think we should go "all in" and support the whole `<image>` syntax.

Sebastian

**Comment by frivoal** [comment]
> However the spec syntax only has `<url>`

and

> The prose currently has this note:

>>    User Agents may, instead of `<url>`, support `<image>` which is a superset.

Right. As far as I remember, we wanted to allow and even encourage `<image>`, but only left it as a "may", without changing the base syntax due to the fact that implementations were lacking, and at least for level 3, we didn't want to claim things that weren't real. We could strengthen the encouragement in level 4.

**Comment by SebastianZ** [comment]
I've added a PR to change it to `<image>` and remove the note. So when there's WG consensus on this, it can be merged.

Sebastian

**Comment by emilio** [comment]
I have a few questions about supporting `<image>` entirely. Gradients and so on don't have sizes. What should be the size of the cursor when defined via `linear-gradient()` for example?

**Comment by SebastianZ** [comment]
How missing natural sizes of images are handled is already defined by this sentence:

> The default object size for cursor images is a UA-defined size that should be based on the size of a typical cursor on the UA’s operating system.

Sebastian

**Comment by SebastianZ** [comment]
Because the PR for this is lying around for quite some time now and I believe that's something the group can decide on in a call, I marked this as Agenda+.

Note, Gecko implemented partial support for the use of `image-set()` in cursor in https://bugzil.la/1695402. Other engines also only support `url()` in their `-webkit` prefixed versions.

The question now is, should the full `<image>` syntax be supported within the `cursor` property? If not, should at least `image-set()` with its syntax limited to `url()` values be supported?

Sebastian

**Comment by frivoal** [comment]
Addressed by https://github.com/w3c/csswg-drafts/commit/78fb03bd72db009decb0bdad200cd31f9dd9a235

**Comment by frivoal** [comment]
There was a pre-existing test for `image-set()` cursors in WPT, until now marked as optional. It is now [no longer marked as optional and I have updated the parsing tests as well](https://github.com/web-platform-tests/wpt/pull/33542), so we do have coverage for this feature. However it is minimal coverage, and we could do with more.
