### ISSUE TITLE
[css-sizing] Image aspect ratio revert to original width and height attribute

### ISSUE THREAD

**Issue by nextend** [w3c/csswg-drafts#5836]
Width and height attributes for images define the aspect ratio of that image since: https://github.com/whatwg/html/pull/4952

There should be a way in CSS to revert back to this original behavior if some other components redefined the width/height of that image in CSS. 

Here is an example: https://jsfiddle.net/g74a0me2/1/

The following redefines the width and height of the image, so the aspect ratio won't work as the attributes are overridden. 
```
img {
  width: 100%;
  height: 100wh;
}
```

Then we want to restore the original aspect ratio functionality for a subset of elements, but there is no way. For example with any of the following:
```
.my-image {
  width: auto;
  height: auto;
}

.my-image {
  width: initial;
  height: initial;
}

.my-image {
  width: revert;
  height: revert;
}

.my-image {
  width: attr(width px);
  height: attr(height px);
}
```

Related Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1161102#c9

**Comment by fantasai** [comment]
All of the methods you've described should restore the aspect ratio. None of them except the last one will restore the image to its attribute-specified *size* (but the last one, in theory, should have that effect).

For Cascade 5, we might want to make sure the HTML preshint level of the cascade is in a separate layer so that the single-layer revert being proposed in #5793 can unwind down but leave preshints untouched.

**Comment by tabatkins** [comment]
Right; since the aspect-ratio preshint isn't overridden in any of the cases presented here, and the remaining issue (explicitly reverting back to the *width and height* preshints* is covered by #5856, I'll close this issue as invalid.
