### ISSUE TITLE
[css-color-4] Consider removing lab(...) and lch(...) syntax and using color(lab ...) and color(lch ...) only

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#5887]
I'd like to propose unifying on the `color()` function syntax for new color types to simplify and unify things.

Right now, you can specify Lab colors directly via `lab(...)`  and `color(lab ...)` and indirectly via `lch(...)`. Since we have a construction for colors with fallbacks in the `color(...)` function already, I think unifying new color descriptions like Lab and LCH to use it would be a nice simplification while we still can. I think this would ease both user understanding (we can say all these new color types use the same syntax) and somewhat ease implementation burden (though I don't really think that should play into it, and it is tiny).

Anyway, food for thought.

**Comment by tabatkins** [comment]
I'm not a fan of this. It's a break from established tradition with color functions, it's more typing, you can't do lch() in color()'s syntax (channels are all number/percentage, not angle), and color() requires a more complex and harder-to-use TypedOM representation than the dedicated color functions.

**Comment by svgeesus** [comment]
Since this issue was opened, we have removed the fallbacks from `color()`, which simplifies it and makes it more like the other functional notations `lab()` and `lch()`.

The points made by @tabatkins regarding brevity and also the complication of allowing a hue angle (would we also add `hsl` and `hwb` to `color()`?) make me tend to want to close this issue with no change.

**Comment by weinig** [comment]
I think the oddity of having two serializations of Lab (lab() and color(lab...)) is still quite odd, and adds a bunch of complexity to the implementation since we need to track which way the color was written. 

Perhaps we could consider leaving lch() alone and removing lab() in favor of just color(lab ...)?

**Comment by svgeesus** [comment]
We could. Originally `color()` did not include lab; it was added at the suggestion of @smfr

**Comment by svgeesus** [comment]
It would be good to get the thoughts of other implementers ( @faceless2 ? ) and content creators on

1. Just have `lab()`, remove lab from `color()`
2. Just have `color(lab ...)`, remove  `lab()`
3. Have both  `lab()` and `color(lab ...)` (the current situation)

**Comment by svgeesus** [comment]
Personally, the logical flow of section [Device-independent Colors: Lab and LCH](https://drafts.csswg.org/css-color-4/#lab-colors) followed by [Profiled, Device-dependent Colors](https://drafts.csswg.org/css-color-4/#icc-colors) - plus the descriptive flow of subsections in those two sections - seems clear. So in terms of specification organization, I would rather keep it that way rather than "oh and if you want to actually specify a Lab color, see the `color()` section".

I take the point about keeping track of which way Lab was specified, so of the three choices above my preference would be option 1. Just have `lab()`, remove lab from `color()`.

**Comment by faceless2** [comment]
(@weinig, you're on the Safari team I think?)

I think it would be a shame to lose `lab()` - it's short. Short is good.

If I'm honest I can't see that `color(lab)` is going to help anyone - it's conceptually nice to have a single way of addressing all the colorspaces, but as we're missing `device-cmyk`, `lch` and so on from that syntax already so if it's just there for consistency, we've missed that target already.

Removing it for us is literally one line of code and we're still not shipping, so if it's causing more work for anyone else we're absolutely fine with dropping it.

**Comment by LeaVerou** [comment]
What if we just change the serialization so that it doesn't need to be preserved whether it was specified as `lab()` or `color()`? We obviously need to preserve it for `sRGB`, but not sure there's any strong rationale for preserving the difference here, except that we have a recent resolution that except legacy colors, colors are serialized as specified. We can always change that (though `color(srgb)` would need to be preserved regardless).

**Comment by tabatkins** [comment]
I'd much rather have a single canonical syntax than a single canonical serialization.

Since we only added `color(lab)` at @smfr's suggestion, and we're discussing removing it at @weinig's suggestion, I suggest we let the Apple folks work out amongst themselves which they'd prefer and let us know when they've come to an agreement. ^_^

**Comment by svgeesus** [comment]
@faceless2 wrote:

> (@weinig, you're on the Safari team I think?)

Yes. Implementer of CSS Color 4 in BFO Publisher, meet implementer of CSS Color 4 in Webkit :)

**Comment by Crissov** [comment]
What if `color()` was only for cartesian coordinates and there were other functions for cylindrical and polar representations?
