### ISSUE TITLE
[css-highlight-api] maplike vs setlike

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5910]
from https://github.com/w3ctag/design-reviews/issues/584#issuecomment-767655588

> @hober and I discussed this today in our VF2F. We noticed that HighlightsRegister is a setlike, but throws when a Highlight object with an existing registered name, which indicates that perhaps maplike would have been more appropriate? It's not ideal developer experience if developers need to iterate the entire data structure before registering their object, to check if an existing one of the same name exists. Maplike would also provide an easy way to get all ranges under a given name.

**Comment by tabatkins** [comment]
Yeah, setlike should only be used if object identity is sufficient for membership. (Or, if a derived key is instead used for uniqueness, adding something else with the same derived key causes replacement, but that's treading on thin ice.) 

If uniqueness depends on a derived key *and* replacement isn't allowed, then it's not a setlike at all, it's a registration map with write-once semantics, and should be a maplike.

**Comment by sanketj** [comment]
@LeaVerou @hober @tabatkins 

The original explainer did use maplike for this (the type was originally called `HighlightMap`), and the Highlight object (originally called `HighlightRangeGroup`) would only need to be named when it was being registered. The reason this was problematic was that the same Highlight object could be registered multiple times under different names. To prevent that, we would have to override put, and either iterate the entire data structure to check if any map entry already has that Highlight as its value (which has similar performance to what we do today), or require authors to create Highlights with a name and also register with that exact same name (which doesn't seem developer friendly).

That's why we went with the current approach. If there's a better solution that we're missing, we'd love to hear it.

**Comment by LeaVerou** [comment]
@sanketj Just so I understand the problem: what was the issue with having the same highlight object registered multiple times under multiple names? Why did this need to be prevented?

**Comment by sanketj** [comment]
Even if we allowed the same highlight object to be registered under multiple names, only one name can be reliably used to style the highlight. If the highlight were to be styled using multiple names, in the case of conflicting styles, the styles for the last registered name would always be painted on top and there would be no way to 'prioritize' the styles for names that were registered earlier. This could be confusing for authors because the paint order may not reflect the expected cascade order. For example, consider the following style rules where the same highlight object is registered with names 'foo' and 'bar', and 'bar' was the last registered name:
```
#p1::highlight(foo) {
    color: yellow;
}

#p1::highlight(bar) {
    color: red;
}

#p1::highlight(foo) {
   color: green;
}
```
Each rule targets the same highlight and has the same specificity, therefore authors may expect the last rule to win and the color of the highlighted content to be green. In reality, `::highlight(foo)` and `::highlight(bar)` are independent pseudo-element selectors and the highlight will be painted twice - once with the green color for 'foo' and once with the red color for 'bar'. Because 'bar' was registered later, the red color would be painted on top. Even if we used `color: green !important` for the third rule, the red color would still paint on top.

Though one could argue that this is not technically a cascade violation, it is definitely confusing behavior. So I think it is best to enforce that a highlight object can only be registered with a single unique name.

**Comment by frivoal** [comment]
In short:
* registering the same highlight multiple times under different names -> they share the priority, which is confusing as @sanketj explained about  -> switched from map to set
* registering a new highlight under an existing name could either replace the old one, or throw. throwing seems to allow for better detection of accidental collision between highlights. That said, we could change that.

Another alternative could be to switch back to a map, and do something if an already registered highlight gets registered again under a new name (throw? remove the older one?). Maybe you can help me think through something here: can we reliably test object equality in JS?

Or maybe we switch back to map, and allow duplicate entries (with at most, a warning in the console), and just advise authors not to do that…

**Comment by LeaVerou** [comment]
@sanketj Isn't this the same in terms of author experience as a new highlight being registered that spans the same text as another highlight? (which is allowed)

@frivoal 

> Maybe you can help me think through something here: can we reliably test object equality in JS?

It depends. What kind of equality would you like to test?

**Comment by sanketj** [comment]
@LeaVerou It is different from the overlapping highlight case because those are actually separate highlight objects. Authors will expect the styles for the two highlights to be independent, and they have the option to control which styles paint on top via the `priority` property. In the case where both names target the same highlight, it is confusing that the highlight gets two independent sets of styles. Additionally, authors cannot control the prioritization of conflicting styles - the styles for the name that was registered later will always paint on top.

That said, if all we are debating is maplike vs. setlike, I do agree with @frivoal that we could switch back to maplike and override the 'set' operation to throw if we try to register a previously registered name.

**Comment by sanketj** [comment]
Summarizing a few approaches based on this thread to guide our vF2F discussion:

Approach 1 (what is currently spec'ed):
`Highlight` objects are constructed with a name, which guarantees that each highlight will have exactly one name. `HighlightRegistry` is a `setlike` collection of registered `Highlight` objects. Multiple independent highlights may be constructed with the same name, but only one can be registered at any time. To avoid duplicate registrations, the `HighlightRegistry.add` API compares the new highlight's name with all previously registered highlight names. If the name was previously registered, the API throws and fails; otherwise, the `add` operation succeeds.

Approach 2:
`Highlight` objects are not associated with a name at construction. Instead, they are given a name when they are registered. `HighlightRegistry` is a `maplike` that takes a highlight name as key and `Highlight` object as value. This approach allows the same `Highlight` to be registered under multiple names, which seems problematic because this allows a highlight to have multiple independent sets of styles and no way to prioritize amongst them (see previous comments in this issue for more details).

Approach 3:
Same as approach 2, but disallow registration of the same highlight under different two names by overriding the `HighlightRegistry.put` API. When registering a highlight, checks the values in the `HighlightRegistry` to see if the new highlight was previously registered. If the highlight was previously registered under a different name, throw and fail. Otherwise, the `put` operation succeeds.

**Comment by LeaVerou** [comment]
> @LeaVerou It is different from the overlapping highlight case because those are actually separate highlight objects. 

I'm not convinced this is a conceptual difference for authors vs an implementation detail. 

> Authors will expect the styles for the two highlights to be independent, and they have the option to control which styles paint on top via the `priority` property. 

This sounds like maybe the `priority` property should be specified at registration then? Just a thought.

I'm also not sure the inability to specify the priority for this edge case is that much of a problem. E.g. authors may wish to register a highlight under many different names to give their users the option of which one to use, without having to keep multiple objects in sync. I can see this being useful for syntax highlighters, e.g. Prism does provide aliases for a lot of its tokens. OTOH, I do agree that the code example presented in https://github.com/w3c/csswg-drafts/issues/5910#issuecomment-803819714 is indeed confusing.
