### ISSUE TITLE
[css-contain] :root/body viewport propagation and containment

### ISSUE THREAD

**Issue by lilles** [w3c/csswg-drafts#5913]
While investigating containment for container queries I've encountered the issue of propagating html/body properties to the viewport. The simple case for container queries is that if you set containment on the html element, expecting the size of the html element being determined without looking at descendants. But if the body element changes the writing-mode, that writing-mode is propagated to the viewport, but also affects the used value for the html element.

This is a circularity problem for container queries because you can have:

```html
<style>
  html { contain: strict }
  body { writing-mode: horizontal-tb }
  @container (min-width: 1000px) { body { writing-mode: vertical-lr } }
</style>
```

and the width of html element may change because of the writing-mode which would then flip to a different writing-mode which gives a circularity.

Disregarding container queries, there is a question if there is an issue with propagation and containment for root/body propagation. Consider this case:

```html
<!doctype html>
<html>
  <head>
    <title>
      The layout of the html element depends on the overflow property of the
      body element which is propagated to the viewport. There are other properties
      which are propagated to the viewport, but also affects the used value of the
      html element. That is, the writing-mode. The used value for writing-mode on
      the html element depends on the computed value for writing-mode on the body
      element. Is there enough text to break this line now?
    </title>
    <style>
      html { overflow: visible; contain: strict }
      body { overflow: scroll; }
      head, title { display: block; }
    </style>
  </head>
  <body></body>
</html>
```

All of Blink, WebKit, Gecko propagate the overflow:scroll to the viewport affecting the layout of the html root element.

Should containment somehow stop propagation to html/viewport?

**Comment by lilles** [comment]
A new proposal:

What if we propagate properties from body to viewport as if no container queries match, but the computed style on body will be evaluated as for any other element.

So in the case below the computed overflow on body will be 'visible', but the value propagated to the viewport will be 'scroll':

```html
<style>
  html {
    width: 500px;
    contain: layout size;
  }
  body {
    overflow: scroll;
  }
  @container (min-width: 400px) {
    body {
      overflow: visible;
    }
  }
  @container (max-width: 400px) {
    body {
      overflow: hidden;
    }
  }
</style>
```

That means we need to store the propagated properties separately. Implementation-wise for Blink, it would probably be done by computing a separate set of computed values for body if the the body computed style depends on container queries for any of the propagated properties.

If the author refrains from adding overflow, writing-mode, etc inside @container rules for body, there should be no extra cost.

**Comment by lilles** [comment]
I've done a [Blink implementation](https://chromium-review.googlesource.com/c/chromium/src/+/2851739) of the alternative [proposal](https://github.com/w3c/csswg-drafts/issues/5913#issuecomment-814726342) to see if it could work.

What I did was to cascade these properties in a separate step for `<body>`:

* direction
* overflow
* writing-mode
* display

where the three first are the ones propagated to the viewport which may affect layout, hence affects container queries, and `display` because the display property may affect whether the properties should propagate to the viewport or not in the first place.

**Comment by lilles** [comment]
I have tried to outline the alternatives I have found in [this document](https://docs.google.com/document/d/1mpN2I0KYVmIoB8LfSV3pzPAoqGBIrubybHPzrhc2dxA/edit#bookmark=id.lk5mhushkdno).

Note that one of the alternatives is relying on the resolution for issue #6178.

**Comment by mirisuzanne** [comment]
Since we agreed to [deprecate propagation from the `body` element](https://github.com/w3c/csswg-drafts/issues/6079#issuecomment-816307011), I don't think we should go out of the way to preserve the behavior, beyond what's required for backwards-compatibility.

Even if #6178 doesn't require root containment by default, that does seem like a very popular/desirable option for authors to add explicitly - and it would be unfortunate if we had to disallow that entirely.

**Comment by fantasai** [comment]
Note that propagation from root to viewport is not affected by containment.

**Comment by lilles** [comment]
Just a couple of clarifying questions/statements:

* Containment on the html root element stops propagation from body, containment on body should be irrelevant.
* By containment, do we mean _any_ containment?
* And by containment, we mean _used_ (applied?) containment, since some properties implies containment without affecting the computed value, like content-visibility?
* Also that would make this resolution compatible with introducing a separate syntax for defining what becomes a container for container queries, since that would typically also make the containment used/applied but not affect computed value for contain.
* Should the edits go into the relevant specs for body propagation like writing-modes, overflow, and backgrounds, or should this be a common section for body propagation in css-contain?

**Comment by lilles** [comment]
Re-opening for getting the questions above clarified.

**Comment by lilles** [comment]
Agenda+ to clarify resolution. See: https://github.com/w3c/csswg-drafts/issues/5913#issuecomment-836692271

**Comment by fantasai** [comment]
IIRC containment on the body also stops propagation.

**Comment by lilles** [comment]
Sorry, didn't see this before. We only need this for containment on the root html element. If you have containment on body, that should not be a problem. I thought we discussed that, but I don't see that from the meeting notes.

**Comment by frivoal** [comment]
* Meetings notes / resolution apply to both equally, so on procedural grounds, we're covered.

* Propagation from body is a compat hack anyway, so since containment on body is a new thing, we can make the change without breaking things.

* Even if it's not strictly needed for container queries, from a containment standpoint in general, I think it is beneficial anyway:
  * on every other element, a change of the overflow property from visible/clip/hidden to auto/scroll can only affect the layout of descends. On body, since it'd change the viewport, it can affect the layout of the element itself. Same thing for writing-mode. Disabling that is a good thing to have
  * similarly for contain:paint, body is the only element where changing the background would require a repaint of ancestors <small>(well, maybe except https://github.com/w3c/csswg-drafts/issues/6325, but that's another story)</small>

@lilles So I think it's fine. If you think it's a problem we went this way, maybe reopen a more narrowly scoped issue?
