### ISSUE TITLE
[mediaqueries][mediaqueries-4] `scan` feature...is there any actual support/need for this?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/csswg-drafts#594]
Not sure if this is a determining factor or not at this stage, but: not only is there currently no actual support for https://drafts.csswg.org/mediaqueries-4/#scan (from testing this recently on various "web on TV" browsers/set-top-boxes), but I'm wondering if the actual use case this tries to address (distinguishing between interlaced and progressive displays) isn't now actually disappearing?

**Comment by frivoal** [comment]
This has been there since the last level of the spec, which is already a REC. I agree that the likelyhood of running into an interlaced display is going down and that the use-case is fairly narrow to start with, but I don't think there is anything inherently wrong with this MQ. The cost of standardizing seems to have already been paid, and it is already implemented https://www.w3.org/Style/CSS/Test/MediaQueries/20120229/reports/implement-report.html#parsing-scan

That said, I just realized there is a difference between the level 3 version of this feature, and the level 4 one: in level 3, this was meant only to apply to the TV media type, but in level 4 there is no such restriction.

I guess this leaves us with a two main options:
- Tie it back to the tv media type, which is deprecated, so deprecate this as well: everybody must parse it, everybody must return false.
- Keep it in as it is specified in level 4: everybody must parse it, and must return true to either `progressive` or `interlace`

@tabatkins Do you remember if the difference between the two levels was intentional? What's your take on this, should we revert the change and make it forever useless, or keep it and impose a small but non zero cost on implementors to adjust their behavior to the new spec?

**Comment by patrickhlauke** [comment]
if you're happy with the feature to be included even though actual interlaced displays in the wild are, to my knowledge, disappearing, then i'd say it makes sense to keep this uncoupled from `tv` media type (as generally there could be interlaced `screen` displays too).

**Comment by markbrown** [comment]
@frivoal Why do you say that everybody must return true to either `progressive` or `interlace`?

In [Section 2.4](https://drafts.csswg.org/mediaqueries-4/#mq-features) it says:

> If a media feature references a concept which does not exist on the device where the UA is running (for example, speech UAs do not have a concept of “width”), the media feature must always evaluate to false.

which implies that the options for features are not necessarily exhaustive. Also, Example 13 mentions that `(scan)` may evaluate to false, meaning that neither value is true.

Given this, is there in fact a difference between the two levels?

**Comment by frivoal** [comment]
Ok, if you have a display which is neither progressive nor interlaced, you should be free to return false for both values.

But common screens are progressive, and so the spec expects them to return true on that value.

**Comment by markbrown** [comment]
I was thinking of the case where the media type is `print`. In this case I take it that the rule I quoted above applies, and `(scan)` ought to be false.

But if that's not correct, could the spec be clarified?

**Comment by patrickhlauke** [comment]
@markbrown i don't think the spec needs to be clarified, as it doesn't currently say anything to the contrary. or do you mean adding an additional note that explicitly says that on devices without a monitor output, BOTH `scan:progressive` and `scan:interlace` will return false? if the latter, then it would seem weird to do it just for `scan`, as there are other similar things like `orientation` that potentially also should evaluate to false for all their possible values on a headless device

**Comment by markbrown** [comment]
@frivoal Thanks, the spec is fine. It was only your comment from above that confused me, but you've clarified that.

**Comment by frivoal** [comment]
@patrickhlauke Are you fine with closing this issue as no change?

**Comment by patrickhlauke** [comment]
sure i'm happy to close it. reason i didn't do it myself before was because i thought you still had some outstanding thoughts on the matter here https://github.com/w3c/csswg-drafts/issues/594#issuecomment-253442827
