### ISSUE TITLE
[css-ruby] replaced annotation containers and base containers are nonsensical

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6000]
It doesn't seem to make sense to allow a replaced element to be a base container or an anotation container. Suspect the easiest thing to do is to adjust the box fixup so that replaced base containers get turned into replaced bases with an anonymous base container around them (and the analogous thing for annotations). Should we just do that, or something else?

Also, how should this affect / not affect is computed `display` value?

**Comment by upsuper** [comment]
I don't think I agree with this decision.

It doesn't sound useful to define the behavior this way. Why would any reasonable developer would want to assign a ruby internal `display` value to a replaced element? If they want to see such element in ruby base or annotation, just drop it into a `<rb>` or `<rt>`. Using those special value with replaced element also easily discards the semantics of ruby for non-CSS consumers. 

In addition, it doesn't seem to me that we have any precedence for this, e.g. we don't handle replaced element with table internal `display` values specially, fixing up them so that they can form part of the table, do we? I don't quite see why it's important to handle ruby internal `display` values specially. This would likely require impls to add extra code for an edge case which may just never happen.

But I don't know how replaced elements should be handled in general with weird `display` values. If it's not defined anywhere, it's probably better to be defined in a general term, rather than case-by-case for each `display` values. I suggest that we just ignore the display internal values, and treat them as `inline` like what Gecko does currently.

**Comment by frivoal** [comment]
While I think the spec needs to handle this situation in some way, I am not strongly attached to the particular way we just resolved on, and your suggestion seems good: saying that such elements should be treated as display inline, and letting the box fix-up give them appropriate parents. That would be inline with what the table spec does since https://github.com/w3c/csswg-drafts/issues/508.

I suppose that we could solve this generically by having this requirement in in css-display in the https://drafts.csswg.org/css-display-3/#layout-specific-display section (loosely inspired by the text at the end of https://drafts.csswg.org/css-tables/#table-structure):

> When the 'display' property of a [=replaced element=] computes to one of the [=layout-internal=] values, it is handled  as having a used value of ''display/inline''. White space collapsing and anonymous box generation must happen around those replaced elements based on that ''display/inline'' value, as if they never had a [=layout-internal=] display value applied to them. 
> Advisement: Authors should not assign a [=layout-internal=] display value to [=replaced elements=].

Then, css-ruby (and css-tables) could just refer to it.

**Comment by frivoal** [comment]
Solved by https://github.com/w3c/csswg-drafts/commit/2297b7b60a7bf76bf1a2b40ac9a0012fa210b7be.

Will close this issue soon unless someone thinks I got it wrong.
