### ISSUE TITLE
[css-color-5] Can "relative color syntax" channel constants be used for a channel other than the one it represents?

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6043]
In CSS Color 5's Relative color syntax, https://drafts.csswg.org/css-color-5/#relative-colors, the spec is not clear on whether it is valid for a channel constant to be used for channel other than one it represents. For example, is the following valid:

```css
    color: rgb(from teal g b r);
```

I could some value in this ability to permute things, but not a ton. In my investigative implementation in WebKit, I have disallowed this pending more clarity. 

(also, I wrote a bunch of tests for this feature, https://trac.webkit.org/browser/webkit/trunk/LayoutTests/fast/css/parsing-relative-color-syntax.html?rev=273127,  but I am not clear if they make sense for WPT at the moment, given the early stage of the spec, please let me know if would be useful to make a PR to add them and I'd be happy to).

**Comment by tabatkins** [comment]
Yes, they can. I don't recall if there was an example showing that off previously, but there is now (Example 9).

The usefulness of this seems relatively low, but I can imagine usecases, and I also imagine that it's easier to have a single parsing form for all the arguments rather than four individually specified forms per function that each allow a single different keyword.

**Comment by samweinig** [comment]
The parsing difficulty is about the same in both cases, since you have to specify which identifiers are valid for each channel in the cases where not all the channels represent the same type (like lch for example, where l and alpha are percentages, c is a number and h is an angle). Here is a link to my implementation without support channel permutation in case you are interested: https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp#L1282 (though it still lacks the calc() support as I need to implement injecting identifiers into calc()).

Looks like the spec does have an example now with Example 9:

```css
--blue-into-gray: rgb(from var(--color)
                    calc(r * .3 + g * .59 + b * .11)
                    calc(r * .3 + g * .59 + b * .11)
                    calc(r * .3 + g * .59 + b * .11));
```

which seems reasonable enough. Thanks for the clarification.
