### ISSUE TITLE
[css-grid-1] Distribution of intrinsic sizes according to flex factors doesn't handle sum < 1

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6078]
https://www.w3.org/TR/css-grid-1/#algo-spanning-flex-items
> if the sum of the flexible sizing functions of all flexible tracks spanned by the item is greater than zero, distributing space to such tracks according to the ratios of their flexible sizing functions rather than distributing space equally 

Distribution of free space in “Expand Flexible Tracks” has special behavior for when the sum is less than one in order to get continuity between sum = 0fr and sum = 1fr, but this behavior is not reflected in the flex-dependent distribution rule under Resolve Intrinsic Track Sizes.

**Comment by Loirooriol** [comment]
I already mentioned this possibility in #3694, but when we discussed it, not distributing the whole contribution didn't seem the right thing to do. Though I guess we could still distribute it all and have continuity by saying something like:
1. If the sum of the flexible sizing functions is < 1, multiply the space to distribute by that sum.
    Otherwise use the space to distribute.
2. Distribute that (if > 0) according to the ratios.
3. Distribute the remaining space (if > 0) equally.

So, when distributing 100px among two flex tracks,

| Tracks  | Current | Continuous |
| ------------- | ------------- | ------------- |
| 0fr 0fr  | 50px 50px  | 50px 50px  |
| 0fr 0.1fr  | 0px 100px | 45px 55px |
| 0fr 1fr  | 0px 100px | 0px 100px |
| 0.1fr 0.3fr  | 25px 75px | 40px 60px |
| 0.2fr 0.6fr  | 25px 75px | 30px 70px |
| 0.3fr 0.9fr  | 25px 75px | 25px 75px |

**Comment by tabatkins** [comment]
Yes, not distributing the space doesn't work here (since we're trying to size the tracks to the content, so they *do* need to grow). We currently distribute that space equally when the sum is 0, and proportionally when it is > 0. As shown by the first three rows in your table, your suggestion is a reasonable blend of the 0fr and 1fr behavior that creates continuity between the two states, so it sounds okay to us.

Agenda+ to confirm this change to the distribution rules is okay with the WG.

**Comment by fantasai** [comment]
Edits checked in. @Loirooriol would you mind reviewing? (Close out the issue if it looks OK.)

**Comment by Loirooriol** [comment]
Maybe it would be clearer to handle this in https://drafts.csswg.org/css-grid/#extra-space rather than monkey-patching it in https://drafts.csswg.org/css-grid/#algo-spanning-flex-items, but I guess it's good.

**Comment by Loirooriol** [comment]
Just some math, in case someone finds it useful.
When distributing among `n` tracks, the `i`-th one gets this fraction of the space:

 - If no flex tracks (equal distribution): `1 / n`
 - If `s ≥ 1`: `fⁱ / s`
 - If `0 ≤ s < 1`: `fⁱ + (1-s)/n`

where `fⁱ` is the flex fraction of the`i`-th track, and `s = ∑fⁱ` is the sum of flex fractions.

**Comment by dholbert** [comment]
@Loirooriol or others: do we know if this spec-change was implemented anywhere?   In particular, the part where we should distribute the remaining space *equally* after we've distributed a portion for the fractional-`fr`-units-that-sum-to-less-than-1.  That is reflected in the spec at https://drafts.csswg.org/css-grid-2/#algo-spanning-flex-items ("...and the rest equally") but I'm not seeing any browser have that behavior.

I wrote a test with `grid-template-columns: 0.1fr 0.3fr;` and with a 100px-wide grid item that spans those two columns, and then I've got "marker" items in the next row to show how wide the columns end up being.
https://jsfiddle.net/dholbert/g1qowxrb/

With this spec change, I think the expected result of my testcase would be for the tracks to be `40px 60px`, per the table that @Loirooriol provided in his [comment above](https://github.com/w3c/csswg-drafts/issues/6078#issuecomment-791558329).   But Chromium and WebKit currently end up with `25px 75px` which seems to be the old behavior of just distributing proportionally. (Firefox does something else which is also clearly wrong.)

**Comment by dholbert** [comment]
Here's an example where I'm trying to get directly at the discontinuity around 0 that we were trying to fix here:
https://jsfiddle.net/dholbert/gypkm461/

This jsfiddle has 3 grids which have column sizes `0fr 0fr`, `0fr 0.1fr`, and `0.1fr 0.1fr`.  The expectation is that the second grid (the one with `0fr 0.1fr`) should have its tracks sized ~similarly to the other two, with just a small difference in column sizing (10px I think).    But Chromium and WebKit collapse away that grid's first column entirely (as shown by the orange marker-item not showing up at all there).

So I think this is an indication that nobody has yet implemented this spec change; but please correct me if I'm wrong. Thanks!  (This is on my radar because we've got an engineer working on getting Gecko up-to-date on this part of the spec right now.)

JSFiddle Source:
```css
.grid {
  display: grid;
  grid-template-rows: 40px 40px;
  border: 5px solid black;
  margin: 5px;
  width: 120px;
}
.item {
  width: 100px;
  grid-column: 1 / span 2;
  border: 3px solid blue;
}
.marker {
  background: currentColor;
}
```
```html
0 0:
<div class="grid" style="grid-template-columns: 0fr 0fr">
  <div class="item"></div>
  <div class="marker" style="color:orange"></div>
  <div class="marker" style="color:fuchsia"></div>
</div>
0 0.1:
<div class="grid" style="grid-template-columns: 0fr 0.1fr">
  <div class="item"></div>
  <div class="marker" style="color:orange"></div>
  <div class="marker" style="color:fuchsia"></div>
</div>
0.1 0.1:
<div class="grid" style="grid-template-columns: 0.1fr 0.1fr">
  <div class="item"></div>
  <div class="marker" style="color:orange"></div>
  <div class="marker" style="color:fuchsia"></div>
</div>
```

**Comment by Loirooriol** [comment]
I kind of remember working on this for Blink's legacy engine, but possibly I didn't finish the patch, and LayoutNG rewrote the entire thing anyways.
