### ISSUE TITLE
[css-overflow-4] Do not remove overflow: overlay

### ISSUE THREAD

**Issue by karl-police** [w3c/csswg-drafts#6090]
I came from https://stackoverflow.com/questions/23200639/transparent-scrollbar-with-css/56365213#56365213 where someone commented that "overlay" would be deprecated.

I saw on stackoverflow that people do still find that question and find it very helpful. So, I asked at Mozilla mail and they linked me this https://github.com/w3c/csswg-drafts/issues/92 and then told me to go to MDN for uhh... I believe it was related to push changes for the docs. But I came here instead, to know if it is still deprecated.

So, is it still deprecrated? And if yes, can this be undone? It's still being used? Hm, I do believe there are better ways to maybe implement the feature, so "overflow" can be used for other things, but I didn't see that yet.

**Comment by tabatkins** [comment]
`overlay` was never in fact defined, so it never needed to get deprecated. ^_^  It existed in WebKit and was exposed to the web temporarily, but was later removed, and the Safari team has no plans to re-add it at the moment.

(I'm sad about this and *really* wish we could *all* move to overlay scrollbars, as it would make many parts of CSS less complicated, but oh well.)

**Comment by karl-police** [comment]
> `overlay` was never in fact defined, so it never needed to get deprecated. ^_^ It existed in WebKit and was exposed to the web temporarily, but was later removed, and the Safari team has no plans to re-add it at the moment.
> 
> (I'm sad about this and _really_ wish we could _all_ move to overlay scrollbars, as it would make many parts of CSS less complicated, but oh well.)

sooo.. there is nothing we could do?

**Comment by tabatkins** [comment]
Specs can't force implementations; they exist to help increase interoperability *between* implementations (and guide the design of features in conjunction with the impls). We currently have one major impl (Safari) with a stated preference for *definitely not* doing this, and the other impls are at best apathetic about the feature at the moment. So, from the spec side of things, there's not much we can do; I prefer writing specifications, not speci-fiction. ^_^

From the author side, you can put pressure on the impls by filing bugs or +1ing existing bugs, and/or making noise and gathering support on blogs and social media. If the impls change their stance as a result of webdev pressure, we can revisit the issue.

**Comment by frivoal** [comment]
Also, note that while that's not exactly the same thing, there's also the [`scrollbar-gutter` property](https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property) which is somewhat related, and is getting some degree of traction. Not saying that's a full replacement, but if you care about this sort of things, it's probably worth knowing about.

**Comment by karl-police** [comment]
> Also, note that while that's not exactly the same thing, there's also the [`scrollbar-gutter` property](https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property) which is somewhat related, and is getting some degree of traction. Not saying that's a full replacement, but if you care about this sort of things, it's probably worth knowing about.

I saw it, not sure if any browsers support it yet. I tried using it.

**Comment by SebastianZ** [comment]
> We currently have one major impl (Safari) with a stated preference for _definitely not_ doing this

Chromium based browsers still have an implementation of `overflow: overlay` at the moment. @tabatkins Could you please post a link to WebKit's stated preference for reference?

Sebastian

**Comment by tabatkins** [comment]
I can dig it up if necessary, but @smfr was very explicit about considering `overlay` being exposed to the web to be a mistake. I know we discussed this at a face-to-face, so it should be in meeting minutes, and it might have shown up in an issue or email thread as well.

**Comment by smfr** [comment]
I made it a synonym for overflow:auto in webkit: https://trac.webkit.org/changeset/236341/webkit

**Comment by amir2mi** [comment]
@smfr they might be the same at the first sight also `scrollbar-gutter` mixture. but a scroll bar that does not affect neighbors in wrapper something like position absolute for elements is such a great feature that can change and improve many websites UI.

**Comment by frivoal** [comment]
@karl-police 

>> … the [`scrollbar-gutter` property](https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property) …

> I saw it, not sure if any browsers support it yet. 

Not yet, but should be [coming soon to a chrome near you](https://bugs.chromium.org/p/chromium/issues/detail?id=710214).

**Comment by karl-police** [comment]
> @karl-police
> 
> > > … the [`scrollbar-gutter` property](https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property) …
> 
> > I saw it, not sure if any browsers support it yet.
> 
> Not yet, but should be [coming soon to a chrome near you](https://bugs.chromium.org/p/chromium/issues/detail?id=710214).

So it seems to be that time, apperantly. The ``scrollbar-gutter`` property was put in Google Chrome. Since it was recently put in, you would need the Google Chrome Nightly build to test it.


So I did do that, However, I don't think I have figured out how to use the property properly or maybe it is broken, I'm not sure. Are there any examples with ``scrollbar-gutter`` ?

**Comment by simonbuchan** [comment]
To those confused, `scrollbar-gutter` provides a nice way to get a speculative `overflow: force-not-overlay`. There is no standardized way to get `overflow: overlay` (due directly to Apple pushback on `scrollbar-gutter`, infuriatingly), but the non-standard implementation is super useful in Electron (though it's a little buggy, sometimes not appearing when it should)

**Comment by karl-police** [comment]
I was told to create a comment here again, to create a follow up.

What acts as a new way to create overlay scrollbars? A way to make the scrollbar-gutter go in overlay mode. Did anyone get that to work?

**Comment by smfr** [comment]
Can you show some examples of where author control over whether scrollbars are overlay scrollbars would be useful?

**Comment by simonbuchan** [comment]
@smfr what a bizarre question. Could you define "useful" a bit more strictly? After all, you could say none of CSS is "useful".

Here's a staff at it, at least: Author control over overlay scrollbars is useful because it let's you create layouts that work the same on all platforms, and don't need to handle having overflow and not differently, and make more space available for interesting content, and they are just better looking, and in fact every platform has moved to using some variant of them in their native UX, so they are more familiar than gutter scrollbars to most users. Is that enough?

**Comment by karl-police** [comment]
> Can you show some examples of where author control over whether scrollbars are overlay scrollbars would be useful?

To allow the gutter of the scrollbar have a transparent background, potentially hiding it when it is unused or something. The workaround might be javascript, but it destroys the integration features from browsers. With integration features, I mean stuff like this:

![image](https://user-images.githubusercontent.com/12023782/183250522-893ccac2-4b64-446d-90be-0c1fd07b2e09.png)

When using CTRL + F as example.

This wouldn't easily be possible if the entire scrollbar has to get removed.

See this JSFiddle in Google Chrome as an example: https://jsfiddle.net/3awLgj5v/

**Comment by smfr** [comment]
The choice of whether scrollbars should be overlay scrollbars or not is generally a user choice, not a web author choice. If the user chose overlay scrollbars at the OS level, overriding this decision at the author level is not very user-friendly (same with the opposite).

**Comment by simonbuchan** [comment]
When is it a user choice to have overlay scrollbars? I can't think of any examples, it's always an artifact of the OS or UI library being used.

Given that the web equivalent to a UI library is generally expected to be building your components completely styled (or rebuilt and replaced!) with CSS it seems entirely in scope to have any and all appearance and behavior be author controlled for any component within the viewport, at least in theory, and scrollbars are a glaring exception. (It's not the only one: select is also famously difficult to customize to fit in with the rest of the design or to add desired features, but at least that is replaceable cleanly; custom reimplementations of scrollbars have many terrible effects)

**Comment by karl-police** [comment]
> When is it a user choice to have overlay scrollbars? I can't think of any examples, it's always an artifact of the OS or UI library being used.
> 
> Given that the web equivalent to a UI library is generally expected to be building your components completely styled (or rebuilt and replaced!) with CSS it seems entirely in scope to have any and all appearance and behavior be author controlled for any component within the viewport, at least in theory, and scrollbars are a glaring exception. (It's not the only one: select is also famously difficult to customize to fit in with the rest of the design or to add desired features, but at least that is replaceable cleanly; custom reimplementations of scrollbars have many terrible effects)

It was way easier to do it with CSS. Why require JS?

**Comment by simonbuchan** [comment]
@karl-police not sure what you mean: this issue is about being able to use CSS. I'm not advocating using JS for a scrollbar, literally the opposite, but there are plenty of people who have done exactly that (with all the problems) because we don't have any portable way to do it with CSS.

**Comment by karl-police** [comment]
> @karl-police not sure what you mean: this issue is about being able to use CSS. I'm not advocating using JS for a scrollbar, literally the opposite, but there are plenty of people who have done exactly that (with all the problems) because we don't have any portable way to do it with CSS.

you mean a way to do it with CSS, with custom rules?

or with overflow: overlay?

**Comment by RealAlphabet** [comment]
> The choice of whether scrollbars should be overlay scrollbars or not is generally a user choice, not a web author choice. If the user chose overlay scrollbars at the OS level, overriding this decision at the author level is not very user-friendly (same with the opposite).

This should be first a choice of the developers before the users.

Let me argue. Let's say you have a web application and you have several groups stacked on top of each other that scroll to the right (horizontally). By defining "overlay" as an alias of "auto", the vertical scroll bar of the page will cause a hole on the right border of the interface.

What do you think will happen? Users will complain to the web developers that the interface is "glitched" and that the horizontally scrollable groups cut off before reaching the end of the window in width.

Maybe I'm wrong, and I sincerely hope I'm wrong, but the scrollbar-gutter feature doesn't seem to fix this problem at all and it will simply cause a deep and sincere sense of hatred among users because their favorite applications/websites are broken. Maybe there is a modern solution to this problem but it is funny to think that those who want the overlay alias have not proposed any alternative.

**"Excuse us, there is nothing we can do about it. This is a feature that has been removed by web browser developers."**

Here's what's going to happen. Do you really think about the web developers before you start removing features you consider "useless" or "unknown to you"? What right do you have to consider these features as unused or unknown? On what do you base such nonsense? Do you have any statistics on the use of the overlay value on the whole web? I don't think so.

The ones who will receive the complaints from the users will be without a doubt neither the developers of these browsers, nor the ones who decided to remove this feature, but us, developers.

I may sound like an angry person here, but at some point someone has to say it. Let me speak for all the web applications you are going to break. What alternative do we have before our web applications get broken by this change?

**Comment by Paper-Folding** [comment]
So since `overflow: overlay` is gone, my web applications' transparent-background scrollbar is gone, too. Using background image for document.body, thus transparent-background scrollbar is needed, what should I do now? Should I write my own scrollbar using div and handle mouse event all by myself?

**Comment by Paper-Folding** [comment]
> @Paper-Folding, use `scrollbar-color` from [[CSS-SCROLLBARS]](//drafts.csswg.org/css-scrollbars#scrollbar-color) with `transparent`.

This property currently has not supported by chrome browser, I don't regard this as a good solution, at least for now.

**Comment by patrickgalbraith** [comment]
@rthrejheytjyrtj545 It's not a proper replacement since the scrollbar will still push the content in rather than being displayed over the content.

**Comment by patrickgalbraith** [comment]
@rthrejheytjyrtj545 I have tried that approach but it doesn't work unfortunately and introduces a lot of edge cases.

**Comment by hrithiksawhney** [comment]
Is there any other way to produce the same effect?

**Comment by dkilgore-eightfold** [comment]
Removing this from potentially being adopted by the wider web was a huge mistake. I mean look at [this mess](http://grsmto.github.io/simplebar/) it's worse for A11y than this one property.

**Comment by dkilgore-eightfold** [comment]
@smfr Fixed `<table>` sticky header and column implementations is a perfect example where web authors should avoid JavaScript mapping, normalizing the horizontal position of the `<thead><tr><th>` and `<tbody>`. Adjusting the width of the last header column to make room for a non-existent scrollbar is not desirable in this scenario.

**Comment by thexeos** [comment]
This is a thoughtless solution to an entirely made-up problem. [87% of page loads](https://chromestatus.com/metrics/css/timeline/popularity/105) use some form of overflow on their page, do we know how many are `overlay` and if we don't then how can this decision be made?

This change is very effectively degrading user experience across hundreds of UI frameworks that contain lightboxes (image galleries) and overlay dialogs. Most use `overflow: hidden` when displaying overlays to hide the irrelevant scrollbars which display above content, followed by unsetting the `overflow` property when overlay is hidden.

**With this alias degradation there are now millions of devices running Chrome browsers wasting their CPU cycles on layout recomputes in response to pointless reflows caused by the lack of overlay scrollbars.**

Similarly, loading screens (aka splash screens) of web apps are affected as there is an immediate layout shift once the splash screen is hidden leading to a terrible first impression.

**As of today, July 11, 2023, there are no CSS-only alternatives to <body> `overflow: overlay` implemented by any browser.**

**Comment by tabatkins** [comment]
This issue has been closed and there is no interest in reopening it in the CSSWG. I am also sad we don't have overlay scrollbars everywhere, but in the absence of agreement among browser vendors to ship this, adding it to the spec won't accomplish anything. As I stated [in the beginning of this issue](https://github.com/w3c/csswg-drafts/issues/6090#issuecomment-801304614), the appropriate place to register complaints is with browser vendors.

I'm going to lock this issue, as further discussion won't accomplish anything.
