### ISSUE TITLE
[css-fonts] `size-adjust` should be moved out of the "Default font metrics overriding" section

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6112]
The new `size-adjust` descriptor is not analogous to the previously-defined `ascent-override` and its friends, and probably shouldn't be grouped in the same section of the spec. Those descriptors *replace* metrics derived from the font with metrics computed from the used font size (as the section title says, they "override" things), while `size-adjust` applies a scale factor to all metrics (and images) derived from the font, but does not "override" them.

The draft text landed in #6108 includes `size-adjust` in the "metrics overriding" section, but then has to call out its different behavior multiple times. I suggest it would be better separated from the metrics overrides and described individually.

**Comment by xiaochengh** [comment]
I'd like to add more notes for the edits needed, if you don't mind sharing the issue. Or I'll file a new one.

1. The initial value should be `100%`. `normal` doesn't do anything special, and acts identical to `100%`.

2. (On [request](https://chromium-review.googlesource.com/c/chromium/src/+/2773716/1..5/third_party/blink/web_tests/external/wpt/css/css-fonts/size-adjust.tentative.html#b1)) Add a Note section to clarify how it affects `text-underline-offset` and `text-decoration-thickness`: `em`- or percentage-based length values are not affected, but `auto` and `from-font` values are affected since they use metrics provided by the font.

**Comment by jfkthame** [comment]
I filed #6110 about the initial value (I agree on `100%` being the simplest choice).

For the interaction with the text-decoration properties, I think filing a separate issue would probably be clearest.

(Slightly related, there's also #6111 about the interaction with the metrics overrides; I think we know what we want to happen, but the current text is confusing.)

**Comment by xiaochengh** [comment]
Thanks for the reference. I've filed #6138 for text decoration.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/df024473bfb1a1e548a3ff42b25d70c92b98e67b
