### ISSUE TITLE
[css-inline] bikeshedding name of `size-adjust` descriptor

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6114]
I'm wondering whether `size-adjust` is the best name for this descriptor that we just resolved to add in #6075.

The association with the `font-size-adjust` property is one consideration; I can't decide if the similarity of the name is good or bad. On the one hand, there's definitely a similarity between the two features: they both adjust the size at which a font is actually used for a given computed `font-size`. But on the other hand, they're quite different in how they operate and what their value means. The descriptor takes a scale factor (percentage) that is simply and directly applied to the font, while the `font-size-adjust` property takes a number that kind-of looks like a scale factor but is actually a proportion of the computed `font-size` that serves as a target for the x-height of the used font. This seems a sufficiently different model that maybe associating the property and the descriptor by similar naming isn't really a good thing.

So before we go ahead and implement/ship this, I'd like us to consider whether a different name such as `glyph-scale-factor`, `scale-factor`, or even simply `scale` or `scaling` would be better. Such names seem to me to very directly state what the descriptor does, and avoid the implied parallel to `font-size-adjust` whose values have quite a different interpretation.

**Comment by fantasai** [comment]
I quite like the name `size-adjust`, since it's a good description both of what it does and why it exists. I'm a bit less happy about `font-size-adjust` to be honest, I think it's quite confusing, not at all obvious what its numerical value means.

I'll also note that, if at some point we want to have a property value that does this kind of size adjustment, expanding into `font-size-adjust` would be possible and appropriate. In fact, prior to this work on descriptors, I'd often thought about adding a percentage list value to `font-size-adjust`, to pair off explicit size adjustments to font-family values...

`glyph-scale-factor` doesn't have quite the same connotation of scaling the whole font (glyphs and metrics, all). And using `size` rather than `scale` is more consistent with `font-size`, whose used value we're effectively adjusting.

**Comment by litherum** [comment]
We could also just use “font-size”. There’s prior art of having duplicate descriptor/property names that mean different things: font-family, font-weight, font-style, font-stretch.

**Comment by jfkthame** [comment]
I don't like the idea of `font-size` -- yes, there's prior art for same-named descriptor/property meaning somewhat different things, but the value of this thing is *not* a font size, either for font-selection purposes or for rendering; it's a scale factor.

I'd be a lot happier with `size-adjust` here if we *didn't* have the `font-size-adjust` property already, which I agree is rather opaque and confusing. But given that it already exists, my preference would be to use a distinct name here because of the difference in what the values mean. It would be natural to assume that `size-adjust: 50%` is comparable to `font-size-adjust: 0.5`, and that's just wrong.

A name that includes `scale` rather than `size` makes it more obvious (IMO) that this is a scale factor rather than an absolute size (usually, setting a `size` to a percentage means the percentage will be resolved against some outside dimension such as a containing block or an inherited dimension). 

If you want to make the connection to `font-size` explicit, how about `font-size-scaling`?

**Comment by chrishtr** [comment]
Two other options:
* `scale-adjust`: includes scale instead of size, to account for @jfkthame's good point that this naming makes it more clear that this is a scale factor.
* `font-scale-adjust`: Adding in "font" make it even more clear that it's not just scale, but also font scale. Downside: very close to font-size-adjust, which may be confusing.

**Comment by jfkthame** [comment]
How about `font-scaling`? I think that is quite straightforward and clear, while avoiding the (possibly misleading) association with the `font-size-adjust` property, which works quite differently.

**Comment by chrishtr** [comment]
`font-scaling` SGTM!

**Comment by litherum** [comment]
`font-scaling` sounds like a boolean descriptor, though; like it would have values `auto | none`.

Maybe `font-scale`?

**Comment by chrishtr** [comment]
`font-scale` is ok, or `font-scaling-factor`?

**Comment by litherum** [comment]
So I guess I'll just close this, then, since there's no change...
