### ISSUE TITLE
[css-grid-2] 12.1. Grid Sizing Algorithm Step 4 should also include columns in some cases

### ISSUE THREAD

**Issue by KurtCattiSchmidt** [w3c/csswg-drafts#6115]
https://drafts.csswg.org/css-grid-2/#algo-overview

"4. Next, if the min-content contribution of any grid item has changed based on the column sizes and alignment calculated in step 3, re-resolve the sizes of the grid rows with the new min-content and max-content contributions (once only)."

It seems like the columns also have to be resized if there are orthogonal grid items, or items with an aspect ratio that changed based on contribution size.

**Comment by tabatkins** [comment]
One of the original design decisions by the team at Microsoft who came up with the grid layout algorithm was to limit the number of cycles through row & column sizing to two passes, so that grid layout with items that have a cross-axis dependency don't cause an indefinite number of cycles. (It's not clear that the layout algorithm is actually guaranteed to converge.) Are you asking to increase the number of passes in the algorithm?

**Comment by tabatkins** [comment]
@KurtCattiSchmidt ping? If you have a strong reason (based on real content getting badly formatted?) to do additional passes, please let us know, otherwise we'll close this issue as Timed Out next time we do triage thru the spec.
