### ISSUE TITLE
[css-nesting] & rules 

### ISSUE THREAD

**Issue by mnussbaumer** [w3c/csswg-drafts#6119]
First thanks, I think it's great nesting is being added and work being done to provide a flexible spec for it.
I have some reservations towards its implementation and meaning and this came about also because I'm working on a pre-processor for CSS (I didn't even know this was being drafted/added to the css spec until someone pointed it out to me).

In my personal opinion of having written non trivial stylesheets using sass/scss I think that it would help the spec to make it stricter on what it can describe. 

My main issue with the current proposal for `&`, and having two syntaxes with `@nest` is that `&` as described can produce two very different css rules depending on if the `&` is followed by `<whitespace><selector>` or just `<selector>`.

In my mind the nesting with `&` should always mean a concatenation of the selector described afterwards to the parent selector chain(s). This means, `&.concatenated` and `& .not-contatenated` have very different meanings, one applies the concatenation and attributes inside the block to the whole selector, e.g. `btn.concatenated`, while the latter creates a simple selector hierarchy, e.g. `btn .not-concatenated` where the attributes inside the nested block apply only to an element with class .not-concatenated inside a btn element. I think this is confusing.

In the most common pre-processors you can usually have nested with or without `&` and a nested selector without `&` means that it's just a simple hierarchy. This also diminishes the visual noise. You no longer have to pay attention extensively to the white-spacing between `&` and you can see immediately if a selector is `gluing` - becoming part of the parent - or if it's a children of the parent.

This would also simplify the parsing:
- parsers, IDEs, tooling (and even browsers) could produce errors/warnings on `&` when followed by spaces giving clear information on how it's not being used correctly
- `&` could only be placed at the beginning of a selector inside a block
- for simple nesting (hierarchical) you wouldn't need to use `&` inside a block. Right now I'm not seeing  any ambiguity in there - if inside a block and the declaration is not `<text><colon><text><semicolon>` and does not start with `&` it's a nested selector ?
- (personal) I also think it becomes less ambiguous and visually more telling

I would go as far as not allowing `&`nesting of non selector tokens. I've seen used sometimes, things like (just to illustrate)
```scss
btn {
    height: 30px;
    &.btn- {
      &xl { height: 40px; }
      &sm { height: 20px; }
    }
}
```

Where the nesting concatenates "plain" text into the parent chain. I think this shouldn't be allowed because you can't grep a file to find the class .btn-xl or .btn-sm. So perhaps it would make sense to force `&` to be followed by a valid selector, meaning, starting with `.`, `#`, `[`, etc, or an html tag when the parent to concatenate is not itself an html tag (since you can only have a selector point to at most one tag).

Not sure if this is useful but since I've been thinking about this for my own work decided to share my thoughts on it.

**Comment by mnussbaumer** [comment]
Forgot to mention also, that once it's part of the spec you can't roll it back, since every stylesheet that depended on the whitespace between `&` and selector would break, while starting with a stricter `&` that means exactly one thing can be extended if it's really deemed important.

**Comment by tabatkins** [comment]
> & as described can produce two very different css rules depending on if the & is followed by `<whitespace><selector>` or just `<selector>`.

Yup, that's how Selectors normally work. ^_^ For example:

```css
.foo {
  ...
  &:hover { /* hover the .foo element */ }
  & :hover { /* hover a descendant of the .foo element */ }
}
```

This is identical to how `.foo:hover` and `.foo :hover` work.

>  Right now I'm not seeing any ambiguity in there

This is mentioned in passing in the intro to <https://drafts.csswg.org/css-nesting/#nesting> - selectors and properties are grammatically ambiguous with each other. For example, `color:red` and `div:hover` are both "two idents, separated by a colon"; you can't tell *for certain* which is which (at best, you can *guess*, based on your knowledge of CSS properties and HTML tagnames). This ambiguity can persist *indefinitely*, until you see a `;` or `{`; if you don't see either (because the parent rule closes with a `}`, for example), it might not be possible at all to tell which was intended.

------

Agreed that *concatenation* is an anti-feature, fwiw. It interacts very badly with other Selector features, so I explicitly rejected it early in Nesting's life.

**Comment by mnussbaumer** [comment]
> Yup, that's how Selectors normally work. ^_^ For example:

I was not talking about selectors, I was talking about a something that is not yet in the language?

> This ambiguity can persist indefinitely, until you see a ; or {; (because the parent rule closes with a }, for example), it might not be possible at all to tell which was intended.

Well, by indefinitely you mean until the next char or line where the parent closes with `}`? 

But even if that was a problem, instead of solving that (forcing the last property of a block to use semi-colon), we introduce 2 new things,  one `&`, and one `@nest` to solve the readability of the first to be introduced? And on the `@nest` you still have to use the ampersand.

Since I can use preprocessors I will do that and not insist on this, it's clear it's something that's going to go anyway and not up to discussion.

```
div {
    &.class_1 { }
    & class_2 {}
    &.class_2 {}
}
``` 

Over this

```
div {
    &.class_1 {}
    .class_2 {}
    &.class_2 {}
}
```

**Comment by tabatkins** [comment]
> I was not talking about selectors, I was talking about a something that is not yet in the language?

I mean that the difference between `X.foo` and `X .foo` is already how Selectors work. Nesting doesn't change anything about this; the nesting selector `&` works exactly the same as any other selector in this regard.

> Well, by indefinitely you mean until the next char or line where the parent closes with }?

No, I meant indefinitely; that is, for as long as it wants.

*If* you eventually see a `;` or a `{`, then you know the preceding tokens were a declaration or a selector, but that can happen *arbitrarily far away* from the start of the token sequence; you can keep it ambiguous as long as you want. Thus it requires infinite lookahead to tell them apart, which is something that browsers wanted to avoid. (Currently you can parse CSS with a single token of lookahead, which makes parsing much easier and cheaper.)

And if you never see either (because the token sequence ended with a `}` closing the parent block, or an EOF), then it might not be resolvable at all, and you just have to arbitrarily decide which it is. (If it was a selector this would be an invalid style rule, because it lacks a `{}` after it, but "invalid style rule" and "valid declaration" still have observably different behaviors, so it's still important which one you guess.)

The current syntax prevents either of these situations from happening. You can tell whether a token sequence is starting a selector or a property according to the *very first* token you look at - if it's an `&`, you should start parsing as a selector, otherwise it's a property. (Or you see an `@nest` token, in which case you parse an at-rule, which is already unambiguous with the other two.)

> one @nest to solve the readability of the first to be introduced? And on the @nest you still have to use the ampersand.

@nest isn't there for readability, it's to allow you to express the remaining cases that the normal syntax doesn't allow - anything that *doesn't* start with an `&` selector, but instead uses the `&` deeper in the selector. For example, `.foo { .bar & {...} }` is invalid (because it's not immediately unambiguous, as described above), but you can write `.foo { @nest .bar & {...} }` and get what you wanted.

> ```
> & class_2 {}
> &.class_2 {}
> ```

And compare both of those with `&+class_2`; it's also the same length, with some arbitrary punctuation between the `&` and the `class_2`, but we don't consider it confusable with either of the above. The descendant combinator is a basic part of CSS used many times in every stylesheet; we don't need to protect people from it.

**Comment by mnussbaumer** [comment]
Thanks for taking the time to reply. I will preface by saying that my concern is related to complexity and the syntax becoming less intuitive than it could be, from the point of an user. As I said before, it's not that I can't understand the chosen tradeoffs, and ultimately I can choose to write my own preprocessor that works just as I want it to and outputs valid css, and so does anyone else. I also imagine it's complex to handle the process of implementing changes into such a widely use thing while keeping all interests in sight. I'm still going to argue though :)

> I mean that the difference between X.foo and X .foo is already how Selectors work. Nesting doesn't change anything about this; the nesting selector & works exactly the same as any other selector in this regard.

But that's how selectors work in css2, `&` is a new token, yes the top-level selectors use spaces to define the chain of selection between them, but not a prefix with a space between them to signal. 

> No, I meant indefinitely; that is, for as long as it wants.

This is the same as it is already, the spec allows `/` multilines (which I guess it shouldn't because anybody writing selectors with multilines deserves their styling to be broken, yes the html spec allows it, but the css shouldn't in my opinion), and any token bound by delimiters can do exactly the same thing, from `"text.........` to `[attri......]`, to `url("base64....."` .
So that problem is already there.

> And if you never see either (because the token sequence ended with a } closing the parent block, or an EOF), then it might not be resolvable at all, and you just have to arbitrarily decide which it is. (If it was a selector this would be an invalid style rule, because it lacks a {} after it, but "invalid style rule" and "valid declaration" still have observably different behaviors, so it's still important which one you guess.)

It's resolvable, if the token sequence ended with a `}`, you add `;` and see if it's a valid rule. If it's not it's a broken query selector because it doesn't open a block? Even if it's a pseudo-selector or class, it has no bearing because it's missing a block, and won't be a valid attribute either way. 

> The current syntax prevents either of these situations from happening. You can tell whether a token sequence is starting a selector or a property according to the very first token you look at - if it's an &, you should start parsing as a selector, otherwise it's a property. (Or you see an @nest token, in which case you parse an at-rule, which is already unambiguous with the other two.)

It prevents that from happening for sure, but it introduces two new declarations targeted at the same functionality. This can result in people using one, or both, across the same codebase or different code bases, instead of having a single way of declaring their intentions. Which is basically more complexity. And because either has different constraints it makes it (or can make it) harder to learn (I'm not saying me, or you, just in general). 

> @nest isn't there for readability, it's to allow you to express the remaining cases that the normal syntax doesn't allow - anything that doesn't start with an & selector, but instead uses the & deeper in the selector. For example, .foo { .bar & {...} } is invalid (because it's not immediately unambiguous, as described above), but you can write .foo { @nest .bar & {...} } and get what you wanted.

This seems to come from exactly not having the ability to do naked nested selectors (as in SCSS)?. Looking at Example # 5 on the draft

```css
.foo {
  color: red;
  @nest & > .bar {
    color: blue;
  }
}

// the scss equivalent is
.foo {
  color: red;
  > .bar {
    color: blue;
  }
}
```
And the other ones seem to follow the same ?

```css
.foo {
  color: red;
  @nest .parent & {
    color: blue;
  }
}

.foo {
  color: red;
  @nest :not(&) {
    color: blue;
  }
}
```
These no longer would have ambiguity correct? 

And these invalid examples
```css
.foo {
  color: red;
  @nest .bar {
    color: blue;
  }
}
/* Invalid because there’s no nesting selector */

.foo {
  color: red;
  @nest & .bar, .baz {
    color: blue;
  }
}
```

Could then be validly written as:
```css
.foo {
  color: red;
  .bar {
    color: blue;
  }
}
/* Invalid because there’s no nesting selector */

.foo {
  color: red;
  bar, .baz {
    color: blue;
  }
}
```

I just think that given how one (at least me, but I imagine more people) think about selectors, in where `.class button` means "a button that is inside an element with class .class" this simple 

```css
.class {
     button {}
}
```

Maps perfectly to it. The nested selector is inside another selector.
I also think that this looks better
```css
div {
   .class_1, &.class_2, .class_3, &#special { }
}

// than this
div {
    & .class_1, &.class_2, & .class_3, &#special {}
}
```
 
> The descendant combinator is a basic part of CSS used many times in every stylesheet; we don't need to protect people from it.

It's another rule one has to know. We do not, but what I find interesting is that some of the arguments you provided are exactly about protecting people from malformed css, so I don't think it's fair ending on that note.

And lastly, this syntax as been used by most major pre-processors, in which most well known css frameworks, that probably thousands of people have used, were written. I'm not saying that that in itself is a reason to not change syntax or introduce new syntax or break away with something, but I do find in this particular case to be clearer. That is of course my own opinion and as the saying goes, everyone has one. I have nonetheless written quite complex stylesheets so I feel like it's not totally worthless to share it. Ultimately this will be part of the spec and I want to have a record of me saying I disagree with it!

Parsers are a dozen, people reading and writing stylesheets are in the millions, death to all non-conformant parsers.

Again thanks for taking the time to reply, have a great week, you can consider this issue closed and answered.

**Comment by djekanovic** [comment]
Including nesting feature will eliminate the last reason of someone needing to use preprocessor. Lot of things were not possible, but they are today. So if we don’t see the solution for it at this moment, we probably will in future, i see that personal preference impacts the whole web which is not ideal.
