### ISSUE TITLE
Pre-defined Counter styles for Indian Languages[css-counter-styles-3]

### ISSUE THREAD

**Issue by vermaprashant1** [w3c/csswg-drafts#6127]
TDIL (Technology Development for Indian languages) programme of Ministry of Electronics and Information Technology, Govt. of India runs Standardization activity for Indian languages. As shown in predefined counter style section(https://drafts.csswg.org/css-counter-styles/#predefined-counters) , the alphabetic counter styles for Indian languages are not being implemented although the user can define it by using @counter-style rule. Through this , the different users can define different counter styles at different places. For seamless access it is required to define pre-defined counter styles for Indian languages. What will be the necessary actions are required to propose pre-defined alphabetic counter styles?

**Comment by tabatkins** [comment]
The list of predefined counter styles was intentionally limited solely to the styles defined by CSS2 (for compatibility) and a small number of additional styles that were, due to some complex aspect of how they worked, impossible or very difficult to implement with a @counter-style rule.

The Internationalization WG maintains another document with a large list of @counter-style rules already defined for many world languages and cultures: <https://www.w3.org/TR/predefined-counter-styles/> (this is linked from the Counter Styles spec in section 8). There are already several Indian-language styles there, but if you find that something is missing, feel free to file a bug at [that document's issue tracker](https://github.com/w3c/predefined-counter-styles/issues).

**Comment by Crissov** [comment]
It may be interesting to note that [support for `@counter-style`](https://caniuse.com/css-at-counter-style) is finally coming to Chrome and hopefully its siblings soon.

**Comment by svgeesus** [comment]
> the alphabetic counter styles for Indian languages are not being implemented although the user can define it by using @counter-style rule.

From [Simple Predefined Counter Styles](https://drafts.csswg.org/css-counter-styles/#predefined-counters)

> 	This stylesheet is normative—UAs must include it in their UA stylesheet (or at least act as if these rules were defined at that level).

So this is already a requirement, for all the ones from CSS2 and CSS 2.1. And users can define others, as they wish, or simply copy them from [Ready-made Counter Styles](https://www.w3.org/TR/predefined-counter-styles/)

In terms of implementation, they are implemented in Firefox and they [currently being implemented in Chrome](https://www.chromestatus.com/feature/5692693659254784). I don't know about WebKit.

**Comment by xfq** [comment]
WebKit doesn't seem to be implementing it. See https://w3c.github.io/i18n-tests/results/counter-styles#basics and https://bugs.webkit.org/show_bug.cgi?id=167645
