### ISSUE TITLE
[css-fonts-5] How do font-size-adjust property and size-adjust descriptor work together?

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#6128]
`font-size-adjust` is [defined](https://drafts.csswg.org/css-fonts-3/#font-size-adjust-prop) as:

> This property allows authors to specify an aspect value for an element that will effectively preserve the x-height of the first choice font, whether it is substituted or not.
> ...
> The value of ‘font-size-adjust’ affects the used value of ‘font-size’ but does not affect the computed value.

While `size-adjust` is recently [resolved](https://github.com/w3c/csswg-drafts/issues/6075#issuecomment-801224623) and [specified](https://drafts.csswg.org/css-fonts-5/#descdef-font-face-size-adjust) as

>  ... when the descriptor value is a percentage, all metrics values of this font, including glyph advance sizes, are resolved as the given percentage multiplied by the used font size.

So they affect the exact same value. What should we do when both of them are set?

In particular, while `size-adjust` scales the x-height, while `font-size-adjust` depends on the unadjusted `x-height` and tries to preserve its value by scaling the used font size. So there seems to be a dependency issue here to clarify, or which one to apply first.

Also @jfkthame since Gecko has already shipped `font-size-adjust` and prototyped `size-adjust`. It would be great to know Gecko's behavior and considerations.

**Comment by jfkthame** [comment]
Given that `size-adjust` is a descriptor on the font face, while `font-size-adjust` is a property on an element, I think the logical behavior is that `size-adjust` applies first, scaling all metrics retrieved from the font (including its x-height). This happens independently in each face that's being used.

These adjusted metrics then provide the basis for the computation and adjustment that the `font-size-adjust` property will do.

I think this is the behavior that will naturally arise from the patches currently in progress for Gecko, though I admit I have not actually tested the interaction yet.

(This feels somewhat parallel to the interaction of the `font-feature-settings` and `font-variation-settings` descriptors and corresponding properties, where the descriptor can set up defaults that go along with the specific font face, but then the property, if present, can adjust them further.)

**Comment by xiaochengh** [comment]
Makes sense to me. Thank you!

**Comment by chrishtr** [comment]
@jfkthame's reasoning make sense to me. Agenda+ to agree on it next week and add to the spec.

**Comment by drott** [comment]
Here's a quick Codepen I put together https://codepen.io/drott_chrome/pen/bGggEeB to test the interaction in Firefox Nightly. Thanks @jfkthame for prototyping this.

I agree with Jonathan's [comment](https://github.com/w3c/csswg-drafts/issues/6128#issuecomment-805106494) and Xiaocheng. This sequence of computation effective font size seems reasonable to me as well, but let's look at how this behaves.

Looking at the codepen that combines the two in FF nightly, I wonder what exactly is happening. It seems that once `font-size-adjust` is in the style, the `size-adjust` no longer has an effect (rendered font size does not change when changing `font-size-adjust`. 

The way the [formula is set up](https://drafts.csswg.org/css-fonts/#font-size-adjust-prop) for `font-size adjust` it only looks at aspects (x-height to font-size / ascent + descent) of the fonts, so a scaling done through the `size-adjust` descriptor does not effectively change that ratio. In the end, it looks like `font-size-adjust` overrules `size-adjust` because the aspect stays unchanged and the `font-size` denoted with `s` in the `c  =  ( a / a' ) s` formula for `font-size-adjust` is the `font-size` from CSS, which also seems correct. 

This looks to me like in fact it is applied after `size-adjust`, but the effect of `size-adjust` becomes void because `font-size-adjust` operates on style `font-size` and font aspects only. This seems fine to me.

**Comment by jfkthame** [comment]
Yes, I agree this is the result. (Sorry I didn't spell this out better before, but it became clear in the course of working on this that it has to be this way.)

The aim of `font-size-adjust` is essentially to harmonize a specific metric (x-height) that otherwise tends to vary between different fonts (for a given `font-size`). `size-adjust` provides a way for authors to customize that metric within each face, by rescaling the glyphs relative to the em size, but whatever the author does at that level, `font-size-adjust` (if applied) will still end up harmonizing the end result.
