### ISSUE TITLE
[css-align-3] Consider making vertical centering

### ISSUE THREAD

**Issue by brendan8c** [w3c/csswg-drafts#6143]
I want to suggest vertical centering of blocks.
It's much easier to do. For instance: 
"**margin: auto 0**",  "**margin: auto auto**"
Without using flex elements.

**Comment by tabatkins** [comment]
While implementations have not yet caught up with the spec, it is defined that `align-content: center` should work on block containers, vertically centering their contents: <https://drafts.csswg.org/css-align/#distribution-block>

(We're hoping that this is still possible, and we don't have a bunch of existing web content accidentally relying on the property doing nothing for blocks.)

However, `align-self: center` is not possible in block containers, for the same reason Flexbox doesn't allow `justify-self` to work - there are multiple elements in the axis, and it's not clear how to reconcile each one asking for a particular alignment. `*-content` works because it aligns all the children as a group.

**Comment by brendan8c** [comment]
Yes you tell right.
We know about `margin: 0 auto;` for horizontal centering.
But it would be logical if `margin: auto 0` or `margin: auto;` work for vertical centering.
I'm talking about `margin` in order to expand its capabilities.

**Comment by tabatkins** [comment]
Ah, unfortunately that can't happen.  Vertical auto margins have never affected positioning, for the reason I said earlier - there are multiple elements in the vertical axis, so it's not clear how multiple children with `auto` vertical margins should work.
