### ISSUE TITLE
[css-pseudo-4] Ensuring selection foreground/background contrast

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#6150]
The [`::selection` pseudo-element](https://drafts.csswg.org/css-pseudo-4/#selectordef-selection) allows the developer to change the foreground and background of a selection.

What happens if there is not good enough contrast between the selected colors? Webkit and Chromium (*) currently have code that inverts the background, if the background and foreground color are exactly
the same. Gecko does not have this logic. [Here](https://codepen.io/webcompat/pen/GRroQJa) is an example page that differs.

Should we view this as a website bug, or an opportunity for the UA to intervene and ensure contrast? One argument for the latter could be that selection is primarily a UA feature, and therefore it's appropriate to intervene to override site bugs. But if we do so, any difference in heuristics between browsers could result in (probably accidentally) broken sites in some browsers.

Finally, the same question could be asked about the various other pseudo elements that are similar to selection.
 
(*) [Webkit code link](https://github.com/WebKit/WebKit/blob/8309593bc3f4715a365652c1a7ba9688efb4bb90/Source/WebCore/rendering/MarkedTextStyle.cpp#L87-L91)
 [Chromium code link](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/paint/ng/ng_highlight_painter.cc;l=111)
[Gecko bug tracking an interop issue caused by this](https://bugzilla.mozilla.org/show_bug.cgi?id=1589539)

**Comment by karlcow** [comment]
Good comment from @jfkthame on https://bugzilla.mozilla.org/show_bug.cgi?id=1589539#c20

> Tend to agree with Emilio, the first thing to do here (given that AFAIK we haven't been getting reports of this all over the place, it's this particular site that has CSS that just doesn't make sense unless they really WANTED the selection to be invisible) is to push for people to follow the spec. It's clear enough on this point, and it shouldn't be hard for authors to use it.
>
> Defining special behavior for fillColor == backgroundColor for text selection gets messy; what about if the colors aren't exactly equal but differ by so little that it's not visible to the eye? We'd probably want to do this in terms of computing the contrast between them, not simple equality, and enforcing a minimum level of contrast. But then we'll end up with some author complaining that a subtle effect they're trying to achieve is impossible because the browser refuses to apply their colors as specified.

**Comment by fantasai** [comment]
FWIW, I agree with @jfkthame that this should be considered a website bug.

A key point in that discussion though is that Blink/WebKit are not following the spec, and are applying an alpha value different from the one specified by the author; currently that's only allowed when the selection color over replaced elements’ content. So I think the key question here is whether Blink/WebKit intend to update to match the author’s specified color, or if ::selection should have a magic background-opacity value.

(...which I suppose we could make non-magic if we actually added background-opacity as a property, but maybe that's a separate issue)

**Comment by mrego** [comment]
We've been hit by this issue while working on improving `::selection` in Chromium.

Chromium inverts the background color when the `::selection` color and background color are the same, e.g. `::selection { color: lime; background: lime; }` (check it [live](https://people.igalia.com/mrego/css/css-pseudo/selection-invert-background-chromium.html)).

However WebKit does something different, because WebKit applies a 80% transparency to the web author specified background color, so it doesn't invert the colors in the previous example. But it inverts the colors in this example: `::selection { color: rgba(0, 255, 0, .8); background: lime; }` (check it [live](https://people.igalia.com/mrego/css/css-pseudo/selection-invert-background-webkit.html)).

This behavior comes from very old times (https://trac.webkit.org/changeset/1447/webkit), and there was even a comment in WebKit in the past stating that it was very unlikely that the background color gets inverted (https://trac.webkit.org/changeset/7766/webkit):
```cc
    // If the text color ends up being the same as the selection background, invert the selection
    // background.  This should basically never happen, since the selection has transparency.
```

Firefox never does this, for the colors specified by the web authors, it always respect them.
But when there are no user specified colors for `::selection`, if the background of the element matches the default background for `::selection`, then it inverts it. For example in Linux when you have a `background: #3584e4;` in an element, not in the `::selection` pseudo, it'll invert the selection background color to make it visible (check it [live](https://people.igalia.com/mrego/css/css-pseudo/selection-invert-default-colors-firefox.html)).

So I guess browsers could have some freedom about what to do when the author doesn't specify any color (and try to match the platform conventions and all that). But I'm not totally convinced what they should do if the author specifies a color, shouldn't respect it? is it ok that WebKit adds a transparency to any color the author specifies?

We added a use counter in Chromium (included in version 93), very few pages are hitting it (~0.0003% so far): https://chromestatus.com/metrics/feature/timeline/popularity/3934

Anyway this is indeed an interop mess, and also this makes selection work differently than the new css-pseudos (particularly `::highlight()`), dunno if that's something we want to keep or not. Or maybe we should do the same for other highlight pseudos, dunno.

It can also prevent the author to create some kind of potential pages/games that could use the same color to hide some text until the user click somewhere else and selection is gone and the text is visible (dunno really if this is a real use case, probably not with `::selection` dunno when `::highlight()` is available though).

CC @delan

**Comment by schenney-chromium** [comment]
I would like to get this issue resolved. My proposal is that UAs should respect the colors given in ::selection pseudos (including inherited) as statements of an author's intent, even if that intent hides text when selected. UAs can do anything they want with selection painting in the absence of ::selection.

It seems desirable to add "only when both color and background color are given in ::selection" but it's not clear to me that it is implementable across browsers and is probably unnecessarily complex. I'm open to discussion.

Looking at the various proposals/concerns raised in the previous discussion:
- This resolution ONLY applies when a ::selection pseudo is applied, in which case the have color and background color on the pseudo style inherited from some place that starts with good contrast, generally HighlightColor and HighlightBackground.
- Allowing UA tweaks is very hard to spec in a way that handles all cases, including transparency, contrast thresholds, compatible color adjustment algorithms etc.
- Allowing UA tweaks in the case of ::selection is essentially ignoring the authors intent, which was to style the selection. Unless we think that's a bad thing to allow (then why have ::selection?) I don't think we should try to second guess their design.

And as one data point, there is a WPT that explicitly tests for this behavior: css/css-pseudo/active-selection-018.html

**Comment by schenney-chromium** [comment]
Adding Stack Overflow question:
* [chromium and gecko disagree on selection colors](https://stackoverflow.com/questions/7224445/css3-selection-behaves-differently-in-ff-chrome) Note you can hack around chromium behavior using a (slightly) transparent color.

**Comment by LeaVerou** [comment]
> Chromium inverts the background color when the `::selection` color and background color are the same, e.g. `::selection { color: lime; background: lime; }`

Note that inverting colors does not guarantee contrast. The closer you get to a mid gray, the lower the contrast, with gray having 0 contrast since it is the inverse of itself. 

----

It seems like something that would really mitigate this problem is `contrast-color()`, which could be the default text color in the UA stylesheet, and could also be applied in cases like these.

**Comment by yisibl** [comment]
To solve this problem once and for all, I hope browsers will implement `contrast-color()` as soon as possible.
