### ISSUE TITLE
[css-color-5] What should the behavior of the CSS Color 5 color functions be when passed `currentcolor` as <color> 

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6168]
What should the behavior (both rendered result and computed value) be for the CSS Color 5 color functions (e.g. `color-mix()`, `color-contrast()`, `color-adjust()` and the relative color syntax forms) when one of the passed in <color> values is `currentcolor` (https://drafts.csswg.org/css-color-4/#currentcolor-color)?

For rendering, I assume we just need to delay computation of the color functions until use time when `currentcolor` is used and use the resolved value, but it would be good to clarify that in the spec if it is the case.

For computed value I am not quite sure since none of the color functions currently have anything about their computed value's specified. Should:

```css
background-color: color-mix(in lch, currentcolor 40%, palegoldenrod)
```

have a computed value of `color-mix(in lch, currentcolor 40%, palegoldenrod)`?

In my current implementation, I am eagerly computing the color-mix(), so in all cases that don't involve currentcolor it computes to the resolved color, but this is just an arbitrary choice I made, and I do not think should motivate the direction of the spec.

**Comment by emilio** [comment]
FWIW, in Gecko we resolve all colors at computed value time to a mix of currentcolor and a foreground color (like [this](https://searchfox.org/mozilla-central/rev/9043e515e9608cc55b252a40cb2dfb6f767bcffd/servo/components/style/values/generics/color.rs#7-40)). That allows us to resolve the functions at computed-value time. So my implementation of `color-mix()` also computes to the resolved color.

I think that's generally preferable as I'd rather not do a lot of color mixing during rendering for every element if we can do it once and let it inherit through.

**Comment by weinig** [comment]
@Emilio, I can't quite understand what you are proposing here. What would the computed and used values of something like the following be:

```css
background-color: color-mix(in lch, currentcolor 40%, palegoldenrod)
```

**Comment by weinig** [comment]
(sidenote, @emilio, is the behavior of using part of using part of currentcolor and part of color for a final color value specified anywhere? I don't believe that is something we do in WebKit, and would interested to find out what that is all about).

**Comment by robertwbradford** [comment]
I was wondering a similar thing. For example, we are maintaining a component library. In one of the components, we would like one of its elements to have a semi-transparent background color based on the `currentcolor`. Something like the following:

```html
<div class="wrapper">
  <div class="my-component">
    <p>Some text</p>
    <div class="my-component__semi-transparent-thing"></div>
  </div>
</div>
```

```css
.wrapper {
  background: darkslateblue;
  color: white;
}

.my-component__semi-transparent-thing {
  background-color: rgb(from currentcolor r g b / 50%);
}
```

We would like to use `currentcolor` because from the component's perspective, it doesn't necessarily know its context. Of course we could use a CSS custom property, but with `currentcolor` working so well elsewhere, it would be nice to use it here too.

**Comment by emilio** [comment]
Sorry I missed this ping before.

@weinig @tabatkins resolving these at computed value time would break `currentcolor` when inheriting.

My point is that something like `color-mix(in lch, currentcolor 40%, palegoldenrod)` should somehow preserve the `currentcolor` component in the computed value, otherwise descendants that change `color` will get the wrong color.

Here's a test-case that shows what I meant. The expected output is greenish, but if you resolve `currentColor` at computed-value time, then you will get red.

I think Firefox's behavior is correct here (WebKit doesn't support `color-mix(..., currentColor, ...)` afaict)?

```html
<!doctype html>
<style>
  div {
    width: 100px;
    height: 100px;
  }
  .outer {
    background-color: color-mix(in srgb, currentcolor 90%, red 10%);
    color: red;
  }
  .inner {
    background-color: inherit;
    color: green;
  }
</style>
<div class="outer">
  <div class="inner"></div>
</div>
```

**Comment by weinig** [comment]
> I think Firefox's behavior is correct here (WebKit doesn't support color-mix(..., currentColor, ...) afaict)?

Correct, in WebKit we currently just don't accept currentColor in the CSS 5 color functions at all. I was waiting for the resolution of this issue before going forward with it.

I agree it should follow normal currentcolor inheritance rules for rendering (I say as much in the first comment). 

What I am not sure is what the computed value should be. If it should preserve the complete "color-mix(..., currentColor, ...)" that would be fine with me, it just needs to be spec'd.

**Comment by emilio** [comment]
I think the computed value of this is not currently visible, because `getComputedStyle` actually resolves `currentColor`, right? I guess it could be observable in typed-om?

**Comment by tabatkins** [comment]
> @weinig @tabatkins resolving these at computed value time would break currentcolor when inheriting.

Right, which is why we didn't say to do that. ^_^

As far as I can tell, we're agreeing - resolve the function *as far as possible* at computed-value time (so you're left with just the parts that depend on `currentcolor`, plus any additional fully-resolved bits that'll combine with it), then finish resolving, if necessary, at used-value time. Just like math functions, [like I said](https://github.com/w3c/csswg-drafts/issues/6168#issuecomment-811307313) ^_^

-----

Yeah, I *think* gCS() returns used values for all properties with colors (but I'm not 100% certain on that), but Typed OM should be returning the actual computed value.

I think I'm fine with just returning the fully unresolved representation when a currentcolor is present? Trying to figure out exactly how much simplification can be done, like we do with math functions, sounds unfun, even if the UA *has* done that work under the covers to avoid duplicate work later.

**Comment by svgeesus** [comment]
> Typed OM should be returning the actual computed value

Yes

> I'm fine with just returning the fully unresolved representation when a currentcolor is present?

That seems way simpler to specify. It isn't just `currentcolor` right, also amount of the un-deprecated system colors too?

**Comment by tabatkins** [comment]
Yup, they also persist thru to used-value time for the same reason as `currentcolor`.

**Comment by svgeesus** [comment]
> That seems way simpler to specify. It isn't just currentcolor right, also amount of the un-deprecated system colors too?

That seems way simpler to specify. It is just currentcolor due to the resolution of

- https://github.com/w3c/csswg-drafts/issues/6773

**Comment by svgeesus** [comment]
@weinig wrote:

> What I am not sure is what the computed value should be. If it should preserve the complete "color-mix(..., currentColor, ...)" that would be fine with me, it just needs to be spec'd.

I just clarified that in the spec, following the suggestions from yourself, @emilio and @tabatkins : 

```html
The computed value is the specified ''color-contrast()'' function
with each <<color>> parameter resolved according to [[css-color-4#resolving-color-values]],
and the keywords ''AA'', ''AA-large'', ''AAA'', ''AAA-large'' replaced with their corresponding numeric value.

If all <<color>> parameters resolve
to the corresponding colors in their respective color spaces,
the used value is the winning color
resolved according to [[css-color-4#resolving-color-values]].
Otherwise (if ''currentColor'' was used in the function),
the used value is the same as the computed value
thus preserving inheritance into child elements.
```

I also changed the example, to now do what the text says.

I also added a new section on resolving `color-mix()`, including what to do with currentColor: 

```html
The computed value is the specified ''color-mix()'' function
with each <<color>> parameter resolved according to [[css-color-4#resolving-color-values]].

If all <<color>> parameters resolve
to the corresponding colors in their respective color spaces,
the used value is the mixed color,
in the specified mixing color space,
resolved according to [[css-color-4#resolving-color-values]].
Otherwise (if ''currentColor'' was used in the function),
the used value is the same as the computed value
thus preserving inheritance into child elements.
```

**Comment by emilio** [comment]
But anyways, great we are in agreement!

**Comment by svgeesus** [comment]
@emilio so, the computed value isn't the function but is the mixed result (unless currentColor is involved)?

> I think in order to deal with nested color-mix() you need to also move color-mix() to the "resolving color values" section, or somehow hook into that.

That is where the text I added above is located: [7. Resolving [<color>](https://drafts.csswg.org/css-color-4/#typedef-color) Values](https://drafts.csswg.org/css-color-5/#resolving-color-values)

> Also, it's a bit unfortunate that the "resolving color values" section is called like that, because CSS has the concept of "resolved value", which is not necessarily what that is describing, but that's another matter :-)

I named it that because of the similar section in CSS Color 4, which has been there a while: [4.7. Resolving [<color>](https://drafts.csswg.org/css-color-4/#typedef-color) Values](https://drafts.csswg.org/css-color-4/#resolving-color-values).

What should these sections be called?

**Comment by svgeesus** [comment]
To have a concrete example to discuss (initial value of `text-emphasis-color` is currentColor)

```css
div { color: black; }
p { color: color-mix(in oklab, currentColor 60%, white 40%); }
em { text-emphasis: dot; }
strong { color: red; }
```
```html
<div><p><em>Some <strong>really</strong> emphasized text.</em></div>
```

so on the `p` and `em`, the used value of color will be the result of  `color-mix(in oklab, black 60%, white 40%);` and on the `strong` it will be the result of `color-mix(in oklab, red 60%, white 40%);` right?

**Comment by svgeesus** [comment]
![image](https://user-images.githubusercontent.com/2506926/171467742-db1ffedb-e9b1-4d72-a3e5-4abc85be7e31.png)

**Comment by mysteryDate** [comment]
From this conversation, am I correct in assuming that:

```

**Comment by svgeesus** [comment]
> I don't recall whether we decided that color-mix serialized to rgb or to `color()` when computed, but I _think_ it might be the later.

Yes, this is described [here](https://drafts.csswg.org/css-color-5/#serial-color-mix) so the computed value is `color(srgb r g b) `
