### ISSUE TITLE
[css-fonts] Computed value of font stretch

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6171]
https://drafts.csswg.org/css-fonts/#font-stretch-prop has:

> For compatibility with [CSS-FONTS-3], getComputedStyle() serializes values that correspond to one of the font-stretch keywords as that keyword (instead of as a <percentage>).

However Chrome and Firefox don't do this, so it's clearly not needed for compat. Should we remove that clause from the spec?

cc @svgeesus @litherum

**Comment by emilio** [comment]
cc @graouts (we noticed this because of https://github.com/web-platform-tests/wpt/pull/28315 caused some tests to fail in Firefox).

Probably while this is sorted out we could update the test to accept both serializations.

**Comment by jfkthame** [comment]
Note that there are a bunch of other WPT tests where this is also relevant, e.g.

    https://wpt.fyi/results/css/css-fonts/inheritance.html
    https://wpt.fyi/results/css/css-fonts/parsing/font-stretch-computed.html
    https://wpt.fyi/results/css/css-fonts/variations/font-stretch.html

Depending what we resolve (always serialize as percentage? allow either percentage or keyword?) these may need updating; currently wpt.fyi shows a bunch of them failing in Safari because it uses the keyword serialization.
