### ISSUE TITLE
[mediaqueries-4] add Security & Privacy questionairre answers

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#619]
Please consider adding answers to the Security & Privacy questionairre to the existing Privacy and Security Considerations section: https://drafts.csswg.org/mediaqueries-4/#priv-sec

https://www.w3.org/TR/security-privacy-questionnaire/

If it helps, I can try answering it and submitting a pull request accordingly.

**Comment by SebastianZ** [comment]
This is part of issue #207.

Sebastian

**Comment by frivoal** [comment]
@tantek I agree, we should do that. We've already given some thoughts to the topic, resulting in the Privacy and Security Considerations section you linked to, but the questionaire helps making sure we consider relevant questions. I think we should include this in addition rather than instead of the high level summary that we already have, and if the questionnaire raises new concerns, the summary should probably be adjusted accordingly.

If you want to take a first stab at answering it and submitting via a pull request, that would be very appreciated. Not only for shouldering part of the work, but also because a review by someone else than the editors is always good. Thanks a lot for the offer.
