### ISSUE TITLE
[css-fonts] Clarify font-optical-sizing behaviour under size-adjust

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#6190]
In 
https://github.com/web-platform-tests/wpt/pull/28399
I made a ref-test ensuring that `font-optical-sizing: auto` behaves according to the adjusted / resulting font-size under `size-adjust`, pending review. 

Since the wording for `size-adjust` says:

> However, the computed font-size (and thus any values that derive from it, such as em units, percentages in text-underline-offset, etc.) remains unaffected.

And `font-optical-sizing: auto` says: 

> The user agent may modify the shape of glyphs based on the font-size and the pixel density of the screen. For OpenType and TrueType fonts using font variations, this is often done by using the "opsz" font variation.

we may want to  clarify that the applied optical sizing value should be based on the resulting/adjusted/displayed font-size, not on the computed font size, in order to avoid confusion?

I believe the behaviour as tested in the new test makes sense as the glyph size is changed by size-adjust, and the scaled glyphs should then be rendered with the scaled/new optical size value. Or in other words, the glyph is displayed larger/smaller, and so should its optical sizing value be adjusted accordingly.

**Comment by jfkthame** [comment]
I agree this makes sense, although I note that the current Gecko implementation fails this test, because it sets 'opsz' based on the computed font size -- so that'll need to be fixed.

(In practice, I think most use cases for `size-adjust` will involve fairly moderate scaling amounts, so the difference will be barely noticeable; but still, we should specify and do the right thing, not just fudge it!)

This also prompted me to wonder how optical sizing interacts with `font-size-adjust`; I believe that is similarly broken in Gecko at present. Maybe you could include a similar test for that?

**Comment by drott** [comment]
Thanks for your feedback, Jonathan. 

> This also prompted me to wonder how optical sizing interacts with font-size-adjust; I believe that is similarly broken in Gecko at present. Maybe you could include a similar test for that?

We're currently not shipping `font-size-adjust:` and if Gecko would fail it, I wouldn't have a way of verifying the test atm, which would make it a bit brittle to submit to WPT.
