### ISSUE TITLE
[css-color-5] A mistake in the "color-mix" examples

### ISSUE THREAD

**Issue by omgovich** [w3c/csswg-drafts#6249]
Hey! 👋 I was working on adding color mixing functionality to my new color conversion library [Colord](https://github.com/omgovich/colord) and it seems to me that I found a mistake [in the examples](https://www.w3.org/TR/css-color-5/#colormix). Probably this is not the only mistake of this kind there.

<img width="878" alt="Xnip2021-04-28_18-10-29" src="https://user-images.githubusercontent.com/206567/116429306-6f1cb580-a84e-11eb-8e5c-2f4d019cbb03.png">
<img width="640" alt="Xnip2021-04-28_18-14-35" src="https://user-images.githubusercontent.com/206567/116429317-7217a600-a84e-11eb-849f-1d7cb48de32d.png">

https://codepen.io/omgovich/pen/bGgJJPq

Tested it with my library (which is based on the color conversion algorithms from the specs) and by the latest Safari Technology Preview. I'm pretty sure that the resulting RGB value is incorrect.

**Comment by facelessuser** [comment]
Yeah, that example looks like it was wrong. The Lch value was out of gamut, but even clipping the color or gamut mapping, the sRGB value still looked wrong.

I actually implemented a library that mixes colors as well, and you do stumble over such issues from time to time, especially in these early versions of the docs, but I like to check the latest drafts as well to see if the issue is already fixed.

The latest draft doesn't have that example at all: https://drafts.csswg.org/css-color-5/#color-mix. If I had to guess, I'm pretty sure it was replaced specifically with an example that didn't require gamut mapping or clipping so that the results were straightforward and easy to understand.

<img width="619" alt="Screen Shot 2021-04-28 at 10 59 19 AM" src="https://user-images.githubusercontent.com/1055125/116443403-d61b7980-a810-11eb-8633-969a2764cb84.png">

These results seem correct in Safari Technology Preview:

<img width="447" alt="Screen Shot 2021-04-28 at 11 03 38 AM" src="https://user-images.githubusercontent.com/1055125/116443887-6c4f9f80-a811-11eb-8fa2-ab4bc21b96aa.png">
:

**Comment by omgovich** [comment]
Thanks for the answer!
Since the latest drafts doesn't have this error, let's close the issue then.

**Comment by svgeesus** [comment]
> I was working on adding color mixing functionality to my new color conversion library Colord 

Excellent, good to hear. Also happy that you have been directed to implement against [the latest draft](https://drafts.csswg.org/css-color-5/) rather than the periodic snapshots.

> The latest draft doesn't have that example at all: https://drafts.csswg.org/css-color-5/#color-mix. If I had to guess, I'm pretty sure it was replaced specifically with an example that didn't require gamut mapping or clipping so that the results were straightforward and easy to understand.

Your guess is exactly correct.

**Comment by aborayan1020** [comment]
Hey! 👋 I was working on adding color mixing functionality to my new color conversion library Colord and it seems to me that I found a mistake in the examples. Probably this is not the only mistake of this kind there.

Xnip2021-04-28_18-10-29

Xnip2021-04-28_18-14-35

https://codepen.io/omgovich/pen/bGgJJPq

Tested it with my library (which is based on the color conversion algorithms from the specs) and by the latest Safari Technology Preview. I'm pretty sure that the resulting RGB value is incorrect.

**Comment by svgeesus** [comment]
> I was working on adding color mixing functionality to my new color conversion library Colord and it seems to me that I found a mistake in the examples

Could you say which example, and what the mistake is?

> Xnip2021-04-28_18-10-29
> Xnip2021-04-28_18-14-35

Were you trying to attach image files? It didn't work.

**Comment by facelessuser** [comment]
The recent post seems to be a copy and paste of the opening post.

**Comment by svgeesus** [comment]
Aha yes, just spam. Thanks!
