### ISSUE TITLE
[css-content][css-pseudo]::before and ::after a void element

### ISSUE THREAD

**Issue by AndySky21** [w3c/csswg-drafts#625]
Is it possible to add `before` and `after` pseudo elements to void elements with a string / attribute content? If no, why?

**Comment by SelenIT** [comment]
Wouldn't it be useful also to define the behavior of `::before` and `::after` for void and (especially) replaced elements more specifically, with regard to the current behavior of the browsers? E.g., all browsers currently support these pseudo-elements for `hr` (and `hr::before { content: "\2727\2003\2003\2727\2003\2003\2727"; }` is widely used in the new design of W3C specs themselves), although this element [is defined as void](https://www.w3.org/TR/html52/syntax.html#void-elements) in HTML. Also, almost all browsers don't apply them to regular `img` elements, but do apply for broken `img`s (https://bitsofco.de/styling-broken-images/). Since the difference between regular and broken differ in their browser Shadow DOM structure ([at least in Blink browsers](http://css-live.ru/Primer/pseudos/chrome-img-shadow-dom.png)), maybe  the behavior of pseudo elements also could be described in Shadow DOM terms?

**Comment by xgqfrms-GitHub** [comment]
https://lists.w3.org/Archives/Public/public-css-archive/2016Oct/0358.html
https://lists.w3.org/Archives/Public/public-css-archive/2016Oct/0358.html
```
hr::before { content: "\2727\2003\2003\2727\2003\2003\2727"; }

```
what's this mean ```\2727\2003\2003\2727\2003\2003\2727``` ???
are the Unicode charset ???

**Comment by Crissov** [comment]
[Yes](https://drafts.csswg.org/css-syntax-3/#consume-an-escaped-code-point)

    hr::before {content: "✧  ✧  ✧" /* U+2727 White Four Pointed Star, U+2003 Em Space */;}

**Comment by xgqfrms-GitHub** [comment]
thanks for reply!

**Comment by fantasai** [comment]
Closing per @SelenIT's reply in https://github.com/w3c/csswg-drafts/issues/625#issuecomment-255303762

FWIW: Replaced elements replace all the content of the element, including ::before and ::after pseudo-elements, that's why it doesn't work on them. When images are rendered as their alt text, they're no longer replaced.

**Comment by equinusocio** [comment]
This issue should be updated since almost all browsers allows (for some reason) pseudo-elements on `input[checkbox]` and `input[radio]`

**Comment by SelenIT** [comment]
> Replaced elements replace all the content of the element, including ::before and ::after pseudo-elements, that's why it doesn't work on them.

Shouldn't this great explanation be somewhere in the spec itself, probably near the definition of ::before and ::after in [css-pseudo-4]? The current situation, where CSS2.x just "doesn't fully define" the behavior of them with replaced elements, and the only place clearly disallowing them seems to be [the note](https://drafts.csswg.org/css-content-3/#typedef-content-content-replacement) in [css-content-3] in the section about a rather specific case of the replaced elements, is often confusing for authors.

Also, there are still some inconsistencies between replaced element definitions in CSS and in HTML. For example, the HTML spec lists all form controls except `<input type="image">` among _non-replaced_ elements, but [css-images-3] contains a phrase "some types of replaced elements, such as form controls". I'm afraid that these inconsistencies still often lead to confusion about the status of the form controls (and whether they should support ::before/::after or not).

**Comment by fantasai** [comment]
The normative requirement is in the statement that
> When their computed content value is not none, these pseudo-elements generate boxes as if they were immediate children of their originating element, with content as specified by content.

But I added an extra statement about this anyway, since it seems to be a point of confusion.
