### ISSUE TITLE
[css-pseudo] Proposal: Add `border-radius` to supported `::cue` properties

### ISSUE THREAD

**Issue by argyleink** [w3c/csswg-drafts#6292]
https://w3c.github.io/webvtt/#the-cue-pseudo-element

It's a subtle and nice touch to have the corners of the cue just slightly rounded. Softens them up and can help them match brand with rounded corners. I've noticed other platforms support this style. `border-radius` is not currently on the approved list of styles for the `::cue` element and I'd love to see it added. 

Thoughts?

**Comment by nigelmegitt** [comment]
See #2811 and w3c/ttml2#189 - we don't have the spec capability to express how to round corners on adjacent different-length lines without it looking really bad.

**Comment by nigelmegitt** [comment]
I see you closed this @argyleink - just want to say, I think it _would_ be a good idea, but it would also be a good idea to fix the background painting behaviour between and at the junction of line areas. I was not trying to shut this down, just point out that it's not as simple as it at first looks, and without other changes, the visual effect might not be what you'd hope for.

**Comment by argyleink** [comment]
no worries! i shut it down because the complexities were so immediately understood and it appeared to already be within view of the spec to offer something like it. so i'm happy knowing it's in good hands and will iron out eventually, thus making this ticket noise 🙂

**Comment by nigelmegitt** [comment]
> it's in good hands and will iron out eventually

That'd be good; realistically, I don't think it will iron out unless someone pushes for it who can make it happen.

There are a few things that, in the subtitle and caption domain (and I would guess, other domains too), would depend on defining CSS behaviour for line areas after layout, for example horizontal alignment, adding padding to the ends of the line areas, adjusting the backgrounds so that they don't have gaps between them, and fixing up border rounding. It's not making progress in CSS at the moment.

I realise I'm commenting on a closed ticket, and this may appear to be noise, but it seems like reasonably well targeted noise to me, hence why I'm posting. Happy to have off-GitHub-issue discussions about it too, of course.
