### ISSUE TITLE
[css-sizing-4] Only apply contain-intrinsic-size: auto with content-visibility: auto

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#6308]
https://drafts.csswg.org/css-sizing-4/#intrinsic-size-override

If `auto` applies to everything, you can into the situation where an element is visible on screen but rendered with outdated dimensions. For example:

```html
<div style="contain-intrinsic-size: auto 100px; float: left; width: 200px;"></div>
```

Now, if JS adds `contain: size; width: auto;`, the element will be rendered at 200px width, even though this size is neither in the current CSS style not is it related to the content size.

This is an unfortunate situation. To fix this, we would like to propose only applying `auto` if the element also has `content-visibility: auto`. This would ensure that the remembered size is only used if the element is offscreen, where an outdated size will only affect the scrollbar size.

Thoughts?

@dbaron @chrishtr @vmpstr @tabatkins

**Comment by chrishtr** [comment]
I think this is a good change, because offscreen placeholder sizing is the only use case we've defined for this feature. And it's very important to provide a way to utilize `content-visibility`, and this use case, this without script, so that pages can have excellent progressive rendering, and improve performance & accessibility.

Also, for developers who want to have the same behavior without `content-visibility: auto`, there is always the option to use a `RezizeObserver`.

**Comment by tabatkins** [comment]
Whoops, didn't link the edits for this issue to this thread: <https://github.com/w3c/csswg-drafts/commit/22a5e0e435a74e6b1ef7db2d2b72e6d405460d1a>

**Comment by cbiesinger** [comment]
Reopening as discussed, that edit does not affect c-v: auto

**Comment by chrishtr** [comment]
Didn't commit 22a5e0e clarify that c-v: auto is the only feature affected by the auto behavior?

**Comment by tabatkins** [comment]
No, my mistake, that was an irrelevant commit, it was just about the fact that an element can gain and lose a last remembered size several times. It has nothing to do with the "phantom size visibly sticking around" problem that Christian is talking about here.

The edit I just committed (6eb6faa) *is* directly handling that, tho.

**Comment by chrishtr** [comment]
I left a comment on that commit..

**Comment by Loirooriol** [comment]
I was confused because from the spec it seems that `contain-intrinsic-size: auto` can be used with `content-visibility: hidden`, but some WPT and this resolution say it's only with `content-visibility: auto`.

According to https://github.com/w3c/csswg-drafts/commit/6eb6faac07f40ae944fda0a0da25e4e5e51b315e#r61269377

> No, **the resolution was worded confusingly** to refer to the property value, when it meant the effect; if I did just gate it on the property value, Christian's issue would still apply exactly as stated, with a visible element having a phantom size. The intention was that it needed to only apply while the element was being skipped.
> 
> Christian and I discussed whether it made sense to only apply it while being skipped as a result of c-v:auto or in any skip, and we couldn't come up with a good reason to be restrictive.

So in https://software.hixie.ch/utilities/js/live-dom-viewer/saved/10484 I expect both elements to keep being 50px tall when gaining `content-visibility: auto` or `hidden`. But in Chromium `content-visibility: hidden` results in 1px, ignoring the `auto` in `contain-intrinsic-size`.

**Comment by cbiesinger** [comment]
I think the problem with c-v: hidden is that it makes it harder to specify when the value should be saved. You don't want the overhead of saving it for all elements. I guess for changing between c-v auto and hidden it would work but that seems less useful?

**Comment by cbiesinger** [comment]
It's been pointed out to me that chrome saves the size based on c-i-s auto, independent of c-v. I think it would be fine to use it also for c-v: hidden

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/css-sizing-4/#last-remembered says that it's not saved if the element has size containment. `content-visibility: hidden` always skips the contents, which turns on size containment.

So it basically matters if you set `content-visibility: hidden` dynamically.

**Comment by vmpstr** [comment]
The overarching question here is whether `contain-intrinsic-size: auto` remembered size should apply when `content-visibility: hidden` applies. 

From the spec text https://drafts.csswg.org/css-sizing-4/#valdef-contain-intrinsic-width-auto-length

> If the element has a [last remembered size](https://drafts.csswg.org/css-sizing-4/#last-remembered), is currently [skipping its contents](https://drafts.csswg.org/css-contain-2/#skips-its-contents), and is not [relevant to the user](https://drafts.csswg.org/css-contain-2/#relevant-to-the-user), its [explicit intrinsic inner size](https://drafts.csswg.org/css-sizing-4/#explicit-intrinsic-inner-size) is the last remembered size.

For `content-visibility: auto` this statement is clear since relevance to the user also determines whether it skips its contents. So, for example, if the element is on screen then it's relevant and we're not skipping contents. If it's off-screen and no other condition holds, it's not relevant and skips its contents.

However, for `content-visibility: hidden` it poses a performance problem: the element is always skipping its contents, so typically relevance to the user is not determined. The text as written changes that (as @Loirooriol pointed out), since we would now also have to keep track of whether `content-visibility: hidden` element is, among other things, on screen. It is also weird that some state may change based on relevance for this element. 

There's one of two possible fixes:
* remove "and is not [relevant to the user](https://drafts.csswg.org/css-contain-2/#relevant-to-the-user)" condition, which would cause `contain-intrinsic-size: auto` last remembered size to apply to `content-visibility: hidden`, if such a size exists
* make the text explicit by mentioning `content-visibility: auto`. This, along with the other two conditions, would cause `contain-intrinsic-size: auto` to only apply to `content-visibility: auto` and not `hidden`.

I don't have a strong opinion here, but I'm leaning slightly towards making `contain-intrinsic-size: auto` apply to `content-visibility: hidden`. For additional context, the [TAG discussion](https://github.com/w3ctag/design-reviews/issues/624) for this issue was satisfied with the limited case of `content-visibility: auto`, and adding `content-visibility: hidden` here as well may raise additional questions

**Comment by Loirooriol** [comment]
Yeah I filed #7521 to drop the "not relevant to the user" condition, but it may be better to discuss here since there is the option of restricting to `content-visibility: auto`.
