### ISSUE TITLE
[css-text] Is the test CSS2/text/text-align-white-space-007.xht valid?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6344]
The test at CSS2/text/text-align-white-space-007.xht involves `white-space: pre-wrap` together with `text-align: justify` and `direction: rtl`.

According to [wpt.fyi](https://wpt.fyi/results/css/CSS2/text?label=master&label=experimental&aligned&q=text-align-white-space-007.xht), it currently passes on Firefox but not on Safari, Edge or Chrome. However, I'm finding it difficult to understand why the expected behavior would be "correct", and a [change I'd like to make in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1712703) will cause it to start "failing" there as well (while fixing other testcases).

It looks to me like this testcase does not take account of the fact that the [`pre-wrap` value](https://drafts.csswg.org/css-text-3/#valdef-white-space-pre-wrap) allows line-end spaces to hang (as noted in the summary table of behaviors below the list of values). I guess it predates the introduction of the separate `break-spaces` value, which wraps similarly but preserves all spaces; for that value, the "expected" result would be correct, but for `pre-wrap` it seems wrong.

If my understanding is correct that this testcase is invalid (at least according to current specs; it may have been valid when written), I would suggest we simply delete it. There are newer tests of these properties under the `/css/css-text/` directory.

**Comment by frivoal** [comment]
I suspect the reason for this test is not just the end-of-line hanging, but mainly that [the spec says](https://drafts.csswg.org/css-text-3/#text-align-property):

> If an element’s white space is not collapsible, then the UA is not required to adjust its text for the purpose of justification and may instead treat the text as having no justification opportunities.

The test does have the "may" piece of meta data, meaning that it's ok to fail, but given that this is merely an allowance for legacy behavior, rather than a requirement or event a suggestion, I agree just deleting the test is probably best.

From a spec point of view, this used to be a requirement in css2, which css-text-3 merely relaxed, but if Firefox aligns with others, then we'll have interoperability on the opposite behavior, so maybe we should spec that behavior, even if it's a breaking change with CSS2.

cc: @fantasai

**Comment by fantasai** [comment]
I think the reason the allowance was made to not justify pre-wrap text was because handling tabs seemed tricky while justifying text. I think the spec is fine, but removing the testcase so that we don't encourage implementations to pass it, sounds good to me.
