### ISSUE TITLE
[css-highlight-api] Need clarification on expected default values for style properties

### ISSUE THREAD

**Issue by ffiori** [w3c/csswg-drafts#6375]
I didn't find any statement on default values for style properties of ::highlight in the [spec draft](https://drafts.csswg.org/css-highlight-api-1/). There are some default values in the [spec for pseudos](https://drafts.csswg.org/css-pseudo-4/#highlight-ua-styles ) but ::highlight is not in the list. Also in the [spec draft of ::highlight](https://drafts.csswg.org/css-highlight-api-1/) there's no mention of it. 

Should it use no visual effects or should it use for example [Highlight/HighlightText](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/layout/layout_theme.cc;l=593;drc=c06511a314747fab345af58b8523eec1b36caf05;bpv=1;bpt=1) colors instead? I assume it's taking no visual effects as default values (as in when background-color is not specified inside a ::highlight(foo) then the content's background is the same as if there was no ::highlight defined), but maybe it should be explicitly stated?

**Comment by sanketj** [comment]
Since ::highlight targets author-defined highlights rather than UA-defined highlights, I don't think UAs should define any styles for ::highlight in their default stylesheets. It's also actually not possible to do this since ::highlight requires a highlight name to be passed and there's no way to write a rule that targets all ::highlight pseudos.

The default styles should just be inherited from the originating element. I do agree that we should mention this explicitly in the spec though.

**Comment by sanketj** [comment]
This issue requires an update to the spec, which is still pending. Leaving this open till that has landed.
