### ISSUE TITLE
[css-contain-3] Provide a syntax to query a specific container-type

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6393]
The draft [Container Query spec](https://drafts.csswg.org/css-contain-3/) describes the container query syntax in two parts: 

```css
@container <<container-name>>? <<container-query-list>> {
  <<stylesheet>>
}
```

Which resolve in two distinct steps:

1. **container selection**: Find the right container to query (nearest ancestor container, after optionally filtering by `<<container-name>>`)
2. **query evaluation**: Evaluate each feature in the `<<container-query-list>>`

If no eligible container is selected, the query evaluates to `false`. 

If the selected container in step 1 is not a valid [container type](https://drafts.csswg.org/css-contain-3/#container-type) for the query features used in step 2, then the query evaluates to `unknown`. For example, if we try to query a `block-size` container-type about its `inline` dimensions, that measurement is unknown. 

That means authors will likely _also_ want to filter and select containers based on container type – eg find the nearest `inline-size` container in step 1, in order to query its `width` in step 2. And, since a `<<container-query-list>>` could combine multiple different features, we might need to select for more than one container type.

Since container-names are custom identifiers, and container types are built-in keywords (with potential for new additions later on) we'll need some way to distinguish them — either by requiring dashed-idents for names (not a great option), or by adding distinct syntax for selecting each one in the `@container` rule. Something like:

```css
@container <<container-name>>? type(<<container-type>>+)? <<container-query-list>> {
  <<stylesheet>>
}

@container sidebar type(inline-size style) (width > 30em) and (--card: small) {
  <<stylesheet>>
}
```

- Is there a better approach than adding a `type()` function, or a better name for that function?
- Do we need clearer delineation between the selection & query aspects of the `@container` rule?

**Comment by mirisuzanne** [comment]
Maybe something that reflects the [container shorthand](https://drafts.csswg.org/css-contain-3/#container-shorthand) syntax?

```css
@container (inline-size style / sidebar) (width > 30em) and (--card: small) {
  <<stylesheet>>
}
```

**Comment by andruud** [comment]
For the shorthand-like proposal, I assume it should be possible to _only_ specify a name or only specify a type? In that case we would need to exclude `size`, `inline-size` etc from the `<custom-ident>`of `<container-name>`, and then we're back at the problem of magic keywords.

> better approach than adding a type() 

Validate its existence somewhat by also having `name()` for name-based selection? :slightly_smiling_face: 

> clearer delineation

Maybe it helps to demand parens, i.e. make the grammar `<media-in-parens>` (or container-in-parens) rather than `<container-query-list>`:

```
<container-selection> = <container-name> | [ name(<container-name>+)? type(<container-type>+)? ]

@container <container-selection>? <media-in-parens> {
  <stylesheet>
}
```

Although one thing to watch out for here is that if `fn()` is valid for both the selection and the query, we get a problem with: `@container fn() {}`. So maybe `<media-in-parens>` is not enough.

**Comment by fantasai** [comment]
I like the idea of keeping the name/type syntax in the `container` shorthand and in the `@container` rule consistent, as mentioned in https://github.com/w3c/csswg-drafts/issues/6393#issuecomment-863470197 . Maybe that means using the `container` syntax in `@container` or maybe it means shifting both to a new syntax that is a good fit for both contexts, but either way I think the consistency would benefit authors.

**Comment by mirisuzanne** [comment]
A few options for a shared shorthand…

We current `container` property syntax relies on consistent order, and the `/` divider (eg `types / names`). In order to make that work with both sides optional, the delimiter needs to be used for all names, even when no type is given. Either using punctuation or a keyword:

```css
/* using the current `/` divider */
@container inline-size / my-name ( width > 30em ) { … }
@container inline-size ( width > 30em ) { … }
@container / my-name ( width > 30em ) { … }

/* using a single keyword, still ordered */
@container for inline-size as my-name ( width > 30em ) { … }
@container as my-name for inline-size ( width > 30em ) { … }
@container for inline-size ( width > 30em ) { … }
@container as my-name ( width > 30em ) { … }
```

But that order was based on the assumption that a type is required, and names are optional in the shorthand. That assumption is clearly false in the `@container` rule, but it may also be wrong for the shorthand property. If we consider re-using named containers for something like a scroll-timeline (see @@@), it doesn't seem like types should be required in those situations. That makes me want a more flexible syntax, where the order is less important. That could be done with two keywords (`'for' <types> || 'as' <names>`): 

```css
@container for inline-size as my-name ( width > 30em ) { … }
@container as my-name for inline-size ( width > 30em ) { … }
@container for inline-size ( width > 30em ) { … }
@container as my-name ( width > 30em ) { … }
```

But the more I stare at this, the more tempted I am to just use dashed-idents for names, and allow the two values to mingle completely: 

```css
@container inline-size --my-name ( width > 30em ) { … }
@container --my-name inline-size ( width > 30em ) { … }
@container inline-size ( width > 30em ) { … }
@container --my-name ( width > 30em ) { … }
```

That might also allow us to express and/or combinations, maybe with the `/` divider between container-selection and query logic (if that division needs more clarity). Something like:

```css
@container inline-size and --my-name / ( width > 30em ) { … }
@container (--my-name or --other-name) / ( width > 30em ) { … }
```

We could consider adding parenthesis around any of these options, if it helps.

**Comment by mirisuzanne** [comment]
I think there are two or three potential resolutions here:

1. Change the query preamble syntax to `@container <name>? [ / <type> ]? { ... }`
2. Change the container shorthand to match, with name first `container: <'container-name'>? [ / <'container-type'> ]?`
3. Make `type` optional for establishing containers:
   - Containers with a name and no type are considered style containers
   - Or perhaps all elements are style containers by default?

**Comment by bramus** [comment]
> Perhaps all elements are style containers by default

If that were the case, that would solve [Higher Level Custom Properties that were talked about late 2020](https://github.com/w3c/csswg-drafts/issues/5624#issuecomment-746339609), no? If I interpret things correctly, the there proposed `@if (<style-query) { … }` could be seen as syntactic sugar for `@container / style (<style-query) { … }`, right?

Furthermore, if all elements were style containers by default, is `style` still a necessary value for `container-type`? Reasoning: as all elements already are style containers, there's not need to define them manually as such, right?
Note that in this case, as a side-effect to that decision, setting `container-type` to, for example, `inline-size` would be something to apply on top of it already being a style container. I.e. `container-type: inline-size;` will result in the element being both a style and size container.

---

Regarding the syntax itself: I feel that there's some tight clinging onto the `@container` at-rule here. With all elements (possibly) being style containers, it — as an author — would feel more logical to write `@style(<style-query>) { … }` instead of `@container / style (<style-query) { … }` though.

IIRC there is discussion somewhere that warned/decided against introducing a lot of new at-rules, so I can definitely understand. From an author's POV however, it feels a bit weird though. I think this "weirdness" stems from the fact that viewport media queries (`@media`) always are size based queries, not style based ones.

My initial reaction to container queries is the same: using `@container` is about the size of the element. I understand that it's more than size only, but I can imagine a lot of authors will be confused about it or only get part of the message (the size part), missing out on style/state/x containers.

---

What I'm trying to say here: as an author, this piece of code would be highly readable, even if I wouldn't know the exact details about style or container queries:

```css
.item {
  --effect: none;
  …

  @style (--effect: fancy) { /* targets self */
    …
  }

  @container (width >= 20em) { /* targets closest parent with size containment */
    …
   }
}
```

A version that uses `@container / style (…)` instead would be harder to read and can confusing, as `@container` there targets a parent whereas `@container / style` targets the element itself.

Given this last confusion I'm raising here: yes, this could be seen as a plea for keeping `@container` reserved for only size based querying.

---

Apologies if I'm sidetracking here, or if I'm raising things in here that were already discussed. Feel free to ignore what's not relevant, I know you all will make the correct decisions in the end :)

_(Congrats on hitting FPWD BTW! 🎉)_

**Comment by mirisuzanne** [comment]
> Furthermore, if all elements were style containers by default, is style still a necessary value for container-type? … I.e. `container-type: inline-size;` will result in the element being both a style and size container.

That seems right to me.

> it — as an author — would feel more logical to write @style(<style-query>) { … } instead of @container / style (<style-query) { … } though.

Specifying the container-type isn't required in the current syntax, and (as you note) `style` might not even be needed as a type if we do make it a default everywhere. We also made the queries into functions. So the currently proposed syntax here for most cases would be:

```css
@container style(--effect: fancy) {…}
@container size(width >= 20em) {…}
```

I think that's already pretty readable? What I like about `@container` as a rule for both size and style is that it clarifies *what element you are querying*, before stating *what feature to query* – and then it allows you to optionally filter those elements by a container name:

```css
@container card style(--effect: fancy) {…}
@container article size(width >= 20em) {…}
```

If we say that every element is a style container, then there would be no reason to ever use `/ style` in the preamble, since that would not filter out any elements. 

> My initial reaction to container queries is the same: using @container is about the size of the element. I understand that it's more than size only, but I can imagine a lot of authors will be confused about it or only get part of the message (the size part), missing out on style/state/x containers.

There is nothing about the word "container" that implies size, so this would only be true for authors with a strong historic attachment to "container queries" as an Idea. That seems to me like a very focused and temporary issue, easily overcome by some good resources.

**Comment by bramus** [comment]
Thanks for clarifying, Miriam.

I was a bit confused about the functions part because the examples in the ED don't use it. For example, I see:

```css
@container card (inline-size > 30em) and (--responsive = true) { … }
```

The definition for `<container-query>` does already include this change

```
<container-query>     = ( <container-condition> )
                      | size( <size-query> )
                      | style( <style-query> )
```

So if I understand correctly the snippet above would — if this change gets accepted — become this:

```css
@container card size(inline-size > 30em) and style(--responsive = true) { … }
```

That's correct?

_(As long as this issue is still open, I can see why the examples aren't updated yet. No worries)_

> There is nothing about the word "container" that implies size, so this would only be true for authors with a strong historic attachment to "container queries" as an Idea. 

I know what I'll be explicitly mentioning whenever I get to talk/write about them :)

**Comment by mirisuzanne** [comment]
Yes, that's correct. I'll make sure to update the examples at some point here. 

> I know what I'll be explicitly mentioning whenever I get to talk/write about them :)

haha, great!

**Comment by una** [comment]
I don't think we should default everything to being a style container. This came up with [currentBackgroundColor](https://github.com/w3c/csswg-drafts/issues/5292) 

Consider the following:

```
<div class="card">
  <img />
  <div class="meta">
    <p>Text <a href="#">Link</a></p>
    <button>
      Buy Me on <span>Store</span>
      <span>$10.99</span>
    </button>
  </div>
</div>
```

If I wanted to change the color of the `span`s or`<a>`'s, based on the card background color, it would use `transparent` by default and not the `.card`'s background color. In this case, we wouldn't want that — we'd want a higher-level parent and not a direct parent. We'd want to query the `.card` container.

Setting explicit containers works better in this case, and setting `container-type` will make it easier to have expected results.

**Comment by mirisuzanne** [comment]
While having all elements default to style containers can cause issues for non-inherited properties (like @una's background-color example), I think it works out great for inherited properties: checking the parent font size, or current font-style, weight, color, etc. Those use-cases are very handy for solving style-toggle use cases (if parent is italic, child should be normal, and vice versa).

For use-cases where it's important to query a specific container (including user-defined container types like 'containers with backgrounds'), setting a `container-name` makes it much more robust against the possibility of accidental intervening containers. Whether or not we revisit this resolution, I would still push authors towards naming containers when that's important — as it is with `background-color`. 

I'm happy to revisit this if we want to put it back on the agenda (or discuss it as a part of resolving #6644), but at this point I still think we made a reasonable decision.

**Comment by una** [comment]
My main issue with this is I just don't think it's a reasonable default to assume that a user wants to query the style of a direct parent in a container query. In my current experience with CQ, the majority of my demos and use cases do not query the direct parent. To help illustrate:

## [CQ Card](https://codepen.io/web-dot-dev/pen/LYzxgxP)
  - adjusting styles of `.desc` which is within a block called `.meta` but I'm querying the parent `.card`'s container size 
 
![Screen Shot 2022-02-09 at 10 24 19 AM](https://user-images.githubusercontent.com/1693164/153232841-292d488d-1065-42e8-a5ad-1a8a7337ec53.png) in:

![Screen Shot 2022-02-09 at 10 28 50 AM](https://user-images.githubusercontent.com/1693164/153233351-2cace09e-181a-4a54-b1c6-92295d67cd50.png)


## [Button Component Inside CQ Card](https://codepen.io/una/pen/zYdJvvw)
- The `span` within `.btn-text` is querying `button`
- `button` within `div` within `.card` is querying `card-container`
- The only thing directly querying its parent is  `plus-icon` within `.cart-icon` because it happens to be organized this way


![Screen Shot 2022-02-09 at 10 30 38 AM](https://user-images.githubusercontent.com/1693164/153236138-9386901b-2a62-4485-a470-babc7ef8c923.png)

in
![Screen Shot 2022-02-09 at 10 38 04 AM](https://user-images.githubusercontent.com/1693164/153235237-b7fe289e-92d4-4fbd-bea4-2448cb4e40b3.png)

**Comment by astearns** [comment]
In https://github.com/w3c/csswg-drafts/issues/6644#issuecomment-1034036418, we resolved to remove type from the preamble

- RESOLVED: remove the container-type syntax from the preamble of the @container rule

**Comment by mirisuzanne** [comment]
I split out the remaining questions here into a new issue #7066. Closing this issue as resolved, as we've decided to remove container-type selection syntax, and rely on automated container-type selection.
