### ISSUE TITLE
[css-highlight-api] Specifying behavior for Highlights involving multiple documents

### ISSUE THREAD

**Issue by dandclark** [w3c/csswg-drafts#6417]
The [Highlight API spec](https://drafts.csswg.org/css-highlight-api-1/) doesn't really consider cases where Highlights exist in multiple documents. The use of same-domain iframes bring up some interesting cases.

#### Case 1: A `Highlight` is registered in multiple registries.
```js
let iframe = document.createElement("iframe");
document.body.appendChild(iframe);
let r = new Range();
r.setStart(document.body, 0);
r.setStart(document.body, 1);
let h1 = new Highlight(r);
CSS.highlights.set("foo", h1);
iframe.contentWindow.CSS.highlights.set("foo", h1);
```

This case breaks some assumptions of the current Chromium implementation, where a [Highlight](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/highlight/highlight.h;l=82?q=blink::highlight&ss=chromium) only has a pointer back to a single HighlightRegistry instance. The language of the spec also seems to assume that a highlight registry only contains highlights from a single document, but there is nothing explicitly blocking the scenario in the code above.

https://drafts.csswg.org/css-highlight-api-1/#registration:
*"The **`highlight registry`** is accessed via the `highlights` attribute of the `CSS` namespace, and represents all the custom highlights registered for the current global object’s associated `Document`."*

It's not completely clear what should happen here. Should it be possible for a Highlight to be added to multiple registries? If so, should changes to its contents trigger repaints for the documents associated with both registries?

#### Case 2: A `Highlight` has ranges from multiple documents

```js
let iframe = document.createElement("iframe");
document.body.appendChild(iframe);
let r1 = new Range();
r1.setStart(document.body, 0);
r1.setStart(document.body, 1);
let r2 = new Range();
r2.setStart(iframe.contentDocument.body, 0);
r2.setStart(iframe.contentDocument.body, 1);
let h1 = new Highlight(r1, r2);
CSS.highlights.set("foo", h1);
```

The language in https://drafts.csswg.org/css-highlight-api-1/#range-invalidation says that the UA must ignore ranges not in a document tree, but doesn't consider the case where ranges are in a different document tree from the one associated with the given highlight registry.

Again it's not clear what should happen here. Should the UA ignore ranges that are in a document tree different from the one associated with the highlight registry containing the `Highlight`?

#### Solutions

An incremental fix for these corner cases would be to specify the following:
1. A Highlight can be added to multiple highlight registries. In Chromium, this would mean that Highlight would store a list of pointers back to highlight registries, instead of a single pointer.
2. When computing how to render a document, if a range in the highlight registry associated with that document is not in that document tree, ignore that range.

A result of doing things this way is that if a Highlight has ranges that are in different document trees, both ranges will be painted if and only if the Highlight was added to the highlight registry for both ranges.

A more adventurous idea that simplifies this somewhat is to consider whether Highlight can be eliminated altogether, such that ranges are added directly to the highlight registry. After https://github.com/w3c/csswg-drafts/pull/6198, Highlight is no longer needed to store the name. That leaves only `priority`. Could `priority` be specified some other way? One idea is to have a method to do this directly on the registry, e.g. `CSS.highlights.setPriority("name", 42)`. Or, maybe the priority could be provided in CSS:

```css
::highlight(name) {
  background-color: orange;
  priority: 42;
}
```
I don't immediately see a reason not to specify the priority through the cascade like this, so it might be worth considering as a way to eliminate Highlight and simplify the API, thus making it easier to handle the cases described above involving multiple document trees.

**Comment by dandclark** [comment]
Pinging some folks who might have thoughts on these cross-document cases: @frivoal, @fantasai, @hober.

I wonder how Webkit's implementation handles this?

**Comment by sanketj** [comment]
RE priority: See the full discussion here: https://github.com/w3c/csswg-drafts/issues/4591#issuecomment-790012016. Priority can't be CSS property because that would allow two highlight pseudos to be stacked differently in different locations within the document, which would violate the "single overlay per highlight for the whole document" principle layed out by the CSS pseudo spec. We also discussed other options for modeling priority, but amongst the options we came up with, a priority attribute on Highlight still seemed to be the best way forward.

Additionally, in the future, when we spec highlight events, it will be beneficial to have the `Highlight` object and make it an event target. This will make it easier for authors to write event handlers that target any range in a highlight. Ex: The author may want to show a corrections card when the user clicks on spelling errors (implemented via custom highlights) on the page. By making `Highlight` an event target, the author can write a handler that targets all spelling errors, rather than having to write one per range.

RE the cross-document cases: Yes, we should update the spec to describe how cross-document cases should be handled. I don't believe there are actual use cases for doing this, therefore I'm okay just doing something simple to handle these reasonably. The suggested solution sound reasonable to me: (1) allow highlights to be registered in multiple highlight registries, and (2) when painting highlights registered within a given registry, do not paint ranges that are associated with a different document. In Chromium at least, I don't believe this will be too hard to implement.

**Comment by dandclark** [comment]
Thanks @sanketj for the extra context! Given that, I'm definitely inclined to go with that simpler solution.

**Comment by dandclark** [comment]
Right after discussing this I realized there's a problem with the "throw on mismatch" approach that we didn't catch during the meeting. The issue is that a Range can be moved to another Document _after_ it has been added to a `Highlight` and _after_ the `Highlight` has been added to the `HighlightRegistry`.

```js
let iframe = document.createElement("iframe");
document.body.appendChild(iframe);
let r1 = new Range();
r1.setStart(document.body, 0);
r1.setStart(document.body, 1);
let h1 = new Highlight(r1); // doesn't throw; r1 is in the creator document of the Highlight.
CSS.highlights.set("foo", h1); // doesn't throw; Highlight's creator document is the same as the HighlightRegistry's.
r1.setStart(iframe.contentDocument.body, 0); // r1 is now in a different document! But it's too late for highlight APIs to throw.
r1.setEnd(iframe.contentDocument.body, 0);
```

The above breaks the proposed invariant that a `HighlightRegistry`'s `Highlight`s only have Ranges from the document associated with the `HighlightRegistry`. But, there was no point at which we could have thrown, unless every time we move a `Range` we do a check for each `Highlight` that it is a member of.

I can't think of a solution for this, so I think we should revisit the original solution discussed during today's meeting:
> 1. A Highlight can contain Ranges from multiple document trees.
> 2. A Highlight can be added to multiple HighlightRegistries.
> 3. When a HighlightRegistry is painting one of its Highlights, it must only paint the Ranges in the document tree associated
   with that HighlightRegistry.

Or maybe there's a way to work around this problem that I'm not seeing. cc @smfr @emilio @tabatkins @sanketj
