### ISSUE TITLE
[css-sizing] aspect-ratio elements can have conflicting min-content sizes

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#6418]
What is the min-content size of the outer element here?
```html
<div style="background: green; height: 100px; aspect-ratio: 1/2;">
  <div style="width: 100px;"></div>
</div>
```

https://drafts.csswg.org/css-sizing-3/#min-content says
> The smallest size a box could take that doesn’t lead to overflow that could be avoided by choosing a larger size.

That's clearly 100px for this case. The inner div would overflow with anything smaller.

&nbsp;  

But https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes says
> The min-content size of a box in each axis is the size it would have if it was a float given an auto size in that axis (and no minimum or maximum size in that axis) and if its containing block was zero-sized in that axis.

So, we can test that with the below [snippet](https://jsfiddle.net/dgrogan/uv59y0jh/1/). Correct me if I'm wrong, but I think 'no minimum or maximum size in that axis' can be represented with `min-width: 0px` and `max-width: none` based on the principle mentioned in the second paragraph of https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-651402662.

```html
<div style="width: 0px">
  <div style="background: green; height: 100px; aspect-ratio: 1/2; min-width: 0px; max-width: none; float: left;">
    <div style="width: 100px;"></div>
  </div>
</div>
```

Both Firefox and Chrome give the green block a 50px width. So 50px is the min-content size. But that's different than the 100px https://drafts.csswg.org/css-sizing-3/#min-content gave us.

I think https://github.com/w3c/csswg-drafts/issues/5032 intended for this case to have a 50px min-content size.

**Comment by tabatkins** [comment]
You're right - the text in "min-content" is (and has been for a long time) a rough conceptual gloss of the behavior; the text in "intrinsic sizes" is the actual technical definition. Your reading of it is right; the min-content size is 50px, since that's the size you'd get if you applied `min-width: 0; width: auto; max-width: none;` and then floated it in a zero-width container. (The aspect-ratio would transfer the height:100px across to resolve the automatic width.)

However, in most cases the element will still end up being 100px wide due to the automatic minimum width, since the inline axis is the ratio-dependent axis and thus <https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum> applies to prevent possibly-unintentional overflow.

Chrome and Firefox (we haven't tested others) already have exactly this behavior, so hopefully this is fine?

**Comment by fantasai** [comment]
@davidsgrogan I checked in some clarifications to the definition of min-content size. Let me know if you think the spec is sufficiently clear now!

**Comment by davidsgrogan** [comment]
Clear now.
