### ISSUE TITLE
The group's home page doesn't appear to link to the group's charter

### ISSUE THREAD

**Issue by hober** [w3c/csswg-drafts#6437]
Find in page for the word "charter" on https://www.w3.org/Style/CSS/ fails to find anything.

**Comment by frivoal** [comment]
It can be found from https://www.w3.org/Style/CSS/members, but I agree there should be a link from the top level

**Comment by atanassov** [comment]
@hober is that an established pattern other WGs follow and we don't, or something people look for and can't find?

**Comment by svgeesus** [comment]
Thanks for reporting this. I had previously fixed it, but the page is still being autogenerated by Bert's old scripts and seems to have removed the charter link again.

**Comment by svgeesus** [comment]
>  is that an established pattern other WGs follow and we don't,

Yes.

**Comment by svgeesus** [comment]
It can also be found from [the list of all working groups](https://www.w3.org/groups/wg/)

**Comment by svgeesus** [comment]
So, I would like to change the official CSS WG homepage (the one that is linked to from Status of this Document on /TR published specs) from [the general CSS Overview that Bert wrote](https://www.w3.org/Style/CSS/) to the [autogenerated and always up to date WG page](https://www.w3.org/groups/wg/css).

This fixes the "link to charter" issue, and makes things easier for AC Reps because we will then have the same structure as most other groups. The page uses a consistent format for finding who the chairs and staff contacts are, when each charter was approved, a list of WG members, IPR status for all specifications, and so on.

The page Bert wrote still has value, for people new to CSS, but it isn't really about  the CSS WG. It is about CSS.
