### ISSUE TITLE
[css-color-4] Meaning of "host syntax"

### ISSUE THREAD

**Issue by leo60228** [w3c/csswg-drafts#6439]
[The spec](https://www.w3.org/TR/css-color-4/#interpolation-space) has this sentence:

> The host syntax may define what the default interpolation space should be for each case, and optionally provide syntax for authors to override this default.

I might be missing something obvious, but I can't find any other usages of "host syntax" in relation to CSS. I'm *guessing* that this means the markup language like HTML or SVG, but I think that should be clarified.

I also found #6059, which was about an unrelated point of confusion with this line.

**Comment by svgeesus** [comment]
Ah, good point and a reasonable interpretation. But primarily, other CSS syntax was meant. Color interpolation happens because of:

- gradients
- filters
- animation
- transitions
- color-mix

In general though we are trying to avoid those defaults for new constructs. For example `color-mix()` used to have an LCH default but we changed it to require an explicit color space.

The older constructs will have to have an sRGB default, sadly, for Web compat (filters has sRGB-linear as default)

**Comment by svgeesus** [comment]
The term "host syntax" has now been explicitly defined, and examples given. @leo60228 does that resolve your comment?

**Comment by leo60228** [comment]
Yep, thanks!
