### ISSUE TITLE
 [css-flexbox][css-align][css-grid] Incompatible spec for align-self computed value when 'auto'

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#644]
It seems that last month it was agreed than 'auto' values on align-self and justify-self compute to itself from now on, based on https://github.com/w3c/csswg-drafts/issues/440 .

I have to say that it's surprising that, after some many discussions, we've ended up with this approach. But anyway, this is in conflict with what the current draft of Flexible Box states for the align-self property:
-  https://drafts.csswg.org/css-flexbox/#align-items-property
  > On absolutely positioned elements, a value of auto computes to itself. On all other elements, a value of auto for align-self computes to the value of align-items on the element’s parent, or stretch if the element has no parent.

I think we need to match both specs, otherwise the implementation of the CSS Alignment specification is going to be really difficult.

**Comment by fantasai** [comment]
I think the key limitations leading to this were that a) absolutely-positioned boxes need auto to compute to itself whereas all other boxes take the value from the parent's align-items, making the computation depend on `position`, and b) Gecko folks don't like cross-property computed value dependencies. Since neither animation nor inheritance provide significant use cases here that we need to consider, we went with the route that yields less accurate computed values in favor of ease-of-implementation.

**Comment by mrego** [comment]
Hi @fantasai it seems that as part of this change, you forget to [update the text on the spec](https://github.com/w3c/csswg-drafts/blob/master/css-flexbox/Overview.bs#L2006):
> On absolutely positioned elements, a value of auto computes to itself. On all other elements, a value of auto for align-self computes to the value of align-items on the element’s parent, or stretch if the element has no parent.

**Comment by fantasai** [comment]
Thanks, @mrego :) Should be fixed now.
