### ISSUE TITLE
[css-scrollbars-1] Are overlay scrollbars/indicators out of scope for scrollbar-color property effects

### ISSUE THREAD

**Issue by jonjohnjohnson** [w3c/csswg-drafts#6443]
https://drafts.csswg.org/css-scrollbars-1/

Nothing in the specs current language leads me to believe the answer to this issues title is explicitly "yes".

> If this property computes to [a] value other than auto, implementations may render a simpler scrollbar than the default platform UI rendering, and color it accordingly.

But the "may" here affords a browser to color non-overlay scrollbars and ignore overlay scrollbars. Is this the intent of the spec?

https://bugzilla.mozilla.org/show_bug.cgi?id=1719948

**Comment by frivoal** [comment]
The intent is that this applies to both classic and overlay scrollbars, but if for some reason these (possibly native) scrollbars cannot be colored, due to how they're structured, or to a lack of control given by the native toolkit, the UA may chose to replace them with differently-constructed scrollbars, which it does know how to color. There's no particular expectation that it would switch from classic to overlay or vice-versa to do so (but then again, no prohibition against it either, since the choice of classic vs overlay is always up to the UA anyway).
