### ISSUE TITLE
[css-cascade-5] Any needs to avoid other layers overriding name-defining @-rules?

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#6461]
The current spec already allows a layer to make a declaration `!important`, so that other layers cannot override it. For example:

```
@layer base { 
  @keyframes foo { ... }
  #target {animation-name: foo !important; }
}

@layer override {
  @keyframes bar { ... }
  #target {animation-name: bar;}
}

/* #target ends up animated with foo */
```

However, override layers can still override the animation by overriding the at-rules (as discussed in #6404):

```
@layer base { 
  @keyframes foo { ... }
  #target {animation-name: foo !important; }
}

@layer override {
  @keyframes foo { ... }
}

/* #target ends up animated with overridden animation */
```

In this way, even though the base layer doesn't want to be overridden, the override layer still has a way to get around it. This is probably against the intention of the author of the base layer, and against why we have the `!important` keyword.

---

I'd like to discuss:

1. Do we want to introduce a mechanism so that override layers cannot override at-rules defined by base layers?
2. If yes, how?
    - Allow `!important` keyword on at-rules?
    - Introduce something like "layer-scoped name/reference" (similar to [tree-scoped name/reference](https://drafts.csswg.org/css-scoping/#shadow-names)), so that declarations in the base layer cannot reference at-rules defined by the override layer?
    - Other thoughts?

**Comment by mirisuzanne** [comment]
I don't see this as an issue specific to cascade layers, or one that layers need to solve. It is already possible for name-defining rules to override each other, and layers make it simpler to describe the _order_ in which they override each other. If the override is intentional, then layers are working as designed. If the override is _accidental_, then it's not a new problem specific to layering. It seems more like a namespace/scope issue.

- If we want to add `!important` at-rules, I think that's an interesting idea, but somewhat tangential to this feature. 
- I would not like to add layer-scoped names. I think that approach blurs the goals. Layers are not a mechanism for locking in particular references to avoid conflicts (that's a scope issue), they are a mechanism for clearly defining an order of cascade precedence – which is working successfully in the example. Authors can move their animations into the appropriate layers so that the proper one is applied.

**Comment by xiaochengh** [comment]
Thanks for resolving!
