### ISSUE TITLE
[css-text] text-align: match-parent on the root element with direction: rtl doesn't match browsers

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#6542]
See this test: https://github.com/web-platform-tests/wpt/pull/30175

If I understand correctly, a used value of 'direction: rtl' on the root element is propagated to the ICB per https://drafts.csswg.org/css-writing-modes-3/#icb

Then, https://drafts.csswg.org/css-text/#valdef-text-align-match-parent says

> match-parent
> This value behaves the same as inherit (computes to its parent’s computed value) except that an inherited value of start or end is interpreted against the parent’s (or the initial containing block’s, if there is no parent) direction value and results in a computed value of either left or right. When specified on the text-align shorthand, sets both text-align-all and text-align-last to match-parent.

The initial value of text-align is 'start', so I guess the inherited value for the root element has to be 'start'. Therefore, it looks at the 'direction' of the ICB, which is propagated from the root element, and is thus 'rtl'. Therefore text-align should compute to 'right'.

Here are the results of the test:

Firefox Nightly | Safari TP | Chrome Canary
----|-----|-----
expected "right" but got "start" | expected "right" but got "left" | expected "right" but got "left"

Is my reading of the spec correct?

Should the spec be changed to side with either Firefox or Safari/Chrome?

Also, the spec only says that the computed value is "either left or right", which doesn't say which value to use. I assume a mapping where direction: ltr -> left and direction: rtl -> right, but the spec should say so explicitly.

**Comment by frivoal** [comment]
> A literal reading allows any behavior so long as the computed value is either left or right.

If it only said 
> results in a computed value of either left or right.

I'd agree with you, but right before that there's 

> start or end is interpreted against the parent’s […] direction value

which doesn't seem to allow "any behavior so long as the computer value is either left or right", but calls for a specific way to find whether it's left or right. At least as far as I can tell. Does it not?

**Comment by frivoal** [comment]
> match-parent on the root doesn't make a whole lot of sense to begin with, so I think the shortest path to interop (Firefox changing to match WebKit/Chromium) seems like a good option.

Do we have any usage numbers on this case? My expectation would be that using it on the root would be pretty rare, but that when it is used there, the specified behavior does make more sense. However, if it's hardly even used, maybe it doesn't matter too much and we could indeed take the quickest path to interop?

**Comment by fantasai** [comment]
If it doesn't matter too much, then having interop or not doesn't matter either. I'd rather the spec defined reasonable, expected behavior so that when the relevant bits of code get rewritten they get rewritten to sensible behavior not some random "shortest path to interop on a small problem" behavior.

**Comment by fantasai** [comment]
Proposal: no change to spec, land the testcase as-is. @zcorpan do you have any objection to this?

**Comment by zcorpan** [comment]
> If it doesn't matter too much, then having interop or not doesn't matter either.

I disagree, getting interop on the details even if the details are by themselves not important makes for a robust and predictable platform where developers can test what happens in one UA and expect it to work the same in others. Specifying something that no UA implements now means the first to conform will make interop worse and risk breaking some web content.

I object to this. Ways to resolve my objection:

- get sign-off from relevant folks from at least two of Gecko, WebKit and Chromium that they want to change to conform to the spec. In this case, they should all have bugs filed to track the issue.
- specify what WebKit and Chromium do. In this case, we should file a bug for Gecko.

**Comment by emilio** [comment]
For the record gecko behavior is intentional, see:

https://searchfox.org/mozilla-central/rev/9902932742fcdce2c956eeb81fd38350f5394ab2/servo/components/style/values/specified/text.rs#558-566
```rust
                // on the root <html> element we should still respect the dir
                // but the parent dir of that element is LTR even if it's <html dir=rtl>
                // and will only be RTL if certain prefs have been set.
                // In that case, the default behavior here will set it to left,
                // but we want to set it to right -- instead set it to the default (`start`),
                // which will do the right thing in this case (but not the general case)
                if _context.builder.is_root_element {
                    return TextAlignKeyword::Start;
                }
```

**Comment by frivoal** [comment]
> but the parent dir of that element is LTR even if it's `<html dir=rtl>`

Is that spec compliant? Unless I'm confused, that seems to go against https://www.w3.org/TR/css-writing-modes-3/#icb

Either way, the keyword that gecko resolves to is `start` rather than `right`, but that does put it on the right side, so it's more spec compliant than Chrome & Safari, isn't it?

**Comment by emilio** [comment]
@frivoal propagation to the icb is done _after_ style resolution, though, so it can't really be used to deal with this. We could use the root element's writing-mode itself, but that wouldn't match the spec either because the principal writing mode is propagated from the _body_ (and we don't have the body style when computing the root style for obvious reasons, you need the root style for the `<body>` to inherit from).

I tracked that bit of code down through blame. Reasoning for our behavior is here:

 * https://bugzilla.mozilla.org/show_bug.cgi?id=645642#c22

Maybe the spec didn't say anything about the ICB back then? I think making it compute to start is the most reasonable thing FWIW.

**Comment by zcorpan** [comment]
A third way to resolve my objection is to specify what Gecko does and get sign-off from at least one of WebKit and Chromium that they want to match Gecko.

**Comment by fantasai** [comment]
>  I think making it compute to start is the most reasonable thing FWIW.

I think the problem with that is that `match-parent` everywhere else computes to an absolute side, and doesn't change sides as it inherits through descendants. I think it's better for it to compute to one of 'left' or 'right', therefore. If we can't make it compute against the ICB when specified on the root, I think making it compute against the root itself is fine. (It'll be a bit weird if someone sets a different writing mode on BODY, but they shouldn't be doing that anyway, they should be setting dir on the root. And who sets match-parent on the root anyway.)

If that's unacceptable then I'd rather go with the Blink/WebKit behavior than Firefox, because at least it inherits as an absolute alignment, and having it resolve against the default directionality (LTR) at least has some kind of logic to it.

**Comment by nt1m** [comment]
Chromium seems to match Firefox's behavior of using `start` now. I'm working on fixing this in WebKit, and I'm not sure what the intended resolution is, so I'm planning to follow Firefox/Chrome here for interop. If this changes, I'm happy to change accordingly.

**Comment by nt1m** [comment]
I've implemented this in WebKit to return `start`: https://github.com/WebKit/WebKit/commit/faf2d5cc3bac6c4a3bdebaa3f6d0c6c8d5e8b4db
