### ISSUE TITLE
[css-scoping] Light-DOM "slots" (donut holes within donuts)

### ISSUE THREAD

**Issue by nolanlawson** [w3c/csswg-drafts#6574]
To motivate this discussion, I'd like to quote [the CSS Scoping explainer](https://css.oddbird.net/scope/explainer/):

> Existing tools would still be able to provide syntax sugar for single-file components -- automatically generating the from/to clauses -- but move the primary functionality into CSS.

As a framework author (Lightning Web Components in my case), I totally agree with this goal! We're looking into light-DOM style scoping, and `@scope` as a potential solution. It would be great if frameworks like Vue and Svelte could also migrate their existing solutions to use `@scope` under the hood. So this issue is about a potential gap between [the CSS Scoping proposal](https://drafts.csswg.org/css-scoping-2/) and existing solutions.

In [Vue](https://v3.vuejs.org/guide/component-slots.html) and [Svelte](https://svelte.dev/docs#slot) (as well as other frameworks), it's possible to have light-DOM "slots," which work similar to `<slot>` in shadow DOM. If I understand the proposal, though, it doesn't handle this scenario.

Consider [this example](https://svelte.dev/repl/a86aeb7609fd49f6af927fa7704ab469?version=3.42.4) (using Svelte, although other frameworks would also apply):

```svelte
<!-- Outer.svelte -->
<div>Outer</div>
<Inner>
  <div>Outer (slotted)</div>
</Inner>
<div>Outer</div>
<style>
  div { color: blue; }
</style>
```

```svelte
<!-- Inner.svelte -->
<div>
  <div>Inner</div>
  <slot></slot>
  <div>Inner</div>
</div>
<style>
  div { color: red; }
</style>
```

This would render:

```html
<div>Outer</div>             <!-- blue -->
<div>
  <div>Inner</div>           <!-- red -->
  <div>Outer (slotted)</div> <!-- blue -->
  <div>Inner</div>           <!-- red -->
</div>
<div>Outer</div>             <!-- blue -->
```

In this case, styles defined in `Outer` should apply both to the "outer" elements as well as the element slotted into the `Inner` component. But the following rule would not work:

```css
@scope (.outer) to (.inner) {
  div { color: blue; }
}
```

The rule would not apply to `<div>Outer (slotted)</div>`, as it's under the lower scope boundary (`.inner`).

Note that I'm assuming that the framework is generating the classes `outer` and `inner` for scoping, e.g.:

```html
<div class="outer">Outer</div>
<div class="inner">
  <div>Inner</div>
  <div class="outer">Outer (slotted)</div>
  <div>Inner</div>
</div>
<div class="outer">Outer</div>
```

Since frameworks will be generating the upper and lower scope boundary selectors, a possible workaround is to generate as many scopes as necessary to handle the "donut holes within donuts" (or [Timbits](https://company.timhortons.com/us/en/menu/timbits.php) if you're Canadian) – with potentially infinite recursion, since slotted content can contain other slottable components. However, this would get tedious, as it requires duplicating CSS rules:

```css
@scope (.outer) to (.inner) {
  div { color: blue; }
}
@scope (.outer-slot-1-start) to (.outer-slot-1-end) {
  div { color: blue; }
}
@scope (.outer-slot-2-start) to (.outer-slot-2-end) {
  div { color: blue; }
}
/* etc. */
```

One potential fix could be to allow multiple `@scope`s to close over the same stylesheet:

```css
@scope (.outer) to (.inner), 
@scope (.outer-slot-1-start) to (.outer-slot-1-end), 
@scope (.outer-slot-2-start) to (.outer-slot-2-end),
/* etc. */ {
  div { color: blue; }
}
```

Another potential fix is to have the spec clarify whether scopes are recursive, e.g.:

```html
<style>
  @scope (.outer) to (.inner) {
    h1 { color: blue; }
  }
</style>
<div class="outer">
  <div class="inner">
    <div class="outer">
      <h1>Blue?</h1>
      <div class="inner"></div>
    </div>
  </div>
</div>
```

Recursive scopes get tricky, though, for selectors that cross the lower boundary. Consider [this example](https://svelte.dev/repl/06beafe73fb145a1bd989768dc7477d0?version=3.42.4) (using Svelte again):

```svelte
<!-- App.svelte -->
<div class="red">
  <Slottable>
    <div>Red</div>
  </Slottable>
</div>
<div class="blue">
  <Slottable>
    <div>Blue</div>
  </Slottable>
</div>
<style>
  .red div { color: red; }
  .blue div { color: blue; }
</style>
```

```svelte
<!-- Slottable.svelte -->
<div class="slottable">
  <slot></slot>
</div>
```

(Credit to @pmdartus for the example.)

As far as I can tell, it would not be possible to use `@scope` to reproduce the effect here, because the descendant selectors `.red div` and `.blue div` each cross the lower boundary. ("Red" and "blue" are maybe bad examples – you can imagine dark mode vs light mode, LTR vs RTL, etc.)

I'm not sure how common this pattern is, or if the spec can be changed to accommodate it. But in any case, it is something that frameworks like Vue and Svelte would have to consider when migrating to `@scope`, since it's currently supported in their implementations.

**Comment by mirisuzanne** [comment]
The spec already works in the way you describe as "recursive". A single scope description (`<<scope-start>>` and optional `<<scope-end>>` selectors) will create **multiple nested scopes on the page**. For every element that is matched by the "from clause" (`<<scope-start>>`), that element becomes the root `:scope` for it's own subtree, which continues until any lower boundaries are encountered. So, if the framework is generating classes in the way you describe:

```html
<div class="outer">Outer</div>
<div class="inner">
  <div>Inner</div>
  <div class="outer">Outer (slotted)</div>
  <div>Inner</div>
</div>
<div class="outer">Outer</div>
```

There are three "outer" scopes created, one for each instance of the `.outer` class, and each scope applies to itself and any descendants, until the `.inner` class is reached _from that starting point_. 

Currently, the spec _does not include_ any way for scoped selectors to "cross the lower boundary". The boundary is there to prevent exactly that behavior, so selectors that are meant to apply more deeply should not be in a scope with lower boundaries. In that case you would want a second scope with the same root, but without lower boundaries. Unlike most tools, my proposal does not impose a single-scope-per-dom-fragment. So it may be true that the framework wants to scope some selectors differently from others -- some with and some without lower boundaries.

---

This does raise a slightly different issue that I think we need to clarify. It might be a mistake for the spec to say that `:scope` is prepended as an ancestor to scoped selectors, unless otherwise used in the selector. The difference being:

```css
@scope (.my-scope) {
  .select { … }
}
```

Does this behave like…
1. `.my-scope .select` -- only selecting nested instances (current spec)
2. `.my-scope.select` as well as `.my-scope .select` -- selecting any match that is in-scope, including the scope root (my initial intent)

That becomes important for e.g. `.red div` in this resulting html:

```html
<div class="scope red">
  <div class="slot">
    <p class="scope">Red</p>
  </div>
</div>
```

Then:

```css
@scope (.scope) to (.slot) {
  .red p {
    /* not a match if we assume ":scope .red p" (option 1) */
    /* matched if we allow any ".red p" that is also in a ".scope" context (option 2) */
  }
}
```

**Comment by nolanlawson** [comment]
Thank you for the clarification. It wasn't clear to me from reading the spec that scopes are recursive. If they are, then that solves "recursive donuts" quite nicely!

As for the second point you raise, I agree that option 2 would allow for `.red p` to work. This is actually what I meant by "crossing the lower boundary," i.e. the `.red` is in the donut, and the `p` is in the donut hole inside the donut (there is a lower boundary between the two).

I think if option 2 were in the spec, then frameworks like Vue and Svelte would have a smoother upgrade path to `@scope`. I'm not even sure they could emulate their current `.red p` behavior without that change. (Unless they identify and parse descendant selectors and generate new selectors based on those, e.g. `.red:scope p:scope`… Possible, but messy.)

**Comment by tabatkins** [comment]
> This does raise a slightly different issue that I think we need to clarify. It might be a mistake for the spec to say that :scope is prepended as an ancestor to scoped selectors, unless otherwise used in the selector. The difference being:

The right way to handle this is to just say that selectors within a @scope block are [scoped](https://drafts.csswg.org/selectors/#scoping) to the elements matched by the upper-boundary selector (plus the additional restriction that they don't match things past a lower-boundary selector). No need to talk about modifying any selectors; the scoping concept does what we need already and with greater functionality, since you can, if needed, match earlier parts of the selector to elements outside of the scope (or prevent that, by explicitly using `:scope` in your selector).

----

Tangent: we might want to fold the lower-boundary concept into the definition of "scoped" so you don't need to do any hacking of the existing concept.

**Comment by mirisuzanne** [comment]
@tabatkins Yeah, that's how I had it specified to begin with, and the change was a bad idea. I'll revert that in the port over to cascade 6. Since the definition of scoped selectors are in a different (selector) spec, I may hold off on that change until we have FPWD approval on the basics?

**Comment by mirisuzanne** [comment]
This is fixed in the updated draft: https://drafts.csswg.org/css-cascade-6/#scoped-styles
