### ISSUE TITLE
[css-fonts] Remove `[supports <font-technology>#]?)]?` from `src:` descriptor?

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#6635]
After discussions in #6520 and #6613, can we clarify whether we still want to have the `[supports <font-technology>#]?)]?` extension syntax in the `src:` descriptor? I believe no engine has shipped this yet. My understanding from [our last conversation on the topic](https://github.com/w3c/csswg-drafts/issues/6520#issuecomment-920187550) was that there seems to be a preference for removing it in favor of the new `font-technology()` conditional function?

@svgeesus @fantasai

**Comment by LeaVerou** [comment]
Yes, absolutely. Having *both* the original microsyntax *and* the feature query is probably the worst of both worlds.

**Comment by svgeesus** [comment]
I was willing to take a shot at putting the same syntax as is used in `font-technology()` into `@font-face src` as suggested on the call by @fantasai, just to see how it looks. Hence #6621 

But I don't think this is a good direction, because the comment about proliferating microsyntaxes from the TAG still stands and the simplification is not huge - it replaces `()` with `-`.

So my preference would be to remove the whole `supports()` from `src`.

But _after_ I have copied out the various references from Fonts 4 which say what all those technologies actually mean :)

**Comment by svgeesus** [comment]
The technology() function has been added to the src descriptor, defined in CSS Fonts 4: [11.1. Font technologies](https://drafts.csswg.org/css-fonts-4/#font-technology-definitions) and used in CSS Fonts 4: [4.3.1. Parsing the src descriptor](https://drafts.csswg.org/css-fonts-4/#font-face-src-parsing)

And an equivalent font-technology() function is now added to `@supports`, defined in CSS Conditional 4: [2. Extensions to the @supports rule](https://drafts.csswg.org/css-conditional-4/#at-supports-ext) which links to the definitions in CSS Fonts 4
