### ISSUE TITLE
[css-color] Add OKLab, OKLCH

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6642]
For the background and explanation of _why_ to add this feature, please see [this Color Workshop presentation](https://www.w3.org/Graphics/Color/Workshop/slides/talk/lilley) which has a video presentation, plus associated slides and transcript. You can just skim the slides/transcript if you are pressed for time.

Having done so, and given the rationale presented, the specific proposal is to add [OKLab](https://bottosson.github.io/posts/oklab/) as follows: _Edit: items re-ordered so highest priority is first._

**CSS Color 4**

1.  in the gamut mapping section, require gamut reduction to use OKLCH chroma reduction and deltaE OK, rather than CIE LCH chroma reduction and deltaE 2000. This is both better _and_ faster. _If we don't do this, I am not confident of being able to write a satisfactory gamut mapping section in CSS Color 4._ See [examples below](https://github.com/w3c/csswg-drafts/issues/6642#issuecomment-942343016)
2. in the interpolation section, for non-legacy color formats, if the host syntax does not specify a colorspace, change `lab` to `oklab` as the default. _If we don't do this, color interpolation in gradients, animations and transitions will not be as good, and will sometimes give surprising hue shifts._
3.  add `oklab()` and `oklch()` (as well as the existing `lab()` and `lch()` which are still useful) and add their implementation to the sample code. _Not doing this means we have a colorspace of proven usefulness, implemented inside the browser, but we deny users access to it._

**CSS Color 5**

4. add `oklab` and `oklch` as [defined color spaces](https://www.w3.org/TR/css-color-5/#color-spaces) which can be used in `color-mix()`. Depends on 3.
5. add `oklab()` and `oklch()`  to Relative Color Syntax. Depends on 3.

@argyleink @una @tabatkins @LeaVerou

**Comment by svgeesus** [comment]
Note - the gamut mapping section does not yet exist, because gamut mapping in CIE LCH gave unacceptable results in the 270-330 degree hue range and also because deltaE 2000 is complex, but is needed for good results and deltaE 76 is fast but not good enough.

Using OKLCH and deltaEOK (which is the simple root-rum-of-squares) gives better results and is computationally simple.

**Comment by argyleink** [comment]
lgtm, nice attention to detail

**Comment by facelessuser** [comment]
Curious, would it use the new lightness discussed here? https://bottosson.github.io/posts/colorpicker/#intermission---a-new-lightness-estimate-for-oklab Or would it be based on the original Oklab work that doesn't adjust the lightness?

**Comment by svgeesus** [comment]
The new Lr lightness estimator brings in a dependency on viewing conditions, which the original OK L did not have; and which is an advantage of the original OK L especially if it allows extension to HDR or at least EDR. Lr also adds a little computational complexity.

I would like to examine it some more and also see how it impacts deltaE, but my initial impression is to stick with the original OK L. I'm very open to thoughts  on which would be the better option though.

**Comment by facelessuser** [comment]
> I would like to examine it some more and also see how it impacts deltaE, but my initial impression is to stick with the original OK L. I'm very open to thoughts on which would be the better option though.

Makes sense. I've only played with Lr to experiment with Okhsl and Okhsv, but use it in no other way. So there may be good reasons to avoid it if using it for distancing. I also hadn't thought of implications in regards to HDR. Something to experiment with though.

**Comment by tabatkins** [comment]
I quickly read thru the slides, and didn't catch this detail - can you elaborate on why we'd want to add these *in addition to* the existing lab()/lch(), rather than just changing those functions to use the OKLab space? Is there a good reason to keep the existing Lab functions?

**Comment by svgeesus** [comment]
>  why we'd want to add these in addition to the existing lab()/lch(), rather than just changing those functions to use the OKLab space? Is there a good reason to keep the existing Lab functions?

Good question, and the main reason I suggest keeping them around is because there is lots of hardware (instrumentation, like spectrophotometers) and software which generates Lab (or LCH, or both) values.  The secondary reason is that Lab and LCH have decades of user experience with them, while OKLab/OKLCH have less than a year.

So:

- to _specify_ a color, people can continue to use `lab()` and `lch()` because that is convenient for them. They can read out a value from Photoshop or Krita or whatever and use it directly. In much the same way they can continue to use `a98rgb()` despite `display-p3` being a more popular choice nowadays. 
- for general interpolation, if the host syntax doesn't specify, then the default changes from `Lab` to `oklab` because that will generally give better results; but you can still get `lab` if you want it, by specifying explicitly. 
- for gamut mapping, we just go straight to `oklch` because it is strictly better.

**Comment by tabatkins** [comment]
My issue is just that, given a choice between "lab" and "oklab", where the two look practically identical in most cases, people will naturally reach for "lab". We should bless the shortest, most convenient names with the most preferred syntaxes, even if we allow other types in other ways. (And in particular, we've accidentally set a precedent of all the specialized color functions have three-letter names. That probably can't persist forever, but for now, at least, "oklab" would join "color" as looking a little out-of-place and possibly "advanced".

Presumably we'd be able to offer the old Lab via `color()`? (Not LCH, tho.)

**Comment by Crissov** [comment]
Three letters you say? 

- `oklab` => `okl(<percentage> <number> <number>)`
- `oklch` => `okl(<percentage> <percentage> <angle>)`

But this idea was already dismissed for `cie()`.

**Comment by svgeesus** [comment]
> we've accidentally set a precedent of all the specialized color functions have three-letter names

I don't think any precedent has been set.

**Comment by facelessuser** [comment]
So, I am curious. It seems there is talk about using chroma reduction using Oklch for gamut mapping/reduction. I was playing around with this and was noticing some interesting things when gamut mapping using this method. Granted, maybe I'm doing something wrong here. This is based on the same algorithm used in color.js for Lch chroma and using the currently specified ∆Eok in that library.

When using something like display-p3, things get mapped very similar as they do with Lch vs Oklch, granted I think their blue range is very similar. But when using something like rec2020 which has a wider blue range, the mapping gets dull blues. (oklch chroma reduction on top).

<img width="1208" alt="Screen Shot 2021-09-29 at 7 16 57 AM" src="https://user-images.githubusercontent.com/1055125/135276330-06eeeb21-95cf-4f50-858c-d75c9fd89972.png">

This doesn't happen as much with greens and lesser with reds. Now granted there doesn't seem to be an official algorithm posted yet, and so I'm more curious if all these edge cases have been evaluated. Maybe the actual algorithm that is to be used compensates for this. I'm more curious if it improves in some places, but lesser in others, or if there is a better algorithm (different from the CIELCH one used on colorjs.io) that is planned to be used that works well with Oklch?

It's possible I'm just not implementing correctly, and in that case, I will wait patiently to better understand how the reduction is actually done, or keep plugging away to see what I'm doing wrong 🙂.

**Comment by svgeesus** [comment]
Thanks for investigating. Any chance you could post your test code?
In the diagram, are the colors being displayed in sRGB? Is it just the portion of the line from neutral to the sRGB gamut boundary, being displayed? (so Rec2020 blue to sRGB gamut boundary is not on that diagram)? It would be good to know what colors are at the boundary, for the two methods.

**Comment by facelessuser** [comment]
Yep, let me throw something together publicly that you can play around with.

**Comment by svgeesus** [comment]
> Having lab() be OKLab, and letting people still access Lab with color(cielab, ...) would enable people to have access to both when needed, but give authors the more preferable functionality with the easier syntax.

oof. That would be super confusing, surely.

However, renaming `lab()` to `cielab()` and `lch()` to `cielch()` would be doable, and more self-describing, and would make `oklab()` the shorter one. I guess. (I'm not a fan of bikeshedding churn, which hurts early adopters).

**Comment by facelessuser** [comment]
So, here is a link to a working example with code. You can edit it and play around with it: https://facelessuser.github.io/coloraide/playground/?source=https%3A%2F%2Fgist.githubusercontent.com%2Ffacelessuser%2F26ff61052f1e4a180d2f98a499d08595%2Fraw%2F454c4a9911e626e537f184b281f51382e83025aa%2Fokfit.py

Basically, I am just interpolating between black and blue in the rec2020 space. Then I convert it to sRGB and fit it in that space and display it directly.

I scale the ∆Eok to by 100 as the difference between black and white is ~0 - 1 and ∆E2000 is ~0-100. I've done it without the scaling, adjusting the limits and such, and the results are basically the same. It seems green starts getting mixed in as chroma reduces.

Again. Maybe there are some assumptions here that just aren't right. This is the exact same algorithm used for the CIELCH fitting.

**Comment by LeaVerou** [comment]
I have been debating this with myself for a good while, hence the lack of comment.

I *did* watch @svgeesus' talk (and I *really* recommend watching it to anyone who wants to have an opinion on this), and I do agree there are significant advantages in Oklab over Lab. However, Lab has been established for 45 years. It has a ton of tooling around it. It has drawbacks, yes, but those are widely studied. Same as all the color formats currently in CSS, they all have drawbacks, but are all old and established, and their drawbacks studied and known. Oklab on the other hand is very new. It has not yet been fully explored, and it has almost no tooling that supports it. Its advantages are known, but its drawbacks are still being researched. It seems a little premature to add it to CSS, especially as a named function.

As a secondary point, we need to decide when we add things as a named function and when as a `color()` keyword. Right now we have both, and some color spaces can only be expressed via `color()` and others via named functions. From an author point of view, the distinction is unclear. The [spec](https://drafts.csswg.org/css-color-4/#icc-colors) lists `color()` as "Profiled, device dependent colors". Does that mean that any color space we add with a restricted gamut is under `color()` and anything else is not? 

I disagree that authors will always reach for the shortest syntax. Firstly, a lot of the time colors are reused via variables, not re-specified. Secondly, if that were true, `#RGB` would be the most popular color syntax, which is not the case.

One issue with Oklab is that it uses different coordinates than Lab, namely 0-1 ranges instead of 0-100. If we do add such a syntax in CSS, I wonder if there is value in trying to harmonize the two a little.

**Comment by Crissov** [comment]
If Tab is saying that values scaled, in external specs, from 0.0 to 1.0 or 0 to 100 should, in CSS,  preferably be expressed as `<percentage>`, I wholeheartedly agree. 

Alternative suggestion to renaming `lab()` and `lch()`: Ditch `color()` in favor of established functional notations with known parameters and introduce the (now optional) colorspace identifier to them:

~~~~ abnf 
// <ident> defaults to "srgb":

rgb( [<colorspace>,]? <channel> <channel> <channel> [/ <opacity>]? )

hsl( [<colorspace>,]? <hue> <saturation> <lightness> [/ <opacity>]? )

hwb( [<colorspace>,]? <hue> <channel> <channel> [/ <opacity>]? )

// <ident> defaults to either "cie1976" or "ok"

lab( [<colorspace>,]? <lightness> <number> <number> [/ <opacity>]? )

lch( [<colorspace>,]? <lightness> <chroma> <hue> [/ <opacity>]? )

// components

<colorspace> = <ident> | <dashed-ident>
<channel>    = <percentage> | <integer[0, 255]>
<hue>        = <angle> | <number[0, 360]>
<saturation>, 
<chroma>     = <percentage>
<lightness>  = <percentage> | <number[0, 100]>
<opacity>    = <percentage> | <number[0.0, 1.0]>
~~~~

**Comment by facelessuser** [comment]
> I'm finding the same thing, and I think it is a consequence of better hue preservation in OKLCH. Mapping in CIE LH gives you a higher chroma, but preserves hue less well.

Ah, very interesting! Yes, those links do illustrate it pretty good.

**Comment by facelessuser** [comment]
I've mentioned this elsewhere, but maybe it will spark a conversation here.

My one issue is that the provided XYZ matrix assumes an XYZ -> Linear sRGB transfer matrix that doesn't align with what is actually suggested for sRGB in the CSS spec. Since the Oklab matrix is essentially a transform of, XYZ D65 -> Linear sRGB -> LMS, this does introduce some noise only because it is assuming a different XYZ -> Linear sRGB matrix than what is specified in the CSS spec.

If converting from XYZ  using the matrix specified in https://bottosson.github.io/posts/oklab/#converting-from-xyz-to-oklab and comparing that to using the CSS XYZ -> Linear sRGB conversion and then using the Linear sRGB to Oklab transform as specified here: https://bottosson.github.io/posts/oklab/#converting-from-linear-srgb-to-oklab, you will get different results.

In short, using the XYZ matrix as specified by the Oklab article assumes the white point that he used, but CSS uses a different white point, so this introduces noise. If the conversion was done from Linear sRGB, this noise is reduced.

Or you can just calculate the XYZ matrix using your own XYZ -> sRGB Linear matrix.

Assuming the XYZ -> Linear sRGB transfer that is specified in the CSS docs:

```
        [
		[  3.2409699419045226,  -1.537383177570094,   -0.4986107602930034  ],
		[ -0.9692436362808796,   1.8759675015077202,   0.04155505740717559 ],
		[  0.05563007969699366, -0.20397695888897652,  1.0569715142428786  ]
	]
```

The Oklab matrices below would be as follows which would reduce the noise.

```
===== XYZ D65 Linear -> lms =====
[[ 0.8190224432164319    0.3619062562801221   -0.12887378261216414 ]
 [ 0.0329836671980271    0.9292868468965546    0.03614466816999844 ]
 [ 0.048177199566046255  0.26423952494422764   0.6335478258136937  ]]
===== lms -> XYZ D65 =====
[[ 1.2268798733741557  -0.5578149965554813   0.28139105017721583]
 [-0.04057576262431372  1.1122868293970594  -0.07171106666151701]
 [-0.07637294974672142 -0.4214933239627914   1.5869240244272418 ]]
```

**Comment by svgeesus** [comment]
> In short, using the XYZ matrix as specified by the Oklab article assumes the white point that he used, but CSS uses a different white point, so this introduces noise. If the conversion was done from Linear sRGB, this noise is reduced.

Thanks! I tested it out and got much better results on neutrals (zeroes to 8dp).

Updated sample code (and also color.js)

**Comment by facelessuser** [comment]
Sounds good, glad I could help!

**Comment by bottosson** [comment]
Exciting stuff! This would certainly increase the reach of Oklab significantly. Let me know if I can be of assistance in any way.

One thing to discuss is that I've been considering making a second revision of Oklab for a few reasons. The things I'm considering addressing are:

1. Switching D65 whitepoint variant to the four-digit x,y D65 whitepoint.
2. Changing the definition of the M1 matrix so that the whitepoint is exact and not dependent on the rounding of the M1 matrix, instead limiting accuracy only by the precision of the computations.
3. Adjust the scaling of a&b to more accurately predict color distances. By more rigorously deriving the scale higher accuracy of color distance predictions could be achieved. This wouldn't affect interpolation, hue predictions and lightness predictions, just the scaling of a,b and C.

1) and 2) I am fairly convinced are good ideas, that only minimally change Oklab and correct minor issues in the current definition. 3) I am less certain about, since it would make the resulting Oklab values incompatible and it has already seen somewhat widespread adoption. On the other hand it is mostly used for doing computations, not for communicating colors between applications, so the impact is a bit limited at least.

Do you have any thoughts around this? This would end up being the most significant usage of Oklab I think, so it makes sense to make sure it is fit for purpose!

Thanks!

**Comment by facelessuser** [comment]
@bottosson 

> * Switching D65 whitepoint variant to the four-digit x,y D65 whitepoint.
> * Changing the definition of the M1 matrix so that the whitepoint is exact and not dependent on the rounding of the M1 matrix, instead limiting accuracy only by the precision of the computations.

I  believe the most recent M1 matrix in the CSS spec no longer uses the M1 matrix from your article, but now uses a recalculated M1 based on the XYZ to Linear sRGB transfer function which is based on the 4 digit whitepoint now. Or are you referring to some other aspect of the M1 calculation that also should be changed?

**Comment by svgeesus** [comment]
@bottosson wrote

> Switching D65 whitepoint variant to the four-digit x,y D65 whitepoint.

I must admit that I already did this, in the sample code which is part of CSS Color 4. I had been troubled by the neutral colors non-zero Chroma in OKLCH, which was worst at white and thus likely due to whitepoint differences. It seems you had used the ASTM XYZ values, to 6 significant figures; while for the various predefined RGB spaces I was getting the best results with the 4-digit x,y values. 

@facelessuser posted in this thread explaining how to derive a new M1 based on your linear-srgb to LMS C++ code and my (well, the sRGB standard) XYZ to sRGB, so that is what I used and it means roundtripping is now excellent.

> Changing the definition of the M1 matrix so that the whitepoint is exact and not dependent on the rounding of the M1 matrix, instead limiting accuracy only by the precision of the computations.

Yes in general, rounding is a consistent source of problems and they compound.

> Adjust the scaling of a&b to more accurately predict color distances. By more rigorously deriving the scale higher accuracy of color distance predictions could be achieved. This wouldn't affect interpolation, hue predictions and lightness predictions, just the scaling of a,b and C.

That would be a breaking change but I would be interested to know more.

**Comment by svgeesus** [comment]
(re-opening so that more people will notice this valuable discussion)

**Comment by bottosson** [comment]
> The a and b plane is scaled so that around 50% gray the ratio of color differences along the lightness axis and the a and b plane is the same as the ratio for color differences predicted by CIEDE2000

To be clear, this statement captures my intent, but I think it isn't quite how Oklab as published ended up being. I've only recently realized this as I started to look more closely at color distance predictions.

> scaling based on some dataset of color pairs will depend on the distribution of mean chroma in that data set

This is in particularly true for small color distance datasets such as Combvd. For large scale distances this is less true, since there is less of a chroma compression effect.

More visually:

Small scale color distances show very strong elongation of spheres into ellipses:
![image](https://user-images.githubusercontent.com/1515602/137774058-56e1dfc0-a681-4f24-bf36-d310a2fc92db.png)

OSA-UCS dataset models larger color distances and has much less chroma compression.
![image](https://user-images.githubusercontent.com/1515602/137774082-e24950e6-522a-4922-b984-180b7326a944.png)

(It is also possible to much closer match the small color difference dataset as well, by introducing chroma compression, similar to what both CIEDE2000 and Ciecam02/16-UCS do, but that also adds quite a bit of complexity and assumptions on viewing conditions, this performs worse for tasks such as color interpolation)

**Comment by svgeesus** [comment]
Closing again as the edits have been made and discussion seems to have died down.

**Comment by Ptico** [comment]
Hi, small question out of curiosity, feel free to just ignore or delete it:

I'm an not a color expert, just an average web-developer, like, you know, 90% of those who use CSS daily. For almost 18 years in a web, I never ever seen a LAB or LCH in a production cycle, except some extremely rare cases of dealing with clunky printed brandbooks back in 2000s or the posts of some clever people on css-tricks. At the same time I've seen some pretty good adoption of HSL, because you don't need to be a Will Hunting to decipher on the fly that 100 100 50 is a toxic green or 360 50 30 is a color of the lipstick of your history teacher. 

Last couple of years, thanks to @LeaVerou and others, I also see a huge progress in an implementation of a good practices in a a11y area, including proper color contrasts. And here is new perceptually uniform color spaces in CSS: easy to maintain color contrast, create accessible palettes, happy days! Except the fact we now should bring back a solar powered Casio calculator back to the working table and deal with acceptable values or AB mixture.

So the question is: why we can't have an okhsl/okhsv for regular people who just want to add some color for their wordpress blog?

Thanks

**Comment by LeaVerou** [comment]
> because you don't need to be a Will Hunting to decipher on the fly that 100 100 50 is a toxic green or 360 50 30 is a color of the lipstick of your history teacher

Both LCH and OkLCH have this property, just with different ranges. If anything, they have this propertly *more* because you know that e.g. `lch(50% 60 30)` is medium lightness due to the 50% regardless of the rest of the values of the other coordinates. HSL does not provide this guarantee at all: `hsl(60 100% 50%)` is a very light color (`#ffff00`) and `hsl(240 100% 50%)` a very dark one (`#0000ff`) despite having the same lightness. That's the exact problem these new color spaces are trying to solve: making things *more* predictable.

> So the question is: oklab and oklch is great, but why we can't have an okhsl/okhsv for regular people who just want to add some color for their wordpress blog?

What would these do? How do you envision they'd work? (I'm not asking for implementation details, just trying to understand what it is you're asking for)

**Comment by Ptico** [comment]
> What would these do? How do you envision they'd work? (I'm not asking for implementation details, just trying to understand what it is you're asking for)

OkLAB have an accompanying color spaces named OkHSL and OkHSV (https://bottosson.github.io/posts/colorpicker/) which address an issue (human-friendliness) I'm talking about in exchange of some trade-offs. Which is good enough for most of the use-cases. I thought if we can have a traditional HSL in a CSS Color 3 and OkLAB in Color 4 it would be natural to have at least OkHSL at some point

**Comment by LeaVerou** [comment]
@Ptico Fascinating, I didn't know Bjorn also created OkHSL and OkHSV spaces. A shame they are also restricted to sRGB. Anyhow, you should open another issue so we can discuss this properly.

**Comment by svgeesus** [comment]
> And here is new perceptually uniform color spaces in CSS: easy to maintain color contrast, create accessible palettes, happy days! Except the fact we now should bring back a solar powered Casio calculator back to the working table and deal with acceptable values or AB mixture.

No you would just use an online tool, like everyone else.

**Comment by svgeesus** [comment]
> address an issue (human-friendliness) I'm talking about in exchange of some trade-offs. Which is good enough for most of the use-cases. 

The trade-offs are that they are no longer perceptually uniform, and that they are restricted to sRGB. These are very significant limitations; the former is the whole point of Oklab and the latter is deeply restricting when the Web has moved to display-p3 and is headed to Rec BT.2100.

**Comment by Ptico** [comment]
> No you would just use an online tool, like everyone else.

I know, I'm exaggerating a bit, but jokes aside: I tried all of them and had almost memetic experience I wish to forget

**Comment by facelessuser** [comment]
@JamesEggleton I'd love to see the work! One of the issues with the current matrices is that Oklab and OkLCh just don't get chroma as close to zero when colors are achromatic. That leads to messy results when assuming zero for chroma or zero for a and b in Oklab, especially as lightness increases. This also makes the hue have more influence in good conversions as chroma is not quite small enough to completely drown out its influence.

```py
>>> Color('white').convert('oklch', norm=False).set('hue', 0).set('chroma', 0).convert('srgb')[:]
[0.9999999610079292, 0.9999999999787738, 1.0000001063154036, 1.0]
```

But your matrices actually yield some pretty good results and have a "tightness" in the conversion that is more inline with the current Lab and LCh conversions:

```py
>>> Color('white').convert('oklch', norm=False).set('hue', 0).set('chroma', 0).convert('srgb')[:]
[1.0000000000000004, 0.9999999999999997, 0.9999999999999999, 1.0]
>>> Color('white').convert('lch', norm=False).set('hue', 0).set('chroma', 0).convert('srgb')[:]
[0.9999999999999999, 0.9999999999999999, 0.9999999999999997, 1.0]
```

**Comment by facelessuser** [comment]
It does seem like it gives some negative, nearly zero values:

```py
>>> Color('blue').convert('oklab').convert('srgb')[:]
[-1.4344081478157022e-15, 0.0, 0.9999999999999999, 1.0]
```

I'd be interested to see the original float 64 values and see how well it all calculates with and without rational numbers. Just having float 64 may make a huge difference. I sometimes find that when using rational numbers, unless all the bits in your system are using rational numbers, you can have stuff like this happen.

**Comment by JamesEggleton** [comment]
@facelessuser I'm happy to see you achieved decent results using these matrices. I'll clean up and share my workings as soon as I get a chunk of free time, hopefully in the next week or so...

**Comment by facelessuser** [comment]
Okay, I was more systematic and was able to get Okhsl/Okhsv working with higher precision matrices but only if using the newly calculated `LMStoOKLab` matrix. I was able to use the Okhsl/Okhsv notebook provided in the related blog to update the tuning and no longer get any of the issues I did previously. It even gave better conversions for these spaces as well.

When I added the newly calculated LMS matrix in addition to the Oklab matrix, it seems to throw things a little off (pushing blue further out of gamut as an example), so for now,  I'll probably stick with just the improved Oklab matrix until I can verify the LMS matrix. Considering how much better the calculations are with just the OKLAB matrix, I think the LMS matrix at slightly lower accuracy wasn't the driving force in bad chroma calculations.

```py
>>> Color('gray').convert('oklab')[:]
[0.5998708056221469, -5.551115123125783e-17, -5.551115123125783e-17, 1.0]
>>> Color('white').convert('oklab')[:]
[1.0, -2.7755575615628914e-16, 0.0, 1.0]
>>> Color('darkgray').convert('oklab')[:]
[0.7348085828066983, -1.1102230246251565e-16, -1.1102230246251565e-16, 1.0]
```

I do wonder if creating the matrices with rational numbers (which also I assume includes the white point) causes the calculation to be different as everywhere else in my code, the white point is applied with floating point math, which likely leads to a disparity in white points causing calculations to not be quite right. It's also very likely that the Okhsl/Okhsv algorithm just needs some more manual tuning at whatever extreme the new matrix puts it at. I'll look into this more once the work is posted.

Regardless, even with just the improved Oklab matrix, things are actually no worse than when including the LMS matrix. And great conversion back to sRGB:

```py
>>> Color('white').convert('oklab').convert('srgb')[:]
[0.9999999999999999, 0.9999999999999999, 0.9999999999999997, 1.0]
```

**Comment by jessestricker** [comment]
@JamesEggleton Did you find some time to publish your work yet? Looking forward to it! 🙂

**Comment by nex3** [comment]
What are considered the best set of XYZD65/LMS matrices to use now? The ones from https://github.com/w3c/csswg-drafts/issues/6642#issuecomment-1490068959 or the ones from https://github.com/color-js/color.js/pull/357?

**Comment by nex3** [comment]
What's the reasoning behind the differences between the spec's values and @JamesEggleton's?

**Comment by facelessuser** [comment]
There's no specific insight into exactly what was done with the James'. There was a claim to have a 64 bit version of the initial matrix of

```
[
    [0.77849780, 0.34399940, -0.12249720],
    [0.03303601, 0.93076195, 0.03620204],
    [0.05092917, 0.27933344, 0.66973739]
]
```

But it was never posted.  My personal interest was to see the approach and verify it. I had noticed an issue using Jame's matrices when applied to Okhsl as well, so I was hesitant to use them without being able to see the process and understand it more. I won't speculate as to exactly what the issue is, only that I had no further insight without being able to evaluate what was actually done. This, of course, does not specifically affect CSS as it does not currently use Okhsl, but it was a concern for me.

I make no claims on the correctness or incorrectness of what James provided. It is likely that there is absolutely nothing wrong with the approach and that Okhsl simply did not handle the 64 bit version of the XYZ_to_LMS portion of the algorithm.  

---

With that out of the way, I can give details as to what is done in Color.js and provide a reproducible example of how it was generated.

The problem with the Oklab matrices as previously defined is that they simply do not resolve `oklab(1 0 0)` to  LMS `[1, 1, 1]` in 64 bit. This is due to how the 32 bit matrices are applied in a 64 bit data type environment, which Color.js uses. Because of this, as lightness increases, achromatic values for `a` and `b` deviate further from zero. When trying to apply CSS logic for powerless values, a larger and larger threshold would need to be used as lightness increases.

CSS simply took the LMS_to_Oklab matrix (the forward transform) and generated the 64 bit inverse matrix for the reverse transform. The problem is that the forward transform does not give you `oklab(1 0 0)` == LMS `[1, 1, 1]` in a 64 bit environment.

It turns out the 32 bit inverse matrix does support `oklab(1 0 0)` == LMS `[1, 1, 1]`, so if you use reverse transform to generate the forward transform for LMS_to_Oklab, you resolve the disparity for achromatic values. You can further emit the reverse transform as 64 bit before inverting the matrix which cleaned up the results a bit more. That is all that was needed and all that was done.

These matrices also did not cause adverse effects when used in Okhsl.

You can recreate them yourself with this script: https://github.com/color-js/color.js/blob/main/scripts/oklab_matrix_maker.py. This makes the changes transparent.

**Comment by nex3** [comment]
Ah thanks, that's really helpful! I can re-run that with my own lossless numerics to get even more precise intermediate matrices.

**Comment by facelessuser** [comment]
Sure! Having something reproducible makes such things possible.
