### ISSUE TITLE
[css-selectors-4] [css-pseudo-elements-4] ::placeholder and :placeholder-shown should explicitly apply to textarea elements

### ISSUE THREAD

**Issue by astearns** [w3c/csswg-drafts#6669]
The MDN documentation for ::placeholder and :placeholder-shown mention that they apply to textarea and input elements:

https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder
https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown

The textarea element is not mentioned in either spec section for these:

https://drafts.csswg.org/css-pseudo/#placeholder-pseudo
https://drafts.csswg.org/selectors/#placeholder

As far as implementations go, ::placeholder appears to work with textareas, but :placeholder-shown has issues.

https://codepen.io/astearns/pen/zYzLaOL

In Mac Firefox, it looks like :placeholder-shown on textareas allows the same properties as ::placeholder (those limited to ::first-line), so you can’t do things like truncate the placeholder text with an ellipsis. In Chrome and Safari, it does not appear to work with textareas at all.

I suggest that we specify what MDN documents (both ::placeholder and :placeholder-shown should work with textarea). This would be specifying reality with regard to ::placeholder, and if that’s acceptable then :placeholder-shown should match.

**Comment by emilio** [comment]
> In Mac Firefox, it looks like :placeholder-shown on textareas allows the same properties as ::placeholder (those limited to ::first-line), so you can’t do things like truncate the placeholder text with an ellipsis. In Chrome and Safari, it does not appear to work with textareas at all.

`:placeholder-shown` is a pseudo-class, not a pseudo-element, so it accepts the same properties as any other selector, nothing specific to `::placeholder`. However `white-space: nowrap` on a textarea's placeholder does nothing, because of [this rule](https://searchfox.org/mozilla-central/rev/f62d42b1d98e67dc3da05d586f71103df02b8c4a/layout/style/res/forms.css#223). That comes from [this commit](https://hg.mozilla.org/mozilla-central/rev/0f28fd24bdf3) that changed it to be `!important`.

It seems that was done because of [implementation issues](https://bugzilla.mozilla.org/show_bug.cgi?id=737786#c33), so I don't think it should matter anymore, I'll try to lift this restriction.

**Comment by fantasai** [comment]
@astearns I don't think the CSS specs need any edits here, so let me know if we can close out this issue!

**Comment by astearns** [comment]
@fantasai I do not think it is clear in the CSS specs that these both have effects on textarea elements as well as input elements. I’d like both sections to at least mention the textarea element.

**Comment by fantasai** [comment]
@astearns I've added TEXTAREA to the example in Selectors 4 and copied it over into the Pseudo-Elements spec as well. Is this enough to close the issue?

**Comment by astearns** [comment]
Yes. Thanks!
