### ISSUE TITLE
[css-backgrounds] Are the rules for interactions of transforms and backgrounds on the root element what we want?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#6683]
In https://github.com/web-platform-tests/wpt/pull/30946 I just wrote some tests for backgrounds on the root element when the root element has a transform.  Both interoperability and conformance to the current specification are poor.  I think it's perhaps worth considering whether the specification says what we want it to say.

In particular, [the transforms spec says](https://www.w3.org/TR/css-transforms-1/#transform-rendering):

> Fixed backgrounds on the root element are affected by any transform specified for that element. For all other elements that are effected by a transform (i.e. have a transform applied to them, or to any of their ancestor elements), a value of fixed for the background-attachment property is treated as if it had a value of scroll. The computed value of background-attachment is not affected.

(Note there's some prose in the previous normative paragraph, prior to the example, about background-attachment fixed backgrounds, but that's actually more recent text that was added in #2185 as part of exporting a formal definition of containing block for all descendants, so it can be ignored here since it's not relevant to the transform property itself, thanks to the text I quoted above.)

Then, in general, the [backgrounds spec describes](https://www.w3.org/TR/css-backgrounds-3/#root-background) the background propagation of the root element to the canvas, and the background positioning area being determined by the root element's padding box.  While it's not completely clear whether this is affected by transforms or not, I think the implication of the current spec is that it is not affected by transforms, although I think it's possible to argue the opposite.

Thus my reading of the current specs is that transforms on the root should affect the root's background only when background-attachment is fixed.

However, what my tests found is that:
 * Chromium does the exact opposite of the current spec (honors transforms only when background-attachment is scroll)
 * Gecko never honors the transform
 * WebKit always honors the transform

The particular conclusion about what the spec currently says doesn't particularly make sense to me, and I wonder if it's something we should reconsider given the lack of interop and lack of conformance to the current spec.

**Comment by dholbert** [comment]
> In [web-platform-tests/wpt#30946](https://github.com/web-platform-tests/wpt/pull/30946) I just wrote some tests for backgrounds on the root element when the root element has a transform. Both interoperability and conformance to the current specification are poor. I think it's perhaps worth considering whether the specification says what we want it to say.

Note: separate from those pending tests, I think this issue is also the core of the differences-in-outcomes on these existing WPT tests (which happen to be in the compat2021 test suite, and all of which pass in Chromium but fail in other browsers):
https://wpt.fyi/results/css/css-transforms/transform-background-007.html
https://wpt.fyi/results/css/css-transforms/transform-background-008.html
https://wpt.fyi/results/css/css-transforms/transform-root-bg-001.html
https://wpt.fyi/results/css/css-transforms/transform-root-bg-002.html
https://wpt.fyi/results/css/css-transforms/transform-root-bg-003.html
https://wpt.fyi/results/css/css-transforms/transform-translate-background-001.html
https://wpt.fyi/results/css/css-transforms/transform-translate-background-002.html

(note that transform-translate-background-001.html and -002 are hitting some other behavior-differences as well, which I've got some notes on in https://bugzilla.mozilla.org/show_bug.cgi?id=1724459 )

**Comment by dholbert** [comment]
Sorry, I should've also added, in case it matters: for some of the WPT tests that I linked, there's a a transform specified on the root **but the background-image is specified on the `<body>`**, e.g. in
https://wpt.fyi/results/css/css-transforms/transform-background-007.html

vs. in others, the background-image is specified on the root, e.g. in
https://wpt.fyi/results/css/css-transforms/transform-background-008.html

(I'm not sure that makes a meaningful difference, since I think background-image gets propagated from the body and behaves essentially the same on body vs. root as a result.  But I wanted to call it out, since dbaron did specifically mention "backgrounds on the root element" as the thing-in-question here.)

**Comment by wangxianzhu** [comment]
I think Chrome's behavior is intentionally to conform to [the compositing spec](https://drafts.fxtf.org/compositing/#pagebackdrop) @chrishtr

Currently Chrome has a [bug](https://crbug.com/667006) about background-attachment:fixed with transforms.

**Comment by wangxianzhu** [comment]
Thought the compositing spec only says we should apply root element filters, masks, etc. on the root element group, it seems reasonable to also apply root element transform on backgrounds (regardless of attachment)

Also [the transform spec](https://www.w3.org/TR/css-transforms-1/#transform-rendering) has a note under the background-attachment:fixed paragraph:

> Note: If the root element is transformed, the transformation applies to the entire canvas, including any background specified for the root element. ...

**Comment by mattwoodrow** [comment]
When we revisit this, if transforming the background is ever the right thing to do, we should also specify in which coordinate space 'background-repeat: space' is resolved (and possibly other position properties).

**Comment by nt1m** [comment]
Can we discuss this at the next APAC call on October 5th?

**Comment by MrHBS** [comment]
Would be great if someone can do the edit.

**Comment by dbaron** [comment]
While writing spec edits, I noticed one other minor inconsistency that I'm going to consider editorial, because on [this testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Ahtml%20%7B%20transform%3A%20translate(50px%2C%2050px)%3B%20%7D%0Abody%20%7B%20background%3A%20url(https%3A%2F%2Fwww.w3.org%2FIcons%2Fw3c_home)%20fixed%3B%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20style%3D%22height%3A%201000px%22%3Ehello%3C%2Fdiv%3E) all of Chrome, Firefox, and Safari do the sensible thing rather than what a literal reading of the spec says.  Read literally, the spec says that the rule that `background-attachment: fixed` backgrounds become `scroll` instead when transforms are involved doesn't apply to *root* backgrounds that are propagated to the canvas, but it doesn't grant the same exception to `<body>` backgrounds that are propagated to the canvas.  This distinction seems wrong, and browsers interoperably ignore it, so I'm just going to fix it.

**Comment by techsin** [comment]
adding transform translate ruins background attachment fixed
