### ISSUE TITLE
[css-contain-3] Container Queries and pseudo elements

### ISSUE THREAD

**Issue by lilles** [w3c/csswg-drafts#6711]
How do we find the container for pseudo elements?

```html
<div id="outer" style="container-type: inline-size">
  <div id="inner" style="container-type: inline-size"></div>
</div>
```

```css
@container (min-width: 200px) {
  #inner::before {} /* is #inner or #outer the container? */
  #inner::after {} /* is #inner or #outer the container? */
  #inner::first-letter {} /* is #inner or #outer the container? */
  #outer::first-letter {} /* is #inner, #outer, or an ancestor of #outer the container? */
  #inner::first-line {} /* is #inner or #outer the container? */
  #outer::first-line {} /* is #inner, #outer, or an ancestor of #outer the container? */
}
```

More cases like ::marker and ::backdrop.

::slotted() and ::part() would match the same flat tree ancestor container as they would have when styled with normal selectors in their own tree scopes, right?

**Comment by mirisuzanne** [comment]
It seems to me as though the [tree-abiding pseudo-elements](https://www.w3.org/TR/css-pseudo-4/#treelike) should behave like any other element when finding their containers. That would mean both `#inner::before` and `#inner::after` are inside the `#inner` container. That would also cover `::marker`, `::placeholder`, and `::file-selector-button`.

My instinct was to treat the typographic pseudo-elements also as though they are nested inside a block - but as @tabatkins [pointed out on Twitter](https://twitter.com/tabatkins/status/1444017728101109760):

> This would expose details of where in the tree the non-tree-abiding pseudos are, which seems bad

(I think `::backdrop` is similarly not tree-abiding, but there's not much detail in the spec. I don't think there is any use for it responding to containers other than the viewport, since it's always full-screen.)

**Comment by lilles** [comment]
Tests based on having the originating element as the closest possible query container:

https://wpt.live/css/css-contain/container-queries/pseudo-elements-001.html
https://wpt.live/css/css-contain/container-queries/pseudo-elements-002.tentative-ref.html
https://wpt.live/css/css-contain/container-queries/pseudo-elements-002.tentative.html
https://wpt.live/css/css-contain/container-queries/pseudo-elements-003.tentative.html
https://wpt.live/css/css-contain/container-queries/top-layer-dialog-backdrop.html
https://wpt.live/css/css-contain/container-queries/top-layer-dialog-container.html
https://wpt.live/css/css-contain/container-queries/top-layer-dialog.html
https://wpt.live/css/css-contain/container-queries/top-layer-nested-dialog.html

**Comment by tabatkins** [comment]
Yes, just using the originating element seems to be the right answer. It matches the obvious intuition for tree-abiding pseudos, and provides an unambiguous answer for the non-abiding ones that doesn't expose implementation details we want to remain hidden.
