### ISSUE TITLE
[css-color-4] proposed breaking change: predefined XYZ is D65 adapted, not D50

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6722]
Originally raised in https://github.com/WICG/color-api/issues/24 and also related to https://github.com/w3c/csswg-drafts/issues/6061

Most RGB colorspaces use a D65 whitepoint. (The sole exception in CSS Color 4 is ProPhoto RGB, which uses D50; other examples include DCI-P3, which has a weird greenish white, and ACEScc which has a white similar to, but not the same as, D60).

In practice this means that most RGB to RGB conversions will proceed via CIE XYZ with a D65 whitepoint. In some cases, there will need to be chromatic adaptation, when the white points differ, because the user is assumed to be adapted to the reference white.

So internally, color conversion code will have various different **relative** XYZ spaces; the question becomes which one to expose to the user (by CSS syntax). 

Because most practical use of CIE Lab has a D50 white, at first I defined the white for XYZ in CSS to be D50 as well. 

This causes some issues (adaptation is needed) when:
- calculating WCAG 2.1 contrast, which assumes a D65 white
- using OKLab and OKLCH (which use a D65 white)
- creating uv chromaticity diagrams for most RGB spaces
- performing most calculations that one might want to do on XYZ in a Color object model
- HDR usage such as PQ Rec.2100 or Jzazbz will also need an **absolute** XYZ; in both those cases, D65

So in [WICG/color-api](https://github.com/WICG/color-api) I proposed that the exposed XYZ be relative, D65 adapted.

For consistency, this means CSS Color 4 should also change to use relative, D65 XYZ in the `color()` function.

This is a breaking change in that it affects any existing usage of `color(xyz ...)`. It does _not_ affect any other usage (such as `lab()` or `lch()`), other code or any other conversions, because all the various XYZ versions are still needed internally anyway. It only affects what is exposed and can be specified directly in XYZ.

Usage is effectively zero at this point (I just checked the [draft CSS Almanac 2021 crawl results](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=1420025896)) so the impacts are:

- slight inconvenience for WebKit and BFO Publisher maintainers
- change a few tests in WPT
- back out a WCAG 21 fix (re-adapt to D65) in color.js

@weinig @faceless2

**Comment by weinig** [comment]
@smfr What do you think? We just shipped support for this, so it's unlikely it is used anywhere, but if anyone adopts now, they are going to have slightly broken content. 

My slight personal preference would be to keep it at D50, not only because we have shipped, but also because it happens to match what CoreGraphics calls `kCGColorSpaceGenericXYZ`, but I will admit that is arbitrary and mostly irrelevant. 

When I was trying to learn about colorspaces about a year and a bit ago, the notion that XYZ came in two flavors (actually, as infinite flavors I guess, or as many valid white points as there are, but for my purposes, two, D50 and D65) and that there was a conversion between that needed to happen, was quite confusing. I think what made it so confusing was that many places simply referred to it as the XYZ colorspace, and didn't mention which whitepoint they meant (usually they meant the one corresponding to the colorspace they were converting from). If more sources had been a little more explicit and said what they meant, XYZ(D50) or XYZ(D65) I think I would have been less confused. 

That all leads me to think that perhaps a better solution is to just be even more specific here and add the whitepoint to the name (or maybe do something crazy like make xyz into a function that takes a whitepoint (e.g. `color(xyz(d50) ...)`).

**Comment by svgeesus** [comment]
I agree that it is confusing at first.

The thing is that our eyes have a built-in mechanism so that *white looks like white* under a fairly broad range of illuminants. The problem is that *all the other colors change too*. Color A no longer looks like color A.

And so, when white changes, we need to compute the **corresponding color** in other words, Color B, which looks like what Color A used to look like before the adaptive white point changed.

**Comment by svgeesus** [comment]
So, maybe go with @LeaVerou [suggestion](https://github.com/WICG/color-api/issues/24#issuecomment-893312899), then?

> There should definitely be a plain xyz, in both Color API and CSS, and it should refer to the same thing.
We should also expose the other one, either xyzD65 or xyzD50. No opinions about which one to go with for the plain xyz, I’ll defer to @svgeesus for that.

Allowing an optional whitepoint would be interesting, and for CSS Color 4 it just needs to be a string or an identifier; but in extensible APIs there needs to be a way to register a new whitepoint. Hmm. @LeaVerou ?

**Comment by svgeesus** [comment]
Color.js is also now updated, so people can play with the new syntax; for example in the [color converter](https://colorjs.io/apps/convert/?color=maroon&precision=6)

**Comment by svgeesus** [comment]
@smfr thanks for the confirmation!
