### ISSUE TITLE
[css-color] Support all existing (non-legacy?) formats in color()?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#6741]
Yes, I know there are unresolved issues wrt to representing polar coordinates in `color()` and we'd need to solve these first. Maybe by changing its grammar to be `[<number-percentage> | <angle> | none]+` instead of `[<number-percentage> | none]+`.

Why should we be able to represent all existing color formats through `color()`?

* Right now the distinction between which color formats have a dedicated function and which ones are specified via `color()` is murky. The spec describes `color()` as "Profiled, Device-dependent Colors", but also includes [the XYZ spaces](https://drafts.csswg.org/css-color-4/#valdef-color-xyz) there.
* There is no way for authors to parameterize the color space for colors not available in `color()` so that e.g. they can use OKLCH if that's supported or LCH if not.
* Even [_we_ are confused](https://github.com/w3c/csswg-drafts/issues/6642#issuecomment-929614506) about whether to add new color spaces in `color()` or as separate functions, imagine how difficult authors will find it to remember the distinction.

Reasons against doing this:
* Which serialization do we pick? The way we decided in #5825 was to drop `color(lab)`. If we adopt this proposal, we'd need to actually pick this time.

**Comment by Crissov** [comment]
I’m [repeating myself](https://github.com/w3c/csswg-drafts/issues/6642#issuecomment-936944553) here, but I’m now almost convinced that it would be a cleaner approach to add the color space identifier to existing color pseudo functions, e.g.: `rgb(prophoto, 10% 20% 30% / 40%)` for cartesian coordinates or `hsl(prophoto, 10deg 20% 30% / 40%)` for cylindrical coordinates.

**Comment by svgeesus** [comment]
Getting back to this and playing with the observable some more, the values [proposed by Lea](https://github.com/w3c/csswg-drafts/issues/6741#issuecomment-951934434) look workable to me.

Agenda+ to get implementer input and agreement to add these reference percentage ranges to the spec.

**Comment by tabatkins** [comment]
Ah, good, I updated Typed OM to reflect all the recent changes in Color 4, and ran across the xyz "numbers only, no percents" part of the grammar and was sad. I punted on it temporarily, so if this goes thru it'll mean I don't have to add extra complexity.

**Comment by svgeesus** [comment]
> the xyz "numbers only, no percents" part of the grammar and was sad.

Okay so `color(xyz-d65 0.9504  1.0000  1.0888)` would also be expressible as `color(xyz-d65 95.04%  100.00%  108.88%)`. That seems fine, since 0..1 and 0..100 ranges are both in common use.

**Comment by svgeesus** [comment]
For the call, to see the full proposal in one place, the percentages would be explicitly defined so that 0% to 100% maps as follows::

* `lab.L`: `[0, 100]`
* `lab.a`: `[-125, 125]`
* `lab.b`: `[-125, 125]` (a and b have the same range, for simplicity)
* `lch.c`: `[0, 150]`
* `oklab.L`: `[0, 1.0]`
* `oklab.a`: `[-0.4, 0.4]`
* `oklab.b`: `[-0.4, 0.4]` (see above re: a and b)
* `oklch.c`: `[0, 0.4]`
* `xyz`, `xyz-d50`, `xyz-d65`: `[0, 1.0]`
* predefined RGB: `[0, 1.0]` (not a change, but a clarification)

No-one mentioned hue as a percentage so it remains an angle, in degrees by default if no unit is given.

This gives useful ranges for percentages on all colors, roughly covering the `display-p3` gamut plus a bit, and should minimize the errors in implementations where something was either not divided by 100, or was and shouldn't be, etc (Safari and color.js and PostCSS all had these at various points).

It also means people can paste in `lab`/`lch`/`oklab`/`oklch` values from other software (which does not use percents) without getting an error and without having to remember if L is [0..1] or [0..100].

`lch(29% 66.5 327)` == `lch(29% 44.33% 327)` == `lch(29 66.5 327)` 
`oklch(58% 0.11 110)` == `oklch(58% 27.5% 110)` == `oklch(0.58 0.11 110)`
`color(xyz-d65 0.9504  1.0000  1.0888)`  == `color(xyz-d65 95.04%  100.00%  108.88%)`

**Comment by faceless2** [comment]
If I'm going to be picky, it feels odd to set the oklab values to +/- 0.4. Making them +/- 0.5 (so the total range is 1) feels a bit more natural and less likely to bite people, particularly as oklab/oklch are new and unfamiliar to most.

 For Lab/LCH, those seem fine - it's arbitrary of course.

A big +1 to making XYZ primaries percentages, as I had the same reaction as Tab when adding these.

**Comment by svgeesus** [comment]
Redirecting discussion back to original subject:

> Right now the distinction between which color formats have a dedicated function and which ones are specified via color() is murky. The spec describes color() as "Profiled, Device-dependent Colors", but also includes [the XYZ spaces](https://drafts.csswg.org/css-color-4/#valdef-color-xyz) there.

A little progress since the issue was first raised:

1. With the move of custom color spaces to CSS Color 5, the section is now entitled [10. Predefined Color Spaces](https://drafts.csswg.org/css-color-4/#predefined) which is not necessarily optimal, but is better
2. Again with that move, all the color spaces in that section are 3-component, rectilinear, [0,0,0] == black ones. (In CSS Color 4 that becomes _n_-dimensional but again with all zeroes == black).
3. CIE XYZ is, when you look at it carefully, a hyper-saturated primary RGB space. This is easier to see in an _x,y_ chromaticity diagram rather than a more modern _u,v_ one. Red (X) is at _x,y_=1,0; green(Y) is at _x,y_=1,0 while blue(Z) is at _x,y_=0.0

The other ones are opponent color spaces (neutral central axis with perceptual Lightness); `oklch` and 'lch`  aim at being fully orthogonal (`oklch` is rather better at that, by design) while `oklab` and `lab` are sort of half-way houses, `a` and `b` don't mean that much in isolation. True, negating a value gets the opponent color, but they are much better expressed in polar form as orthogonal Chroma and Hue.

**Comment by LeaVerou** [comment]
> Again with that move, all the color spaces in that section are 3-component, rectilinear, [0,0,0] == black ones. (In CSS Color 4 that becomes n-dimensional but again with all zeroes == black).

In CMYK (0,0,0,0) is white.

**Comment by svgeesus** [comment]
> In CMYK (0,0,0,0) is white.

/facepalm

**Comment by svgeesus** [comment]
Closing this old issue since the spec has changed a fair bit since the issue was first raised.

**Comment by danburzo** [comment]
Hi @svgeesus, just to make the conclusion explicit: unbound color spaces (that is `oklab`, `oklch`, `lab`, `lch`) are not available via the `color()` syntax in css-color-4. Is that correct?

**Comment by svgeesus** [comment]
Correct.
