### ISSUE TITLE
[css-values-4] Punt attr() and toggle() to Level 5

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6753]
Tab and I think it's time to start preparing css-values-4 for CR, as a lot of the stuff in here is already implemented (and shipped!). We think it would make sense, however, to cut ''attr()'' and ''toggle()'' and push them to Level 5. Agenda+ to ask about doing this.

**Comment by fantasai** [comment]
@Loirooriol No, we need that one to handle serialization of interpolation of transforms.

**Comment by SelenIT** [comment]
Given that `attr()` has been there since at least 2005 and keeps being deferred because of no implementation signal, shouldn’t it be reconsidered more deeply? The existing situation seems much like the lack of implementers’ interest. Perhaps the `attr()` function should forever stay in the string-only form as defined in CSS2.x, and for deriving typed values from attributes something new should be introduced instead, to avoid confusion and make experimenting/implementation easier?

**Comment by Crissov** [comment]
I don’t really disagree, but this idea was basically rejected in #3702.

**Comment by SebastianZ** [comment]
The question is how to get implementer interest because author interest is definitely there regarding its many use cases.

Sebastian
