### ISSUE TITLE
[css-position] Behaviour of semi-replaced elements.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#6789]
From: https://github.com/w3c/csswg-drafts/issues/6580#issuecomment-953174441

By @tabatkins 

> For buttons and inputs, behavior seems inconsistent across browsers; in particular, it seems WebKit just treats buttons (and inputs) like any other box, so seems like that would be a reasonable direction to go in given the other browsers are very inconsistent? In any case, should be a separate issue if we need to address anything in the spec.

Doing this breaks this particular WPT test:
https://wpt.fyi/results/html/rendering/widgets/button-layout/abspos.html

This was added in:
https://github.com/web-platform-tests/wpt/pull/14824
By @zcorpan , (primarily reviewed by @emilio )
https://github.com/whatwg/html/pull/4143
https://github.com/whatwg/html/issues/2948 (by @dholbert )
https://github.com/whatwg/html/issues/4081#issuecomment-429324630

etc.

Currently we (Blink) have different behaviour in the inline/block axis which we were about to fix (with zero insets, should still shrink-fit, instead of stretch).

**Comment by bfgeek** [comment]
More history:
https://bugs.chromium.org/p/chromium/issues/detail?id=281380

**Comment by bfgeek** [comment]
Example:
 https://www.software.hixie.ch/utilities/js/live-dom-viewer/saved/9793

**Comment by tabatkins** [comment]
> Doing this breaks this particular WPT test:

Well, it would fix it for Safari. ^_^

> Currently we (Blink) have different behaviour in the inline/block axis which we were about to fix (with zero insets, should still shrink-fit, instead of stretch).

I suppose I'd find it acceptable to have it shrink-fit in both axises (at least it would be consistent, rather than a new and weird behavior), but every divergence that buttons make from a standard inline-block is unfortunate.

**Comment by dholbert** [comment]
> <fantasai> iank_: I'm fine either way, but historically FF folks have been very strong in their opinion wrt shrink-to-fit

Clarifying this: I think we've mostly been arguing for something coherent/sensible, rather than arguing specifically for shrink-to-fit.  It just happened to be that shrink-to-fit seemed to be the sensible/spec-mandated behavior, at the time of those earlier discussions; but I don't think we're inherently opposed to stretching behavior.

I do want to be sure that we consider other related form controls (e.g. textarea, `<input type="image">`, etc.) as well. It looks like things are a bit all over the place right now -- e.g. for buttons, WebKit stretches in both axes (vs. Gecko/Chrome shrink in the inline axis).  But for `<input type="image">`, WebKit shrinks in both axes, Gecko stretches in both axes, and Chrome stretches in the block axis and shrinks in the inline axis.

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1740580 as a place to post a testcase with screenshots.
Here's my [testcase](https://bugzilla.mozilla.org/attachment.cgi?id=9250271), which has a variety of form controls with all the `inset` properties set to 3px, and with a green `outline` around the form control to highlight its final bounds.

Here are screenshots in the three major browser engines:
[screenshot in Firefox Nightly 96](https://bugzilla.mozilla.org/attachment.cgi?id=9250272)
[screenshot in Chrome dev 97](https://bugzilla.mozilla.org/attachment.cgi?id=9250273)
[screenshot in Safari 15.1](https://bugzilla.mozilla.org/attachment.cgi?id=9250274)

**Comment by dholbert** [comment]
Some observations:
 1. it's not as simple as "Safari stretches buttons in both axes". They do that for literal `<button>` but they don't for any other button-like element. (They shrink input type="button/reset/submit" in the block axis, and they shrink input type="image" in both axes.)
 2. Textfield-like elements are another related area where browsers disagree. Firefox does shrink-to-fit in both axes (except for `date` which we stretch in block axis); Chrome does shrink-to-fit in the inline axis only, and stretches in the block axis; Safari stretches in both axes.
 3. input type="range" has the same behavior across the three engines (fully shrink-to-fit in Firefox; shrink-to-fit in inline axis in Chrome, fully-stretched in Safari)
 4. All three browsers agree on shrink-to-fit for `<input>` with `type="color/checkbox/radio"`, and also for `<progress>`, and `<meter>`.
 5. All three browsers agree on stretching for `<label>` and `<fieldset>`, and we nearly-agree for `<output>` (Chrome shrinks in the inline axis for that one so it's not full agreement).

So: things are a bit of a mess, though (4) and (5) are the points of agreement.  Ideally I'd like to have a coherent and likely-to-be-web-compatible way forward here, and I'm not sure that the proposed change (stretching in both axes) is that, given that there are a handful of button-like elements that no browser stretches in both axes at this point.

**Comment by bfgeek** [comment]
@dholbert - I think your testcase can be slightly improved by adding:
```css
.abs { width: auto; height: auto; }
```

radio/checkboxes in Blink have some magic happening where they effectively set:
```css
width: 13px !important; height: 13px !important;
```
which is why that behaviour is observed.

With those explanations currently Blink stretches in the block-axis, and shrink-to-fit in the inline-axis everywhere - except for `<label>`, `<fieldset>` as discussed.

(5) - agree that can move to stretching in all axes for those three.

(4) - Is clouded by default UA styles I believe.

The results of above makes me think that'd it be safest to move to a shrink-to-fit behaviour in both axes (except for fieldset, label, output).
E.g. where Blink stretches in the block-axes there is at least one other engine which shrink-to-fit in the block-axis (with the exception of the regular button element).

**Comment by dholbert** [comment]
Thanks. Here's a variant of my earlier testcase, now with explicit `width:auto; height:auto` on the abspos elements:
https://bug1740580.bmoattachments.org/attachment.cgi?id=9250287

This change doesn't change the outcome much, though. The only differences from this change:
- It makes `<input type="color">` size the same as `<button>` (whatever that means for the given browser)
- In Chrome and Safari, it makes `progress` and `meter` stretch in both axes. (This makes them consistent with `<input type="range">` in Safari, though not in Chrome, since Chrome shrinks-to-fit `<input type="range">` in the inline axis.)

**Comment by dholbert** [comment]
I think I'm still neutral as to which is the best way forward here.

Argument in favor of stretching (aside from checkbox/radio):
- Essentially, every form-control has its inline size stretched in some browser, *and* has its block size stretched in some (possibly-different) browser.  The exceptions here are: checkbox/radio which interoperably refuse to stretch and so we could set them aside as special cases; and also `<input type='color'>`, `<progress>`, and `<range>`, which aren't really exceptions since they fully-stretch in Safari when styled with `width:auto;height:auto`.

Argument in favor of shrinking (aside from output/label/fieldset):
- The ~reverse of the above argument is nearly true but not quite. i.e. we can say that *nearly* every form control has its inline-size shrunk in some browser **and** has its block-size shrunk in some (possibly-different) browser, but there are more exceptions.  In particular, no browser does block-axis shrinking for `<button>`, or for `<input type="color" style='width:auto;height:auto">`, `<input type="date">`, or `<input type="file">`.

So, from a position of maximal paranoia, it's conceivable that there'd be webcompat fallout from changing to shrink-to-fit for `button` (for example) since no browser shrinks `button` in the block axis right now, so there could be content that assumes that `button` with `top:0;bottom:0` always stretches.

**Comment by dholbert** [comment]
All of which is to say: it feels like stretching would probably be the safest change here (from a webcompat perspective).

**Comment by bfgeek** [comment]
> All of which is to say: it feels like stretching would probably be the safest change here (from a webcompat perspective).

I'd be fine w/ that.

**Comment by bfgeek** [comment]
Opps - should probably have mentioned that we'll likely need to leave checkbox & radio buttons alone for the moment. But all browsers are currently consistent there. (and all likely apply an equivalent of a !important width/height property).

**Comment by dholbert** [comment]
> Opps - should probably have mentioned that we'll likely need to leave checkbox & radio buttons alone for the moment. But all browsers are currently consistent there. (and all likely apply an equivalent of a !important width/height property).

Right, those are the exception to this stretching.

(Minor correction: they don't seem to do this via something along the line of `!important` width/height; this testcase shows that authors can specify their own heights: `data:text/html,<input type="checkbox" style="width: 400px; height: 400px; outline: 3px solid orange">`.  But in any case, they are special in that they interoperably shrink-to-fit, and they're typically quite tiny, both of which mean it wouldn't make sense to stretch them.)

**Comment by zcorpan** [comment]
Does https://html.spec.whatwg.org/multipage/rendering.html#button-layout need changes? (This section should probably be moved to some CSS spec, but not sure where.)

**Comment by bfgeek** [comment]
> Does https://html.spec.whatwg.org/multipage/rendering.html#button-layout need changes? (This section should probably be moved to some CSS spec, but not sure where.)

I don't beleive this section needs immediate change. The button element is under "widgets" now - so pretty clear it isn't replaced, (and no mention of semi-replaced in that document). The change decided here makes it so there isn't any special behaviour for these widget elements.

**Comment by tabatkins** [comment]
We should adapt dholbert's test case into a reftest for this issue.

**Comment by dholbert** [comment]
I posted another testcase on the bug which is a slightly better reftest than the previous ones, and has a reference:
testcase: https://bugzilla.mozilla.org/attachment.cgi?id=9311171
reference: https://bugzilla.mozilla.org/attachment.cgi?id=9311172

Chrome *almost* matches the expectations here but they seem to have a subtle bug with one form control -- `<input type="image">` (the first item in the second row) has slightly different positioning of its contents for some reason. I'll file that as a Chrome bug in a sec.

**Comment by dholbert** [comment]
(I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1405560 for the Chromium mismatch that I noted. for `input type="image"`)

**Comment by fantasai** [comment]
Forgot to except input type=image from the note.
