### ISSUE TITLE
[css-display] Introduction

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#680]
1. I don't understand why an introduction is normative. That doesn't make much sense.
2. The introduction attempts to define "element" (which clashes with DOM), but that definition is only used in the introduction. I don't see how that helps implementations. And it also doesn't help specifications that need to link to the definition of element.

**Comment by fantasai** [comment]
The introduction is normative because we needed a normative definition of how elements, boxes, and fragments relate. It so happened that this text also served as a reasonable introduction to the Display module, so it was labelled as such.

The definition used in CSS is a bit more general than the one in the DOM, as CSS can in theory (and has, in the past, been used to) lay out documents formed by other object models. I can make this a non-exported definition, so that it doesn't clash with the auto-generation of other specs, though. Most CSS specs other than this one (and Selectors) don't need to refer to elements, since we mostly operate on boxes.

**Comment by fantasai** [comment]
Closing. Feel free to re-open if there's something specific you need fixed.
