### ISSUE TITLE
[css-color-5] Testable but untested sections

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6824]
- [x] [Mixing colors: the color-mix() function](https://drafts.csswg.org/css-color-5/#color-mix)

Has 2 simple tests, ~~both marked tentative~~ and a very comprehensive parsing test

 - [x] [Selecting the most contrasting color: the color-contrast() function](https://drafts.csswg.org/css-color-5/#colorcontrast)

Has some  tests. Spec examples would be a start.

 - [x] [Relative color syntax](https://drafts.csswg.org/css-color-5/#relative-colors)

Now has some tests

 - [x] [Custom color spaces](https://drafts.csswg.org/css-color-5/#custom-color)

 - [x] [Specifying a color profile: the @color-profile at-rule](https://drafts.csswg.org/css-color-5/#at-profile)

   - one simple test
  
 - [x] [CSS and print: using calibrated CMYK and other printed color spaces](https://drafts.csswg.org/css-color-5/#cal-cmyk)
   - [x] This section is primarily examples and explanation; it does not contain normative statements

 - [ ] [Device-dependent CMYK Colors: the device-cmyk() function](https://drafts.csswg.org/css-color-5/#device-cmyk)

Hard to test reliably, but at least an @supports test

 - [ ] [Resolving <color> Values](https://drafts.csswg.org/css-color-5/#resolving-color-values)

 - [x] [Serialization](https://drafts.csswg.org/css-color-5/#serial)

Has some tests, using computed value

**Comment by weinig** [comment]
I have a few for parsing and serialization and color-mixing I would be happy to convert to wpt and donate if you would find them helpful (some are being updated for the recent changes right now, so may be a bit out of date):

https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/css/parsing-color-contrast.html
https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/css/parsing-color-mix.html
https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/css/parsing-color-function.html
https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/css/parsing-relative-color-syntax.html
https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/css/parsing-lab-colors.html

My biggest concern is with floating point precision differences between browsers in some of them (since precision of component storage is only defined with a minimum bound among other issues).  

Let me know and I will make some time to get out a PR.

**Comment by svgeesus** [comment]
Please do add the rel=help pointing to the actual spec sections, though.

- [writing the test file](https://web-platform-tests.org/writing-tests/reftest-tutorial.html#writing-the-test-file)
- [CSS metadata](https://web-platform-tests.org/writing-tests/css-metadata.html)

So for example on [the `color-mix()` test](https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/css/parsing-color-mix.html) add

```html
<link rel="help" href="https://drafts.csswg.org/css-color-5/#color-mix"/>
```

**Comment by weinig** [comment]
> > among other issues).
> 
> Other issues?

I meant things like the precision of the color conversions themselves, for issues like how many digits of significance are used for the matrices, since the exact algorithms are not defined and floating point operations can introduce error with small differences. That said, I think there is far more benefit in having the tests now, and figuring out how to solve those than not.

**Comment by svgeesus** [comment]
Oh, I see. Yes, the general problem with floats and precision, especially cumulative roundoff error.

Agree it is far better to have good tests now and improve them over time, than perfect tests never.

**Comment by weinig** [comment]
Put up a few PRs:

- `color-mix()` - https://github.com/web-platform-tests/wpt/pull/31902
- `color-contrast()` - https://github.com/web-platform-tests/wpt/pull/31903
- `relative colors` - https://github.com/web-platform-tests/wpt/pull/31904

Also a few CSS Color 4 ones:
- reference tests for new colors - https://github.com/web-platform-tests/wpt/pull/31901
- parsing and serialization for new colors - https://github.com/web-platform-tests/wpt/pull/31905

**Comment by svgeesus** [comment]
These are all merged now except that @tabatkins asked for changes on RCS and I don't understand why. He comments about not producing integer values, yet [they are not required by spec](https://drafts.csswg.org/css-color-5/#serial-relative-color) because [serializing says](https://drafts.csswg.org/css-color-4/#serializing-color-function-values) that  [decimal values are allowed in `rgb()`](https://drafts.csswg.org/css-color-4/#resolving-sRGB-values)

**Comment by tabatkins** [comment]
It appears you understand my comments exactly backwards. ^_^ Sam's tests were testing serialization of %s like 10% or 25%, which produce non-integer values when converted to numbers, while their expected results were integers (which is *allowed* but not required, as you note). So I was asking them to either allow multiple correct values, both rounded and unrounded, or ensure that all %s tested were multiples of 20%. (They did the latter, so we're good to go now; I merged the tests.)

**Comment by svgeesus** [comment]
Aha, got it.

**Comment by svgeesus** [comment]
I have a [PR for an initial @color-profile test](https://github.com/web-platform-tests/wpt/pull/32157) which uses a red-green swapped ICC profile. Waiting for a reviewer.

**Comment by svgeesus** [comment]
I have a [PR for 5 tagged and untagged image tests](https://github.com/web-platform-tests/wpt/pull/32162) looking for a reviewer
