### ISSUE TITLE
[css-overflow-3] should -webkit-discard be a valid value for continue?

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#6842]
https://drafts.csswg.org/css-overflow-3/#propdef-continue / https://drafts.csswg.org/css-overflow-3/#valdef-continue--webkit-discard

Per the value grammar for `continue`, `-webkit-discard` is not a valid value, despite it being set as the value of `continue` by the `-webkit-line-clamp` shorthand.

I'm unaware of any other case where a property has a value that can _only_ be set via a shorthand, hence this feels like it's adding an oddity (and quite probably causing extra implementation complexity as a result, for unclear benefit to anyone).

It's also somewhat surprising that a value for `continue` is defined within the "Limiting Visible Lines: the line-clamp shorthand property" section, without "Fragmentation of Overflow: the continue property" even mentioning that value.

Also, if the computed value of `continue` is `-webkit-discard` (via the shorthand), how do we expect `continue` to serialise? Do we expect it to serialise to an invalid value, or to what?

**Comment by frivoal** [comment]
The spec's intent is that it is a valid value of the continue property, but since it's only there for legacy compat, it's described in a compatibility subsection rather than in the main body of text.

The current write up means it as an editorial tweak to deemphasize that value, but it is still mean to behave perfectly normally, excatly as if it had. But I can see how that's not obvious. I've just pushed an editorial update to that section that hopefully should avoid this confusion. Let me know if that works for you.

**Comment by gsnedders** [comment]
Yeah, I think this works for me.
