### ISSUE TITLE
[css-color-5] Percent normalization does not account for computed zero percentages

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6890]
[The spec says](https://drafts.csswg.org/css-color-5/#color-mix)

- Percentages are required to be in the range 0% to 100%. Negative percentages are specifically disallowed.
- Otherwise, if p2 is omitted, it becomes 100% - p1
- Otherwise, if p1 is omitted, it becomes 100% - p2

So if I type

```css
color-mix(in lch, purple 80%, plum -30%)
```

it is invalid per spec, but if I instead go

```css
color-mix(in lch, purple 120%, plum )
```

then `p2` computes to -20% and the spec is silent on what do do next because only `p1` was specified and

- Otherwise, if **both** are provided and add up to greater than 100%, they are scaled accordingly so that they add up to 100%.

but they weren't both specified.

**Comment by tabatkins** [comment]
That second one is *also* invalid per spec, since it's individually greater than 100%. So the question is moot, isn't it?

(The spec calls out negative percentages in the prose, but that's technically superfluous; the grammar already defines the valid range to be 0-100 only, so negatives and >100 are invalid at the syntax level.)

**Comment by svgeesus** [comment]
Ah good point so if someone types `120%`, the function is invalid?

OK, close with no action then
