### ISSUE TITLE
[css-color-5] Clarify / add example of gamut mapping during color-mix() 

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6913]
The [`color-mix()`](https://drafts.csswg.org/css-color-5/#color-mix) function has the following step defined:

> Both colors are converted to the specified &lt;color-space>. If the specified color space has a smaller gamut than the one in which the color to be adjusted is specified, gamut mapping will occur.

It would be useful to understand exactly when this applies, as its not entirely clear to me.

For instance, would the following require gamut mapping?

```
color-mix(in srgb, color(display-p3 0 1 0) 100%, red 0%)
```

Should the `color(display-p3 0 1 0)` color be gamut mapped to the sRGB gamut, or would it be ok for this to produce a result like `color(srgb -5.35 10.17 -3.43)`?

Presumably this only applies to `srgb`, `srgb-linear`, `hsl` and `hwb` at the moment as well, but clarification would also be helpful.

**Comment by svgeesus** [comment]
I agree this is under-specified and confusing. I suspect the language you quote was not updated when we went to extended colorspaces for all the predefined RGB spaces.

`hsl` and `hwb` certainly are unable to express out of gamut colors, so in those cases certainly gamut mapping would occur. And doing manipulations in `hsl` is likely to be common as people move color-manipulation logic from the likes of Sass where hsl was until recently the only option.

> Should the color(display-p3 0 1 0) color be gamut mapped to the sRGB gamut, or would it be ok for this to produce a result like color(srgb -5.35 10.17 -3.43)?

Well ideally it would produce `color(srgb -0.5116 1.01827 -0.3107)` :) but yes, there is color space conversion but no gamut mapping in this case

CSS Color 4 [says](https://drafts.csswg.org/css-color-4/#interpolation-space), in Color Spaces for Interpolation:

> If the colors to be interpolated are outside the gamut of the interpolation space, then once converted to that space, they will contain out of range values.

> These are not clipped, but the values are interpolated as-is.

I think the fix is to change the text you cited, from "has a smaller gamut" to "cannot express the color" plus adding an example.

**Comment by LeaVerou** [comment]
Note [this part from css-color-4](https://drafts.csswg.org/css-color-4/#interpolation-space)

> If the colors to be interpolated are outside the gamut of the interpolation space, then once converted to that space, they will contain out of range values.
> 
> These are not clipped, but the values are interpolated as-is.

I think this is how we should handle `color-mix()` as well. No gamut mapping should happen until the very end. Thoughts, @svgeesus?

**Comment by weinig** [comment]
Is it safe to say that for the non-legacy colors, gamut mapping will only happen at used value time? For things like computed value, returning the un-mapped value is the right thing to do?

**Comment by svgeesus** [comment]
@weinig yes, indeed

**Comment by svgeesus** [comment]
Clarified that gamut mapping for `color-mix()` is only used when an oog color cannot be expressed (`hsl` and `hwb`).

Added an example, with display-p3 green mixed in hsl.
