### ISSUE TITLE
[css-color-4] Consider not basing interpolation color space on input color types

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6914]
In CSS Color 4's section on interpolation, https://drafts.csswg.org/css-color-4/#interpolation-space, it states:

> If the host syntax does not define what color space interpolation should take place in, it defaults to OKLab.
>
> However, user agents may handle interpolation between legacy sRGB color formats (hex colors, named colors, rgb(), hsl() or hwb() and the equivalent alpha-including forms) in gamma-encoded sRGB space. This provides Web compatibility; legacy sRGB content interpolates in the sRGB space by default.

I don't think changing the interpolation color space based on input types (e.g. legacy sRGB formats vs. newer formats) is a good idea, as this could easily lead to surprising results with just small changes to input. For instance, if a gradient specified like:

`linear-gradient(red, blue)` 

is changed to

`linear-graident(color(srgb 1 0 0), color(srgb 0 0 1))`

I would not expect a change.

This is exacerbated by the use of CSS variables, where the definition of the color values might not be local to the use.

I propose we leave the current host syntaxes for interpolation (gradient, animation, transition, etc.) alone by specifying they use sRGB unless a syntax for specifying the interpolation space is explicitly specified (like we now have for gradients). Additionally we would encourage any additional uses of interpolation to consider either always requiring the interpolation space (like color-mix) or defaulting to OKLab (though the former is preferred by me, as predicting what our future selves will think is a good interpolation color space is quite difficult).

(It's possible I have filed something like this in the past, but I couldn't recall. If so, apologies for the double report).

**Comment by LeaVerou** [comment]
Interpolating in gamma-encoded sRGB is legacy handling, as it tends to produce _**terrible**_ results (for the lulz, try to interpolate between `lime` and `red`). The current spec is a compromise between better interpolation handling and web compat.
I would be fine with deciding to interpolate *everything* in oklab or lab unless otherwise specified, but it's nonsensical to force non-legacy colors (e.g. think of a gradient between two oklab colors) to interpolate in gamma-encoded sRGB, nor should we suddenly require all gradients to specify an explicit interpolation space.



> I don't think changing the interpolation color space based on input types (e.g. legacy sRGB formats vs. newer formats) is a good idea, as this could easily lead to surprising results with just small changes to input. For instance, if a gradient specified like:
> 
> `linear-gradient(red, blue)`
> 
> is changed to
> 
> `linear-graident(color(srgb 1 0 0), color(srgb 0 0 1))`
> 
> I would not expect a change.

This is intentional, so that people can opt in to improved interpolation by using a non-legacy format.

> This is exacerbated by the use of CSS variables, where the definition of the color values might not be local to the use.

In those cases there is no compat issue, so no need to interpolate in sRGB.

In general, the idea here is that the **only** use cases for interpolating in gamma-encoded sRGB are compat. If you believe that assumption is wrong, we should have a different discussion, and we'd love to hear all about these other use cases.

> I propose we leave the current host syntaxes for interpolation (gradient, animation, transition, etc.) alone by specifying they use sRGB unless a syntax for specifying the interpolation space is explicitly specified **(like we now have for gradients)**. 

We do? That should be changed if so. Gradients should also interpolate in oklab, unless all colors are legacy.

**Comment by weinig** [comment]
> This is intentional, so that people can opt in to improved interpolation by using a non-legacy format.

I understand its intentional, I just think it is more surprising than useful. I think it would be much more clear and less error prone if people opted into the new improve interpolation by stating an interpolation color space. I can equally see this being confusing going the other way. A gradient that uses a non-legacy color switches that one to some named color (e.g. `blue`) and now all of a sudden the interpolation changes. That feels much harder to teach than just, sRGB is the default legacy interpolation, but we suggest you use one of our better ones!

> > I propose we leave the current host syntaxes for interpolation (gradient, animation, transition, etc.) alone by specifying they use sRGB unless a syntax for specifying the interpolation space is explicitly specified (like we now have for gradients).
> We do? That should be changed if so. Gradients should also interpolate in oklab, unless all colors are legacy.

I was mistaken, the gradient spec doesn't state this, indeed, [it says](https://drafts.csswg.org/css-images-4/#coloring-gradient-line):

> If no `<color-interpolation-method>` is specified in the gradient function, the color space used for gradient interpolation is the default interpolation color space as defined in [css-color-4].

This would be a breaking change in WebKit, where we have been shipping CSS gradients with color stops using `color()` functions for a few years. It might be an acceptable break, but I am not sure. I will check with others on the project to see what they think for some additional feedback here.

To restate my point a bit, in general, I think there is virtue in requiring opting in to this behavior explicitly, via an explicit `in <color-interpolation-method>` as it 1) provides a clear indication of intent, 2) simplifies the understanding of the API of the `gradient()` by having only single default color space, 3) aids in teaching about the different interpolation methods by making it front and center, 4) does not hardcode another default color space choice into the standard that we might one day not think is the right choice (at one point in the past we were ok-ish with sRGB, until recently I believe either CIE Lab or CIE LCH were going to be the default, so it stands to reason that in the future, we may find yet a better pick).

I do agree that this is a tradeoff, and there is also virtue in improving the default color space today, I just don't think that is enough to merit the downsides.

**Comment by LeaVerou** [comment]
When we looked into usage of `color()` on the web as part of the Web Almanac, it was extremely low, so I doubt there are any significant web compat implications here.

I agree `color(srgb)` behaving differently than `rgb()` can be confusing. However, we cannot always require an interpolation space in gradients or transitions, and using sRGB interpolation by default for all colors just because of legacy is terrible.
I would be fine however using better interpolation for everything by default, as I doubt there are many websites that depend on the crappy gamma-encoded sRGB interpolation (and for the few cases that do, e.g. some kind of interpolation-related tool perhaps?, they can still specify an interpolation space explicitly, if that syntax is implemented at the same time.

Note that we still don't have syntax to specify interpolation for everything in CSS. E.g. there is nothing for transitions and animations yet.

I sympathize with your worry that we've already changed default interpolation space once, what if we want to change it again in the future. I've also worried about this, but having sensible defaults is one of the basic rules of good API design. The same reasoning could be extended to literally every default we have (what if we want to change it in the future?), but the language would have significantly worse ergonomics if we could not take advantage of defaults and initial values.

Btw, the reason we require an interpolation space in `color-mix()` was a compromise, because some UAs wanted to implement it with sRGB interpolation only, IIRC.

**Comment by Crissov** [comment]
Well, it would be possible to introduce explicit default color spaces, e.g. like this

~~~~ css
:root {color-space: OKlab;}
~~~~

and then handle the recommended interpolation space via the sample stylesheet for HTML.

**Comment by svgeesus** [comment]
> When we looked into usage of color() on the web as part of the Web Almanac, it was extremely low, so I doubt there are any significant web compat implications here.

https://almanac.httparchive.org/en/2021/css#colors shows everything except hex, `rgba` and named colors at 0%. Looking at the [spreadsheet of data](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=2108707108) these vary from `rgb()` at 0.40%, through `hsl()` at 0.01%, to `color()` at 0.00% (actually 0.00183%)

**Comment by svgeesus** [comment]
> For instance, if a gradient specified like:
> `linear-gradient(red, blue)` 
> is changed to
> `linear-graident(color(srgb 1 0 0), color(srgb 0 0 1))`
> I would not expect a change.

I can see both sides of this. However, if explaining such a change, i would point to [what the spec says](https://drafts.csswg.org/css-color-4/#interpolation-space):

> This also means that authors can choose to opt-in to better interpolation by using the non-legacy `color(srgb r g b)` form for one of their colors.

**Comment by svgeesus** [comment]
> Various features in CSS depend on interpolating colors. Examples include:

- [x]    **&lt;gradient>** (explicit `color-interpolation-method`)
- [ ]    **filter** (srgb-linear, with gamut-clipping at each stage)
- [ ]    **animation** (srgb, silent on handling of non-legacy)
- [ ]    **transition** (srgb, silent on handling of non-legacy)

Updating `filter` is possible but will be hard due to lack of an active editor and general browser-dev disinterest in anything to do with SVG.

Updating transitions and animations is possible, and worth doing.

Compositing (srgb, silent on handling of non-legacy) is not mentioned as an example of interpolating colors, but should be.

**Comment by svgeesus** [comment]
@weinig wrote:

> This would be a breaking change in WebKit, where we have been shipping CSS gradients with color stops using color() functions for a few years.

Are these interpolating in gamma-encoded `display-p3` currently?

**Comment by weinig** [comment]
> @weinig wrote:
> 
> > This would be a breaking change in WebKit, where we have been shipping CSS gradients with color stops using color() functions for a few years.
> 
> Are these interpolating in gamma-encoded `display-p3` currently?

No, it uses gamma-encoded `extended-srgb`. (though I would assume they would give very similar results).

**Comment by svgeesus** [comment]
Those would indeed give similar results.

I couldn't tell from the [TP 137 release notes](https://webkit.org/blog/12156/release-notes-for-safari-technology-preview-137/) is the `in <color-space>` implemented for gradients?

**Comment by weinig** [comment]
> I couldn't tell from the [TP 137 release notes](https://webkit.org/blog/12156/release-notes-for-safari-technology-preview-137/) is the `in <color-space>` implemented for gradients?

It wouldn't have made it into TP 137, but should be in the next one, behind an experimental feature flag.

**Comment by svgeesus** [comment]
So you are able to test out the impact of a default `oklab` interpolation method for gradients, compared to an `sRGB` one (which is extended, as are all the non-legacy RGB spaces in CSS)?

**Comment by weinig** [comment]
> So you are able to test out the impact of a default oklab interpolation method for gradients, compared to an sRGB one (which is extended, as are all the non-legacy RGB spaces in CSS)?

I mean, somewhat (testing that you don't "break" things is always hard on the infinite web).

**Comment by svgeesus** [comment]
I see code and test commits by @weinig to enforce an oklab default interpolation.

I still believe this is the right approach, because these options are worse:

1. enforce an sRGB interpolation space for interpolating all colors (unless there is an explicit `in <colorspace>`), thus forcing all non-legacy colors to interpolate in a gamma-encoded space with known bad results
2. enforce `in <colorspace>` for interpolation of all non-legacy colors

![image](https://user-images.githubusercontent.com/2506926/150681113-1127fe50-a0a8-410b-a800-e0f7793c64e5.png)

**Comment by svgeesus** [comment]
Thus the conclusion is to close this issue with no change.

**Comment by LeaVerou** [comment]
@svgeesus The other option we were considering was using the same default interpolation regardless of color types. We were going to investigate the web compat impact of this, though it was unclear how.

**Comment by svgeesus** [comment]
That is already allowed by the _may_ so do you mean we were considering requiring it?

**Comment by LeaVerou** [comment]
Yes.
