### ISSUE TITLE
Consider reverting “allow child-index pseudos to select unparented elements” change

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/csswg-drafts#695]
Spec section: https://drafts.csswg.org/selectors-4/#child-index

Original CSS WG issue: https://www.w3.org/Style/CSS/Tracker/issues/317
Discussion: https://lists.w3.org/Archives/Public/www-style/2013Mar/thread.html#msg290

But see also https://lists.w3.org/Archives/Public/www-archive/2016Oct/0009.html

At the time when  this spec change was made more than 3 years ago at a time, we had interoperability among all UAs on this: They all implemented the original spec requirements. And in the 3 years since, Gecko is the only engine that has changed to match the spec change. So interop on this has now regressed, and it’s not clear if there are even any Blink/WebKit/Edge browser bugs open to request those other browsers implement this change.

So it seems like consideration should be made about either reverting the change or else getting some browser bugs raised and making an effort to get back to interoperability on this.

**Comment by tabatkins** [comment]
Browser bugs are the right way to do this.  Something like this change is necessary to make the child pseudos work in the expected way on shadow trees (otherwise, all the top-level elements don't match, because they don't have a parent), and it's dumb to carve out a special exception for shadow trees while still making &lt;html> not match.  I'll file a Chrome bug, at least.

**Comment by Ms2ger** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=675670

**Comment by yisibl** [comment]
Firefox fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1300374

**Comment by tabatkins** [comment]
Since we have two implementations, I'm gonna go ahead and close this bug.
