### ISSUE TITLE
[css-text-4] Make ideograph-alpha and ideograph-numeric part of text-spacing: normal

### ISSUE THREAD

**Issue by hfhchan** [w3c/csswg-drafts#6950]
The baseline behaviour of text-spacing should always turn on ideograph-alpha and ideograph-numeric when in the horizontal writing direction. In the vertical direction, it should be turned on when the western text is rotated[^1] and turned off if the western text is not[^2].

Microsoft Word has ideograph-alpha/ideograph-numeric turned on by default. The iOS UI also has this spacing, but I'm not sure if it's done on the rendering level, or spaces are injected during string interpolation.

On other platforms, it is not supported out of the box. Authors end up adding spaces themselves inconsistently, leading to horrible UIs like this:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/8191296/149442034-483ad4c1-3a78-4d25-9e03-d0ce855d00ad.png">

CSS should support this turned on as the default.

There may also need to be an additional property for authors to specify the width of the inserted space they want.  The default 1/4 space is fine.

[^1]: See [CLREQ Figure 8](https://www.w3.org/TR/clreq/images/en/latin-90-clockwise.svg).
[^2]: See [CLREQ Figure 7](https://www.w3.org/TR/clreq/images/en/latin-one-by-one.svg).

**Comment by frivoal** [comment]
There's a double question here:
* what is good behavior
* what is compatible with existing content

I believe you're right about what's good, but given that it is not the historical behavior and that plenty of content was written assuming it wouldn't happen, this is likely not to be compatible.

We could maybe write an informative note giving a suggestion of an algorithm for the UA-dependent `auto` value, which could do what you suggest, including the dependencies on writing-modes, but I suspect we cannot make that behavior the default. If you'd like to insist on it, it would take some evidence that this is web compatible.

**Comment by hfhchan** [comment]
I tried imagining scenarios where changing to more desirable defaults would make it incompatible with existing content, but I cannot come up with much.

Content which already has extra space characters injected wouldn't be affected, because ideograph-alpha and ideograph-numeric do not insert additional spaces between characters and spaces.

One case which may potentially be affected would be designs that emulate a terminal with mixed western/CJK text.

Since there's no guarantee that the browser font selected for CJK will be an integer multiple of the monospace font selected for western text, any site which wants pixel-perfect alignment will likely already be breaking characters into blocks with hard-coded widths and/or CSS grid. Ideograph-alpha and ideograph-numeric should not interact across blocks, so there would not be any impact if implemented that way.

About the behavior being turned off depending on the writing mode, I think I have approached it wrongly. It's more about the behavior of ideograph-alpha and ideograph-numeric itself, i.e. when turned on, spaces are only injected between characters in the same inline direction.

**Comment by frivoal** [comment]
> I tried imagining scenarios where changing to more desirable defaults would make it incompatible with existing content, but I cannot come up with much.

Content that used to fit within a element of a certain given size is now longer due to these inserted spaces, no longer fits, and now brakes into two lines.

If a paragraph of text goes from 7 to 8 lines, it's usually fine, but if a UI element like a button or a menu entry goes from 1 line to 2, there's not always room to fit that, and it can easily overflow.

**Comment by hfhchan** [comment]
Note the current specified value trim-adjacent and allow-end for normal also causes content to no longer align on character grid boundaries.

Quad space is not much, has been universally used in commercial printing (sometimes more than quad, so the western text takes up a whole number of CJK characters), and is still better for alignment than a full space.

Also it's quite unlikely for UI to have mixed script CJK & Western; it is usually considered bad style. The vast majority of script mixing would be in titles, slogans and prose.

**Comment by hfhchan** [comment]
Would there be an update to this issue?

**Comment by CharlesBelov** [comment]
English reader here who has a bare acquaintance with Chinese text. As a webmaster, I would prefer that the default behavior, not inserting automatic spaces on language switch between CJK and Western, not be changed and that any new behaviors, such as automatically inserting spaces, need to be explicitly stated through a non-default property. This would prevent breaking legacy content.

I checked with two colleagues who have professional experience in Chinese-language media and here are their responses on the proposal:

Jay Lu:

> “When I worked for the Chinese media, our style book called for no-space. I would recommend no-space because 1) our local press (Sing Tao and World Journal) follows no-space guide; 2) it looks better.”

Jessie Liang:

> “As for newspapers and online articles, it's better to have no spaces before and after the English words, which look better. However, as for the subtitle on TV, you may or may not use a space because when you read a subtitle with a limited time, having a space before and after the English words would be easier to catch each word.”

**Comment by r12a** [comment]
It's not an easy call, one way or the other. 

If autospacing is the default, it's possible that some web text somewhere might grow a little, although it's not clear to me how many cases like that exist, and it may be a small number.

On the other hand, if the behaviour has to be applied manually to all Chinese and Japanese text in the future, that's a pain in the neck (for all web pages going forward, forever).   Especially in cases such as where text is converted automatically from markdown, or where strings from a database or field-based input from users are integrated into a document that doesn't have styling for Chinese, and so on.

But i also find myself wondering about a couple of aspects of this.

@CharlesBelov makes a case for no autospacing in some types of text.  Of course, one possibility would be to have a value that turns autospacing off, except that we don't appear to have one, and that leads to another thought.  It suggests that it would also not be possible to have, say, autospacing set for the document as a whole (by default or by a style declaration), and then turn it off for some parts of the content.

Another feature that might be useful is the ability to say, "If spacing has been used in an existing text between Han and ASCII alphanumeric text, rather than adding yet more space if autospacing is turned on (1/4 em plus the existing space), _replace_ the existing space with a 1/4em gap. That would make it easier to have consistent spacing when mixing text from different sources on the same page (especially including user input via forms, where they may add spaces). That would also allow content authors to apply autospacing without being concerned that  existing text would wrap onto 2 lines, as @frivoal fears.

Which makes me wonder whether it's right to treat autospacing as just a value of `text-spacing`, or whether it better to have an `autospacing` property with values such as `on|off|override-space|<width>`.  (I seem to vaguely remember that this is more like what was implemented in Internet Explorer in times past.)

**Comment by r12a** [comment]
By the way, i think that separating out the autospacing we're talking about here – moving Han and alphanumeric inline runs apart – from the punctuation-related text spacing feels intuitively better, too.  When writing this stuff up so that others could learn about it, i found myself doing that anyway (see http://localhost/scripts/jpan/#letterspace).

**Comment by macnmm** [comment]
These "spaces" need special handling not normally found in Western typography, in that they compress more readily than Western spaces would in a tight justification scenario, and they would do so before any adjustments would be applied to U+0020 characters' widths. So, this is a new concept and has complexity. The Japanese case is more so, in that spacing around full-width punctuation is added to the prioritized list of spacing to be adjusted. These adjustment considerations need to be accounted for in the feature or it may not work well.

**Comment by r12a** [comment]
I think those features would be accounted for in the _justification_ algorithm, no?

**Comment by CharlesBelov** [comment]
I'm not sure I've been understood. That Microsoft Word does autospacing when mixing CJK and Western text does not make it correct (or wrong, for that matter). My concern is that you appear to be proposing to implement something that changes default behavior whether a site wants it or not, resulting in breaking existing content, based on your perception that adding spacing looks better. I have had two professionals who come from journalism tell me that removing spacing looks better, with adding spaces being reserved for special use cases.

Again, I am not an expert in Chinese, so take my random search judiciously, but in visits to four Chinese newspaper websites, all four sites had examples of mixed content where it appears there is intentionally no spaces between CJK and Western text. No endorsement of the content is intended; these are merely examples of Chinese content with strings of Western text.

https://std.stheadline.com/daily/article/2452186/%E6%97%A5%E5%A0%B1-%E6%B8%AF%E8%81%9E-%E5%85%A7%E5%9C%B0%E8%88%87%E6%B8%AF%E7%A7%8B%E5%AD%A3%E5%89%8D%E6%81%90%E9%9B%A3%E9%80%9A%E9%97%9C (Sing Tao Daily)

https://language.chinadaily.com.cn/a/202203/29/WS6242d221a310fd2b29e53fc5.html (China Daily)

https://www.zaobao.com.sg/lifestyle/columns/story20220328-1256766 (Zaobao Singapore)

https://www.chinatimes.com/realtimenews/20220330001102-260403 (China Times, Taiwan)

I acknowledge I did see in my searching discussions on this issue asserting that web designers like to add spacing in these cases. So I am fully in support of adding the automated capability. I am only concerned with the idea of making it the default behavior to the point where it breaks existing content or changes existing behavior to enforce a behavior that appears to not have agreement between designers and journalists. 

I want to urge that when the CSS Working Group discusses the outcome of this issue, that they respect legacy content.

**Comment by xfq** [comment]
According to my observations, the two cases (non-ideographic *letters* and *numerals*) are not the same. But in either case, you can find examples with and without extra spacing on the market.

Note that I am only talking about print publications here. I'm not talking about the web because no browsers currently don't support `text-spacing`. Although it is possible to implement this behavior via JavaScript (e.g., [1](https://github.com/ethantw/Han/blob/master/README-en.md) [2](https://sivan.github.io/heti/) [3](https://github.com/sofish/typo.css) [4](https://github.com/CyC2018/Text-Typesetting)), it is more troublesome and there is no standard way. And another issue is that some libraries implement this by adding ASCII spaces (`U+0020`), but the width of `U+0020` is uneven font by font.

-----

Here are a few examples:

-----

[Reference News](https://en.wikipedia.org/wiki/Reference_News) in 2014:

![Reference_News_2014](https://user-images.githubusercontent.com/2863444/160757725-3253d608-0327-408b-8ba7-4adaed604da0.jpeg)

There's extra spacing between runs of ideographs and non-ideographic numerals.

-----

[People's Daily](https://en.wikipedia.org/wiki/People%27s_Daily) in 2022:

![PD_2022](https://user-images.githubusercontent.com/2863444/160757758-b86f9a15-f051-4686-b864-ff66daddd771.jpeg)

There's no extra spacing between runs of ideographs and non-ideographic letters.

-----

[ネットワークはなぜつながるのか 第2版](https://www.amazon.co.jp/%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E3%81%AF%E3%81%AA%E3%81%9C%E3%81%A4%E3%81%AA%E3%81%8C%E3%82%8B%E3%81%AE%E3%81%8B-%E7%AC%AC2%E7%89%88-%E7%9F%A5%E3%81%A3%E3%81%A6%E3%81%8A%E3%81%8D%E3%81%9F%E3%81%84TCP-IP%E3%80%81LAN%E3%80%81%E5%85%89%E3%83%95%E3%82%A1%E3%82%A4%E3%83%90%E3%81%AE%E5%9F%BA%E7%A4%8E%E7%9F%A5%E8%AD%98-%E6%88%B8%E6%A0%B9/dp/4822283119) in Chinese:

![ネットワークはなぜつながるのか](https://user-images.githubusercontent.com/2863444/160757778-750510e9-71af-4d53-91e5-cc636f0f2e83.jpg)

There's extra spacing between runs of ideographs and non-ideographic letters.

**Comment by r12a** [comment]
@CharlesBelov if by 'you' you mean me, i was not proposing a particular default, just voicing some factors that need to be taken into consideration.

I edited my comment a little to hopefully make it clearer.

The main point of my comment was the stuff below the line that i added. hth

**Comment by r12a** [comment]
Btw, i'd urge a little caution in basing decisions solely on online text. It may indicate a fundamental preference for no autospacing.  Or it may done because without a proper way of typesetting online text so that it has the right size of gap, no gap looks better.  It may even be the case that this is a new trend that is becoming normalised.

Across many languages i see approaches to typography that have been produced by the inability of technology to do what's really wanted, and several cases where this is just accepted, or even starting to become considered as normal.

So, I think it's also important to also consider common approaches in quality printed text, where correct autospacing can be applied if desired,  and @xfq provides several examples just above that suggest that autospacing is used in such. 

I await with interest the advice of people (such as the clreq group) that have expertise in Chinese typography as to what should be the best default – although there may not be a clear answer even then.

**Comment by CharlesBelov** [comment]
The following examples are from SingTao Daily, April 4, 2022, as published in San Francisco, CA. These images are intended solely for the demonstration of newspaper typography and were selected by me. No endorsement or criticism of the source, content or issues covered is implied.
![Samples for posting to issue](https://user-images.githubusercontent.com/3281090/161650089-ddbb1fee-f1ee-400e-989d-0d9172de33f5.png)

**Comment by xfq** [comment]
The Chinese Layout Task Force [discussed](https://www.w3.org/2022/04/15-clreq-minutes.html#t02) this issue. Most group participants think that ideally, there should be extra spacing between Han and Western text. The specific value can be discussed separately, but the TF members think 1/8em is an acceptable default value for the Web (for print publications, the spacing can be larger). Many people think that solid setting between Han and Western text is bad typography.

Also, some think that Japanese is more tolerant of not having the extra spacing, because unlike Chinese, the Japanese writing system uses a combination of a variety of scripts. The Japanese version of some apps do not have extra spacing by default, while the Chinese version of the same app have extra spacing by default. But since this is original research of the clreq group, and I'll let the [jlreq](https://github.com/w3c/jlreq) group share what they think.

If the CSS Working Group decides not to change the default due to compatibility issues, we (the clreq group) are fine with that.

The clreq group members think that this is an important issue, and maybe even the most important issue that CSS needs to solve now for Chinese typography. Because browsers don't support `ideograph-alpha` and `ideograph-numeric` currently, many authors add `U+0020` manually, which eventually leads to all kinds of potential interoperability issues (like #4992) or bad typography (for example, `U+0020` in some fonts are too wide or too narrow).

**Comment by hftf** [comment]
I just came across something possibly relevant to this issue. A user of the not-hugely-popular note-taking app Logseq wrote a [plugin](https://github.com/sethyuan/logseq-plugin-charspacing) to render extra spaces between Chinese and Latin characters. This little mod – one of a few dozen Logseq plugins – might be a pithy example of how end-users tend to go about implementing makeshift solutions in the absence of a better default or wider browser support for a modern feature, and might also convey the importance of this aspect of typography as it was enough for someone a bit savvy to spend the time creating and then to publish it for others to use to their advantage.

**Comment by xfq** [comment]
That option is about manually added whitespace (`U+0020`), not automatically added spacing, and this issue is about automatically added spacing.

@CharlesBelov What you are looking for is probably **Format** > **Paragraph...** > **Asian Typography**. In the **Asian Typography** task pane, there are two checkboxes:

* [x] Automatically adjust space between Asian and Latin text
* [x] Automatically adjust space between Asian text and numbers

But *whether an option exists* has nothing to do with this issue, which is about the default behavior (because CSS already has such a property, and it's been around for years).

**Comment by himorin** [comment]
Sorry for late response, although I've catched this earlier but could not secure time on this.
I'm chatting with JL-TF participants if we can write something more.

Several random notes:
As @xfq pointed, Mozilla's Japanese translation [places a rule to insert U+0020 between CJK Ideograph characters and western characters in Editorial Guideline (only in Japanese)](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline), which was originally agreed around 2000 and also commonly shared among documentation sites like MSDN (at that time) via collaborating discussions among these. (On this point, it might be welcomed to suppress such hand-input/hard-coded white space and put narrower space by using this CSS feature?)
Also, JL-TF is preparing draft of line composition layout to be used as a part of (so-called) jlreq-d, and [1/4em as default but preferred to be configurable](https://w3c.github.io/jlreq/docs/line-composition/index.html#japanese-western-space) for spacing between CJK ideograph characters and western characters. Some old research exist on this area in Japan and 1/6-1/4em seems to be preferred (as far as I remember...).

**Comment by xfq** [comment]
> Because browsers don't support ideograph-alpha and ideograph-numeric currently, many authors add U+0020 manually

FWIW, here are some examples for Chinese:

* [Node.js docs](http://nodejs.cn/api/)
* [PyTorch tutorials](https://pytorch.apachecn.org/#/)
* [React docs](https://zh-hans.reactjs.org/)
* [Redux docs](https://cn.redux.js.org/)
* [Vue 3 docs](https://staging-cn.vuejs.org/guide/introduction.html)

**Comment by fantasai** [comment]
Recommendation from i18n is to make this part of the initial value _if Web-compatible_.

**Comment by kidayasuo** [comment]
We discussed this at a JLReq TF meeting. and here is our feedback.

### Summary
- All agreed that it is easier to read when there is an appropriate space between ideographic and non-ideographic characters.
- We could not reach an agreement on what should then be the default on the web. Values suggested are 1/4 (metal type traditional), 1/8 (common in recent publishing), zero (for compatibility).
- JLReq TF's recommendation at this time is to make "auto" as the default value (throwing the decision up to the browser engines)

### Discussions / opinions
- The 1/4 space originated from technical limitations of the workflow of metal type. It has long been considered as a default since then. Many recent professionals think it is too wide. 1/6 or 1/8 for example are actually used.
- Similar to the word space in English, there seems to be a trend of the space becoming smaller. It seems 1/8 is common in recent books / magazines.
- JLReq says that this space cannot be used for adjustment of line width. If so, when a line is stretched and other kinds of spaces become wider, the balance between the ideograph-non-ideograph space and other kinds of spaces can become unbalanced, especially when the default is narrow. For this reason, if the ideograph-non-ideograph space cannot be used for adjustment, we should not make the default too narrow. InDesign allows to use this space for line adjustment (and therefore you can safely set the default narrower).
- There are many existing text that have U+0020 between ideograph and non-ideograph because web do not support the ideograph-non-ideograph space right now. Also, html's line folding algorithm automatically insert U+0020 between lines. How do we support those spaces that are intentionally or unintentionally inserted between ideograph and non-ideograph?
- The ideal value are different depending on the font design. For example fonts are designed with large kana and/or narrower space between kanji body, like ones on Windows, they are best with relatively narrower ideograph-non-ideograph space.
- Apple uses 1/8 as the default on its Notes application. It looks nice and easier to read.

**Comment by r12a** [comment]
>  How do we handle those intentionally or unintentionally inserted spaces between ideograph and non-ideograph?

See my proposal under point [2] at https://github.com/w3c/csswg-drafts/issues/7183#issue-1186516551  Essentially, i'm proposing that the author would be able to use CSS to replace space characters with an appropriate gap, if they want to.

**Comment by ayaka14732** [comment]
+1 for making this enabled by default.

On WeChat (the most popular IM app in China), this is the default behaviour:

![image](https://user-images.githubusercontent.com/68557794/192914115-fd62b62a-c7b9-4d1c-a81d-789f9e3b6734.png)

**Comment by fantasai** [comment]
Edits committed. Florian and I went with specifying 1/8ic as the spacing, since we wanted to stay on the conservative side if we're inserting spaces by default. Please file follow-up issues about anything that needs further adjustment.

Also, there's a follow-up issue about replacing spaces with auto-spacing at https://github.com/w3c/csswg-drafts/issues/8263

**Comment by MurakamiShinyu** [comment]
The [`text-spacing: normal`](https://drafts.csswg.org/css-text-4/#valdef-text-spacing-normal)  definition is now:

`normal` -- Specifies the baseline behavior, equivalent to `space-start trim-end trim-adjacent ideograph-alpha ideograph-numeric`.

I am a little confused about the "baseline behavior.

Before ideograph-alpha and ideograph-numeric were added to `normal` definition, the meaning was clear to me, that is, the each value included in the definition of `normal` is the default value, so when we specify the text-spacing property partially changed from `normal` we can specify just changed values and omit values that are included in the `normal` definition.
For example, when just `text-spacing: trim-start` is specified, it implies omitted normal values, trim-end and trim-adjacent. i.e., `text-spacing: trim-start` was equivalent to `text-spacing: trim-start trim-end trim-adjacent`.

However, after ideograph-alpha and ideograph-numeric were added to `normal` definition, it is no longer that simple. Is `text-spacing: trim-start` equivalent to `text-spacing: trim-start trim-end trim-adjacent ideograph-alpha ideograph-numeric`? That will be useful when we want to change only trim-start/space-start/space-first behavior and keep other `normal` behavior, but if so, how do we change just ideograph-alpha/ideograph-numeric behavior from `normal`?

Then I decided to interpret it as follows:

- `text-spacing: trim-start` is still equivalent to `text-spacing: trim-start trim-end trim-adjacent`. The omitted default *-start/first, *-end, and *-adjacent are kept but ideograph-alpha and ideograph-numeric are turned off.
- ideograph-alpha and ideograph-numeric are turned on only when these values are explicitly specified, or `normal` (or `auto`, probably) is specified.

(I implemented it in Vivliostyle.js as per this interpretation. https://github.com/vivliostyle/vivliostyle.js/issues/1080)

----

However this spec is not very clear and not very useful.

It would be better adding a new keyword, `no-interscript-space`, to turn off the interscript spacing.

The `ideograph-alpha || ideograph-numeric` part of the value definition becomes `[no-interscript-space | ideograph-alpha || ideograph-numeric]` and we can specify only this part to the text-spacing property when keeping other default (normal) behavior.

**Comment by MurakamiShinyu** [comment]
Or maybe it would be better to change the `ideograph-alpha || ideograph-numeric` value to `ideograph-alpha <number> || ideograph-numeric <number>` where the `<number>` represents the space width as a multiple of the fullwidth advance measure. The `normal` definition would contain `ideograph-alpha 0.125 ideograph-numeric 0.125`. Examples:

- `text-spacing: ideograph-alpha 0 ideograph-numeric 0` turns off the ideograph-alpha/ideograph-numeric spacing and keeps other `normal` behavior.
- `text-spacing: trim-start` only changes the \*-start/first part of `normal` behavior. i.e, is equivalent to `text-spacing: trim-start trim-end trim-adjacent ideograph-alpha 0.125 ideograph-numeric 0.125`.
