### ISSUE TITLE
[selectors] “any <a> or <area> elements are hyperlinks” is incorrect

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#6957]
I think this information is not entirely correct:

> For example, in HTML5, any `<a>` or `<area>` elements are hyperlinks, and thus match `:any-link`.

Link to section: https://drafts.csswg.org/selectors/#the-any-link-pseudo

According to the HTML Standard, the `<a>` and `<area>` elements are only then hyperlinks if they have an `href` attribute.

> If the `<a>` element has an `href` attribute, then it represents a hyperlink (a hypertext anchor) labeled by its contents.  If the `<a>` element has no `href` attribute, then the element represents a placeholder…

Source: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

Browsers follow this definition. In browsers, the `:any-link` selector matches `<a href="#">foo</a>` but not `<a>foo</a>`. Therefore, the CSS spec should say “any `<a>` or `<area>` elements **with `href` attributes** are hyperlinks”.

**Comment by tigt** [comment]
This may fall under “specifications of the host language”, but for backwards compatibility reasons, `a[xlink|href]` in the SVG namespace also matches `:any-link`. (This applies to SVG-in-HTML5 and also SVG-as-XML, where the XLink namespace can be bound to any prefix, not just `xlink:`.)

**Comment by ByteEater-pl** [comment]
More precisely, an `a` or `area` element with a href attribute is a source of a hyperlink and the resource or resource fragment identified in `href` is the target – a link cannot exist without both (or more than two – XLink allows that). And although HTML5 drops the mention that `a` without `href` may be used to mark up the target, it neither forbids it, nor offers an alternative (fortunately), so it IMO remains advisable.

Incidentally, the above also suggests that `:any-link` shouldn't match if the value of `href` is syntactically invalid per RFC 3986.

**Comment by simevidas** [comment]
> although HTML5 drops the mention that a without href may be used to mark up the target, it neither forbids it, nor offers an alternative

Is the `id` attribute not the standard way to mark up link targets?

**Comment by ByteEater-pl** [comment]
Yes! But on what element? If there is already an element encompassing exactly the fragment you want to link to, probably adding an `a` around it would be overkill in most cases. But if not, what do you use? There is the generic block-level container `div` and the generic inline-level container `span`, so they could say: use one of those, depending on how you want it treated, if the contents are all inline-level, and always `div` otherwise. But that's both a more complex set of guidelines and overloading `div` and `span` with yet more semantic roles, whereas a `href`less `a` is already perfect for the job and specified to fulfill it in earlier versions and other branches of (X)HTML. So I stick to it and hope others will too.

**Comment by simevidas** [comment]
@ByteEater-pl The `id` attribute is already allowed on all elements, and websites are using different elements as link targets (e.g., headings, `<main>`). This is going to stay that way because limiting link target functionality to `href`-less `<a>` would break the web.

**Comment by ByteEater-pl** [comment]
Oh, no, that I definitely don't propose. Linking to arbitrary elements by their `id` has always worked and it's fine, shouldn't be changed. What I described is a situation where there's no element already at the target, just some range of a document.

**Comment by fantasai** [comment]
Just noticed this while reviewing changes in preparation for republication. :) This was previously correct, but was broken in https://github.com/w3c/csswg-drafts/commit/0ea038ec3e1a8e142be91d1b92eec84c78336523 ; it's now fixed in https://github.com/w3c/csswg-drafts/commit/887dbb3cb55b538babd46bb9097d32511249a34b

Thanks for noticing!
