### ISSUE TITLE
[css-color-4] Clarify serialization of rgb()/rgba() functions that have `none` components

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6959]
CSS Color 4 [indicates](https://drafts.csswg.org/css-color/#rgb-functions) that `none` components are only allowed in the space separated syntax for `rgb()` / `rgba()` functions, but since `rgb()` / `rgba()` functions are serialized in the comma separated style, this leads to a weird case where the serialized form is not reparseable if any of the components are `none`. For example:

```css
rgb(255 0 none)
```

should currently serialize as:

```css
rgb(255, 0, none)
```

which is an invalid value.

Seems like either `none` should be allowed in the comma separated legacy form or serialization should be updated to specify a different serialization if `none` is used.

**Comment by svgeesus** [comment]
Good catch!

Because the comma-separated form is preferred mainly due to greatest backward compatibility, and because `none` is new, it would seem to make sense to serialize in the non-legacy form in that case.

On the other hand, allowing `none` everywhere is a bit of a heavy hammer and I would also be fine with just saying that `none` serializes as `0` here because I can't really see a use case for preserving `none` in RGB values. And in HSL or HWB it will serialize as `rgb()` in any case, with conversion to 0 for the hue if that was `none`.

**Comment by tabatkins** [comment]
Yeah, just serializing as 0 in rgb() seems reasonable to me, too.

**Comment by svgeesus** [comment]
Does this apply to resolving values, or just to serialization? (I assume the latter but just wanted to check first)

**Comment by weinig** [comment]
I hope just serialization. Doesn't seem like there is a compelling reason here to change value resolution.
