### ISSUE TITLE
A proposal for controlling screen brightness

### ISSUE THREAD

**Issue by anssiko** [w3c/csswg-drafts#6990]
Hi CSS WG,

The Devices and Sensors WG has produced an explainer for a proposed new feature for controlling screen brightness:

https://github.com/w3c/screen-wake-lock/blob/gh-pages/brightness-mode-explainer.md

We know many CSS WG participants have expertise in this space, so we’re reaching out to you to gather your feedback and comments before advancing (or not). In particular, the open design issues and the proposed CSS property are looking for your feedback.

You can provide your feedback on this issue or via https://github.com/w3c/screen-wake-lock/issues/129

Thanks everyone who already reviewed an earlier iteration of this proposal.

**Comment by tabatkins** [comment]
Looking over this, I think your JS API looks reasonable. This is something that should be permissioned, so I don't *think* we want this to be controllable via a CSS property. (In any case, this is more document-global rather than element-specific.)

I don't *think* we need to say anything about MQs; anything that's true of "screen locked to bright" should apply identically to "screen manually adjusted to bright" already.

**Comment by svgeesus** [comment]
HDR is already being discussed in two issues:

 - https://github.com/w3c/screen-wake-lock/issues/335
 - https://github.com/w3c/screen-wake-lock/issues/129

**Comment by svgeesus** [comment]
@anssiko have you had enough review from CSSWG? If so we can close this issue.
