### ISSUE TITLE
[css-ui] Should inertness be exposed as CSS property?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7021]
When discussing the `inert` attribute for HTML, there was some controversy about whether inertness should be propagated to descendants in the flat tree, or to shadow-including descendants.

@rniwa argued that semantic content attributes (like `contenteditable`, `lang`, etc.) don't use the flat tree.

@othermaciej argued that `inert` needs to operate on the flat tree to have its functional effect.

The current situation is that all Blink, WebKit and Gecko implement inertness as part of the computed style, so it propagates in the flat tree, like the CSS cascade. Also, in #6685 we resolved that the effect of inertness can be mostly explained by setting existing CSS properties like `pointer-events`.

So given the highly presentational nature of inertness, @rniwa proposed that maybe `inert` should actually be a CSS property:

> the correct course of action is to introduce a new CSS property which specifies inertness in CSS since that seems like the most natural mechanism to set inertness anyway. I don’t see any strong reason not to add such a CSS property given most use cases for “inert” seems to involve modifying the style of an element at the same time as inertness.

@cookiecrook argued that it should still be an attribute, but wasn't opposed to also having a reflecting CSS property.

This would be consistent with `hidden`, which maps to `display: none` and then works in the flat tree.

Then, should we add this property? Since descendants are not supposed to escape inertness, I guess it would be a non-inherited property that would be propagated to descendants somewhat like `text-decoration`.

CC @nt1m, @emilio, @chrishtr

**Comment by emilio** [comment]
> When discussing the `inert` attribute for HTML, there was some controversy about whether inertness should be propagated to descendants in the flat tree, or to shadow-including descendants.
> 
> @rniwa argued that semantic content attributes (like `contenteditable`, `lang`, etc.) don't use the flat tree.

FWIW I think `lang` in Gecko is implemented as a CSS property and thus would inherit in the flat tree (though interestingly we don't use the flat tree to get the language for selector-matching [here](https://searchfox.org/mozilla-central/rev/8e1eb5cbd89a2455c34032d921f8de28261d016b/dom/base/FragmentOrElement.cpp#291-313), so it's a bit inconsistent).

> @othermaciej argued that `inert` needs to operate on the flat tree to have its functional effect.

I agree, fwiw. It'd be pretty weird otherwise.

> Then, show we add this property? Since descendants are not supposed to escape inertness, I guess it would be a non-inherited property that would be propagated to descendants somewhat like `text-decoration`.

That model seems a bit unfortunate, it would cause us either having to do a tree walk at used value time to query inertness, or be one of these "not-inherited but kinda" properties that introduce special-cases in the CSS engines (like https://github.com/w3c/csswg-drafts/issues/3344).

Given there's no point in making something non-inert inside something inert (except for modal `<dialog>` I guess) I'd rather not add a CSS property, tbh.

**Comment by Loirooriol** [comment]
> it would cause us either having to do a tree walk at used value time to query inertness, or be one of these "not-inherited but kinda" properties that introduce special-cases in the CSS engines

I was imagining the implementation with two properties: one non-inherited and exposed to authors, the other internal and inherited. Setting the former would set the latter, which would be the one that actually forces `pointer-events: none` and such.

**Comment by annevk** [comment]
`lang` is discussed in https://github.com/whatwg/html/issues/4906.

I'd rather not add a CSS property until we have some more experience with the `inert` attribute.
