### ISSUE TITLE
A way of altering HEX colors lightness and opacity

### ISSUE THREAD

**Issue by mangelozzi** [w3c/csswg-drafts#7052]
There are many great features in CSS for altering color, however the one difficulty I encounter often is as follows:

Say I have a button web-component, and there are many variations. To set the background color dark on hover, one requires a lot of server side processing to do all sorts of color magic, and store all these results and inject them somehow into the CSS.

The `filter` property is great, however it can't be scoped, it is not desirable for the children of the button, its text and icons, to change color too. 

Most color systems use hexcode. I understand it is possible to use CSS properties in RGB tuples, but it is not trivial to work with.

Say I have a color #123456, and I wish to make it darker. Would be great if CSS hard a darken or lighten function, like `calc`. I am not proposing the following syntax, just giving examples of what would be nice:
E.g. `lightness(var(--mycolor), -20%)`
E.g. `alpha(var(--mycolor), 0.5)`
E.g. `calc(#123456 x 1.2)` = `#163E67`
E.g. `cat(var(--mycolor) + '80')` to half the alpha (set aplha to 0x80)

A way to change the alpha and brightness/darkness of colors would make styling framesworks so much easier to implement.

I am not sure of the syntax or how the feature would work, but being able to alter hexcolor codes would be fantastic.

**Comment by tabatkins** [comment]
And now that it's in the right place, we can close this because Color 5 already addresses it ^_^ The [relative color syntax](https://drafts.csswg.org/css-color-5/#relative-colors) can adjust any property of a color in any colorspace. All your examples can be written as:

* `lch(from var(--mycolor) calc(l * .8) c h)`
* `rgb(from var(--mycolor) r g b / calc(a * .5))`
* `rgb(from var(--mycolor) calc(r * 1.2) calc(g * 1.2) calc(b * 1.2))`
* `rgb(from var(--mycolor) r g b / 50%)`

**Comment by svgeesus** [comment]
I agree [Color 5 already addresses it](https://drafts.csswg.org/css-color-5/#relative-OKLCH) although I wasn't able to point that out when I transferred it because drafts.csswg.org was down again.

Incidentally the third example does what was asked, but not what is wanted, as it does calculations on gamma-encoded values. So 

`color(from var(--mycolor) srgb-linear calc(r * 1.2) calc(g * 1.2) calc(b * 1.2))`  or
`color(from var(--mycolor) xyz-d65 calc(x * 1.2) calc(y * 1.2) calc(z * 1.2))`

would achieve the desired result.
