### ISSUE TITLE
[css-images-4] Proposal to allow replaced elements to paint outside of their bounds

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#7058]
Context: <https://github.com/WICG/shared-element-transitions/issues/120>, where we want to snapshot an element as an image, paint it into a box of the right size, but also get the "decorations" (borders, outlines, shadows) painted outside of that box.

This seems like a useful functionality more generally, as well; in some cases you can use border-image to make an image paint "outside of" an element, but the painting area still takes up layout space (you inset from the edge of the border area, but can't go outside of it). This can allow an author to, for example, create an image with a custom glow or shadow applied, with proper ink-overflow behavior like a CSS shadow would have.

I propose we do this with two new `object-*` properties:

------------------

```
Name: object-view-box
Values: none | <length-percentage>{4}
Initial: none
Percentages: For the first and third values, relative to the object's original natural width. For the 2nd and 4th, relative to the object's original natural height.
```

`object-view-box` takes an x/y/width/height quartet of lengths, and has two effects:

* The object's "natural size" is changed to the specified width and height. (This happens before the other object-* properties take effect; they work on the new natural size.)
* The replaced content is shifted such that the point (x,y) of its paint rectangle is in the top-left of its natural size rectangle, and the point (x+width, y+height) is in the bottom-right of its natural-size rectangle.
* If this puts any pixels outside of the natural size rectangle, and object-fit/position/overflow allow for it, these pixels will be visible. (By default, the natural size rectangle exactly fills the element and is clipped to it, so any pixels outside the natural size rectangle won't be visible.)
* If the replaced content itself has its own notion of "view box" (such as SVG), this has no special interaction with it - it applies on top with the listed effects.

----------------

```
Name: object-overflow
Values: hidden | visible
Initial: hidden
```

* If `hidden`, the replaced content is clipped to the element's content box. 
* If `visible`, the replaced content can overflow the element's content-box. This overflowing content is counted as ink overflow. (To overflow, at least one of the other `object-*` properties must be in use.)

----------------

So for the use-case in the linked issue, we'd set the w/h part of object-view-box to the size of the snapshotted element, and x/y according to the amount of snapshot margin captured around it (to get shadows/etc), and set `object-overflow: visible` to let those shadow ink-overflow properly. If we then let the element size per its natural size, it will correctly take on the size of the snappshotted border box exactly, which is precisely what we want.

Thoughts? Concerns? Other possible directions?

/cc @chrishtr @jakearchibald @khushalsagar

**Comment by vmpstr** [comment]
I think this would work for both the overflowing pixels and pixels that are clipped to be smaller than the element box (e.g. with clip-path), since that allows us to capture just the bounds of the actual visible pixels and then use object-view-box to position them appropriately.

One question: presumably this has no direct interaction with something like witdth/height changes but is affected by transform changes, right? If we create an animation to change the width, we would have to create an animation to also change the object-view-box properties to change in tandem so that it looks like the element is shrinking and its drop shadow (for e.g) is changing shape but is remaining relative to the bottom right of the new element

I think that's fine, but if we can have some sort of a syntactic sugar to help, it would be awesome. Thinking out-loud: I'm thinking something like if we had object-intrinsic-size and object-view-box where the object-intrinsic-size would specify how big the replaced element naturally is and object-view-box is what you said (except that it only affects the pixel content size not the.. natural size (i fully appreciate that we might need new terminology)). Then if you do a width animation, you would note that the object-intrinsic-size doesn't match the element size anymore, and you can figure out exactly how to scale the object-intrinsic-size to make the two rects align. Then you apply that same scale to the object-view-box which should scale the pixel contents in the same way as the width animation is changing the element

Let me know if any of that makes sense and what your thoughts are

**Comment by fantasai** [comment]
> If the replaced content itself has its own notion of "view box" (such as SVG), this has no special interaction with it - it applies on top with the listed effects.

SVG has been on a quest to map all its attributes to CSS properties, why not map this to the viewbox attribute?

**Comment by vmpstr** [comment]
> presumably this has no direct interaction with something like witdth/height changes but is affected by transform changes, right?

I probably misunderstood the proposal, since I think the width/height changes will naturally change the object, by scaling its natural dimensions (subject to object-fit).

**Comment by khushalsagar** [comment]
The idea looks good. I want to reiterate to make sure I understand it correctly and also clarify how this interacts with existing sizing/positioning options of object-fit and object-position.

So for example if we have an element sized 100X200 with a 10px shadow on all edges, it's snapshot's intrinsic size is 120X220. We'd render this in a replaced element sized to 100X200 (which provides the specified size) with object-view-box: 10,10,100,200. The natural size used by the replaced element's sizing algorithm is then 100X200 and the paint content is the subset specified using object-view-box.

What happens when this image is rendered in a replaced element of specified size of 100X100 with object-fit: contain and object-position: left top? I'm assuming we'd downscale the complete image to 50X100. So now point (5,5) in the downscaled image will map to the origin of the replaced element's content-box.

**Comment by tabatkins** [comment]
> So for example if we have an element sized 100X200 with a 10px shadow on all edges, it's snapshot's intrinsic size is 120X220. We'd render this in a replaced element sized to 100X200 (which provides the specified size) with object-view-box: 10,10,100,200. The natural size used by the replaced element's sizing algorithm is then 100X200 and the paint content is the subset specified using object-view-box.

Correct.

> What happens when this image is rendered in a replaced element of specified size of 100X100 with object-fit: contain and object-position: left top? I'm assuming we'd downscale the complete image to 50X100. So now point (5,5) in the downscaled image will map to the origin of the replaced element's content-box.

Correct; that's still the edge of the element-box part of the image, with the shadow outside of that point. The view-box shifting/stretching happens before any of the other object-* adjustments.

**Comment by tabatkins** [comment]
> One question: presumably this has no direct interaction with something like witdth/height changes but is affected by transform changes, right? If we create an animation to change the width, we would have to create an animation to also change the object-view-box properties to change in tandem so that it looks like the element is shrinking and its drop shadow (for e.g) is changing shape but is remaining relative to the bottom right of the new element

You mean if you're animating the source element providing the image snapshot? Yes, you'd have to align the object-view-box on the pseudo-element hosting the snapshot to match it.

If we wanted sugar, we could invent a new "natural view-box" term (which all existing images wouldn't have), and let the snapshotting process produce an image with the natural view-box set appropriately to match the element dimensions; then we can have an `object-view-box: from-image` value just use that.

**Comment by khushalsagar** [comment]
> I'm assuming we'd downscale the complete image to 50X100.

I meant to say that the downscaled image would be 60X110 in this case with a 5px shadow around it. But I think you got it. :)

I'm also assuming that object-view-box should be a strict subset of the image's intrinsic size, since it's meant to be a subset of the image's pixels. So x/y can't have any negative values and x+width/y+height is capped to its intrinsic width/height?

**Comment by dholbert** [comment]
If the viewBox-like property here does indeed end up being an alias / override for the SVG viewBox attribute, then a few things to consider...
- we should make sure it's unambiguous what happens if you set this new property on the `img` and/or internal SVG elements in an `<img src="foo.svg">` scenario.
- There are a few other elements (beyond `<svg>`) that also accept the `viewBox` attribute.  According to https://www.w3.org/TR/SVG2/attindex.html and https://www.w3.org/TR/SVG11/attindex.html , `viewBox` applies to the `marker`, `pattern`, `svg`, `symbol`, and `view` elements.  So, we should probably be sure the new property has similar effects on those elements.

**Comment by fantasai** [comment]
@tabatkins The WG resolution said to add this to CSS Images L5, not L4. And it was said to map it to the SVG viewbox attribute, not make it similar but different. Please try to pay more attention to what you're supposed to be editing when making edits? :(
