### ISSUE TITLE
[css-contain-3] Move style() to the feature level in the grammar

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#7073]
I just wanted to check if we still want to keep `style()` at its current level in the grammar now that `size()` is removed. It is not consistent with previous choices (`@supports / selector()`), which places the function at or near the "leaf nodes". We should probably do the same for this case, i.e. `style( <style-feature> )`.

**Comment by mirisuzanne** [comment]
I think the feature is usable either way, if we decide to go that rout - but I do think there is a pretty good expectation that people will want to string together multiple style selectors, and I like that this allows it to happen inside a single function.

**Comment by mirisuzanne** [comment]
To clarify the difference here, the two options look like…

A **feature-level** syntax might be a bit simpler from the spec/implementation side:

```css
@container card-component (style(--card: feature) and style(--mode: dark)) or style(background: maroon) { … }
```

But the current **higher-level** syntax provides a bit more sugar for authors, since the function is only required once, and can contain multiple `style()` conditions:

```css
@container card-component style(((--card: feature) and (--mode: dark)) or (background: maroon)) { … }
```

My thoughts:

- My preference is for the higher-level syntax sugar, but it's not a big difference, and there's no functionality at stake
- This decision would likely apply to any new non-size features added in the future (eg 'state queries')

**Comment by andruud** [comment]
High-level syntax sugar is totally fine, but since it looks like a deviation from the pattern established by `@supports/selector()`, just making sure it's a deliberate choice, and that it still makes sense now that `size()` is gone. :slightly_smiling_face:

**Comment by mirisuzanne** [comment]
@andruud if you want to push on this more, feel free to reopen and put back on the agenda for some time you can make your case to the group?

**Comment by andruud** [comment]
Nope, it's fine. :slightly_smiling_face:
