### ISSUE TITLE
[css-cascade] Should 'revert' really treat animation origin as author origin?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7083]
https://drafts.csswg.org/css-cascade/#default

> **[author origin](https://drafts.csswg.org/css-cascade/#cascade-origin-author)**: Rolls back the [cascaded value](https://drafts.csswg.org/css-cascade/#cascaded-value) to the user level, so that the [specified value](https://drafts.csswg.org/css-cascade/#specified-value) is calculated as if no [author-origin](https://drafts.csswg.org/css-cascade/#cascade-origin-author) rules were specified for this property on this element. For the purpose of [revert](https://drafts.csswg.org/css-cascade/#valdef-all-revert), this [origin](https://drafts.csswg.org/css-cascade/#origin) includes the Animation origin.

But it's different for `revert-layer` https://drafts.csswg.org/css-cascade-5/#revert-layer

> Note: The [animation origin](https://drafts.csswg.org/css-cascade-5/#cascade-origin-animation) is not collapsed with the [author origin](https://drafts.csswg.org/css-cascade-5/#cascade-origin-author) for this purpose as it is for [revert](https://drafts.csswg.org/css-cascade-5/#valdef-all-revert), and thus effectively forms its own [cascade layer](https://drafts.csswg.org/css-cascade-5/#cascade-layers).

`revert-layer` was resolved to respect origins in #6749.

But I wonder if `revert` really needs to have this strange exception? I have tracked the origin of the text to 9fed7ff07d38d0f2c9c462d8bb2647750936086d and https://lists.w3.org/Archives/Public/www-style/2012Dec/0270.html

Note the text is old, but it's not like `revert` in `@keyframes` has much interoperability:
 - Blink implemented it in https://chromium-review.googlesource.com/c/chromium/src/+/2132249
 - WebKit just treats it as `unset`, I'm fixing it in https://bugs.webkit.org/show_bug.cgi?id=237073
 - Doesn't work in Firefox either

Having to roll back to user origin defeats some optimizations. From the Blink patch:

> the existence of the base computed style optimization makes things more complicated, as we can't use this optimization if 'revert' exists in a keyframe. (We don't even match selectors when that optimization is in use, so we wouldn't know what to revert to). In order to fix that, it's necessary to know if an ongoing animation contains a 'revert' or not, and if so disable the optimization in that case.

It's similar in WebKit, when resolving the `@keyframes` styles, it knows the base styles for the element, but not the styles for each origin. So UA and user declarations need to be recollected if there is a `revert`.

It doesn't seem a big deal, but given that removing the exception would provide some perf benefits and consistency with `revert-layer`, it may be worth it?

**Comment by andruud** [comment]
All for simplifying if it makes sense, but I just wanted to note that the Blink optimization mentioned above would still need to be disabled with this proposal. This is because the value being reverted to may be an `em` length (for example) which needs to be responsive to a simultaneous `font-size` animation.

This may make sense to do anyway of course.

We could also classify `revert/-layer` as _special_ (relevant: https://github.com/w3c/csswg-drafts/issues/7080#issuecomment-1055153925), and just make them invalid in `@keyframes`.

**Comment by dbaron** [comment]
I don't have a strong opinion on how `revert` should behave for animations.

I think when I wrote the [email in 2012](https://lists.w3.org/Archives/Public/www-style/2012Dec/0270.html), we'd spent a long time talking about origins as UA-user-author, and those origins do have value in that they reflect the [priority of constituencies](https://w3ctag.github.io/design-principles/#priority-of-constituencies).  Since then, we've moved towards a definition of origins that includes more items and more closely matches how implementations work.

I still think there's some value in aligning with the priority of constituencies.  However, I don't see a whole lot of use cases for `revert` in animations (though maybe I'm missing something), so if doing something different for animations makes things easier to implement, I think that's an entirely reasonable thing to do in order to save the implementation effort for things that are more valuable.

**Comment by Loirooriol** [comment]
It's not that it's hard to implement, it's that it can have a performance cost. Though andruud said that changing this wouldn't really optimize Blink due to `em` units. It would benefit WebKit, but WebKit doesn't handle `em` units correctly in animations. If that's fixed, changing this may not really benefit performance after all.

I'm fine with closing no change, if you think the current spec reflects better the priority of constituencies.

**Comment by dbaron** [comment]
I guess I'm still curious if anyone has concrete use cases for `revert` or `revert-layer` in animations.

**Comment by Loirooriol** [comment]
Not sure about `revert`.

`revert-layer` doesn't generally seem useful since you can just not declare the property in that keyframe. But I guess something like `var(--foo, revert-layer)` can make sense: if for some reason the variable has not been set, the property will roll back to the non-animated style, instead of becoming IACVT.

**Comment by tabatkins** [comment]
Agenda+ for resolution, since the discussion seems to have concluded.

* for `revert-layer`: suggest closing no-change. There seem to be use-cases from authors that would benefit from the currently-specified `revert-layer` behavior, and there's not a significant perf impact, per Anders/Oriol.
* for `revert`: suggest closing no-change (`revert` reverts the author-levels below the animation as well, stripping back to user origin), since this is what is already specced and implemented. Alternatively, we could sync it with `revert-layer` for convenience.
