### ISSUE TITLE
[css-values] Double bar with duplicate values

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#710]
https://drafts.csswg.org/css-values-4/#comb-any states:

`A double bar (||) separates two or more options: one or more of them must occur, in any order.`

So, if you have the syntax `a || b` then the following constructions are valid:
```
a
b
a b
b a
```

Does the "them" in "one or more of them" refer to the values or instances of values? Or, more concretely, is the following valid:

```
a a b
```

The spec could be clearer on this point.

**Comment by litherum** [comment]
cc @tabatkins @fantasai

**Comment by fantasai** [comment]
It is a combinator not a multiplier. :/

**Comment by litherum** [comment]
So `a a b` shouldn't be valid?

**Comment by tabatkins** [comment]
Correct. The pronoun's only possible referent is the "two or more options"; as stated, you choose one or more of those options, in any order. Nothing suggests allowing an option to be chosen repeatedly. (And as @fantasai implies, its placement in the "combinators" section rather than "multipliers" also further suggests that it doesn't allow multiplying a single option.)

**Comment by litherum** [comment]
I wish the spec was more explicit about this.

**Comment by tabatkins** [comment]
Are you running into problems with engineers on your team misinterpreting this? This issue is the only time we've ever heard of anyone running into trouble with it.
