### ISSUE TITLE
[scroll-animations-1] CSSNumberish time values to represent types.

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#7102]
In #6674 the rewritten API uses doubles to represent time values for many of the properties. However, the current scroll-animations-1 spec switched to using CSSNumberish in https://github.com/w3c/csswg-drafts/pull/4890 when we decided that the different time units should have different types. Using CSSNumberish allows us to avoid accidentally using one type in another context, and we can use doubles for backwards compatibility with time-based animations.

I think we should continue to use CSSNumberish (either pixels or percentages depending on which way we go on #7045) for time values on these scroll timeline animations.

**Comment by kevers-google** [comment]
Agreed, in fact the lack of units for non-scroll-linked animations has been a source of confusion for some developers who feel more comfortable working in seconds rather than milliseconds.

In sticking with CSSNumberish, we don't have to strictly limit ourselves to percentages or pixels.  If we do decide that pixels is an acceptable unit of time (not my preference), we could allow setters to use either unit provided we agree on a canonical form for the corresponding getters and have suitable conversion algorithms in place (straightforward extension of the normalization process used went updating the timeline on a previously non-scroll-based animation).

**Comment by flackr** [comment]
Another reason to use CSSNumberish is to explain why there would be an automatic conversion if you apply a scroll-timeline to an animation that has a duration in time. If we naively mix units, you would convert milliseconds to pixels which in my opinion is unexpected.

e.g.
```html
<style>
#target {
  animation: slide 2s linear;
}
.scroll-linked {
  animation-timeline: scroll();
}
</style>
<div id="target" class="scroll-linked"></div>
```

Naively, if we want `animation.currentTime` to be unit-less pixels, then we would be effectively treating each millisecond as one pixel. However, automatically converting the above animation to a 2000px scroll animation feels awkward. As a developer, I would greatly prefer the above animation either scale to fit the timeline or fail to animate 
due to an error mixing units.

**Comment by flackr** [comment]
@birtles you were instrumental in the original PR where we shifted scroll-animations to use CSSNumberish, let me know if I've missed any reasons why we should use CSSNumberish or if you think we shouldn't.

**Comment by birtles** [comment]
> @birtles you were instrumental in the original PR where we shifted scroll-animations to use CSSNumberish, let me know if I've missed any reasons why we should use CSSNumberish or if you think we shouldn't.

Hi!

I'm afraid I haven't followed too closely the API update so I don't know what would be best. Flicking through the previous discussion about this, I think some of the concerns included:

- loss of information / round-tripping if APIs return percentages resolved to absolute values (perhaps the API has changed such that this is no longer an issue?)
- precision of specifying percentages (i.e. if percentages are specified as values in the range [0, 1] you are more likely run into floating-point issues, e.g. `0.2 + 0.4 === 0.6000000000000001` whereas `20 + 40 === 60`). That said, we already use fractions like this for keyframe offsets so I guess it's not an issue.


I think it's probably helpful to think about what we want to do with **(1)** percentage-based times and **(2)** absolute-time keyframes in the future and let that inform our decision.

For example, for **(1)** I think we will want to support group effects where we specify the length of the group (e.g. 1000ms) and then define child keyframe effects that take up, e.g. 50% of that duration, and have a start delay of 25% etc. We've seen requests for that.

In that case, even for a purely time-based animation, it seems we would want to be able to support percentage-based inputs, at least. Would that suggest we should support percentage-based outputs too?

For **(2)** we've had almost the opposite request: support keyframes with absolute offsets (i.e. time values instead of percentages). See #4907 which includes samples like:

```js
document.querySelector(".box").animate([
    { offset: "0s", opacity: 1 },
    { offset: "1s", opacity: 0 }
  ]); /* No duration needed */
```

Would supporting that suggest we will end up using `CSSNumberish` in at least _some_ places in the API anyway?

It's a tough issue! I can see how the pixel-based approach feels simpler and more intuitive in some cases at least, but I wonder if the `CSSNumberish` approach might be more inline with future directions we want to take the API?

**Comment by flackr** [comment]
To attempt to summarize, this issue is about what type of value API's like `currentTime`, or the values in `getTiming` / `getComputedTiming` should return. Regardless of whether scroll linked animations return pixels or percentages, the question in this issue is whether they should be double or CSSNumericValue with the corresponding type (but fall back to double when that type is milliseconds for backwards compatibility). The [old web animations interface only supported double](https://drafts.csswg.org/web-animations-1/#the-animation-interface), but in preparation for ScrollTimeline we [updated these interfaces in web-animations-2 to return CSSNumberish](https://drafts.csswg.org/web-animations-2/#the-animation-interface).

The advantages of using double are:
* Ease of use - can be directly used in calculations
* Follows existing pattern of unit-less type for animation times in current APIs.
* No errors required as all numbers are assumed to be the same units.

The advantages of CSSNumberish are:
* Can fall back to double for backwards compatibility on time based animations.
* Avoids accidental mixing of types (e.g. anim1.currentTime = anim2.currentTime where types are not equal)
* Can support other types of time in the future (e.g. we may want a different type of timeline to use percentages / lengths)
* Allows sensible implicit conversion to [adapt a time based animation to a non-time based timeline](https://drafts.csswg.org/web-animations-2/#animations:~:text=The%20procedure%20for%20converting%20a%20is%20as%20follows).
* We will likely want to support CSSNumberish input anyways as @birtles mentioned above for offsets

I think a discussion would be really helpful to surface whether there are strong reasons for or against one or the other approach.
