### ISSUE TITLE
[css-values][cssom] Clarify: parsing missing ending parentheses with CSS functions

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#7106]
When setting a CSS function via JS that is missing its ending parentheses `)`, the value is accepted in all browsers. It is not specified anywhere to my knowledge.

For example:
`someElement.style.transform = 'rotate(45deg'` works.

If this shouldn't be valid, it should probably be fixed.
If this should be valid or we have to keep it valid for backwards compat, let's put it in the spec.

See [this codepen](https://codepen.io/noamr/pen/podYZbR)

(Apologies if this is a really old issue, please mark as duplicate of something if it is...)

**Comment by astearns** [comment]
Interesting. It works in script setting a single property, and it works (in Mac FF at least) in a style attribute if it’s the last property in the string. But it fails anywhere else in a style attribute or anywhere directly in CSS.

So I assume it’s a bug and should be fixed in each individual implementation. This does not seem to me like the kind of load-bearing quirk we would need to document. But if you have evidence that scripts rely on this behavior please let us know

**Comment by noamr** [comment]
Apparently this is mentioned in https://drafts.csswg.org/css-syntax/#consume-a-component-value and tested
😮
