### ISSUE TITLE
[css-contain-3] container :/ size

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#7142]
While it's awesome that the new `container` shorthand grammar allows for ASCII-emojis in the middle of the declaration, it has some drawbacks as well:

- An empty value is a valid declaration: `container:`. (Equivalent to `none / none`).
- Values equivalent to `none / none` (the initial values) would serialize as an empty value (e.g. via gCS) per cssom shorthand serialization algos.
- Values equivalent to `none / <something>` would serialize as a string starting with `/`, which looks very odd. (E.g. `container: / size`).

It seems more _normal_ to make the `container-name` part non-optional, i.e.:

```
  <container-name>? [ / <container-type> ]?
                  ^
                 Drop
```

**Comment by mirisuzanne** [comment]
I like this change. It further encourages naming containers, and also makes it clear that leaving a name off would set the name to `none`. If authors want to add a container-type without setting the name, we already have a longhand for that.

**Comment by mirisuzanne** [comment]
Agenda+ for a resolution

**Comment by mirisuzanne** [comment]
I (hopefully) addressed some of the confusion here in a related issue: https://github.com/w3c/csswg-drafts/issues/7180#issuecomment-1083422839

I'll also get the spec is up to date with our resolutions, which should help clarify even more…

**Comment by SebastianZ** [comment]
Copying my point from https://github.com/w3c/csswg-drafts/issues/7180#issuecomment-1082704210 over to here:

Making all values of a shorthand optional is incorrect. As @tabatkins said on the call, you might use `[ ... ]!` to force a value to be set. Though this comes with some downsides. As @andruud already pointed out, the current definition allows values starting with a slash, which is probably not something you'd expect. And _if_ the slash is meant to go away when only one value is specified, container names can clash with the container type keywords.

So, either we make the container name obligatory as @andruud wrote and which I support, or we allow to only specify a container type (without leading slash), and clarify in the prose that the container type keywords cannot be used as container names.

Regarding the slash: This could either be solved via the syntax I suggested in the other issue, or by generally implicitly omitting slashes at the beginning or end of values. I actually tend to the latter option. Therefore I created #7200 now.

Sebastian

**Comment by mirisuzanne** [comment]
To clarify: The current spec _only allows you to drop the slash_ when providing names without types, not the other way around. So the current spec does not have any clash between names and type keywords. That's what leads to the `:/` syntax currently, if you want to set _only_ a type.

**Comment by SebastianZ** [comment]
If you only want to set a type, the syntax currently allows you to skip the name completely but requires the slash. E.g. you'd have to write `/size`. `:/size` means the colon is interpreted as the container name and `size` as the container type. `:/` _alone_ is invalid as of the current syntax because if the value contains a slash, it requires to define a container type.

My point is that the current syntax definition is invalid because it allows empty values. The correct syntax definition for allowing both values to be optional would be `<'container-name'> [ / <'container-type'> ]? | <'container-type'>`. And _that_ syntax would require to define to exclude container types from names in order to allow specifying _only_ a container type. Otherwise a value like `size` or `style` would then be ambiguous.

Anyway, I think we all want the same, drop the question mark from the `<'container-name'>`, i.e. require a container name in the shorthand. This resolves the issue about empty values being valid and pushes the usage of container names.

Sebastian
