### ISSUE TITLE
[scroll-animations-1] ViewTimelineOptions dictionary should accept subject

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#7157]
The proposed rewrite in #6674 adds a ViewTimeline, which produces a time value based on an element's position within the scroller. The dictionary passed to the ViewTimeline constructor is defined as:

```
dictionary ViewTimelineOptions {
  Element source;
  ScrollDirection axis = "block";
};
```

Given that ViewTimeline extends ScrollTimeline I assume the source is the scrolling element whose scroll position is to be observed. I think the dictionary should have a subject member, to set the readonly subject attribute on the ViewTimeline.

**Comment by kevers-google** [comment]
Agreed on having subject as an option; however, it would allow us to get into an inconsistent state if subject and source are both set, since the source should be the nearest scrolling ancestor to the subject, which might not match the specified source.  Though we could make the default source the nearest scrolling ancestor and allow setting a different source.
