### ISSUE TITLE
[css-contain] container shorthand syntax is confusing.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7180]
https://andreubotella.com/csswg-auto-build/css-contain-3/#container-shorthand says:

> [<'container-name'>](https://andreubotella.com/csswg-auto-build/css-contain-3/#propdef-container-name)[?](https://andreubotella.com/csswg-auto-build/css-values-4/#mult-opt) [ / [<'container-type'>](https://andreubotella.com/csswg-auto-build/css-contain-3/#propdef-container-type) ]?

But tests expect `<container-type> [ / <container-name> ]?` which makes a lot more sense to me. Having both parts of the syntax optional doesn't really make sense to me.

cc @mirisuzanne @andruud

**Comment by SebastianZ** [comment]
And _if_ both parts of the syntax should be optional, the syntax is still incorrect.

If all parts of a group are optional but need to produce at least one value, you need to add an [exclamation mark](https://drafts.csswg.org/css-values-4/#component-multipliers), but in this case we have the slash before the second value. That would make values like `/ style` valid.

So it should be:

```
<'container-name'> [ / <'container-type'> ]? | <'container-type'>
```

Having said that, this syntax would be ambiguous as names could clash with the types. So again, _if_ container names are also be meant to be optional, the prose needs to clarify that the keywords defined for `container-type` are invalid as container names.

Sebastian

**Comment by andruud** [comment]
Duplicate? https://github.com/w3c/csswg-drafts/issues/7142

**Comment by mirisuzanne** [comment]
Yes, sorry, the spec (and tests) are out-of-date with the current resolutions (because I thought we were revisiting a decision, but then we didn't). I'll get those changes in the spec today/tomorrow. Sorry for the confusion.

In brief:
- [We resolved](https://github.com/w3c/csswg-drafts/issues/6393#issuecomment-1011283604) that the initial value of container-type is `style`, not `none`.
- In the same resolution, since both name & type are now 'optional' for a container, we swapped the order of the `container` shorthand to encourage naming containers.
- (we also swapped the order in `@container` so they would match, but then [we removed `container-type`](https://github.com/w3c/csswg-drafts/issues/6393#issuecomment-1034059934) from that syntax altogether)

So, in relation to the shorthand syntax that means currently:
- If no container-name is provided, it is set to `none` (#7142 suggests making this explicitly required)
- If no container-type is provided, it is set to `style`

**Comment by mirisuzanne** [comment]
The [Editor's Draft](https://drafts.csswg.org/css-contain-3/#container-queries) is now updated to reflect the current state of our resolutions. There are open issues for addressing the fact that both our optional (linked above), and your request to revisit the `style` initial-value. Closing as question answered for now.
