### ISSUE TITLE
[css-values-4] Clarify how slashes are used in grammar

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#7218]
There are many different syntax definitions using a slash as a separator for values that would otherwise be ambigious. Also, the existing definitions do not allow a leading or trailing slash.

Examples for that are `font`, `border-image`, `border-radius` and `grid-area`.

Though there is currently no clear definition for that.

The slash is obviously some kind of combinator literal. So I suggest to define it as such. That definition would include several things:

1. It separates two ambigious values in the given order.
2. There must always be an item on the left and right side of it, i.e. it can't be placed at the beginning or end of a value syntax. Though adjacent slashes are allowed.
3. The `/` is a literal, meaning it is part of the value.

This allows to simplify the grammar of syntaxes like `border-image`, which could then be defined as

```
<'border-image-source'> || <'border-image-slice'> / <'border-image-width'>? / <'border-image-outset'>? || <'border-image-repeat'>
```

Note, that this change is only meant to allow simplifying the grammar definitions within the specifications and to clarify when slashes are used (over other separators like commas or brackets). It is _not_ meant to touch any existing syntaxes.

Sebastian

**Comment by tabatkins** [comment]
Slash is already defined in <https://drafts.csswg.org/css-values-4/#component-types>:

> Some property value definitions also include the slash (/), the comma (,), and/or parentheses as literals. These represent their corresponding tokens. 

-----

> This allows to simplify the grammar of syntaxes like border-image, 

Our comma elision rules exist because we use commas *constantly*, and very often around optional things, such that without the rules our grammars were frequently complex and hard to read purely for technical reasons, not reflecting the actual complexity of the grammars. That said, they've still caused occasional confusion for implementors and other readers of our specs, so I don't want to introduce additional rules (especially if the're subtly different) without a clear and large value.

I don't think we're in anywhere near the same situation for slashes. Slashes are rarely used in the first place, and when they are used they're rarely paired with heavy optionality; border-image might be the only real offender here.

As such, I'm moderately opposed to adding any special rules for slash. When and if we ever start using slash heavily and in similar situations as comma, such that expressing their presence correctly frequently results in unwieldy, confusing grammars, we can fix the problem then. For now I don't think there's a reasonable justification for such, especially since they'd require subtly different rules than comma-elision.

**Comment by fantasai** [comment]
Closing as invalid, since, as Tab points out, we already define slashes as a literal. @SebastianZ Please re-open if you think there is something left to address here.
