### ISSUE TITLE
[css-ui] Should caret-color apply to any element?

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#725]
[From the text on the spec](https://drafts.csswg.org/css-ui/#propdef-caret-color):
> Applies to:	elements that accept input

I guess this include the form entries (inputs, textares, etc.), but also the `contenteditable` elements.

However, even if it's a regular element, I'm wondering if we should be able to modify the `caret-color`, for example, for caret navigation.

@frivoal what do you think?

**Comment by frivoal** [comment]
I think caret navigation is entirely unspecified, so we cannot really say much about it.
I think it would be reasonable for an implementation to apply caret-color to the navigation caret, but I would not require it.

How about making it explicit in the spec that the effect of this property on caret navigation is undefined?

**Comment by frivoal** [comment]
Agenda+ing to check with the group if this is ok to mark explicitly as undefined.

**Comment by tabatkins** [comment]
I'm not sure why we should leave this undefined.  Navigation carets are indeed undefined, but they're still *a caret*; it makes sense to me that caret-color can control that color.  (Functionally they act identically to a contenteditable caret.)

So I support defining it to be valid on all elements, perhaps with a note pointing out that navigation carets, if they exist, count as a "caret" which is affected by this property.

**Comment by frivoal** [comment]
Resolutions: 
* change the apply line to apply to all elements
* add a note to clarify that this can apply to other caret like things (like the navigation caret), but that this does not include the cursors (since people tend to confuse the two).

**Comment by tabatkins** [comment]
Suggested text of the note:

Note: UAs might have additional things that count as "carets". For example, some UAs can show a "navigation caret", which acts similarly to an insertion caret but can be moved around in non-editable text, and is functionally a caret. On the other hand, the cursor image shown when hovering over text, tho it sometimes resembles a caret, is not a caret (it's a cursor).

**Comment by frivoal** [comment]
Looks good to me. Since that text cursor is defined in the same spec though, we can augment that with hyperlinks. 

Note: UAs might have additional things that count as "carets". For example, some UAs can show a "navigation caret", which acts similarly to an insertion caret but can be moved around in non-editable text, and is functionally a caret. On the other hand, the cursor image shown when hovering over text when the 'cursor' property is ''auto'', or when hovering over an element where the 'cursor' property is ''text'' or ''vertical-text'', though it sometimes resembles a caret, is not a caret (it's a cursor).

**Comment by frivoal** [comment]
@mrego Can you please confirm you're happy with the resolution of this issue?

**Comment by mrego** [comment]
Yes, it sounds good. Thanks!
