### ISSUE TITLE
[css-scoping] [selectors] :scope and DocumentFragment / ShadowRoot

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7261]
Relevant spec sections are:

 * https://drafts.csswg.org/selectors-4/#the-scope-pseudo
 * https://drafts.csswg.org/selectors-4/#scoping-root
 * https://dom.spec.whatwg.org/#dom-parentnode-queryselector
 * https://drafts.csswg.org/css-scoping/#host-element-in-tree

If I read the specs correctly:

 1. `Element.querySelectorAll(":scope > *")` returns all the direct descendants of the given element. This is interoperable behavior and not ambiguous.
 2. `Document.querySelectorAll(":scope > *")` ought to work and return only the root element (the scoping root would be the `Document` node, and it has only one child, which is the document element). Browsers are interoperable here but not following this reasoning. Instead, `:scope` is the root element (so such a query returns the `<head>` and `<body>` elements, usually). 
 3. `DocumentFragment.querySelectorAll(":scope > *")` ought to work and return the children of the fragment, because the scoping root is the fragment, and is a virtual scoping root. This works in Blink, but not in Gecko and WebKit (`:scope` is undefined, so it falls back to the root element of the document, so it never matches anything).
 4. In style sheets, `:scope` is always the root element of the document, because there's no defined scoping node, and that's the fallback. That's Gecko and WebKit's behavior. Blink in shadow trees considers the shadow root a `:scope` (https://crbug.com/1272434), but `:scope` doesn't match the shadow host directly like `:host` does.

This is all very unfortunate and inconsistent. It's clear that the spec is wrong for the `Document.querySelector` case, IMO (though the spec doesn't define `Document` as a potential "virtual" scoping root, it follows that if such should work for `DocumentFragment` it ought to work for `Document` as well?).

We should probably agree on the non-interoperable cases. If we wanted to make `:scope` behave consistently for `Document` and `DocumentFragment`, we ought to probably either:

 * Make all direct children of the fragment match `:scope` (rather than what the spec currently says / what Blink does), or.
 * Leave the scope node undefined (which is what WebKit / Gecko does), so it always matches the root element as a fallback.

For the stylesheets case, I think WebKit and Gecko follow the spec and the spec is somewhat reasonable. We have `:host` for shadow trees, and even tho defining `:scope` is possible, it might be a bit tricky, depending on how we define the above.

Thoughts?

cc @tabatkins @lilles @anttijk

**Comment by lifaon74** [comment]
In my opinion, the `:scope` should match the node itself, even if it is virtual. So calling `:scope > *` on a DocumentFragment should returns its direct children, just as it would have happen on a HTMLElement. It solves the problem: I have a container, I want to select some of its direct children, how can I do it ? ex `:scope > scope[name="abc"]`.

Usually, the `:scope` usage is coupled with custom elements.

**Comment by emilio** [comment]
> In my opinion, the `:scope` should match the node itself, even if it is virtual. So calling `:scope > *` on a DocumentFragment should returns its direct children, just as it would have happen on a HTMLElement.

Then doing so in `Document` should select the root element for the same reasoning right? That's not how browsers behave right now.

> Usually, the `:scope` usage is coupled with custom elements.

`:host` works like you want for custom elements across all browsers afaict.

**Comment by lilles** [comment]
Reading the Selectors4 spec, it looks to me that :scope always matches a true element, even if the scoping root can be a Document or a DocumentFragment/ShadowRoot? Am I reading it correctly?

https://drafts.csswg.org/selectors-4/#the-scope-pseudo says afaict that :scope must match an element?

If so, point 2. Document.querySelectorAll(":scope > *") should return body/head because the scoping root is not an Element, hence falling back to the document root element?

**Comment by emilio** [comment]
Hmm, I guess you're right. In which case Gecko and WebKit are just right?

**Comment by astearns** [comment]
@emilio can you give an update on what we should resolve on for this?

**Comment by emilio** [comment]
It seems we all agree on the spec meaning, so I guess what's left here is landing some tests.

**Comment by lilles** [comment]
There are tests with the wrong assumptions:

https://wpt.fyi/results/css/selectors/scope-selector.html?label=experimental&label=master&aligned

**Comment by emilio** [comment]
Those come from https://github.com/web-platform-tests/wpt/pull/12252. @lilles I saw some movement in the Chromium bug, are you fixing these or do you want me to send a PR?

**Comment by emilio** [comment]
@lilles https://github.com/web-platform-tests/wpt/pull/34032

**Comment by tabatkins** [comment]
Not a ninja edit! I was applying the resolutions from #6399, as the commit message says!

Further, I don't think my edits had any impact on this thread. Can you elaborate on what you think I changed that's relevant here?

**Comment by tabatkins** [comment]
[Rune's reading](https://github.com/w3c/csswg-drafts/issues/7261#issuecomment-1121340655):

> Reading the Selectors4 spec, it looks to me that :scope always matches a true element, even if the scoping root can be a Document or a DocumentFragment/ShadowRoot? Am I reading it correctly?

Was just wrong. :scope can match a virtual scoping root, like a DocumentFragment; my #6399 edits reworded the relevant text but maintained this fact. A virtual scoping root can't be the *subject of a selector*, but that just means that `docfrag.querySelector(":scope")` won't return anything; it can still match the non-element DocumentFragment node so long as it then moves the subject to an actual element (or pseudo-element).

The relevant question for `Document.querySelector()` and `DocumentFragment.querySelector()` is just whether they pass a "scoping root" to the "match a selector" algorithm. [Per DOM](https://dom.spec.whatwg.org/#dom-parentnode-queryselector), it appears they do in both cases (since Document, DocumentFragment, and Element all share the same algorithm via the ParentNode mixin).

So following the specs as they are written today, `document.querySelector(":scope > *")` should return the `html` element, just as `myshadowroot.querySelector(":scope > *")` returns all the root nodes in the shadow tree.

**Comment by andruud** [comment]
OK, I may have been too quick to declare a ninja edit. [But hey, I got your attention :-)]. I did see the https://github.com/w3c/csswg-drafts/issues/6399 reference, but I couldn't immediately understand why some fix related to `:has()` would also (seemingly) change whether or not `:scope` _in general_ could match non-elements (subject or not).

> Rune's reading [...] was just wrong.

OK, but to be fair, Emilio and me (I remember looking at the spec at the time as well) _also_ read the old spec as ":scope matches ELEMENTS ONLY". But whatever, let's move on:

> So following the specs as they are written today, document.querySelector(":scope > *") should return the html element, just as myshadowroot.querySelector(":scope > *") returns all the root nodes in the shadow tree.

Yeah, that behavior makes sense. It's not what browsers implement though.

But this is good, it resolves another question I had about `@scope {}` (without a prelude) from a constructed stylesheet in a shadow tree. If `:scope` could _only_ match real elements, then `@scope { :scope > div {} }` could never match anything, but with the "virtual scoping root" it could be allowed to match the shadow root.

Closing the issue again, hopefully we can change implementations rather than changing the spec.

**Comment by tabatkins** [comment]
> Closing the issue again, hopefully we can change implementations rather than changing the spec.

I wrote it in an edit, but note that I think the current browser behavior (where `:scope` returns the html element, `:scope > *` returns body and head) *is* reasonable for `document`. I'd honestly prefer to fix the DOM spec there; it's a trivial edit.

But for document fragments (like shadow roots) `:scope` does indeed need to match the docfrag itself.

**Comment by lifaon74** [comment]
In my opinion, `document.querySelector(":scope > *")` should return the `document.html` element and `document.querySelector(":scope")` the `document` itself.
And `docFrag.querySelector(":scope > *")` its child elements and  `docFrag.querySelector(":scope")` the document fragment. This would allow a better consistency and natural interpretation. However, it could be a little confuse if we expect only Element or null as a return. In this case, we may consider `querySelector(":scope")`  always returning null if the parent is not an Element.

**Comment by andruud** [comment]
>> So following the specs as they are written today, document.querySelector(":scope > *") should return the html element, just as myshadowroot.querySelector(":scope > *") returns all the root nodes in the shadow tree.

> Yeah, that behavior makes sense. It's not what browsers implement though.

Actually, no, that does _not_ make sense for shadow roots, because the shadow root itself does not exist for the purposes of selector matching (when matching in the context of that shadow tree):

Scoping:

> When a selector is matched against a [shadow tree](https://dom.spec.whatwg.org/#concept-shadow-tree), the selector match list is initially the [shadow host](https://dom.spec.whatwg.org/#element-shadow-host), followed by all children of the shadow tree’s [shadow root](https://dom.spec.whatwg.org/#concept-shadow-root) and their descendants, ordered by a pre-order traversal.

Also, to reinforce that:

> For the purpose of Selectors, a [shadow host](https://dom.spec.whatwg.org/#element-shadow-host) also appears in its [shadow tree](https://dom.spec.whatwg.org/#concept-shadow-tree), with the contents of the shadow tree treated as its children. (In other words, the shadow host is treated as replacing the [shadow root](https://dom.spec.whatwg.org/#concept-shadow-root) node.)

This is aligned with the current behavior of all browsers as well. To visualize: 

If this matches:
```css
:host > div { ... }
```
then this can't _also_ match:
```css
:scope > div { ... }
```
At least not as long as `:scope` points to the shadow root.
