### ISSUE TITLE
[css-pseudo] Highlight pseudos and forced-color-adjust

### ISSUE THREAD

**Issue by dandclark** [w3c/csswg-drafts#7264]
I'd like to try to clarify how `forced-color-adjust` should apply to highlight pseudos.

In [crbug.com/1309835](https://crbug.com/1309835), @andruud raised the question of how `forced-color-adjust:preserve-parent-color` should interact with the special definition of [`currentColor`](https://drafts.csswg.org/css-pseudo-4/#highlight-text) used with [highlight inheritance](https://drafts.csswg.org/css-pseudo-4/#highlight-cascade). Normally `preserve-parent-color` has `currentColor` compute to the *used* value of the parent's color, but with highlights it's not so clear what this value should resolve to. Making it dependent on which highlight overlays are active could be problematic as that info may not be readily available until paint-time.

A simple way to resolve any strangeness could be to just treat `forced-color-adjust:preserve-parent-color` as `forced-color-adjust:none` for highlights. The [motivating use case](https://github.com/w3c/csswg-drafts/issues/6310) for `preserve-parent-color` involving SVG icons doesn't seem to be applicable to highlight pseudos as far as I can tell.

Considering things more broadly, does it make sense to allow `forced-color-adjust` in highlight pseudos at all? It is not one of the properties listed at https://drafts.csswg.org/css-pseudo-4/#highlight-styling, but Chrome allows it to be used with `::selection` and the other highlight pseudos when `--enable-blink-features=HighlightInheritance` is enabled. [Example here](https://codepen.io/daniec/pen/eYVZywZ). (When HighlightInheritance is not enabled, Chrome looks like it always ignores forced colors for `::selection` pseudos, which seems clearly wrong).

Perhaps highlights should always just use the forced-colors state of the originating element. Does it actually make sense to allow authors to opt out of forced colors for highlights but not the element containing the underlying text? Or vice versa?

cc @alisonmaher @delan @mrego

**Comment by delan** [comment]
(ping @fantasai, @frivoal)

**Comment by dandclark** [comment]
@fantasai Could you help me understand what these tags mean?
I'm guessing that `Needs Edits` means that a spec change is needed to reflect the meeting resolution, but I'm not sure about  `Closed Accepted by CSSWG Resolution`.

Sorry if these are documented somewhere; I looked but couldn't find anything.

**Comment by fantasai** [comment]
@dandclark The Needs Edits label, as you guessed, means that the spec needs edits to reflect the resolution; Closed Accepted by CSSWG Resolution means that the issue was resolved by a CSSWG decision. There's other Closed labels that reflect whether it was accepted or rejected, and what type of acceptance... these are currently only documented in https://github.com/w3c/csswg-drafts/blob/main/bin/issuegen.pl#L104 and I mainly use it as a forcing function to think about what kind of decision or review might be needed.

The resolution is now edit in as https://github.com/w3c/csswg-drafts/commit/05e463df88be8e9ac861a8a80ac68dd968080c04 ; please let me know if that reflects your understanding of the resolution of this issue! Thanks!
