### ISSUE TITLE
[css-contain] <container-name> name syntax question

### ISSUE THREAD

**Issue by matthew-dean** [w3c/csswg-drafts#7299]
Is there a reason container name uses plain identifiers and doesn't follow other CSS specs for assigning / defining arbitrary names? (Like CSS grid's `[name]` syntax). I guess I've internalized identifiers as being like an enum (a set of static values), with `[name]` being a way to define / add-to a list of identifier values, but maybe that's a mis-reading of the intent of the Grid syntax. Does CSS have an internal logic about how identifiers / names are created?

**Comment by Loirooriol** [comment]
What do you mean arbitrary? The CSS Grid grammar is

```
<line-names> = '[' <custom-ident>* ']'
```

Just idents, so e.g. `[ 5af ]` is invalid. Of course, you can use escaping in idents, so they can end up having pretty arbitrary data. But that should also be the case for `<container-name>`.

**Comment by mirisuzanne** [comment]
Closing this for now as question-answered - @matthew-dean feel free to re-open if that doesn't answer the question fully.

**Comment by tabatkins** [comment]
Right, the Grid thing is a completely novel thing we dont' use anywhere else, just because we need a way to group together a set of N possible line-names. That is, the `[]` are a grouping syntax, not part of the name. (You can write `[foo bar baz]` to give the line three names, for example.)

We *do*, on a case-by-case basis, use `<dashed-ident>` (like `--foo`) for author-defined identifiers, particularly when they're going to mix with language-defined keywords (either in the same value space, like for color space names, or just in a grammar where it's possible to create ambiguous parses). But there's no hard-and-fast rule about when we use `<dashed-ident>` versus just a `<custom-ident>`.

**Comment by matthew-dean** [comment]
@tabatkins Ah, good points / clarification. Thanks!
