### ISSUE TITLE
[css-fonts-4] error in example 81 for `@font-palette-values`

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#7309]
In the examples for the [`@font-palette-values` rule](https://drafts.csswg.org/css-fonts-4/#font-palette-values), I think Example 81 has a mistake: it includes the fragment
```
@font-palette-values --ToxicGreen {
  font-family: Bungeehee;
  base-palette: 7; /* This is Bungeehee’s green palette... */
  2: lime; /* ...except this is pink, which I overwrite to lime */
}
```
which (if I'm understanding correctly) is lacking an `override-colors` descriptor. (Perhaps it reflects an earlier version of the rule?)

**Comment by cdoublev** [comment]
(I was looking for related issues.) Fixed in https://github.com/w3c/csswg-drafts/commit/3d1ac3cfd08e8b3a0e2033f1846c8b463999fd77 after https://github.com/w3c/csswg-drafts/issues/6916#issuecomment-1240684141.

<sup>I guess it can be closed as ***Closed Accepted as Editorial*** but I would not be comfortable taking on this responsibility.</sup>
