### ISSUE TITLE
[cssom-view] Rename Element.isVisible to Element.isHidden?

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#7317]
In Issue #6850 we decided to add [`isVisible`](https://drafts.csswg.org/cssom-view/#dom-element-isvisible). Should we rename it to `isHidden` and flip the return value?

The only difference I can see is that it flips what is considered a "positive" result, and therefore maybe developers would be less likely to misinterpret the results. i.e. developers might interpret `isVisible` as a stronger assertion from the browser than "not `isHidden`". Since `isVisible` does not actually mean "guaranteed to be visible right now to the user", maybe `isHidden` is better?

**Comment by yisibl** [comment]
How about `isCSSHidden`?

**Comment by ziyunfei** [comment]
> How about `isCSSHidden`?

inert isn't about CSS, and an off-document element also not hidden by CSS.

**Comment by manuelmeister** [comment]
What does isHidden do? I'm not sure what this would return on sr-only elements.

**Comment by tabatkins** [comment]
Twitter polls are weak evidence, but [my poll](https://twitter.com/tabatkins/status/1532138513704943617) seemed to record a pretty strong (3:1) preference for `isVisible()`, with 29 votes.

**Comment by vmpstr** [comment]
To me, this isn't just about the name but what information the function is providing.

`isVisible`: We check a fixed, not necessarily comprehensive, set of conditions (opacity is 0, visibility is not visible, etc) and if none of those conditions are true, then we seemingly jump to the conclusion that the element must be visible -> return true
`isHidden`: We check the same fixed set of conditions and if none of those conditions are true, we say that _as far as we know_ this element is not hidden, but we're not promising that it's visible -> return false

Am I reading too much into the name?

**Comment by vmpstr** [comment]
Maybe a better options is having a neutral name, something like `checkVisibilityState` with possibly a non-optional dictionary which would return a string/enum indicating the result of requested checks. This is obviously less ergonomic, but maybe less confusing

**Comment by tabatkins** [comment]
This function is not, strictly, telling you whether the element is hidden *or* visible, since it also cares about the inert state (and previously, and perhaps in the future, about other things beyond visibility).

But yes, I think you're reading too much into it. ^_^ Neither "isVisible" nor "isHidden" are more or less authoritative-sounding than the other; the fact that in either case we have to mean "as far as we can tell, using some relatively limited tests" is equally apparent (or not) in either.

I don't think a less ergonomic version is any better, especially if it continues to just return two values. That's just a less convenient version of a bool, for no benefit afaict. And I don't think returning an object with bools for each possible test is worthwhile; that just means authors now have to write code to coalesce those results into a single boolean. It doesn't help them at all, since if they wanted individual test results they can ask for them via the options argument already, potentially via separate calls if they want to check multiple things. All this does is make the common case more annoying.

**Comment by Loirooriol** [comment]
Some comments mention inert, but #7274 resolved to remove that.

**Comment by heycam** [comment]
`element.isHidden()` is pretty similar to `element.hidden`, and these are different things. I think there is a chance of confusion between the two.

**Comment by vmpstr** [comment]
There is also IntersectionObserver v2 which has [isVisible](https://w3c.github.io/IntersectionObserver/v2/#dom-intersectionobserverentry-isvisible) which disallows false positives but allows false positives. The proposed isVisible here would compute a different value, allow false positives and disallow false negatives

Admittedly, it's not on the element interface so maybe that's ok

**Comment by vmpstr** [comment]
To summarize, the current options that we’ve seen are the following:

* isHidden - current name
	* May be confused with Element.hidden attribute
	* Tab’s twitter poll indicates that isVisible is more preferred
	* Semantically, it would have no false positives but may have false negatives
* isVisible
	* May be confused with IntersectionObserver’s isVisible
	* Preferred in Tab’s twitter poll
	* Semantically, it would have false positives, but no false negatives
* checkVisibility
	* Is not biased towards “is visible” or “is hidden”
	* Unclear about the return value: boolean may not be the best fit
	* Maybe return HiddenByX vs Unknown enums, which may be less ergonomic
* computeVisibility
	* Same arguments as checkVisibility, just different name

For posterity, Jen’s twitter poll seems to be mixed with roughly similar support for both isHidden and isVisible.

Are there other suggestions?

**Comment by foolip** [comment]
@vmpstr for `isVisible`, I think your observation in https://github.com/w3c/csswg-drafts/issues/7317#issuecomment-1149949799 is also relevant. That's an attribute on another interface, but has the opposite behavior in terms of false positives/negatives.

**Comment by vmpstr** [comment]
Since there hasn't been much engagement here so far, maybe we can emoji-vote on the existing proposed names? And please comment with other suggestions if you can think of something better

👍 - isHidden
😄 - isVisible
🎉 - checkVisibility
❤️ - computeVisibility
🚀 - checkVisibilityState

**Comment by chrishtr** [comment]
`checkVisibility` has 8 votes and in the clear lead. I propose we resolve with that name and close the issue.

**Comment by alystair** [comment]
Where do I go to see actual spec discussion? I accidentally came across the `checkVisibility` function whilst playing around in Chrome Canary and noticed (what I feel is) a false positive.

When an element is styled with
```css
pointer-events: none;
visibility: hidden;
content-visibility: hidden;
```
and its width/height are 0px, it seems nonsensical to me that the function returns true. I'd think 0px would signify no visibility?

**Comment by josepharhar** [comment]
> Where do I go to see actual spec discussion?

https://github.com/w3c/csswg-drafts/issues/6850#issuecomment-1011300312
https://github.com/w3c/csswg-drafts/issues/7317#issuecomment-1144232411
https://github.com/w3c/csswg-drafts/issues/7317#issuecomment-1150123208

> I'd think 0px would signify no visibility?

I'm not sure if 0x0 sized elements were ever discussed in the spec, but yes that is considered visible by checkVisibility because checkVisibility does not look at the actual size of the element.

`content-visibility: hidden` only makes child elements hidden, so if you call checkVisibility directly on an element with `content-visibility: hidden` it will be considered visible.

`visibility: hidden` is only checked for if you explicitly ask like this: `element.checkVisibility({checkVisibilityCSS: true})`

**Comment by tabatkins** [comment]
> Where do I go to see actual spec discussion?

You're looking at it!

> it seems nonsensical to me that the function returns true. I'd think 0px would signify no visibility?

A 0x0 element can still absolutely be visible, for example if it has `outline` or `box-shadow`.

Now, your specific example includes `visibility:hidden`, which *would* make the element invisible (suppressing the effect of outline/etc), and this can be activated with the `.checkVisibility({checkVisibilityCSS:true})` option. We don't include this by default because the most common type of "invisibility" is actually avoiding generating any boxes (such as by `display:none`), and whether or not you want to include other types (like `opacity` or `visibility`) isn't something we can reliably infer one way or the other, so instead we give you the option.

**Comment by alystair** [comment]
Thanks for the clarification! My source of confusion likely stemmed from not spotting the options list. I guess discoverability via the DevTools console can't be underestimated :^)

**Comment by smfr** [comment]
How does `checkVisibility` relate to Intersection Observer's [`trackVisibility`](https://w3c.github.io/IntersectionObserver/v2/#dom-intersectionobserver-trackvisibility)?  Ideally they would use identical underlying concepts so an implementation could share code.
