### ISSUE TITLE
[css-text] text-align-last: match-parent; is not well defined

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#7331]
It's not clear what `text-align-last: match-parent` should do from a web developer perspective, and also ambiguous how this should work on the `:root` element. Can this be clarified in the spec?

**Comment by nt1m** [comment]
Fwiw, no browser supports `text-align-last: match-parent`.

@fantasai Do you know where this was added?

**Comment by Loirooriol** [comment]
Isn't this defined in https://drafts.csswg.org/css-text/#valdef-text-align-match-parent ?

> This value behaves the same as [`inherit`](https://drafts.csswg.org/css-cascade-5/#valdef-all-inherit) (computes to its parent’s computed value) except that an [inherited value](https://drafts.csswg.org/css-cascade-5/#inherited-value) of [`start`](https://drafts.csswg.org/css-text/#valdef-text-align-start) or [`end`](https://drafts.csswg.org/css-text/#valdef-text-align-end) is interpreted against the parent’s (or the [initial containing block](https://drafts.csswg.org/css-display-3/#initial-containing-block)’s, if there is no parent) [`direction`](https://drafts.csswg.org/css-writing-modes-3/#propdef-direction) value and results in a computed value of either [`left`](https://drafts.csswg.org/css-text/#valdef-text-align-left) or [`right`](https://drafts.csswg.org/css-text/#valdef-text-align-right).

The behavior would be like for `text-align-all`, but for the last line.

**Comment by nt1m** [comment]
> Isn't this defined in https://drafts.csswg.org/css-text/#valdef-text-align-match-parent ?
> 
> > This value behaves the same as [`inherit`](https://drafts.csswg.org/css-cascade-5/#valdef-all-inherit) (computes to its parent’s computed value) except that an [inherited value](https://drafts.csswg.org/css-cascade-5/#inherited-value) of [`start`](https://drafts.csswg.org/css-text/#valdef-text-align-start) or [`end`](https://drafts.csswg.org/css-text/#valdef-text-align-end) is interpreted against the parent’s (or the [initial containing block](https://drafts.csswg.org/css-display-3/#initial-containing-block)’s, if there is no parent) [`direction`](https://drafts.csswg.org/css-writing-modes-3/#propdef-direction) value and results in a computed value of either [`left`](https://drafts.csswg.org/css-text/#valdef-text-align-left) or [`right`](https://drafts.csswg.org/css-text/#valdef-text-align-right).
> 
> The behavior would be like for `text-align-all`, but for the last line.

That's for `text-align`. What is the parent of the last-line?  Also it doesn't explain why the computed value of `match-parent` is as specified for `text-align-last`, but not `text-align` (where `match-parent` computes to `left`/`right`).

**Comment by Loirooriol** [comment]
> That's for `text-align`.

But in the spec `text-align` is a shorthand, so `text-align: match-parent` just sets `text-align-all: match-parent` and `text-align-last: match-parent`. Defining values in shorthands seems confusing to me, but it also happens e.g. in https://drafts.csswg.org/css-overflow/#propdef-overflow

> What is the parent of the last-line?

It's not the parent of the last line. If the block container is element-generated, then it's the parent element of the element that generates that block container. If it's anonymous, it's the parent box of the block container (see https://drafts.csswg.org/css-display-3/#anonymous).

The root element has no parent. So the inherited value is the initial value, `start`, which is then resolved using the `direction` of the initial containing block, which per https://drafts.csswg.org/css-display-3/#containing-block is the `direction` of the root element itself. Not sure if this is the computed or the used value, which may be different due to https://drafts.csswg.org/css-writing-modes-4/#principal-flow. Whatever happens, it should be analogous for `text-align-all` and `text-align-last`.

> Also it doesn't explain why the computed value of `match-parent` is as specified for `text-align-last`, but not `text-align`

Yeah, I guess `text-align-last` should also say "Computed value: keyword as specified, except for match-parent which computes as defined above".

**Comment by fantasai** [comment]
@nt1m Given Oriol's explanations and the edits, do we need any further edits here?

**Comment by nt1m** [comment]
Sounds good.
