### ISSUE TITLE
[css-variables] custom property cycles not updating according to specs.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [w3c/csswg-drafts#7336]
https://drafts.csswg.org/css-variables/#cycles

Imagine a scenario where you're setting up the main color of a site:
```
:root{
  --maincolor-h: 193;
  --maincolor-s: 66%;
  --maincolor-l: 53%;
  --maincolor: hsl(var(--maincolor-h), var(--maincolor-s), var(--maincolor-l));
}

button.button-a{
  background-color: var(--maincolor)
}

button.button-b{
  background-color: hsl(var(--maincolor-h), var(--maincolor-s), var(--maincolor-l))
}

button:hover{
  --maincolor-l: 75%
}
```
now i imagine if i were to change --maincolor-l the background color of both buttons would change, but as it is implemented right now, only the background-color of .button-b would change.
https://codepen.io/sunturion/pen/rNJKzZY

Im not sure whether this is intended, or if its a browser implementation issue, but as i read the specs, it seems to me like this is supposed to work.

**Comment by Loirooriol** [comment]
This is per spec. `--maincolor` computes to `hsl(193, 66%, 53%)` on `:root`

> Computed value: specified value with variables substituted, or the guaranteed-invalid value

And then that's the value that will be inherited by descendants. Changing `--maincolor-l` on a descendant has no effect since it has already been substituted on `:root`. You can workaround this by setting `--maincolor` on all descendants:

```css
:root, :root * {
    --maincolor: hsl(var(--maincolor-h), var(--maincolor-s), var(--maincolor-l));
}
```

Adding a better mechanism to cover your usecase is already tracked in #2749
