### ISSUE TITLE
[css-color-5] Mixing `<number>` and `<percentage>` in non-legacy `<rgb()>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7363]
The current value definition of [`<rgb()>`](https://drafts.csswg.org/css-color-5/#funcdef-rgb) is:

> `rgb( [<percentage> | none]{3} [ / [<alpha-value> | none] ]? ) | `
> `rgb( [<number> | none]{3} [ / [<alpha-value> | none] ]?`
> `rgb( [ from <color> ]? [ <number> | <percentage> | none]{3} [ / [<alpha-value> | none] ]?  )`

I think only the last line should remain.

Also discussed in #7338.

**Comment by svgeesus** [comment]
That one is odd, agreed, but deliberate, and an attempt at backwards compat.

The first two lines are CSS Color 4 formats (without `from <color>`) and require either three `number` or three `percentage`. The third line is Relative Color Syntax, and we allowed  `number` and `percentage` to be freely mixed there (because people kept mixing them in examples).

However, given that these are all the non-legacy comma-less form, and given that `none` was a relatively late addition, I am not sure that this is really buying us much in terms of Web compat or browser compat.

@tabatkins @LeaVerou @argyleink @una thoughts?

**Comment by argyleink** [comment]
I could understand the first 2 being removed also, as the 3rd seems encompassing of the syntax options. Alternatively, I could see the first two being moved into an aside and provided as simpler, less feature rich and legacy, versions of the syntax for those looking for it?

**Comment by cdoublev** [comment]
My immediate concern is is the missing `) |` at the end of the second line.

**Comment by LeaVerou** [comment]
> I could understand the first 2 being removed also, as the 3rd seems encompassing of the syntax options. Alternatively, I could see the first two being moved into an aside and provided as simpler, less feature rich and legacy, versions of the syntax for those looking for it?

That would mean things like `rgb(255 40% 100%)` are valid. Do we want that?

**Comment by romainmenke** [comment]
> That would mean things like rgb(255 40% 100%) are valid. Do we want that?

Tools like VSCode actually already support this by accident.
These support percentage values but don't check that all values use the same unit.

<img width="216" alt="Screenshot 2022-06-16 at 11 33 48" src="https://user-images.githubusercontent.com/11521496/174040747-df5f8402-6ff4-4ef9-820c-0c3ba2802a1e.png">

- some color functions already have mixed units and `var()` `calc()`
- `var()` and `calc()` can obfuscate units

These things considered I think it will help stylesheet authors if mixed units are just supported.

**Comment by svgeesus** [comment]
> That would mean things like `rgb(255 40% 100%)` are valid. Do we want that?

However, RCS already allows `rgb(from black 255 40% 100%)` (where the 'from black' does nothing and is not used in the computation).

**Comment by cdoublev** [comment]
Closing in favour of #8231.
