### ISSUE TITLE
[css-contain-3] Should style() queries allow !important flag?

### ISSUE THREAD

**Issue by lilles** [w3c/csswg-drafts#7413]
According to the current draft[1], the syntax for style features are the same as for declarations which means !important is allowed as part of the feature. I don't think that would have an effect, but would it still make sense to change the syntax to not allow it?

[1] https://drafts.csswg.org/css-contain-3/#style-container

**Comment by frivoal** [comment]
In the case of `@supports`,
> A trailing !important on a declaration being tested is allowed, though it won’t change the validity of the declaration.

I suspect we may want to do the same here: allow the `!important` syntactically, but ignore it. That way, we're consistent about the allowed syntaxes in the places that let you give a declaration for the sake of checking something rather than for declaring something. That said, if people feel strongly about disallowing it, that seems ok too.

**Comment by fantasai** [comment]
Disagree in the case of @supports. You're doing a syntax "is it supported" check there, and !important is arguably part of it.

**Comment by lilles** [comment]
FWIW, I'm fine with closing this as no change. I have changed our implementation to allow !important and adjusted the WPTs accordingly to match the current spec.

**Comment by mirisuzanne** [comment]
Sorry for that noise. I was clicking badly. Meanwhile, I agree with the general (though incomplete) consensus here that `!important` should be allowed and ignored. Proposing we close this wontfix.

**Comment by lilles** [comment]
I agree that we should just close this. I have updated our impl to match the current spec and allow !important in style() query values.

**Comment by lilles** [comment]
Proposed resolution: no change

**Comment by astearns** [comment]
@tabatkins @fantasai would you be OK with a resolution of no change here?

**Comment by LeaVerou** [comment]
> Sorry for that noise. I was clicking badly. Meanwhile, I agree with the general (though incomplete) consensus here that `!important` should be allowed and ignored. Proposing we close this wontfix.

Another vote for this.

**Comment by tabatkins** [comment]
I have no strong opinion, so I'm fine with an async resolution in either direction.

**Comment by fantasai** [comment]
Ditto @tabatkins. I personally think it doesn't belong as part of style() syntax, but if there's a convenience to allowing it I don't see it as problematic.

**Comment by astearns** [comment]
Since this has consensus here in the issue we likely do not need to spend meeting time on it.

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: No Change

**Comment by astearns** [comment]
RESOLVED: No change
