### ISSUE TITLE
[css-values-3] Restrict none/auto/normal from <custom-ident>

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7431]
We often use these keywords in grammars, so @tabatkins suggested we blanket-restrict them the same way we do all the global keyboards (initial/inherit/etc.)

**Comment by tabatkins** [comment]
Okay, at least for most of these the CSS is already invalid and/or useless. In particular, the CSS counter `auto` appears to not do anything (it looks like they were intending it to be `none`, maybe?).  I can't find the usage of a `none` grid line on the first page listed, so it must be buried in one of the many, many additional requests. (And haven't looked in the others.) Without seeing it, tho, it really seems weird to have a line named `none`, and I suspect it's an attempt to say `[]` - no grid line names.

So, uh, seems like we're pretty reasonably compatible?

**Comment by tabatkins** [comment]
Agenda+ to discuss this change

**Comment by tabatkins** [comment]
After the discussion today, I no longer think this is needed. The breakage potential seems higher than I initially thought, and the use-cases less important - generally, new APIs should use dashed-ident rather than custom-ident anyway. (And if it's safe to use custom-ident because it wont' mix with other keywords, like grid line names, then it's safe to name them none/auto/normal as well.)
