### ISSUE TITLE
[css-margin-block-start] Margin-block-start takes hidden elements into account causing empty space

### ISSUE THREAD

**Issue by LukaszJaro** [w3c/csswg-drafts#7480]
For example, <template> tag or hidden div above a element which has margin-block-start applied to it causing empty white space.

![image](https://user-images.githubusercontent.com/10998875/178027845-9358a4b1-fde7-46a2-8709-18991766dbd7.png)

Not expecting hidden elements to be taken into account when using margin-block-start?

https://docs.w3cub.com/css/margin-block-start

**Comment by Loirooriol** [comment]
What do you mean "takes hidden elements into account"? `<template>` has `display: none` by default, so it's not laid out. And if you set `display: block`, the margin will typically collapse thru.

Getting empty space is normal since you are adding some margin? If you want margins between siblings but not before the 1st box, there is [`margin-trim: block-start`](https://drafts.csswg.org/css-box-4/#margin-trim).
