### ISSUE TITLE
[css-shared-element-transitions-1] Video elements and transition screenshot?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#7555]
What happens to video elements during the locked phase of the transition? (when rendering is prevented by the `prepare` promise)

If a screenshot is made and it takes a couple of frames before the transition starts, this could result in issues. But I can imagine that if the video is a livestream, stopping the video is not great either. This could potentially be left to the authors to solve, but I was wondering if there is some reasonable default here.

Some videos are also rendered fully on the compositor thread, is this an issue?

**Comment by khushalsagar** [comment]
@FremyCompany this was discussed as a part of #7784. The video element in particular came up during the discussion (captured in the meeting notes). The conclusion was to pause the video, just like other animations on the page. Otherwise there is an odd jump from the last rendered video frame to the last snapshotted frame when the transition starts.

Can we close this issue given the resolution on #7784?

**Comment by FremyCompany** [comment]
Yes, I wanted to raise this so it was thought about, glad you have reached a conclusion here that's consistent with other types of animations.
