### ISSUE TITLE
[scroll-animations-1] `scroll-timeline` and `view-timeline` shorthand syntax

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#7627]
The syntax for [the `scroll-timeline` shorthand](https://drafts.csswg.org/scroll-animations-1/#scroll-timeline-shorthand) is defined as such:

```css
scroll-timeline: <'scroll-timeline-axis'> || <'scroll-timeline-name'>
```

The syntax for [the `view-timeline` shorthand](https://drafts.csswg.org/scroll-animations-1/#view-timeline-shorthand) is defined as such:

```css
view-timeline: [<'view-timeline-name'> || <'view-timeline-axis'>]#
```

It’s odd that the `scroll-timeline` has the name mentioned first, while in `view-timeline` it is the axis. Even though the order of both does not matter – due to `||` – I would like to see these listed in the same order for consistency reasons.

---

Going further, maybe we should disallow reordering the values? There is precedent to have the `*-name` first: [the `container` shorthand](https://www.w3.org/TR/css-contain-3/#propdef-container) has the `container-name` first and then the `container-type`.

```css
container: <'container-name'> [ / <'container-type'> ]?
```

Maybe we can update the `scroll-timeline` and `view-timeline` shorthands to follow the form of the `container` shorthand? Like so:

```css
scroll-timeline: <'scroll-timeline-name'> [ / <'scroll-timeline-axis'> ]?
```
```css
view-timeline: [<'view-timeline-name'> [ / <'view-timeline-axis'> ]?]#
```

**Comment by andruud** [comment]
Yeah, it's weird that the order is reversed. Is that intentional @fantasai?

Especially since we don't disallow block/inline/etc from &lt;custom-ident>, so:

- `view-timeline:block` creates a timeline named `block`, with the default axis.
- `scroll-timeline:block` creates no timeline, since it has no name.

See also https://github.com/w3c/csswg-drafts/pull/7694 (which doesn't address the ordering, but it's related).

**Comment by fantasai** [comment]
Pretty sure that's not intentional, I agree we should fix it to be consistent.

**Comment by fantasai** [comment]
@bramus Flipped ordering of scroll-timeline as you suggested. I agree we should discuss fixing the ordering, since reorderability is creating an unfortunate parsing ambiguity here. :(

**Comment by cdoublev** [comment]
After reading [this thread](https://lists.w3.org/Archives/Public/www-style/2012Sep/0393.html), I wonder if `none` could not be further restricted to be used alone in `transition` and `view-timeline`.

> First, animation-name: none is basically a special value for
disabling an animation or set of animations; there's really no
reason to use it with a list, only on its own, since when
animation-name is none all the other properties are irrelevant.

Would there be a reason to use `transition: none 1s;` or `view-timeline: none inline`?

`animation: none 1s` would still have to be valid because `none` must be assigned to `animation-fill-mode`.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/c57ee4f2be513edcb89974c0f861578d7b13c551
