### ISSUE TITLE
!important is not important!

### ISSUE THREAD

**Issue by trusktr** [w3c/csswg-drafts#7650]
I never knew until now that `!important` on a property inherited by a higher parent does no override the same property inherited from a lower parent. It was not what my intuition expected.

Example:

https://codepen.io/trusktr/pen/abYPpGO

I thought all the text would be `deeppink`.

Should there be a solution to this?

**Comment by dbaron** [comment]
[I was surprised](https://groups.google.com/g/netscape.public.mozilla.layout/c/5HPmBm8I_m0/m/BqnTPPSqVcoJ) when I first learned of this as well.  (The more relevant parts of the thread aren't properly archived, though!)

**Comment by Loirooriol** [comment]
You can use `#one, #one *` to also set the important value to all descendants.

**Comment by tabatkins** [comment]
Right, !important solely affects the cascade algorithm for the element the style is applied to; inherited values continue to act as normal regardless of what cascade origin/etc they were generated from. This is almost always what you want; the various inputs to the cascade (specificity, origin, importance, etc) are rarely what you want for determining *all* style resolution, or else you'd have to make all your styles increasingly specific as you target things further down the tree.

Since there's a trivial way to get this effect when you *do* want it (append `" *"` to your selector to spam it onto all children), I'm going to close this issue.
