### ISSUE TITLE
[css-anchor-1] Need ability to say "don't render" when anchor is off-screen

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#7758]
Consider: an anchor is inside of a scroll container. The positioned element is outside of the scroll container. This is legit if you want the positioned element, when visible, to be able to project outside of the scrollable area, such as into the margin.

However, this then means that if the anchor is scrolled outside of the scrollport, the positioned element just hovers above or below the scroll container, wherever the anchor is theoretically positioned. That is *almost certainly* not what you want!

So we should have some way to specify that if the anchor is off-screen, the positioned element should hide itself.

Questions:
* What does "hide itself" mean? display:none? visibility:hidden? I suspect just visibility should be used, so it still has a meaningful position and can, say, be scrollIntoView()'d.
* What anchor do we care about if you use multiple anchors? I think the right answer might be if *any* anchor is off-screen it should trigger.
* Does this need to be controllable? This probably needs to activate by default, but are there good reasons to have an anchored element continue to show up when its anchor is off-screen?
* Maybe this only activates when there is a scroll container between the anchor and the positioned element? When the positioned element is inside the same scroll container, it'll hide itself naturally due to the scroller, and being able to show up as you scroll *near* the anchor (rather than suddenly popping in when the anchor comes on-screen) seems good.

**Comment by tbondwilkinson** [comment]
I think JUST add display:none could be jarring as anchors scroll in and out of the viewport. 

From an Open UI perspective for `popup=hint`, it might be better to trigger a hide event when anchors scroll out of the visible content, rather than hiding and reshowing.

It might be hard to guess what a good default would be for this, hiding is not a bad idea.

Another thought is that maybe sometimes people will want the anchored element to be clipped by the scroll container rather than hidden?

**Comment by tabatkins** [comment]
> I think JUST add display:none could be jarring as anchors scroll in and out of the visible content.

It could be, or could not be, depending! If your anchors purposely hang out outside of the scroller, tho, you've gotta do *something* when the anchor is out of the viewport.

> From an Open UI perspective for popup=hint, it might be better to trigger a hide event when anchors scroll out of the visible content, rather than hiding and reshowing.

I haven't dug deeply enough into OpenUI - can you give me a pointer to hide event stuff? 

> Another thought is that maybe sometimes people will want the anchored element to be clipped by the scroll container rather than hidden?

You can achieve this by putting the positioned element in the same scroller as the anchor.

**Comment by clshortfuse** [comment]
Just saw the blog on this and was concerned about this, watching them overlayed outside the container. My custom anchor system uses `InsersectionObserver`:

https://github.com/clshortfuse/materialdesignweb/blob/d4aad60b14b4820d4b7ae207f78653f9a5b33b5d/mixins/TooltipTriggerMixin.js#L61-L86

`this` is the the anchor. If the anchor is less than 50% visible, I close the tooltip. Automatic handling is neat, but I think `InsersectionObserver` would handle it. Now if we're saying over CSS, then that's something else...

**Comment by xiaochengh** [comment]
I have a proposal that's built on top of #8724, which if resolved will allow us to specify a bounding box (not just the CB in positioned layout) for position fallback.

Then we can have a new property that controls what to do when the anchored element ends up overflowing that bounding box:

```css
position-fallback-overflow: clip | visible
```

`clip` means the anchored element should be clipped by the bounding box. `visible` means no such clipping.

The initial value is `clip`.

---

Discussion:

1. I think using the position fallback bounding box is more natural than checking whether the anchor is off screen (or off any box). And it doesn't have any issue with multiple anchors.

2. Clipping seems to provide a better/smoother UX than hiding & showing. User probably don't want to see the element suddenly disappear when something is just slightly off screen.

3. The UX can be even smoother if we have #8200

4. Clipping seems more friendly to the rendering pipeline than hiding/showing, because we are just introducing a clip box.

5. Agreed that it should be activated by default. But it might be just safer to also provide an opt-out. (and it also means I don't need to massively rewrite all the existing WPT)

6. I don't think it should fire any event on its own. `IntersectionObserver` should be good enough, at least for now.

**Comment by tabatkins** [comment]
This is an *excellent* argument, and a great idea. Yeah, I think being able to clip to the box that you're using for overflow bounds sounds great.

Not sure we should default to `clip`, tho - allowing the element to extend out of the element by default seems fine. Like, a tooltip should be able to poke out a bit. In particular, I think that the behavior if you get it wrong is better if we default to `visible`: if you *mean* to clip and forget it's probably pretty obvious in common cases (you'll have things floating in space randomly on the page), while if we default to clip and you *mean* to use `visible` that's only obvious if the element happens to get positioned near the edge so it overflow a little bit. Plus in general it better fits our "fail visible/open" policy in CSS - you should usually design defaults so that if the author doesn't think about it the content is still visible, even if it makes the page ugly.

Okay, so I'm inclined to just go ahead and edit in #8724 and this one. I'll review #8200 as well to see if I want to go ahead and pull it in, too.

**Comment by tabatkins** [comment]
Or hm, maybe we should act as 'clip' if you have a specified -fallback-bound element, and visible if you don't. So the initial value should be an 'auto'.

**Comment by xiaochengh** [comment]
I found a real use case for the `visible` value: https://floating-ui.com/docs/autoPlacement

We can achieve the same by:
- Using a small `position-fallback-bounding-box` at the center of the viewport 
- Setting `position-fallback-overflow: visible`
- And https://github.com/w3c/csswg-drafts/issues/8200

**Comment by clshortfuse** [comment]
Would `visible` that also allow replicating this? 

https://github.com/w3c/csswg-drafts/assets/9271155/0360aa7b-b4e8-4c37-a0c5-341cd353c3dc

**Comment by xiaochengh** [comment]
@clshortfuse

This looks like a different thing, which is closer to Floating UI's [shift](https://floating-ui.com/docs/shift) that tries to keep the element in the bounding box without switching position; while this issue is about what to do when it's overflowing the bounding box.

And we don't have full support for `shift` yet. I have a [hacky demo](https://jsfiddle.net/3xytvL5h/), but it doesn't work with `position: fixed`, so it probably doesn't work for popovers.

**Comment by tabatkins** [comment]
Thinking about this more as I try to write it up - rather than clipping to the overflow box, would it make more sense for the default to be "clip to the bounds of every scroller between you and the specified anchor"?

In particular, if there are *two* scrollers between your CB and your anchor, and the innermost has the anchor in the scrollport but the outer has the entire inner scroller out of the scrollport, you still want to clip, I assume. If we rely on just the overflow box, even if you specify an additional one with anchor-overflow-bounds, it won't be able to capture both boxes.

**Comment by xiaochengh** [comment]
I feel like we may still want some consistency between here and #8724. If we use a box for overflow clipping, we would very likely also want to use the same box to trigger position fallback.

Then everything gets really complicated if we need to consider a chain of clipping boxes. Imagine if someone wants to use the intersection of the ancestor scrollers of the anchor to trigger position fallback...

I don't have a good idea towards this direction. Some thoughts are:
- Maybe we can clip with the position fallback bounding box + any ancestor clipping boxes of the PFBB?
- How to opt-out if there are many clipping boxes? All or nothing? Or is there a way to opt out just some clipping boxes?

**Comment by tabatkins** [comment]
> If we use a box for overflow clipping, we would very likely also want to use the same box to trigger position fallback.

Yeah, I definitely agree. I'm talking about an *additional* clip - in addition (and maybe by default?) clip to the scrollers between the anchor-scroll element and them as well.  Multiple values for the clipping property (which we should move to an `anchor-*` name rather than `position-fallback-*` name, probably `anchor-clip`).

Like, `anchor-clip: none | [ fallback || scroll ]`? Meaning "clip to the position-fallback-bounds elements and/or the scroll containers of the scroll-anchor element". Initial value `scroll`? Or maybe `none`, hm.

> Imagine if someone wants to use the intersection of the ancestor scrollers of the anchor to trigger position fallback...

I don't think *fallback* with the scrollers is necessary; the intermediate scrollers don't have any particular reason to be *layout-relevant* to the positioned element, they're just ways to hide the anchor and thus things that the positioned element probably wants to be hidden by as well.

**Comment by xiaochengh** [comment]
`anchor-clip: none | [ fallback || scroll ]` SGTM

**Comment by xiaochengh** [comment]
@wangxianzhu 

I'd like to get your input here. Do you think `anchor-clip: scroll` is implementable?

In particular, for each anchor-positioned element, we need to duplicate a bunch of clip nodes from the ancestor scrollers of the anchor.

**Comment by xiaochengh** [comment]
Discussed with @wangxianzhu offline. This should be implementable in Chromium

The solution doesn't involve duplicating any clip nodes, but we can simply make `PaintPropertyTreeBuilder` switch to the scroller's clip state for the target element, so there's no performance issues either.

**Comment by xiaochengh** [comment]
A slightly revised idea: `anchor-clip: auto | none`, where
- `auto` is the default value, meaning it should be clipped by all ancestor clip boxes of the default anchor<sup>1</sup>
- `none` means no clipping, same as before

There's a possibility that in the future, this gets extended into `anchor-clip: auto | none | fallback | <anchor-element>`, meaning this element should be clipped by all ancestor clip boxes of the target element of the value, and the impl should be pretty similar. Or even extended into a multi-value syntax. But everything feels like YAGNI at least for now.

Also `auto` feels much easier for people to use, although it's semantically the same as `scroll` you suggested previously

<sup>1</sup> Note that we no longer have a separate `anchor-scroll` element due to #8675

**Comment by xiaochengh** [comment]
I'm wondering if the default value should be `auto` or `none`. Maybe `none` is better.

It's pretty common to have a scroller with `overflow: auto`, which doesn't show a clear clip boundary to users when the content doesn't overflow. However, it should still apply clipping for `anchor-clip: auto`, which can be quite confusing to users, and developers may actuall want the positioned element (e.g. a tooltip) to overflow such a scroller.

On the other hand, it can be less confusing when the default value is `none`, so that developers can opt-in when they need clipping.

**Comment by kizu** [comment]
I would say that in my experiments I, sometimes, wanted to have the `auto`, but mostly wanted the `none` (the current behavior).

Also, I imagine clipping would also work for `overflow: hidden`, and that could mean that clipping by default could lead to the content being not accessible if it would go beyond the overflow of such elements.

**Comment by clshortfuse** [comment]
I've coded my tooltips to be a psuedo top-layer, so they break through their anchor's boundary. For example, this is anchor to the button, but overlays above the Nav Drawer and its scrollbar on the left:

![image](https://github.com/w3c/csswg-drafts/assets/9271155/8771381c-d452-44a4-9d21-c63571459f58)

I can simulate a clip by dropping the z-index:

![image](https://github.com/w3c/csswg-drafts/assets/9271155/0fd5a75f-c8b6-48b3-a25c-563e958ad28c)

An example of "don't render" because the anchor is off-screen is applicable to what I call "semi-sticky" toolbars, where it scrolls aways on scroll down, but stickied on scroll up. If the keyboard is focused on a toolbar button, the tooltip is shown. But when the toolbar button is no longer more than 50%, then it meets my custom threshold of being "off-screen" and I close the tooltip. 

![image](https://github.com/w3c/csswg-drafts/assets/9271155/edefb476-a710-4934-8f7a-2e6e180a8925)

And mid-hide when scrolling down:

![image](https://github.com/w3c/csswg-drafts/assets/9271155/2837797f-28d1-4ee0-a8d8-504508f0766f)

The consequence of not doing this is the issue we know where a tooltip can appear when it shouldn't:

![image](https://github.com/w3c/csswg-drafts/assets/9271155/196ff405-14be-4308-a980-76b8b0df818f)

I'm using intersection observer on the anchor as well as on the tooltip itself. Because the tooltip isn't useful without what it's giving a tip for, I want it on the anchor. But there could be an instance where the tooltip gets occluded (eg: forced position) and then I want it to hide instead of reposition when partially occluded.

I'm unsure what `anchor-clip` means here. Is it when the anchor (eg: the button) is clipped? Or do we mean to clip the tooltip? Is my terminology wrong? Is "anchor" the button or tooltip here?

**Comment by tabatkins** [comment]
Yeah, it basically gives you back the clipping that you would have if your positioned element was an abspos next to the anchor. Being able to have your positioned element elsewhere in the page is a big part of what makes anchor positioning powerful.

> Also, I imagine clipping would also work for overflow: hidden

Yes, overflow:hidden is a scroller so it would act identically to overflow:scroll.

**Comment by yisibl** [comment]
> And we don't have full support for shift yet. I have a [hacky demo](https://jsfiddle.net/3xytvL5h/), but it doesn't work with position: fixed, so it probably doesn't work for popovers.

@xiaochengh  Will `css-anchor` consider implementing a shift effect in the future?

**Comment by xiaochengh** [comment]
@yisibl Yes, but I don't have a clear idea how it should work. Anyway, it's better to file a separate issue for it.

**Comment by khushalsagar** [comment]
How do non-trivial clips like clip-path/border-radius behave? Implementation wise it seems like unless its simple rects (which can be collapsed) it'll be very difficult.

**Comment by vmpstr** [comment]
It also wasn't clear whether the desire is to have the anchored element be clipped by the (immediate or all?) scroller(s) or whether any ancestor clip should play a part, including things like overflow-clip-margin

**Comment by fantasai** [comment]
Tab was just describing[ this proposal](https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1626355764) to me, and I think... I can't see any use case for wanting to anchor to an object that's been scrolled completely outside its scroll container.

What you want is to be able to use the intersection of that scroll container and the anchor element inside it as the anchor box, and to hide the anchorpos when the anchor box clips down to zero.

**Comment by tabatkins** [comment]
Okay so while it's good that we got a resolution to do *something* in this space, we still need to work out details.

As far as I can see, there are two independent cases we might want to address:

1. Clip as if you're sitting next to your anchor. That is, use *precisely* the clipping that your anchor does, so there's no difference in clip behavior between "popup is next to the anchor in the markup" and "popup is somewhere unrelated in the markup", or between "popup is using abspos" and "popup is using fixpos/top layer".
2. Hide yourself when your anchor is clipped away. For example, a sidenote displaying alongside a scrollable region of text can't reuse the clip area like in (1), since it's positioned outside the scrollport bounds already, but it still wants to stop rendering when the anchor is scrolled out of the scrollport. Possibly we want to differentiate between "anchor starts to get clipped by something" and "anchor is fully clipped away". Probably we want to use the anchor's border box; I doubt this needs to be controllable.

(2) *might* be most simply solved by allowing a positioned element to be clipped by its inset-modified containing block? The sidenote case, for example, would look like:

```css
.sidenote {
  position: fixed;
  top: anchor(--container top);
  bottom: anchor(--container bottom);
  left: anchor(--container right);
  right: 0;
  anchor-default: --target;
  align-self: anchor-center;
  clip-to-containing-block: true;
}
```

This does rely on `anchor-center` for positioning, tho; if you wanted any other alignment you'd be out of luck, since you're having to use your top/bottom to give yourself clipping bounds. It also relies on the scroll container having an anchor-name, rather than just relying on the nearest scroll container of the default anchor, which is probably what you want. So probably we do instead want to more explicitly reference the bounds of some scroller, defaulting to the default anchor element's nearest scroll container, like:

```css
.sidenote {
  position: fixed;
  anchor-default: --target;
  top: anchor(top);
  left: anchor(--container right);

  /* vertically clips to the bounds of the default anchor's nearest scroller */
  position-clip: vertical;

  /* inline-axis clips to the specified element, which must be a scroller */
  position-clip: inline --some-container;
}
```

Hmm. More thought is needed here.

**Comment by fantasai** [comment]
For the first case, we might be able to solve by simply saying that when your containing block is the scroller (or inside it) then you get clipped just like the contents of that scroller. See #9868. Then we can just have the second case be the behavior in all other cases.

**Comment by fantasai** [comment]
Tab and I discussed the uses cases in this issue and #9380 and tried to come up with a proposal to handle them all. There are a few major cases to address:

1. Make a positioned element act like it's inside its anchor's scroller (clipped by the intervening scrollers). This is already proposed to be handled by `position-container`. See [earlier comment](https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1935048879) and [issue 9868](https://github.com/w3c/csswg-drafts/issues/9868).
2. Make the positioned element act like it's outside the anchor's scroller (as normal), but hide itself if the anchor would be clipped away by the intervening scrollers. (Doesn't make sense to display the positioned element if its anchor isn't visible.) See [Tab's comment](https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1931019866).
3. Make a positioned element hide itself if all of its `position-try-options` result in overflow. See [issue 9380](https://github.com/w3c/csswg-drafts/issues/9380).


Our current suggestion for handling both 2 and 3 is a new `position-visibility` property:

```
position-visibility: always | [ anchors-valid | anchors-visible ] || no-overflow
```

* `always` is the initial value; the abspos is always visible (as currently)
* `anchors-valid` hides the abspos if any of the anchors it depends on are missing. Absposes depend on their default anchor element and any anchor element referenced in an `anchor()`/`anchor-size()` function without a fallback value.
* `anchors-visible` hides the abspos if any of the anchors it references are missing or invisible (and it hasn't explicitly specified a fallback value), where invisible means either its not `visibility: visible` or it's been clipped by `overflow` of an intervening container. (We're also considering `clip-path` for this check.)
* `no-overflow` hides the abspos if it overflows its inset-modified containing block (after exhausting all `position-try` options, if relevant). Note this value would apply even when using regular abspos or fixedpos.

In all these cases, “hide” means that it (and all of its contents) are invisible (like ''visibility: hidden'') and do not contribute to scrollable overflow.

**Comment by tabatkins** [comment]
Currently the definition is up in the air. I agree we should be consistent with VT (and scroll animations?).

**Comment by kizu** [comment]
> In all these cases, “hide” means that it (and all of its contents) are invisible (like ''visibility: hidden'') and do not contribute to scrollable overflow.

One thing that we will need to handle: make the `position-visibility` transition in the same way as `visibility` itself, from [Web Animations spec](https://www.w3.org/TR/web-animations/#animating-visibility):

> For the [visibility](https://www.w3.org/TR/css-display-3/#propdef-visibility) property, [visible](https://www.w3.org/TR/css-display-3/#valdef-visibility-visible) is [interpolated](https://www.w3.org/TR/css-values-4/#interpolation) as a discrete step where values of p between 0 and 1 map to visible and other values of p map to the closer endpoint; if neither value is visible then [discrete](https://www.w3.org/TR/web-animations/#discrete) animation is used.

- - -

A related note: if the `position-visibility` will not work in the same as `visibility` in a “can be overridden on a child” way, this new property could be used as a hack for “non-overridable” visibility (given the element is abspos). If this will be the case, we could want to think about introducing a new keyword to `visibility` itself that will make it possible to achieve the same effect (making it non-overridable on the children). I wrote [an article on visibility](https://kizu.dev/restoring-visibility/) at some point, and I remember encountering use cases for this behavior (but that is probably better to open as a separate issue if there is no such yet).

- - -

All of that said, would it be possible to somehow make it apply the `visibility` itself? It will make things a lot simpler from the author standpoint.

**Comment by chrishtr** [comment]
> In all these cases, “hide” means that it (and all of its contents) are invisible (like ''visibility: hidden'') and do not contribute to scrollable overflow.

I think we should amend it to remove the part about not contributing to scrollable overflow. Here's why:

* Making it no longer contribute to scrollable overflow would require layout effect being in response to scroll or try-block layout+style effects, for the `no-overflow` and `anchors-visible` keywords. This would either be circular or introduce the potential for significant complexity in the layout and style engine.

* Anchored elements will need to avoid causing layout overflow for their containing blocks anyway, or else there would be useless scrollbars for that element even when the anchored element is not hidden.

I'm good with the `position-visibility ` proposal @fantasai wrote with this small change, and think it is easily implementable.

**Comment by tabatkins** [comment]
The adjustment is currently specified as an additional translate, so without further specification it would have the same behavior as translations, which do affect overflow. But we can change that.

**Comment by khushalsagar** [comment]
@fantasai @tabatkins should I file a separate issue to clarify how we decide whether the anchor is offscreen? This [comment](https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1912799837) suggested taking an intersection of the scroll container with the anchor element but its unclear what the reference box is (border box or ink overflow rect). And also why use the nearest scroll container instead of the viewport, what happens if the scroll container itself is offscreen. Would love to get a common definition of whether an element is onscreen since VT needs the same concept.

**Comment by chrishtr** [comment]
> how we decide whether the anchor is offscreen?

I think we should use the same definition as IntersectionObserver viewport visibility. That is simple, consistent, makes it easy for implementations to use that to hide or show the anchored element, and at least one developer mentioned on this issue they already use this definition in their polyfill.

**Comment by khushalsagar** [comment]
IntersectionObserver has a [mode](https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo) to check occlusion. I'm assuming we're not including that here?

**Comment by chrishtr** [comment]
> IntersectionObserver has a [mode](https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo) to check occlusion. I'm assuming we're not including that here?

Correct, we would not use that mode. We'd just use the one that applies clips and filters, not the "v2" one.

**Comment by wangxianzhu** [comment]
> We'd just use the one that applies clips and filters

Currently IntersectionObserver v1 doesn't respect filters, see https://github.com/w3c/IntersectionObserver/issues/509 and https://crbug.com/40937025. However, internal intersection observers respect filters to follow the corresponding specs (e.g. [contents-visibility](https://drafts.csswg.org/css-contain-2/#:~:text=If%20a%20filter)). We may need to either resolve this discrepancy in intersection observer spec or specify we need to consider filters here in css-anchor-1.

**Comment by khushalsagar** [comment]
> We'd just use the one that applies clips and filters

The algorithm [here](https://w3c.github.io/IntersectionObserver/v2/#calculate-intersection-rect-algo:~:text=Let%20intersectionRect%20be%20the%20result%20of%20running%20the%20getBoundingClientRect()%20algorithm%20on%20the%20target.) uses the result of `getBoundingClientRect()` as the element's box to intersect against. IIUC that's based on border box so won't include overflow from filters like blur. If you want to include filters, wouldn't using the element's ink overflow rect be better?

**Comment by chrishtr** [comment]
> The algorithm [here](https://w3c.github.io/IntersectionObserver/v2/#calculate-intersection-rect-algo:~:text=Let%20intersectionRect%20be%20the%20result%20of%20running%20the%20getBoundingClientRect()%20algorithm%20on%20the%20target.) uses the result of `getBoundingClientRect()` as the element's box to intersect against. IIUC that's based on border box so won't include overflow from filters like blur. If you want to include filters, wouldn't using the element's ink overflow rect be better?

I suggest we take this particular point to the Intersection Observer spec.

**Comment by tabatkins** [comment]
> And also why use the nearest scroll container instead of the viewport, what happens if the scroll container itself is offscreen. Would love to get a common definition of whether an element is onscreen since VT needs the same concept.

What we want is that the element is clipped away "entirely", by some combination of overflow clip rects (and maybe other clipping operations?). This should include all the scroll containers up to the nearest inclusive ancestor of the positioned element's own containing block, at least; higher than that and you're already guaranteed that both elements are getting clipped by the same scroll container, so there's no need to specially care about them.

As for what precisely to consider "the box" that is getting clipped, I agree we should defer to what IO/etc are doing for consistency.

**Comment by wangxianzhu** [comment]
> I suggest we take this particular point to the Intersection Observer spec.

I think we still need to address the filter issue here. See #issuecomment-1994974242.

**Comment by wangxianzhu** [comment]
> One thing that we will need to handle: make the `position-visibility` transition in the same way as `visibility` itself, from [Web Animations spec](https://www.w3.org/TR/web-animations/#animating-visibility):

Do we need to handle the transition of actual visibility (not the value of `position-visibility` property)? This seems only feasible if the spec defines a new `visibility` value and lets the UA update the value of `visibility` when the visibility requirement of the anchored element changes.

**Comment by wangxianzhu** [comment]
> * `no-overflow` hides the abspos if it overflows its inset-modified containing block (after exhausting all `position-try` options, if relevant). Note this value would apply even when using regular abspos or fixedpos.

Can you clarify which of the following of the abspos should be used to check if it overflows its inset-modified containing block?
1. the padding box;
2. the unclipped scrollable overflow;
3. the ink overflow.

**Comment by wangxianzhu** [comment]
During the implementation of `anchors-valid` and `anchors-visible`, I found the following things may need clarification about validity/visibility of anchors:
1. Is an anchor valid or visible if
   - it has `display: none`,
   - it's under `content-visibility: hidden`, or
   - it's under `content-visibility: auto` and is currently not rendered.
Our current plan is to treat them as invalid because the anchor doesn't exist in the layout tree.

2. For validity of anchor references,
   - should we iterate all CSS properties to find invalid anchor references? For example, is `border-width: anchor(--a top)` an invalid anchor reference or should it be ignored?
   - should we check the validity of anchor references from unused `@position-try` styles?
   - should an anchor reference with missing default anchor (e.g. `width: anchor-size(width)` without a default anchor) be treated as invalid or be ignored?
   - should we check the validity of anchor references from `anchor-size()`?
Our current plan is to only check for validity and visibility for anchor references that are actually resolved, but not including those in unused `@position-try`s.

**Comment by wangxianzhu** [comment]
Besides the questions in the above comment, actually we are also considering a different interpretation for `anchors-valid` and `anchors-visible`:
- `anchors-valid`: hides the abspos if its position is not anchored to any anchor. ...
- `anchors-visible` hides the abspos if its position is not anchored to any anchor, or all position anchors are invisible. ...

`anchor-size()` will be ignored because it doesn't directly affect positioning.

This interpretation may be better because:
- It seems to reflect the intention better;
- It seems easier to define, understand and implement.

**Comment by wangxianzhu** [comment]
Another thing needing clarification: If an anchored element with `position-visibility: anchors-*` has chained anchors (like the case in #9071)
```
  <div id="anchor" style="anchor-name: --a"></div>
  <div id="chained-anchor" style="position-anchor: --a; anchor-name: --b; ..."></div>
  <div id-"anchored" style="position-anchor: --b; position-visibility: anchors-visible"></div>
```
Should `anchored` check visibility of all anchors in the anchor chain?

A simple interpretation may be like
- Visibility of `anchored` depends on `chained-anchor` only.
- If `chained-anchor` also has `position-visibility: anchors-visible`, then visibility of `anchored` will indirectly depend on `anchor` through the visibility of `chained-anchor`.

**Comment by tabatkins** [comment]
> Is an anchor valid or visible if
> * it has display: none,
> * it's under content-visibility: hidden, or
> * it's under content-visibility: auto and is currently not rendered.

None of those are valid; they all fail to be [acceptable anchor elements](https://drafts.csswg.org/css-anchor-position/#acceptable-anchor-element), so an anchor function that would only be referencing those is not a [valid anchor function](https://drafts.csswg.org/css-anchor-position/#anchor-valid), because finding the target anchor element returns nothing.

> For example, is border-width: anchor(--a top) an invalid anchor reference or should it be ignored?

This also fails to be a [valid anchor function](https://drafts.csswg.org/css-anchor-position/#anchor-valid), and thus is ignored.

> should we check the validity of anchor references from unused @position-try styles?

No, only the styles actually being used should be considered.

> should an anchor reference with missing default anchor (e.g. width: anchor-size(width) without a default anchor) be treated as invalid or be ignored?

That's similarly not a [valid anchor function](https://drafts.csswg.org/css-anchor-position/#anchor-valid), because finding the [target anchor element](https://drafts.csswg.org/css-anchor-position/#target-anchor-element) returns nothing.

> should we check the validity of anchor references from anchor-size()?

Hmmmmm. I initially thought yes, it should match anchor(), but on further consideration I think it's reasonable to *not* check those. The whole point of the hiding behavior is to allow an element that's positioning relative to an anchor to not hover over a nonsense position when the anchor is outside the scrollport, but *sizing* is different. Being able to match the size of an anchor even before the anchor is visible seems reasonable, and virtually every use-case I can think of is *also* going to be using anchor() anyway. Whatever cases exist where you want to match an anchor's size without caring about the anchor's position *at all*, I suspect those probably *want* to be visible regardless.

Worst case, you can always smuggle in an explicit anchor() to trigger the hiding behavior. (Change your `top: 20px;` to `top: calc(20px + anchor(--foo)*0);` to get identical behavior but with an anchor reference.)

> actually we are also considering a different interpretation for anchors-valid and anchors-visible:

I think what you're describing here matches the answers I provided above? It sounds to me like you're just reiterating the basic behavior that was already described, but I assume since you were asking the previous questions y'all were starting from a slightly different idea of what the behavior was supposed to be. Assuming this is the case, it looks like y'all are settling on exactly what I'm already intending to write into the spec. ^_^

> Should anchored check visibility of all anchors in the anchor chain?

I think not. Your "simple interpretation" seems correct to me - while you can end up *indirectly* depending on the first abspos's anchors (if that abspos also uses position-visibility), your direct dependencies should only be the anchors you're explicitly using.

**Comment by wangxianzhu** [comment]
Thanks tabakins for the clarifications.

> This also fails to be a [valid anchor function](https://drafts.csswg.org/css-anchor-position/#anchor-valid), and thus is ignored.

My understanding is that invalid anchor functions are ignored instead of directly falsifying `anchors-valid` or `anchors-visible` to make the anchored element invisible. An anchored element with `anchors-valid` is visible if it has at least one valid anchor function [1]. Does this understanding align with yours?

For `anchors-visible`, if there are multiple anchors referenced from valid anchor functions, should we require all or at least one of these anchors to be visible [2]?

> The whole point of the hiding behavior is to allow an element that's positioning relative to an anchor to not hover over a nonsense position when the anchor is outside the scrollport

As we do scroll adjustment [scroll adjustment](https://www.w3.org/TR/css-anchor-position-1/#scroll) only if the default anchor exists:
[1] Should we use the conditions of scroll adjustment as the preconditions of `anchors-valid` and `anchors-visible`?
[2] Should `visibility-visible` just check the visibility of the default anchor (which is our current basic implementation)?

**Comment by tabatkins** [comment]
> An anchored element with anchors-valid is visible if it has at least one valid anchor function [1]. Does this understanding align with yours?

In [the proposal](https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1965540529), we're saying it should hide if *any* of its anchors are invalid/invisible (and the anchor function doesn't have a fallback).

> Should we use the conditions of scroll adjustment as the preconditions of anchors-valid and anchors-visible?

I'm not sure what this means. Could you elaborate?

> Should anchors-visible just check the visibility of the default anchor (which is our current basic implementation)?

Hm, that's a good question. Since we only adjust for the scroll position of the default anchor, that might make sense. @fantasai, thoughts?

**Comment by wangxianzhu** [comment]
> This also fails to be a [valid anchor function](https://drafts.csswg.org/css-anchor-position/#anchor-valid), and thus is ignored.

> In https://github.com/w3c/csswg-drafts/issues/7758#issuecomment-1965540529, we're saying it should hide if any of its anchors are invalid/invisible (and the anchor function doesn't have a fallback).

Does "invalid" mean an anchor function is not a [valid anchor function](https://drafts.csswg.org/css-anchor-position/#anchor-valid)? If yes, should invalid anchor functions like
- `border-width: anchor(top)`
- `top: anchor(left)`
- `top: anchor(top)` without a default anchor

cause the anchored element with `anchors-visible` or `anchors-valid` to hide, instead of being ignored? If we ignore them, then in what conditions an anchored element with `anchors-valid` should hide?

> I'm not sure what this means. Could you elaborate?

I mean whether we should check the two conditions listed under "An absolutely-positioned element query el **needs scroll adjustment**" in [Taking Scroll Into Account](https://www.w3.org/TR/css-anchor-position-1/#scroll):
- query el has a [default anchor element](https://www.w3.org/TR/css-anchor-position-1/#default-anchor-element).
- At least one [anchor()](https://www.w3.org/TR/css-anchor-position-1/#funcdef-anchor) function on query el’s used ...

I'm asking because `anchors-visible` and `anchors-valid` seem to be meaningful only if the anchored element needs scroll adjustment.

If we check these functions, the anchored element with `anchors-visible` and `anchors-valid` will hide e.g. if there is not a default anchor.

**Comment by progers** [comment]
The latest [spec draft](https://drafts.csswg.org/css-anchor-position-1/#position-visibility) currently specifies `anchors-visible` as:
> If the element has a [default anchor element](https://drafts.csswg.org/css-anchor-position-1/#default-anchor-element) but the anchor element is [clipped by intervening elements](https://drafts.csswg.org/css-anchor-position-1/#clipped-by-intervening-elements), this element is also [strongly hidden](https://drafts.csswg.org/css-anchor-position-1/#strongly-hidden).

@fantasai's original proposal would also consider visibility of the anchor element. Can this be added back with: "If the element has a [default anchor element](https://drafts.csswg.org/css-anchor-position-1/#default-anchor-element) but the anchor element is [clipped by intervening elements](https://drafts.csswg.org/css-anchor-position-1/#clipped-by-intervening-elements) **or the anchor element is not visibility: visible**, this element is also [strongly hidden](https://drafts.csswg.org/css-anchor-position-1/#strongly-hidden)."?

Should `anchors-visible` also consider whether the anchor element itself is strongly hidden? This is useful for nested anchor scenarios.

**Comment by tabatkins** [comment]
Ooh, yeah, that makes sense.

I don't think we should tie it to visibility in general, at least not without further discussion (there are many ways to be invisible, after all), but in the "chained anchor" case, hidden-ness should indeed propagate, I think.

**Comment by wangxianzhu** [comment]
Should we rename `anchors-visible` to `anchor-visible` as only the default anchor's visibility matters?

**Comment by progers** [comment]
> Can anyone provide an example for how to make appear/leave transitions or animations work? And do I understand correctly that this is not possible as of yet?

I don't think this is possible yet, see: https://github.com/w3c/csswg-drafts/issues/10182
