### ISSUE TITLE
[css-nesting-1] Move to FPWD

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#7796]
With the resolution of #4748, the nesting syntax is basically decided. I'd like us to move to FPWD for nesting to put it on the standards track.

https://drafts.csswg.org/css-nesting-1/

**Comment by fantasai** [comment]
I'm in favor of moving to FPWD. It's clear we have consensus on moving forward with Nesting in general.

I do think there are some serious problems with the syntax that need to be worked out, though, and I'd like to see this marked clearly as an issue in the draft. I'll file a follow-up issue on it, but discussing it with @LeaVerou, the short version is:
* incompatibility with syntax outside of nested context and with syntax within `@scope` invites a lot of copy-paste errors, and
* the requirement to include `&` within all the selectors in a list (instead of allowing relative selectors) is annoying to type, easy to forget, and makes automated conversion of existing code much more difficult (requires selector parsing rather than regex).

So I think we have some more work to do here, and I'd like to make that clear in the FPWD. That said, I support FPWD.

**Comment by fantasai** [comment]
Looks like we already have an FPWD: https://www.w3.org/TR/css-nesting-1/

**Comment by fantasai** [comment]
Btw, I do think there are some serious problems with the syntax that need to be worked out, and I'd like to see that marked clearly as an issue in the draft. I'll file a follow-up issue on it later, but discussing it with @LeaVerou, the short version is:
* incompatibility with syntax outside of nested context, and with syntax within `@scope`, invites a lot of copy-paste errors
* the requirement to include `&` within all the selectors in a list even beyond disambiguation (instead of allowing relative selectors) is annoying to type, easy to forget, and makes automated conversion of existing code much more difficult (requires selector parsing rather than regex).

So even if we're not adopting the nested-bracket syntax proposed in #4748, I think we still have more design work to do here.

**Comment by LeaVerou** [comment]
To follow up on @fantasai's comment above, at first I rejected discussion saying we have explored the design space, and resolved there's nothing better than the current proposal, but after some discussion, I’m convinced she's right that there's more design work to do here, ideally to figure out a way to switch to rule parsing mode within a rule that doesn't involve editing every single selector. We already have relative selectors in `:has()` and `@scope` and should probably follow the same pattern here, rather than having an entirely different type of relative selector.
