### ISSUE TITLE
[css-view-transitions-1] Should isolation and plus-lighter blending be applied conditionally

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#7814]
The default animation in shared element transitions can have either of the following trees per tag:

## Cross-fade
```
::page-transition-container
|_::page-transition-image-wrapper
    |_::page-transition-incoming-image
    |_::page-transition-outgoing-image
```

There is visual state for an element in both outgoing and incoming DOM. The 2 have a cross-fade and need `isolation: isolate` on the wrapper and `mix-blend-mode: plus-lighter` on both the images to the blending right.

## Enter animation
```
::page-transition-container
|_::page-transition-image-wrapper
    |_::page-transition-incoming-image
```

There is visual state only for an element in the incoming page which fades in.

## Exit animation
```
::page-transition-container
|_::page-transition-image-wrapper
    |_::page-transition-outgoing-image
```

There is visual state only for an element in the outgoing page which fades out.

It's unclear how best to handle `isolation` and `mix-blend-mode` for the 3 cases:

1. Technically we don't need the `isolation` and `mix-blend-mode` properties in enter/exit animations. These were also causing sub-optimal rendering (in Blink) because the fact that they are no-op isn't always optimized out. So we could omit adding them in these 2 modes.
2. Always add them to these elements to ensure developers see a consistent style. Optimize out their effect in the implementation.

Option 1 is always better perf wise though it can be optimized if needed. I'd err for that unless there is a good reason to have option 2.

**Comment by jakearchibald** [comment]
Summary for CSSWG:

We use `mix-blend-mode: plus-lighter` on the old & new views, plus `isolation: isolate` on the image-pair, in order to create a true cross-fade.

Isolation isn't free performance-wise.

Some transition groups only have an old view, or only new view. This happens when an element with a particular `view-transition-name` only exists on one side of the transition. Isolation is unnecessary in these cases.

## Option 1: Apply isolation & blend mode styles only when both old & new views are present

This would be observable in `getComputedStyle`.

It would also result in a different rendering if the developer gives the image-pair a background color, since some contents will plus-lighter blend with that background, and others wouldn't. However, if you set a background on the image-pair, it like that you'd want to set blending to normal anyway.

We already apply lots of styles dynamically in a view transition, such as width, height, transform etc of transition groups.

## Option 2: Optimise internally for cases where isolation and blending is unnecessary

`getComputedStyle` would still see isolation and plus-lighter, but the rendering engine would avoid rendering to another buffer in cases where doing so would have no visual effect.

It's unclear how tricky this would be.

**Comment by khushalsagar** [comment]
Discussed this offline again, the summary above is great. Adding what came up at the last discussion.

Option 2 will need to be done anyway for cases like [this](https://developer.chrome.com/docs/web-platform/view-transitions/#transitioning-without-freezing). In this case the author is adding `view-transition-name` for elements in both the old and new DOM, since they want a size/transform animation. But they're setting `opacity: 0` on the old image because the content hasn't changed. In fact they want the live animating new image instead of a cross-fade. In this case the engine will set up all the isolation and mix-blend-mode styles for cross-fade anyway and would have to detect that only image is actually being rendered so this blending can be optimized.

The worry is still that while the UA can optimize the default entry/exit transitions, authors might add styles (like `background`) which will require the expensive blending without realizing it. Since it comes from rules in the UA CSS. On the flip side, if normal blending is incorrect for them, they would discover that and add the requisite blend-mode/isolation (same as the regular DOM rendering).

So the proposal is to go with option 1. This is also in the spec already [here](https://drafts.csswg.org/css-view-transitions-1/#:~:text=Set%20capturedElement%E2%80%99s%20image%20pair%20isolation%20rule%20to%20a%20new%20CSSStyleRule%20representing%20the%20following%20CSS%2C%20and%20append%20it%20to%20document%E2%80%99s%20view%20transition%20style%20sheet). Adding this for async resolution.

**Comment by astearns** [comment]
I am reluctant to resolve on this without some agreement from others who have more expertise in animations and transitions than I have. Could you solicit opinions from outside your team before we try for an async resolution?

**Comment by khushalsagar** [comment]
@flackr was present in the discussion I summarized above for animations/transitions expertise. @rcabanier for compositing/blending expertise since that's what we're trying to decide here: what should be the default isolation/blending on the pseudo-DOM generated by the UA if we don't need a cross-fade as described [here](https://jakearchibald.com/2021/dom-cross-fade/).

**Comment by khushalsagar** [comment]
Resolution aligns with current spec, no work needed.
