### ISSUE TITLE
[css-display-3] Should the Glossary contain a entry for 'flow container' as a synonym for 'block container' ?

### ISSUE THREAD

**Issue by lcchueri** [w3c/csswg-drafts#7844]
CSS has table, flex, grid, ruby containers for table, flex, grid, ruby layout. But 'block containers' is used instead 'flow containers' for flow layout as indicated in #1265.
Should, for easy of understanding, 'flow containers' be a synonym for 'block containers' in glossary or vice versa ?

Differently form #1265, I ask not it to be a main entry in Glossary, but just a synonym entry.

**Comment by fantasai** [comment]
I don't think it's useful for us to define synonyms that we aren't going to use in the specs, and we shouldn't use two different terms for the same thing because that makes the specs harder to follow.

I wouldn't mind if authors wanted to use it in their tutorials, but for the specs... I don't think it's a good idea.
