### ISSUE TITLE
[css-grid] Set `grid-template-rows` to `none` instead of `auto` when declaring `grid-template`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7849]
Can you please clarify me how `el.style.gridTemplate` should serialize when declaring eg. `el.style.cssText = 'grid-template: "."; grid-template-rows: none;'`? `"." auto`? `"."`? Empty string?

From reading `none` definition for [`grid-template-rows|columns`](https://drafts.csswg.org/css-grid-2/#propdef-grid-template-columns), I think it should be considered as if the property were not declared. If so, I suggest the following change [here](https://drafts.csswg.org/css-grid-2/#grid-template-ascii)...

```diff
-  Sets grid-template-rows to the `<track-size>`s following each string (filling in `auto` for any missing sizes), and splicing in the named lines defined before/after each size.
+  Sets grid-template-rows to the `<track-size>`s following each string (filling in `auto` for any missing sizes), and splicing in the named lines defined before/after each size, or `none` if all line names are omitted and all sizes end up being `auto`.
```

... which would clarify that my previous example should serialize to `"."`, and also that `"." auto` should serialize to `"."`.

**Comment by Loirooriol** [comment]
It should serialize as empty string, like Firefox does, since it seems that `grid-template` can't represent `grid-template-rows: none` when `grid-template-areas` is not `none`.

With your proposal, `grid-template: "." 1px "."` would set `grid-template-rows: 1px auto`, and  `grid-template: "." "."` would set `grid-template-rows: none`? Seems a bit inconsistent.

Also, I guess in "if all line names are omitted" you meant the `<track-size>`s, because it seems quite wrong if `grid-template: "." auto` would set `grid-template-rows: none`.

**Comment by cdoublev** [comment]
You are right. I was confused that the visual rendering remains the same whether `grid-template-rows` is set to `none` or `auto`.

I'm closing this issue and keep a note of this case for a WPT (when `grid` or `grid-template` should serialize to empty string), although I'd rather not commit to creating it soon.

**Comment by Loirooriol** [comment]
Note that `none` typically behaves like `auto` because of the initial `grid-auto-rows`, but they are different in general.
