### ISSUE TITLE
[css-color-5] Clarification on how `channel keywords` with multiple specified types work

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#7876]
In the [relative color syntax](http://w3c.github.io/csswg-drafts/css-color-5/#relative-colors) section of CSS Color 5, some of the `channel keywords` specify more than one type. For instance, the channel color `l` for the `lab()` relative color syntax states:

> - `l` is a [`<percentage>`](https://drafts.csswg.org/css-values-4/#percentage-value) or [`<number>`](https://drafts.csswg.org/css-values-4/#number-value) that corresponds to the [origin color’s](https://drafts.csswg.org/css-color/#origin-color) CIE Lightness

(http://w3c.github.io/csswg-drafts/css-color-5/##valdef-lab-l)

I am unclear on what this means with respect to using `l` in a `calc()` expression. For instance, in the following contrived case:

```
lab(from purple calc(l + 2) a b / 100%)
```

should I be interpreting `l` as a `<percentage>` or a `<number>`? (or am I missing something fundamental about calc that makes this not an issue?)

_Edit:_ linked to stable drafts, and corrected to CSS Color 5, not 4

**Comment by svgeesus** [comment]
I think this is a case of the editors not appreciating the impact of other changes. At the time it was introduced to CSS, CIE L was a `<number>` in [0..100]. Then it became a mandatory `<percentage>` for a long time, and relatively recently became `<percentage>` | `<number>`. You are right that this means RCS no longer defines what you actually calculate with for `calc()` inside RCS.

Following the advice that @LeaVerou gives in her CSS Variables talks:

> converting a number to a value with units is easy, `calc(var(--foo) * 100%)` 
> converting a value with units to a number requires things like `calc(var(--foo) / 1%)` which don't exist yet
> so make your custom properties be pure data with no units

Then I suggest resolving this such that `<percentage>` gets resolved to `<number>` because that will be the most convenient thing to manipulate in `calc()`

So 
```css
--base: oklab(50% 0.2 -12%);
--darker: oklab(from var(--base) calc(l * 0.8) a b);
```

Using the [percent reference ranges for oklab](http://w3c.github.io/csswg-drafts/css-color-4/#specifying-oklab-oklch) the value of --base becomes `oklab(0.5 0.2 -0.048) and the value of --darker becomes `oklab(0.4 0.2 -0.048)'

Converting the `<percentage>` values to `<number>` is also consistent with [how those values are serialized](http://w3c.github.io/csswg-drafts/css-color-4/#serializing-oklab-oklch)

**Comment by LeaVerou** [comment]
> I think this is a case of the editors not appreciating the impact of other changes. At the time it was introduced to CSS, CIE L was a `<number>` in [0..100]. Then it became a mandatory `<percentage>` for a long time, and relatively recently became `<percentage>` | `<number>`. You are right that this means RCS no longer defines what you actually calculate with for `calc()` inside RCS.

Yeah, [this appears to have been some sort of mass change](https://github.com/w3c/csswg-drafts/commit/102f3c3a8c9a273d6ab7db046341a92b13d1307d).

> Following the advice that @LeaVerou gives in her CSS Variables talks:
> 
> > converting a number to a value with units is easy, `calc(var(--foo) * 100%)`
> > converting a value with units to a number requires things like `calc(var(--foo) / 1%)` which don't exist yet
> > so make your custom properties be pure data with no units
> 
> Then I suggest resolving this such that `<percentage>` gets resolved to `<number>` because that will be the most convenient thing to manipulate in `calc()`

As a general principle, we should not be designing the language long-term based on short-term limitations.
However, I don't see anything wrong with erring on `<number>` whenever possible, to limit the number of conversions needed. That could be a general principle for RCS.

**Comment by svgeesus** [comment]
Another point is that forcing users to convert from percentage form themselves requires them to memorize or look up the percentage reference ranges for each component. 100% maps to 100 for CIE L, 1.0 for Oklab L, 125 for CIE a, 0.4 for Oklab a. Having the implementation do this will reduce errors.

**Comment by LeaVerou** [comment]
> Another point is that forcing users to convert from percentage form themselves requires them to memorize or look up the percentage reference ranges for each component. 100% maps to 100 for CIE L, 1.0 for Oklab L, 125 for CIE a, 0.4 for Oklab a. Having the implementation do this will reduce errors.

Correct, though it may make operations easier, e.g. `calc(l + 20%)` becomes more meaningful across color spaces.

**Comment by svgeesus** [comment]
`calc(l * 1.2)` seems easy enough

**Comment by LeaVerou** [comment]
Yes, but they do different things. Both are useful.

**Comment by LeaVerou** [comment]
Perhaps we can make it `<number-percentage>` so that math with percentages still works? @tabatkins is that a thing? Can it be?

**Comment by svgeesus** [comment]
There is no more `<number-percentage>`, it was removed.

**Comment by svgeesus** [comment]
So:
 -  @tabatkins [is fine with `<number>`](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1282797648), 
 - @LeaVerou [wanted `<number-percentage>`](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1278038929) which isn't possible, but [earlier said `<number>` was fine](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1277935443), and 
 - I argued for `<number>` [because if the implementation resolves percentages, that is less error prone than the user doing it](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1277943108).

No-one has argued for `<percentage>` only, and it is agreed that the channel keywords need to resolve to a single type.

In the interest of having concrete text to discuss on the call today, I am going to do the edits to make all channel keywords resolve to `<number>`.

**Comment by svgeesus** [comment]
For clarity, this only applies to channel keywords which are currently specified as **multiple types**, like  [`<percentage>`](https://drafts.csswg.org/css-values-4/#percentage-value) or [`<number>`](https://drafts.csswg.org/css-values-4/#number-value), as reported by @weinig. 

Channel keywords which use other (single) types, like `<angle>` for hues or `<percentage>` for the saturation and lightness of HSL, are not affected and they don't change to `<number>`.

**Comment by svgeesus** [comment]
Ok so now:

 - all channel keywords specify a single type
 - examples updated to consistently use that type
 - added an example of resolving specified percentage values to numbers

**Comment by LeaVerou** [comment]
> Channel keywords which use other (single) types, like `<angle>` for hues

Erm, [hue is `<number> | <angle>`](https://drafts.csswg.org/css-color-4/#typedef-hue) (and `<angle>` isn't actually used much at all in the wild)

**Comment by tabatkins** [comment]
Again, this is not about what types are valid for *input*, but rather what type the channel keywords are as *output* - those have to be a single known type or else the type of a calculation is completely undefined.

**Comment by tabatkins** [comment]
@svgeesus in hwb() you're still specifying the w and b keywords as percentages. Otherwise the edits look good.

**Comment by svgeesus** [comment]
> in hwb() you're still specifying the w and b keywords as percentages.

Yes, because [in CSS Color 4](https://drafts.csswg.org/css-color-4/#the-hwb-notation)

> The syntax of the [hwb()](https://drafts.csswg.org/css-color-4/#funcdef-hwb) function is:

> hwb() = hwb( [[`<hue>`](https://drafts.csswg.org/css-color-4/#typedef-hue) [|](https://drafts.csswg.org/css-values-4/#comb-one) none] [[`<percentage>`](https://drafts.csswg.org/css-values-4/#percentage-value) [|](https://drafts.csswg.org/css-values-4/#comb-one) none] [[<percentage>](https://drafts.csswg.org/css-values-4/#percentage-value) [|](https://drafts.csswg.org/css-values-4/#comb-one) none] [ / [[`<alpha-value>`](https://drafts.csswg.org/css-color-4/#typedef-alpha-value) [|](https://drafts.csswg.org/css-values-4/#comb-one) none] ][?](https://drafts.csswg.org/css-values-4/#mult-opt)

and

> The second argument specifies the amount of white to mix in, **as a percentage** from 0% (no whiteness) to 100% (full whiteness). Similarly, the third argument specifies the amount of black to mix in, also from 0% (no blackness) to 100% (full blackness). 

So percentage is required and number is not allowed. Should that be changed?
So numbers are not accepted, only percentages. Same as the non-hue components in HSL.

**Comment by romainmenke** [comment]
@tabatkins @svgeesus Maybe this issue should be re-opened.
The WPT tests were never updated to match the spec change and Safari shipped relative color syntax in 16.4 based on an old version of the specification.

**Comment by devongovett** [comment]
This is an unfortunate breaking change for folks using pre-processors. It means that something like `lch(from indianred calc(l + 10%) c h)` isn't possible anymore. You have to write it as `lch(from indianred calc(l + .1) c h)` which seems less intuitive, especially since you can normally write the `l` channel as a percentage (e.g. `lch(63.9252% 51.2776 26.8448)`). Why can't we have it be a number or percentage depending on which one type checks? That's how I had implemented it in Lightning CSS - it first tries the calculation where `l` is a number, and if that fails, tries it as a percentage.

**Comment by devongovett** [comment]
Another question about this: WPT has this test: https://github.com/web-platform-tests/wpt/blob/7c0ad5dcce2aa7a073b6f09b99213325b0c4574a/css/css-color/parsing/color-computed-relative-color.html#L90

```js
test_computed_value(`color`, `rgb(from rebeccapurple b alpha r / g)`, `rgba(153, 255, 102, 0.2)`);
```

This implies either that `alpha` values are stored in 0-255 range rather than 0-1 as specified by [`<alpha-value>`](https://w3c.github.io/csswg-drafts/css-color-4/#typedef-alpha-value), or that they are somehow converted. Here the alpha becomes the green channel (1 becomes 255), and the green channel becomes the alpha channel (51 becomes 0.2).

Is this the intentional behavior or should the output actually be `rgba(153, 1, 102, 1)`?

**Comment by romainmenke** [comment]
The WPT tests were never updated after the change from percentages to numbers.

**Comment by romainmenke** [comment]
I don't know why `<number>` was favored over `<percentage>` but I also find it very hard to work with.

Components as specified can have these types in RCS :
- `<number>`
- `<percentage>`
- `<angle>`

It is much harder to effectively write `calc` expressions for components because of this.

If `<percentage>` was favored it could be limited to :
- `<percentage>` (everything not `hue`)
- `<angle>` (only `hue`)

It would also be much more intuitive because `+ 10%` is "a little bit more" in any notation and for any component. Whereas `+ 1` could be out of gamut or barely noticeable.

**Comment by romainmenke** [comment]
A downside of percentages is that it limits the possible operations.

For example multiplying channels by alpha becomes impossible because percentages can not be multiplied.

I think that what I actually want is to be able to use numbers but have all number ranges have the same scales, which is just not how the different number notations works.

**Comment by devongovett** [comment]
also multiplying by `1.1` and adding `10%` are different things.

```
lch(from slateblue calc(l * 1.1) c h) => lch(49.0282% 65.7776 296.794)
lch(from slateblue calc(l + 10) c h) => lch(54.5711% 65.7776 296.794)
```

The first is 110% of the original `l` value. The second adds 10% of the overall range of the `l` channel.

**Comment by svgeesus** [comment]
> The WPT tests were never updated after the changes from mixed types to percentages or numbers.

They have now all been updated.
