### ISSUE TITLE
[css-fonts] hasn’t been updated in a long time

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#788]
https://github.com/w3c/csswg-drafts/commit/9d5ee04cc86a24b3177c7899e773133bced06487 from July 4, and more recently https://github.com/w3c/csswg-drafts/commit/e717903b844e40672d3eb96a9e68687c412c3cda, have not appeared in the Fonts 3 module yet. Is this expected? According to [this](https://hg.csswg.org/drafts/log/tip/css-fonts/Fonts.html), the last “original” revision was 7 months ago.

**Comment by svgeesus** [comment]
I think this is because the CSS3 Fonts spec does not use Bikeshed (IIRC) while CSS4 fonts does. Maybe it needs a manual build step?
https://drafts.csswg.org/css-fonts-4/

It is also noticeable that all the current discussion is on CSS4 Fonts: compare the number of issues
3:  https://github.com/w3c/csswg-drafts/labels/css-fonts-3
4: https://github.com/w3c/csswg-drafts/labels/css-fonts-4

**Comment by svgeesus** [comment]
@litherum mentioned for comment

**Comment by svgeesus** [comment]
Expected to publish an updated CR in December 2017.
