### ISSUE TITLE
Oklab captialization

### ISSUE THREAD

**Issue by mysteryDate** [w3c/csswg-drafts#7880]
In tremendous nit news: In the spec, the "Oklab" color space is capitalized as "OKLab"

[https://csswg.sesse.net/css-color-4/#specifying-oklab-oklch](https://csswg.sesse.net/css-color-4/#specifying-oklab-oklch)

In Ottosson blog that the spec references, the color space is always capitalized as "Oklab":

[https://bottosson.github.io/posts/oklab/](https://bottosson.github.io/posts/oklab/)

Where should we be consistent about capitalization if not in spec documents?

**Comment by svgeesus** [comment]
You are right.

**Comment by svgeesus** [comment]
Now we need a consistent capitalization for OKLCH, where Björn Ottosson
 does not give any guidance. I guess Oklch?

**Comment by svgeesus** [comment]
In the absence of other opinions, going for Oklch.

**Comment by LeaVerou** [comment]
"Oklch" looks really wrong. Could we please reconsider, especially since this was something we only went with in the absence of other opinions? 

- There is no precedent for referring to LCH as lch. LCH is typically capitalized, or only the h is lowercase: https://en.wikipedia.org/wiki/HCL_color_space
- LCH being an initialism would point towards uppercase, while it's ok to lowercase the "ab" in "Lab" since that’s what they are actually called.
- "OKLCH" seems [far more widespread](https://www.google.com/search?q=oklch)

No opinion about OKLCH vs OKLCh vs OkLCH, but strong -1 on Oklch.

**Comment by svgeesus** [comment]
Björn [uses OKLCh](https://bottosson.github.io/posts/colorpicker/) in passing, while defining Okhsv and Okhsl. Note that has OKLCh [uses L<sub>r</sub> rather than L](https://bottosson.github.io/posts/colorpicker/#intermission---a-new-lightness-estimate-for-oklab), too.

**Comment by LeaVerou** [comment]
I’m fine with OKLCh. @astearns I wonder if we could get an async resolution on this?

**Comment by astearns** [comment]
@LeaVerou I am assuming this is just for the specification. The functions and keywords are case-insensitive in code, correct?

**Comment by astearns** [comment]
OK, then I think there is no resolution required. This can be just at the editor’s discretion.

**Comment by Crissov** [comment]
So, now it’s “OKLCh” but still “Oklab”, not “OKLab”!?

**Comment by svgeesus** [comment]
> So, now it’s “OKLCh” but still “Oklab”, not “OKLab”!?

Correct. Both using the original author preferred spelling.

**Comment by lhecker** [comment]
@svgeesus I noticed that Björn uses OkLCh in his blog post, not OKLCh. This appears consistent to me as Oklab also uses a lowercase "k". Should the draft be adjusted accordingly?

**Comment by LeaVerou** [comment]
I would be fine with that.
