### ISSUE TITLE
[css-view-transitions-1] Should the DOMChangeCallback be posted as a task from skip transition steps?

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#7904]
Step 4 in [skip the page transition algorithm](https://drafts.csswg.org/css-view-transitions-1/#skip-the-page-transition-algorithm) says that the DOM change callback has to be invoked synchronously. However, the skip the page transition algorithm sometimes runs as part of the update the rendering, and we really want to avoid running (new) script in those steps. 

We should make it asynchronous. The question is should we just make it asynchronous for all places that run the skip the page transition algorithm, or should it be conditional?

I'm leaning towards just make it all asynchronous, but I'm unsure if there are cases where synchronous invocation is important.

/cc @khushalsagar @jakearchibald

**Comment by khushalsagar** [comment]
The downside of making it async is the following sequence:

- Queue a transition with createDocumentTransition.
- While snapshot is pending (so the callback hasn't run) initiate a new transition so the previous one is skipped.

It would be nice if the callback for the previous one consistently happened before or after we capture for the new one. But that depends on whether the event loop already has a task to run the next frame? I think the answer to this is a [microtask](https://html.spec.whatwg.org/multipage/webappapis.html#microtask) which would ensure that this runs before the next frame. @flackr on that.

Microtask won't help if multiple transitions are set up within the same frame but that seems like an edge case that the developer can handle better.

**Comment by khushalsagar** [comment]
Summary from offline discussion. Microtasks need a checkpoint to ensure they run before a specific event. Since there is already a checkpoint for [Web Animations](https://drafts.csswg.org/web-animations-1/#update-animations-and-send-events:~:text=Perform%20a%20microtask%20checkpoint), using a microtask will ensure the callback runs before the next rAF. It is brittle to rely on an unrelated checkpoint for this timing though.

Also since the callback itself is async, it's already possible that it hasn't finished before the next rAF. The [domUpdated](https://drafts.csswg.org/css-view-transitions-1/#dom-viewtransition-domupdated) promise was added precisely so developers have a hook to know when the callback is done. That could be used to delay queueing another transition if it should deterministically start after the callback for the first one is done.

**Proposed Resolution**: [Invoking the dom-update-callback](https://drafts.csswg.org/css-view-transitions-1/#skip-the-page-transition-algorithm:~:text=If%20transition%E2%80%99s%20phase%20is%20before%20%22%60dom%2Dupdate%2Dcallback%2Dcalled%60%22%2C%20then%20call%20the%20DOM%20update%20callback%20of%20transition.) is done by positing a task in skip the page transition.

**Comment by ydaniv** [comment]
If I'm following correctly the proposal is to always post as microtask?
In any case it must be consistently one of sync/next task/next microtask to be predictable for authors and also mockable for testing.

**Comment by khushalsagar** [comment]
The proposal is to use a [task](https://html.spec.whatwg.org/multipage/webappapis.html#concept-task) instead of microtask. Microtask timing can be unpredictable since the microtask checkpoint which runs them can be triggered by any feature.

**Comment by astearns** [comment]
@ydaniv (and/or anyone else) are you OK with the clarification and proposed resolution?

**Comment by ydaniv** [comment]
@astearns SGTM!

**Comment by astearns** [comment]
OK, seeing consensus here so this should get in the spec for wider review.

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

**Proposed Resolution**: Invoking the dom-update-callback is done by positing a task in skip the page transition.

**Comment by astearns** [comment]
RESOLVED: Invoking the dom-update-callback is done by positing a task in skip the page transition.

**Comment by noamr** [comment]
This resolution is from October and a lot of the naming has been changed since. It's entirely unclear to me how this resolution would work on the current "skip transition". Are we supposed to only run `call the update callback` asynchronously? What about handling the ready/finished promises, and removing the suppress-rendering flag? Wouldn't running part of this asynchronously create a race/flicker in some cases?

**Comment by noamr** [comment]
This would assert as it would mess up the phases. By making `update the callback` async we make it happen after the ready/finish phases. Note that the change callback is called synchronously during the update phase also when it's not skiped, when preparing the transition.

IMO the callback should be called synchronouosly.

**Comment by khushalsagar** [comment]
> IMO the callback should be called synchronouosly

That's not feasible because we can execute this step very late in the [update the rendering](https://html.spec.whatwg.org/#update-the-rendering) steps. Specifically, [step 8.7.5](https://drafts.csswg.org/css-view-transitions-1/#handle-transition-frame:~:text=Return.-,If%20transition%E2%80%99s%20initial%20snapshot%20root%20size%20is%20not%20equal%20to%20the%20snapshot%20root%20size%2C%20then%20skip%20the%20view%20transition%20for%20transition%2C%20and%20return.,-Update%20pseudo%2Delement) : 

```
If transition’s initial snapshot root size is not equal to the snapshot root size, then skip the view transition for transition, and return.
```

The "Handle transition frame" algorithm is triggered [here](https://drafts.csswg.org/css-view-transitions-1/#ref-for-perform-pending-transition-operations%E2%91%A0:~:text=For%20each%20fully%20active%20Document%20in%20docs%2C%20perform%20pending%20transition%20operations%20for%20that%20Document.), right before step 16. The goal behind running it this late is that its supposed to reflect DOM changes into the corresponding pseudo-elements. So we want to run it at a point when script is guaranteed to not modify the DOM. But that also means we're at a point where running script is bad. It won't be logically incorrect for this feature but adding a hook where script can run implies the DOM can be dirtied and we'll need to re-run style/layout again.

We can make the async approach by doing the following:

- In step 8.4.1 assert that phase is either before `update-callback-called`, which means this is running in the regular transition flow. Or assert that its `done`, which means this is happening because the transition was skipped before the callback was invoked.
- Make step 8.4.5 conditional to only update the phase if it was before `update-callback-called`.
- Add step 8.4.7 to invoke the `finished` promise if the phase is `done`. This means we delay dispatching the `finished` promise until the update callback is done if we're skipping the transition.
- Step 8.5.4 will post a task to call the update function.
- In step 8.5.9, don't resolve the finished promise if this task was posted.

I'll try to dig up the exact issue but IIRC we resolved on the fact that `ready` promise should reject immediately if you skip before `call the update callback` but `finished` should mirror the result of that callback.

**Comment by khushalsagar** [comment]
> What adding a postTask here would cause is a potential flicker. you'd have a moment where on one hand rendering is allowed ("transition suppressing rendering" is off), and OTOH the update callback wasn't called.

Just reiterating the case which could potentially flicker:

```js
function cancelTransition(transition) {
  // Author assumes that update callback was dispatched synchronously here.
  transition.skipTransition();

  // Author updates DOM assuming the update callback was already run.
  // This causes a flicker when the update callback is dispatched.
  updateDOMAfterTransition();
}
```

The update callback itself is async. In the case above, even if dispatched the update callback synchronously in skipTransition, the author still has to ensure its completed before running `updateDOMAfterTransition`. They can use `updateCallbackDone` promise for it.

```js
function cancelTransition(transition) {
  transition.skipTransition();
  transition.updateCallbackDone.then(updateDOMAfterTransition);
}
```

Also note that we don't want to suppress rendering until the callback finishes if the transition was skipped. We don't know if the author will make the updateDOM callback a no-op in this case.

**Comment by noamr** [comment]
Thanks @khushalsagar, this gives me enough context, I'll proceed with a PR based on the resolution.
