### ISSUE TITLE
[css-text-3] Priority between break-all/break-word/hyphens

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#791]
When these properties are set together, browses have different priorities.

Test: http://output.jsbin.com/bivori

Observations:

| Browser | Priority |
|-----|-----|
| Edge | `break-all` > `hyphens` > `break-word` |
| Gecko | `break-all` > `hyphens` > `break-word` |
| WebKit | `hyphens` > `break-all`/`break-word` |
| Blink | `break-all` > `break-word` > `hyphens` |

From a [user feedback](http://crbug.com/671341) and for consistency with other 3 browsers, I'm changing Blink to prioritize `hyphens` over `break-word`.

This leaves a question whether `hyphens` should win over `break-all`, or opposite.

Thoughts, anyone?

**Comment by frivoal** [comment]
> From a user feedback and for consistency with other 3 browsers, I'm changing Blink to prioritize hyphens over break-word.

Sounds good to me. Also, the spec already requires it:

> break-word
>   An otherwise unbreakable sequence of characters may be broken at an arbitrary point **if there are no otherwise-acceptable break points in the line**.

We could change it, but I don't think we should.

----

> This leaves a question whether hyphens should win over break-all, or opposite.

Based on the spec, break-all should win:

> break-all
>    [...] Hyphenation is not applied.

That said, as we've been discussing in #785, there is a use case for hyphenation to apply as well in some cases. One way to do that is to introduce a new value like `break-all-hyphenate`, another would be to look at the `hyphens` property to decide if a hyphen should be inserted or not at the wrapping point. Not entirely sure we should support this, but if we do, I think the first alternative is better.

So we could change the spec, but I don't think we should, and webkit should get fixed.

**Comment by kojiishi** [comment]
>> break-word
>> An otherwise unbreakable sequence of characters may be broken at an arbitrary point if there are no otherwise-acceptable break points in the line.

> We could change it, but I don't think we should.

Ah, ok, so "otherwise-acceptable break points" include hyphenation points. I just didn't interpret that way, but I'm fine with the conclusion.

> Based on the spec, break-all should win:

>> break-all
>> [...] Hyphenation is not applied.

IIRC this sentence doesn't intend that; its intention is "can break at non-hyphenation points, and does not insert hyphenation character," because we thought otherwise it may be misunderstood for Latin speakers.

Also, `break-all` and `break-word` look two variation features of a same feature group to me, having hyphenation in between the two looks weird.

**Comment by frivoal** [comment]
> Also, break-all and break-word look two variation features of a same feature group to me, having hyphenation in between the two looks weird.

I think that's just because they are very unfortunately named.

`overflow-wrap: normal | break-word` is
`what-to-do-to-avoid-overflow: nothing | break-anywhere-if-you-have-to`

`word-break: normal | keep-all | break-all` is
`CJK-or-latin-wrap-style: auto | latin | CJK`

**Comment by frivoal** [comment]
> Ah, ok, so "otherwise-acceptable break points" include hyphenation points. I just didn't interpret that way, but I'm fine with the conclusion.

I think this is defined by this sentence in the definition of `hyphens`:
  This property controls whether hyphenation is allowed
  to create more soft wrap opportunities within a line of text.

Since what hyphenation creates are "soft wrap opportunities", they are equally acceptable as break points as any other soft wrap opportunity.

**Comment by frivoal** [comment]
>>    Based on the spec, break-all should win:
>> >       break-all
>>>        [...] Hyphenation is not applied.
> IIRC this sentence doesn't intend that; its intention is "can break at non-hyphenation points, and does not insert hyphenation character," because we thought otherwise it may be misunderstood for Latin speakers.

Sure, but if you do "break at non-hyphenation points, and does not insert hyphenation character", then how/when can you still hyphenate?

Let's assume that you have have `hyphens:auto` and `line-break: break-all`, that the line contains the word "today" which has a hyphenation opportunity between o and d. If the line has room for 3 characters, we break (without hyphen) after d, since `line-break:break-all` creates a soft wrap opportunity between every letter. If the line has room for 2 characters, we should break after the o, but we cannot insert the hyphen, since that "to-" would be 3 characters, which doesn't it. So we break after the o without a hyphen because `line-break:break-all` creates a soft wrap opportunity between every letter and because it tells us that hyphenation does not apply.

I don't quite see what else could happen without inventing rules that are not in the spec.

**Comment by fantasai** [comment]
Closing issue as invalid per @frivoal's explanations. Please re-open if you think something needs clarification in the spec, but to me it's clear...
