### ISSUE TITLE
[css-view-transitions-1] Behaviour of the `finished` promise

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#7956]
```js
const transition = document.createViewTransition(updateDOMCallback);
await transition.finished;
```

There are two other promises:

- `domUpdated` - resolves with the promise returned by `updateDOMCallback`.
- `ready` - the transition has successfully prepared, and the pseudo-elements can now be targeted with JavaScript (eg web animation API). It will reject if the transition cannot be ready, either due to misconfiguration, or if `updateDOMCallback` returns a rejected promise.

I see two possible behaviours for `finished`:

## Option 1: Fulfill on full uninterrupted completion of the transition

If the transition animation does not fully play through, `finished` rejects. This can happen if:

- `updateDOMCallback` rejects - a failed DOM update is not transitioned
- A misconfiguration means that, although the DOM successfully updated, a transition cannot be performed. For example, multiple elements have the same `view-transition-name`, when they're supposed to be unique.
- The transition is aborted due to a newer transition.

## Option 2: Fulfill on the 'end state' being visible to the user

The 'end state' being the state after a successful DOM change. This means `finished` will resolve with whatever happens first:

- The transition plays through to completion
- The transition is aborted, so it visually appears to skip to the end

`finished` will only reject if `updateDOMCallback` returns a rejected promise. In this case the DOM change failed, so it does not reach a valid end state.

---

I originally spec'd option 1, but I've been convinced on option 2, since this is slower in spirit to `animation.finished`, which will resolve even if the animation is skipped to the end (via `animation.finish()`).

**Comment by ydaniv** [comment]
So this means that `finished` will be used _only_ for transitions that played/seeked/skipped **forward** to completion, right?

What about animations that are `reverse()`'d during playing? Or seeked/skipped **backwards** to 0%? Will that count as rejection?
If the user is seeking the animation manually via script I guess they would need to either `.reverse()` the animation when it's back at 0% progress or `.cancel()` (the former seems more likely perhaps).
What should be the state of `finished` in such cases?

**Comment by jakearchibald** [comment]
There's no concept of reverse for view transitions.

**Comment by khushalsagar** [comment]
> There's no concept of 'reverse' for View Transitions.

Yeah, no such concept right now. There is some discussion on this at #7957 but for now ViewTransitions build on animation primitives which are either active or not.

With option 2, when does the `finished` promise resolve with respect to `updateDOMCallback` callback. Especially because we're leaning to dispatch that callback using a task in #7904:

* Immediately when [skip the page transition](https://drafts.csswg.org/css-view-transitions-1/#skip-the-page-transition-algorithm) steps runs.
* After the callback is invoked but doesn't wait for the `domUpdated` promise to settle.
* After the `domUpdated` promise settles.

The WA-API doesn't have this problem since it synchronously reaches the end state if you call `finish()`.

Maybe an example of how developers would rely on the `finished` promise always resolving will help with this. I figured if some code needs to be executed when we've reached the end state, i.e. DOM has been updated, it should wait on `domUpdated` promise.

**Comment by ydaniv** [comment]
> finished will only reject if updateDOMCallback returns a rejected promise. In this case the DOM change failed, so it does not reach a valid end state.

Option 2 does sound better. 

> With option 2, when does the finished promise resolve with respect to updateDOMCallback callback.

That's a good point. I think it's important that `finished` is at least chained to promise returned from `updateDOMCallback` so that the author can predict the sequence. 

>

>  > There's no concept of 'reverse' for View Transitions.
> 
> Yeah, no such concept right now. There is some discussion on this at #7957 but for now ViewTransitions build on animation primitives which are either active or not.

Yes, question is how this API behaves when a user navigates back in mid transition? So that animations are reversed and 'end state' is actually previous view.

> I figured if some code needs to be executed when we've reached the end state, i.e. DOM has been updated, it should wait on domUpdated promise.

It's possible that authors will await the `finished` promise so to not interfere with the animation, both waiting for idle visible state and possibly wishing not to degrade its perf.

**Comment by khushalsagar** [comment]
**Proposed Resolution**:  In [skip the page transition](https://drafts.csswg.org/css-view-transitions-1/#skip-the-page-transition), the [finished](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-finished-promise) promise resolves after the [domUpdated](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-dom-updated-promise) resolves, or rejects after the [domUpdated](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-dom-updated-promise) rejects (with the same error).
