### ISSUE TITLE
[css-nesting-1] do not hide important notes in `<details>` elements

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#7967]
https://github.com/w3c/csswg-drafts/blob/c13755f34aa773986fa765fe0f8fe25bad86ce6c/css-nesting-1/Overview.bs#L205

Hiding these in dialogs does not improve the readability of the specification.
It only makes it more likely that someone will not read these.

**Comment by LeaVerou** [comment]
These are non-normative descriptions providing background, not essential for the spec to be understood, and the `<summary>` is still shown even with the `<details>` element collapsed:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/175836/198388291-7197bd7e-80c7-4890-879d-f82a61072b55.png">

I think this is a very appropriate use of `<details>` in a spec.

**Comment by tabatkins** [comment]
The use of those `details` are indeed very intentional. They're long, and not required for the understanding of the feature, just providing potentially-useful context for the curious. Having them as plain div.note would make the flow of the spec worse.

(We do similar in several other specs for this exact same reason - when we think it would be useful to provide some context for a decision, but the explanation is long and not required for actually understanding the feature.)

**Comment by romainmenke** [comment]
Ok
