### ISSUE TITLE
[css-logical-props] percentages need better definition

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#800]
https://drafts.csswg.org/css-logical-props/#propdef-min-block-size

That section (and others) says:
> Percentages:	block-size/inline-size, respectively, of containing block

However, this is a bit underdefined IMO:
- A strict reading of that line implies that a min-block-size percentage gets resolved to the parent's block-size property. However, if the parent has an orthogonal writing mode relative to the child, this property actually maps to the inline-size, right?

- Also, does this need a more explicit mention that percentages only resolve relative to definite sizes?

**Comment by prjnt** [comment]
I propose that the normative text be changed to "As for the corresponding physical property" (preferably accompanied by informative links to relevant parts of CSS).

(In which case the answer to the second question becomes "no" for css-logical-props, as this would already be covered in the definition of the physical property.)

I haven't tested, but I would be quite surprised if any UA had implemented a behaviour where the interpretation of a percentage depended on whether the winner of the cascade was a physical or logical property.


[The "informative" (i.e. non-normative) part of that proposal is important because I suspect that it will be easy to miss some relevant parts of CSS when giving a list of references due to the fact that CSS specs aren't always updated when another part of CSS gives new behaviour for something: e.g. percentage margin-top is resolved against *height* in page context (see e.g. CSS22/page.html#page-margins), contrary to what the actual propdef for margin-top says in CSS 2.x box.html#margin-properties.  Of course css-writing-modes/#dimension-mapping is also relevant.  Similar comments apply to the width & height properties, where one would think of referencing the propdef in CSS 2.x visudet.html, but might forget to link to the contradictory information in tables.html of the same spec.  Maybe bikeshed format makes it a bit easier to find most definitions of percentages for a given property?]

**Comment by cbiesinger** [comment]
I would support a change to "As for the corresponding physical property".
