### ISSUE TITLE
[css-view-transitions-1] Handling snapshot viewport sizes changes during transitions

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8045]
The [snapshot viewport](https://github.com/w3c/csswg-drafts/pull/8037) size would change by:

- The user or [script](https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo) resizing the window.
- A mobile device changing orientation.

This impacts a transition if it happens:

- Between capturing the old and new states.
- During the transition animation.

Options:

## Skip the transition

A resize creates situations the developer may not have predicted and catered for. For example, they may have assumed that their site header would be the same size in the old and new states. A resize can break that assumption.

Given that the transition is an enhancement, and the user is performing an 'interrupting' action by resizing the window, skipping the transition seems reasonable.

## Update the animation state and continue

All 'new' elements will be updated with their new size, which in turn will update all animations in progress. This includes the transition container representing the root element - this will be the only case where this element animates width & height.

**Comment by khushalsagar** [comment]
My vote is for skipping the transition:

- Your point here: "they may have assumed that their site header would be the same size in the old and new states" is particularly true for changes in screen orientation. I doubt there is a good way to do a more involved transition there other than a cross-fade.

- To do this properly we'll also need animation retargeting from #7813 which is not trivial.

So not worth the complexity IMO. We can collect metrics to see how often we get these resizes midway through a transition and do something better if its worthwhile.

**Comment by astearns** [comment]
Since this is merely limiting the scope of the first iteration of this feature we likely do not need to spend meeting time on it.

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: For the current module level, abort view transitions if the snapshot viewport changes size. We can take this up in future levels as use cases and solutions permit.

**Comment by astearns** [comment]
RESOLVED: For the current module level, abort view transitions if the snapshot viewport changes size. We can take this up in future levels as use cases and solutions permit.
