### ISSUE TITLE
[css-overflow-3] Standardize `overlay` as a synonym for `auto`

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#8063]
WebKit-ancestral browsers (including Blink) at one point implemented a non-standard `overlay` value for scrolling.This was never standardized (see [here](https://github.com/w3c/csswg-drafts/issues/7421) for a discussion of why it shouldn't be).

Subsequently, WebKit made `overlay` a synonym for `auto` .Gecko treats it as an invalid keyword. Blink still retains the original implementation (but the change to match Webkit is tracked in [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1271942)).

This also came up as a [compat problem in Interop 2023 discussions](https://github.com/web-platform-tests/interop/issues/187).

I propose to put the current WebKit behavior (`overlay` is an alias to `auto`) into the spec as a web compat compromise, because making it invalid would likely break too many sites.

**Comment by Loirooriol** [comment]
I think it would be quite confusing to accept `overlay` but then use classic scrollbars. It could also be a problem for webpages that are using `CSS.supports("overflow", "overlay")` to decide whether to polyfill overlay scrollbars or try to use a native approach.
Would the breakage be that bad, given that Gecko doesn't support `overlay`?

**Comment by tabatkins** [comment]
That polyfill test would already fail in WebKit, per Chris's comment about their behavior.

I'm surprised Gecko can get away with `overlay` being invalid, since if there's no backup value it defaults to `visible` which is very different, but maybe it's the case that *due* to Firefox, enough sites set `overflow: auto; overflow: overlay;`. Or maybe those pages are just broken in Firefox. :/  It would be good to see if we could indeed get away with just killing it, tho.

**Comment by jgraham** [comment]
Firefox doesn't really get away with this; it's a pretty significant webcompat issue, which is why we're keen to get something fixed here; see https://bugzilla.mozilla.org/show_bug.cgi?id=1521631 for details (all the See Also links are site breakage).

That bug has a patch to alias to `overflow: auto`, but there was a concern that this doesn't work as well on non-mac platforms which don't always have overlay scrollbars cc @emilio

**Comment by emilio** [comment]
Aliasing to `auto` seems better than the status quo for us, that's for sure. If blink plans to do it we're more than happy to do so as well.

**Comment by Loirooriol** [comment]
AFAIK the problem with `overflow: overlay` is that for now there is no implementation interest to have a feature to allow authors to choose overlay scrollbars. If this changes in the future, but now we define `overflow: overlay` as `auto`, then authors won't be able to use `@supports` to check whether they can choose overlay.

**Comment by chrishtr** [comment]
> If this changes in the future

I don't think it will change in the future. We generally resolved that the choice of overlay or non-overlay scrollbars is a user/UA/OS setting, not a developer setting.

**Comment by emilio** [comment]
What I didn't realize at the time of reviewing @jwatt's patch for Gecko is that Safari apparently _does_ support non-overlay scrollbars (based on OS settings).

So if WebKit is already providing `overflow: overlay` as classic scrollbars in that case, seems like aliasing to `auto` is even more palatable.

**Comment by emilio** [comment]
@fantasai I'd like to prioritize this if possible, just to confirm that aliasing to auto should be fine. I believe this should be simple enough, wdyt?

**Comment by frivoal** [comment]
Addressed in https://github.com/w3c/csswg-drafts/commit/9381b07ef65175c435269cc0ea4fb6911c0b45af, closing.
