### ISSUE TITLE
[scroll-animations-1] Rename “Scroll-linked Animations” to “Scroll-driven Animations”

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8101]
Was just thinking that the latter might be a bit more clear, given we want to avoid people thinking this is about scroll-triggered animations. Thoughts?

**Comment by birtles** [comment]
I think we were initially going to call it "scroll-driven" but wanted something a bit more encompassing and approachable ("linked" seems more friendly to me than "driven").

**Comment by fantasai** [comment]
@birtles What do you mean by “encompassing”?

**Comment by birtles** [comment]
> @birtles What do you mean by “encompassing”?

I guess because initially we had scroll triggers and hand-off between scroll/time-based animations so the effects weren't tied so heavily to scroll position.

**Comment by ydaniv** [comment]
I guess my initial thought was same as @bramus', "linked" seemed initially a bit strange. Perhaps "driven" might be better.

Here we use the term "scrub" if it helps.

**Comment by birtles** [comment]
It sounds like everyone prefers scroll-driven, so go for it!

**Comment by fantasai** [comment]
@birtles Either that, or retitle to something appropriate and have scroll-driven animations be Part 1 and scroll-triggered animations be Part 2. The nice thing is, we won't need to change the shortname, just up the level. :)

**Comment by astearns** [comment]
Since this has consensus here in the issue we likely do not need to spend meeting time on it.

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Change “Scroll-linked Animations” to “Scroll-driven Animations” in scroll-animations-1

**Comment by astearns** [comment]
RESOLVED: Change “Scroll-linked Animations” to “Scroll-driven Animations” in scroll-animations-1
