### ISSUE TITLE
[scroll-animations-1] [web-animations-2] Clarifying behavior of getCurrentTime(rangeName)

### ISSUE THREAD

**Issue by kevers-google** [w3c/csswg-drafts#8114]
A few questions regarding getCurrnetTime(rangeName) in AnimationTimeline.

Why does the progress need to be constrained between 0 and 100%.  If in the 'contain' range and asking for the currentTime of the 'enter' range, should we  not return a value greater than 100%?

What if the range is zero? If I recall correctly, a zero 'cover' range should result in an inactive timeline, which is handled in the algorithm, but what if the enter / exit range is zero due to having a target element of height zero (axis: vertical) and then querying one of those ranges? Perhaps this is deserving of a "returns null".  This example may seem contrived, but it is doable.  How about the case when the target exceeds the viewport size and fetching the 'contain' progress?  As we transition from the 'enter' to the 'exit' range, the cover range has a height or width of zero.

**Comment by flackr** [comment]
> A few questions regarding getCurrnetTime(rangeName) in AnimationTimeline.
> 
> Why does the progress need to be constrained between 0 and 100%. If in the 'contain' range and asking for the currentTime of the 'enter' range, should we not return a value greater than 100%?

I suspect so. This matches the time used by an animation over that range.

> What if the range is zero? If I recall correctly, a zero 'cover' range should result in an inactive timeline, which is handled in the algorithm, but what if the enter / exit range is zero due to having a target element of height zero (axis: vertical) and then querying one of those ranges? Perhaps this is deserving of a "returns null". This example may seem contrived, but it is doable. How about the case when the target exceeds the viewport size and fetching the 'contain' progress? As we transition from the 'enter' to the 'exit' range, the cover range has a height or width of zero.

Zero range does not necessarily mean inactive. See https://github.com/w3c/csswg-drafts/issues/7778#issuecomment-1313875566 for details. We should follow the calculation we define there. Though interestingly, for 0 range as long as you can scroll before or after the 0 range it probably makes sense to have the progress by -infinity and +infinity so that if your effect fills it applies the fill effect based on which side you're on.

**Comment by fantasai** [comment]
@flackr @kevers-google I updated the definition to remove the clamping. For the case of zero-size ranges, I specced the following:

> If the start and end points of the named timeline range coincide, return negative infinity for time values before it, positive infinity for time values after it, and zero for time values coinciding with that point.

Let me know if that seems appropriate or if you want something different.

**Comment by kevers-google** [comment]
CSSUnitValue is specced to have the value as double (https://drafts.css-houdini.org/css-typed-om/#simple-numeric) and not unrestricted double, which would include +/-infinity.   Returning +/-Inifinity% could be problematic assuming we wish to use TypedOM as the canonical form for the return value.

**Comment by kevers-google** [comment]
We could make the return type for getCurrentTime (unrestricted double or CSSNumericValue) and simply drop the unit in the +/-Infinity case. Would like to keep the unit otherwise.

**Comment by tabatkins** [comment]
> CSSUnitValue is specced to have the value as double ([drafts.css-houdini.org/css-typed-om/#simple-numeric](https://drafts.css-houdini.org/css-typed-om/#simple-numeric)) and not unrestricted double

Hm, that's actually just because I forgot to think about it. I think it would be fine make it an unrestricted double (since CSS can represent infinite and NaN values now).

**Comment by flackr** [comment]
> > If the start and end points of the named timeline range coincide, return negative infinity for time values before it, positive infinity for time values after it, and zero for time values coinciding with that point.

If range-start = range-end, the animation isn't active so I'm not sure if 0 makes sense or if it should be -infinity since we seem to be in the before phase:

https://jsfiddle.net/flackr/z2ghe9qx/8/

@kevers-google are you good with the +/- infinity values given that we can add them and so that if you copy the progress to another animation you get the same effect?

**Comment by kevers-google** [comment]
I'm good with +/- infinity

**Comment by fantasai** [comment]
(Filed https://github.com/w3c/css-houdini-drafts/issues/1089 as the OM issue; let's keep this one open to track it since that's in a different repo.)

It looks like we need a follow-up resolution here for what happens when start=end? I think we basically have these two options for when the start and end points of a named timeline range coincide:

* Return negative infinity for time values before the range, positive infinity for time values after it, and zero for time values coinciding with that point.
* Return positive infinity for time values after the range, and negative infinity for times coinciding with and before.

**Comment by flackr** [comment]
> It looks like we need a follow-up resolution here for what happens when start=end? I think we basically have these two options for when the start and end points of a named timeline range coincide:
> 
> * Return negative infinity for time values before the range, positive infinity for time values after it, and zero for time values coinciding with that point.
> * Return positive infinity for time values after the range, and negative infinity for times coinciding with and before.

I recommend the latter for the same reason I recommended the infinity values. If a developer applies this to another animation it will clearly put the effect into the before phase rather than active as it would be on a real animation.

**Comment by flackr** [comment]
I just put together a quick test of a time based animation of 0 duration time based animation:
https://jsbin.com/qarogay/edit?html,css,output

And it behaves more like I expected, being in the after phase. So perhaps times coinciding with the empty range should be positive infinity. This also aligns with what I expected would be the case.
