### ISSUE TITLE
[css-values-3] Normative ref to CSS Values 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#8120]
There are 12 normative reference to CSS Values 5. This has two problems:

1. 5 > 3
2. https://www.w3.org/TR/css-values-5 doesn't exist (no FPWD)

**Comment by svgeesus** [comment]
These are caused by Bikeshed reporting links in informative sections (changes list) as normative.

**Comment by tabatkins** [comment]
Well, that's because it doesn't know those sections are informative. Put one of the [informative classes](https://tabatkins.github.io/bikeshed/#metadata-informative-classes) on the changes list (or a wrapper div) and it'll know.

(By default, "note", "example", "informative", and "non-normative" all work.)
