### ISSUE TITLE
[css-contain] Allow container query style features to evaluate in a boolean?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#8127]
Dimensional media/container queries can [evaluate in a boolean context](https://www.w3.org/TR/mediaqueries-4/#mq-boolean-context). This isn't terribly useful (dimensional queries aren't the main use-case for booleans), but it works:

```css
@container (inline-size) {
  /* element has an inline-size container 
      with inline-size greater than 0 */
}
```

With style queries, a boolean check is much more useful:

```css
@container style(gap) {
  /* remove margins when a gap is defined? */
}

@container style(--button-theme) {
  /* shared styles for all button themes? */
}

@container style(--reverse) {
  /* styles for something that's reversed? */
}
```

I think all these checks are possible in the current spec by querying for `initial` and negating the query, so allowing boolean queries would just be syntax sugar:

```css
@container not style(gap: initial) {
  /* remove margins when a gap is defined? */
}

@container not style(--button-theme: initial) {
  /* shared styles for all button themes? */
}

@container not style(--reverse: initial) {
  /* styles for something that's reversed? */
}
```

**Comment by LeaVerou** [comment]
+1 to this. There are use cases, and it's congruent with the principle of least surprise, since all other types of queries support this.

**Comment by LeaVerou** [comment]
In fact, this seems straightforward enough that maybe we can resolve on async?

**Comment by una** [comment]
+1 to this, here's an example where I needed it to reduce redundancy: https://codepen.io/una/pen/LYBrYGX

**Comment by LeaVerou** [comment]
@astearns @atanassov do you think we could resolve async on this?

**Comment by mirisuzanne** [comment]
This should be defined in a way that also works with standard properties as well as custom properties, right? If the query is checking for a value other than 'guaranteed invalid', that would only work on custom properties. Would we check for a value other than the defined initial value? Or would we need some other definition of truthy/falsey values?

**Comment by astearns** [comment]
Can this be resolved async for both custom properties and regular properties, or does the definition need to be worked through first? Please add a proposed resolution if you want to go the async route

**Comment by LeaVerou** [comment]
I think the definition is pretty straightforward: it evaluates to `true` if the property is NOT `initial`. Some kinks still need to be ironed out for regular properties and registered custom properties (e.g. if a property is explicitly set to its initial value, e.g. `font-weight: normal`) does it evaluate to `false`? That seems unintuitive but not sure how else to design something reasonably implementable) but we can still resolve to add the feature, and work through issues related to the design like any other issue on any other spec.

**Comment by Loirooriol** [comment]
Checking `revert` instead of `initial` might also be interesting.

**Comment by mirisuzanne** [comment]
> Checking `revert` instead of `initial` might also be interesting.

Good point, for regular properties this is much more likely to match author expectations.

**Comment by una** [comment]
What is `@container(--var)` if we have `--var: false`?

It's kind of funky, but according to how we're discussing this, I would expect `@container(--var)` to return **true** since `--var` is defined, and would by default be a string value. It looks like this shouldn't conflict with `@property`-defined CSS custom properties either, considering boolean isn't an available [syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax) type (correct me if I'm wrong because that would then be an issue).

But because of this confusion ^ we should define if this is a **"presence" query** or if this a **boolean query** and discuss it as such.

**Comment by andruud** [comment]
@Loirooriol It's unfortunately not possible to check `revert`. https://github.com/w3c/csswg-drafts/issues/7080#issuecomment-1083388588

**Comment by lilles** [comment]
> What is `@container(--var)` if we have `--var: false`?
> 
> It's kind of funky, but according to how we're discussing this, I would expect `@container(--var)` to return **true** since `--var` is defined, and would by default be a string value. It looks like this shouldn't conflict with `@property`-defined CSS custom properties either, considering boolean isn't an available [syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax) type (correct me if I'm wrong because that would then be an issue).
> 

`<boolean>` is not a syntax, but you can register a syntax which has two keywords, `true` and `false`, and have `false` as the initial value. Then (assuming we're choosing the initial value comparison), `false` can evaluate to false in the boolean context.

> But because of this confusion ^ we should define if this is a **"presence" query** or if this a **boolean query** and discuss it as such.

It's not a boolean query, but "evaluated in a boolean context", which is phrased like that because that's how the same thing is phrased in the media queries spec, which basically means evaluated without a value/comparison.

**Comment by cdoublev** [comment]
`<style-feature>` has been updated according to the above resolution and is now explicitly defined with `<ident> : <declaration-value> | <ident>` instead of this sole [prose](https://drafts.csswg.org/css-contain-3/#style-container):

  > The syntax of a `<style-feature>` is the same as for a declaration [...]

Note: it may also have to be updated with *is a property name or is the same as for a declaration [...]*, the basic syntax can be simplified to `<declaration> | <ident>` or `<ident> [':' <declaration-value>]?`, and `:` should be quoted, according to [CSS Values](https://drafts.csswg.org/css-values-4/#component-types).

In #8735, I ask for clarifications about `<declaration>`. It is not defined, and I am not sure if it represents a valid declaration according to the CSS syntax or more specifically, a valid declaration according to the CSS grammar, ie. `color: 1px` is valid according to the CSS syntax but is invalid according to the CSS grammar.

(Sorry if I am using *grammar* and *syntax* terms incorrectly/inappropriately)

If `<ident>` can match an invalid property (which would then not be matched as `<any-value>`), `<declaration>` can match `color: 1px` and represents a valid declaration (structure).

**Comment by lilles** [comment]
@cdoublev Good catch, and it makes a difference because it decides whether these cases evaluate to `false` or `unknown`:

```
style(specced-but-not-implemented-property)
style(color: 1px)
style(color: specced-but-not-implemented-value)
```

How about reverting the syntax change and instead change the prose to something like:

"The syntax of a `<style-feature>` is either a valid declaration or a supported property name"

That would result in all of the style() queries in the block above to fall back to `<general-enclosed>` and evaluate to `unknown`.

Does that look reasonable?

**Comment by cdoublev** [comment]
Entirely. 

I have no strong opinion but I would say that `<declaration>` cannot match `invalid: var(--custom)` whereas `<ident>` can match `invalid`.

**Comment by Loirooriol** [comment]
> The syntax of a `<style-feature>` is either a valid declaration or a supported property name

This would exclude custom properties, wouldn't it?

**Comment by cdoublev** [comment]
I think I caused a bit of confusion, sorry.

The evaluation of the query may not directly depend on the result of parsing. `invalid-property` matches `<ident>`, `color: invalid` matches `<declaration>`, and both evaluate to `unknown`.

I stand by my suggestion and extend it:

  > `<style-feature> = <declaration> | <ident>`

https://drafts.csswg.org/css-contain-3/#typedef-style-feature

  > `<style-feature>` is associated with a boolean result. If the UA does not accept that declaration (discarding it as a parse error) or property within a style rule, the result is false. If the computed value of the given property on the query container matches the given value (which is also computed with respect to the query container), the result is true. Otherwise it is unknown.

https://drafts.csswg.org/css-contain-3/#style-container

**Comment by lilles** [comment]
> > The syntax of a `<style-feature>` is either a valid declaration or a supported property name
> 
> This would exclude custom properties, wouldn't it?

You mean the "supported property name" part? Custom property declarations are valid declarations, right?

I would like to avoid is having to parse and store invalid declarations. So where the current spec says that invalid property names and values evaluate to unknown, I'd rather make style() queries with invalid declarations fall back to general-enclosed parsing which would also evaluate to unknown.

**Comment by cdoublev** [comment]
> The term supported CSS property refers to a CSS property that the user agent implements, including any vendor-prefixed properties, **but excluding custom properties**.

https://drafts.csswg.org/cssom-1/#supported-css-property

I borrowed *if it accepts that property in a style rule* from the prose in CSS Conditionals 3 for `<supports-decl>`, which I would be fine if its result would be defined as true if the declaration is successfully parsed against `<declaration>`, defined as matching a declaration whose value is valid according to the grammar of the property that corresponds to its name.

**Comment by lilles** [comment]
> > The term supported CSS property refers to a CSS property that the user agent implements, including any vendor-prefixed properties, **but excluding custom properties**.

Got it.

How about: [`supported CSS property`](https://drafts.csswg.org/cssom-1/#supported-css-property) or a [`<custom-property-name>`](https://drafts.csswg.org/css-variables/#typedef-custom-property-name) ?
 
> https://drafts.csswg.org/cssom-1/#supported-css-property
> 
> I borrowed _if it accepts that property in a style rule_ from the prose in CSS Conditionals 3 for `<supports-decl>`, which I would be fine if its result would be defined as true if the declaration is successfully parsed against `<declaration>`, defined as matching a declaration whose value is valid according to the grammar of the property that corresponds to its name.

I'm not able to understand what you're trying to say here. Where did you borrow that?

**Comment by cdoublev** [comment]
> I'm not able to understand what you're trying to say here.

Oh, sorry. 

`<supports-decl>`, which is defined with `( <declaration> )`, evaluates to true if *the CSS processor accepts that declaration within a style rule* (the borrowed part). I suggested that *`<style-feature>` evaluates to true if the CSS processor accepts that property (`<ident>`) within a style rule*, because I knew that *supported CSS property* excludes custom properties.

In the next part of my comment (which I should have split), I say that I would have no problem if `<supports-decl>` were defined to evaluate to true if the result from parsing `<declaration>` represents a declaration that the CSS processor accepts within a style rule. (I think that is what you want, if I understood correctly.)
