### ISSUE TITLE
[css-images-4] Computed value of stripes()

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8140]
The current spec says that the computed value of stripes() has all length-percentage values “absolutized and computed to the extent possible”. For border widths, that means it'll resolve to an absolute length.

However, I suspect we want to keep percentages uncomputed for inheritance, if we ever do use this in an inherited property, so I propose to use the same formulation as `width` etc. rather than `line-height`.

**Comment by SebastianZ** [comment]
> However, I suspect we want to keep percentages uncomputed for inheritance, if we ever do use this in an inherited property, so I propose to use the same formulation as `width` etc. rather than `line-height`.

But percentages in `width` do get computed to a `<length>`. If we keep percentages (and `<flex>` values) uncomputed, how would you transition between different values? See also https://github.com/w3c/csswg-drafts/issues/8163#issuecomment-1334576429 and generally the discussion there.

Sebastian

**Comment by Loirooriol** [comment]
Percentages in `width` compute as-is, not to a length. In this [testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22width%3A%20400px%3B%20border%3A%20solid%20cyan%22%3E%0A%20%20%3Cdiv%20style%3D%22width%3A%2050%25%3B%20border%3A%20solid%20orange%22%3E%0A%20%20%20%20%3Cdiv%20style%3D%22width%3A%20inherit%3B%20border%3A%20solid%20magenta%22%3E%0A%20%20%20%20%20%20Lorem%20ipsum), `width: inherit` sees `50%` instead of the resolved width.

**Comment by SebastianZ** [comment]
> Percentages in `width` compute as-is, not to a length. In this [testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22width%3A%20400px%3B%20border%3A%20solid%20cyan%22%3E%0A%20%20%3Cdiv%20style%3D%22width%3A%2050%25%3B%20border%3A%20solid%20orange%22%3E%0A%20%20%20%20%3Cdiv%20style%3D%22width%3A%20inherit%3B%20border%3A%20solid%20magenta%22%3E%0A%20%20%20%20%20%20Lorem%20ipsum), `width: inherit` sees `50%` instead of the resolved width.

You're right. I mixed up the resolved value from `getComputedStyle()` with the computed value.

Because @fantasai already [changed the spec. to keep percentages unchanged](https://github.com/w3c/csswg-drafts/commit/d07c8c50bee37e7cdff14afdc90103f82629e2d5), I close this issue now. Feel free to re-open it if I missed anything.

Sebastian

**Comment by SebastianZ** [comment]
Having said that, https://github.com/w3c/csswg-drafts/issues/8163#issuecomment-1334576429 outlines a reason why keeping percentages as-is restricts us regarding transitions.

Sebastian

**Comment by tabatkins** [comment]
Actually, I think this was better initially, where flexes were computed to lengths eagerly. That solves the transition issue immediately and clearly, without needing further interventions as I outlined in [my comment](https://github.com/w3c/csswg-drafts/issues/8622#issuecomment-1483386351).

And as stripes are *essentially* an image type, I find it very unlikely that they'll ever be used in an inherited property.

**Comment by SebastianZ** [comment]
I added #8622 to the agenda, which will also cover the things discussed here. The proposal is to adopt Tab's suggestion from above.

I assume, if there's a real need to add `stripes()` to an inherited property at some point, we could still account for that in that specific context.

Sebastian
