### ISSUE TITLE
[css-view-transitions-1] domUpdated isn't the right term

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#8144]
Apart from a couple of events that are prefixed with `DOM*`, we don't really expose DOM as a term to web content and I think we should keep it that way.

Either keep this somewhat more abstract or go with `nodeTreeChanged` or some such.

cc @jakearchibald @domenic

**Comment by jakearchibald** [comment]
The developer provides a callback that updates the state of the page in some way that forms the 'after' state of a transition.

`domUpdated` relates to the success/failure of that update.

Some other name ideas:

- `stateUpdated`
- `viewUpdated`

I'll try and think up more.

**Comment by annevk** [comment]
It sounds like you and I have a different understanding of what DOM means. If the overall feature is called view transitions, viewUpdated makes some sense to me.

**Comment by jakearchibald** [comment]
The problem with `viewUpdated`, is… what the user sees isn't updated yet.

Here's a diagram I've been working on to go in the spec that tries to explain the phases of a view transition.

https://user-images.githubusercontent.com/93594/204783724-fa9e7782-1b7b-4ccf-b628-bf6d67148f30.mp4

The three promises map to those phases:

- `domUpdated` - once "developer updates DOM"
- `ready` - once "transition layer populated"
- `finished` - once "transition layer cleared"

I had assumed that a change to styling counted as a DOM change, as text content of a style would have changed, or a rule in CSSOM would have changed etc etc. My assumption is that CSSOM was a subset of the DOM, since it's properties that hang off nodes that are part of the document.

`viewUpdated` seems wrong, because the user may not see it yet. It's the document model that's updated.

**Comment by annevk** [comment]
How about something like `stateChanged`?

I think there's quite distinct ideas about the scope of the term DOM and as such I'd rather also not have it as a term-of-art in APIs or even prose.

**Comment by jakearchibald** [comment]
I thought you were saying 'state' was problematic in https://github.com/w3c/csswg-drafts/issues/8143?

**Comment by jakearchibald** [comment]
Ah, ok, I think I understand what you mean in https://github.com/w3c/csswg-drafts/issues/8143 now.

`stateChanged` is vague, and clashes with state updates in frameworks (which happen before DOM updates). I'll have a think.

**Comment by jakearchibald** [comment]
@vmpstr suggested the name should reflect that it's linked to the callback passed to `startViewTransition`.

So:

- `callbackDone`
- `updateCallbackDone`

I prefer the latter, in case we add other callbacks in future.

**Comment by tbondwilkinson** [comment]
From an API perspective:

```
startViewTransition(callback);
```

There's nothing about the API shape right now that implies a name for the callback parameter passed to `startViewTransition`. The spec does call it a `UpdateDOMCallback`, but that doesn't appear in the API. If Anne has an issue with DOM appearing in the API, perhaps the spec should also be changed to a more neutral name?

You could consider using "render," as I believe that's a term unrelated to DOM but reflects that the operation is to change the rendered content.

`renderViewCallback`, perhaps.

**Comment by jakearchibald** [comment]
> There's nothing about the API shape right now that implies a name for the callback

There might in future, if the API changes to a dictionary to allow for options, and perhaps other callbacks.

> perhaps the spec should also be changed to a more neutral name?

Yep, it will be, to reflect the name we decide here. But the developer-facing name is more important.

> You could consider using "render,"

See the video in https://github.com/w3c/csswg-drafts/issues/8144#issuecomment-1332007696. I don't think "render" is a good choice because the change is not rendered visually.

**Comment by tbondwilkinson** [comment]
`updateCallbackDone` just feels so generic. :( Is there really no verb commonly used for the modification of HTML elements on the page?

**Comment by annevk** [comment]
Mutations (see `MutationObserver`), but those exclude changes to style sheets.

**Comment by ydaniv** [comment]
Perhaps it would be more correct to say `targetReady`? Since it's not just updating the DOM that needs to be done. The developer may want to preload other resources for the final state to be visually ready, etc.
Currently there's no mention in the spec of a "target" but there are always a source and target views for a transition.

**Comment by khushalsagar** [comment]
Posting a summary of all the options brought up on the issue so folks can quickly skim through and pick the one they most agree with.

- Option 1 builds on `domUpdated`: "Updated" is the verb to indicate state has changed and "dom" is the noun to refer to this state.

   For the prefix we want something which encompasses any update to the DOM (node state, tree state, computed style, loading state, canvas update etc). The options are:
   - `stateUpdated` : state can be a bit generic.
   - `viewUpdated` : We landed on "view" transitions with the idea that the transition is between the user visible "views" of the page. Since the callback doesn't change visuals for the user, view can be ambiguous.
   - `renderingUpdated` : Similar to above, rendering hasn't been updated when this promise resolves.
   - `nodeTreeUpdated` : Doesn't encompass all the ways in which the page state can change.
   - `targetUpdated` : Follows the nomenclature of source and target views to refer to new page state as "target". Not great since the spec has settled on old and new views for this.

   There are a few other options for the suffix too:
   - `domReady` : We already have a "ready" promise to indicate the pseudo-DOM has been generated.
   - `domChanged`
   - `domMutated`
   - `domUpdateHandled` : Don't see the advantage of this vs domUpdated, its just longer.
   - `domChangeHandled` : Same as above.

- Option 2 is to tie the promise to the callback passed by the developer in startViewTransition. The callback is currently named `UpdateDOMCallback` and the promise will `updateDOMCallbackDone` or `updateDOMCallbackHandled`. So it seems like we still need a noun + verb combination as the options above.

   A related options is to skip the noun. So you'd just have `updateCallback` (see verb options for update above) and the promise will be callback name + "done/handled", like `updateCallbackDone` or `updateCallbackHandled`.

Please add in case I missed something.

---

My take is that the pattern for nounVerbCallback for the callback and nounVerb for the promise is good. And `update` is fine for the verb. The discussion started with avoiding the use of "dom" as the noun. And from the options above, I'd go with state. It's generic but intentionally so since we want to encompass a broad type of updates. So, `updateStateCallback` and `stateUpdated`.

If we can't agree on a noun then next best option is to drop it and go with `updateCallback` and `updateCallbackDone`.

**Comment by khushalsagar** [comment]
Conclusion from a discussion just now, we've got 2 proposals that we'd like the group's feedback on:

1. `updateStateCallback` for the callback and `stateUpdated` for the corresponding promise.
2. `updateCallback` for the callback and `updateCallbackDone` for the corresponding promise.

No strong preference on either of the options above.

**Comment by ydaniv** [comment]
I'd prefer 2.

To me "state" sounds very vague. I do however understand that the callback argument is _the_ "update callback".
