### ISSUE TITLE
[scroll-animation-1] Define scroll linked animation behavior in printing documents

### ISSUE THREAD

**Issue by hiikezoe** [w3c/csswg-drafts#8226]
What most of users expect in printing documents is, I think, printing out the document as it is when the user printed out.

So basically any scroll linked animations should be output as it is, other then animations tied to the root scroll container in the top level document because there's not scroll position for the root scroller I think.

That's said, it's just my opinion. The spec needs to clarify it.

**Comment by bramus** [comment]
When printing I would assume there is no scroll estate, so the logic from https://github.com/w3c/csswg-drafts/issues/7778#issuecomment-1341822948 would apply in that case.

**Comment by hiikezoe** [comment]
@bramus what do you mean by "no scroll estate"? IIRC Chrome does preserve each scroll position for sub scroll containers in printing document.

**Comment by hiikezoe** [comment]
I suppose you meant for the root scroll container cases?

**Comment by bramus** [comment]
> I suppose you meant for the root scroll container cases?

Definitely for the root scroller as printing is paged media without a viewport.

For non-root scrollers I hadn’t really checked what printing does. In Chrome it prints the contents at the current scroll position like you mentioned. With that given, it makes sense to print the scroll-linked element at a certain position.

Maybe the progression of the animation could be snapshotted and then be re-applied when printing? E.g. say you’ve scrolled halfway and the scroll-linked animation is at 50% because of that. When printing, then use that 50% as the animation progress instead of trying to recalc the whole lot based on the printed box’s size.

**Comment by flackr** [comment]
I think the most natural thing to do is treat the root as a scroller that is fully in view with no overscroll, and inner scrollers as their current position, which is the original position put forward by @hiikezoe and clarified by @bramus for what that means https://github.com/w3c/csswg-drafts/issues/8226#issuecomment-1353002054

**Comment by flackr** [comment]
I believe the required changes for this issue are all landed with c6c859862d018ab9d5b998cf51dc75c933505c96.
