### ISSUE TITLE
[css-view-transitions-1] How do the writing-mode and direction properties affect the view-transition pseudo-elements?

### ISSUE THREAD

**Issue by bert-github** [w3c/csswg-drafts#8230]
After reviewing the spec for i18n issues, I wasn't clear what the function of the 'writing-mode' and 'direction' properties was. They occur, e.g., in 8.3. [Setup view transition](https://www.w3.org/TR/2022/WD-css-view-transitions-1-20221124/#setup-view-transition):

>    Set capture’s [old styles](https://www.w3.org/TR/2022/WD-css-view-transitions-1-20221124/#captured-element-old-styles) to the following:
>    [...]
>
> *   [writing-mode](https://www.w3.org/TR/css-writing-modes-4/#propdef-writing-mode)
>    The [writing-mode](https://www.w3.org/TR/css-writing-modes-4/#propdef-writing-mode) of element.
>  *  [direction](https://www.w3.org/TR/css-writing-modes-3/#propdef-direction)
>    The [direction](https://www.w3.org/TR/css-writing-modes-3/#propdef-direction) of element.

And similar in 8.9. [Update pseudo-element styles](https://www.w3.org/TR/2022/WD-css-view-transitions-1-20221124/#update-pseudo-element-styles).

These properties are set on elements that are images. But they don't have effect on images, do they? In other words, would anything change if these properties were omitted from the style for these view-transition pseudo-elements?

If they do have an effect, a note or an example could be useful.

And, please, write the answer to this issue, and any explanation in the spec, in simple language! We (the I18N WG) found the spec rather difficult to understand…

**Comment by vmpstr** [comment]
The position of the image elements (i.e. the -new and -old pseudo elements) are specified in terms of block and inline directions: https://drafts.csswg.org/css-view-transitions-1/#selectordef-view-transition-old-pt-name-selector

The css here is
```css
position: absolute;
inset-block-start: 0;
inline-size: 100%;
block-size: auto;
```

The block and inline directions map to vertical or horizontal physical directions based on the writing mode.

In layperson terms, in horizontal writing mode, the CSS above says "image is located at the top of its container; the image width fills the container and the image height is automatically determined based on aspect ratio and width"

However, in vertical left-to-right writing mode (as an example), this is "image is located at the left of its container; the image height fills the container and the image width is automatically determined based on the aspect ratio and height"

It's for this reason that we capture the writing mode and direction.

In practice, this would only be noticeable with CSS that changes the group pseudo element size, which would cause the inline size and the block size of the container to differ from the aspect ratio of the new or old images

Let me know if I can elaborate on anything better

**Comment by noamr** [comment]
@khushalsagar is this actionable? Can we close this?

**Comment by khushalsagar** [comment]
@fantasai did you want to take a look at this? You mentioned that you can do an i18n review.

**Comment by svgeesus** [comment]
ping @bert-github could you confirm that our clarification resolves your concerns!

**Comment by khushalsagar** [comment]
Let me take another stab at clarifying this since it came up on https://github.com/w3c/csswg-drafts/issues/8958 this as well. Just to make sure we're preserving the right bits from computed style.

There's 2 aspects of layout that ViewTransitions sets up a default animation for :

- A change in the element's viewport based transform. This is covered in https://github.com/w3c/csswg-drafts/issues/8886.
- The size of the element. This is the animation that requires properties like writing-mode so I'll cover that below.

If an element's border box size is changing, which could also involve a change in its aspect ratio, the default animation animates between the layout sizes of the old and new element. Since the element snapshots may not match the size of the replaced element during this animation, we take the following strategy to decide how to scale the snapshots during the animation:

- In the inline direction, the snapshot scales to match the length of that edge.
- In the block direction, the snapshot scales to maintain the same aspect ratio (so there is no weird stretching).

This is because we found that in most use-cases, it's better for a single line of text to be completely visible. The content in the block direction can gradually reveal or hide itself. For example, you click on a button which expands into a details list. If the developer puts `overflow: clip` on the replaced elements, the visual effect is that you see more lines of text as the box size expands.

So we do this by copying over the `writing-mode` and `direction` from the DOM elements onto their group pseudo-element. And setting up the layout of the replaced elements using logical properties:

```css
:root::view-transition-old(*),
:root::view-transition-new(*) {
	position: absolute;
	inset-block-start: 0;
	inline-size: 100%;
	block-size: auto;
}
```

I don't think we need `text-orientation` because the effect of that properties is baked into the captured image itself, i.e, text-orientation will determine how the glyph is rendered when capturing the snapshot. So it doesn't need to impact how the pseudo-elements are rendered.

**Comment by fantasai** [comment]
> So it doesn't need to impact how the pseudo-elements are rendered.

Yes, but it can impact how the properties cascade together. E.g. whether 'margin-inline-start' maps to 'margin-top' or 'margin-bottom' in vertical writing depends on 'text-orientation'. So I think it would be good to copy them as a set.

**Comment by khushalsagar** [comment]
Added an additional note to the spec for this: https://github.com/w3c/csswg-drafts/pull/9092.
