### ISSUE TITLE
[scroll-animations-1] Interaction with 'animation-iteration-count'

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8233]
We don't define what happens if the animation-iteration-count is not 1. We could:

- ignore it entirely
- split the length of the timeline (or what remains after limiting by animation-range/delay) by the number of iterations, treating `infinite` as `1`, and loop over the keyframes for each iteration

In the latter case, things get weird if keyframes are attached using named range offsets. We could...
- attach those frames, then ignore them while attaching any other frames using the iteration count
- attach those frames, then split the timeline up by those frames and iterate any other keyframes within each interval
- something else?

CC @bramus

**Comment by ydaniv** [comment]
My initial thought was "ignore", but authors may want to create repeating effects which is otherwise very cumbersome with spreading repeats over the Keyframes set.
So I see 2 options:
1. split the length as you wrote above for finite numbers.
2. split automatically per a given duration in pixels, just like `background-repeat`, but then we'll need to also think of either a new syntax or interaction with `animation-duration`.

Also, in case of repeats there may be an interaction with `animation-direction`, as in alternate direction on repeat or not, and with `animation-delay-end` that needs to be considered.

**Comment by bramus** [comment]
Passing on to @kevers-google - I heard him talk about this before, so pretty sure he has this one figured out already.

**Comment by kevers-google** [comment]
The experimental implementation in Blink currently factors in animation-iteration-count when determining the intrinsic-iteration-duration.   Since effect end is 100% and equal to start delay + end delay + iteration count * iteration duration, we can calculate a duration that makes the end time match up when using duration auto.  Similarly if specifying a time-based iteration duration we can compute the end time and then scale/normalize accordingly to make it align to 100%.  This normalization is useful for example if setting the animation timeline to convert a time-based to a scroll-based animation.

The infinite iteration count implies that iteration-duration is zero.  At present, the spec  handles 0 duration * infinite count by resolving the product to be zero (https://www.w3.org/TR/web-animations-1/#calculating-the-active-duration).  Though using infinite iterations with a scroll-linked animation is not particularly useful, we can at least define sensible behavior.  In this case, the animation collapses to zero active duration.

**Comment by flackr** [comment]
+1 to what @kevers-google, we have implemented (and spec'd in [web-animations-2 intrinsic iteration duration](https://drafts.csswg.org/web-animations-2/#intrinsic-iteration-duration)) to split the length between iterations.

> In the latter case, things get weird if keyframes are attached using named range offsets. We could...
>
> attach those frames, then ignore them while attaching any other frames using the iteration count
> attach those frames, then split the timeline up by those frames and iterate any other keyframes within each interval
something else?

From a pure API point of view, I would expect these keyframes to work similarly to how they behave when they are outside of the `animation-range`, that being they produce a negative or positive offset within the effect.

However, animations don't create extra sets of keyframes for each iteration so having the keyframes be different for each iteration is not something that easily maps to animations. I would propose that we take a naive position and either ignore these keyframes or calculate their progress assuming a single iteration even though it will no longer map correctly after the range is split between iterations. My preference would be for the latter as I think it would be the closest to honoring what the dev asked for. E.g. if your animation-range is enter, and your keyframes are `enter 0%` and `enter 100%`, having 2 iterations would result in the effect playing twice.
