### ISSUE TITLE
[css-text-4] Renaming text-space-* to white-space-*

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8273]
In https://github.com/w3c/csswg-drafts/issues/448 @SebastianZ asked about renaming the text-space-collapse/trim properties to white-space-*. Historically there was some kind of conflict problem with XSL:FO's white-space-collapse, which takes a different set of values, which is why we had to rename it to something else.

I'm filing this issue to ask two questions:
- Do we still have a conflict problem with XSL:FO?
- If not, do we want to switch up the names to white-space-*?

CC @MurakamiShinyu @LiamQuin

**Comment by liamquin** [comment]
white-space-collapse in XSL-FO [1] when true replaces sequences of white space other than linefeed with the first white space in a sequence, so e.g. multiple spaces get turned into a single space everywhere.

white-space-treatment in XSL-FO [2] controls whether spaces go away around linefeeds, e.g. including after wrapping.

Although XSL-FO is certainly being used, and there are multiple active implementations, i'm not sure how much it matters if CSS itself has a property with a name used by XSL-FO.  You could think of XSL-FO as an XML vocabulary that incorporates CSS for styling, though.  Because of weird W3C process rules, the XSL-FO spec actually includes a copy of the CSS 2.1 properties, so that it could be published as a Recommendation, but the intent was that they would be the same.  However, XSL-FO property values are generally expressions, almost as if they were implicitly surrounded with "calc(...)", so there are limits on how compatible they can be.

Antenna House have a product that implements both CSS and XSL-FO, so they might be affected, but, again, in FO mode the values are interpreted differently anyway.

A bigger question is whether users would be confused. However, XSL-FO is primarily used in cases where CSS for paged media isn't ready or isn't sophisticated enough, and the stylesheet authors are more likely to cope with the confusion than many other users. I do think it would be better to avoid the confusion if possible, though. It also seems to me that `white-space-collapse` might be confused with margin-collapse, so that `inline-space-collapse` might be better?

[1] https://www.w3.org/TR/xsl/#white-space-collapse
[2] https://www.w3.org/TR/xsl/#white-space-treatment

**Comment by MurakamiShinyu** [comment]
I worked on Antenna House's XSL-FO & CSS implementation in the past, but presently I am not in that position. So this is my guess, but they and their users will not be much troubled by this renaming, because properties of XSL-FO and CSS are already quite different.

My impression is that "white-space-*" is a natural naming for the longhand properties of the "white-space" shorthand property.

**Comment by fantasai** [comment]
Thanks very much, @MurakamiShinyu and @liamquin ! Agenda+ to propose renaming.

> It also seems to me that white-space-collapse might be confused with margin-collapse, so that inline-space-collapse might be better?

No, CSS authors are used to `white-space` referring to actual space characters and not to margins or padding. Meanwhile `inline` is currently used as a prefix/suffix indicating things affecting the inline axis vs the block axis (e.g. we have `margin-inline` as a shorthand for `margin-inline-start` and `margin-inline-end`, which are our equivalents to XSL's `margin-start` and `margin-end`).

**Comment by SebastianZ** [comment]
Another reason to rename `text-space-*` is that it can easily get confused with `text-spacing` (and possible longhands as discussed in #4246.

And the reason why I proposed to rename them to `white-space-*` is that those properties are meant to be longhands for the [`white-space` property](https://drafts.csswg.org/css-text-4/#white-space-property).

Sebastian

**Comment by fantasai** [comment]
@SebastianZ There's no doubt in my mind that `white-space-collapse` is the better name. We were asked to move away from that by the XSL:FO a couple decades ago; but since Liam and Murakami think it's okay I think the obvious thing is to rename them back.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/3050d057dc4cf5fe0d77a96cbd116c531d3fcf43
