### ISSUE TITLE
[css-color-4] Resolving and serializing the opacity property

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#8311]
As @lilles [originally noted in passing](https://github.com/w3c/csswg-drafts/issues/7677#issuecomment-1381979976)

> we have existing interop on the opacity property not being clamped for declared values. 

The []() part is now clear that this only applies to the alpha component of `<color>` values, but now we need a separate section defining that there is no `opacity` clamping, and how this is resolved and serialized.

**Comment by cdoublev** [comment]
I think clamping should not be defined in [4.2. Representing Transparency: the `<alpha-value>` syntax](https://drafts.csswg.org/css-color-4/#alpha-syntax):

  > **4.2. Representing Transparency: the `<alpha-value>` syntax**
  >
  > `<alpha-value> = <number> | <percentage>`
  >
  > [...]
  >
  > Values outside the range [0,1] are not invalid, but are clamped to that range at parsed-value time.

It is a sub-section of *4. Representing Colors: the `<color>` type* (which means clamping only applies in this context) but the problem is that all references of `<alpha-value>` links to the above production rule.

**Comment by svgeesus** [comment]
I think the way to resolve that is not to not link to a single `<alpha-value>` production but instead:

`<alpha-value>` = `<alpha-component>` | `<opacity-value>`

The clamping of each one can then be independently specified. WDYT?

**Comment by cdoublev** [comment]
I would keep a single definition (ideally placed below `opacity` definition table) with the production rule and without clamping, and I would add a context specific definition (via `dfn-for`) below `color` definition table. 

I do not like splitting productions just to apply clamping separately, whereas these productions match the same input. Worse, I also do not like splitting `<rg-ending-shape>` and `<ending-shape>` just because `sides` is also valid in `ray()` but not in `radial-gradient()`.

Therefore I think it would be more appropriate to ask Tab Atkins.

**Comment by svgeesus** [comment]
I am concerned by this assertion in [`t32-opacity-clamping-0.0-b.xht`](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/t32-opacity-clamping-0.0-b.xht) by @dbaron (which [all browsers pass](https://wpt.fyi/results/css/css-color/t32-opacity-clamping-0.0-b.xht?label=master&label=experimental&aligned&q=opacity)):

```html
<meta name="assert" content="Opacity values less than 0.0 are clamped to 0.0" />
```
and similarly in [`t32-opacity-clamping-1.0-b.xht`](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/t32-opacity-clamping-1.0-b.xht) which again [all browsers pass](https://wpt.fyi/results/css/css-color/t32-opacity-clamping-1.0-b.xht?label=master&label=experimental&aligned&q=opacity):

```html
<meta name="assert" content="Opacity values greater than 1.0 are clamped to 1.0" />
```

So **specified** values are _not_ clamped (see [codepen](https://codepen.io/lilles/pen/YzjQEzj by @lilles) but **computed** values (which is what @dbaron was testing) _are_.

Right?

**Comment by cdoublev** [comment]
With https://github.com/w3c/csswg-drafts/commit/711296f983ad8bb84ef762dca7155076858b6df5 and https://github.com/w3c/csswg-drafts/commit/d995b3485fb98ee7557449fd0ca7c3e79a11c8c3, `opacity` is now defined with `<opacity-value>` instead of `<alpha-value>`. Below are some suggestions and remaining problems.

---

In [3.3. Transparency: the `opacity` property](https://drafts.csswg.org/css-color-4/#transparency) (CSS Color 4), this sentence seems a bit confusing to me:

  > Opacity in CSS is typically represented using the `<opacity-value>` syntax, for example in the opacity property or as the alpha component in a color function, using the `<alpha-value>` syntax.

This seems clearer: *Opacity in CSS is typically represented using `<x>` syntax, [example for `<x>`], or using the `<y>` syntax, [example for `<y>`]*.

But other specs should only use `<opacity-value>` (which is missing a production rule, unlike `<alpha-value>`) and this section is about the `opacity` property, so it could be simplified to *Opacity in CSS is typically represented using the `<opacity-value>` syntax*.

However, other specs currently use `<'opacity'>` (except [`flood-opacity`](https://drafts.fxtf.org/filter-effects-1/#FloodOpacityProperty) and [`shape-image-threshold`](https://drafts.csswg.org/css-shapes-1/#shape-image-threshold-property), which incorrectly use `<alpha-value>`):

  - `fill-opacity` (SVG 2, Fill Stroke)
  - `stop-opacity` (SVG 2)
  - `stroke-opacity` (SVG 2, Fill Stroke, SVG Strokes)
  - `shape-image-threshold` (CSS Basic Shapes 1)

So it might be simpler to define `opacity` with `<number> | <percentage>` and a prose that requires clamping at computed value time, and `<alpha-value>` with `<'opacity'>` and a prose that requires clamping at parse time.

---

In [15.1 Serializing alpha values](https://drafts.csswg.org/css-color-4/#serializing-alpha-values) (CSS Color 4), the emphasized parts below seem redundant:

  > This applies to any `<color>` value which can take an optional alpha value. **It does not apply to the `opacity` property.**
  >
  > If, **after clamping to the range `[0.0, 1.0]`** the alpha is exactly `1`, it is omitted from the serialization; an implicit value of `1` (fully opaque) is the default.

Besides, one may wonder whether `1.0` as input (tokenized to `1`) can be omitted, because it is not *exactly* `1` and the specs do not clearly define when a component value can be omitted when serializing a specified value, at the moment (see https://github.com/w3c/csswg-drafts/issues/5642#issuecomment-1717185053)

**Comment by cdoublev** [comment]
> In *15.1 Serializing alpha values* (CSS Color 4), the emphasized parts below seem redundant:
  >
  > > [...] If, **after clamping to the range [0.0, 1.0]** the alpha is exactly 1 [...]

Actually I would remove it from [4.2. Representing Transparency in Colors: the `<alpha-value>` syntax](https://drafts.csswg.org/css-color-4/#alpha-syntax):

  > Unless otherwise specified, an `<alpha-value>` component of a color defaults to 100% when omitted. **Values outside the range `[0,1]` are not invalid, but are clamped to that range at parsed-value time**.

I agree with https://github.com/w3c/csswg-drafts/issues/7677#issuecomment-1380872899, you just need the specified value to be clamped. Implementers may choose to do it at parse time or not.

**Comment by svgeesus** [comment]
> I agree with https://github.com/w3c/csswg-drafts/issues/7677#issuecomment-1380872899, you just need the specified value to be clamped. Implementers may choose to do it at parse time or "just in time" when serializing the specified value.

The various specs use "parsed value time" frequently. Determining whether this has actually been done at parse time or when serializing the specified value is not, afaict, observable.

**Comment by svgeesus** [comment]
> Besides, one may wonder whether `1.0` as input (tokenized to `1`) can be omitted, because it is not _exactly_ `1` and the specs do not clearly define when a component value can be omitted when serializing a specified value, at the moment (see [#5642 (comment)](https://github.com/w3c/csswg-drafts/issues/5642#issuecomment-1717185053))

Oh, you mean because that implies a float comparison (if the value is stored as a float)? Maybe we could say "if the serialized value would be '1' or something like that?

**Comment by cdoublev** [comment]
At the current state of #5642, I would just write `[0,1]` instead of `[0.0,1.0]` to define the range, and remove *exactly*.

But *"remove `x` if it serializes as the default value"* is probably the simplest implementation and makes sense to me. It implies that `calc(1)` cannot be omitted, but some browsers currently remove math functions representing default values in some places.

**Comment by cdoublev** [comment]
As I already noted [above](https://github.com/w3c/csswg-drafts/issues/8311#issuecomment-1892198235), `<opacity-value>` is  missing a production rule: `<opacity-value> = <number> | <percentage>` (`<alpha-value>` already has one) but imo `<opacity-value>` can just be removed and `opacity` can be defined with `<number> | <percentage>`: other specs must use `<'opacity'>` to represent an opacity value, as they already do.

But of course you may have reasons not to follow these suggestions.

**Comment by svgeesus** [comment]
> other specs must use `<'opacity'>` to represent an opacity value, as they already do.

The issue I see with that, is that it is linking to a property definition (the opacity property), not to a value type. 

I also see some other specs allow only `<number` while others accept `<number> | <percentage>`.

I agree that a production rule needs to be added.

**Comment by cdoublev** [comment]
I understand your concern about using `<'opacity'>` in other property value definitions. Productions of property value ranges embed the semantics of the property and are more often used in shorthand value definitions, or in properties that are semantically related: `background-blend-mode` with `<'mix-blend-mode'>`, `block-size` with `<'width'>`, etc.

I cannot find any property that only allows `<number>` to express an opacity or transparency value.

**Comment by svgeesus** [comment]
> I cannot find any property that only allows `<number>` to express an opacity or transparency value.

[`shape-image-threshold`](https://drafts.csswg.org/css-shapes-1/#shape-image-threshold-property) says 

> [`<number>`](https://drafts.csswg.org/css-values-4/#number-value)
    Sets the threshold used for extracting a shape from an image.

**Comment by cdoublev** [comment]
I filled #9884 about `<percentage>` for `shape-image-threshold`.

**Comment by svgeesus** [comment]
Yes, I think `<opacity-value>` is correct there
