### ISSUE TITLE
Interaction with Safari's back/forward previews

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8333]
Both Safari iOS and Safari Desktop have a feature where you see a 'preview' of the previous history entry when you drag from the edge (iOS) or two-finger swipe (Desktop). This includes same-document traversals.

https://user-images.githubusercontent.com/93594/213422693-c1f607e7-de00-4c8e-9be2-86d4d48cc93f.mp4

https://user-images.githubusercontent.com/93594/213422739-3a773a47-cb7e-4a5a-a578-c4bcd7dc5cda.mp4

This already causes issues in cases where developers have created their own transition. Demo: https://static-misc-3.glitch.me/basic-navigation-transition/. Here's what happens:

1. User is on "state 2".
2. User drags from the left, revealing a screenshot of "state 1".
3. Navigation commits, but since it's same-document, it's still in "state 1".
4. Developer gets a `popstate` event, so they begin a transition from "state 1" to "state 2", meaning it looks like things 'snap back' to "state 2".

https://user-images.githubusercontent.com/93594/213426547-7a76c525-c974-44a4-a48f-9055cd865a15.mp4

It feels like we should avoid this kind of experience with view transitions (both SPA and MPA) at least.

I think a good starting point is: Is there something developers should be doing today to avoid this kind of experience in Safari? If not, we can invent something 😀

@smfr any ideas around this? It seems to be a problem in the wild https://twitter.com/ryanflorence/status/1362095580827160578

**Comment by khushalsagar** [comment]
This is an issue even without View Transitions, an SPA could do custom transitions with any internal framework.

**Comment by romainmenke** [comment]
Also doesn't need to be an SPA :)

click any of big titles and then swipe for a back preview :
https://www.hugoandmarie.com/creative/

There is no way to tell Safari when it should create these previews.
So any "outro" animation will mess with it.

We never found away to make these previews work properly and have transitions.

<img width="1250" alt="Screenshot 2023-01-19 at 19 12 38" src="https://user-images.githubusercontent.com/11521496/213526384-5a3a0b9e-5b7b-4322-bff2-ef3ac7239efc.png">

**Comment by khushalsagar** [comment]
@romainmenke, I'm able to repro the issue on the site above. Do you mind clarifying the timing of the animation with the navigation? What event do you use to trigger the animation?

I'm seeing 2 classes of problems with these default transitions. I think solving Double Transition is easier so we could start with the small API proposal for it below. @domenic @annevk thoughts?

**Double Transition**
The browser does a transition in response to swipe and the author (who is unaware of this transition) does a transition after. @jakearchibald's demo and the twitter thread above shows that clearly. A trivial way developers can avoid this is by being notified that there's already been a browser transition for a navigation. Something like:

```js
window.addEventListener('popstate', (event) => {
  if (event.hasBrowserTransition) {
   navigateOnly();
    return;
  }

  navigateAndAnimate();
});

navigation.addEventListener('navigate', (event) => {
  if (event.hasBrowserTransition) {
    navigateOnly();
    return;
  }

  navigateAndAnimate();
});
```

**Incorrect Capture**
The browser captures a visual state which is inconsistent with what the user will see on back. This could be from multiple cases:

1. An exit animation like in the comment above.
2. Transient UI which is intentionally removed by the page. Example.
3. User interacted with the page before navigation and a new load doesn't have the mutations in response to that interaction. Scroll restoration takes care of the common case of restoring the scroll offset but not everything. This also depends on whether the nav gets a BFCache hit.

This is harder to solve. We could add a hook where the browser informs the page that it will be captured for a preview and should set up state accordingly. But given #3, it's not deterministic what the user will see at the time the browser would ideally do a capture (the last frame rendered by the outgoing page).

**Comment by romainmenke** [comment]
> I'm able to repro the issue on the site above. Do you mind clarifying the timing of the animation with the navigation? What event do you use to trigger the animation?

In short :

- user hovers a link that is "transitionable"
- prefetch/prerender the target page
- user clicks a link that is "transitionable"
- play the matching outro
- trigger the navigation

We have to be careful to undo the outro when a user navigates back but other than that it is a fairly simple setup.

Browsers avoid a flash of white in between navigations, so it appears to be seamless like an SPA transition. But it is just `hover` and `click` events.

Because this is al just hacks there is no way for Safari to "understand" that we are playing an outro. It captures the back preview when the actual navigation happens, not when the user clicks the link.

**Comment by khushalsagar** [comment]
Got it, so you consume the click to do an animation and then trigger the navigation.

> We would never implement anything like this if there was a native API for transitions of this kind. Today there is no native way.

Glad to hear this. So a primitive like [cross-document ViewTransitions](https://github.com/WICG/view-transitions/blob/main/explainer.md#cross-document-same-origin-transitions) would help. If the animation is expressed using a browser primitive, then the browser knows what to capture.

**Comment by jakearchibald** [comment]
Filed https://github.com/whatwg/html/issues/8782 with a proposal

**Comment by khushalsagar** [comment]
@fantasai This issue is still on our priority list, https://github.com/whatwg/html/issues/8782 was discussed at the html triage meeting and we're waiting for feedback from other implementors.

I don't think this needs to be a blocker for VT L1 though. Interaction with UA transitions is a problem irrespective of View Transitions, since authors can create them for same-document navigations with a framework other than VT. And conversely, VT has no way of knowing if a transition is in response to a navigation or just any DOM change. Sounds reasonable?

**Comment by khushalsagar** [comment]
Chatted with @fantasai offline. The solution for this problem is tracked in https://github.com/whatwg/html/issues/8782 and https://github.com/w3c/csswg-drafts/issues/8747 but I'm putting this on the agenda to confirm with the group that VT L1 doesn't need to block on this.

**Comment by khushalsagar** [comment]
I'll close this in favour of https://github.com/whatwg/html/issues/8782 which addresses the problem described in this issue. The API addition will need to be in the html spec.

**Comment by js-choi** [comment]
For any other outsiders reading about this: The current state-of-the-art proposal for dealing with default UA back/forward transitions in Safari and Android seems to be at [default-ua-transitions.md](https://github.com/WICG/view-transitions/blob/main/default-ua-transitions.md). This was last updated in 2023.

I also have a couple of questions:

In https://github.com/whatwg/html/issues/8782#issuecomment-1591586904, @khushalsagar explains:

> That's why we need a 2 part API for this problem:
> 
> 1. An API which lets the author specify whether they prefer to override a navigation transition.
> 2. An API which informs the author of the UA's decision.
> 
> This API [i.e., adding `hasUAVisualTransition` to `PopStateEvent` and `NavigateEvent`] is doing 2. We'd like to not block this on 1 since its easier to do first and makes sense as a standalone API. UAs already make the decision for whether to choose UA or author transition which this API communicates to the author.

As far as I can tell, whatwg/html#8782 only addresses informing the author of the UA’s decision on whether it will use the author’s visual transition in *same-document* transitions.

But it does *not* seem to address informing the author of the UA’s decision in *cross-document* transitions, since `hasUAVisualTransition` requires JavaScript.

1. Is the expectation that a UA will simply not animate an author-provided cross-document transition whenever the UA prefers to do its own default transition (like when swiping back/forward in history)?
2. I don’t see any active issues in this repository devoted to [default-ua-transitions.md](https://github.com/WICG/view-transitions/blob/main/default-ua-transitions.md).
   - Has there been recent work on the “API which lets the author specify whether they prefer to override a navigation transition”?
   - Should a new issue devoted to that API be opened here?

**Comment by domenic** [comment]
> But it does _not_ seem to address informing the author of the UA’s decision in _cross-document_ transitions, since `hasUAVisualTransition` requires JavaScript.

I don't understand the connection between the two halves of these sentences. Cross-document transitions can be seen with JavaScript just as easily as same-document transitions, using `NavigateEvent`'s `hasUAVisualTransition`.

**Comment by js-choi** [comment]
> I don't understand the connection between the two halves of this sentence. Cross-document transitions can be seen with JavaScript just as easily as same-document transitions, using NavigateEvent's hasUAVisualTransition.

@domenic: Yes, sorry, you’re right; I misspoke here. (Cross-document transitions were strongly coupled in my mind to CSS-only, no-JavaScript solutions, but of course that’s not necessarily true.) I’ve crossed out that sentence in the comment.

To sharpen my first question: In Safari 18.4, sliding to navigate back in history does seem to suppress author-provided cross-document transitions. But I could not confirm whether this “don’t do a cross-document transition if a visual transition was already done by the user agent” behavior is actually specified anywhere in [CSS View Transitions Level 2](https://drafts.csswg.org/css-view-transitions-2/).

(It’s also still worth asking whether a new issue for “an API which lets the author specify whether they prefer to override a navigation transition”—i.e., the bulk of [default-ua-transitions.md](https://github.com/WICG/view-transitions/blob/main/default-ua-transitions.md)—is worth opening. Alternatively, this issue could be reopened.)

**Comment by bramus** [comment]
> Cross-document transitions can be seen with JavaScript just as easily as same-document transitions, using `NavigateEvent`'s `hasUAVisualTransition`.

There is no way to detect `hasUAVisualTransition` on Cross-Document Navigations, though. I believe this info should be exposed on `NavigationActivation` – See https://github.com/whatwg/html/issues/10831

**Comment by js-choi** [comment]
Along with whatwg/html#10831 for detecting `hasUAVisualTransition` on cross-document navigation—it looks like I missed that w3c/csswg-drafts#8747 is also still open.
