### ISSUE TITLE
[css-view-transitions-1] Capturing fragmented elements

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#8339]
[View transitions](https://drafts.csswg.org/css-view-transitions-1/#capture-the-image-algorithm) specify that the image should be captured at the same size as in the document

> Render element and its [descendants](https://dom.spec.whatwg.org/#concept-tree-descendant), at the same size it appears in its [node document](https://dom.spec.whatwg.org/#concept-node-document), over an infinite transparent canvas, following the [capture rendering characteristics](https://drafts.csswg.org/css-view-transitions-1/#capture-rendering-characteristics).

It's unclear what to do if the element is fragmented. Is this supposed to capture the union of the fragment sizes/positions or something else?

I can't think of any good example where a developer would want to transition a fragmented element, so my proposal is to treat an element that is fragmented as invalid element to share in a view transition and skip the transition.

**Comment by flackr** [comment]
As a developer I would expect the union of the fragments to be captured. FYI this is also done by the element() function: https://jsbin.com/wukobal/edit?html,css,output

I think not doing this is just making users add or use a wrapping element which they wouldn't otherwise have had to use to e.g. transition from article content in columns.

**Comment by khushalsagar** [comment]
The definition for how to get the bounding box for a fragmented element is [here](https://w3c.github.io/csswg-drafts/css-images-4/#element-notation:~:text=for%20an%20element%20rendered%20using%20a%20CSS%20rendering%20model%2C%20the%20decorated%20bounding%20box%20is%20the%20smallest%20axis%2Daligned%20rectangle%20that%20contains%20the%20border%20image%20areas%20of%20all%20the%20fragments%20of%20the%20principal%20box), which does take a union of all fragments. This spec uses the border image areas of each fragment (since snapshots are clipped to the element's border box). In VT's case, that would be the ink overflow areas of each fragment.

**Comment by vmpstr** [comment]
I still don't think there are good cases where transitioning a fragmented element makes for a good visual transition. I understand that there's nothing to stop developers from trying, I just don't think that this is a use-case that is important.

There are also complexities with things like transforms where each fragment is transformed independently, which doesn't align with our model of "capture contents without transform, and then apply the transform to the corresponding group pseudo". Specifically, performing the steps in our model will not result in the same visual look as original fragments. There are also complexities with overflow and object-view-box calculations in these cases. 

So in general, I'd still like us to say that you cannot transition a fragmented element. I don't have a strong preference between skipping the whole transition or omitting the fragmented element from participating. We can also consider a new break-inside value to ensure the element cannot fragment (TIL that break-inside: avoid still sometimes fragments)

**Comment by flackr** [comment]
For transformed fragments one way this could work is to bake the transform into the captured pixels and only apply any transforms from outside the fragmentation. For example, consider how this is captured with the element() function in Firefox:

https://jsbin.com/pozumog/edit?html,css,output

We could do the same except include in the ink overflow the content which flowed outside of the bounding box of the fragments.

**Comment by khushalsagar** [comment]
The Firefox implementation doesn't seem to align to the [spec](https://w3c.github.io/csswg-drafts/css-images-4/#element-notation:~:text=If%20the%20referenced%20element%20has%20a%20transform%20applied%20to%20it%20or%20an%20ancestor%2C%20the%20transform%20must%20be%20ignored%20when%20rendering%20the%20element%20as%20an%20image.), it explicitly states that transforms on the element should be ignored: "If the referenced element has a transform applied to it or an ancestor, the transform must be ignored when rendering the element as an image."

View Transition [spec](https://drafts.csswg.org/css-view-transitions-1/#capture-rendering-characteristics:~:text=If%20the%20referenced%20element%20has%20a%20transform%20applied%20to%20it%20(or%20its%20ancestors)%2C%20then%20the%20transform%20is%20ignored) handles transforms the same way, they are ignored when rendering the element's image: "If the referenced element has a transform applied to it (or its ancestors), then the transform is ignored".

This model makes sense for non-fragmented content since the element's screen space transform, which includes layout position, transform from ancestors and its local transform; is applied to the pseudo-element displaying it. We'll have to carve out many special cases for fragmented elements:

- Figure out what the border box size should be to decide what to size its ::view-transition-group. We've talked about unioning the rects of each fragment, but I'm not sure what these rects are relative to.
- Render the image with the local transform, as opposed to without it in the default case.
- Figure out what the image size should be. This is different from the non-fragmented case where we take the ink overflow rectangle. This size will be the union of transformed rects for each fragment with their overflow.
- Figure out what the object-view-box should be. In the default case its the value which places the border-box origin in the image at ::view-transition-group's pseudo's origin.

I'm not saying the above is not doable, but its a lot of complexity for an esoteric case that I don't think is worth doing. Though would be good to get another implementor's take on this: @emilio @dholbert.

Also @vmpstr, @bfgeek and @chrishtr who probably know a lot more complications with this case than me; and have expressed disallowing transitions on a fragmented element as the better option. Please clarify if I misunderstood.

**Comment by jakearchibald** [comment]
> The Firefox implementation doesn't seem to align to the [spec](https://w3c.github.io/csswg-drafts/css-images-4/#element-notation:~:text=If%20the%20referenced%20element%20has%20a%20transform%20applied%20to%20it%20or%20an%20ancestor%2C%20the%20transform%20must%20be%20ignored%20when%20rendering%20the%20element%20as%20an%20image.), it explicitly states that transforms on the element should be ignored: "If the referenced element has a transform applied to it or an ancestor, the transform must be ignored when rendering the element as an image."
> 
> View Transition [spec](https://drafts.csswg.org/css-view-transitions-1/#capture-rendering-characteristics:~:text=If%20the%20referenced%20element%20has%20a%20transform%20applied%20to%20it%20(or%20its%20ancestors)%2C%20then%20the%20transform%20is%20ignored) handles transforms the same way, they are ignored when rendering the element's image: "If the referenced element has a transform applied to it (or its ancestors), then the transform is ignored".

I'm not convinced these are the same. With view transitions we apply ancestor transforms, and capture the target transform. The `element()` spec is vague, but I'm not sure "the transform must be ignored" is the same thing.

The `element()` spec does have specific things to say about fragmentation:

> If the referenced element is broken across pages, the element is displayed as if the page content areas were joined flush in the pagination direction, with pages' edges corresponding to the initial containing block’s start edge aligned. Elements broken across lines or columns are just rendered with their [decorated bounding box](https://w3c.github.io/csswg-drafts/css-images-4/#decorated-bounding-box).

I'm not 100% sure what this means, particularly in the multi-column layouts where the column widths are not equal (which [seems to be possible using negative margins](https://stackoverflow.com/a/29156418/123395), although that might be an implementation bug).

**Comment by jakearchibald** [comment]
Summary for CSSWG:

When an element is captured as part of a view transition, we ignore all ancestor & element transforms when capturing the image, and apply a transform to the group that positions the element in the correct place in relation to the snapshot viewport. So, if the difference between the old & new view is that the element has been rotated 90 degrees, by itself or a parent, you'll get a rotating transition, rather than just a cross-fade.

Elements can become fragmented, eg across columns. When transforms are applied to fragmented elements, the transform is applied to each fragment individually. This isn't compatible with the view transition model that wants to capture the element as a single image + a single transform.

It's unclear whether view transitions are desirable on elements that fragment. Particularly if the amount of fragmentation is different between the old and new views. Eg, going from fragmented across 2 columns, to fragmented across 3.

Prior art: [The `element()` spec](https://w3c.github.io/csswg-drafts/css-images-4/#element-notation:~:text=If%20the%20referenced%20element%20has%20a%20transform%20applied%20to%20it%20or%20an%20ancestor%2C%20the%20transform%20must%20be%20ignored%20when%20rendering%20the%20element%20as%20an%20image.) says:

> If the referenced element is broken across pages, the element is displayed as if the page content areas were joined flush in the pagination direction, with pages' edges corresponding to the initial containing block’s start edge aligned. Elements broken across lines or columns are just rendered with their [decorated bounding box](https://w3c.github.io/csswg-drafts/css-images-4/#decorated-bounding-box).

I'm not 100% what that means. Firefox's implementation seems to capture the union of all fragment rects before transforms are applied, but captures the pixels with transforms applied ([demo](https://jsbin.com/pozumog/edit?html,css,output)).

## Option 1: Fragmentation breaks view transition constraints

Because it's complicated, and seemingly not desirable, make no-fragmentation a constraint.

When constraints are broken, transitions skip to the end ([previous resolution](https://github.com/w3c/csswg-drafts/issues/7882)).

**Sub-option**: Is the constraint broken if an element fragments, or if an element can fragment?

[Previous resolution](https://github.com/w3c/csswg-drafts/issues/8139): A `view-transition-name` value that isn't `none` gives an element stacking context, grouping element, backdrop root, similar to non-1 `opacity`, as view transitions need these constraints.

**Sub-option**: Should a non-none `view-transition-name` prevent an element being fragmented? This would be in line with a previous resolution.

## Option 2: The view transition only applies to the first fragment

This doesn't seem useful, but it's not-failing. It's also an easily-definable rule. You could argue that how transforms apply to fragments is similarly not-useful, but also not-failing.

## Option 3: Capture union of fragments with transforms baked-in

This is taking inspiration from what Firefox does with `element()`, which may not be in line with the spec.

We capture the transform for the transition group, for fragmented elements, by:

1. Remove any transform from the element.
2. The quad is a union of fragment quads.
3. Figure out the transform needed to place the quad in the snapshot root, equivalent to its current position.
4. Reapply the element's transform.
5. Capture the image. Anything overflowing the quad is ink overflow.

Again, it isn't clear if this is useful, but it's not-failing. It's much more complex than option 2, but involves all fragments.
