### ISSUE TITLE
[css-display] editorial: some "Expands to:" tooltips are wrong

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#834]
https://drafts.csswg.org/css-display/#the-display-properties
When hovering `<display-outside>` etc, there are duplicates and unwanted text items.
For example, hovering  `<display-inside>` lists all values twice, and also has an illegal "flow layout" value.
The same problem occurs in `<display-internal>` and other places.

**Comment by tabatkins** [comment]
Woo, done! That was harder than I expected.

* The illegal "flow layout" value (and a few other illegal values) are a result of bad markup. I've fixed in the ED, but we need to push a fixed WD to avoid other specs getting those values.
* The duplication was an accidental result of some other refactoring work I did. Fixed now.
