### ISSUE TITLE
[css-tables] Ignorable whitespace and tables.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#8358]
It seems WebKit and Blink ignore whitespace text nodes in tables unconditionally, see [this test-case](https://bug1811353.bmoattachments.org/attachment.cgi?id=9314059). I found the [Blink code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/text.cc;l=264;drc=c74dba0e87527f5271d3f0c884f768d299b9b258), I didn't dig into the WebKit one.

I don't think the spec mandates this, and it's not super-hard to support in Firefox, but is it intentional? It definitely seems weird.

It should either be specified or tested. This broke a diff page in Firefox, see [bug 1811353](https://bugzil.la/1811353).

cc @bfgeek @FremyCompany @tabatkins  @jrmuizel

**Comment by FremyCompany** [comment]
You are correct that Webkit/Blink behavior is not what is described in the spec.
I have always considered it as a bug.

The spec is in fact quite clear that this is not the correct behavior.
> ![image](https://user-images.githubusercontent.com/364405/214702576-28a71095-be57-4e03-977b-fb06ddda3488.png)
In this case, the space between the inline blocks should not be removed because inline-block is not a (non-root) table box.

However, the grouping of these two elements in the same cell is described here:
> ![image](https://user-images.githubusercontent.com/364405/214703008-baf89cdd-ea38-4c30-ab20-ab466fd65c6a.png)

Per spec, gecko has the correct behavior. We could of course always change the spec, but what we have now is intentional (some of the discussion being recorded in #467).

**Comment by FremyCompany** [comment]
I would note that CSS 2.1 already specified the same behavior as the current spec, the current spec only tried to make the behavior more explicit.

**Comment by emilio** [comment]
Ah, I see. Yeah, I had missed that bit of the spec. I agree the Gecko behavior is more consistent over-all. I'll file bugs in chromium / webkit.

**Comment by emilio** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1410345 / https://bugs.webkit.org/show_bug.cgi?id=251178
