### ISSUE TITLE
[css-anchor-1] Allow smooth transitioning between fallback positions

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#8372]
(I'm filing this to discuss the [inline issue](https://drafts4.csswg.org/css-anchor-1/#issue-da47c41b) in the spec)

In the current spec, fallback position styles are [applied at used value time](https://drafts4.csswg.org/css-anchor-1/#fallback-apply), which means we cannot create a smooth transition when switching between two fallback positions. 

To solve this, @tabatkins and I had an offline discussion today. Below is the summary:

---

First of all, the only proper way to solve it is to apply fallback position styles at computed value time. Any other approach (i.e., using view transition) seems to create more problems than it solves.

Then there are two approaches. Both are fine on their own, but give different tradeoffs between behavior cleanliness and implementation complexity (on top of the existing impl in Chromium).

### 1. Also decide which fallback position to use when snapshotting the scroll offsets

We are currently [snapshotting the scroll offsets](https://drafts4.csswg.org/css-anchor-1/#snapshotted-scroll-offset) of the relevant scrollers at the beginning of a frame update, and use it later during layout to decide which fallback position to use.

In this approach, we can do more when taking the snapshot: we can snapshot everything we need from the previous frame's layout, decide which fallback position to use, and then apply that to the computed style. Similar as before, this means we may be applying an incorrect fallback position, in which case we trigger another frame update to fix it.

This also gives a solution to #8171: we introduce a CQ-like query that actually queries the snapshot.

### 2. Make fallback positioning CQ-like, and completely get rid of snapshotting

With the same idea of container queries, we can pause the style resolution of an element if it's anchor positioned, and resume at layout time. As now we have all the layout information needed, we can choose and apply the correct fallback position to the computed style.

This is feasible since we require that the anchor element must be laid out before the target element.

This also gives a cleaner behavior, since we will never apply any stale information and trigger another frame to fix it, so rendering is always stable. #8171 is also solved naturally.

---

The discussion may also extend to a broader context: what to do when we have style depending on layout?

We currently have scroll-linked animations and anchor positioning that snapshot the previous frame, and container queries that do interleaving style and layout based on explicit dependencies between elements (as long as the dependency is acyclic).

Theoretically, we can use the same approach to solve all of them. And the CQ-like approach always seem to give a cleaner behavior, so it's still a tradeoff between implementation complexity and cleaner spec.

cc @mfreed7 @bfgeek @andruud

**Comment by xiaochengh** [comment]
As an implementor, I personally prefer to adopt idea 1 first to enable the behavior, and then leave the discussion open for whether we need to switch to behavior 2.

**Comment by andruud** [comment]
(2)

For scroll-linked animations, it's not going to work with the current API at least. It works for CQ because we have sufficient containment at the interleaving points and also cannot query "self", but e.g. the `view-timeline` property on some element can drive an animation (possibly layout-affecting) on _that same element_.

For position-fallback, it sounds preferable to the current used-value time behavior, if we can make it work.

**Comment by andruud** [comment]
In my opinion, this issue (and others, e.g. https://github.com/w3c/csswg-drafts/issues/9149) shows that the current path we're on with fallbacks being applied at used-value time just isn't workable.

Spec:

> This implies that the values can’t be transitioned in the usual fashion, since transitions key off of computed values and we’re past that point. However, popovers sliding between positions is a common effect in UI libs. Probably should introduce a smooth keyword to [position-fallback](https://drafts.csswg.org/css-anchor-position-1/#propdef-position-fallback) to trigger automatic "animation" of the fallback’d properties.

Inventing totally new animation concepts in an attempt to fix the problems from doing the wrong thing doesn't seem worth it at all. (Although I realize that part of the spec doesn't necessarily represent very refined thought on this issue). If we can't make this integrate reasonably with existing CSS, I'd rather drop the feature completely.

---

Re. the CQ model:

> This is feasible since we require that the anchor element must be laid out before the target element.

So the target element can't via its fallback-style affect the layout of the anchor element, nor affect any other layout that would cause a different fallback-style to be chosen? (I guess that would cause problems with the current impl. too).

I assume this approach has _some_ associated difficulty? (Otherwise why aren't we just doing it? :slightly_smiling_face:). @bfgeek (since @xiaochengh is OOO).

**Comment by tabatkins** [comment]
Closing this as part of #9598 now
