### ISSUE TITLE
[web-animations-1] Should a property be not animatable by default?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8428]
I created a few PRs to add `Animation Type` to property definitions that were missing this field, because [Web Animations 1](https://drafts.csswg.org/web-animations-1/#animating-properties) says:

  > Unless otherwise specified, all CSS properties are animatable.

There might be some reason for this choice but if not, I think it would be easier to define properties as *not animatable unless otherwise specified*, eg. when they are not defined with `Animation Type`.

**Comment by birtles** [comment]
Good question.

I don't recall, but I suspect this came about because when CSS transitions etc. were introduced, we didn't want to have to edit all the specs in order to mark all the properties as animatable. Rather, we just defined, e.g. how to animate a `<length>` and if the property took a `<length>` it would animate using that definition unless it explicitly opted out of it.

If we're now at the point where all the specs have `Animatable type` specified, then we _could_ switch that definition to default to not animatable as suggested.

Personally, I think the cases where we _don't_ want a property to be animatable are very few (e.g. `animation-*` properties and possibly `display`) such that they are very much the exception and require justification for why they are _not_ animatable so keeping animatable as the default makes sense to me in that regard.

**Comment by cdoublev** [comment]
You are right. There are very few non animatable properties and the risk of a spec author introducing one because `Animation type: not animatable` would not be defined, is very low.

I suggested to add `Animation type: not animatable` to properties from [CSS Spatial Navigation](https://drafts.csswg.org/css-nav-1/) and [CSS Speech](https://drafts.csswg.org/css-speech-1/), but actually I am not sure all properties from CSS Speech should be not animatable, eg. `voice-volume`, `voice-balance`, `voice-rate`, etc.

**Comment by birtles** [comment]
Thanks for following up here.

> I suggested to add `Animation type: not animatable` to properties from [CSS Spatial Navigation](https://drafts.csswg.org/css-nav-1/) and [CSS Speech](https://drafts.csswg.org/css-speech-1/), but actually I am not sure all properties from CSS Speech should be not animatable, eg. `voice-volume`, `voice-balance`, `voice-rate`, etc.

Generally we should make all properties, even if it is only discrete animation, unless there's a reason not to (e.g. creating cyclic dependencies with the animation parameters). Without knowing the CSS Speech spec, my initial assumption is that all the `voice-*` properties should be animatable.

**Comment by cdoublev** [comment]
I assume you meant *we should make all properties **animatable***.

Yeah, I realized this while reviewing all non animatable properties or missing *Animation type*.

Among non-animatable properties, `background-blend-mode` and `mix-blend-mode` are the only non animatable properties I wonder why their animation type cannot be *discrete*, therefore I created this [issue](https://github.com/w3c/fxtf-drafts/issues/497).

Among properties missing *Animation type*, only those from CSS Spatial Navigation and other properties than `voice-*` from CSS Speech, should be non animatable, imo.

**Comment by birtles** [comment]
> I assume you meant _we should make all properties **animatable**_.

Yes, sorry!

> Yeah, I realized this while reviewing all non animatable properties or missing _Animation type_.
> 
> Among non-animatable properties, `background-blend-mode` and `mix-blend-mode` are the only non animatable properties I wonder why their animation type cannot be _discrete_, therefore I created this [issue](https://github.com/w3c/fxtf-drafts/issues/497).
> 
> Among properties missing _Animation type_, only those from CSS Spatial Navigation and other properties than `voice-*` from CSS Speech, should be non animatable, imo.

Thanks, that sounds great.
