### ISSUE TITLE
[css-color-4] Allow out-of-gamut HSL/HWB colors (previously "Move gamut mapping to a future spec")

### ISSUE THREAD

**Issue by mysteryDate** [w3c/csswg-drafts#8444]
[Section 13.2 of CSS Color 4](https://www.w3.org/TR/css-color-4/#css-gamut-mapping) contains a non-normative section describing a binary search gamut-mapping algorithm. Though user agents are beginning to ship CSS Color 4, there is still a lot of ongoing debate over the appropriateness of this algorithm (https://github.com/w3c/csswg-drafts/issues/7610). Proposed alternatives can be found here: https://github.com/w3c/csswg-drafts/issues/7653.

Some UA developers met recently to discuss the issue. A consensus was reached that it would be better to allow out-of-gamut color conversions to remain out-of-gamut (as opposed to clipping) while the working group continues to develop a gamut mapping algorithm. To that end, we could move the entire section 13 to a CSS Color 5 or 6 while this work is being done.

For CSS Color 4, [step 8](https://www.w3.org/TR/css-color-4/#convert-hslhwb) in converting colors could be removed. And since colors are now possibly out-of-gamut [Converting sRGB Colors to HSL](https://www.w3.org/TR/css-color-4/#rgb-to-hsl) would need to deal with rgb channels outside of the [0,1] range:

```js
/**
 * @param {number} red - Red component
 * @param {number} green - Green component
 * @param {number} blue - Blue component
 * @return {number[]} Array of HSL values: [snip]
 */
function rgbToHsl (red, green, blue) {
   red =   Math.min(Math.max(red,   0), 1); 
   green = Math.min(Math.max(green, 0), 1);
   blue =  Math.min(Math.max(blue,  0), 1);
   let max = Math.max(red, green, blue);
 ```
 
  Since `color-mix()` from CSS Color 5 is the only feature for color 4 or 5 that can result in intermediate out-of-gamut results, our exposure to out-of-gamut colors would remain relatively minimal and we can preserve interoperability. Leaving out-of-gamut results and not clipping avoids the worst results, like saturation at the boundaries and different results for canvases. It has the added bonus of color conversions round tripping.

**Comment by LeaVerou** [comment]
I think there are some misunderstandings here.

- The primary place that gamut mapping happens, is **to display a color on the user's actual screen**, and that's the kind of gamut mapping you cannot avoid. When it gets down to hardware, you cannot output 120% of a component, you need to map, and simply clipping tends to produce unacceptable results, unless you're close to the gamut boundary.
- I think (@svgeesus please confirm) that we (editors of CSS Color) are happy to have intermediate calculations not be gamut mapped, since most of them should happen within infinite gamut spaces anyway. What matters is gamut mapping for display.
- If intermediate calculations are not gamut mapped, this would affect what authors read back as used values through the CSSOM; so there needs an alternate way for them to figure out what color is actually displayed, though that could be a [Color API](https://github.com/wicg/color-api) method.

> Some UA developers met recently to discuss the issue. 

Do you mean that you met with your team, or was this a more diverse group of UA developers, including developers from other UAs? If it's the latter, I don't understand why the discussion did not happen in the CSS WG; that's what it's for. If the former, it would be helpful to phrase it that way to prevent misunderstandings.

> To that end, we could move the entire section 13 to a CSS Color 5 or 6 while this work is being done.

Please note that CSS Color 5 is pretty mature, with all of its current features cleared for shipping.

> For CSS Color 4, [step 8](https://www.w3.org/TR/css-color-4/#convert-hslhwb) in converting colors could be removed. And since colors are now possibly out-of-gamut [Converting sRGB Colors to HSL](https://www.w3.org/TR/css-color-4/#rgb-to-hsl) would need to deal with rgb channels outside of the [0,1] range:
> 
> ```js
> /**
>  * @param {number} red - Red component
>  * @param {number} green - Green component
>  * @param {number} blue - Blue component
>  * @return {number[]} Array of HSL values: [snip]
>  */
> function rgbToHsl (red, green, blue) {
>    red =   Math.min(Math.max(red,   0), 1); 
>    green = Math.min(Math.max(green, 0), 1);
>    blue =  Math.min(Math.max(blue,  0), 1);
>    let max = Math.max(red, green, blue);
> ```

This is still a form of gamut mapping, just not a very good one; you’re basically doing [clipping](https://drafts.csswg.org/css-color-4/#GM-clip). 

> Since `color-mix()` from CSS Color 5 is the only feature for color 4 or 5 that can result in intermediate out-of-gamut results

This is incorrect. Relative Color Syntax can also produce out of gamut results, as well as directly specifying values in LCH, Lab, OKLab, OKLCH. I would expect these to be far more common ways of getting OOG than `color-mix()`. 

I think part of the confusion lies on the fact that there are two types of out-of-gamut:

a) Out of gamut of the specified color format (e.g. `rgb(from red, calc(r * 1.05) g b)` is OOG for sRGB, even though it's not OOG for a P3 display)
b) Out of gamut *of the display device* (e.g. even an sRGB color like `red` could be OOG for a 2013 MacBook Air, whose gamut is approximately 60% of sRGB).

When talking about where gamut mapping should be applied, we need to be clear about which OOG we're talking about.

**Comment by svgeesus** [comment]
> [Section 13.2 of CSS Color 4](https://www.w3.org/TR/css-color-4/#css-gamut-mapping) contains a non-normative section describing a binary search gamut-mapping algorithm. 

[Section 13.1. An Introduction to Gamut Mapping](https://w3c.github.io/csswg-drafts/css-color-4/#gamut-mapping-intro) is a _non-normative backgrounder_ to explain to implementers the design decisions for section 13. In particular it explains the quality differences between a change in chroma (not very visible unless large), a change in lightness (more visible, but acceptable if small) and a change in hue (very visible unless very small).

[Section 13.2. CSS Gamut Mapping to an RGB Destination](https://w3c.github.io/csswg-drafts/css-color-4/#css-gamut-mapping) is _normative_, and defines (to a given tolerance, which is much smaller than any visible difference) a specific location on the gamut boundary which intersects with a constant-hue, constant lightness ray from the origin color to the achromatic axis in Oklch.

There are two methods to _find_ this point; one is iterative and one is analytical. To the tolerance specified, they give the same result. Describing the implementer choice between these two as "non-normative section" is quite incorrect. They give the same result.

Naive clipping finds an entirely different point, with very different properties: for any origin color which is visibly different to the gamut boundary point specified in 13.2, it gives a result with large difference in hue and in lightness.

> Some UA developers met recently to discuss the issue.  

Private and unminuted meetings are a suboptimal way to reach working group consensus. They are much more likely to come to inaccurate or erroneous conclusions, based on incorrect assumptions or misunderstandings. Such as:

> A consensus was reached that it would be _better to allow out-of-gamut color conversions to remain out-of-gamut_ (as opposed to clipping) 

That isn't a change. The specification [already requires](https://w3c.github.io/csswg-drafts/css-color-4/#color-conversion) that intermediate results are retained, not gamut mapped:

>> Colors may be converted from one color space to another and, provided that there is no gamut mapping and that each color space can represent out of gamut colors, (for RGB spaces, this means that the transfer function is defined over the extended range) then (subject to numerical precision and round-off error) the two colors will look the same and represent the same color sensation.

and again in [12.1. Color Space for Interpolation](https://w3c.github.io/csswg-drafts/css-color-4/#interpolation-space) If the colors to be interpolated are outside the gamut of the [interpolation color space](https://w3c.github.io/csswg-drafts/css-color-4/#interpolation-color-space) , then once converted to that space, **they will contain out of range values.

These are not clipped, but the values are interpolated as-is.**

There are two places where some sort of gamut mapping is _required_ however:

[7. ](https://w3c.github.io/csswg-drafts/css-color-4/#convert-display) If dest is a physical output color space, such as a display, then col2 must be [css gamut mapped](https://w3c.github.io/csswg-drafts/css-color-4/#css-gamut-mapped) so that it [can be displayed](https://w3c.github.io/csswg-drafts/css-color-4/#can-be-displayed).

As @LeaVerou already pointed out, no specification can require that a display emit colors that it **can't display**. That should be obvious.

[8.](https://w3c.github.io/csswg-drafts/css-color-4/#convert-hslhwb) If dest cannot represent [out of gamut](https://w3c.github.io/csswg-drafts/css-color-4/#out-of-gamut) colors, for example [hsl](https://w3c.github.io/csswg-drafts/css-color-4/#valdef-hsl-hsl) or [hwb](https://w3c.github.io/csswg-drafts/css-color-4/#valdef-hwb-hwb), then col2 must be [css gamut mapped](https://w3c.github.io/csswg-drafts/css-color-4/#css-gamut-mapped).

That is it. All other color space conversions can, and must, accomodate results which are out of gamut for the color space used.

So, bravo on forming a consensus that agrees with what the spec already says.

To address one additional inaccurate assumption, which @LeaVerou already mentioned:

> Since `color-mix()` from CSS Color 5 is the only feature for color 4 or 5 that can result in intermediate out-of-gamut results

Wrong. Out of gamut results are trivially possible from:

- direct specification (`color(display-p3 -0.1 1.1 0)` is out of gamut for display-p3, but is a perfectly valid color
- relative color syntax (`color(from color(display-p3 0.7 0.7 0.7) calc(r*2) g b)`  is out of gamut for display-p3, but is a perfectly valid color
- `color-mix()`, particularly in polar color spaces
- gradient interpolation, particularly in polar color spaces
- animation or transition, particularly in polar color spaces

**Comment by mysteryDate** [comment]
> I think part of the confusion lies on the fact that there are two types of out-of-gamut:
> 
> a) Out of gamut of the specified color format (e.g. rgb(from red, calc(r * 1.05) g b) is OOG for sRGB, even though it's not OOG for a P3 display)
> 
> b) Out of gamut of the display device (e.g. even an sRGB color like red could be OOG for a 2013 MacBook Air, whose gamut is approximately 60% of sRGB).

Thanks so much Lea. This clears things up quite a bit. The crux of the confusion are [these tests](https://github.com/web-platform-tests/wpt/blob/2bb60461aad0075ca8e1ae08aa836f06b4870d49/css/css-color/parsing/gamut-mapping.html), which, if I understand correctly are an instance of a) and not b)? 

> I think (@svgeesus please confirm) that we (editors of CSS Color) are happy to have intermediate calculations not be gamut mapped, since most of them should happen within infinite gamut spaces anyway. What matters is gamut mapping for display.

If both these things are true, then the tests are invalid, no? The gamut mapping will happen later in the pipeline, or even not at all if the display device is capable of colors outside the sRGB gamut?

> [8.](https://w3c.github.io/csswg-drafts/css-color-4/#convert-hslhwb) If dest cannot represent [out of gamut](https://w3c.github.io/csswg-drafts/css-color-4/#out-of-gamut) colors, for example [hsl](https://w3c.github.io/csswg-drafts/css-color-4/#valdef-hsl-hsl) or [hwb](https://w3c.github.io/csswg-drafts/css-color-4/#valdef-hwb-hwb), then col2 must be [css gamut mapped](https://w3c.github.io/csswg-drafts/css-color-4/#css-gamut-mapped).
>
> That is it. All other color space conversions can, and must, accomodate results which are out of gamut for the color space used.

So, we _should_ be doing something similar to [the aforementioned tests](https://github.com/web-platform-tests/wpt/blob/2bb60461aad0075ca8e1ae08aa836f06b4870d49/css/css-color/parsing/gamut-mapping.html), but with `hsl` and `hwb` as output color spaces since they are simply incapable of representing out-of-gamut color (as opposed to not being able to display out-of-gamut colors)? Are `hwb` and `hsl` the only colors spaces for which that is the case?

The concern raised in this issue was primarily about interoperability, since Safari and Chrome are beginning to ship `color-mix()`. If we can resolve the issue about the appropriateness of the above tests, we can defer larger discussions about gamut mapping to pre-existing threads (i.e. https://github.com/w3c/csswg-drafts/issues/7653 and https://github.com/w3c/csswg-drafts/issues/7610).

**Comment by svgeesus** [comment]
> The crux of the confusion are [these tests](https://github.com/web-platform-tests/wpt/blob/2bb60461aad0075ca8e1ae08aa836f06b4870d49/css/css-color/parsing/gamut-mapping.html), which, if I understand correctly are an instance of a) and not b)?

They are c) Not expressible in a given color format. HSL and HWB require in-gamut sRGB values as input, and give nonsense values if they get negative number or numbers grester than 100%. So, as the spec says, they need gamut mapped before the sRGB to HSL/HWB conversion step.

So  (unlike gamut mapping to the used value on the display) this case is observable through script, and the tests are indeed valid. Used values are not exposed through script, the only way to see if the right color is being displayed is to physically measure it or compare it visually to a reference color patch.

**Comment by mysteryDate** [comment]
>  HWB require in-gamut sRGB values as input, and give nonsense values if they get negative number or numbers grester than 100%. 

Do they, though? An experiment:

The `srgb` equivalent of display-p3 red (`color(display-p3 1 0 0)`) is `color(srgb 1.09306 -0.226721 -0.150111)`. This is clearly out-of-gamut, but not nonsensical. Both UAs I've tested (safari TPM and chrome canary) [treat it as valid input](https://jsfiddle.net/o8dnrgqf/) and [wpt validates similar test cases as valid](https://github.com/web-platform-tests/wpt/blob/2c23021044/css/css-color/parsing/color-valid-color-function.html#L36).

Using the algorithm defined [in 7.2](https://csswg.sesse.net/css-color-4/#rgb-to-hsl) and the srgb equivalent of display-p3 red as input [1.09306 -0.226721 -0.150111] we get the hsl equivalent of [356.51714943615644, 152.34001932269007, 43.31695]. [See a demo here](https://jsfiddle.net/0Lao6ed8/). This value round trips fine using the algorithm in 7.1, with some float-precision issues.

Is a hue of 356 degrees, a saturation of 152% and a lightness of 43% nonsensical if negative values and values greater than one for srgb are not?

[Here's a demo for arbitrary values for display-p3 input, including HWB](https://jsfiddle.net/zn6uhgj7/1/).  All resulting values for hsl make sense if we allow saturation > 100%. The highest value I was able to see was about 300%. All values roundtrip to srgb with only rounding errors on the order of 10^-16. I see similar results with HWB, with some negative values for whiteness and blackness when out-of-gamut

> Since color-mix() from CSS Color 5 is the only feature for color 4 or 5 that can result in intermediate out-of-gamut results

What I should have said here is "out-of-gamut results that are observable through script and are expected to be gamut mapped as opposed to left-as-is." Per the discussion here it would appear that we can further narrow this case to be color-mix values in the `hsl` and `hwb` colorspaces. If we allow representation of out-of-gamut `hsl` and `hwb` colors, like we already do for other colorspaces, then we can remove the need to gamut map colors in a script-visible way, which was the original intention of this issue.

**Comment by mysteryDate** [comment]
I did not intend to close the issue, apologies.

**Comment by svgeesus** [comment]
> This value round trips fine using the algorithm in 7.1, with some float-precision issues.

> [Here's a demo for arbitrary values for display-p3 input, including HWB](https://jsfiddle.net/zn6uhgj7/1/). All resulting values for hsl make sense if we allow saturation > 100%.

Interesting. I don't recall why I thought the values became nonsensical; I would need to look again.

If HSL and HWB were made unbounded, we would need to drop statements [like this](https://drafts.csswg.org/css-color-4/#the-hsl-notation):

>  If the saturation or lightness are less than 0% or greater than 100%, they are clamped to those values at parsed-value time, before being converted to an sRGB color.

**Comment by facelessuser** [comment]
IIRC, HSL behaves in a fairly sane way when out of gamut within the SDR range, it mainly pushes saturation higher. I think when lightness exceeds the HDR range, either positive or negative, saturation goes into the negative which is a little weird, but it round trips fine. I don't think this is true for all HSL variants out there (OkHSL or HSLuv), but the traditional HSL does round-trip fine.

**Comment by mysteryDate** [comment]
> f HSL and HWB were made unbounded, we would need to drop statements [like this](https://drafts.csswg.org/css-color- 4/#the-hsl-notation):

>If the saturation or lightness are less than 0% or greater than 100%, they are clamped to those values at parsed-value time, >before being converted to an sRGB color.

I'm in favor! Would you like me to draft a PR to this repo of unbounded HSL and HWB?

If HSL and HWB are the only exceptions to the "keep out-of-gamut colors until use-time" paradigm, it would make implementations simpler and less surprising to make them behave like other colorspaces.

**Comment by svgeesus** [comment]
> I don't recall why I thought the values became nonsensical; I would need to look again.

> when lightness exceeds the HDR range, either positive or negative, saturation goes into the negative 

Ah, right. And interpolating in HSL where one component has negative Saturation will give unexpected results.

However, I agree that it makes things more consistent if all color spaces can round trip values, and all CSS colors have a unique colorimetric value (which is also why we got rid of preserving hues outside [0..360]).

> Would you like me to draft a PR to this repo of unbounded HSL and HWB?

Sure. I would also like to hear from @emilio and @weinig about this proposed change.

**Comment by facelessuser** [comment]
> Ah, right. And interpolating in HSL where one component has negative Saturation will give unexpected results.

I assume, if the change to not clamp HSL saturation and/or lightness went into place, it would still be required to gamut map HSL before interpolating in that space to avoid such issues?

**Comment by svgeesus** [comment]
> I assume, if the change to not clamp HSL saturation and/or lightness went into place, it would still be required to gamut map HSL before interpolating in that space to avoid such issues?

That still needs to be discussed.

**Comment by tabatkins** [comment]
The big benefit of letting HSL/etc go out of gamut is to avoid having to specify the precise gamut mapping right now; if we still have to gamut map before interpolating that defeats the point.

I think if you interpolate colors in HSL where the endpoints are out of gamut, you get what you get honestly.

**Comment by facelessuser** [comment]
> I think if you interpolate colors in HSL where the endpoints are out of gamut, you get what you get honestly.

That's a fair statement. Currently, saturation only goes negative when lightness goes negative or when in the HDR range. The only way it could accidentally go out is if you are converting from one of the newer color spaces like Oklab, OkLCh and maybe Lab and LCh which is not always very precise at the edges.

```js
> let color = new Color("oklch", [1, 0,0]).to('hsl').coords.toString();
"223.8135974487593,-172.5242095991637,100.00000421453782"
```

If needed, this could be managed by just clamping lightness to the SDR range during the HSL conversion if it exceeds those limits. None of the current color spaces are meant for HDR use at this time anyways.

**Comment by mysteryDate** [comment]
> I think if you interpolate colors in HSL where the endpoints are out of gamut, you get what you get honestly.

For those curious about "what you get": https://mysterydate.github.io/web-demos/hsl-out-of-gamut-interpolation.html

Since Chromium is currently not gamut mapping the inputs (just allowing out-of-gamut values) and Safari TP _is_ gamut mapping, it provides a good side-by-side comparison.

Even in with `xyz` inputs, which are potentially _way_ out of gamut, it's rare that saturation goes negative. When that happens (for example `color(xyz 0 1 1)`), you do certainly get some artifacts. Interestingly, pulling the endpoints into gamut produces artifacts as well. For example, here are three gradients from full red to full green in hsl. For the top bar the endpoints are srgb (so, in gamut), the middle is with display-p3 endpoints (slightly out of gamut) and the bottom is with xyz endpoints (WAY out of gamut). This is a screenshot from the demo above. Apologies that the text here is hard to read:

<img width="1688" alt="Screenshot 2023-03-08 at 5 14 22 PM" src="https://user-images.githubusercontent.com/2529989/223889732-07eb9140-291d-412c-b6a7-547efc518b2d.png">

This result is more or less aligned with expectations. Each gradient is more saturated that the previous one. Even though display-p3 is outside of the hsl gamut, the resulting gradient looks fine because my display supports p3 (look at how much more vibrant the green is, for example). For the gradient with xyz endpoints the colors so saturated that the result is out of gamut for my display and as a result we see more saturation throughout the gradient.

This is as opposed to gamut mapping the endpoints _before_ generating the gradients:

<img width="1685" alt="Screenshot 2023-03-08 at 5 14 31 PM" src="https://user-images.githubusercontent.com/2529989/223889748-7897e18e-5497-4f8b-be30-d000461a0ae7.png">

Since the display-p3 gradient's endpoints are being pulled in to srgb, the result is no-longer brighter than using srgb endpoints. The xyz endpoints are pulled so far away from their original place that the gradient now looks totally different, interpolating from a not-quite-red to a not-quite-green.

> let color = new Color("oklch", [1, 0,0]).to('hsl').coords.toString();
> "223.8135974487593,-172.5242095991637,100.00000421453782"

Is this a library you're using for the `Color` object and the `to` function? The result I get for the conversions defined in the spec for `oklch(1 0 0)` is hue: 186 saturation: 481% lightness: 100%, so it's certainly out of gamut, but the saturation is non-negative.

> If needed, this could be managed by just clamping lightness to the SDR range during the HSL conversion if it exceeds those limits. None of the current color spaces are meant for HDR use at this time anyways.

This would be minimally invasive and really quite rare, though I think it would be better if we just left values as-is. This allows everything to rountrip always and keeps the implementation as simple as possible with the only cost being some artifacts when interpolating certain _far_ out of gamut colors in HSL.

**Comment by svgeesus** [comment]
Worth noting that `oklch 1 0 0)` should be sRGB white and (in [color.js](https://colorjs.io/)) converts to white to 9 significant figures:

rgb = [0.9999999694343976, 1.000000008665371, 1.000000114856359]

but the HSL algorithm seems totally thrown by those fractionally higher than 1.0 numbers.

**Comment by facelessuser** [comment]
> Is this a library you're using for the `Color` object and the `to` function? The result I get for the conversions defined in the spec for `oklch(1 0 0)` is hue: 186 saturation: 481% lightness: 100%, so it's certainly out of gamut, but the saturation is non-negative.

This is using the color library that the CSS color spec writers maintain: https://colorjs.io/. Depending on the precision of the matrices, and the precision of the values that are maintained, that value could be slightly different.

The exact value is probably not as important, but the point is simply that the algorithm was never designed to give you an exact sRGB `[1, 1, 1]` white. And when lightness exceeds the SDR range, that is when you can get negative saturation. If CSS doesn't care right now, that is fine, but I just want to make sure all the info is there to make an informed decision.

**Comment by svgeesus** [comment]
> I think it would be better if we just left values as-is. This allows everything to rountrip always and keeps the implementation as simple as possible with the only cost being some artifacts when interpolating certain far out of gamut colors in HSL.

That seems reasonable to me. If people want perceptually uniform results they should not be interpolating in HSL or HWB anyway.

**Comment by facelessuser** [comment]
> That seems reasonable to me. If people want perceptually uniform results they should not be interpolating in HSL or HWB anyway.

Yeah, this is probably the most important point. If you are using OkLCh, why are you converting back to HSL to do interpolation?  🙂 It may be worth noting that you could get odd results if you do though.

**Comment by mysteryDate** [comment]
Excellent! I will begin writing a PR on this repo that allows unbounded HSL and HWB in that case.

**Comment by svgeesus** [comment]
I would like to hear from WebKit and Gecko developers about allowing out-of-sRGB-gamut HSL and HWB colors, before making the spec edits (but personally feel this is a good direction). @weinig @emilio ?

**Comment by tabatkins** [comment]
The out-of-gamut result is incredible, no notes.

**Comment by facelessuser** [comment]
> so `hsl(none 0% -43.9%)` which is an achromatic (grey) color with negative lightness. That looks nothing like the original color.

Is that actually correct? I get `[55.278310940499026, 228.17518248175182, 34.25]`. That's using the algorithm exactly as stated here: https://www.w3.org/TR/css-color-4/#rgb-to-hsl.

**Comment by svgeesus** [comment]
To get the gamut-mapped result I was using the [algorithm from color.js](https://github.com/LeaVerou/color.js/blob/main/src/spaces/hsl.js#L25-L46) via our [convert app](https://colorjs.io/apps/convert/), which is (apart from terser variable names) the same. For the un-mapped one, I pasted the [sample code from the spec](https://drafts.csswg.org/css-color-4/#rgb-to-hsl) into the console and gave it the sRGB
 array (percents converted from [0%..100%] to [0..1])

**Comment by kdashg** [comment]
Leniency seems better than strictness here. Where the math works out, I prefer GIGO.

**Comment by facelessuser** [comment]
I figured it had to be an input mistake 🙂 .

**Comment by tabatkins** [comment]
Would be good to see if unbounded rgb() was possible, but if not, naive clipping is probably okay? If you're specifically converting to rgb() you get what you deserve, honestly.

**Comment by svgeesus** [comment]
Unbounded legacy `rgb()` does not seem Web-compatible; there were [already tests for CSS Color 3](https://wpt.fyi/results/css/css-color/parsing/color-valid.html?label=experimental&label=master&aligned) that checked (based on a suggestive comment, not actual spec text) that values outside of 0,255 got _clipped_. The [actual spec text in CSS Color 3](https://www.w3.org/TR/css-color-3/#rgb-color) is looser:

> Values outside the device gamut should be clipped or mapped into the gamut when the gamut is known: the red, green, and blue values must be changed to fall within the range supported by the device. User agents may perform higher quality mapping of colors from one gamut to another. This specification does not define precise clipping behavior. 

There were no such tests for CSS Color 4 despite [actual spec text](https://drafts.csswg.org/css-color-4/#serializing-sRGB-values) :

> 	the component values are serialized in base 10, with a range of [0-255], regardless of the bit depth with which they are stored.

so I [made a PR](https://github.com/web-platform-tests/wpt/pull/39451) to extend `parsing/color-valid-rgb` which tests for simple clipping of specified `rgb()` and `rgba()` values that are out of gamut.

Testing that on Chrome and Firefox they both clip. I would need to get a hold of a Mac to test on Safari.

**Comment by svgeesus** [comment]
@tabatkins said

>  If you're specifically converting to rgb() you get what you deserve, honestly.

Converting to HSL, the specified value is auto-converted to legacy `rgb)` or `rgba()`. Which, as widely implemented, clips to [0,255].

**Comment by mysteryDate** [comment]
> Options:
> 1. Use gamut mapping as tested in WPT
> 2. Use clip (the wording "are clamped" comes from at least CSS Color 3; CSS 2.2 is silent but has [an example showing clipping](https://www.w3.org/TR/CSS22/syndata.html#color-units))
> 3. See if unbounded rgb() would be acceptable (we already went from integer to number on rgb())
> 4. Disallow RCS with rgb() and have people use color(srgb) instead which has no gamut limitation, being defined on the full range

Options 2) or 4) both seam reasonable, with 4) being ideal. Instead of disabling relative color syntax (or color-mix) for that matter with legacy rgb, we could just return with the `color(srgb` syntax, which I think fits the general design pattern of "CSS Color 4/5 functions use non-legacy color types, when possible." Like how `oklab` is the default gradient interpolation space.

Given that display-p3 green in sRGB is `color(srgb -0.511814 1.01832 -0.310726)`, we'd have the following computed styles:
`rgb(from color(display-p3 0 1 0) r g b / alpha)` --> `color(srgb -0.511814 1.01832 -0.310726)`
`color-mix(in hsl, color(display-p3 0 1 0) 100%, black)` --> `color(srgb -0.511814 1.01832 -0.310726)`

If both `color-mix` and `from color` always returned non-legacy colors (`color(srgb` for `rgb`, `hsl`, `hwb`) that would very cleanly solve our issues in a straightforward and unsurprising way. You are correct that unbounded legacy rgb is a break with history and would surely cause some backwards compatibility issues.

> @tabatkins @weinig @GPHemsley could you review https://github.com/web-platform-tests/wpt/pull/39451 please?

LGTM!

**Comment by svgeesus** [comment]
I agree that returning `color(srgb ...)` for RCS and `color-mix` if the color space is `rgb`, `hsl` or `hwb` is a clean and round-trip-preserving solution.

It is however a breaking change from currently shipping implementations in WebKit, Chromium and Gecko and would require changes to existing WPT tests including tests which were tagged `Interop2022` so I am requesting further discussion from implementer, and Agenda+ to get a resolution.

@astearns @atanassov _I will miss the 26 Apr CSS call due to being at the International Color Consortium meeting in London, so despite the Agenda+ please don't put it then :)_

**Comment by mysteryDate** [comment]
> It is however a breaking change from currently shipping implementations in WebKit, Chromium and Gecko and would require changes to existing WPT tests including tests which were tagged Interop2022 so I am requesting further discussion from implementers, and Agenda+ to get a resolution.

Relative color is not yet shipped anywhere and no RCS tests were part of Interop2022.

`color-mix` is shipped in Safari and Chrome, but the [gamut-mapping](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/gamut-mapping.html) tests were also not part of [Interop2022](https://wpt.fyi/results/css/css-color/parsing?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-color).

There were some tests that were a part of Interop2022 that would need to change. All `color-mix` tests here that used `hsl` or `hwb` as a colorspace, but AFAICT that is all:

https://wpt.fyi/results/css/css-color/parsing/color-computed-color-mix-function.html?label=master&label=stable&aligned&q=label%3Ainterop2022

**Comment by svgeesus** [comment]
> All color-mix tests here that used `hsl` or `hwb` as a colorspace

Yup, those are the Interop2022 ones I was thinking of.

**Comment by svgeesus** [comment]
> Relative color is not yet shipped anywhere 

From the [Safari 16.4 release notes](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes):

>> Added support for CSS relative color syntax.

[WPT RCS tests on stable](https://wpt.fyi/results/css/css-color/parsing/color-computed-relative-color.html?label=master&label=stable&aligned)

**Comment by mysteryDate** [comment]
> Added support for CSS relative color syntax.

Hahaha, it RCS wasn't working on Safari on my laptop 2 hours ago, then clearly and update ran in the background and now it is. Truly on the bleeding edge!

**Comment by svgeesus** [comment]
@weinig @jensimmons @emilio thoughts on this proposal to make `color-mix(0` and RCS using `rgb`, `hsl` and `hwb` return round-trippable, unbounded results in `color(srgb ...)`?

**Comment by mysteryDate** [comment]
Anyone else we could ping @svgeesus? It would be great to get this finally resolved.

**Comment by svgeesus** [comment]
Yes, would love to get this issue agreed on and closed out.

If someone (such as yourself?) could review (and clear the false-positive error) on this WPT PR:

 - https://github.com/web-platform-tests/wpt/pull/39451

that would be helpful. It demonstrates that we can't rely on retaining OOG `rgb()` values.

Once the Agenda+ gets discussed and we have WG consensus then I can do a follow-on WPT PR to test the new behavior and update tests that check the currently-specified behavior.

Unfortunately there is quite an agenda backlog currently. But this issue is 6th on the proposed agenda for this Wednesday so hopefully ...

**Comment by mysteryDate** [comment]
> Yes, would love to get this issue agreed on and closed out.
> 
> If someone (such as yourself?) could review (and clear the false-positive error) on this WPT PR:
> 
> * [test out of [0,255] rgb web-platform-tests/wpt#39451](https://github.com/web-platform-tests/wpt/pull/39451)
> 
> that would be helpful. It demonstrates that we can't rely on retaining OOG `rgb()` values.

@svgeesus  Done! All looks good to me, I lack the power to truly +1 it though, I think. I bugged a reviewer at chromium to do so. The false positive error looks to be cleared up (https://github.com/web-platform-tests/wpt/pull/39451), can you re-run the linter? I don't seem to have the power to do that either.

**Comment by svgeesus** [comment]
Note to self the [Color 5 hsl color-mix() example](https://drafts.csswg.org/css-color-5/#ex-hsl-gamut-map) still uses gamut mapping on conversion to hsl, and needs to be recalculated.

**Comment by svgeesus** [comment]
Closing this (and other issues where no change to the spec is expected).

**Comment by danburzo** [comment]
If I’m not mistaken, the [resolution to serialize the result of RCS using rgb, hsl, etc.](https://github.com/w3c/csswg-drafts/issues/8444#issuecomment-1542537362) as `color(srgb …)` still requires additions to [[css-color-5] § 10.2. Serializing Relative Color Functions](https://drafts.csswg.org/css-color-5/#serial-relative-color) similar to `color-mix()`?
