### ISSUE TITLE
[css-view-transitions-1] Include aria-busy="true" by default

### ISSUE THREAD

**Issue by nattarnoff** [w3c/csswg-drafts#8447]
[css-view-transitions-1]
We've had aria-busy for a little why now to indicate when dynamically loaded content is being fetched and rendered to the client. This is something the author needs to set though. With CSS View Transitions there will be a significant  amount of content updating, moving, and changing. Users who are blind or have low vision and are reliant on screen readers will need to know that the content is in a change state. I'm proposing that instead of leaving it up to the author to include aria-busy="true" when they are developing the transitions the specification should include this during the transition. This will improve accessibility and reduce the weight to implement the CSS feature by reassuring basic accessibility is covered.

**Comment by jakearchibald** [comment]
Wouldn't this be more appropriate for the navigation API? Transitions should come _after_ content fetching, so it seems like a busy period should start before view transitions are involved, and from (for example) a screen reader's point of view, the content may be fully available from the start of the transition.

**Comment by khushalsagar** [comment]
+1 to Jake's feedback, the idea with ViewTransitions is for authors to call the API after fetching content from the network. Since as soon as you call `document.startViewTransition`, the browser freezes rendering to let you asynchronously update the DOM.

While its possible that you can start the transition while some parts of your page are still loading, the transition API is agnostic to that and can't tell whether the DOM is fully loaded. So it doesn't make sense for aria-busy to be set automatically.

**Comment by noamr** [comment]
Is this actionable?

**Comment by khushalsagar** [comment]
Let's give [nattarnoff](https://github.com/nattarnoff) another week to reply before closing.

**Comment by nattarnoff** [comment]
Closing. I haven't had time to play and understand the concept deeper than what is laid out here. If it is an issue in the future, I'll open another issue.
