### ISSUE TITLE
[css-text-4] is text-autospace: auto missing?

### ISSUE THREAD

**Issue by vitorroriz** [w3c/csswg-drafts#8512]
At https://drafts.csswg.org/css-text-4/#text-spacing-property
we have the description for the shorthand `text-spacing: auto`:

> Sets both text-spacing-trim and text-autospace to auto.

I've got confused because text-spacing-trim has a description for 'auto' but text-autospace doesn't.

**Comment by cdoublev** [comment]
Also, `text-autospace: none` seems simpler than `text-autospace: no-autospace` (`none` is much more common).

Forgive me for this aside but this issue seems to be the first related to `text-autospace` since its introduction, so I thought it may be only another minor oversight.

**Comment by fantasai** [comment]
@vitorroriz Thanks for reporting that, I believe it was an oversight from when we split text-spacing out into longhands. Should be fixed in the ED now. :)

**Comment by fantasai** [comment]
@cdoublev I think that question is a bit more complicated, because it affects shorthanding. We want `text-spacing: none` to turn off both `text-autospace` and `text-spacing-trim`, but there should also be a keyword in the shorthand to turn off `text-autospace` without touching `text-spacing-trim`. So maybe it's worth filing a separate issue?

**Comment by cdoublev** [comment]
> there should also be a keyword in the shorthand to turn off `text-autospace` without touching `text-spacing-trim`

Oh I had not seen that. I am fine with `text-autospace: no-autospace`, even if the redundancy surprised me instantly. I guess it is not worse than forcing the author to declare `none space-all`.
