### ISSUE TITLE
[css-animations-2][scroll-animations-1] Is `view()` meant to allow multiple `view-timeline-inset` values?

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#8519]
The syntax of the `view()` function allows [`<'view-timeline-inset'>`](https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-inset) values. And the syntax for `view-timeline-inset` is defined as a comma-separated list of values.

So, as it stands, the syntax currently allows values like `view(block 100px 200px, 10% 20%)`.

I assume `view()` was intended to only take _one_ set of view timeline insets. Correct?

If so, this could be solved by introducing a new `<single-view-timeline-inset>` data type that refers to `[ auto | <length-percentage> ]{1,2}`. And that data type could then be used for `view-timeline-inset` as `<single-view-timeline-inset>#` and for `<view()>` as `view( [ <axis> || <single-view-timeline-inset> ]? )`.

Sebastian

**Comment by ydaniv** [comment]
> I assume view() was intended to only take one set of view timeline insets. Correct?

Yep, good catch!
`view()` is used inline as a single `animation-timeline` value and references a single timeline.

**Comment by fantasai** [comment]
Actually, I forgot, we already fixed this in Values and Units: https://www.w3.org/TR/css-values-4/#component-types

When referencing a property grammar using `<'property'>` notation, we drop any top-level #-multiplier, exactly because we run into this case *all the time* and it makes the grammars harder to read when we need to keep introducing these intermediate productions.

**Comment by SebastianZ** [comment]
Ah, great! Thanks for the note!

Sebastian
