### ISSUE TITLE
[css-view-transitions-1] Define the constraints which must be satisfied by a named element during the transition

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8548]
#8139 resolved on the exact constraints we need on a named element in View Transitions and the fact that they are implicitly applied by view-transition-name. #7882 resolved that if constraints on the element are unsatisfied during the animation, we should abort the transition.

As the spec changes for these were being landed in #8540 we realized we need a more precise resolution on how the constraints are checked. Here's the list:

1. Any [=flat tree=] ancestor of |capturedElement|'s [=new element=] [=skips its contents=].
2. |capturedElement|'s [=new element=] is [=element-not-rendered|not rendered=].
3. |capturedElement|'s [=new element=] does not form a [=stacking context=].
4. |capturedElement|'s [=new element=] does not form a [[css-transforms-2#grouping-property-values|group]].
5. |capturedElement|'s [=new element=] does not form a [=backdrop root=].

2 was explicitly spelled out [here](https://github.com/w3c/csswg-drafts/issues/7882#issuecomment-1377660423): "The element must have an associated box."

1 states that the element's contents should not be skipped, for example via `content-visibility: hidden`. We ignore named elements which skip their contents when capturing the new state [here](https://drafts.csswg.org/css-view-transitions-1/#capture-new-state-algorithm), see 3.1. So this check makes sure the developer doesn't modify their CSS to make the element skip its contents once the transition starts. `content-visibility: auto` could have caused the element to skip its contents without a change from the developer, but the resolution [here](https://github.com/w3c/csswg-drafts/issues/8060#issuecomment-1411189366) ensures that once a named element is participating in a transition it is forced to stay relevant to the user.

3, 4 and 5 are constraints we resolved on in #8139 but the question is do we check for these constraints explicitly or enforce that the computed value of `view-transition-name` for an element participating in a transition is not none or doesn't change at all. The second option achieves the same effect since having the property will continue to apply any requisite constraints.

**My opinion**
If the developer had CSS, outside of view-transition-name, that was applying these constraints. Suddenly a seemingly unrelated change will break their transition. I can imagine a developer going: "setting opacity seems to make this work, Idk why". So enforcing that you don't remove view-transition-name until the animations are done makes the CSS that the feature relies on less brittle.

@jakearchibald @vmpstr @tabatkins FYI.

**Comment by vmpstr** [comment]
I mentioned it on the related PR, but I'll mention it here for posterity: I don't believe that requiring the constraints 3, 4, and 5 is equivalent to requiring `view-transition-name` non-`none` value since the latter also requires the `view-transition-name` to have a non-`none` value for the duration of the animation. That was not a constraint we've resolved to have.

Having this extra constraint seems to put a limit on what a developer can do while the animation is happening. They, for example, can't remove `view-transition-name`s to set up the next part of the view transition. (That's the only example I can think of, btw)

My opinion is that a `view-transition-name` non-`none` value is a convenient way to ensure that all constraints are satisfied, but it should itself not be a requirement. If a developer chooses to satisfy the constraints 3, 4, and 5 in ways other than `view-transition-name` non-`none` value, that should be fine. If the developer needs another convenience CSS (aside from `view-transition-name`) to make sure the requirements are satisfied, then they can probably use one of the `will-change` values or maybe we can add another `will-change` value if none of the existing ones are sufficient

**Comment by jakearchibald** [comment]
Summary for CSSWG meeting:

[Previous resolution](https://github.com/w3c/csswg-drafts/issues/8139): A `view-transition-name` value that isn't `none` gives an element stacking context, grouping element, backdrop root, similar to non-1 `opacity`, as view transitions need these constraints.

The value of `view-transition-name` is only consulted during the setup of the view transition, to decide which elements should be involved in the transition. However, because the `::view-transition-new` view is 'live', the constraints need to be checked per frame.

[Previous resolution](https://github.com/w3c/csswg-drafts/issues/7882): If constraints are broken mid-transition, the rest of the transition is skipped.

There are additional constraints per-frame that aren't covered by `view-transition-name`, such as the element being rendered. These aren't constraints during the setup of the transition, as these constraints simply result in the element being ignored.

The question is, how should we check these conditions are met per frame?

**Option 1**: Assert the additional conditions, such as "rendered", then assert the remaining conditions by checking the `view-transition-name` is not none.

This means removing the `view-transition-name` from a transitioning element mid-transition would skip the transition. However, setting the `view-transition-name` to another value has no effect - it wouldn't change the transition group of the element. We're only concerned with the side-effects of `view-transition-name`.

**Option 2**: Assert all of the conditions individually, regardless of `view-transition-name`.

This means removing the `view-transition-name` from a transitioning element mid-transition would skip the transition, unless the constraints are satisfied by other means, such as a non-0 `opacity`.

We're split on this, so help us decide 😄

**Comment by khushalsagar** [comment]
Fixed by https://github.com/w3c/csswg-drafts/pull/8540
