### ISSUE TITLE
[css-text] Question re white space processing rules for U+000D

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#855]
AFAICT from https://drafts.csswg.org/css-text-3/#white-space-processing, a lone CR (U+000D) character should be treated just like a lone LF (U+000A) or a CRLF pair: it is a segment break, which will be transformed to a preserved line feed, removed, or transformed to a space (U+0020), depending on the value of `white-space` and possibly the context of the segment break.

However, none of the browsers I have tested so far (Firefox, Chrome, Safari, Edge) appear to behave this way; rather, they all discard the lone CR.

Testcase: https://people-mozilla.org/~jkew/tests/cr.html

Am I misunderstanding something here, should the spec be changed to better match actual behavior, or do we expect all the browsers to change to match the spec?

**Comment by upsuper** [comment]
(cc myself)

**Comment by fantasai** [comment]
Probably we should make the spec match the implementations here.

**Comment by fantasai** [comment]
So, as I was working on this I realized that making a character invisible is underdefined: what effect does it have on surrounding characters? Does it break joining? Afaict, Chrome drops form feeds and carriage returns from rendering entirely, whereas Gecko treats them similar to zwsp.

http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%D8%B4%D8%AA%0AVA%3Cbr%3E%0A%D8%B4%26%23x000c%3B%D8%AA%0AV%26%23x000c%3BA%3Cbr%3E%0A%D8%B4%26%23x000d%3B%D8%AA%0AV%26%23x000d%3BA%3Cbr%3E%0A%D8%B4%26%23x200b%3B%D8%AA%0AV%26%23x200b%3BA%0A%0A

What do we want to do here?

**Comment by frivoal** [comment]
I was talking with @FremyCompany after this discussion, and we were thinking that this resolution is inconsistent with https://github.com/w3c/csswg-drafts/issues/1990 since we've decided that control characters should be visible, then applying the same treatment for this one as well could make sense.

**Comment by frivoal** [comment]
Agenda+ to follow up on the [previous comment](https://github.com/w3c/csswg-drafts/issues/855#issuecomment-381264904), and see if we want to resolve the inconsistency between the resolution in this issue and the one in #1990

**Comment by fantasai** [comment]
Reopening because the WG discussed handling of lone CRs in https://github.com/w3c/csswg-drafts/issues/855, but not form feeds (or at least, they weren't minuted as having been discussed). The question is, should they continue to be handled as zwsp as resolved in response to  https://github.com/w3c/csswg-drafts/issues/855 or should they also be affected by the resolution saying CRs are rendered just like any other control character?
