### ISSUE TITLE
[scroll-animations-1] Clarify that progress percentages must be between 0% and 100%

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#8552]
While checking https://github.com/w3c/csswg-drafts/issues/5203#issuecomment-1461962937, I noticed the scroll-animations-1 spec doesn’t mention that the percentages for the timeline ranges must be between 0% and 100%. 

Furthermore the [original `<keyframe-selector>` definition from css-animations-1](https://drafts.csswg.org/css-animations-1/#typedef-keyframe-selector) seems to have inadvertently been relaxed as the allowed range for `<percentage>` is no longer mentioned.

- css-animations-1:

    ```
    <keyframe-selector> = from | to | <percentage [0,100]>
    ```
- scroll-animations-1:

    ```
    <keyframe-selector> = from | to | <percentage> | <timeline-range-name> <percentage>
    ```

I think we should explicitly mention the allowed range.

**Comment by flackr** [comment]
Do we have to restrict it? Isn't something like `contain -20%` valid? It can be calculated out to a particular scroll position and we already have to handle keyframes outside of the animation range.

**Comment by bramus** [comment]
If there's no need to limit the accepted range, then please. Just to be sure: this would also play nice with negative offsets?

**Comment by flackr** [comment]
Yes, negative offsets calculate to their overall relative percentage. The only weird case we have right now is that view timelines do not start before the cover period so if you try to go less than 0% or more than 100% of the cover range it will interpolate from that position but not be active until you're in the cover range. I think this is probably fine, though I have often wondered whether we should make view timelines active for the entire scroll range so that cases like this would be supported.

**Comment by cdoublev** [comment]
I am not sure if you are only discussing the `<percentage>` associated to `<timeline-range-name>` but if not, would this be backward-compatibile?

  > Values less than `0%` or higher than `100%` are invalid and cause their `<keyframe-block>` to be ignored.

https://drafts.csswg.org/css-animations-1/#keyframes

**Comment by fantasai** [comment]
Merged in @bramus's PR to clarify that raw percentage @keyframes are invalid. Keeping the issue open in case @flackr wants to follow up on any of his comments above.

**Comment by flackr** [comment]
This all looks good to me.
