### ISSUE TITLE
[color-5] Serialization of percentages in color-mix()

### ISSUE THREAD

**Issue by tiaanl** [w3c/csswg-drafts#8564]
In reference to this section:
https://github.com/w3c/csswg-drafts/blob/43b12e47663cff4cead0d187086dcf9ea8f33626/css-color-5/Overview.bs#L2585

The spec doesn't mention anything about serializing the incoming color-mix(), only the result.  For color-mix() itself the tests suggest that the percentages on both sides should only be omitted if the author omitted them, otherwise they should be present.

@emilio mentioned that there is also the [serializing-css-values](https://drafts.csswg.org/cssom/#serializing-css-values) section that suggests the percentages could be omitted if they are obvious.

So for example `color-mix(in hsl, red 60%, blue 40%)` should serialize to `color-mix(in hsl, red 60%, blue)`.  This contradicts what is currently in the tests.

As all other browsers (except firefox) is following the current wpt tests, I think we should maybe explicitly mention this in the spec?

**Comment by emilio** [comment]
I think we should fix the test instead FWIW. cc @svgeesus

**Comment by svgeesus** [comment]
The spec should clearly state what happens, even if it is just the logical application of a principle, and should have an example. I'm sure that lack of this clarity explains the divergent implementations on that point.

I agree that the tests do not follow that, and should be corrected.

**Comment by svgeesus** [comment]
So I just added this

```html
The serialization of the specified value of a ''color-mix()'' function
is the string "color-mix(in ",
followed by the specified <<color-space>> in all-lowercase,
followed by ", ",
followed by the first specified color,
followed by a space,
followed by the normalized first percentage,
followed by ", ",
followed by the second specified color,
followed by ")".

Following the principle of shortest serialization,
and given that the normalized percentages are serialized,
the normalized second percentage is omitted.
```

but see a problem: if the normalized percentages add to less than 100%, how do we serialize the alpha multiplier (which cannot be expressed directly in the syntax, only indirectly.

Si I am thinking we need to retain the as-specified (un-normalized) percentages, if they are both given and if they add to less than 100%.

**Comment by svgeesus** [comment]
@tiaanl @emilio any thoughts? The only way I see to retain the alpha modifier is to retain the un-normalized percentages; we can do that just where they add to less than 100%, or do it always.

**Comment by emilio** [comment]
Here's [what we do](https://searchfox.org/mozilla-central/rev/82828dba9e290914eddd294a0871533875b3a0b5/servo/components/style/values/generics/color.rs#64-73) which I think is sensible. TLDR, you omit the right percentage if left + right add up to 100%, you omit both if left and right are 50% each, otherwise you omit none of them.

**Comment by svgeesus** [comment]
Okay, but is that the _specified_ percentage or the _normalized_ percentage (sounds like the specified one)?

So for `color-mix(in oklab, yellow 70%, orange 70%)` do you store as-is or do you normalize to 50% each and thus omit both?

**Comment by mysteryDate** [comment]
> followed by the specified (un-normalized) first percentage (unless that is 50%)

We are missing tests in `color-valid-color-mix-function.html` that validate this behavoir. I've added some here along with the subsequent change in chromium:
https://chromium-review.googlesource.com/c/chromium/src/+/4646411?tab=comments

Currently Firefox passes these new tests, though Safari does not.

**Comment by svgeesus** [comment]
Cool, will these be upstreamed to WPT in due course?

**Comment by mysteryDate** [comment]
Absolutely! Happens automatically.

**Comment by AndresRPerez12** [comment]
We have a failure on a specific test caused by an edge-case of the spec:

`color-mix(in srgb, 70% red, 50% blue)` from
 https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid-color-mix-function.html#L20

From the instructions in the spec, the percentage specified for the second color is not included following the `unless either that is 50%` rule, resulting in `color-mix(in srgb, red 70%, blue)`

A similar situation can occur with the first percentage, like in `color-mix(in srgb, 50% red, 70% blue)`. The `50%` for the first color would not be included following the `unless either that is 50%` rule, resulting then as `color-mix(in srgb, red, blue 70%)`.

A possible wording for the spec that would resolve the issue would be:

```
The serialization of the specified value of a ''color-mix()'' function
is the string "color-mix(in ",
followed by the specified <<color-space>> in all-lowercase,
followed by ", ",
followed by the first specified color,
followed by a space,
followed by the specified (un-normalized) first percentage (unless both percentages are 50%),
followed by ", ",
followed by the second specified color,
followed by the specified (un-normalized) second percentage (unless the two specified percentages add to 100%),
followed by ")".
```

**Comment by tiaanl** [comment]
That does make it more clear. @AndresRPerez12 can you make a pr for the change to the wording?

**Comment by AndresRPerez12** [comment]
I have created the pull request with the proposed wording: https://github.com/w3c/csswg-drafts/pull/9231
