### ISSUE TITLE
[css-inline] should `initial-letter` be plural?

### ISSUE THREAD

**Issue by dauwhe** [w3c/csswg-drafts#862]
It's possible (though rare) for `initial-letter` to apply to more than one letter. Should it be plural? Note this is shipping in WebKit as singular. 

P.S. This is all my fault.

**Comment by frivoal** [comment]
Bah, I think it's fine as it is. ::first-letter can also contain some punctuation in addition to the letter, but nobody complains about its name. The purpose is clear from the current name, so I'd say it's good.

**Comment by fantasai** [comment]
@frivoal It's not about punctuations, which are indeed pretty incidental. It's about the fact that you can apply 'initial-letter' to entire words, and it's not at all obvious that this is possible.

If it wasn't shipping already, I'd push for renaming it. :/

**Comment by anjia** [comment]
Reference: [certain inline-level boxes](https://drafts.csswg.org/css-inline/#first-most-inline-level)
> ... the `initial-letter` property applies not just to the CSS-defined `::first-letter` pseudo-element, but also to inline-level boxes that are placed at the start of the first line. 

When applying to inline-level boxes, `initial-letter` or `initial-letters` may be not a preferable property name. 

Maybe the name `first-child` or something else would be more suitable, because it's not only related to pure CSS, but also to the HTML structure. What do you think?

**Comment by dauwhe** [comment]
> Maybe the name initial-child or something else would be more suitable, because it's not only related to pure CSS, but also to the HTML structure. What do you think?

This property exists to create properly-aligned larger letter(s) at the start of a block. In the typographic tradition they have always been called initial letters or drop caps; we chose the former as it covered more of the use cases. `initial-child` seems to describe what the property applies to, not what the property does. I think that term would be confusing for authors.

**Comment by litherum** [comment]
See also: https://github.com/w3c/csswg-drafts/issues/2809

**Comment by jensimmons** [comment]
I just wrote a line of code in a Tweet and realized this might just be far more confusing.

`p:first-letter { initial-letters: 5; }` 

Trying to keep track of initial-letters being plural and first-letter being singular is hard. Honestly `first-letter` is the property that should be plural (Time Machine time), and initial letter should be renamed to mean embiggen. 

(Also I did drop it on Twitter to see what random words emerge: https://twitter.com/jensimmons/status/1022155415239450625)

**Comment by dauwhe** [comment]
See also #2950

**Comment by fantasai** [comment]
Do we need to revert this change?

**Comment by r12a** [comment]
My 2p: yes, we should revert it.  Initial-letter is a concept; no need to get too pedantic about whether it's one letter or more, since you'd by rights need to concede that punctuation are not letters, too.  But for me it's also significant that it's already implemented and socialised in the singular (which caused me a problem recently for setting up tests), and that there's the mismatch with :first-letter, that @jensimmons points out.

**Comment by jensimmons** [comment]
I would like us to revert this, and go back to a singular form — `letter`. The more I've lived with the plural form, the more problematic and awkward it feels.
