### ISSUE TITLE
[css-counter-styles-3] Should "Ready-made Counter Styles" be supported by UA?

### ISSUE THREAD

**Issue by vitorroriz** [w3c/csswg-drafts#8636]
At https://w3c.github.io/csswg-drafts/css-counter-styles/#additional-predefined spec says:

> The Internationalization Working Group maintains a large list of ready-made [@counter-style](https://w3c.github.io/csswg-drafts/css-counter-styles/#at-ruledef-counter-style) rules for various world languages in their [Ready-made Counter Styles](https://www.w3.org/TR/predefined-counter-styles/) document. [[predefined-counter-styles]](https://w3c.github.io/csswg-drafts/css-counter-styles/#biblio-predefined-counter-styles)
> 
> These additional counter styles are not intended to be supported by user-agents by default, but can be used by users or authors copying them directly into style sheets.
> 

Is there a reason why these are not intended to be supported by user-agent or should some, or all, of them be moved to predefined styles?

**Comment by gsnedders** [comment]
https://github.com/w3c/csswg-drafts/commit/009fab0a191e5cc319c20e3644998a56f315e547 seems to be the commit that removed many of them from the spec

Unfortunately I don't know how to easily find what resolutions that commit refers to (given mostly they're just in weekly minutes emails).

**Comment by gsnedders** [comment]
These from [2012](https://www.w3.org/Search/Mail/Public/advanced_search?keywords=%22counter+styles%22&hdr-1-name=subject&hdr-1-query=minutes&hdr-2-name=from&hdr-2-query=&hdr-3-name=message-id&hdr-3-query=&period_month=&period_year=2012&index-grp=Public__FULL&index-type=t&type-index=www-style&resultsperpage=20&sortby=date) and [2011](https://www.w3.org/Search/Mail/Public/advanced_search?keywords=%22counter+styles%22&hdr-1-name=subject&hdr-1-query=minutes&hdr-2-name=from&hdr-2-query=&hdr-3-name=message-id&hdr-3-query=&period_month=&period_year=2011&index-grp=Public__FULL&index-type=t&type-index=www-style&resultsperpage=20&sortby=date) hopefully cover relevant resolutions.

https://lists.w3.org/Archives/Public/www-style/2011Nov/0814.html seems to contain the original resolution to split Counter Styles out of Lists, so Lists could progress to CR separately (which it still hasn't):

> RESOLVED: split predefined counter styles into a separate spec

https://lists.w3.org/Archives/Public/www-style/2012Aug/0899.html seems to cover dropping many of them from Counter Styles:

> RESOLVED: Move @counter-style rule and symbols() function to the counter styles spec. Retain in that spec the 2.0, 2.1 and the six way cjk ideographic split (which is marked at-risk). Move rest of counter styles to registry on W3C wiki.

It's less clear here in the minutes what the motivation here? It sounds like the WG was just unclear how many of the styles were correct; does the I18N IG have that confidence in their Note?

**Comment by tabatkins** [comment]
Mainly it's that the set was both large and likely to continue growing, and there was no reasonable place to split it and say "**these** are the languages we're officially blessing with a shipped counter style, **these** are the languages we're not". So instead we went with the Schelling fence of "what css2 blessed" + the tiny handful that we know about that are too complex to reasonably handle in `@counter-style`.

It is not intended that the big list in Ready-Made Counter Styles ship in any browser; it's intended that authors include the `@counter-style` rule themselves when they're using such a language. The spec just does the work of actually constructing such a rule for the authors, so they just need to copy/paste.

**Comment by tabatkins** [comment]
What I said above, essentially. And it means a pretty large addition to the UA stylesheet.

I'm not opposed to changing that decision, but it *does* mean a continuing maintenance burden.

**Comment by svgeesus** [comment]
From memory (and this was over a decade ago) another motivation was to encourage browser devs to implement `@counter-style` because they were already complaining about a big list of list styles. So the argument was "implement this, then the list won't grow".

Pleased to see [Safari TP 166 enables `@counter-style`](https://developer.apple.com/safari/technology-preview/release-notes/)

**Comment by litherum** [comment]
I must not be understanding something. The ready made counter styles list is implemented in terms of counter styles. So the list is only useful if the browser has already implemented counter styles. So, the browser's choice isn't "either implement this list or implement counter styles" but instead the browser's choice is "definitely implement counter styles, then after you're done, decide whether or not to use the thing you just implemented to implement a bunch of default counters that authors can just use without making every site define them themselves"

**Comment by tabatkins** [comment]
I seem to recall it being an issue back then, but if it's no longer an issue, then great! Happy to revisit the issue. ^_^

**Comment by svgeesus** [comment]
> I must not be understanding something. 

I probably didn't explain it well. The original lists were documented in spec prose, and the list kept growing, which was seen as an issue at the time. (There was originally pushback against standardizing the X11 color names, for example, because "that is a big list and makes my code bigger").

Inventing `@counter-style` was a way to prevent the list from growing and to enable authors for unsupported styles to add them to their pages.

Trimming down the official list was a stick-and-carrot way to encourage browser implementation.

**Comment by svgeesus** [comment]
@tab you closed this but it seems there is ongoing conversation about including these by default rather than making every page author copy-paste it. OK to re-open?

A disadvantage of the copy-paste route is maintenance: if we find that the `foo` style gets 219 to 234 wrong, updating in a browser is easy and getting every web page to updater is hard.

**Comment by tabatkins** [comment]
Yeah fine to reopen, at the time I closed it the question was, indeed, answered.

**Comment by litherum** [comment]
`@counter-style` makes perfect sense to support scripts that we _don't_ know about. Just like AAT fonts don't require Unicode shaping data, `hyphens:manual` supports content-provided hyphenation locations, `<br>` allows custom line breaking positions, etc.

If browsers know how a particular script's counters work, and implementation is possible (because it uses the `@counter-style` infrastructure), it seems like browsers should support those counters by default, without the page having to implement/maintain it themselves. In general, script-specific internationalization should work _by default_.

**Comment by jensimmons** [comment]
I do think the CSSWG should have a conversation in 2023 about including _all_ of the styles defined in [Ready-Made Counter Styles](https://www.w3.org/TR/predefined-counter-styles/) in browser UA styles. 

Decisions made in the 90s regarding language support on the web do need reconsideration. The status quo provides support for multiple different ways to count using the numbering system that's dominant in western Europe, and zero ways to count using even one numbering system from the continent of Africa. "Because that would be too many, let's keep it to only supporting the ones we picked first" does not do justice for many cultures around the world. 

> it means a pretty large addition to the UA stylesheet.

And is there a practical downside to a large UA stylesheet in 2023? Kbs are cheaper than they used to be. 

> it does mean a continuing maintenance burden.

Do these change much? It seems rarely.

**Comment by tabatkins** [comment]
> Decisions made in the 90s regarding language support on the web do need reconsideration. 

We made this particular decision about a decade ago, fwiw. As @svgeesus said, it was done to placate browser devs at the time. See <https://lists.w3.org/Archives/Public/www-style/2011Nov/0814.html> for the discussion and resolution.

> Do these change much? It seems rarely.

There've been updates to the list maybe once a year or so, if I'm recalling correctly. It's not a lot, but it is ongoing.

**Comment by tabatkins** [comment]
Oh I was very wrong about the update frequency; there've been [100 commits](https://github.com/w3c/predefined-counter-styles/commits/gh-pages) to the repo in the last 8 years, most of which are indeed substantive additions/tweaks to the algos.

Again, this isn't a lot, but it does mean we'll be regularly updating the list for correctness.

**Comment by svgeesus** [comment]
> Oh I was very wrong about the update frequency; there've been [100 commits](https://github.com/w3c/predefined-counter-styles/commits/gh-pages) to the repo in the last 8 years, most of which are indeed substantive additions/tweaks to the algos.

Given the number of browser releases in the last 8 years, that seems a very manageable number of UA stylesheet updates.

So, are we doing this?

**Comment by dbaron** [comment]
> Given the number of browser releases in the last 8 years, that seems a very manageable number of UA stylesheet updates.

I think it's worth noting that if this were part of what browsers ship, then those updates would at least require *assessment* of whether they posed web-compatibility problems.  I don't know how much work those assessments would be, or how often they would lead to the conclusion that the change was not acceptable due to compatibility.  But it might be worth reviewing some set of recent changes to see whether they would have had a risk of compatibility problems.

**Comment by r12a** [comment]
> Do these change much? It seems rarely.

I have a good sized stack of changes that have built up because i haven't had time to deal with them. Hopefully, i'll be making a substantial number of changes next week.  But i expect to make additional changes after that, as i research other orthographies.

**Comment by r12a** [comment]
Hmm. The RMCS doc was always intended to provide quick access to styles that people thought were good enough to acquire 'off the shelf', but the expectation was always that people could and would tweak them and rename them to suit their preferences.  

In particular, you'll see that a while ago we began deconstructing the entries because affixes are very susceptible to change according to the context or author preference.  For example, it is common in indic/seasian styles to not use the period as a separator, but there's no clear default alternative: some people use (...), some may use ...), in Burmese one may also use ...။, and these may change within a single document.  If putting them in a registry and requiring browsers to support all of those, i think we will be offering users an overly rigid (or, if it includes all options, baroque) situation that the move to customised counter styles was meant to remove.

I'm not sure how the registry would decide on a 'standardised' approach for Burmese, for example, or how useful that would be.

It would also make life much more complicated if things need to be corrected – it's not always possible to get the right information about these counter styles on the first go round, and several have been changed so far.

The other thing is that we do sometimes need to change the styles defined, either because new information comes to light, or sometimes because the original style contained an error.  This is not an issue when people are copying the styles into their own stylesheets – where they can change them at will and changes to our document will not affect them. But it may be more problematic if they have been set in concrete by the browser, making it difficult to change them, and by changing them will affect existing content.

We'll also be back in the game of trying to maintain interoperability.  It's all well and good to say that browsers must support all the items in the registry, but browsers typically don't, and if they do then adding new items to the registry will involve a lot of lag before all engines support them, and probably a lot of persuasion, creating tests, tracking results, etc., too.

We don't have any of these problems at all at the moment, and i'm not keen to start introducing them. I'm not sure what the benefit is of introducing the registry, and whether it outweighs the problems and hassle involved in creating it and policing it.

So i have some misgivings...

(Personally, i'd prefer to use our energies in fixing some other areas that i think need it more, such as sideways values of writing-mode, horizontal-in-vertical support, text opacity cleanup for cursive scripts, logical keyword support, etc.)

**Comment by vitorroriz** [comment]
@r12a These are great points, thanks for joining the thread. Can you give more details on:
> But it may be more problematic if they have been set in concrete by the browser, making it difficult to change them

The current specification allow authors to extend a rule and redefine specific descriptors of them, with `system: extends <name>`. So, if author would prefer a specific `suffix`, it would be quite easy to just extend an existent style and alter just that descriptor. Or they could even override most UA counter-styles, by redefining the rule with the same name. So I thought it wouldn't be so hard to change them. Or do you mean that if author needs to extend a UA style, they could define it as they want directly so it wouldn't be such a useful feature for them anyway?

**Comment by r12a** [comment]
> The current specification allow authors to extend a rule and redefine specific descriptors of them, with system: extends <name>.....

@vitorroriz here's what worries me: In an ideal world, i'd agree that it seems straightforward to use a UA supported style, and change it with `extends` where needed.  However, i think that in practice, with the best will in the world, authors will often have to do some research before using many of the styles.  Even if we support many more styles in the UA, there will still be some that aren't supported, and some that are not supported by all browsers, and the author won't know which those are without some research.  If they want to use a style such as `bangla` they will have to first check whether or not it is supported interoperably by all the browsers they and their readers use. And they may also need to experiment a bit to check how/whether they need to extend it. 

To me, it seems much simpler to me to just open up the Ready-made Counters doc, see that `bangla` is there, and copy-paste it to their CSS style sheet, replacing lines as needed. No need to worry about browser support or interop issues, and it's clear what the default syntax is. (We even make suggestions about alternative affixes.)

**Comment by jensimmons** [comment]
1. I do not believe even a tiny minority of web developers know that the Ready-made Counters doc exists. That's why I talked about it in [What's new in CSS](https://developer.apple.com/videos/play/wwdc2023/10121/?time=1729) — to help spread the word. But a document like that will never get widespread evangelism. 99% of web developers do not know that the CSS Working Group exists, let alone the Internationalization Working Group. They don't know what web standards are. They do not look up things in any flavor of W3C document. They depend instead on other resources that represent what's supposed to be shipping in browsers.

2. I have great hope that browsers will align on whatever the CSSWG agrees should be done. It will take a year or so to get there — but it's incredibly doable for every browser to ship 100% interoperable implementations of the entire Ready-made Counters document. DevRel / evangelism can coordinate. We can ask Interop 2024 to help by [publicizing](https://wpt.fyi/interop-2023) test failures. The CSSWG is the right place to encourage such interoperability… Things are much different than they were 20 years ago, when it was very common for browsers to have done something quite different from each other with very little hope of getting to interoperability.

3. Many browsers already support more languages than what was listed by the CSSWG. It's already impossible to know which languages are supported in which browsers, because [MDN documents](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) what the spec says, not the current reality. By specifying a larger set and pushing for interoperability on that larger set, this reduces the amount of work for developers, not increases it. As it is now, it's likely a developer will try something in their favorite browser — and assume if it works/doesn't that's how it will work/not in every browser. They often do not test. And will end up with missing support on platforms they are not checking. The above resolution is how to get to interoperability. 

4. If these styles are part of what browser are expected to ship, then they will get far better documentation on MDN and other CSS resources — books, blogs, conference talks, videos, podcasts. There will be developer documentation for both the UA stylesheet, and for how to override it. 

5. Personally, I really don't want us to stop at "these languages are supported because they were there first, all the rest are not important enough to be included — so go find this document hardly anyone knows about, and add support to your website for your language manually". There were many things baked into the web in the 1990s that favors English and other European (Latin-based / `horizontal-tb`, LTR) scripts as "correct", while the cultures of many countries are considered "not worthy". I expect everyone on the Internationalization Working Group does _not_ believe this — and that's why you've dedicated years of work and tons of expertise to make the web truly international. But let's undo the wrongs of the past, and unbias the early choices as much as possible. Entire continents have few indigenous languages listed in what's "supposed to be" in the UA stylesheet (prior to the above resolution), while colonial languages are deeply represented. Don't we want to change this? We should make it as easy as possible to switch from "1, 2, 3" to another counter style. Not make it easy for a few cultures, while hard for most. We might not be able to get all cultures, or keep things perfectly up to date, but we can try. We can succeed 80-90% of the time, and give developers the tools they need to perfect support the other 10-20%.

**Comment by litherum** [comment]
A few additional points I'd like to make:

1. The ready-made counter styles definitions aren't going away. Authors can still create their own counter styles which both A) can be tweaked at a finer-grained way than swapping out the whole counter style for another, and B) are forward-compatible and won't change with future browser updates.
2. I think much of the arguments [above](https://github.com/w3c/csswg-drafts/issues/8636#issuecomment-1594317071) are making the perfect the enemy of the good. Are there people who want to specify in great detail the counter style algorithm to use on their webpages? Sure. Are there other people would just want the browser defaults for their language? Certainly.
3. This kind of "simple things simple, complex things possible" is central to the design of CSS. An analogy: it's possible for an author to implement letter-spacing themselves by wrapping every letter in their content in a `<span>` - and people can do that if they want super fine control over how letter spacing is applied. But we still offer the `letter-spacing` property for the people who just want the default behavior which is sufficient for most people.
4. If there are, in fact, corrections to be made to these ready-made counter styles, it's way easier to update ~3 major browsers than it is to update all the websites which use them. I also expect browsers would stay up-to-date with the spec, as updating these rules is essentially a data change, which is cheap from a browser developer's point of view.

**Comment by aphillips** [comment]
I was [actioned](https://www.w3.org/International/track/actions/1276) by I18N-WG in [this call](https://www.w3.org/2023/06/22-i18n-minutes.html#t05) to respond to this issue. Adding wider built-in support for other languages/cultures is generally a good thing: it is our mission to encourage wider availability of linguistic/cultural support in the Web, with no culture, language, or writing tradition excluded. 

I18N is concerned (for the reasons @r12a enumerates elsewhere) that converting our work in this space into a registry might be a maintenance headache unless approached carefully. The ready-made counter styles are meant to be useful to page authors whose linguistic or cultural needs are not built-in to browsers. At the same time, we have not stabilized the data we capture and are continually striving to improve the styles provided. Registries (and a requirement for browsers to implement the registry) generally carry a certain level of stability guarantee. 

We believe we would support CSSWG operating a registry of counter styles given appropriate thought into gathering, vetting, and updating styles.
