### ISSUE TITLE
[css-overflow-3] Specify extent of ink overflow

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#8649]
The spec [defines ink overflow](https://drafts.csswg.org/css-overflow-3/#ink), but does not specify the extent of it, because some effects in CSS, such as blur radius or box shadow radius, are theoretically infinite.

However, issues such as #8597 and w3c/IntersectionObserver#295 are good reasons to define it, for the purpose of knowing the size of an animated image of a DOM subtree for the purpose of creating a bitmap image, or occlusion testing.

I think we can define it in cases of blur or box shadow in a reasonable way, such as defining the ink overflow to go out to a certain [specified standard deviation](https://w3c.github.io/csswg-drafts/css-backgrounds/#shadow-blur) on its Gaussian shape.

**Comment by fantasai** [comment]
If it's possible, it would be better to find a way to solve these problems without needing to define the extent of ink overflow. The ink overflow extent isn't something that can be made necessarily interoperable (it depends on where you cut infinite blur etc, but also on what fonts are used, and possibly other effects). So pages that depend on it being a certain value could then break... I'd rather not expose it to the Web if we can avoid it.

**Comment by szager-chromium** [comment]
> If it's possible, it would be better to find a way to solve these problems without needing to define the extent of ink overflow. The ink overflow extent isn't something that can be made necessarily interoperable (it depends on where you cut infinite blur etc, but also on what fonts are used, and possibly other effects). So pages that depend on it being a certain value could then break... I'd rather not expose it to the Web if we can avoid it.

I'd like to press on this issue a bit if I may. There are now a couple of in-development specs that would like to rely on ink overflow extent, and it seems like a legitimately useful thing for any visually rich application environment. It isn't necessary, I think, to specify ink overflow down to the pixel; it would be enough to specify the maximum possible extent of any ink overflow, and by that measure many types of ink overflow are already de facto interoperable and specifiable. Glyph overhang is a notable exception, but perhaps there is a way to specify the *maximum* possible glyph overhang for a piece of text?

If necessary, we could limit the spec language to the lowest-hanging fruit, i.e., types of ink overflow that are trivial to describe. But I'd like to see if we can do *something*.

**Comment by drott** [comment]
From the font technology perspective, for OpenType fonts the maximum glyph extent and maximum per-glyph bounding box should be specified in the HEAD table in the xMin, xMax, yMin, yMax fields. [Compare here](https://learn.microsoft.com/en-us/typography/opentype/spec/head#:~:text=int16,Minimum%20x%20coordinate%20across%20all%20glyph%20bounding%20boxes.). This a per-font metrics, as opposed to a per-glyph metric.

**But**: I am not sure if applications are practically limited by that or restricting glyph drawing to the extents of this top-level bounding box. The individual bounding box of a glyph can still be determined by calculating a bounding box of its glyph shape and thus, a drawing backing surface can be allocated for an individual glyph that's potentially larger than what the font specifies in the HEAD table. 

I haven't checked a set of fonts on whether they specify reasonable values in there. So what usually happens if relying on a font metrics that's not been used in a strict way before: We may find many existing fonts having incorrect values in these field and if they were used as a strict restriction, glyphs may be cut off.

CC @bungeman @behdad

**Comment by jfkthame** [comment]
I've definitely seen fonts with incorrect bounding-box data, though I don't recall the specific examples, and this did result in clipped rendering in some context (which is what led to investigating the font data), while in other environments the glyphs rendered fully.

One point to note with regard to OpenType bounding boxes is that they represent the bounding box of the glyph geometry, but do not account for the fact that at rendering time, the effects of grid-fitting and antialiasing may mean that pixels just outside the "theoretical" glyph bounds are actually affected.

And how do the extents in the 'head' table work in the case of variable fonts? Do they indicate the maximum bounding box under any combination of variation settings, or the bounding box of the default instance? The spec does not appear to provide for applying deltas to these fields, AFAICS.

**Comment by szager-chromium** [comment]
@drott I presume all browsers must already compute glyph overhang extent, for the purpose of determining the size of composited layers, no? If I'm not mistaken, [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/layout/ng/ng_ink_overflow.cc;drc=7fa0c25da15ae39bbd2fd720832ec4df4fee705a;l=450) is where chromium does that.

This code is unfamiliar to me, but it appears that chromium iterates over individual glyph bounds rather than relying on xMin etc. for the font. That probably doesn't bode well for the prospect of specifying glyph overhang interoperably.

I'm quite ignorant about font specifications, so I'm asking the most naive questions, but: can you think of any reliable way to describe the maximum possible extent of glyph rendering for a given block of text and a given font across *all* browsers?

**Comment by szager-chromium** [comment]
I'm hoping the CSSWG can resolve on whether to land these PR's, which relate to this issue and also #10066:

https://github.com/w3c/csswg-drafts/pull/9823
https://github.com/w3c/csswg-drafts/pull/9842
https://github.com/w3c/csswg-drafts/pull/10085

**Comment by fantasai** [comment]
@szager-chromium I think it would help if you could describe what you're trying to accomplish with these PRs and for what purpose. I'm not sure I agree with the changes, and I'm not convinced that defining ink overflow in this manner is reasonable or warranted; but it would help to understand what you are trying to do.

**Comment by szager-chromium** [comment]
@fantasai I refer to the issue links in the first comment, and to my comments below it. I'm not very familiar with view transitions so I don't have much to add about #8597, but I can speak to the IntersectionObserver [issue]( w3c/IntersectionObserver#295), regarding the [V2](https://github.com/w3c/IntersectionObserver/blob/v2/explainer.md) feature set. A critical aspect of that API is that it reports whether an element of interest is occluded by other content, and the occlusion detection is [based on ink overflow rectangle](https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo). V2 shipped in chromium in 2020, and it is [increasingly popular](https://chromestatus.com/metrics/feature/timeline/popularity/3051). One of the issues that came up in spec conversations about V2 is that it's difficult to guarantee interoperability because the extent of ink overflow is insufficiently specified.

IntersectionObserver V2 is most useful in a cross-origin embedding context, where the embedee doesn't trust the embedder to display the embedded content faithfully. In this situation, the burden falls on the embedder to ensure that the embedding page doesn't inadvertently occlude embedded content, and it's difficult for authors to do this reliably and interoperably if they can't depend on some upper bound on ink overflow rects generated by their content. For that reason, the focus of my work has been to provide a reliable *upper bound* on ink overflow, and to provide practical guidance that authors can rely on.

**Comment by fantasai** [comment]
@szager-chromium I think the bounds that you would want for occlusion detection and the bounds we'd want for painting are not necessarily the same. For example, the theoretical bounds of a blur radius are infinite, although practically speaking we clip those. But where we clip the blur effect and where you decide "the stuff below this is occluded" might not be the same.

I also don't understand what sort of real-world interop issues you're running into that are motivating your proposed changes to the spec.s

**Comment by szager-chromium** [comment]
@fantasai At least in the case of IntersectionObserver V2, which is security-focused, we always want to err on the side of caution and report content as "possibly occluded" whenever the UA cannot absolutely guarantee that not a single pixel gets shaded by other content. It is prohibitively expensive to determine occlusion precisely; that's why "maximum possible extent" is an useful concept. We can analyze the maximum possible extent of all ink overflow on a page and conservatively mark content as "possibly occluded" whenever there is any overlap whatsoever.

We have done some monitoring and analysis of IntersectionObserver V2 as deployed on partner sites, and have concluded that this conservative approach based on maximum possible extent of ink overflow works well in practice. There is a very low incidence of embedders inadvertently causing V2 to report content as "possibly occluded." So we have confidence in this approach. However, other browsers have rightly pointed out that the lack of specificity in the HTML spec around the extent of ink overflow makes it hard to guarantee interoperability of this feature.

Blur radius is the quintessential example of a feature that runs exactly counter to the "maximum possible extent" approach, but fortunately all the major browser implementations are de facto interoperable because they all use the same math to determine the extent of a blur effect. The [change](https://github.com/w3c/fxtf-drafts/pull/544) I landed to the fxtf spec was simply to non-conformingly codify and document that.

Text and text decorations are the only sources of ink overflow for which there isn't a completely satisfying answer to the "maximum possible extent" question. However, in conversation with @drott and @kojiishi, I landed on the language in #9842. The tl;dr is: "for a given well-defined font and text input, across browser implementations, the maximum possible extent of ink overflow from hanging glyphs is no more that a 2px outset from the painted area determined by visual inspection in any conforming browser." Or, even more succinctly: "look at your content in any browser, and make sure there's a 2px gap between any painted text and any element you want to avoid occluding."

Text decorations are even harder than text in this regard: the extent of ink overflow is a combined product of the font rendering system *and* the browser implementation. #10085 is, I admit, not wholly satisfying, but it is the best guidance I could come up with for authors trying to reason about the maximum possible extent of ink overflow.

**Comment by jfkthame** [comment]
> "for a given well-defined font and text input, across browser implementations, the maximum possible extent of ink overflow from hanging glyphs is no more that a 2px outset from the painted area determined by visual inspection in any conforming browser."

This seems a bit unsatisfactory to me, because I think there are a number of factors it ignores. As an author, you can't actually be sure what font will be used to render the content on the user's machine. Your carefully-chosen webfont may have failed to load, for any of various potential technical, policy, or user-preference reasons. So the user may end up seeing a substitute or fallback font that has very different overhang characteristics.

In addition, the user may have set a min-font-size preference in their UA (e.g. for accessibility reasons) that mean the text is being rendered at a different size than you expected, resulting in greater overflow. Or they may have an accessibility feature that adds a high-contrast opaque background behind text elements, potentially extending more than 2px outside the glyph bounds.

So if it's necessary for authors to reason with absolute certainty about this for security reasons, I think the proposed text here falls short, and potentially gives a false assurance.

**Comment by szager-chromium** [comment]
@jfkthame Those are legitimate concerns with respect to IntersectionObserver V2. If UA settings or accessibility features cause an element of interest to be occluded, then the correct behavior is for V2 to report the content as "possibly occluded". I think it's a good idea to for the spec to call out these issues in non-normative text, but I would lean towards adding it to the IntersectionObserver spec.

I still think it's worth exploring whether there is some language we can add to css-text that is helpful to developers and relevant to non-IntersectionObserver use cases. Including caveats such as "for a given well-defined font" allows this change to be focused on the behavior of the glyph rendering subsystem without involving other parts of the spec or the browser.

**Comment by noamr** [comment]
For view transitions, the relevant issue is #8282. We want elements to count as "off screen" if they're *actually* offscreen, including their drop-shadows etc.

Perhaps we can reach some middle ground, where we define something that's ink-overflow-ish, and includes glyphs of the known font, drop-shadows, a fixed number/function for blur etc, and ignores user overrides, and can be used for Intersection observer v2, view transitions, and any other place that requires this kind of insight. Though these quirks should be measured against an option for the author to supply their own margin with reasonable defaults.

**Comment by szager-chromium** [comment]
@noamr For the view transition case, similar to IntersectionObserver, it appears that "maximum possible extent of ink overflow" is a useful concept.

**Comment by astearns** [comment]
Given that @fantasai and @jfkthame do not yet appear to be satisfied with this discussion, I think it’s premature to put this on the agenda.

**Comment by szager-chromium** [comment]
@fantasai @jfkthame Can I ask you to respond to my most recent comments? There is a genuine need here -- View Transitions is a [CR](https://drafts.csswg.org/css-view-transitions/), and IntersectionObserver V2 is used on [6% of page loads](https://chromestatus.com/metrics/feature/timeline/popularity/3051) in Chrome. Even if I can't overcome your objections to the PR's I put up, I would like to find a way forward.

Thanks,

Stefan

**Comment by szager-chromium** [comment]
@jfkthame  -- you make a good point that the actual font description used by the glyph rendering subsystem might be different from the one requested by the developer, in which case any visual inspection of ink overflow they did during development will not apply. I meant to acknowledge this with the preface “for a given well-defined font” , but the spec text could be more explicit, something like:

“note that there are many factors that may cause the glyph rendering subsystem to use a font other than the one specified in stylesheets when drawing text, including but not limited to UA settings, accessibility features, and the availability of web fonts. The extent of ink overflow derives from the actual font used for rendering text, and developers should allow for the possibility that the actual rendered extent of ink overflow from glyph overhang does not match what they measured during development.

... and then we could add some language to the IntersectionObserver spec along these lines, with links to the css-text spec:

“Note that the extent of ink overflow from text and text decorations cannot always be predicted or measured in advance. In all cases, IntersectionObserver will determine occlusion based on the actual rendered extent of ink overflow.”

@fantasai  -- Although the *concept* of ink overflow is well-defined, the *extent* of it is not, and that’s what I’d like to fix. I hope my previous comment about the utility of “maximum possible extent of ink overflow” shows why the difference between painted extent and occlusion is not a problem – in fact in almost all cases they are the same, and even for blur filters there is an easy practical solution that also agrees with browsers in practice. If we encounter a particular special case where there is a divergence we can note it explicitly in the spec.

**Comment by fantasai** [comment]
Some points from reviewing the issue and the proposed PRs:

- What @szager-chromium describes as a "hanging glyph" in his [proposed appendix](https://github.com/szager-chromium/csswg-drafts/commit/706fb9ed0193b21e6e1505c41e142e11d45601bb) is not what css-text considers a "hanging glyph". What he's describing (see his [illustration](https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20class%3D%22figure%22%20style%3D%22margin%3A0%3B%20font-size%3A10rem%3B%20font-family%3Agaramond%3B%20font-style%3Aitalic%22%3E%0A%09%20%20%20%20%3Cspan%20style%3D%22display%3Ainline-block%3B%20width%3A1ch%3B%20height%3A1lh%3B%20background%3Agreen%3B%20opacity%3A0.5%22%3E%3C%2Fspan%3E%3Cspan%20style%3D%22vertical-align%3A%20top%3B%22%3Ef%3C%2Fspan%3E%3Cspan%20style%3D%22display%3Ainline-block%3B%20width%3A1ch%3B%20height%3A1lh%3B%20background%3Agreen%3B%20opacity%3A0.5%22%3E%3C%2Fspan%3E%0A%09%20%20%3C%2Fdiv%3E%0A%09%3C%2Fdiv%3E)) is a glyph whose glyph bounds extend beyond its bounding box. This is already defined as being ink overflow in the [definition of ink overflow](https://www.w3.org/TR/css-overflow-3/#ink). I don't mind adding clarifying statements about that elsewhere (e.g. where we define the sizing of an inline box), but it definitely has nothing to do with the definitions in `hanging-punctuation`.
- For `border-image`, this is already defined as ink overflow, but the terminology didn't exist when css-backgrounds-3 was written; added in as an editorial clarification to the spec in https://github.com/w3c/csswg-drafts/commit/ee0d71805788f959d8c10886e099e1143f0aed1d. I also made the same clarification for `box-shadow` in https://github.com/w3c/csswg-drafts/commit/b03d1239730353564165aa9ee464887f531b906b.
- Text decoration is already defined as ink overflow, and I don't think the proposed example adds very much to the spec.

As @jfkthame explains, and as several of [your PRs](https://github.com/w3c/csswg-drafts/issues/8649#issuecomment-1998341267) admit, ink overflow is not going to be a 100% interoperable measurement, only an interoperable concept, because of the differences in painting and font rendering across implementations.

Given we've defined what is and is not ink overflow already, what point of confusion are you trying to clarify here in this issue?

**Comment by szager-chromium** [comment]
@fantasai -- jfkthame made the same point about "hanging glyph" in a code review [comment](https://github.com/w3c/csswg-drafts/issues/10066#issuecomment-2088122192); I updated the PR to correct the language.

For `box-shadow`, I deliberately placed the new text just after the illustrated example that shows the effect of spread and blur; I felt that it added clarity to the specifics of the geometry. I agree that `border-image-outset` doesn't need any clarification.

More generally, although the language added to `text` and `text-decoration` is squishy and non-normative, it might also be useful for developers who want to reason about the extent of ink overflow. Specifically, the de facto (within 2px) consistency of ink overflow extent between different implementations for a given well-defined font, and the effect of using the `from-font` keyword where supported for text decorations, might be useful guidance. Maybe they belong in the IntersectionObserver spec rather than in `css-text` or `css-text-decoration`; or maybe they belong in a blog post or a tweet instead of a spec. That's the question I'm hoping to resolve.

**Comment by frivoal** [comment]
> maybe they belong in a blog post or a tweet instead of a spec. 

That would be my take.
