### ISSUE TITLE
[css-view-transitions-2] What happens if an SPA view transition starts while an MPA transition is in progress?

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8678]
A couple of options:

1. MPA transition skips to the end, allowing the SPA transition to start.
2. SPA transition skips to the end, allowing the MPA transition to continue (assuming the elements it needs are still there).

If an SPA transition starts while another SPA transition is in progress, the first transition skips to the end, allowing the second to start.

---

My opinion is option 1, given the consistency. I think we should avoid making MPA transitions different to SPA transitions, as much as possible. This thinking also seems in line with https://github.com/w3c/csswg-drafts/issues/8677

**Comment by vmpstr** [comment]
Ideally both transitions would run, since it seems like MPA is a liminal transition from some other page and the SPA one is doing things within the page. 

I see the desire to go with option 1 for consistency of MPA and SPA transitions from the developer perspective. However, from the user perspective, I would want option 2. My rationale here is that the navigation was already initiated and I'd rather have a consistent experience in transitioning page rather than elements moving on the page -- which is what presumably the incoming page is trying to do.

**Comment by noamr** [comment]
Closing in favor of #9512
