### ISSUE TITLE
[css-view-transitions-2] MPA: Interacting with transition states

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8682]
With SPA transitions:

```js
const transition = document.startViewTransition(callback);

transition.updateCallbackDone.then(() => …);
transition.ready.then(() => …);
transition.finished.then(() => …);
transition.skipTransition();
```

`ready` is at the start of the transition. The pseudos exist at this point, so you can animate them with JavaScript.

`finished` is when the final state is visible and the pseudos are gone.

We want something similar for MPA transitions, except for `updateCallbackDone` which doesn't make sense for MPA, as the browser handles the update, and script can't span the update (the new page is a new scripting context).

Some options:

```js
document.addEventListener('crossdocviewtransition', (event) => {
  event.ready.then(() => …);
  event.finished.then(() => …);
  event.skipTransition();
});
```

Or:

```js
document.addEventListener('crossdocviewtransition', (event) => {
  event.transition.ready.then(() => …);
  event.transition.finished.then(() => …);
  event.transition.skipTransition();
});
```

The latter might be preferable, because it means a helper function can do things with a transition instance, and in most cases it won't matter if it's an MPA or SPA transition.

We could have a `ViewTransition` class that omits `updateCallbackDone`, and `document.startViewTransition` would return a `SameDocumentViewTransition` that inherits from `ViewTransition` and adds `updateCallbackDone`. Or, an MPA `ViewTransition` instance could just have a `updateCallbackDone` promise that's already fulfilled.

**Comment by noamr** [comment]
Note for @jakearchibald: Forgive me if this has already been discussed, I don't think it has by looking at the previous issues.

I wonder if instead of having new events with a slightly different `ViewTransition` object, we could combine this problem with #8687. This would also be a solution to the problem of programmatically extending the MPA transition's `updateCallback`. 

Let's say that instead of an existing transition object, we had `document.startViewTransition(updateCallback, { existingTransition: 'skip' | 'finish' | 'continue' }` or `document.continueViewTransition` (strawman, as per how I understood the #8687 mindset), where `skip` is the current behavior, `finish` is "wait until previous transition is finished and use end state as old state for this one` and `continue` would be to use whatever the current state is as the old state.

In the MPA case, you could do this:
```html
<head>
function continueTransition() {
  const transition = document.startTransition(async () => { await extendTransition() }, {existingTransition: 'continue' });
transition.ready().then(() => { ... });
}

// Either this:
continueTransition();
addEventListener('pageshow', () => continueTransition());

// or the following if we go down the path of a new event:
addEventListener('reveal', () => continueTransition());
</head>
```

**Comment by noamr** [comment]
Closing this, this is handled in the spec draft. `updateCallbackDone` is a resolved promise. Please feel free to reopen/open a new issue if this is still an issue!
