### ISSUE TITLE
[css-view-transitions-2] MPA: What happens if there's a cross-origin redirect?

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8684]
Previous discussion: https://github.com/WICG/view-transitions/issues/200

If you navigate from origin A to origin B, which redirects back to A, it seems bad to expose that there was no in-between page by allowing a transition to run or not.

So, if there's a cross-origin redirect, it feels like we should disallow transitions. We can lift the behaviour in future if we feel it's safe.

**Comment by tabatkins** [comment]
Agreed.

**Comment by noamr** [comment]
I don't think there is any disagreement here. Can we close this issue? It's in the explainer.

**Comment by jakearchibald** [comment]
As long as folks remember to put it in a spec

**Comment by noamr** [comment]
Speaking with @annevk about this, one valid reason to disallow transitions on cross-origin redirects though is so that the user doesn't feel that things are "smoothed out", they should probably be aware somehow that there was a redirect, even if it's minor like a flash-of-white etc.

If this is the reason to disallow VT on XO-redirect, it's pretty clear to spec, and wouldn't apply to history traversals as the redirect doesn't happen then and it's ok to keep them smooth.

**Comment by noamr** [comment]
Closing, as this is in the draft spec. https://drafts.csswg.org/css-view-transitions-2/#document-setup-outbound-cross-document-view-transition
