### ISSUE TITLE
[cssom-1] [css-cascade-4] Extend CSSImportRule to expose supports condition

### ISSUE THREAD

**Issue by CanadaHonk** [w3c/csswg-drafts#8710]
[CSSImportRule](https://w3c.github.io/csswg-drafts/cssom/#cssimportrule) does not allow exposing a potential [\<supports-condition>](https://w3c.github.io/csswg-drafts/css-conditional-3/#typedef-supports-condition) of an `@import`, like [specified in css-cascade-4](https://drafts.csswg.org/css-cascade-4/#import-conditions):

```css
@import "example.css" supports(display: flex);
```

Without this, it is not possible to access an `@import`s supports condition with JS/etc.

In css-cascade-5, [CSSImportRule was extended](https://drafts.csswg.org/css-cascade-5/#extensions-to-cssimportrule-interface) to add `layerName` for the new cascade layers, but nothing was added for supports in CSSImportRule.

**Comment by CanadaHonk** [comment]
I can make a PR to css-cascade-4 if it seems reasonable, having something roughly like:
```
partial interface CSSImportRule {
  readonly attribute CSSOMString? supportsCondition;
};
```

As there is no parsing/particular types for supports conditions (or `@supports` rules). Thoughts? cc @emilio @tabatkins @fantasai

**Comment by tabatkins** [comment]
Wrt elika's comment about consistent naming:

* the CSSSupportsRule uses the generic `conditionText` from the CSSConditionRule superclass
* CSSImportRule uses `media` for its media condition, but that's a `MediaList` object, rather than a string

While a plain `supports` attribute sounds nice, I propose we avoid it for a possible future where we have an object representing a supports condition in more detail. Instead I recommend `supportsText` as the attribute name, matching `conditionText` from CSSConditionRule, and things like `selectorText` from CSSStyleRule.

**Comment by CanadaHonk** [comment]
Agreed, just updated property name to `supportsText` in PR (#8712).
