### ISSUE TITLE
[css-background-4] add background-layers property to set everything but background-color

### ISSUE THREAD

**Issue by JaneOri** [w3c/csswg-drafts#8726]
spec: https://w3c.github.io/csswg-drafts/css-backgrounds/#the-background

We often run into situations where `background-color` has already been set for an element or component, and in a separate class we want to also add a background image to it.

In order to do this without overriding the color, we have to use the `background-image` property specifically.

Then we need to size, position, no-repeat it and that's 3 more longhand properties.

Add two bg images and we're managing parallel arrays in every longhand property above to avoid overriding the background-color set elsewhere.

[It gets pretty tedious very quickly.](https://twitter.com/LeaVerou/status/1647617109835350016)

Fortunately, [the spec already defines a `<bg-layer>`](https://w3c.github.io/csswg-drafts/css-backgrounds/#typedef-bg-layer) so it may not be a big ask to _add `background-layers` as a shorthand property that defines everything for a background, excluding `background-color`._

`background-layers = <bg-layer># | none`

(suggesting plural `background-layers` even though the longhand bg properties are singular since they predate multiple image layers)

Thank you!

**Comment by LeaVerou** [comment]
+1

We could then define `background` as a shorthand of `background-layers` and `background-color`.

**Comment by tabatkins** [comment]
I don't have a strong opinion on this, but it sounds reasonable, and the proposal itself seems right.

> I think I'd slightly favor background-layer for consistency, since the common case is one layer.

Right, name-wise we almost never do plurals, so it would be `background-layer`.

> but it should still expand to the full list of 9 longhands.

Yeah, it would be a separate shorthand, unrelated to the `background` shorthand.

**Comment by SebastianZ** [comment]
As there's just positive feedback for this suggestion, so far, let's get a resolution on whether to add it.

The proposal is to add a `background-layer` shorthand that allows to define the background layers independently from `background-color`.

Sebastian

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Add a `background-layer` shorthand for everything in `background` aside from `background-color`

**Comment by fantasai** [comment]
-1 to the proposal, mainly because having `background-layer` expand to multiple layers seems really off. If we don't want to make it plural, we should find a word that represents the whole stack of layers somehow.

**Comment by tabatkins** [comment]
I don't understand your objection, @fantasai. We virtually *never* use plurals in property names, even tho a lot of properties are comma-separated multiple instances. Specifically *in the `background-*` properties, not a single one of them is plural despite accepting multiple values. The longhands don't even have the excuse that `background` might refer collectively to all the background images; `background-image` is very clearly talking about *one* image, `background-position` about *one* position, etc.

It would be a pretty big break from tradition to suddenly have one `background-*` property be pluralized.

**Comment by fantasai** [comment]
@tabatkins I'm not arguing for plural, I'm just arguing against `background-layer`. I think it's confusing for multiple reasons... And additional one would be, the color is itself a layer... but we're intentionally excluding it here.

**Comment by fantasai** [comment]
What about `background-overlay`? That addresses both of the concerns I raised:

- It more clearly refers to the part of the background overlaying the color. (The background color is itself, functionally, a layer of the background so `background-layer` is confusing in this respect.)
- It can be interpreted in a collective sense, so it doesn't feel odd that it's not plural.

**Comment by tabatkins** [comment]
Not the hugest fan of that, since a background is, itself, an underlay for the element. ^_^

**Comment by Afif13** [comment]
A few ideas

```
background-stack
background-list
background-canvas
```

**Comment by j-f1** [comment]
Maybe `background-pattern` (kinda the opposite of the solid `background-color`)?

**Comment by manuelmeister** [comment]
What about `background-sheet` or `background-screen`?
I also thought about `background-cover`, but this would be definitely confusing.

**Comment by gavinmcfarland** [comment]
Can I confirm if I understand the proposal correctly? Would the proposal introduce a new way to control backgrounds, that instead of overriding, would combine, blend or overlay backgrounds from different rules?

For example:
```css
.foo {
  background-layer: red;
}

.bar {
  background-layer: url("image.png") no-repeat right top;
}

.baz {
  background: url("image2.png");
}

Would be equivalent to computed CSS of
```css
background: red, url("image.png") no-repeat right top, url("image2.png");
```

If so, I feel like `background-layer` seems appropriate and matches up with the mental model of many design programs where fills can have several layers.

**Comment by Loirooriol** [comment]
@gavinmcfarland You are misunderstanding, this proposal is for a normal shorthand, not for additive cascade.

It would just allow writing

```css
background: url("image.png") no-repeat right top, url("image2.png"), red;
```

as

```css
background-something: url("image.png") no-repeat right top, url("image2.png");
background-color: red;
```

**Comment by gavinmcfarland** [comment]
Perhaps it's overkill, but could we draw inspiration from other CSS properties. Like `grid-template-areas` where you can name the areas and specify them in each individual rule?

For example:

```css
div {
  background-layers: "base"  "artwork";
}

.foo {
  background-layer: "base";
  background: red;
}

.bar {
  background-layer: "artwork";
  background: url("image.png") no-repeat right top;
}
```

Which would compute to:

```css
background: red, url("image.png") no-repeat right top;
```

I feel like this could play nicely with existing conventions and understanding of the `background` property?

**Comment by Loirooriol** [comment]
Additive cascade is off-topic for this issue, it's discussed in https://github.com/w3c/csswg-drafts/issues/1594 instead.

**Comment by gavinmcfarland** [comment]
> @gavinmcfarland You are misunderstanding, this proposal is for a normal shorthand, not for additive cascade.
> 
> It would just allow writing
> 
> ```css
> background: url("image.png") no-repeat right top, url("image2.png") red;
> ```
> 
> as
> 
> ```css
> background-something: url("image.png") no-repeat right top, url("image2.png");
> background-color: red;
> ```

Thanks @Loirooriol for clarifying. So it is quite literally just another property that excludes `background-color`.

I'm not sure I'm in favour of this. I think it could introduce more confusion about the use of the existing `background` property works. It's changing the mental model of how background works by introducing the idea that `background` has a primary base which is a colour and then everything else on top, ie `background-something (if I've understood it correctly). I think it could undo lots of learning that people have worked towards understanding CSS only to find out there's an expectation or special property that they need to factor into their existing knowledge.

I like the intent of the proposal, just not sure if I agree with the suggested implementation.

**Comment by gavinmcfarland** [comment]
> Additive cascade is off-topic for this issue, it's discussed in #1594 instead.

Ok, thank you. I'll take a look at that issue. Perhaps then there's a chance that resolves the need for this proposal?

**Comment by nt1m** [comment]
I feel like the current proposal is a bit confusing because people already know `background` / `background-image` as different ways to set background images, and `background-layers` is adding another one on top. So there will be cases where those 3 will just have the same syntax (if you don't set the other properties).

I'm sympathetic to the use case though and I'd suggest a shorthand that covers everything that `background` covers, but leaves out `image` and `color`.

**Comment by j-f1** [comment]
> I'm sympathetic to the use case though and I'd suggest a shorthand that covers everything that background covers, but leaves out image and color.

I like this idea too! Maybe something like `background-placement` for that

**Comment by MakhBeth** [comment]
my vote goes to background-stack. I found it more clear. 
Also don’t dislike background-layer. In singular because the plural make create confusion with additive cascade. background-overlay has the issue that a background is actually an underlay? Don’t feel it natural

**Comment by GreLI** [comment]
Have you considered `background-slice`?

**Comment by ljharb** [comment]
Is a new property a better choice than introducing some inline keyword in `background` to mean “ignore this one”? like, something that allows background to not override the color.

**Comment by Loirooriol** [comment]
> It's changing the mental model of how background works by introducing the idea that background has a primary base which is a colour and then everything else on top

But that's precisely how the current model works, see https://drafts.csswg.org/css-backgrounds-3/#background-color

> This property sets the background color of an element. The color is drawn behind any background images.

Your example with `background: red, url("image.png") no-repeat right top;` is precisely invalid syntax because `red` is not in the last layer.

**Comment by Crissov** [comment]
I’m fine with the name and concept of `background-layer`, but what if this was available in a different way where you could access random background layers?

~~~~ css
foo::background(1) {
  content: <background-image>;
  top: right: bottom: left: <background-position>;
  width: height: <background-size>;
  overflow[-x/-y]: <background-repeat>;
  position: <background-attachment>;
  sizing: <background-origin> <background-clip>;
}
~~~~

**Comment by neetij** [comment]
> Is a new property a better choice than introducing some inline keyword in `background` to mean “ignore this one”? like, something that allows background to not override the color.

I like this idea of adding a keyword to reuse a previously defined value.  
Keyword options: `revert-value`, `inherit-value`, `specified`.  
```css
.foo {background:gray;}
.alert {background:red;}
.alert {background:inherit-value url("alert.png") no-repeat right top; /* takes color from .alert */}
.bar {background:inherit-value url("bar.png") no-repeat right top; /* no color found, so behaves like 'inherit' */}
.foo .bar {background:inherit-value url("foo-bar.png") no-repeat right top; /* takes color from .foo */}
```

If the above is not within scope...
- `background-image-stack` / `background-stack`, or
- `background-media`, which is conceptually close to `background-image` (though possibly unclear we can't use videos)

**Comment by Loirooriol** [comment]
I don't think it can be a keyword, or be part of the value in general.
That's because shorthand expansion happens at parse time, but the value may not be known until computed-value time due to `var()`, so by then it's too late to decide whether a longhand should be part of the shorthand expansion or not.
Well, maybe it could work with a magical `ignore` (#5319) that skips that declaration and rolls back to the next winner of the cascade, but I'm not sure if that's doable.

Another idea could be using #8055, though you would still need to list the longhands once, an ugly universal selector, and a roundabout of setting via variables:

```css
* {
  background-position: from-shorthand(background: var(--background));
  background-repeat: from-shorthand(background: var(--background));
  background-attachment: from-shorthand(background: var(--background));
  background-image: from-shorthand(background: var(--background));
  background-size: from-shorthand(background: var(--background));
  background-origin: from-shorthand(background: var(--background));
  background-clip: from-shorthand(background: var(--background));
}
.foo { --background: url('foo.png') content-box no-repeat; }
.bar { --background: url('bar.png') 10px 20px no-repeat; }
```

However, I think the best solution (and already works in browsers!) would be setting the full `background` shorthand inside a layer, and then reverting `background-color` to the previous layer:

```css
@layer {
  .foo { background: url('foo.png') content-box no-repeat; background-color: revert-layer }
  .bar { background: url('bar.png') 10px 20px no-repeat; background-color: revert-layer }
}
```

**Comment by ljharb** [comment]
A keyword could mean “skip” and at parse time the shorthand could be expanded to every longhand except the skipped ones; that doesn’t seem like an obstacle.

**Comment by gavinmcfarland** [comment]
> @gavinmcfarland You are misunderstanding, this proposal is for a normal shorthand, not for additive cascade.
> 
> It would just allow writing
> 
> ```css
> background: url("image.png") no-repeat right top, url("image2.png") red;
> ```
> 
> as
> 
> ```css
> background-something: url("image.png") no-repeat right top, url("image2.png");
> background-color: red;
> ```

You're right, how silly of me. It's been a while since I worked with colours and images together and I don't think I realised that the colour had to be at the end.

Ok, now I understand what the problem is. Eek, I'm not sure if there a great alternative. I now realise what Lea was trying to describe.

What is currently `background-image` should have really bean `background-image-source`, but obviously want can't change how `background-image` works because that would break in every browser. Ultimately we're trying to find a word to describe a group of images, which is simple "images". And because most properties in CSS aren't plural that sort of feels weird to have `background-images`. `background-layer` feels completely alien to me, it has little to do with images (regardless or any similarities it might have with how browser engines work).

My best suggestions are:
- `background-image-list`
- `background-image-layer` <- even this one makes me shudder a bit

**Comment by gavinmcfarland** [comment]
> > It's changing the mental model of how background works by introducing the idea that background has a primary base which is a colour and then everything else on top
> 
> @gavinmcfarland But that's precisely how the current model works, see https://drafts.csswg.org/css-backgrounds-3/#background-color
> 
> > This property sets the background color of an element. The color is drawn behind any background images.
> 
> Your example with `background: red, url("image.png") no-repeat right top;` is precisely invalid syntax because `red` is not in the last layer.

You're right, how silly of me. It's been a while since I worked with colours and images together and I don't think I realised that the colour had to be at the end.

Ok, now I understand what the problem is. Eek, I'm not sure if there a great alternative. I now realise what Lea was trying to describe.

What is currently background-image should have really bean background-image-source, but obviously want can't change how background-image works because that would break in every browser. Ultimately we're trying to find a word to describe a group of images, which is simple "images". And because most properties in CSS aren't plural that sort of feels weird to have background-images. background-layer feels completely alien to me, it has little to do with images (regardless or any similarities it might have with how browser engines work).

My best suggestions are:

background-image-list
background-image-layer <- even this one makes me shudder a bit

**Comment by ljharb** [comment]
@Loirooriol i mean, what does it say for that now?

**Comment by Loirooriol** [comment]
It says `true` because `background-color` is part of the expansion, it's set to an internal [pending-substitution value](https://drafts.csswg.org/css-variables-1/#pending-substitution-value).

If in  #5319 we add `ignore`, we could maybe say that this pending-substitution value will be treated as `ignore` if the shorthand has the value that skips the longhand. But otherwise it's not straightforward.

**Comment by ljharb** [comment]
Yes, that's exactly what i'd say the default should be pending the var's value - but even if the default is `true` then the variable would be able to contain this new "ignore" keyword and override that. I'm not seeing a problem.

**Comment by SebastianZ** [comment]
Summary of the proposals above:

1. Add a new shorthand that includes all background layers but excludes the color. (Initial proposal by @JaneOri)
   Suggested names:
   * `background-layer`
   * `background-overlay`
   * `background-stack`
   * `background-list`
   * `background-canvas`
   * `background-pattern`
   * `background-sheet`
   * `background-screen`
   * `background-cover`
   * `background-slice`
   * `background-image-stack`
   * `background-media`
   * `background-image-list`
   * `background-image-layer`
2. Add a new shorthand that covers the background positioning, sizing, etc. but excludes the images and color (proposed by @nt1m)
   Suggested name: `background-placement`
3. Add a `::background()` pseudo-element (proposed by @Crissov; also [proposed by him earlier in another issue](https://github.com/w3c/csswg-drafts/issues/8634#issuecomment-1484070131))
4. Use additive cascade to add background layers instead of overwriting them (proposed by @gavinmcfarland; discussed separately in #1594)
5. Add a new keyword to `background` that skips overwriting the color (or any layer; proposed by @ljharb; related discussion in #5319)

Sebastian

**Comment by Loirooriol** [comment]
6. Close no change and tell authors to use `background-color: revert-layer` (https://github.com/w3c/csswg-drafts/issues/8726#issuecomment-1565469028)

**Comment by fantasai** [comment]
I think it's worth noting that we have a similar pattern of properties for `fill`, and might want to use the same name there: https://drafts.fxtf.org/fill-stroke-3/

**Comment by Schepp** [comment]
While this is not what the original poster asked for, here is a way to do exactly that: https://schepp.dev/posts/chaining-declarations-with-css-animation-composition/

So maybe the new thing might be based off whatever mechanic is at work here.

**Comment by fantasai** [comment]
@Schepp Ummmm, no, we definitely should not be using fill-forwards animations to declare normal specified values. :) https://www.w3.org/TR/web-animations-1/#fill-behavior

**Comment by Schepp** [comment]
Absolutely! 😅 

But maybe the fact that this works opens up new ideas.

**Comment by Loirooriol** [comment]
Improving https://github.com/w3c/csswg-drafts/issues/8726#issuecomment-1569033374, now that #10443 added `revert-rule` and Blink is implementing it, it will be possible to just do

```css
div {
  background: cyan;
}
div#foo {
  background: url("image") 10px 10px / 20px 20px no-repeat fixed border-box content-box;
  background-color: revert-rule; /* Reverts to cyan */
}
```

No need to add layers nor expand into longhands manually to avoid overriding the color.

**Comment by SebastianZ** [comment]
@Loirooriol If you want to resolution to be reconsidered, you should probably reopen this issue or create a new one and add it to the agenda.

Personally, I still see value in a shorthand that only sets the background layers. It feels less hacky to just set what you want to set instead of setting everything and then reverting the `background-color` value. Though it's definitely much nicer than having to set all the longhands.

Sebastian
