### ISSUE TITLE
[css-anchor] Anchor positioning should be logical first, not physical

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#8727]
I started reading the specification for Anchor Positioning, and I was surprised to see it littered with examples that refer to `top`, `left`, etc. 

In 2023, as we design a new way to do layout, it should be _logical_ in the way it describes things. Not _physical_. 

Especially since this is a way to layout popovers in a dynamic fashion — where the designer is being suggestive, not being controlling. "Please try to put this popover over here if it fits, or over there if it doesn't." Here and there should refer to block and inline start, and end. Not top, bottom, left and right.

**Comment by tabatkins** [comment]
Nothing about the spec is physical-only. The `<anchor-side>` keywords allow both physical and logical options; they can be used in any inset property, both `top` and `inline-start`.

Some of the example are written with physical properties, but that's just because they're shorter. I'd be happy to switch some of them to logical to ensure it's even more obvious this feature can be used either way, tho.

**Comment by jensimmons** [comment]
That's great to hear. Yes, I think it'd be wise to make most if not almost all of the examples use logical options. I know it does make the code a bit longer, and even a bit slower to understand... but the web industry _is_ adopting logical thinking and replacing physical layout, but by bit. We want to encourage people to do so. And new layout mechanisms like Anchor Positioning are the perfect opportunity to say "This is how this works. Logical. (oh, I guess if you have to use physical, ok, whatever, we won't break that... but everyone out there teaching this, teach it using logical syntax!"
