### ISSUE TITLE
[scroll-animations-1] Require <dashed-ident> for timeline names

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#8746]
Split out from https://github.com/w3c/csswg-drafts/issues/7759:

@tabatkins wrote:

> timeline names are `<custom-ident>` right now. Is that a necessity? Making it `<dashed-ident>` would be nice since it would avoid the grammar ever clashing in the future with new keywords.

+1, this will make future changes to the syntax easier.

**Comment by bramus** [comment]
I don’t see the exact need _right now_. `<custom-ident>` is used for a lot of name-giving-things; AFAIK only CSS Anchor Positioning requires a `<dashed-ident>` for the name.

That said, also not opposed to `<dashed-ident>` as it keeps things open syntax-wise. @tabatkins: As you raised this, is the intention here to use `<dashed-ident>` for name-things across all upcoming/future specs from now on?

Curious to hear what @fantasai, @flackr, and @ydaniv think about this.

**Comment by tabatkins** [comment]
No, we use dashed-ident in a few places, like custom color space names. We do have a bunch of custom names that predate the dashed-ident technology, tho, so our consistency isn't great.

> As you raised this, is the intention here to use <dashed-ident> for name-things across all upcoming/future specs from now on?

In general, yes. We don't want another repeat of the 'animation' shorthand fiasco. A plain custom-ident is fine *if* it's positionally fixed (requiring to go first, for example); if it can be mixed arbitrarily, as is usually the case in CSS, we really want to shift those to dashed-ident to avoid compat pain.

(And, anecdotally, it seems many people find it nice to have the dashed-ident in a complex value, as it makes it easy to pick out from the CSS-defined keywords at a glance.)

**Comment by flackr** [comment]
I'm good with requiring a `<dashed-ident>` for timeline names. It makes sense to try to avoid potential clashes in our shorthands.

Thinking about animation timelines specifically, it probably doesn't help for the animation shorthand since we already have animation-name as a `<custom-ident>` so we'd probably have to say in the `animation` shorthand that we interpret the first identifier as the animation name and the second as the timeline if specified. However, it should help avoid conflicts in the shorthands for establishing scroll and view timelines.
