### ISSUE TITLE
[css-view-transitions-2] Define the timing for capturing old Document state with respect to events on new Document

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8790]
https://github.com/w3c/csswg-drafts/issues/8785 and https://github.com/w3c/csswg-drafts/issues/8805 clarify the syntax of the events which are fired on the old/new Document during a transition. The timing of these events with respect to a navigation's lifecycle needs to be clarified.

Here are some constraints:

- The event dispatched on the old Document must be followed by a render to capture its visual state.
- The event dispatched on the new Document must be after the above event, since it passes contextual information.
- The event dispatched on the new Document show allow addition of render-blocking resources.

**Comment by noamr** [comment]
See https://github.com/w3c/csswg-drafts/issues/8805#issuecomment-1562370122.

- Not sure we should send a new type of event on the old document at all. Let users customize their exit state on navigate/click events rather than rely on a precise processing model.
- The JS in the new document should be activated after all the JS in the old document is complete.
- See https://github.com/w3c/csswg-drafts/issues/8805#issuecomment-1562370122. A place to do this would be a regular script at the end of the head.

**Comment by noamr** [comment]
I think this can be closed @khushalsagar ?
