### ISSUE TITLE
[css-shapes] Allow shape-outside to apply to initial letter

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#885]
I think that authors would like to be able to use [initial-letter](https://drafts.csswg.org/css-inline/#initial-letter-styling) with shape-outside. As the CSS WG have resolved that floats are ignored on an initial letter box, it now would not be possible to float the initial-letter in order to use shape-outside.

A solution (as mentioned in the f2f) would be to allow [shape-outside](https://drafts.csswg.org/css-shapes-2/#shape-outside-property) on initial-letter.

**Comment by upsuper** [comment]
Hasn't that already been covered by the [`initial-letter-wrapping`](https://drafts.csswg.org/css-inline/#initial-letter-wrapping) property (though at-risk) in the css-inline spec?

Or maybe you are proposing dropping `initial-letter-wrapping` in favor of `shape-outside` on initial letter?

**Comment by rachelandrew** [comment]
`initial-letter-wrapping` wouldn't allow for an arbitrary shape to be applied however, so the two use cases may be a bit different.

**Comment by fantasai** [comment]
OK, @dauwhe and I checked in edits to make the initial letter use `shape-outside` instead of the glyph outline when `initial-letter-wrap` is set to `wrap`. Let us know if this seems appropriate or if some other definition makes more sense?

**Comment by anjia** [comment]
Maybe the both `shape-outside` and glyph outline coexist could be better?

I think, for initial letter, if wrapping, most cases could be hoped to be wrapped by it's glyph outline
since this could perfectly fit the lines of the letter, which may be more difficult to achieve by using `shape-outside`.

By default, the initial letter use the glyph outline. And if website makers specify `shape-outside` property, then use the `shape-outside`.

**Comment by fantasai** [comment]
Yes, if `shape-outside` is `none` then we do the usual thing of using the glyph outline, of course. :) The question is whether it should key off of `initial-letter-wrap: wrap` or if `shape-outside` should always override even for other values of `initial-letter-wrap`.

**Comment by anjia** [comment]
Oh, yeah, I think I got the key point of this issue now. 

I prefer `shape-outside should always override ...`. Firstly, it's more simple to use, more easy to understand. Secondly, it's convenient to fallback. If it needs to specify the two properties like following. 
```css
initial-letter-wrap: wrap;
shape-outside: circle() /* or something else */
```
And assume that if `shape-outside` is invalid (due to either the wrong value or browser compat),
it would become difficult to let the other behaviors of `initial-letter-wrap` to be valid, because it had been used to set to wrap the value to make `shape-outside` to be valid.

**Comment by anjia** [comment]
> The question is whether it should key off of `initial-letter-wrap: wrap` or ...

@fantasai , I have a linguistic question to consult. What's the meaning of `key off of`?  :)

**Comment by astearns** [comment]
@anjia that's just another way of asking the same question about overrides. If `shape-outside` would key off of the value `wrap` then it would only apply when that value was set and not be used when other values of `initial-letter-wrap` were used.

I think it might be better to recast `initial-letter-wrap` to have `all` as the initial value, defined to have all lines wrap around the rectangular shape *or* shape-outside, if one is defined. Then the value of `first` could be to wrap all lines but the first around the rect *or* shape-outside, etc.

**Comment by fantasai** [comment]
*Sigh* I'm super confused. It *is* called `all`. Let me fix up the comments.

**Comment by fantasai** [comment]
@astearns Also, in your case, how would you get it to wrap around the glyph shape?? That's currently what `all` means.

**Comment by fantasai** [comment]
@anjia “key off” means “To take as a controlling input” according to wiktionary :) which is a very abstract way to define it. In this case it's setting a condition. I can't say I've ever really thought about the phrase too deeply, so I don't know how best to explain it. ^_^;;

**Comment by astearns** [comment]
My preference would be to define a value of `shape-outside` that created a shape out of the rendered content (it's an issue on css-shapes level 2, and a fairly often-requested addition). For the initial-letter case, this would be the ink bounds. I realize this would probably delay the feature, but I think it would be better than having two ways of wrapping around a character's ink (one as an initial-letter, another as a float)

**Comment by fantasai** [comment]
@astearns That's fine, but requiring authors to set `shape-outside` on an initial letter in order to get it to work at all seems unnecessary.

**Comment by astearns** [comment]
@fantasai I don't understand your last comment. You'd only need to use `shape-outside` in order to use a shape (including the ink bounds shape). The non-shaped rectangular behavior currently defined for `initial-letter` would happen if you left `shape-outside` alone.

**Comment by anjia** [comment]
@astearns  Eh! yeah, it was a typo, the related comments have been re-edited now.
the value `wrap` → `all`

**Comment by anjia** [comment]
If `shape-outside` could implement the similar effects to what `initial-letter-wrap` now does by adding some new rules or values, that would sound much better.

**Comment by astearns** [comment]
@anjia I'm not sure I agree - most of the effects of `initial-letter-wrap` are about readability in the `initial-letter` case (allowing the word to wrap closer to its initial letter). That's likely not very useful in the general `shape-outside` case.

**Comment by fantasai** [comment]
@astearns Afaict, you're proposing that for a typical drop-cap, we need to set `initial-letter-wrap: first` to get it to kern the first line into the rectangular space, and also set `shape-outside: special-initial-letter-behavior`. I think that's unnecessary. If someone needs a shape that's not the initial letter’s own shape, they can set `shape-outside`. Otherwise we should just use the shape of the initial letter as described in the spec.

**Comment by astearns** [comment]
Ah, no. Let me spell out my thinking. Currently, the `initial-letter-wrap` property allows you to:

`none` wrap all the lines around the rectangular margin box
`all` wrap around the ink, or a shape-outside if it's defined
`first` wrap the first line at the ink, then the rest at the rectangle
`grid` same as `none` but possibly increased to match a grid 

My thought was that since `shape-outside` is eventually going to have an `ink` or `rendered-content` value, we could make the `initial-letter-wrap` property more expressive and closer to the way floats currently work. So my definition would start with this:

Initial letter wrapping uses the margin box if `shape-outside` is `none`. Any other value of `shape-outside` causes initial letter wrapping to use the defined shape. Wrapping around the ink bounds is accomplished by using `shape-outside: rendered-content` (or whatever it ends up being named).

Then we recast the initial-letter-wrap values to use the definition above. 

With no `shape-outside`:

`all` (or `none` or `auto`) all lines wrap around the margin-box
`first` the first line wraps at the ink, and the rest at the margin-box
`grid` use the margin-box, increased to match a grid

With a `shape-outside`:

`all` (or `none` or `auto`) all lines wrap around the shape
`first` the first line wraps at the ink, and the rest at the shape
`grid` use the shape, increased to match a grid

So we can use `first` and `grid` with `shape-outside`, and you do not have to fiddle with your `initial-letter-wrap` value in order for `shape-outside` to be effective.

**Comment by astearns** [comment]
It's a little unclear in the minutes, but one drawback to my scheme above is that it does not allow an author to say, “wrap everything at the margin box, except for the first line that should wrap at my `shape-outside`-defined position”

**Comment by frivoal** [comment]
Right. And on the face of it, both variants of `first` seem reasonable.

**Comment by anjia** [comment]
Er, based on the discussions above, I have another idea to discuss.

Perhaps we could define the relationship between these two properties at first, `shape-outside` and `initial-letter-wrap`. The following is my opinion.

- `shape-outside` defines the external shape of the element as a whole
- `initial-letter-wrap` defines how to place the element in the specific context. And in this case the context is initial letter, then this property specially indicates how to handle its glyph outline.

About priority, of course, `initial-letter-wrap` priors to `shape-outside`, because it represents the specific context.

Then we recast the values of `shape-outside` and `initial-letter-wrap`.

#### Values of `shape-outside`
```css
shape-outside: none;

shape-outside: margin-box; /* by default */
shape-outside: content-box;
shape-outside: border-box;
shape-outside: padding-box;
/* these above xxx-box could represent the rectangular shape of the initial letter box */

/* new values */
shape-outside: rendered-content;  /* or whatever it ends up being named */
shape-outside: grid;  /* be same as https://drafts.csswg.org/css-inline/#valdef-initial-letter-wrap-grid  */

/* custom arbitrary shapes */
shape-outside: circle();
shape-outside: ellipse();
...
```

#### Values of `initial-letter-wrap`
```css
initial-letter-wrap: none;   /* by default, i.e. using rectangular box */
initial-letter-wrap: first;  /* the first line uses glyph outline */
initial-letter-wrap: non-first; /* the non-first lines use glyph outline */
```

#### Usage
e.g.
```css
/* 1. no setting the both, all lines wrap margin-box*/

/* 2. all lines wrap glyph outline */
shape-outside: rendered-content;  /* or some other name */

/* 3. first line wraps glyph and the others wrap margin-box */
initial-letter-wrap: first;

/* 4. first line wraps margin-box, and the others wrap glyph */
initial-letter-wrap: no-first;

/* 5. all lines wrap custom shape */
shape-outside: circle();

/* 6. first line wraps glyph and the others wrap custom shape */
shape-outside: circle();
initial-letter-wrap: first;
```

**Comment by fantasai** [comment]
@astearns We discussed the interaction of `shape-outside` and `initial-letter-wrap` last week in https://lists.w3.org/Archives/Public/www-style/2020Jun/0009.html as a consequence of https://github.com/w3c/csswg-drafts/issues/5117
Are you satisfied with the current definition, and can we close this issue, or is there something here you want to pursue?

**Comment by fantasai** [comment]
> The first paragraph talks about in bounds and the second paragraph talks about glyph shapes. 

@astearns I can't figure out which paragraph you're referring to, can you quote it?

@anjia The current draft has the behavior you outline in https://github.com/w3c/csswg-drafts/issues/885#issuecomment-397826202 except for two things:

- There's no `non-first` value for `initial-letter-wrap` since nobody has asked for it yet. :) (That should be a separate issue if you think it's needed.)
- If `shape-outside` is `none`, we use the glyph outline; no need to specify anything special for `shape-outside` to get `initial-letter-wrap` to this very common effect.

I think that should solve it for this issue. Let me know if there's anything that remains incomplete?

**Comment by astearns** [comment]
It's the two paragraphs in the definition for `initial-letter-wrap: all` - ink versus glyph outline. I assume they're the same thing, but it would probably be better to use glyph outline in both places.

> For each line of text impacted by the initial letter, the line box adjacent to the initial letter starts at the start-most point that touches the ink of the initial letter, plus the amount of the initial letter’s end-side border+padding+margin.

If the value of shape-outside is not none, shape-outside is used instead of the glyph outline. In both cases, shape-margin is applied to expand the outline.

**Comment by fantasai** [comment]
@astearns Gotcha. Fixed.
