### ISSUE TITLE
[css-color] Support using "inherit" in color-mix()

### ISSUE THREAD

**Issue by fabiospampinato** [w3c/csswg-drafts#8872]
[CSS Color 5](https://drafts.csswg.org/css-color-5/#color-mix) added the `color-mix` function, but it looks like it doesn't allow for mixing `inherit`. It'd be pretty powerful to enable support for that in some properties, so I think it should be added.

**Comment by fabiospampinato** [comment]
I'm thinking it would only work when it could work. 

So for example when using it with `border-color`, `color`, `background-color` etc. `inherit` would point to the value of that same property on the parent.

And it would simply not be supported for other arbitrary properties because it wouldn't make sense in that context.

**Comment by Loirooriol** [comment]
This can be covered by #2864 (but for now it may be restricted to custom properties).

Worth noting that `border-color` is a shorthand, so something like this seems safer:

```css
    border-top-color: color-mix(in oklab, inherit(border-top-color) 70%, black);
    border-right-color: color-mix(in oklab, inherit(border-right-color) 70%, black);
    border-bottom-color: color-mix(in oklab, inherit(border-bottom-color) 70%, black);
    border-left-color: color-mix(in oklab, inherit(border-left-color) 70%, black);
```

Doing the expansion automatically seems tricky. I guess the process would be like:
 1. Treat `inherit()` as a `<color>`
 2. Do longhand expansion normally
 3. Each longhand receiving `inherit()` resolves it to that same longhand (not the shorthand).

but what if the shorthand has longhands that don't compute to a `<color>`? Like

```css
    border: 5px solid color-mix(in oklab, inherit() 70%, black);
```

some longhands like `border-top-width` compute to a length instead of to a color. Of course using a length there wouldn't be valid syntax, but in general we could get ambiguous situations. So how do we know `inherit()` should be treated as a `<color>`?

**Comment by fabiospampinato** [comment]
Maybe `inherit` could return `transparent` in those cases? Like is there something better that it could do?

**Comment by svgeesus** [comment]
Indeed this seems like a better approach, as @Loirooriol suggested

 - https://github.com/w3c/csswg-drafts/issues/2864
