### ISSUE TITLE
[css-view-transitions-1] top/left vs block-start/inline-start

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8886]
https://www.w3.org/TR/css-view-transitions-1/#::view-transition-group

I'm wondering if the top/left rules shouldn't be inset-block-start/inset-inline-start?

**Comment by khushalsagar** [comment]
https://github.com/w3c/csswg-drafts/issues/8599 was meant to clarify this! There's some more background context on that issue.

The relevant part is that the group element is meant to position itself at the same position as the underlying DOM element using `transform`. We're using `transform` instead of `top`/`left` (or any other layout position properties) because we want the animation to be accelerated which can be done using `transform`.

CSS `transform` is always relative to the top left corner of the containing block. If I do `translateX(10px)`, the result is the same irrespective of what the `writing-mode` (or block/inline direction) is.

So UA CSS puts the layout position of the box to the top left corner with `top: 0; left: 0` and adds a `transform`. We could technically compute the `transform` in logical coordinate space and use inset-block-start/inset-inline-start but that seems backward? For example if the author adds an additive `transform` animation (because they want to create a bounce effect), that `transform` will also be physical coordinates.

**Comment by fantasai** [comment]
OK, I've been thinking about this... I *think* the right answer is to lay it out using block-start/inline-start, but transform it using physical coordinates (at least for now, since we don't have logical transforms). So if the author *turns off* the UA-provided transforms, the element is anchored to the start/start corner even on an RTL page.

Let me know if that makes sense or not. :)

**Comment by khushalsagar** [comment]
The awkwardness with this is because the `transform` property is in physical coordinates. The UA will have to convert the `transform` applied to the group from physical to logical coordinates which doesn't sound right.

The whole idea with the group pseudo is to position it in the viewport using `transform`, because it can be accelerated and the setup is for an ephemeral effect rather than proper positioning. Even if the author wants to override for a custom animation, they should still do it using `transform`. If they have a legit use-case that *needs* logical positioning for this animation, they can override `top`/`left` in favour of logical coordinates. Its the origin anyway so trivial to override to logical origin.

I would've been ok if we had logical transforms. Say in the future we do add logical transforms, using block-start/inline-start now still won't make it possible to switch to those because of compat. Authors can read the transform value computed by the UA, so we won't be able to change it from logical to physical coorindates.
