### ISSUE TITLE
[css-writing-modes][css-pseudo][css-inline] text-combine-upright, initial-letter and i18n quotation

### ISSUE THREAD

**Issue by realskk** [w3c/csswg-drafts#889]
This issue is forked from #653 .

```
p {
 writing-mode:vertical-rl;
  text-orientation: sideways;
  text-combine-upright: 2;
}
p::first-letter {
  initial-letter: 3;
 }
<p>"13" is a really nice number. Lorem Ipsum...</p>
```
When TCY includes quotation, and in case of the above code, what is the adequate rendering results?
The below two images are what I imagined. 

The example depicts ```text-orientation: sideways;```, but this question is applicable when the contents is vertical writing text, such as Japanese. 

Moreover, when quotations are 「」 or 「」, the position of these quotations might be different from "", or ''. 

![image](https://cloud.githubusercontent.com/assets/17156693/21866615/48b90266-d88e-11e6-8cd2-86e09fe8e590.png)

![image](https://cloud.githubusercontent.com/assets/17156693/21866620/4e6c67fc-d88e-11e6-8bf2-ad75338fa957.png)

**Comment by svgeesus** [comment]
@kojiishi @fantasai is this the same issue as [already-closed #653](https://github.com/w3c/csswg-drafts/issues/653#issuecomment-278147519) or does it represent a new request?

**Comment by frivoal** [comment]
@svgeesus It is forked from that, but distinct. @kojiishi asked for it to be reported separately: https://github.com/w3c/csswg-drafts/issues/653#issuecomment-270904941

**Comment by fantasai** [comment]
The resolutions/response in https://github.com/w3c/csswg-drafts/issues/653#issuecomment-278147519 apply here as well: there is no special interaction between any of initial-letter, :first-letter, or text-combine-upright, they all apply exactly as specified.

The end result in this case will be that the quotations are sideways, the 13 is upright, and the set as a whole is enlarged to span three lines of text. So, similar to the second rendering, but with larger quotation marks.

Closing as invalid, since there is no spec issue.
