### ISSUE TITLE
[css-view-transitions-1] Multiple elements with same view-transition-name

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8890]
What happens when multiple elements have the same view-transition-name value?

**Comment by khushalsagar** [comment]
The transition is aborted. Its step 8.3.1.6.5 [here](https://drafts.csswg.org/css-view-transitions-1/#capture-the-old-state) : "If usedTransitionNames [contains](https://infra.spec.whatwg.org/#list-contain) transitionName, then return failure." Same thing happens when we look for transition names in the new DOM.

The name has to match exactly 2 elements from the old and new DOM so it must be unique or the author made an error.

**Comment by khushalsagar** [comment]
Thanks for that link! You hit a very good con of the approach to tag every item in a list with a view-transition-name here: "I imagine this is fairly moot, but could also be similar to a “too many DOM nodes” performance and debugging issue."

There is a significant rendering overhead to adding `view-transition-name` on an element. The browser has to render it into a separate layer/buffer since the assumption is that it will be animated independently. But when you're going from a list to details page (or back), only one of the list items needs to animate independently. So a name on every single list item causes a lot of redundant rendering work.

The optimal way to do this is to add the name only to the list item the user clicked. This is trivial to do with script (using a `click` or `navigate` event handler) but we do want this to be possible declaratively. https://github.com/w3c/csswg-drafts/issues/8889 has our current thinking behind a declarative solution. The idea is to add navigation specific CSS so when the user is leaving the list page, you can add view-transition-names (or any other styles) depending on the destination URL. Would appreciate your feedback there! https://github.com/w3c/csswg-drafts/issues/8209 also has relevant discussion.

Coming back to this topic, the fundamental issue is that the browser needs `view-transition-name` to match 2 unique elements between the old/new DOM states respectively. We initially considered an approach similar to `querySelector`, if you find the name on multiple elements use the first one. But it ended up masking developer errors instead of selecting the element the author would've wanted. For your example, if you add the same name on every list item you don't actually want the browser to select the first item. It is better to surface the duplicate view-transition-names as an error to authors instead of guessing which one to pick.

**Comment by khushalsagar** [comment]
Sorry about the late reply and thanks for the clarification.

> it can remember from the interaction with which element from the set the transition occurred

It sounds like you want the UA to tie an interaction (like a click event) to an element and the transition to the interaction. This would basically allow conditionally adding a view-transition-name to one of the elements in the list, if that's the one the user interacted with. https://github.com/w3c/csswg-drafts/issues/8209 seems like a nicer way to do that, since it basically allows you to set any CSS (including view-transition-name). I noticed you +1'd the last comment there (thanks for taking the time to review the proposal). Given that, I'll close this issue but please feel free to re-open.
