### ISSUE TITLE
[css-view-transitions-1] Consider centralizing UA style rules

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8891]
The View Transitions spec has a lot of additions to the UA style sheet split across many sections. It's just a suggestion, but I wonder if it might be easier if these rules were all centralized into one section (after the definitions of all of the pseudo-elements so that we know what we're styling and how they relate).

**Comment by svgeesus** [comment]
I agree.

Related, I wonder if the snapshot should aggregate all the UA additions for the Official Definition specifications, for the same reason.

**Comment by fantasai** [comment]
@svgeesus Probably at that point we should make sure they're upstreamed to HTML etc.

**Comment by khushalsagar** [comment]
There's 2 types of UA style rules in this spec:

1. Static styles which are split across [User Agent Styles](https://drafts.csswg.org/css-view-transitions-1/#ua-styles) and [View Transition Pseudo Elements](https://drafts.csswg.org/css-view-transitions-1/#view-transition-pseudos). I don't have a strong preference between inlining the styles with the defining of each pseudo vs one section for all of them after the pseudos. How about moving the "User Agent styles" section after "Pseudo Elements" and adding all the static styles there?

2. Dynamic styles which are generated using layout info from each element and are Document scope. The stylesheet is defined [here](https://drafts.csswg.org/css-view-transitions-1/#document-view-transition-style-sheet) and the exact values are part of the algorithms which generate the styles. These should stay as-is since how the style values are generated is intertwined with these algorithms.

> Probably at that point we should make sure they're upstreamed to HTML etc.

I didn't follow this. The styles in this spec apply to all namespaces (not just html). This came up on https://github.com/w3c/csswg-drafts/issues/8573 with the conclusion that it makes sense for each CSS spec to define styles which apply to all namespaces.

**Comment by fantasai** [comment]
@khushalsagar I think I agree that the generated styles need to stay where they are, it seems that consolidating the global sheet (and noting at the end that there is a generated sheet as well) would be a good idea.

> Probably at that point we should make sure they're upstreamed to HTML etc.

I was referring to the HTML-specific styles. :) A lot of the UA rules we have in the CSS specs are currently just informative suggestions for HTML. The rules that apply to all namespaces (like those in View Transitions) should of course stay defined in CSS.
