### ISSUE TITLE
[css-fonts-5] Proposal: Animating font-palette

### ISSUE THREAD

**Issue by tursunova** [w3c/csswg-drafts#8922]
### Overview

We propose the animation of font-palette property. Currently [CSS Fonts 4 spec](https://drafts.csswg.org/css-fonts/#font-palette-prop) defines the animation behaviour of this property as discrete, which is insufficient to achieve a smooth transition between two selected palettes. 

For motivation, examples and more information, see [Explainer: Animating font-palette](https://docs.google.com/document/d/1XMTrKH003KBOes6hxzI-3E7LTwp5YwFC-rnzoFpFrfw/edit?usp=sharing).

### Proposal

The [font-palette property accepts](https://drafts.csswg.org/css-fonts/#font-palette-prop) either `@font-palette-values` identifier or keyword. Currently there are no [existing animation types](https://www.w3.org/TR/web-animations/#animation-type) to represent animation of font-palette property. For this we propose the following modifications to the font-palette property specification:

```
Value:		        normal | light | dark | <palette-identifier> | <palette-mix()>
Animation type: 	by mix value
```

### Animation type:   by mix value

Since there are no [existing animation types](https://www.w3.org/TR/web-animations/#animation-type) to represent the interpolated value of font-palette property at the specific time, we propose the animation type “by mix value”. For that, we introduce a new font-palette function `palette-mix()` to be accepted by the font-palette property. Function `palette-mix()` is used to represent the interpolated value of font-palette property during transition / animation progress. 

### Mixing Palettes: the ‘palette-mix()’ Function

This function, modeled after the [color-mix() function](https://drafts.csswg.org/css-color-5/#color-mix), takes two `<font-palette>` specifications and returns the result of mixing them, performing the interpolation in a given [\<color-interpolation-method\>](https://drafts.csswg.org/css-color-5/#color-interpolation-method), by a specified amount:

```
palette-mix() = palette-mix(<color-interpolation-method> , [ [normal | light | dark | <palette-identifier> | <palette-mix()>] && <percentage [0,100]>? ]#{2})
```

Percentages not adding up to 100% follow the  rules for [percentage normalization of the color-mix function](https://drafts.csswg.org/css-color-5/#color-mix-percent-norm).

### Palette interpolation
A font-palette property interpolates by interpolating each color from the palette the same way it is done for other color properties, [see section 12 Color Interpolation of ](https://drafts.csswg.org/css-color-4/#interpolation)CSS Color Level 4:

> “Interpolation between <color> values occurs by first converting them to a given color space which will be referred to as the interpolation color space below, and then linearly interpolating each component of the computed value of the color separately.”

But since there is no way for the user to specify which color spaces should be used for interpolation, so Oklab should be used as default interpolation color space for interpolating colors in the palette, [as recommend in section 12.1 Color Space for Interpolation of CSS Color Level 4](https://www.w3.org/TR/css-color-4/#interpolation:~:text=If%20the%20host%20syntax%20does%20not%20define%20what%20color%20space%20interpolation%20should%20take%20place%20in%2C%20it%20defaults%20to%20Oklab).

We propose font-palette to not be additive since it was [recently resolved](https://github.com/w3c/csswg-drafts/commit/327110f01b36c79c4d04f55d8fa30898e8d2cae0) that “The `<color>` type is not additive.”, compare [section 8.1.1. Combination of <color> of CSS Color Level 4](https://drafts.csswg.org/css-values-4/#combine-colors). That means in additive animations, animation-composition would always have a replacement behavior. For more information see [Explainer: Animating font-palette](https://docs.google.com/document/d/1XMTrKH003KBOes6hxzI-3E7LTwp5YwFC-rnzoFpFrfw/edit?usp=sharing) subsection “Combination of palettes”.

_Edited: added palette-mix() itself to grammar to account for nesting (e.g. during retargeting of transitions)_

**Comment by tabatkins** [comment]
I reviewed this proposal, and :+1: from me. In particular, I think it's appropriate to have a dedicated palette-mix() function rather than trying to rely on the generic mix() function, because palette-mix() lets you specify the color interpolation space. (It also lets you mix in transparency, like color-mix() does, but that's *probably* a lesser use-case.)

**Comment by svgeesus** [comment]
Overall this looks good; well thought out and compatible with other uses of color on the web platform.

Would like to hear comments and interest from the browser implementers.

**Comment by litherum** [comment]
Maybe this is naive, but why not slam in an @font-palette-values directly inside the @keyframes?

**Comment by fantasai** [comment]
@tabatkins wrt https://github.com/w3c/csswg-drafts/issues/8922#issuecomment-1579154428 makes sense, but also the generic mix() function should work and interpolate accordingly.

**Comment by drott** [comment]
> @tabatkins wrt [#8922 (comment)](https://github.com/w3c/csswg-drafts/issues/8922#issuecomment-1579154428) makes sense, but also the generic mix() function should work and interpolate accordingly.

The generic mix() function lacks an option to specify interpolation color space. So, similar to color-mix, we need something to specify that in order to improve interpolation quality. What's the direction and intention of your comment. Do you suggest to allow `mix()` and `palette-mix()` in parallel, where `mix()` would for example assume a default interpolation color space? (pending an agreement on what the canonical serialisation should be).
(On `mix()` for other color, similarly in Chrome we currently do not support the generic mix() function for color properties, compare test in https://codepen.io/tursunova/pen/mdQwYdq).

**Comment by tabatkins** [comment]
Yeah, `mix()` just represents the default interpolation behavior, identical to animating the property. I *think* @fantasai was just pointing out that mix() *also* will work for this purpose once we define interpolation behavior for 'font-palette'. (But I didn't imply that it wouldn't work, just that it wouldn't have the full suite of useful functionality we can expose with a dedicated function.)

(Do we actually support `mix()` at all? If we do, we should do our best to implement it in a generic fashion that works for every property, since it's just an invocation of a generic facility (animation) that works on every property. (Modulo the non-animatable properties, of course.) Having it implemented piecemeal is nearly as useless as not having it at all.)

**Comment by SebastianZ** [comment]
For what it's worth, I just had an idea for another approach to this. The idea is to expose the individual palette colors, so they can be animated separately, among other use cases.

Sebastian

**Comment by drott** [comment]
> I just had an idea for another approach to this in https://github.com/w3c/csswg-drafts/issues/9046 

I [commented there](https://github.com/w3c/csswg-drafts/issues/9046#issuecomment-1700975370) - in short, in my view this proposal creates redundancy between the proposed `font-palette-color` and the existing `font-palette` and lacks compatibility with the existing definition of `font-palette`.

**Comment by svgeesus** [comment]
Added in https://github.com/w3c/csswg-drafts/commit/54be250558f977bef772bd51a30bd5e6ef1350fa

**Comment by yisibl** [comment]
The current implementation in Chrome doesn't animate if from is omitted, which doesn't seem to be the same as other CSS properties, and I'd like to be able to animate when it's omitted.

```css
@keyframes palette {
  from {
   /* font-palette: normal; */
  }
  to {
    font-palette: --red;
  }
}
```

Demo: https://codepen.io/yisi/pen/wvRRORG?editors=0100

**Comment by drott** [comment]
> The current implementation in Chrome doesn't animate if from is omitted.

Thanks for the info, but in such cases please use the Chrome bug tracker for such reports - as this looks like an implementation specific issue, not a spec concern. I will file an issue.

**Comment by yisibl** [comment]
@drott Thanks for the clarification, I thought there was something special about the specification.

**Comment by drott** [comment]
Picking up the remaining:
> bikeshed on the issue about the interpolation color space

originating from @emilio's question on whether the specified `color-interpolation-method` is needed and going to be used.

At TPAC we discussed further with @emilio to describe the use-case that the gradient interpolation in COLRv1 fonts is in sRGB, and thus it is useful to specify the palette-mix interpolation also as sRGB for consistency, which I dare to paraphrase as sounding like a reasonable use-case to @emilio.

After helpful input from @svgeesus, @lilles, @andruud, @tursunova (thanks!),
I would like to add some more clarity on interpolation method/color space and distinguish two kinds of interpolation:
1) The _static_ computation and resolution into a palette of a `palette-mix()` with an interpolation method specified at a fixed point in time.
2) The specification of the color interpolation method during animation and transitions.


Here, we are discussing 1), and 2) is being discussed in #7741 and #7063.

So `palette-mix()` is not used for specifying the interpolation color space during animations and transitions, but is used to for example specify the color space to a) blend between two palettes as specified by a user, or b) represent a computed value that occurs during transitions or animations. 

In particular, when #7063 is resolved and a proposed `transition-interpolation:` property is added (which seems likely following that discussion), and more so if in the future something similar is added for animations, then we need a place to express what interpolation method between two palettes was used during a transition or animation. A computed `font-palette` value then necessarily needs a `<color-interpolation-method>` so that it is a closed form, correct representation of the blended palettes at a particular time during the transition/animation.

With that, I think we can conclude that the value is needed, and I'd be curious about your feedback, @emilio.
