### ISSUE TITLE
[css-anchor-1] Should `anchor-scroll` take overscroll into account?

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#8971]
See this demo: https://charistheo.github.io/html-popovers/

If we scroll to the bottom and overscroll, then the popovers are detached from their anchors

This is because the popovers are `position-fixed`, and are attached to the anchors with `anchor-scroll`. When the page is overscrolled, the overscroll offset isn't included into the snapshotted scroll offset, so the popovers don't overscroll with the rest of the page.

Should this be fixed?

**Comment by xiaochengh** [comment]
Hmm wait, is overscroll bouncing specified in CSS, or is it just UA-specific?

**Comment by tabatkins** [comment]
The *concept* of overscroll is specified in CSS <https://drafts.csswg.org/css-overscroll/>, but exactly what happens *when* you overscroll (aka what the "local boundary default action" is, to use the spec's term) is intentionally unspecified because platforms differ and don't want to standardize.

Impls should be consistent with their scrolling APIs, but we shouldn't (currently, at least) specify what that behavior is. So we should at minimum be consistent with whatever stickypos does in the impl, and ideally with what Scroll Animations does too. But I don't think we need to specify anything in this spec.

**Comment by tabatkins** [comment]
@flackr points out that <https://github.com/w3c/csswg-drafts/issues/6299#issuecomment-1076552713> is a resolution that stuck stickypos elements shouldn't rubberband with the scroller's contents (they should "stay stuck"). Chrome doesn't implement it yet, but when we do we should match up.
