### ISSUE TITLE
[css-counter-styles-3] fallback for cjk-earthly-branch and cjk-heavenly-stem

### ISSUE THREAD

**Issue by vitorroriz** [w3c/csswg-drafts#8975]
As it is being discussed in https://github.com/w3c/csswg-drafts/issues/8596, it seems the right system for these styles is `fixed`. With that, the `fallback` for them becomes more relevant, given they defined just a few `symbols` (10 and 12). The styles don't explicitly define a `fallback`, so it is `decimal`.

I have no knowledge on CJK languages, but I'm wondering if `decimal` is the best `fallback` for them. For example, other CJK related styles have `cjk-decimal` as `fallback`. So I'd like to discuss if this (or another style) would be a better fallback option here.

**Comment by xfq** [comment]
We [discussed](https://www.w3.org/2023/07/05-clreq-minutes.html#t02) this issue in the Chinese Layout Task Force Teleconference.

The consensus of the task force was that `cjk-decimal` is an improvement over `decimal`. `simp-chinese-informal` and `trad-chinese-informal` are even better, but since `cjk-earthly-branch` and `cjk-heavenly-stem` do not distinguish between Simplified and Traditional Chinese, we're OK with keeping it as is (`cjk-decimal`).

**Comment by vitorroriz** [comment]
@xfq we could create another issue for adding new styles, like: `cjk-earthly-brach-simp` and `cjk-earthly-branch-trad` each with a specific fallback.

**Comment by r12a** [comment]
These changes were added to the Ready-made Counter Styles doc editor's draft.
