### ISSUE TITLE
[CSS2] Nobody follows the spec that clearance should prevent margin collapse

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#8977]
https://drafts.csswg.org/css2/#adjoining-margins

> Two margins are adjoining if and only if: [...]
> - no line boxes, **no clearance**, no padding and no border separate them

However, Firefox, Chromium and WebKit collapse in this case:

```html
<!DOCTYPE html>
aaaa
<div style="margin: 50px 0">
  <div style="clear: both"></div>
</div>
bbbb
```

Not sure if I'm missing something, but should the condition be dropped?

**Comment by bfgeek** [comment]
I wouldn't look to this part of the spec for too much guidance for implementing margin-collapsing + floats, but this likely should say *applied* clearance.

**Comment by fantasai** [comment]
Roughly what @bfgeek said: clearance refers to the excess spacing introduced by `clear` in order to clear a float, not having `clear` set to a non-`none` value. See https://www.w3.org/TR/CSS2/visuren.html#clearance

> I wouldn't look to this part of the spec for too much guidance

There isn't any other spec for it? We should fix any problems that actually exist here, but it's the most correct spec we have...

**Comment by fantasai** [comment]
Close out if you're satisfied @Loirooriol ; or reply if you think there's still something to fix.

**Comment by Loirooriol** [comment]
OK thanks, I guess this is the relevant quote:

> If this hypothetical position of the element's top border edge is not past the relevant floats, then clearance is introduced

(implying that there is no clearance if there is no float or the hypothetical pos is past the floats)
