### ISSUE TITLE
[css-position-3] Incorrect value definitions for `inset-*` shorthands

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#8986]
The value of `inset-block` and `inset-inline` is defined as `<top>{1,2}`, and that of `inset` is `<top>{1,4}`.

These should be `<'top'>{1,2}` and `<'top'>{1,4}` instead.

**Comment by cdoublev** [comment]
I think `inset` is a shorthand for the four corresponding physical properties, as noted below its definition table:

  > By default, the `inset` property values are assigned to the corresponding physical longhand properties — `top`, `right`, `bottom`, and `left` [...]

I proposed in #6894 to add `Canonical order` in shorthand definition tables, in order to bind them with their longhands (which can be useful to CSS tool libraries like `w3c/webref`) and define their canonical order, but it did not get much traction (and `all` would be problematic).

**Comment by fantasai** [comment]
Fixed by @cdoublev in 743af48588 nine months ago, marking this closed. :)
