### ISSUE TITLE
[css-color-5] Only `hsl` and `hwb` have channel values as percentages in RCS

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#9016]
I was going over the list of changes in `css-color-5` and I noticed that only `hsl` and `hwb` have channel keywords in RCS that have percentage values.

Both however also allow number values as regular arguments.  
In `css-color-5` these are both valid and equal :
- `hwb(90deg 25% 25%)`
- `hwb(90deg 25 25)`

@svgeesus is there a reason not to give the channel keywords the number type?
That would make these two color functions more consistent with every other color function.

- https://drafts.csswg.org/css-color-5/#relative-HSL
- https://drafts.csswg.org/css-color-5/#relative-HWB

**Comment by svgeesus** [comment]
No, it looks like just a failure on my part to update all affected parts of the spec. [This edit](https://github.com/w3c/csswg-drafts/commit/4f09d0500a5fe768c4fadd032942b220d017a105) changed 

`They are <<number>>s or <<percentage>>s`

to

`They are <<number>>s`

but only for relative `color()` not for other color functions.

You are right that `hsl()` and `hwb()` [were changed to always allow number or percentage](https://github.com/w3c/csswg-drafts/commit/b5fdc892cc1cf10e2b6484eb10e93ed1e9aa7dca), and the [CSS WG resolution](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1379264467) was that channel keywords should resolve to `<number>`. 

* RESOLVED: keywords with multiple specified types result in number

@tabatkins had [pointed out that channel keywords were still using percentage for HWB](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1379197254), and I [stated that this was correct](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1379222327) because that predated the resolution (which was [made on the call that same day](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1379264467)).

And the spec was even changed elsewhere to refer to these being number for HSL and HWB, see [this edit[(https://github.com/w3c/csswg-drafts/commit/9f319804bf6ac8fec705978acedec44cac961266), as part of https://github.com/w3c/csswg-drafts/issues/8322.

So I should fix that, for consistency. Thanks for your careful review!

**Comment by svgeesus** [comment]
Also from the [intro to RCS](https://drafts.csswg.org/css-color-5/#relative-colors);

> The [channel keywords](https://drafts.csswg.org/css-color-5/#channel-keyword) return a [`<number>`](https://drafts.csswg.org/css-values-4/#number-value); if they were originally specified as a [`<percentage>`](https://drafts.csswg.org/css-values-4/#percentage-value) or an [`<angle>`](https://drafts.csswg.org/css-values-4/#angle-value), that `<percentage>` is resolved to a `<number>` and the `<angle>` is resolved to a `<number>` of degrees (which is the [canonical unit](https://drafts.csswg.org/css-values-4/#canonical-unit)) in the range [0, 360].

**Comment by svgeesus** [comment]
Relevant tests to check:

 - [parsing/color-valid-relative-color.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid-relative-color.html)
 - [parsing/color-invalid-relative-color.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-invalid-relative-color.html)
 
Add subtests with calc(), to check correct types used,  on:

 - HSL hue
 - HSL L and S
 - HWB hue
 - HWB W and B
 - LCH hue
 - Oklch hue

**Comment by romainmenke** [comment]
One more :)
https://github.com/w3c/csswg-drafts/blob/70622d07191bfbfc15229c2636a2ec7736510cea/css-color-5/Overview.bs#L1417

**Comment by svgeesus** [comment]
Thanks!

**Comment by romainmenke** [comment]
Thank you for these edits and clarifications 🙇

**Comment by svgeesus** [comment]
_(Leaving the issue open so I don't forget about the need for testcase review and supplementation)_

**Comment by romainmenke** [comment]
I've added a few tests that should also cover this issue : https://github.com/web-platform-tests/wpt/pull/43931

**Comment by svgeesus** [comment]
The spec is now correct and the tests are updated, so I believe this can be closed.
