### ISSUE TITLE
[css-color] lab and lch color spaces should use the D65 illuminant commonly used for digital media (not D50)

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [w3c/csswg-drafts#9061]
Lab and Lch color spaces should use Illuminant D65; not D50. The D50 illuminant is more commonly used in real-wrold/physical applications like "car paint" while D65 is used for digital displays.

See:
<img width="635" alt="image" src="https://github.com/w3c/csswg-drafts/assets/11559173/1d207f27-cbb0-47b1-9cc2-662b2e98bbcb">
https://en.wikipedia.org/wiki/Standard_illuminant#White_points_of_standard_illuminants

Link to CSS spec:
https://drafts.csswg.org/css-color/#lab-colors

**Comment by svgeesus** [comment]
You are correct that D50 is typically used for physical measurements, like reading a surface color with a spectrophotometer. Also, as you note, in ICC profile processing, where Lab is the profile connection space. 

Which is why it was chosen: for compatibility with industry usage. This was not an error.

Oklab, which improves on CIE Lab in many ways, uses D65.
