### ISSUE TITLE
[css-text-4] Should `text-wrap: balance` apply separate logic before and after forced breaks?

### ISSUE THREAD

**Issue by RWDavid** [w3c/csswg-drafts#9112]
Relevant spec: https://drafts.csswg.org/css-text-4/#valdef-text-wrap-balance

Currently, `text-wrap: balance` applies to the line boxes of an inline formatting context.

> Line boxes are balanced when the standard deviation from the average [inline-size](https://drafts.csswg.org/css-writing-modes-4/#inline-size) of the remaining space in each line box is reduced over the block (including lines that end in a forced break).

However, it is unclear whether inline content broken apart by a `<br>` should cause `text-wrap: balance` to treat them as two separate 'units' to be balanced. For example, given the following code snippet:
```
<style>
div {
    width: 20em;
    text-wrap: balance;
}
</style>

<div>
    Paragraph A: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  <br>
    Paragraph B: Feugiat in fermentum posuere urna nec tincidunt praesent. Porttitor lacus luctus accumsan tortor posuere ac ut. Aliquet porttitor lacus luctus accumsan tortor. Nibh sed pulvinar.
</div>
```
Should the browser attempt to balance Paragraphs A and B individually (with the goal of reducing variance of line lengths within each paragraph) or together (with the goal of reducing overall line length variance)?

I did some investigation into some text-balancing algorithms, and it's worth noting that some algorithms will produce virtually identical line-breaking decisions regardless of balancing them together or separately. For example, if you define a cost function to be $f(w) = (w - \overline{w})^2$, where $w$ is a candidate line width and $\overline{w}$ is the ideal/average line width, then minimizing this cost function across all lines will result in identical line-breaking decisions. This cost function also models variance pretty well.

However, for other text-balancing algorithms, applying them on individual paragraphs delimited by forced breaks can result in different line breaking decisions, so I think it's worth trying to clarify this now.

**Comment by frivoal** [comment]
@astearns @fantasai @litherum @jfkthame what do you think?

**Comment by frivoal** [comment]
Since "lines" is plural in this part of the spec,

> (including lines that end in a forced break)

I think the intended meaning is that you balance the whole block as one thing, across forced line breaks. Otherwise, for each sub-block, you'd only be taking into account one "line that ends in a forced break" at a time.

But I don't think it would hurt to be explicit if that is what we mean.

On the other hand, if the difference in layout is minimal in most cases, maybe it's worth defining it the other way around, or at least allowing UAs to treat each sub-block separately, as that should have better performance characteristics.

**Comment by kojiishi** [comment]
+1 to @jfkthame.

**Comment by frivoal** [comment]
I'm not sure it would make that much of a difference, or maybe none at all. Since `balance` is not allowed to change the number of lines, only where they wrap. Even in the presence of forcibly short lines, this will not result in a bunch of short lines.

How much it actually matters might depend on the exact definition we give to what it means to balance (see https://github.com/w3c/csswg-drafts/issues/9111), but I'm starting to think it's probably not that relevant, ant that we might want to go with whatever is simplest to do.

**Comment by kojiishi** [comment]
From the performance point of view, though the algorithm is not defined, the algorithm is likely O(n), O(n!), or O(n^2) for the n lines of the "paragraph". It'll perform better if the "paragraph" has less lines.
