### ISSUE TITLE
[css-transforms-2] Explicitly specify that a transform is a containing block for all descendants

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#913]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=16328

Comment:  https://www.w3.org/Bugs/Public/show_bug.cgi?id=16328
Comment:  http://www.w3.org/mid/514E058C.5060105@exyr.org

Also
Comment: https://www.w3.org/mid/24BE3FE7-60C9-4690-A01C-F2291460DE7F@adobe.com
Comment:  https://www.w3.org/mid/20151125002414.GA22745@pescadero.dbaron.org

**Comment by mikemcguire** [comment]
WOAH! moving issues to github, +1 for that and +1 for resolving this issue

**Comment by tomasdev** [comment]
Are there any plans on fixing this?

http://jsbin.com/jazuwus/edit?html,css,output

**Comment by asiljan** [comment]
+1

**Comment by chrishtr** [comment]
Is this issue removing transform as a containing block for fixed-position elements? I don't think
that is a good idea, as it:
* makes clipping and filter effects hard to define and implement, and in general ill-defined because
it's impossible to "filter" across multiple 2d planes.
* introduces difficult and complex code to implement compositing
* makes it hard to provide clean fast paths for transforms

**Comment by mikemcguire** [comment]
Im not going to pretend to understand the difficulties in implementing the client code cause I'm completely unqualified. But want to put my two cents in. When I ran into this issue I sat stumped forever. While this issue is now well documented on the web, it took me forever to actually figure out that the transform is what was causing the issue and thus being able to find the chrome bug filed and eventually the original Bugzilla spec bug to request an update. 

It seems counter-intuitive to not update the spec with what seems to be a universal expectation to accommodate the Chrome team. Especially since other browsers are accommodating what seems to be universally expected.

Additionally, while the spec for positioned elements outlines this issue, I find it difficult to understand the language used in the spec. Front-end devs could potentially waste a lot of time looking for a fix, and possibly explains a lack of interest for this issue. I personally find that the transforms spec more clearly outlines the behavior than the positioning spec.

**Comment by RByers** [comment]
I believe #1945 tracks doing exactly that - updating the spec to match Chrome's behavior.  Is that right @chrishtr @smfr?  Should we merge these issues somehow to reflect the current thinking?

**Comment by RByers** [comment]
I verified that Firefox, Edge (14 and 16), Chrome and Safari all behave the same here.  Only IE appears not to create a containing block for a transform.  So definitely we just need to update the spec and web-platform-tests for this.

For the record, [here's the relevant chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=20574).

**Comment by tegtmeier** [comment]
+1

**Comment by chasebank** [comment]
Is there a separate issue to clarify the behavior of fixed positioning?

Because if I'm reading this right, it doesn't quite cover that concern.

**Comment by HandsomeMedia** [comment]
Possible workaround: use `position:sticky` instead (tested in Chrome).  
And expanding on that - why would `position:sticky` behave as expected and `fixed` not?  Seems like both should behave similarly...

**Comment by fantasai** [comment]
@HandsomeMedia Technically, `position: sticky` is more similar to `position: relative` than `position: fixed`.

**Comment by zixia** [comment]
+1

**Comment by matthew-dean** [comment]
> Is this issue removing transform as a containing block for fixed-position elements? I don't think
that is a good idea, as it:

> makes clipping and filter effects hard to define and implement, and in general ill-defined because
> it's impossible to "filter" across multiple 2d planes.
> introduces difficult and complex code to implement compositing
> makes it hard to provide clean fast paths for transforms

None of the "implementation is really difficult" seems relevant in terms of what makes sense in consistency of the language. `position: fixed` should always maintain that element in relation to the viewport. Setting a transform should not make it "steal" a fixed-positioned element from the viewport and inject it into its own context as if it's `position: absolute`. Algorithmically, you should still be able to scale/translate/rotate a fixed-positioned element based on it's original "viewport" position without changing what its height/width/top/left values initially mean.

**Comment by koko236** [comment]
This is nonsense. Is there any reliable explanation of why is this implemented the way it is beside assumptions? With the spread of CSS transforms `position: fixed` becomes completely unreliable and writing in any current spec or guide that `fixed` has anything to do with the viewport is simply misleading. 

What makes me go crazy is that it's an issue from 2012 or earlier and you still read about viewport e.g. in Mozilla Web Docs:

> The element is removed from the normal document flow; no space is created for the element in the page layout. Instead, it is positioned relative to the screen's viewport and doesn't move when scrolled.

Then later it's casually added that:

> When an ancestor has the transform, perspective, or filter property set to something other than none, that ancestor is used as the container instead of the viewport

As this breaks probably each reasonable use case for `fixed` I'd put much more emphasis on it and mark clearly `fixed` as half broken.

**Comment by jonjohnjohnson** [comment]
In all honesty, better terminology needs to be created for how a `fixed` positioned elements containing block is defined, beyond just `transform`...

- Firefox and blink are also affected by `perspective` not set to `none`, which makes sense in line with `transform`.
- Firefox is affected by `filter` not set to `none`, making a leap from just informing the stacking context or isolation.
- Safari (desktop) only uses `transform` not set to `none`, yet `perspective` not set to `none` will still create a stacking context and there is no mention of this in the spec.
- Not as intimate with or sure of how Edge relates to this?

I understand that moving relationships of elements around different representations of the tree isn't easy and this issue isn't about removing `transform` affecting `fixed` (has anyone else seen iOS Safari juttering `fixed` elements when they are nested inside `-webkit-overflow-scrolling: touch`?), but there are serious compatibility issues that should be ironed out or at least...

...documented within [css-position](https://drafts.csswg.org/css-position-3/#fixed-pos).

**Comment by dirkschulze** [comment]
@smfr transforms 1 still has an issue referencing this one. Is it still relevant for level 1? https://drafts.csswg.org/css-transforms/#issue-4e97f62c
