### ISSUE TITLE
[css-anchor-position-1] Define interaction with the cascade in `@position-try`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9149]
The spec does not seem to define the interaction of property declarations with the cascade in `@try`, as required by [CSS Syntax](https://drafts.csswg.org/css-syntax-3/#block-contents):

  > If any declarations are valid, and are property declarations, it must define whether they interact with the cascade; if they do, it must define their specificity and how they use `!important`.

Sorry, I am not very familar with the CSS Anchor Position spec yet, but I guess they interact like declarations in keyframe rules (`!important` is invalid), right?

**Comment by fantasai** [comment]
Fwiw, I think they should go in the Animation Origin, prior to actual animations. I think the spec currently implies that they win over everything. (This is what I suggested for the analogous `@position-area` proposal option presented at the F2F.)

**Comment by xiaochengh** [comment]
> I think the spec currently implies that they win over everything

This is also my understanding of the spec, and what the Chromium implementation is doing.

> ...which imho is not great.

Agreed it's not great, but it would be very hard to change.

The main difficulty is that we need to run layout to decide which fallback position to apply, at which time the cascade is already finished. That's why everything is done at used value time.

It would be really great if we can resolve fallback postion at computed value time, which not only prevents overwriting e.g. `!important` UA style, but also supports [smooth transitions between fallback positions](https://github.com/w3c/csswg-drafts/issues/8372).

**Comment by fantasai** [comment]
Copying over comment from #9331: 

> Reading through the issues, apparently rules in the `@try` blocks apply “at used value time”, which means they don't fit into the cascade _at all_&mdash;even `!important` rules won't apply.
> 
> This is problematic to begin with, and it becomes more problematic the more properties you allow in `@try`.

Relates also to https://github.com/w3c/csswg-drafts/issues/9332

**Comment by xiaochengh** [comment]
Also copying from #9331:

> But preventing them from overriding `!important` style should be implementable, and I agree that should be probably be done now for sanity.

**Comment by xiaochengh** [comment]
In the last meeting we mentioned another sub-issue, which is the behavior of `revert` in `@try`.

This won't be an issue if `@try` rules can properly cascade, but right now they don't. I suppose the only choice for now is to disallow `revert` until we figure out how to make `@try` rules cascade.

**Comment by andruud** [comment]
> Fwiw, I think they should go in the Animation Origin, prior to actual animations.

That position in the cascade makes sense to me, but maybe can add a new "Position Fallback Origin" there instead of claiming they're animations. (Like animations, it could be considered part of the author origin for the purposes of `revert`).

**Comment by andruud** [comment]
The spec says this at the moment:

> These modified styles are applied to the element via interleaving, so they affect computed values (and can trigger transitions/etc) even tho they depend on layout and used values. They are applied as part of the **author origin, as part of a theoretical UA-controlled final cascade layer.**

This works, I think, but it would be good to clarify whether it's intended to be weaker or stronger than [element attached styles](https://drafts.csswg.org/css-cascade-5/#style-attr). As written currently, it could be interpreted to mean _weaker_, since it's described as a [layer](https://drafts.csswg.org/css-cascade-5/#cascade-layering).

**Comment by tabatkins** [comment]
Hmmmmm yeah, I wrote it as a layer because that's how you referred to it when we were discussing it. ^_^  But yes, element-attached styles should be weaker. (You should be able to style an element from `style=""`, including a position-try-options that uses flip-* keywords, and have it work.)

So I think specifying it as a cascade origin (between author and animation) is indeed the right thing.

**Comment by tabatkins** [comment]
K, specified as a new origin now. We should move the definition fo the origin to Cascade so we're not monkey-patching the origin list, tho.

We also need to define the behavior of `revert`, as @xiaochengh pointed out in <https://github.com/w3c/csswg-drafts/issues/9149#issuecomment-1730463108>. I'm inclined to either (a) say that `revert` isn't allowed, or (b) have it revert to the user origin, similar to how it works in animations.

**Comment by andruud** [comment]
OK. That also works.

> revert isn't allowed

Now that we have functioning cascade interaction due to interleaving, there's no _technical_ reason to ban reverts. I'd just go for (b).
