### ISSUE TITLE
[css-view-transitions-2] Abort transition if the navigation takes too long

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#9155]
This came up on the [TAG review](https://github.com/w3ctag/design-reviews/issues/851#issuecomment-1663075082). If the navigation is taking longer than a certain threshold, it's better to just show the new content directly instead of running an animation. The exact time can be left to the UA.

**Comment by vmpstr** [comment]
If it's possible, I'd like to generalize this to allow the UA to skip the transition if it decides that the transition effect would contribute to a worse user experience rather than skipping it.

I think we can provide guidance, such as some timeout, but there may be other situations where the transition might not make sense. For example, if for whatever reason the UA clears the visual buffer of the previous page, but the new page hasn't loaded yet, then it might not make sense to do a transition.

**Comment by khushalsagar** [comment]
Yeah, there are other cases where skipping makes sense. I'd prefer for the spec to list out the conditions where the UA is advised to skip instead of a generic, "if you think it would contribute to a worse user experience". For example, https://github.com/w3c/csswg-drafts/issues/8953 says that the UA should skip if its doing its own transition. Feel free to file issues for any other cases you have in mind.

> if for whatever reason the UA clears the visual buffer of the previous page, but the new page hasn't loaded yet, then it might not make sense to do a transition.

When would this happen?

**Comment by vmpstr** [comment]
> When would this happen?

Correct me if I'm wrong, but I don't think the spec (html or css) is opinionated whether the visual buffer has to remain uncleared for any duration. This is the reason why I think listing out explicit condition when the UA is advised to skip the transition is insufficient, since it would imply that other situations have to have a transition. I don't think we'd be able to list all possible situations because at least some would be implementation dependent

**Comment by fantasai** [comment]
@khushalsagar Might want to treat that as a transition from a blank/unknown URL rather than blocking the transition entirely. I think it's a bit of a separate question from whether it's taking too long to load the page.

**Comment by khushalsagar** [comment]
> Might want to treat that as a transition from a blank/unknown URL rather than blocking the transition entirely. I think it's a bit of a separate question from whether it's taking too long to load the page.

There's a couple of cases for slow loads where we might want a different strategy:

- The server took too long to respond. In these cases we leave the current Document interactive, because the server response might cancel the navigation (like a 204). In the meantime the user can still interact with the page or hit the stop button.
   
   I don't know if we want to start the timer for "slow load" until we have a server response. The fact that the current page is interactive/animating makes me think not. But I might be biased because I want more transitions. ^_^

- The server has responded, we've unloaded the old Document and the visual buffer is showing last paint of old content until the new Document is ready. So there are no animations in the page content and user input doesn't work. At some point the browser has to clear the visual buffer (so the user understands that the new page is loading).
   
    This scenario lines up with your thinking of: "I think it's a bit of a separate question from whether it's taking too long to load the page". It's conceptually similar to the problem in https://github.com/w3c/csswg-drafts/issues/8791 perhaps. If we don't have any state from the old Document then its basically the new Document doing a bunch of entry animations on a blank tab.

**Comment by vmpstr** [comment]
I suspect going into detail about every possible situations where a transition should be skipped might imply that all other situations must have a transition, and that may not be possible now or in the future, depending on the situation.

A simple example is something like a UA defined transition on regular navigation. AFAIK, no major browser has this type of a transition, and it's not in the spec, but requiring a view transition in this case might be wrong if some browser does implement a default transition and runs it instead of the view transition.

So the carve out I'm suggesting is to say that ultimately the choice whether to run the transition is up to the UA. It should make all effort to do so, but in situations that doing such a transition will certainly result in a worse user experience, it should skip it.

Or do you believe that we should make the effort in the spec to outline every situations in which a transition must be skipped?

**Comment by khushalsagar** [comment]
> So the carve out I'm suggesting is to say that ultimately the choice whether to run the transition is up to the UA. It should make all effort to do so, but in situations that doing such a transition will certainly result in a worse user experience, it should skip it.

I'm just not sure how vague we want to leave this. For example, I like the resolution we had on https://github.com/w3c/csswg-drafts/issues/8953. It clearly states that UAs can abort the view transition if they provided their own transition, but doesn't specify in what cases UAs can do their own transition.

I'd be ok with the wording you mentioned as well, would prefer that we at least document the conditions for aborting as we find them. As non-normative recommendations for implementors and to ensure reasonable interop.
