### ISSUE TITLE
[css-anchor-position] Does fallback affect the computed style?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#9229]
https://drafts.csswg.org/css-anchor-position-1/#fallback-rule is pretty vague on how fallback applies.

Should the fallback be observable from `getComputedStyle()`? What about `computedStyleMap`?

Presumably insets/margins should since those return the used values from `getComputedStyle`, but others properties won't?

**Comment by xiaochengh** [comment]
I think these are already clear in the current specs.

https://drafts.csswg.org/css-anchor-position-1/#fallback-apply: 

> When an element uses a [position fallback list](https://drafts.csswg.org/css-anchor-position-1/#position-fallback-list), it selects one entry from the list as defined below, and applies those properties to itself as [used values](https://drafts.csswg.org/css-cascade-5/#used-value)."

So they are applied at used value time (during layout), and do not affect the computed values.

> Should the fallback be observable from `getComputedStyle()`? 

Yes, because `getComputedStyle()` returns used values for [some properties](https://drafts.csswg.org/cssom/#resolved-values).

> What about `computedStyleMap`?

No, because `computedStyleMap` holds computed values only.

---

Note: this is just how it currently works, but ideally, we would still like fallback declarations to be applied at computed value time, so that smooth transitioning between fallback positions can be possible. See #8372

**Comment by emilio** [comment]
Ok, that matches my intuition on how it should be spec'd, great :)

I think I just didn't realize that was properly defined further down. Maybe https://drafts.csswg.org/css-anchor-position-1/#fallback-rule should somehow link to that section?

**Comment by xiaochengh** [comment]
I assume this issue is purely editorial then?

**Comment by emilio** [comment]
Yes

**Comment by tabatkins** [comment]
This should be well specified now.
