### ISSUE TITLE
[css-transforms] Smarter interpolation of truncated transform lists

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#927]
https://www.w3.org/mid/CALXxKfCKZd+P0mH2oFyDkBgps56WqwQnLSMpKk1nrqiFXScqVA@mail.gmail.com
https://www.w3.org/mid/CAAWBYDBPafEbiXNy=Mw4a9w1jmvK6dUJzq28PPjN7APgtjqAEw@mail.gmail.com

Need to decide what goes into Level 1, and what to call the new identify functions. Related to https://github.com/w3c/csswg-drafts/issues/898

**Comment by alancutter** [comment]
This seems to be the key suggestion from the linked thread.
> I wonder if we could take this a bit further - rather than just
removing identical prefixes (where both the functions and arguments
match), we could find the prefix that just has functions matching,
with potentially different arguments.  Then we can interpolate that
common prefix normally, and run the rest of the two states back
through the list again as you describe, either matching the remainder
up with identity transforms or mashing the remainder up into a matrix.

My interpretation of this is that `translateX(100px) scaleX(2) rotateX(90deg)` interpolating with `translateY(100px) scaleY(2) rotateY(90deg)` would use pairwise function interpolation for `translate` and `scale` and use post multiplied matrix interpolation for `rotate`.

**Comment by smfr** [comment]
Propose moving to level 2.

**Comment by smfr** [comment]
That resolution wording is obtuse, but I think means that we resolved to make the behavior change in transforms-1.

**Comment by birtles** [comment]
We started implementing this in Firefox but I'm a little unclear about the intention of this change. In the IRC log I see the comment:

> smfr: it's saying that it uses the common prefix for as much as possible, then smoosh together the rest into a matrix

but in the spec change we seem to only handle mismatched lists where the functions of the shorter one match primitives of the longer.

i.e. it seemed like we were initially looking at allowing `rotate(0deg) translate(10px)` → `rotate(720deg) scale(2)`  to interpolate the `rotate()` component directly and then use matrix interpolation for the remainder but the spec change would make the whole thing use matrix interpolation.

It may well be that the spec change deliberately doesn't allow the "common prefix" behavior due to compatibility concerns but I'd like to confirm we've understood the intention here since it's not clear to me from the IRC log what the outcome was.

**Comment by dirkschulze** [comment]
@birtles From the proposal and the discussion, the spec change does not fully support the requested "smoosh". According to the discussion above this could either be by:
* multiplying all not matching functions to a matrix and interpolate the others.
* adding neutral transform functions where needed.

Both do not sound ideal to me. The latter mostly because we need to define an algorithm where and when to add neutral transformations. At the first glance this might sound intuitive but really isn't.

I wasn't in the discussion but what @smfr added seems to be logical and matching the behavior of other CSS properties:
* Fill up the shorter list with matching, neutral transform functions.
* (Special requirement: only if the transforms are otherwise compatible.)

**Comment by birtles** [comment]
Yeah, it seems to be reasonable. I just wanted to check if the spec change was intentionally different from what the discussion seemed to conclude.

**Comment by tabatkins** [comment]
My interpretation of the discussion was that *both* of Dirk's suggestions should be used:

* If one list is shorter than the other, pad it with identify functions to match lengths.
* Then do a compatible-prefix match, "smooshing" the incompatible suffix (if any) of each into a `matrix()` or `matrix3d()` and transitioning appropriately.

So @birtles' example should work as they expect - `rotate(0deg) translate(10px)` → `rotate(720deg) scale(2)` will do two full rotations (as `rotate()` is the compatible prefix) and then do a matrix-interpolation between `translate(10px)` and `scale(2)`.

**Comment by dirkschulze** [comment]
@tabatkins Yes, phrased it wrong. I am just suspicious about
> * adding neutral transform functions where needed.

Where should missing/differing functions be added?

Simple example:
`rotate(720deg)` → `translate(100px, 100px)`
A translate needs to get added to the former and a rotate to the latter transform function list. But in which order? After all the order matters a lot from the visual perspective.
* We could say that we follow the TRS schema proposed for the `translate`, `rotate` and `scale` properties in Level 2. So translate has precedence over rotate which has precedence over scale. This potentially doubles the number of transform functions if they all differ.
* We could provide an algorithm that adds a transform function to the shorter list. Going from left to right: If 2 transform functions between the 2 lists differ, add the neutral pendant at the same spot to the shorter list. We would still need to decide what the precedence is if the transform function lists have the _same number_ of transform functions.

Potentially both algorithms would replace matrix decomposition for the majority of cases.
However, quite often there would be a solution that could have been smarter from a human eye perspective but wasn't used. Sometimes, even the first solution does not give the most pleasant result.

The complex algorithm needs to get implemented in an interoperable way in all UAs as well. Given how long even smaller changes in the spec took, it might be a while and I expect that we will see some additional feedback from UAs after implementing.

**Comment by tabatkins** [comment]
Like I just outlined, you fix *length* mismatches by adding neutral transforms to the end of the shorter list.

In your example, no fixup is possible. They're the same length, and have no common prefix, so you still just go straight to matrix interpolation.

**Comment by dirkschulze** [comment]
@tabatkins Oh got it. The common [transform function primitive](https://drafts.csswg.org/css-transforms/#transform-primitives) is there already and [adding neutral transform functions at the end of the list](https://drafts.csswg.org/css-transforms/#transform-transform-neutral-extend-animation) was added recently.

The proposal in https://github.com/w3c/csswg-drafts/issues/927#issue-200763204 and the question from @birtles https://github.com/w3c/csswg-drafts/issues/927#issuecomment-392390666 goes adds an additional step:

If there is a mismatch between 2 transform function pairs (no common primitive): Instead of multiplying all transform functions into one matrix before decomposing the suggestion is to do the matrix interpolation part only between not matching transform function pairs.

An additional question I have for that proposal: `rotate(180deg) translate(120px) scale(2)` -> `rotate(180deg) scale(2) skewX(45deg)`. According to the proposal, `rotate` uses  normal interpolation for rotate:
* Would the 2nd and 3rd transform functions get multiplied first before the matrix interpolation happens or does it happen per transform function pair? Matrix decomposition and recomposition involves a lot of operations. Doing it for each function pair might be too expensive. The order of multiplication matters.
* If we collapse multiple not-matching transform function pairs before matrix interpolation, would it happen up to the next matching function pair or do we just do it for the entire rest of the transform function lists?

**Comment by tabatkins** [comment]
I think the simplest thing is to collapse the rest once you have a mismatch.  That's also the minimal change from the current behavior for things that differ early; they can't accidentally get "back on track" and change behavior.

**Comment by birtles** [comment]
[Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1472917) for updating this.

**Comment by LeaVerou** [comment]
One different idea, possibly bad, but figured I'd throw it out there just in case: Matrix interpolation looks far worse for angle-based (rotate and skew) transforms than the rest. What if we try to match those up and interpolate the rest via matrix interpolation?

**Comment by birtles** [comment]
It turns out this change breaks the header on Channel News Asia. See https://github.com/webcompat/web-bugs/issues/23687
