### ISSUE TITLE
[css-contain-2] Should CSS highlights make content relevant to the user?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9277]
This section is ambiguous: https://drafts.csswg.org/css-contain/#relevant-to-the-user , it only mentions selection, but also links to https://drafts.csswg.org/css-pseudo-4/#highlight-pseudos

More-over, scroll to text fragment seems to have some integration in https://searchfox.org/wubkat/source/LayoutTests/imported/w3c/web-platform-tests/css/css-contain/content-visibility/content-visibility-048.html

So it's not obvious which CSS highlight pseudos should trigger content relevancy. Can we get a clarification on which of these trigger content relevancy?

* ::target-text
* ::spelling-error / ::grammar-error
* ::highlight(*)

cc @frivoal @tabatkins @vmpstr @fantasai

**Comment by vmpstr** [comment]
I suspect `::selection` is the important one here. The reason for making selection cause content to be relevant is because this is the copy target when the user hits cmd-c or ctrl-c, so even if content is off-screen, it should still be selected with up to date rendering.

It's not as straightforward to say that the element with `::selection` pseudo element is the right one, since the highlight pseudos can be parented arbitrarily. This is  according to https://drafts.csswg.org/css-pseudo-4/#highlight-pseudos:

> The [highlight pseudo-elements](https://drafts.csswg.org/css-pseudo-4/#highlight-pseudo-element) do not necessarily fit into the element tree, and can arbitrarily cross element boundaries without honoring its nesting structure.

I'm not sure if there's a better spec text to explain what selection means though

**Comment by schenney-chromium** [comment]
Maybe instead link to the selection API spec? So if JS has selected content the user knows what they are going to get with copy commands.

I think target-text is another case, but again not because of any CSS that's applied, but because the document is going to scroll there (which I guess brings it into the viewport and makes it user relevant regardless).

**Comment by nt1m** [comment]
So from what I'm hearing, CSS highlights and grammar / spelling pseudos should be excluded? That's fine by me, but would be good if we didn't link to a section that's ambiguous.

**Comment by vmpstr** [comment]
Maybe we can link to https://w3c.github.io/selection-api/#dfn-selection

**Comment by tabatkins** [comment]
Yeah, agreed, we shoudl be a little clearer and link to a better target. The Selection API looks good.
