### ISSUE TITLE
URL encoding of CSS values

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#9301]
A long time ago @zcorpan wrote a great set of tests to determine whether features used the URL parser with a non-UTF-8 encoding. As you might expect, there is no interoperability:

https://wpt.fyi/results/html/infrastructure/urls/resolving-urls/query-encoding/windows-1252.html%3Finclude%3Dcss

Everyone seems to agree that `@import` uses UTF-8, but CSS values depend on the stylesheet encoding in Chromium and WebKit. I wanted to double check with the WG that this is intentional and everyone is on board with aligning with the standard or if this is something that should be changed.

**Comment by zcorpan** [comment]
Using utf-8 as the URL encoding for all CSS features is what the test currently expects, and what Firefox does. I tried to find compat bugs but didn't find any.

Is it possible for webkit and chromium to try switching to utf-8?

**Comment by annevk** [comment]
If Chromium is willing to switch around the same time I think that would be ok for WebKit. I'm personally not too worried about compatibility fallout for this.

**Comment by annevk** [comment]
Forgot to copy @chrishtr on this issue. I suspect he can weigh in for Chromium and then maybe it can be removed from the agenda.

**Comment by tabatkins** [comment]
I don't see any particular reason to not align, only the possibility of compat issues. So long as those end up fine, let's please align with the rest of the platform.

**Comment by foolip** [comment]
What kind of compat issues could there plausibly be here? If I'm reading https://url.spec.whatwg.org/#concept-basic-url-parser correctly the encoding only matters in the query string, so is it cases like `url(http://example.com/?text=Ångström)` when percent-encoding isn't used in the CSS source?

**Comment by annevk** [comment]
Correct, coupled with the stylesheet not using UTF-8 as its encoding.

**Comment by foolip** [comment]
I tried the change in https://chromium-review.googlesource.com/4846986 and the only test failures are in WPT. That's good.

With my Blink API owner hat on, to ship this change in Blink now I'd want to see some kind of compat analysis showing the risk is low, either by looking for such cases in httparchive, or via Chrome use counters.

However, if this behavior was already shipped in Firefox _and_ Safari without hiccups I'd be convinced is low enough risk to just try it.

**Comment by annevk** [comment]
WebKit is not compliant. I have a patch, but there are similar concerns around stability that would be resolved if Chromium shipped: https://github.com/WebKit/WebKit/pull/17383. 😅

**Comment by foolip** [comment]
@annevk sounds like we're both saying we'd be happy to ship if the other proves it safe by shipping first. Deadlock.

Another way forward is to do the kind of web compat analysis required by the Blink launch process. In this case, I think an analysis of CSS resources in http archive could be enough. Concretely, look for any CSS files served with a non-UTF8 encoding, and within those look for any non-ASCII bytes in the query component of any URL. Make a list of all of them, then randomly sample 50. For each, load the site including that CSS in Chrome, Firefox and Safari and see if there's any observable difference.

Is that something you'd be willing to do? I could do the blink-dev paperwork pointing to such an analysis and predict we'd try to ship it.

**Comment by zcorpan** [comment]
I can take a stab at writing a query.

**Comment by tabatkins** [comment]
Okay, I've dropped in some text about this.

> Some legacy implementations preserved the original encoding of URLs
> (as represented in the stylesheet)
> and reproduced that encoding when communicating over the network.
> UAs <em>must not</em> do this;
> when it's necessary to re-encode a URL into bytes
> to communicate over the network,
> the URL must be encoded as UTF-8,
> regardless of the original stylesheet encoding.

I think this sufficiently captures the context? Let me know if I can word anything better.

**Comment by zcorpan** [comment]
@tabatkins the URL parser will percent-encode the query, so the bytes that go over the network will be limited to the ASCII range. The issue is which encoding to use when percent-encoding the query string (always utf-8, or the encoding of the stylesheet or document). See https://url.spec.whatwg.org/#query-encoding-example

So maybe a bit clearer would be to say that for URLs in CSS, the URL parser's *encoding* argument must be omitted (i.e. use the default, UTF-8). https://url.spec.whatwg.org/#concept-url-parser

**Comment by zcorpan** [comment]
I've now queried httparchive. Getting the actual encoding is quite tricky, and so I gave up on that. I assume a big chunk is utf-8, but certainly not everything.

The dataset is from 2022-07-01 (same as [2022 Web Almanac](https://almanac.httparchive.org/en/2022/)). Total number of pages is 7,303,959.

Number of pages with non-ASCII in the query string in `url()` in CSS: 2231. So at most **0.03% of pages** in the dataset (likely less since this includes utf-8 pages).

An example match is `url('https://fonts.googleapis.com/css?family=Noto+Sans+JP:900&text=西部警察2020年12月29日 発売決定！「大都会」シリーズ')` (but the page for this uses utf-8).

(I excluded the cases where the first non-ASCII character in the query string is "â" because there were some that used non-ASCII quote marks and with encoding mismatch it became e.g. `url(â€˜./fonts/Avenir-Next.eot?#iefixâ€™)` – which is unlikely to work to begin with, and therefore not interesting to include.)

Full results: https://docs.google.com/spreadsheets/d/1i9Gvs1JIDo5mOw-rwPc5ppI6KrbXC8ol2XJ7h9PGAVs/edit?usp=sharing

**Comment by tabatkins** [comment]
Okay, rephrased. @zcorpan, does this wording look better?

(Also, thanks for the archive trawling, and further review in general! Looks pretty safe, then.)

**Comment by annevk** [comment]
Two things:

1. It's really that when you invoke the URL parser you don't use its _encoding_ argument. All the percent-encoding happens underneath and CSS doesn't really directly access that (to my knowledge).
2. I landed a patch for this in WebKit so it'll get some more exposure: https://github.com/WebKit/WebKit/commit/c195704a1cc8afc565fb5bd694d06fd329321267.

**Comment by zcorpan** [comment]
As @annevk said, https://url.spec.whatwg.org/#concept-url-parser is the appropriate entry point.

> for URLs in CSS, the URL parser's *encoding* argument must be omitted (i.e. use the default, UTF-8)

**Comment by tabatkins** [comment]
Yeah, after discussing with @annevk out-of-thread, I realized that the URL design is, for historical reasons, really weird. I had assumed that URLs stored their value normally, as codepoints, and then percent-encoded when you asked them to be serialized; instead, they store *ASCII only*, and percent-encode any non-ASCII (or ASCII-but-weird) codepoints *during parsing* according to a specified encoding.

Fix incoming.

**Comment by tabatkins** [comment]
Okay, I'm finally confident I've gotten this right. Thanks for the wording suggestion, @zcorpan, I basically used that.

**Comment by fantasai** [comment]
@zcorpan Sorry to bug you again, but, I kindof insisted we re-write the sentence so that it can be understandable what's happening to non-URL-spec-editors-and-peers. :) New text is here: https://github.com/w3c/csswg-drafts/commit/2da19025a5b59c86639688c167e70b9a03a3abe5

(The core sentence hasn't changed, we just added a bunch of explanatory text, which is hopefully correct.)

**Comment by annevk** [comment]
@fantasai it's correct, but it really only applies to the query portion of the URL. The remainder was already using UTF-8. And all of this is also the recommended default, so I'm not sure it's worth calling out as if it's something special, but that's up to you. (As in, I'd have a note when you do supply that argument.)

**Comment by zcorpan** [comment]
Yes it looks correct. It's the recommended default but it's different from URLs in HTML links, so it can still be surprising if one isn't already familiar with these details.
