### ISSUE TITLE
[css-color-hdr] Add mechanism to query HDR headroom

### ISSUE THREAD

**Issue by ccameron-chromium** [w3c/csswg-drafts#9306]
The current [dynamic-range](https://www.w3.org/TR/mediaqueries-5/#dynamic-range) media query indicates a binary value indicating if the screen is HDR (`high`) or SDR (`standard`).

The capability of an HDR screen is parameterized by its HDR headroom (how many times brighter than SDR white it can produce). This parameter is dynamic. It depends on the viewing conditions and the content on-screen.

This issue is to explore mechanisms for exposing this parameter.

**Comment by ccameron-chromium** [comment]
Probably the simplest scheme for solving this would be add a property to the [`Screen` interface](https://drafts.csswg.org/cssom-view/#the-screen-interface).

To avoid fingerprinting, implementations would probably want to round the value to to the nearest power-of-two, unless specific permission is granted.

**Comment by svgeesus** [comment]
https://github.com/ccameron-chromium/hdr-headroom-limit/blob/main/EXPLAINER.md

**Comment by palemieux** [comment]
Please consider the latest recommendation of the Color on the Web CG on adding output color volume information (including luminance headroom information) to the Screen interface of the CSS Object Model:

https://github.com/w3c/ColorWeb-CG/blob/hdr_canvas_r2/hdr_html_canvas_element.md#add-display-color-volume-information-to-screen-interface-of-the-css-object-model

**Comment by smfr** [comment]
If it's the case that `referenceWhiteLuminance` depends on viewing conditions which influence screen brightness, then WebKit objects to adding that. A web page should not be able to detect the viewing conditions in effect; it should not be able to detect when you walk outside, for instance. And I don't think there's a user prompt that could be worded in a way that users would understand that this access could be gated on.

The preferred approach is to allow authors to supply a list of assets, and have the UA pick the appropriate asset (like `srcset`).

**Comment by svgeesus** [comment]
> The preferred approach is to allow authors to supply a list of assets, and have the UA pick the appropriate asset (like srcset).

That approach doesn't really work well in the case where there is a **single asset** which can adapt to a range of HDR headroom values. One example of that approach is being standardized in ISO TC 42/WG 23 on Gain Maps. A single image resource has an SDR baseline image and a gain map; from that information a variety of HDR renderings can be reconstructed, corresponding to the actual HDR headroom.

That work is being driven and implemented by Apple, and Adobe.

 - https://github.com/w3c/PNG-spec/issues/366

Another example would be a web app which draws to Canvas 2D context, which computes a tone mapping curve in real time following the procedure in section _5.4.1 Mapping to display with limited brightness range_ of ITU Rec_BT.2390.

HDR is being widely adopted by native apps. The web also needs to adopt it, and one size definitely does not fit all viewing conditions. Presumably WebKit would not want to hold that back, especially since the Apple platforms on which it primarily runs already have that HDR headroom adaptation capability.

How can we move forward on this in a way that provides the capability in a privacy-sensitive way?

**Comment by svgeesus** [comment]
@ccameron-chromium wrote:

> To avoid fingerprinting, implementations would probably want to round the value to to the nearest power-of-two, unless specific permission is granted.

So, that would give headroom values of 1 (_i.e._SDR), 2, 4 and 8 ? Or would 16 (three stops above reference white) also be useful, in a consumer web delivery context? At an SDR white of 100 nits those would correspond to peak white luminances of 200, 400, 800 and 1600 nits.

**Comment by svgeesus** [comment]
@smfr there were some questions for you above, regarding how to expose this existing capability on the Web Platform.

**Comment by adixon-adobe** [comment]
On https://lightroom.adobe.com we'll need this to enable meaningful HDR editing, as you really need to know the amount of HDR headroom you're seeing to accurately understand the preview. For example, in the current Lightroom Desktop UI, as well as in the Adobe Camera Raw UI in Photoshop, we display a histogram of the image, along with a white line showing the peak brightness of the current monitor. It's very common to change brightness as you're editing to test different ranges, so having live updates to this during an editing session is needed,

<img width="281" alt="hdr-range" src="https://github.com/w3c/csswg-drafts/assets/48841507/8688fd11-327e-4d3a-9765-bef8cf229987">

It would be very reasonable to require the user to opt-in to this given the privacy implications.

**Comment by svgeesus** [comment]
@ccameron-chromium given that this mechanism has now been [added to the spec](https://drafts.csswg.org/css-color-hdr/#controlling-dynamic-range), per [CSSWG resolution](https://github.com/w3c/csswg-drafts/issues/9306#issuecomment-1864864440), and also that you [have asked for TAG review](https://github.com/w3ctag/design-reviews/issues/1027) it seems that this issue can be closed as completed?

**Comment by ccameron-chromium** [comment]
Yes, thanks!
