### ISSUE TITLE
[css-fonts] Drop the emoji font-family

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9359]
I may be missing something, but I think the `emoji` font family serves no useful purpose, and does not have well defined behavior, so we should drop it.

The only thing I think it could reasonably be used for is better served by the `font-variant-emoji` property: for the few characters that can ambiguously have an emoji rendering, or a symbol rendering, this lets you pick how they are rendered.

Other than this choice of variant, which is better defined in and better suited to `font-variant-emoji` property, it seems to me that an emoji font-family doesn't make sense.

Am I missing something? If no, we should drop that family.

cc @svgeesus

**Comment by frivoal** [comment]
As far as I can tell, this was introduced in response to https://lists.w3.org/Archives/Public/www-style/2014Aug/0323.html, which seems to confirm that the motivation was indeed the same problem that is now better solved with `font-variant-emoji`.

**Comment by svgeesus** [comment]
Precisely:

> Specifying the 'emoji' value in a fontlist would prioritize the use of color
glyphs for all codepoints covered by the emoji font.

So yes, it might have been an okay idea in 2014 but is entirely redundant now.

**Comment by svgeesus** [comment]
Indeed, the [discussion that led to `font-variant-emoji`](https://lists.w3.org/Archives/Public/www-style/2014Aug/0322.html) started that same day.

**Comment by svgeesus** [comment]
@jfkthame @emilio thoughts on this?

**Comment by drott** [comment]
I am in favor of removing it and agree with @frivoal's comment above.

**Comment by svgeesus** [comment]
**Proposed offline resolution:** Remove the `emoji` font family from CSS Fonts 4

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Remove the `emoji` font family from CSS Fonts 4

**Comment by o-t-w** [comment]
Sorry to comment on a closed issue, but I am under the impression that `font-variant-emoji` alone may not always be enough to render an emoji, at least in Chrome. If you want regular text characters to be rendered using system-ui on Mac, for example, but want to include some colorful emoji, because SF Pro includes a black heart glyph, that will be used instead of the system emoji font. To quote someone more knowledgable than I am "Font fallback logic in text engines is not necessarily going to have special-case logic for variation sequences". https://fullystacked.net/using-emoji-on-the-web/ https://codepen.io/cssgrid/pen/yLrZqGz
