### ISSUE TITLE
[css-text-decor] Default color of text-shadow

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#942]
[https://drafts.csswg.org/css-text-decor-3/#text-shadow-property](https://drafts.csswg.org/css-text-decor-3/#text-shadow-property) says that:

> If the color of the shadow is not specified, the shadow has the resulting color of the ink that it shadows.

This seems to imply, for instance, that a colored emoji glyph would by default (i.e. no explicit shadow color is specified) cast a multi-colored shadow, as its ink is multi-colored. But ISTM that a "shadow" is inherently monochrome, regardless of the color(s) of the thing being shadowed.

Perhaps this text was written with text decorations in mind, given that `text-decoration-color` can give different colors to underline, overline, etc.; so the "ink" of a decoration may have a different color than the "ink" of the associated text, and the intent may have been to allow different-colored decorations to cast corresponding different-colored shadows.

But this still seems wrong to me. In the case of text with a colored underline (perhaps even multiple, differently-colored decoration lines), I think the natural interpretation of text-shadow is that it causes the complete (decorated) text rendering to cast a single, monochromatic shadow, and not that it causes the (bare) text to cast a shadow that then has various-colored decorations applied to it.

Also, compare [`box-shadow`](https://drafts.csswg.org/css-backgrounds-3/#the-box-shadow), which says:

> If the color is absent, the used color is taken from the ‘color’ property.

So a multi-colored `<img>`, for example, does not magically cast a multi-colored shadow. Neither should multi-colored decorated text, IMO, cast a multi-colored shadow.

Therefore, I suggest the `text-shadow` spec should be changed to be like `box-shadow` in this respect.

**Comment by upsuper** [comment]
cc myself

**Comment by KuoE0** [comment]
CC myself.

**Comment by FremyCompany** [comment]
![image](https://cloud.githubusercontent.com/assets/364405/22603515/92f2439a-e9fc-11e6-9856-6d98e9c5f851.png) ![image](https://cloud.githubusercontent.com/assets/364405/22603522/9f301e34-e9fc-11e6-8061-c5a4e4dec471.png) ![image](https://cloud.githubusercontent.com/assets/364405/22603531/a9375078-e9fc-11e6-912a-613938dc95a2.png)
https://jsfiddle.net/bqzwj1ke/ (Edge, Firefox, Chrome)

**Comment by FremyCompany** [comment]
![image](https://cloud.githubusercontent.com/assets/364405/22604666/7b663952-ea01-11e6-8718-2ab5837ed2e6.png) ![image](https://cloud.githubusercontent.com/assets/364405/22604672/8745a7b2-ea01-11e6-8b72-fd197cac4d99.png) ![image](https://cloud.githubusercontent.com/assets/364405/22604680/8fcacb2e-ea01-11e6-96ea-728e0ca21af4.png)
https://jsfiddle.net/bqzwj1ke/1/

**Comment by upsuper** [comment]
I guess it means we do want to change the spec to make the whole shadow use `currentcolor` by default rather than the "color of the ink".

**Comment by kojiishi** [comment]
So the proposals from @jfkthame and @upsuper are the same, correct? Sounds reasonable to me IIUC.

@FremyCompany's test is interesting...for shadows of decorations, should we honor the used color of `color` property, or propagated color? Anyone have any preferences?

**Comment by upsuper** [comment]
The motivation of this proposal was that, having different color in a blur shadow is hard to implement (takes time but doesn't seem to be useful), so I think the proposal is to make the shadow of decoration lines always use the same color as the text.

More formally, the proposal should be something like, when color is omitted, it is treated as if `currentcolor` is specified.

**Comment by FremyCompany** [comment]
Then there is also the question of chrome repainting for each text decoration instead of one for the complete geometry. We don't have this issue in Edge as a result of how we do underlining (there can be only one, but its color will vary depending on closest text-decoration:underline parent).

**Comment by upsuper** [comment]
If we treat omitted `<color>` as `currentcolor`, then I don't think there is ambiguity anymore. Everything from the same `text-shadow` would have the same color.

**Comment by kojiishi** [comment]
@FremyCompany I'm failing to understand... Can you explain a bit more?

**Comment by FremyCompany** [comment]
@kojiishi Look at the underline under "bcd" in Chrome in case 1 vs case 2. You will see that the underline in case 1 is "darker" because it seems to be drawn twice (once for the parent "a" underline, and once for the child "span" underline).

**Comment by kojiishi** [comment]
@FremyCompany oh I see, thank you. Yes, we draw all of nested decorations in order to support different style/position etc., ex. http://jsbin.com/kikuju

**Comment by FremyCompany** [comment]
@kojiishi I see. But that means that you render using full-color blur, since the underlines can overlap and compose to darker colors. In Edge we try to use the geometry not redraw the text (the same thing we do for background-clip:text, actually).

Also, here is a test case that shows how non-interoperable we are:

![image](https://cloud.githubusercontent.com/assets/364405/22763358/12df5ef6-ee19-11e6-93c9-2c76a5e0347a.png) ![image](https://cloud.githubusercontent.com/assets/364405/22763340/fad512d8-ee18-11e6-81a8-882fb1b517aa.png) ![image](https://cloud.githubusercontent.com/assets/364405/22763271/99f77884-ee18-11e6-9930-298438c9c34a.png)
https://jsfiddle.net/k53Ld4g3/ (Edge, Firefox, Chrome)

As I understand, this thread seems to be about standardizing Edge's behavior, right?

**Comment by upsuper** [comment]
Isn't it about standardizing Chrome's behavior? Chrome uses the currentcolor for shadow of decoration lines. If there is any blur, you would see that Firefox would have the same behavior, and the proposal is about aligning our non-blur case with our blur case.

**Comment by kojiishi** [comment]
Do we agree that "rendering nested decorations" and "color of shadow, including shadow of decorations" are separate issues? Related, but I suppose we can repro the former without shadows, using alpha for decoration color.

For shadow, Edge looks most reasonable to me, but I might need to check with other members in our team.

For nested decorations, I haven't determined my thoughts well enough yet. This might worth a separate issue if we were that non-interoperable.

**Comment by upsuper** [comment]
> Do we agree that "rendering nested decorations" and "color of shadow, including shadow of decorations" are separate issues? Related, but I suppose we can repro the former without shadows, using alpha for decoration color.

Isn't nested decoration supposed to exist? I think that is a natural consequence of propagation style text-decoration which Edge probably just haven't implemented yet.

I believe the issue is simply about the color of shadow of decorations.

> For shadow, Edge looks most reasonable to me, but I might need to check with other members in our team.

That means we give text shadow a default color of grey or semi-transparent black. That might be fine either.

I don't know why text-shadow currently uses color of "ink" by default. But I would probably prefer we use `currentcolor` as the default, to align with behavior of `box-shadow`.

**Comment by kojiishi** [comment]
> I don't know why text-shadow currently uses color of "ink" by default

I think it meant `currentColor`, just written before color Emoji was invented. @fantasai could you chime in?

**Comment by upsuper** [comment]
> I think it meant currentColor, just written before color Emoji was invented.

But decoration lines are defined in the same spec, so color of "ink" is already ambiguous in the spec itself regardless of emoji.

**Comment by FremyCompany** [comment]
@upsuper I think you had a too quick look at the test case. The shadow uses the color of the body element which I set to some gray. If I had set two shadows instead (one of the "a" and one on the "b") then Chrome behavior would be correct (and would match Edge in that case).

**Comment by upsuper** [comment]
@FremyCompany Yeah, I probably look too quick, sorry.

But in that testcase, Chrome's behavior still matches what I expect from the spec with my proposed change, because `text-shadow` inherits, and `currentcolor` is a computed-value time value, which means the shadow should use the value of `color` property of the current text rather than `color` of the element with `text-shadow` specified. Whether it is desired is another question, though...

**Comment by FremyCompany** [comment]
Oh well, ```currentColor``` is an annoying thing sometimes... I guess you are right, this is the per-spec behavior. It prefer either having everything the same color or having the underlines respect their original color, a behavior where text preserves its color but not the underline is confusing.

Anyway, I ended up on this issue for another reason: I was wondering what browsers do in the case of color emojis. I like Edge's behavior better but I guess it only works because on Windows we maintain strict parity between color and non-color emojis:

https://jsfiddle.net/k53Ld4g3/3/
![image](https://cloud.githubusercontent.com/assets/364405/22992300/1df1f762-f374-11e6-9ba9-bf7c140bdc49.png) ![image](https://cloud.githubusercontent.com/assets/364405/22992309/27a29366-f374-11e6-8c75-1b2177bac685.png)

Any opinion on that?

Also, @upsuper: I found out that in Firefox the text shadow disappears on selection, is that by design?

**Comment by KuoE0** [comment]
@FremyCompany Can you provide the test case about the disappearance of text-shadow on selection? I can't reproduce with https://jsfiddle.net/pd3zoymq/.

**Comment by FremyCompany** [comment]
@KuoE0 The testcase you just mentioned reproduces on my pc, as all others do too. Both Firefox 53.0a2 (2017-02-10) and 51.0.1 are affected on my Windows 10 machine. 
![image](https://cloud.githubusercontent.com/assets/364405/23089124/239fea72-f539-11e6-9637-043f6226c7c9.png)

**Comment by upsuper** [comment]
> The testcase you just mentioned reproduces on my pc, as all others do too. Both Firefox 53.0a2 (2017-02-10) and 51.0.1 are affected on my Windows 10 machine.

Oh, that's... definitely a bug of Firefox. It is because we changes the text color when rendering selected text. That theoretically shouldn't affect the color used to render the shadow.

**Comment by dbaron** [comment]
We've made a bunch of changes in the past to how text-shadow and selection interact; I think for more "normal" text shadows, leaving the original color during selection looks pretty bad.

**Comment by FremyCompany** [comment]
If the div has an underline, does that underline end up being of the color of the text of the div (black)? That should be what happens, right? If so, I think the proposed text lgtm.

**Comment by fantasai** [comment]
Link to resolution: https://lists.w3.org/Archives/Public/www-style/2017Feb/0088.html

**Comment by fantasai** [comment]
Sounds great. I'm calling this issue closed.
