### ISSUE TITLE
[selectors] Is it intentional that :has(:is()) is different from :has()?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#9422]
This means that `:has` and nesting don't play super-well, and it's a bit unintuitive.

Test-case:

```html
<!DOCTYPE html>
<div id="outer">
  <div id="middle">
    <div id="inner"></div>
  </div>
</div>
<pre><script>
  function w(el, selector) {
    document.writeln(`#${el.id}.matches(${selector}) = ${el.matches(selector)}`);
  }
  w(middle, ":has(#outer #inner)");
  w(middle, ":has(:is(#outer #inner))");
</script></pre>
```

Maybe we shouldn't allow `:has()` to escape its scope?

cc @tabatkins @lilles @byung-woo @dshin-moz

**Comment by emilio** [comment]
Live: https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20id%3D%22outer%22%3E%0A%20%20%3Cdiv%20id%3D%22middle%22%3E%0A%20%20%20%20%3Cdiv%20id%3D%22inner%22%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cpre%3E%3Cscript%3E%0A%20%20function%20w(el%2C%20selector)%20%7B%0A%20%20%20%20document.writeln(%60%23%24%7Bel.id%7D.matches(%24%7Bselector%7D)%20%3D%20%24%7Bel.matches(selector)%7D%60)%3B%0A%20%20%7D%0A%20%20w(middle%2C%20%22%3Ahas(%23outer%20%23inner)%22)%3B%0A%20%20w(middle%2C%20%22%3Ahas(%3Ais(%23outer%20%23inner))%22)%3B%0A%3C%2Fscript%3E%3C%2Fpre%3E

**Comment by Loirooriol** [comment]
I always assumed it was intentional...

**Comment by tabatkins** [comment]
The behavior listed here *is* basically intentional; both features are working as intended. `:has()`'s argument is forced to be relative, so `#outer` must be a descendant of `#middle` (and it isn't), while `:is()`'s argument is specifically *not* relative, so `#outer` can be further up the tree.

You'll get this same behavior from, say, @scope: in `@scope #middle { #outer #inner {...} :is(#outer #inner) {...}}` the first won't match (it's relative-by-default, since there's no `:scope` or `&` in the selector) but the second will.

Could you elaborate on what you see as the problem with Nesting?

**Comment by emilio** [comment]
Yeah, I'm ok with close no change I guess, but I think it's rather confusing that things inside `:has()` (and `@scope`) escape the scope. Not only implementation-wise it's a pain, but also it's very weird that something like:

```css
@scope #middle {
  #outer #inner {
    display: block
  }
}
```

Behaves differently from:

```css
#outer #inner {
  @scope #middle {
    display: block;
  }
}
```

You could argue that it's kind of the same with descendant combinators and such, but I find it a bit more confusing / less intuitive for things that implicitly create a scope like `@scope` / `:has()`...

**Comment by tabatkins** [comment]
I'm sorry, I don't understand your example there. Ignoring the obvious difference in the ordering of the selectors, the two do act identically - they're both *basically* equivalent to just concatenating the selectors. (And neither would match.) Are you thinking of a more complicated example that actually shows a difference in the nesting?

> things that implicitly create a scope like @scope / :has()...

`@scope` (and Nesting) both have easy ways to escape that "implicit scope" caused by relative selectors, tho - just put an `&` or `:scope` in the inner selector. In all these cases the "scoping" is just a very light convenience feature caused by relative selectors, not an actual boundary in any sense.

**Comment by emilio** [comment]
@tabatkins I might be confused, but my understanding is that the nesting rules we ended up with end up making my later example desugar to:

```css
#outer #inner {
  @scope #middle {
    & { display: block; }
  }
}
```

Which would effectively desugar to:

```css
:is(#outer #inner) { display: block }
```

Is that not how it is supposed to work? That's how e.g.:

```
#outer #inner {
  #middle & { ...  }
}
```

works now ([link](https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%23outer%20%23inner%20%7B%0A%20%20%23middle%20%26%20%7B%20width%3A%20100px%3B%20height%3A%20100px%3B%20background%3A%20green%20%7D%0A%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%20id%3D%22outer%22%3E%0A%20%20%3Cdiv%20id%3D%22middle%22%3E%0A%20%20%20%20%3Cdiv%20id%3D%22inner%22%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E)). It does match, because it's effectively `#middle :is(#outer #inner)`, not `#middle #outer #inner`. Is there any magic in `@scope` that would make it work some other way?

**Comment by tabatkins** [comment]
Ohhhh, I glossed right over the fact that the inner `@scope` was just holding raw properties. Sorry, it is indeed equivalent to the `&` desugaring in your first block.

But your second desugaring isn't at all correct. First, the `#middle` is nested relative to the outer rule, so it's effectively `:is(#outer #inner) #middle` (aka just `#outer #inner #middle`). Then the `&` matches the elements matched by the scoping root, so it's *also* effectively `#outer #inner #middle`.

It looks like you're assuming the `&` "skips past" the `@scope` rule and is relative to the nearest "normal" style rule, but that's not the case. This is defined by <https://drafts.csswg.org/css-nesting/#nesting-at-scope> (and a little bit by <https://drafts.csswg.org/css-cascade-6/#scoped-rules>).
