### ISSUE TITLE
[css-values-4] Distributing multiplication over sums clarification

### ISSUE THREAD

**Issue by danielsakhapov** [w3c/csswg-drafts#9434]
The [spec](https://drafts.csswg.org/css-values-4/#calc-simplification) says that
> [Internal representations](https://drafts.css-houdini.org/css-typed-om-1/#css-internal-representation) of [math functions](https://drafts.csswg.org/css-values-4/#math-function) are eagerly simplified to the extent possible, using standard algebraic simplifications (distributing multiplication over sums, combining similar units, etc.).

So, the case like `calc(2 * (10px - 1rem))` becomes `calc(20px - 2rem)`.

It's not clear to me if we should do the same for when we have functions inside the brackets, like:
`calc(2 * (min(10px, 10%) + max(1rem, 1%))` should become `calc(2 * min(10px, 10%) + 2 * max(1rem, 1%))`?

Currently, no browser does `calc(2 * min(10px, 10%) + 2 * max(1rem, 1%))` and just leaves the expression as it is.

So, my question is, should we distribute multiplication over sums in case when the parts are math functions?

@tabatkins @fantasai

**Comment by danielsakhapov** [comment]
Never mind, I can't read the spec...

But why don't we simplify in case of operands of the sum/sub being non-numeric?

**Comment by tabatkins** [comment]
The spec doesn't do that distribution, currently, because doing so wouldn't meaningfully simplify the expression.

The current rule means that `Product(Numeric, Sum(Numeric, Numeric, Numeric))` can be simplified to `Sum(Numeric, Numeric, Numeric)`, which is a noticeable simplification; we remove one level of nesting.

But if there are math functions, like `Product(Numeric, Sum(MathFn, MathFn, MathFn))`, distributing the multiplication would leave you with `Sum(Product(Numeric, MathFn), Product(Numeric, MathFn), Product(Numeric, MathFn))` - it's no simpler, it just inverts the order of the nested functions.
