### ISSUE TITLE
[cssom-view] API to expose skipped content state

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9474]
Currently there is no straightforward way to query the skipped content state, despite browsers having this info internally.

In the context of web extensions, it would be useful if you could query that state without invoking the layout of the element, which takes away from the content-visibility optimizations.

@vmpstr @rwlbuis

**Comment by Loirooriol** [comment]
Some past discussion in https://github.com/w3c/csswg-drafts/issues/6850#issuecomment-1030416796

**Comment by nt1m** [comment]
Perhaps it should just be an extension to `checkVisibility` to check for `c-v: auto` skipped content

**Comment by vmpstr** [comment]
I think this is a pretty good idea. We currently have 
* The [Contentvisibilityautostatechange](https://drafts.csswg.org/css-contain/#content-visibility-auto-state-change) event which is nice to checking when `content-visibility: auto` switches state
* The checkVisibility function that Oriol mentioned.

I don't know if we want checkVisibility to specifically check for c-v auto skipped content, since that content is still visible to a lot of features like find-in-page and accessibility. So saying it's not visible in checkVisibility is a bit misleading.

I wouldn't be opposed to a new function though. 

/cc @josepharhar

**Comment by AutoSponge** [comment]
APA will track this issue. We want to ensure that elements not rendered (e.g., `display:none`) but that could still end up in the AxTree (e.g., targeted by `aria-describedby`) are not conflated by developers to be "skipped" for AT.
