### ISSUE TITLE
[css-text-4] Let `text-wrap-style` apply to more than just block containers

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9524]
A [quick test](https://codepen.io/SebastianZ1983/pen/YzBXREJ) shows that implementations for `text-wrap` actually allow flex and block containers as well as tables, generally speaking all non-inline blocks.

Though the spec. currently [restricts `text-wrap-style` to block containers](https://drafts.csswg.org/css-text-4/#text-wrap-style).

Therefore, I suggest to change that to say that it applies to all containers but inline-level boxes.

Sebastian

**Comment by nt1m** [comment]
Should it be the `text-wrap` shorthand in general? Not sure about just changing a single longhand

**Comment by Loirooriol** [comment]
The 3 cases have an anonymous block container. It just works because it's an inherited property.

Applying to a flex container would imply affecting how flex items are distributed among flex lines, that's not what's happening here. (That would be reasonable, and I recall some existing issue about this, but probably shouldn't be named `text-`)

**Comment by frivoal** [comment]
I agree with @Loirooriol .

As for
> Should it be the text-wrap shorthand in general?

No, because text-wrap-mode needs to apply to inlines/text, rather than block containers.

> Not sure about just changing a single longhand

I don't think that's an issue. shorthand / longhand relationships are about parsing / cascading, while the "applies to" part describes the effects. Property having a value but no effect is common, and I'm pretty sure there's precedent for shorthands having longhands with different "applies to".
