### ISSUE TITLE
[css-grid] fr unit and other length units

### ISSUE THREAD

**Issue by ylafon** [w3c/csswg-drafts#955]
grid defines the ['fr' unit as a flexible length](https://drafts.csswg.org/css-grid/#fr-unit), how does this kind of length relates to relative and absolute lengths that are defined in https://www.w3.org/TR/css3-values/#lengths ?
What would be the behaviour if 1fr was used as the width of an element?
The definition should be more explicit about the scope of this unit and its relationship to other length units.

**Comment by SelenIT** [comment]
The CSS Grid Layout spec actually doesn't define the `fr` unit as a _length unit_ of any kind. Instead, it introduces the new dimension type — "Flexible Length", which can currently be used in one context only — for a [size of a grid track](https://drafts.csswg.org/css-grid/#typedef-track-breadth), which is defined as
> `<track-breadth>       = <length-percentage> | <flex> | min-content | max-content | auto`

(where `<flex>` is this new dimension type).

Since [the `width` property](https://drafts.csswg.org/css-box-3/#propdef-width) is defined as
> `[<length> | <percentage>] | available | min-content | max-content | fit-content | auto`

which doesn't allow `<flex>` type of value, `width: 1fr` would be an invalid declaration, just like `width: 1deg`, `width: 500Hz` and so on. I don't see any ambiguity in the current definition

**Comment by ylafon** [comment]
Yes, I saw that it was defined as a "Flexible Length", but the fact that it is not a "length" despite its name (unlike "relative length" and "absolute length") would deserve a better definition in the spec (and ideally be moved to the css-values spec), as in other specifications, it is quite common to use "length" and not "length, but not of the flexible kind, as it is not a real length".

**Comment by SelenIT** [comment]
Agree. Maybe we should raise a "meta-issue": do all CSS dimensions and values defined anywhere (even in one module only) need to be reflected in css-values? At least, I believe that they should have a special section in [CSS Indexes page](https://drafts.csswg.org/indexes/).

**Comment by tabatkins** [comment]
> The CSS Grid Layout spec actually doesn't define the fr unit as a length unit of any kind.

Yup. We refer to it colloquially as a "length", because it serves a similar purpose, but it's very specifically not a subtype of `<length>` in the spec.  Using it in 'width' would be invalid due to grammar reasons.

> Maybe we should raise a "meta-issue": do all CSS dimensions and values defined anywhere (even in one module only) need to be reflected in css-values?

Our general rule is that anything which is widely applicable across specs belongs in the V&U spec.  Specialized dimensions don't need to live there, but all `<length>`s are CSS-wide, and should have their definitions in V&U.

**Comment by fantasai** [comment]
We need to clarify whether fr units represent lengths and are combinable with them in `calc()`.

**Comment by dbaron** [comment]
This was [discussed in today's teleconference](https://log.csswg.org/irc.w3.org/css/2017-03-15/#e781389) concluding with:
> RESOLVED: length & frs are not combinable, but will reconsider if/when length & auto are combinable
