### ISSUE TITLE
[css-values-4] Simplification algorithm should possibly return single child for min/max

### ISSUE THREAD

**Issue by johannesodland** [w3c/csswg-drafts#9559]
Step 5 for min/max of [simplify a calculation tree](https://drafts.csswg.org/css-values-4/#simplify-a-calculation-tree) currently states:

> If root is a Min or Max node, attempt to partially simplify it:
>
> [For each](https://infra.spec.whatwg.org/#list-iterate) node child of root’s children:
>
> If child is a numeric value with enough information to compare magnitudes with another child of the same unit (see note in previous step), and there are other children of root that are numeric values with the same unit, combine all such children with the appropriate operator per root, and replace child with the result, removing all other child nodes involved.
>
> Return root.

I might miss something, but this seems to simplify the children of the Min or Max node, but if you're left with only one child it seems to return the Min/Max node with a single child. 

Should it not return the child in this case? I belive an earlier version of the spec did the same as the step for Sum nodes: 

> If root has only a single child at this point, return the child. Otherwise, return root.

**Comment by cdoublev** [comment]
> I belive an earlier version of the spec did the same as the step for Sum nodes

You are right (see [56fb598](https://github.com/w3c/csswg-drafts/commit/56fb59809e43220bb42f626d2a9e066a2172d33c#diff-fc1c32de78d227c8f0c8008469824444d1ba7f027e48a336125017d40b8f6f6fL4283)). But I think I remember some discussions about preserving `min(1em)`.

**Comment by johannesodland** [comment]
> You are right (see [56fb598](https://github.com/w3c/csswg-drafts/commit/56fb59809e43220bb42f626d2a9e066a2172d33c#diff-fc1c32de78d227c8f0c8008469824444d1ba7f027e48a336125017d40b8f6f6fL4283)). But I think I remember some discussions about preserving `min(1em)`.

Could it be related to https://github.com/w3c/csswg-drafts/issues/7456?

Should the Min node in `min(1em)` be preserved during parsing for internal representation?
It doesn't seem like it's preserved when simplifying for computed or used value though?

**Comment by cdoublev** [comment]
> Could it be related to #7456?

No, this issue is about my misunderstandings (which still hold to this day) regarding the simplification of a Product node, and more generally, about the whole parsing/simplification procedures. I think I was thinking to #4399.

`min(1em)` should not be preserved at computed/used value time. I think `1em` is resolved to an absolute px at step 1.2, then `min()` is resolved at step 4.

To be honest, I do not know what should be the serialization as a component of a specified value, for `min(1em)` as input. Based on current browser outputs, I would say `calc(1em)` but from reading the spec, the step you are suggesting seems to be missing, indeed. There do not appear to be any existing [WPTs](https://github.com/web-platform-tests/wpt/blob/master/css/css-values/minmax-length-serialize.html).

**Comment by johannesodland** [comment]
Did a quick test across browsers to check how they serialize the specified style: 

Firefox: `calc(1em)`
Chrome: `min(1em)`
Safari: `calc(1em)`

I'm not sure how important this is though..

**Comment by cdoublev** [comment]
Chrome now outputs `calc(1em)`.



I was trying to figure out which part of the simplification algo would allow FF to simplify `abs(abs(-1%))` as `calc(1%)`, and from reading step 4

**Comment by tabatkins** [comment]
> Should it not return the child in this case? I belive an earlier version of the spec did the same as the step for Sum nodes:

Note that removing a Sum node does not change the functional structure of the value; it just means that you don't have a silly `Sum(5px)` tree that just serializes to `calc(5px)` anyway. The same is not true of simplifying away other functions; that changes what the result looks like - `Sum(5px + Min(10px))` serializes to `calc(5px + min(10px))`, rather than `calc(15px)` as if would if you removed the Min node.

But it does appear that browsers do exactly that simplification now, so I'm fine with making it.

(And I'm not really sure why I removed the Min/Max simplification in <https://github.com/w3c/csswg-drafts/commit/56fb59809e43220bb42f626d2a9e066a2172d33c#diff-fc1c32de78d227c8f0c8008469824444d1ba7f027e48a336125017d40b8f6f6fL4283>; the minutes in <https://github.com/w3c/csswg-drafts/issues/4399> don't suggest we stop doing that.)

**Comment by tabatkins** [comment]
As far as I can tell, the reason I removed the explicit "min()/max() is dropped if it has only one child" is that I figured it was covered by the *generic* "replace a node with its result if you can", and just didn't realize that the restrictions I placed on that clause ("in the canonical unit") would be too restrictive.

Anyway, restored now; as part of the special min/max "partial simplification" it'll replace itself with its sole child *regardless* of whether the child is fully resolveable yet.
