### ISSUE TITLE
[selectors] Universal selector missing from grammar

### ISSUE THREAD

**Issue by tim-loh** [w3c/csswg-drafts#957]
The universal selector (i.e. `*`) is missing from the selectors spec's grammar.

https://drafts.csswg.org/selectors/#grammar

**Comment by SelenIT** [comment]
Agree. Even if the spec [defines](https://drafts.csswg.org/selectors/#the-universal-selector) it as 'a special _type_ selector' (which kind of makes sense, although might be confusing regarding different specificity), shouldn't its formal grammar be `<type-selector> = <wq-name> | <ns-prefix>? '*'` (with optional namespece token) instead of `<type-selector> = <wq-name> | <ns-prefix> '*'`?
