### ISSUE TITLE
[css-values-5] Accept `<whole-value>` as argument of `first-valid()`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9590]
Is `first-valid()` intentionally defined with `<declaration-value>` rather than `<whole-value>`? Should `first-valid(toggle(red; green))` be invalid?

https://drafts.csswg.org/css-values-5/#typedef-first-valid

  > `<first-valid()> = first-valid( <declaration-value> [ ';' <declaration-value> ]* )`

**Comment by Loirooriol** [comment]
> Accept `<whole-value>` as argument of `first-valid()`

I thought the same in https://github.com/w3c/csswg-drafts/commit/5fc63f5825d2aeca87a35f59146eac2fde844b80#r131685583

But e.g. consider `color: first-valid(invalid(), green)`. This needs to be valid (and resolve to green), so we can't require `invalid()` to be a `<whole-value>`.

> Should `first-valid(toggle(red; green))` be invalid?

No, it's valid, since  `toggle(red; green)` is a `<declaration-value>` (being a `<whole-value>` is not exclusive).

**Comment by Loirooriol** [comment]
> I am still not sure if toggle() nested in first-valid() is valid at computed value time

`toggle()` is not preserved at computed-value time. https://drafts.csswg.org/css-values-5/#toggle-notation: "the computed value of `toggle()` is C_{n+1}"

> it is not allowed to be nested

I think this means that you can't have a `toggle()` inside another `toggle()`. But it should be fine to have a `toggle()` inside a `first-valid()`.

**Comment by tabatkins** [comment]
Yeah @Loirooriol is correct on all counts.
