### ISSUE TITLE
[view-transitions-1] Is view-transition-name discretely animatable?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9619]
https://drafts.csswg.org/css-view-transitions/#view-transition-name-prop

says this supports discrete animations, but I don't really see the point of supporting them on view-transition-name...

@noamr @khushalsagar @fantasai @tabatkins

**Comment by khushalsagar** [comment]
^ that makes sense to me. It should be "not animatable".

**Comment by flackr** [comment]
Why not though? Is there a reason having it animateable makes the implementation more complex? In https://www.w3.org/TR/web-animations/#not-animatable we say:

> Note: Properties are typically excluded from animation because animating them would create excessive complications. For example, properties defining animation parameters are [not animatable](https://www.w3.org/TR/web-animations/#not-animatable) since doing so would create complex recursive behavior.

In the past we've defined several properties as not animateable because we didn't see reasons to animate them, and then later reasons to animate them came up and we took compat risk in making them animateable. I'd prefer if we err on the side of everything is animateable unless doing so results in complex recursive behavior.

**Comment by fantasai** [comment]
The logic for leaving as `discrete` was that, since animating `view-transition-name` doesn't affect a running view transition, there's no need to make it "not animatable". But if there's some complication that wasn't captured in the discussion, @nt1m, since you weren't here, we can put it back on the agenda to review.

**Comment by nt1m** [comment]
If animating view-transition-name doesn't affect the running VT then I guess my question is what are the use cases? It's not terribly hard to implement the behavior of switching the name without affecting the current VT, but I don't see much of a point for developers. It's confusing at best IMO.

**Comment by flackr** [comment]
I think you could make the same argument for many discrete animateable properties - but allowing properties to be discretely "animated" allows using the animation infrastructure to implement delayed or timed changes of property values which can often be useful in certain circumstances.

E.g. maybe you use an "animation" with a view-timeline such that only the on screen elements participate in a view transition.

**Comment by nt1m** [comment]
OK I guess that might be fine then. I think it would be good to add a note that animating view-transition-name does not affect running VT (even though it's implicit with how the spec is written), potentially describing the use cases you mentioned.

**Comment by nt1m** [comment]
Fixed by https://github.com/w3c/csswg-drafts/commit/26515437c0e21b170cd913e65f9ca61e4beb2ac4
