### ISSUE TITLE
[css-display] "flow-root" is a confusing value for display

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#964]
https://drafts.csswg.org/css-display-3/#display-flow-layout

The only place that CSS uses the term "flow" is in Regions (flow-from, flow-into). I think it's super confusing to have a "flow-root" value that isn't region-related, and authors don't know the term "flow layout".

Can we call it "float-container" or something?

**Comment by astearns** [comment]
+1 to making the name be more explicit about the effect, though tying it to 'float' might also be confusing. Container seems appropriate. Are there terms in common use by web devs that correlate to 'block formatting context'?

**Comment by dbaron** [comment]
I fear the term most in common use might be <code>hasLayout</code>, but I don't think we want that one, and I don't think it exactly matches the concept of block formatting context.

**Comment by SelenIT** [comment]
@smfr, CSS also uses the term "[normal flow](https://drafts.csswg.org/css2/visuren.html#normal-flow)", as opposed to [other](https://drafts.csswg.org/css2/visuren.html#positioning-scheme) positioning schemes. I believe that the term "flow root" comes from that meaning of "flow" (also mentioned in the [block formatting section](https://drafts.csswg.org/css2/visuren.html#block-formatting)), maybe with some influence of the "sectioning root" concept [from HTML5](https://www.w3.org/TR/html52/sections.html#sectioning-roots).

AFAIK, there are at least three aspects in which BFC-creating elements differ from regular blocks:

1. Containing nested floats (most often mentioned)
2. [Collapsing margins](https://drafts.csswg.org/css2/box.html#collapsing-margins)
3. Border box overlapping with floats (paragraph above the "Example" in [Section 9.5](https://drafts.csswg.org/css2/visuren.html#floats) of CSS2.2)

If `display:flow-root` affects all of these, I suppose that naming should also reflect them all.

**Comment by mrego** [comment]
Note that this has already been implemented in Firefox and Chrome, and, if I'm not wrong, it'd be shipped in Firefox 53 and Chrome 57.
So, if we want to change the name it should be fast enough so it's not shipped with a different syntax.

**Comment by SelenIT** [comment]
I don't see much need in renaming. Are authors really more familiar with Regions (which the Chrome team even [doesn't plan to support](https://www.chromestatus.com/feature/5655612935372800)) than with phrases like "absolutely positioned elements _are removed from the flow"_ (often used in many CSS articles for beginners) or with the "Flow content" concept from HTML5? Existing implementations also count against the renaming, IMHO.

But if the renaming is absolutely necessary, I suppose it's important to highlight that the BFC-establishing element is 'self-contained', that nothing inside it overlaps anything outside it (leaving out special cases like negative margins). What about `display: enclosed-block`, or `separate-block`, or just `new-block` (since it establishes the _new_ BFC)?

**Comment by tabatkins** [comment]
Right; the term "out-of-flow" shows up plenty in specs; anyone who looks at layout specs or tutorials that use similar wording will have at least some exposure to the term.

(Elika and I used the "flow" terminology for the two keywords because we needed some term that covered both "block" and "inline" stuff, and "flow" was already threaded thruout the specs to refer to that layout mode's concepts.)

**Comment by fantasai** [comment]
It's not just about containing floats... or even just about blocks. The 'flow' keyword (as opposed to 'flow-root') is applied to blocks to indicate that their context and their contents are all part of the same formatting context--implying a certain boundary transparency wrt margins and floats--but it also is applied to inlines to indicate the same thing, that the contents of the inline and its surrounding context all participate in the same formatting context (which in this case is about merging text runs, aligning together, performing bidi-reordering across boundaries, etc.).

"Flow" is also used to describe the content model in HTML that allows intermixing of block and inline content, and we wanted to tie into that concept.

**Comment by js-choi** [comment]
If the name is left as-is, the [rationale for the name](#issuecomment-274638719) from @fantasai might well be worth including in the spec. It was usefully illuminating for me and might be for many others too.

**Comment by laukstein** [comment]
Please consider to apply "flow-root" for different-new property, #983!

**Comment by nadangergeo** [comment]
I propose "display: river", because there's a flow, and elements can float. To metaphorical maybe?

**Comment by SelenIT** [comment]
@nadangergeo, as for me, "display:river" fits better for `display:flow` (as a metaphor of the open stream of water that can carry floating things far away), `flow-root` is more like "display:lake" (as something completely enclosed by its banks that floating things never escape). But I'm afraid it's still too metaphorical and there is no other concept in CSS that would support this metaphor:)

**Comment by Marat-Tanalin** [comment]
There is nothing wrong with the `flow-root` keyword, it is quite clear and natural based on what it does.

Fwiw, if renaming was required, `isolated` or `context` would probably be viable options.

**Comment by inoas** [comment]
considering [`display:flow`](https://drafts.csswg.org/css-display-3/#display-flow) would `display:flow-block` instead of [`display:flow-root`](https://drafts.csswg.org/css-display-3/#display-flow) make sense?

Just from the nomenclature it would also be in line with `display: block` vs `display: inline-block` in a way.

**Comment by alastc** [comment]
As an old-school CSSer, I read the description and thought it was effectively "block" but containing floats. How about `block-container`.

Slightly related, does it have to be a display attribute? Could it apply to flex or grid as well? If so, perhaps a separate attribute would be more effective?

**Comment by kalleboo** [comment]
Based on the description in the spec,

> The element generates a block container box, and lays out its contents using flow layout. It always establishes a new block formatting context for its contents.

I like the "flow-block" suggestion by @inoas

**Comment by SelenIT** [comment]
There is a problem with "flow-block" sugestion: there is already a `display: block flow` [longhand value](https://drafts.csswg.org/css-display/#display-value-summary) in the spec, which means _just the opposite_ — the block that _doesn't_ establish new block formatting context (i.e., default `display:block` behavior). Would be way more confusing that current naming.

If I understand correctly, the whole flow/flow-root thing that @fantasai explains in https://github.com/w3c/csswg-drafts/issues/964#issuecomment-274638719 applies only to blocks and inlines (collectively referred as "flow layout") since they are the only two display values that can have the same formatting context inside as outside. It doesn't make sense for flex and grid containers since they always establish the new formatting context (different from the one they live in themselves) and therefore don't have issues like float leaking or descendant margin collapsing.

But I like the idea to have a separate property for switching new context generation on/off. Maybe this behavior has something to do with the scope of [css-containment], especially with [`contain:layout`](https://drafts.csswg.org/css-containment/#containment-layout)? Looks like something very similar from the first glimpse, and new formatting context is explicitly mentioned there.

**Comment by Marat-Tanalin** [comment]
As an option, we could have _separate_ properties: one for self-clearing like `self-clear`, and another one for controlling collapsing margins like `margin-collapse`.

**Comment by Timoti** [comment]
"flow-root" is completely non-intuitive. Given this is essentially a modification of display:block, I'm for a display property name that leads with block , as suggested above, a seperate property.

**Comment by SelenIT** [comment]
As an [inner display value](https://drafts.csswg.org/css-display-3/#inner-model), "flow-root" can be also a modification of display:inline (resulting in display:inline-block behavior).

**Comment by FremyCompany** [comment]
It was resolved in today's telcon we would not rename flow-root for lack of a name that seemed conclusively better. 

Since that may be relevant to this thread, I would also note that the two-value syntax was proposed to be removed from the current draft last face-to-face, and possibly postponed for a later level.

**Comment by FremyCompany** [comment]
Though at the risk of getting @fantasai to roll her eyes at me not proposing this during the call, I wonder if "display: block-bfc" doesn't indeed convey the meaning better (as well as starting to educate people on what a bfc is and does).

Though it may also add confusion, I don't know. Not sure I am convinced myself :)

**Comment by yisibl** [comment]
I do not agree to change the name, as long as the specification is written clearly enough, as long as the author understands the concept of `BFC(block formatting context)` naturally know what `display: flow-root` can do.
