### ISSUE TITLE
[css-ui-4] inteference with the caret blinking and the ability to animate its color

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9707]
Using `caret-color`, you can change the color of the text insertion caret. Using css animations, you can animate that color. Using this, people could create carets that:

* fade in and out instead of blinking
(variations around this concept are for instance available in VS Code: https://www.youtube.com/watch?v=Hms3gUBKaVQ)

* alternate between two (or more) colors instead of alternate between visible and invisible, such as a bright and a subdued variant of the same color.
(This is an effect that can for instance be seen in Bloomberg Terminal https://www.youtube.com/watch?v=MaWWOQgAMLY&t=115s )

Well, you almost could do that, but in practice it doesn't work, because at the same time as you are animating the caret color, it's still blinking. So instead, people who try to do this sort of things hide the caret (by making it transparent), place an empty div where the caret is (and use JavaScript to track it around) just so they can style it. This is cumbersome and brittle.

A while back, we had explored a `caret-animation` property, with one value (`auto`) letting the caret blink or animate in whatever way is native to the platform, and one value (we last called it `none`, but I would actually rather go with `manual`) making the caret just be the color of `caret-color`, allowing animations to do their work undisrupted. This would be easy to implement, and would remove the need for complicated workarounds.

I would like to revive this.

(We could also have a couple of convenience values, such as `fade` or `blink`, but these don't enable anything that isn't possible with animations once we have `manual`)

**Comment by javifernandez** [comment]
I think the idea makes a lot of sense. There is indeed a strong use case on adapting the caret animation to the context of the web content being rendered. Sometimes the default blinking is very annoying and distracting. 

This solution would simplify considerably the implementation of those designs, making web author's life easier and better interoperability between browsers.

**Comment by progers** [comment]
I worry that the potential issues of custom color animations may outweigh the benefits. For example:
* Webkit recently added a special caret for dictation ([commit](https://github.com/WebKit/WebKit/pull/14809/files)) which has more of a throbbing effect, rather than blinking. It would be difficult to keep a custom color animation in sync with this effect.
* Chromium uses the OS's blink rate setting, and Firefox has a blink rate setting. There is the potential to annoy users if these are not honored.
* A solid caret may confuse users.

Vscode and bloomberg are super customized (e.g., supporting multiple cursors) and are unlikely to use this feature. Are there usecases for custom caret color animations other than editors/terminals?

https://github.com/w3c/csswg-drafts/assets/569214/fb1c8743-a947-487f-b4d4-4d92f0d7d45f

**Comment by frivoal** [comment]
Landed the changes through https://github.com/w3c/csswg-drafts/commit/58d739bbe865ec799fd9cbf449d3f0b159657af0.

Note that I called the non-`auto` value `manual` rather than `none`, as that seems better to avoid confusions that this prevents any animation (it doesn't: it only prevents ua-driven annimations).

**Comment by schenney-chromium** [comment]
Note I have a CL up in Chromium to add the WPT test along with initial support for the feature.

**Comment by schenney-chromium** [comment]
The best we can do for testing this is CSS style testing, because caret blinking is inconsistent across platforms and likely to be flaky under test machine load. The WPT style tests have landed, so I'll remove the tag related to testing.

WPT css/css-ui/animation/caret-animation-parsing.html
