### ISSUE TITLE
[web-animations] Why is ::placeholder considered invalid?

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#9751]
WPT [web-animations/interfaces/Animatable/animate.html](https://github.com/web-platform-tests/wpt/blob/master/web-animations/interfaces/Animatable/animate.html) asserts `::placeholder` is not a valid pseudo-element. Seems bogus? Stumbled across this while doing some cleanup in WebKit: https://github.com/WebKit/WebKit/pull/22231.

Also a problem with [web-animations/interfaces/KeyframeEffect/target.html](https://github.com/web-platform-tests/wpt/blob/master/web-animations/interfaces/KeyframeEffect/target.html).

cc @flackr @graouts

**Comment by birtles** [comment]
We used to have a hard-coded set of accepted pseudo-elements (based on what CSS transitions etc. originally supported, I think) but at one point we expanded it to allow all pseudos but I guess these tests never got updated. I think these tests would still pass in Firefox and maybe other browsers because in #4745 we seemed to agree that implementations should throw for pseudos that they don't support animating.
