### ISSUE TITLE
Latest Published Version in Specs and Drafts

### ISSUE THREAD

**Issue by francescorn** [w3c/csswg-drafts#9777]
For example, in [css-values-3](https://drafts.csswg.org/css-values-3/), it says that the latest published version is "https://www.w3.org/TR/css-values-3/".

The naming order is confusing since there are recently released versions which are [css-values-4](https://www.w3.org/TR/css-values-4/) and [css-values-5](https://drafts.csswg.org/css-values-5/).

I think it would be better update each previous one to the latest one when they are created to be more efficient and to update the older versions of specs and drafts.

**Comment by svgeesus** [comment]
If each level of a module was fully completed before starting the next one, that would indeed be a good idea.

However, different levels are typically developed in parallel. So you can find that `css-foo-3` is very stable and widely implemented, but not yet 100% interoperable; while `css-foo-4` is in active development but still has a ton of open issues, and `css-foo-5` is basically rough notes and ideas.

So the notion of "latest" is complicated.

To help with this, more recent specifications have a "history" link, for example [this one for `css-values-3`](https://www.w3.org/standards/history/css-values-3/) which also has links to the [history for `css-values-4`](https://www.w3.org/standards/history/css-values-4/). And there is no history link for `css-values-5` because it hasn't ever been published to the TR (Technical Reports) page. In fact the [editor's draft of `css-values-5`](https://drafts.csswg.org/css-values-5/) omits all of `css-values-4` and just has a few ideas for how to extend it.

So hopefully you can see that making `css-values-3` and `css-values-4` redirect to `css-values-5` would not be the right thing to do at all.

**Comment by francescorn** [comment]
Thank you for clarifying. I am closing the pr.
