### ISSUE TITLE
[css-cascade-4] Add an alias to !important

### ISSUE THREAD

**Issue by francescorn** [w3c/csswg-drafts#9778]
[css-cascade-4](https://www.w3.org/TR/css-cascade-4/#importance)

! is the logical not operator. When adding ! in front of important, it should mean it is not important, as in not taking precedence.

`*` would make more sense to be in front since it covers all of the elements.

My proposed task would be to:

1. Add an alias for !important such as *important because it is closer to meaning more/most important of all elements.

**Comment by Loirooriol** [comment]
> ! is the logical not operator

CSS doesn't have a logical not operator

> Add an alias for !important

At this point it doesn't seem feasible to deprecate `!important`, so adding an alias will just increase confusion IMO.

> *important

That's problematic, because that's valid in a [`<declaration-value>`](https://drafts.csswg.org/css-syntax-3/#typedef-declaration-value). But a top-level `!` is not, so it can act as a delimiter.

In particular, this would break:

```js
document.body.style.cssText = "--foo: bar*important";
document.body.style.getPropertyValue("--foo"); // "bar*important"
```

**Comment by astearns** [comment]
It definitely is confusing, and on our list of [mistakes](https://wiki.csswg.org/ideas/mistakes).

It might be possible to come up with an alias that works better, but I expect this would need to be a longer keyword instead of adding some special character. And I’d like the new thing to make it more clear how `important` declarations interact with origins and contexts https://www.w3.org/TR/css-cascade-4/#cascade-origin

**Comment by francescorn** [comment]
There would be a space in between `*important` and the previous, just like in `!important`. This would live in the CSS realm where *important is always declared separated by a space. We could possibly alias it as `~important`, `^important`, or `&important` if it causes less confusion to web developers.

An example:
`.myElement {
  color: blue;
  font-size: 16px;
}

/* Override styles with *important */
.myElement.special {
  color: red !important;
  font-size: 20px !important;
}`

and an alias of

`.myElement {
  color: blue;
  font-size: 16px;
}

/* Override styles with *important */
.myElement.special {
  color: red *important;
  font-size: 20px *important;
}`

**Comment by francescorn** [comment]
`!important` is declared using a space beforehand. It would live in the CSS realm. It would be the same with `*important`. We can also possibly use `^important` or `&important` as an alias.

an example:
````
.myElement {
  color: blue;
  font-size: 16px;
}

/* Override styles with !important */
.myElement.special {
  color: red !important;
  font-size: 20px !important;
}
````

an alias:
````
.myElement {
  color: blue;
  font-size: 16px;
}

/* Override styles with *important */
.myElement.special {
  color: red !important;
  font-size: 20px !important;
}
````

**Comment by francescorn** [comment]
Maybe mostImportant or moreImportant?

**Comment by francescorn** [comment]
@fantasai @litherum What are your thoughts on a better alias name?

**Comment by litherum** [comment]
I’m categorically against aliases.

- They have maintenance cost for implementers
- They don’t offer authors any functionality that they didn’t have before
- The web is the biggest platform in the world. As such, it is totally capable of defining its own conventions.

**Comment by Crissov** [comment]
Do XML and HTML get the same kind of comments for having `<!DOCTYPE` and `<!--`?

**Comment by francescorn** [comment]
What about `important`/`importance` or `priority`? Maybe we can add number priorities/importance such as `first-priority`, `second-priority`, `third-priority` etc. or add a number attached such as `priority-1`, `priority-2`, `priority-3`... etc. Or `important-1`, `important-2`, `important-3`, `important-4`... etc.

Or we could also maybe assign them in categories with 3 importances/priorities such as:  `high-importance`, `medium-importance`, `low-importance`. Or `high-priority`, `medium-priority`, `low-priority`.

**Comment by tabatkins** [comment]
Yes, I'm just going to close this issue. `!important`, while historically somewhat confusing, is decades old and long-established at this point. It's not used often, and when it is, it's rather obvious that the property isn't "not important", since it wins over most other things.

As noted, there are also parsing concerns with using any other character besides `!` at this point, due to custom properties accepting any syntax.

Aliases are something we very intentionally use only rarely, when the previous name is just actively bad for some reason. (For example, some `-webkit-*` prefixed properties that became necessary for the web ended up aliasing a proper standardized name.)

--------

For the separate issue of wanting more levels of "importance", that's what we designed [Cascade Layers](https://drafts.csswg.org/css-cascade-5/#layering) for. We don't anticipate expanding `!important` itself, and in general `!important` can be better replaced by Cascade Layers. (Tho we do reserve the right to add additional `!`-prefixed things in the future, if we find something that requires it.)
