### ISSUE TITLE
[css-view-transitions-1] [css-view-transitions-2] consider a living-standard model for view-transitions

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#9850]
The delta-spec model has made adding features to css-view-transitions-2 a bit awkward and counterproductive. 
See https://github.com/w3c/csswg-drafts/pull/9773 for example.
The more we advance the feature, the more this is likely to make that problem more difficult.

Suggesting instead to have a single level for CSS view-transitions, and keep things in an editor draft, moving to /TR/ once they're stable, but without levels. (Is that the model for css-syntax?)

We should still be careful about feature-detection, to make sure subfeatures are properly detected (e.g. you don't assume `view-transition-class` is supported just because `view-transition-name` is supported).

Alternate proposals for cleaner models also appreciated.

/cc @tabatkins @khushalsagar @vmpstr @nt1m

**Comment by khushalsagar** [comment]
Another example of awkwardness in the spec is [process old state captured](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-process-old-state-captured). It's a callback used to inject code for cross-document transitions (which is the L2 spec) in the middle of an algorithm defined by the L1 spec.

I've seen a lot of value in having an ED to incubate a new feature. It helps in iterating as we work through all the issues associated with a feature. The awkwardness is also reasonable in the interim state. But if we have to actually take L2 through the standards track, it becomes messy. So I'd prefer if we can use the ED to incubate but move features to a living spec once all associated issues have been resolved.

Drawing from the html spec as an example (which is a living spec), IIRC the navigation API started off in a rough ED like spec and was then moved to the html spec in 1 PR? @domenic on that.

Also @astearns @atanassov in case there's other CSS specs we can learn from.

**Comment by vmpstr** [comment]
+1 to rethinking the levels here and I support more of a living standard type of model: work in ED and republish occasionally?

Other than the awkwardness of authoring the spec text, I also find it confusing to think about which features go into which level. For instance, view transition types, view transition classes, and cross-document view transitions are all L2, but that's almost coincidental since types and classes need to integrate with same-document view transitions which is L1. 

If we publish L2, then would things like scope transitions need to go into L3? Seems somewhat arbitrary and confusing.

**Comment by nt1m** [comment]
I think the levels model might be fine here? but maybe instead of having level 2 patch level 1, we could make level 2 re-define algorithms from level 1.

**Comment by noamr** [comment]
> I think the levels model might be fine here? but maybe instead of having level 2 patch level 1, we could make level 2 re-define algorithms from level 1.

Having the same algorithms defined in two places can get confusing... what's the benefit?

**Comment by nt1m** [comment]
I would prefer having a stable algorithm to implement from rather than one that is consistently changing.

**Comment by noamr** [comment]
> I would prefer having a stable algorithm to implement from rather than one that is consistently changing. (Especially as bugs may be found on the newer changes)

The algorithm can probably stay stable on /TR/ and change as needed on ED (specifically for adding features like `view-transition-class`)? Do we need a new level for that?

**Comment by nt1m** [comment]
Also whatever happens here, it would be nice to have some way to see the spec diff in a readable view

**Comment by khushalsagar** [comment]
> I also find it confusing to think about which features go into which level.

FWIW, this hasn't been a concern for me. We are working on new features, on regular intervals we decide which features need to stabilize that go into the next level. The decision for which level something is deferred to is on a case by case basis. For example, the spec for same-document transitions (and other features in L1) was fairly stable so decided to cut off there and defer cross-document transitions to L2.

It's the fact that patching algorithms in lower levels for features in higher levels becomes very messy. If the solution is to re-define algorithms, I can live with that. Whenever we do this, we can leave a non-normative note indicating the highest level which replaces an algorithm.

We are gearing up towards a FPWD of L2 since cross-document transitions is pretty close so would love to get this resolved soon.

**Comment by vmpstr** [comment]
Accidentally closed, but I think we can actually close it based on the resolution
