### ISSUE TITLE
[css-anchor-position-1] Can we clarify the `inset-area` syntax? It can be confusing to read and reason about.

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#9862]
Overall, I really like the mental model behind the [inset-area](https://drafts.csswg.org/css-anchor-position-1/#inset-area) property, as a quick way to set relative insets. But looking at the syntax today with @una, there were a few aspects of the syntax that make it hard to read and reason about. In my mind the primary issue is the overlap between:

- two axis values, which can be listed in either order
- two values _within an axis_ for spanning multiple areas
- for `center` and the logical values, names are the same on either axis
- for single values, the implied axis is `all` 
 
That leads to some interesting situations: 

- simple `center` value becomes `center / all` rather than `center / center`
- `center / all` is not clear unless you know which axis comes first by default (but not always)
- `left / center` and `center / left` mean the same thing, but `start / center` and `center / start` are different
- `bottom center` is not the center of the bottom area, that's `bottom / center` (or `center / bottom` etc)

There's two changes that I think would help, while leaving some flexibility:

- Clarify spans with a function syntax (`span(left, center)`). This would reduce the top-level space to two values without needing the `/` divider. (It might also be useful for grid to support a `span()` function for spanning multiple grid areas.)
- I expected single axis-ambiguous values to duplicate for the cross-axis: so that the bare keywords `start`, `end`, `center`, `self-start`, and `self-end` resolve to eg `start / start` and `center / center` etc. _(clarification: This helps with the issue where e.g. `center` first can mean either axis, but `center` alone always means one specific axis.)_

Thoughts?

**Comment by una** [comment]
+1, as @mirisuzanne mentioned, I started exploring `inset-area` positioning and found the syntax very confusing thus far, especially with a single value converting to `/ all` and not doubling, as well as the order being interchangable.

![Screenshot 2024-01-29 at 5 09 48 PM](https://github.com/w3c/csswg-drafts/assets/1693164/88877954-f8de-47e7-b4ba-8c423068f5b5)

**Comment by fantasai** [comment]
I think we should try to go for consistency with `<position>` in some fashion (recognizing that this is a separate problem with its own syntax space but still).

**Comment by tabatkins** [comment]
All right, Elika and I discussed this today, and agree the syntax can be improved a bit.

First, to let us remove the slash (getting closer to `<position>`, as Elika just suggested), we have two possible syntax suggestions:

```
<inset-area-alpha> = [
  [ left | center | right | center-left | center-right
  | x-start | x-end | center-x-start | center-x-end 
  | x-self-start | x-self-end | center-x-self-start | center-x-self-end 
  | all ]
  &&
  [ top | center | bottom | center-top | center-bottom
  | y-start | y-end | center-y-start | center-y-end
  | y-self-start | y-self-end | center-y-self-start | center-y-self-end 
  | all ]
|
  [ block-start | center | block-end | center-block-start | center-block-end
  | self-block-start | self-block-end | center-self-block-start | center-self-block-end 
  | all ]
  &&
  [ inline-start | center | inline-end | center-inline-start | center-inline-end ]
  | self-inline-start | self-inline-end | center-self-inline-start | center-self-inline-end 
  | all ]
|
  [ start | center | end | center-start | center-end | all ]{1, 2}
|
  [ self-start | center | self-end | center-self-start | center-self-end | all ]{1, 2}
]

<inset-area-beta> = [
  [ left | center | right | span( left || center || right )
  | x-start | x-end | span( x-start || center || x-end )
  | x-self-start | x-self-end | span( x-self-start || center || x-self-end )
  | all ]
  &&
  [ top | center | bottom | span( top || center || bottom )
  | y-start | y-end | span( y-start || center || y-end )
  | y-self-start | y-self-end | span( y-self-start || center || y-self-end )
  | all ]
|
  [ block-start | center | block-end | span( block-start || center || block-end )
  | self-block-start | self-block-end | span( self-block-start || center || self-block-end )
  | all ]
&&
  [ inline-start | center | inline-end | span( inline-start || center || inline-end )
  | self-inline-start | self-inline-end | span( self-inline-start || center || self-inline-end)
  | all ]
|
  [ start | center | end | span( start || center || end ) | all ]{1, 2}
|
  [ self-start | center | self-end | span( self-start || center || self-end ) | all ]{1,2}
]
```

In `alpha`, we just specify the two-region values with a dashed `center-*` keyword, so if you want to fill the left and center columns, you write `center-left`.

In `beta`, we have the `span()` function, which takes two keywords and spans between them, so you'd instead right `span(left center)`.
(The grammar is a little loose above, for readability; it would actually need to be `span( [left && [center | right]] | [right && [center | left]] )`, to guarantee two keywords get specified.)

In either case, the 2-track values are now single components, so we no longer need the slash. To fill just the upper-left and upper-center regions, you could say `center-left top` or `top center-left` (or equivalently, `span(left center) top`, for beta).

We think we mildly prefer the dashed version over the span() version, but will leave the choice up to the WG.

-----------

For the "single-value is a little confusing", we agree, and think Miriam's suggestion is reasonable. So:

Single keyword defaults other axis to:
    * duplication if keyword is axis-ambiguous (start/self-start/center/end/self-end)
    * all in all other cases

And then we'd probably want to sync this with `<position>`. Currently, we just disallow saying `start` by itself (you must specify two keywords if they're axis-ambiguous), but we think it would be reasonable to adopt a similar "duplicate if axis-ambiguous, `center` otherwise" rule, so `background-position: start` would be equivalent to `start start`.

**Comment by tabatkins** [comment]
Una's three examples would thus be `bottom`, `center-bottom`, and `bottom center`

**Comment by fantasai** [comment]
> But that's an issue with all axis-ambiguous syntaxes. Learning that the order is always block->inline will continue to be correct across CSS.

But in the proposed syntax above, in sync with `<position>`, we introduced the axis-specific keywords (`block-*`/`inline-*`) so that you don't have to remember the order.

**Comment by mirisuzanne** [comment]
I like this solution, and also lean towards the `alpha` hyphenated approach. 

I agree the axis-ordering can be learned. My main concern was the stacking of those implicit rules – with an ambiguous keyword treated as a _positional axis keyword_ when the position is already somewhat ambiguous. This change removes the stacking of ambiguities. :)

**Comment by tidoust** [comment]
@tabatkins The new syntax is imbalanced because the closing bracket at the end of line 400 is already closed at the end of line 398:
https://github.com/w3c/csswg-drafts/blob/7875737d2178c85e8d51a47bec7d4da296b0e132/css-anchor-position-1/Overview.bs#L398-L400

Not sure where the closing bracket needs to go, I let you sort that out ;)

Also, the Value Definition Syntax does not mention the possibility of whitespaces being used in [multipliers](https://www.w3.org/TR/css-values-4/#component-multipliers), and at least the [CSSTree parser](https://github.com/csstree/csstree) chokes on those at the end of lines 402 and 404.
https://github.com/w3c/csswg-drafts/blob/7875737d2178c85e8d51a47bec7d4da296b0e132/css-anchor-position-1/Overview.bs#L402
https://github.com/w3c/csswg-drafts/blob/7875737d2178c85e8d51a47bec7d4da296b0e132/css-anchor-position-1/Overview.bs#L404

Could the whitespaces be dropped as well, or should CSS parsers support these whitespaces?

**Comment by tabatkins** [comment]
Fixed the brackets. I also removed the whitespace from the multipliers, tho I think the parser should be forgiving of that. ^_^

**Comment by una** [comment]
Updates syntax in context: ![Screenshot 2024-02-08 at 3 16 19 PM](https://github.com/w3c/csswg-drafts/assets/1693164/75333bfc-3ae8-4df9-82ec-ae8852aaaf85)

**Comment by mirisuzanne** [comment]
@una On the middle diagram, I think it would be `center-block-end` instead of `block-end center`.

**Comment by kizu** [comment]
I don't think a specific preference over the exact syntax, but, at the first glance, I would prefer the `span()` one, mostly due to a personal dislike of long chains of dashed keywords.

For someone not familiar with how things work, things like `center-block-end` could be confusing, as the two dashes inside represent two different concepts: one is spanning, the another is a connector inside a single keyword.

Looking at it, you'll have to spend a bit of time parsing what is going on: is it “center-block and end”? Is it “center, block, and end?“ Is it “center and block-end”?

With experience, you'd probably learn that we have these “block-end”-like entities in CSS, but I feel that this invites more cognitive load required to understand the keywords than might be necessary.

**Comment by una** [comment]
> @una On the middle diagram, I think it would be `center-block-end` instead of `block-end center`.

Good catch, updated

**Comment by mfreed7** [comment]
One of the confusing things about the hyphenated names are that they use the same words as single-column/row names, just separated by a hyphen. So "center left" and "center-left" are very similar, which adds confusion. The hyphenated versions all mean **two columns or rows**. So how about add `-and-` to emphasize that. E.g.

- `center-and-left`
- `center-and-top`

etc.

**Comment by FremyCompany** [comment]
Random thought: what if we give a name to all possible combinations that make sense. There are not many of them.

**Horizontal popups:**
> `above` (top, all), 
> `above-only` (top, center), 
> `above-and-before` (top, left+center), `above-and-before-only` (top, left), 
> `above-and-after` (top,center+right), `above-and-after-only` (top, right). 
> 
> Ditto with `below` as a prefix for the bottom row.

**Vertical popups:**
> `before` (all, left), 
> `before-only` (center, left), 
> `before-and-above` (top+center, left), 
> `before-and-above-only` (top, left), `before-and-below` (center+bottom, left), 
> `before-and-below-only` (bottom, left). 
> 
> Ditto with `after` as a prefix for the right column.

**Dialogs:**
For popus that cover the entire anchor, I suspect we can also add 
> `over` for (top+center+bottom, left+center+right) and 
> `over-only` (center, center).

All the other options look rare to me, and could be achieved with a less intuitive syntax.

Some cells have two names with this proposal (e.g. `above-and-after-only` and `after-and-above-only`) but maybe another naming scheme could avoid this (but maybe it's ok though, as they have slightly different semantics).

I can imagine `stritctly` being an appealing alternative to `only` (but it's a bit longer to type, and usually happens as first word in English, while `only` is allowed on both sides, but this is a detail).

**Comment by fantasai** [comment]
I liked @mirisuzanne's suggestion to replace "center" with "and", so you'd have e.g. `bottom span-left` instead of `bottom center-left`.
