### ISSUE TITLE
[css-view-transitions-2] Consider allowing `::view-transition-group(.class)` without *

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#9874]
This would be consistent with how class selectors work outside of view-transitions.

**Comment by vmpstr** [comment]
Probably to go with #9626 as well

**Comment by astearns** [comment]
Right. I believe `:active-view-transition` is meant to cover this case

https://github.com/w3c/csswg-drafts/issues/9972#issuecomment-1994889933

(if I am incorrect, please re-open this issue)

**Comment by vmpstr** [comment]
This is a separate issue. #9972 only dealt with `:active-view-transition*` pseudo classes.

This issue is about allowing `::view-transition-*` pseudo classes to also omit the asterisk if a class is specified. Note that I think we would still want to require the asterisk if there is no class or specific name specified, but that can be discussed

**Comment by cdoublev** [comment]
I guess whitespaces are invalid between tokens matching these [productions](https://drafts.csswg.org/css-view-transitions-2/#typedef-pt-name-and-class-selector).

```
<pt-name-and-class-selector> = <pt-name-selector><pt-class-selector>? | <pt-class-selector>
<pt-class-selector> = ['.' <custom-ident>]+
```

Would it be possible to clarify it explicitly (like for [selector productions](https://drafts.csswg.org/selectors-4/#white-space)), and add a whitespace between `<pt-name-selector>` and `<pt-class-selector>?`?
