### ISSUE TITLE
[css-view-transitions-2] Dealing with promises on old VT object

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#9888]
What should happen with all the promises once capture is done.

**Comment by khushalsagar** [comment]
This is a tricky one that could use author feedback: @mirisuzanne @jakearchibald @bramus. The following is a summary of discussion and tentative proposed resolution based on that.

The old Document will have an event when the navigation is about to be committed but before the browser renders/caches the last frame. We want authors to be able to set up CSS, including [type](https://drafts.csswg.org/css-view-transitions-2/#view-transition-type-descriptor), based on the destination page or skip the transition. The question is how should that API be exposed.

1. Provide a [ViewTransition](https://drafts.csswg.org/css-view-transitions-1/#viewtransition) object on this event. The `skipTransition()` API lets the author abort the transition. We're also planning to add a mutable `types` parameter to toggle types used in `active-view-transition`. The other use-case of providing the VT object is to enable sharing code for SPA/MPA cases.

   But the ViewTransition IDL has promises to track the lifecycle of transition animations. Since the old Document has no animation, promises like `ready`/`finish` conceptually don't make sense. We could model it as the ViewTransition on the old Document started off like an SPA transition but was skipped once the old DOM was captured and its state was copied over to the new DOM. So `ready` would reject and `updateCallbackDone`+`finish` would resolve, potentially when the Document exits BFCache (if it was persisted).
   
   It's unclear to us whether providing a VT object here with this default behaviour of promises is ergonomic or error prone, shared code mistakenly assumes the transition failed because `ready` rejected.

2. The other option is to introduce a new IDL (`SnapshotViewTransition`) which is the `ViewTransition` equivalent for the Document which provides snapshots for the start state but doesn't run animations. This would have a subset of the `ViewTransition` APIs but no class relationship.

   The pro of this is that its future proof. If we add more APIs to ViewTransition, we don't have to shoehorn a meaning for the old Document's object which might not make sense. The con is that sharing code with SPA libraries might be harder.

**Proposed Resolution**: Option 1, use the VT IDL on the old Doc with default behaviour for promises (and new APIs as they are introduced).

**Comment by bramus** [comment]
> This is a tricky one that could use author feedback

I would need to get my hands on a prototype to be sure but my gut feeling tells me none of the promises make sense at all. IUC the vt object you receive inside `pageconceal` still incomplete. Only after the logic inside that handler has been executed, the viewTransition will actually start.

Looking at existing code that I use in an SPA+VT, looking to see see what I could carry over to MPA/`pageconceal`, I would only carry over the stuff that happens before `document.startViewTransition()` ever gets called. The stuff after `document.startViewTransition()` would be used on the new page.

- SPA:
    
    ```js
    navigation.addEventListener("navigate", (e) => {
      // … If VT MPA Support: return

      e.intercept({
        handler: async () => {
          // … Determine transition type
          
          // … Give some elements a v-t-name if needed
        
          // Create and start VT
          const t = document.startViewTransition({
            update,
            type,
          });
          
          await t.updateCallbackDone;
          // … Analytics, or whatever
          
          await t.finished;
          // … Cleanup
        },
    });
    ```

-  MPA (old page):

    ```js
    document.addEventListener(`pageconceal`, (e) => {
      // … Determine transition type
    
      // … Give some elements a v-t-name
    });
    ```

In the MPA code I would only need to determine the VT type to use (or maybe skip the transition) and have no need for any of the promises.

Maybe it makes sense to expose something like a `PendingViewTransition` instance in `pageconceal` to make it easily distinguishable for authors? You can’t really do anything with, besides changing some properties or skipping it. It would also have no promises at all. I think that is what is meant with option 2?

This `PendingViewTransition` instance would then be converted to a full `ViewTransition` instance on the new page, which an author gets passed into the `pagereveal` event.

> The old Document will have an event when the navigation is **about to be committed** but before the browser renders/caches the last frame.

Hmm. How would authors then easily get to know what the target URL is in order to determine the transition type? In the SPA, when intercepting the navigation, the navigation is already committed and the `navigation.currentEntry` updated. But here in `pageconceal` it is not.

It would be handy if the navigation already was committed, so that authors can then reuse their SPA code: read `navigation.currentEntry`, knowing that it’s the up-to-date destination URL. With it not being committed yet, authors would need to keep track of `destination` in the `navigate` event, store it in a variable, and then have `pageconceal` use that variable.

**Comment by khushalsagar** [comment]
> I think that is what is meant with option 2?

Yup. Regarding naming, I went with `SnapshotViewTransition` because this Document only provides the snapshot but no animations. `PendingViewTransition` is also fine.

>  How would authors then easily get to know what the target URL is in order to determine the transition type?

The `pageconceal` event has a [NavigationActivation](https://html.spec.whatwg.org/#navigation-activation-interface) to provide the final URL, nav type and a reference to the destination entry. We can't commit the navigation, i.e. change the current entry, because the old Document has to remain active so it can produce one last frame which the browser will cache.

**Comment by noamr** [comment]
Proposed resolution from internal sync:
The outgoing event would have an ordinary `ViewTransition` object with all the promises.
The promises would behave as if the view transition was skipped after the page was unloaded, so would only be observable if restored from BFCache.

Alternative considered: a new interface with just `skipViewTransition` & types.
