### ISSUE TITLE
[css-overflow] scrollLeft and scrollTop as CSS properties?

### ISSUE THREAD

**Issue by ByteEater-pl** [w3c/csswg-drafts#9956]
Why aren't `scrollLeft` and `scrollTop` CSS properties? They're about presentation in interactive visual media, so it seems appropriate. And declarative animation with CSS would be possible, in a way that's uniform (and often needs to be combined) with other properties, without resorting to `requestAnimationFrame`, as currently (and that only for a few years; there was no good, widely implemented way before).

**Comment by tabatkins** [comment]
Because they're controlled directly by the user. This would put them, at best, in the same awkward spot that `resize` is, where it has to reflect the user's actions by writing them into inline style, which will *usually* win in the cascade.

Affecting the *initial* scroll position is a different thing, and generally fine - see [the 'scroll-start' property proposal](https://drafts.csswg.org/css-scroll-snap-2/#scroll-start).
