### ISSUE TITLE
[css-view-transitions-1] Cross-fade should use linear blending

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#9983]
The cross-fade animation used by ViewTransitions needs to ensure that blending 2 identical pixels yields identical results. This requires the following:

1. The old/new snapshots need a linear timing function. This ensures that at any point during the animation, the opacity for `::view-transition-old` and `::view-transition-new` add up to 1.
2. The 2 images need to be composed with `plus-lighter` blending.  See example [here](https://drafts.fxtf.org/compositing/#plus-lighter) for why this is required for cross-fading.

The spec currently has 2) but 1) is missing. Since the initial value for `animation-timing-function` is `ease`, it needs to be set to `linear` in UA CSS for `::view-transition-old`/`::view-transition-new`.

**Comment by vmpstr** [comment]
If we have an animation from 0 to 1 and another from 1 to 0, as long as they both use the same timing function and run at the same time for the same duration, then the sum of these two should be 1 at all times during the animation, right? I'm failing to come up with an example where that would not be true.

I know this issue came from a real world example, but I suspect we need to figure out exactly what's happening

**Comment by khushalsagar** [comment]
You're right, both theoretically and confirming on a simple example [here](https://jsbin.com/xozavaposi/edit?html,output). Looks like this might be a chrome devtools issue where one of the animations is progressing with linear blending. This mismatch in timing functions is cause the issue. Let me reopen this with more data.
